---
title: "Collation of Byz^RP^ vs 32652 (2652)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 2652 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=32652).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 2652                                   	| λογος                              	|
| 2652 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 2652 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 2652               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 2652                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 2652 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 2652                                                     	| [―]{.gap}                        	|
:::

## Acts

### Chapter 1

τον μεν πρωτον λογον εποιησαμην περι παντων ω θεοφιλε ων ηρξατο ο [ιησους]{.greek-abbr} ποιειν τε και διδασκειν[1:1]{.aside}

αχρι ης ημερας εντειλαμενος τοις αποστολοις δια [πνευματος]{.greek-abbr} αγιου ους εξελεξατο ανεληφθη[1:2]{.aside}

οις και παρεστησεν εαυτον ζωντα μετα το παθειν αυτον εν πολλοις τεκμηριοις δι ημερων τεσσαρακοντα οπτανομενος αυτοις και λεγων τα περι της βασιλειας του [θεου]{.greek-abbr}[1:3]{.aside}

και [συναλιζομενος]{.greek-omitted} [συναυλιζομενος]{.greek-added} παρηγγειλεν αυτοις απο ιεροσολυμων μη χωριζεσθαι αλλα περιμενειν την επαγγελιαν του [πατρος]{.greek-abbr} ην ηκουσατε μου[1:4]{.aside}

οτι ιωαννης μεν εβαπτισεν υδατι υμεις δε βαπτισθησεσθε εν [πνευματι]{.greek-abbr} αγιω ου μετα πολλας ταυτας ημερας[1:5]{.aside}

οι μεν ουν συνελθοντες επηρωτων αυτον λεγοντες [κυριε]{.greek-abbr} ει εν τω χρονω τουτω αποκαθιστανεις την βασιλειαν τω [ισραηλ]{.greek-abbr}[1:6]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε προς αυτο[υ]{.greek-supplied}ς ουχ υμων [εστιν]{.greek-omitted} [εστι]{.greek-added} γνωναι χρονους η καιρους ους ο [πατηρ]{.greek-abbr} εθετο εν τη ιδια εξουσια[1:7]{.aside}

αλλα [ληψεσθε]{.greek-omitted} [ληψεσθαι]{.greek-added} δυναμιν επελθοντος του αγιου [πνευματος]{.greek-abbr} εφ υμας και εσεσθε μοι μαρτυρες εν τε ιερουσαλημ και εν παση τη ιουδαια και σαμαρεια και εως εσχατου της γης[1:8]{.aside}

και ταυτα ειπων βλεποντων αυτων επηρθη και νεφελη υπελαβεν αυτον απο των οφθαλμων αυτων[1:9]{.aside}

και ως ατενιζοντες ησαν εις τον [ουρανον]{.greek-abbr} πορευομενου αυτου και ιδου ανδρες δυο παρειστηκεισαν αυτοις εν ε[σ]{.unclear}θητι λευκη[1:10]{.aside}

οι και ειπον ανδρες γαλιλαιοι τι εστηκατε εμβλεποντες εις τον [ουρανον]{.greek-abbr} ουτος ο [ιησους]{.greek-abbr} ο αναληφθεις αφ υμων εις τον [ουρανον]{.greek-abbr} ουτως ελευσεται [παλιν]{.greek-added} ον τροπον εθεασασθε αυτον πορευομενον εις τον [ουρανον]{.greek-abbr}[1:11]{.aside}

τοτε υπεστρεψαν [οι]{.greek-added} [αποστολοι]{.greek-added} εις ιερουσαλημ απο ορους του καλουμενου ελαιωνος ο εστιν εγγυς ιερουσαλημ σαββατου [εχον]{.greek-omitted} [εχων]{.greek-added} οδον[1:12]{.aside}

και οτε εισηλθον [και]{.greek-added} ανεβησαν εις το υπερωον ου ησαν καταμενοντες ο τε πετρος [κα]{.unclear}ι ιακωβος και ιωαννης και ανδρεας φιλιππος και θωμας βαρθολομαιος και ματθαιος ιακωβος αλφαιου και σιμων ο ζηλωτης και ιουδας ιακωβου[1:13]{.aside}

ουτοι παντες ησαν προσκαρτερουντες [ομοθυμαδον]{.greek-omitted} [ομοθυ]{.greek-added} [μαδον]{.greek-added} τη προσευχη και τη δεησει συν γυναιξιν και μαρια τη [μητρι]{.greek-abbr} του [ιησου]{.greek-abbr} και συν τοις αδελφοις αυτου[1:14]{.aside}

και εν [ταις]{.greek-omitted} [τες]{.greek-added} ημεραις [ταυταις]{.greek-omitted} [ταυτες]{.greek-added} αναστας πετρος εν μεσω των μαθητων ειπεν ην τε οχλος ονοματων επι το [αυτο]{.greek-omitted} [αυτω]{.greek-added} ως εκατον [εικοσι]{.greek-omitted} [εικοσιν]{.greek-added}[1:15]{.aside}

ανδρες αδελφοι εδει πληρωθηναι την γραφην ταυτην ην προειπεν το [πνευμα]{.greek-abbr} το αγιον δια στοματος [δαυιδ]{.greek-abbr} περι ιουδα του γενομενου οδηγου τοις [συλλαβουσιν]{.greek-omitted} [συλλαβουσι]{.greek-added} τον [ιησουν]{.greek-abbr}[1:16]{.aside}

οτι κατηριθμημενος ην συν ημιν και [ελαχεν]{.greek-omitted} [ελαχε]{.greek-added} τον κληρον της διακονιας ταυτης[1:17]{.aside}

ουτος μεν ουν εκτησατο χωριον εκ μισθου της αδικιας και [πρηνης]{.greek-omitted} [πρινης]{.greek-added} γενομενος [ελακησεν]{.greek-omitted} [ελακκισε]{.greek-added} μεσος και εξεχυθη παντα τα σπλαγχνα αυτου[1:18]{.aside}

και γνωστον εγενετο [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις κατοικουσιν [ιερουσαλημ]{.greek-abbr} ωστε κληθηναι το χωριον εκεινο τη ιδια διαλεκτω αυτων ακελδαμα τουτ [εστιν]{.greek-omitted} [εστι]{.greek-added} χωριον αιματος[1:19]{.aside}

γεγραπται γαρ εν βιβλω ψαλμων γενηθητω η επαυλις αυτου ερημος και μη εστω ο κατοικων εν αυτη και την επισκοπην αυτου λαβοι ετερος[1:20]{.aside}

δει [ουν]{.greek-omitted} [γουν]{.greek-added} των [συνελθοντων]{.greek-omitted} [συνελθωντων]{.greek-added} ημιν ανδρων εν παντι χρον[ω]{.unclear} εν ω εισηλθεν και εξηλθεν εφ ημας ο [κυριος]{.greek-abbr} [ιησους]{.greek-abbr}[1:21]{.aside}

αρξαμενος απο του βαπτισματος [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} [ε]{.greek-added} [ως]{.greek-added} [εως]{.corr} της ημερας ης ανεληφθη αφ ημων μαρτυρ[α]{.greek-supplied} της αναστασεως αυτου γενεσθαι συν ημιν ενα τουτων[1:22]{.aside}

και εστησαν δυο ιωσηφ τον καλου[μ]{.unclear}[ε]{.greek-supplied}νον [βαρσαβαν]{.greek-omitted} [βαρσαββαν]{.greek-added} ος επεκληθη ιουστος και μ[α]{.greek-supplied}τθιαν[1:23]{.aside}

και προσευξαμενοι ειπον συ [κυριε]{.greek-abbr} κα[ρ]{.greek-supplied}διογνωστα παντων αναδειξον ον εξελεξω εκ τουτων των δυο ενα[1:24]{.aside}

λαβειν τον κληρον της διακονιας ταυτης και αποστολης εξ ης παρεβ[η]{.greek-supplied} ιουδας πορευθηναι εις τον τοπον τον ιδιον[1:25]{.aside}

και εδωκαν κληρους [αυτων]{.greek-omitted} [αυτον]{.greek-added} και επεσεν ο κληρο[ς]{.greek-supplied} επι ματθιαν και συγκατεψηφισθη μετα των ενδεκα αποστολων[1:26]{.aside}

### Chapter 2

και εν τω συμπληρουσθαι την ημεραν της πεντηκοστης ησαν απαντες ομοθυμαδον επι το [αυτο]{.greek-omitted} [αυτω]{.greek-added}[2:1]{.aside}

και εγενετο αφνω εκ του [ουρανου]{.greek-abbr} ηχος ωσπερ φερ[ο]{.unclear}μενης [πνοης]{.greek-omitted} [πνωης]{.greek-added} βιαιας και επληρωσεν ολον τον οικον ου ησαν καθημενοι[2:2]{.aside}

και ωφθησαν [αυτοις]{.greek-omitted} [α[υ]{.unclear}της]{.greek-added} διαμεριζομεναι γλωσσαι ωσει πυρος [[και]{.unclear}]{.greek-added} [εκαθισεν]{.greek-omitted} [εκαθισε]{.greek-added} τε εφ ενα εκαστον [αυτων]{.greek-omitted} [αυτον]{.greek-added}[2:3]{.aside}

και επλησθ[η]{.unclear}σαν απαντες [πνευματος]{.greek-abbr} αγιου και ηρξαντο λαλειν ετ[ε]{.greek-supplied}ραις γλωσσαις καθως το [πνευμα]{.greek-abbr} εδιδου αυτοις [α]{.unclear}ποφθεγγεσθαι[2:4]{.aside}

ησαν δε εν [ιερουσαλημ]{.greek-abbr} κατοικο[υν]{.unclear}τες ιουδαιοι ανδρες ευλαβεις απο παντος εθνους των υπο [τον]{.greek-omitted} [των]{.greek-added} [[ουρανων]{.greek-abbr}]{.greek-added} [[ουρανον]{.greek-abbr}]{.corr}[2:5]{.aside}

γενομενης δε της φωνης ταυτης συνηλθεν το πληθος και συνεχυθη οτι ηκουον εις εκαστος τη ιδια διαλεκτω λαλουντων αυτων[2:6]{.aside}

[εξισταντο]{.greek-omitted} [εξησταντο]{.greek-added} δε [παντες]{.greek-omitted} και εθαυμαζον λεγοντες προς αλληλ[ο]{.unclear}[υ]{.greek-supplied}ς ουκ ιδου παντες ουτοι εισιν οι λαλουντες γαλιλαιοι[2:7]{.aside}

και πως ημεις ακουομεν εκαστος τη ιδια διαλεκτω ημων εν η εγεννηθημεν[2:8]{.aside}

παρθοι και μηδοι και [ελαμιται]{.greek-omitted} [ελαμιτε]{.greek-added} και οι κατοικουντες την μεσοποταμιαν ιουδαιαν τε και καππαδοκιαν ποντον και την ασιαν[2:9]{.aside}

φρυγιαν τε και παμφυλιαν αιγυπτον και τα μερη της [λιβυης]{.greek-omitted} [λυβυης]{.greek-added} της κατα κυρηνην και οι επιδημουντες ρωμαιοι [ιουδαιοι]{.greek-omitted} [τε]{.greek-omitted} [και]{.greek-omitted} [προσηλυτοι]{.greek-omitted}[2:10]{.aside}

[ιουδαιοι]{.greek-added} [τε]{.greek-added} [και]{.greek-added} [προσηλυτοι]{.greek-added} κρητες και αραβες ακουομεν λαλουντων αυτων ταις ημετεραις γλωσσαις τα μεγαλεια του [θεου]{.greek-abbr}[2:11]{.aside}

εξισταντο δε παντες και διηπορουν [αλλος]{.greek-omitted} προς [αλλον]{.greek-omitted} [αλληλους]{.greek-added} λεγοντες τι αν [θελοι]{.greek-omitted} [θελει]{.greek-added} τουτο ειναι[2:12]{.aside}

ετεροι δε χλευαζοντες ελεγον οτι γλευκους μεμεστωμενοι [εισιν]{.greek-omitted} [εισι]{.greek-added}[2:13]{.aside}

σταθεις δε πετρος συν τοις ενδεκα [επηρεν]{.greek-omitted} [επηρε]{.greek-added} την φωνην αυτου και απεφθεγξατο αυτοις ανδρες ιουδαιοι και οι κατοικουντες [ιερουσαλημ]{.greek-abbr} απαντες τουτο υμιν γνωστον εστω και ενωτισασθε τα ρηματα μου[2:14]{.aside}

ου γαρ ως υμεις υπολαμβανετε ουτοι μεθυουσιν [εστιν]{.greek-omitted} [εστι]{.greek-added} γαρ ωρα τριτη της ημερας[2:15]{.aside}

αλλα τουτο [εστιν]{.greek-omitted} [εστι]{.greek-added} το ειρημενον δια του προφητου ιωηλ[2:16]{.aside}

και εσται εν ται[ς]{.unclear} εσχαταις ημεραις λεγει ο [θεος]{.greek-abbr} εκχεω απο του [πνευματος]{.greek-abbr} μου επι πασαν σαρκα και προφητευσουσιν οι υι[οι]{.greek-supplied} υμων και αι θυγατερες υμων και οι νεανισκοι υμων ορασεις οψονται και οι πρεσβυτεροι υμων ενυπνια [ενυπνιασθησονται]{.greek-omitted} [ενιπνιασθησονται]{.greek-added}[2:17]{.aside}

και γε επι τους δουλους μου και επι τας δουλας μου εν ταις ημεραις εκειναις εκχεω απο του [πνευματος]{.greek-abbr} μου και προφητευσουσιν[2:18]{.aside}

και δωσω τερατα εν τω [ουρανω]{.greek-abbr} ανω κα[ι]{.unclear} σημεια επι της γης κατω αιμα και πυρ και ατμιδα καπνου[2:19]{.aside}

ο ηλιος μεταστραφησεται εις σκ[ο]{.unclear}τος και η σεληνη εις αιμα πριν [η]{.greek-omitted} ελθειν την ημεραν [κυριου]{.greek-abbr} την μεγαλην και επιφανη[2:20]{.aside}

και εσται πας ος αν επικαλεσηται το ονομα [κυριου]{.greek-abbr} σωθη[σεται]{.greek-supplied}[2:21]{.aside}

ανδρες ισραηλιται ακουσατε τους λογους τουτους [ιησουν]{.greek-abbr} τον ναζωραιον ανδρα απο του [θεου]{.greek-abbr} αποδεδειγμεν[ον]{.greek-supplied} εις υμας [δυναμεσιν]{.greek-omitted} [δυναμεσι]{.greek-added} και [τερασιν]{.greek-omitted} [τερασι]{.greek-added} και σημειοις οις [εποιησεν]{.greek-omitted} [[ε]{.greek-supplied}ποιησε]{.greek-added} δι αυτου ο [θεος]{.greek-abbr} εν μεσω υμων καθως κα[ι]{.greek-supplied} αυτοι οιδατε[2:22]{.aside}

τουτον τη ωρισμενη βουλη και πρ[ο]{.greek-supplied}γνωσει του [θεου]{.greek-abbr} εκδοτον λαβοντες δια [χειρων]{.greek-omitted} [χειρ[ο]{.unclear}[ς]{.greek-supplied}]{.greek-added} ανομων [προσπηξαντες]{.greek-omitted} [προσπιξαντες]{.greek-added} ανειλετε[2:23]{.aside}

ον ο [θεος]{.greek-abbr} ανεστησεν λυσας τας ωδινας του θανατου [κα]{.greek-supplied}θοτι ουκ ην δυνατον κρατεισθαι αυτον υπ αυτ[ου]{.greek-supplied}[2:24]{.aside}

### Chapter 3

[και]{.greek-omitted} [επι]{.greek-omitted} [τη]{.greek-omitted} [πιστει]{.greek-omitted} [του]{.greek-omitted} [ονοματος]{.greek-omitted} [αυτου]{.greek-omitted} [τουτον]{.greek-omitted} [ον]{.greek-omitted} [θεωρειτε]{.greek-omitted} [και]{.greek-omitted} [οιδατε]{.greek-omitted} [εστερεωσεν]{.greek-omitted} [το]{.greek-omitted} [ονομα]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [πιστις]{.greek-omitted} [η]{.greek-omitted} [δι]{.greek-omitted} [αυ]{.greek-supplied}του εδωκεν αυτω την ολοκληριαν ταυτην απεναντι παντων υμων[[3:16 *(lacunose)*]{.lacunose}]{.aside}

και νυν αδελφοι οιδα οτι κατα αγνοιαν επραξατε ωσπερ και οι [αρχοντες]{.greek-omitted} [αρχωντες]{.greek-added} υμων[3:17]{.aside}

ο δε [θεος]{.greek-abbr} α [προκατηγγειλεν]{.greek-omitted} [προκατηγγειλε]{.greek-added} δια στοματος παντων των προφητων αυτου παθειν τον [χριστον]{.greek-abbr} επληρωσεν ουτως[3:18]{.aside}

μετανοησατε [ουν]{.greek-omitted} [γουν]{.greek-added} και επιστρεψατε εις το εξαλειφθηναι υμων τας αμαρτιας [οπως]{.greek-omitted} [αν]{.greek-omitted} [ελθωσιν]{.greek-omitted} [καιροι]{.greek-omitted} [αναψυξεως]{.greek-omitted} [απο]{.greek-omitted} [προσωπου]{.greek-omitted} [του]{.greek-omitted} [κυριου]{.greek-omitted}[3:19]{.aside}

[οπως]{.greek-added} [αν]{.greek-added} [ελθωσι]{.greek-added} [καιροι]{.greek-added} [αναψυξεως]{.greek-added} [απο]{.greek-added} [προσωπου]{.greek-added} [[κυριου]{.greek-abbr}]{.greek-added} και αποστειλη τον προκεχειρισμενον υμιν [χριστον]{.greek-abbr} [ιησουν]{.greek-abbr}[3:20]{.aside}

ον δει [ουρανον]{.greek-abbr} μεν δεξασθαι αχρι χρονων αποκαταστασεως παντων ων [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} [ο]{.greek-omitted} [θεος]{.greek-omitted} δια στοματος παντων των αγιων αυτου προφητων απ αιωνος[3:21]{.aside}

[μωσης]{.greek-omitted} [μωυσις]{.greek-added} μεν γαρ προς τους [πατερας]{.greek-abbr} [υμων]{.greek-added} ειπεν οτι προφητην υμιν αναστησει [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ημων εκ των αδελφων υμων ως εμε αυτου ακουσεσθε κατα παντα οσα αν λαληση προς [υμας]{.greek-omitted} [ημας]{.greek-added}[3:22]{.aside}

[εσται]{.greek-omitted} [εστε]{.greek-added} δε πασα ψυχη ητις εαν μη ακουση του προφητου εκεινου εξολοθρευθησεται εκ του λαου [αυτης]{.greek-added}[3:23]{.aside}

και παντες δε [οι]{.greek-omitted} προφηται απο σαμουηλ και των καθεξης οσοι ελαλησαν και [κατηγγειλαν]{.greek-omitted} [προκατηγγειλαν]{.greek-added} τας ημερας ταυτας[3:24]{.aside}

υμεις εστε [οι]{.greek-added} υιοι [[τω]{.unclear}ν]{.greek-added} των προφητων και της [διαθηκης]{.greek-omitted} [διαθικης]{.greek-added} ης διεθετο ο [θεος]{.greek-abbr} προς τους [πατερας]{.greek-abbr} [ημων]{.greek-omitted} [υμων]{.greek-added} λεγων προς αβρααμ και εν τω σπερματι σου ενευλογηθησονται πασαι αι πατριαι τη[ς]{.unclear} γης[3:25]{.aside}

υμιν πρωτον [ο]{.greek-omitted} [θεος]{.greek-omitted} αναστησας τον παιδα αυτου [ιησουν]{.greek-abbr} απεστειλεν αυτον ευλογουντα υμας εν τω αποστρεφε[ιν]{.greek-supplied} εκαστον απο των πονηριων [υμων]{.greek-omitted} [αυτου]{.greek-added}[3:26]{.aside}

### Chapter 4

λαλου[ντ]{.unclear}ων δε αυτων προς τον λαον επεστησαν αυτοις οι [ερεις]{.greek-added} [ιερεις]{.corr} και ο στρατηγος του ιερου και οι σαδδουκαιοι[4:1]{.aside}

διαπονουμενοι δια το διδασκειν αυτους τον λαον και καταγγελλειν εν τω [ιησου]{.greek-abbr} την αναστασιν των νεκρων[4:2]{.aside}

και επεβαλον αυτοις τας χειρας και εθεντο εις τηρησιν εις την αυριον ην γαρ εσπερα ηδη[4:3]{.aside}

πολλοι δε των ακουσαντων τον λογον επιστευσαν και εγενηθη ο αριθμος των ανδρων ωσει χιλιαδες πεντε[4:4]{.aside}

εγενετο δε επι τη[ν]{.greek-supplied} αυριον συναχθηναι [αυτων]{.greek-omitted} [αυτον]{.greek-added} τους αρχοντας και πρεσβ[υ]{.unclear}τερους και γραμματεις εις [ιερουσαλημ]{.greek-abbr}[4:5]{.aside}

και [ανναν]{.greek-omitted} [αναν]{.greek-added} τον αρχιερεα και καιαφαν και ιωαννην και αλεξανδρον και οσοι ησαν εκ γενους αρχιερατικου[4:6]{.aside}

και στησαντες αυτους εν μεσω [αυτων]{.greek-added} επυνθανοντο εν ποια δυναμει η εν ποιω ονοματι εποιησατε τουτο υμεις[4:7]{.aside}

τοτε πετρος πλησθεις [πνευματος]{.greek-abbr} αγιου [ειπεν]{.greek-omitted} [ειπε]{.greek-added} προς αυτους αρχοντες του λαου και πρεσβυτεροι του [ισραηλ]{.greek-abbr}[4:8]{.aside}

ει ημεις σημερον ανακρινομεθα επι ευεργεσια [ανθρωπου]{.greek-abbr} ασθενους εν τινι ουτος σεσωσται[4:9]{.aside}

γνωστον εστω πασιν υμιν και παντι τω λαω [ισραηλ]{.greek-abbr} οτι εν τω ονοματι [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} του ναζωραιου ον υμεις [εσταυρωσατε]{.greek-abbr} ον ο [θεος]{.greek-abbr} ηγειρεν εκ νεκρων εν τουτω ουτος παρεστηκ[εν]{.greek-supplied} ενωπιον υμων υγιης[4:10]{.aside}

ουτος εστιν ο λιθος ο εξουθενηθεις υφ υμων των οικοδομουντων ο γενομενος εις κεφαλην γωνιας[4:11]{.aside}

και ουκ εστιν εν [αλλω]{.greek-omitted} [αλω]{.greek-added} ουδενι η [σωτηρια]{.greek-abbr} ουτε γαρ ονομ[α]{.unclear} εστιν ετερον το δεδομενον εν [ανθρωποις]{.greek-abbr} εν ω δει σωθηναι ημας[4:12]{.aside}

θεωρουντες δε [οι]{.greek-added} [ιουδαιοι]{.greek-added} την του πετρου παρρησιαν και ιωαννου και καταλαβομενοι οτι [ανθρωποι]{.greek-abbr} αγραμματοι [εισιν]{.greek-omitted} [εισι]{.greek-added} και ιδιωται εθαυμαζον επεγινωσκον τε αυτους οτι συν τω [ιησου]{.greek-abbr} ησαν[4:13]{.aside}

τον [δε]{.greek-omitted} [τε]{.greek-added} [ανθρωπον]{.greek-abbr} [βλεποντες]{.greek-omitted} [θεωρουντες]{.greek-added} συν αυτοις εστωτα τον τεθεραπευμενον ουδεν ειχον αντειπειν[4:14]{.aside}

κελευσαντες δε αυτους εξω του συνεδριου απελθειν [συνεβαλλον]{.greek-omitted} [συνεβαλον]{.greek-added} προς [αλληλους]{.greek-omitted} [αληλους]{.greek-added}[4:15]{.aside}

λεγοντες τι ποιησομεν τοις [ανθρωποις]{.greek-abbr} τουτοις οτι μεν γαρ γνωστον σημειον [γεγονεν]{.greek-omitted} [γεγωνεν]{.greek-added} δι αυτων [πασιν]{.greek-omitted} [παση]{.greek-added} τοις κατοικουσιν [ιερουσαλημ]{.greek-abbr} φανερον και ου δυναμεθα αρνησασθαι[4:16]{.aside}

αλλ ινα μη επι πλειον διανεμηθη εις τον λαον απειλη [απειλησομεθα]{.greek-omitted} [απειλησωμεθα]{.greek-added} αυτοις μηκετι λαλειν επι τω ονοματι τουτω μηδενι [ανθρωπων]{.greek-abbr}[4:17]{.aside}

και καλεσαντες αυτους παρηγγειλαν αυτοις το καθολου μη φθεγγεσθαι μηδε διδασκειν επι τω ονοματι του [ιησου]{.greek-abbr}[4:18]{.aside}

ο δε πετρος και ιωαννης αποκριθεντες προς αυτους ειπον ει δικαιον εστιν ενωπιον του [θεου]{.greek-abbr} υμων ακουειν μαλλον η του [θεου]{.greek-abbr} κρινατε[4:19]{.aside}

ου δυναμεθα γαρ ημεις α ειδομεν και ηκουσαμεν μη λαλειν[4:20]{.aside}

οι δε προσαπειλησαμενοι απελυσαν αυτους μηδεν ευρισκοντες το πως [κολασονται]{.greek-omitted} [κολασωνται]{.greek-added} αυτους δια τον λαον οτι [παντ[η]{.unclear}]{.greek-added} [παντες]{.corr} εδοξαζον τον [θεον]{.greek-abbr} επι τω γεγονοτι[4:21]{.aside}

ετων γαρ ην πλειονων [τεσσαρακοντα]{.greek-omitted} [τεσαρακοντα]{.greek-added} ο [ανθρωπος]{.greek-abbr} εφ ον εγεγονει το σημειον τουτο της ιασεως[4:22]{.aside}

απολυθεντες δε ηλθον προς τους ιδιους και απηγγειλαν οσα προς αυτους οι αρχιερεις και οι πρεσβυτεροι ειπον[4:23]{.aside}

οι δε ακουσαντες ομοθυμαδον ηραν φωνην προς τον [θεον]{.greek-omitted} [λογον]{.greek-added} και ειπον δεσποτα συ ο [θεος]{.greek-abbr} ο ποιησας τον [ουρανον]{.greek-abbr} και την γην και την [θαλασσαν]{.greek-omitted} [θαλασαν]{.greek-added} και παντα τα εν αυτοις[4:24]{.aside}

ο δια στοματος δαυιδ [του]{.greek-added} παιδος σου ειπων [ινα]{.greek-omitted} [ινατι]{.greek-added} [τι]{.greek-omitted} εφρυαξαν εθνη και λαοι εμελετησαν κενα[4:25]{.aside}

παρεστησαν οι βασιλεις της γης και οι αρχοντες συνηχθησαν επι το αυτο κατα του [κυριου]{.greek-abbr} και κατα του [χριστου]{.greek-abbr} αυτου[4:26]{.aside}

συνηχθησαν γαρ επ αληθειας [εν]{.greek-added} [τη]{.greek-added} [πολη]{.greek-added} [ταυτει]{.greek-added} επι τον αγιον παιδα σου [ιησουν]{.greek-abbr} ον εχρισας [ηρωδης]{.greek-omitted} [ηροδης]{.greek-added} τε και ποντιος πιλατος συν εθνεσιν και λαοις [ισραηλ]{.greek-abbr}[4:27]{.aside}

ποιησαι οσα η χειρ σου και η βουλη σου [προωρισεν]{.greek-omitted} [προωρισε]{.greek-added} γενεσθαι[4:28]{.aside}

και τα νυν [κυριε]{.greek-abbr} επιδε επι τας απειλας αυτων και δος [τοις]{.greek-omitted} [της]{.greek-added} δουλοις σου μετα παρρησιας πασης λαλειν τον λογον σου[4:29]{.aside}

εν τω την [χειρα]{.greek-omitted} [χειραν]{.greek-added} σου εκτεινειν [σε]{.greek-omitted} εις ιασιν και σημει[α]{.unclear} και τερατα γινεσθαι δια του ονοματος του αγιου παιδο[ς]{.unclear} σου [ιησου]{.greek-abbr}[4:30]{.aside}

και δεηθεντων αυτων εσαλευθη ο το[π]{.unclear}[ος]{.greek-supplied} εν ω ησαν συνηγμενοι και επλησθησαν απαντες [πνευματος]{.greek-abbr} αγιου και ελαλουν τον λογον του [θεου]{.greek-abbr} μετα παρρ[η]{.unclear}σιας[4:31]{.aside}

του δε πληθους των πιστευσαντων ην η καρδια και η ψυχη μια και ουδε εις τι των υπαρχ[ον]{.unclear}των [αυτων]{.greek-omitted} [αυτω]{.greek-added} ελεγεν ιδιον ειναι αλλ ην αυτοις α[παν]{.greek-supplied}τα κοινα[4:32]{.aside}

και μεγαλη δυναμει απεδιδουν το μαρτυριον οι αποστολοι της αναστασεως του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} χαρις τ[ε]{.unclear} μεγαλη ην επι παντας αυτους[4:33]{.aside}

ουδε γαρ ενδεης τις υπηρχεν εν αυτοις οσοι γαρ κτητορες χωριων [η]{.unclear} οικ[ι]{.unclear}ων υπηρχον [πωλουντες]{.greek-omitted} [πολουντες]{.greek-added} εφερον τας τιμας των πιπρασκομενων[4:34]{.aside}

και ετιθουν παρα τους [πο]{.unclear}δας των αποστολων διεδιδοτο δε εκαστω [καθοτι]{.greek-omitted} [καθο]{.greek-added} αν τις χρειαν ειχεν[4:35]{.aside}

ιωσης δε ο επικληθεις βαρναβας [απο]{.greek-omitted} [υπο]{.greek-added} των αποστολων ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομε[ν]{.unclear}[ον]{.greek-supplied} υιος παρακλησεως λευιτης κυπριος τω γενει[4:36]{.aside}

υπαρχοντος αυτω αγρου πωλησας [ηνεγκεν]{.greek-omitted} [ηνεγκε]{.greek-added} το χρ[η]{.unclear}μα και [εθηκεν]{.greek-omitted} [εθηκε]{.greek-added} παρα τους ποδας των αποστολων[4:37]{.aside}

### Chapter 5

ανηρ δε τις ανανιας ονοματι συν σαπφειρη τη γυναικι αυτου [επωλησεν]{.greek-omitted} [επωλησε]{.greek-added} κτημ[α]{.unclear}[5:1]{.aside}

και ενοσφισατο απο της [τιμης]{.greek-omitted} [τημης]{.greek-added} συνειδυιας κα[ι]{.unclear} της γυναικος αυτου και ενεγκας μερος τι παρα τους ποδας των αποστολων εθηκεν[5:2]{.aside}

ειπεν δε [ο]{.greek-added} πετρος ανανια δια τι επληρωσεν ο σατανας την καρδιαν σου ψευσασθαι σε το [πνευμα]{.greek-abbr} το αγιον και νοσφισασθαι [σε]{.greek-omitted} απο της τιμης του χωριου[5:3]{.aside}

ουχι μενον σοι [εμενεν]{.greek-omitted} [εμενε]{.greek-added} και πραθεν εν τη ση εξουσια υπηρ[χεν]{.greek-supplied} τι οτι εθου εν τη καρδια σου το πραγμα τουτο ουκ εψευσω [ανθρωποις]{.greek-abbr} αλλα τω [θεω]{.greek-abbr}[5:4]{.aside}

ακουων δε ο ανανιας [τ]{.unclear}ους λογους τουτους πεσων [εξεψυξεν]{.greek-omitted} [εξεψυξε]{.greek-added} και εγενετο φοβος μεγας επι παντας τους ακουοντας ταυτα[5:5]{.aside}

ανασταντες δε οι νεωτεροι [συνεστειλαν]{.greek-omitted} [συνεστηλαν]{.greek-added} αυτον και εξενεγκαντες εθαψαν[5:6]{.aside}

εγενετο δε ως ωρων τριων διαστημα και η γυνη αυτου μη ειδυια το γεγονος εισηλθεν[5:7]{.aside}

απεκριθη δε [προς]{.greek-added} [αυτη]{.greek-omitted} [αυτην]{.greek-added} ο πετρος ειπε μοι ει τοσουτου το χωριον απεδοσθε η δε [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [ν]{.unclear}αι τοσουτου[5:8]{.aside}

ο δε πετρος ειπεν προς αυτην τι οτι συ[ν]{.unclear}εφωνηθη υμιν [πειρασαι]{.greek-omitted} [πυρασαι]{.greek-added} το [πνευμα]{.greek-abbr} [κυριου]{.greek-abbr} ιδου οι ποδες [των]{.greek-omitted} [τον]{.greek-added} θαψαντων τον [ανδρα]{.greek-omitted} [ανδραν]{.greek-added} σου επι τη θυρα και [εξοισουσιν]{.greek-omitted} [εξοισουσι]{.greek-added} σε[5:9]{.aside}

[επεσεν]{.greek-omitted} [επεσε]{.greek-added} δε παραχρημα παρα τους ποδας αυτου και εξεψυξεν εισελθοντες δε οι νεανισκοι ευρον αυτην νεκραν και εξενεγκαντες εθαψαν προς τον ανδρα αυτης[5:10]{.aside}

και εγενετο φοβος μεγας εφ ολην την εκκλησιαν και επι παντας τους ακουοντας ταυτα[5:11]{.aside}

δια δε των χειρων των αποστολων [εγινετο]{.greek-omitted} [εγενετο]{.greek-added} σημεια και τερατα εν τω λαω πολλα και ησαν ομοθυμαδον απαντες εν τη στοα σολομωντος[5:12]{.aside}

των δε λοιπων ουδεις ετολμα [κολλασθαι]{.greek-omitted} [κολασθαι]{.greek-added} αυτοις αλλ εμεγαλυνεν αυτους ο λαος[5:13]{.aside}

μαλλον δε προσετιθεντο πιστευοντες τω [κυριω]{.greek-abbr} πληθη ανδρων τε και γυναικων[5:14]{.aside}

ωστε κατα τας πλατειας εκφερειν τους [ασθενεις]{.greek-omitted} [ασθενουντας]{.greek-added} και τιθεναι επι κλινων και κραββατων ινα ερχομενου πετρου καν η σκια επισκιαση τινι [εξ]{.greek-added} α[υ]{.unclear}των[5:15]{.aside}

[συνηρχετο]{.greek-omitted} [συνηρχοντο]{.greek-added} δε και το πληθος των περιξ πολεων εις ιερουσαλημ φεροντες ασθενεις και οχλουμενους υπο [πνευματων]{.greek-abbr} ακαθαρτων οιτινες εθεραπευοντο απαντες[5:16]{.aside}

αναστας δε ο αρχιερ[ε]{.unclear}[υς]{.greek-supplied} και παντες οι συν αυτω η ουσα αιρεσις των σαδδουκαιων επλησθησαν ζηλου[5:17]{.aside}

και επεβαλον τας χειρας αυτων επι τους αποστολους και εθεντο αυτους εν τηρησει δημοσια[5:18]{.aside}

αγγελος δε [κυριου]{.greek-abbr} δια της νυκτος [ηνοιξεν]{.greek-omitted} [οινιξε]{.greek-added} τας θυρας της φυλακης εξαγαγων τε αυτους [ειπεν]{.greek-omitted} [ειπε]{.greek-added}[5:19]{.aside}

πορευεσθε και σταθεντες λαλειτε εν τω ιερω τω λαω παντα τα ρηματα της ζωης ταυτης[5:20]{.aside}

ακουσαντες δε εισηλθον υπο τον ορθρον εις το ιερον και εδιδασκον παραγενομενος δε ο αρχιερευς και οι συν αυτω συνεκαλεσαν το συνεδριον και πασαν την γερουσιαν των υιων [ισραηλ]{.greek-abbr} και [απεστειλαν]{.greek-omitted} [απεστηλαν]{.greek-added} εις το [δεσμωτηριον]{.greek-omitted} [δεσμοτηριον]{.greek-added} αχθηναι αυτους[5:21]{.aside}

οι δε υπηρεται παραγενομενοι ουχ ευρον αυτους εν τη φυλακη αναστρεψαντες δε απηγγειλαν[5:22]{.aside}

λεγοντες οτι το μεν δεσμωτηριον ευρομεν κεκλεισμενον εν παση ασφαλεια και τους φυλακας εστωτας προ των θυρων ανοιξαντες δε εσω ουδενα ευρομεν[5:23]{.aside}

ως δε ηκουσαν τους λογους τουτους ο τε ιερευς και ο στρατηγος του ιερου και οι αρχιερεις διηπορουν περι αυτων τι αν γενοιτο τουτο[5:24]{.aside}

παραγενομενος δε τις απηγγειλεν αυτοις οτι ιδου οι ανδρες ους εθεσθε εν τη φυλακη εισιν εν τω ιερω εστωτες και διδασκοντες τον λαον[5:25]{.aside}

τοτε απελθων ο στρατηγος συν τοις υπηρεταις ηγαγεν αυτους ου μετα βιας εφοβουντο γαρ τον λαον ινα μη λιθασθωσιν[5:26]{.aside}

αγαγοντες δε αυτους εστησαν εν τω συνεδριω και επηρωτησεν αυτους ο αρχι[ε]{.unclear}ρευς[5:27]{.aside}

λεγων ου [παραγγελια]{.greek-omitted} [παραγκελια]{.greek-added} παρηγγειλαμεν υμιν μη διδασκειν επι τω ονοματι τουτω και ιδου πεπληρωκατε την [ιερουσαλημ]{.greek-abbr} της διδαχης υμων και βουλεσθε επαγαγειν εφ ημας το αιμα του [ανθρωπου]{.greek-abbr} τουτου[5:28]{.aside}

αποκριθεις δε πετρος και οι αποστολοι ειπον πειθαρχειν δει [θεω]{.greek-abbr} μαλλον η [ανθρωποις]{.greek-abbr}[5:29]{.aside}

ο [θεος]{.greek-abbr} των [πατερων]{.greek-abbr} ημων ηγειρεν [ιησουν]{.greek-abbr} ον [υμεις]{.greek-omitted} [ημεις]{.greek-added} διεχειρισασθε κρεμασαντες επι ξυλου[5:30]{.aside}

τουτον ο [θεος]{.greek-abbr} αρχηγον και [σωτηρα]{.greek-abbr} υψωσεν τη δεξια αυτου δουναι μετανοιαν τω [ισραηλ]{.greek-abbr} και αφεσιν αμαρτιων[5:31]{.aside}

και ημεις εσμεν [αυτου]{.greek-omitted} μαρτυρες των ρηματων τουτων και το [πνευμα]{.greek-abbr} [δε]{.greek-omitted} το αγιο[ν]{.unclear} ο εδωκεν ο [θεος]{.greek-abbr} τοις πειθαρχουσιν αυτω[5:32]{.aside}

οι δε [ακουοντες]{.greek-omitted} [ακουσαντες]{.greek-added} διεπριοντο και εβουλευοντο ανελ[ε]{.unclear}[ιν]{.greek-supplied} αυτους[5:33]{.aside}

αναστας δε τις εν τω συνεδριω φαρισαιος ονοματι γαμαλιηλ νομοδιδασκαλος τιμιος παντι τω λαω εκελευσεν εξω βραχυ τι τους αποστολους ποιησαι[5:34]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} τε προς αυτους ανδρες ισραηλιται προ[σ]{.unclear}εχετε εαυτοις επι τοις [ανθρωποις]{.greek-abbr} τουτοις τι [με]{.greek-added} [μελλετε]{.greek-omitted} [λλετε]{.greek-added} πρασσειν[5:35]{.aside}

προ γαρ τουτων των ημερων ανεστη θευδας λεγων ειναι τινα εαυτον ω [προσεκληθη]{.greek-omitted} [προσεκοληθη]{.greek-added} αριθμος ανδρων ωσει τετρακοσιων ος ανηρεθη και παντες οσοι επειθοντο αυτω διελυθησαν και εγενοντο εις ουδεν[5:36]{.aside}

μετα [τουτον]{.greek-omitted} [τουτων]{.greek-added} ανεστη ιουδας ο γαλιλαιος εν ταις ημεραις της απογραφης και [απεστησεν]{.greek-omitted} [απεστησε]{.greek-added} λαον ικανον οπισω αυτου κακεινος [απωλετο]{.greek-omitted} [απολετο]{.greek-added} και παντες οσοι επειθοντο αυτω διεσκορπισθησαν[5:37]{.aside}

και τα νυν λεγω υμιν αποστητε απο των [ανθρωπων]{.greek-abbr} τουτων και εασατε αυτους οτι εαν η εξ [ανθρωπων]{.greek-abbr} η βουλη [αυτη]{.greek-added} η το εργον τουτο καταλυθησεται[5:38]{.aside}

ει δε εκ [θεου]{.greek-abbr} εστιν ου δυνασθε καταλυσαι αυτο μηποτε και θεομαχοι ευρεθητε [επεισθησαν]{.greek-added} [δε]{.greek-added} [αυτω]{.greek-added}[5:39]{.aside}

[επεισθησαν]{.greek-omitted} [δε]{.greek-omitted} [αυτω]{.greek-omitted} και προσκαλεσαμενοι τους αποστολους δειραντες παρηγγειλαν μη λαλειν επι τω ονοματι του [ιησου]{.greek-abbr} και απελυσαν αυτους[5:40]{.aside}

οι μεν ουν επορευοντο χαιροντες απο προσωπου του συνεδριου οτι υπερ του ονοματος του [ιησου]{.greek-abbr} κατηξιωθησαν ατιμασθηναι[5:41]{.aside}

πασαν τε ημεραν εν τω ιερω και κατ οικον ουκ [επαυοντο]{.greek-omitted} [επαβοντο]{.greek-added} διδασκοντες και ευαγγελιζομενοι [ιησουν]{.greek-omitted} τον [χριστον]{.greek-abbr} [[ιησουν]{.greek-abbr}]{.greek-added}[5:42]{.aside}

### Chapter 6

εν δε ταις ημεραις [ταυταις]{.greek-omitted} [ταυτες]{.greek-added} πληθυνοντων των μαθητων εγενετο γογγυσμος των ελληνιστων προς τους εβραιους οτι παρεθεωρουντο εν τη διακονια τη καθημερινη αι χηραι αυτων[6:1]{.aside}

προσκαλεσαμενοι δε οι δωδεκα το [πληθος]{.greek-omitted} [πληθς]{.greek-added} των μαθητων ειπον ουκ αρεστον εστιν ημας καταλειψαντας τον λογον του [θεου]{.greek-abbr} διακονειν τραπεζαις[6:2]{.aside}

επισκεψασθε [ουν]{.greek-omitted} [γουν]{.greek-added} αδελφοι ανδρας εξ υμων μαρτυρουμενους επτα πληρεις [πνευματος]{.greek-abbr} αγιου και σοφιας ους [καταστησωμεν]{.greek-omitted} [καταστησομεν]{.greek-added} επι της χρειας ταυτης[6:3]{.aside}

ημεις δε τη προσευχη και τη διακονια του λογου προσκαρτερησομεν[6:4]{.aside}

και ηρεσεν ο λογος ενωπιον παντος του πληθους και [εξελεξαντο]{.greek-omitted} [εξελεξατο]{.greek-added} στεφανον ανδρα [πληρης]{.greek-omitted} [πληρη]{.greek-added} πιστεως και [πνευματος]{.greek-abbr} αγιου και φιλιππον και προχορον και νικανορα και τιμωνα και παρμεναν και νικολαον [προσηλυτον]{.greek-omitted} [προσυλητον]{.greek-added} αντιοχεα[6:5]{.aside}

ους εστησαν ενωπιον των αποστολων και προσευξαμενοι επεθηκαν αυτοις τας χειρας[6:6]{.aside}

και ο λογος του [θεου]{.greek-abbr} [ηυξανεν]{.greek-omitted} [ηυξανε]{.greek-added} και επληθυνετο ο αριθμος των μαθητων εν [ιερουσαλημ]{.greek-abbr} σφοδρα πολυς τε οχλος των [ιερεων]{.greek-omitted} [ιουδαιων]{.greek-added} υπηκουον τη πιστει[6:7]{.aside}

στεφανος δε πληρης πιστεως και δυναμεως [εποιει]{.greek-omitted} [επειοι]{.greek-added} τερατα και σημεια μεγαλα εν τω λαω[6:8]{.aside}

ανεστησαν δε τινες των εκ της συναγωγης της λεγομενης λιβερτινων και κυρηναιων και αλεξανδρεων και των απο κιλικιας [και]{.greek-omitted} [ασιας]{.greek-omitted} συζητουντες τω στεφανω[6:9]{.aside}

και ουκ [ισχυον]{.greek-omitted} [ισχιον]{.greek-added} αντιστηναι τη σοφια και τω [πνευματι]{.greek-abbr} ω ελαλει[6:10]{.aside}

τοτε υπεβαλον ανδρας λεγοντας οτι ακηκοαμεν αυτου λαλουντος ρηματα βλασφημα εις μωσην και τον [θεον]{.greek-abbr}[6:11]{.aside}

συνεκινησαν τε τον λαον και τους πρεσβυτερους και τους γραμματεις και επισταντες συνηρπασαν αυτον και ηγαγον εις το συνεδριον[6:12]{.aside}

εστησαν τε μαρτυρας ψευδεις λεγοντας ο [ανθρωπος]{.greek-abbr} ουτος ου παυεται ρηματα βλασφημα λαλων κατα του τοπου του αγιου [τουτου]{.greek-added} και του νομου[6:13]{.aside}

ακηκοαμεν γαρ αυτου λεγοντος οτι [ιησους]{.greek-abbr} ο ναζωραιος ουτος καταλυσει τον τοπον τουτον και αλλαξει τα εθη α [παρεδωκεν]{.greek-omitted} [περεδωκεν]{.greek-added} ημιν [μωσης]{.greek-omitted} [μωυσης]{.greek-added}[6:14]{.aside}

και ατενισαντες εις αυτον απαντες οι καθεζομενοι εν τω συνεδριω ειδον το προσωπον αυτου ωσει προσωπον αγγελου[6:15]{.aside}

### Chapter 7

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε ο αρχιερευς ει αρα ταυτα ουτως εχει[7:1]{.aside}

ο δε εφη ανδρες αδελφοι και [πατερες]{.greek-abbr} ακουσατε ο [θεος]{.greek-abbr} της δοξης ωφθη τω [πατρι]{.greek-abbr} [ημων]{.greek-omitted} [υμων]{.greek-added} αβρααμ οντι εν τη μεσοποταμια πριν η κατοικησαι αυτον εν [χαρραν]{.greek-omitted} [χαραν]{.greek-added}[7:2]{.aside}

και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} προς αυτον εξελθε εκ της γης σου και εκ της [συγγενειας]{.greek-omitted} [συγγενεια]{.greek-added} σου και δευρο εις γην ην αν σοι δειξω[7:3]{.aside}

τοτε εξελθων εκ γης χαλδαιων κατωκησεν εν [χαρραν]{.greek-omitted} [χαραν]{.greek-added} [και]{.greek-added} [κακειθεν]{.greek-omitted} [εκειθεν]{.greek-added} μετα το αποθανειν τον [πατερα]{.greek-abbr} αυτου [μετωκισεν]{.greek-omitted} [μετοκησεν]{.greek-added} αυτον εις την γην ταυτην εις ην υμεις νυν κατοικειτε[7:4]{.aside}

και ουκ εδωκεν αυτω κληρονομιαν εν αυτη ουδε βημα ποδος και επηγγειλατο δουναι [αυτω]{.greek-omitted} [αυτην]{.greek-added} εις κατασχεσιν [αυτην]{.greek-omitted} [αυτω]{.greek-added} και τω σπερματι αυτου μετ αυτον ουκ οντος αυτω τεκνου[7:5]{.aside}

ελαλησεν δε ουτως ο [θεος]{.greek-abbr} οτι [εσται]{.greek-omitted} [εστε]{.greek-added} το σπερμα αυτου παροικον εν γη αλλοτρια και δουλωσουσιν [αυτο]{.greek-omitted} [αυτω]{.greek-added} και κακωσουσιν ετη τετρακοσια[7:6]{.aside}

[και]{.greek-omitted} το [δε]{.greek-added} εθνος ω εαν δουλευσωσιν κρινω εγω ειπεν ο [θεος]{.greek-abbr} και μετα ταυτα εξελευσονται και [λατρευσουσιν]{.greek-omitted} [λατρευσουσι]{.greek-added} μοι εν τω τοπω τουτω[7:7]{.aside}

και εδωκεν αυτω διαθηκην περιτομης και [ουτως]{.greek-omitted} [ουτος]{.greek-added} [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ισαακ και περιετεμεν αυτον τη ημερα τη ογδοη και ο ισαακ τον ιακωβ και ο ιακωβ τους δωδεκα πατριαρχας[7:8]{.aside}

και οι πατριαρχαι ζηλωσαντες τον ιωσηφ απεδοντο εις αιγυπτον και ην ο [θεος]{.greek-abbr} μετ αυτου[7:9]{.aside}

και εξειλετο αυτον εκ πασων των θλιψεων αυτου και εδωκεν αυτω χαριν και σοφιαν εναντιον φαραω βασιλεως αιγυπτου και κατεστησεν αυτον ηγουμενον επ αιγυπτον και ολον τον οικον αυτου[7:10]{.aside}

[ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} δε λιμος εφ ολην την γην αιγυπτου και χανααν και θλ[ι]{.greek-supplied}ψις μεγαλη και ουχ ευρισκον χορτασματα οι [πατερες]{.greek-abbr} ημων[7:11]{.aside}

ακουσας δε ιακωβ οντα σιτα εν αιγυπτω [εξαπεστειλεν]{.greek-omitted} [εξαπεστηλεν]{.greek-added} τους [πατερας]{.greek-abbr} ημων πρωτον[7:12]{.aside}

και εν τω δευτερω ανεγνωρισθη ιωσηφ τοις αδελφοις αυτου και φανερον εγενετο τω φαραω το γενος του ιωσηφ[7:13]{.aside}

αποστειλας δε ιωσηφ μετεκαλεσατο τον [πατερα]{.greek-abbr} αυτου ιακωβ και πασαν την [συγγενειαν]{.greek-omitted} [συνγγενειαν]{.greek-added} εν ψυχαις εβδομηκοντα πεντε[7:14]{.aside}

κατεβη δε ιακωβ εις αιγυπτον και ετελευτησεν [και]{.greek-added} αυτος και οι [πατερες]{.greek-abbr} ημων[7:15]{.aside}

και μετετεθησαν εις συχεμ και ετεθησαν εν τω μνηματι ο ωνησατο αβρααμ τιμης αργυριου παρα των υιων εμμορ [του]{.greek-omitted} [εν]{.greek-added} συχεμ[7:16]{.aside}

καθως δε ηγγιζεν ο χρονος της επαγγελιας ης ωμοσεν ο [θεος]{.greek-abbr} τω αβρααμ ηυξησεν ο λαος και επληθυνθη εν αιγυπτω[7:17]{.aside}

[αχρι]{.greek-omitted} [αχρις]{.greek-added} ου ανεστη βασιλευς ετερος ος ουκ ηδει τον ιωσηφ[7:18]{.aside}

ουτος κατασοφισαμενος το γενος ημων εκακωσεν τους [πατερας]{.greek-abbr} ημων του ποιειν εκθετα τα βρεφη αυτων εις το μη [ζωογονεισθαι]{.greek-omitted} [ζωογονησθαι]{.greek-added}[7:19]{.aside}

εν ω καιρω εγεννηθη [μωσης]{.greek-omitted} [μωυσις]{.greek-added} και ην αστειος τω [θεω]{.greek-abbr} ος ανετραφη μηνας τρεις εν τω οικω του [πατρος]{.greek-abbr}[7:20]{.aside}

εκτεθεντα δε [αυτον]{.greek-omitted} ανειλετο [αυτω]{.greek-added} η θυγατηρ φαραω και ανεθρεψατο αυτον [εαυτη]{.greek-omitted} [εαυτην]{.greek-added} εις υιον[7:21]{.aside}

και [επαιδευθη]{.greek-omitted} [επεδευθη]{.greek-added} [μωσης]{.greek-omitted} [μωυσης]{.greek-added} παση σ[ο]{.unclear}φια αιγυπτιων ην δε δυνατος εν λογοις και εργοις[7:22]{.aside}

ως δε επληρουτο αυτω [τεσσαρακονταετης]{.greek-omitted} [τεσαρακονταετης]{.greek-added} χρονος ανεβη επι την καρδιαν αυτου επισκεψασθαι τους αδελφους αυτου τους υιους [ισραηλ]{.greek-abbr}[7:23]{.aside}

και ιδων τινα αδικουμενον ημυνατο και εποιησεν εκδικησιν τω καταπονουμενω παταξας τον αιγυπτιον[7:24]{.aside}

[ενομιζεν]{.greek-omitted} [ενομιζε]{.greek-added} δε συνιεναι τους αδελφους αυτου οτι ο [θεος]{.greek-abbr} δια χειρος αυτου διδωσιν αυτοις [την]{.greek-added} [σωτηριαν]{.greek-abbr} οι δε ου συνηκαν[7:25]{.aside}

τη τε επιουση ημερα ωφθη αυτοις μαχομενοις και συνηλασεν αυτους εις ειρηνην ειπων ανδρες αδελφοι εστε υμεις [ινα]{.greek-omitted} [ινατι]{.greek-added} [τι]{.greek-omitted} αδικειτε αλληλους[7:26]{.aside}

ο δε αδικων τον πλησιον απωσατο αυτον ειπων τις σε κατεστησεν [αρ]{.greek-added} [αρχοντα]{.greek-omitted} [χονταν]{.greek-added} και δικαστην εφ ημας[7:27]{.aside}

μη ανελειν με συ θελεις ον τροπον ανειλες χθες τον αιγυπτιον[7:28]{.aside}

[εφυγεν]{.greek-omitted} [εφυγε]{.greek-added} δε [μωσης]{.greek-omitted} [μωυσης]{.greek-added} εν τω λογω τουτω και εγενετο παροικος εν γη μαδιαμ ου εγεννησεν υιους δυο[7:29]{.aside}

και πληρωθεντων ετων [τεσσαρακοντα]{.greek-omitted} [τεσαρακοντα]{.greek-added} ωφθη αυτω εν τη ερημω του ορους σινα αγγελος [κυριου]{.greek-abbr} εν φλογι πυρος βατου[7:30]{.aside}

ο δε [μωσης]{.greek-omitted} [μωυσης]{.greek-added} ιδων [εθαυμαζεν]{.greek-omitted} [εθαυμαζε]{.greek-added} το οραμα προσερχομενου δε αυτου κατανοησαι εγενετο φωνη [κυριου]{.greek-abbr} προς αυτον[7:31]{.aside}

εγω ο [θεος]{.greek-abbr} των [πατερων]{.greek-abbr} σου ο [θεος]{.greek-abbr} αβρααμ και ο [θεος]{.greek-abbr} ισαακ και ο [θεος]{.greek-abbr} ιακωβ εντρομος δε γενομενος [μωσης]{.greek-omitted} [μωυσης]{.greek-added} ουκ ετολμα κατανοησαι[7:32]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε αυτω ο [κυριος]{.greek-abbr} λυσον το υποδημα των ποδων σου ο γαρ τοπος [ον]{.greek-added} [εν]{.corr} ω εστηκας γη αγια εστιν[7:33]{.aside}

ιδων ειδον την κακωσιν του λαου μου του εν αιγυπτω και του στεναγμου αυτων ηκουσα και κατεβην εξελεσθαι αυτους και νυν δευρο αποστελω σε εις αιγυπτον[7:34]{.aside}

τουτον τον [μωσην]{.greek-omitted} [μωυσην]{.greek-added} ον ηρνησαντο ειποντες τις σε κατεστησεν αρχοντα και δικαστην τουτον ο [θεος]{.greek-abbr} [και]{.greek-added} αρχοντα και λυτρωτην [απεστειλεν]{.greek-omitted} [απεσταλεν]{.greek-added} εν χειρι αγγελου του οφθεντος αυτω εν τη βατω[7:35]{.aside}

ουτος εξηγαγεν αυτους ποιησας τερατα και σημεια εν γη [αιγυπτω]{.greek-omitted} [αιγυπτου]{.greek-added} και εν [ερυθρα]{.greek-omitted} [ερηθρα]{.greek-added} θαλασση και εν τη ερημω ετη [τεσσαρακοντα]{.greek-omitted} [τεσαρακοντα]{.greek-added}[7:36]{.aside}

ουτος εστιν [ο]{.greek-omitted} [μωσης]{.greek-omitted} [μωυσης]{.greek-added} ο ειπων τοις υιοις [ισραηλ]{.greek-abbr} προφητην υμιν αναστησει [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ημων εκ των αδελφων υμων ως εμε[7:37]{.aside}

ουτος εστιν ο γενομενος εν τη εκκλησια εν τη ερημω μετα του αγγελου του λαλουντος αυτω εν τω ορει σινα και των [πατερων]{.greek-abbr} ημων ος εδεξατο [λογον]{.greek-omitted} [λογια]{.greek-added} ζωντα δουναι ημιν[7:38]{.aside}

ω ουκ ηθ[ε]{.unclear}λησαν υπηκοοι γενεσθαι οι [πατερες]{.greek-abbr} ημων αλλ απωσαντο και εστραφησαν τη καρδια αυτων εις αιγυπτον[7:39]{.aside}

ειποντες τω ααρων ποιησον ημιν θεους οι προπορευσονται ημων ο γαρ [μωσης]{.greek-omitted} [μωυσης]{.greek-added} ουτος ος εξηγαγεν ημας εκ γης αιγυπτου ουκ οιδαμεν τι γεγονεν αυτω[7:40]{.aside}

και εμοσχοποιησαν εν ταις ημεραις εκειναις και ανηγαγον θυσιαν τω ειδωλω και [ευφραινοντο]{.greek-omitted} [ηυφραινοντο]{.greek-added} εν τοις εργοις των χειρων αυτων[7:41]{.aside}

εστρεψεν δε ο [θεος]{.greek-abbr} και παρε[δ]{.unclear}ωκεν αυτους λατρευειν τη στρατια του [ουρανου]{.greek-abbr} καθως γεγραπται εν βιβλω των προφητων μη σφαγια και θυσιας προσηνεγκατε μοι ετη [τεσσαρακοντα]{.greek-omitted} [τεσαρακοντα]{.greek-added} εν τη ερημω οικος [ισραηλ]{.greek-abbr}[7:42]{.aside}

και ανελαβετε την σκηνην του μολοχ και το αστρον του [θεου]{.greek-abbr} [υμων]{.greek-omitted} [ημων]{.greek-added} [ρεμφαν]{.greek-omitted} [ρεφφαν]{.greek-added} τους τυπους ους εποιησατε προσκυνειν [αυτοις]{.greek-omitted} [αυτους]{.greek-added} και μετοικιω υμας επεκεινα βαβυλωνος[7:43]{.aside}

η σκηνη του μαρτυριου ην τοις πατρασιν ημων εν τη ερημω καθως διεταξατο ο λαλων τω [μωση]{.greek-omitted} [μωυση]{.greek-added} ποιησαι αυτην κατα τον τυπον ον εωρακει[7:44]{.aside}

ην και εισηγαγον διαδεξαμενοι οι [πατερες]{.greek-abbr} ημων μετα [ιησου]{.greek-omitted} [ισου]{.greek-added} εν τη κατασχεσει των εθνων ων εξωσεν ο [θεος]{.greek-abbr} απο προσωπου των [πατερων]{.greek-abbr} ημων εως των ημερων δαυιδ[7:45]{.aside}

ος [ευρεν]{.greek-omitted} [ευρε]{.greek-added} χαριν ενωπιον του [θεου]{.greek-abbr} και ητησατο ευρειν σκηνωμα τω [θεω]{.greek-abbr} ιακωβ[7:46]{.aside}

σολομων δε ωκοδομησεν αυτω οικον[7:47]{.aside}

αλλ ουχ ο υψιστος εν χειροποιητοις ναοις κατοικει καθως [και]{.greek-added} ο προφητης λεγει[7:48]{.aside}

ο [ουρανος]{.greek-abbr} μοι θρονος η δε γη υποποδιον των ποδων μου ποιον οικον οικοδομησετε μοι [λεγει]{.greek-omitted} [κυριος]{.greek-omitted} η τις τοπος της καταπαυσεως μου[7:49]{.aside}

ουχι η χειρ μου εποιησεν [παντα]{.greek-added} ταυτα [παντα]{.greek-omitted}[7:50]{.aside}

σκληροτραχηλοι και απεριτμητοι τη καρδια και τοις ωσιν υμεις αει τω [πνευματι]{.greek-abbr} τω αγιω αντιπιπτετε ως οι [πατερες]{.greek-abbr} [υμων]{.greek-omitted} [ημων]{.greek-added} και [υμεις]{.greek-omitted} [ημεις]{.greek-added}[7:51]{.aside}

τινα των προφητων ουκ εδιωξαν οι [πατερες]{.greek-abbr} υμων και [απεκτειναν]{.greek-omitted} [απεκτηναν]{.greek-added} τους προκαταγγειλαντας περι της ελευσεως του δικαιου ου νυν υμεις [προδοται]{.greek-omitted} [προδοτε]{.greek-added} και [φονεις]{.greek-omitted} [φωνεις]{.greek-added} γεγενησθε[7:52]{.aside}

οιτινες ελαβετε τον νομον εις διαταγας αγγελων και ουκ εφυλαξατε[7:53]{.aside}

ακουοντες δε ταυτα διεπριοντο ταις καρδιαις αυτων και εβρυχον τους οδοντας επ αυτον[7:54]{.aside}

[υπαρχων]{.greek-omitted} [υπαρχον]{.greek-added} δε πληρης [πνευματος]{.greek-abbr} αγιου ατενισας εις τον [ουρανον]{.greek-abbr} [ειδεν]{.greek-omitted} [οιδε]{.greek-added} δοξαν [θεου]{.greek-abbr} και [ιησουν]{.greek-abbr} εστωτα εκ δεξιων του [θεου]{.greek-abbr}[7:55]{.aside}

και ειπεν ιδου θεωρω τους [ουρανους]{.greek-abbr} ανεωγμενους και τον υιον του [ανθρωπου]{.greek-abbr} εκ δεξιων εστωτα του [θεου]{.greek-abbr}[7:56]{.aside}

κραξαντες δε φωνη μεγαλη συνεσχον τα ωτα αυτων και ωρμησαν ομοθυμαδον επ αυτον[7:57]{.aside}

και εκβαλοντες εξω της πολεως ελιθοβολουν και οι μαρτυρες απεθεντο τ[α]{.unclear} ιματια παρα τους ποδας νεανιου καλουμενου σαυλου[7:58]{.aside}

και ελιθοβολουν τον στεφανον επικαλουμενον και λεγοντα [κυριε]{.greek-abbr} [ιησου]{.greek-abbr} δεξαι το [πνευμα]{.greek-abbr} μου[7:59]{.aside}

θεις δε τα γονατα [εκραξεν]{.greek-omitted} [εκραξε]{.greek-added} φωνη μεγαλη [κυριε]{.greek-abbr} μη στησης αυτοις την αμαρτιαν ταυτην και τουτο ειπων εκοιμηθη[7:60]{.aside}

### Chapter 8

σαυλος δε ην συνευδοκων τη αναιρεσει αυτου εγενετο δε εν εκεινη τη ημερα διωγμος μεγας επι την εκκλησιαν την εν ιεροσολυμοις παντες δε διεσπαρησαν κατα τας χωρας της ιουδαιας και σαμαρειας πλην των αποστολων[8:1]{.aside}

[συνεκομισαν]{.greek-omitted} [συνεκομισατο]{.greek-added} δε τον στεφανον ανδρες ευλαβεις και [εποιησαντο]{.greek-omitted} [εποιησαν]{.greek-added} κοπετον μεγαν επ [αυτω]{.greek-omitted} [αυτον]{.greek-added}[8:2]{.aside}

σαυλος δε ελυμαινετο την εκκλησιαν κατα τους οικους εισπορευομενος συρων τε ανδρας και γυναικας παρεδιδου εις φυλακην[8:3]{.aside}

οι μεν ουν διασπαρεντες διηλθον ευαγγελιζομενοι τον λογον[8:4]{.aside}

φιλιππος δε κατελθων εις πολιν της σαμαρειας [εκηρυσσεν]{.greek-omitted} [εκηρυσεν]{.greek-added} αυτοις τον [χριστον]{.greek-abbr}[8:5]{.aside}

προσειχον τε οι οχλοι τοις λεγομενοις υπο του φιλιππου ομοθυμαδον εν τω ακουειν αυτους και βλεπειν τα σημεια α εποιει[8:6]{.aside}

πολλων γαρ των εχοντων πνευματα ακαθαρτα βοωντα φωνη μεγαλη [εξηρχετο]{.greek-omitted} [εξηρχοντο]{.greek-added} πολλοι δε παραλελυμενοι και χωλοι εθεραπευθησαν[8:7]{.aside}

και εγενετο χαρα μεγαλη εν τη πολει εκεινη[8:8]{.aside}

ανηρ δε τις ονοματι σιμων προυπηρχεν εν τη πολει μαγευων και εξιστων το εθνος της σαμαρειας λεγων ειναι τινα εαυτον μεγαν[8:9]{.aside}

ω προσειχον απο μικρου εως μεγαλου [αυτων]{.greek-added} λεγοντες ουτος εστιν η δυναμις του [θεου]{.greek-abbr} η μεγαλη[8:10]{.aside}

προσειχον δε αυτω δια το ικανω χρονω ταις μαγειαις εξεστακεναι αυτους[8:11]{.aside}

οτε δε επιστευσαν τω φιλιππω ευαγγελιζομενω τα περι της βασιλειας του [θεου]{.greek-abbr} και του ονοματος [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} εβαπτιζοντο ανδρες τε και γυναικες[8:12]{.aside}

ο δε σιμων και αυτος επιστευσεν και βαπτισθεις ην [προσκαρτερων]{.greek-omitted} [προσκαρτερω]{.greek-added} τω φιλιππω θεωρων τε δυναμεις και σημεια γινομενα εξιστατο[8:13]{.aside}

ακουσαντες δε οι εν ιεροσολυμοις αποστολοι οτι δεδεκται η σαμαρεια τον λογον του [θεου]{.greek-abbr} απεστειλαν προς αυτους τον πετρον και ιωαννην[8:14]{.aside}

οιτινες [καταβαντες]{.greek-omitted} [ακουσαντες]{.greek-added} [προσηυξαντο]{.greek-omitted} [προσηυξατο]{.greek-added} περι αυτων οπως λαβωσιν [πνευμα]{.greek-abbr} αγιον[8:15]{.aside}

ουπω γαρ ην επ ουδενι αυτων επιπεπτωκος μονον δε βεβαπτισμενοι υπηρχον εις το ονομα [του]{.greek-omitted} [[ιησου]{.greek-abbr}]{.greek-added} [χριστου]{.greek-abbr} [ιησου]{.greek-omitted}[8:16]{.aside}

τοτε επετιθουν τας χειρας επ αυτους και ελαμβανον [πνευμα]{.greek-abbr} αγιον[8:17]{.aside}

θεασαμενος δε ο σιμων οτι δια της επιθεσεως των χειρων των αποστολων [διδοται]{.greek-omitted} [διδοτε]{.greek-added} το [πνευμα]{.greek-abbr} το αγιον προσηνεγκεν αυτοις χρηματα[8:18]{.aside}

λεγων δοτε καμοι την εξουσιαν ταυτην ινα ω εαν επιθω τας χειρας [μου]{.greek-added} λαμβανη [πνευμα]{.greek-abbr} αγιον[8:19]{.aside}

πετρος δε ειπεν προς αυτον το αργυριον σου συν σοι ειη εις απωλειαν οτι την δωρεαν του [θεου]{.greek-abbr} ενομισας δια χρηματων κτασθαι[8:20]{.aside}

ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} σοι μερις ουδε κληρος εν τω λογω τουτω η γαρ καρδια σου ουκ εστιν ευθεια ενωπιον του [θεου]{.greek-abbr}[8:21]{.aside}

μετανοησον ουν απο της κακιας σου ταυτης και δεηθητι του [θεου]{.greek-abbr} ει αρα α[φ]{.unclear}εθησεται σοι η επινοια της καρδιας σου[8:22]{.aside}

εις γαρ χολην πικριας και συνδεσμον αδικιας ορω σε οντα[8:23]{.aside}

αποκριθεις δε ο σιμων [ειπεν]{.greek-omitted} [ειπε]{.greek-added} δεηθητε [υμεις]{.greek-omitted} [ημεις]{.greek-added} υπερ εμου προς τον [κυριον]{.greek-abbr} οπως μηδεν επελθη επ εμε ων ειρηκατε[8:24]{.aside}

οι μεν ουν διαμαρτυραμενοι και λαλησαντες τον λογον του [κυριου]{.greek-abbr} υπεστρεψαν εις [ιερουσαλημ]{.greek-omitted} [[ιλημ]{.greek-abbr}]{.greek-added} πολλας τε [κωμας]{.greek-omitted} [κομας]{.greek-added} των [σαμαρειτων]{.greek-omitted} [σαμαριτων]{.greek-added} ευηγγελισαντο[8:25]{.aside}

αγγελος δε [κυριου]{.greek-abbr} [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} προς φιλιππον λεγων αναστηθι και πορευου κατα μεσημβριαν επι την οδον την καταβαινουσαν απο ιερουσαλημ εις γαζαν αυτη εστιν ερημος[8:26]{.aside}

και αναστας επορευθη και ιδου ανηρ αιθιοψ ευνουχος [δυναστης]{.greek-omitted} κανδακης της βασιλισσης αιθιοπων ος ην επι πασης της γαζης αυτης ος εληλυθει προσκυνησων εις ιερουσαλημ[8:27]{.aside}

ην τε υποστρεφων και καθημενος επι του αρματος αυτου και [ανεγινωσκεν]{.greek-omitted} [ανεγινωσκε]{.greek-added} τον προφητην ησαιαν[8:28]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε το [πνευμα]{.greek-abbr} τω φιλιππω προσελθε και κολληθητι τω αρματι τουτω[8:29]{.aside}

προσδραμων δε ο φιλιππος ηκουσεν αυτου αναγινωσκοντος τον προφητην ησαιαν και ειπεν αρα γε γινωσκεις α αναγινωσκεις[8:30]{.aside}

ο δε [ειπεν]{.greek-omitted} [ειπε]{.greek-added} πως γαρ αν δυναιμην εαν μη τις οδηγηση με [παρεκαλεσεν]{.greek-omitted} [παρεκαλεσε]{.greek-added} τε τ[ο]{.greek-supplied}ν φιλιππον αναβαντα καθισαι συν αυτω[8:31]{.aside}

η δε π[ερ]{.unclear}ιοχη της γραφης ην ανεγινωσκεν ην αυτη ως προβατον επι σφαγην ηχθη και ως αμνος εναντιον του κειροντος αυτον αφωνος ουτως ουκ ανοιγει το στομα αυτου[8:32]{.aside}

εν τη ταπεινωσει αυτου η κρισις αυτου ηρθη την δε γενεαν αυτου τις διηγησεται οτι αιρεται απο της γης η ζωη αυτου[8:33]{.aside}

αποκριθεις δε ο ευνουχος τω φιλιππω [ειπεν]{.greek-omitted} [ειπε]{.greek-added} δεομαι σου περι τινος ο προφητης λεγει τουτο περι εαυτου η περι ετερου τινος[8:34]{.aside}

ανοιξας δε ο φιλιππος το στομα αυτου και αρξαμενος απο της γραφης ταυτης ευηγγελισατο αυτω τον [ιησουν]{.greek-abbr}[8:35]{.aside}

ως δε επορευοντο κατα την οδον ηλθον επι τι υδωρ και φησιν ο ευνουχος ιδου υδωρ τι κωλυει με βαπτισθηναι[8:36]{.aside}

και εκελευσεν στηναι το αρμα και κατεβησαν αμφοτεροι εις το υδωρ ο τε φιλιππος και ο ευνουχος και εβαπτισεν αυτον[8:38]{.aside}

οτε δε ανεβησα[ν]{.unclear} εκ του υδατος [πνευμα]{.greek-abbr} [κυριου]{.greek-abbr} [ηρπασεν]{.greek-omitted} [ηρπασε]{.greek-added} τον φιλιππο[ν]{.unclear} και ουκ ειδεν αυτον ουκετι ο ευνουχος επορευετο γ[α]{.unclear}[ρ]{.greek-supplied} την οδον αυτου χαιρων[8:39]{.aside}

φιλιππος δε ευρεθη εις αζωτον και διερχομενος ευηγγελιζετο τας πολεις πασας εως του ελθειν αυτον εις καισαρειαν[8:40]{.aside}

### Chapter 9

ο δε σαυλος ετι εμπνεων απειλης και φονου εις τους μαθητας του [κυριου]{.greek-abbr} προσελθων τω αρχιερει[9:1]{.aside}

ητησατο παρ αυτου επιστολας εις δαμασκον προς τας συναγωγας οπως εαν τινας ευρη της οδο[υ]{.unclear} οντας ανδρας τε και γυναικας δεδεμενους αγαγη εις [ιερουσαλημ]{.greek-abbr}[9:2]{.aside}

εν δε τω πορευεσθαι εγενετο αυτον εγγιζειν τη δαμασκω και εξαιφνης περιηστραψεν αυτον φως απο του [ουρανου]{.greek-abbr}[9:3]{.aside}

και πεσων επι την γην [ηκουσεν]{.greek-omitted} [ηκουσε]{.greek-added} [φωνην]{.greek-omitted} [φωνης]{.greek-added} [λεγουσαν]{.greek-omitted} [λεγουσης]{.greek-added} αυτω σαουλ σαουλ τι με [διωκεις]{.greek-omitted} [διωκης]{.greek-added}[9:4]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε τις ει [κυριε]{.greek-abbr} ο δε [κυριος]{.greek-abbr} ειπεν εγω ειμι [ιησους]{.greek-abbr} ον συ διωκεις[9:5]{.aside}

[αλλα]{.greek-omitted} [αλλ]{.greek-added} αναστηθι και εισελθε εις την πολιν και λαληθησεται σοι τι σε δει ποιειν[9:6]{.aside}

οι δε ανδρες οι συνοδευοντες αυτω ειστηκεισαν [ενεοι]{.greek-omitted} [εννεοι]{.greek-added} ακουοντες μεν της φωνης μηδενα δε θεωρουντες[9:7]{.aside}

ηγερθη δε ο σαυλος απο της γης ανεωγμενων τε των οφθαλμων αυτου ουδενα [εβλεπεν]{.greek-omitted} [εβλεπε]{.greek-added} χειραγωγουντες δε αυτον [εισηγαγον]{.greek-omitted} [ηγαγον]{.greek-added} εις δαμασκον[9:8]{.aside}

και ην ημερας τρεις μη βλεπων και [ουκ]{.greek-omitted} [ουδε]{.greek-added} εφαγεν ουδε επιεν[9:9]{.aside}

ην δε τις μαθητης εν δαμασκω ονοματι ανανιας και ειπεν προς αυτον ο [κυριος]{.greek-abbr} εν οραματι ανανια ο δε ειπεν ιδου εγω [κυριε]{.greek-abbr}[9:10]{.aside}

ο δε [κυριος]{.greek-abbr} προς αυτον αναστας πορευθητι επι την ρυμην την καλουμενην [ευθειαν]{.greek-omitted} [ευθυαν]{.greek-added} και ζητησον εν οικια ιουδα σαυλον ονοματι ταρσεα ιδου γαρ προσευχεται[9:11]{.aside}

και ειδεν εν οραματι ανδρα [ανανιαν]{.greek-added} ονοματι [ανανιαν]{.greek-omitted} εισελθοντα και επιθεντα αυτω χειρα οπως αναβλεψη[9:12]{.aside}

απεκριθη δε ανανιας [κυριε]{.greek-abbr} ακηκοα απο πολλων περι του ανδρος τουτου οσα κακα [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} τοις αγιοις σου εν [ιερουσαλημ]{.greek-abbr}[9:13]{.aside}

και [ω]{.unclear}δε εχει εξουσιαν παρα των αρχιερεων δησαι παντας τους επικαλουμενους το ονομα σου[9:14]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε προς αυτον ο [κυριος]{.greek-abbr} πορευου οτι σκευος εκλογης μοι εστιν ουτος του βαστασαι το ονομα μου ενωπιον εθνων και βασιλεων υιων τε [ισραηλ]{.greek-abbr}[9:15]{.aside}

εγω γαρ υποδειξω αυτω οσα δει [αυτον]{.greek-omitted} υπερ του ονοματος μου παθειν[9:16]{.aside}

[απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} δε ανανιας και εισηλθεν εις την [οικιαν]{.greek-omitted} [οικειαν]{.greek-added} και επιθεις [αυτω]{.greek-added} [επ]{.greek-omitted} [αυτον]{.greek-omitted} τας χειρας [ειπεν]{.greek-omitted} [ειπε]{.greek-added} σαου[λ]{.unclear} αδελφε ο [κυριος]{.greek-abbr} [απεσταλκεν]{.greek-omitted} [απεσταλκε]{.greek-added} με ο οφθεις σοι εν τη οδω η ηρχου οπως αναβλεψης και πλησθης [πνευματος]{.greek-abbr} αγιου[9:17]{.aside}

και ευθεως απεπεσον απο των οφθαλμων αυτου ωσει λεπιδες [ανεβλεψεν]{.greek-omitted} [ανεβλεψε]{.greek-added} τε και αναστας εβαπτισθη[9:18]{.aside}

και λαβων τροφην ενισχυσεν εγενετο δε ο σαυλος μετα των [οντων]{.greek-added} εν δαμασκω μαθητων ημερας τινας[9:19]{.aside}

και ευθεως εν ταις συναγωγαις [εκηρυσσεν]{.greek-omitted} [εκηρυσσε]{.greek-added} τον [χριστον]{.greek-abbr} οτι ουτος εστιν ο υιος του [θεου]{.greek-abbr}[9:20]{.aside}

εξισταντο δε παντες οι ακουοντες και ελεγο[ν]{.greek-supplied} ουχ ουτος εστιν ο πορθησας εν [ιερουσαλημ]{.greek-abbr} τους επικαλουμενους το ονομα τουτο και ωδε εις τουτο εληλυθεν ινα δεδεμενους αυτους αγαγη επι τους αρχιερεις[9:21]{.aside}

σαυλος δε [μαλλον]{.greek-omitted} [ε]{.greek-added} [ενεδυναμουτο]{.greek-omitted} [νεδυναμουτο]{.greek-added} και [συνεχυνεν]{.greek-omitted} [συνεχυνε]{.greek-added} τους ιουδαιους τους κατοικουντας εν δαμασκω συμβιβαζων οτι ουτος εστιν ο [χριστος]{.greek-abbr}[9:22]{.aside}

ως δε επληρουντο ημεραι ικαναι συνεβουλευσαντο οι ιουδαιοι ανελειν αυτον[9:23]{.aside}

εγνωσθη δε τω σαυλω [η]{.unclear} [ε]{.unclear}πιβουλη αυτων παρετηρουν τε τας πυλας ημερας τε και νυκτος οπως αυτον [ανελωσιν]{.greek-omitted} [ανελωσι]{.greek-added}[9:24]{.aside}

λαβοντες δε αυτον οι μαθηται νυκτος καθηκαν δια του [τειχους]{.greek-omitted} [τοιχους]{.greek-added} χαλασαντες εν σπυριδι[9:25]{.aside}

παραγενομενος δε ο σαυλος εν [ιερουσαλημ]{.greek-abbr} επειρατο κολλασθαι τοις μαθηταις και παντες εφοβουντο αυτον μη πιστευοντες οτι εστιν μαθητης[9:26]{.aside}

βαρναβας δε επιλαβομενος αυτον [ηγαγεν]{.greek-omitted} [ηγαγε]{.greek-added} προς τους αποστολους και διηγησατο αυτοις πως εν τη οδω [ειδεν]{.greek-omitted} [ειδε]{.greek-added} τον [κυριον]{.greek-abbr} και οτι ελαλησεν αυτω και πως εν δαμασκω επαρρησιασατο εν τω ονοματι του [ιησου]{.greek-abbr}[9:27]{.aside}

και ην μετ αυτων εισπορευομενος εις [ιερουσαλημ]{.greek-abbr} και παρρησιαζομενος εν τω ονοματι του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr}[9:28]{.aside}

ελαλει τε και [συνεζητει]{.greek-omitted} [συνεζειτη]{.greek-added} προς τους ελληνιστας οι δε επεχειρουν αυτον ανελειν[9:29]{.aside}

επιγνοντες δε οι αδελφοι κατηγαγον αυτον εις καισαρειαν και [εξαπεστειλαν]{.greek-omitted} [εξαπεστηλαν]{.greek-added} αυτον εις ταρσον[9:30]{.aside}

αι μεν ουν εκκλησιαι καθ ολης της ιουδαιας και γαλιλαιας και σαμαρειας ειχον ειρηνην οικοδομουμεναι και πορευομεναι τω φοβω του [κυριου]{.greek-abbr} και τη παρακλησει του αγιου [πνευματος]{.greek-abbr} επληθυνοντο[9:31]{.aside}

εγενετο δε πετρον διερχομενον δια παντων κατελθειν και προς τους αγιους τους κατοικουντας λυδδαν[9:32]{.aside}

[ευρεν]{.greek-omitted} [ευρε]{.greek-added} δε εκει [ανθρωπον]{.greek-abbr} [τινα]{.greek-omitted} αινεαν ονοματι εξ ε[τ]{.greek-supplied}[ω]{.unclear}ν οκτω κατακειμενον επι κραββατω ος ην π[α]{.unclear}ραλελυμενος[9:33]{.aside}

και ειπεν αυτω ο πετρος αινεα ιαται σε [ιησους]{.greek-abbr} ο [χριστος]{.greek-abbr} αναστηθι και στρωσον σεαυτω και ευθεως ανεστη[9:34]{.aside}

και ειδον αυτον παντες οι κατοικουντες λυδδαν και τον [ασσαρωνα]{.greek-omitted} [σαρωναν]{.greek-added} οιτινες επεστρεψαν επι τον [κυριον]{.greek-abbr}[9:35]{.aside}

εν [ιοππη]{.greek-omitted} [ιωπη]{.greek-added} δε τις ην μαθ[η]{.unclear}τρια ονοματι ταβηθα η [διερμηνευομενη]{.greek-omitted} [διερμηνευομενοι]{.greek-added} λεγ[ε]{.unclear}ται δορκας αυτη ην [πληρης]{.greek-omitted} [πληρις]{.greek-added} αγαθων εργων και ελεημοσυνων ων εποιει[9:36]{.aside}

εγενετο δε εν ταις ημεραις εκειναις ασθενησασαν αυτην αποθανειν λουσαντες δε αυτην εθηκαν εν υπερωω[9:37]{.aside}

εγγυς δε ουσης λυδδης τη [ιοππη]{.greek-omitted} [ιωπη]{.greek-added} οι μαθηται ακουσαντες οτι πετρος εστιν εν αυτη [απεστειλαν]{.greek-omitted} [απεστηλαν]{.greek-added} προς αυτον παρακαλουντες μη οκνησαι διελθειν εως [αυτων]{.greek-omitted} [αυτον]{.greek-added}[9:38]{.aside}

αν[α]{.unclear}στας δε πετρος συνηλθεν αυτοις ον παραγενομε[ν]{.unclear}[ον]{.greek-supplied} ανηγαγον εις το υπερωον και παρεστησαν αυτω πασαι αι χηραι κλαιουσαι και επιδεικνυμεναι χιτωνας και ιματια οσα εποιει μετ αυτων ουσα η δορκας[9:39]{.aside}

εκβαλων δε εξω παντας ο πετρος θεις τα γονατα προσηυξατ[ο]{.unclear} και επιστρεψας προς το σωμα [ειπεν]{.greek-omitted} [ειπε]{.greek-added} ταβηθα αναστηθι η δε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} τους οφθαλμους αυτης και ιδουσα τον πετρον [ανεκαθισεν]{.greek-omitted} [ανεκαθησε]{.greek-added}[9:40]{.aside}

δους δε αυτη χειρα [ο]{.greek-added} [πετρος]{.greek-added} ανεστησεν αυτην φωνησας δε τους αγιους και τας [χηρας]{.greek-omitted} [χειρας]{.greek-added} παρεστησεν αυτην ζωσα[ν]{.greek-supplied}[9:41]{.aside}

γνωστον δε εγενετο καθ ολης της ιοππης και πολλοι επιστευσαν επι τον [κυριον]{.greek-abbr}[9:42]{.aside}

εγενετο δε ημερας ικανας μειναι αυτον εν [ιοππη]{.greek-omitted} [ιωπει]{.greek-added} παρα τινι σιμωνι βυρσει[9:43]{.aside}

### Chapter 10

ανηρ δε τις ην εν καισαρεια ονοματι κορνηλιος εκατονταρχης εκ [σπειρης]{.greek-omitted} [σπειρας]{.greek-added} της καλουμενης ιταλικης[10:1]{.aside}

ευσεβης και φοβουμενος τον [θεον]{.greek-abbr} συν παντι τω οικω αυτου ποιων τε ελεημοσυνας πολλας τω λαω και δεομενος [δια]{.greek-added} [παντος]{.greek-added} του [θεου]{.greek-abbr} [δια]{.greek-omitted} [παντος]{.greek-omitted}[10:2]{.aside}

ειδεν εν οραματι φανερως ωσει ωραν [ενατην]{.greek-omitted} [εννατην]{.greek-added} της ημερας αγγελον του [θεου]{.greek-abbr} εισελθοντα προς αυτον και ειποντα αυτω κορνηλιε[10:3]{.aside}

ο δε ατενισας αυτω και εμφοβος γενομενος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τι [εστιν]{.greek-omitted} [εστι]{.greek-added} [κυριε]{.greek-abbr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε αυτω αι προσευχαι σου και [αι]{.greek-omitted} ελεημοσυναι σου ανεβησαν εις μνημοσυνον ενωπιον του [θεου]{.greek-abbr}[10:4]{.aside}

και νυν πεμψον εις [ιοππην]{.greek-omitted} [ιωπην]{.greek-added} ανδρας και μεταπεμψαι σιμωνα τον επικαλουμενον πετρον[10:5]{.aside}

ουτος ξενιζεται παρα τινι σιμωνι βυρσει ω εστιν οικια [παρα]{.greek-omitted} [περι]{.greek-added} θαλασσαν[10:6]{.aside}

ως δε απηλθεν ο αγγελος ο λαλων τω κορνηλιω φωνησας δυο των οικετων αυτου και στρατιωτην [ευσεβη]{.greek-omitted} [ευσεβει]{.greek-added} των προσκαρτερουντων [αυτω]{.greek-omitted} [αυτων]{.greek-added}[10:7]{.aside}

και εξηγησα[μ]{.unclear}ενος αυτοις απαντα [απεστειλεν]{.greek-omitted} [απεστηλεν]{.greek-added} αυτους εις την [ιοππην]{.greek-omitted} [ιωπην]{.greek-added}[10:8]{.aside}

τη δε επαυριον οδοιπορουντων [εκεινων]{.greek-omitted} [εκεινον]{.greek-added} και τη πολει εγγιζοντων ανεβη πετρος επι το δωμα προσευξασθαι περι ωραν εκτην[10:9]{.aside}

εγενετο δε προσπεινος και [ηθελεν]{.greek-omitted} [ηθελε]{.greek-added} γευσασθαι παρασκευαζοντων δε εκεινων [επεπεσεν]{.greek-omitted} [επεσεν]{.greek-added} επ αυτον εκστασις[10:10]{.aside}

και θεωρει τον [ουρανον]{.greek-abbr} ανεωγμενον και καταβαινον επ αυτον σκευος τι ως οθονην μεγαλην [τεσσαρσιν]{.greek-omitted} [τεσαρσιν]{.greek-added} αρχαις δεδεμενον και καθιεμενον επι της γης[10:11]{.aside}

εν ω υπηρχεν παντα τα τετραποδα της γης και τα θηρια και τα ερπετα και τα πετεινα του [ουρανου]{.greek-abbr}[10:12]{.aside}

και εγενετο φωνη προς αυτον αναστας πετρε θυσον και φαγε[10:13]{.aside}

ο δε πετρος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} μηδαμως [κυριε]{.greek-abbr} οτι ουδεποτε εφαγον πα[ν]{.greek-supplied} κοινον η ακαθαρτον[10:14]{.aside}

και φωνη παλιν [εκ]{.greek-omitted} [δευτερου]{.greek-omitted} προς αυτο[ν]{.unclear} α ο [θεος]{.greek-abbr} [εκαθαρισεν]{.greek-omitted} [εκαθαρισε]{.greek-added} συ μη κοινου[10:15]{.aside}

τουτο δε εγενετο [ε]{.unclear}πι τρις και παλιν ανεληφθη το σκευος εις το[ν]{.unclear} [ουρανον]{.greek-abbr}[10:16]{.aside}

ως δε εν εαυτω διηπορει ο π[ε]{.unclear}τρος τι αν ειη το οραμα ο [ειδεν]{.greek-omitted} [ειδε]{.greek-added} και ιδου [οι]{.greek-omitted} [ανδρες]{.greek-omitted} οι απεσταλμ[ε]{.unclear}νοι απο του κορνηλιου διερωτησαντες την οικιαν σιμ[ω]{.unclear}νος επεστησαν επι τον πυλωνα[10:17]{.aside}

και φωνησαντες επυνθανοντο ει σιμων ο [επι]{.greek-added} [επικαλουμενος]{.greek-omitted} [καλουμενος]{.greek-added} πετρος ενθαδε ξενιζεται[10:18]{.aside}

του δε πετρου διενθυμουμενου περι του οραματος ειπεν αυτω το [πνευμα]{.greek-abbr} ιδου ανδρες [ζητουσιν]{.greek-omitted} [ζητουσι]{.greek-added} σε[10:19]{.aside}

αλλα αναστας καταβηθι και πορευου συν αυτοις μηδεν διακρινομενος διοτι εγω απεσταλκα αυτους[10:20]{.aside}

καταβας δε πετρο[ς]{.unclear} προς τους ανδρας ειπεν ιδου εγω ειμι ον ζητειτ[ε]{.unclear} τις η αιτια δι ην παρεστε[10:21]{.aside}

οι δε ειπον κορνηλιος εκατονταρχης ανηρ δικαιος και φοβουμενος τον [θεον]{.greek-abbr} μαρτυρουμενος τε υπο ολου του εθνους των ιουδαιων εχρηματισθη υπο αγγελου αγιου μεταπεμψασθαι σε εις τον οικον αυτου και ακουσαι ρηματα παρα σου[10:22]{.aside}

εισκαλεσαμενος ουν αυτους [εξενισεν]{.greek-omitted} [εξενισε]{.greek-added} τη δε επαυριον ο πετρος εξηλθεν συν αυτοις και τινες των αδελφων των απο [ιοππης]{.greek-omitted} [ιωπης]{.greek-added} συνηλθον αυτω[10:23]{.aside}

και τη επαυριον εισηλθον εις την καισαρειαν ο δε κορνηλιος ην προσδοκων αυτους συγκαλεσαμενος τους συγγενεις αυτου και τους [αναγκαιους]{.greek-omitted} [αναγγαιους]{.greek-added} φιλους[10:24]{.aside}

ως δε εγενετο του εισελθειν τον πετρον συναντησας αυτω ο κορνηλιος πεσων επι τους ποδας προσεκυνησεν[10:25]{.aside}

ο δε πετρος [ηγειρεν]{.greek-added} αυτον [ηγειρεν]{.greek-omitted} λεγων αναστηθι καγω αυτος [ανθρωπος]{.greek-abbr} ειμι[10:26]{.aside}

και συνομιλων αυτω [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} και ευρισκει συν[ε]{.unclear}ληλυθοτας πολλους[10:27]{.aside}

εφη τε προς αυτους υμεις επιστασθε ως αθεμιτον εστιν ανδρι ιουδαιω κολλασθαι η προσερχεσθαι αλλοφυλω και εμοι ο [θεος]{.greek-abbr} εδειξεν μηδενα κοινον η ακαθαρτον λεγειν [ανθρωπον]{.greek-abbr}[10:28]{.aside}

διο και [αναντιρρητως]{.greek-omitted} [αναντηρρητως]{.greek-added} ηλθον μεταπεμφθεις πυνθανομαι [ουν]{.greek-omitted} [γουν]{.greek-added} τινι λογω μετεπεμψ[ασ]{.unclear}θε με[10:29]{.aside}

και [ο]{.unclear} κορνηλιος εφη απο τεταρτης ημερας [μ]{.unclear}εχρι ταυτης της ωρας ημην νηστευων και την [ενατην]{.greek-omitted} [εννατην]{.greek-added} ωραν προσευχομενος εν τω οικω μου και ιδου ανηρ εστη ενωπιον μου εν εσθητι λαμπρα[10:30]{.aside}

και [φησιν]{.greek-omitted} [φησι]{.greek-added} κορνηλιε εισηκουσθη σου η προσευχη και αι ελεημοσυναι σου εμνησθησαν ενωπιον του [θεου]{.greek-abbr}[10:31]{.aside}

πεμψον ουν εις [ιοππην]{.greek-omitted} [ιωπην]{.greek-added} και μετακαλεσαι σιμωνα ος επικαλειται πετρος ουτος ξενιζεται εν οικια σιμωνος [βυρσεως]{.greek-omitted} [βυρσαιος]{.greek-added} παρα θαλασσαν ος παραγενομενος λαλησει σοι[10:32]{.aside}

εξαυτης ουν επεμψα προ[ς]{.greek-supplied} σε συ τε καλως εποιησας παραγενομενος νυν ουν παντες ημεις ενωπιον του [θεου]{.greek-abbr} παρεσμεν ακουσαι παντα τα προστεταγμενα [σοι]{.greek-omitted} υπο του [θεου]{.greek-abbr}[10:33]{.aside}

ανοιξας δε πετρος το στομα [αυτου]{.greek-added} ειπεν επ αληθειας καταλαμβανομαι οτι ουκ εστιν προσωποληπτης ο [θεος]{.greek-abbr}[10:34]{.aside}

αλλ [εν]{.greek-supplied} παντι εθνει ο φοβουμενος [αυτον]{.greek-omitted} [τον]{.greek-added} [[θεον]{.greek-abbr}]{.greek-added} και εργαζομε[νος]{.greek-supplied} δικαιοσυνην δεκτος αυτω [εστιν]{.greek-omitted} [εστι]{.greek-added}[10:35]{.aside}

τον λογον ον απ[ε]{.unclear}στειλεν τοις υιοις [ισραηλ]{.greek-abbr} ευαγγελιζομενος ειρην[ην]{.greek-supplied} δια [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} ουτος εστιν παντων [κυριος]{.greek-abbr}[10:36]{.aside}

υμεις οιδατε το γενομενον ρημα καθ ολης της ιουδαιας αρξαμενον απο της γαλιλαιας μετα το [β[α]{.greek-supplied}]{.greek-added} [βαπτισμα]{.greek-omitted} [πτισμα]{.greek-added} ο εκηρυξεν ιωαννης[10:37]{.aside}

[ιησουν]{.greek-abbr} τον απο [ναζαρετ]{.greek-omitted} [ναζαρεθ]{.greek-added} ως εχρισεν αυτον ο [θεος]{.greek-abbr} [πνευματι]{.greek-abbr} αγιω και δυναμει [ος]{.greek-omitted} [ως]{.greek-added} [δε]{.greek-added} [διηλθεν]{.greek-omitted} [ηλθεν]{.greek-added} ευεργετων και ιωμενος παντας τους καταδυναστευομενους υπο του διαβολου οτι ο [θεος]{.greek-abbr} ην μετ αυτου[10:38]{.aside}

και ημεις εσμεν μαρτυρες [παντων]{.greek-omitted} ων εποιησεν εν τε τη χωρα των ιουδαιων και εν ιερουσαλημ ον [και]{.greek-omitted} ανειλον κρεμασαντες επι ξυλου[10:39]{.aside}

τουτον ο [θεος]{.greek-abbr} [ηγειρεν]{.greek-omitted} [ηγειρε]{.greek-added} τη τριτη ημερα και εδωκεν αυτον εμφανη γενεσθαι[10:40]{.aside}

ου παντι τω λαω αλλα [μαρτυσιν]{.greek-omitted} [μαρτυσι]{.greek-added} τοις προκεχειροτονημενοις υπο του [θεου]{.greek-abbr} ημιν οιτινες σ[υ]{.unclear}νεφαγομεν και συνεπιομεν αυτω μετα το αναστηναι αυτον εκ νεκρων[10:41]{.aside}

και παρηγγειλεν ημιν [κηρυξαι]{.greek-omitted} [κυρυξαι]{.greek-added} τω λαω και διαμαρτυρασθαι οτι αυτος εστιν ο ωρισμενος υπο του [θεου]{.greek-abbr} κριτης ζωντων και νεκρων[10:42]{.aside}

[τουτω]{.greek-omitted} [τουτο]{.greek-added} παντες οι προφηται μαρτυρουσιν αφεσιν αμαρτιων λαβειν δια του ονοματος αυτου παντα τον πιστευοντα εις αυτον[10:43]{.aside}

ετι [δε]{.greek-added} λαλουντος του πετρου τα ρηματα ταυτα [επεπεσεν]{.greek-omitted} [επεπεσε]{.greek-added} το [πνευμα]{.greek-abbr} το αγιον επι παντας τους ακουοντας τον λογον[10:44]{.aside}

και εξεστησαν οι εκ περιτομης πιστοι οσοι συνηλθον τω πετρω οτι και επι τα εθνη η δωρεα του αγιου [πνευματος]{.greek-abbr} εκκεχυται[10:45]{.aside}

ηκουον γαρ αυτων λαλουντων γλωσσαις και μεγαλυνοντων τον [θεον]{.greek-abbr} τοτε απεκριθη ο πετρος[10:46]{.aside}

μητι το υδωρ κωλυσαι δυναται τις του [μη]{.greek-omitted} βαπτισθηναι τουτους οιτινες το [πνευμα]{.greek-abbr} το αγιον ελαβον καθως και ημεις[10:47]{.aside}

[προσεταξεν]{.greek-omitted} [προσεταξε]{.greek-added} τε αυτ[ους]{.greek-supplied} βαπτισθηναι εν τω ονοματι του [κυριου]{.greek-abbr} τοτε ηρωτ[η]{.greek-supplied}σαν αυτον επιμειναι ημερας τινας[10:48]{.aside}

### Chapter 11

ηκουσαν δ[ε]{.unclear} οι αποστολοι και οι αδελφοι οι οντες κατα την ιο[υ]{.greek-supplied}δαιαν οτι και τα εθνη εδεξαντο τον λογον του [θεου]{.greek-abbr}[11:1]{.aside}

και οτε ανεβη πετρος εις ιεροσολυμα διεκρινοντο προς αυτον οι εκ περιτομης[11:2]{.aside}

λεγοντες οτι προς ανδρας ακροβυστιαν εχοντας εισηλθες και συνεφαγες αυτοις[11:3]{.aside}

αρξαμενος δε ο πετρος [εξετιθετο]{.greek-omitted} [εξεθετο]{.greek-added} αυτοις [καθεξης]{.greek-omitted} λεγων[11:4]{.aside}

εγω ημην εν πολει [ιοππη]{.greek-omitted} [ιωπει]{.greek-added} προσευχομενος και ειδον εν εκστασει οραμα καταβαινον σκευος τι ως οθονην με[γα]{.greek-supplied}λην [τεσσαρσιν]{.greek-omitted} [τεσαρσιν]{.greek-added} αρχαις καθιεμενην εκ του [ουρανου]{.greek-abbr} και ηλθεν [αχρι]{.greek-omitted} [αχρις]{.greek-added} εμου[11:5]{.aside}

εις ην ατενισας κατενοουν και ειδον τα τετραποδα της γης και τα θηρια και τα ερπετα και τα πετεινα του [ουρανου]{.greek-abbr}[11:6]{.aside}

ηκουσα δε φ[ω]{.greek-supplied}νης λεγουσης μοι αναστας πετρε θυσον και φαγ[ε]{.unclear}[11:7]{.aside}

ειπον δε μηδαμως [κυριε]{.greek-abbr} οτι παν κοινον η ακαθ[α]{.unclear}[ρ]{.greek-supplied}τον ουδεποτε εισηλθεν εις το στομα μου[11:8]{.aside}

απεκρ[ι]{.unclear}θη δε μοι φωνη εκ δευτερου εκ του [ουρανου]{.greek-abbr} α ο [θεος]{.greek-abbr} [εκαθαρισεν]{.greek-omitted} [εκαθαρισε]{.greek-added} συ μη κοινου[11:9]{.aside}

τουτο δε εγενετο επι τρις και παλιν ανεσπασθη απαντα εις τον [ουρανον]{.greek-abbr}[11:10]{.aside}

και ιδου εξαυτης τρεις ανδρες επεστησαν επι την οικιαν εν η [ημην]{.greek-omitted} [ημεν]{.greek-added} απεσταλμενοι απο καισαρειας προς με[11:11]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε μοι το [πνευμα]{.greek-abbr} συνελθειν αυτοις μηδεν διακρινομενον ηλθον δε συν εμοι και οι εξ αδελφοι ουτοι και εισηλθομεν εις [τον]{.greek-omitted} [οικον]{.greek-omitted} [την]{.greek-added} [οικιαν]{.greek-added} του ανδρος[11:12]{.aside}

[απηγγειλεν]{.greek-omitted} [απηγγειλε]{.greek-added} τε ημιν πως [ειδεν]{.greek-omitted} [οιδε]{.greek-added} τον αγγελον εν τω οικω αυτου σταθεντα και ειποντα αυτω αποστειλον εις [ιοππην]{.greek-omitted} [ιωπην]{.greek-added} ανδρας και μεταπεμψαι σιμωνα τον επικαλουμενον πετρον[11:13]{.aside}

ος λαλησει ρηματα προς σε εν οις σωθηση συ και πας ο οικος σου[11:14]{.aside}

εν δε τω αρξασθαι με λαλειν [επεπεσεν]{.greek-omitted} [επεπεσε]{.greek-added} το [πνευμα]{.greek-abbr} το αγιον επ αυτους ωσπερ και εφ ημας εν αρχη[11:15]{.aside}

εμνησθην δε του ρηματος [κυριου]{.greek-abbr} ως ελεγεν ιωαννης μεν [εβαπτισεν]{.greek-omitted} [εβαπτ[η]{.unclear}σεν]{.greek-added} υδατι υμεις δε βαπτισθησεσθε εν [πνευματι]{.greek-abbr} αγιω[11:16]{.aside}

ει [ουν]{.greek-omitted} [γουν]{.greek-added} την ισην δωρεαν εδωκεν αυτοις ο [θεος]{.greek-abbr} ως και ημιν πιστευσασιν επι τον [κυριον]{.greek-abbr} [ιησουν]{.greek-abbr} [χριστον]{.greek-abbr} εγω δε τις ημην δυνατος κωλυσαι τον [θεον]{.greek-abbr}[11:17]{.aside}

ακουσαντες δε ταυτα ησυχασαν και [εδοξαζον]{.greek-omitted} [εδοξασαν]{.greek-added} τον [θεον]{.greek-abbr} λεγοντες [αρα]{.greek-omitted} [αραγε]{.greek-added} [γε]{.greek-omitted} και τοις εθνεσιν ο [θεος]{.greek-abbr} την μετανοιαν εδωκεν εις ζωην[11:18]{.aside}

οι μεν ουν διασπαρεντες [α]{.greek-supplied}πο της θλιψεως της [γενομενης]{.greek-omitted} [γενομενοις]{.greek-added} επι στεφανω διηλθον εως φοινικης και κυπρου [και]{.greek-omitted} αντιοχειας μηδενι λαλουντες τον λογον ει μη μονον ιουδαιοις[11:19]{.aside}

ησαν δε τινες εξ αυτων ανδρες κυπριοι και κυρηναιοι οιτινες [εισελθοντες]{.greek-omitted} [ελθοντες]{.greek-added} εις αντιοχειαν ελαλουν προς τους ελληνιστας [ε]{.greek-supplied}[υ]{.unclear}αγγελιζομενοι τον [κυριον]{.greek-abbr} [ιησουν]{.greek-abbr}[11:20]{.aside}

και ην χειρ [κυριου]{.greek-abbr} μετ αυτων πολυς τε αριθμος πιστευσας επεστρεψεν επι τον [κυριον]{.greek-abbr}[11:21]{.aside}

ηκουσθη δε ο λογος εις τα ωτα της εκκλησιας της εν ιεροσολυμοις περι αυτων και εξαπεστειλαν βαρναβαν διελθειν εως αντιοχειας[11:22]{.aside}

ος παραγενομενος και ιδων την χαριν του [θεου]{.greek-abbr} εχαρη και παρεκαλει π[α]{.unclear}[ν]{.greek-supplied}τας τη προθεσει της καρδιας προσμενειν τω [κυριω]{.greek-abbr}[11:23]{.aside}

οτι ην ανηρ αγαθος και [πληρης]{.greek-omitted} [πληρις]{.greek-added} [πνευματος]{.greek-abbr} αγιου και πιστεω[ς]{.unclear} και προσετεθη οχλος ικανος τω [κυριω]{.greek-abbr}[11:24]{.aside}

[εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} δε εις ταρσον ο βαρναβας αναζητησαι σαυλον[11:25]{.aside}

και ευρ[ων]{.unclear} [αυτον]{.greek-added} ηγαγεν [αυτον]{.greek-omitted} εις αντιοχειαν εγενετο δε [αυτους]{.greek-omitted} [αυτοις]{.greek-added} ενιαυτον ολον συναχθηναι τη εκκλησια και διδαξα[ι]{.unclear} οχλον ικανον χρηματισαι τε πρωτον εν αντιοχεια τους μαθητας χριστιανους[11:26]{.aside}

εν ταυταις δε ταις ημεραις κατηλθον απο ιεροσολυμων προφηται εις αντιοχειαν[11:27]{.aside}

αναστας δ[ε]{.greek-supplied} εις εξ αυτων ονοματι αγαβος [εσημανεν]{.greek-omitted} [εσημανε]{.greek-added} δια του [πνευματος]{.greek-abbr} λιμον μεγαν μελλειν εσεσθαι εφ [ο]{.unclear}λην την οικουμενην οστις και εγενετο επι κ[λ]{.unclear}[αυ]{.greek-supplied}διου καισαρος[11:28]{.aside}

των δε μαθητων καθως ευπορειτο τις ωρισαν εκαστος αυτων εις διακονιαν πεμψαι τοις κατοικουσιν εν τη ιουδαια [α]{.greek-supplied}δελφοις[11:29]{.aside}

ο και εποιησαν αποστειλαντες προ[ς]{.unclear} τους πρεσβυτερους δια χειρος βαρναβα και σαυλου[11:30]{.aside}

### Chapter 12

κατ εκεινον δε τον καιρον επεβαλεν ηρωδης ο βασιλευς τας χειρας [κακωσαι]{.greek-omitted} [κακωσε]{.greek-added} τινας των απο της εκκλησιας[12:1]{.aside}

[ανειλεν]{.greek-omitted} [ανειλε]{.greek-added} δε ιακωβον τον αδελφον ιωαννου μαχαιρα[12:2]{.aside}

και ιδων οτι αρεστον [εστιν]{.greek-omitted} [εστι]{.greek-added} τοις ιουδαιοις προσεθετο συλλαβειν και πετρον ησαν δε αι ημεραι των αζυμων[12:3]{.aside}

ον και πιασας εθετο εις φυλακην παραδους [τεσσαρσιν]{.greek-omitted} [τεσαρσιν]{.greek-added} τετραδιοις στρατιωτων φυλασσειν αυτον βουλομενος μετα το [πασχα]{.greek-omitted} [πασχ[α]{.unclear}ν]{.greek-added} [αναγαγειν]{.greek-omitted} [αγαγειν]{.greek-added} αυτον τω λαω[12:4]{.aside}

ο μεν ουν πετρος ετηρειτο εν τη φυλακη προσευχη δε ην εκτενης γινομενη υπο της εκκλησιας προς τον [θεον]{.greek-abbr} υπερ αυτου[12:5]{.aside}

οτε δε εμελλεν αυτον [προαγειν]{.greek-omitted} [προαγαγειν]{.greek-added} ο ηρωδης τη νυκτι εκεινη ην ο πετρος κοιμωμενος μεταξυ δυο στρατιωτων δεδεμενος [αλυσεσιν]{.greek-omitted} [αλυσεσι]{.greek-added} [δυσιν]{.greek-omitted} [δυσι]{.greek-added} φυλακες τε προ της θυρας ετηρουν την φυλακην[12:6]{.aside}

και ιδου αγγελος [κυριου]{.greek-abbr} επ[ε]{.unclear}στη και φως ελαμψεν εν τω οικηματι παταξας δε την πλευραν του πετρο[υ]{.unclear} ηγειρεν αυτον λεγων αναστα εν [ταχει]{.greek-omitted} [ταχη]{.greek-added} και εξεπεσον αυτου αι αλυσεις εκ των χειρων[12:7]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} τε ο αγγελος προς αυτον περιζωσαι και υποδησαι τα σανδαλια σου [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} δε ουτως και λεγει αυτω περιβαλου το ιματιον σου και ακολουθει μοι[12:8]{.aside}

και εξελθων ηκολουθει αυτω και ουκ ηδει οτι αληθες [εστιν]{.greek-omitted} [εστι]{.greek-added} το γινομενον δια του αγγελου εδοκει δε οραμα βλεπειν[12:9]{.aside}

διελθοντες δε πρωτην φυλακην και δευτεραν ηλθον επι την πυλην την σ[ι]{.greek-supplied}δηραν την φερουσαν εις την πολιν ητις αυτοματη ηνοιχθη αυτοις και εξελθοντες προηλθον ρυμ[η]{.unclear}[ν]{.greek-supplied} μιαν και ευθεως απεστη ο αγγελος απ αυτου[12:10]{.aside}

[και]{.unclear} ο πετρος γενομενος εν εαυτω [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [νυ]{.unclear}ν οιδα αλ[η]{.greek-supplied}θως οτι [εξαπεστειλεν]{.greek-omitted} [εξαπεστηλεν]{.greek-added} [κυριος]{.greek-abbr} τον αγγελον αυτου και εξ[ει]{.greek-supplied}λετο με εκ χειρος ηρωδου και πασης της προσδο[κι]{.greek-supplied}ας του λαου των ιουδαιων[12:11]{.aside}

συνιδων τε ηλθεν επι την οικιαν μαριας της [μητρος]{.greek-abbr} ιωαννου του [ε]{.greek-supplied}πικαλουμενου μαρκου ου ησαν ικανοι συνηθ[ροι]{.greek-supplied}σμενοι και προσευχομενοι[12:12]{.aside}

κρουσαντος δε του πετρο[υ]{.unclear} την θυραν του πυλωνος [προσηλθεν]{.greek-omitted} [προσηλθε]{.greek-added} παιδισκ[η]{.greek-supplied} υπακουσαι ονοματι ροδη[12:13]{.aside}

και επιγνουσα την φωνην του πετρου απο της χαρας ουκ [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} τ[ον]{.greek-supplied} πυλωνα εισδραμουσα δε απηγγειλεν εσταν[α]{.unclear}[ι]{.greek-supplied} [τον]{.greek-supplied} πετρον προ του πυλωνος[12:14]{.aside}

οι δε προς αυτην ειπον μαινη η δε διισχυριζετο ουτως εχειν οι δε [ε]{.greek-supplied}λεγον ο αγγελος αυτου εστιν[12:15]{.aside}

ο δε πετρος [επεμενεν]{.greek-omitted} [επ[ε]{.unclear}μενε]{.greek-added} κρουων ανοιξαντες δε ειδον αυτον κα[ι]{.greek-supplied} [ε]{.greek-supplied}ξεστησαν[12:16]{.aside}

κατασεισας δε αυτοις τη χειρι σιγαν διηγησατο αυτοις πως ο [κυριος]{.greek-abbr} [εξηγαγεν]{.greek-added} αυτο[ν]{.unclear} [εξηγαγεν]{.greek-omitted} εκ της φυλακης [ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε απαγγειλατ[ε]{.unclear} ιακωβω και τοις αδελφοις ταυτα κα[ι]{.greek-supplied} [εξελθων]{.greek-omitted} [[ε]{.greek-supplied}ξελθον]{.greek-added} επορευθη εις ετερον τοπον[12:17]{.aside}

γενομενης δε ημερας ην ταραχος ουκ ολιγος εν τοις στρατιωταις τι αρα ο πετρος εγενετο[12:18]{.aside}

ηρωδης δε επιζητησας αυτον και μη ευρων ανακρινας τους φυλακας εκελευσεν απαχθηναι και κατελθων απο της ιουδαιας εις την καισαρειαν διετριβεν[12:19]{.aside}

ην δε ο ηρωδης [θυμομαχων]{.greek-omitted} [θυμομαχον]{.greek-added} τυριοις και [σιδωνιοις]{.greek-omitted} [σιδονιοις]{.greek-added} ομοθυμαδον δε παρησαν προς αυτον και πεισαντες βλαστον τον επι του κοιτωνος του βασιλεως ητουντο ειρηνην δια το τρεφεσθαι αυτων την χωραν απο της βασιλικης[12:20]{.aside}

τακτη δε ημερα ο ηρωδης ενδυσαμενος εσθητα βασιλικην και καθισας επι του βηματος εδημηγορει προς αυτους[12:21]{.aside}

ο δε δημος επεφωνει φωνη [θεου]{.greek-abbr} και ουκ [ανθρωπου]{.greek-abbr}[12:22]{.aside}

παραχρημα δε επαταξεν αυτον αγγελος [κυριου]{.greek-abbr} ανθ ων ουκ [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} δοξαν τω [θεω]{.greek-abbr} και γενομενος σκωληκοβρωτος εξεψυξεν[12:23]{.aside}

ο δε λογος του [θεου]{.greek-abbr} [ηυξανεν]{.greek-omitted} [ηυξανε]{.greek-added} και επληθυνετο[12:24]{.aside}

βαρναβας δε και σαυλος υπεστρεψαν εις [ιερουσαλημ]{.greek-omitted} [[ιλημ]{.greek-abbr}]{.greek-added} πληρωσαντες την διακονιαν συμπαραλαβοντες [και]{.greek-omitted} ιωαννην τον επικληθεντα μαρκον[12:25]{.aside}

### Chapter 13

ησαν δε [τινες]{.greek-omitted} [τιναις]{.greek-added} εν αντιοχεια κατα την ουσαν εκκλησιαν προφηται και διδασκαλοι ο τε βαρναβας και συμεων ο καλουμενος νιγερ και λουκιος [ο]{.greek-omitted} κυρηναιος μαναην τε ηρωδου του [τραρχου]{.greek-added} [τετραρχου]{.corr} συντροφος και σαυλος[13:1]{.aside}

λειτουργουντων δε αυτων τω [κυριω]{.greek-abbr} και νηστευοντων [ειπεν]{.greek-omitted} [ειπε]{.greek-added} το [πνευμα]{.greek-abbr} το αγιον αφορ[ι]{.greek-supplied}σατε [δη]{.greek-omitted} μοι τον βαρναβαν και τον σαυλον εις το [ε]{.unclear}[ρ]{.greek-supplied}γον ο προσκεκλημαι αυτους[13:2]{.aside}

τοτε νηστευσαντε[ς]{.greek-supplied} και προσευξαμενοι και επιθεντες [αυτοις]{.greek-added} τας χ[ει]{.greek-supplied}ρας [αυτοις]{.greek-omitted} απελυσαν[13:3]{.aside}

ουτοι μεν ουν εκπεμφθεντες [υ]{.greek-supplied}πο του [πνευματος]{.greek-abbr} του αγιου κατηλθον εις την σελευκει[αν]{.greek-supplied} εκειθεν δε απεπλευσαν εις την κυπρον[13:4]{.aside}

και γενομενοι εν σαλαμινι [κατηγγελλον]{.greek-omitted} [κατηγγελον]{.greek-added} τον λογον του [θεου]{.greek-abbr} ε[ν]{.greek-supplied} ταις συναγωγαις των ιουδαιων ειχον δε και ιωα[ν]{.unclear}[νην]{.greek-supplied} υπηρετην[13:5]{.aside}

διελθοντες δε την νησον αχρι παφ[ου]{.greek-supplied} ευρον τινα μαγον ψευδοπροφητην ιουδαιον ω ο[νο]{.greek-supplied}μα βαριησους[13:6]{.aside}

ος ην συν τω ανθυπατω σεργιω παυλω ανδρι συνετω ουτος προσκαλεσαμενος βαρναβαν και σαυλον επεζητησεν ακουσαι [τον]{.greek-supplied} λογον του [θεου]{.greek-abbr}[13:7]{.aside}

ανθιστατο δε αυτοις ελυμας ο μ[α]{.unclear}γος ουτως γαρ μεθερμηνευεται το ονομα αυ[του]{.greek-supplied} ζητων διαστρεψαι τον ανθυπατον απο της π[ι]{.unclear}στεως[13:8]{.aside}

σαυλος δε ο και παυλος πλησθεις [πνευματος]{.greek-abbr} αγιου [και]{.greek-omitted} ατενισας εις αυτον[13:9]{.aside}

ειπεν ω πληρ[ης]{.greek-supplied} παντος δολου και [πασης]{.greek-omitted} ραδιουργιας υιε διαβολ[ου]{.greek-supplied} εχθρε πασ[η]{.unclear}ς [[πασεις]{.corr}]{.greek-added} δικαιοσυνης ου παυση διαστρεφων τας οδους [του]{.greek-added} [κυριου]{.greek-abbr} τας ευθειας[13:10]{.aside}

και νυ[ν]{.unclear} ιδου χειρ [κυριου]{.greek-abbr} επι σε και εση τυφλος μη [βλεπων]{.greek-omitted} [βλεπον]{.greek-added} τον ηλιον αχρι καιρου παραχρημα δε [ε]{.greek-supplied}πεπεσεν επ αυτον αχλυς και σκοτος και περιαγων εζητει χειραγωγους[13:11]{.aside}

τοτε ιδων ο ανθυπατος το γεγονος επιστευσεν εκπλησσομενος επι τη διδαχη του [κυριου]{.greek-abbr}[13:12]{.aside}

[α]{.unclear}ναχθεντες δε απο της παφου οι περι τον παυλον ηλθον εις περγην της παμφυλιας ιωαννης δε αποχωρησας απ αυτων υπεστρεψεν εις [ιεροσολυμαν]{.greek-added} [ιεροσολυμα]{.corr}[13:13]{.aside}

αυτοι δε διελθοντες απο της περγης παρεγενοντο εις αντιοχειαν της πισιδιας και εισελθοντες εις την συναγωγην τη ημερα των σαββατων εκαθισαν[13:14]{.aside}

μετα δε την αναγνωσιν του νομου και των προφητων απεστειλαν οι αρχισυναγωγοι προς αυτους λεγοντες ανδρες αδελφοι ει [εστιν]{.greek-omitted} [εστι]{.greek-added} λογος εν υμιν παρακλησεως προς τον λαον λεγετε[13:15]{.aside}

αναστας δε παυλος και κατασεισας τη χειρι ειπεν ανδρες ισραηλιται και οι φοβουμενοι τον [θεον]{.greek-abbr} ακουσατε[13:16]{.aside}

ο [θεος]{.greek-abbr} του λαου τουτου εξελεξατο τους [πατερας]{.greek-abbr} ημων και τον λαον υψωσεν εν τη παροικια εν γη [αιγυπτω]{.greek-omitted} [αιγυπτου]{.greek-added} και μετα βραχιονος υψηλου εξηγαγεν [αυτους]{.greek-omitted} εξ αυτης[13:17]{.aside}

και ως [τεσσαρακονταετη]{.greek-omitted} [τεσαρακονταετη]{.greek-added} χρονον ετροποφορησεν αυτους εν τη ερημω[13:18]{.aside}

και καθελων εθνη επτα εν γη χανααν κατεκληρονομησεν αυτοις την γην αυτων[13:19]{.aside}

και μετα ταυτα ως [ετεσιν]{.greek-omitted} [ετεσι]{.greek-added} τετρακοσιοις και πεντηκοντα εδωκεν κριτας εως σαμουηλ του προφητου[13:20]{.aside}

κακειθεν ητησαντο [βασιλεα]{.greek-omitted} [βασιλεαν]{.greek-added} και εδωκεν αυτοις [ο]{.greek-omitted} [θεος]{.greek-omitted} τ[ον]{.greek-supplied} σαουλ υιον κις ανδρα εκ φυλης βενιαμιν ετη [τεσσαρακοντα]{.greek-omitted} [τεσ[α]{.greek-supplied}ρακοντα]{.greek-added}[13:21]{.aside}

και μεταστησας αυτον ηγειρεν αυτοις τον [δαυιδ]{.greek-abbr} [εις]{.greek-supplied} βασιλεα ω και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} μαρτυρησας ευρον [δαυιδ]{.greek-abbr} τον [τ]{.unclear}[ου]{.greek-supplied} [ιεσσαι]{.greek-omitted} [ιεσαι]{.greek-added} ανδρα κατα την καρδιαν μου ος ποιησει παντα [τα]{.greek-supplied} θεληματα μου[13:22]{.aside}

τουτου ο [θεος]{.greek-abbr} απο του σπερματος κατ ε[πα]{.greek-supplied}γγελιαν [ηγαγεν]{.greek-omitted} [ηγαγε]{.greek-added} τω [ισραηλ]{.greek-abbr} [σωτηριαν]{.greek-omitted} [σωτηρα]{.greek-added}[13:23]{.aside}

προκηρυξαντος [ιω]{.greek-supplied}αννου προ προσωπου της εισοδου αυτου βαπτισμ[α]{.greek-supplied} μετανοιας τω [ισραηλ]{.greek-abbr}[13:24]{.aside}

ως δε επληρο[υ]{.greek-supplied} ο ιωαννης τον δρομον [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} τινα με υπονοειτε ειναι ουκ ειμι εγω αλλ ιδου ερχεται μετ εμε ου [ο]{.unclear}[υ]{.greek-supplied}κ ειμι αξιος το υποδημα των ποδων λυσαι[13:25]{.aside}

α[ν]{.greek-supplied}δρες αδελφοι υιοι γενους αβρααμ και οι εν υμ[ιν]{.greek-supplied} φοβουμενοι τον [θεον]{.greek-abbr} υμιν ο λογος της [σωτηριας]{.greek-abbr} ταυτης απεσταλη[13:26]{.aside}

οι γαρ κατοικουντες [εν]{.greek-omitted} ιερουσαλημ και οι αρχοντες αυτων τουτον αγνοησαντες και τας φωνα[ς]{.greek-supplied} των προφητων τας κατα παν σαββατον αναγι[νω]{.greek-supplied}σκομενας κριναντες επληρωσαν[13:27]{.aside}

και μηδεμιαν αιτιαν θανατου ευροντες ητησαντο πιλατον αν[αι]{.greek-supplied}ρεθηναι αυτον[13:28]{.aside}

ως δε ετελεσαν παντα [τα]{.unclear} περι αυτου γεγραμμενα καθελοντες απο το[υ]{.unclear} ξυλου εθηκαν εις μνημειον[13:29]{.aside}

ο δε [θεος]{.greek-abbr} ηγειρεν α[υ]{.greek-supplied}τον εκ νεκρων[13:30]{.aside}

ος ωφθη επι ημερας πλειους τοις συναναβασιν αυτω απο της γαλιλαιας εις [ιερουσαλημ]{.greek-abbr} οιτινες [εισιν]{.greek-omitted} [εισι]{.greek-added} μαρτυρες αυτου προς τον λαον[13:31]{.aside}

και ημεις υμας ευαγγελιζομεθα την προς τους [πατερας]{.greek-abbr} επαγγελιαν γενομενην [οτι]{.greek-omitted} [ταυτην]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [εκπεπληρωκεν]{.greek-omitted} [τοις]{.greek-omitted} [τεκνοις]{.greek-omitted} [αυτων]{.greek-omitted} [ημιν]{.greek-omitted} [αναστησας]{.greek-omitted} [ιησουν]{.greek-omitted}[13:32]{.aside}

[οτι]{.greek-added} [ταυτην]{.greek-added} [ο]{.greek-added} [[θεος]{.greek-abbr}]{.greek-added} [εκπεπληρωκε]{.greek-added} [τοις]{.greek-added} [τεκνοις]{.greek-added} [αυτων]{.greek-added} [ημιν]{.greek-added} [αναστησας]{.greek-added} [[ιησουν]{.greek-abbr}]{.greek-added} ως και εν τω [δευτερω]{.greek-added} ψαλμω [τω]{.greek-omitted} [δευτερω]{.greek-omitted} γεγραπται υιος μου ει συ εγω σημερον γεγεννηκα σε[13:33]{.aside}

οτι δε ανεστησεν αυτον εκ νεκρων μηκετι μελλοντα υποστρεφειν εις διαφθοραν ουτως ειρηκεν οτι δωσω υμιν τα οσια δαυιδ τα πιστα[13:34]{.aside}

διο και εν ετερω λεγει ου δωσεις τον οσιον σου ιδειν διαφθοραν[13:35]{.aside}

δαυιδ μεν γαρ ιδια γενεα υπηρετησας τη του [θεου]{.greek-abbr} βουλη εκοιμηθη και προσετεθη προς τους [πατερας]{.greek-abbr} αυτου και [ειδεν]{.greek-omitted} [ειδε]{.greek-added} διαφθοραν[13:36]{.aside}

ον δε ο [θεος]{.greek-abbr} ηγειρεν ουκ [ειδεν]{.greek-omitted} [ειδε]{.greek-added} διαφθοραν[13:37]{.aside}

γνωστον ουν εστω υμιν [ανδρες]{.greek-omitted} [πασιν]{.greek-added} αδελφοι οτι δια τουτου υμιν αφεσις αμαρτιων καταγγελλεται [και]{.greek-added} [απο]{.greek-added} [παντων]{.greek-added} [ων]{.greek-added} [ουκ]{.greek-added} [ηδυνηθητε]{.greek-added} [εν]{.greek-added} [τω]{.greek-added} [νομω]{.greek-added} [μωσεως]{.greek-added} [δικαιωθηναι]{.greek-added}[13:38]{.aside}

[και]{.greek-omitted} [απο]{.greek-omitted} [παντων]{.greek-omitted} [ων]{.greek-omitted} [ουκ]{.greek-omitted} [ηδυνηθητε]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [νομω]{.greek-omitted} [μωυσεως]{.greek-omitted} [δικαιωθηναι]{.greek-omitted} εν τουτω πας ο πιστευων δικαιουται [παρα]{.greek-added} [τω]{.greek-added} [[θεω]{.greek-abbr}]{.greek-added}[13:39]{.aside}

βλεπετε [ουν]{.greek-omitted} [δε]{.greek-added} μη επελθη εφ υμας το ειρημενον εν τοις προφηταις[13:40]{.aside}

ιδετε οι καταφρονηται [και]{.greek-added} [επιβλεψατε]{.greek-added} και θαυμασατε και αφανισθητε οτι εργον εγω εργαζομαι εν ταις [ημεραις]{.greek-omitted} [ημερας]{.greek-added} υμων [ο]{.greek-omitted} [ω]{.greek-added} ου μη πιστευσητε εαν τις εκδιηγηται υμιν[13:41]{.aside}

εξιοντων δε εκ της συναγωγης των ιουδαιων παρεκαλουν τα εθνη εις [το]{.corr} μεταξυ σαββατον λαληθηναι αυ[τ]{.unclear}[οις]{.greek-supplied} τα ρηματα [ταυτα]{.greek-added}[13:42]{.aside}

λυθεισης δε της συναγωγης ηκολουθησαν πολλοι των ιουδαιων και των σεβομενω[ν]{.greek-supplied} προσηλυτων τω παυλω και τω βαρναβα [αξιουν[ε]{.unclear}[ς]{.greek-supplied}]{.greek-added} [βαπτισθηναι]{.greek-added} οιτινες προσλαλουντες επειθ[ον]{.greek-supplied} αυτους [επιμενειν]{.greek-omitted} [προσμενειν]{.greek-added} τη χαριτι του [θεου]{.greek-abbr}[13:43]{.aside}

τω [τε]{.greek-omitted} [δε]{.greek-added} ερ[χ]{.unclear}[ο]{.greek-supplied}μενω σαββατω σχεδον πασα η πολις [συνηχθη]{.greek-omitted} [συνη[χ]{.unclear}[θη]{.greek-supplied}σαν]{.greek-added} ακουσαι τον λογον του [θεου]{.greek-abbr}[13:44]{.aside}

ιδοντες δε οι ι[ου]{.greek-supplied}δαιοι τους οχλους επλησθησαν ζηλου και αντ[ε]{.unclear}[λε]{.greek-supplied}γον τοις υπο [του]{.greek-omitted} παυλου λεγομενοις αντιλεγοντες [και]{.greek-supplied} βλασφημουντες[13:45]{.aside}

παρρησιασαμενοι δε ο παυλος κα[ι]{.greek-supplied} [ο]{.greek-supplied} βαρναβας ειπον υμιν ην αναγκαιον πρωτον λ[α]{.unclear}[λη]{.greek-supplied}θηναι τον λογον του [θεου]{.greek-abbr} επειδη δε [απωθεισθε]{.greek-omitted} [αποθεισθε]{.greek-added} [α]{.unclear}[υ]{.greek-supplied}τον και ουκ αξιους κρινετε εαυτους της αιωνιου ζ[ω]{.unclear}[ης]{.greek-supplied} ιδου στρεφομεθα εις τα εθνη[13:46]{.aside}

ουτως γαρ [ημιν]{.greek-added} εντεταλ[ται]{.greek-supplied} [ημιν]{.greek-omitted} [ο]{.greek-supplied} [κυριος]{.greek-abbr} τεθεικα σε εις φως εθνων του ειναι σε εις [σωτηριαν]{.greek-abbr} [εως]{.greek-supplied} εσχατου της γης[13:47]{.aside}

ακουοντα δε τα εθνη [εχαιρεν]{.greek-omitted} [εχαιρον]{.greek-added} κα[ι]{.greek-supplied} [ε]{.greek-supplied}δοξαζον τον [λογον]{.greek-omitted} [[θεον]{.greek-abbr}]{.greek-added} [και]{.greek-added} [επιστευσαν]{.greek-added} [τω]{.greek-added} [λογω]{.greek-added} του [κυριου]{.greek-abbr} [και]{.greek-omitted} [επιστευσαν]{.greek-omitted} οσοι ησαν [τε]{.greek-supplied}ταγμενοι εις ζωην αιωνιον[13:48]{.aside}

διεφερετο δε ο λογος [του]{.greek-supplied} [κυριου]{.greek-abbr} δι ολης της χωρας[13:49]{.aside}

οι δε ιουδαιοι παρωτρυν[α]{.unclear}[ν]{.greek-supplied} τας σεβομενας γυναικας και τας ευσχημ[ονας]{.greek-supplied} και τους πρωτους της πολεως και επηγειραν διωγμον ε[π]{.unclear}[ι]{.greek-supplied} τον παυλον και τον βαρναβαν και εξεβαλον αυτους απ[ο]{.unclear} [των]{.greek-supplied} οριων αυτων[13:50]{.aside}

οι δε εκτιναξαμενοι τον κονιορτον τω[ν]{.unclear} ποδων αυτων επ αυτους ηλθον εις ικονιον[13:51]{.aside}

οι δε μαθηται επληρουντο χαρας και [πνευματος]{.greek-abbr} αγιου[13:52]{.aside}

### Chapter 14

εγενετο δε [ε]{.unclear}ν ικονιω κατα το αυτο εισελθειν αυτους εις την συναγω[γ]{.greek-supplied}ην των ιουδαιων και λαλησαι ουτως ωστε πιστευσαι [ι]{.unclear}ουδαιων τε και ελληνων πολυ πληθος[14:1]{.aside}

οι δε απειθουντες ιουδαιοι επηγειραν [διωγμον]{.greek-added} και εκακωσαν τας ψυχας των εθνων κατα των αδελφων[14:2]{.aside}

ικανον μεν ουν χρονον διετριψαν παρρησιαζομενοι επι τω [κυριω]{.greek-abbr} τω μαρτυρουντι τω λογω της χαριτος αυτου διδοντι σημεια και τερατα γινεσθαι δια των χειρων αυτων[14:3]{.aside}

εσχισθη δε το πληθος της πολεως και οι μεν ησαν συν τοις ιουδαιοις οι δε συν τοις αποστολοις[14:4]{.aside}

ως δε εγενετο ορμη των εθνων τε και ιουδαιων συν τοις αρχουσιν αυτων υβρισαι και [λιθοβολησαι]{.greek-omitted} [λιθοβολισαι]{.greek-added} αυτους[14:5]{.aside}

συνιδοντες κατεφυγον [ε]{.unclear}ις τας πολεις της λυκαονιας λυστραν και δερβην και την περιχωρον[14:6]{.aside}

κακει [ευαγγελιζομενοι]{.greek-added} ησαν [ευαγγελιζομενοι]{.greek-omitted}[14:7]{.aside}

και τις ανηρ εν λυστροις [εκαθητο]{.greek-added} αδυνατος τοις [ποσιν]{.greek-omitted} [ποσι]{.greek-added} [εκαθητο]{.greek-omitted} χωλος [ετι]{.greek-added} εκ κοιλιας [μητρος]{.greek-abbr} αυτου [υπαρχων]{.greek-omitted} ος ουδεποτε περιπεπατηκει[14:8]{.aside}

ουτος [ηκουσεν]{.greek-omitted} [ηκουσε]{.greek-added} του παυλου [λαλουντος]{.greek-omitted} [λεγοντος]{.greek-added} ος ατενισας αυτω και ιδων οτι πιστιν εχει του σωθηναι[14:9]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} μεγαλη τη φωνη [σοι]{.greek-added} [λεγω]{.greek-added} [εν]{.greek-added} [τω]{.greek-added} [ονοματι]{.greek-added} [του]{.greek-added} [[κυριου]{.greek-abbr}]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} [[χριστου]{.greek-abbr}]{.greek-added} αναστηθι επι τους ποδας [σου]{.greek-omitted} [ου]{.greek-added} [ορθως]{.greek-omitted} [ορθος]{.greek-added} και [ηλλετο]{.greek-omitted} [ειλλετο]{.greek-added} και περιεπατει[14:10]{.aside}

οι δε οχλοι ιδοντες ο εποιησεν ο παυλος επηραν [αυτων]{.greek-added} την φωνην [αυτων]{.greek-omitted} λυκαονιστι λεγοντες οι θεοι ομοιωθεντες [ανθρωποις]{.greek-abbr} κατεβησαν προς ημας[14:11]{.aside}

εκ[α]{.greek-supplied}λουν τε τον μεν βαρναβαν δια τον δε παυλον ερμην [ε]{.unclear}πειδη αυτος ην ο ηγουμενος του λογου[14:12]{.aside}

ο δε ιερευς τ[ου]{.greek-supplied} διος του οντος προ της πολεως αυτων ταυρους και στεμ[μ]{.unclear}[ατα]{.greek-supplied} επι τους πυλωνας ενεγκας συν τοις οχλοις ηθε[λ]{.unclear}[εν]{.greek-supplied} θυειν[14:13]{.aside}

ακουσαντες δε οι αποστολοι βαρναβας και παυ[λος]{.greek-supplied} διαρρηξαντες τα ιματια αυτων εισεπηδησαν εις τον ο[χ]{.unclear}[λον]{.greek-supplied} κραζοντες[14:14]{.aside}

και λεγοντες ανδρες τι ταυτα ποιειτε κα[ι]{.greek-supplied} [η]{.greek-supplied}μεις ομοιοπαθεις [υμιν]{.greek-added} εσμεν [υμιν]{.greek-omitted} [ανθρωποι]{.greek-abbr} ευαγγελιζομεν[οι]{.greek-supplied} υμας απο [τουτων]{.greek-omitted} των ματαιων [τουτων]{.greek-added} επιστρεφειν επ[ι]{.greek-supplied} [τον]{.greek-omitted} [θεον]{.greek-abbr} τον ζωντα ος εποιησεν τον [ουρανον]{.greek-abbr} και την γην και [την]{.greek-supplied} θαλασσαν και παντα τα εν αυτοις[14:15]{.aside}

ος εν ταις παρ[ω]{.greek-supplied}χημεναις γενεαις [ειασεν]{.greek-omitted} [ειασε]{.greek-added} παντα τα εθνη πορευε[σθαι]{.greek-supplied} ταις οδοις αυτων[14:16]{.aside}

καιτοιγε ουκ αμαρτυρον εαυτο[ν]{.unclear} αφηκεν αγαθοποιων [ουρανοθεν]{.greek-abbr} [υμιν]{.greek-omitted} [ημιν]{.greek-added} [διδους]{.greek-added} υετους [διδους]{.greek-omitted} και καιρους καρποφορους εμπιπλων τροφης και ευφροσυνης τας καρδιας ημων[14:17]{.aside}

και ταυτα λεγοντες μ[ολις]{.greek-supplied} κατεπαυσαν τους οχλους του μη θυειν αυτοις [αλλ[α]{.greek-supplied}]{.greek-added} [πορευεσθαι]{.greek-added} [εκαστον]{.greek-added} [εις]{.greek-added} [τα]{.greek-added} [ιδια]{.greek-added}[14:18]{.aside}

επηλθον δε [και]{.greek-added} α[π]{.unclear}[ο]{.greek-supplied} αντιοχειας και ικονιου ιουδαιοι και πεισαντες του[ς]{.unclear} οχλους και λιθασαντες τον παυλον εσυρον εξω της πολεως νομισαντες αυτον τεθναναι[14:19]{.aside}

κυκλ[ω]{.greek-supplied}σαντων δε [αυτον]{.greek-omitted} των μαθητων [αυτον]{.greek-added} αναστας εισηλθεν [εις]{.greek-omitted} [εν]{.greek-added} τη[ν]{.unclear} [π]{.unclear}[ολιν]{.greek-supplied} και τη επαυριον εξηλθεν συν τω βαρναβα εις δερβην[14:20]{.aside}

ευαγγελισαμενοι τε την πολιν εκεινην και μαθητευσαντες ικανους υπεστρεψαν εις την λυστραν και ικονιον και αντιοχειαν[14:21]{.aside}

επιστηριζοντες τας ψυχας των μαθητων [και]{.greek-added} παρακαλουντες εμμενειν τη πιστει και οτι δια πολλων θλιψεων δει ημας εισελθειν εις την βασιλειαν του [θεου]{.greek-abbr}[14:22]{.aside}

χειροτονησαντες δε αυτοις πρεσβυτερους κατ εκκλησιαν [και]{.greek-added} προσευξαμενοι μετα νηστειων παρεθεντο αυτους τω [κυριω]{.greek-abbr} εις ον [και]{.greek-added} [πεπιστευκεισαν]{.greek-omitted} [πεπιστευκασι]{.greek-added}[14:23]{.aside}

και διελθοντες την πισιδιαν ηλθον εις παμφυλιαν[14:24]{.aside}

και λαλησαντες εν περγη τον λογον [του]{.greek-added} [[κυριου]{.greek-abbr}]{.greek-added} κατεβησαν εις ατταλειαν [ευαγγελιζομενοι]{.greek-added} [αυτης]{.greek-added}[14:25]{.aside}

κακειθεν απεπλευσαν εις αντιοχειαν οθεν ησαν παραδε[δ]{.unclear}ομενοι τη [χαριτι]{.greek-omitted} [χαριτη]{.greek-added} του [θεου]{.greek-abbr} εις το εργον ο επληρωσαν[14:26]{.aside}

παραγενομενοι δε και συναγαγοντες την εκκλησιαν ανηγγειλαν οσα εποιησεν ο [θεος]{.greek-abbr} μετ αυτων και οτι [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} τοις εθνεσιν θυραν πιστεως[14:27]{.aside}

διετριβον δε εκει χρονον ουκ ολιγον συν τοις μαθηταις[14:28]{.aside}

### Chapter 15

και τινες κατελθοντες απο της ιουδαιας [των]{.greek-added} [πεπιστευκοτων]{.greek-added} [απο]{.greek-added} [της]{.greek-added} [αιρεσεως]{.greek-added} [των]{.greek-added} [φαρισαιων]{.greek-added} εδιδασκον τους αδελφους οτι εαν μη περιτεμνησθε τω εθει [μωυσεως]{.greek-omitted} [μωσεως]{.greek-added} ου δυνασθε σωθηναι[15:1]{.aside}

γενομενης [ουν]{.greek-omitted} [δε]{.greek-added} στασεως και ζητησεως ουκ ολιγης τω παυλω και τω βαρναβα προς αυτους εταξαν αναβαινειν παυλον και βαρναβαν και τινας αλλους εξ αυτων προς τους αποστολους και πρεσβυτερους εις [ιερουσαλημ]{.greek-abbr} περι [του]{.greek-supplied} ζητηματος τουτου [οπως]{.greek-added} [κριθωσιν]{.greek-added} [επ]{.greek-added} [αυτοις]{.greek-added}[15:2]{.aside}

οι μ[ε]{.unclear}[ν]{.greek-supplied} ουν προπεμφθεντες υπο της εκκλησιας διηρχοντο τ[η]{.unclear}[ν]{.greek-supplied} [[τε]{.greek-supplied}]{.greek-added} φοινικην και [την]{.greek-added} σαμαρειαν εκδιηγουμενοι την επιστρο[φην]{.greek-supplied} των εθνων και εποιουν χαραν μεγαλην [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις [α]{.greek-supplied}δελφοις[15:3]{.aside}

παραγενομενοι δε εις [ιερουσαλημ]{.greek-omitted} [ιεροσολυμαν]{.greek-added} απεδεχ[θ]{.unclear}[η]{.greek-supplied}σαν [μεγαλως]{.greek-added} υπο της εκκλησιας και των αποστολων κα[ι]{.unclear} [των]{.greek-supplied} πρεσβυτερων ανηγγειλαν τε οσα [εποιησεν]{.greek-added} ο [θεος]{.greek-abbr} [εποιησεν]{.greek-omitted} μετ α[υ]{.unclear}[των]{.greek-supplied} [και]{.greek-added} [οτι]{.greek-added} [οινοιξε]{.greek-added} [τοις]{.greek-added} [εθνεσι]{.greek-added} [θυραν]{.greek-added} [πιστεως]{.greek-added}[15:4]{.aside}

εξαν[ε]{.unclear}[στησαν]{.greek-supplied} [δε]{.greek-supplied} τινες των απο της αιρεσεως των φαρισαιων πεπιστευκοτες λεγοντες οτι δει περιτεμνειν αυτους παραγγελλ[ειν]{.greek-supplied} τε τηρειν τον νομον [μωυσεως]{.greek-omitted} [μωσεως]{.greek-added}[15:5]{.aside}

συνηχθησαν δε οι αποστ[ο]{.unclear}[λοι]{.greek-supplied} και οι πρεσβυτεροι [συν]{.greek-added} [τω]{.greek-added} [πληθει]{.greek-added} ιδειν περι του λ[ο]{.greek-supplied}γου τουτου[15:6]{.aside}

πολλης δε [συζητησεως]{.greek-omitted} [συνζητησεως]{.greek-added} γενομενης αν[α]{.greek-supplied}στας πετρος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} προς αυτους ανδρες αδελφοι [υ]{.greek-supplied}μεις επιστασθε οτι αφ ημερων αρχαιων [εν]{.greek-added} [ημιν]{.greek-added} [ο]{.greek-supplied} [θεος]{.greek-abbr} [εν]{.greek-omitted} [ημιν]{.greek-omitted} εξελεξατο δια του στοματος μου ακουσαι τα εθνη τ[ο]{.unclear}[ν]{.greek-supplied} λογον του ευαγγελιου και πιστευσαι[15:7]{.aside}

και ο καρδιογνωστης [θεος]{.greek-abbr} εμαρτυρησεν αυτοις δους αυτοις το [πνευμα]{.greek-abbr} το αγιον κ[α]{.greek-supplied}θως και ημιν[15:8]{.aside}

και [ουδεν]{.greek-omitted} [ουθεν]{.greek-added} [διεκρινεν]{.greek-omitted} [διεκρινε]{.greek-added} μεταξυ ημ[ων]{.greek-supplied} τε και [αυτων]{.greek-omitted} [αυτον]{.greek-added} τη πιστει καθαρισας τας καρδια[ς]{.unclear} αυτων[15:9]{.aside}

νυν ουν τι πειραζετε τον [θεον]{.greek-abbr} επιθειναι ζ[υ]{.greek-supplied}γον επι τον τραχηλον των μαθητων ον ουτε οι [πατερες]{.greek-abbr} [ημων]{.greek-omitted} [ουτε]{.greek-omitted} [ημεις]{.greek-omitted} [ισχυσαμεν]{.greek-omitted} [βαστασαι]{.greek-omitted}[15:10]{.aside}

[οι]{.greek-omitted} [μεν]{.greek-omitted} [ουν]{.greek-omitted} [απολυθεντες]{.greek-omitted} [ηλθον]{.greek-omitted} [εις]{.greek-omitted} [αντιοχειαν]{.greek-omitted} [και]{.greek-omitted} [συναγαγοντες]{.greek-omitted} [το]{.greek-omitted} [πληθος]{.greek-omitted} [επεδωκαν]{.greek-omitted} [πεδωκαν]{.greek-added} την επιστολην[15:30]{.aside}

αναγνοντες δε εχαρησαν επι τη παρακλησει[15:31]{.aside}

ιουδας τε και σιλας και αυτοι προφηται οντες δια λογου πολλου παρεκαλεσαν τους αδελφους και επεστηριξαν[15:32]{.aside}

ποιησαντες δε χρονον απελυθησαν μετ ειρηνης απο των αδελφων προς τους αποστολους[15:33]{.aside}

[εδοξε]{.greek-added} [δε]{.greek-added} [τω]{.greek-added} [σιλα]{.greek-added} [εποιμειναι]{.greek-added} [αυτου]{.greek-added}[15:34]{.aside}

παυλος δε και βαρναβας διετριβον εν αντιοχεια διδασκοντες και ευαγγελιζομενοι μετα και ετερων πολλων τον λογον του [κυριου]{.greek-abbr}[15:35]{.aside}

μετα δε τινας ημερας [ειπεν]{.greek-omitted} [ειπε]{.greek-added} παυλος προς βαρναβαν επιστρεψαντες δη επισκεψωμεθα τους αδελφους [ημων]{.greek-omitted} [τους]{.greek-added} κατα πασαν πολιν εν αις κατηγγειλαμεν τον λογον του [κυριου]{.greek-abbr} πως [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added}[15:36]{.aside}

βαρναβας δε εβουλευσατο συμπαραλαβειν [τον]{.greek-omitted} ιωαννην τον [καλουμενον]{.greek-omitted} [επικαλουμενον]{.greek-added} μαρκον[15:37]{.aside}

παυλος δε ηξιου τον αποσταντ[α]{.unclear} α[π]{.unclear} αυτων απο παμφυλιας και μη συνελθοντα αυτοις εις το εργον μη [συμπαραλαβειν]{.greek-omitted} [συμπαραλαμβανειν]{.greek-added} τουτον[15:38]{.aside}

εγενετο [ουν]{.greek-omitted} [γουν]{.greek-added} παροξυσμος ωστε αποχωρισθηναι αυτους απ αλληλων τον τε βαρναβαν παραλαβοντα τον μαρκον εκπλευσαι εις κυπρον[15:39]{.aside}

παυλος δε επιλεξαμενος σιλαν εξηλθεν παραδοθεις τη χαριτι του [θεου]{.greek-abbr} υπο των αδελφων[15:40]{.aside}

διηρχετο δε την συριαν και κιλικιαν επιστηριζων τας εκκλησιας[15:41]{.aside}

### Chapter 16

[κατηντησεν]{.greek-omitted} [κατηντησε]{.greek-added} δε εις δερβην και λυστραν και ιδου μαθητης τις ην εκει ονοματι τιμοθεος υιος γυναικος [τινος]{.greek-omitted} ιουδαιας πιστης [πατρος]{.greek-abbr} δε ελληνος[16:1]{.aside}

ος εμαρτυρειτ[ο]{.unclear} υπο των εν λυστροις και ικονιω αδελφων[16:2]{.aside}

τουτον [ηθ]{.unclear}[ε]{.greek-supplied}λησεν ο παυλος συν αυτω εξελθειν και [λαβων]{.greek-omitted} [ελαβεν]{.greek-added} [και]{.greek-added} [πε]{.greek-supplied}ριετεμεν αυτον δια τους ιουδαιους τους οντας εν τοις τ[οπ]{.unclear}[οις]{.greek-supplied} [εκεινοις]{.greek-omitted} [εκεινης]{.greek-added} ηδεισαν γαρ [απαντες]{.greek-omitted} τον [πατερα]{.greek-abbr} αυτου [απαντες]{.greek-added} οτι ελλην υπηρχεν[16:3]{.aside}

ως δε διεπορευοντο τας πολ[εις]{.greek-supplied} παρεδιδουν αυτοις φυλασσειν τα δογματα τα κεκ[ρι]{.greek-supplied}μενα υπο των αποστολων και [των]{.greek-omitted} πρεσβυτερων των ε[ν]{.greek-supplied} [ιερουσαλημ]{.greek-omitted} [[[ι]{.greek-supplied}]{.greek-abbr}]{.greek-added}[16:4]{.aside}

αι μεν ουν εκκλησιαι εστερεουντο τη πιστει και ε[πε]{.greek-supplied}ρισσευον τω αριθμω καθ ημεραν[16:5]{.aside}

[διελθοντες]{.greek-omitted} [διηλθοντες]{.greek-added} δε [τ]{.unclear}[ην]{.greek-supplied} φρυγιαν και την γαλατικην χωραν [και]{.greek-added} κωλυθεντες υ[πο]{.greek-supplied} του αγιου [πνευματος]{.greek-abbr} λαλησαι τον λογον εν τη ασια[16:6]{.aside}

ελθ[ον]{.greek-supplied}τες κατα την μυσιαν επειραζον [κατα]{.greek-omitted} [εις]{.greek-added} την βιθυ[ν]{.unclear}[ιαν]{.greek-supplied} πορευεσθαι και ουκ ειασεν αυτους το [πνευμα]{.greek-abbr}[16:7]{.aside}

παρ[ε]{.unclear}[λ]{.greek-supplied}θοντες δε την μυσιαν κατεβησαν εις τρωαδα[16:8]{.aside}

κ[αι]{.greek-supplied} οραμα δια της νυκτος ωφθη τω παυλω ανηρ τι[ς]{.unclear} ην μακεδων εστως [κατα]{.greek-added} [προσωπον]{.greek-added} [αυτου]{.greek-added} [και]{.greek-added} παρ[α]{.unclear}καλων αυτον και λεγων διαβας εις μακεδονια[ν]{.greek-supplied} βοηθησον ημιν[16:9]{.aside}

ως δε το οραμα ειδεν ευθεω[ς]{.greek-supplied} εζητησαμεν [εις]{.greek-added} [μακεδονιαν]{.greek-added} εξελθειν [εις]{.greek-omitted} [την]{.greek-omitted} [μακεδονιαν]{.greek-omitted} συμβ[ιβα]{.greek-supplied}ζοντες οτι [προσκεκληται]{.greek-omitted} [προσκεκληκεν]{.greek-added} ημας ο [κυριος]{.greek-abbr} ευαγγ[ε]{.unclear}[λι]{.greek-supplied}σασθαι αυτους[16:10]{.aside}

[τη]{.greek-added} [δε]{.greek-added} [επαυριον]{.greek-added} αναχθεντ[ες]{.greek-supplied} [ουν]{.greek-omitted} απο [της]{.greek-omitted} τρωαδος ευθυδρομησαμεν εις [σαμοθρακην]{.greek-omitted} [σαμ[ο]{.unclear}[θρα]{.greek-supplied}]{.greek-added} [κην]{.greek-added} τη τε επιουση εις νεαπολιν[16:11]{.aside}

εκειθεν [τε]{.greek-omitted} [δε]{.greek-added} εις φιλιππους ητις [εστιν]{.greek-omitted} [εστι]{.greek-added} πρωτη της μεριδος της μακεδονιας πολις κολωνεια ημεν δε εν [αυτη]{.greek-omitted} τη πολει [ταυτη]{.greek-added} διατριβοντες ημερας τινας[16:12]{.aside}

τη [τε]{.greek-omitted} [δε]{.greek-added} ημερα των σαββατων εξηλθομεν εξω της πολεως παρα ποταμον ου ενομιζετο προσευχη ειναι και καθισαντες ελαλουμεν ταις συνελθουσαις [γυναιξιν]{.greek-omitted} [γυναιξι]{.greek-added}[16:13]{.aside}

και τις γυνη ονοματι λυδια πορφυροπωλις πολεως θυατειρων σεβομενη τον [θεον]{.greek-abbr} [ηκουεν]{.greek-omitted} [ηκουσεν]{.greek-added} ης ο [κυριος]{.greek-abbr} [διηνοιξεν]{.greek-omitted} [διηνοιξε]{.greek-added} την καρδιαν προσεχειν τοις λαλουμενοις υπο του παυλου[16:14]{.aside}

ως δε εβαπτισθη και ο οικος αυτης [παρεκαλεσεν]{.greek-omitted} [παρεκαλεσε]{.greek-added} λεγουσα ει κεκρικατε με [π]{.unclear}ιστην [ειναι]{.greek-added} τω [κυριω]{.greek-abbr} [ειναι]{.greek-omitted} εισελθοντες εις τον οικον μου μεινατε και παρεβιασατο ημας[16:15]{.aside}

εγενετο δε πορευομενων ημων εις προσευχην παιδισκην τινα εχουσαν [πνευμα]{.greek-abbr} πυθωνος απαντησαι ημιν ητις εργασιαν πολλην [παρειχεν]{.greek-omitted} [παρειχε]{.greek-added} τοις κυριοις αυτης μαντευομενη[16:16]{.aside}

αυτη κατακολουθησασα τω παυλω και ημιν [εκραζεν]{.greek-omitted} [εκραζε]{.greek-added} λεγουσα ουτοι οι [ανθρωποι]{.greek-abbr} δουλοι του [θεου]{.greek-abbr} του υψιστου εισιν οιτινες καταγγελλουσιν ημιν οδον [σωτηριας]{.greek-abbr}[16:17]{.aside}

τουτο δε εποιει επι πολλας ημερας διαπονηθεις δε ο παυλος και επιστρεψας τω [πνευματι]{.greek-abbr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [παραγγελλω]{.greek-omitted} [παραγγελω]{.greek-added} σοι εν τω ονοματι [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} εξελθειν απ αυτης και εξηλθεν αυτη τη ωρα[16:18]{.aside}

ιδοντες δε οι κυριοι αυτης οτι εξηλθεν η ελπις της εργασιας αυτων επιλαβομενοι τον παυλον και τον σιλαν ειλκυσαν εις την αγοραν επι τους αρχοντας[16:19]{.aside}

και προσαγαγοντες αυτους τοις στρατηγοις ειπον ουτοι οι [ανθρωποι]{.greek-abbr} [εκταρασσουσιν]{.greek-omitted} [εκταρασουσιν]{.greek-added} ημων την πολιν ιουδαιοι υπαρχοντες[16:20]{.aside}

και [καταγγελλουσιν]{.greek-omitted} [καταγγελουσιν]{.greek-added} εθη α ουκ εξεστιν ημιν παραδεχεσθαι ουδε ποιειν ρωμαιοις [ουσιν]{.greek-omitted} [ουσι]{.greek-added}[16:21]{.aside}

και συνεπεστη ο οχλος κατ αυτων και οι στρατηγοι περιρρηξαντες αυτων τα ιματια [εκελυον]{.greek-added} [εκελευον]{.corr} ραβδιζειν[16:22]{.aside}

πολλας τε επιθεντες αυτοις πληγας εβαλον εις φυλακην παραγγειλαντες τω δεσμοφυλακι ασφαλως τηρειν αυτους[16:23]{.aside}

ος παραγ[γ]{.unclear}[ε]{.greek-supplied}λιαν τοιαυτην ειληφως εβαλεν αυτους εις την [εσωτεραν]{.greek-omitted} [εσοτεραν]{.greek-added} φυλακην και τους ποδας αυτων ησφαλισατο εις το ξυλον[16:24]{.aside}

κατα δε το μεσονυκτιον παυλος και σιλας προσευχομενοι υμνουν τον [θεον]{.greek-abbr} επηκροωντο δε αυτων οι δεσμιοι[16:25]{.aside}

αφνω δε σεισμος εγενετο μεγας ωστε σαλευθηναι τα θεμελια του δεσμωτηριου ανεωχθησαν [τε]{.greek-omitted} [δε]{.greek-added} παραχρημα αι θυραι πασαι και παντων τα δεσμα [ανεθη]{.greek-omitted} [ανειθη]{.greek-added}[16:26]{.aside}

εξυπνος δε γενομενος ο δεσμοφυλαξ [ο]{.greek-added} [πιστος]{.greek-added} [στεφανας]{.greek-added} και ιδων ανεωγμενας τας θυρας της φυλακης σπασαμενος [μα]{.greek-added} [μαχαιραν]{.greek-omitted} [χαιραν]{.greek-added} εμελλεν εαυτον αναιρειν νομιζων εκπεφευγεναι τους δεσμιους[16:27]{.aside}

[εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added} δε φωνη μεγαλη ο παυλος λεγων μηδεν πραξης σεαυτω κακον απαντες γαρ εσμεν ενθαδε[16:28]{.aside}

αιτησας δε φωτα [εισεπηδησεν]{.greek-omitted} [εισεπηδησε]{.greek-added} και εντρομος γενομενος [προσεπεσεν]{.greek-omitted} [προσεπεσε]{.greek-added} τω παυλω και τω σιλα[16:29]{.aside}

και προαγαγων αυτους εξω εφη κυριοι τι [δει]{.greek-added} με [δει]{.greek-omitted} ποιειν ινα σωθω[16:30]{.aside}

οι δε ειπον πιστευσον επι τον [κυριον]{.greek-abbr} [ιησουν]{.greek-abbr} [χριστον]{.greek-abbr} και [σωθηση]{.greek-omitted} [σωθησει]{.greek-added} συ και ο οικος σου[16:31]{.aside}

και ελαλησαν αυτω τον λογον του [κυριου]{.greek-abbr} και [πασιν]{.greek-omitted} [παση]{.greek-added} τοις εν τη οικια αυτου[16:32]{.aside}

και παραλαβων αυτους εν εκεινη τη ωρα της νυκτος ελουσεν απο των πληγων και εβαπτισθη αυτος και οι αυτου [παντες]{.greek-omitted} [απαντες]{.greek-added} παραχρημα[16:33]{.aside}

αναγαγων τε αυτους εις τον οικον αυτου παρεθηκεν τραπεζαν και [ηγαλλιατο]{.greek-omitted} [ηγαλλιασατο]{.greek-added} πανοικι πεπιστευκως τω [θεω]{.greek-abbr}[16:34]{.aside}

ημερας δε γενομενης [απεστειλαν]{.greek-omitted} [απεσταλκασιν]{.greek-added} οι στρατηγοι τους ραβδουχους λεγοντες απολυσον τους [ανθρωπους]{.greek-abbr} εκεινους [ους]{.greek-added} [χθες]{.greek-added} [παρελαβες]{.greek-added}[16:35]{.aside}

[απηγγειλεν]{.greek-omitted} [απηγγειλε]{.greek-added} δε ο δεσμοφυλαξ τους λογους τουτους προς τον παυλον οτι απεσταλκασιν οι στρατηγοι ινα απολυθητε νυν ουν εξελθοντες [πορευεσθε]{.greek-omitted} [πορεβεσθε]{.greek-added} εν ειρηνη[16:36]{.aside}

ο δε παυλος εφη προς αυτους δειραντες ημας δημοσια ακατακριτους [ανθρωπους]{.greek-abbr} ρωμαιους υπαρχοντας εβαλον εις φυλακην και [νυν]{.greek-omitted} [λαθρα]{.greek-omitted} [αλαλαθρα]{.greek-added} ημας εκβαλλουσιν ου γαρ αλλα ελθοντες αυτοι εξαγαγετωσαν [ημας]{.greek-added}[16:37]{.aside}

[ανηγγειλαν]{.greek-omitted} [απηγγειλαν]{.greek-added} δε τοις στρατηγοις οι ραβδουχοι τα ρηματα ταυτα και εφοβηθησαν ακουσαντες οτι ρωμαιοι [εισιν]{.greek-omitted} [εισι]{.greek-added}[16:38]{.aside}

και ελθοντες [εις]{.greek-added} [την]{.greek-added} [φυλακην]{.greek-added} παρεκαλεσαν αυτους [εξελθειν]{.greek-added} [ειποντες]{.greek-added} [ηγνωησαμεν]{.greek-added} [τα]{.greek-added} [καθ]{.greek-added} [ημας]{.greek-added} [οτι]{.greek-added} [εστε]{.greek-added} [ανδρες]{.greek-added} [δικαιοι]{.greek-added} και [εκ]{.greek-added} [ταυτης]{.greek-added} [εξαγαγοντες]{.greek-omitted} [ηρωτων]{.greek-omitted} [εξελθειν]{.greek-omitted} της πολεως [εξελθετε]{.greek-added} [μη]{.greek-added} [πως]{.greek-added} [επιστραφωσι]{.greek-added} [παλιν]{.greek-added} [οι]{.greek-added} [επικραξαντες]{.greek-added} [καθ]{.greek-added} [υμων]{.greek-added}[16:39]{.aside}

εξελθοντες δε εκ της φυλακης εισηλθον προς την λυδιαν και ιδοντες τους αδελφους παρεκαλεσαν αυτους και εξηλθον[16:40]{.aside}

### Chapter 17

διοδευσαντες δε την αμφιπολιν και απολλωνιαν ηλθον εις θεσσαλονικην οπου ην η [συναγωγη]{.greek-omitted} [συναγωγοι]{.greek-added} των ιουδαιων[17:1]{.aside}

κατα δε το ειωθος τω παυλω [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} προς αυτους και επι σαββατα τρια [διελεξατο]{.greek-omitted} [διηλεχθη]{.greek-added} αυτοις [απο]{.greek-omitted} [υπο]{.greek-added} των γραφων[17:2]{.aside}

διανοιγων και παρατιθεμενος [αυτοις]{.greek-added} οτι τον [χριστον]{.greek-abbr} εδει παθειν και αναστηναι εκ νεκρων και οτι ουτος εστιν [ο]{.greek-omitted} [[ιησους]{.greek-abbr}]{.greek-added} [χριστος]{.greek-abbr} [ιησους]{.greek-omitted} ον εγω [καταγγελλω]{.greek-omitted} [καταγγελω]{.greek-added} υμιν[17:3]{.aside}

και τινες εξ αυτων [επεισθησαν]{.greek-omitted} [επιστευσαν]{.greek-added} και προσεκληρωθησαν τω παυλω και τω σιλα των τε σεβομενων ελληνων [πληθος]{.greek-added} πολυ [πληθος]{.greek-omitted} γυναικων τε των πρωτων ουκ ολιγαι[17:4]{.aside}

[προσλαβομενοι]{.greek-omitted} [ζηλωσαντες]{.greek-added} δε οι ιουδαιοι [και]{.greek-added} [προσλαβομενοι]{.greek-added} οι απειθουντες των αγοραιων τινας ανδρας πονηρους και οχλοποιησαντες εθορυβουν την πολιν επ[ι]{.greek-supplied}σταντες τε τη οικια [ιασονος]{.greek-omitted} [ιασωνος]{.greek-added} εζητουν αυτους [αγαγειν]{.greek-omitted} [προαγαγειν]{.greek-added} εις τον δημον[17:5]{.aside}

μη ευροντες δε αυτους εσυρον τ[ο]{.unclear}[ν]{.greek-supplied} [ιασονα]{.greek-omitted} [ιασωνα]{.greek-added} και τινας αδελφους επι τους πολιταρχας βοωντες οτι οι την οικουμενην αναστατωσαντες ουτοι και ενθαδε παρεισιν[17:6]{.aside}

ους υποδεδεκται ιασων και ουτοι παντες απεναντι των δογματων καισαρος πρασσουσιν βασιλεα λεγοντες ετερον ειναι [ιησουν]{.greek-abbr}[17:7]{.aside}

εταραξαν δε τον οχλον και τους πολιταρχας ακουοντας ταυτα[17:8]{.aside}

και λαβοντες το ικανον παρα του [ιασονος]{.greek-omitted} [ιασωνος]{.greek-added} και των λοιπων απελυσαν αυτους[17:9]{.aside}

οι δε αδελφοι ευθεως δια της νυκτος εξεπεμψαν τον [τε]{.greek-omitted} παυλον και τον σιλαν εις [βεροιαν]{.greek-omitted} [βερροιαν]{.greek-added} οιτινες παραγενομενοι εις την συναγωγην απηεσαν των ιουδαιων[17:10]{.aside}

ουτοι δε ησαν ευγενεστεροι των εν [θεσσαλονικη]{.greek-omitted} [θεσαλονικη]{.greek-added} οιτινες εδεξαντο τον λογον μετα πασης προθυμιας το καθ ημεραν ανακρινοντες τας γραφας ει [εχοι]{.greek-omitted} [εχει]{.greek-added} ταυτα ουτως [καθως]{.greek-added} [παυλος]{.greek-added} [απαγγελει]{.greek-added}[17:11]{.aside}

πολλοι [μεν]{.greek-omitted} ουν εξ αυτων επιστευσαν [τινες]{.greek-added} [δε]{.greek-added} [ηπιστησαν]{.greek-added} και των ελληνιδων γυναικων των ευσχημονων [επιστευσαν]{.greek-added} και ανδρων ουκ ολιγοι[17:12]{.aside}

ως δε εγνωσαν οι απο της [θεσσαλονικης]{.greek-omitted} [θεσαλονικης]{.greek-added} ιουδαιοι οτι και εν τη [βεροια]{.greek-omitted} [βερροια]{.greek-added} κατηγγελη υπο του παυλου ο λογος του [θεου]{.greek-abbr} ηλθον κακει σαλευοντες [και]{.greek-added} [ταρασσοντες]{.greek-added} τους οχλους[17:13]{.aside}

ευθεως δε [τοτε]{.greek-omitted} τον παυλον εξαπεστειλαν οι αδελφοι πορευεσθαι ως επι την θαλασσαν [υπεμενον]{.greek-omitted} [υπεμεινε]{.greek-added} [δε]{.greek-omitted} [τε]{.greek-added} ο τε σιλας και ο [τιμοθεος]{.greek-omitted} [τιμοθεως]{.greek-added} εκει[17:14]{.aside}

οι δε καθιστωντες τον παυλον ηγαγον αυτον εως αθηνων και λαβοντες εντολην προς τον σιλαν και [τιμοθεον]{.greek-omitted} [τιμο]{.greek-added} [θεον]{.greek-added} ινα ως ταχιστα [ελθωσιν]{.greek-omitted} [ελθωσι]{.greek-added} προς αυτον εξηεσαν[17:15]{.aside}

εν δε ταις αθηναις εκδεχομενου αυτους του παυλου [παρωξυνετο]{.greek-omitted} [παρωξηνετο]{.greek-added} το [πνευμα]{.greek-abbr} αυτου εν [αυτω]{.greek-omitted} [εαυτω]{.greek-added} θεωρουντι κατειδωλον ουσαν την πολιν[17:16]{.aside}

διελεγετο μεν ουν εν τη συναγωγη τοις ιουδαιοις και τοις σεβομενοις και [τοις]{.greek-added} εν τη αγορα κατ[α]{.greek-supplied} πασαν ημεραν προς τους παρατυγχανοντας[17:17]{.aside}

τινες δ[ε]{.unclear} [και]{.greek-omitted} των επικουρειων και [των]{.greek-omitted} στοικων φιλοσοφων συνεβαλλ[ον]{.greek-supplied} αυτω και τινες ελεγον τι αν θελοι ο σπερμολογος ουτος λεγειν οι δε ξενων δαιμονιων δοκει καταγγελευ[ς]{.unclear} ειναι οτι τον [ιησουν]{.greek-abbr} και την αναστασιν ευηγγελιζετο [αυτοις]{.greek-added} [μετα]{.greek-added} [δε]{.greek-added} [ημερας]{.greek-added} [τινας]{.greek-added}[17:18]{.aside}

επιλαβομενοι [τε]{.greek-omitted} αυτου επι τον αρειον παγον ηγαγον λεγοντες δυναμεθα γνωναι τις η καινη αυτη η υπο σου λαλουμενη διδαχη[17:19]{.aside}

ξενιζοντα γαρ τινα εισφερεις εις τας ακοας ημων βουλομεθα ουν γνωναι τι αν θελοι ταυτα ειναι[17:20]{.aside}

αθηναιοι δε παντες και οι επιδημουντες ξενοι εις ουδεν ετερον [ευκαιρουν]{.greek-omitted} [ηυκαιρουν]{.greek-added} η λεγειν τι και [α]{.unclear}κουειν καινοτερον[17:21]{.aside}

σταθεις δε ο παυλος εν μεσω του αρειου παγου εφη ανδρες αθηναιοι κατα παντα ως δεισιδαιμονεστερους υμας θεωρω[17:22]{.aside}

διερχομενος γαρ και αναθεωρων τα σεβασματα υμων ευρον και βωμον εν ω επεγεγραπτο αγνωσ[τω]{.unclear} [θεω]{.greek-abbr} ον ουν αγνοουντες ευσεβειτε τουτον εγω καταγγελλω υμιν[17:23]{.aside}

ο [θεος]{.greek-abbr} ο ποιησας τον κοσμον και παντα τα εν αυτω ουτος [ουρανου]{.greek-abbr} και γης [κυριος]{.greek-abbr} υπαρχων ουκ εν χειροποιητοις ναοις κατοικει[17:24]{.aside}

ουδε υπο χειρων [ανθρωπων]{.greek-abbr} θεραπευεται προσδεομενος τινος αυτος διδους [πασιν]{.greek-omitted} [πασι]{.greek-added} [πνοην]{.greek-added} [και]{.greek-added} ζωην [και]{.greek-omitted} [πνοην]{.greek-omitted} κατα παντα[17:25]{.aside}

[εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} τε εξ ενος αιματος παν [εθνος]{.greek-omitted} [γενος]{.greek-added} [ανθρωπων]{.greek-abbr} κατοικειν επι παν το προσωπον της γης ορισας προστεταγμενους καιρους και τας οροθεσιας της κατοικιας αυτων[17:26]{.aside}

ζητειν τον [κυριον]{.greek-omitted} [[θεον]{.greek-abbr}]{.greek-added} ει αρα γε ψηλαφησειαν αυτον και ευροιεν και γε ου μακραν απο ενος εκαστου [ημων]{.greek-omitted} υπαρχοντα[17:27]{.aside}

εν αυτω γαρ ζωμεν και κινουμεθα και εσμεν ως και τινες των καθ υμας ποιητων [ειρηκασιν]{.greek-omitted} [ειρηκασι]{.greek-added} του γαρ και γενος εσμεν[17:28]{.aside}

γενος ουν υπαρχοντες του [θεου]{.greek-abbr} ουκ οφειλομεν νομιζειν χρυσω η αργυρω η λιθω χαραγματι τεχνης και ενθυμησεως [ανθρωπου]{.greek-abbr} το θειον ειναι ομοιον[17:29]{.aside}

τους μεν ουν χρονους της αγνοιας υπεριδων ο [θεος]{.greek-abbr} τα νυν [παραγγελλει]{.greek-omitted} [παραγγελει]{.greek-added} τοις [ανθρωποις]{.greek-abbr} [πασιν]{.greek-omitted} [πασι]{.greek-added} πανταχου μετανοειν[17:30]{.aside}

[διοτι]{.greek-omitted} [καθοτι]{.greek-added} εστησεν ημεραν εν η μελλει κρινειν την οικουμενην εν δικαιοσυνη εν ανδρι ω [ωρισεν]{.greek-omitted} [ωρισε]{.greek-added} [πιστιν]{.greek-omitted} [πιστην]{.greek-added} παρασχων πασιν αναστησας αυτον εκ νεκρων[17:31]{.aside}

ακουσαντες δε αναστασιν νεκρων οι μεν εχλευαζον οι δε ειπον [ακουσομεθα]{.greek-omitted} [ακουσωμεθα]{.greek-added} σου παλιν περι τουτου[17:32]{.aside}

και ουτως ο παυλος εξηλθεν εκ μεσου αυτων[17:33]{.aside}

τινες δε ανδρες κολληθεντες αυτω επιστευσαν εν οις και διονυσιος ο αρεοπαγιτης και γυνη ονοματι δαμαρις και ετεροι συν αυτοις[17:34]{.aside}

### Chapter 18

μετα δε ταυτα [χωρισθης]{.greek-added} [χωρισθεις]{.corr} ο παυλος εκ των αθηνω[ν]{.greek-supplied} ηλθεν εις κορινθον[18:1]{.aside}

και ευρων τινα ιουδαιον ονομ[α]{.greek-supplied}τι ακυλαν ποντικον τω γενει προσφατως εληλ[υ]{.greek-supplied}θοτα απο της ιταλιας και πρισκιλλαν γυναικα αυτου δια το τεταχεναι κλαυδιον χωριζεσθαι π[α]{.unclear}[ν]{.greek-supplied}τας τους ιουδαιους εκ της ρωμης προσηλθεν αυτ[οις]{.greek-supplied}[18:2]{.aside}

και δια το ομοτεχνον ειναι [εμενεν]{.greek-omitted} [εμεινε]{.greek-added} παρ αυτοις και ει[ρ]{.greek-supplied}γαζετο ησαν γαρ σκηνοποιοι την τεχνην[18:3]{.aside}

διελ[ε]{.greek-supplied}γετο δε εν τη συναγωγη κατα παν σαββατον [επειθεν]{.greek-omitted} [ε[πει]{.greek-supplied}θε]{.greek-added} τε ιουδαιους και ελληνας[18:4]{.aside}

ως δε κατηλθον απο τ[ης]{.greek-supplied} μακεδονιας ο τε σιλας και ο τιμοθεος συνειχετο [τω]{.greek-supplied} [πνευματι]{.greek-abbr} ο παυλος διαμαρτυρομενος τοις ιουδαιοις τον [χριστον]{.greek-abbr} [ιησουν]{.greek-abbr}[18:5]{.aside}

αντιτασσομενων δε αυτων και βλασφημουντ[ω]{.unclear}[ν]{.greek-supplied} εκτιναξαμενος τα ιματια [ειπεν]{.greek-omitted} [ειπε]{.greek-added} προς αυτου[ς]{.unclear} το αιμα υμων επι την κεφαλην υμων καθαρος ε[γ]{.unclear}[ω]{.greek-supplied} απο του νυν εις τα εθνη πορευσομαι[18:6]{.aside}

και μεταβας ε[κει]{.greek-supplied}θεν [απο]{.greek-added} [ακυλαν]{.greek-added} ηλθεν εις οικιαν τινος ονομα[τ]{.unclear}[ι]{.greek-supplied} ιουστου σεβομενου τον [θεον]{.greek-abbr} ου η οικια ην συνομορ[ου]{.greek-supplied}σα τη συναγωγη[18:7]{.aside}

κρισπος δε ο αρχισυναγωγος [επιστευσεν]{.greek-omitted} [[ε]{.unclear}πιστευσε]{.greek-added} τω [κυριω]{.greek-abbr} συν ολω τω οικω αυτου και πολ[λ]{.unclear}[οι]{.greek-supplied} των κορινθιων [ακουοντες]{.greek-omitted} [ακουσαντες]{.greek-added} [επιστευον]{.greek-omitted} [επιστευσαν]{.greek-added} [δια]{.greek-added} [του]{.greek-added} [ονομ[α]{.greek-supplied}τος]{.greek-added} [του]{.greek-added} [[κυριου]{.greek-abbr}]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} [[χριστου]{.greek-abbr}]{.greek-added} και εβαπτιζοντο[18:8]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε ο [κυριος]{.greek-abbr} δ[ι]{.unclear} [ο]{.greek-supplied}ραματος [εν]{.greek-omitted} [νυκτι]{.greek-omitted} [ενυκτι]{.greek-added} τω παυλω μη φοβου αλλα λ[α]{.greek-supplied}λει και μη [σιωπησης]{.greek-omitted} [σιωπησεις]{.greek-added}[18:9]{.aside}

διοτι εγω ειμι μετα σου κ[αι]{.greek-supplied} ουδεις [επιθησεται]{.greek-omitted} [επιθησετε]{.greek-added} σοι του κακωσαι σε διοτι λαος [εστιν]{.greek-omitted} [εστι]{.greek-added} μοι πολυς εν τη πολει ταυτη[18:10]{.aside}

εκαθισεν [τε]{.greek-omitted} [δε]{.greek-added} ενιαυτον και μηνας εξ διδασκων [εν]{.greek-omitted} αυτοις τον λογον του [θεου]{.greek-abbr}[18:11]{.aside}

γαλλιωνος δε ανθυπατευοντος της αχαιας κατεπεστησαν ομοθυμαδον [τω]{.greek-added} [παυλω]{.greek-added} οι ιουδαιοι [τω]{.greek-omitted} [παυλω]{.greek-omitted} και ηγαγον αυτον επι το βημα[18:12]{.aside}

λεγοντες οτι παρα τον νομον ουτος αναπειθει τους [ανθρωπους]{.greek-abbr} σεβεσθαι τον [θεον]{.greek-abbr}[18:13]{.aside}

μελλοντος δε του παυλου ανοιγειν το στομα ειπεν ο γαλλιων προς τους ιουδαιους ει μεν [ουν]{.greek-omitted} ην αδικημα τι η ραδιουργημα πονηρον ω ιουδαιοι κατα λογον αν ηνεσχομην υμων[18:14]{.aside}

ει δε [ζητημα]{.greek-omitted} [ζητηματα]{.greek-added} [εστιν]{.greek-omitted} [εστι]{.greek-added} περι λογου και [ονοματων]{.greek-omitted} [ονοματος]{.greek-added} και νομου του καθ υμας οψεσθε αυτοι κριτης γαρ εγω τουτων ου βουλομαι ειναι[18:15]{.aside}

και απηλασεν αυτους απο του βηματος[18:16]{.aside}

επιλαβομενοι δε παντες οι ελληνες σωσθενην τον αρχισυναγωγον ετυπτον εμπροσθεν του βηματος και ουδεν τουτων τω γαλλιωνι εμελλεν[18:17]{.aside}

ο δε παυλος ετι προσμεινας ημερας ικανας τοις αδελφοις αποταξαμενος εξεπλει εις την συριαν και συν αυτω πρισκιλλα και ακυλας κειραμενος την κεφαλην εν κεγχρεαις [ειχεν]{.greek-omitted} [ειχε]{.greek-added} γαρ ευχην[18:18]{.aside}

[κατηντησεν]{.greek-omitted} [κατηντησε]{.greek-added} δε εις εφεσον [και]{.greek-omitted} [τω]{.greek-added} [επιοντι]{.greek-added} [σαββατω]{.greek-added} [εκεινους]{.greek-omitted} [κακεινους]{.greek-added} κατελιπεν αυτου αυτος δε εισελθων εις την συναγωγην διελεχθη τοις ιουδαιοις[18:19]{.aside}

ερωτωντων δε [αυτων]{.greek-omitted} [αυτον]{.greek-added} επι πλειονα χρονον μειναι παρ αυτοις [ου]{.unclear}κ [επεν]{.unclear}ευ[σε]{.unclear}ν[18:20]{.aside}

[αλλ]{.greek-omitted} [αλλα]{.greek-added} απεταξατο αυτοις ειπων δει με παντως την εορτην την ερχομενην ποιησαι εις ιεροσολυμα παλιν δε ανακαμψω [προς]{.greek-omitted} [εις]{.greek-added} [υμας]{.greek-omitted} [ημας]{.greek-added} του [θεου]{.greek-abbr} θελοντος [και]{.greek-added} ανηχθη απο της εφεσου[18:21]{.aside}

[τον]{.greek-added} [δε]{.greek-added} [ακυλα[ν]{.greek-supplied}]{.greek-added} [ειασεν]{.greek-added} [εν]{.greek-added} [εφεσω]{.greek-added} και κατελθων εις [την]{.greek-added} καισαρειαν αναβας και ασπασαμενος την εκκλ[η]{.greek-supplied}σιαν [κατεβη]{.greek-omitted} [κατεβει]{.greek-added} εις αντιοχειαν[18:22]{.aside}

και ποιησας χρονον τινα [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} διερχομενος καθεξης την γαλατικη[ν]{.greek-supplied} χωραν και φρυγιαν επιστηριζων παντας τους μαθητας[18:23]{.aside}

ιουδαιος δε τις απολλως ονοματι αλεξανδρευς τω γενει ανηρ λογιος κατηντησεν εις εφεσον δυνατος ων εν ταις γραφαις[18:24]{.aside}

ουτος η[ν]{.greek-supplied} κατηχημενος την οδον του [κυριου]{.greek-abbr} και ζεων τω [πνευματι]{.greek-abbr} ελαλει και εδιδασκεν ακριβως τα περι του [κυριου]{.greek-omitted} [[ιησου]{.greek-abbr}]{.greek-added} επισταμενος μονον το βαπτισμα ιωαννου[18:25]{.aside}

ουτος τε ηρξατο παρρησιαζεσθαι εν τη συν[α]{.unclear}γωγη ακουσαντες δε αυτου ακυλας και π[ρι]{.greek-supplied}σκιλλα προσελαβοντο αυτον και ακριβε[στ]{.unclear}[ε]{.greek-supplied}ρον αυτω εξεθεντο την [οδον]{.greek-added} του [θεου]{.greek-abbr} [οδον]{.greek-omitted}[18:26]{.aside}

βουλομε[νου]{.greek-supplied} δε αυτου διελθειν [εις]{.greek-omitted} την αχαιαν [προτρεψαμενοι]{.greek-omitted} [προπεμψαμεν[οι]{.greek-supplied}]{.greek-added} οι αδελφοι εγραψαν τοις μαθηταις [μαθ[η]{.unclear}τ[α]{.unclear}[ις]{.greek-supplied}]{.greek-added} αποδεξασθαι αυτον ος παραγενομενος [ει[ς]{.unclear}]{.greek-added} [την]{.greek-added} [αχαιαν]{.greek-added} συνεβαλετο πολυ τοις [πεπιστευκοσιν]{.greek-omitted} [πεπι[στευ]{.greek-supplied}κοσι]{.greek-added} δια της χαριτος[18:27]{.aside}

ευτονως γαρ τοις ιουδ[α]{.unclear}[ιοις]{.greek-supplied} διακατηλεγχετο δημοσια [διαλεγομενος]{.greek-added} [και]{.greek-added} επιδεικνυς δια των γραφων ειναι τον [χριστον]{.greek-abbr} [ιησουν]{.greek-abbr}[18:28]{.aside}

### Chapter 19

εγενετο δε εν τω τον [απολλω]{.greek-omitted} [απολλων]{.greek-added} ειναι εν κορινθω παυλον διελθοντα τα ανωτερικα μερη ελθειν εις εφεσον και ευρων τινας μαθητας[19:1]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} προς αυτους ει [πνευμα]{.greek-abbr} αγιον ελαβετε πιστευσαντες οι δε ειπον προς αυτον αλλ ουδε ει [πνευμα]{.greek-abbr} αγιον εστιν ηκουσαμεν[19:2]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} τε προς αυτους εις τι [ουν]{.greek-omitted} [γουν]{.greek-added} εβαπτισθητε οι δε ειπον εις το ιωαννου βαπτισμα[19:3]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε παυλος ιωαννης μεν [εβαπτισεν]{.greek-omitted} [εβαπτισε]{.greek-added} βαπτισμα μετανοιας τω λαω λεγων εις τον ερχομενον μετ αυτον ινα [πιστευσωσιν]{.greek-omitted} [πιστευσωσι]{.greek-added} τουτ εστιν εις τον [χριστον]{.greek-abbr} [ιησουν]{.greek-abbr}[19:4]{.aside}

ακουσαντες δε εβαπτισθησαν εις το ονομα του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} [[χριστου]{.greek-abbr}]{.greek-added} [εις]{.greek-added} [αφεσιν]{.greek-added} [αμαρτιων]{.greek-added}[19:5]{.aside}

και επιθεντος αυτοις του παυλου τας χειρας [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} το [πνευμα]{.greek-abbr} το αγιον επ αυτους ελαλουν τε γλωσσαις και προεφητευον[19:6]{.aside}

ησαν δε οι παντες ανδρες ωσει δεκαδυο[19:7]{.aside}

εισελθων δε εις την συναγωγην επαρρησιαζετο επι μηνας τρεις διαλεγομενος και [πειθων]{.greek-omitted} [πειθον]{.greek-added} τα περι της βασιλειας του [θεου]{.greek-abbr}[19:8]{.aside}

ως δε τινες [των]{.greek-added} [εθνων]{.greek-added} εσκληρυνοντο και ηπειθουν κακολογουντες την οδον ενωπιον του πληθους αποστας απ αυτων [αφωρισεν]{.greek-omitted} [αφωρισε]{.greek-added} τους μαθητας [το]{.greek-added} καθ ημεραν διαλεγομενος εν τη σχολη τυραννου τινος [απο]{.greek-added} [ωρας]{.greek-added} [πεπτης]{.greek-added} [[πεμπτης]{.corr}]{.greek-added} [εως]{.greek-added} [ωρας]{.greek-added} [δεκατις]{.greek-added}[19:9]{.aside}

τουτο δε [εγενετο]{.greek-omitted} [εγινετο]{.greek-added} επι ετη δυο ωστε παντας τους [κατοικουντας]{.greek-omitted} [κατηκουντας]{.greek-added} την ασιαν ακουσαι τον λογον του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} ιουδαιους τε και ελληνας[19:10]{.aside}

δυναμεις τε ου τας τυχουσας εποιει ο [θεος]{.greek-abbr} δια των χειρων παυλου[19:11]{.aside}

ω[σ]{.greek-supplied}τε και επι τους ασθενουντας επιφερεσθαι απο του χρωτος αυτου σουδαρια η σιμικινθια και απαλλ[α]{.greek-supplied}σσεσθαι απ αυτων τας νοσους τα τε [πνευματα]{.greek-abbr} τα πον[η]{.unclear}ρα εξερχεσθαι απ αυτων[19:12]{.aside}

επεχειρησαν δε τινες [απο]{.greek-omitted} [και]{.greek-added} των περιερχομενων ιουδαιων εξορκιστων ονομαζειν επι τους [ασθενουντας]{.greek-added} [και]{.greek-added} [εχοντας]{.greek-omitted} [εχοντα]{.greek-added} [τα]{.greek-omitted} πνευματα [τα]{.greek-omitted} πονηρα το ονομα του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} λεγοντες [ορκιζομεν]{.greek-omitted} [εξορκιζομ[ε]{.unclear}[ν]{.greek-supplied}]{.greek-added} υμας τον [ιησουν]{.greek-abbr} ον [ο]{.greek-omitted} παυλος κηρυσσει[19:13]{.aside}

ησαν δε τινες υιοι σκευα ιουδαιου αρχιερεως επτα οι τουτο ποιουντες[19:14]{.aside}

αποκριθεν δε το [πνευμα]{.greek-abbr} το πονηρον ειπεν [αυτοις]{.greek-added} το[ν]{.unclear} [μεν]{.greek-added} [ιησουν]{.greek-abbr} γινωσκω και τον παυλον επισταμαι υμει[ς]{.unclear} δε τινες εστε[19:15]{.aside}

και εφαλλομενος επ αυτους ο [ανθρωπος]{.greek-abbr} εν ω ην το [πνευμα]{.greek-abbr} το πονηρον και κατακυριευσαν αυτ[ω]{.unclear}[ν]{.greek-supplied} [ισχυσεν]{.greek-omitted} [ισχυσε]{.greek-added} κατ αυτων ωστε γυμνους και τετραυματ[ισ]{.greek-supplied}μενους εκφυγειν εκ του οικου εκεινου[19:16]{.aside}

τουτο δε εγενετο γνωστον πασιν ιουδαιοις τε και [ελλησιν]{.greek-omitted} [ελλησι]{.greek-added} τοις κατοικουσιν [την]{.greek-omitted} εφεσον και [επεπεσεν]{.greek-omitted} [επεσεν]{.greek-added} φοβος επι παντας αυτους και εμεγαλυνετο το ονομα του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr}[19:17]{.aside}

πολλοι τε των πεπιστευκοτων ηρχο[ντο]{.greek-supplied} εξομολογουμενοι και [αναγγελλοντες]{.greek-omitted} [αναγγελοντες]{.greek-added} τας πραξεις αυτων[19:18]{.aside}

ικανοι [δε]{.greek-omitted} [τε]{.greek-added} των τα περιεργα πραξαντων συνενεγκαντες τας βιβλους κατεκαιον ενωπιον παντων και συνεψηφισαν τας τιμας αυτων και ευρον [αργυριου]{.greek-omitted} [χρυσιου]{.greek-added} μυριαδας πεντε[19:19]{.aside}

ουτως κατα κρατος ο λογος του [κυριου]{.greek-abbr} [ηυξανεν]{.greek-omitted} [ηυξανε]{.greek-added} και ισχυεν[19:20]{.aside}

ως δε επληρωθη ταυτα εθετο ο παυλος εν τω [πνευματι]{.greek-abbr} διελθων την μακεδονιαν και αχαιαν πορευεσθαι εις [ιερουσαλημ]{.greek-omitted} [ιεροσολυμαν]{.greek-added} ειπων οτι μετα το γενεσθαι με εκει δει με και ρωμην ιδειν[19:21]{.aside}

αποστειλας δε εις [την]{.greek-omitted} μακεδονιαν δυο [των]{.greek-added} [αδελφων]{.greek-added} των διακονουντων αυτω τιμοθεον και εραστον αυτος [επεσχεν]{.greek-omitted} [επεσχε]{.greek-added} χρονον εις την ασιαν[19:22]{.aside}

εγενετο δε κατα τον καιρον εκεινον ταραχος ουκ ολιγος [περι]{.greek-omitted} [κατα]{.greek-added} της οδου[19:23]{.aside}

δημητριος γαρ τις ονοματι αργυροκοπος ποιων ναους αργυρους αρτεμιδος παρειχετο τοις τεχνιταις εργασιαν ουκ ολιγην[19:24]{.aside}

ους συναθροισας και τους περι τα τοιαυτα εργατας ειπεν ανδρες επιστασθε οτι εκ ταυτης της εργασιας η ευπορια ημων [εστιν]{.greek-omitted} [εστι]{.greek-added}[19:25]{.aside}

και θεωρειτε και ακουετε οτι ου μονον εφεσου αλλα σχεδον πασης της ασιας ο παυλος ουτος πεισας μετεστησεν ικανον οχλον λεγων οτι ουκ [εισιν]{.greek-omitted} [εισι]{.greek-added} θεοι οι δια χειρων [[ανθρωπων]{.greek-abbr}]{.greek-added} γινομενοι[19:26]{.aside}

ου μονον δε τουτο [το]{.greek-added} [μερος]{.greek-added} κινδυνευει ημιν [το]{.greek-omitted} [μερος]{.greek-omitted} εις απελεγμον ελθειν αλλα και το της μεγαλης θεας [αρτεμιδος]{.greek-added} [ιερ]{.unclear}ον [αρτεμιδος]{.greek-omitted} εις ουθεν λογισθηναι μελλειν [τε]{.greek-added} [δε]{.greek-omitted} [και]{.greek-omitted} [καθαιρεισθαι]{.greek-omitted} [καθερεισθαι]{.greek-added} την μεγαλειοτητα αυτης ην [η]{.greek-added} ολη [η]{.greek-omitted} ασια και η οικουμ[ε]{.unclear}νη σεβεται[19:27]{.aside}

ακουσαντες δε και γενομενοι πληρεις θ[υ]{.unclear}μου [και]{.greek-added} [δραμοντες]{.greek-added} [εις]{.greek-added} [το]{.greek-added} [αμφοδον]{.greek-added} εκραζον λεγοντες μεγαλη η αρτεμις εφεσιων[19:28]{.aside}

και επλη[σ]{.greek-supplied}θη η πολις ολη της συγχυσεως ωρμησαν τε [ο]{.unclear}μοθυμαδον εις το θεατρον συναρπασαντες γαιον και αρισταρχον μακεδονας συνεκδημους παυλου[19:29]{.aside}

του δε παυλου βουλομενου εισελθειν ε[ι]{.unclear}[ς]{.greek-supplied} τον δημον ουκ ειων αυτον οι μαθηται[19:30]{.aside}

τινες δε και των ασιαρχων οντες αυτω φιλοι πεμψ[α]{.unclear}[ν]{.greek-supplied}τες προς [αυτον]{.greek-omitted} [αυτων]{.greek-added} παρεκαλουν μη δουναι εαυτο[ν]{.greek-supplied} εις το θεατρον[19:31]{.aside}

αλλοι μεν ουν αλλο τι εκραζ[ο]{.unclear}[ν]{.greek-supplied} ην γαρ η εκκλησια συγκεχυμενη και [οι]{.greek-omitted} [[η]{.unclear}]{.greek-added} πλειους [ου]{.greek-supplied}κ ηδεισαν τινος [ενεκεν]{.greek-omitted} [ενεκα]{.greek-added} συνεληλυθεισαν[19:32]{.aside}

εκ δε τ[ου]{.greek-supplied} οχλου [προεβιβασαν]{.greek-omitted} [προεβιασαν]{.greek-added} αλεξανδρον προβαλο[ν]{.unclear}των [αυτον]{.greek-omitted} [αυτων]{.greek-added} των ιουδαιων ο δε αλεξανδρος κ[α]{.greek-supplied}τασεισας την [χειρα]{.greek-omitted} [χειραν]{.greek-added} ηθελεν απολογεισθαι τ[ω]{.unclear} δημω[19:33]{.aside}

επιγνοντες δε οτι ιουδαιος [εστιν]{.greek-omitted} [εστι]{.greek-added} φωνη [ε]{.unclear}γενετο [μια]{.greek-omitted} εκ παντων ως επι ωρας δυο κραζο[ν]{.greek-supplied}των μεγαλη η αρτεμις εφεσιων[19:34]{.aside}

καταστειλ[ας]{.greek-supplied} δε ο γραμματευς τον οχλον φησιν ανδρες [εφεσιοι]{.greek-omitted} [εφ[ε]{.greek-supplied}σειοι]{.greek-added} τις γαρ εστιν [ανθρωπος]{.greek-omitted} [[ανθρωπων]{.greek-abbr}]{.greek-added} ος ου [γινωσκ[ι]{.unclear}]{.greek-added} [γινωσκει]{.corr} την εφ[εσι]{.greek-supplied}ων πολιν νεωκορον ουσαν της μεγαλης [θεας]{.greek-omitted} αρ[τε]{.greek-supplied}μιδος και του διοπετους[19:35]{.aside}

[αναντιρρητων]{.greek-omitted} [αναντηρητω[ν]{.greek-supplied}]{.greek-added} ουν οντων τουτων δεον εστιν υμας κατεσταλμενους υπαρχειν και μηδεν προπετες πρασσειν[19:36]{.aside}

ηγαγετε γαρ τους ανδρας τουτους [ενθαδε]{.greek-added} ουτε ιεροσυλους ουτε βλασφημουντας την θεον υμων[19:37]{.aside}

ει μεν ουν [ο]{.greek-added} δημητριος και οι συν αυτω τεχνιται εχουσιν προς τινα λογον αγοραιοι αγονται και ανθυπατοι εισιν εγκαλειτωσαν αλληλοις[19:38]{.aside}

ει δε τι περι ετερων επιζητειτε εν τη εννομω εκκλησια επιλυθησεται[19:39]{.aside}

και γαρ κινδυνευομεν εγκαλεισθαι στασεως περι της σημερον μηδενος αιτιου υπαρχοντος περι ου ου δυνησομεθα [δουναι]{.greek-omitted} [αποδουναι]{.greek-added} λογον [περι]{.greek-added} της συστροφης ταυτης [και]{.greek-added} [ταυτα]{.greek-added} [ειπων]{.greek-added} [απελυσε]{.greek-added} [την]{.greek-added} [εκκλησιαν]{.greek-added}[19:40]{.aside}

### Chapter 20

μετα δε το παυσασθαι τον θορυβον προσκαλεσαμενος ο παυλος τους μαθητας και [παρακαλεσας]{.greek-added} ασπασαμενος [τε]{.greek-added} [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} πορευθηναι εις [την]{.greek-omitted} μακεδονιαν[20:1]{.aside}

διελθων δε τα μερη εκεινα και παρακαλεσας αυτους λογω πολλω ηλθεν εις την ελλαδα[20:2]{.aside}

ποιησας [τε]{.greek-omitted} [δε]{.greek-added} μηνας τρεις γενομενης αυτω επιβουλης υπο των ιουδαιων μελλοντι αναγεσθαι εις την συριαν εγενετο γνωμη του υποστρεφειν δια μακεδονιας[20:3]{.aside}

συνειπετο δε αυτω αχρι της ασιας [σωπατρος]{.greek-omitted} [σωσιπατρος]{.greek-added} [βεροιαιος]{.greek-omitted} [βερροιαιος]{.greek-added} [θεσσαλονικεων]{.greek-omitted} [θεσαλονικεων]{.greek-added} δε αρισταρχος και σεκουνδος και γαιος δερβαιος και τιμοθεος [εφεσιος]{.greek-added} ασιανοι δε [τυ]{.unclear}χικος και τροφιμος[20:4]{.aside}

ουτοι [προσελθοντες]{.greek-omitted} [προελθοντες]{.greek-added} εμενον ημας εν τρωαδι[20:5]{.aside}

ημεις δε εξεπλευσαμεν μετα τας ημερας των αζυμων απο φιλιππων και ηλθομεν προς αυτους εις την τρωαδα [αχρι]{.greek-omitted} [αχρις]{.greek-added} ημερων πεντε ου [και]{.greek-added} διετριψαμεν ημερας επτα[20:6]{.aside}

εν δε τη μια των σαββατων συνηγμενων [ημων]{.greek-added} [των]{.greek-omitted} [μαθητων]{.greek-omitted} κλασαι αρτον ο παυλος διελεγετο αυτοις μελλων εξιεναι τη επαυριον [παρετεινεν]{.greek-omitted} [παρετι[ν]{.unclear}ε]{.greek-added} τε τον λογον μεχρι μεσονυκτιου[20:7]{.aside}

ησαν δε λαμπαδες ικαναι εν τω υπερωω ου ημεν συνηγμενοι[20:8]{.aside}

καθημενος δ[ε]{.unclear} τις [νεανιας]{.greek-omitted} [νεανισκος]{.greek-added} ονοματι ευτυχος [επι]{.greek-omitted} [της]{.greek-omitted} [θυριδος]{.greek-omitted} καταφερομενος υπνω βαθει διαλεγομενου του παυλου επι πλειον κατενεχθεις [απο]{.greek-omitted} [υπο]{.greek-added} του υπνου επεσεν απο του τριστεγου κατω και ηρθη νεκρος[20:9]{.aside}

καταβας δε ο παυλος επεπεσεν αυτω και συμπεριλαβων [ειπεν]{.greek-omitted} [ειπε]{.greek-added} μη [θορυβεισθε]{.greek-omitted} [θορυβησθε]{.greek-added} η γαρ ψυχη αυτου εν αυτω εστιν[20:10]{.aside}

αναβας δε και κλασας αρτον και γευσαμενος εφ ικανον τε ομιλησας [αχρι]{.greek-omitted} [αχρις]{.greek-added} αυγης ουτως εξηλθεν[20:11]{.aside}

ηγαγον δε τον παιδα ζωντα και παρεκληθησαν ου μετρι[ω]{.unclear}[ς]{.greek-supplied}[20:12]{.aside}

ημεις δε [προσελθοντες]{.greek-omitted} [προελθοντες]{.greek-added} επι το πλοιον ανηχθημεν εις την ασσον εκειθεν μελλοντες αναλαμβανειν τον παυλον ουτως γαρ ην διατεταγμενος μελλων αυτος πεζευειν[20:13]{.aside}

ως δε συνεβαλεν ημιν εις τη[ν]{.unclear} ασσον αναλαβοντες αυτον ηλθομεν εις μιτυλην[ην]{.unclear}[20:14]{.aside}

[κακειθεν]{.greek-omitted} [κακει]{.greek-added} αποπλευσαντες τη επιουση [κατηντησαμεν]{.greek-omitted} [κατην]{.greek-added} [τησαμεν]{.greek-added} αντικρυ χιου τη δε ετερα παρεβαλομεν εις σαμον και μειναντες εν [τρωγυλλιω]{.greek-omitted} [τρογυλλιω]{.greek-added} τη εχομενη ηλθομεν εις μιλητον[20:15]{.aside}

[εκρινεν]{.greek-omitted} [εκρινε]{.greek-added} γαρ ο παυλος παραπλευσαι την εφεσον οπως μη γενηται αυτω χρονοτριβησαι εν τη ασια [εσπευδεν]{.greek-omitted} [εσπευδε]{.greek-added} γαρ ει δυνατον ην αυτω την ημεραν της πεντηκοστης γενεσθαι εις ιεροσολυμα[20:16]{.aside}

απο δε της μιλητου πεμψας εις εφεσον μετεκαλεσατο τους πρεσβυτερους της εκκλησιας[20:17]{.aside}

ως δε παρεγενοντο προς αυτον ειπεν αυτοις υμεις επιστασθε απο πρωτης ημερας αφ ης επεβην εις την ασιαν πως μεθ [υμων]{.greek-omitted} [ημων]{.greek-added} τον παντα χρονον εγενομην[20:18]{.aside}

δουλευων τω [κυριω]{.greek-abbr} μετα πασης ταπεινοφροσυνης και πολλων δακρυων και [πειρασμων]{.greek-omitted} [πυρασμων]{.greek-added} των συμβαντων μοι εν [ταις]{.greek-omitted} [τες]{.greek-added} επιβουλαις των ιουδαιων[20:19]{.aside}

ως ουδεν υπεστειλαμην των συμφεροντων του μη αναγγειλαι υμιν και διδαξαι υμας δημοσια και κατ οικους[20:20]{.aside}

διαμαρτυρομενος ιουδαιοις τε και [ελλησιν]{.greek-omitted} [ελλησι]{.greek-added} την εις τον [θεον]{.greek-abbr} μετανοιαν και πιστιν την εις τον [κυριον]{.greek-abbr} ημων [ιησουν]{.greek-abbr} [[χριστον]{.greek-abbr}]{.greek-added}[20:21]{.aside}

και [νυν]{.greek-omitted} ιδου εγω δεδεμενος τω [πνευματι]{.greek-abbr} πορευομαι εις ιερουσαλημ τα εν αυτη συναντησοντα μοι μη ειδως[20:22]{.aside}

πλην οτι το [πνευμα]{.greek-abbr} [μοι]{.greek-added} το αγιον κατα πολιν διαμαρτυρεται λεγον οτι δεσμα με και θλιψεις μενουσιν[20:23]{.aside}

αλλ ουδενος λογον ποιουμαι ουδε εχω την ψυχην μου τιμιαν εμαυτω ως τελειωσαι τον δρομον μου μετα χαρας και την διακονιαν ην [ελαβον]{.greek-omitted} [παρελαβον]{.greek-added} παρα του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} διαμαρτυρασθαι το ευαγγελιον της χαριτος του [θεου]{.greek-abbr}[20:24]{.aside}

και νυν ιδου εγω οιδα οτι ουκετι οψεσθε το προσωπον μου υμεις παντες εν οις διηλθον κηρυσσων την βασιλειαν του [θεου]{.greek-abbr}[20:25]{.aside}

[διοτι]{.greek-omitted} [διο]{.greek-added} μαρτυρομαι υμιν εν τη σημερον ημερα οτι καθαρος εγω απο του αιματος παντων[20:26]{.aside}

ου γαρ υπεστειλαμην του μη αναγγειλαι υμιν πασαν την βουλην του [θεου]{.greek-abbr}[20:27]{.aside}

προσεχετε [ουν]{.greek-omitted} [γουν]{.greek-added} εαυτοις και πα[ν]{.unclear}τι τω ποιμνιω εν ω υμας το [πνευμα]{.greek-abbr} το αγιον εθετο επ[ι]{.greek-supplied}σκοπους [ποιμαινειν]{.greek-omitted} [ποιμενειν]{.greek-added} την εκκλησιαν του [κυριου]{.greek-omitted} [και]{.greek-omitted} [θεου]{.greek-abbr} ην περ[ι]{.greek-supplied}εποιησατο δια του ιδιου αιματος[20:28]{.aside}

εγω γαρ οιδα το[υτ]{.unclear}[ο]{.greek-supplied} οτι [εισελευσονται]{.greek-omitted} μετα την αφιξιν μου [εισελευσονται]{.greek-added} [εις]{.greek-added} [υμας]{.greek-added} λυκοι βαρεις [εις]{.greek-omitted} [υμας]{.greek-omitted} μη φειδομενοι του ποιμνιου[20:29]{.aside}

και εξ [υ]{.unclear}μων αυτων αναστησονται ανδρες λαλουντες διεστ[ρα]{.greek-supplied}μμενα του αποσπαν τους μαθητας οπισω αυ[τ]{.unclear}[ων]{.greek-supplied}[20:30]{.aside}

διο [γρηγορειτε]{.greek-omitted} [γρηγορειται]{.greek-added} μνημονευοντες οτι τριετιαν νυκτ[α]{.unclear} και ημεραν ουκ επαυσαμην μετα δακρυων νουθετων ενα εκαστον [υμων]{.greek-added}[20:31]{.aside}

και τα νυν παρατιθεμαι υμας [αδελφοι]{.greek-omitted} τω [θεω]{.greek-abbr} [αδελφοι]{.greek-added} και τω λογω της χαριτος αυτο[υ]{.unclear} [τ]{.unclear}[ω]{.greek-supplied} δυναμενω εποικοδομησαι και δουναι [υμιν]{.greek-omitted} [ημιν]{.greek-added} κληρονομ[ι]{.greek-supplied}αν εν τοις ηγιασμενοις πασιν [αυτω]{.greek-added} [η]{.greek-added} [δοξα]{.greek-added} [εις]{.greek-added} [το[υς]{.greek-supplied}]{.greek-added} [αιωνας]{.greek-added} [των]{.greek-added} [αιωνων]{.greek-added} [αμην]{.greek-added}[20:32]{.aside}

αργυριου η χρυσιο[υ]{.greek-supplied} [η]{.greek-supplied} ιματισμου ουδενος επεθυμησα[20:33]{.aside}

αυτοι [γινωσκετε]{.greek-omitted} [γινωσ]{.greek-added} [κετε]{.greek-added} οτι ταις χρειαις μου και τοις [ουσιν]{.greek-omitted} [ουσι]{.greek-added} μετ εμου υπηρετησαν αι χειρες αυται[20:34]{.aside}

παντα υπεδειξα υμιν οτι ουτως κοπιωντας δει αντιλαμβανεσθαι των ασθενουντων [μνημονευειν]{.greek-omitted} [μνημονευεν]{.greek-added} τε [των]{.greek-omitted} [τον]{.greek-added} [λογων]{.greek-omitted} [λογον]{.greek-added} του [κυριου]{.greek-abbr} [ιησου]{.greek-omitted} οτι αυτος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} μακαριον [εστιν]{.greek-omitted} [εστι]{.greek-added} μαλλον διδοναι η λαμβανειν[20:35]{.aside}

και ταυτα ειπων θεις τα γονατα αυτου συν πασιν αυτοις προσηυξατο[20:36]{.aside}

[εγενετο]{.greek-added} [δε]{.greek-added} [κλαυθμος]{.greek-added} ικανος [δε]{.greek-omitted} [εγενετο]{.greek-omitted} [κλαυθμος]{.greek-omitted} παντων και επιπεσοντες επι τον τραχηλον [του]{.greek-omitted} παυλου κατεφιλουν αυτον[20:37]{.aside}

οδυνωμενοι μαλιστα επι τω λογω ω ειρηκει οτι ουκετι [μελλουσιν]{.greek-omitted} [μελλουσι]{.greek-added} το προσωπον αυτου θεωρειν προεπεμπον δε αυτον εις το πλοιον[20:38]{.aside}

### Chapter 21

ως δε εγενετο αναχθηναι ημας αποσπασθεντας απ αυτων ευθυδρομησαντες ηλθομεν εις την [κων]{.greek-omitted} [κω]{.greek-added} τη δε εξης εις την ροδον κακειθεν εις παταρα[21:1]{.aside}

και ευροντες [πλοιον]{.greek-omitted} [πλειον]{.greek-added} [διαπερων]{.greek-omitted} [διαπερουν]{.greek-added} εις φοινικην επιβαντες ανηχθημεν[21:2]{.aside}

αναφανεντες δε την κυπρον και καταλιποντες αυτην ευωνυμον επλεομεν εις συριαν και κατηχθημεν εις τυρον εκεισε γαρ ην το πλοιον αποφορτιζομενον τον γομον[21:3]{.aside}

και ανευροντες μαθητας επεμειναμεν αυτου ημερας επτα οιτινες τω παυλω ελεγον δια του [πνευματος]{.greek-abbr} μη αναβαινειν εις ιερουσαλημ[21:4]{.aside}

οτε δε εγενετο ημας [εξαρτισαι]{.greek-omitted} [εξαρτησαι]{.greek-added} τας ημερας εξελθοντες επορευομεθα προπεμποντων ημας παντων συν [γυναιξιν]{.greek-omitted} [γυναιξι]{.greek-added} και τεκνοις εως εξω της πολεως και θεντες τα γ[ο]{.greek-supplied}νατα επι τον αιγιαλον προσηυξαμεθα[21:5]{.aside}

κ[α]{.unclear}[ι]{.greek-supplied} ασπασαμενοι αλληλους [επεβημεν]{.greek-omitted} [ανεβημεν]{.greek-added} εις το πλοιον εκεινοι [δε]{.greek-omitted} [τε]{.greek-added} υπεστρεψαν εις τα ιδια[21:6]{.aside}

ημεις δε τον πλουν διανυσαντες απο τυρου κατηντησ[α]{.unclear}μεν εις πτολεμαιδα και ασπασαμενοι τους αδελφους εμειναμεν ημεραν μιαν παρ αυτοις[21:7]{.aside}

τη δε επαυριον εξελθοντες [οι]{.greek-omitted} [περι]{.greek-omitted} [τον]{.greek-omitted} [παυλον]{.greek-omitted} [ηλθον]{.greek-omitted} [ηλθομεν]{.greek-added} εις καισαρειαν και εισελθοντες εις τον οικον φιλιππου του ευαγγελιστου οντος εκ των επτα εμεινα[μ]{.unclear}[εν]{.greek-supplied} παρ αυτω[21:8]{.aside}

[τουτω]{.greek-omitted} [τουτο]{.greek-added} δε ησαν θυγατερες παρθενοι τεσσαρες προφητευουσαι[21:9]{.aside}

επιμενοντων δε ημων η[μ]{.unclear}[ε]{.greek-supplied}ρας πλειους [κατηλθεν]{.greek-omitted} [κατηλθε]{.greek-added} τις απο της ιουδαιας προφ[η]{.unclear}της ονοματι αγαβος[21:10]{.aside}

και ελθων προς ημας και αρ[α]{.unclear}[ς]{.greek-supplied} την ζωνην του παυλου δησας [τε]{.greek-omitted} [αυτου]{.greek-omitted} [εαυτου]{.greek-added} [τας]{.greek-added} [χειρας]{.greek-added} [[και]{.greek-supplied}]{.greek-added} τους ποδας [και]{.greek-omitted} [τας]{.greek-omitted} [χειρας]{.greek-omitted} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} ταδε λεγει το [πνευμα]{.greek-abbr} το αγιον τ[ο]{.unclear}[ν]{.greek-supplied} ανδρα ου εστιν η ζωνη αυτη ουτως δησουσιν εν ιερουσαλημ οι ιουδαιοι και παραδωσουσιν εις χειρα[ς]{.unclear} εθνων[21:11]{.aside}

ως δε ηκουσαμεν ταυτα παρεκαλουμεν [η]{.greek-supplied}μεις τε και οι εντοπιοι του μη αναβαινειν αυτον ε[ις]{.greek-supplied} ιερουσαλημ[21:12]{.aside}

απεκριθη [τε]{.greek-omitted} [δε]{.greek-added} ο παυλος τι ποιειτε κλ[α]{.unclear}[ι]{.greek-supplied}οντες και συνθρυπτοντες μου την καρδιαν εγω γ[α]{.unclear}[ρ]{.greek-supplied} ου μονον δεθηναι αλλα και αποθανειν [εις]{.greek-omitted} [ιερουσαλημ]{.greek-omitted} [ετοιμως]{.greek-omitted} [ετοιμος]{.greek-added} εχω υπερ του ονοματος του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr}[21:13]{.aside}

μη πειθομενου δε αυτου ησυχασαμεν ειποντες το θελημα του [κυριου]{.greek-abbr} γενε[σ]{.unclear}[θω]{.greek-supplied}[21:14]{.aside}

μετα δε τας ημερας ταυτας επισκευασαμενοι ανεβαινομεν εις ιερουσαλημ[21:15]{.aside}

συνηλθον δε και των μαθητων απο καισαρειας συν ημιν αγοντες παρ ω ξενισθωμεν [μνασωνι]{.greek-omitted} [μνασωννι]{.greek-added} τινι κυπριω αρχαιω μαθητη[21:16]{.aside}

γενομενων δε ημων εις [ιεροσολυμα]{.greek-omitted} [[ιερουσαλημ]{.greek-abbr}]{.greek-added} [ασμενως]{.greek-omitted} [ασμενος]{.greek-added} εδεξαντο ημας οι αδελφοι[21:17]{.aside}

τη δε [επιουση]{.greek-omitted} [εποιουση]{.greek-added} εισηει ο παυλος συν ημιν προς ιακωβον παντες τε παρεγενοντο οι πρεσβυτεροι[21:18]{.aside}

και ασπασαμενος αυτους εξηγειτο καθ εν εκαστον ων εποιησεν ο [θεος]{.greek-abbr} εν τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} δια της διακονιας αυτου[21:19]{.aside}

οι δε ακουσαντες εδοξαζον τον [κυριον]{.greek-abbr} ειποντες αυτω θεωρεις αδελφε ποσαι μυριαδες εισιν ιουδαιων των πεπιστευκοτων και παντες ζηλωται του νομου υπαρχουσιν[21:20]{.aside}

κατηχηθησαν δε περι σου οτι αποστασιαν διδασκεις απο [μωυσεως]{.greek-omitted} [μωυσεος]{.greek-added} τους κατα τα εθνη παντας ιουδαιους λεγων μη περιτεμνειν αυτους τα τεκνα μηδε τοις [εθεσιν]{.greek-omitted} [εθεσι]{.greek-added} περιπατειν[21:21]{.aside}

τι [ουν]{.greek-omitted} [γουν]{.greek-added} [εστιν]{.greek-omitted} [εστι]{.greek-added} παντως δει πληθος [συνελθειν]{.greek-omitted} [σανελθειν]{.greek-added} ακουσονται γαρ οτι εληλυθας[21:22]{.aside}

τουτο [ουν]{.greek-omitted} [γουν]{.greek-added} ποιησον ο σοι λεγομεν εισιν ημιν ανδρες τεσσαρες ευχην εχοντες εφ εαυτων[21:23]{.aside}

τουτους παραλαβων αγνισθητι συν αυτοις και δαπανησον επ αυτοις ινα [ξυρησωνται]{.greek-omitted} [ξυρησονται]{.greek-added} την κεφαλην και [γνωσιν]{.greek-omitted} [γνωσι]{.greek-added} παντες οτι ων κατηχηνται περι σου ουδεν εστιν αλλα στοιχεις και αυτος [φυλασσων]{.greek-added} τον νομον [φυλασσων]{.greek-omitted}[21:24]{.aside}

περι δε των πεπιστευκοτων εθνων ημεις επεστειλαμεν κριναντες μηδεν τοιουτον τηρειν αυτους ει μη φυλασσεσθαι αυτους το [τε]{.greek-omitted} ειδωλοθυτο[ν]{.unclear} και το αιμα και πνικτον και πορνειαν[21:25]{.aside}

τοτε ο παυλος παραλαβων τους ανδρας τη εχομενη ημερα συν αυτοις αγνισθεις εισηει εις το ιερον διαγγελλων την εκπληρωσιν των ημερων του αγνισμου εως ου προσηνεχθη υπερ ενος εκαστου αυτω[ν]{.unclear} η προσφορα[21:26]{.aside}

ως δε εμελλον αι επτα ημεραι [συντελεισθαι]{.greek-omitted} [τελ[ει]{.unclear}ουσθαι]{.greek-added} [θεασαμενοι]{.greek-added} [αυτον]{.greek-added} οι απο της ασιας ιουδαιοι [θεασαμενοι]{.greek-omitted} [αυτον]{.greek-omitted} εν τω ιερω συνεχεον παντα τον [οχλον]{.greek-omitted} [λαον]{.greek-added} και επεβαλον [επ]{.greek-added} [αυτον]{.greek-added} τας χειρας [επ]{.greek-omitted} [αυτον]{.greek-omitted}[21:27]{.aside}

κραζοντες ανδρ[ε]{.unclear}[ς]{.greek-supplied} ισραηλιται βοηθειτε ουτος εστιν ο [ανθρωπος]{.greek-abbr} ο κατα του λαου και του νομου και του τοπου τουτου παντας πα[ν]{.unclear}ταχου διδασκων ετι τε και ελληνας εισηγαγεν εις το ιερον και [κεκοινωκεν]{.greek-omitted} [κεκοινωκε]{.greek-added} τον αγιον τοπον τουτον[21:28]{.aside}

ησα[ν]{.unclear} γαρ [εωρακοτες]{.greek-omitted} [προεωρακοτες]{.greek-added} τροφιμον τον εφεσιον εν τη πολει συν αυτω ον ενομιζον οτι εις το ιερον εισηγαγεν ο παυλος[21:29]{.aside}

εκινηθη τε η πολις ολη και εγενετο συνδρομη του λαου και επιλαβομενοι του πα[υ]{.unclear}λου ειλκον αυτον εξω του ιερου και ευθεως εκλεισθησαν αι θυραι[21:30]{.aside}

ζητουντων δε αυτον αποκτειναι ανεβη φασις τω χιλιαρχω της [σπειρης]{.greek-omitted} [σπειρας]{.greek-added} οτι ολη συγκεχυται [ιερουσαλημ]{.greek-abbr}[21:31]{.aside}

ος εξαυτης παραλαβων στρατιωτας και εκατονταρχους κατεδραμεν επ αυτ[ους]{.greek-supplied} οι δε ιδοντες τον χιλιαρχον και τους στρατιωτας επαυσαντο τυπτοντες τον παυλον[21:32]{.aside}

[[τ]{.unclear}[ο]{.greek-supplied}[τε]{.unclear}]{.greek-added} εγγισας δε ο χιλιαρχος επελαβετο αυτου και [εκελευσεν]{.greek-omitted} [εκελευσε]{.greek-added} δεθηναι [αλυσεσιν]{.greek-omitted} [αλυσεσι]{.greek-added} [δυσιν]{.greek-omitted} [δυσι]{.greek-added} και επυνθανετο τις αν ειη και τι [εστιν]{.greek-omitted} [εστι]{.greek-added} πεποιηκως[21:33]{.aside}

αλλοι δε αλλο τι [εβοων]{.greek-omitted} [επεφωνουν]{.greek-added} εν τω οχλω μη δυναμενος δε γνωναι το ασφαλες δια τον θορυβον εκελευσεν αγεσθαι αυτον εις την παρεμβολην[21:34]{.aside}

οτε δε εγενετο επι τους αναβαθμους συνεβη βασταζεσθαι αυτον υπο των στρατιωτων δια την βιαν του οχλου[21:35]{.aside}

ηκολουθει γαρ το πληθος του [λαου]{.greek-omitted} [οχλου]{.greek-added} [κραζον]{.greek-omitted} [κραζων]{.greek-added} αιρε αυτον [απο]{.greek-added} [των]{.greek-added} [ζωντων]{.greek-added}[21:36]{.aside}

μελλων [τε]{.greek-omitted} [δε]{.greek-added} εισαγεσθαι εις την παρεμβολην ο παυλος λεγει τω χιλιαρχω ει [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} μοι ειπειν [τι]{.greek-added} προς σε ο δε εφη ελληνιστι γινωσκεις[21:37]{.aside}

ουκ αρα συ ει ο αιγυπτιος ο προ τουτων των ημερων αναστατωσας και εξαγαγων εις την ερημον τους τετρακισχιλιους ανδρας των σικαριων[21:38]{.aside}

ειπεν [δε]{.greek-omitted} [τε]{.greek-added} ο παυλος εγω [μεν]{.greek-added} [ανθρωπος]{.greek-abbr} [μεν]{.greek-omitted} ειμι ιουδαιος ταρσευς της κιλικιας ουκ ασημου πολεως πολιτης δεομαι δε σου επιτρεψον μοι λαλησαι προς τον λαον[21:39]{.aside}

επιτρεψαντος δε αυτου ο παυλος εστως επι των αναβαθμων [κατεσεισεν]{.greek-omitted} [κατεσεισε]{.greek-added} τη χειρι τω λαω πολλης δε σιγης γενομενης [προσεφωνει]{.greek-omitted} [προσεφωνησε]{.greek-added} τη εβρα[ι]{.unclear}δι διαλεκτω λεγων[21:40]{.aside}

### Chapter 22

ανδρες αδελφοι και [πατερες]{.greek-abbr} ακουσατε μου της προς υμας νυνι απολογιας[22:1]{.aside}

ακουσαντες δε οτι τη εβραιδι διαλεκτω [προσεφωνει]{.greek-omitted} [προσεφωνησεν]{.greek-added} αυτοις μαλλον παρεσχον ησυχιαν και φησιν[22:2]{.aside}

εγω με[ν]{.unclear} [ει]{.unclear}μι ανηρ ιουδαιος γεγεννημενος εν τ[α]{.unclear}[ρ]{.greek-supplied}σω της κιλικιας ανατεθραμμενος δε εν [τη]{.greek-omitted} π[ο]{.unclear}λει ταυτη παρα τους ποδας γαμαλιηλ πεπαιδε[υ]{.unclear}μενος κατα ακριβειαν του πατρωου νομου ζη[λω]{.greek-supplied}της υπαρχων του [θεου]{.greek-abbr} καθως παντες υμεις εστε ση[με]{.greek-supplied}ρον[22:3]{.aside}

ος ταυτην την οδον εδιωξα [αχρι]{.greek-omitted} [μεχρι]{.greek-added} θανατου δεσμε[υ]{.greek-supplied}ων και παραδιδους εις φυλακας ανδρας τε και γυναι[κ]{.unclear}[ας]{.greek-supplied}[22:4]{.aside}

ως και ο αρχιερευς [ανανιας]{.greek-added} [μαρτυρει]{.greek-omitted} [επιμαρτυρει]{.greek-added} μοι και π[αν]{.greek-supplied} το πρεσβυτεριον παρ ων και επιστολας δεξαμενος προς τους αδελφους εις δαμασκον επορευομην αξ[ω]{.unclear}[ν]{.greek-supplied} και τους εκεισε οντας δεδεμενους εις [ιερουσαλημ]{.greek-abbr} ινα τιμωρ[η]{.greek-supplied}θωσιν[22:5]{.aside}

εγενετο δε μοι πορευομενω και εγγιζοντι τ[η]{.unclear} [δα]{.greek-supplied}μασκω περι μεσημβριαν [εξαιφνης]{.greek-omitted} [εξεφνης]{.greek-added} εκ του [ουρανου]{.greek-abbr} [π]{.unclear}[ε]{.greek-supplied}ριαστραψαι φως ικανον περι εμε[22:6]{.aside}

[επεσα]{.greek-omitted} [επεσον]{.greek-added} τε ε[ι]{.unclear}[ς]{.greek-supplied} [το]{.greek-supplied} εδαφος και ηκουσα φωνης λεγουσης μοι σαουλ σ[α]{.unclear}[ουλ]{.greek-supplied} τι με διωκεις[22:7]{.aside}

εγω δε απεκριθην τις ει [κυριε]{.greek-abbr} ειπ[εν]{.greek-supplied} [τε]{.greek-supplied} προς με εγω ειμι [ιησους]{.greek-abbr} ο ναζωραιος ον συ διωκει[ς]{.unclear}[22:8]{.aside}

[οι]{.greek-supplied} δε συν εμοι οντες το μεν φως εθεασαντο και εμφο[βοι]{.greek-supplied} εγενοντο την δε φωνην ουκ ηκουσαν του λαλουντ[ος]{.greek-supplied} μοι[22:9]{.aside}

ειπον δε τι ποιησω [κυριε]{.greek-abbr} ο δε [κυριος]{.greek-abbr} ειπεν προ[ς]{.greek-supplied} [με]{.greek-supplied} αναστας πορευου εις δαμασκον κακει σοι λαλη[θ]{.unclear}[ησε]{.greek-supplied}ται περι παντων ων [τεκ]{.greek-added} [τετακται]{.corr} σοι ποιησαι[22:10]{.aside}

ως [δε]{.greek-supplied} ουκ ενεβλεπον απο της δοξης του φωτος εκεινου χειραγωγουμενος υπο των συνοντων μοι [ηλθον]{.greek-omitted} [εισηλθον]{.greek-added} εις δαμασκον[22:11]{.aside}

ανανιας δε τις ανηρ ευσεβης κατα τον νομον μαρτυρουμενος υπο παντων των κατοικουντων [εν]{.greek-added} [δαμασκω]{.greek-added} ιουδαιων[22:12]{.aside}

ελθων προς με και επιστας [ειπεν]{.greek-omitted} [ειπε]{.greek-added} μοι σαουλ αδελφε αναβλεψον καγω αυτη τη ωρα ανεβλεψα εις αυτον[22:13]{.aside}

ο δε ειπεν ο [θεος]{.greek-abbr} των [πατερων]{.greek-abbr} ημων προεχειρισατο σε γνωναι το [θελημα]{.greek-omitted} [θελημαν]{.greek-added} αυτου και ιδειν τον δικαιον και ακουσαι φωνην εκ του στοματος αυτου[22:14]{.aside}

οτι [εση]{.greek-omitted} [εσυ]{.greek-added} μαρτυς [αυτω]{.greek-omitted} [αυτου]{.greek-added} προς παντας [ανθρωπους]{.greek-abbr} ων εωρακας και ηκουσας[22:15]{.aside}

και νυν τι [μελλεις]{.greek-omitted} [μελεις]{.greek-added} αναστας βαπτισαι και απολουσαι τας αμαρτιας σου επικαλεσαμενος το ονομα του [κυριου]{.greek-abbr}[22:16]{.aside}

εγενετο δε μοι υποστρεψαντι εις [ιερουσαλημ]{.greek-abbr} και προσευχομενου μου εν τω ιερω γενεσθαι με εν εκστασει[22:17]{.aside}

και ιδειν αυτον λεγοντα μοι σπευσον [και]{.greek-omitted} εξελθε εν ταχει εξ [ιερουσαλημ]{.greek-abbr} διοτι ου παραδεξονται σου την μαρτυριαν περι εμου[22:18]{.aside}

καγω ειπον [κυριε]{.greek-abbr} αυτοι επιστανται οτι εγω ημην φυλακιζων και [δερων]{.greek-omitted} [δερρων]{.greek-added} κατα τας συναγωγας τους πιστευοντας επι σε[22:19]{.aside}

και οτε εξεχειτο το αιμα στεφανου του [μαρτυρος]{.greek-omitted} [πρωτομαρτυρος]{.greek-added} σου και αυτος ημην εφεστως και συνευδοκων τη [ανε]{.greek-added} [αναιρεσει]{.corr} αυτου φυλασσων τα ιματια των αναιρουντων αυτον[22:20]{.aside}

και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} προς με πορευου οτι εγω εις εθνη μακραν εξαποστελω σε[22:21]{.aside}

ηκουον δε αυτου αχρι [τουτου]{.greek-omitted} του λογου [τουτου]{.greek-added} και επηραν την φωνην αυτων λεγοντες αιρε απο της γης τον τοιουτον ου γαρ καθηκεν αυτον ζην[22:22]{.aside}

κραζοντων δε αυτων και ριπτουντων τα ιμ[ατια]{.greek-supplied} και κονιορτον βαλλοντων εις τον αερα[22:23]{.aside}

εκελευσεν [αυτον]{.greek-omitted} ο [χι]{.greek-supplied}λιαρχος αγεσθαι [αυτον]{.greek-added} εις την παρεμβολην [ειπων]{.greek-omitted} [ειπα[ς]{.unclear}]{.greek-added} μαστιξιν ανεταζεσθαι [αυτον]{.greek-omitted} ινα επιγνω δι ην αιτιαν [ο]{.unclear}[υ]{.greek-supplied}τως [επεφωνουν]{.greek-omitted} [αυτω]{.greek-omitted} [κατεφωνουν]{.greek-added} [αυτου]{.greek-added}[22:24]{.aside}

ως δε [προετεινεν]{.greek-omitted} [προετειναν]{.greek-added} [αυτον]{.greek-omitted} τοις [ι]{.greek-supplied}μασιν [αυτον]{.greek-added} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} προς τον εστωτα εκατονταρχον [ο]{.greek-omitted} [παυλος]{.greek-omitted} [ει]{.greek-supplied} [ανθρωπον]{.greek-abbr} ρωμαιον και ακατακριτον εξεστιν υμιν μα[σ]{.unclear}[τι]{.greek-supplied}ζειν[22:25]{.aside}

ακουσας δε ο εκατονταρχος προσελθων [απηγγειλεν]{.greek-omitted} τω χιλιαρχω [απηγκειλε]{.greek-added} λεγων ορα τι μελλεις ποιε[ιν]{.greek-supplied} ο γαρ [ανθρωπος]{.greek-abbr} ουτος ρωμαιος [εστιν]{.greek-omitted} [εστι]{.greek-added}[22:26]{.aside}

προσελθων δε ο χιλιαρχος [ει]{.greek-supplied}πεν αυτω λεγε μοι [ει]{.greek-omitted} συ ρωμαιος ει ο δε εφη ναι[22:27]{.aside}

απεκ[ρ]{.unclear}[ι]{.greek-supplied}θη [τε]{.greek-omitted} [δε]{.greek-added} ο χιλιαρχος εγω πολλου κεφαλαιου την πολιτει[αν]{.greek-supplied} ταυτην εκτησαμην ο δε παυλος εφη εγω δε και γεγε[ν]{.greek-supplied}νημαι[22:28]{.aside}

ευθεως ουν απεστησαν απ αυτου οι μελλοντες αυτον ανεταζειν και ο χιλιαρχος δε εφοβηθη επι[γνους]{.greek-supplied} οτι ρωμαιος εστιν και οτι ην αυτον δεδεκως[22:29]{.aside}

τη δε επ[αυ]{.greek-supplied}ριον βουλομενος γνωναι το ασφαλες το τι κατηγορει[ται]{.greek-supplied} [παρα]{.greek-omitted} [υπο]{.greek-added} των ιουδαιων [πεμψας]{.greek-added} ελυσεν αυτον α[π]{.unclear}[ο]{.greek-supplied} των δεσμων και εκελευσεν [ελθειν]{.greek-omitted} [συνεισελθειν]{.greek-added} τους α[ρ]{.unclear}[χι]{.greek-supplied}ερεις και ολον το συνεδριον αυτων και καταγαγων τον [παυ]{.greek-supplied}λον εστησεν εις αυτους[22:30]{.aside}

### Chapter 23

ατενισας δε ο παυλος τω συνεδριω ειπεν ανδρες αδελφοι εγ[ω]{.unclear} παση συνειδησει αγαθη πεπολιτευμαι τω [θεω]{.greek-abbr} αχρι [ταυτης]{.greek-omitted} της ημερας [ταυτης]{.greek-added}[23:1]{.aside}

ο δε αρχιερευς [ανανιας]{.greek-omitted} [ανανοιας]{.greek-added} [επεταξεν]{.greek-omitted} [επεταξε]{.greek-added} τοις παρεστωσιν αυτω τυπτειν αυτου το στομα[23:2]{.aside}

τοτε ο παυλος προς αυτον ειπεν τυπτειν σε μελλει ο [θεος]{.greek-abbr} τοιχε κεκονιαμενε και συ καθη [κρινων]{.greek-omitted} [κρινον]{.greek-added} με κατα τον νομον και παρανομων κελευεις με τυπτεσθαι[23:3]{.aside}

οι δε παρεστωτες ειπον τον [αρχιερεα]{.greek-omitted} [αρχιερεαν]{.greek-added} του [θεου]{.greek-abbr} λοιδορεις[23:4]{.aside}

εφη [τε]{.greek-omitted} [δε]{.greek-added} ο παυλος ουκ ηδειν αδελφοι οτι [εστιν]{.greek-omitted} αρχιερευς [εστι]{.greek-added} γεγραπται γαρ αρχοντα του λαου σου ουκ ερεις κακως[23:5]{.aside}

γνους δε ο παυλος οτι το εν μερος εστιν σαδδουκαιων το δε ετερον φαρισαιων [εκραξεν]{.greek-omitted} [εκραζεν]{.greek-added} εν τω συνεδριω ανδρες αδελφοι εγω φαρισαιος ειμι υιος φαρισαιου περι ελπιδος και αναστασεως νεκρων εγω κρινομαι[23:6]{.aside}

τουτο δε αυτου λαλησαντος εγενετο στασις των [σαδδουκαιων]{.greek-added} [και]{.greek-added} [των]{.greek-added} φαρισαιων και εσχισθη το πληθος[23:7]{.aside}

σαδδουκαιοι μεν γαρ λεγουσιν μη ειναι αναστασιν [μηδε]{.greek-omitted} [μητε]{.greek-added} αγγελον μητε [πνευμα]{.greek-abbr} φαρισαιοι δε [ομολογουσιν]{.greek-omitted} [ομολογουσι]{.greek-added} τα αμφοτερα[23:8]{.aside}

εγενετο δε κραυγη μεγαλη και ανασταντες [οι]{.greek-omitted} γραμματεις του μερους των φαρισαιων διεμαχοντο λεγοντες ουδεν κακον ευρισκομεν εν τω [ανθρωπω]{.greek-abbr} τουτω ει δε [πνευμα]{.greek-abbr} ελαλησεν αυτω η αγγελος μη θεομαχωμεν[23:9]{.aside}

πολλης δε γενομενης στασεως ευλαβηθεις ο χιλιαρχος μη διασπασθη ο παυλος υπ αυτων [εκελευσεν]{.greek-omitted} [εκελευσε]{.greek-added} το στρατευμα καταβηναι και αρπασαι αυτον εκ μεσου αυτων αγειν τε εις την παρεμβολην[23:10]{.aside}

τη δε επιουση [νυ]{.greek-added} [νυκτι]{.greek-omitted} [κτι]{.greek-added} επιστας αυτω ο [κυριος]{.greek-abbr} ειπεν θαρσει παυλε ως γ[α]{.unclear}[ρ]{.greek-supplied} διεμαρτυρω τα περι εμου εις [ιερουσαλημ]{.greek-abbr} ουτως σε δει και εις ρωμην μαρτυρησαι[23:11]{.aside}

γενομενης δε ημερ[α]{.unclear}[ς]{.greek-supplied} ποιησαντες τινες των ιουδαιων συστροφην ανεθ[ε]{.greek-supplied}ματισαν εαυτους [λεγοντες]{.greek-omitted} μητε φαγειν μητε [πιειν]{.greek-omitted} [ποιειν]{.greek-added} εως ο[υ]{.unclear} [αποκτεινωσιν]{.greek-omitted} [αποκτεινωσι]{.greek-added} τον παυλον[23:12]{.aside}

ησαν δε πλειους τεσσαρακοντα οι ταυτην την [συνωμοσιαν]{.greek-omitted} [συνομοσιαν]{.greek-added} πεποιηκοτες[23:13]{.aside}

οιτ[ι]{.greek-supplied}νες προσελθοντες τοις [αρχιερευσιν]{.greek-omitted} [αρχιερευσι]{.greek-added} και τοις πρεσβυτεροις ειπον αναθεματι ανεθεματισαμεν εαυτο[υ]{.unclear}[ς]{.greek-supplied} μηδενος γευσασθαι εως ου [αποκτεινωμεν]{.greek-omitted} [αποκτεινομεν]{.greek-added} τον παυλ[ον]{.greek-supplied}[23:14]{.aside}

νυν ουν υμεις εμφανισατε τω χιλιαρχω συν [ολω]{.greek-added} τω συνεδριω οπως αυριον [καταγαγη]{.greek-added} αυτον [καταγαγη]{.greek-omitted} προς υμας ω[ς]{.greek-supplied} μελλοντας [ακριβεστερον]{.greek-added} διαγινωσκειν [ακριβεστερον]{.greek-omitted} τα περι αυτου ημεις δε προ του εγγισαι αυτον ετοιμοι εσμεν του αν[ε]{.greek-supplied}λειν αυτον [εαν]{.greek-added} [δεη]{.greek-added} [και]{.greek-added} [αποθανειν]{.greek-added}[23:15]{.aside}

ακουσας δε ο υιος της αδελφης παυλου το ενεδρον παραγενομενος και εισελθων εις την παρεμβολην [απηγγειλεν]{.greek-omitted} [απηγγειλε]{.greek-added} τω πα[υ]{.greek-supplied}λω[23:16]{.aside}

προσκαλεσαμενος δε ο παυλος ενα των εκατονταρχων εφη τον [νεανιαν]{.greek-omitted} [νεανισκον]{.greek-added} τουτον απαγαγε προ[ς]{.unclear} τον χιλιαρχον εχει γαρ τι απαγγειλαι αυτω[23:17]{.aside}

ο μεν ο[υν]{.greek-supplied} παραλαβων αυτον [ηγαγεν]{.greek-omitted} [ηγαγε]{.greek-added} προς τον χιλιαρχον και φ[η]{.unclear}σιν ο δεσμιος παυλος προσκαλεσαμενος με [ηρωτησεν]{.greek-omitted} [ηρωτ[η]{.greek-supplied}σε]{.greek-added} [τουτον]{.greek-omitted} τον νεανιαν [τουτον]{.greek-added} αγαγειν προς σε εχοντα τι [λ]{.unclear}[α]{.greek-supplied}λησαι σοι[23:18]{.aside}

επιλαβομενος δε της χειρος αυτου [ο]{.greek-supplied} χιλιαρχος και αναχωρησας κατ ιδιαν επυνθανετο τι εστιν ο εχεις απαγγειλαι μοι[23:19]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε οτι οι ιουδαιοι συνεθεντο του ερωτησαι σε οπως αυριον [καταγαγης]{.greek-added} [τον]{.greek-added} [παυλον]{.greek-added} εις το συνεδριον [καταγαγης]{.greek-omitted} [τον]{.greek-omitted} [παυλον]{.greek-omitted} ως [μελλοντα]{.greek-omitted} [μελλων]{.greek-added} τι ακριβεστερον πυνθανεσθαι περι αυτου[23:20]{.aside}

συ [ουν]{.greek-omitted} [γουν]{.greek-added} μη πεισθης αυτοις [ενεδρευουσιν]{.greek-omitted} [ενεδρευουσι]{.greek-added} γαρ αυτον εξ αυτων ανδρες πλειους τεσσαρακοντα οιτινες ανεθεματισαν εαυτους μητε φαγειν μητε [πιειν]{.greek-omitted} [ποιειν]{.greek-added} εως ου ανελωσιν αυτον και νυν ετοιμοι [εισιν]{.greek-omitted} [εισι]{.greek-added} προσδεχομενοι την απο σου επαγγελιαν[23:21]{.aside}

ο μεν ουν χιλιαρχος [απελυσεν]{.greek-omitted} [απελυσε]{.greek-added} τον νεανιαν παραγγειλας μηδενι εκλαλησαι οτι ταυτα ενεφανισας προς με[23:22]{.aside}

και προσκαλεσαμενος δυο τινας των εκατονταρχων ειπεν ετοιμασατε στρατιωτας διακοσιους οπως πορευθωσιν εως καισαρειας και [ιππεις]{.greek-omitted} [ιπεις]{.greek-added} εβδομηκοντα και δεξιολαβους διακοσιους απο τριτης ωρας της νυκτος[23:23]{.aside}

κτηνη τε παραστησαι ινα επιβιβασαντες τον παυλον διασωσωσιν [εις]{.greek-added} [καισαρειαν]{.greek-added} προς [φηλικα]{.greek-omitted} [φιλικα]{.greek-added} τον ηγεμονα[23:24]{.aside}

[γραψας]{.greek-omitted} [εφοβηθη]{.greek-added} [γαρ]{.greek-added} [ο]{.greek-added} [χιλιαρχος]{.greek-added} [μηποτε]{.greek-added} [αρπασαντες]{.greek-added} [τον]{.greek-added} [παυλον]{.greek-added} [οι]{.greek-added} [ιουδαιοι]{.greek-added} [αποκτεινωσι]{.greek-added} [και]{.greek-added} [αυτος]{.greek-added} [μεταξυ]{.greek-added} [εγκλημα]{.greek-added} [σχη]{.greek-added} [ως]{.greek-added} [αργυριον]{.greek-added} [ειληφως]{.greek-added} [εγραψε]{.greek-added} [δε]{.greek-added} [και]{.greek-added} επιστολην [περιεχουσαν]{.greek-omitted} [περιεχουσα]{.greek-added} τον τυπον τουτον[23:25]{.aside}

κλαυδιος λυσιας τω κρατιστω ηγεμονι [φηλικι]{.greek-omitted} [φιλικι]{.greek-added} χαιρειν[23:26]{.aside}

τον ανδρα τουτον συλληφθεντα υπο των ιουδαιων και μελλοντα αναιρεισθαι υπ αυτων επιστας συν τω στρατευματι εξειλομην αυτον μαθων οτι ρωμαιος εσ[τιν]{.greek-supplied}[23:27]{.aside}

βουλομενος δε γνωναι την αιτιαν δι ην ενεκαλουν αυ[τ]{.unclear}[ω]{.greek-supplied} κατηγαγον αυτον εις το συνεδριον αυτων[23:28]{.aside}

ον ευρον [ε]{.unclear}[γκα]{.greek-supplied}λουμενον περι ζητηματων του νομου αυτων [μωυσ[ε]{.unclear}ος]{.greek-added} [και]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} [τινος]{.greek-added} μηδεν [δε]{.greek-added} αξιον θανατου η δεσμ[ω]{.unclear}[ν]{.greek-supplied} [εχοντα]{.greek-added} εγκλημα [εχοντα]{.greek-omitted} [εξηγαγον]{.greek-added} [αυτον]{.greek-added} [μολις]{.greek-added} [τη]{.greek-added} [β[ι]{.greek-supplied}α]{.greek-added}[23:29]{.aside}

μηνυθεισης δε μοι επιβουλης εις τον α[ν]{.unclear}δρα [μελλειν]{.greek-omitted} εσεσθαι υπο των ιουδαιων εξαυτης επ[ε]{.unclear}μψα προς σε παραγγειλας και [τοις]{.greek-omitted} [της]{.greek-added} [κατηγοροις]{.greek-omitted} [κατηγ[ορης]{.greek-supplied}]{.greek-added} λεγειν τα προς αυτον επι σου ερρωσο[23:30]{.aside}

οι μ[εν]{.greek-supplied} ουν στρατιωται κατα το διατεταγμενον αυτοις αναλαβοντες τον παυλον ηγαγον δια [της]{.greek-omitted} νυκτος εις την αντ[ι]{.greek-supplied}πατριδα[23:31]{.aside}

τη δε επαυριον εασαντες τους ιπ[π]{.unclear}[εις]{.greek-supplied} πορευεσθαι συν αυτω υπεστρεψαν εις την παρεμ[β]{.unclear}[ο]{.greek-supplied}λην[23:32]{.aside}

οιτινες εισελθοντες εις την καισαρειαν κα[ι]{.greek-supplied} αναδοντες την επιστολην τω ηγεμονι παρεστ[ησα]{.unclear}[ν]{.greek-supplied} και τον παυλον αυτω[23:33]{.aside}

αναγνους δε [την]{.greek-added} [επιστολην]{.greek-added} ο η[γ]{.unclear}[ε]{.greek-supplied}μων [και]{.greek-omitted} [επερωτησας]{.greek-omitted} [επερωτησε]{.greek-added} [τον]{.greek-added} [παυλον]{.greek-added} εκ ποιας [επαρχιας]{.greek-omitted} [επαρχ[ειας]{.greek-supplied}]{.greek-added} [εστιν]{.greek-omitted} [ει]{.greek-added} [εφη]{.greek-added} [κιλιξ]{.greek-added} και πυθομενος [εφη]{.greek-added} [οτι]{.greek-omitted} [απο]{.greek-omitted} [κιλικιας]{.greek-omitted}[23:34]{.aside}

[διακουσομαι]{.greek-omitted} [ακουσομαι]{.greek-added} [σ]{.unclear}[ου]{.greek-supplied} [εφη]{.greek-omitted} οταν [η]{.greek-added} [και]{.greek-omitted} [οι]{.greek-omitted} κατηγοροι σου [παραγενωνται]{.greek-omitted} [παραγενονται]{.greek-added} [εκελευσεν]{.greek-omitted} [εκελευσε]{.greek-added} τ[ε]{.greek-supplied} αυτον εν τω [πραιτωριω]{.greek-omitted} [πραιτωρειω]{.greek-added} ηρωδου φυλασσεσθαι[23:35]{.aside}

### Chapter 24

μετα δε πεντε ημερας κατεβη ο αρχιερευ[ς]{.unclear} [α]{.greek-supplied}νανιας μετα [των]{.greek-omitted} πρεσβυτερων [τινων]{.greek-added} και ρητορος [τ]{.unclear}[ερ]{.greek-supplied}τυλλου [τινος]{.greek-omitted} οιτινες ενεφανισαν τω ηγεμονι κα[τ]{.unclear}[α]{.greek-supplied} του παυλου[24:1]{.aside}

κληθεντος δε αυτου ηρξατο κατηγορειν ο τερτυλλος λεγων πολλης ειρηνης τυγχανοντες δια σου και κατορθωματων γινομενων τω εθνει τουτω δια της σης προνοιας[24:2]{.aside}

παντη τε και πανταχου αποδεχομεθα κρατιστε [φηλιξ]{.greek-omitted} [φιλιξ]{.greek-added} μετα πασης ευχαριστιας[24:3]{.aside}

ινα δε μη επι πλειον σε εγκοπτω παρακαλω ακουσαι σε ημων συντομως τη ση επιεικεια[24:4]{.aside}

ευροντες [γαρ]{.greek-omitted} τον ανδρα τουτον [λοιμον]{.greek-omitted} [λυμον]{.greek-added} και κινουντα στασιν πασιν τοις ιουδαιοις τοις κατα την οικουμενην πρωτοστατην [τε]{.greek-omitted} [δε]{.greek-added} της των ναζωραιων αιρεσεως[24:5]{.aside}

ος και το ιερον [επειρασεν]{.greek-omitted} [επειρασε]{.greek-added} βεβηλωσαι ον και εκρατησαμεν [και]{.greek-added} [κατα]{.greek-added} [τον]{.greek-added} [ημετερον]{.greek-added} [νομον]{.greek-added} [ηθελησαμεν]{.greek-added} [κρινειν]{.greek-added}[24:6]{.aside}

[παρελθων]{.greek-added} [δε]{.greek-added} [λυσιας]{.greek-added} [ο]{.greek-added} [χιλιαρχος]{.greek-added} [μετα]{.greek-added} [πολλης]{.greek-added} [βιας]{.greek-added} [εκ]{.greek-added} [των]{.greek-added} [χειρων]{.greek-added} [ημων]{.greek-added} [απηγαγε]{.greek-added} [κελευσας]{.greek-added} [τους]{.greek-added} [κατηγορους]{.greek-added} [αυτου]{.greek-added} [ερχεσθαι]{.greek-added} [επι]{.greek-added} [σου]{.greek-added}[24:7]{.aside}

παρ ου [δυνηση]{.greek-omitted} [δυνησει]{.greek-added} αυτος ανακρινας περι παντων τουτων επιγνωναι ων ημεις κατηγορουμεν αυτου[24:8]{.aside}

[ειποντος]{.greek-added} [δε]{.greek-added} [αυτου]{.greek-added} [ταυτα]{.greek-added} συνεπεθεντο [δε]{.greek-omitted} και οι ιουδαιοι φασκοντες ταυτα ουτως εχειν[24:9]{.aside}

απεκριθη δε ο παυλος νευσαντος αυτω του ηγεμονος [λεγειν]{.greek-omitted} [λαλειν]{.greek-added} εκ πολλων ετων οντα σε κριτην [δικαιον]{.greek-added} τω εθνει τουτω επισταμενος [ευθυμοτερον]{.greek-omitted} [ευθυμως]{.greek-added} τα περι εμαυτου απολογουμαι[24:10]{.aside}

δυναμενου σου [γνωναι]{.greek-omitted} [επιγνωναι]{.greek-added} οτι ου πλειους [εισιν]{.greek-omitted} [εισι]{.greek-added} μοι ημεραι δεκαδυο αφ ης ανεβην προσκυνησων εν [ιερουσαλημ]{.greek-omitted} [[ιλημ]{.greek-abbr}]{.greek-added}[24:11]{.aside}

και ουτε εν τω ιερω ευρον με προς τινα διαλεγομενον η επισυστασιν ποιουντα οχλου ουτε εν ταις συναγωγαις ουτε κατα την πολιν[24:12]{.aside}

ουτε παραστησαι [με]{.greek-omitted} [δυνανται]{.greek-omitted} [δυναντε]{.greek-added} περι ων νυν [κατηγορουσιν]{.greek-omitted} [κατηγορουσι]{.greek-added} μου[24:13]{.aside}

ομολογω δε τουτο σοι οτι κατα την οδον ην λεγουσιν αιρεσιν ουτως λατρευω τω πατρωω [θεω]{.greek-abbr} πιστευων [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις κατα τον νομον και τοις [εν]{.greek-added} [τοις]{.greek-added} προφηταις γεγραμμενοις[24:14]{.aside}

ελπιδα εχων εις τον [θεον]{.greek-abbr} ην και αυτοι ουτοι [προσδεχονται]{.greek-omitted} [εκδεχονται]{.greek-added} αναστασιν μελλειν εσεσθαι νεκρων δικαιων τε και αδικων[24:15]{.aside}

εν τουτω [δε]{.greek-omitted} [και]{.greek-added} αυτος ασκω απροσκοπον συνειδησιν εχων [δια]{.greek-added} [παντος]{.greek-added} προς [τε]{.greek-added} τον [θεον]{.greek-abbr} και [προς]{.greek-added} τους [ανθρωπους]{.greek-abbr} [δια]{.greek-omitted} [παντος]{.greek-omitted}[24:16]{.aside}

δι ετων δε πλειονων παρεγενομην ελεημοσυνας [ποιησων]{.greek-omitted} [ποιησον]{.greek-added} εις το εθνος μου και προσφορας[24:17]{.aside}

εν οις ευρον με ηγνισμενον εν τω ιερω ου μετα οχλου ουδε μετα θορυβου [τινες]{.greek-omitted} [απο]{.greek-omitted} [της]{.greek-omitted} [ασιας]{.greek-omitted} [ιουδαιοι]{.greek-omitted}[24:18]{.aside}

[τινες]{.greek-added} [δε]{.greek-added} [των]{.greek-added} [απο]{.greek-added} [της]{.greek-added} [ασιας]{.greek-added} [ιουδαιων]{.greek-added} ους [η]{.greek-added} [δει]{.greek-omitted} [[εδει]{.corr}]{.greek-added} επι σου παρειναι και κατηγορειν ει τι [εχοιεν]{.greek-omitted} [εχειεν]{.greek-added} προς με[24:19]{.aside}

η αυτοι ουτοι ειπατωσαν τι ευρον εν εμοι αδικημα σταντος μου επι του συνεδριου[24:20]{.aside}

η περι μιας ταυτης φωνης ης εκραξα εστως εν αυτοις οτι περι αναστασεως νεκρων εγω [κρινομαι]{.greek-omitted} σημερον [κρινομε]{.greek-added} υφ υμων[24:21]{.aside}

ακουσας δε ταυτα ο [φηλιξ]{.greek-omitted} [φιλιξ]{.greek-added} ανεβαλετο αυτους ακριβεστερον ειδως τα περι της οδου ειπων οταν λυσιας ο χιλιαρχος καταβη [διαγνωσομαι]{.greek-omitted} [διαγνωσομε]{.greek-added} τα καθ υμας[24:22]{.aside}

διαταξαμενος [τε]{.greek-omitted} τω εκατονταρχη τηρεισθαι [τον]{.greek-omitted} [αυτον]{.greek-added} [παυλον]{.greek-omitted} εχειν τε ανεσιν και μηδενα κωλυειν των ιδιων αυτου υπηρετειν η προσερχεσθαι αυτω[24:23]{.aside}

μετα δε [τινας]{.greek-added} ημερας [τινας]{.greek-omitted} παραγενομενος ο [φηλιξ]{.greek-omitted} [φιλιξ]{.greek-added} συν δρουσιλλη τη γυναικι ουση ιουδαια μετεπεμψατο τον παυλον και [ηκουσεν]{.greek-omitted} [ηκουσε]{.greek-added} [παρ]{.greek-added} αυτου περι της εις [χριστον]{.greek-abbr} πιστεως[24:24]{.aside}

διαλεγομενου δε αυτου περι δικαιοσυνης και εγκρατειας και του κριματος του μελλοντος [εσεσθαι]{.greek-omitted} εμφοβος γενομενος ο [φηλιξ]{.greek-omitted} [φιλιξ]{.greek-added} απεκριθη το νυν εχον πορευου καιρον δε μεταλαβων μετακαλεσομαι σε[24:25]{.aside}

αμα [και]{.greek-omitted} ελπιζων οτι [και]{.greek-added} χρηματα [αυτω]{.greek-added} δοθησεται [αυτω]{.greek-omitted} υπο του παυλου οπως λυση αυτον διο και πυκνοτερον αυτον μεταπεμπομενος ωμιλει αυτω[24:26]{.aside}

διετιας δε πληρωθεισης [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added} διαδοχον ο [φηλιξ]{.greek-omitted} [φιλιξ]{.greek-added} πορκιον φηστον [τον]{.greek-added} [δε]{.greek-added} [παυλον]{.greek-added} [ειασεν]{.greek-added} [εν]{.greek-added} [τηρησει]{.greek-added} [δια]{.greek-added} [δρουσιλλαν]{.greek-added} θελων [τε]{.greek-omitted} [χαριτας]{.greek-omitted} [δε]{.greek-added} [χαριν]{.greek-added} καταθεσθαι τοις ιουδαιοις ο [φηλιξ]{.greek-omitted} [φιλιξ]{.greek-added} [κατελιπεν]{.greek-omitted} [κατελοιπεν]{.greek-added} τον παυλον δεδεμενον[24:27]{.aside}

### Chapter 25

φηστος ουν επιβας τη επαρχια μετα τρεις ημερας ανεβη εις ιεροσολυμα απο καισαρειας[25:1]{.aside}

ενεφανισαν δε αυτω [ο]{.greek-omitted} [οι]{.greek-added} [αρχιερευς]{.greek-omitted} [αρχιερεις]{.greek-added} και οι πρωτοι των ιουδαιων κατα του παυλου και παρεκαλουν αυτον[25:2]{.aside}

αιτουμενοι χαριν κατ αυτου οπως μεταπεμψηται αυτον εις [ιερουσαλημ]{.greek-abbr} [ενεδραν]{.greek-omitted} [ενεδρον]{.greek-added} ποιουντες ανελειν αυτον κατα την οδον[25:3]{.aside}

ο μεν ουν φηστος απεκριθη τηρεισθαι τον παυλον εν καισαρεια εαυτον δε μελλειν εν ταχει εκπορευεσθαι[25:4]{.aside}

οι [ουν]{.greek-omitted} [γουν]{.greek-added} δυνατοι εν υμιν [φησιν]{.greek-omitted} [φησι]{.greek-added} συγκαταβαντες ει τι εστιν εν τω ανδρι τουτω [ατοπον]{.greek-added} κατηγορειτωσαν αυτου[25:5]{.aside}

διατριψας δε εν αυτοις ημερας πλειους η δεκα καταβας εις καισαρειαν [και]{.greek-added} τη επαυριον καθισας επι του βηματος [εκελευσεν]{.greek-omitted} [εκελευσε]{.greek-added} τον παυλον αχθηναι[25:6]{.aside}

παραγενομενου δε αυτου περιεστησαν οι απο ιεροσολυμων [καταβεβηκοτες]{.greek-omitted} [καταβαντες]{.greek-added} ιουδαιοι πολλα και βαρεα [αιτιωματα]{.greek-omitted} [αιτιαματα]{.greek-added} φεροντες κατα του παυλου α ουκ ισχυον αποδειξαι[25:7]{.aside}

[του]{.greek-added} [παυλου]{.greek-added} απολογουμενου [αυτου]{.greek-omitted} οτι ουτε εις τον νομον [των]{.greek-omitted} [ιουδαιων]{.greek-omitted} ουτε εις το ιερον ουτε εις καισαρα τι ημαρτον[25:8]{.aside}

ο φηστος δε [θελων]{.greek-added} τοις ιουδαιοις [θελων]{.greek-omitted} χαριν καταθεσθαι αποκριθεις τω παυλω [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [θελεις]{.greek-omitted} [θελης]{.greek-added} εις ιεροσολυμα αναβας εκει περι τουτων κρινεσθαι [επ]{.greek-omitted} [υπ]{.greek-added} εμου[25:9]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε ο παυλος επι του βηματος καισαρος εστως ειμι ου με δει κρινεσθαι ιουδαιο[υ]{.unclear}[ς]{.greek-supplied} [ουδεν]{.greek-omitted} [ουκ]{.greek-added} ηδικησα ως και συ [καλλιον]{.greek-omitted} [καλιον]{.greek-added} [επιγινωσκεις]{.greek-omitted} [γινωσκεις]{.greek-added}[25:10]{.aside}

ει μεν γα[ρ]{.unclear} αδικω και αξιον θανατου πεπραχα τι ου [παραιτουμαι]{.greek-omitted} [παρετουμαι]{.greek-added} το αποθανειν ει δε ουδεν εστιν ων ουτοι [κατηγορουσιν]{.greek-omitted} [κατοιγορουσι]{.greek-added} μου ουδεις με [δυναται]{.greek-omitted} [δυνατε]{.greek-added} αυτοις χαρισασθαι καισαρα επικαλουμαι[25:11]{.aside}

τοτε ο φηστος συλλαλησας μετα του συμβουλιου απεκριθη καισαρα επικεκλησαι επι καισαρα πορευση[25:12]{.aside}

ημερων δε διαγενομενων τιν[ων]{.unclear} αγριππας ο βασιλευς και βερνικη κατηντησαν εις καισαρειαν ασπασαμενοι τον φηστον[25:13]{.aside}

ως δε πλειους ημερας [διετριβεν]{.greek-omitted} [διετριβον]{.greek-added} εκει ο φηστος τω βασιλει ανεθετο τα κατα τον παυλον λεγων ανηρ τις εστιν καταλελειμμενος υπο [φηλικος]{.greek-omitted} [φιλικος]{.greek-added} δεσμιος[25:14]{.aside}

περι ου γενομενου μου εις ιεροσολυμα ενεφανισαν οι αρχιερεις και οι πρεσβυτεροι των ιουδαιων αιτουμενοι κατ αυτου δικην[25:15]{.aside}

προς ους απεκριθην οτι ουκ εστιν εθος ρωμαιοις χαριζεσθαι τινα [ανθρωπον]{.greek-abbr} εις απωλειαν πριν η ο κατηγορουμενος κατα προσ[ω]{.unclear}πον εχοι τους κατηγορους τοπον τε απολογιας λαβοι περι του εγκληματος[25:16]{.aside}

συνελθοντων ουν [ενθαδε]{.greek-added} αυτων [ενθαδε]{.greek-omitted} αναβολην μηδεμιαν ποιησαμενος τη εξης καθισας επι του βηματος εκελευσα αχθηναι τον ανδρα[25:17]{.aside}

περι ου σταθεντες οι κατηγοροι ουδεμιαν αιτιαν [επεφερον]{.greek-omitted} [εφερον]{.greek-added} ων υπενοουν εγω [πονηραν]{.greek-added}[25:18]{.aside}

ζητηματα δε τινα περι της ιδιας δεισιδαιμονιας ειχον προς αυτον και περι τινος [ιησου]{.greek-abbr} τεθνηκοτος ον εφασκεν ο παυλος ζην[25:19]{.aside}

απορουμενος δε εγω [εις]{.greek-added} την [τουτων]{.greek-added} [περι]{.greek-omitted} [τουτου]{.greek-omitted} ζητησιν ελεγον ει βουλοιτο [πορευεσθαι]{.greek-omitted} [πορευθηναι]{.greek-added} εις [ιερουσαλημ]{.greek-omitted} [ιεροσολυμα]{.greek-added} κακει κρινεσθαι περι τουτων[25:20]{.aside}

του δε παυλου επικαλεσαμενου τηρηθηναι αυτον εις την του σεβαστου διαγνωσιν εκελευσα [αυτον]{.greek-added} τηρεισθαι [αυτον]{.greek-omitted} εως ου πεμψω αυτον προς καισαρα[25:21]{.aside}

αγριππας δε προς τον φηστον εφη εβουλομην και αυτος του [ανθρωπου]{.greek-abbr} ακουσαι ο δε αυριον φησιν ακουση αυτου[25:22]{.aside}

τη [ουν]{.greek-omitted} [γουν]{.greek-added} επαυριον ελθοντος του αγριππα και της βερνικης μετα πολλης φαντασιας και εισελθοντων εις το ακροατηριον συν τε τοις χιλιαρχοις και [ανδρασιν]{.greek-omitted} [ανδρασι]{.greek-added} τοις κατ εξοχην [ουσιν]{.greek-omitted} [ουσι]{.greek-added} της πολεως και κελευσαντος του φηστου ηχθη ο παυλος[25:23]{.aside}

και φησιν ο φηστος αγριππα βασιλευ και παντες οι συμπαροντες ημιν ανδρες θεωρειτε τουτον περι [ου]{.greek-omitted} [τουτου]{.greek-added} [παν]{.greek-omitted} [απαν]{.greek-added} το πληθος των ιουδαιων ενετυχον μοι εν τε ιεροσολυμοις και ενθαδε επιβοωντες μη δειν ζην αυτον μηκετι[25:24]{.aside}

εγω δε [καταλαβομενος]{.greek-omitted} [κατελαβομενος]{.greek-added} μηδεν αξιον θανατου [πεπραχεναι]{.greek-added} αυτον [πεπραχεναι]{.greek-omitted} και αυτου δε τουτου επικαλεσαμενου τον σεβαστον εκρινα πεμπειν αυτον[25:25]{.aside}

περι ου ασφαλες τι γραψαι τω κυριω ουκ εχω διο προηγαγον αυτον εφ υμων και μαλιστα επι σου βασιλευ αγριππα οπως της ανακρισεως γενομενης σχω τι γραψαι[25:26]{.aside}

αλογον γαρ μοι δοκει πεμποντα δεσμιον μη και τας κατ αυτου αιτιας σημαναι[25:27]{.aside}

### Chapter 26

αγριππας δε προς τον παυλ[ον]{.greek-supplied} εφη επιτρεπεται σοι υπερ σεαυτου λεγειν τοτε ο παυλος απελογειτο εκτεινας την χειρα[26:1]{.aside}

περι π[αντων]{.greek-supplied} ων εγκαλουμαι υπο ιουδαιων βασιλευ [αγριππα]{.greek-omitted} [αγριπα]{.greek-added} ηγημαι εμαυτον μακαριον [μελλων]{.greek-added} επι σου [μελλων]{.greek-omitted} απολογεισθαι σημερον[26:2]{.aside}

μαλιστα γνωστην οντα σε [παντων]{.greek-omitted} των κατα ιουδαιους [ηθων]{.greek-omitted} [εθων]{.greek-added} τε και ζητηματων [επισταμενος]{.greek-added} διο δεομαι σου μακροθυμως ακουσαι μου[26:3]{.aside}

την μεν ουν βιωσιν μου την εκ [ν]{.unclear}εοτητος την απ αρχης γενομενην εν τω εθνει μου εν ιεροσολυμοις [ισασιν]{.greek-omitted} [ισασι]{.greek-added} παντες οι ιουδαιοι[26:4]{.aside}

προγινωσκοντες [με]{.greek-omitted} ανωθεν εαν [θελωσιν]{.greek-omitted} [θελωσι]{.greek-added} μαρτυρειν οτι κατα την ακριβεστατην αιρεσιν της ημετερας θρησκειας εζησα φαρισαιος[26:5]{.aside}

και νυν επ ελπιδι της προς τους [πατερας]{.greek-abbr} [ημων]{.greek-added} [γενομενης]{.greek-added} επαγγελιας [γενομενης]{.greek-omitted} υπο του [θεου]{.greek-abbr} εστηκα [κ]{.unclear}ρινομενος[26:6]{.aside}

εις ην το δωδεκαφυλον ημων εν εκτενεια νυκτα και ημεραν λατρευον ελπιζει [κα]{.greek-added} [καταντησαι]{.greek-omitted} [ταντησαι]{.greek-added} περι ης ελπιδος εγκαλουμαι βασιλευ αγριππα υπο ιουδαιων[26:7]{.aside}

τι απιστον κρινεται παρ υμιν ει ο [θεος]{.greek-abbr} νεκρους εγειρει[26:8]{.aside}

εγω μεν ουν εδοξα εμαυτω προς το ονομα [ιησου]{.greek-abbr} του ναζωραιο[υ]{.unclear} δειν πολλα εναντια πραξαι[26:9]{.aside}

ο και εποιησα εν ιεροσολυμοις και πολλους των αγιων εγω [εν]{.greek-added} φυλακαις κατεκλεισα την παρα των αρχιερεων εξουσιαν λαβων αναιρουμενων [τε]{.greek-omitted} [δε]{.greek-added} αυτων κατηνεγκα ψηφον[26:10]{.aside}

και κατα πασας τας συναγωγας πολλακις τιμωρων αυτους ηναγκαζον βλασφημειν περισσως τε [εμμαινομενος]{.greek-omitted} [εκμαινομενος]{.greek-added} αυτοις εδιωκον εως και εις τας εξω πολεις[26:11]{.aside}

εν οις και πορευομενος εις την δαμασκον [μετ]{.greek-omitted} [μετα]{.greek-added} εξουσιας και [επιτροπης]{.greek-omitted} [επιτροποις]{.greek-added} της [παρα]{.greek-omitted} των αρχιερεων[26:12]{.aside}

ημερας μεσης κατα την οδον ειδον βασιλευ [ουρανοθεν]{.greek-abbr} υπερ την λαμπροτητα του ηλιου περιλαμψαν με φως και τους συν εμοι πορευομενους[26:13]{.aside}

παντων δε καταπεσοντων ημων εις την γην [δια]{.greek-added} [τον]{.greek-added} [φοβον]{.greek-added} [εγω]{.greek-added} [μονος]{.greek-added} ηκουσα φωνην λαλουσαν προς με και λεγουσαν τη εβραιδι διαλεκτω σαουλ σαουλ τι με διωκεις σκληρον σοι προς κεντρα λακτιζειν[26:14]{.aside}

εγω δε ειπον τις ει [κυριε]{.greek-abbr} ο δε [[κυριος]{.greek-abbr}]{.greek-added} ειπεν εγω ειμι [ιησους]{.greek-abbr} [ο]{.greek-added} [ναζωραιος]{.greek-added} ον συ διωκεις[26:15]{.aside}

αλλα αναστηθι και στηθι επι τους ποδας σου εις τουτο γαρ ωφθην σοι προχειρισασθαι σε υπηρετην και μαρτυρα ων τε ειδες ων τε οφθησομαι σοι[26:16]{.aside}

εξαιρουμενος σε εκ του λαου [και]{.greek-omitted} των εθνων εις [ου]{.unclear}ς εγω σε αποστελλω[26:17]{.aside}

ανοιξαι οφθαλμους αυτων του [υποστρεψαι]{.greek-omitted} [αποστρεψαι]{.greek-added} απο σκοτους εις φως και [απο]{.greek-added} της εξουσιας του σατανα επι τον [θεον]{.greek-abbr} του λαβειν αυτους αφεσιν αμαρτιων και κληρον εν τοις ηγιασμενοις πιστει τη εις εμε[26:18]{.aside}

οθεν βασιλευ αγριππα ουκ εγενομην απειθης τη [ουρανιω]{.greek-abbr} οπτασια[26:19]{.aside}

αλλα τοις εν δαμασκω πρωτον και [τοις]{.greek-added} [εν]{.greek-added} ιεροσολυμοις εις πασαν τε την χωραν της ιουδαιας και τοις εθνεσιν [απαγγελλων]{.greek-omitted} [απηγγελον]{.greek-added} μετανοειν και επιστρεφειν επι τον [θεον]{.greek-abbr} αξια της μετανοιας εργα πρασσοντας[26:20]{.aside}

ενεκα τουτων [με]{.greek-added} οι ιουδαιοι [με]{.greek-omitted} [συλλαβομενοι]{.greek-omitted} [συλλαβωμενοι]{.greek-added} [οντα]{.greek-added} εν τω ιερω επειρωντο διαχειρισασθαι[26:21]{.aside}

επικουριας ουν τυχων [της]{.greek-omitted} παρα του [θεου]{.greek-abbr} αχρι της ημερας ταυτης εστηκα μαρτυρομενος μικρω τε και μεγαλω ουδεν εκτος λεγων ων τε οι προφηται ελαλησαν μελλοντων γινεσθαι και [μωυσης]{.greek-omitted} [μωσης]{.greek-added}[26:22]{.aside}

ει παθητος ο [χριστος]{.greek-abbr} ει πρωτος εξ αναστασεως νεκρων φως μελλει καταγγελλειν τω [τε]{.greek-added} λαω και τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added}[26:23]{.aside}

ταυτα δε αυτου απολογουμενου ο φηστος μεγαλη τη φωνη εφη μαινη παυλε τα πολλα σε γραμματα εις μανιαν περιτρεπει[26:24]{.aside}

ο δε ου [μαινομαι]{.greek-omitted} [μενομαι]{.greek-added} [φησιν]{.greek-omitted} [φησι]{.greek-added} κρατιστε φηστε αλλα αληθειας και σωφροσυνης ρηματα αποφθεγγομαι[26:25]{.aside}

επισταται γαρ περι τουτων ο βασιλευς προς ον και παρρησιαζομενος λαλω λανθανειν γαρ αυτον τι τουτων ου πειθομαι [ουδεν]{.greek-omitted} [ουθεν]{.greek-added} ου γαρ [εστιν]{.greek-added} εν γωνια πεπραγμενον τουτο[26:26]{.aside}

πιστευεις βασιλευ αγριππα τοις προφηταις οιδα οτι πιστευεις[26:27]{.aside}

ο δε αγριππας προς τον παυλον εφη εν ολιγω με πειθεις χριστιανον γενεσθαι[26:28]{.aside}

ο δε παυλος ειπεν ευξαιμην αν τω [θεω]{.greek-abbr} και εν ολιγω και εν πολλω ου μονον σε αλλα και παντας τους ακουοντας μου σημερον γενεσθαι τοιουτους οποιος [καγω]{.greek-omitted} [και]{.greek-added} [εγω]{.greek-added} ειμι παρεκτος των δεσμων τουτων[26:29]{.aside}

και ταυτα ειποντος αυτου ανεστη ο βασιλευς και ο ηγεμων η τε βερνικη και οι συγκαθημενοι [αυτοις]{.greek-omitted} [αυτης]{.greek-added}[26:30]{.aside}

και αναχωρησαντες ελαλουν προς αλληλους λεγοντες οτι ουδεν [αξιον]{.greek-added} θανατου [αξιον]{.greek-omitted} η δεσμων πρασσει ο [ανθρωπος]{.greek-abbr} ουτος[26:31]{.aside}

αγριππας δε τω φηστω εφη απολελυσθαι [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} ο [ανθρωπος]{.greek-abbr} ουτος ει μη [επεκεκλητο]{.greek-omitted} [επεκεκλυτο]{.greek-added} καισαρα[26:32]{.aside}

### Chapter 27

ως δε εκριθη του αποπλειν ημας εις την ιταλιαν παρεδιδουν τον τε παυλον και τινας ετερους δεσμωτας εκατονταρχη ονοματι ιουλιω σπειρης σεβαστης[27:1]{.aside}

επιβαντες δε πλοιω [αδραμυττηνω]{.greek-omitted} [ατραμυτηνω]{.greek-added} [μελλοντες]{.greek-omitted} [μελλοντι]{.greek-added} [πλειν]{.greek-omitted} [πλεειν]{.greek-added} [επι]{.greek-added} τους κατα την ασιαν τοπους ανηχθημεν οντος συν ημιν αρισταρχου μακεδονος [θεσσαλονικεως]{.greek-omitted} [θεσσαλονικεων]{.greek-added} [δε]{.greek-added} [αρισταρχου]{.greek-added} [και]{.greek-added} [σεκουνδου]{.greek-added}[27:2]{.aside}

τη τε ετερα κατηχθημεν εις σιδωνα φιλανθρωπως τε ο ιουλιος τω παυλω χρησαμενος [επετρεψεν]{.greek-omitted} [επετρεψε]{.greek-added} προς τους φιλους πορευθεντα επιμελειας τυχειν[27:3]{.aside}

κακειθεν αναχθεντες υπεπλευσαμεν την κυπρον δια το τους ανεμους ειναι εναντιους[27:4]{.aside}

το τε πελαγος το κατα την κιλικιαν και παμφυλιαν διαπλευσαντες [δι]{.greek-added} [ημερων]{.greek-added} [δεκαπεντε]{.greek-added} κατηλθομεν εις μυρα της λυκιας[27:5]{.aside}

κακει ευρων ο εκατονταρχος πλοιον [αλεξανδρινον]{.greek-omitted} [αλεξανδρηνον]{.greek-added} πλεον εις την ιταλιαν ενεβιβασεν ημας εις αυτο[27:6]{.aside}

[εν]{.greek-omitted} ικαναις δε ημεραις βραδυπλοουντες και μολις γενομενοι κατα την κνιδον μη προσεωντος ημας του ανεμου υπεπλευσαμεν την κρητην κατα σαλμωνην[27:7]{.aside}

μολις τε παραλεγομενοι αυτην ηλθομεν εις τοπον τινα καλουμενον καλους λιμενας ω εγγυς ην πολις λασαια[27:8]{.aside}

ικανου δε χρονου διαγενομενου και οντος ηδη [επισφαλους]{.greek-omitted} του πλοος [επισφαλους]{.greek-added} δια το και την νηστειαν ηδη παρεληλυθεναι παρηνει ο παυλος[27:9]{.aside}

λεγων αυτοις ανδρες θεωρω οτι μετα υβρεως και πολλης ζημιας ου μονον του [φορτιου]{.greek-omitted} [φορτου]{.greek-added} και του πλοιου αλλα και των ψυχων ημων μελλειν εσεσθαι τον πλουν[27:10]{.aside}

ο δε [εκατονταρχης]{.greek-omitted} [εκατονταρχος]{.greek-added} τω κυβερνητη και τω ναυκληρω επειθετο μαλλον η τοις υπο του παυλου λεγομενοις[27:11]{.aside}

ανευθετου δε του λιμενος υπαρχοντος προς παραχειμασιαν οι πλειους εθεντο βουλην αναχθηναι [κακειθεν]{.greek-omitted} [εκειθεν]{.greek-added} ει πως δυναιντο καταντησαντες εις φοινικα παραχειμασαι λιμενα της κρητης βλεποντα κατα λιβα και κατα χωρον[27:12]{.aside}

υποπνευσαντος δε νοτου δοξαντες της προθεσεως κεκρατηκεναι αραντες ασσον παρελεγοντο την κρητην[27:13]{.aside}

μετ ου πολυ δε εβαλεν κατ αυτης ανεμος τυφωνικος ο καλουμενος ευροκλυδων[27:14]{.aside}

συναρπασθεντος δε του πλοιου και μη δυναμενου αντοφθαλμειν τω ανεμω επιδοντες [τω]{.greek-added} [πλειοντι]{.greek-added} [και]{.greek-added} [συστειλαντες]{.greek-added} [τα]{.greek-added} [ιστια]{.greek-added} [εφερομεθα]{.greek-omitted} [εφερωμεθα]{.greek-added}[27:15]{.aside}

νησιον δε τι υποδραμοντες καλουμενον κλαυδην [μολις]{.greek-omitted} [μολυς]{.greek-added} ισχυσαμεν περικρατεις γενεσθαι της [καφης]{.greek-added} [σκαφης]{.corr}[27:16]{.aside}

ην αραντες βοηθειαις εχρωντο υποζωννυντες το πλοιον φοβουμενοι τε μη [πως]{.greek-added} εις την συρτην [εκπεσωσιν]{.greek-omitted} [εκπεσωσι]{.greek-added} χαλασαντες το σκευος ουτως εφεροντο[27:17]{.aside}

σφοδρως δε χειμαζομενων ημων τη εξης εκβολην εποιουντο[27:18]{.aside}

και τη τριτη αυτοχειρες την σκευην του πλοιου ερριψαμεν [εις]{.greek-added} [την]{.greek-added} [θαλασσαν]{.greek-added}[27:19]{.aside}

μητε δε ηλιου μητε αστρων [επιφαινοντων]{.greek-omitted} [επιφαινομενων]{.greek-added} επι πλειονας ημερας χειμωνος τε ουκ ολιγου επικειμενου λοιπον περιηρειτο πασα ελπις του σωζεσθαι ημας[27:20]{.aside}

πολλης δε ασιτιας υπαρχουσης τοτε σταθεις ο παυλος εν μεσω αυτων ειπεν εδει μεν ω ανδρες πειθαρχησαντας μοι μη αναγεσθαι απο της κρητης [κερδησαι]{.greek-omitted} [κερδησεται]{.greek-added} [τε]{.greek-omitted} την υβριν ταυτην και την ζημιαν[27:21]{.aside}

και τα νυν παραινω υμας ευθυμειν αποβολη γαρ ψυχης ουδεμια εσται εξ υμων πλην του πλοιου[27:22]{.aside}

παρεστη γαρ μοι ταυτη τη νυκτι αγγελος του [θεου]{.greek-abbr} ου ειμι ω [και]{.greek-omitted} λατρευω[27:23]{.aside}

λεγων μη φοβου παυλε καισαρι [σε]{.greek-omitted} [σαι]{.greek-added} δει παραστηναι και ιδου κεχαρισται σοι ο [θεος]{.greek-abbr} παντας τους πλεοντας μετα σου[27:24]{.aside}

διο ευθυμειτε ανδρες πιστευω γαρ τω [θεω]{.greek-abbr} [οτι]{.greek-omitted} ουτως εσται καθ ον τροπον λελαληται μοι[27:25]{.aside}

εις νησον δε τινα δει ημας εκπεσειν[27:26]{.aside}

ως δε τεσσαρεσκαιδεκατη νυξ εγενετο διαφερομενων ημων εν τω αδρια κατα μεσον της νυκτος υπενοουν οι ναυται [προσαγειν]{.greek-omitted} [προσ[ε]{.unclear}γγιζειν]{.greek-added} τινα αυτοις χωραν[27:27]{.aside}

και [βολισαντες]{.greek-omitted} [βολησαντες]{.greek-added} ευρον οργυιας εικοσι βραχυ δε διαστησαντες και π[α]{.unclear}λιν [βολισαντες]{.greek-omitted} [βολησαντες]{.greek-added} ευρον οργυιας δεκαπεντε[27:28]{.aside}

φοβουμενοι [τε]{.greek-omitted} [δε]{.greek-added} [μη]{.greek-added} [μηπως]{.greek-omitted} [πως]{.greek-added} εις τραχεις τοπους εκπεσωμεν εκ πρυμνης ριψαντες αγκυρας τεσσαρας ηυχοντο ημεραν γενεσθαι[27:29]{.aside}

των δε ναυτων ζητουντων [φυγειν]{.greek-omitted} [εκφυγειν]{.greek-added} εκ του πλοιου και χαλασαντων την σκαφην εις την θαλασσαν προφασει ως εκ πρ[ω]{.unclear}ρας μελλοντων αγκυρας εκτεινειν[27:30]{.aside}

ειπεν ο παυλος τω εκατονταρχη και τοις στρατιωταις εαν μη ουτοι [μεινωσιν]{.greek-omitted} εν τω πλοιω [μεινωσιν]{.greek-added} υμεις σωθηναι ου [δυνασθε]{.greek-omitted} [δυνασθαι]{.greek-added}[27:31]{.aside}

τοτε [απεκοψαν]{.greek-added} οι στρατιωται [απεκοψαν]{.greek-omitted} τα σχοινια της σκαφης και ειασαν αυτην εκπεσειν[27:32]{.aside}

αχρι δε ου [ημελλεν]{.greek-omitted} [εμελλεν]{.greek-added} ημερα γινεσθαι παρεκαλει ο παυλος απαντας μεταλαβειν τροφης λεγων τεσσαρεσκαιδεκατην σημερον ημεραν προσδοκωντες ασιτοι διατελειτε μηδεν προσλαβομενοι[27:33]{.aside}

διο παρακαλω [υμας]{.greek-omitted} [ημας]{.greek-added} προσλαβειν τροφης τουτο γαρ προς της [υμετερας]{.greek-omitted} [ημετερας]{.greek-added} [σωτηριας]{.greek-abbr} υπαρχει ουδενος γαρ υμων θριξ εκ της κεφαλης πεσειται[27:34]{.aside}

ειπων δε ταυτα και λαβων αρτον [ευχαριστησεν]{.greek-omitted} [ηυχαριστησε]{.greek-added} τω [θεω]{.greek-abbr} ενωπιον παντων και κλασας ηρξατο εσθιειν [επιδιδους]{.greek-added} [και]{.greek-added} [ημιν]{.greek-added}[27:35]{.aside}

ευθυμοι δε γενομενοι παντες και αυτοι [προσελαβοντο]{.greek-omitted} [μετελαμβανον]{.greek-added} τροφης[27:36]{.aside}

ημεν δε εν τω πλοιω αι πασαι ψυχαι διακοσιαι εβδομηκοντα εξ[27:37]{.aside}

κορεσθεντες δε της τροφης εκουφιζον το πλοιον εκβαλλομενοι τον σιτον εις την θαλασσαν[27:38]{.aside}

οτε δε ημερα εγενετο την γην ουκ επεγινωσκον κολπον δε τινα κατενοουν εχοντα αιγιαλον εις ον εβουλευσαντο ει [δυνατον]{.greek-omitted} [δυναιντο]{.greek-added} εξωσαι το πλοιον[27:39]{.aside}

και τας αγκυρας περιελοντες ειων εις την θαλασσαν αμα ανεντες τας ζευκτηριας των πηδαλιων και επαραντες τον αρτεμονα τη [γη]{.greek-added} πνεουση κατειχον εις τον αιγιαλον[27:40]{.aside}

περιπεσοντες δε εις τοπον διθαλασσον επωκειλαν την ναυν και η μεν πρωρα ερεισασα εμεινεν ασαλευτος η δε πρυμνα [ελυετο]{.greek-omitted} [διελυετο]{.greek-added} υπο της βιας των κυματων[27:41]{.aside}

των δε στρατιωτων βουλη εγενετο ινα τους δεσμωτας [αποκτεινωσιν]{.greek-omitted} [αποκτεινωσι]{.greek-added} μη τις εκκολυμβησας διαφυγη[27:42]{.aside}

ο δε εκατονταρχος βουλομενος διασωσαι τον παυλον εκωλυσεν αυτους του βουληματος [εκελευσεν]{.greek-omitted} [εκελευσε]{.greek-added} τε τους δυναμενους κολυμβαν απορριψαντας πρωτους επι την γην εξιεναι[27:43]{.aside}

και τους λοιπους ους μεν επι σανισιν ους δε επι τινων των απο του πλοιου και ουτως εγενετο παντας διασωθηναι επι την γην[27:44]{.aside}

### Chapter 28

και διασωθεντες [οι]{.greek-added} [περι]{.greek-added} [τον]{.greek-added} [παυλον]{.greek-added} [εκ]{.greek-added} [του]{.greek-added} [πλοος]{.greek-added} τοτε επεγνωσαν οτι μελιτη η νησος καλειται[28:1]{.aside}

οι δε βαρβαροι παρειχον ου την τυχουσαν [φιλανθρωπιαν]{.greek-abbr} ημιν αναψαντες γαρ πυραν προσελαβοντο πα[ν]{.greek-supplied}τας ημας δια τον υετον τον εφεστωτα και δια το ψυχος[28:2]{.aside}

συστρεψαντος δε του παυλου φρυγανων πληθος και επιθεντος επι την πυραν εχιδνα [εκ]{.greek-omitted} [απο]{.greek-added} της θερμης [διεξελθουσα]{.greek-omitted} [εξελθουσα]{.greek-added} [καθηψεν]{.greek-omitted} [καθηψατο]{.greek-added} της χειρος αυτου[28:3]{.aside}

ως δε ειδον οι βαρβαροι κρεμαμενον το θηριον εκ της χειρος αυτου [ελεγον]{.greek-omitted} προς αλληλους [ελεγον]{.greek-added} πα[ν]{.unclear}τως [φονευς]{.greek-omitted} [φωνευς]{.greek-added} εστιν ο [ανθρωπος]{.greek-abbr} ουτος ον διασωθεντα εκ της θαλασσης η δικη ζην ουκ ειασεν[28:4]{.aside}

ο μεν ουν [αποτιναξας]{.greek-omitted} [αποτιναξαμενος]{.greek-added} το θηριον εις το πυρ επαθε[ν]{.unclear} ουδεν κακον[28:5]{.aside}

οι δε προσεδοκων αυτον μελλειν πιμπρασθαι η καταπιπτειν αφνω νεκρον επι πολυ δε αυτων προσδοκωντων και θεωρουντων μηδεν ατοπον εις αυτον γινομενον μεταβαλλομενοι ελεγον [θεον]{.greek-abbr} αυτον ειναι[28:6]{.aside}

εν δε [τοις]{.greek-omitted} [της]{.greek-added} περι τον τοπον εκεινον υπηρχεν χωρια τω πρωτ[ω]{.unclear} της νησου ονοματι ποπλιω ος αναδεξαμενος ημας [ημερας]{.greek-added} τρεις [ημερας]{.greek-omitted} φιλοφρονως εξενισεν[28:7]{.aside}

εγενετο δε τον [πατερα]{.greek-abbr} του ποπλιου πυρετοις και δυσεντερια συνεχομενον κατακεισθαι προς ον ο παυλος εισελθων και προσευξαμενος επιθεις τας χειρας αυτω ιασατο αυτον[28:8]{.aside}

τουτου [ουν]{.greek-omitted} [δε]{.greek-added} γενομενου και οι λοιποι οι εχοντες ασθενειας εν τη νησω προσηρχοντο και εθεραπευοντο[28:9]{.aside}

οι και πολλαις τιμαις ετιμησαν ημας και αναγομενοις επεθεντο τα προς την χρειαν[28:10]{.aside}

μετα δε τρεις μηνας ηχθημεν εν πλοιω παρακεχειμακοτι εν τη νησω [αλεξανδρινω]{.greek-omitted} [αλεξανδρηνω]{.greek-added} παρασημω διοσκουροις[28:11]{.aside}

και καταχθεντες εις συρακουσας επεμειναμεν [τρεις]{.greek-added} ημερας [τρεις]{.greek-omitted}[28:12]{.aside}

[ο]{.unclear}θεν περιελθοντες κατηντησαμεν εις ρηγιον κα[ι]{.unclear} μετα μιαν ημεραν επιγενομενου νοτου δευτεραιοι [η]{.unclear}λθομεν εις ποτιολους[28:13]{.aside}

ου ευροντες αδελφους παρεκληθημεν επ αυτοις [επιμειναι]{.greek-omitted} [επι]{.greek-added} ημερας επτα και ουτω[ς]{.unclear} εις [την]{.greek-omitted} ρωμην ηλθομεν[28:14]{.aside}

κακειθεν οι αδελφοι ακουσαντες τα περι ημων εξηλθον εις απαντησιν [ημιν]{.greek-omitted} [ημων]{.greek-added} [αχρι]{.greek-omitted} [αχρις]{.greek-added} [αππιου]{.greek-omitted} [απφιου]{.greek-added} φορου και τριων ταβερνων ους ιδων ο παυλος ευχαριστησας τω [θεω]{.greek-abbr} [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added} θαρσος[28:15]{.aside}

οτε δε ηλθομεν εις ρωμην ο εκατονταρχος [παρεδωκεν]{.greek-omitted} [παρεδωκε]{.greek-added} τους δεσμιους τω στρατοπεδαρχη τω δε παυλω [επετραπη]{.greek-omitted} [επετραπειν]{.greek-added} μενειν καθ εαυτον [εξω]{.greek-added} [της]{.greek-added} [παρε]{.greek-added} [μβολης]{.greek-added} συν τω φυλασσοντι αυτον [στρατιωτη]{.greek-omitted} [στρατιωτην]{.greek-added}[28:16]{.aside}

εγενετο δε μετα ημερας τρεις συγκαλεσασθαι τον παυλον τους οντας των ιουδαιων πρωτους συνελθοντων δε αυτων [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} προς αυτους ανδρες αδελφοι εγω ουδεν εναντιον ποιησας τω λαω η τοις [εθεσιν]{.greek-omitted} [εθεσι]{.greek-added} τοις πατρωοις δεσμιος εξ ιεροσολυμων παρεδοθην εις τας χειρας των ρωμαιων[28:17]{.aside}

οιτινες [πολλα]{.greek-added} ανακριναντες με εβουλοντο απολυσαι δια το μηδεμιαν αιτιαν θανατου υπαρχειν εν εμοι[28:18]{.aside}

αντιλεγοντων δε των ιουδαιων [και]{.greek-added} [επικραζοντων]{.greek-added} [αιρε]{.greek-added} [τον]{.greek-added} [εχθρον]{.greek-added} [ημων]{.greek-added} ηναγκασθην επικαλεσασθαι καισαρα ουχ ως του εθνους μου εχων τι κατηγορησαι [αλλ]{.greek-added} [ινα]{.greek-added} [λυτρωσωμαι]{.greek-added} [την]{.greek-added} [ψυχην]{.greek-added} [μου]{.greek-added} [εκ]{.greek-added} [θανατου]{.greek-added}[28:19]{.aside}

δια ταυτην ουν την αιτιαν παρεκαλεσα υμας ιδειν και προσλαλησαι ενεκεν γαρ της ελπιδος του [ισραηλ]{.greek-abbr} την αλυσιν ταυτην περικειμαι[28:20]{.aside}

οι δε προς αυτον ειπον ημεις ουτε γραμματα περι σου εδεξαμεθα απο της ιουδαιας ουτε παραγενομενος τις των αδελφων απηγγειλεν η [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} τι περι σου πονηρον[28:21]{.aside}

αξιουμεν δε παρα σου ακουσαι α φρονεις περι μεν γαρ της αιρεσεως ταυτης γνωστον εστιν ημιν οτι πανταχου αντιλεγεται[28:22]{.aside}

ταξαμενοι δε αυτω ημεραν ηκον προς αυτον εις την ξενιαν πλειονες οις εξετιθετο διαμαρτυρομενος την βασιλειαν του [θεου]{.greek-abbr} [πειθων]{.greek-omitted} [πειθον]{.greek-added} τε αυτους [τα]{.greek-omitted} περι του [ιησου]{.greek-abbr} απο τε του νομου [μωυσεως]{.greek-omitted} [μωσεως]{.greek-added} και των προφητων απο πρωι εως εσπερας[28:23]{.aside}

και οι μεν επειθοντο τοις λεγομενοις οι δε ηπιστουν[28:24]{.aside}

ασυμφωνοι δε οντες προς αλληλους απελυοντο ειποντος του παυλου ρημα εν οτι καλως το [πνευμα]{.greek-abbr} το αγιον [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} δια ησαιου του προφητου προς τους [πατερας]{.greek-abbr} [ημων]{.greek-omitted} [υμων]{.greek-added}[28:25]{.aside}

λεγον [πορ]{.greek-supplied}ευθητι προς τον λαον τουτον και [ειπον]{.greek-omitted} [ειπε]{.greek-added} ακο[η]{.unclear} ακουσετε και ου μη συνητε και βλεποντες βλεψετε και ου μη ιδητε[28:26]{.aside}

επαχυνθη γαρ η καρδια του λαου τουτου και τοις [ωσιν]{.greek-omitted} [ωσι]{.greek-added} βαρεως ηκουσαν και τους οφθαλμους αυτων εκαμμυσαν μηποτε [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} τοις οφθαλμοις και τοις ωσιν [ακουσωσιν]{.greek-omitted} [ακουσωσι]{.greek-added} και τη καρδια [συνωσιν]{.greek-omitted} [συνωσι]{.greek-added} και [επιστρεψωσιν]{.greek-omitted} [επιστρεψωσι]{.greek-added} και ιασομαι αυτους[28:27]{.aside}

γνωστον ουν εστω υμιν οτι τοις εθνεσιν απεσταλη το σωτηριον του [θεου]{.greek-abbr} αυτοι και ακουσονται[28:28]{.aside}

και ταυτα αυτου ειποντος απηλθον οι ιουδαιοι πολλην εχοντες εν εαυτοις συζητησιν[28:29]{.aside}

[εμεινεν]{.greek-omitted} [εμεινε]{.greek-added} δε ο παυλος διετιαν ολην εν ιδιω μισθωματι και απεδεχετο παντας τους εισπορευομενους προς αυτον [ιουδαιους]{.greek-added} [τε]{.greek-added} [και]{.greek-added} [ελληνας]{.greek-added}[28:30]{.aside}

κηρυσσων την βασιλειαν του [θεου]{.greek-abbr} και [διδασκων]{.greek-omitted} [διδα[σ]{.unclear}κον]{.greek-added} τα περι του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} [χριστου]{.greek-omitted} μετα πασης παρρησιας ακωλυτως [αμην]{.greek-added}[28:31]{.aside}

