---
title: "Collation of Byz^RP^ vs 32672 (2672)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 2672 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=32672).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 2672                                   	| λογος                              	|
| 2672 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 2672 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 2672               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 2672                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 2672 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 2672                                                     	| [―]{.gap}                        	|
:::

## Revelation

### Chapter 1

αποκαλυψις [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} ην εδωκεν αυτω ο [θεος]{.greek-abbr} δειξαι τοις δουλοις αυτου α δει γενεσθαι εν ταχει και εσημανεν αποστειλας δια του αγγελου αυτου [τω]{.greek-omitted} [δουλω]{.greek-omitted} [αυτου]{.greek-omitted} ιωαννη[1:1]{.aside}

ος εμαρτυρησεν τον λογον του [θεου]{.greek-abbr} και την μαρτυριαν [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} οσα [ειδεν]{.greek-omitted} [ειδε]{.greek-added}[1:2]{.aside}

μακαριος ο αναγινωσκων και οι ακουοντες τους λογους της προφητειας και τηρουντες τα εν αυτη γεγραμμενα ο γαρ καιρος [εγγυς]{.greek-omitted} [εγγεις]{.greek-added}[1:3]{.aside}

ιωαννης ταις επτα εκκλησιαις ταις εν τη ασια χαρις υμιν και ειρηνη απο [θεου]{.greek-abbr} ο ων και ο ην και ο ερχομενος και απο των επτα [πνευματων]{.greek-abbr} α ενωπιον του θρονου [του]{.greek-added} [θρονου]{.greek-added} αυτου[1:4]{.aside}

και απο [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} ο μαρτυς ο πιστος ο πρωτοτοκος των νεκρων και ο αρχων των βασιλεων της γης τω αγαπωντι ημας και λουσαντι ημας απο των αμαρτιων ημων εν τω αιματι αυτου[1:5]{.aside}

και εποιησεν ημας βασιλειαν ιερεις τω [θεω]{.greek-abbr} και [πατρι]{.greek-abbr} αυτου αυτω η δοξα [και]{.greek-omitted} [το]{.greek-omitted} [κρατος]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [αιωνας]{.greek-omitted} [των]{.greek-omitted} [αιωνων]{.greek-omitted} [αμην]{.greek-omitted}[1:6]{.aside}

[και]{.greek-omitted} [εποιησεν]{.greek-omitted} [ημας]{.greek-omitted} [βασιλειαν]{.greek-omitted} [ιερεις]{.greek-omitted} [τω]{.greek-omitted} [θεω]{.greek-omitted} [και]{.greek-omitted} [πατρι]{.greek-omitted} [αυτου]{.greek-omitted} [αυτω]{.greek-omitted} [η]{.greek-omitted} [δοξα]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [κρατος]{.greek-omitted} εις τους αιωνας των αιωνων αμην[1:6 | instance no. 2]{.aside}

ιδου ερχεται μετα των νεφελων και οψεται αυτον πας οφθαλμος και οιτινες αυτον εξεκεντησαν και κοψονται επ αυτον πασαι αι φυλαι της γης ναι αμην[1:7]{.aside}

εγω ειμι το [αλφα]{.greek-omitted} [ἄλφα]{.greek-added} και το [ω]{.greek-omitted} [ὦ]{.greek-added} λεγει [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο ων και ο ην και ο ερχομενος ο παντοκρατωρ[1:8]{.aside}

εγω ιωαννης ο αδελφος υμων και κοινωνος εν τη θλιψει και βασιλεια και υπομονη εν [χριστω]{.greek-abbr} [ιησου]{.greek-abbr} εγενομην εν τη νησω τη καλουμενη πατμω δια τον λογον του [θεου]{.greek-abbr} και δια την μαρτυριαν [ιησου]{.greek-abbr} [χριστου]{.greek-abbr}[1:9]{.aside}

εγενομην εν [πνευματι]{.greek-abbr} εν τη κυριακη ημερα και ηκουσα φωνην οπισω μου μεγαλην ως σαλπιγγος[1:10]{.aside}

λεγουσης ο βλεπεις γραψον εις βιβλιον και πεμψον ταις επτα εκκλησιαις εις εφεσον και εις [σμυρναν]{.greek-omitted} [μυρνην]{.greek-added} και εις περγαμον και εις [θυατειρα]{.greek-omitted} [θυατηρα]{.greek-added} και εις [σαρδεις]{.greek-omitted} [σαρδην]{.greek-added} και εις [φιλαδελφειαν]{.greek-omitted} [φιλαδελφιαν]{.greek-added} και εις [λαοδικειαν]{.greek-omitted} [λαοδικιαν]{.greek-added}[1:11]{.aside}

και εκει επεστρεψα βλεπειν την φωνην ητις [ελαλει]{.greek-omitted} [ελαλη]{.greek-added} μετ εμου και [επιστρεψας]{.greek-omitted} [επιστρε]{.greek-added} [ειδον]{.greek-omitted} [επτα]{.greek-omitted} [λυχνιας]{.greek-omitted} [χρυσας]{.greek-omitted}[1:12]{.aside}

[και]{.greek-omitted} [εκει]{.greek-omitted} [επεστρεψα]{.greek-omitted} [βλεπειν]{.greek-omitted} [την]{.greek-omitted} [φωνην]{.greek-omitted} [ητις]{.greek-omitted} [ελαλει]{.greek-omitted} [μετ]{.greek-omitted} [εμου]{.greek-omitted} [και]{.greek-omitted} [επιστρεψας]{.greek-omitted} [στρεψας]{.greek-added} ειδον επτα λυχνιας χρυσας[1:12 | instance no. 2]{.aside}

και εν μεσω των επτα λυχνιων ομοιον [υιω]{.greek-omitted} [υιον]{.greek-added} [ανθρωπου]{.greek-abbr} ενδεδυμενον ποδηρη και περιεζωσμενον προς τοις μαστοις ζωνην χρυσην[1:13]{.aside}

η δε κεφαλη αυτου [και]{.greek-omitted} [αι]{.greek-omitted} [τριχες]{.greek-omitted} [λευκαι]{.greek-omitted} [ως]{.greek-omitted} [εριον]{.greek-omitted} [λευκον]{.greek-omitted} [ως]{.greek-omitted} [χιων]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [οφθαλμοι]{.greek-omitted} [αυτου]{.greek-omitted} [ως]{.greek-omitted} [φλοξ]{.greek-omitted} [πυρος]{.greek-omitted}[1:14]{.aside}

[και]{.greek-omitted} [οι]{.greek-omitted} [ποδες]{.greek-omitted} [αυτου]{.greek-omitted} ομοιοι [χαλκολιβανω]{.greek-omitted} [χαλκολιβανων]{.greek-added} ως εν καμινω πεπυρωμενοι και η φωνη αυτου ως φωνη υδατων πολλων[1:15]{.aside}

και εχων εν τη δεξια αυτου χειρι αστερας επτα και εκ του στοματος αυτου ρομφαια διστομος οξεια εκπορευομενη και η οψις αυτου ως ο ηλιος φαινει εν τη δυναμει αυτου[1:16]{.aside}

και οτε ειδον αυτον [επεσα]{.greek-omitted} [προς]{.greek-omitted} [επεσον]{.greek-added} [[εις]{.corr}]{.greek-added} τους ποδας αυτου ως νεκρος και [εθηκεν]{.greek-omitted} [εθηκε]{.greek-added} την δεξιαν αυτου επ εμε λεγων μη φοβου εγω ειμι ο πρωτος και ο εσχατος[1:17]{.aside}

και ο ζων και εγενομην νεκρος και ιδου ζων ειμι εις τους αιωνας των αιωνων αμην και εχω τας κλεις του θανατου και του αδου[1:18]{.aside}

γραψον [ουν]{.greek-omitted} α ειδες και α [εισιν]{.greek-omitted} [εισι]{.greek-added} και α μελλει [γινεσθαι]{.greek-omitted} [γενεσθαι]{.greek-added} μετα ταυτα[1:19]{.aside}

το μυστηριον των επτα αστερων ων ειδες επι της δεξιας μου και τας επτα λυχνιας τας χρυσας [ταυτα]{.greek-added} [εισιν]{.greek-added} οι επτα [ασ]{.greek-added} [αστερες]{.greek-omitted} [αγγελοι]{.greek-omitted} [των]{.greek-omitted} [επτα]{.greek-omitted} [εκκλησιων]{.greek-omitted} [εισιν]{.greek-omitted} [και]{.greek-omitted} [αι]{.greek-omitted} [λυχνιαι]{.greek-omitted} [αι]{.greek-omitted} [επτα]{.greek-omitted} [επτα]{.greek-omitted} [εκκλησιαι]{.greek-omitted} [εισιν]{.greek-omitted}[1:20]{.aside}

[το]{.greek-omitted} [μυστηριον]{.greek-omitted} [των]{.greek-omitted} [επτα]{.greek-omitted} [αστερων]{.greek-omitted} [ων]{.greek-omitted} [ειδες]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [δεξιας]{.greek-omitted} [μου]{.greek-omitted} [και]{.greek-omitted} [τας]{.greek-omitted} [επτα]{.greek-omitted} [λυχνιας]{.greek-omitted} [τας]{.greek-omitted} [χρυσας]{.greek-omitted} [οι]{.greek-omitted} [επτα]{.greek-omitted} [αστερες]{.greek-omitted} [στερες]{.greek-added} αγγελοι των [επτα]{.greek-omitted} εκκλησιων εισιν και αι λυχνιαι αι επτα [αι]{.greek-added} [εκκλησιαι]{.greek-added} [αι]{.greek-added} επτα [εκκλησιαι]{.greek-omitted} [εισιν]{.greek-omitted} [εισι]{.greek-added}[1:20 | instance no. 2]{.aside}

### Chapter 2

τω αγγελω της εν εφεσω εκκλησιας γραψον ταδε λεγει ο κρατων τους επτα αστερας εν τη δεξια αυτου ο περιπατων εν μεσω των επτα λυχνιων των χρυσων[2:1]{.aside}

οιδα τα εργα σου και τον κοπον σου και την υπομονην σου και οτι ου δυνη βαστασαι κακους και επειρασας τους λεγοντας εαυτους αποστολους [ναι]{.greek-added} [ειναι]{.corr} και ουκ [εισιν]{.greek-omitted} [εισι]{.greek-added} και ευρες αυτους ψευδεις[2:2]{.aside}

και υπομονην εχεις και εβαστασας δια το ονομα μου και [ουκ]{.greek-omitted} [οὐκ]{.greek-added} [εκοπιασας]{.greek-omitted} [ἐκοπίασας]{.greek-added}[2:3]{.aside}

αλλα εχω κατα σου οτι την αγαπην σου την πρωτην αφηκας[2:4]{.aside}

[μνημονευε]{.greek-omitted} [μνημονεβε]{.greek-added} ουν ποθεν πεπτωκας και μετανοησον και τα πρωτα εργα ποιησον ει δε μη ερχομαι σοι ταχυ και κινησω την λυχνιαν σου εκ του τοπου αυτης εαν μη [μετανοησης]{.greek-omitted} [μετανοησεις]{.greek-added}[2:5]{.aside}

αλλα τουτο εχεις οτι μισεις τα εργα των νικολαιτων α καγω μισω[2:6]{.aside}

ο εχων [ους]{.greek-omitted} [ουν]{.greek-added} ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις τω νικωντι δωσω αυτω [φαγειν]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [ξυλου]{.greek-omitted} [της]{.greek-omitted} [ζωης]{.greek-omitted} [ο]{.greek-omitted} [εστιν]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [παραδεισω]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [μου]{.greek-omitted}[2:7]{.aside}

[ο]{.greek-omitted} [εχων]{.greek-omitted} [ους]{.greek-omitted} [ακουσατω]{.greek-omitted} [τι]{.greek-omitted} [το]{.greek-omitted} [πνευμα]{.greek-omitted} [λεγει]{.greek-omitted} [ταις]{.greek-omitted} [εκκλησιαις]{.greek-omitted} [τω]{.greek-omitted} [νικωντι]{.greek-omitted} [δωσω]{.greek-omitted} [αυτω]{.greek-omitted} φαγειν εκ του ξυλου της ζωης ο εστιν εν τω παραδεισω του [θεου]{.greek-abbr} μου[2:7 | instance no. 2]{.aside}

και τω αγγελω της εν σμυρνη εκκλησιας γραψον ταδε λεγει ο πρωτος και ο εσχατος [ος]{.greek-omitted} εγενετο νεκρος και εζησεν[2:8]{.aside}

οιδα σου τα εργα και την θλιψιν και την [πτωχειαν]{.greek-omitted} [πτωχιαν]{.greek-added} αλλα πλουσιος ει και την βλασφημιαν [εκ]{.greek-omitted} των [λεγοντων]{.greek-omitted} [λεγων]{.greek-added} [τον]{.greek-added} ιουδαιους ειναι εαυτους και ουκ εισιν αλλα συναγωγη του σατανα[2:9]{.aside}

μηδεν φοβου α μελλεις παθειν ιδου δη μελλει [βαλειν]{.greek-omitted} [βαλεῖν]{.greek-added} ο διαβολος εξ υμων εις φυλακην ινα πειρασθητε και εξετε θλιψιν [ημερων]{.greek-omitted} [ημερας]{.greek-added} δεκα γινου [πιστος]{.greek-omitted} [πιστως]{.greek-added} αχρι θανατου και δωσω σοι τον στεφανον της ζωης[2:10]{.aside}

ο εχων ους [α]{.greek-added} [α]{.greek-added} [ακουσατω]{.greek-omitted} [κουσατω]{.greek-added} τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις ο νικων ου μη αδικηθη εκ του [δευτερου]{.greek-added} θανατου [του]{.greek-omitted} [δευτερου]{.greek-omitted}[2:11]{.aside}

και τω αγγελω της εν περγαμω εκκλησιας γραψον ταδε λεγει ο εχων την ρομφαιαν την διστομον την οξειαν[2:12]{.aside}

[οιδα]{.greek-omitted} [ειδον]{.greek-added} τα εργα σου και που κατοικεις [οπου]{.greek-omitted} [οπως]{.greek-added} ο θρονος του σατανα και κρατεις το ονομα μου και ουκ ηρνησω την [πιστιν]{.greek-omitted} [πιστην]{.greek-added} μου εν ταις ημεραις [ἀντί]{.greek-added} [εν]{.greek-omitted} [αις]{.greek-omitted} [αντιπας]{.greek-omitted} [ο]{.greek-omitted} [μαρτυς]{.greek-omitted} [μου]{.greek-omitted} [ο]{.greek-omitted} [πιστος]{.greek-omitted} [ος]{.greek-omitted} [απεκτανθη]{.greek-omitted} [παρ]{.greek-omitted} [υμιν]{.greek-omitted} [οπου]{.greek-omitted} [ο]{.greek-omitted} [σατανας]{.greek-omitted} [κατοικει]{.greek-omitted}[2:13]{.aside}

[πας]{.greek-added} [οιδα]{.greek-omitted} [τα]{.greek-omitted} [εργα]{.greek-omitted} [σου]{.greek-omitted} [και]{.greek-omitted} [που]{.greek-omitted} [κατοικεις]{.greek-omitted} [οπου]{.greek-omitted} ο [θρονος]{.greek-omitted} [του]{.greek-omitted} [σατανα]{.greek-omitted} [και]{.greek-omitted} [κρατεις]{.greek-omitted} [το]{.greek-omitted} [ονομα]{.greek-omitted} [μου]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [ηρνησω]{.greek-omitted} [την]{.greek-omitted} [πιστιν]{.greek-omitted} [μου]{.greek-omitted} [εν]{.greek-omitted} [ταις]{.greek-omitted} [ημεραις]{.greek-omitted} [εν]{.greek-omitted} [αις]{.greek-omitted} [αντιπας]{.greek-omitted} [ο]{.greek-omitted} [μαρτυς]{.greek-omitted} [μαρτις]{.greek-added} μου ο πιστος ος απεκτανθη παρ υμιν οπου ο σατανας [[ο]{.unclear}]{.greek-added} κατοικει[2:13 | instance no. 2]{.aside}

[αλλ]{.greek-omitted} [αλλα]{.greek-added} εχω κατα σου ολιγα οτι εχεις εκει κρατουντας την διδαχην βαλααμ ος [εδιδαξεν]{.greek-omitted} [εδιδαξε]{.greek-added} τον βαλακ βαλειν σκανδαλον ενωπιον των υιων [ισραηλ]{.greek-omitted} [[ηλ]{.greek-abbr}]{.greek-added} και φαγειν ειδωλοθυτα και πορνευσαι[2:14]{.aside}

ουτως εχεις και συ κρατουντας την διδαχην [των]{.greek-omitted} νικολαιτων ομοιως[2:15]{.aside}

μετανοησον ουν ει δε μη ερχομαι σοι ταχυ και πολεμησω μετ αυτων εν τη ρομφαια του στοματος μου[2:16]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις τω νικωντι δωσω αυτω του μαννα του κεκρυμμενου και δωσω αυτω ψηφον λευκην και επι την ψηφον ονομα καινον γεγραμμενον ο ουδεις οιδεν ει μη ο λαμβανων[2:17]{.aside}

και τω αγγελω της [θυατηρων]{.greek-added} [εν]{.greek-omitted} [θυατειροις]{.greek-omitted} εκκλησιας γραψον ταδε λεγει ο υιος του [θεου]{.greek-abbr} ο εχων τους οφθαλμους αυτου ως φλογα πυρος και οι ποδες αυτου ομοιοι [χαλκολιβανω]{.greek-omitted} [χαλκολιβανων]{.greek-added}[2:18]{.aside}

οιδα σου τα εργα και την [αγα]{.greek-added} [αγαπην]{.greek-omitted} [και]{.greek-omitted} [την]{.greek-omitted} [πιστιν]{.greek-omitted} [και]{.greek-omitted} [την]{.greek-omitted} [διακονιαν]{.greek-omitted} [και]{.greek-omitted} [την]{.greek-omitted} [υπομονην]{.greek-omitted} [σου]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} [εργα]{.greek-omitted} [σου]{.greek-omitted} [τα]{.greek-omitted} [εσχατα]{.greek-omitted} [πλειονα]{.greek-omitted} [των]{.greek-omitted} [πρωτων]{.greek-omitted}[2:19]{.aside}

[πην]{.greek-added} [οιδα]{.greek-omitted} [σου]{.greek-omitted} [τα]{.greek-omitted} [εργα]{.greek-omitted} και την [αγαπην]{.greek-omitted} [και]{.greek-omitted} [την]{.greek-omitted} [πιστιν]{.greek-omitted} [πιστην]{.greek-added} και την διακονιαν και την υπομονην σου και τα εργα σου τα εσχατα [πλειονα]{.greek-omitted} [πλειωνα]{.greek-added} [των]{.greek-added} των πρωτων[2:19 | instance no. 2]{.aside}

[αλλ]{.greek-omitted} [αλλα]{.greek-added} εχω κατα σου οτι αφεις την γυναικα σου ιεζαβελ η λεγει εαυτην [προφητιν]{.greek-omitted} [προφητην]{.greek-added} και διδασκει και πλανα τους εμους δουλους πορνευσαι και φαγειν ειδωλοθυτα[2:20]{.aside}

και εδωκα [αυτη]{.greek-omitted} [αυτην]{.greek-added} χρονον ινα [μετανοηση]{.greek-omitted} [μετανοησει]{.greek-added} και ου θελει μετανοησαι εκ της πορνειας αυτης[2:21]{.aside}

ιδου βαλλω αυτην εις κλινην και τους μοιχευοντας μετ αυτης εις θλιψιν μεγαλην εαν μη μετανοησωσιν εκ των εργων αυτης[2:22]{.aside}

και τα τεκνα αυτης αποκτενω εν θανατω και γνωσονται πασαι αι εκκλησιαι οτι εγω ειμι ο ερευνων νεφρους και καρδιας και δωσω υμιν εκαστω κατα τα εργα υμων[2:23]{.aside}

υμιν δε λεγω τοις λοιποις τοις εν [θυατειροις]{.greek-omitted} [θυατηροις]{.greek-added} οσοι ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} την διδαχην ταυτην οιτινες ουκ εγνωσαν τα [βαθεα]{.greek-omitted} [βαθέα]{.greek-added} του σατανα ως λεγουσιν ου [βαλλω]{.greek-omitted} [βαλω]{.greek-added} εφ υμας αλλο βαρος[2:24]{.aside}

πλην ο εχετε κρατησατε [αχρι]{.greek-omitted} [ου]{.greek-omitted} [αν]{.greek-omitted} [ηξω]{.greek-omitted}[2:25]{.aside}

[πλην]{.greek-omitted} [ο]{.greek-omitted} [εχετε]{.greek-omitted} [κρατησατε]{.greek-omitted} [αχρι]{.greek-omitted} [αχρις]{.greek-added} ου [ανοιξω]{.greek-added} [αν]{.greek-omitted} [ηξω]{.greek-omitted}[2:25 | instance no. 2]{.aside}

και ο νικων και ο τηρων αχρι τελους τα εργα μου δωσω αυτω εξουσιαν επι των εθνων[2:26]{.aside}

και ποιμανει αυτους εν ραβδω σιδηρα ως τα [σκευη]{.greek-omitted} [σκευει]{.greek-added} τα κεραμικα συντριβησεται [ως]{.greek-omitted} [καγω]{.greek-omitted} [ειληφα]{.greek-omitted} [παρα]{.greek-omitted} [του]{.greek-omitted} [πατρος]{.greek-omitted} [μου]{.greek-omitted}[2:27]{.aside}

[ως]{.greek-added} [καγω]{.greek-added} [ειληφα]{.greek-added} [παρα]{.greek-added} [του]{.greek-added} [[πατρος]{.greek-abbr}]{.greek-added} [μου]{.greek-added} και δωσω αυτω τον αστερα τον [πρωινον]{.greek-omitted} [προινον]{.greek-added}[2:28]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[2:29]{.aside}

### Chapter 3

και τω αγγελω της εν σαρδεσιν εκκλησιας γραψον ταδε λεγει ο εχων τα επτα [πνευματα]{.greek-abbr} [του]{.greek-omitted} [θεου]{.greek-omitted} και τους επτα [αστερας]{.greek-omitted} [ασστερας]{.greek-added} οιδα σου τα εργα οτι ονομα εχεις [οτι]{.greek-omitted} [και]{.greek-added} ζης και νεκρος ει[3:1]{.aside}

γινου γρηγορων [[γρηγορον]{.corr}]{.greek-added} και [στηρισον]{.greek-omitted} [τηρησον]{.greek-added} τα λοιπα α [εμελλες]{.greek-omitted} [ημελλες]{.greek-added} αποβαλλειν ου γαρ ευρηκα σου τα εργα πεπληρωμενα ενωπιον του [θεου]{.greek-abbr} μου[3:2]{.aside}

μνημονευε ουν πως ειληφας [και]{.greek-omitted} [ηκουσας]{.greek-omitted} [και]{.greek-omitted} [τηρει]{.greek-omitted} και μετανοησον εαν ουν μη γρηγορησης ηξω επι σε ως κλεπτης και ου μη [γνως]{.greek-omitted} [γνωση]{.greek-added} ποιαν ωραν ηξω επι σε[3:3]{.aside}

αλλ ολιγα εχεις ονοματα εν σαρδεσιν α ουκ εμολυναν τα ιματια αυτων και [περιπατησουσιν]{.greek-omitted} [περιπατησουσι]{.greek-added} μετ εμου εν λευκοις οτι [αξιοι]{.greek-omitted} [εισιν]{.greek-omitted}[3:4]{.aside}

[αλλ]{.greek-omitted} [ολιγα]{.greek-omitted} [εχεις]{.greek-omitted} [ονοματα]{.greek-omitted} [εν]{.greek-omitted} [σαρδεσιν]{.greek-omitted} [α]{.greek-omitted} [ουκ]{.greek-omitted} [εμολυναν]{.greek-omitted} [τα]{.greek-omitted} [ιματια]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [περιπατησουσιν]{.greek-omitted} [μετ]{.greek-omitted} [εμου]{.greek-omitted} [εν]{.greek-omitted} [λευκοις]{.greek-omitted} [οτι]{.greek-omitted} αξιοι εισιν[3:4 | instance no. 2]{.aside}

ο νικων [ουτος]{.greek-omitted} [ουτως]{.greek-added} περιβαλειται εν ιματιοις λευκοις και ου μη εξαλειψω το ονομα αυτου [εκ]{.greek-omitted} [της]{.greek-omitted} [βιβλου]{.greek-omitted} [της]{.greek-omitted} [ζωης]{.greek-omitted} [και]{.greek-omitted} [ομολογησω]{.greek-omitted} [το]{.greek-omitted} [ονομα]{.greek-omitted} [αυτου]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [πατρος]{.greek-omitted} [μου]{.greek-omitted} [και]{.greek-omitted} [ενωπιον]{.greek-omitted} [των]{.greek-omitted} [αγγελων]{.greek-omitted} [αυτου]{.greek-omitted}[3:5]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[3:6]{.aside}

και τω αγγελω της εν [φιλαδελφεια]{.greek-omitted} [φιλαδελφια]{.greek-added} εκκλησιας γραψον ταδε λεγει [ο]{.greek-omitted} [αγιος]{.greek-omitted} ο αληθινος ο εχων την κλειν του [δαυιδ]{.greek-abbr} ο ανοιγων και ουδεις κλεισει αυτην ει μη ο ανοιγων και ουδεις ανοιξει[3:7]{.aside}

οιδα σου τα εργα ιδου δεδωκα ενωπιον σου θυραν ανεωγμενην ην ουδεις δυναται κλεισαι αυτην οτι μικραν εχεις δυναμιν και ετηρησας μου τον λογον και ουκ ηρνησω το ονομα μου[3:8]{.aside}

ιδου διδωμι εκ της συναγωγης του σατανα των λεγοντων εαυτους ιουδαιους ειναι και ουκ εισιν αλλα ψευδονται ιδου ποιησω αυτους ινα [ηξωσιν]{.greek-omitted} [ηξουσι]{.greek-added} και [προσκυνησωσιν]{.greek-omitted} [προσκυνησουσιν]{.greek-added} ενωπιον των ποδων σου και γνωσιν οτι ηγαπησα σε[3:9]{.aside}

οτι ετηρησας τον λογον της υπομονης μου καγω σε τηρησω εκ της ωρας του πειρασμου της μελλουσης ερχεσθαι επι της οικουμενης [ο]{.greek-added} [ολης]{.greek-omitted} [πειρασαι]{.greek-omitted} [τους]{.greek-omitted} [κατοικουντας]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted}[3:10]{.aside}

[οτι]{.greek-omitted} [ετηρησας]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted} [της]{.greek-omitted} [υπομονης]{.greek-omitted} [μου]{.greek-omitted} [καγω]{.greek-omitted} [σε]{.greek-omitted} [τηρησω]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [ωρας]{.greek-omitted} [του]{.greek-omitted} [πειρασμου]{.greek-omitted} [της]{.greek-omitted} [μελλουσης]{.greek-omitted} [ερχεσθαι]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [οικουμενης]{.greek-omitted} [ολης]{.greek-omitted} [λης]{.greek-added} πειρασαι τους κατοικουντας επι της γης[3:10 | instance no. 2]{.aside}

ερχομαι ταχυ κρατει ο εχεις ινα μηδεις λαβη τον στεφανον σου[3:11]{.aside}

ο νικων ποιησω [αυτον]{.greek-omitted} [αυτω]{.greek-added} στυλον εν τω ναω του [θεου]{.greek-abbr} μου και εξω ου μη εξελθη [ετι]{.greek-omitted} [ετη]{.greek-added} και γραψω επ αυτον το ονομα του [θεου]{.greek-abbr} μου και το ονομα [της]{.greek-omitted} [πολεως]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [μου]{.greek-omitted} [της]{.greek-omitted} [καινης]{.greek-omitted} [ιερουσαλημ]{.greek-omitted} [η]{.greek-omitted} [καταβαινει]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [μου]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [ονομα]{.greek-omitted} [μου]{.greek-omitted} το καινον[3:12]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[3:13]{.aside}

και τω αγγελω της εν [λαοδικεια]{.greek-omitted} [λαοδικια]{.greek-added} [εκκλησιας]{.greek-omitted} γραψον ταδε λεγει ο αμην ο μαρτυς ο πιστος και αληθινος η αρχη της [κτισεως]{.greek-omitted} [πιστεως]{.greek-added} του [θεου]{.greek-abbr}[3:14]{.aside}

οιδα σου τα εργα οτι [ουτε]{.greek-omitted} [ου]{.greek-added} ψυχρος ει ουτε ζεστος [οφελον]{.greek-omitted} [ψυχρος]{.greek-omitted} [ης]{.greek-omitted} [η]{.greek-omitted} [ζεστος]{.greek-omitted}[3:15]{.aside}

ουτως οτι χλιαρος ει και ου ζεστος ουτε ψυχρος μελλω σε εμεσαι εκ του στοματος μου[3:16]{.aside}

οτι λεγεις [οτι]{.greek-added} πλουσιος ειμι [και]{.greek-omitted} [πεπλουτηκα]{.greek-omitted} και ουδενος χρειαν εχω και ουκ οιδας οτι συ ει ο [ταλαιπωρος]{.greek-omitted} [ελεεινος]{.greek-added} και ο [ελεεινος]{.greek-omitted} [ταλαιπωρος]{.greek-added} και πτωχος και [γυμνος]{.greek-added} [και]{.greek-added} τυφλος [και]{.greek-omitted} [γυμνος]{.greek-omitted}[3:17]{.aside}

συμβουλευω σοι αγορασαι χρυσιον παρ [εμου]{.greek-omitted} [εμοι]{.greek-added} πεπυρωμενον εκ πυρος ινα πλουτησης και ιματια λευκα ινα περιβαλη και μη φανερωθη η αισχυνη της γυμνοτητος σου [και]{.greek-omitted} [κολλυριον]{.greek-omitted} [ινα]{.greek-omitted} [εγχριση]{.greek-omitted} [τους]{.greek-omitted} [οφθαλμους]{.greek-omitted} [σου]{.greek-omitted} [ινα]{.greek-omitted} [βλεπης]{.greek-omitted}[3:18]{.aside}

[συμβουλευω]{.greek-omitted} [σοι]{.greek-omitted} [αγορασαι]{.greek-omitted} [χρυσιον]{.greek-omitted} [παρ]{.greek-omitted} [εμου]{.greek-omitted} [πεπυρωμενον]{.greek-omitted} [εκ]{.greek-omitted} [πυρος]{.greek-omitted} [ινα]{.greek-omitted} [πλουτησης]{.greek-omitted} και [ιματια]{.greek-omitted} [λευκα]{.greek-omitted} [ινα]{.greek-omitted} [περιβαλη]{.greek-omitted} [και]{.greek-omitted} [μη]{.greek-omitted} [φανερωθη]{.greek-omitted} [η]{.greek-omitted} [αισχυνη]{.greek-omitted} [της]{.greek-omitted} [γυμνοτητος]{.greek-omitted} [σου]{.greek-omitted} [και]{.greek-omitted} [κολλυριον]{.greek-omitted} [κολουριον]{.greek-added} ινα εγχριση τους οφθαλμους σου ινα [βλεπης]{.greek-omitted} [βλεπεις]{.greek-added}[3:18 | instance no. 2]{.aside}

εγω οσους εαν φιλω ελεγχω και παιδευω [ζηλωσον]{.greek-omitted} [ζηλευε]{.greek-added} ουν και μετανοησον[3:19]{.aside}

ιδου εστηκα επι την θυραν και κρουω εαν τις ακουση της φωνης μου και ανοιξη την θυραν και εισελευσομαι προς αυτον και δειπνησω μετ αυτου και αυτος μετ εμου[3:20]{.aside}

ο νικων δωσω αυτω [καθισαι]{.greek-omitted} [καθησαι]{.greek-added} μετ εμου εν τω θρονω μου ως καγω ενικησα και εκαθισα μετα του [πατρος]{.greek-abbr} μου εν τω [θρονω]{.greek-omitted} [θρωνω]{.greek-added} αυτου[3:21]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις [εκκλησιαις]{.greek-omitted} [εκκλησιας]{.greek-added}[3:22]{.aside}

### Chapter 4

μετα ταυτα ειδον και ιδου θυρα ανεωγμενη εν τω [ουρανω]{.greek-abbr} και η φωνη η πρωτη ην ηκουσα ως σαλπιγγος λαλουσης μετ εμου λεγων αναβα ωδε και δειξω [σοι]{.greek-omitted} [σε]{.greek-added} α δει γενεσθαι μετα ταυτα[4:1]{.aside}

[και]{.greek-omitted} ευθεως εγενομην εν [πνευματι]{.greek-abbr} και ιδου θρονος εκειτο εν τω [ουρανω]{.greek-abbr} και επι τον θρονον καθημενος[4:2]{.aside}

[ομοιος]{.greek-omitted} [ομοιως]{.greek-added} ορασει λιθω ιασπιδι και σαρδιω και [ιρις]{.greek-omitted} [ϊρις]{.greek-added} [κυκλοθεν]{.greek-omitted} [κυκλωθεν]{.greek-added} του θρονου [ομοιως]{.greek-omitted} [ομοιος]{.greek-added} ορασις σμαραγδινων[4:3]{.aside}

[και]{.greek-omitted} κυκλοθεν του θρονου [θρονοι]{.greek-omitted} [εικοσι]{.greek-omitted} [τεσσαρες]{.greek-omitted} [και]{.greek-omitted} [επι]{.greek-omitted} [τους]{.greek-omitted} [θρονους]{.greek-omitted} [τους]{.greek-omitted} [εικοσι]{.greek-omitted} [τεσσαρας]{.greek-omitted} [πρεσβυτερους]{.greek-omitted} [καθημενους]{.greek-omitted} [περιβεβλημενους]{.greek-omitted} [εν]{.greek-omitted} [ιματιοις]{.greek-omitted} [λευκοις]{.greek-omitted} [και]{.greek-omitted} [επι]{.greek-omitted} [τας]{.greek-omitted} [κεφαλας]{.greek-omitted} [αυτων]{.greek-omitted} [στεφανους]{.greek-omitted} [χρυσους]{.greek-omitted}[4:4]{.aside}

και [κυκλοθεν]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} θρονοι [εικοσι]{.greek-omitted} [τεσσαρες]{.greek-omitted} [οι]{.greek-added} [[κδ]{.greek-abbr}]{.greek-added} και επι τους θρονους τους [[κδ]{.greek-abbr}]{.greek-added} [εικοσι]{.greek-omitted} [τεσσαρας]{.greek-omitted} πρεσβυτερους καθημενους [περιβεβλημενους]{.greek-omitted} [περιβεβλημενοις]{.greek-added} εν ιματιοις λευκοις και επι τας κεφαλας αυτων στεφανους χρυσους[4:4 | instance no. 2]{.aside}

και εκ του θρονου εκπορευονται αστραπαι και φωναι και βρονται και επτα λαμπαδες πυρος καιομεναι ενωπιον του θρονου αυτου [αι]{.greek-omitted} [α]{.greek-added} εισιν επτα [πνευματα]{.greek-abbr} του [θεου]{.greek-abbr}[4:5]{.aside}

και ενωπιον του θρονου [ως]{.greek-omitted} θαλασσα υαλινη ομοια [κρυσταλλω]{.greek-omitted} [κρυσταλω]{.greek-added} και εν μεσω του θρονου και κυκλω [του]{.greek-omitted} [αυτου]{.greek-added} [θρονου]{.greek-omitted} τεσσαρα ζωα γεμοντα οφθαλμων εμπροσθεν και οπισθεν[4:6]{.aside}

και το [πρωτον]{.greek-added} ζωον [το]{.greek-omitted} [πρωτον]{.greek-omitted} ομοιον λεοντι και το δευτερον ζωον ομοιον μοσχω και το τριτον ζωον [εχον]{.greek-omitted} [εχων]{.greek-added} προσωπον [ανθρωπου]{.greek-abbr} και το τεταρτον [ζωον]{.greek-omitted} ομοιον αετω πετομενω[4:7]{.aside}

και [τα]{.greek-omitted} τεσσαρα ζωα εν καθ εν [εχον]{.greek-omitted} [εχων]{.greek-added} ανα πτερυγας εξ κυκλοθεν και εσωθεν γεμουσιν οφθαλμων και αναπαυσιν ουκ εχουσιν ημερας και νυκτος λεγοντες αγιος αγιος αγιος [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ ο [ων]{.greek-added} [και]{.greek-added} [ο]{.greek-added} ην και ο [ων]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} ερχομενος[4:8]{.aside}

και οταν [δω]{.greek-added} [δωσιν]{.greek-omitted} [τα]{.greek-omitted} [ζωα]{.greek-omitted} [δοξαν]{.greek-omitted} [και]{.greek-omitted} [τιμην]{.greek-omitted} [και]{.greek-omitted} [ευχαριστιαν]{.greek-omitted} [τω]{.greek-omitted} [καθημενω]{.greek-omitted} [επι]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [τω]{.greek-omitted} [ζωντι]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [αιωνας]{.greek-omitted} [των]{.greek-omitted} [αιωνων]{.greek-omitted}[4:9]{.aside}

[σι]{.greek-added} [και]{.greek-omitted} [οταν]{.greek-omitted} [δωσιν]{.greek-omitted} τα ζωα δοξαν και τιμην και ευχαριστιαν τω καθημενω επι του θρονου τω ζωντι εις τους αιωνας των αιωνων[4:9 | instance no. 2]{.aside}

πεσουνται οι εικοσι τεσσαρες πρεσβυτεροι ενωπιον του καθημενου επι του θρονου και [προσκυνησουσιν]{.greek-omitted} [προσκυνησουσι]{.greek-added} τω ζωντι εις τους αιωνας των αιωνων και [βαλουσιν]{.greek-omitted} [βαλοῦσι]{.greek-added} τους στεφανους αυτων [ενωπιον]{.greek-omitted} [ενωπιων]{.greek-added} του θρονου λεγοντες[4:10]{.aside}

αξιος ει ο [κυριος]{.greek-abbr} και ο [θεος]{.greek-abbr} ημων [ο]{.greek-omitted} [αγιος]{.greek-omitted} λαβειν την δοξαν και την [τιμην]{.greek-omitted} [τιμιν]{.greek-added} και την δυναμιν οτι συ εκτισας παντα και δια το θελημα σου ησαν και εκτισθησαν[4:11]{.aside}

### Chapter 5

και ειδον επι την δεξιαν του καθημενου επι του θρονου βιβλιον γεγραμμενον εσωθεν και εξωθεν κατεσφραγισμενον σφραγισιν επτα[5:1]{.aside}

και ειδον αγγελον ισχυρον κηρυσσοντα εν φωνη μεγαλη [τις]{.greek-omitted} [τίς]{.greek-added} αξιος εστιν ανοιξαι το [βιβλιον]{.greek-omitted} [ββλιον]{.greek-added} και λυσαι τας [σφραγιδας]{.greek-omitted} [φραγιδας]{.greek-added} αυτου[5:2]{.aside}

και ουδεις [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} εν τω [ουρανω]{.greek-abbr} ανω ουτε επι της γης [κατω]{.greek-added} [ουτε]{.greek-omitted} [υποκατω]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} ανοιξαι το βιβλιον ουτε βλεπειν αυτο[5:3]{.aside}

και εγω εκλαιον πολυ οτι ουδεις αξιος ευρεθη ανοιξαι το βιβλιον ουτε [βλε]{.greek-added} [βλεπειν]{.greek-omitted} [αυτο]{.greek-omitted}[5:4]{.aside}

[πειν]{.greek-added} [και]{.greek-omitted} [εγω]{.greek-omitted} [εκλαιον]{.greek-omitted} [πολυ]{.greek-omitted} [οτι]{.greek-omitted} [ουδεις]{.greek-omitted} [αξιος]{.greek-omitted} [ευρεθη]{.greek-omitted} [ανοιξαι]{.greek-omitted} [το]{.greek-omitted} [βιβλιον]{.greek-omitted} [ουτε]{.greek-omitted} [βλεπειν]{.greek-omitted} αυτο[5:4 | instance no. 2]{.aside}

και εις εκ των πρεσβυτερων λεγει μοι μη κλαιε ιδου ενικησεν ο λεων ο εκ της φυλης ιουδα η ριζα [δαυιδ]{.greek-abbr} ο ανοιγων το βιβλιον και τας επτα σφραγιδας αυτου[5:5]{.aside}

και ειδον εν μεσω του θρονου και των τεσσαρων ζωων και εν μεσω των πρεσβυτερων αρνιον [εστηκος]{.greek-omitted} [εστηκως]{.greek-added} ως [εσφαγμενον]{.greek-omitted} [εσφραγισμενον]{.greek-added} [εχον]{.greek-omitted} [εχων]{.greek-added} κερατα επτα και οφθαλμους επτα α [εισιν]{.greek-omitted} [εστι]{.greek-added} τα επτα [πνευματα]{.greek-abbr} του [θεου]{.greek-abbr} αποστελλομενα εις πασαν την γην[5:6]{.aside}

και [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και ειληφεν εκ της δεξιας του καθημενου επι του θρονου[5:7]{.aside}

και οτε [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added} το βιβλιον τα τεσσαρα ζωα και οι [εικοσι]{.greek-omitted} [εικο]{.greek-added} [τεσσαρες]{.greek-omitted} [τεσαρες]{.greek-added} πρεσβυτεροι επεσον [ενωπιον]{.greek-omitted} [ενοπιον]{.greek-added} του αρνιου εχοντες εκαστος κιθαραν και φιαλας χρυσας γεμουσας [θυαματων]{.greek-added} [θυμιαματων]{.corr} αι [εισιν]{.greek-omitted} [εισι]{.greek-added} προσευχαι των αγιων[5:8]{.aside}

και αδουσιν ωδην καινην λεγοντες αξιος ει λαβειν το βιβλιον και ανοιξαι τας σφραγιδας αυτου οτι [εσφαγης]{.greek-omitted} [εσφαγις]{.greek-added} και ηγορασας τω [θεω]{.greek-abbr} ημας εν τω αιματι σου εκ πασης φυλης και [γλωσσης]{.greek-omitted} [και]{.greek-omitted} λαου και εθνους[5:9]{.aside}

και εποιησας αυτους τω [θεω]{.greek-abbr} ημων [και]{.greek-added} βασιλεις και ιερεις και [βασιλευσουσιν]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted}[5:10]{.aside}

[και]{.greek-omitted} [εποιησας]{.greek-omitted} [αυτους]{.greek-omitted} [τω]{.greek-omitted} [θεω]{.greek-omitted} [ημων]{.greek-omitted} [βασιλεις]{.greek-omitted} [και]{.greek-omitted} [ιερεις]{.greek-omitted} [και]{.greek-omitted} βασιλευσουσιν επι της γης[5:10 | instance no. 2]{.aside}

και ειδον και ηκουσα ως φωνην αγγελων πολλων κυκλω του θρονου και των ζωων και των πρεσβυτερων και ην ο αριθμος αυτων μυριαδες μυριαδων και χιλιαδες χιλιαδων[5:11]{.aside}

λεγοντες φωνη μεγαλη αξιον [εστιν]{.greek-omitted} [εστι]{.greek-added} το αρνιον το εσφαγμενον λαβειν την δυναμιν και [τον]{.greek-omitted} πλουτον και σοφιαν και ισχυν και τιμην και δοξαν και ευλογιαν[5:12]{.aside}

και παν κτισμα ο εν τω [ουρανω]{.greek-abbr} και επι [της]{.greek-omitted} [γης]{.greek-omitted} [και]{.greek-omitted} [υποκατω]{.greek-omitted} [της]{.greek-omitted} γης και επι της θαλασσης [εστιν]{.greek-omitted} [και]{.greek-added} [επι]{.greek-added} και τα εν [αυτοις]{.greek-omitted} [αυτης]{.greek-added} [και]{.greek-added} παντας ηκουσα λεγοντας τω καθημενω επι [του]{.greek-omitted} [θρονου]{.greek-omitted} [τω]{.greek-added} [θρονω]{.greek-added} και τω αρνιω η ευλογια και η τιμη και η δοξα και το κρατος εις τους αιωνας των αιωνων αμην[5:13]{.aside}

και τα τεσσαρα ζωα λεγοντα το αμην και οι πρεσβυτεροι επεσον και προσεκυνησαν[5:14]{.aside}

### Chapter 6

και ειδον οτι [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} το αρνιον μιαν εκ των επτα σφραγιδων και ηκουσα ενος εκ των τεσσαρων ζωων λεγοντος ως [φωνη]{.greek-omitted} [φωνῆ]{.greek-added} βροντης ερχου [και]{.greek-omitted} [ιδε]{.greek-omitted}[6:1]{.aside}

[και]{.greek-added} [ιδε]{.greek-added} και ιδου ιππος λευκος και ο καθημενος επ αυτον εχων τοξον και εδοθη αυτω στεφανος [και]{.greek-omitted} [εξηλθεν]{.greek-omitted} [νικων]{.greek-omitted} [και]{.greek-omitted} [ινα]{.greek-omitted} [νικηση]{.greek-omitted}[6:2]{.aside}

και [ιδου]{.greek-omitted} [ιππος]{.greek-omitted} [λευκος]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [καθημενος]{.greek-omitted} [επ]{.greek-omitted} [αυτον]{.greek-omitted} [εχων]{.greek-omitted} [τοξον]{.greek-omitted} [και]{.greek-omitted} [εδοθη]{.greek-omitted} [αυτω]{.greek-omitted} [στεφανος]{.greek-omitted} [και]{.greek-omitted} [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} νικων και ινα νικηση[6:2 | instance no. 2]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την δευτεραν σφραγιδα ηκουσα του δευτερου ζωου λεγοντος ερχου[6:3]{.aside}

και εξηλθεν αλλος ιππος πυρος και τω καθημενω επ αυτον [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} αυτω λαβειν την ειρηνην εκ της γης ινα [αλληλους]{.greek-omitted} [αλληλοις]{.greek-added} [σφαξωσιν]{.greek-omitted} [σφαξωσι]{.greek-added} και [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} αυτω μαχαιρα μεγαλη[6:4]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την σφραγιδα την τριτην ηκουσα του τριτου ζωου λεγοντος ερχου και ιδε και ιδου ιππος μελας και ο καθημενος επ αυτον εχων ζυγον εν τη χειρι αυτου[6:5]{.aside}

και ηκουσα [φωνην]{.greek-omitted} [φωνη]{.greek-added} εν μεσω των τεσσαρων ζωων λεγουσαν χοινιξ σιτου δηναριου και [τρεις]{.greek-omitted} [χοινικες]{.greek-omitted} [κριθης]{.greek-omitted} [δηναριου]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [τον]{.greek-added} ελαιον και τον οινον μη [αδικησης]{.greek-omitted} [αδικησις]{.greek-added}[6:6]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την σφραγιδα την τεταρτην ηκουσα του τεταρτου ζωου λεγοντος ερχου και [ιδε]{.greek-omitted} [ειδε]{.greek-added}[6:7]{.aside}

[και]{.greek-added} [ιδον]{.greek-added} και ιδου ιππος χλωρος και ο καθημενος επανω αυτου ονομα αυτω ο θανατος και ο αδης [ηκολουθει]{.greek-omitted} [ηκολουθη]{.greek-added} αυτω και [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} αυτω εξουσια επι το τεταρτον της γης αποκτειναι εν ρομφαια και [εν]{.greek-omitted} λιμω και εν [θα]{.greek-added} [θανατω]{.greek-omitted} [και]{.greek-omitted} [υπο]{.greek-omitted} [των]{.greek-omitted} [θηριων]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted}[6:8]{.aside}

[νατω]{.greek-added} και [ιδου]{.greek-omitted} [ιππος]{.greek-omitted} [ιπο]{.greek-added} [χλωρος]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [καθημενος]{.greek-omitted} [επανω]{.greek-omitted} [αυτου]{.greek-omitted} [ονομα]{.greek-omitted} [αυτω]{.greek-omitted} [ο]{.greek-omitted} [θανατος]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [αδης]{.greek-omitted} [ηκολουθει]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [εδοθη]{.greek-omitted} [αυτω]{.greek-omitted} [εξουσια]{.greek-omitted} [επι]{.greek-omitted} [το]{.greek-omitted} [τεταρτον]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [αποκτειναι]{.greek-omitted} [εν]{.greek-omitted} [ρομφαια]{.greek-omitted} [και]{.greek-omitted} [εν]{.greek-omitted} [λιμω]{.greek-omitted} [και]{.greek-omitted} [εν]{.greek-omitted} [θανατω]{.greek-omitted} [και]{.greek-omitted} [υπο]{.greek-omitted} των θηριων της γης[6:8 | instance no. 2]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την [πεμπτην]{.greek-omitted} [πεμτην]{.greek-added} σφραγιδα ειδον υποκατω του θυσιαστηριου τας ψυχας των εσφαγμενων δια τον λογον του [θεου]{.greek-abbr} και δια την μαρτυριαν του αρνιου ην ειχον[6:9]{.aside}

και εκραξαν [φωνη]{.greek-omitted} [φωνην]{.greek-added} [μεγαλη]{.greek-omitted} [μεγαλην]{.greek-added} λεγοντες εως ποτε ο δεσποτης ο αγιος και αληθινος ου κρινεις και εκδικεις το αιμα ημων εκ των κατοικουντων επι της γης[6:10]{.aside}

και εδοθη αυτοις [εκαστω]{.greek-omitted} στολη λευκη και ερρεθη αυτοις ινα [αναπαυσωνται]{.greek-omitted} [αναπαυσονται]{.greek-added} [ετι]{.greek-omitted} [χρονον]{.greek-omitted} [χρονων]{.greek-added} εως [πληρωσωσιν]{.greek-omitted} [πληρωσωσι]{.greek-added} και οι συνδουλοι αυτων [και]{.greek-omitted} οι αδελφοι αυτων και οι μελλοντες αποκτενεσθαι ως και αυτοι[6:11]{.aside}

και ειδον οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την σφραγιδα την εκτην και [σεισμος]{.greek-omitted} [σισμος]{.greek-added} μεγας εγενετο και ο ηλιος [μελας]{.greek-omitted} [σελας]{.greek-added} εγενετο ως σακκος τριχινος και η σεληνη ολη εγενετο ως αιμα[6:12]{.aside}

και οι αστερες του [ουρανου]{.greek-abbr} επεσον εις την γην ως συκη βαλουσα τους ολυνθους αυτης υπο ανεμου μεγαλου σειομενη[6:13]{.aside}

και ο [ουρανος]{.greek-abbr} απεχωρισθη ως βιβλιον [ελισσομενον]{.greek-omitted} [ελισσομενος]{.greek-added} και παν ορος και [νη]{.greek-added} [νησος]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [τοπων]{.greek-omitted} [αυτων]{.greek-omitted} [εκινηθησαν]{.greek-omitted}[6:14]{.aside}

[και]{.greek-omitted} [ο]{.greek-omitted} [ουρανος]{.greek-omitted} [απεχωρισθη]{.greek-omitted} [ως]{.greek-omitted} [βιβλιον]{.greek-omitted} [ελισσομενον]{.greek-omitted} [και]{.greek-omitted} [παν]{.greek-omitted} [ορος]{.greek-omitted} [και]{.greek-omitted} [νησος]{.greek-omitted} [σος]{.greek-added} εκ των [τοπων]{.greek-omitted} [τοπον]{.greek-added} αυτων [εκινηθησαν]{.greek-omitted} [εκηνηθησαν]{.greek-added}[6:14 | instance no. 2]{.aside}

και οι βασιλεις της γης και οι μεγιστανες και οι χιλιαρχοι και οι πλουσιοι και οι ισχυροι και πας δουλος και ελευθερος εκρυψαν εαυτους εις τα [σπηλαια]{.greek-omitted} [σπηλεα]{.greek-added} και εις τας πετρας των ορεων[6:15]{.aside}

και [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} τοις [ορεσιν]{.greek-omitted} [ορεσι]{.greek-added} και ταις πετραις πεσετε εφ ημας και κρυψατε ημας απο προσωπου του καθημενου επι του θρονου και απο της οργης του αρνιου[6:16]{.aside}

οτι ηλθεν η ημερα η μεγαλη της οργης αυτου και τις δυναται σταθηναι[6:17]{.aside}

### Chapter 7

και μετα [τουτο]{.greek-omitted} [ταυτα]{.greek-added} ειδον [τεσσαρας]{.greek-omitted} [τεσαρας]{.greek-added} αγγελους εστωτας επι [τας]{.greek-omitted} τεσσαρας γωνιας [επι]{.greek-added} της γης [και]{.greek-added} κρατουντας τους τεσσαρας ανεμους της γης ινα μη πνεη ανεμος επι της γης μητε επι της θαλασσης μητε επι τι δενδρον[7:1]{.aside}

και ειδον αλλον αγγελον αναβαινοντα απο ανατολης ηλιου εχοντα σφραγιδα [θεου]{.greek-abbr} ζωντος και [εκραξεν]{.greek-omitted} [εκραξε]{.greek-added} φωνη μεγαλη τοις τεσσαρσιν αγγελοις οις εδοθη [αυτοις]{.greek-omitted} αδικησαι την γην και την θαλασσαν[7:2]{.aside}

λεγων μη [αδικησητε]{.greek-omitted} [αδικησιτε]{.greek-added} την γην μητε την θαλασσαν [μητε]{.greek-omitted} [τα]{.greek-omitted} [δενδρα]{.greek-omitted} [αχρι]{.greek-omitted} [ου]{.greek-omitted} [σφραγισωμεν]{.greek-omitted} [τους]{.greek-omitted} [δουλους]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [ημων]{.greek-omitted} [επι]{.greek-omitted} [των]{.greek-omitted} [μετωπων]{.greek-omitted} [αυτων]{.greek-omitted}[7:3]{.aside}

[λεγων]{.greek-omitted} [μη]{.greek-omitted} [αδικησητε]{.greek-omitted} [την]{.greek-omitted} [γην]{.greek-omitted} μητε [την]{.greek-omitted} [θαλασσαν]{.greek-omitted} [μητε]{.greek-omitted} [τα]{.greek-omitted} [δενδρα]{.greek-omitted} [δενδρον]{.greek-added} [αχρι]{.greek-omitted} [αχρις]{.greek-added} ου σφραγισωμεν τους δουλους του [θεου]{.greek-abbr} ημων επι των [μετωπων]{.greek-omitted} [μετοπων]{.greek-added} αυτων[7:3 | instance no. 2]{.aside}

και ηκουσα [τον]{.greek-omitted} [των]{.greek-added} [αριθμον]{.greek-omitted} [αριθμων]{.greek-added} των εσφραγισμενων εκατον [και]{.greek-omitted} [τεσσαρακοντα]{.greek-omitted} [τεσσερακοντα]{.greek-added} τεσσαρες χιλιαδες [εσφραγισμενων]{.greek-omitted} εκ πασης φυλης υιων [ισραηλ]{.greek-abbr}[7:4]{.aside}

εκ φυλης ιουδα [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εσφραγισμεναι εκ φυλης [ρουβιμ]{.greek-omitted} [ρουβιν]{.greek-added} [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εκ φυλης γαδ [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες[7:5]{.aside}

εκ φυλης ασηρ [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εκ φυλης [νεφθαλειμ]{.greek-omitted} [νεφθαλημ]{.greek-added} [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εκ φυλης μανασση [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες[7:6]{.aside}

εκ φυλης συμεων [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εκ φυλης λευι [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εκ φυλης ισαχαρ [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες[7:7]{.aside}

εκ φυλης ζαβουλων [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εκ φυλης ιωσηφ [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εκ φυλης [βενιαμιν]{.greek-omitted} [βενιαμην]{.greek-added} [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εσφραγισμεναι[7:8]{.aside}

μετα ταυτα ειδον και ιδου οχλος πολυς ον αριθμησαι ουδεις εδυνατο εκ παντος εθνους και φυλων και λαων και γλωσσων εστωτας ενωπιον του θρονου και ενωπιον του αρνιου [περιβεβλημενας]{.greek-added} [περιβεβλημενους]{.corr} στολας λευκας και φοινικας εν ταις χερσιν αυτων[7:9]{.aside}

και [κραζουσιν]{.greek-omitted} [φωνη]{.greek-omitted} [μεγαλη]{.greek-omitted} [λεγοντες]{.greek-omitted} [η]{.greek-omitted} [σωτηρια]{.greek-omitted} [τω]{.greek-omitted} [θεω]{.greek-omitted} [ημων]{.greek-omitted} [τω]{.greek-omitted} [καθημενω]{.greek-omitted} [επι]{.greek-omitted} [τω]{.greek-omitted} [θρονω]{.greek-omitted} [και]{.greek-omitted} [τω]{.greek-omitted} [αρνιω]{.greek-omitted}[7:10]{.aside}

[και]{.greek-omitted} [κραζουσιν]{.greek-omitted} [κραζουσι]{.greek-added} φωνη μεγαλη λεγοντες η [σωτηρια]{.greek-abbr} τω [θεω]{.greek-abbr} ημων τω καθημενω επι τω θρονω και [επι]{.greek-added} τω αρνιω[7:10 | instance no. 2]{.aside}

και παντες οι αγγελοι [ειστηκεισαν]{.greek-omitted} [ηστηκησαν]{.greek-added} κυκλω του θρονου και των πρεσβυτερων και των τεσσαρων ζωων και επεσον ενωπιον του θρονου [αυτου]{.greek-added} επι τα προσωπα αυτων και προσεκυνησαν τω [θεω]{.greek-abbr}[7:11]{.aside}

λεγοντες αμην η ευλογια και η δοξα και η σοφια και η ευχαριστια και η τιμη και η δυναμις και η ισχυς τω [θεω]{.greek-abbr} ημων εις τους αιωνας των αιωνων αμην[7:12]{.aside}

και απεκριθη εις εκ των πρεσβυτερων λεγων μοι ουτοι οι περιβεβλημενοι τας στολας τας λευκας τινες [εισιν]{.greek-omitted} [εισι]{.greek-added} και ποθεν ηλθον[7:13]{.aside}

και ειπον αυτω [κυριε]{.greek-abbr} μου συ οιδας και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} μοι ουτοι εισιν οι ερχομενοι εκ της θλιψεως της μεγαλης και [επλυναν]{.greek-omitted} [επλατυναν]{.greek-added} τας στολας αυτων και ελευκαναν εν τω αιματι του αρνιου[7:14]{.aside}

δια τουτο εισιν ενωπιον [του]{.greek-omitted} [θρονου]{.greek-omitted} του [θεου]{.greek-abbr} και λατρευουσιν αυτω ημερας και νυκτος εν τω ναω αυτου και ο καθημενος επι τω θρονω σκηνωσει επ αυτους[7:15]{.aside}

ου πεινασουσιν ετι ουδε [δι]{.greek-added} [διψησουσιν]{.greek-omitted} [ετι]{.greek-omitted} [ουδ]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [πεση]{.greek-omitted} [επ]{.greek-omitted} [αυτους]{.greek-omitted} [ο]{.greek-omitted} [ηλιος]{.greek-omitted} [ουδε]{.greek-omitted} [παν]{.greek-omitted} [καυμα]{.greek-omitted}[7:16]{.aside}

[ου]{.greek-omitted} [πεινασουσιν]{.greek-omitted} [ετι]{.greek-omitted} [ουδε]{.greek-omitted} [διψησουσιν]{.greek-omitted} [ψησισουσιν]{.greek-added} ετι ουδ ου μη πεση επ αυτους ο ηλιος ουδε παν καυμα[7:16 | instance no. 2]{.aside}

οτι το αρνιον το ανα μεσον του θρονου [ποιμαινει]{.greek-omitted} [ποιμεν]{.greek-added} αυτους και οδηγει αυτους επι ζωης πηγας υδατων και εξαλειψει ο [θεος]{.greek-abbr} παν δακρυον εκ των οφθαλμων αυτων[7:17]{.aside}

### Chapter 8

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την σφραγιδα την εβδομην εγενετο σιγη εν τω [ουρανω]{.greek-abbr} ως [ημιωριον]{.greek-omitted} [ἠμιώριον]{.greek-added}[8:1]{.aside}

και ειδον τους επτα αγγελους οι ενωπιον του [θεου]{.greek-abbr} [εστηκασιν]{.greek-omitted} [εστηκασι]{.greek-added} και [εδοθησαν]{.greek-omitted} [εδωθησαν]{.greek-added} αυτοις επτα σαλπιγγες[8:2]{.aside}

και αλλος αγγελος [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και εσταθη επι του θυσιαστηριου εχων λιβανωτον χρυσουν και [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} αυτω θυμιαματα πολλα ινα δωση ταις προσευχαις των αγιων παντων επι το θυσιαστηριον το χρυσουν το ενωπιον του θρονου[8:3]{.aside}

και ανεβη ο καπνος των θυμιαματων ταις προσευχαις των αγιων εκ χειρος του αγγελου ενωπιον του [θεου]{.greek-abbr}[8:4]{.aside}

και ειληφεν ο αγγελος τον λιβανωτον και εγεμισεν αυτον εκ του πυρος του θυσιαστηριου και εβαλεν εις την γην και [εγενοντο]{.greek-omitted} [εγενετο]{.greek-added} [φωναι]{.greek-added} [και]{.greek-added} βρονται [και]{.greek-omitted} [φωναι]{.greek-omitted} και αστραπαι και σεισμος[8:5]{.aside}

και [οι]{.greek-omitted} [επτα]{.greek-omitted} [αγγελοι]{.greek-omitted} [οι]{.greek-omitted} [εχοντες]{.greek-omitted} [τας]{.greek-omitted} [επτα]{.greek-omitted} [σαλπιγγας]{.greek-omitted} [ητοιμασαν]{.greek-omitted} [εαυτους]{.greek-omitted} [ινα]{.greek-omitted} [ια]{.greek-added} [σαλπισωσιν]{.greek-omitted}[8:6]{.aside}

[και]{.greek-omitted} οι επτα αγγελοι οι εχοντες τας επτα σαλπιγγας ητοιμασαν εαυτους ινα [σαλπισωσιν]{.greek-omitted} [σαλπισωσι]{.greek-added}[8:6 | instance no. 2]{.aside}

και ο πρωτος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και εγενετο χαλαζα και πυρ μεμιγμενα εν αιματι και εβληθη εις την γην και το τριτον [της]{.greek-omitted} [γης]{.greek-omitted} [κατεκαη]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [τριτον]{.greek-omitted} των δενδρων κατεκαη [και]{.greek-omitted} [πας]{.greek-omitted} [χορτος]{.greek-omitted} [χλωρος]{.greek-omitted} [κατεκαη]{.greek-omitted}[8:7]{.aside}

και ο δευτερος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και ως ορος μεγα καιομενον εβληθη εις την θαλασσαν και εγενετο το τριτον της θαλασσης αιμα[8:8]{.aside}

και [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} το τριτον των κτισματων εν τη θαλασση τα εχοντα ψυχας και το τριτον των πλοιων διεφθαρη[8:9]{.aside}

και ο τριτος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και επεσεν εκ του [ουρανου]{.greek-abbr} αστηρ μεγας καιομενος ως λαμπας και επεσεν επι το τριτον των ποταμων και επι τας πηγας των υδατων[8:10]{.aside}

και το ονομα του αστερος λεγεται ο αψινθος και εγενετο το τριτον των υδατων εις αψινθον και πολλοι των [ανθρωπων]{.greek-abbr} απεθανον εκ των υδατων οτι επικρανθησαν[8:11]{.aside}

και ο [τεταρτος]{.greek-omitted} [τεταρ]{.greek-added} [ιβ]{.greek-added} [αγγελος]{.greek-omitted} [εσαλπισεν]{.greek-omitted} [και]{.greek-omitted} [επληγη]{.greek-omitted} [το]{.greek-omitted} [τριτον]{.greek-omitted} [του]{.greek-omitted} [ηλιου]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [τριτον]{.greek-omitted} [της]{.greek-omitted} [σεληνης]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [τριτον]{.greek-omitted} [των]{.greek-omitted} [αστερων]{.greek-omitted} [ινα]{.greek-omitted} [σκοτισθη]{.greek-omitted} [το]{.greek-omitted} [τριτον]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [τριτον]{.greek-omitted} [αυτης]{.greek-omitted} [μη]{.greek-omitted} [φανη]{.greek-omitted} [η]{.greek-omitted} [ημερα]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [νυξ]{.greek-omitted} [ομοιως]{.greek-omitted}[8:12]{.aside}

[τος]{.greek-added} [και]{.greek-omitted} [ο]{.greek-omitted} [τεταρτος]{.greek-omitted} αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και επληγη [το]{.greek-omitted} [τριτον]{.greek-omitted} [του]{.greek-omitted} [ηλιου]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [τριτον]{.greek-omitted} [της]{.greek-omitted} [σεληνης]{.greek-omitted} [και]{.greek-omitted} το τριτον των αστερων ινα σκοτισθη το τριτον αυτων και το τριτον [αυτης]{.greek-omitted} [αυτοις]{.greek-added} μη φανη η ημερα και η νυξ ομοιως[8:12 | instance no. 2]{.aside}

και ειδον και ηκουσα ενος αετου [πετομενου]{.greek-omitted} [πετωμενου]{.greek-added} εν μεσουρανηματι λεγοντος φωνη μεγαλη ουαι ουαι ουαι [τοις]{.greek-omitted} [τους]{.greek-added} [κατοικουσιν]{.greek-omitted} [κατοικουντας]{.greek-added} επι της γης εκ των [λοιπων]{.greek-omitted} [τριων]{.greek-added} φωνων της σαλπιγγος των τριων αγγελων των μελλοντων σαλπιζειν[8:13]{.aside}

### Chapter 9

και ο πεμπτος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και ειδον αστερα εκ του [ουρανου]{.greek-abbr} πεπτωκοτα εις την γην και [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} αυτω η κλεις του φρεατος της αβυσσου[9:1]{.aside}

[και]{.greek-omitted} [ηνοιξεν]{.greek-omitted} [το]{.greek-omitted} [φρεαρ]{.greek-omitted} [της]{.greek-omitted} [αβυσσου]{.greek-omitted} και ανεβη καπνος εκ του φρεατος ως καπνος καμινου καιομενης και εσκοτισθη ο ηλιος και ο αηρ εκ του καπνου του φρεατος[9:2]{.aside}

και εκ του καπνου εξηλθον [ακριδες]{.greek-omitted} [ακριδαι]{.greek-added} εις την γην και [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} [αυταις]{.greek-omitted} [αυτοις]{.greek-added} εξουσια ως εχουσιν [εξουσιαν]{.greek-omitted} οι σκορπιοι της γης[9:3]{.aside}

και ερρεθη αυταις ινα μη [αδικησωσιν]{.greek-omitted} [αδικησωσι]{.greek-added} τον [χορ]{.greek-added} [χορτον]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [ουδε]{.greek-omitted} [παν]{.greek-omitted} [χλωρον]{.greek-omitted} [ουδε]{.greek-omitted} [παν]{.greek-omitted} [δενδρον]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [τους]{.greek-omitted} [ανθρωπους]{.greek-omitted} [οιτινες]{.greek-omitted} [ουκ]{.greek-omitted} [εχουσιν]{.greek-omitted} [την]{.greek-omitted} [σφραγιδα]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [επι]{.greek-omitted} [των]{.greek-omitted} [μετωπων]{.greek-omitted} [αυτων]{.greek-omitted}[9:4]{.aside}

[τον]{.greek-added} [του]{.greek-added} [αγρου]{.greek-added} και [ου]{.greek-added} [ερρεθη]{.greek-omitted} [αυταις]{.greek-omitted} [ινα]{.greek-omitted} [μη]{.greek-omitted} [αδικησωσιν]{.greek-omitted} [τον]{.greek-omitted} [χορτον]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [ουδε]{.greek-omitted} παν [χλωρον]{.greek-omitted} [χλορον]{.greek-added} ουδε παν δενδρον ει μη τους [ανθρωπους]{.greek-abbr} οιτινες ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} την [σφραγιδα]{.greek-omitted} [σφραγι]{.greek-added} του [θεου]{.greek-abbr} επι των [μετωπων]{.greek-omitted} [μετοπων]{.greek-added} αυτων[9:4 | instance no. 2]{.aside}

και [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} αυταις ινα μη αποκτεινωσιν αυτους αλλ ινα [βασανισθωσιν]{.greek-omitted} [βασανισθωσι]{.greek-added} μηνας [πεντε]{.greek-omitted} [[ε]{.greek-abbr}]{.greek-added} και ο βασανισμος αυτων ως βασανισμος σκορπιου οταν [παιση]{.greek-omitted} [δακη]{.greek-added} [ανθρωπον]{.greek-abbr}[9:5]{.aside}

και εν ταις ημεραις εκειναις [ζητησουσιν]{.greek-omitted} [ζητουσιν]{.greek-added} οι [ανθρωποι]{.greek-abbr} τον θανατον και ου μη [ευρησουσιν]{.greek-omitted} [εὑρήσουσιν]{.greek-added} αυτον και επιθυμησουσιν αποθανειν και [φευξεται]{.greek-omitted} [φευξαιται]{.greek-added} απ αυτων ο θανατος[9:6]{.aside}

και τα ομοιωματα των ακριδων ομοια ιπποις [ητοιμασμενοις]{.greek-omitted} [ητοιμασμενοι]{.greek-added} εις πολεμον και επι τας κεφαλας αυτων ως στεφανοι χρυσοι και τα προσωπα αυτων ως προσωπα [ανθρωπων]{.greek-abbr}[9:7]{.aside}

και ειχον τριχας ως τριχας γυναικων και οι οδοντες αυτων ως λεοντων ησαν[9:8]{.aside}

και ειχον θωρακας ως θωρακας σιδηρους και η φωνη των [πτερυγων]{.greek-omitted} [αυτων]{.greek-omitted} [ως]{.greek-omitted} [φωνη]{.greek-omitted} [αρματων]{.greek-omitted} [ιππων]{.greek-omitted} [πολλων]{.greek-omitted} [τρεχοντων]{.greek-omitted} [εις]{.greek-omitted} [πολεμον]{.greek-omitted}[9:9]{.aside}

[και]{.greek-omitted} [ειχον]{.greek-omitted} [θωρακας]{.greek-omitted} [ως]{.greek-omitted} [θωρακας]{.greek-omitted} [σιδηρους]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [φωνη]{.greek-omitted} των πτερυγων αυτων ως φωνη αρματων [ιππων]{.greek-omitted} πολλων τρεχοντων εις πολεμον[9:9 | instance no. 2]{.aside}

και εχουσιν ουρας [ομοιας]{.greek-omitted} [ομοιαις]{.greek-added} σκορπιοις και κεντρα και εν ταις ουραις αυτων εξουσιαν [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} του αδικησαι τους [ανθρωπους]{.greek-abbr} μηνας πεντε[9:10]{.aside}

[εχουσαι]{.greek-omitted} [εχουσα]{.greek-added} [επ]{.greek-added} [αυτον]{.greek-added} βασιλεα [επ]{.greek-omitted} [αυτων]{.greek-omitted} αγγελον της [αβυσσου]{.greek-omitted} [αβυσου]{.greek-added} ονομα αυτω [εβραιστι]{.greek-omitted} [εββραιστι]{.greek-added} αββαδων εν δε τη ελληνικη ονομα εχει απολλυων[9:11]{.aside}

η ουαι η μια απηλθεν ιδου ερχεται [ετι]{.greek-omitted} δυο ουαι μετα ταυτα[9:12]{.aside}

και ο εκτος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και ηκουσα φωνην μιαν εκ των τεσσαρων κερατων του θυσιαστηριου του χρυσου του ενωπιον του [θεου]{.greek-abbr}[9:13]{.aside}

[λεγουσαν]{.greek-omitted} [λεγοντος]{.greek-added} τω εκτω αγγελω ο εχων την σαλπιγγα λυσον τους τεσσαρας αγγελους τους δεδεμενους επι τω ποταμω τω μεγαλω ευφρατη[9:14]{.aside}

και ελυθησαν οι τεσσαρες αγγελοι οι ητοιμασμενοι εις την ωραν και [εις]{.greek-omitted} [την]{.greek-omitted} [ημεραν]{.greek-omitted} [και]{.greek-omitted} μηνα και ενιαυτον ινα [αποκτεινωσιν]{.greek-omitted} [αποκτεινωσι]{.greek-added} το τριτον των [ανθρωπων]{.greek-abbr}[9:15]{.aside}

και ο αριθμος των στρατευματων [του]{.greek-omitted} [ιππου]{.greek-omitted} [μυριαδες]{.greek-omitted} [μυριαδων]{.greek-omitted} [ηκουσα]{.greek-omitted} [τον]{.greek-omitted} [αριθμον]{.greek-omitted} [αυτων]{.greek-omitted} [των]{.greek-added} [ιππων]{.greek-added}[9:16]{.aside}

[και]{.greek-omitted} [ο]{.greek-omitted} [αριθμος]{.greek-omitted} [των]{.greek-omitted} [στρατευματων]{.greek-omitted} [του]{.greek-omitted} [ιππου]{.greek-omitted} μυριαδες μυριαδων ηκουσα [τον]{.greek-omitted} [των]{.greek-added} [αριθμον]{.greek-omitted} [αριθμων]{.greek-added} αυτων[9:16 | instance no. 2]{.aside}

και ουτως [ειδον]{.greek-omitted} [ειδων]{.greek-added} τους ιππους εν τη ορασει και τους καθημενους επ αυτων εχοντας θωρακας [και]{.greek-added} πυρινους και [υακινθινους]{.greek-omitted} [υακινθηνους]{.greek-added} και θειωδεις και [αι]{.greek-omitted} [κεφαλαι]{.greek-omitted} [εκαιφαλαι]{.greek-added} των ιππων ως κεφαλαι λεοντων και εκ των στοματων αυτων εκπορευεται πυρ και καπνος και θειον[9:17]{.aside}

απο των τριων πληγων τουτων απεκτανθησαν το τριτον των [ανθρωπων]{.greek-abbr} απο του πυρος και του καπνου και του θειου του εκπορευομενου εκ των στοματων αυτων[9:18]{.aside}

η γαρ εξουσια των ιππων εν [τω]{.greek-omitted} [το]{.greek-added} στοματι αυτων εστιν και εν ταις ουραις αυτων αι γαρ ουραι αυτων ομοιαι οφεων [εχουσαι]{.greek-omitted} [εχουσι]{.greek-added} κεφαλας και εν αυταις [αδικουσιν]{.greek-omitted} [αδικουσι]{.greek-added}[9:19]{.aside}

και οι λοιποι των [ανθρωπων]{.greek-abbr} οι ουκ απεκτανθησαν εν ταις πληγαις ταυταις ου μετενοησαν εκ των εργων των χειρων αυτων ινα μη [προσκυνησωσιν]{.greek-omitted} [προσκυνησουσι]{.greek-added} τα δαιμονια και τα ειδωλα τα χρυσα και τα αργυρα και [τα]{.greek-omitted} [χαλκα]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} [λιθινα]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} [ξυλινα]{.greek-omitted} [α]{.greek-omitted} [ουτε]{.greek-omitted} [βλεπειν]{.greek-omitted} [δυναται]{.greek-omitted} [ουτε]{.greek-omitted} [ακουειν]{.greek-omitted} [ουτε]{.greek-omitted} [περιπατειν]{.greek-omitted}[9:20]{.aside}

[και]{.greek-omitted} [οι]{.greek-omitted} [λοιποι]{.greek-omitted} [των]{.greek-omitted} [ανθρωπων]{.greek-omitted} [οι]{.greek-omitted} [ουκ]{.greek-omitted} [απεκτανθησαν]{.greek-omitted} [εν]{.greek-omitted} [ταις]{.greek-omitted} [πληγαις]{.greek-omitted} [ταυταις]{.greek-omitted} [ου]{.greek-omitted} [μετενοησαν]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [εργων]{.greek-omitted} [των]{.greek-omitted} [χειρων]{.greek-omitted} [αυτων]{.greek-omitted} [ινα]{.greek-omitted} [μη]{.greek-omitted} [προσκυνησωσιν]{.greek-omitted} [τα]{.greek-omitted} [δαιμονια]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} [ειδωλα]{.greek-omitted} [τα]{.greek-omitted} [χρυσα]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} [αργυρα]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} [χαλκα]{.greek-omitted} [και]{.greek-omitted} τα λιθινα και τα ξυλινα α ουτε βλεπειν [δυνατε]{.greek-added} [δυναται]{.corr} ουτε ακουειν ουτε περιπατειν[9:20 | instance no. 2]{.aside}

και ου μετενοησαν εκ των [φονων]{.greek-omitted} [φωνων]{.greek-added} αυτων ουτε εκ των [φαρμακειων]{.greek-omitted} [φαρμακων]{.greek-added} αυτων [ουτε]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [πορνειας]{.greek-omitted} [αυτων]{.greek-omitted} [ουτε]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [κλεμματων]{.greek-omitted} [αυτων]{.greek-omitted}[9:21]{.aside}

### Chapter 10

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} αγγελον ισχυρον καταβαινοντα εκ του [ουρανου]{.greek-abbr} περιβεβλημενον [νεφελην]{.greek-omitted} [νεφεσιν]{.greek-added} και η ιρις επι της κεφαλης αυτου και το προσωπον αυτου ως ο ηλιος και οι ποδες αυτου ως [στυλοι]{.greek-omitted} [στυλλοι]{.greek-added} πυρος[10:1]{.aside}

και εχων εν τη χειρι αυτου βιβλιον ανεωγμενον και εθηκεν τον ποδα αυτου τον δεξιον επι της θαλασσης τον δε ευωνυμον επι της γης[10:2]{.aside}

και εκραξεν φωνη μεγαλη ωσπερ λεων μυκαται και οτε εκραξεν ελαλησαν αι επτα βρονται τας εαυτων φωνας[10:3]{.aside}

και οτε ελαλησαν αι επτα βρονται [εμελλον]{.greek-omitted} [ημελλον]{.greek-added} γραφειν και ηκουσα φωνην εκ του [ουρανου]{.greek-abbr} λεγουσαν σφραγισον α ελαλησαν αι επτα βρονται και μη αυτα [γραψης]{.greek-omitted} [γραψεις]{.greek-added}[10:4]{.aside}

και ο αγγελος ον [ειδον]{.greek-omitted} [ιδον]{.greek-added} εστωτα επι της θαλασσης και επι της γης [ηρεν]{.greek-omitted} [την]{.greek-omitted} [χειρα]{.greek-omitted} [αυτου]{.greek-omitted} [την]{.greek-omitted} [δεξιαν]{.greek-omitted} [εις]{.greek-omitted} [τον]{.greek-omitted} [ουρανον]{.greek-omitted}[10:5]{.aside}

[και]{.greek-omitted} [ο]{.greek-omitted} [αγγελος]{.greek-omitted} [ον]{.greek-omitted} [ειδον]{.greek-omitted} [εστωτα]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [θαλασσης]{.greek-omitted} [και]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} ηρεν την χειρα αυτου την δεξιαν εις τον ουρανον[10:5 | instance no. 2]{.aside}

και [ωμοσεν]{.greek-omitted} [ωμωσε]{.greek-added} τω ζωντι εις τους αιωνας των αιωνων ος εκτισεν [τον]{.greek-omitted} [ουρανον]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} [εν]{.greek-omitted} [αυτω]{.greek-omitted} και την γην και [τον]{.greek-added} [[ουρανον]{.greek-abbr}]{.greek-added} [και]{.greek-added} [παντα]{.greek-added} τα εν [αυτη]{.greek-omitted} [αυτω]{.greek-added} και την θαλασσαν και τα εν αυτη οτι χρονος ουκετι εσται[10:6]{.aside}

αλλ εν ταις ημεραις της φωνης του εβδομου αγγελου οταν μελλη σαλπιζειν [και]{.greek-omitted} ετελεσθη το μυστηριον του [θεου]{.greek-abbr} ως [ευηγγελισεν]{.greek-omitted} [εβηγγελησε]{.greek-added} τους δουλους αυτου τους προφητας[10:7]{.aside}

και η φωνη ην ηκουσα εκ του [ουρανου]{.greek-abbr} παλιν λαλουσα [μετ]{.greek-omitted} [εμου]{.greek-omitted} και λεγουσα υπαγε λαβε το βιβλιδαριον το ανεωγμενον εν τη χειρι του αγγελου του εστωτος επι της θαλασσης και επι της γης[10:8]{.aside}

και [απηλθον]{.greek-omitted} [απηλθα]{.greek-added} προς τον αγγελον λεγων αυτω δουναι μοι το βιβλιδαριον και λεγει μοι λαβε και καταφαγε αυτο και πικρανει σου την κοιλιαν αλλ εν τω στοματι σου εσται γλυκυ ως μελι[10:9]{.aside}

και ελαβον το βιβλιον εκ της χειρος του αγγελου και κατεφαγον [αυτο]{.greek-omitted} [αὐτό]{.greek-added} και ην εν τω στοματι μου ως [μελι]{.greek-omitted} [γλυκυ]{.greek-omitted} [και]{.greek-omitted} [οτε]{.greek-omitted} [εφαγον]{.greek-omitted} [αυτο]{.greek-omitted} [επικρανθη]{.greek-omitted} [η]{.greek-omitted} [κοιλια]{.greek-omitted} [μου]{.greek-omitted}[10:10]{.aside}

[και]{.greek-omitted} [ελαβον]{.greek-omitted} [το]{.greek-omitted} [βιβλιον]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [χειρος]{.greek-omitted} [του]{.greek-omitted} [αγγελου]{.greek-omitted} [και]{.greek-omitted} [κατεφαγον]{.greek-omitted} [αυτο]{.greek-omitted} [και]{.greek-omitted} [ην]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [στοματι]{.greek-omitted} [μου]{.greek-omitted} [ως]{.greek-omitted} μελι γλυκυ και οτε εφαγον αυτο επικρανθη η κοιλια μου[10:10 | instance no. 2]{.aside}

και λεγουσιν μοι δει σε παλιν προφητευσαι επι λαοις και επι [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} και γλωσσαις και [βασιλευσιν]{.greek-omitted} [βασιλευσι]{.greek-added} πολλοις[10:11]{.aside}

### Chapter 11

και [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} μοι καλαμος ομοιος ραβδω λεγων [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} και μετρησον τον ναον του [θεου]{.greek-abbr} και το θυσιαστηριον και τους προσκυνουντας εν αυτω[11:1]{.aside}

και την αυλην την εξωθεν του ναου εκβαλε εξω και μη αυτην μετρησης οτι [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} τοις εθνεσιν και την πολιν την αγιαν πατησουσιν μηνας τεσσαρακοντα και δυο[11:2]{.aside}

και δωσω τοις [δυσιν]{.greek-omitted} [δυσι]{.greek-added} [μαρτυσιν]{.greek-omitted} [μαρτυσι]{.greek-added} μου και προφητευσουσιν ημερας χιλιας διακοσιας [εξηκοντα]{.greek-omitted} [εξικοντα]{.greek-added} περιβεβλημενοι σακκους[11:3]{.aside}

ουτοι εισιν αι δυο ελαιαι και αι δυο λυχνιαι αι ενωπιον του [κυριου]{.greek-abbr} της γης [εστωσαι]{.greek-omitted} [εστωτες]{.greek-added}[11:4]{.aside}

και ει τις αυτους θελει αδικησαι πυρ εκπορευεται εκ του στοματος [αυτον]{.greek-added} [αυτων]{.corr} και κατεσθιει τους εχθρους αυτων και ει τις θελει αυτους αδικησαι ουτως δει [αυτον]{.greek-omitted} [αποκτανθηναι]{.greek-omitted}[11:5]{.aside}

[και]{.greek-omitted} [ει]{.greek-omitted} [τις]{.greek-omitted} [αυτους]{.greek-omitted} [θελει]{.greek-omitted} [αδικησαι]{.greek-omitted} [πυρ]{.greek-omitted} [εκπορευεται]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [στοματος]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [κατεσθιει]{.greek-omitted} [τους]{.greek-omitted} [εχθρους]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [ει]{.greek-omitted} [τις]{.greek-omitted} [θελει]{.greek-omitted} [αυτους]{.greek-omitted} [αδικησαι]{.greek-omitted} [ουτως]{.greek-omitted} [δει]{.greek-omitted} αυτον αποκτανθηναι[11:5 | instance no. 2]{.aside}

ουτοι [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} τον ουρανον εξουσιαν κλεισαι ινα μη υετος [βρεχη]{.greek-omitted} [βρεχει]{.greek-added} τας ημερας της προφητειας αυτων και εξουσιαν εχουσιν επι των υδατων στρεφειν αυτα εις αιμα και παταξαι την γην οσακις εαν [θελησωσιν]{.greek-omitted} [θελησωσην]{.greek-added} εν παση [πληγη]{.greek-omitted} [τη]{.greek-added} [γη]{.greek-added}[11:6]{.aside}

και οταν [τελεσωσιν]{.greek-omitted} [τελεσωσι]{.greek-added} την μαρτυριαν αυτων το [μαρτυριον]{.greek-added} [αυτων]{.greek-added} [το]{.greek-added} [μαρ]{.greek-added} [το]{.greek-added} θηριον το [αναβαινον]{.greek-omitted} [ἀναβαῖνον]{.greek-added} εκ της [αβυσσου]{.greek-omitted} [αβυσου]{.greek-added} ποιησει μετ αυτων πολεμον και νικησει αυτους και αποκτενει αυτους[11:7]{.aside}

και το πτωμα αυτων επι της πλατειας της πολεως της μεγαλης ητις καλειται [πνευματικως]{.greek-abbr} σοδομα και αιγυπτος οπου και ο [κυριος]{.greek-abbr} αυτων [εσταυρωθη]{.greek-abbr}[11:8]{.aside}

και βλεπουσιν εκ των λαων και φυλων και γλωσσων και εθνων το πτωμα αυτων ημερας τρεις ημισυ και τα πτωματα αυτων ουκ [αφησουσιν]{.greek-omitted} [αφησουσι]{.greek-added} τεθηναι εις μνημα[11:9]{.aside}

και οι κατοικουντες επι της γης χαιρουσιν επ [αυτοις]{.greek-omitted} [αυτης]{.greek-added} και ευφρανθησονται [και]{.greek-omitted} [δωρα]{.greek-omitted} [δωσουσιν]{.greek-omitted} [αλληλοις]{.greek-omitted} [οτι]{.greek-omitted} [ουτοι]{.greek-omitted} [οι]{.greek-omitted} [δυο]{.greek-omitted} [προφηται]{.greek-omitted} [εβασανισαν]{.greek-omitted} [τους]{.greek-omitted} [κατοικουντας]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted}[11:10]{.aside}

[και]{.greek-omitted} [οι]{.greek-omitted} [κατοικουντες]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [χαιρουσιν]{.greek-omitted} [επ]{.greek-omitted} [αυτοις]{.greek-omitted} [και]{.greek-omitted} [ευφρανθησονται]{.greek-omitted} και δωρα δωσουσιν αλληλοις οτι [ουτοι]{.greek-omitted} οι δυο προφηται εβασανισαν τους κατοικουντας επι της γης[11:10 | instance no. 2]{.aside}

και μετα [τας]{.greek-omitted} τρεις ημερας και ημισυ [πνευμα]{.greek-abbr} ζωης εκ του [θεου]{.greek-abbr} εισηλθεν εις αυτους και εστησαν επι τους ποδας αυτων και φοβος μεγας επεσεν επι τους θεωρουντας αυτους[11:11]{.aside}

και ηκουσα φωνην μεγαλην εκ του [ουρανου]{.greek-abbr} λεγουσαν αυτοις [αναβητε]{.greek-omitted} [ἀνάβητε]{.greek-added} ωδε και ανεβησαν εις τον [ουρανον]{.greek-abbr} εν τη νεφελη και εθεωρησαν αυτους οι εχθροι αυτων[11:12]{.aside}

[και]{.greek-omitted} εν εκεινη τη ημερα εγενετο σεισμος μεγας και το δεκατον της πολεως επεσεν και απεκτανθησαν εν τω σεισμω ονοματα [ανθρωπων]{.greek-abbr} χιλιαδες επτα και οι λοιποι εμφοβοι εγενοντο και εδωκαν δοξαν τω [θεω]{.greek-abbr} του [ουρανου]{.greek-abbr}[11:13]{.aside}

η ουαι η δευτερα απηλθεν η ουαι η τριτη ιδου ερχεται ταχυ[11:14]{.aside}

και ο εβδομος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και εγενοντο φωναι μεγαλαι εν τω [ουρανω]{.greek-abbr} [λεγουσαι]{.greek-omitted} [λεγοντες]{.greek-added} εγενετο η βασιλεια του κοσμου του [κυριου]{.greek-abbr} ημων και του [χριστου]{.greek-abbr} αυτου και [βα]{.greek-added} [βασιλευσει]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [αιωνας]{.greek-omitted} [των]{.greek-omitted} [αιωνων]{.greek-omitted}[11:15]{.aside}

[και]{.greek-omitted} [ο]{.greek-omitted} [εβδομος]{.greek-omitted} [αγγελος]{.greek-omitted} [εσαλπισεν]{.greek-omitted} [και]{.greek-omitted} [εγενοντο]{.greek-omitted} [φωναι]{.greek-omitted} [μεγαλαι]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ουρανω]{.greek-omitted} [λεγουσαι]{.greek-omitted} [εγενετο]{.greek-omitted} [η]{.greek-omitted} [βασιλεια]{.greek-omitted} [του]{.greek-omitted} [κοσμου]{.greek-omitted} [του]{.greek-omitted} [κυριου]{.greek-omitted} [ημων]{.greek-omitted} [και]{.greek-omitted} [του]{.greek-omitted} [χριστου]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [βασιλευσει]{.greek-omitted} [σιλευσει]{.greek-added} εις τους αιωνας των αιωνων [αμην]{.greek-added}[11:15 | instance no. 2]{.aside}

και οι εικοσι [τεσσαρες]{.greek-omitted} [τεσσαρις]{.greek-added} πρεσβυτεροι οι ενωπιον του θρονου του [θεου]{.greek-abbr} [καθημενοι]{.greek-omitted} [οι]{.greek-added} [καθηνται]{.greek-added} επι τους θρονους αυτων [επεσον]{.greek-omitted} [επεσαν]{.greek-added} επι τα προσωπα αυτων και προσεκυνησαν τω [θεω]{.greek-abbr}[11:16]{.aside}

λεγοντες ευχαριστουμεν σοι [κυριε]{.greek-abbr} ο [θεος]{.greek-abbr} ο [παντοκρατωρ]{.greek-omitted} [παντοκρατορ]{.greek-added} ο ων και ο ην οτι ειληφας την δυναμιν σου την μεγαλην και εβασιλευσας[11:17]{.aside}

και τα εθνη ωργισθησαν και ηλθεν η οργη σου και ο καιρος των νεκρων κριθηναι και δουναι τον μισθον τοις δουλοις σου τοις προφηταις και τοις αγιοις και τοις φοβουμενοις το ονομα σου τοις μικροις και τοις μεγαλοις και διαφθειραι τους διαφθειροντας την γην[11:18]{.aside}

και [ηνοιγη]{.greek-omitted} [ηνοιχθη]{.greek-added} [ο]{.greek-omitted} [ναος]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ουρανω]{.greek-omitted} [και]{.greek-omitted} [ωφθη]{.greek-omitted} η κιβωτος της διαθηκης του [ναου]{.greek-added} [του]{.greek-added} [κυριου]{.greek-abbr} [εν]{.greek-omitted} [τω]{.greek-omitted} [ναω]{.greek-omitted} [αυτου]{.greek-omitted} και εγενοντο αστραπαι και φωναι και βρονται και χαλαζα μεγαλη[11:19]{.aside}

### Chapter 12

και σημειον μεγα ωφθη εν τω [ουρανω]{.greek-abbr} γυνη περιβεβλημενη τον ηλιον και η σεληνη [υπο]{.greek-added} [υποκατω]{.greek-omitted} [των]{.greek-omitted} [ποδων]{.greek-omitted} [αυτης]{.greek-omitted} [και]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [κεφαλης]{.greek-omitted} [αυτης]{.greek-omitted} [στεφανος]{.greek-omitted} [αστερων]{.greek-omitted} [δωδεκα]{.greek-omitted}[12:1]{.aside}

[κατω]{.greek-added} [και]{.greek-omitted} [σημειον]{.greek-omitted} [μεγα]{.greek-omitted} [ωφθη]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ουρανω]{.greek-omitted} [γυνη]{.greek-omitted} [περιβεβλημενη]{.greek-omitted} τον [ηλιον]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [σεληνη]{.greek-omitted} [υποκατω]{.greek-omitted} [των]{.greek-omitted} ποδων αυτης και επι της κεφαλης αυτης στεφανος αστερων δωδεκα[12:1 | instance no. 2]{.aside}

και εν γαστρι εχουσα εκραζεν ωδινουσα και βασανιζομενη τεκειν[12:2]{.aside}

και ωφθη αλλο σημειον εν τω [ουρανω]{.greek-abbr} και ιδου δρακων πυρος μεγας εχων κεφαλας επτα και κερατα δεκα και επι τας κεφαλας αυτου επτα διαδηματα[12:3]{.aside}

και η ουρα αυτου συρει το τριτον των αστερων του [ουρανου]{.greek-abbr} και εβαλεν αυτους εις την γην και ο δρακων [εστηκεν]{.greek-omitted} [ἐστήκεν]{.greek-added} ενωπιον της γυναικος της μελλουσης τεκειν ινα οταν [τεκη]{.greek-omitted} [τεκειν]{.greek-added} το τεκνον αυτης καταφαγη[12:4]{.aside}

και ετεκεν υιον [αρρενα]{.greek-omitted} [αρενα]{.greek-added} ος μελλει [ποιμαινειν]{.greek-omitted} [ποιμενειν]{.greek-added} παντα τα εθνη εν ραβδω σιδηρα και [ηρπασθη]{.greek-omitted} [ηρπαγη]{.greek-added} το τεκνον αυτης προς τον [θεον]{.greek-abbr} και προς τον θρονον αυτου[12:5]{.aside}

και η γυνη εφυγεν εις την ερημον οπου εχει εκει τοπον ητοιμασμενον υπο του [θεου]{.greek-abbr} ινα εκει [εκ]{.greek-added} [εκτρεφωσιν]{.greek-omitted} [τρεφωσιν]{.greek-added} αυτην ημερας χιλιας διακοσιας εξηκοντα[12:6]{.aside}

και [εγενετο]{.greek-omitted} [εγενε]{.greek-added} [πολεμος]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ουρανω]{.greek-omitted} [ο]{.greek-omitted} [μιχαηλ]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [αγγελοι]{.greek-omitted} [αυτου]{.greek-omitted} [πολεμησαι]{.greek-omitted} [μετα]{.greek-omitted} [του]{.greek-omitted} [δρακοντος]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [δρακων]{.greek-omitted} [επολεμησεν]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [αγγελοι]{.greek-omitted} [αυτου]{.greek-omitted}[12:7]{.aside}

[το]{.greek-added} [και]{.greek-omitted} [εγενετο]{.greek-omitted} πολεμος εν τω [ουρανω]{.greek-abbr} ο μιχαηλ και οι αγγελοι αυτου πολεμησαι [μετα]{.greek-omitted} [κατα]{.greek-added} του δρακοντος και ο δρακων [επολεμησεν]{.greek-omitted} [επολεμησε]{.greek-added} και οι αγγελοι αυτου[12:7 | instance no. 2]{.aside}

και ουκ ισχυσεν ουδε τοπος ευρεθη αυτω ετι εν τω [ουρανω]{.greek-abbr}[12:8]{.aside}

και εβληθη ο δρακων ο μεγας ο οφις ο αρχαιος ο καλουμενος διαβολος και σατανας ο πλανων την οικουμενην ολην εβληθη εις την γην και οι αγγελοι αυτου μετ αυτου εβληθησαν[12:9]{.aside}

και ηκουσα φωνην μεγαλην εν τω [ουρανω]{.greek-abbr} λεγουσαν αρτι εγενετο η [σωτηρια]{.greek-abbr} και η [δυναμις]{.greek-omitted} [δυναμεις]{.greek-added} και η βασιλεια του [θεου]{.greek-abbr} ημων και η εξουσια του [χριστου]{.greek-abbr} αυτου οτι εβληθη ο κατηγορος των αδελφων ημων ο κατηγορων αυτων [ενωπιον]{.greek-omitted} [ενοπιον]{.greek-added} του [θεου]{.greek-abbr} ημων ημερας και νυκτος[12:10]{.aside}

και αυτοι ενικησαν αυτον δια το αιμα του αρνιου και δια τον λογον της μαρτυριας αυτων και ουκ ηγαπησαν την ψυχην αυτων αχρι θανατου[12:11]{.aside}

δια τουτο ευφραινεσθε [ουρανοι]{.greek-abbr} και οι εν [αυ]{.greek-added} [αυτοις]{.greek-omitted} [σκηνουντες]{.greek-omitted} [ουαι]{.greek-omitted} [τη]{.greek-omitted} [γη]{.greek-omitted} [και]{.greek-omitted} [τη]{.greek-omitted} [θαλασση]{.greek-omitted} [οτι]{.greek-omitted} [κατεβη]{.greek-omitted} [ο]{.greek-omitted} [διαβολος]{.greek-omitted} [προς]{.greek-omitted} [υμας]{.greek-omitted} [εχων]{.greek-omitted} [θυμον]{.greek-omitted} [μεγαν]{.greek-omitted} [ειδως]{.greek-omitted} [οτι]{.greek-omitted} [ολιγον]{.greek-omitted} [καιρον]{.greek-omitted} [εχει]{.greek-omitted}[12:12]{.aside}

[δια]{.greek-omitted} [τουτο]{.greek-omitted} [ευφραινεσθε]{.greek-omitted} [ουρανοι]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [εν]{.greek-omitted} [αυτοις]{.greek-omitted} [τοις]{.greek-added} σκηνουντες ουαι τη [γη]{.greek-omitted} [γην]{.greek-added} και τη [θαλασση]{.greek-omitted} [θααασση]{.greek-added} οτι κατεβη ο διαβολος προς [υμας]{.greek-omitted} [ημας]{.greek-added} εχων θυμον μεγαν ειδως οτι ολιγον καιρον εχει[12:12 | instance no. 2]{.aside}

και [οτε]{.greek-omitted} [οτι]{.greek-added} ειδεν ο δρακων οτι εβληθη εις την γην [εδιωξεν]{.greek-omitted} [εδιωξε]{.greek-added} την γυναικα [ητις]{.greek-omitted} [ειτις]{.greek-added} [ετεκεν]{.greek-omitted} [ετεκε]{.greek-added} τον αρρενα[12:13]{.aside}

και [εδοθησαν]{.greek-omitted} [εδωθησαν]{.greek-added} τη γυναικι δυο πτερυγες του αετου του μεγαλου ινα [πετηται]{.greek-omitted} [πεσηται]{.greek-added} εις την ερημον εις τον τοπον αυτης [οπως]{.greek-omitted} [οπου]{.greek-added} [τρεφηται]{.greek-omitted} [τρεφεται]{.greek-added} εκει καιρον και καιρους και ημισυ καιρου απο προσωπου του οφεως[12:14]{.aside}

και εβαλεν ο οφις εκ του στοματος αυτου οπισω της γυναικος υδωρ ως ποταμον ινα αυτην ποταμοφορητον [ποιηση]{.greek-omitted} [ποιησει]{.greek-added}[12:15]{.aside}

και εβοηθησεν η γη τη γυναικι και ηνοιξεν η γη το στομα αυτης και [κατεπιεν]{.greek-omitted} [κατεπιε]{.greek-added} τον ποταμον ον εβαλεν ο δρακων εκ του στοματος αυτου[12:16]{.aside}

και [ωργισθη]{.greek-omitted} [οργισθη]{.greek-added} ο δρακων επι τη γυναικι και [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} ποιησαι πολεμον μετα των λοιπων του σπερματος αυτης των τηρουντων τας εντολας του [θεου]{.greek-abbr} και εχοντων [την]{.greek-omitted} [μαρτυριαν]{.greek-omitted} [ιησου]{.greek-omitted} [τας]{.greek-added} [εντολας]{.greek-added} [του]{.greek-added} [[θεου]{.greek-abbr}]{.greek-added}[12:17]{.aside}

και [ωργισθη]{.greek-omitted} [ο]{.greek-omitted} [δρακων]{.greek-omitted} [επι]{.greek-omitted} [τη]{.greek-omitted} [γυναικι]{.greek-omitted} [και]{.greek-omitted} [απηλθεν]{.greek-omitted} [ποιησαι]{.greek-omitted} [πολεμον]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} [λοιπων]{.greek-omitted} [του]{.greek-omitted} [σπερματος]{.greek-omitted} [αυτης]{.greek-omitted} [των]{.greek-omitted} [τηρουντων]{.greek-omitted} [τας]{.greek-omitted} [εντολας]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [και]{.greek-omitted} [εχοντων]{.greek-omitted} την μαρτυριαν [ιησου]{.greek-abbr}[12:17 | instance no. 2]{.aside}

[και]{.greek-added} [εσταθην]{.greek-added} [επι]{.greek-added} [την]{.greek-added} [αμμον]{.greek-added} [της]{.greek-added} [θαλασσης]{.greek-added}[12:18]{.aside}

### Chapter 13

[και]{.greek-omitted} [εσταθην]{.greek-omitted} [επι]{.greek-omitted} [την]{.greek-omitted} [αμμον]{.greek-omitted} [της]{.greek-omitted} [θαλασσης]{.greek-omitted} και ειδον εκ της θαλασσης θηριον αναβαινον [εχον]{.greek-omitted} [εχων]{.greek-added} κερατα [δεκα]{.greek-omitted} [[ι]{.greek-abbr}]{.greek-added} και κεφαλας επτα και επι των κερατων αυτου δεκα διαδηματα και επι τας κεφαλας αυτου ονοματα βλασφημιας[13:1]{.aside}

και το θηριον [ο]{.greek-omitted} [ον]{.greek-added} ειδον ην ομοιον [παρδαλει]{.greek-omitted} [παρδαλη]{.greek-added} και οι ποδες αυτου ως αρκου και το στομα αυτου ως στομα [λεοντος]{.greek-omitted} [λεωντος]{.greek-added} και εδωκεν αυτω ο δρακων την [δυναμιν]{.greek-omitted} [δυναμην]{.greek-added} αυτου και τον θρονον αυτου και εξουσιαν μεγαλην[13:2]{.aside}

και μιαν εκ των κεφαλων αυτου [ωσει]{.greek-omitted} [ωσσει]{.greek-added} [εσφαγμενην]{.greek-omitted} [εσφραγισμενην]{.greek-added} εις θανατον και η πληγη του θανατου [αυτου]{.greek-omitted} εθεραπευθη και εθαυμασεν ολη η γη οπισω του θηριου[13:3]{.aside}

και προσεκυνησαν τω δρακοντι τω δεδωκοτι την εξουσιαν [το]{.greek-added} [θηριον]{.greek-added} [τω]{.greek-omitted} [θηριω]{.greek-omitted} [και]{.greek-omitted} [προσεκυνησαν]{.greek-omitted} [τω]{.greek-omitted} [θηριω]{.greek-omitted} λεγοντες τις ομοιος τω θηριω [και]{.greek-omitted} τις δυνατος πολεμησαι μετ αυτου[13:4]{.aside}

και [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} αυτω στομα λαλουν μεγαλα και [βλασφημιαν]{.greek-omitted} [βλασφημιας]{.greek-added} και [εδοθη]{.greek-omitted} [αυτω]{.greek-omitted} [εξουσια]{.greek-omitted} [πολεμον]{.greek-omitted} [ποιησαι]{.greek-omitted} [μηνας]{.greek-omitted} [τεσσαρακοντα]{.greek-omitted} [δυο]{.greek-omitted}[13:5]{.aside}

[και]{.greek-omitted} [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} αυτω [στομα]{.greek-omitted} [λαλουν]{.greek-omitted} [μεγαλα]{.greek-omitted} [και]{.greek-omitted} [βλασφημιαν]{.greek-omitted} [και]{.greek-omitted} [εδοθη]{.greek-omitted} [αυτω]{.greek-omitted} [εξουσια]{.greek-omitted} [εξουσιαν]{.greek-added} πολεμον ποιησαι μηνας τεσσαρακοντα δυο[13:5 | instance no. 2]{.aside}

και [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} το στομα αυτου εις βλασφημιαν προς τον [θεον]{.greek-abbr} [βλασφημησαι]{.greek-omitted} [βλασφημισαι]{.greek-added} το ονομα αυτου και την σκηνην αυτου τους εν τω [ουρανω]{.greek-abbr} [σκηνουντας]{.greek-omitted} [οικουντας]{.greek-added}[13:6]{.aside}

και [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} αυτω [εξουσια]{.greek-added} ποιησαι πολεμον μετα των αγιων και νικησαι αυτους και [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} αυτω εξουσια επι πασαν φυλην και λαον και γλωσσαν και εθνος[13:7]{.aside}

και προσκυνησουσιν [αυτω]{.greek-omitted} [αυτον]{.greek-added} παντες οι κατοικουντες επι της γης ων ου γεγραπται το ονομα εν τω βιβλιω της ζωης του αρνιου του [εσφαγμενου]{.greek-omitted} [εσφραγισμενου]{.greek-added} απο καταβολης κοσμου[13:8]{.aside}

ει τις εχει ους ακουσατω[13:9]{.aside}

ει τις [εχει]{.greek-omitted} [εις]{.greek-added} αιχμαλωσιαν υπαγει ει τις εν μαχαιρα [αποκτενει]{.greek-omitted} δει αυτον [εν]{.greek-omitted} [μαχαιρα]{.greek-omitted} αποκτανθηναι ωδε εστιν η υπομονη [των]{.greek-added} [αγιων]{.greek-added} και η πιστις [των]{.greek-omitted} [αγιων]{.greek-omitted}[13:10]{.aside}

και ειδον αλλο θηριον [αναβαινον]{.greek-omitted} [ἀναβαῖνοντα]{.greek-added} εκ της γης και [ειχεν]{.greek-omitted} [ειχε]{.greek-added} κερατα [δυο]{.greek-omitted} ομοια αρνιω και [ελαλει]{.greek-omitted} [ελαλη]{.greek-added} ως δρακων[13:11]{.aside}

και την εξουσιαν του πρωτου θηριου πασαν ποιει ενωπιον αυτου [και]{.greek-omitted} [εποιει]{.greek-omitted} [την]{.greek-omitted} [γην]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [εν]{.greek-omitted} [αυτη]{.greek-omitted} [κατοικουντας]{.greek-omitted} [ινα]{.greek-omitted} [προσκυνησωσιν]{.greek-omitted} [το]{.greek-omitted} [θηριον]{.greek-omitted} [το]{.greek-omitted} [πρωτον]{.greek-omitted} [ου]{.greek-omitted} [εθεραπευθη]{.greek-omitted} [η]{.greek-omitted} [πληγη]{.greek-omitted} [του]{.greek-omitted} [θανατου]{.greek-omitted} [αυτου]{.greek-omitted}[13:12]{.aside}

και [εποιη]{.greek-added} [την]{.greek-omitted} [εξουσιαν]{.greek-omitted} [του]{.greek-omitted} [πρωτου]{.greek-omitted} [θηριου]{.greek-omitted} [πασαν]{.greek-omitted} [ποιει]{.greek-omitted} [ενωπιον]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [εποιει]{.greek-omitted} την γην και τους εν αυτη κατοικουντας ινα [προσκυνησωσιν]{.greek-omitted} [προσκυνησουσι]{.greek-added} το θηριον το πρωτον ου εθεραπευθη η πληγη του θανατου αυτου[13:12 | instance no. 2]{.aside}

και ποιει σημεια μεγαλα και πυρ ινα εκ του [ουρανου]{.greek-abbr} [καταβαινη]{.greek-omitted} [καταβαινει]{.greek-added} επι την γην ενωπιον των [ανθρωπων]{.greek-abbr}[13:13]{.aside}

και πλανα τους εμους τους κατοικουντας επι της γης δια τα σημεια α [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} αυτω ποιησαι ενωπιον του θηριου λεγων τοις κατοικουσιν επι της γης ποιησαι εικονα τω θηριω [ο]{.greek-omitted} [ὂ]{.greek-added} [ειχεν]{.greek-omitted} [ειχε]{.greek-added} [την]{.greek-omitted} πληγην και εζησεν απο της μαχαιρας[13:14]{.aside}

και [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} αυτω [πνευμα]{.greek-abbr} δουναι τη εικονι του θηριου ινα και λαληση η εικ[ω]{.unclear}ν του θηριου και [ποιηση]{.greek-omitted} [ποιησει]{.greek-added} οσοι εαν μη [προσκυνησωσιν]{.greek-omitted} [προσκυνησουσι]{.greek-added} τη εικονι του θηριου [αποκτανθωσιν]{.greek-omitted} [αποκτανθωσι]{.greek-added}[13:15]{.aside}

και [ποιει]{.greek-omitted} [ποιη]{.greek-added} παντας τους μικρους και [τους]{.greek-omitted} [ους]{.greek-added} μεγαλους και τους πλουσιους και τους πτωχους και [τους]{.greek-omitted} ελευθερους και τους δουλους ινα δωσωσιν αυτοις χαραγματα επι της χειρος αυτων της δεξιας η επι το [μετωπον]{.greek-omitted} [αυτων]{.greek-omitted} [μετο]{.greek-added} [ιγ]{.greek-added}[13:16]{.aside}

[πον]{.greek-added} [και]{.greek-omitted} [ποιει]{.greek-omitted} [παντας]{.greek-omitted} [τους]{.greek-omitted} [μικρους]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [μεγαλους]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [πλουσιους]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [πτωχους]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [ελευθερους]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [δουλους]{.greek-omitted} [ινα]{.greek-omitted} [δωσωσιν]{.greek-omitted} [αυτοις]{.greek-omitted} [χαραγματα]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [χειρος]{.greek-omitted} αυτων [της]{.greek-omitted} [δεξιας]{.greek-omitted} [η]{.greek-omitted} [επι]{.greek-omitted} [το]{.greek-omitted} [μετωπον]{.greek-omitted} [αυτων]{.greek-omitted}[13:16 | instance no. 2]{.aside}

και ινα μη τις δυναται αγορασαι η πωλησαι ει μη ο εχων το χαραγμα το ονομα του θηριου η τον αριθμον του ονοματος αυτου[13:17]{.aside}

ωδε η σοφια εστιν ο εχων νουν [ψηφισατω]{.greek-omitted} [ψηφησατω]{.greek-added} τον αριθμον του θηριου αριθμος γαρ [ανθρωπου]{.greek-abbr} εστιν [και]{.greek-omitted} ο αριθμος αυτου [[χξστ]{.greek-abbr}]{.greek-added} [εστιν]{.greek-omitted} [εξακοσια]{.greek-omitted} [εξηκοντα]{.greek-omitted} [εξ]{.greek-omitted}[13:18]{.aside}

### Chapter 14

και ειδον και ιδου το αρνιον [εστηκος]{.greek-omitted} [εστικως]{.greek-added} επι το ορος σιων και μετ αυτου αριθμος [[ρμδ]{.greek-abbr}]{.greek-added} [εκατον]{.greek-omitted} [τεσσαρακοντα]{.greek-omitted} [τεσσαρες]{.greek-omitted} χιλιαδες εχουσαι το ονομα αυτου και το ονομα του [πατρος]{.greek-abbr} αυτου γεγραμμενον επι των [μετωπων]{.greek-omitted} [μετοπων]{.greek-added} αυτων[14:1]{.aside}

και ηκουσα [φωνην]{.greek-omitted} [φωνης]{.greek-added} [λεγουσης]{.greek-added} εκ του [ουρανου]{.greek-abbr} ως φωνην υδατων πολλων και ως φωνην βροντης μεγαλης και η φωνη ην ηκουσα ως [κιθαθαρωδων]{.greek-added} [κιθαρωδων]{.corr} κιθαριζοντων εν ταις κιθαραις αυτων[14:2]{.aside}

και αδουσιν ωδην καινην ενωπιον του θρονου και ενωπιον των [θ]{.greek-added} [τεσσαρων]{.greek-omitted} [τεσαρων]{.greek-added} ζωων και των πρεσβυτερων και [ουδεις]{.greek-omitted} [ουδε]{.greek-added} [εις]{.greek-added} [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} μαθειν την ωδην ει μη αι [[ρμδ]{.greek-abbr}]{.greek-added} [εκατον]{.greek-omitted} [τεσσαρακοντα]{.greek-omitted} [τεσσαρες]{.greek-omitted} χιλιαδες οι ηγορασμενοι [ε]{.greek-added} [απο]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted}[14:3]{.aside}

[πι]{.greek-added} [και]{.greek-omitted} [αδουσιν]{.greek-omitted} [ωδην]{.greek-omitted} [καινην]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [και]{.greek-omitted} [ενωπιον]{.greek-omitted} [των]{.greek-omitted} [τεσσαρων]{.greek-omitted} [ζωων]{.greek-omitted} [και]{.greek-omitted} [των]{.greek-omitted} [πρεσβυτερων]{.greek-omitted} [και]{.greek-omitted} [ουδεις]{.greek-omitted} [εδυνατο]{.greek-omitted} [μαθειν]{.greek-omitted} [την]{.greek-omitted} [ωδην]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [αι]{.greek-omitted} [εκατον]{.greek-omitted} [τεσσαρακοντα]{.greek-omitted} [τεσσαρες]{.greek-omitted} [χιλιαδες]{.greek-omitted} [οι]{.greek-omitted} [ηγορασμενοι]{.greek-omitted} [απο]{.greek-omitted} της γης[14:3 | instance no. 2]{.aside}

ουτοι εισιν οι μετα γυναικων ουκ εμολυνθησαν παρθενοι γαρ εισιν ουτοι εισιν οι ακολουθουντες τω αρνιω οπου [αν]{.greek-omitted} [εαν]{.greek-added} υπαγη ουτοι υπο [ιησου]{.greek-abbr} ηγορασθησαν απο των [ανθρωπων]{.greek-abbr} απαρχη τω [θεω]{.greek-abbr} και τω αρνιω[14:4]{.aside}

και ουχ ευρεθη εν τω στοματι αυτων ψευδος αμωμοι γαρ εισιν[14:5]{.aside}

και ειδον αγγελον [πετομενον]{.greek-omitted} [πετωμενον]{.greek-added} εν μεσουρανηματι εχοντα ευαγγελιον αιωνιον ευαγγελισαι τους καθημενους επι της γης και επι παν εθνος και φυλην και γλωσσαν και λαον[14:6]{.aside}

λεγων εν φωνη μεγαλη φοβηθητε τον [κυριον]{.greek-abbr} και δοτε αυτω δοξαν οτι ηλθεν η ωρα της κρισεως αυτου και [προσκυνησατε]{.greek-omitted} [προσκυνησαντες]{.greek-added} αυτον τον ποιησαντα τον [ουρανον]{.greek-abbr} και την γην και την θαλασσαν και πηγας υδατων[14:7]{.aside}

και [αλλος]{.greek-omitted} [αλος]{.greek-added} δευτερος αγγελος [ηκολουθησεν]{.greek-omitted} [ηκολουθησε]{.greek-added} λεγων [επεσεν]{.greek-omitted} [επεσε]{.greek-added} βαβυλων η μεγαλη [η]{.greek-added} εκ του οινου [του]{.greek-omitted} [θυμου]{.greek-omitted} της πορνειας αυτης [του]{.greek-added} [θυμου]{.greek-added} [πε]{.greek-added} [πεποτικεν]{.greek-omitted} [παντα]{.greek-omitted} [τα]{.greek-omitted} [εθνη]{.greek-omitted}[14:8]{.aside}

[και]{.greek-omitted} [αλλος]{.greek-omitted} [δευτερος]{.greek-omitted} [αγγελος]{.greek-omitted} [ηκολουθησεν]{.greek-omitted} [λεγων]{.greek-omitted} [επεσεν]{.greek-omitted} [βαβυλων]{.greek-omitted} [η]{.greek-omitted} [μεγαλη]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [οινου]{.greek-omitted} [του]{.greek-omitted} [θυμου]{.greek-omitted} [της]{.greek-omitted} [πορνειας]{.greek-omitted} [αυτης]{.greek-omitted} [πεποτικεν]{.greek-omitted} [ποτικε]{.greek-added} παντα τα εθνη[14:8 | instance no. 2]{.aside}

και αλλος αγγελος τριτος ηκολουθησεν αυτοις λεγων εν φωνη μεγαλη ει τις [προσκυνει]{.greek-omitted} [προσκυνη]{.greek-added} το θηριον και την εικονα αυτου και λαμβανει χαραγμα επι του [μετωπου]{.greek-omitted} [μετοπου]{.greek-added} αυτου η επι την χειρα αυτου[14:9]{.aside}

και αυτος πιεται εκ του οινου του θυμου του [θεου]{.greek-abbr} του [κεκερασμενου]{.greek-omitted} [κερασμενου]{.greek-added} ακρατου εν τω ποτηριω της οργης αυτου και βασανισθησεται εν πυρι και θειω ενωπιον των αγιων αγγελων και ενωπιον του αρνιου[14:10]{.aside}

και ο καπνος του βασανισμου αυτων εις αιωνας αιωνων αναβαινει και ουκ εχουσιν αναπαυσιν ημερας και νυκτος οι προσκυνουντες το θηριον και την εικονα αυτου και ει τις λαμβανει το χαραγμα του ονοματος αυτου[14:11]{.aside}

ωδε η υπομονη των αγιων εστιν οι τηρουντες τας εντολας του [θεου]{.greek-abbr} και την πιστιν [ιησου]{.greek-abbr}[14:12]{.aside}

και ηκουσα [φωνης]{.greek-omitted} [φωνην]{.greek-added} εκ του [ουρανου]{.greek-abbr} [λεγουσης]{.greek-omitted} [λεγουσαν]{.greek-added} γραψον μακαριοι οι νεκροι [οι]{.greek-omitted} [εν]{.greek-omitted} [κυριω]{.greek-omitted} [αποθνησκοντες]{.greek-omitted} [απ]{.greek-omitted} [αρτι]{.greek-omitted} [λεγει]{.greek-omitted} [ναι]{.greek-omitted} [το]{.greek-omitted} [πνευμα]{.greek-omitted} [ινα]{.greek-omitted} [αναπαυσωνται]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [κοπων]{.greek-omitted} [αυτων]{.greek-omitted} [τα]{.greek-omitted} [δε]{.greek-omitted} [εργα]{.greek-omitted} [αυτων]{.greek-omitted} [ακολουθει]{.greek-omitted} [μετ]{.greek-omitted} [αυτων]{.greek-omitted}[14:13]{.aside}

[και]{.greek-omitted} [ηκουσα]{.greek-omitted} [φωνης]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [λεγουσης]{.greek-omitted} [γραψον]{.greek-omitted} [μακαριοι]{.greek-omitted} [οι]{.greek-omitted} [νεκροι]{.greek-omitted} οι εν [κυριω]{.greek-abbr} αποθνησκοντες [ἀπάρτι]{.greek-added} [λεγοντες]{.greek-added} [απ]{.greek-omitted} [αρτι]{.greek-omitted} [λεγει]{.greek-omitted} ναι το [πνευμα]{.greek-abbr} ινα [αναπαυσωνται]{.greek-omitted} [αναπαυσονται]{.greek-added} εκ των κοπων αυτων τα δε εργα αυτων ακολουθει μετ αυτων[14:13 | instance no. 2]{.aside}

και ειδον και ιδου νεφελη λευκη και επι την νεφελην καθημενον ομοιον [υιω]{.greek-omitted} [υιον]{.greek-added} [ανθρωπου]{.greek-abbr} εχων [επι]{.corr} [της]{.greek-omitted} [την]{.greek-added} [κεφαλης]{.greek-omitted} [κεφαλην]{.greek-added} αυτου στεφανον χρυσουν και εν τη [χειρι]{.greek-omitted} [χειρα]{.greek-added} αυτου δρεπανον οξυ[14:14]{.aside}

και αλλος αγγελος εξηλθεν εκ του ναου κραζων εν φωνη μεγαλη τω καθημενω επι της νεφελης πεμψον το δρεπανον σου και θερισον οτι ηλθεν η ωρα θερισαι οτι εξηρανθη ο θερισμος της γης[14:15]{.aside}

και εβαλεν ο καθημενος επι [την]{.greek-omitted} [τη]{.greek-added} [νεφελην]{.greek-omitted} [νεφελη]{.greek-added} το δρεπανον αυτου επι την γην και εθερισθη η γη[14:16]{.aside}

και αλλος αγγελος εξηλθεν εκ του ναου [του]{.greek-omitted} εν τω [ουρανω]{.greek-abbr} εχων και αυτος δρεπανον οξυ[14:17]{.aside}

και αλλος αγγελος [εξηλθεν]{.greek-omitted} [εξησθεν]{.greek-added} εκ του θυσιαστηριου εχων εξουσιαν επι του πυρος και [ελενησεν]{.greek-added} [εφωνησεν]{.corr} [εν]{.greek-added} κραυγη μεγαλη τω εχοντι το δρεπανον [το]{.greek-omitted} [οξυ]{.greek-omitted} [λεγων]{.greek-omitted} [πεμψον]{.greek-omitted} [σου]{.greek-omitted} [το]{.greek-omitted} [δρεπανον]{.greek-omitted} [το]{.greek-omitted} [οξυ]{.greek-omitted} [και]{.greek-omitted} [τρυγησον]{.greek-omitted} [τους]{.greek-omitted} [βοτρυας]{.greek-omitted} [της]{.greek-omitted} [αμπελου]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [οτι]{.greek-omitted} [ηκμασαν]{.greek-omitted} [αι]{.greek-omitted} [σταφυλαι]{.greek-omitted} [αυτης]{.greek-omitted}[14:18]{.aside}

[και]{.greek-omitted} [αλλος]{.greek-omitted} [αγγελος]{.greek-omitted} [εξηλθεν]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [θυσιαστηριου]{.greek-omitted} [εχων]{.greek-omitted} [εξουσιαν]{.greek-omitted} [επι]{.greek-omitted} [του]{.greek-omitted} [πυρος]{.greek-omitted} [και]{.greek-omitted} [εφωνησεν]{.greek-omitted} [κραυγη]{.greek-omitted} [μεγαλη]{.greek-omitted} [τω]{.greek-omitted} [εχοντι]{.greek-omitted} [το]{.greek-omitted} [δρεπανον]{.greek-omitted} το οξυ λεγων πεμψον σου το δρεπανον το οξυ και τρυγησον τους βοτρυας της αμπελου της γης [οτι]{.greek-omitted} [ηκμασαν]{.greek-omitted} [αι]{.greek-omitted} [σταφυλαι]{.greek-omitted} [αυτης]{.greek-omitted}[14:18 | instance no. 2]{.aside}

και [εβαλεν]{.greek-omitted} [εξεβαλεν]{.greek-added} ο αγγελος το δρεπανον αυτου εις την γην και ετρυγησεν την αμπελον της γης και εβαλεν εις [την]{.greek-omitted} [τον]{.greek-added} ληνον [του]{.greek-omitted} [τον]{.greek-added} [θυμου]{.greek-omitted} [θυμον]{.greek-added} του [θεου]{.greek-abbr} τον μεγαν[14:19]{.aside}

και επατηθη [η]{.corr} ληνος εξωθεν της πολεως και εξηλθεν αιμα εκ της ληνου [αχρι]{.greek-omitted} [αχρη]{.greek-added} των χαλινων των ιππων απο σταδιων χιλιων εξακοσιων[14:20]{.aside}

### Chapter 15

και ειδον αλλο σημειον εν τω [υνω]{.greek-added} [[ουρανω]{.greek-abbr}]{.corr} μεγα και θαυμαστον αγγελους επτα εχοντας πληγας επτα τας εσχατας οτι εν αυταις ετελεσθη ο θυμος του [θεου]{.greek-abbr}[15:1]{.aside}

και ειδον ως θαλασσαν [υαλινην]{.greek-omitted} [υαληνην]{.greek-added} μεμιγμενην πυρι και τους νικωντας εκ [της]{.greek-added} [εικονος]{.greek-added} [και]{.greek-added} [εκ]{.greek-added} του θηριου [και]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [εικονος]{.greek-omitted} αυτου και εκ του αριθμου του ονοματος αυτου εστωτας επι την θαλασσαν την [υαλινην]{.greek-omitted} [υαληνην]{.greek-added} εχοντας κιθαρας του [θεου]{.greek-abbr}[15:2]{.aside}

και [αδουσιν]{.greek-omitted} [αδουσι]{.greek-added} [την]{.greek-omitted} [ωδην]{.greek-omitted} [μωυσεως]{.greek-omitted} [του]{.greek-omitted} [δουλου]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [και]{.greek-omitted} την ωδην του αρνιου λεγοντες μεγαλα και θαυμαστα τα εργα σου [κυριε]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ [δικαιαι]{.greek-omitted} [αικαιαι]{.greek-added} και [αληθιναι]{.greek-omitted} [αληθηναι]{.greek-added} αι οδοι σου ο βασιλευς [των]{.greek-omitted} [εθνων]{.greek-omitted}[15:3]{.aside}

[και]{.greek-omitted} [αδουσιν]{.greek-omitted} [την]{.greek-omitted} [ωδην]{.greek-omitted} [μωυσεως]{.greek-omitted} [του]{.greek-omitted} [δουλου]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [και]{.greek-omitted} [την]{.greek-omitted} [ωδην]{.greek-omitted} [του]{.greek-omitted} [αρνιου]{.greek-omitted} [λεγοντες]{.greek-omitted} [μεγαλα]{.greek-omitted} [και]{.greek-omitted} [θαυμαστα]{.greek-omitted} [τα]{.greek-omitted} [εργα]{.greek-omitted} [σου]{.greek-omitted} [κυριε]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [ο]{.greek-omitted} [παντοκρατωρ]{.greek-omitted} [δικαιαι]{.greek-omitted} [και]{.greek-omitted} [αληθιναι]{.greek-omitted} [αι]{.greek-omitted} [οδοι]{.greek-omitted} [σου]{.greek-omitted} [ο]{.greek-omitted} [βασιλευς]{.greek-omitted} των εθνων[15:3 | instance no. 2]{.aside}

τις ου μη φοβηθη σε [κυριε]{.greek-abbr} και δοξαση το ονομα σου [ονομος]{.greek-added} [οτι]{.greek-omitted} [μονος]{.greek-omitted} αγιος οτι παντα τα εθνη [ηξουσιν]{.greek-omitted} [ηξουσι]{.greek-added} και προσκυνησουσιν ενωπιον σου οτι τα δικαιωματα σου εφανερωθησαν[15:4]{.aside}

και μετα ταυτα ειδον και ηνοιγη ο ναος της σκηνης του μαρτυριου εν τω [ουρανω]{.greek-abbr}[15:5]{.aside}

και εξηλθον οι επτα [πτεριγοι]{.greek-added} [επτα]{.greek-added} αγγελοι [εκ]{.greek-added} [του]{.greek-added} [ναου]{.greek-added} οι εχοντες τας επτα πληγας [εκ]{.greek-omitted} [του]{.greek-omitted} [ναου]{.greek-omitted} οι ησαν ενδεδυμενοι λινον καθαρον λαμπρον και περιεζωσμενοι περι τα στηθη ζωνας χρυσας[15:6]{.aside}

και εν εκ των τεσσαρων ζωων [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} τοις επτα αγγελοις επτα φιαλας χρυσας γεμουσας του θυμου του [θεου]{.greek-abbr} [του]{.greek-omitted} ζωντος εις τους αιωνας [των]{.greek-omitted} [αιωνων]{.greek-omitted}[15:7]{.aside}

και εγεμισθη ο ναος [του]{.greek-added} καπνου εκ της δοξης του [θεου]{.greek-abbr} και [εκ]{.greek-omitted} της δυναμεως αυτου και ουδεις [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} εισελθειν εις τον ναον αχρι τελεσθωσιν αι επτα πληγαι των επτα αγγελων[15:8]{.aside}

### Chapter 16

και ηκουσα [μεγαλης]{.greek-added} φωνης [μεγαλης]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [ναου]{.greek-omitted} λεγουσης τοις επτα αγγελοις υπαγετε και εκχεατε τας επτα φιαλας του θυμου του [θεου]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [γην]{.greek-omitted}[16:1]{.aside}

[και]{.greek-omitted} [ηκουσα]{.greek-omitted} [φωνης]{.greek-omitted} [μεγαλης]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [ναου]{.greek-omitted} [λεγουσης]{.greek-omitted} [τοις]{.greek-omitted} [επτα]{.greek-omitted} [αγγελοις]{.greek-omitted} [υπαγετε]{.greek-omitted} [και]{.greek-omitted} [εκχεατε]{.greek-omitted} [τας]{.greek-omitted} [επτα]{.greek-omitted} [φιαλας]{.greek-omitted} [του]{.greek-omitted} [θυμου]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-abbr} εις την γην[16:1 | instance no. 2]{.aside}

και απηλθεν ο πρωτος και [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου εις την γην και εγενετο ελκος κακον και πονηρον επι τους [ανθρωπους]{.greek-abbr} τους [εχοντας]{.greek-omitted} [ανεχοντας]{.greek-added} το χαραγμα του θηριου και τους προσκυνουντας τη εικονι αυτου[16:2]{.aside}

και ο δευτερος αγγελος [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου εις την θαλασσαν και εγενετο αιμα ως νεκρου και πασα ψυχη [ζωσα]{.greek-omitted} απεθανεν εν τη θαλασση[16:3]{.aside}

και ο τριτος [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου εις τους ποταμους και εις τας πηγας των υδατων και εγενετο αιμα[16:4]{.aside}

και ηκουσα του αγγελου των υδατων λεγοντος δικαιος ει ο ων και ο ην ο οσιος οτι ταυτα εκρινας[16:5]{.aside}

οτι αιμα [αγιων]{.greek-omitted} [ἁγίων]{.greek-added} και προφητων εξεχεαν και αιμα αυτοις εδωκας πιειν αξιοι [εισιν]{.greek-omitted} [εισι]{.greek-added}[16:6]{.aside}

και ηκουσα του [θυσιαστηριου]{.greek-omitted} [θησιστηριου]{.greek-added} λεγοντος ναι [κυριε]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ αληθιναι και δικαιαι αι κρισεις σου[16:7]{.aside}

και ο τεταρτος αγγελος [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου επι τον ηλιον και [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} αυτω καυματισαι εν πυρι τους [ανθρωπους]{.greek-omitted}[16:8]{.aside}

[και]{.greek-omitted} [ο]{.greek-omitted} [τεταρτος]{.greek-omitted} [αγγελος]{.greek-omitted} [εξεχεεν]{.greek-omitted} [την]{.greek-omitted} [φιαλην]{.greek-omitted} [αυτου]{.greek-omitted} [επι]{.greek-omitted} [τον]{.greek-omitted} [ηλιον]{.greek-omitted} [και]{.greek-omitted} [εδοθη]{.greek-omitted} [αυτω]{.greek-omitted} [καυματισαι]{.greek-omitted} [εν]{.greek-omitted} [πυρι]{.greek-omitted} [τους]{.greek-omitted} [ανθρωπους]{.greek-abbr}[16:8 | instance no. 2]{.aside}

και εκαυματισθησαν οι [ανθρωποι]{.greek-abbr} καυμα μεγα και [εβλασφημησαν]{.greek-omitted} [εβλασφημισαν]{.greek-added} οι [ανθρωποι]{.greek-abbr} το ονομα του [θεου]{.greek-abbr} του εχοντος εξουσιαν επι τας πληγας ταυτας και ου μετενοησαν δουναι αυτω δοξαν[16:9]{.aside}

και ο [πεμπτος]{.greek-omitted} [πεμτος]{.greek-added} [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου επι τον θρονον του θηριου και εγενετο η βασιλεια αυτου [εσκοτωμενη]{.greek-omitted} [εσκοτισμενη]{.greek-added} και [εμασωντο]{.greek-omitted} [εμασοντο]{.greek-added} τας γλωσσας αυτων εκ του πονου[16:10]{.aside}

και [εβλασφημησαν]{.greek-omitted} [εβλασφημισαν]{.greek-added} τον [θεον]{.greek-abbr} του [ουρανου]{.greek-abbr} εκ των πονων αυτων και εκ των ελκων αυτων και ου μετενοησαν εκ των εργων αυτων[16:11]{.aside}

και ο εκτος [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} [αυτου]{.greek-added} την φιαλην [αυτου]{.greek-omitted} επι τον ποταμον τον μεγαν ευφρατην και εξηρανθη το υδωρ αυτου ινα ετοιμασθη η οδος [απο]{.greek-added} [ανατολης]{.greek-added} των βασιλεων [των]{.greek-omitted} [απο]{.greek-omitted} [ανατολης]{.greek-omitted} [ηλιου]{.greek-omitted}[16:12]{.aside}

και ειδον εκ του στοματος του [δρακοντος]{.greek-omitted} [δρακωντος]{.greek-added} και εκ του στοματος του θηριου και εκ του στοματος του ψευδοπροφητου πνευματα ακαθαρτα τρια ως βατραχοι[16:13]{.aside}

[εισιν]{.greek-omitted} [εισι]{.greek-added} γαρ πνευματα δαιμονιων [ποιουντα]{.greek-omitted} [ποιουν]{.greek-added} [σημεια]{.greek-omitted} [α]{.greek-omitted} [εκπορευεται]{.greek-omitted} [επι]{.greek-omitted} [τους]{.greek-omitted} [βασιλεις]{.greek-omitted} [της]{.greek-omitted} [οικουμενης]{.greek-omitted} [ολης]{.greek-omitted} [συναγαγειν]{.greek-omitted} [αυτους]{.greek-omitted} [εις]{.greek-omitted} [τον]{.greek-omitted} [πολεμον]{.greek-omitted} [της]{.greek-omitted} [ημερας]{.greek-omitted} [εκεινης]{.greek-omitted} [της]{.greek-omitted} [μεγαλης]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [του]{.greek-omitted} [παντοκρατορος]{.greek-omitted}[16:14]{.aside}

[τα]{.greek-added} [εισιν]{.greek-omitted} [γαρ]{.greek-omitted} [πνευματα]{.greek-omitted} [δαιμονιων]{.greek-omitted} [ποιουντα]{.greek-omitted} σημεια α εκπορευεται επι τους βασιλεις της οικουμενης ολης συναγαγειν αυτους εις τον πολεμον της ημερας εκεινης της μεγαλης του [θεου]{.greek-abbr} [του]{.greek-omitted} παντοκρατορος[16:14 | instance no. 2]{.aside}

ιδου ερχομαι ως κλεπτης [και]{.greek-added} μακαριος ο γρηγορων και τηρων τα ιματια αυτου ινα [μη]{.greek-omitted} γυμνος περιπατη και [βλεπωσιν]{.greek-omitted} [βλεπουσι]{.greek-added} την ασχημοσυνην αυτου[16:15]{.aside}

και συνηγαγεν αυτους εις τον τοπον τον καλουμενον εβραιστι [αρμαγεδων]{.greek-omitted} [μαγιδὼν]{.greek-added}[16:16]{.aside}

και ο εβδομος [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου επι τον αερα και [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} φωνη μεγαλη απο του ναου του ουρανου απο του θρονου [του]{.greek-added} [[θεου]{.greek-abbr}]{.greek-added} λεγουσα [γεγονεν]{.greek-omitted} [γεγονε]{.greek-added}[16:17]{.aside}

και εγενοντο αστραπαι και βρονται και φωναι και σεισμος μεγας οιος ουκ εγενετο αφ ου οι [ανθρωποι]{.greek-abbr} εγενοντο επι της γης τηλικουτος σεισμος [ουτως]{.greek-omitted} [ουτω]{.greek-added} μεγας[16:18]{.aside}

και εγενετο [η]{.greek-added} [πολεις]{.greek-added} η πολις η μεγαλη εις τρια μερη και [αι]{.greek-omitted} [πολεις]{.greek-omitted} [επολεις]{.greek-added} των εθνων [επεσον]{.greek-omitted} [επεσσον]{.greek-added} και βαβυλων η μεγαλη εμνησθη [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [δουναι]{.greek-omitted} [αυτη]{.greek-omitted} [το]{.greek-omitted} [ποτηριον]{.greek-omitted} [του]{.greek-omitted} [οινου]{.greek-omitted} [του]{.greek-omitted} [θυμου]{.greek-omitted} [της]{.greek-omitted} [οργης]{.greek-omitted} [αυτου]{.greek-omitted}[16:19]{.aside}

[και]{.greek-omitted} [εγενετο]{.greek-omitted} [η]{.greek-omitted} [πολις]{.greek-omitted} [η]{.greek-omitted} [μεγαλη]{.greek-omitted} [εις]{.greek-omitted} [τρια]{.greek-omitted} [μερη]{.greek-omitted} [και]{.greek-omitted} [αι]{.greek-omitted} [πολεις]{.greek-omitted} [των]{.greek-omitted} [εθνων]{.greek-omitted} [επεσον]{.greek-omitted} [και]{.greek-omitted} [βαβυλων]{.greek-omitted} [η]{.greek-omitted} [μεγαλη]{.greek-omitted} [εμνησθη]{.greek-omitted} [ενωπιον]{.greek-omitted} [ενοπιον]{.greek-added} του [θεου]{.greek-abbr} δουναι αυτη το ποτηριον του οινου του θυμου της οργης [αυτου]{.greek-omitted} [του]{.greek-added} [[θεου]{.greek-abbr}]{.greek-added}[16:19 | instance no. 2]{.aside}

και πασα νησος [εφυγεν]{.greek-omitted} [εφυγε]{.greek-added} και ορη ουχ ευρεθησαν[16:20]{.aside}

και χαλαζα μεγαλη ως ταλαντιαια καταβαινει εκ του [ουρανου]{.greek-abbr} επι τους [ανθρωπους]{.greek-abbr} και εβλασφημησαν οι [ανθρωποι]{.greek-abbr} [επι]{.greek-added} τον [θεον]{.greek-abbr} εκ της πληγης της χαλαζης οτι μεγαλη εστιν η πληγη [αυ]{.greek-added} [αυτης]{.greek-omitted} [[αυτη]{.corr}]{.greek-added} σφοδρα[16:21]{.aside}

### Chapter 17

και ηλθεν εις εκ των επτα αγγελων των εχοντων τας [επτα]{.greek-omitted} φιαλας και [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} μετ εμου λεγων δευρο δειξω σοι το κριμα της πορνης της μεγαλης της καθημενης επι [των]{.greek-omitted} υδατων των [πολλων]{.greek-omitted} [πολων]{.greek-added}[17:1]{.aside}

μεθ ης επορνευσαν οι βασιλεις της γης και εμεθυσθησαν οι [κατοικουντεστες]{.greek-added} [κατοικουντες]{.corr} την γην εκ του οινου της πορνειας αυτης[17:2]{.aside}

και [απηνεγκεν]{.greek-omitted} [απηνεγκε]{.greek-added} [με]{.greek-omitted} [μοι]{.greek-added} εις ερημον [εν]{.greek-omitted} [τοπον]{.greek-added} [πνευματι]{.greek-abbr} και ειδον γυναικα καθημενην επι θηριον [το]{.greek-added} [κοκκινον]{.greek-omitted} [κοκινον]{.greek-added} [γεμον]{.greek-omitted} [γεμων]{.greek-added} ονοματα βλασφημιας [εχον]{.greek-omitted} [εχων]{.greek-added} κεφαλας επτα [και]{.greek-omitted} κερατα δεκα[17:3]{.aside}

και η γυνη [η]{.unclear}ν περιβεβλημενη [πορφυρουν]{.greek-omitted} [και]{.greek-omitted} [κοκκινον]{.greek-omitted} [κεχρυσωμενη]{.greek-omitted} χρυσιω και λιθω τιμιω και [μαργαριταις]{.greek-omitted} [μαργαριτας]{.greek-added} εχουσα ποτηριον [χρυ]{.greek-added} [χρυσουν]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [χειρι]{.greek-omitted} [αυτης]{.greek-omitted} [γεμον]{.greek-omitted} [βδελυγματων]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} [ακαθαρτα]{.greek-omitted} [της]{.greek-omitted} [πορνειας]{.greek-omitted} [αυτης]{.greek-omitted}[17:4]{.aside}

[σουν]{.greek-added} [και]{.greek-omitted} [η]{.greek-omitted} [γυνη]{.greek-omitted} [ην]{.greek-omitted} [περιβεβλημενη]{.greek-omitted} [πορφυρουν]{.greek-omitted} [και]{.greek-omitted} [κοκκινον]{.greek-omitted} [κεχρυσωμενη]{.greek-omitted} [χρυσιω]{.greek-omitted} [και]{.greek-omitted} [λιθω]{.greek-omitted} [τιμιω]{.greek-omitted} [και]{.greek-omitted} [μαργαριταις]{.greek-omitted} [εχουσα]{.greek-omitted} [ποτηριον]{.greek-omitted} [χρυσουν]{.greek-omitted} εν τη χειρι αυτης [γεμον]{.greek-omitted} [γεμων]{.greek-added} [βδελυγματων]{.greek-omitted} [βδεληγματων]{.greek-added} και τα ακαθαρτα της πορνειας αυτης[17:4 | instance no. 2]{.aside}

και επι το [μετωπον]{.greek-omitted} [μετοπον]{.greek-added} αυτης [ονομα]{.greek-omitted} [γεγραμμενον]{.greek-omitted} [γεγραμενον]{.greek-added} μυστηριον βαβυλων η μεγαλη η [μητηρ]{.greek-abbr} των [πορνων]{.greek-omitted} [πορνῶν]{.greek-added} και των βδελυγματων της γης[17:5]{.aside}

και ειδον την γυναικα μεθυουσαν [εκ]{.greek-omitted} του αιματος των αγιων εκ του αιματος των μαρτυρων [ιησου]{.greek-abbr} και εθαυμασα ιδων αυτην θαυμα μεγα[17:6]{.aside}

και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} μοι ο αγγελος δια τι εθαυμασας [εγω]{.greek-omitted} ερω σοι το μυστηριον της γυναικος και του θηριου του βασταζοντος αυτην του εχοντος τας επτα κεφαλας και τα δεκα κερατα[17:7]{.aside}

το θηριον ο ειδες ην [και]{.greek-omitted} ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} και μελλει αναβαινειν εκ της αβυσσου και εις [απωλειαν]{.greek-omitted} [απολειαν]{.greek-added} υπαγειν και θαυμασονται οι κατοικουντες [την]{.greek-added} [γην]{.greek-added} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} ων ου γεγραπται [τα]{.greek-omitted} [το]{.greek-added} [ονοματα]{.greek-omitted} [ονομα]{.greek-added} επι [το]{.greek-omitted} [του]{.greek-added} [βιβλιον]{.greek-omitted} [βιβλιου]{.greek-added} της ζωης απο καταβολης κοσμου βλεποντων οτι ην το θηριον και ουκ [εστιν]{.greek-omitted} [εσται]{.greek-added} και παρεσται[17:8]{.aside}

ωδε ο νους ο εχων σοφιαν αι επτα κεφαλαι επτα ορη εισιν οπου η γυνη [καθη]{.greek-added} [καθηται]{.greek-omitted} [επ]{.greek-omitted} [αυτων]{.greek-omitted}[17:9]{.aside}

[ωδε]{.greek-omitted} [ο]{.greek-omitted} [νους]{.greek-omitted} [ο]{.greek-omitted} [εχων]{.greek-omitted} [σοφιαν]{.greek-omitted} [αι]{.greek-omitted} [ται]{.greek-added} [επτα]{.greek-omitted} [κεφαλαι]{.greek-omitted} [επτα]{.greek-omitted} [ορη]{.greek-omitted} [εισιν]{.greek-omitted} [οπου]{.greek-omitted} [η]{.greek-omitted} [γυνη]{.greek-omitted} [καθηται]{.greek-omitted} επ αυτων [και]{.greek-added} [βασιλεις]{.greek-added} [εισιν]{.greek-added} [επτα]{.greek-added}[17:9 | instance no. 2]{.aside}

[και]{.greek-omitted} [βασιλεις]{.greek-omitted} [εισιν]{.greek-omitted} [επτα]{.greek-omitted} οι πεντε επεσον ο εις εστιν [και]{.greek-added} ο αλλος ουπω ηλθεν και οταν ελθη ολιγον δει αυτον μειναι[17:10]{.aside}

και το θηριον ο ην [ουκ]{.greek-added} [εστι]{.greek-added} και [ουκ]{.greek-omitted} [εστιν]{.greek-omitted} [και]{.greek-omitted} [αυτος]{.greek-omitted} [ουτος]{.greek-added} ογδοος [εστιν]{.greek-omitted} [εστι]{.greek-added} [και]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [επτα]{.greek-omitted} [εστιν]{.greek-omitted} και εις απωλειαν υπαγει[17:11]{.aside}

και τα δεκα κερατα α ειδες δεκα βασιλεις εισιν οιτινες βασιλειαν ουπω ελαβον αλλ εξουσιαν ως βασιλεις μιαν ωραν λαμβανουσιν μετα του θηριου[17:12]{.aside}

ουτοι μιαν [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} γνωμην και την [δυναμιν]{.greek-omitted} [δυναμην]{.greek-added} και την εξουσιαν αυτων τω θηριω [διδοασιν]{.greek-omitted} [διδωασιν]{.greek-added}[17:13]{.aside}

ουτοι μετα του αρνιου [πολεμησουσιν]{.greek-omitted} [πολεμισουσι]{.greek-added} και το αρνιον νικησει αυτους οτι [κυριος]{.greek-abbr} κυριων [εστιν]{.greek-omitted} [εστι]{.greek-added} και βασιλευς βασιλεων και οι μετ αυτου [κλητοι]{.greek-omitted} [κλιτοι]{.greek-added} και εκλεκτοι και πιστοι[17:14]{.aside}

και λεγει μοι τα υδατα α ειδες ου η πορνη καθηται λαοι και οχλοι [εισιν]{.greek-omitted} [εισι]{.greek-added} και εθνη και γλωσσαι[17:15]{.aside}

και τα δεκα κερατα α ειδες και το θηριον ουτοι [μισησουσιν]{.greek-omitted} [μισησουσι]{.greek-added} την πορνην και ηρημωμενην ποιησουσιν αυτην και γυμνην ποιησουσιν αυτην και τας σαρκας αυτης φαγονται [και]{.greek-omitted} [αυτην]{.greek-omitted} [κατακαυσουσιν]{.greek-omitted} [εν]{.greek-omitted} [πυρι]{.greek-omitted}[17:16]{.aside}

[και]{.greek-omitted} [τα]{.greek-omitted} [δεκα]{.greek-omitted} [κερατα]{.greek-omitted} [α]{.greek-omitted} [ειδες]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [θηριον]{.greek-omitted} [ουτοι]{.greek-omitted} [μισησουσιν]{.greek-omitted} [την]{.greek-omitted} [πορνην]{.greek-omitted} [και]{.greek-omitted} [ηρημωμενην]{.greek-omitted} [ποιησουσιν]{.greek-omitted} [αυτην]{.greek-omitted} [και]{.greek-omitted} [γυμνην]{.greek-omitted} [ποιησουσιν]{.greek-omitted} [αυτην]{.greek-omitted} [και]{.greek-omitted} [τας]{.greek-omitted} [σαρκας]{.greek-omitted} [αυτης]{.greek-omitted} [φαγονται]{.greek-omitted} και αυτην κατακαυσουσιν εν πυρι[17:16 | instance no. 2]{.aside}

ο γαρ [θεος]{.greek-abbr} εδωκεν εις τας καρδιας αυτων ποιησαι την [γνωμην]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [ποιησαι]{.greek-omitted} γνωμην μιαν και δουναι την βασιλειαν αυτων τω θηριω αχρι τελεσθωσιν οι λογοι του [θεου]{.greek-abbr}[17:17]{.aside}

και η γυνη ην ειδες εστιν η πολις η μεγαλη [η]{.greek-omitted} [εχουσα]{.greek-omitted} [εχουσαι]{.greek-added} βασιλειαν επι των βασιλεων της γης[17:18]{.aside}

### Chapter 18

μετα ταυτα ειδον αλλον αγγελον καταβαινοντα εκ του [ουρανου]{.greek-abbr} [εχοντα]{.greek-omitted} [εχον]{.greek-added} εξουσιαν μεγαλην και η γη εφωτισθη [εκ]{.greek-omitted} [επι]{.greek-added} της δοξης αυτου[18:1]{.aside}

και εκραξεν ισχυρα φωνη λεγων [επεσεν]{.greek-omitted} [επεσε]{.greek-added} βαβυλων η μεγαλη και εγενετο κατοικητηριον δαιμονων και φυλακη παντος [πνευματος]{.greek-abbr} ακαθαρτου και φυλακη παντος ορνεου ακαθαρτου και μεμισημενου[18:2]{.aside}

οτι εκ του οινου του θυμου της πορνειας αυτης [πεπτωκασιν]{.greek-omitted} [πεπτωκασι]{.greek-added} παντα τα εθνη και οι βασιλεις της γης μετ αυτης επορνευσαν και οι εμποροι της γης εκ της δυναμεως του στρηνους αυτης επλουτησαν[18:3]{.aside}

και [ηκουσα]{.greek-omitted} [ηκουσαν]{.greek-added} αλλην φωνην εκ του [ουρανου]{.greek-abbr} λεγουσαν εξελθε [ε]{.greek-added} [εξ]{.greek-omitted} [αυτης]{.greek-omitted} [ο]{.greek-omitted} [λαος]{.greek-omitted} [μου]{.greek-omitted} [ινα]{.greek-omitted} [μη]{.greek-omitted} [συγκοινωνησητε]{.greek-omitted} [ταις]{.greek-omitted} [αμαρτιαις]{.greek-omitted} [αυτης]{.greek-omitted} [και]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [πληγων]{.greek-omitted} [αυτης]{.greek-omitted} [ινα]{.greek-omitted} [μη]{.greek-omitted} [λαβητε]{.greek-omitted}[18:4]{.aside}

[ξ]{.greek-added} [και]{.greek-omitted} [ηκουσα]{.greek-omitted} [αλλην]{.greek-omitted} [φωνην]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [λεγουσαν]{.greek-omitted} [εξελθε]{.greek-omitted} [εξ]{.greek-omitted} αυτης ο λαος μου [ινα]{.greek-omitted} [και]{.greek-added} μη συγκοινωνησητε ταις αμαρτιαις αυτης [και]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [πληγων]{.greek-omitted} [αυτης]{.greek-omitted} ινα μη [λαβητε]{.greek-omitted} [λαθηται]{.greek-added}[18:4 | instance no. 2]{.aside}

οτι εκολληθησαν αυτης αι αμαρτιαι αχρι του [ουρανου]{.greek-abbr} και εμνημονευσεν [αυτοις]{.greek-added} ο [θεος]{.greek-abbr} τα αδικηματα αυτης[18:5]{.aside}

αποδοτε αυτη ως και αυτη [απεδωκεν]{.greek-omitted} [απεδωκε]{.greek-added} και διπλωσατε [τα]{.greek-added} [διπλα]{.greek-added} [ως]{.greek-added} [και]{.greek-added} αυτη [και]{.greek-added} [διπλα]{.greek-omitted} [κατα]{.greek-omitted} τα εργα αυτης εν τω ποτηριω [αυτης]{.greek-added} ω [εκερασεν]{.greek-omitted} [εκερασε]{.greek-added} κερασατε αυτη διπλουν[18:6]{.aside}

οσα εδοξασεν αυτην και εστρηνιασεν τοσουτον δοτε αυτη [βασανισμον]{.greek-omitted} [βασανεισμον]{.greek-added} και πενθος οτι εν τη καρδια αυτης λεγει οτι [καθημαι]{.greek-omitted} [ειμι]{.greek-added} [καθως]{.greek-added} [βασιλισσα]{.greek-omitted} [βασιλεισα]{.greek-added} και χηρα ουκ [ειμι]{.greek-omitted} [ιμι]{.greek-added} και πενθος ου μη ιδω[18:7]{.aside}

δια τουτο εν μια ημερα ηξουσιν αι πληγαι αυτης θανατος [και]{.greek-omitted} πενθος και λιμος και εν πυρι [κατακαυθησεται]{.greek-omitted} [καυθησεται]{.greek-added} οτι [ισχυρος]{.greek-omitted} [εισχυρος]{.greek-added} [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο κρινας αυτην[18:8]{.aside}

και [κλαυσουσιν]{.greek-omitted} [κλαυσουσι]{.greek-added} και κοψονται επ αυτην οι βασιλεις της γης οι μετ αυτης πορνευσαντες [και]{.greek-omitted} στρηνιασαντες οταν [βλεπωσιν]{.greek-omitted} [βλεπωσι]{.greek-added} τον καπνον της πυρωσεως αυτης[18:9]{.aside}

απο μακροθεν εστηκοτες δια τον φοβον του [βα]{.greek-added} [βασανισμου]{.greek-omitted} [αυτης]{.greek-omitted} [λεγοντες]{.greek-omitted} [ουαι]{.greek-omitted} [ουαι]{.greek-omitted} [η]{.greek-omitted} [πολις]{.greek-omitted} [η]{.greek-omitted} [μεγαλη]{.greek-omitted} [βαβυλων]{.greek-omitted} [η]{.greek-omitted} [πολις]{.greek-omitted} [η]{.greek-omitted} [ισχυρα]{.greek-omitted} [οτι]{.greek-omitted} [μια]{.greek-omitted} [ωρα]{.greek-omitted} [ηλθεν]{.greek-omitted} [η]{.greek-omitted} [κρισις]{.greek-omitted} [σου]{.greek-omitted}[18:10]{.aside}

[απο]{.greek-omitted} [μακροθεν]{.greek-omitted} [εστηκοτες]{.greek-omitted} [δια]{.greek-omitted} [τον]{.greek-omitted} [φοβον]{.greek-omitted} [του]{.greek-omitted} [βασανισμου]{.greek-omitted} [σανεισμου]{.greek-added} αυτης λεγοντες ουαι ουαι η [πολις]{.greek-omitted} [πολεις]{.greek-added} η μεγαλη βαβυλων η πολις η ισχυρα οτι μια ωρα ηλθεν η κρισις σου[18:10 | instance no. 2]{.aside}

και οι εμποροι της γης [κλαυσουσιν]{.greek-omitted} [κλαυσουσι]{.greek-added} και πενθησουσιν επ [αυτη]{.greek-omitted} [αυτην]{.greek-added} οτι τον γομον αυτων ουδεις αγοραζει ουκετι[18:11]{.aside}

γομον χρυσου και αργυρου και [λιθου]{.greek-omitted} [λιθον]{.greek-added} τιμιου και μαργαριτου και βυσσινου και πορφυρου και [σηρικου]{.greek-omitted} [συρικου]{.greek-added} και [κοκκινου]{.greek-omitted} [κοκινου]{.greek-added} και παν ξυλον θυινον [και]{.greek-omitted} [παν]{.greek-omitted} [σκευος]{.greek-omitted} [ελεφαντινον]{.greek-omitted} και παν σκευος εκ ξυλου τιμιωτατου και χαλκου και σιδηρου και μαρμαρου[18:12]{.aside}

και [κιναμωμον]{.greek-omitted} [κιναμωμου]{.greek-added} και [θυμιαματα]{.greek-omitted} [θυμιαματων]{.greek-added} και [μυρον]{.greek-omitted} [μυρων]{.greek-added} και [λιβανον]{.greek-omitted} [λιβανων]{.greek-added} [και]{.greek-omitted} [οινον]{.greek-omitted} και ελαιον και σεμιδαλιν και σιτον και προβατα και κτηνη και ιππων και ραιδων και [σωματων]{.greek-omitted} [και]{.greek-omitted} ψυχας [ανθρωπων]{.greek-abbr}[18:13]{.aside}

και η [οπωρα]{.greek-omitted} [οπορα]{.greek-added} της επιθυμιας της ψυχης σου απηλθεν απο σου και παντα τα λιπαρα και τα λαμπρα [απωλετο]{.greek-omitted} [απωλετω]{.greek-added} απο σου και ουκετι αυτα ου μη ευρης[18:14]{.aside}

οι εμποροι τουτων οι πλουτησαντες [απ]{.greek-omitted} [επ]{.greek-added} αυτης απο μακροθεν στησονται δια τον φοβον του [βασα]{.greek-added} [βασανισμου]{.greek-omitted} [αυτης]{.greek-omitted} [κλαιοντες]{.greek-omitted} [και]{.greek-omitted} [πενθουντες]{.greek-omitted}[18:15]{.aside}

[νισμου]{.greek-added} [οι]{.greek-omitted} [εμποροι]{.greek-omitted} [τουτων]{.greek-omitted} [οι]{.greek-omitted} [πλουτησαντες]{.greek-omitted} [απ]{.greek-omitted} αυτης [και]{.greek-added} [απο]{.greek-omitted} [μακροθεν]{.greek-omitted} [στησονται]{.greek-omitted} [δια]{.greek-omitted} [τον]{.greek-omitted} [φοβον]{.greek-omitted} [του]{.greek-omitted} [βασανισμου]{.greek-omitted} [αυτης]{.greek-omitted} κλαιοντες και πενθουντες[18:15 | instance no. 2]{.aside}

[και]{.greek-omitted} λεγοντες [ουαι]{.greek-omitted} ουαι η πολις η μεγαλη η περιβεβλημενη [βυσσινον]{.greek-omitted} [βυσσον]{.greek-added} και [πορφυρουν]{.greek-omitted} [πορφυραν]{.greek-added} και [κοκκινον]{.greek-omitted} [κοκινον]{.greek-added} και κεχρυσωμενη χρυσιω και λιθω τιμιω και μαργαριταις[18:16]{.aside}

οτι μια ωρα ηρημωθη ο τοσουτος πλουτος και πας [κυβερνητης]{.greek-omitted} [κυβερνιτις]{.greek-added} και πας [ο]{.greek-omitted} επι τοπον πλεων και ναυται και οσοι την θαλασσαν εργαζονται απο μακροθεν εστησαν[18:17]{.aside}

και εκραζον βλεποντες τον καπνον της πυρωσεως αυτης λεγοντες τις ομοια τη πολει τη μεγαλη[18:18]{.aside}

και εβαλον χουν επι τας κεφαλας αυτων και εκραζον κλαιοντες και πενθουντες [και]{.greek-omitted} λεγοντες ουαι ουαι η πολις η μεγαλη εν η [επλουτησαν]{.greek-omitted} [επλουτισαν]{.greek-added} παντες οι εχοντες τα πλοια εν τη θαλασση εκ της [τιμιοτητος]{.greek-omitted} [τιμιωτητος]{.greek-added} αυτης οτι μια ωρα ηρημωθη[18:19]{.aside}

[ευφραινου]{.greek-omitted} [ευφρενου]{.greek-added} επ αυτη [ουρανε]{.greek-abbr} και οι αγιοι και οι αποστολοι και οι προφηται οτι εκρινεν ο [θεος]{.greek-abbr} το κριμα [υμων]{.greek-omitted} [ημων]{.greek-added} εξ αυτης[18:20]{.aside}

και ηρεν εις αγγελος [ισχυρος]{.greek-omitted} λιθον ως μυλον μεγαν και [εβα]{.greek-added} [εβαλεν]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [θαλασσαν]{.greek-omitted} [λεγων]{.greek-omitted} [ουτως]{.greek-omitted} [ορμηματι]{.greek-omitted} [βληθησεται]{.greek-omitted} [βαβυλων]{.greek-omitted} [η]{.greek-omitted} [μεγαλη]{.greek-omitted} [πολις]{.greek-omitted} [και]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [ευρεθη]{.greek-omitted} [ετι]{.greek-omitted}[18:21]{.aside}

[λεν]{.greek-added} [και]{.greek-omitted} [ηρεν]{.greek-omitted} [εις]{.greek-omitted} [αγγελος]{.greek-omitted} [ισχυρος]{.greek-omitted} [λιθον]{.greek-omitted} [ως]{.greek-omitted} [μυλον]{.greek-omitted} [μεγαν]{.greek-omitted} [και]{.greek-omitted} [εβαλεν]{.greek-omitted} εις την θαλασσαν λεγων ουτως ορμηματι [βληθησεται]{.greek-omitted} [βληθησετε]{.greek-added} βαβυλων η μεγαλη πολις και ου μη ευρεθη ετι[18:21 | instance no. 2]{.aside}

και φωνη κιθαρωδων και μουσικων και αυλητων και σαλπιστων ου μη ακουσθη εν σοι ετι και πας τεχνιτης [πασης]{.greek-omitted} [τεχνης]{.greek-omitted} ου μη ευρεθη εν σοι ετι και φωνη μυλου ου μη ακουσθη εν σοι ετι[18:22]{.aside}

και [φως]{.greek-omitted} [φωνη]{.greek-added} λυχνου ου μη [φανη]{.greek-omitted} [φανῆ]{.greek-added} εν σοι ετι και φωνη νυμφιου και νυμφης ου μη ακουσθη εν σοι ετι [οτι]{.greek-omitted} οι εμποροι σου [ησαν]{.greek-omitted} οι μεγιστανες της γης οτι εν τη [φαρμακεια]{.greek-omitted} [φαρμακια]{.greek-added} σου επλανηθησαν παντα τα εθνη[18:23]{.aside}

και εν αυτη αιματα προφητων και αγιων ευρεθη και παντων των εσφαγμενων επι της γης[18:24]{.aside}

### Chapter 19

μετα ταυτα ηκουσα [ως]{.greek-omitted} φωνην μεγαλην οχλου [πολλου]{.greek-omitted} [πολου]{.greek-added} εν τω [ουρανω]{.greek-abbr} λεγοντων [αλληλουια]{.greek-omitted} [ἀλληλούια]{.greek-added} η [σωτηρια]{.greek-abbr} και η [δυναμις]{.greek-omitted} [δυναμεις]{.greek-added} και η δοξα του [θεου]{.greek-abbr} ημων[19:1]{.aside}

οτι αληθιναι και δικαιαι αι κρισεις αυτου οτι [εκρινεν]{.greek-omitted} [εκρινε]{.greek-added} την πορνην την μεγαλην ητις [διεφθειρεν]{.greek-omitted} [διεφθηρε]{.greek-added} την γην εν τη πορνεια αυτης και [εξεδικησεν]{.greek-omitted} [εξεδικησε]{.greek-added} το αιμα των δουλων [αυ]{.greek-added} [αυτου]{.greek-omitted} [εκ]{.greek-omitted} [χειρος]{.greek-omitted} [αυτης]{.greek-omitted}[19:2]{.aside}

[οτι]{.greek-omitted} [αληθιναι]{.greek-omitted} [και]{.greek-omitted} [δικαιαι]{.greek-omitted} [αι]{.greek-omitted} [κρισεις]{.greek-omitted} [αυτου]{.greek-omitted} [οτι]{.greek-omitted} [εκρινεν]{.greek-omitted} [την]{.greek-omitted} [πορνην]{.greek-omitted} [την]{.greek-omitted} [μεγαλην]{.greek-omitted} [ητις]{.greek-omitted} [διεφθειρεν]{.greek-omitted} [την]{.greek-omitted} [γην]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [πορνεια]{.greek-omitted} [αυτης]{.greek-omitted} [και]{.greek-omitted} [εξεδικησεν]{.greek-omitted} [το]{.greek-omitted} [του]{.greek-added} [αιμα]{.greek-omitted} [των]{.greek-omitted} [δουλων]{.greek-omitted} [αυτου]{.greek-omitted} εκ χειρος αυτης[19:2 | instance no. 2]{.aside}

και δευτερον [ειρηκεν]{.greek-omitted} [ειρηκασιν]{.greek-added} αλληλουια και ο καπνος αυτης αναβαινει εις τους αιωνας των αιωνων[19:3]{.aside}

και επεσον οι πρεσβυτεροι οι εικοσι [τεσσαρες]{.greek-omitted} [τεσσερεις]{.greek-added} και τα τεσσαρα ζωα και προσεκυνησαν τω [θεω]{.greek-abbr} τω καθημενω επι [του]{.greek-omitted} [θρονου]{.greek-omitted} [τω]{.greek-added} [θρωνω]{.greek-added} λεγοντες αμην αλληλουια[19:4]{.aside}

και φωνη απο του θρονου [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} λεγουσα [αινειτε]{.greek-omitted} [αινειται]{.greek-added} τον [θεον]{.greek-abbr} ημων παντες οι δουλοι αυτου και οι φοβουμενοι αυτον οι [μικροι]{.greek-omitted} [μικρι]{.greek-added} και οι μεγαλοι[19:5]{.aside}

και ηκουσα ως φωνην [οχλου]{.greek-omitted} [πολλου]{.greek-omitted} [και]{.greek-omitted} [ως]{.greek-omitted} [φωνην]{.greek-omitted} υδατων [πολλων]{.greek-omitted} [πολων]{.greek-added} και ως φωνην βροντων ισχυρων λεγοντες αλληλουια οτι [εβασιλευσεν]{.greek-omitted} [ε[β]{.unclear}ασιλευσε]{.greek-added} [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ημων ο παντοκρατωρ[19:6]{.aside}

[χαιρωμεν]{.greek-omitted} [χαιρομεν]{.greek-added} και [αγαλλιωμεθα]{.greek-omitted} [αγαλλιωμεν]{.greek-added} και δωμεν [την]{.greek-omitted} δοξαν αυτω οτι ηλθεν ο γαμος του αρνιου [αυτου]{.greek-added} και η γυνη αυτου ητοιμασεν εαυτην[19:7]{.aside}

και εδοθη αυτη ινα περιβαληται βυσσινον [λαμπρον]{.greek-omitted} [και]{.greek-omitted} [καθαρον]{.greek-omitted} [το]{.greek-omitted} [γαρ]{.greek-omitted} [βυσσινον]{.greek-omitted} τα δικαιωματα των αγιων [εστιν]{.greek-omitted} [εισι]{.greek-added}[19:8]{.aside}

και λεγει μοι γραψον μακαριοι οι εις [το]{.greek-omitted} [τον]{.greek-added} δειπνον του γαμου του αρνιου κεκλημενοι και λεγει μοι ουτοι οι λογοι [αλη]{.greek-added} [αληθινοι]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [εισιν]{.greek-omitted}[19:9]{.aside}

[και]{.greek-omitted} [λεγει]{.greek-omitted} [μοι]{.greek-omitted} [γραψον]{.greek-omitted} [μακαριοι]{.greek-omitted} [οι]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [δειπνον]{.greek-omitted} [του]{.greek-omitted} [γαμου]{.greek-omitted} [του]{.greek-omitted} [αρνιου]{.greek-omitted} [κεκλημενοι]{.greek-omitted} [και]{.greek-omitted} [λεγει]{.greek-omitted} [μοι]{.greek-omitted} [ουτοι]{.greek-omitted} [οι]{.greek-omitted} [λογοι]{.greek-omitted} [αληθινοι]{.greek-omitted} [θινοι]{.greek-added} του [θεου]{.greek-abbr} [εισιν]{.greek-omitted} [εισι]{.greek-added}[19:9 | instance no. 2]{.aside}

και [επεσα]{.greek-omitted} [επεσον]{.greek-added} εμπροσθεν των ποδων αυτου προσκυνησαι αυτω και λεγει μοι ορα μη συνδουλος σου ειμι και των αδελφων σου των [εχοντων]{.greek-omitted} [εχωντων]{.greek-added} την μαρτυριαν [ιησου]{.greek-abbr} τω [θεω]{.greek-abbr} προσκυνησον η γαρ μαρτυρια του [ιησου]{.greek-abbr} [εστιν]{.greek-omitted} [εστι]{.greek-added} το [πνευμα]{.greek-abbr} της προφητειας[19:10]{.aside}

και ειδον τον [ουρανον]{.greek-abbr} ανεωγμενον και ιδου ιππος λευκος και ο καθημενος επ αυτον καλουμενος πιστος και αληθινος και εν δικαιοσυνη [κρινει]{.greek-omitted} [κρινη]{.greek-added} και πολεμει[19:11]{.aside}

οι δε οφθαλμοι αυτου φλοξ πυρος και επι την κεφαλην αυτου διαδηματα πολλα εχων ονοματα [γεγραμμενα]{.greek-omitted} [γεγραμμε]{.greek-added} και ονομα [γεγραμμενον]{.greek-omitted} [γγραμμενον]{.greek-added} ο ουδεις οιδεν ει μη αυτος[19:12]{.aside}

και περιβεβλημενος ιματιον [πορφυρουν]{.greek-added} [βεβαμμενον]{.greek-omitted} [βεβαμενον]{.greek-added} αιματι και [καλειται]{.greek-omitted} [κεληται]{.greek-added} το ονομα αυτου ο λογος του [θεου]{.greek-abbr}[19:13]{.aside}

και τα στρατευματα [τα]{.greek-omitted} εν τω [ουρανω]{.greek-abbr} ηκολουθει αυτω επι ιπποις λευκοις ενδεδυμενοι [βυσσινον]{.greek-omitted} [βυσινον]{.greek-added} λευκον καθαρον[19:14]{.aside}

και εκ του στοματος αυτου [εκπορευεται]{.greek-omitted} [εκπορευετε]{.greek-added} ρομφαια διστομος [οξεια]{.greek-omitted} [ινα]{.greek-omitted} [εν]{.greek-omitted} [αυτη]{.greek-omitted} [παταξη]{.greek-omitted} [τα]{.greek-omitted} [εθνη]{.greek-omitted} [και]{.greek-omitted} [αυτος]{.greek-omitted} [ποιμανει]{.greek-omitted} [αυτους]{.greek-omitted} [εν]{.greek-omitted} [ραβδω]{.greek-omitted} [σιδηρα]{.greek-omitted} [και]{.greek-omitted} [αυτος]{.greek-omitted} [πατει]{.greek-omitted} [την]{.greek-omitted} [ληνον]{.greek-omitted} [του]{.greek-omitted} [οινου]{.greek-omitted} [του]{.greek-omitted} [θυμου]{.greek-omitted} [της]{.greek-omitted} [οργης]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [του]{.greek-omitted} [παντοκρατορος]{.greek-omitted}[19:15]{.aside}

[και]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [στοματος]{.greek-omitted} [αυτου]{.greek-omitted} [εκπορευεται]{.greek-omitted} [ρομφαια]{.greek-omitted} [διστομος]{.greek-omitted} οξεια ινα εν αυτη παταξη τα εθνη και αυτος ποιμανει αυτους εν ραβδω σιδηρα και αυτος πατει την ληνον του οινου του θυμου της οργης του [θεου]{.greek-abbr} του [παντοκρατορος]{.greek-omitted} [παντοκρατωρος]{.greek-added}[19:15 | instance no. 2]{.aside}

και εχει επι το ιματιον και επι τον μηρον αυτου ονομα γεγραμμενον βασιλευς βασιλεων και [κυριος]{.greek-abbr} κυριων[19:16]{.aside}

και ειδον αγγελον [εστωτα]{.greek-omitted} [εστοτα]{.greek-added} εν τω ηλιω και εκραξεν φωνη μεγαλη λεγων [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις ορνεοις τοις πετομενοις εν μεσουρανηματι δευτε συναχθητε εις [το]{.greek-omitted} [τον]{.greek-added} δειπνον [το]{.greek-omitted} [τον]{.greek-added} μεγα [του]{.greek-omitted} [τον]{.greek-added} [θεου]{.greek-abbr}[19:17]{.aside}

ινα φαγητε σαρκας βασιλεων και σαρκας χιλιαρχων και σαρκας ισχυρων και σαρκας ιππων και των καθημενων επ αυτων και σαρκας παντων ελευθερων τε και δουλων και μικρων τε και μεγαλων[19:18]{.aside}

και ειδον το θηριον και τους βασιλεις της γης και τα στρατευματα αυτων [συνηγμενα]{.greek-omitted} [συνηγμεγμενα]{.greek-added} ποιησαι πολεμον μετα του καθημενου επι του ιππου και μετα του στρατευματος αυτου[19:19]{.aside}

και επιασθη το θηριον [και]{.greek-omitted} [ο]{.greek-omitted} [μετ]{.greek-omitted} [αυτου]{.greek-omitted} [ψευδοπροφητης]{.greek-omitted} [ο]{.greek-omitted} [ποιησας]{.greek-omitted} [τα]{.greek-omitted} [σημεια]{.greek-omitted} [ενωπιον]{.greek-omitted} [αυτου]{.greek-omitted} [εν]{.greek-omitted} [οις]{.greek-omitted} [επλανησεν]{.greek-omitted} [τους]{.greek-omitted} [λαβοντας]{.greek-omitted} [το]{.greek-omitted} [χαραγμα]{.greek-omitted} [του]{.greek-omitted} [θηριου]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [προσκυνουντας]{.greek-omitted} [τη]{.greek-omitted} [εικονι]{.greek-omitted} [αυτου]{.greek-omitted} [ζωντες]{.greek-omitted} [εβληθησαν]{.greek-omitted} [οι]{.greek-omitted} [δυο]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [λιμνην]{.greek-omitted} [του]{.greek-omitted} [πυρος]{.greek-omitted} [την]{.greek-omitted} [καιομενην]{.greek-omitted} [εν]{.greek-omitted} [θειω]{.greek-omitted}[19:20]{.aside}

[και]{.greek-omitted} [επιασθη]{.greek-omitted} [το]{.greek-omitted} [θηριον]{.greek-omitted} και ο μετ αυτου ψευδοπροφητης ο ποιησας τα σημεια ενωπιον αυτου εν οις [επλανησεν]{.greek-omitted} [επλανησε]{.greek-added} τους λαβοντας το χαραγμα του θηριου και τους προσκυνουντας τη εικονι αυτου ζωντες εβληθησαν οι δυο εις την λιμνην του πυρος την [καιομενην]{.greek-omitted} [κεομενην]{.greek-added} εν θειω[19:20 | instance no. 2]{.aside}

και οι λοιποι απεκτανθησαν εν τη ρομφαια του καθημενου επι του ιππου τη εξελθουση εκ του στοματος αυτου και παντα τα ορνεα εχορτασθησαν εκ των σαρκων αυτων[19:21]{.aside}

### Chapter 20

και ειδον [αγγελολ]{.greek-added} [αγγελον]{.corr} καταβαινοντα εκ του [ουρανου]{.greek-abbr} εχοντα την κλειν της αβυσσου και αλυσιν μεγαλην επι την χειρα αυτου[20:1]{.aside}

και [εκρατησεν]{.greek-omitted} [εκρατεισε]{.greek-added} τον δρακοντα τον οφιν τον αρχαιον ος [εστιν]{.greek-omitted} [εστι]{.greek-added} διαβολος και [ο]{.greek-omitted} σατανας ο πλανων την οικουμενην ολην και εδησεν αυτον χιλια ετη[20:2]{.aside}

και εβαλεν αυτον εις την αβυσσον και [εκλεισεν]{.greek-omitted} [εκλησε]{.greek-added} και εσφραγισεν επανω αυτου ινα μη πλανα ετι τα εθνη [αχρι]{.greek-omitted} [αχρη]{.greek-added} τελεσθη τα χιλια [ετι]{.greek-added} [ετη]{.greek-omitted} [και]{.greek-omitted} μετα ταυτα δει [λυθηναι]{.greek-added} αυτον [λυθηναι]{.greek-omitted} μικρον χρονον[20:3]{.aside}

και ειδον [θρονους]{.greek-omitted} [και]{.greek-omitted} [εκαθισαν]{.greek-omitted} [επ]{.greek-omitted} [αυτους]{.greek-omitted} [και]{.greek-omitted} [κριμα]{.greek-omitted} [εδοθη]{.greek-omitted} [αυτοις]{.greek-omitted} [και]{.greek-omitted} [τας]{.greek-omitted} [ψυχας]{.greek-omitted} [των]{.greek-omitted} [πεπελεκισμενων]{.greek-omitted} [δια]{.greek-omitted} [την]{.greek-omitted} [μαρτυριαν]{.greek-omitted} [ιησου]{.greek-omitted} [και]{.greek-omitted} [δια]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [και]{.greek-omitted} [οιτινες]{.greek-omitted} [ου]{.greek-omitted} [προσεκυνησαν]{.greek-omitted} [το]{.greek-omitted} [θηριον]{.greek-omitted} [ουδε]{.greek-omitted} [την]{.greek-omitted} [εικονα]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [ελαβον]{.greek-omitted} [το]{.greek-omitted} [χαραγμα]{.greek-omitted} [επι]{.greek-omitted} [το]{.greek-omitted} [μετωπον]{.greek-omitted} [και]{.greek-omitted} [επι]{.greek-omitted} [την]{.greek-omitted} [χειρα]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [εζησαν]{.greek-omitted} [και]{.greek-omitted} [εβασιλευσαν]{.greek-omitted} [μετα]{.greek-omitted} [του]{.greek-omitted} [χριστου]{.greek-omitted} [τα]{.greek-omitted} [χιλια]{.greek-omitted} [ετη]{.greek-omitted}[20:4]{.aside}

[και]{.greek-omitted} [ειδον]{.greek-omitted} θρονους και [εκαθισαν]{.greek-omitted} [εκαθησαν]{.greek-added} επ [αυτους]{.greek-omitted} [αυτης]{.greek-added} και [εδωθη]{.greek-added} κριμα [εδοθη]{.greek-omitted} αυτοις και τας ψυχας των [πεπελεκισμενων]{.greek-omitted} [πεπελεκειμενων]{.greek-added} δια την μαρτυριαν [ιησου]{.greek-abbr} και δια τον λογον του [θεου]{.greek-abbr} και οιτινες ου [προσεκυνησαν]{.greek-omitted} [προσεκυνουν]{.greek-added} το θηριον ουδε την εικονα αυτου και ουκ ελαβον το χαραγμα επι [το]{.greek-omitted} [μετωπον]{.greek-omitted} [των]{.greek-added} [μετοπων]{.greek-added} και επι [την]{.greek-omitted} [τας]{.greek-added} [χειρα]{.greek-omitted} [χειρας]{.greek-added} αυτων και εζησαν και εβασιλευσαν μετα του [χριστου]{.greek-abbr} τα χιλια ετη[20:4 | instance no. 2]{.aside}

[και]{.greek-omitted} [οι]{.greek-omitted} [λοιποι]{.greek-omitted} [των]{.greek-omitted} [νεκρων]{.greek-omitted} [ουκ]{.greek-omitted} [εζησαν]{.greek-omitted} [αχρι]{.greek-omitted} [τελεσθη]{.greek-omitted} [τα]{.greek-omitted} [χιλια]{.greek-omitted} [ετη]{.greek-omitted} αυτη η [αναστασις]{.greek-omitted} [αναστασης]{.greek-added} η πρωτη[20:5]{.aside}

μακαριος και αγιος ο εχων μερος εν τη [αναστασει]{.greek-omitted} [ανασταση]{.greek-added} τη πρωτη [τους]{.greek-added} επι [τουτων]{.greek-omitted} [τουτους]{.greek-added} ο δευτερος θανατος ουκ εχει εξουσιαν αλλ εσονται ιερεις του [θεου]{.greek-abbr} και του [χριστου]{.greek-abbr} και [βασιλευσουσιν]{.greek-omitted} [βασιλευσουσι]{.greek-added} [μετ]{.greek-omitted} [μετα]{.greek-added} [αυτου]{.greek-omitted} [ταυτα]{.greek-added} [ετη]{.greek-added} χιλια [ετη]{.greek-omitted}[20:6]{.aside}

και [μετα]{.greek-added} [οταν]{.greek-omitted} [τελεσθη]{.greek-omitted} τα χιλια ετη λυθησεται ο σατανας εκ της φυλακης αυτου[20:7]{.aside}

και εξελευσεται πλανησαι [τα]{.greek-omitted} εθνη τα εν ταις [τεσσαρσιν]{.greek-omitted} [τεσσαρσι]{.greek-added} [γωνιαις]{.greek-omitted} [γονιαις]{.greek-added} της γης τον [γωγ]{.greek-omitted} [γογ]{.greek-added} και τον μαγωγ συναγαγειν αυτους εις τον πολεμον ων ο αριθμος [αυτων]{.greek-added} ως [η]{.greek-omitted} [ει]{.greek-added} αμμος της θαλασσης[20:8]{.aside}

και ανεβησαν επι το πλατος [της]{.greek-omitted} γης και [εκυκλωσαν]{.greek-omitted} [την]{.greek-omitted} [παρεμβολην]{.greek-omitted} [των]{.greek-omitted} [αγιων]{.greek-omitted} [και]{.greek-omitted} [την]{.greek-omitted} [πολιν]{.greek-omitted} [την]{.greek-omitted} [ηγαπημενην]{.greek-omitted} [και]{.greek-omitted} [κατεβη]{.greek-omitted} [πυρ]{.greek-omitted} [εκ]{.greek-omitted} [εκυ]{.greek-added} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [και]{.greek-omitted} [κατεφαγεν]{.greek-omitted} [αυτους]{.greek-omitted}[20:9]{.aside}

[κλευσαν]{.greek-added} [και]{.greek-omitted} [ανεβησαν]{.greek-omitted} [επι]{.greek-omitted} [το]{.greek-omitted} [πλατος]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [και]{.greek-omitted} [εκυκλωσαν]{.greek-omitted} την παρεμβολην των αγιων και την [πολιν]{.greek-omitted} [πολην]{.greek-added} την ηγαπημενην και κατεβη πυρ εκ του [ουρανου]{.greek-abbr} απο του [θεου]{.greek-abbr} και κατεφαγεν αυτους[20:9 | instance no. 2]{.aside}

και ο διαβολος ο πλανων αυτους εβληθη εις την [λιμνην]{.greek-omitted} [θαλασσαν]{.greek-added} του πυρος και θειου οπου [και]{.greek-omitted} [το]{.greek-omitted} [θηριον]{.greek-omitted} και ο ψευδοπροφητης και βασανισθησονται ημερας και νυκτος εις τους αιωνας των αιωνων[20:10]{.aside}

και ειδον θρονον μεγαν λευκον και τον καθημενον επ αυτον ου απο προσωπου εφυγεν [ο]{.greek-added} [[ουρανος]{.greek-abbr}]{.greek-added} [και]{.greek-added} η γη [και]{.greek-omitted} [ο]{.greek-omitted} [ουρανος]{.greek-omitted} και τοπος ουχ ευρεθη [αυτοις]{.greek-omitted} [αυτης]{.greek-added}[20:11]{.aside}

και ειδον τους νεκρους [τους]{.greek-omitted} [μεγαλους]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [μικρους]{.greek-omitted} εστωτας ενωπιον του θρονου και [βιβλια]{.greek-omitted} [βιβλιον]{.greek-added} [ηνεωχθησαν]{.greek-omitted} [ηνοιξαν]{.greek-added} και αλλο βιβλιον ηνεωχθη ο [εστιν]{.greek-omitted} [εστη]{.greek-added} της ζωης και εκριθησαν οι νεκροι εκ των γεγραμμενων εν τοις βιβλιοις κατα τα εργα αυτων[20:12]{.aside}

και εδωκεν η θαλασσα τους νεκρους τους εν αυτη και ο θανατος και ο αδης εδωκαν τους νεκρους τους εν αυτοις και εκριθησαν εκαστος κατα τα εργα αυτων[20:13]{.aside}

και ο θανατος και ο αδης εβληθησαν εις την λιμνην του πυρος ουτος ο [θανατος]{.greek-omitted} [ο]{.greek-omitted} [δευτερος]{.greek-omitted} [εστιν]{.greek-omitted} [η]{.greek-omitted} [λιμνη]{.greek-omitted} [του]{.greek-omitted} [πυρος]{.greek-omitted}[20:14]{.aside}

[και]{.greek-omitted} [ο]{.greek-omitted} [θανατος]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [αδης]{.greek-omitted} [εβληθησαν]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [λιμνην]{.greek-omitted} [του]{.greek-omitted} [πυρος]{.greek-omitted} [ουτος]{.greek-omitted} [ο]{.greek-omitted} θανατος ο δευτερος εστιν η λιμνη του πυρος[20:14 | instance no. 2]{.aside}

και ει τις ουχ ευρεθη εν τω βιβλιω της ζωης γεγραμμενος εβληθη εις την λιμνην του πυρος[20:15]{.aside}

### Chapter 21

και ειδον [ουρανον]{.greek-abbr} καινον και γην καινην ο γαρ πρωτος [ουρανος]{.greek-abbr} και η πρωτη γη απηλθον και η θαλασσα ουκ εστιν ετι[21:1]{.aside}

και την πολιν την αγιαν [ιερουσαλημ]{.greek-abbr} καινην ειδον καταβαινουσαν εκ του [ουρανου]{.greek-abbr} απο του [θεου]{.greek-abbr} ητοιμασμενην ως νυμφην κεκοσμημενην τω ανδρι αυτης[21:2]{.aside}

και ηκουσα φωνης μεγαλης εκ του [ουρανου]{.greek-omitted} [θρονου]{.greek-added} λεγουσης [αυτης]{.greek-added} ιδου η σκηνη του [θεου]{.greek-abbr} μετα των [ανθρωπων]{.greek-abbr} και σκηνωσει μετ αυτων και αυτοι λαος αυτου εσονται και αυτος ο [θεος]{.greek-abbr} [εσται]{.greek-omitted} μετ αυτων [εσται]{.greek-added}[21:3]{.aside}

και [εξαλειψει]{.greek-omitted} [εξαληψει]{.greek-added} [απ]{.greek-added} [αυτων]{.greek-added} παν δακρυον απο των οφθαλμων αυτων και ο θανατος ουκ εσται ετι [ουτε]{.greek-omitted} [πενθος]{.greek-omitted} [ουτε]{.greek-omitted} [κραυγη]{.greek-omitted} [ουτε]{.greek-omitted} [πονος]{.greek-omitted} [ουκ]{.greek-omitted} [εσται]{.greek-omitted} [ετι]{.greek-omitted} οτι τα πρωτα [απηλθον]{.greek-omitted} [απηλθεν]{.greek-added}[21:4]{.aside}

[και]{.greek-omitted} ειπεν ο καθημενος επι τω θρονω ιδου παντα καινα ποιω και λεγει [μοι]{.greek-omitted} γραψον [οτι]{.greek-omitted} ουτοι οι λογοι [πιστοι]{.greek-added} [και]{.greek-added} αληθινοι [και]{.greek-omitted} [πιστοι]{.greek-omitted} [του]{.greek-added} [[θεου]{.greek-abbr}]{.greek-added} [εισιν]{.greek-omitted} [εισι]{.greek-added}[21:5]{.aside}

και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} μοι [γεγονα]{.greek-omitted} [το]{.greek-omitted} [αλφα]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [ω]{.greek-omitted} [η]{.greek-omitted} [αρχη]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [τελος]{.greek-omitted} [εγω]{.greek-omitted} [τω]{.greek-omitted} [διψωντι]{.greek-omitted} [δωσω]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [πηγης]{.greek-omitted} [του]{.greek-omitted} [υδατος]{.greek-omitted} [της]{.greek-omitted} [ζωης]{.greek-omitted} [δωρεαν]{.greek-omitted}[21:6]{.aside}

[και]{.greek-omitted} [ειπεν]{.greek-omitted} [μοι]{.greek-omitted} γεγονα το [αλφα]{.greek-omitted} [άλφα]{.greek-added} και το [ω]{.greek-omitted} [ὦ]{.greek-added} [και]{.greek-added} η αρχη και το τελος εγω τω διψωντι δωσω [αυτω]{.greek-added} εκ της πηγης του υδατος [της]{.greek-omitted} [ζωης]{.greek-omitted} δωρεαν[21:6 | instance no. 2]{.aside}

ο νικων [κληρονομησει]{.greek-omitted} [δωσω]{.greek-added} [αυτω]{.greek-added} ταυτα και [εσομαι]{.greek-omitted} [εσωμαι]{.greek-added} αυτω [θεος]{.greek-abbr} και αυτος εσται [μοι]{.greek-omitted} [μου]{.greek-added} υιος[21:7]{.aside}

τοις δε [δειλοις]{.greek-omitted} [δηλοις]{.greek-added} και απιστοις και [αμαρτωλοις]{.greek-omitted} [αμαρτολοις]{.greek-added} και εβδελυγμενοις και [φονευσιν]{.greek-omitted} [φωνευσι]{.greek-added} και πορνοις και φαρμακοις και ειδωλολατραις και [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις [ψευδεσιν]{.greek-omitted} [ψευδεσι]{.greek-added} το μερος αυτων εν τη λιμνη τη καιομενη πυρι και θειω ο εστιν ο θανατος ο δευτερος[21:8]{.aside}

και ηλθεν εις εκ των επτα αγγελων των [εχοντων]{.greek-omitted} [εχωντων]{.greek-added} τας επτα φιαλας γεμουσας [των]{.greek-omitted} επτα [πληγων]{.greek-omitted} [των]{.greek-omitted} [εσχατων]{.greek-omitted} [πληγας]{.greek-added} [τας]{.greek-added} [εσχατας]{.greek-added} και [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} μετ εμου λεγων δευρο δειξω σοι την γυναικα την νυμφην του αρνιου[21:9]{.aside}

και [απηνεγκεν]{.greek-omitted} [απηνεγκε]{.greek-added} [με]{.greek-omitted} [μοι]{.greek-added} εν [πνευματι]{.greek-abbr} επ ορος μεγα και υψηλον και [εδειξεν]{.greek-omitted} [εδειξε]{.greek-added} μοι την [πολιν]{.greek-omitted} [πολην]{.greek-added} [την]{.greek-omitted} [μεγαλην]{.greek-omitted} την αγιαν [ιερουσαλημ]{.greek-abbr} καταβαινουσαν εκ του [ουρανου]{.greek-abbr} [απο]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted}[21:10]{.aside}

εχουσαν την δοξαν του θεου ο φωστηρ αυτης ομοιος λιθω [τιμιωτατω]{.greek-omitted} [τιμιω]{.greek-added} ως λιθω ιασπιδι κρυσταλλιζοντι[21:11]{.aside}

[εχουσα]{.greek-omitted} [εχου]{.greek-added} [τειχος]{.greek-omitted} [μεγα]{.greek-omitted} [και]{.greek-omitted} [υψηλον]{.greek-omitted} [εχουσα]{.greek-omitted} [πυλωνας]{.greek-omitted} [δωδεκα]{.greek-omitted} [και]{.greek-omitted} [επι]{.greek-omitted} [τοις]{.greek-omitted} [πυλωσιν]{.greek-omitted} [αγγελους]{.greek-omitted} [δωδεκα]{.greek-omitted} [και]{.greek-omitted} [ονοματα]{.greek-omitted} [επιγεγραμμενα]{.greek-omitted} [α]{.greek-omitted} [εστιν]{.greek-omitted} [ονοματα]{.greek-omitted} [των]{.greek-omitted} [δωδεκα]{.greek-omitted} [φυλων]{.greek-omitted} [των]{.greek-omitted} [υιων]{.greek-omitted} [ισραηλ]{.greek-omitted}[21:12]{.aside}

[εχουσα]{.greek-omitted} [σα]{.greek-added} τειχος μεγα και υψηλον εχουσα πυλωνας δωδεκα και επι τοις πυλωσιν αγγελους [δωδεκα]{.greek-omitted} [δεκα]{.greek-added} [δυο]{.greek-added} και ονοματα επιγεγραμμενα α εστιν ονοματα [επιγεγραμμενα]{.greek-added} των δωδεκα φυλων [των]{.greek-omitted} υιων [ισραηλ]{.greek-abbr}[21:12 | instance no. 2]{.aside}

απο ανατολων [πυλωνες]{.greek-added} [τρεις]{.greek-added} [και]{.greek-added} [απο]{.greek-added} [δυσμων]{.greek-added} πυλωνες τρεις και απο βορρα πυλωνες τρεις και απο [νοτου]{.greek-omitted} [νωτου]{.greek-added} πυλωνες τρεις [και]{.greek-omitted} [απο]{.greek-omitted} [δυσμων]{.greek-omitted} [πυλωνες]{.greek-omitted} [τρεις]{.greek-omitted}[21:13]{.aside}

και το τειχος της πολεως [εχον]{.greek-omitted} [εχων]{.greek-added} θεμελιους [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} και επ αυτων δωδεκα ονοματα των δωδεκα αποστολων του αρνιου[21:14]{.aside}

και ο λαλων μετ εμου [ειχεν]{.greek-omitted} [ειχε]{.greek-added} μετρον καλαμον χρυσουν ινα [μετρηση]{.greek-omitted} [μετριση]{.greek-added} την [πολιν]{.greek-omitted} [πολην]{.greek-added} και τους πυλωνας αυτης [και]{.greek-omitted} [το]{.greek-omitted} [τειχος]{.greek-omitted} [αυτης]{.greek-omitted}[21:15]{.aside}

και η πολις τετραγωνος κειται και το μηκος αυτης οσον το πλατος και [εμετρησεν]{.greek-omitted} [εμετρησε]{.greek-added} την πολιν τω καλαμω επι σταδιους [δωδεκα]{.greek-omitted} [δεκα]{.greek-added} [δυο]{.greek-added} χιλιαδων δωδεκα το μηκος [αυτης]{.greek-added} και το πλατος και το υψος αυτης ισα εστιν[21:16]{.aside}

και [εμετρησεν]{.greek-omitted} το τειχος αυτης [[ρμδ]{.greek-abbr}]{.greek-added} [εκατον]{.greek-omitted} [τεσσαρακοντα]{.greek-omitted} [τεσσαρων]{.greek-omitted} πηχων μετρον [ανθρωπου]{.greek-omitted} [ο]{.greek-omitted} [εστιν]{.greek-omitted} [αγγελου]{.greek-omitted}[21:17]{.aside}

[και]{.greek-omitted} [εμετρησεν]{.greek-omitted} [το]{.greek-omitted} [τειχος]{.greek-omitted} [αυτης]{.greek-omitted} [εκατον]{.greek-omitted} [τεσσαρακοντα]{.greek-omitted} [τεσσαρων]{.greek-omitted} [πηχων]{.greek-omitted} [μετρον]{.greek-omitted} [ανθρωπου]{.greek-abbr} ο εστιν αγγελου[21:17 | instance no. 2]{.aside}

και ην η ενδομησις του τειχους αυτης ιασπις και [η]{.greek-omitted} πολις χρυσιον καθαρον ομοιον [υελω]{.greek-omitted} [υαλω]{.greek-added} καθαρω[21:18]{.aside}

οι θεμελιοι του τειχους της πολεως παντι λιθω τιμιω [κεκοσμημενοι]{.greek-omitted} [κεκοσμημενη]{.greek-added} ο θεμελιος ο πρωτος ιασπις ο δευτερος σαπφειρος ο τριτος χαλκηδων ο τεταρτος σμαραγδος[21:19]{.aside}

ο πεμπτος σαρδονυξ ο εκτος σαρδιον ο εβδομος χρυσολιθος ο ογδοος βηρυλλος ο [ενατος]{.greek-omitted} [εννατος]{.greek-added} τοπαζιον ο δεκατος χρυσοπρασος ο ενδεκατος υακινθος ο δωδεκατος αμεθυσος[21:20]{.aside}

και οι δωδεκα πυλωνες δωδεκα μαργαριται ανα εις εκαστος των πυλωνων ην εξ ενος μαργαριτου και η πλατεια της πολεως [ως]{.greek-added} χρυσιον καθαρον [και]{.greek-added} ως υελος διαυγης[21:21]{.aside}

και ναον ουκ ειδον εν αυτη ο γαρ [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ ναος αυτης [εστιν]{.greek-omitted} [εστι]{.greek-added} και το αρνιον[21:22]{.aside}

και η πολις ου χρειαν [εχει]{.greek-omitted} [ειχε]{.greek-added} του ηλιου ουδε της σεληνης ινα φαινωσιν [αυτη]{.greek-omitted} [η]{.greek-omitted} [γαρ]{.greek-omitted} [δοξα]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [εφωτισεν]{.greek-omitted} [αυτην]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [λυχνος]{.greek-omitted} [αυτης]{.greek-omitted} [το]{.greek-omitted} [αρνιον]{.greek-omitted}[21:23]{.aside}

[και]{.greek-omitted} [αυτη]{.greek-added} [γαρ]{.greek-added} η [πολις]{.greek-omitted} [ου]{.greek-omitted} [χρειαν]{.greek-omitted} [εχει]{.greek-omitted} [του]{.greek-omitted} [ηλιου]{.greek-omitted} [ουδε]{.greek-omitted} [της]{.greek-omitted} [σεληνης]{.greek-omitted} [ινα]{.greek-omitted} [φαινωσιν]{.greek-omitted} [αυτη]{.greek-omitted} [η]{.greek-omitted} [γαρ]{.greek-omitted} δοξα του [θεου]{.greek-abbr} εφωτισεν αυτην και ο λυχνος αυτης το αρνιον[21:23 | instance no. 2]{.aside}

και [περιπατησουσιν]{.greek-omitted} [περιπατησουσι]{.greek-added} τα εθνη δια του φωτος αυτης και οι βασιλεις της γης φερουσιν αυτω [δοξαν]{.greek-omitted} [δοξα]{.greek-added} και [την]{.greek-added} τιμην των εθνων εις αυτην[21:24]{.aside}

και οι πυλωνες αυτης ου μη κλεισθωσιν ημερας νυξ γαρ ουκ [εσται]{.greek-omitted} [εστε]{.greek-added} εκει[21:25]{.aside}

και [οισουσιν]{.greek-omitted} [εισουσι]{.greek-added} την δοξαν και την τιμην των εθνων εις αυτην [ινα]{.greek-added} [εισελθωσι]{.greek-added}[21:26]{.aside}

και ου μη [εισελθη]{.greek-omitted} [εισελθι]{.greek-added} εις αυτην παν κοινον και [ποιουν]{.greek-omitted} [ο]{.greek-added} [ποιων]{.greek-added} βδελυγμα και ψευδος ει μη οι γεγραμμενοι εν τω βιβλιω της ζωης του αρνιου[21:27]{.aside}

### Chapter 22

και [εδειξεν]{.greek-omitted} [εδειξε]{.greek-added} μοι ποταμον [καθαρον]{.greek-omitted} [υδατος]{.greek-omitted} [υαατος]{.greek-added} ζωης [λαμπρον]{.greek-omitted} ως [κρυσταλλον]{.greek-omitted} [κρυσταλον]{.greek-added} [εκπορευομενον]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} και του αρνιου[22:1]{.aside}

εν μεσω της πλατειας αυτης και του ποταμου εντευθεν και εκειθεν ξυλον ζωης ποιουν καρπους δωδεκα κατα μηνα [αποδιδους]{.greek-added} εκαστον [αποδιδους]{.greek-omitted} τον καρπον αυτου και τα φυλλα του ξυλου εις [θεραπειαν]{.greek-omitted} [θεραπιαν]{.greek-added} των εθνων[22:2]{.aside}

και παν καταθεμα ουκ εσται ετι και ο θρονος του [θεου]{.greek-abbr} και του αρνιου εν αυτη [εσται]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [δουλοι]{.greek-omitted} [αυτου]{.greek-omitted} [λατρευσουσιν]{.greek-omitted} [αυτω]{.greek-omitted}[22:3]{.aside}

[και]{.greek-omitted} [παν]{.greek-omitted} [καταθεμα]{.greek-omitted} [ουκ]{.greek-omitted} [εσται]{.greek-omitted} [ετι]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [θρονος]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [και]{.greek-omitted} [του]{.greek-omitted} [αρνιου]{.greek-omitted} [εν]{.greek-omitted} [αυτη]{.greek-omitted} εσται και οι δουλοι [αυτου]{.greek-omitted} [αυτω]{.greek-added} λατρευσουσιν αυτω[22:3 | instance no. 2]{.aside}

και οψονται το προσωπον αυτου και το ονομα αυτου επι των μετ[ω]{.unclear}πων αυτων[22:4]{.aside}

και νυξ ουκ εσται [εκει]{.greek-omitted} και [ου]{.greek-added} [χρειαν]{.greek-omitted} [χρεια]{.greek-added} [ουκ]{.greek-omitted} [εχουσιν]{.greek-omitted} λυχνου [και]{.greek-omitted} φωτος [ηλιου]{.greek-omitted} οτι [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} φωτιει αυτους και βασιλευσουσιν εις τους αιωνας των αιωνων[22:5]{.aside}

και λεγει μοι ουτοι οι λογοι πιστοι και [αληθινοι]{.greek-omitted} [αληθηνοι]{.greek-added} και [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} των [πνευματων]{.greek-omitted} [των]{.greek-omitted} προφητων [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} τον αγγελον [αυτου]{.greek-omitted} [δειξαι]{.greek-omitted} [τοις]{.greek-omitted} [δουλοις]{.greek-omitted} αυτου α δει γενεσθαι εν ταχει[22:6]{.aside}

και ιδου ερχομαι ταχυ μακαριος ο τηρων τους λογους της προφητειας του βιβλιου τουτου[22:7]{.aside}

καγω ιωαννης ο ακουων και βλεπων ταυτα και οτε ηκουσα και [εβλεψα]{.greek-omitted} [ειδον]{.greek-added} επεσον προσκυνησαι εμπροσθεν των ποδων του αγγελου του [δεικνυοντος]{.greek-omitted} [δεικνυωντος]{.greek-added} [μοι]{.greek-omitted} [μου]{.greek-added} ταυτα[22:8]{.aside}

και λεγει μοι ορα μη συνδουλος σου ειμι και των αδελφων σου των προφητων [και]{.greek-omitted} των τηρουντων τους λογους του βιβλιου τουτου τω [θεω]{.greek-abbr} προσκυνησον[22:9]{.aside}

και λεγει μοι μη σφραγισης τους λογους της [προφητειας]{.greek-omitted} [προφητιας]{.greek-added} του βιβλιου τουτου ο καιρος γαρ [εγγυς]{.greek-omitted} [εγγεις]{.greek-added} εστιν[22:10]{.aside}

ο αδικων αδικησατω ετι και ο [αγιος]{.greek-added} [αγισθη]{.greek-added} [[αγιασθη]{.corr}]{.greek-added} [ετι]{.greek-added} [και]{.greek-added} [ο]{.greek-added} ρυπαρος [ρυπαρευθητω]{.greek-omitted} [ρυπαρευσατω]{.greek-added} ετι και ο δικαιος δικαιοσυνην ποιησατω ετι [και]{.greek-omitted} [ο]{.greek-omitted} [αγιος]{.greek-omitted} [αγιασθητω]{.greek-omitted} [ετι]{.greek-omitted}[22:11]{.aside}

ιδου ερχομαι ταχυ και ο μισθος μου μετ εμου αποδουναι εκαστω ως το εργον εσται αυτου[22:12]{.aside}

εγω το [αλφα]{.greek-omitted} [ἄλφα]{.greek-added} και το [ω]{.greek-omitted} [ὦ]{.greek-added} ο πρωτος και ο εσχατος η αρχη και το τελος[22:13]{.aside}

μακαριοι οι ποιουντες [τας]{.greek-omitted} [εντολας]{.greek-omitted} [αυτου]{.greek-omitted} [ινα]{.greek-omitted} [εσται]{.greek-omitted} [η]{.greek-omitted} [εξουσια]{.greek-omitted} [αυτων]{.greek-omitted} [επι]{.greek-omitted} το ξυλον της ζωης και τοις πυλωσιν εισελθωσιν εις την πολιν[22:14]{.aside}

εξω οι κυνες και οι φαρμακοι και οι πορνοι και οι [φονεις]{.greek-omitted} [φωνοις]{.greek-added} και οι ειδωλολατραι και πας φιλων και ποιων ψευδος[22:15]{.aside}

εγω [ιησους]{.greek-abbr} επεμψα τον αγγελον μου μαρτυρησαι υμιν ταυτα επι ταις εκκλησιαις εγω ειμι η ριζα [[δαυιδ]{.greek-abbr}]{.greek-added} και το γενος [δαυιδ]{.greek-omitted} ο αστηρ ο λαμπρος ο [πρωινος]{.greek-omitted} [προινος]{.greek-added}[22:16]{.aside}

και το [πνευμα]{.greek-abbr} και η νυμφη λεγουσιν ερχου και ο ακουων ειπατω [ερ]{.greek-added} [ερχου]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [διψων]{.greek-omitted} [ερχεσθω]{.greek-omitted} [ο]{.greek-omitted} [θελων]{.greek-omitted} [λαβετω]{.greek-omitted} [υδωρ]{.greek-omitted} [ζωης]{.greek-omitted} [δωρεαν]{.greek-omitted}[22:17]{.aside}

[και]{.greek-omitted} [το]{.greek-omitted} [πνευμα]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [νυμφη]{.greek-omitted} [λεγουσιν]{.greek-omitted} [ερχου]{.greek-omitted} [χου]{.greek-added} [και]{.greek-omitted} [ο]{.greek-omitted} [ακουων]{.greek-omitted} [ειπατω]{.greek-omitted} [ερχου]{.greek-omitted} και ο διψων ερχεσθω ο θελων λαβετω υδωρ ζωης δωρεαν[22:17 | instance no. 2]{.aside}

μαρτυρω εγω παντι τω ακουοντι τους λογους της [προφητειας]{.greek-omitted} [προφητηας]{.greek-added} [ταυτης]{.greek-added} [εκ]{.greek-added} του βιβλιου τουτου εαν τις επιθη επ αυτα επιθησαι [επ]{.greek-added} [αυτον]{.greek-added} ο [θεος]{.greek-abbr} [επ]{.greek-omitted} [αυτον]{.greek-omitted} τας πληγας τας γεγραμμενας εν τω βιβλιω [τουτω]{.greek-omitted} [τουτο]{.greek-added}[22:18]{.aside}

και εαν τις [αφελη]{.greek-omitted} [αφελει]{.greek-added} απο των λογων [της]{.greek-added} [προφητειας]{.greek-added} του βιβλιου [τουτο]{.greek-added} [της]{.greek-omitted} [προφητειας]{.greek-omitted} [ταυτης]{.greek-omitted} [αφελοι]{.greek-omitted} [αφελει]{.greek-added} ο [θεος]{.greek-abbr} το μερος αυτου απο του ξυλου της ζωης και εκ της πολεως της αγιας των γεγραμμενων εν τω βιβλιω [τουτω]{.greek-omitted} [τουτο]{.greek-added}[22:19]{.aside}

λεγει ο μαρτυρων ταυτα ναι ερχομαι ταχυ αμην ναι ερχου [κυριε]{.greek-abbr} [ιησου]{.greek-abbr} [[χριστε]{.greek-abbr}]{.greek-added}[22:20]{.aside}

η χαρις του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} [χριστου]{.greek-omitted} [[χριστε]{.greek-abbr}]{.greek-added} μετα παντων των αγιων αμην[22:21]{.aside}

