---
title: "Collation of Byz^RP^ vs 32681 (2681)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 2681 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=32681).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 2681                                   	| λογος                              	|
| 2681 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 2681 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 2681               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 2681                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 2681 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 2681                                                     	| [―]{.gap}                        	|
:::

## Revelation

### Chapter 1

αποκαλυψις [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} ην εδωκεν αυτω ο [θεος]{.greek-abbr} δειξαι τοις δουλοις αυτου α δει γενεσθαι εν ταχει και εσημανεν αποστειλας δια του αγγελου αυτου τω δουλω αυτου ιωαννη[1:1]{.aside}

ος [εμαρτυρησεν]{.greek-omitted} [εμαρτυρησε]{.greek-added} τον λογον του [θεου]{.greek-abbr} και την μαρτυριαν [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} οσα [ειδεν]{.greek-omitted} [ειδε]{.greek-added}[1:2]{.aside}

[και]{.greek-added} μακαριος ο αναγινωσκων και οι ακουοντες τους λογους της προφητειας και τηρουντες τα εν αυτη γεγραμμενα ο γαρ καιρος εγγυς[1:3]{.aside}

ιωαννης ταις επτα εκκλησιαις ταις εν τη ασια χαρις υμιν και ειρηνη απο [θεου]{.greek-abbr} [παντοκρατορος]{.greek-added} ο ων και ο ην και ο ερχομενος και απο των επτα [πνευματων]{.greek-abbr} [α]{.greek-omitted} [των]{.greek-added} ενωπιον του θρονου αυτου[1:4]{.aside}

και απο [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} ο μαρτυς ο πιστος ο πρωτοτοκος των νεκρων και ο αρχων των βασιλεων της γης τω [αγαπωντι]{.greek-omitted} [αγαποντι]{.greek-added} ημας και [λουσαντι]{.greek-omitted} [λοισαντι]{.greek-added} ημας απο των αμαρτιων ημων εν τω αιματι αυτου[1:5]{.aside}

και εποιησεν ημας βασιλειαν ιερεις τω [θεω]{.greek-abbr} και [πατρι]{.greek-abbr} αυτου αυτω η δοξα και το κρατος εις τους αιωνας των αιωνων αμην[1:6]{.aside}

ιδου ερχεται μετα των [νεφελων]{.greek-omitted} [και]{.greek-omitted} [οψεται]{.greek-omitted} [αυτον]{.greek-omitted} [πας]{.greek-omitted} [οφθαλμος]{.greek-omitted} [και]{.greek-omitted} [οιτινες]{.greek-omitted} [αυτον]{.greek-omitted} [εξεκεντησαν]{.greek-omitted} [και]{.greek-omitted} [κοψονται]{.greek-omitted} [επ]{.greek-omitted} [αυτον]{.greek-omitted} [πασαι]{.greek-omitted} [αι]{.greek-omitted} [φυλαι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [ναι]{.greek-omitted} [αμην]{.greek-omitted}[1:7]{.aside}

[ιδου]{.greek-omitted} [ερχεται]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} νεφελων και οψεται αυτον πας οφθαλμος και οιτινες αυτον εξεκεντησαν και κοψονται επ αυτον πασαι αι φυλαι της γης ναι αμην[1:7 | instance no. 2]{.aside}

εγω ειμι το [αλφα]{.greek-omitted} [ἄλφα]{.greek-added} και το [ω]{.greek-omitted} [ὤ]{.greek-added} λεγει [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο ων και ο ην και ο ερχομενος ο παντοκρατωρ[1:8]{.aside}

εγω ιωαννης ο αδελφος υμων και κοινωνος εν τη θλιψει και βασιλεια και υπομονη εν [χριστω]{.greek-abbr} [ιησου]{.greek-abbr} εγενομην εν τη νησω τη καλουμενη πατμω δια τον λογον του [θεου]{.greek-abbr} και δια την μαρτυριαν [ιησου]{.greek-abbr} [χριστου]{.greek-abbr}[1:9]{.aside}

εγενομην εν [πνευματι]{.greek-abbr} εν τη κυριακη ημερα και ηκουσα [φωνην]{.greek-omitted} [φωνη]{.greek-added} οπισω μου μεγαλην ως σαλπιγγος[1:10]{.aside}

λεγουσης [ο]{.greek-omitted} [βλεπεις]{.greek-omitted} [γραψον]{.greek-omitted} [εις]{.greek-omitted} [βιβλιον]{.greek-omitted} [και]{.greek-omitted} [πεμψον]{.greek-omitted} [ταις]{.greek-omitted} [επτα]{.greek-omitted} [εκκλησιαις]{.greek-omitted} [εις]{.greek-omitted} [εφεσον]{.greek-omitted} [και]{.greek-omitted} [εις]{.greek-omitted} [σμυρναν]{.greek-omitted} [και]{.greek-omitted} [εις]{.greek-omitted} [περγαμον]{.greek-omitted} [και]{.greek-omitted} [εις]{.greek-omitted} [θυατειρα]{.greek-omitted} [και]{.greek-omitted} [εις]{.greek-omitted} [σαρδεις]{.greek-omitted} [και]{.greek-omitted} [εις]{.greek-omitted} [φιλαδελφειαν]{.greek-omitted} [και]{.greek-omitted} [εις]{.greek-omitted} [λαοδικειαν]{.greek-omitted}[1:11]{.aside}

[λεγουσης]{.greek-omitted} ο βλεπεις γραψον εις βιβλιον και πεμψον ταις επτα [εκκλησιαις]{.greek-omitted} [εκκλησιας]{.greek-added} εις εφεσον και εις [σμυρναν]{.greek-omitted} [μυρναν]{.greek-added} και εις περγαμον και εις θυατειρα και εις σαρδεις και εις φιλαδελφειαν και εις λαοδικειαν[1:11 | instance no. 2]{.aside}

και εκει επεστρεψα βλεπειν την φωνην ητις ελαλει μετ εμου και επιστρεψας ειδον επτα λυχνιας χρυσας[1:12]{.aside}

και εν μεσω των επτα λυχνιων ομοιον υιω [ανθρωπου]{.greek-abbr} ενδεδυμενον ποδηρη και [περιεζωσμενον]{.greek-omitted} [περιεζωσμενος]{.greek-added} προς τοις μαστοις ζωνην χρυσην[1:13]{.aside}

η δε κεφαλη αυτου και αι τριχες λευκαι [και]{.greek-added} ως εριον λευκον ως χιων και οι οφθαλμοι αυτου ως φλοξ πυρος[1:14]{.aside}

και οι ποδες αυτου ομοιοι χαλκολιβανω ως εν καμινω πεπυρωμενοι και η φωνη αυτου ως φωνη υδατων πολλων[1:15]{.aside}

και εχων εν τη δεξια αυτου χειρι αστερας επτα και εκ του στοματος αυτου ρομφαια διστομος οξεια εκπορευομενη και η οψις αυτου ως ο ηλιος [φαινει]{.greek-omitted} [φαινεται]{.greek-added} εν τη δυναμει αυτου[1:16]{.aside}

και οτε ειδον αυτον [επεσα]{.greek-omitted} [επεσον]{.greek-added} προς τους ποδας αυτου ως νεκρος και [εθηκεν]{.greek-omitted} [εθηκε]{.greek-added} την δεξιαν αυτου επ εμε λεγων μ[η]{.unclear} φοβου εγω ειμι ο πρωτος [και]{.unclear} ο εσχατος[1:17]{.aside}

και ο ζων και εγεν[ομην]{.unclear} νεκρος και ιδου ζων ειμι εις [τους]{.unclear} αιωνας των αιωνων [αμην]{.unclear} [και]{.greek-omitted} [εχω]{.greek-omitted} [τας]{.greek-omitted} [κλεις]{.greek-omitted} [του]{.greek-omitted} [θανατου]{.greek-omitted} [και]{.greek-omitted} [του]{.greek-omitted} [αδου]{.greek-omitted}[1:18]{.aside}

[και]{.greek-omitted} [ο]{.greek-omitted} [ζων]{.greek-omitted} [και]{.greek-omitted} [εγενομην]{.greek-omitted} [νεκρος]{.greek-omitted} [και]{.greek-omitted} [ιδου]{.greek-omitted} [ζων]{.greek-omitted} [ειμι]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [αιωνας]{.greek-omitted} [των]{.greek-omitted} [αιωνων]{.greek-omitted} [αμην]{.greek-omitted} και εχω τας κλεις του θανατου και του αδου[1:18 | instance no. 2]{.aside}

γραψον ουν α ειδες και α [εισιν]{.greek-omitted} [εισι]{.greek-added} και α μελλει γινεσθαι μετα ταυτα[1:19]{.aside}

το μυστηριον των επτα αστερων ων ειδες επι της δεξιας μου και τας επτα λυχνιας τας χρυσας οι επτα αστερες αγγελοι των επτα εκκλησιων [εισιν]{.greek-omitted} [εισι]{.greek-added} και αι λυχνιαι αι επτα [αι]{.greek-added} επτα εκκλησιαι [εισιν]{.greek-omitted} [εισι]{.greek-added}[1:20]{.aside}

### Chapter 2

τω αγγελω της εν εφεσω εκκλησιας γραψον ταδε λεγει ο κρατων τους επτα αστερας εν τη δεξια αυτου ο περιπατων εν μεσω των επτα λυχνιων των χρυσων[2:1]{.aside}

οιδα [τον]{.greek-added} [κοπον]{.greek-added} [σου]{.greek-added} [και]{.greek-added} τα εργα σου και [τον]{.greek-omitted} [κοπον]{.greek-omitted} [σου]{.greek-omitted} [και]{.greek-omitted} την [υπομονην]{.greek-omitted} [σου]{.greek-omitted} [και]{.greek-omitted} [οτι]{.greek-omitted} [ου]{.greek-omitted} [δυνη]{.greek-omitted} [βαστασαι]{.greek-omitted} [κακους]{.greek-omitted} [και]{.greek-omitted} [επειρασας]{.greek-omitted} [τους]{.greek-omitted} [λεγοντας]{.greek-omitted} [εαυτους]{.greek-omitted} [αποστολους]{.greek-omitted} [ειναι]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [εισιν]{.greek-omitted} [και]{.greek-omitted} [ευρες]{.greek-omitted} [αυτους]{.greek-omitted} [ψευδεις]{.greek-omitted}[2:2]{.aside}

[οιδα]{.greek-omitted} [τα]{.greek-omitted} [εργα]{.greek-omitted} [σου]{.greek-omitted} [και]{.greek-omitted} [τον]{.greek-omitted} [κοπον]{.greek-omitted} [σου]{.greek-omitted} [και]{.greek-omitted} [την]{.greek-omitted} υπομονην σου και οτι ου δυνη βαστασαι κακους και επειρασας τους λεγοντας εαυτους αποστολους ειναι και ουκ [εισιν]{.greek-omitted} [εισι]{.greek-added} και ευρες αυτους ψευδεις[2:2 | instance no. 2]{.aside}

και υπομονην εχεις και [εβαστασας]{.greek-omitted} [ευαστασας]{.greek-added} δια το ονομα μου και ουκ [εκοπιασας]{.greek-omitted} [ἐκοπίασας]{.greek-added}[2:3]{.aside}

αλλα εχω κατα σου οτι την αγαπην σου την πρωτην αφηκας[2:4]{.aside}

μνημονευε ουν ποθεν πεπτωκας και μετανοησον και τα πρωτα εργα ποιησον ει δε μη ερχομαι σοι ταχυ και κινησω την λυχνιαν σου εκ του τοπου αυτης εαν μη μετανοησης[2:5]{.aside}

αλλα τουτο εχεις οτι μισεις τα εργα [των]{.greek-omitted} [τω]{.greek-added} νικολαιτων α καγω μισω[2:6]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις τω νικωντι δωσω αυτω φαγειν εκ του ξυλου της ζωης ο εστιν εν τω παραδεισω του [θεου]{.greek-abbr} μου[2:7]{.aside}

και τω αγγελω της εν σμυρνη εκκλησιας γραψον ταδε λεγει ο πρωτος και ο εσχατος ος εγενετο νεκρος και εζησεν[2:8]{.aside}

οιδα σου [τα]{.greek-omitted} [εργα]{.greek-omitted} [και]{.greek-omitted} την θλιψιν και την πτωχειαν αλλα πλουσιος ει και την βλασφημιαν εκ των λεγοντων ιουδαιους ειναι εαυτους και ουκ εισιν αλλα συναγωγη του σατανα[2:9]{.aside}

[μη]{.greek-added} [μηδεν]{.greek-omitted} [δεν]{.greek-added} φοβου α μελλεις παθειν ιδου δη μελλει [βαλειν]{.greek-omitted} [βαλεῖν]{.greek-added} ο διαβολος εξ υμων [εις]{.greek-omitted} [εκ]{.greek-added} [φυλακην]{.greek-omitted} [φυλακειν]{.greek-added} ινα [πει]{.greek-added} [πειρασθητε]{.greek-omitted} [και]{.greek-omitted} [εξετε]{.greek-omitted} [θλιψιν]{.greek-omitted} [ημερων]{.greek-omitted} [δεκα]{.greek-omitted} [γινου]{.greek-omitted} [πιστος]{.greek-omitted} [αχρι]{.greek-omitted} [θανατου]{.greek-omitted} [και]{.greek-omitted} [δωσω]{.greek-omitted} [σοι]{.greek-omitted} [τον]{.greek-omitted} [στεφανον]{.greek-omitted} [της]{.greek-omitted} [ζωης]{.greek-omitted}[2:10]{.aside}

[μηδεν]{.greek-omitted} [φοβου]{.greek-omitted} [α]{.greek-omitted} [μελλεις]{.greek-omitted} [παθειν]{.greek-omitted} [ιδου]{.greek-omitted} [δη]{.greek-omitted} [μελλει]{.greek-omitted} [βαλειν]{.greek-omitted} [ο]{.greek-omitted} [διαβολος]{.greek-omitted} [εξ]{.greek-omitted} [υμων]{.greek-omitted} [εις]{.greek-omitted} [φυλακην]{.greek-omitted} [ινα]{.greek-omitted} [πειρασθητε]{.greek-omitted} [ρασθητε]{.greek-added} και εξετε θλιψιν [ημερων]{.greek-omitted} [ημερας]{.greek-added} δεκα γινου πιστος αχρι θανατου και δωσω σοι τον στεφανον της ζωης[2:10 | instance no. 2]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις ο νικων ου μη αδικηθη εκ του θανατου του δευτερου[2:11]{.aside}

και τω αγγελω της εν περγαμω εκκλησιας γραψον ταδε λεγει ο εχων την ρομφαιαν την διστομον την οξειαν[2:12]{.aside}

οιδα τα εργα σου και που κατοικεις οπου ο θρονος του σατανα και κρατεις το ονομα μου και ουκ ηρνησω την πιστιν μου εν ταις ημεραις [εν]{.greek-omitted} αις [αντιπας]{.greek-omitted} [ἀντίπας]{.greek-added} ο μαρτυς μ[ο]{.unclear}υ ο πιστος ος απεκτανθη [π]{.unclear}αρ [υ]{.greek-added} [υμιν]{.greek-omitted} [οπου]{.greek-omitted} [ο]{.greek-omitted} [σατανας]{.greek-omitted} [κατοικει]{.greek-omitted}[2:13]{.aside}

[οιδα]{.greek-omitted} [τα]{.greek-omitted} [εργα]{.greek-omitted} [σου]{.greek-omitted} [και]{.greek-omitted} [που]{.greek-omitted} [κατοικεις]{.greek-omitted} [οπου]{.greek-omitted} [ο]{.greek-omitted} [θρονος]{.greek-omitted} [του]{.greek-omitted} [σατανα]{.greek-omitted} [και]{.greek-omitted} [κρατεις]{.greek-omitted} [το]{.greek-omitted} [ονομα]{.greek-omitted} [μου]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [ηρνησω]{.greek-omitted} [την]{.greek-omitted} [πιστιν]{.greek-omitted} [μου]{.greek-omitted} [εν]{.greek-omitted} [ταις]{.greek-omitted} [ημεραις]{.greek-omitted} [εν]{.greek-omitted} [αις]{.greek-omitted} [αντιπας]{.greek-omitted} [ο]{.greek-omitted} [μαρτυς]{.greek-omitted} [μου]{.greek-omitted} [ο]{.greek-omitted} [πιστος]{.greek-omitted} [ος]{.greek-omitted} [απεκτανθη]{.greek-omitted} [παρ]{.greek-omitted} [υμιν]{.greek-omitted} [μιν]{.greek-added} οπου ο σατανας κατοικει[2:13 | instance no. 2]{.aside}

αλλ εχω κατα σου ολιγα οτι εχεις εκει κρατουντας την διδαχην βαλααμ ος [εδιδαξεν]{.greek-omitted} [εδιδαξε]{.greek-added} τον βαλακ βαλειν σκανδαλον ενωπιον των υιων [ισραηλ]{.greek-abbr} και φαγειν ειδωλοθυτα και πορνευσαι[2:14]{.aside}

ουτως εχεις και συ κρατουντας την διδαχην των νικολαιτων ομοιως[2:15]{.aside}

μετανοησον ουν ει δε μη ερχομαι σοι ταχυ και πολεμησω μετ αυτων εν τη ρομφαια του στοματος μου[2:16]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις τω νικωντι δωσω αυτω του μαννα του κεκρυμμενου και δωσω αυτω [ψηφον]{.greek-omitted} [λευκην]{.greek-omitted} [και]{.greek-omitted} [επι]{.greek-omitted} [την]{.greek-omitted} [ψηφον]{.greek-omitted} [ονομα]{.greek-omitted} [καινον]{.greek-omitted} [γεγραμμενον]{.greek-omitted} [ο]{.greek-omitted} [ουδεις]{.greek-omitted} [οιδεν]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [ο]{.greek-omitted} [λαμβανων]{.greek-omitted}[2:17]{.aside}

[ο]{.greek-omitted} [εχων]{.greek-omitted} [ους]{.greek-omitted} [ακουσατω]{.greek-omitted} [τι]{.greek-omitted} [το]{.greek-omitted} [πνευμα]{.greek-omitted} [λεγει]{.greek-omitted} [ταις]{.greek-omitted} [εκκλησιαις]{.greek-omitted} [τω]{.greek-omitted} [νικωντι]{.greek-omitted} [δωσω]{.greek-omitted} [αυτω]{.greek-omitted} [του]{.greek-omitted} [μαννα]{.greek-omitted} [του]{.greek-omitted} [κεκρυμμενου]{.greek-omitted} [και]{.greek-omitted} [δωσω]{.greek-omitted} [αυτω]{.greek-omitted} ψηφον λευκην και επι την ψηφον ονομα καινον γεγραμμενον ο ουδεις οιδεν ει μη ο λαμβανων[2:17 | instance no. 2]{.aside}

και τω αγγελω της εν θυατειροις εκκλησιας γραψον ταδε λεγει ο υιος του [θεου]{.greek-abbr} ο εχων τους οφθαλμους αυτου ως φλογα πυρος και οι ποδες αυτου ομοιοι χαλκολιβανω[2:18]{.aside}

οιδα σου τα εργα και την αγαπην και την πιστιν και την διακονιαν και την υπομονην [σου]{.greek-omitted} και τα εργα σου τα εσχατα πλειονα των πρωτων[2:19]{.aside}

[αλλ]{.greek-omitted} [αλλα]{.greek-added} εχω κατα σου [οτι]{.greek-omitted} [ο]{.greek-added} [η]{.greek-added} [αφεις]{.greek-omitted} [αφιης]{.greek-added} την γυναικα σου ιεζαβελ η λεγει εαυτην προφητιν και διδασκει και πλανα τους εμους δουλους [πορνευσαι]{.greek-omitted} [και]{.greek-omitted} [φαγειν]{.greek-omitted} [ειδωλοθυτα]{.greek-omitted}[2:20]{.aside}

[αλλ]{.greek-omitted} [εχω]{.greek-omitted} [κατα]{.greek-omitted} [σου]{.greek-omitted} [οτι]{.greek-omitted} [αφεις]{.greek-omitted} [την]{.greek-omitted} [γυναικα]{.greek-omitted} [σου]{.greek-omitted} [ιεζαβελ]{.greek-omitted} [η]{.greek-omitted} [λεγει]{.greek-omitted} [εαυτην]{.greek-omitted} [προφητιν]{.greek-omitted} [και]{.greek-omitted} [διδασκει]{.greek-omitted} [και]{.greek-omitted} [πλανα]{.greek-omitted} [τους]{.greek-omitted} [εμους]{.greek-omitted} [δουλους]{.greek-omitted} πορνευσαι και φαγειν ειδωλοθυτα[2:20 | instance no. 2]{.aside}

και εδωκα αυτη χρονον ινα μετανοηση και ου θελει μετανοησαι εκ της πορνειας αυτης[2:21]{.aside}

ιδου [βαλλω]{.greek-omitted} [βαλλον]{.greek-added} αυτην εις κλινην και τους [μοιχευοντας]{.greek-omitted} [μοιχευσαντας]{.greek-added} μετ αυτης εις θλιψιν μεγαλην εαν μη μετανοησωσιν εκ των εργων αυτης[2:22]{.aside}

και τα τεκνα αυτης αποκτενω εν θανατω και γνωσονται πασαι αι εκκλησιαι οτι εγω ειμι ο ερευνων νεφρους και καρδιας και δωσω υμιν εκαστω κατα τα εργα υμων[2:23]{.aside}

υμιν δε λεγω τοις λοιποις τοις εν θυατειροις οσοι ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} την διδαχην ταυτην οιτινες ουκ εγνωσαν [τα]{.greek-omitted} [βαθεα]{.greek-omitted} [του]{.greek-omitted} [σατανα]{.greek-omitted} [ως]{.greek-omitted} [λεγουσιν]{.greek-omitted} [ου]{.greek-omitted} [βαλλω]{.greek-omitted} [εφ]{.greek-omitted} [υμας]{.greek-omitted} [αλλο]{.greek-omitted} [βαρος]{.greek-omitted}[2:24]{.aside}

[υμιν]{.greek-omitted} [δε]{.greek-omitted} [λεγω]{.greek-omitted} [τοις]{.greek-omitted} [λοιποις]{.greek-omitted} [τοις]{.greek-omitted} [εν]{.greek-omitted} [θυατειροις]{.greek-omitted} [οσοι]{.greek-omitted} [ουκ]{.greek-omitted} [εχουσιν]{.greek-omitted} [την]{.greek-omitted} [διδαχην]{.greek-omitted} [ταυτην]{.greek-omitted} [οιτινες]{.greek-omitted} [ουκ]{.greek-omitted} [εγνωσαν]{.greek-omitted} τα [βαθεα]{.greek-omitted} [βαθέα]{.greek-added} του σατανα ως λεγουσιν ου [βαλλω]{.greek-omitted} [βαλω]{.greek-added} εφ υμας αλλο βαρος[2:24 | instance no. 2]{.aside}

πλην ο εχετε κρατησατε [αχρι]{.greek-omitted} [εως]{.greek-added} ου αν ηξω[2:25]{.aside}

και ο νικων και ο τηρων αχρι τελους τα εργα μου δωσω αυτω εξουσιαν επι των εθνων[2:26]{.aside}

και ποιμανει αυτους εν ραβδω σιδηρα ως τα σκευη τα κεραμικα συντριβησεται [ως]{.greek-omitted} [καγω]{.greek-omitted} [ειληφα]{.greek-omitted} [παρα]{.greek-omitted} [του]{.greek-omitted} [πατρος]{.greek-omitted} [μου]{.greek-omitted}[2:27]{.aside}

[ως]{.greek-added} [καγω]{.greek-added} [ειληφα]{.greek-added} [παρα]{.greek-added} [του]{.greek-added} [[πατρος]{.greek-abbr}]{.greek-added} [μου]{.greek-added} και δωσω αυτω τον αστερα τον πρωινον[2:28]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[2:29]{.aside}

### Chapter 3

και τω αγγελω της εν σαρδεσιν εκκλησιας γραψον ταδε λεγει ο εχων τα επτα [πνευματα]{.greek-abbr} του [θεου]{.greek-abbr} και τους επτα [αστερας]{.greek-omitted} [οιδα]{.greek-omitted} [σου]{.greek-omitted} [τα]{.greek-omitted} [εργα]{.greek-omitted} [οτι]{.greek-omitted} [ονομα]{.greek-omitted} [εχεις]{.greek-omitted} [οτι]{.greek-omitted} [ζης]{.greek-omitted} [και]{.greek-omitted} [νεκρος]{.greek-omitted} [ει]{.greek-omitted}[3:1]{.aside}

[και]{.greek-omitted} [τω]{.greek-omitted} [αγγελω]{.greek-omitted} [της]{.greek-omitted} [εν]{.greek-omitted} [σαρδεσιν]{.greek-omitted} [εκκλησιας]{.greek-omitted} [γραψον]{.greek-omitted} [ταδε]{.greek-omitted} [λεγει]{.greek-omitted} [ο]{.greek-omitted} [εχων]{.greek-omitted} [τα]{.greek-omitted} [επτα]{.greek-omitted} [πνευματα]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [επτα]{.greek-omitted} αστερας οιδα σου τα εργα οτι ονομα εχεις [οτι]{.greek-omitted} [και]{.greek-added} ζης και νεκρος ει[3:1 | instance no. 2]{.aside}

γινου γρηγορων και [στηρισον]{.greek-omitted} [στηριξον]{.greek-added} τα λοιπα α εμελλες [αποβαλλειν]{.greek-omitted} [αποβαλειν]{.greek-added} ου γαρ ευρηκα σου τα εργα πεπληρωμενα ενωπιον του [θεου]{.greek-abbr} μου[3:2]{.aside}

[μνημονευε]{.greek-omitted} [μνημονεβε]{.greek-added} ουν πως ειληφας [και]{.greek-omitted} [ηκουσας]{.greek-omitted} [και]{.greek-omitted} [τηρει]{.greek-omitted} και μετανοησον εαν ουν μη γρηγορησης ηξω επι σε ως κλεπτης και ου μη [γνως]{.greek-omitted} [γνωση]{.greek-added} ποιαν ωραν ηξω επι σε[3:3]{.aside}

αλλ ολιγα [ονοματα]{.greek-added} εχεις [ονοματα]{.greek-omitted} εν σαρδεσιν α ουκ εμολυναν τα ιματια αυτων και [περιπατησουσιν]{.greek-omitted} [περιπατησουσι]{.greek-added} μετ εμου εν λευκοις οτι αξιοι εισιν[3:4]{.aside}

ο νικων ουτος [πε]{.greek-added} [περιβαλειται]{.greek-omitted} [εν]{.greek-omitted} [ιματιοις]{.greek-omitted} [λευκοις]{.greek-omitted} [και]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [εξαλειψω]{.greek-omitted} [το]{.greek-omitted} [ονομα]{.greek-omitted} [αυτου]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [βιβλου]{.greek-omitted} [της]{.greek-omitted} [ζωης]{.greek-omitted} [και]{.greek-omitted} [ομολογησω]{.greek-omitted} [το]{.greek-omitted} [ονομα]{.greek-omitted} [αυτου]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [πατρος]{.greek-omitted} [μου]{.greek-omitted} [και]{.greek-omitted} [ενωπιον]{.greek-omitted} [των]{.greek-omitted} [αγγελων]{.greek-omitted} [αυτου]{.greek-omitted}[3:5]{.aside}

[ο]{.greek-omitted} [νικων]{.greek-omitted} [ουτος]{.greek-omitted} [περιβαλειται]{.greek-omitted} [ριβαλειται]{.greek-added} εν ιματιοις λευκοις και ου μη εξαλειψω το ονομα αυτου εκ της βιβλου της ζωης και ομολογησω το ονομα αυτου ενωπιον του [πατρος]{.greek-abbr} μου και ενωπιον των αγγελων αυτου[3:5 | instance no. 2]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[3:6]{.aside}

και τω αγγελω της εν φιλαδελφεια εκκλησιας γραψον ταδε λεγει ο αγιος ο αληθινος ο εχων την κλειν του [δαυιδ]{.greek-abbr} ο ανοιγων και ουδεις κλεισει [και]{.greek-added} [κλειων]{.greek-added} [αυτην]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [ο]{.greek-omitted} [ανοιγων]{.greek-omitted} και ουδεις αν[ο]{.unclear}ιξει[3:7]{.aside}

οιδα σου τα εργα ιδου δεδωκα ενωπιον σου θυραν [α]{.unclear}νεωγμενην ην ουδεις δυναται κλεισαι αυτην οτι μικραν [ε]{.greek-added} [εχεις]{.greek-omitted} [δυναμιν]{.greek-omitted} [και]{.greek-omitted} [ετηρησας]{.greek-omitted} [μου]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [ηρνησω]{.greek-omitted} [το]{.greek-omitted} [ονομα]{.greek-omitted} [μου]{.greek-omitted}[3:8]{.aside}

[οιδα]{.greek-omitted} [σου]{.greek-omitted} [τα]{.greek-omitted} [εργα]{.greek-omitted} [ιδου]{.greek-omitted} [δεδωκα]{.greek-omitted} [ενωπιον]{.greek-omitted} [σου]{.greek-omitted} [θυραν]{.greek-omitted} [ανεωγμενην]{.greek-omitted} [ην]{.greek-omitted} [ουδεις]{.greek-omitted} [δυναται]{.greek-omitted} [κλεισαι]{.greek-omitted} [αυτην]{.greek-omitted} [οτι]{.greek-omitted} [μικραν]{.greek-omitted} [εχεις]{.greek-omitted} [χεις]{.greek-added} δυναμιν και ετηρησας μου τον λογον και ουκ ηρνησω το ονομα μου[3:8 | instance no. 2]{.aside}

ιδου διδωμι εκ της συναγωγης του σατανα των λεγοντων εαυτους ιουδαιους ειναι και ουκ εισιν αλλα ψευδονται ιδου ποιησω αυτους ινα [ηξωσιν]{.greek-omitted} [ηξωσι]{.greek-added} και προσκυνησωσιν ενωπιον των ποδων σου και γνωσιν οτι ηγαπησα σε[3:9]{.aside}

οτι ετηρησας τον λογον της υπομονης μου καγω σε τηρησω εκ της ωρας του πειρασμου της μελλουσης ερχεσθαι επι της οικουμενης ολης πειρασαι τους κατοικουντας επι της γης[3:10]{.aside}

ερχομαι ταχυ κρατει ο εχεις ινα μηδεις [λα]{.greek-added} [λαβη]{.greek-omitted} [τον]{.greek-omitted} [στεφανον]{.greek-omitted} [σου]{.greek-omitted}[3:11]{.aside}

[βη]{.greek-added} [ερχομαι]{.greek-omitted} [ταχυ]{.greek-omitted} [κρατει]{.greek-omitted} [ο]{.greek-omitted} [εχεις]{.greek-omitted} [ινα]{.greek-omitted} [μηδεις]{.greek-omitted} [λαβη]{.greek-omitted} τον στεφανον σου[3:11 | instance no. 2]{.aside}

ο νικων ποιησω αυτον στυλον εν τω ναω του [θεου]{.greek-abbr} μου και εξω ου μη εξελθη ετι και γραψω επ αυτον το ονομα του [θεου]{.greek-abbr} μου και το ονομα της πολεως του [θεου]{.greek-abbr} μου της καινης [ιερουσαλημ]{.greek-abbr} η καταβαινει [εκ]{.greek-omitted} [απο]{.greek-added} του [ουρανου]{.greek-abbr} απο του [θεου]{.greek-abbr} μου και το ονομα [μου]{.greek-omitted} το καινον[3:12]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[3:13]{.aside}

και τω αγγελω της εν λαοδικεια εκκλησιας γραψον ταδε λεγει ο αμην ο μαρτυς ο πιστος και αληθινος η αρχη της κτισεως του [θεου]{.greek-abbr}[3:14]{.aside}

οιδα σου τα εργα οτι ουτε ψυχρος ει ουτε ζεστος [οφελον]{.greek-omitted} [ψυχρος]{.greek-omitted} [ης]{.greek-omitted} [η]{.greek-omitted} [ζεστος]{.greek-omitted}[3:15]{.aside}

ουτως οτι [χλι]{.greek-added} [χλιαρος]{.greek-omitted} [ει]{.greek-omitted} [και]{.greek-omitted} [ου]{.greek-omitted} [ζεστος]{.greek-omitted} [ουτε]{.greek-omitted} [ψυχρος]{.greek-omitted} [μελλω]{.greek-omitted} [σε]{.greek-omitted} [εμεσαι]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [στοματος]{.greek-omitted} [μου]{.greek-omitted}[3:16]{.aside}

[αρος]{.greek-added} [ουτως]{.greek-omitted} [οτι]{.greek-omitted} [χλιαρος]{.greek-omitted} ει και [ου]{.greek-omitted} [ουτε]{.greek-added} ζεστος ουτε ψυχρος μελλω σε εμεσαι εκ του στοματος μου[3:16 | instance no. 2]{.aside}

οτι λεγεις πλουσιος ειμι και πεπλουτηκα και ουδενος χρειαν εχω και ουκ οιδας οτι συ ει ο ταλαιπωρος και ο ελεεινος και πτωχος και τυφλος και γυμνος[3:17]{.aside}

συμβουλευω σοι αγορασαι χρυσιον παρ εμου πεπυρωμενον εκ πυρος ινα πλουτησης και ιματια λευκα ινα περιβαλη και μη φανερωθη η αισχυνη της γυμνοτητος σου και κολλυριον ινα [εγχριση]{.greek-omitted} [εχρισης]{.greek-added} τους οφθαλμους [σου]{.greek-omitted} ινα βλεπης[3:18]{.aside}

εγω οσους εαν [φιλω]{.greek-omitted} [φιλων]{.greek-added} ελεγχω και παιδευω [ζηλωσον]{.greek-omitted} [ζηλεβε]{.greek-added} ουν και μετανοησον[3:19]{.aside}

ιδου [εστηκα]{.greek-omitted} [επι]{.greek-omitted} [την]{.greek-omitted} [θυραν]{.greek-omitted} [και]{.greek-omitted} [κρουω]{.greek-omitted} [εαν]{.greek-omitted} [τις]{.greek-omitted} [ακουση]{.greek-omitted} [της]{.greek-omitted} [φωνης]{.greek-omitted} [μου]{.greek-omitted} [και]{.greek-omitted} [ανοιξη]{.greek-omitted} [την]{.greek-omitted} [θυραν]{.greek-omitted} [και]{.greek-omitted} [εισελευσομαι]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [δειπνησω]{.greek-omitted} [μετ]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [αυτος]{.greek-omitted} [μετ]{.greek-omitted} [εμου]{.greek-omitted}[3:20]{.aside}

[ιδου]{.greek-omitted} εστηκα επι την θυραν και κρουω εαν τις ακουση της φωνης μου και ανοιξη την θυραν και εισελευσομαι προς αυτον και δειπνησω μετ αυτου και αυτος μετ εμου[3:20 | instance no. 2]{.aside}

ο νικων δωσω αυτω καθισαι μετ εμου εν τω [θρονω]{.greek-omitted} [θρονον]{.greek-added} μου ως καγω ενικησα και εκαθισα μετα του [πατρος]{.greek-abbr} μου εν τω [θρονω]{.greek-omitted} [θρονον]{.greek-added} αυτου[3:21]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[3:22]{.aside}

### Chapter 4

μετα ταυτα ειδον και ιδου θυρα ανεωγμενη εν τω [ουρανω]{.greek-abbr} και η φωνη η πρωτη ην ηκουσα ως σαλπιγγος λαλουσης μετ εμου λεγων αναβα ωδε και δειξω σοι α [δει]{.greek-omitted} [γενεσθαι]{.greek-omitted} [μετα]{.greek-omitted} [ταυτα]{.greek-omitted}[4:1]{.aside}

[μετα]{.greek-omitted} [ταυτα]{.greek-omitted} [ειδον]{.greek-omitted} [και]{.greek-omitted} [ιδου]{.greek-omitted} [θυρα]{.greek-omitted} [ανεωγμενη]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ουρανω]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [φωνη]{.greek-omitted} [η]{.greek-omitted} [πρωτη]{.greek-omitted} [ην]{.greek-omitted} [ηκουσα]{.greek-omitted} [ως]{.greek-omitted} [σαλπιγγος]{.greek-omitted} [λαλουσης]{.greek-omitted} [μετ]{.greek-omitted} [εμου]{.greek-omitted} [λεγων]{.greek-omitted} [αναβα]{.greek-omitted} [ωδε]{.greek-omitted} [και]{.greek-omitted} [δειξω]{.greek-omitted} [σοι]{.greek-omitted} [α]{.greek-omitted} δει γενεσθαι μετα ταυτα[4:1 | instance no. 2]{.aside}

και ευθεως εγενομην εν [πνευματι]{.greek-abbr} και ιδου θρονος εκειτο εν τω [ουρανω]{.greek-abbr} και επι τον θρονον καθημενος[4:2]{.aside}

ομοιος ορασει λιθω ιασπιδι και [σαρδιω]{.greek-omitted} [σαρδις]{.greek-added} [[σαρδιες]{.corr}]{.greek-added} και [ιρις]{.greek-omitted} [κυκλοθεν]{.greek-omitted} [ἶρες]{.greek-added} [κυκλω]{.greek-added} του θρονου [ομοιως]{.greek-omitted} [ομοιω]{.greek-added} [ως]{.greek-added} ορασις [σμαραγδινων]{.greek-omitted} [σμαραγδου]{.greek-added}[4:3]{.aside}

και κυκλοθεν του θρονου θρονοι εικοσι τεσσαρες και επι τους θρονους τους εικοσι τεσσαρας πρεσβυτερους καθημενους περιβεβλημενους εν ιματιοις λευκοις και επι τας κεφαλας αυτων στεφανους χρυσους[4:4]{.aside}

και εκ του θρονου [εκπορευονται]{.greek-omitted} [εκπορευον]{.greek-added} [αστραπαι]{.greek-omitted} [και]{.greek-omitted} [φωναι]{.greek-omitted} [και]{.greek-omitted} [βρονται]{.greek-omitted} [και]{.greek-omitted} [επτα]{.greek-omitted} [λαμπαδες]{.greek-omitted} [πυρος]{.greek-omitted} [καιομεναι]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [αυτου]{.greek-omitted} [αι]{.greek-omitted} [εισιν]{.greek-omitted} [επτα]{.greek-omitted} [πνευματα]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted}[4:5]{.aside}

[ται]{.greek-added} [και]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [εκπορευονται]{.greek-omitted} αστραπαι και φωναι και βρονται και επτα λαμπαδες πυρος καιομεναι ενωπιον του θρονου αυτου αι εισιν επτα [πνευματα]{.greek-abbr} [του]{.greek-omitted} [θεου]{.greek-omitted}[4:5 | instance no. 2]{.aside}

και ενωπιον του θρονου ως θαλασσα [υαλινη]{.greek-omitted} [υελινη]{.greek-added} [ομοιω]{.greek-added} [ομοια]{.corr} [κρυσταλλω]{.greek-omitted} [κρυσταλων]{.greek-added} και εν μεσω του θρονου και κυκλω του θρονου τεσσαρα ζωα γεμοντα οφθαλμων εμπροσθεν και οπισθεν[4:6]{.aside}

και το ζωον το πρωτον ομοιον λεοντι και το [ζωον]{.greek-added} [το]{.greek-added} δευτερον [ζωον]{.greek-omitted} ομοιον μοσχω και το τριτον ζωον [προσωπον]{.greek-added} εχον [προσωπον]{.greek-omitted} [ανθρωπου]{.greek-abbr} και το τεταρτον [ζωον]{.greek-omitted} ομοιον αετω [πετομενω]{.greek-omitted} [πετομενων]{.greek-added}[4:7]{.aside}

και [τα]{.greek-omitted} τεσσαρα ζωα εν [καθ]{.greek-omitted} [καθεν]{.greek-added} [εν]{.greek-omitted} εχον ανα πτερυγας [εξ]{.greek-omitted} [κυκλοθεν]{.greek-omitted} [και]{.greek-omitted} [εσωθεν]{.greek-omitted} [γεμουσιν]{.greek-omitted} [οφθαλμων]{.greek-omitted} [και]{.greek-omitted} [αναπαυσιν]{.greek-omitted} [ουκ]{.greek-omitted} [εχουσιν]{.greek-omitted} [ημερας]{.greek-omitted} [και]{.greek-omitted} [νυκτος]{.greek-omitted} [λεγοντες]{.greek-omitted} [αγιος]{.greek-omitted} [αγιος]{.greek-omitted} [αγιος]{.greek-omitted} [κυριος]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [ο]{.greek-omitted} [παντοκρατωρ]{.greek-omitted} [ο]{.greek-omitted} [ην]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [ων]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [ερχομενος]{.greek-omitted}[4:8]{.aside}

[και]{.greek-omitted} [τα]{.greek-omitted} [τεσσαρα]{.greek-omitted} [ζωα]{.greek-omitted} [εν]{.greek-omitted} [καθ]{.greek-omitted} [εν]{.greek-omitted} [εχον]{.greek-omitted} [ανα]{.greek-omitted} [πτερυγας]{.greek-omitted} εξ κυκλοθεν και εσωθεν γεμουσιν οφθαλμων και αναπαυσιν ουκ εχουσιν ημερας και νυκτος λεγοντες αγιος αγιος αγιος [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ ο ην και ο ων και ο ερχομενος[4:8 | instance no. 2]{.aside}

και οταν [δωσιν]{.greek-omitted} [δωσουσι]{.greek-added} τα ζωα δοξαν και τιμην και ευχαριστιαν τω καθημενω επι του θρονου τω ζωντι εις τους αιωνας των αιωνων[4:9]{.aside}

πεσουνται οι εικοσι τεσσαρες πρεσβυτεροι ενωπιον του καθημενου επι του θρονου και [προσκυνησουσιν]{.greek-omitted} [προσκηνησουσι]{.greek-added} τω ζωντι εις τους αιωνας των αιωνων και [βαλουσιν]{.greek-omitted} [βαλοῦσι]{.greek-added} τους στεφανους αυτων ενωπιον [του]{.greek-omitted} [θρονου]{.greek-omitted} [λεγοντες]{.greek-omitted}[4:10]{.aside}

[πεσουνται]{.greek-omitted} [οι]{.greek-omitted} [εικοσι]{.greek-omitted} [τεσσαρες]{.greek-omitted} [πρεσβυτεροι]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [καθημενου]{.greek-omitted} [επι]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [και]{.greek-omitted} [προσκυνησουσιν]{.greek-omitted} [τω]{.greek-omitted} [ζωντι]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [αιωνας]{.greek-omitted} [των]{.greek-omitted} [αιωνων]{.greek-omitted} [και]{.greek-omitted} [βαλουσιν]{.greek-omitted} [τους]{.greek-omitted} [στεφανους]{.greek-omitted} [αυτων]{.greek-omitted} [ενωπιον]{.greek-omitted} του θρονου λεγοντες[4:10 | instance no. 2]{.aside}

αξιος ει [[κυριε]{.greek-abbr}]{.greek-added} [ο]{.greek-omitted} [κυριος]{.greek-omitted} [και]{.greek-omitted} ο [θεος]{.greek-abbr} ημων [ο]{.greek-omitted} [αγιος]{.greek-omitted} λαβειν την δοξαν και την τιμην και την δυναμιν οτι συ εκτισας παντα και δια το θελημα σου [ησαν]{.greek-omitted} [εισι]{.greek-added} και εκτισθησαν[4:11]{.aside}

### Chapter 5

και ειδον επι την δεξιαν του καθημενου επι του θρονου βιβλιον γεγραμμενον εσωθεν και εξωθεν κατεσφραγισμενον σφραγισιν επτα[5:1]{.aside}

και ειδον αγγελον ισχυρον κηρυσσοντα [εν]{.greek-omitted} φωνη μεγαλη [τις]{.greek-omitted} [τίς]{.greek-added} αξιος εστιν ανοιξαι το βιβλιον και λυσαι τας σφραγιδας αυτου[5:2]{.aside}

και ουδεις [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} εν τω [ουρανω]{.greek-abbr} [ανω]{.greek-omitted} [ουτε]{.greek-omitted} [ουδε]{.greek-added} επι της γης [ουτε]{.greek-omitted} [ουδε]{.greek-added} υποκατω της γης ανοιξαι το βιβλιον [ουτε]{.greek-omitted} [βλεπειν]{.greek-omitted} [αυτο]{.greek-omitted}[5:3]{.aside}

[και]{.greek-omitted} [ουδεις]{.greek-omitted} [εδυνατο]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ουρανω]{.greek-omitted} [ανω]{.greek-omitted} [ουτε]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [ουτε]{.greek-omitted} [υποκατω]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [ανοιξαι]{.greek-omitted} [το]{.greek-omitted} [βιβλιον]{.greek-omitted} ουτε βλεπειν αυτο[5:3 | instance no. 2]{.aside}

και εγω εκλαιον πολυ οτι ουδεις αξιος ευρεθη ανοιξαι το βιβλιον ουτε βλεπειν αυτο[5:4]{.aside}

και εις εκ των πρεσβυτερων λεγει μοι μη κλαιε ιδου ενικησεν ο λεων ο εκ της φυλης ιουδα η ριζα [δαυιδ]{.greek-abbr} ο ανοιγων το βιβλιον και τας επτα σφραγιδας αυτου[5:5]{.aside}

και ειδον εν μεσω του θρονου και των τεσσαρων ζωων και εν μεσω των πρεσβυτερων αρνιον εστηκος ως εσφαγμενον [ε]{.unclear}χ[ο]{.unclear}ν κερατα επτα και οφθαλμους επτα [α]{.greek-omitted} [ατινα]{.greek-added} [εισιν]{.greek-omitted} [εισι]{.greek-added} τα επτα [πνευματα]{.greek-abbr} του [θεου]{.greek-abbr} αποστελλομενα εις πασαν την γην[5:6]{.aside}

και [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και ειληφεν εκ της δεξιας του καθημενου επι του θρονου[5:7]{.aside}

και οτε [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added} το βιβλιον τα τεσσαρα ζωα και οι εικοσι τεσσαρες πρεσβυτεροι επεσον ενωπιον του αρνιου εχοντες εκαστος κιθαραν και φιαλας χρυσας γεμουσας θυμιαματων αι εισιν [[αι]{.unclear}]{.greek-added} προσευχαι των αγιων[5:8]{.aside}

και αδ[ου]{.unclear}σιν ωδην καινην λεγοντες αξ[ιο]{.unclear}ς ει λαβειν το βιβλιον και α[ν]{.unclear}οιξαι τας σφραγιδας αυτ[ου]{.unclear} [οτι]{.unclear} εσφαγης και ηγορα[σας]{.unclear} [τω]{.unclear} [[θεω]{.greek-abbr}]{.unclear} ημας εν τω [αιμ]{.unclear}ατι σου [εκ]{.unclear} [πα]{.unclear}σης φυλης και γλωσσ[ης]{.unclear} [και]{.unclear} [λαου]{.unclear} και εθνους[5:9]{.aside}

και εποιησ[ας]{.unclear} [αυτους]{.unclear} [τω]{.greek-omitted} [θεω]{.greek-omitted} [ημων]{.greek-omitted} [βασιλεις]{.greek-omitted} [και]{.greek-omitted} [ιερεις]{.greek-omitted} [και]{.greek-omitted} [βασιλευσουσιν]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted}[5:10]{.aside}

[και]{.greek-omitted} [εποιησας]{.greek-omitted} [αυτους]{.greek-omitted} τω [θεω]{.greek-abbr} ημων βασιλεις και ιερεις και βασιλευσουσιν επι της γης[5:10 | instance no. 2]{.aside}

και ειδον και ηκουσα ως φωνην αγγελων πολλων κυκλω του θρονου [αυτου]{.greek-added} και των ζωων και των πρεσβυτερων και ην ο αριθμος αυτων μυριαδες μυριαδων και χιλιαδες χιλιαδων[5:11]{.aside}

λεγοντες φωνη μεγαλη αξιον [εστιν]{.greek-omitted} [εστι]{.greek-added} το αρνιον το εσφαγμενον λαβειν την δυναμιν και τον πλουτον και σοφιαν και ισχυν και τιμην και δοξαν και ευλογιαν[5:12]{.aside}

και παν κτισμα ο [εστιν]{.greek-added} εν τω [ουρανω]{.greek-abbr} και επι της γης και [υποκατω]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [και]{.greek-omitted} επι της θαλασσης [εστιν]{.greek-omitted} και τα εν αυτοις [και]{.greek-added} παντας [ηκουσα]{.greek-omitted} [ηκου]{.greek-added} [λεγοντας]{.greek-omitted} [τω]{.greek-omitted} [καθημενω]{.greek-omitted} [επι]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [και]{.greek-omitted} [τω]{.greek-omitted} [αρνιω]{.greek-omitted} [η]{.greek-omitted} [ευλογια]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [τιμη]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [δοξα]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [κρατος]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [αιωνας]{.greek-omitted} [των]{.greek-omitted} [αιωνων]{.greek-omitted} [αμην]{.greek-omitted}[5:13]{.aside}

[σα]{.greek-added} [και]{.greek-omitted} [παν]{.greek-omitted} [κτισμα]{.greek-omitted} [ο]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ουρανω]{.greek-omitted} [και]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [και]{.greek-omitted} [υποκατω]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [και]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [θαλασσης]{.greek-omitted} [εστιν]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} [εν]{.greek-omitted} [αυτοις]{.greek-omitted} [παντας]{.greek-omitted} [ηκουσα]{.greek-omitted} λεγοντας [των]{.greek-added} [καθημενων]{.greek-added} [τω]{.corr} [καθημενω]{.corr} επι του θρονου και τω [αρνιω]{.greek-omitted} [αρνιον]{.greek-added} η ευλογια και η τιμη και η δοξα και το κρατος εις τους αιωνας των αιωνων αμην[5:13 | instance no. 2]{.aside}

και τα τεσσαρα ζωα [λεγοντα]{.greek-omitted} [ελεγον]{.greek-added} το αμην και οι πρεσβυτεροι επεσον και προσεκυνησαν[5:14]{.aside}

### Chapter 6

και ειδον οτι [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} το αρνιον μιαν εκ των επτα σφραγιδων και ηκουσα ενος εκ των τεσσαρων ζωων λεγοντος ως φων[η]{.unclear} βροντης ερχου [και]{.greek-omitted} [ιδε]{.greek-omitted}[6:1]{.aside}

[και]{.greek-added} [ειδον]{.greek-added} και ιδου ιππος λευκος και ο καθημενος επ αυτον εχων τοξον και εδοθη αυτω στεφανος και [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} νικων και ινα νικηση[6:2]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την [δευ]{.greek-added} [δευτεραν]{.greek-omitted} [σφραγιδα]{.greek-omitted} [ηκουσα]{.greek-omitted} [του]{.greek-omitted} [δευτερου]{.greek-omitted} [ζωου]{.greek-omitted} [λεγοντος]{.greek-omitted} [ερχου]{.greek-omitted}[6:3]{.aside}

[και]{.greek-omitted} [οτε]{.greek-omitted} [ηνοιξεν]{.greek-omitted} [την]{.greek-omitted} [δευτεραν]{.greek-omitted} [τεραν]{.greek-added} σφραγιδα ηκουσα του δευτερου ζωου λεγοντος ερχου[6:3 | instance no. 2]{.aside}

και εξηλθεν αλλος ιππος [πυρος]{.greek-omitted} [πυρρος]{.greek-added} και τω καθημενω επ αυτον εδοθη αυτω λαβειν την ειρηνην εκ της γης ινα αλληλους [σφαξωσιν]{.greek-omitted} [σφαξωσι]{.greek-added} και εδοθη αυτω μαχαιρα μεγαλη[6:4]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την σφραγιδα την τριτην ηκουσα του τριτου ζωου λεγοντος ερχου και [ιδε]{.greek-omitted} [ειδον]{.greek-added} και ιδου ιππος μελας και ο καθημενος επ αυτον εχων ζυγον εν τη χειρι αυτου[6:5]{.aside}

και ηκουσα φωνην εν μεσω των τεσσαρων ζωων λεγουσαν χοινιξ σιτου δηναριου και τρεις χοινικες κριθης δηναριου και το ελαιον [και]{.greek-omitted} [τον]{.greek-omitted} [οινον]{.greek-omitted} [μη]{.greek-omitted} [αδικησης]{.greek-omitted}[6:6]{.aside}

[και]{.greek-omitted} [ηκουσα]{.greek-omitted} [φωνην]{.greek-omitted} [εν]{.greek-omitted} [μεσω]{.greek-omitted} [των]{.greek-omitted} [τεσσαρων]{.greek-omitted} [ζωων]{.greek-omitted} [λεγουσαν]{.greek-omitted} [χοινιξ]{.greek-omitted} [σιτου]{.greek-omitted} [δηναριου]{.greek-omitted} [και]{.greek-omitted} [τρεις]{.greek-omitted} [χοινικες]{.greek-omitted} [κριθης]{.greek-omitted} [δηναριου]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [ελαιον]{.greek-omitted} και τον οινον μη αδικησης[6:6 | instance no. 2]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την σφραγιδα την τεταρτην ηκουσα του τεταρτου ζωου λεγοντος ερχου [και]{.greek-omitted} [ιδε]{.greek-omitted}[6:7]{.aside}

[και]{.greek-added} [ειδον]{.greek-added} και ιδου ιππος χλωρος και ο καθημενος επανω αυτου ονομα αυτω ο θανατος και ο αδης ηκολουθει αυτω και εδοθη αυτω εξουσια επι το τεταρτον της γης αποκτειναι εν ρομφαια και εν λιμω και εν θανατω και υπο των θηριων της γης[6:8]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την πεμπτην σφραγιδα ειδον υποκατω του θυσιαστηριου τας ψυχας των εσφαγμενων δια τον λογον του [θεου]{.greek-abbr} και δια την μαρτυριαν [του]{.greek-omitted} [αρνιου]{.greek-omitted} ην ειχον[6:9]{.aside}

και [ε]{.greek-added} [εκραξαν]{.greek-omitted} [φωνη]{.greek-omitted} [μεγαλη]{.greek-omitted} [λεγοντες]{.greek-omitted} [εως]{.greek-omitted} [ποτε]{.greek-omitted} [ο]{.greek-omitted} [δεσποτης]{.greek-omitted} [ο]{.greek-omitted} [αγιος]{.greek-omitted} [και]{.greek-omitted} [αληθινος]{.greek-omitted} [ου]{.greek-omitted} [κρινεις]{.greek-omitted} [και]{.greek-omitted} [εκδικεις]{.greek-omitted} [το]{.greek-omitted} [αιμα]{.greek-omitted} [ημων]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [κατοικουντων]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted}[6:10]{.aside}

[κρα[ζ]{.unclear}ον]{.greek-added} [και]{.greek-omitted} [εκραξαν]{.greek-omitted} φωνη μεγαλη λεγοντες εως ποτε ο δεσποτης ο αγιος και αληθινος ου κρινεις και εκδικεις το αιμα ημων εκ των κατοικουντων επι της γης[6:10 | instance no. 2]{.aside}

και εδοθη αυτοις εκαστω στολη λευκη και [ερρεθη]{.greek-omitted} [ευρεθη]{.greek-added} αυτοις ινα αναπαυσωνται ετι [μικρον]{.greek-added} χρονον εως [πληρωσωσιν]{.greek-omitted} [πληρωσουσι]{.greek-added} και οι συνδουλοι αυτων και οι αδελφοι αυτων και οι μελλοντες αποκτενεσθαι ως και αυτοι[6:11]{.aside}

και ειδον οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την σφραγιδα την εκτην και σεισμος μεγας εγενετο και ο ηλιος μελας εγενετο ως [σακκος]{.greek-omitted} [τριχινος]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [σεληνη]{.greek-omitted} [ολη]{.greek-omitted} [εγενετο]{.greek-omitted} [ως]{.greek-omitted} αιμα[6:12]{.aside}

και οι αστερες του [ουρανου]{.greek-abbr} επεσον [εις]{.greek-omitted} [επι]{.greek-added} την γην ως συκη βαλουσα [τους]{.greek-omitted} [ολυνθους]{.greek-omitted} [αυτης]{.greek-omitted} [υπο]{.greek-omitted} [ανεμου]{.greek-omitted} [μεγαλου]{.greek-omitted} [σειομενη]{.greek-omitted}[6:13]{.aside}

[και]{.greek-omitted} [οι]{.greek-omitted} [αστερες]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [επεσον]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [γην]{.greek-omitted} [ως]{.greek-omitted} [συκη]{.greek-omitted} [βαλουσα]{.greek-omitted} τους ολυνθους αυτης [υ]{.unclear}πο ανεμου μεγαλου σειομενη[6:13 | instance no. 2]{.aside}

και ο [ουρανος]{.greek-abbr} απεχωρισθη ως βιβλιον [ελισσομενον]{.greek-omitted} [ελισσομενος]{.greek-added} και παν ορος και νησος εκ των τοπων αυτων εκινηθησαν[6:14]{.aside}

και οι βασιλεις της γης και οι μεγιστανες και οι χιλιαρχοι και οι πλουσιοι και [οι]{.greek-omitted} ισχυροι και πας δουλος και ελευθερος εκρυψαν εαυτους εις τα σπηλαια και εις τας πετρας των ορεων[6:15]{.aside}

και [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} τοις [ορεσιν]{.greek-omitted} [ορεσι]{.greek-added} και ταις [πετραις]{.greek-omitted} [πετρες]{.greek-added} πεσετε εφ ημας και κρυψατε ημας απο προσωπου του καθημενου επι του θρονου και απο της οργης του αρνιου[6:16]{.aside}

οτι ηλθεν η ημερα η μεγαλη της οργης αυτου και τις δυναται [σταθηναι]{.greek-omitted}[6:17]{.aside}

[οτι]{.greek-omitted} [ηλθεν]{.greek-omitted} [η]{.greek-omitted} [ημερα]{.greek-omitted} [η]{.greek-omitted} [μεγαλη]{.greek-omitted} [της]{.greek-omitted} [οργης]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [τις]{.greek-omitted} [δυναται]{.greek-omitted} σταθηναι[6:17 | instance no. 2]{.aside}

### Chapter 7

και μετα [τουτο]{.greek-omitted} [ταυτα]{.greek-added} ειδον τεσσαρας αγγελους εστωτας επι τας τεσσαρας γωνιας της γης κρατουντας τους τεσσαρας ανεμους της γης ινα μη [πνεη]{.greek-omitted} [πνευση]{.greek-added} ανεμος επι της γης μητε επι της θαλασσης μητε επι τι δενδρον[7:1]{.aside}

και ειδον αλλον αγγελον αναβαινοντα απο ανατολης ηλιου εχοντα σφραγιδα [θεου]{.greek-abbr} ζωντος και [εκραξεν]{.greek-omitted} [εκραξε]{.greek-added} φωνη μεγαλη τοις τεσσαρσιν αγγελοις οις εδοθη αυτοις αδικησαι την γην και την θαλασσαν[7:2]{.aside}

λεγων μη αδικησητε την γην μητε την θαλασσαν μητε τα δενδρα [αχρι]{.greek-omitted} [αχρις]{.greek-added} ου σφραγισωμεν τους δουλους του [θεου]{.greek-abbr} [ημων]{.greek-omitted} επι των μετωπων [αυτων]{.greek-omitted}[7:3]{.aside}

[λεγων]{.greek-omitted} [μη]{.greek-omitted} [αδικησητε]{.greek-omitted} [την]{.greek-omitted} [γην]{.greek-omitted} [μητε]{.greek-omitted} [την]{.greek-omitted} [θαλασσαν]{.greek-omitted} [μητε]{.greek-omitted} [τα]{.greek-omitted} [δενδρα]{.greek-omitted} [αχρι]{.greek-omitted} [ου]{.greek-omitted} [σφραγισωμεν]{.greek-omitted} [τους]{.greek-omitted} [δουλους]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [ημων]{.greek-omitted} [επι]{.greek-omitted} [των]{.greek-omitted} [μετωπων]{.greek-omitted} αυτων[7:3 | instance no. 2]{.aside}

και ηκουσα τον αριθμον των εσφραγισμενων εκατον και τεσσαρακοντα τεσσαρες χιλιαδες [εσφραγισμενων]{.greek-omitted} [εσφραγισμενοι]{.greek-added} εκ πασης φυλης υιων [ισραηλ]{.greek-abbr}[7:4]{.aside}

εκ φυλης ιουδα δωδεκα χιλιαδες [εσφραγισμεναι]{.greek-omitted} [εσφραγισμενοι]{.greek-added} εκ φυλης ρουβιμ δωδεκα χιλιαδες εκ φυλης γαδ δωδεκα χιλιαδες[7:5]{.aside}

εκ φυλης ασηρ δωδεκα χιλιαδες εκ φυλης νεφθαλειμ δωδεκα χιλιαδες εκ φυλης μανασση δωδεκα χιλιαδες[7:6]{.aside}

εκ φυλης συμεων δωδεκα χιλιαδες εκ φυλης λευι δωδεκα χιλιαδες εκ φυλης ισαχαρ δωδεκα χιλιαδες[7:7]{.aside}

εκ φυλης ζαβουλων δωδεκα χιλιαδες εκ φυλης ιωσηφ δωδεκα [χιλιαδες]{.greek-omitted} [εκ]{.greek-omitted} [φυλης]{.greek-omitted} [βενιαμιν]{.greek-omitted} [δωδεκα]{.greek-omitted} [χιλιαδες]{.greek-omitted} [εσφραγισμεναι]{.greek-omitted}[7:8]{.aside}

[εκ]{.greek-omitted} [φυλης]{.greek-omitted} [ζαβουλων]{.greek-omitted} [δωδεκα]{.greek-omitted} [χιλιαδες]{.greek-omitted} [εκ]{.greek-omitted} [φυλης]{.greek-omitted} [ιωσηφ]{.greek-omitted} [δωδεκα]{.greek-omitted} χιλιαδες εκ φυλης βενιαμιν δωδεκα χιλιαδες [εσφραγισμεναι]{.greek-omitted} [εσφραγισμενοι]{.greek-added}[7:8 | instance no. 2]{.aside}

μετα ταυτα ειδον και ιδου οχλος πολυς ον [ουδεις]{.greek-added} αριθμησαι [ουδεις]{.greek-omitted} [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} εκ παντος [γενους]{.greek-added} εθνους και φυλων και λαων και γλωσσων εστωτας ενωπιον του θρονου και ενωπιον του αρνιου περιβεβλημενους στολας λευκας και φοινικας εν ταις χερσιν αυτων[7:9]{.aside}

και [κραζουσιν]{.greek-omitted} [κραζουσι]{.greek-added} φωνη μεγαλη λεγοντες η [σωτηρια]{.greek-abbr} τω [θεω]{.greek-abbr} ημων τω καθημενω επι [τω]{.greek-omitted} [θρονω]{.greek-omitted} [του]{.greek-added} [θρονου]{.greek-added} και τω αρνιω[7:10]{.aside}

και παντες οι αγγελοι ειστηκεισαν κυκλω του θρονου και των πρεσβυτερων και των τεσσαρων ζωων και [επε]{.greek-added} [επεσον]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [επι]{.greek-omitted} [τα]{.greek-omitted} [προσωπα]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [προσεκυνησαν]{.greek-omitted} [τω]{.greek-omitted} [θεω]{.greek-omitted}[7:11]{.aside}

[σον]{.greek-added} [και]{.greek-omitted} [παντες]{.greek-omitted} [οι]{.greek-omitted} [αγγελοι]{.greek-omitted} [ειστηκεισαν]{.greek-omitted} [κυκλω]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [και]{.greek-omitted} [των]{.greek-omitted} [πρεσβυτερων]{.greek-omitted} [και]{.greek-omitted} [των]{.greek-omitted} [τεσσαρων]{.greek-omitted} [ζωων]{.greek-omitted} [και]{.greek-omitted} [επεσον]{.greek-omitted} ενωπιον του θρονου [αυτου]{.greek-added} επι τα προσωπα αυτων και προσεκυνησαν τω [θεω]{.greek-abbr}[7:11 | instance no. 2]{.aside}

λεγοντες αμην [και]{.greek-added} η ευλογια και η δοξα και η σοφια και η ευχαριστια και η τιμη και η δυναμις και η ισχυς τω [θεω]{.greek-abbr} ημων εις τους αιωνας των αιωνων αμην[7:12]{.aside}

και απεκριθη εις εκ των πρεσβυτερων λεγων μοι ουτοι οι περιβεβλημενοι τας στολας τας λευκας τινες [εισιν]{.greek-omitted} [εισι]{.greek-added} και ποθεν ηλθον[7:13]{.aside}

και ειπον αυτω κυριε μου συ οιδας και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} μοι ουτοι εισιν οι ερχομενοι εκ της θλιψεως της μεγαλης και επλυναν τας στολας αυτων και ελευκαναν εν τω αιματι [του]{.greek-omitted} [αρνιου]{.greek-omitted}[7:14]{.aside}

[και]{.greek-omitted} [ειπον]{.greek-omitted} [αυτω]{.greek-omitted} [κυριε]{.greek-omitted} [μου]{.greek-omitted} [συ]{.greek-omitted} [οιδας]{.greek-omitted} [και]{.greek-omitted} [ειπεν]{.greek-omitted} [μοι]{.greek-omitted} [ουτοι]{.greek-omitted} [εισιν]{.greek-omitted} [οι]{.greek-omitted} [ερχομενοι]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [θλιψεως]{.greek-omitted} [της]{.greek-omitted} [μεγαλης]{.greek-omitted} [και]{.greek-omitted} [επλυναν]{.greek-omitted} [τας]{.greek-omitted} [στολας]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [ελευκαναν]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [αιματι]{.greek-omitted} του αρνιου[7:14 | instance no. 2]{.aside}

δια τουτο εισιν ενωπιον του θρονου του [θεου]{.greek-abbr} και λατρευουσιν αυτω ημερας και νυκτος εν τω ναω αυτου και ο καθημενος επι τω θρονω σκηνωσει επ αυτους[7:15]{.aside}

ου πεινασουσιν ετι ουδε διψησουσιν ετι ουδ ου μη πεση επ αυτους ο ηλιος ουδε παν καυμα[7:16]{.aside}

οτι το αρνιον το [ανα]{.greek-omitted} [μεσον]{.greek-omitted} [αναμεσον]{.greek-added} του θρονου ποιμαινει αυτους και οδηγει αυτους επι ζωης πηγας υδατων και εξαλειψει ο [θεος]{.greek-abbr} παν δακρυον [εκ]{.greek-omitted} [απο]{.greek-added} των οφθαλμων αυτων[7:17]{.aside}

### Chapter 8

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την σφραγιδα την [εβδομην]{.greek-omitted} [ευδομην]{.greek-added} εγενετο σιγη εν τω [ουρανω]{.greek-abbr} ως [ημιωριον]{.greek-omitted} [ἡμιώ]{.greek-added}[8:1]{.aside}

[ριον]{.greek-added} [και]{.greek-omitted} [οτε]{.greek-omitted} [ηνοιξεν]{.greek-omitted} [την]{.greek-omitted} [σφραγιδα]{.greek-omitted} [την]{.greek-omitted} [εβδομην]{.greek-omitted} [εγενετο]{.greek-omitted} [σιγη]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ουρανω]{.greek-omitted} [ως]{.greek-omitted} [ημιωριον]{.greek-omitted}[8:1 | instance no. 2]{.aside}

και ειδον τους επτα αγγελους οι ενωπιον του [θεου]{.greek-abbr} [εστηκασιν]{.greek-omitted} [εστηκασι]{.greek-added} και εδοθησαν αυτοις επτα σαλπιγγες[8:2]{.aside}

και αλλος αγγελος [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και εσταθη επι του θυσιαστηριου εχων λιβανωτον χρυσουν και εδοθη αυτω [θυμιαματα]{.greek-omitted} [θυμιαντα]{.greek-added} πολλα ινα [δωση]{.greek-omitted} [δωσει]{.greek-added} ταις προσευχαις των αγιων παντων επι το θυσιαστηριον το χρυσουν το ενωπιον του θρονου[8:3]{.aside}

και ανεβη ο καπνος των θυμιαματων ταις προσευχαις των αγιων εκ χειρος του αγγελου ενωπιον του [θεου]{.greek-abbr}[8:4]{.aside}

και ειληφεν ο αγγελος τον λιβανωτον και [εγεμισεν]{.greek-omitted} [εγεμησεν]{.greek-added} αυτον εκ του πυρος του [θυ]{.greek-added} [θυσιαστηριου]{.greek-omitted} [και]{.greek-omitted} [εβαλεν]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [γην]{.greek-omitted} [και]{.greek-omitted} [εγενοντο]{.greek-omitted} [βρονται]{.greek-omitted} [και]{.greek-omitted} [φωναι]{.greek-omitted} [και]{.greek-omitted} [αστραπαι]{.greek-omitted} [και]{.greek-omitted} [σεισμος]{.greek-omitted}[8:5]{.aside}

[και]{.greek-omitted} [ειληφεν]{.greek-omitted} [ο]{.greek-omitted} [αγγελος]{.greek-omitted} [τον]{.greek-omitted} [λιβανωτον]{.greek-omitted} [και]{.greek-omitted} [εγεμισεν]{.greek-omitted} [αυτον]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [πυρος]{.greek-omitted} [του]{.greek-omitted} [θυσιαστηριου]{.greek-omitted} [σιαστηριου]{.greek-added} και εβαλεν εις την γην και εγενοντο βρονται και φωναι και αστραπαι και σεισμος[8:5 | instance no. 2]{.aside}

και οι επτα αγγελοι οι εχοντες τας επτα σαλπιγγας [ητοιμασαν]{.greek-omitted} [ητοιμησαν]{.greek-added} εαυτους ινα [σαλπισωσιν]{.greek-omitted} [σαλπισωσι]{.greek-added}[8:6]{.aside}

και ο πρωτος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και εγενετο χαλαζα και πυρ [μεμιγμενα]{.greek-omitted} [μεμιγμενω]{.greek-added} εν αιματι και εβληθη εις την γην και το τριτον της γης κατεκαη και το τριτον των δενδρων κατεκαη και πας χορτος χλωρος κατεκαη[8:7]{.aside}

και ο δευτερος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και ως ορος μεγα καιομενον εβληθη εις την θαλασσαν και εγενετο το τριτον της θαλασσης αιμα[8:8]{.aside}

και [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} το τριτον των [κτισ]{.greek-added} [κτισματων]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [θαλασση]{.greek-omitted} [τα]{.greek-omitted} [εχοντα]{.greek-omitted} [ψυχας]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [τριτον]{.greek-omitted} [των]{.greek-omitted} [πλοιων]{.greek-omitted} [διεφθαρη]{.greek-omitted}[8:9]{.aside}

[και]{.greek-omitted} [απεθανεν]{.greek-omitted} [το]{.greek-omitted} [τριτον]{.greek-omitted} [των]{.greek-omitted} [ματων]{.greek-added} [κτισματων]{.greek-omitted} εν τη θαλασση τα εχοντα ψυχας και το τριτον των πλοιων διεφθαρη[8:9 | instance no. 2]{.aside}

και ο τριτος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και επεσεν εκ του [ουρανου]{.greek-abbr} αστηρ μεγας καιομενος ως λαμπας και επεσεν επι το τριτον των ποταμων και επι τας πηγας των υδατων[8:10]{.aside}

και το ονομα του αστερος λεγεται ο αψινθος και εγενετο το τριτον των υδατων εις αψινθον και πολλοι των [ανθρωπων]{.greek-abbr} απεθανον εκ των υδατων οτι επικρανθησαν[8:11]{.aside}

και ο τεταρτος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και επληγη το τριτον του ηλιου και το τριτον της σεληνης και το τριτον των αστερων ινα [σκοτισθη]{.greek-omitted} [το]{.greek-omitted} [τριτον]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [τριτον]{.greek-omitted} [αυτης]{.greek-omitted} [μη]{.greek-omitted} [φανη]{.greek-omitted} [η]{.greek-omitted} [ημερα]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [νυξ]{.greek-omitted} [ομοιως]{.greek-omitted}[8:12]{.aside}

[και]{.greek-omitted} [ο]{.greek-omitted} [τεταρτος]{.greek-omitted} [αγγελος]{.greek-omitted} [εσαλπισεν]{.greek-omitted} [και]{.greek-omitted} [επληγη]{.greek-omitted} [το]{.greek-omitted} [τριτον]{.greek-omitted} [του]{.greek-omitted} [ηλιου]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [τριτον]{.greek-omitted} [της]{.greek-omitted} [σεληνης]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [τριτον]{.greek-omitted} [των]{.greek-omitted} [αστερων]{.greek-omitted} [ινα]{.greek-omitted} σκοτισθη το τριτον αυτων και [η]{.greek-added} [ημερα]{.greek-added} [ινα]{.greek-added} [μη]{.greek-added} [φανη]{.greek-added} [και]{.greek-added} το τριτον [αυτων]{.greek-added} [αυτης]{.greek-omitted} [μη]{.greek-omitted} [φανη]{.greek-omitted} [η]{.greek-omitted} [ημερα]{.greek-omitted} και η νυξ ομοιως[8:12 | instance no. 2]{.aside}

και ειδον και ηκουσα ενος [αετου]{.greek-omitted} [αγγελου]{.greek-added} πετομενου εν μεσουρανηματι λεγοντος φωνη μεγαλη ουαι ουαι ουαι τοις κατοικουσιν επι της γης εκ των λοιπων φωνων της σαλπιγγος των τριων αγγελων των μελλοντων σαλπιζειν[8:13]{.aside}

### Chapter 9

και ο πεμπτος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και ειδον αστερα εκ του [ουρανου]{.greek-abbr} πεπτωκοτα εις την γην και εδοθη αυτω η κλεις του φρεατος της αβυσσου[9:1]{.aside}

[και]{.greek-omitted} [ηνοιξεν]{.greek-omitted} [το]{.greek-omitted} [φρεαρ]{.greek-omitted} [της]{.greek-omitted} [αβυσσου]{.greek-omitted} και ανεβη καπνος εκ του φρεατος ως καπνος καμινου καιομενης και εσκοτισθη [ο]{.greek-omitted} [ηλιος]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [αηρ]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [καπνου]{.greek-omitted} [του]{.greek-omitted} [φρεατος]{.greek-omitted}[9:2]{.aside}

[και]{.greek-omitted} [ηνοιξεν]{.greek-omitted} [το]{.greek-omitted} [φρεαρ]{.greek-omitted} [της]{.greek-omitted} [αβυσσου]{.greek-omitted} [και]{.greek-omitted} [ανεβη]{.greek-omitted} [καπνος]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [φρεατος]{.greek-omitted} [ως]{.greek-omitted} [καπνος]{.greek-omitted} [καμινου]{.greek-omitted} [καιομενης]{.greek-omitted} [και]{.greek-omitted} [εσκοτισθη]{.greek-omitted} ο ηλιος και ο αηρ εκ του καπνου του φρεατος[9:2 | instance no. 2]{.aside}

και εκ του καπνου εξηλθον ακριδες εις την γην και εδοθη αυταις εξουσια ως εχουσιν εξουσιαν οι σκορπιοι της γης[9:3]{.aside}

και ερρεθη αυταις ινα μη [αδικησωσιν]{.greek-omitted} [αδικησωσι]{.greek-added} τον χορτον της γης ουδε παν χλωρον ουδε παν δενδρον ει μη τους [ανθρωπους]{.greek-abbr} οιτινες ουκ εχουσιν την σφραγιδα [του]{.greek-omitted} [θεου]{.greek-omitted} επι των [μετωπων]{.greek-omitted} [μετοπων]{.greek-added} αυτων[9:4]{.aside}

και εδοθη αυταις ινα μη αποκτεινωσιν αυτους αλλ ινα [βασανισθωσιν]{.greek-omitted} [βασανισθωσι]{.greek-added} μηνας πεντε και ο βασανισμος αυτων ως βασανισμος σκορπιου οταν παιση [ανθρωπον]{.greek-abbr}[9:5]{.aside}

και εν ταις ημεραις εκειναις [ζητησουσιν]{.greek-omitted} [οι]{.greek-omitted} [ανθρωποι]{.greek-omitted} [τον]{.greek-omitted} [θανατον]{.greek-omitted} [και]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [ευρησουσιν]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [επιθυμησουσιν]{.greek-omitted} [αποθανειν]{.greek-omitted} [και]{.greek-omitted} [φευξεται]{.greek-omitted} [απ]{.greek-omitted} [αυτων]{.greek-omitted} [ο]{.greek-omitted} [θανατος]{.greek-omitted}[9:6]{.aside}

[και]{.greek-omitted} [εν]{.greek-omitted} [ταις]{.greek-omitted} [ημεραις]{.greek-omitted} [εκειναις]{.greek-omitted} ζητησουσιν οι [ανθρωποι]{.greek-abbr} τον θανατον και ου μη [ευρησουσιν]{.greek-omitted} [εὑρήσουσιν]{.greek-added} αυτον και επιθυμησουσιν αποθανειν και φευξεται απ αυτων ο θανατος[9:6 | instance no. 2]{.aside}

και τα ομοιωματα των ακριδων ομοια ιπποις ητοιμασμενοις εις πολεμον και επι τας κεφαλας αυτων ως στεφανοι χρυσοι και τα προσωπα αυτων ως προσωπα [ανθρωπων]{.greek-abbr}[9:7]{.aside}

και ειχον τριχας ως τριχας γυναικων και οι οδοντες αυτων ως λεοντων ησαν[9:8]{.aside}

και ειχον θωρακας ως θωρακας σιδηρους και η φωνη των πτερυγων αυτων ως φωνη αρματων ιππων πολλων τρεχοντων εις πολεμον[9:9]{.aside}

και [εχουσιν]{.greek-omitted} [ουρας]{.greek-omitted} [ομοιας]{.greek-omitted} [σκορπιοις]{.greek-omitted} [και]{.greek-omitted} [κεντρα]{.greek-omitted} [και]{.greek-omitted} [εν]{.greek-omitted} [ταις]{.greek-omitted} [ουραις]{.greek-omitted} [αυτων]{.greek-omitted} [εξουσιαν]{.greek-omitted} [εχουσιν]{.greek-omitted} [του]{.greek-omitted} [αδικησαι]{.greek-omitted} [τους]{.greek-omitted} [ανθρωπους]{.greek-omitted} [μηνας]{.greek-omitted} [πεντε]{.greek-omitted}[9:10]{.aside}

[και]{.greek-omitted} εχουσιν ουρας ομοιας σκορπιοις και κεντρα [και]{.greek-omitted} εν ταις ουραις αυτων [και]{.greek-added} εξουσιαν [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} του αδικησαι τους [ανθρωπους]{.greek-abbr} μηνας πεντε[9:10 | instance no. 2]{.aside}

εχουσαι βασιλεα επ αυτων [τον]{.greek-added} αγγελον της αβυσσου ονομα αυτω εβραιστι [αββαδων]{.greek-omitted} [αββααδδων]{.greek-added} εν δε τη ελληνικη ονομα εχει απολλυων[9:11]{.aside}

η ουαι η μια απηλθεν ιδου [ερχεται]{.greek-omitted} [ερχονται]{.greek-added} ετι [και]{.greek-added} [αι]{.greek-added} δυο ουαι μετα ταυτα[9:12]{.aside}

και ο εκτος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και ηκουσα φωνην μιαν εκ των τεσσαρων [κερατων]{.greek-omitted} [κερατιων]{.greek-added} του θυσιαστηριου του χρυσου του ενωπιον του [θεου]{.greek-abbr}[9:13]{.aside}

[λεγουσαν]{.greek-omitted} [λεγοντος]{.greek-added} τω εκτω αγγελω ο εχων την σαλπιγγα [λυσον]{.greek-omitted} [τους]{.greek-omitted} [τεσσαρας]{.greek-omitted} [αγγελους]{.greek-omitted} [τους]{.greek-omitted} [δεδεμενους]{.greek-omitted} [επι]{.greek-omitted} [τω]{.greek-omitted} [ποταμω]{.greek-omitted} [τω]{.greek-omitted} [μεγαλω]{.greek-omitted} [ευφρατη]{.greek-omitted}[9:14]{.aside}

[λεγουσαν]{.greek-omitted} [τω]{.greek-omitted} [εκτω]{.greek-omitted} [αγγελω]{.greek-omitted} [ο]{.greek-omitted} [εχων]{.greek-omitted} [την]{.greek-omitted} [σαλπιγγα]{.greek-omitted} λυσον τους τεσσαρας αγγελους τους δεδεμενους επι τω ποταμω τω μεγαλω ευφρατη[9:14 | instance no. 2]{.aside}

και ελυθησαν οι τεσσαρες αγγελοι οι ητοιμασμενοι εις την ωραν και εις την ημεραν και μηνα και ενιαυτον ινα [αποκτεινωσιν]{.greek-omitted} [αποκτεινωσι]{.greek-added} το τριτον των [ανθρωπων]{.greek-abbr}[9:15]{.aside}

και ο αριθμος των στρατευματων του ιππου μυριαδες μυριαδων ηκουσα τον αριθμον αυτων[9:16]{.aside}

και ουτως ειδον τους ιππους εν τη ορασει και τους καθημενους επ [αυτων]{.greek-omitted} [αυτους]{.greek-added} εχοντας θωρακας πυρινους και υακινθινους και θειωδεις και αι κεφαλαι των ιππων ως κεφαλαι λεοντων και εκ των στοματων [αυτων]{.greek-omitted} [εκπορευεται]{.greek-omitted} [πυρ]{.greek-omitted} [και]{.greek-omitted} [καπνος]{.greek-omitted} [και]{.greek-omitted} [θειον]{.greek-omitted}[9:17]{.aside}

[και]{.greek-omitted} [ουτως]{.greek-omitted} [ειδον]{.greek-omitted} [τους]{.greek-omitted} [ιππους]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [ορασει]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [καθημενους]{.greek-omitted} [επ]{.greek-omitted} [αυτων]{.greek-omitted} [εχοντας]{.greek-omitted} [θωρακας]{.greek-omitted} [πυρινους]{.greek-omitted} [και]{.greek-omitted} [υακινθινους]{.greek-omitted} [και]{.greek-omitted} [θειωδεις]{.greek-omitted} [και]{.greek-omitted} [αι]{.greek-omitted} [κεφαλαι]{.greek-omitted} [των]{.greek-omitted} [ιππων]{.greek-omitted} [ως]{.greek-omitted} [κεφαλαι]{.greek-omitted} [λεοντων]{.greek-omitted} [και]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [στοματων]{.greek-omitted} αυτων εκπορευεται πυρ και καπνος και θειον[9:17 | instance no. 2]{.aside}

απο των τριων πληγων τουτων απεκτανθησαν το τριτον των [ανθρωπων]{.greek-abbr} απο του πυρος και του καπνου και του θειου του εκπορευομενου εκ των στοματων αυτων[9:18]{.aside}

η γαρ εξουσια των ιππων εν τω στοματι αυτων [εστιν]{.greek-omitted} [ετι]{.greek-added} και εν ταις ουραις αυτων αι γαρ ουραι αυτων ομοιαι οφεων εχουσαι κεφαλας και εν αυταις αδικουσιν[9:19]{.aside}

και οι λοιποι των [ανθρωπων]{.greek-abbr} [οι]{.greek-omitted} [οιτινες]{.greek-added} ουκ απεκτανθησαν εν ταις πληγαις ταυταις ου μετενοησαν εκ των εργων των χειρων αυτων ινα μη [προσκυνησωσιν]{.greek-omitted} [προσκυνησωσι]{.greek-added} τα δαιμονια και τα [ειδωλα]{.greek-omitted} [τα]{.greek-omitted} [χρυσα]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} [αργυρα]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} [χαλκα]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} [λιθινα]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} [ξυλινα]{.greek-omitted} [α]{.greek-omitted} [ουτε]{.greek-omitted} [βλεπειν]{.greek-omitted} [δυναται]{.greek-omitted} [ουτε]{.greek-omitted} [ακουειν]{.greek-omitted} [ουτε]{.greek-omitted} [περιπατειν]{.greek-omitted}[9:20]{.aside}

[και]{.greek-omitted} [οι]{.greek-omitted} [λοιποι]{.greek-omitted} [των]{.greek-omitted} [ανθρωπων]{.greek-omitted} [οι]{.greek-omitted} [ουκ]{.greek-omitted} [απεκτανθησαν]{.greek-omitted} [εν]{.greek-omitted} [ταις]{.greek-omitted} [πληγαις]{.greek-omitted} [ταυταις]{.greek-omitted} [ου]{.greek-omitted} [μετενοησαν]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [εργων]{.greek-omitted} [των]{.greek-omitted} [χειρων]{.greek-omitted} [αυτων]{.greek-omitted} [ινα]{.greek-omitted} [μη]{.greek-omitted} [προσκυνησωσιν]{.greek-omitted} [τα]{.greek-omitted} [δαιμονια]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} ειδωλα τα χρυσα και τα αργυρα [και]{.greek-omitted} [τα]{.greek-omitted} [χαλκα]{.greek-omitted} και τα λιθινα και τα ξυλινα α ουτε βλεπειν [δυναται]{.greek-omitted} [δυνανται]{.greek-added} ουτε ακουειν ουτε περιπατειν[9:20 | instance no. 2]{.aside}

και ου μετενοησαν εκ των φονων αυτων ουτε εκ των φαρμακειων αυτων ουτε εκ της πορνειας α[υ]{.unclear}των ουτε εκ των κλεμματων αυτων[9:21]{.aside}

### Chapter 10

και ειδον αγγελον ισχυρον καταβα[ι]{.unclear}νοντα εκ του [ουρανου]{.greek-abbr} περιβεβλημενον νεφελην και [η]{.unclear} ιρις επι της κεφαλης α[υ]{.unclear}τ[ο]{.unclear}υ και το [προ]{.unclear}σωπον αυτου ως ο ηλιος [και]{.unclear} [οι]{.unclear} ποδες αυτου [ω]{.unclear}ς στυλοι πυρος[10:1]{.aside}

και [εχων]{.greek-omitted} [ειχεν]{.greek-added} εν [τη]{.unclear} χειρι αυτου [βιβλιον]{.greek-omitted} [βιβλιδαριον]{.greek-added} [ανεω]{.unclear}γμενον και εθηκε[ν]{.unclear} τον [ποδα]{.greek-omitted} [αυτου]{.greek-omitted} [τον]{.greek-omitted} [δεξιον]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [θαλασσης]{.greek-omitted} [τον]{.greek-omitted} [δε]{.greek-omitted} [ευωνυμον]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted}[10:2]{.aside}

[και]{.greek-omitted} [εχων]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [χειρι]{.greek-omitted} [αυτου]{.greek-omitted} [βιβλιον]{.greek-omitted} [ανεωγμενον]{.greek-omitted} [και]{.greek-omitted} [εθηκεν]{.greek-omitted} [τον]{.greek-omitted} ποδα αυτου τον δεξιον επι της θαλασσης τον δε ευωνυμον επι της γης[10:2 | instance no. 2]{.aside}

και [εκραξεν]{.greek-omitted} [εκραξε]{.greek-added} φωνη μεγαλη ωσπερ λεων μυκαται και οτε εκραξεν ελαλησαν αι επτα βρονται τας εαυτων φωνας[10:3]{.aside}

και οτε ελαλησαν αι επτα βρονται εμελλον γραφειν και ηκουσα φωνην εκ του [ουρανου]{.greek-abbr} λεγουσαν [σφραγι]{.unclear}σον α ελαλησαν αι ε[πτα]{.unclear} [βρονται]{.unclear} και μη αυτα γραψης[10:4]{.aside}

[και]{.unclear} [ο]{.unclear} αγγελος ον ειδον εστωτ[α]{.unclear} [επι]{.unclear} της θαλασσης και [επι]{.unclear} [της]{.unclear} [γης]{.unclear} [ηρεν]{.greek-omitted} [ηρε]{.greek-added} την χειρα αυτου [την]{.unclear} [δε]{.unclear}ξιαν εις τον [ουρανον]{.greek-abbr}[10:5]{.aside}

και [ωμοσεν]{.unclear} τω ζωντι εις τους αι[ωνας]{.unclear} [των]{.unclear} [αιωνων]{.unclear} [ος]{.greek-omitted} [εκτισεν]{.greek-omitted} [τον]{.greek-omitted} [ουρανον]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} [εν]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [την]{.greek-omitted} [γην]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} [εν]{.greek-omitted} [αυτη]{.greek-omitted} [και]{.greek-omitted} [την]{.greek-omitted} [θαλασσαν]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} [εν]{.greek-omitted} [αυτη]{.greek-omitted} [οτι]{.greek-omitted} [χρονος]{.greek-omitted} [ουκετι]{.greek-omitted} [εσται]{.greek-omitted}[10:6]{.aside}

[και]{.greek-omitted} [ωμοσεν]{.greek-omitted} [τω]{.greek-omitted} [ζωντι]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [αιωνας]{.greek-omitted} [των]{.greek-omitted} [αιωνων]{.greek-omitted} ος [εκτισεν]{.greek-omitted} [εκτισε]{.greek-added} τον [ουρανον]{.greek-abbr} και τα εν αυτω και την γην και τα εν αυτη και την θαλασσαν και τα εν αυτη οτι χρονος ουκετι εσται[10:6 | instance no. 2]{.aside}

αλλ εν ταις ημεραις της φωνης του [εβδομου]{.greek-omitted} [ευδομου]{.greek-added} αγγελου οταν μελλη σαλπιζειν και ετελεσθη το μυστηριον του [θεου]{.greek-abbr} ως [ευηγγελισεν]{.greek-omitted} [ευηγγελισε]{.greek-added} τους δουλους αυτου τους προφητας[10:7]{.aside}

και η φωνη ην ηκουσα εκ του [ουρανου]{.greek-abbr} παλιν λαλουσα μετ εμου και λεγουσα υπαγε λαβε το βιβλιδαριον το ανεωγμενον εν τη χειρι [του]{.greek-supplied} [α]{.greek-supplied}γγελου του εστωτος επι της θαλασσης και επι της γης[10:8]{.aside}

και απηλθον προς τον αγγελον λεγων αυτω δουναι μοι [το]{.greek-omitted} [βιβλιδαριον]{.greek-omitted} [και]{.greek-omitted} [λεγει]{.greek-omitted} [μοι]{.greek-omitted} [λαβε]{.greek-omitted} [και]{.greek-omitted} [καταφαγε]{.greek-omitted} [αυτο]{.greek-omitted} [και]{.greek-omitted} [πικρανει]{.greek-omitted} [σου]{.greek-omitted} [την]{.greek-omitted} [κοιλιαν]{.greek-omitted} [αλλ]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [στοματι]{.greek-omitted} [σου]{.greek-omitted} [εσται]{.greek-omitted} [γλυκυ]{.greek-omitted} [ως]{.greek-omitted} [μελι]{.greek-omitted}[10:9]{.aside}

[και]{.greek-omitted} [απηλθον]{.greek-omitted} [προς]{.greek-omitted} [τον]{.greek-omitted} [αγγελον]{.greek-omitted} [λεγων]{.greek-omitted} [αυτω]{.greek-omitted} [δουναι]{.greek-omitted} [μοι]{.greek-omitted} το βιβλιδαριον και λεγει μοι λαβε και καταφαγε αυτο και πικρανει σου την κοιλιαν αλλ εν τω στοματι σου εσται γλυκυ ως μελι[10:9 | instance no. 2]{.aside}

και ελαβον το βιβλιον εκ της χειρος του αγγελου και κατεφαγον [αυτο]{.greek-omitted} [αὐτό]{.greek-added} και ην εν τω στοματι μου ως μελι γλυκυ και οτε εφαγον αυτο επικρανθη η κοιλια μου[10:10]{.aside}

και [λεγουσιν]{.greek-omitted} [λεγει]{.greek-added} μοι δει σε παλιν [προφητευσαι]{.greek-omitted} [προφητευσεις]{.greek-added} επι λαοις και [επι]{.greek-omitted} [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} και γλωσσαις και [βασιλευσιν]{.greek-omitted} [βασιλευσι]{.greek-added} πολλοις[10:11]{.aside}

### Chapter 11

και εδοθη μοι καλαμος ομοιος ραβδω λεγων εγειραι και μετρησον τον ναον του [θεου]{.greek-abbr} και το θυσιαστηριον και τους προσκυνουντας εν αυτω[11:1]{.aside}

και την αυλην την εξωθεν του ναου εκβαλε εξω και μη αυτην μετρησης οτι εδοθη τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} και την πολιν την αγιαν [πατησουσιν]{.greek-omitted} [πατησουσι]{.greek-added} μηνας τεσσαρακοντα και δυο[11:2]{.aside}

και δωσω τοις [δυσιν]{.greek-omitted} [δυσι]{.greek-added} [μαρτυσιν]{.greek-omitted} [μαρτυσι]{.greek-added} μου και προφητευσουσιν ημερας χιλιας διακοσιας εξηκοντα περιβεβλημενοι σακκους[11:3]{.aside}

ουτοι εισιν αι δυο ελαιαι και αι δυο λυχνιαι αι ενωπιον του [κυριου]{.greek-abbr} της γης εστωσαι[11:4]{.aside}

και ει τις αυτους θελει αδικησαι πυρ εκπορευεται εκ του στοματος αυτων και κατεσθιει τους εχθρους αυτων και ει τις [αυτους]{.greek-added} θελει [αυτους]{.greek-omitted} αδικησαι [ου]{.greek-added} [ουτως]{.greek-omitted} [δει]{.greek-omitted} [αυτον]{.greek-omitted} [αποκτανθηναι]{.greek-omitted}[11:5]{.aside}

[τω]{.greek-added} [και]{.greek-omitted} [ει]{.greek-omitted} [τις]{.greek-omitted} [αυτους]{.greek-omitted} [θελει]{.greek-omitted} [αδικησαι]{.greek-omitted} [πυρ]{.greek-omitted} [εκπορευεται]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [στοματος]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [κατεσθιει]{.greek-omitted} [τους]{.greek-omitted} [εχθρους]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [ει]{.greek-omitted} [τις]{.greek-omitted} [θελει]{.greek-omitted} [αυτους]{.greek-omitted} [αδικησαι]{.greek-omitted} [ουτως]{.greek-omitted} δει αυτον αποκτανθηναι[11:5 | instance no. 2]{.aside}

ουτοι [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} τον [ουρανον]{.greek-abbr} εξουσιαν κλεισαι ινα μη υετος βρεχη τας ημερας της προφητειας αυτων και εξουσιαν εχουσιν επι των υδατων στρεφειν αυτα εις αιμα και παταξαι την γην οσακις εαν θελησωσιν εν παση πληγη[11:6]{.aside}

και οταν [τελεσωσιν]{.greek-omitted} [τελεσωσι]{.greek-added} την μαρτυριαν αυτων το θηριον το [αναβαινον]{.greek-omitted} [ἀναβαῖνον]{.greek-added} εκ της αβυσσου ποιησει μετ αυτων πολεμον και νικησει αυτους και αποκτενει αυτους[11:7]{.aside}

και το πτωμα αυτων επι της πλατειας της πολεως της μεγαλης [ητις]{.greek-omitted} [καλειται]{.greek-omitted} [πνευματικως]{.greek-omitted} [σοδομα]{.greek-omitted} [και]{.greek-omitted} [αιγυπτος]{.greek-omitted} [οπου]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [κυριος]{.greek-omitted} [αυτων]{.greek-omitted} [εσταυρωθη]{.greek-omitted}[11:8]{.aside}

[και]{.greek-omitted} [το]{.greek-omitted} [πτωμα]{.greek-omitted} [αυτων]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [πλατειας]{.greek-omitted} [της]{.greek-omitted} [πολεως]{.greek-omitted} [της]{.greek-omitted} [μεγαλης]{.greek-omitted} ητις καλειται [πνευματικως]{.greek-abbr} σοδομα και αιγυπτος οπου και ο [κυριος]{.greek-abbr} αυτων [εσταυρωθη]{.greek-abbr}[11:8 | instance no. 2]{.aside}

και βλεπουσιν εκ των λαων και φυλων και γλωσσων και εθνων το πτωμα αυτων ημερας τρεις ημισυ και τα πτωματα αυτων ουκ [αφησουσιν]{.greek-omitted} [αφησουσι]{.greek-added} τεθηναι εις μνημα[11:9]{.aside}

και οι κατοικουντες επι της γης χαιρουσιν επ αυτοις και ευφρανθησονται και δωρα [δωσουσιν]{.greek-omitted} [[πεμψ]{.unclear}ουσιν]{.greek-added} αλληλοις οτι ου[τοι]{.unclear} [οι]{.unclear} δυο πρ[ο]{.unclear}φηται εβασανισαν τους κ[α]{.unclear}τ[οικουν]{.unclear}τας επι [τ]{.unclear}ης γη[ς]{.unclear}[11:10]{.aside}

και μετα τας τρεις [ημε]{.unclear}ρας και ημισ[υ]{.unclear} [πνευμα]{.greek-abbr} ζω[ης]{.unclear} [εκ]{.unclear} του [θεου]{.greek-abbr} εισηλθεν εις [αυτους]{.greek-omitted} [και]{.greek-omitted} [εστησαν]{.greek-omitted} [επι]{.greek-omitted} [τους]{.greek-omitted} [ποδας]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [φοβος]{.greek-omitted} [μεγας]{.greek-omitted} [επεσεν]{.greek-omitted} [επι]{.greek-omitted} [τους]{.greek-omitted} [θεωρουντας]{.greek-omitted} [αυτους]{.greek-omitted}[11:11]{.aside}

[και]{.greek-omitted} [μετα]{.greek-omitted} [τας]{.greek-omitted} [τρεις]{.greek-omitted} [ημερας]{.greek-omitted} [και]{.greek-omitted} [ημισυ]{.greek-omitted} [πνευμα]{.greek-omitted} [ζωης]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [εισηλθεν]{.greek-omitted} [εις]{.greek-omitted} αυτους και εστησαν επι τους ποδας αυτων και φοβος μεγας [επεσεν]{.greek-omitted} [επεπεσεν]{.greek-added} επι τους θεωρουντας αυτους[11:11 | instance no. 2]{.aside}

και ηκουσα [φωνην]{.greek-omitted} [φωνη]{.greek-added} [μεγαλην]{.greek-omitted} [μεγαλη]{.greek-added} εκ του [ουρανου]{.greek-abbr} λεγουσαν [αυ]{.unclear}τοις [αναβητε]{.greek-omitted} [ἀνάβητε]{.greek-added} ωδε και ανεβησαν ει[ς]{.unclear} τον [ουρανον]{.greek-abbr} εν τη νεφελη και ε[θ]{.unclear}εωρησαν αυτους οι εχθροι αυτων[11:12]{.aside}

[και]{.greek-omitted} εν εκεινη τη ημερα εγενετο σεισμος μεγας και τ[ο]{.unclear} δε[κατον]{.unclear} της πολεως [επεσεν]{.greek-omitted} [επεσε]{.greek-added} [και]{.unclear} α[π]{.unclear}εκτανθησαν εν τω σεισ[μω]{.unclear} [ονο]{.unclear}ματα [ανθρωπων]{.greek-abbr} χιλιαδες [επτα]{.unclear} και οι λοιποι εμφο[βοι]{.unclear} [εγενοντο]{.unclear} και εδωκαν δοξα[ν]{.unclear} [τω]{.unclear} [[θεω]{.greek-abbr}]{.unclear} [του]{.unclear} [ουρανου]{.greek-abbr}[11:13]{.aside}

η ουαι η δευ[τερα]{.unclear} [απηλ]{.unclear}θεν η ουαι η τριτη [ιδου]{.unclear} [ερχεται]{.unclear} [ταχυ]{.greek-omitted}[11:14]{.aside}

[η]{.greek-omitted} [ουαι]{.greek-omitted} [η]{.greek-omitted} [δευτερα]{.greek-omitted} [απηλθεν]{.greek-omitted} [η]{.greek-omitted} [ουαι]{.greek-omitted} [η]{.greek-omitted} [τριτη]{.greek-omitted} [ιδου]{.greek-omitted} [ερχεται]{.greek-omitted} ταχυ[11:14 | instance no. 2]{.aside}

και ο [εβδομος]{.greek-omitted} [εβδομας]{.greek-added} αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και εγενοντο φωναι μεγαλαι εν τω [ουρανω]{.greek-abbr} λεγουσαι εγενετο η βασιλεια του κοσμου του [κυριου]{.greek-abbr} ημων και του [χριστου]{.greek-abbr} αυτου και βασιλευσει εις τους αιωνας των αιωνων[11:15]{.aside}

και οι εικοσι τεσσαρες πρεσβυτεροι οι ενωπιον του θρονου του [θεου]{.greek-abbr} καθημενοι επι τους θρονους αυτων επεσ[ο]{.unclear}ν επι τα προσωπα αυτων και προσεκυνησαν τω [θεω]{.greek-abbr}[11:16]{.aside}

λεγοντες ευχαριστουμεν σοι [κυριε]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ ο ων και ο ην οτι ειληφας την δυναμιν σου την μεγαλην και [εβασιλευσας]{.greek-omitted} [ευα]{.greek-added}[11:17]{.aside}

[λεγοντες]{.greek-omitted} [ευχαριστουμεν]{.greek-omitted} [σοι]{.greek-omitted} [κυριε]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [ο]{.greek-omitted} [παντοκρατωρ]{.greek-omitted} [ο]{.greek-omitted} [ων]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [ην]{.greek-omitted} [οτι]{.greek-omitted} [ειληφας]{.greek-omitted} [την]{.greek-omitted} [δυναμιν]{.greek-omitted} [σου]{.greek-omitted} [την]{.greek-omitted} [μεγαλην]{.greek-omitted} [και]{.greek-omitted} [εβασιλευσας]{.greek-omitted} [σιλευσας]{.greek-added}[11:17 | instance no. 2]{.aside}

και τα εθνη ωργισθησαν και ηλθεν η οργη σου και ο καιρος των νεκρων κριθηναι και δουναι τον μισθον τοις δουλοις σου τοις προφηταις και τοις αγιοις και τοις φοβουμενοις το ονομα σου τοις μικροις και τοις μεγαλοις και διαφθειραι τους [διαφθειροντας]{.greek-omitted} [διαφθειραντας]{.greek-added} την γην[11:18]{.aside}

και [ηνοιγη]{.greek-omitted} [ηνοιχθη]{.greek-added} ο ναος του [θεου]{.greek-abbr} εν τω [ουρανω]{.greek-abbr} και ωφθη η κιβωτος της διαθηκης του [κυριου]{.greek-abbr} εν τω ναω αυτου και εγενοντο αστραπαι και φωναι και βρονται και χαλαζα μεγαλη[11:19]{.aside}

### Chapter 12

και σημειον μεγα ωφθη εν τω [ουρανω]{.greek-abbr} [γυνη]{.greek-omitted} [περιβεβλημενη]{.greek-omitted} [τον]{.greek-omitted} [ηλιον]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [σεληνη]{.greek-omitted} [υποκατω]{.greek-omitted} [των]{.greek-omitted} [ποδων]{.greek-omitted} [αυτης]{.greek-omitted} [και]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [κεφαλης]{.greek-omitted} [αυτης]{.greek-omitted} [στεφανος]{.greek-omitted} [αστερων]{.greek-omitted} [δωδεκα]{.greek-omitted}[12:1]{.aside}

[και]{.greek-omitted} [σημειον]{.greek-omitted} [μεγα]{.greek-omitted} [ωφθη]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ουρανω]{.greek-omitted} [γ]{.unclear}υνη περιβεβλημενη τον ηλιον και η σεληνη υποκατω των ποδων αυτης και επι της κεφαλης αυτης στεφανος αστερων δωδεκα[12:1 | instance no. 2]{.aside}

και εν γαστρι εχουσα εκραζεν ωδινουσα και βασανιζομενη τεκειν[12:2]{.aside}

και ωφθη αλλο σημειον εν τω [ουρανω]{.greek-abbr} και ιδου δρακων πυρος μεγας εχων κεφαλας επτα και κερατα δεκα και επι τας κεφαλας αυτου επτα διαδηματα[12:3]{.aside}

και η ουρα αυτου συρει το τριτον των αστερων του [ουρανου]{.greek-abbr} και εβαλεν αυτους εις την γην και ο δρακων [εστηκεν]{.greek-omitted} [ἔστηκεν]{.greek-added} ενωπιον της γυναικος της μελλουσης [τεκειν]{.greek-omitted} [ινα]{.greek-omitted} [οταν]{.greek-omitted} [τεκη]{.greek-omitted} [το]{.greek-omitted} [τεκνον]{.greek-omitted} [αυτης]{.greek-omitted} [καταφαγη]{.greek-omitted}[12:4]{.aside}

[και]{.greek-omitted} [η]{.greek-omitted} [ουρα]{.greek-omitted} [αυτου]{.greek-omitted} [συρει]{.greek-omitted} [το]{.greek-omitted} [τριτον]{.greek-omitted} [των]{.greek-omitted} [αστερων]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [και]{.greek-omitted} [εβαλεν]{.greek-omitted} [αυτους]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [γην]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [δρακων]{.greek-omitted} [εστηκεν]{.greek-omitted} [ενωπιον]{.greek-omitted} [της]{.greek-omitted} [γυναικος]{.greek-omitted} [της]{.greek-omitted} [μελλουσης]{.greek-omitted} τεκειν ινα οταν τεκη το τεκνον αυτης καταφαγη[12:4 | instance no. 2]{.aside}

και ετεκεν υιον αρρενα ος μελλει ποιμαινειν παντα τα εθνη εν ραβδω [σιδηρα]{.greek-omitted} [σιδηρω]{.greek-added} και [ηρπασθη]{.greek-omitted} [ηρπαγη]{.greek-added} το τεκνον αυτης προς τον [θεον]{.greek-abbr} και προς τον θρονον αυτου[12:5]{.aside}

και η γυνη εφυγεν εις την ερημον οπου εχει [τοπον]{.greek-added} εκει [τοπον]{.greek-omitted} ητοιμασμενον υπο του [θεου]{.greek-abbr} ινα εκει εκτρεφωσιν αυτην ημερας χιλιας διακοσιας εξηκοντα[12:6]{.aside}

και εγενετο πολεμος εν τω [ουρανω]{.greek-abbr} ο μιχαηλ και οι αγγελοι αυτου πολεμησαι μετα του δρακοντος και ο δρακων [επολεμησεν]{.greek-omitted} [επολεμησε]{.greek-added} και οι αγγελοι αυτου[12:7]{.aside}

και [ουκ]{.greek-omitted} [ισχυσεν]{.greek-omitted} [ουδε]{.greek-omitted} [τοπος]{.greek-omitted} [ευρεθη]{.greek-omitted} [αυτω]{.greek-omitted} [ετι]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ουρανω]{.greek-omitted}[12:8]{.aside}

[και]{.greek-omitted} ουκ [ισχυσεν]{.greek-omitted} [ισχυσιν]{.greek-added} ουδε τοπος [αυτω]{.greek-added} ευρεθη [αυτω]{.greek-omitted} ετι εν τω [ουρανω]{.greek-abbr}[12:8 | instance no. 2]{.aside}

και εβληθη ο δρακων ο μεγας ο οφις ο αρχαιος ο καλουμενος διαβολος και σατανας ο πλανων την οικουμενην ολην εβληθη εις την γην και οι αγγελοι αυτου μετ αυτου εβληθησαν[12:9]{.aside}

και ηκουσα φωνην μεγαλην εν τω [ουρανω]{.greek-abbr} λεγουσαν αρτι εγενετο η [σωτηρια]{.greek-abbr} και η δυναμις και η βασιλεια του [θεου]{.greek-abbr} ημων και η εξουσια του [χριστου]{.greek-abbr} αυτου οτι εβληθη ο κατηγορος των αδελφων ημων ο κατηγορων αυτων ενωπιον του [θεου]{.greek-abbr} ημων ημερας και νυκτος[12:10]{.aside}

και αυτοι ενικησαν [αυτον]{.greek-omitted} [δια]{.greek-omitted} [το]{.greek-omitted} [αιμα]{.greek-omitted} [του]{.greek-omitted} [αρνιου]{.greek-omitted} [και]{.greek-omitted} [δια]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted} [της]{.greek-omitted} [μαρτυριας]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [ηγαπησαν]{.greek-omitted} [την]{.greek-omitted} [ψυχην]{.greek-omitted} [αυτων]{.greek-omitted} [αχρι]{.greek-omitted} [θανατου]{.greek-omitted}[12:11]{.aside}

[και]{.greek-omitted} [αυτοι]{.greek-omitted} [ενικησαν]{.greek-omitted} αυτον δια το αιμα του αρνιου και δια τον λογον της μαρτυριας [αυτων]{.greek-omitted} [αυτου]{.greek-added} και ουκ ηγαπησαν την ψυχην αυτων αχρι θανατου[12:11 | instance no. 2]{.aside}

δια τουτο ευφραινεσθε [οι]{.greek-added} ουρανοι και οι εν αυτοις σκηνουντες ουαι τη γη και τη θαλασση οτι κατεβη ο διαβολος προς υμας εχων θυμον μεγαν ειδως οτι ολιγον καιρον εχει[12:12]{.aside}

και οτε ειδεν ο δρακων οτι εβληθη εις την γην [εδιωξεν]{.greek-omitted} [εδιωκε]{.greek-added} την γυναικα ητις [ετεκεν]{.greek-omitted} [ετεκε]{.greek-added} τον αρρενα[12:13]{.aside}

και εδοθησαν τη γυνα[ι]{.unclear}κι δυο πτερυγες του αετου του μεγαλου ινα πετηται εις την ερημον εις τον τοπον [αυτης]{.greek-omitted} [οπως]{.greek-omitted} [τρεφηται]{.greek-omitted} [εκει]{.greek-omitted} [καιρον]{.greek-omitted} [και]{.greek-omitted} [καιρους]{.greek-omitted} [και]{.greek-omitted} [ημισυ]{.greek-omitted} [καιρου]{.greek-omitted} [απο]{.greek-omitted} [προσωπου]{.greek-omitted} [του]{.greek-omitted} [οφεως]{.greek-omitted}[12:14]{.aside}

[και]{.greek-omitted} [εδοθησαν]{.greek-omitted} [τη]{.greek-omitted} [γυναικι]{.greek-omitted} [δυο]{.greek-omitted} [πτερυγες]{.greek-omitted} [του]{.greek-omitted} [αετου]{.greek-omitted} [του]{.greek-omitted} [μεγαλου]{.greek-omitted} [ινα]{.greek-omitted} [πετηται]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [ερημον]{.greek-omitted} [εις]{.greek-omitted} [τον]{.greek-omitted} [τοπον]{.greek-omitted} αυτης οπως τρεφηται εκει καιρον και καιρους και ημισυ καιρου απο προσωπου του οφεως[12:14 | instance no. 2]{.aside}

και εβαλεν ο οφις εκ του στοματος αυτου οπισω της γυναικος υδωρ ως ποταμον ινα αυτην ποταμοφορητον ποιηση[12:15]{.aside}

και εβοηθησεν η γη τη γυναικι και ηνοιξεν η γη το στομα αυτης και [κατεπιεν]{.greek-omitted} [κατεπιε]{.greek-added} τον ποταμον ον εβαλεν ο δρακων εκ του στοματος αυτου[12:16]{.aside}

και ωργισθη ο δρακων επι τη γυναικι και [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} ποιησαι πολεμον μετα των λοιπων του σπερματος αυτης των τηρουντων τας εντολας του [θεου]{.greek-abbr} και [εχοντων]{.greek-omitted} [εχοντα]{.greek-added} [την]{.greek-omitted} [μαρτυριαν]{.greek-omitted} [ιησου]{.greek-omitted}[12:17]{.aside}

[και]{.greek-omitted} [ωργισθη]{.greek-omitted} [ο]{.greek-omitted} [δρακων]{.greek-omitted} [επι]{.greek-omitted} [τη]{.greek-omitted} [γυναικι]{.greek-omitted} [και]{.greek-omitted} [απηλθεν]{.greek-omitted} [ποιησαι]{.greek-omitted} [πολεμον]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} [λοιπων]{.greek-omitted} [του]{.greek-omitted} [σπερματος]{.greek-omitted} [αυτης]{.greek-omitted} [των]{.greek-omitted} [τηρουντων]{.greek-omitted} [τας]{.greek-omitted} [εντολας]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [και]{.greek-omitted} [εχοντων]{.greek-omitted} την μαρτυριαν [ιησου]{.greek-abbr}[12:17 | instance no. 2]{.aside}

[και]{.greek-added} [εσταθην]{.greek-added} [επι]{.greek-added} [την]{.greek-added} [αμμον]{.greek-added} [της]{.greek-added} [θαλασσης]{.greek-added}[12:18]{.aside}

### Chapter 13

[και]{.greek-omitted} [εσταθην]{.greek-omitted} [επι]{.greek-omitted} [την]{.greek-omitted} [αμμον]{.greek-omitted} [της]{.greek-omitted} [θαλασσης]{.greek-omitted} και ειδον εκ της θαλασσης θηριον αναβαινον εχον κερατα δεκα και κεφαλας επτα και επι των κερατων αυτου δεκα διαδηματα και επι τας κεφαλας αυτου ονοματα βλασφημιας[13:1]{.aside}

και το θηριον ο ειδον ην ομοιον παρδαλει και οι ποδες αυτου ως [αρκου]{.greek-omitted} [αρκτου]{.greek-added} και το στομα αυτου ως στομα λεοντος και εδωκεν αυτω ο δρακων την δυναμιν αυτου και τον θρονον αυτου και εξουσιαν μεγαλην[13:2]{.aside}

και μιαν εκ των κεφαλων αυτου ωσει εσφαγμενην εις θανα[τον]{.unclear} [και]{.greek-omitted} [η]{.greek-omitted} [πληγη]{.greek-omitted} [του]{.greek-omitted} [θανατου]{.greek-omitted} [αυτου]{.greek-omitted} [εθεραπευθη]{.greek-omitted} [και]{.greek-omitted} [εθαυμασεν]{.greek-omitted} [ολη]{.greek-omitted} [η]{.greek-omitted} [γη]{.greek-omitted} [οπισω]{.greek-omitted} [του]{.greek-omitted} [θηριου]{.greek-omitted}[13:3]{.aside}

[και]{.greek-omitted} [μιαν]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [κεφαλων]{.greek-omitted} [αυτου]{.greek-omitted} [ωσει]{.greek-omitted} [εσφαγμενην]{.greek-omitted} [εις]{.greek-omitted} [θανατον]{.greek-omitted} και η πληγη του θανατου αυτου εθεραπευθη και εθαυμασεν ολη η γη οπισω του θηριου[13:3 | instance no. 2]{.aside}

και προσεκυνησαν τω δρακοντι τω δεδωκοτι την εξουσιαν τω θηριω και προσεκυνησαν τω θηριω λεγοντες τις ομοιος τω θηριω και τις δυνατος πολεμησαι μετ αυτου[13:4]{.aside}

και εδοθη αυτω στομα λαλουν μεγαλα και [βλασφημιαν]{.greek-omitted} [βλασφημα]{.greek-added} και εδοθη αυτω εξουσια πολεμον ποιησαι μηνας τεσσαρακοντα δυο[13:5]{.aside}

και [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} το στομα αυτου εις βλασφημιαν προς τον [θεον]{.greek-abbr} βλασφημησαι το ονομα αυτου και την σκηνην αυτου [και]{.greek-added} τους [εν]{.greek-omitted} [τω]{.greek-omitted} [ουρανω]{.greek-omitted} [σκηνουντας]{.greek-omitted}[13:6]{.aside}

[και]{.greek-omitted} [ηνοιξεν]{.greek-omitted} [το]{.greek-omitted} [στομα]{.greek-omitted} [αυτου]{.greek-omitted} [εις]{.greek-omitted} [βλασφημιαν]{.greek-omitted} [προς]{.greek-omitted} [τον]{.greek-omitted} [θεον]{.greek-omitted} [βλασφημησαι]{.greek-omitted} [το]{.greek-omitted} [ονομα]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [την]{.greek-omitted} [σκηνην]{.greek-omitted} [αυτου]{.greek-omitted} [τους]{.greek-omitted} εν τω [ουρανω]{.greek-abbr} σκηνουντας[13:6 | instance no. 2]{.aside}

και εδοθη αυτω ποιησαι πολεμον μετα των αγιων και νικησαι αυτους και εδοθη αυτω εξουσια επι πασαν φυλην και λαον και γλωσσαν και εθνος[13:7]{.aside}

και προσκυνησουσιν αυτω παντες οι κατοικουντες επι της γης ων ου γεγραπται [το]{.greek-omitted} [τα]{.greek-added} [ονομα]{.greek-omitted} [ονοματα]{.greek-added} εν τω βιβλιω της ζωης του αρνιου του εσφαγμενου απο καταβολης κοσμου[13:8]{.aside}

ει τις εχει ους ακουσατω[13:9]{.aside}

ει τις [εχει]{.greek-omitted} αιχμαλωσιαν υπαγει ει τις εν μαχαιρα [αποκτενει]{.greek-omitted} [ἀποκτείνη]{.greek-added} δει αυτον [εν]{.greek-omitted} [μαχαιρα]{.greek-omitted} αποκτανθηναι ωδε εστιν η υπομονη και η πιστις των αγιων[13:10]{.aside}

και ειδον αλλο θηριον [αναβαινον]{.greek-omitted} [ἀναβαῖνον]{.greek-added} [εκ]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [και]{.greek-omitted} [ειχεν]{.greek-omitted} [κερατα]{.greek-omitted} [δυο]{.greek-omitted} [ομοια]{.greek-omitted} [αρνιω]{.greek-omitted} [και]{.greek-omitted} [ελαλει]{.greek-omitted} [ως]{.greek-omitted} [δρακων]{.greek-omitted}[13:11]{.aside}

[και]{.greek-omitted} [ειδον]{.greek-omitted} [αλλο]{.greek-omitted} [θηριον]{.greek-omitted} [αναβαινον]{.greek-omitted} εκ της γης και [ειχεν]{.greek-omitted} [ειχε]{.greek-added} κερατα [δυο]{.greek-omitted} ομοια αρνιω και ελαλει ως δρακων[13:11 | instance no. 2]{.aside}

και την εξουσιαν του πρωτου θηριου πασαν [ποιει]{.greek-omitted} [ποιειν]{.greek-added} ενωπιον αυτου και [εποιει]{.greek-omitted} [ποιει]{.greek-added} την γην και τους εν αυτη κατοικουντας ινα [προσκυνησωσιν]{.greek-omitted} [προσκυνησωσι]{.greek-added} το θηριον το πρωτον ου εθεραπευθη η πληγη του θανατου αυτου[13:12]{.aside}

και ποιει σημεια μεγαλα και [ινα]{.greek-added} πυρ [ινα]{.greek-omitted} εκ του [ουρανου]{.greek-abbr} καταβαινη επι την γην ενωπιον των [ανθρωπων]{.greek-abbr}[13:13]{.aside}

και πλανα [τους]{.greek-omitted} [εμους]{.greek-omitted} τους κατοικουντας επι της γης δια τα σημεια α εδοθη αυτω ποιησαι ενωπιον του θηριου λεγων τοις κατοικουσιν επι της γης ποιησαι [εικονα]{.greek-omitted} [τω]{.greek-omitted} [θηριω]{.greek-omitted} [ο]{.greek-omitted} [ειχεν]{.greek-omitted} [την]{.greek-omitted} [πληγην]{.greek-omitted} [και]{.greek-omitted} [εζησεν]{.greek-omitted} [απο]{.greek-omitted} [της]{.greek-omitted} [μαχαιρας]{.greek-omitted}[13:14]{.aside}

[και]{.greek-omitted} [πλανα]{.greek-omitted} [τους]{.greek-omitted} [εμους]{.greek-omitted} [τους]{.greek-omitted} [κατοικουντας]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [δια]{.greek-omitted} [τα]{.greek-omitted} [σημεια]{.greek-omitted} [α]{.greek-omitted} [εδοθη]{.greek-omitted} [αυτω]{.greek-omitted} [ποιησαι]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [θηριου]{.greek-omitted} [λεγων]{.greek-omitted} [τοις]{.greek-omitted} [κατοικουσιν]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [ποιησαι]{.greek-omitted} εικονα τω θηριω [ο]{.greek-omitted} [ὁ]{.greek-added} [ειχεν]{.greek-omitted} [ειχε]{.greek-added} την πληγην [και]{.greek-omitted} [εζησεν]{.greek-omitted} απο της μαχαιρας [και]{.greek-added} [εζησε]{.greek-added}[13:14 | instance no. 2]{.aside}

και εδοθη αυτω [πνευμα]{.greek-abbr} δουναι τη εικονι του θηριου ινα και λαληση η εικων του θηριου και ποιηση οσοι εαν μη [προσκυνησωσιν]{.greek-omitted} [προσκυνησωσι]{.greek-added} τη εικονι του θηριου [ινα]{.greek-added} [αποκτανθωσιν]{.greek-omitted} [αποκτανθωσι]{.greek-added}[13:15]{.aside}

και [ποιει]{.greek-omitted} [ποιη]{.greek-added} παντας τους μικρους και τους μεγαλους και τους πλουσιους και τους πτωχους και τους ελευθερους και τους δουλους ινα [δωσωσιν]{.greek-omitted} [δωσουσιν]{.greek-added} αυτοις [χαραγματα]{.greek-omitted} [χαραγμα]{.greek-added} επι της χειρος αυτων της δεξιας η επι το [μετωπον]{.greek-omitted} [μετοπον]{.greek-added} αυτων[13:16]{.aside}

και ινα μη τις [δυναται]{.greek-omitted} [δυνηται]{.greek-added} αγορασαι η πωλησαι ει μη ο εχων το χαραγμα το ονομα του [θηριου]{.greek-omitted} [η]{.greek-omitted} [τον]{.greek-omitted} [αριθμον]{.greek-omitted} [του]{.greek-omitted} [ονοματος]{.greek-omitted} [αυτου]{.greek-omitted}[13:17]{.aside}

[και]{.greek-omitted} [ινα]{.greek-omitted} [μη]{.greek-omitted} [τις]{.greek-omitted} [δυναται]{.greek-omitted} [αγορασαι]{.greek-omitted} [η]{.greek-omitted} [πωλησαι]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [ο]{.greek-omitted} [εχων]{.greek-omitted} [το]{.greek-omitted} [χαραγμα]{.greek-omitted} [το]{.greek-omitted} [ονομα]{.greek-omitted} [του]{.greek-omitted} θηριου η τον αριθμον του ονοματος αυτου[13:17 | instance no. 2]{.aside}

ωδε η σοφια εστιν ο εχων νουν ψηφισατω τον αριθμον του θηριου αριθμος γαρ [ανθρωπου]{.greek-abbr} [εστιν]{.greek-omitted} [εστι]{.greek-added} και ο αριθμος αυτου [εστιν]{.greek-omitted} εξακοσια εξηκοντα εξ[13:18]{.aside}

### Chapter 14

και ειδον και ιδου το αρνιον εστηκος επι το ορος σιων και μετ αυτου αριθμος εκατον τεσσαρακοντα τεσσαρες χιλιαδες εχουσαι το ονομα αυτου και το ονομα του [πατρος]{.greek-abbr} αυτου γεγραμμενον επι των μετωπων αυτων[14:1]{.aside}

και ηκουσα φωνην εκ του [ουρανου]{.greek-abbr} ως φωνην υδατων πολλων και ως φωνην βροντης μεγαλης και η φωνη ην [ηκουσα]{.greek-omitted} [ως]{.greek-omitted} [κιθαρωδων]{.greek-omitted} [κιθαριζοντων]{.greek-omitted} [εν]{.greek-omitted} [ταις]{.greek-omitted} [κιθαραις]{.greek-omitted} [αυτων]{.greek-omitted}[14:2]{.aside}

[και]{.greek-omitted} [ηκουσα]{.greek-omitted} [φωνην]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [ως]{.greek-omitted} [φωνην]{.greek-omitted} [υδατων]{.greek-omitted} [πολλων]{.greek-omitted} [και]{.greek-omitted} [ως]{.greek-omitted} [φωνην]{.greek-omitted} [βροντης]{.greek-omitted} [μεγαλης]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [φωνη]{.greek-omitted} [ην]{.greek-omitted} ηκουσα ως κιθαρωδων κιθαριζοντων εν ταις κιθαραις αυτων[14:2 | instance no. 2]{.aside}

και αδουσιν ωδην καινην ενωπιον του θρονου και ενωπιον των τεσσαρων ζωων και των πρεσβυτερων και ουδεις [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} μαθειν την ωδην ει μη αι εκατον τεσσαρακοντα τεσσαρες χιλιαδες οι ηγορασμενοι απο της γης[14:3]{.aside}

ουτοι εισιν οι μετα [γυναικων]{.greek-omitted} [γυναικος]{.greek-added} ουκ εμολυνθησαν παρθενοι γαρ εισιν ουτοι εισιν οι ακολουθουντες τω αρνιω οπου [αν]{.greek-omitted} [εαν]{.greek-added} υπαγη ουτοι υπο [ιησου]{.greek-abbr} ηγορασθησαν απο των [ανθρωπων]{.greek-abbr} απαρχη τω [θεω]{.greek-abbr} και τω αρνιω[14:4]{.aside}

και ουχ ευρεθη [εν]{.greek-omitted} [τω]{.greek-omitted} [στοματι]{.greek-omitted} [αυτων]{.greek-omitted} [ψευδος]{.greek-omitted} [αμωμοι]{.greek-omitted} [γαρ]{.greek-omitted} [εισιν]{.greek-omitted}[14:5]{.aside}

[και]{.greek-omitted} [ουχ]{.greek-omitted} [ευρεθη]{.greek-omitted} εν τω στοματι αυτων ψευδος αμωμοι γαρ [εισιν]{.greek-omitted} [εισι]{.greek-added}[14:5 | instance no. 2]{.aside}

και ειδον αγγελον πετομενον εν μεσουρανηματι εχοντα ευαγγελιον αιωνιον ευαγγελισαι τους καθημενους επι της γης και επι παν εθνος και φυλην και [γλωσσαν]{.greek-omitted} [γλωσσης]{.greek-added} και λαον[14:6]{.aside}

λεγων εν φωνη μεγαλη [φοβηθητε]{.greek-omitted} [φοβηθητι]{.greek-added} τον [κυριον]{.greek-abbr} και δοτε αυτω δοξαν οτι ηλθεν η ωρα της κρισεως αυτου και προσκυνησατε αυτον τον ποιησαντα τον [ουρανον]{.greek-abbr} και την γην και την θαλασσαν και πηγας υδατων[14:7]{.aside}

και αλλος δευτερος αγγελος [ηκολουθησεν]{.greek-omitted} [ηκολουθησε]{.greek-added} λεγων επεσεν [επεσε]{.greek-added} [βα]{.greek-added} [βαβυλων]{.greek-omitted} [η]{.greek-omitted} [μεγαλη]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [οινου]{.greek-omitted} [του]{.greek-omitted} [θυμου]{.greek-omitted} [της]{.greek-omitted} [πορνειας]{.greek-omitted} [αυτης]{.greek-omitted} [πεποτικεν]{.greek-omitted} [παντα]{.greek-omitted} [τα]{.greek-omitted} [εθνη]{.greek-omitted}[14:8]{.aside}

[και]{.greek-omitted} [αλλος]{.greek-omitted} [δευτερος]{.greek-omitted} [αγγελος]{.greek-omitted} [ηκολουθησεν]{.greek-omitted} [λεγων]{.greek-omitted} [επεσεν]{.greek-omitted} [βαβυλων]{.greek-omitted} [βυλων]{.greek-added} η μεγαλη εκ του οινου του θυμου της πορνειας αυτης [[κυριος]{.greek-abbr}]{.greek-added} [πεποτικεν]{.greek-omitted} [πεποτικε]{.greek-added} παντα τα εθνη[14:8 | instance no. 2]{.aside}

και αλλος αγγελος τριτος ηκολουθησεν αυτοις λεγων εν φωνη μεγαλη ει τις προσκυνει το θηριον και την εικονα αυτου και λαμβανει χαραγμα επι του [μετωπου]{.greek-omitted} [μετοπου]{.greek-added} αυτου η επι την χειρα αυτου[14:9]{.aside}

και αυτος πιεται εκ του οινου του θυμου του [θεου]{.greek-abbr} του [κεκερασμενου]{.greek-omitted} [κεκεραμενου]{.greek-added} ακρατου εν τω ποτηριω της οργης αυτου και βασανισθησεται εν πυρι και θειω ενωπιον των αγιων αγγελων και ενωπιον του αρνιου[14:10]{.aside}

και ο καπνος του [βασα]{.greek-added} [βασανισμου]{.greek-omitted} [αυτων]{.greek-omitted} [εις]{.greek-omitted} [αιωνας]{.greek-omitted} [αιωνων]{.greek-omitted} [αναβαινει]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [εχουσιν]{.greek-omitted} [αναπαυσιν]{.greek-omitted} [ημερας]{.greek-omitted} [και]{.greek-omitted} [νυκτος]{.greek-omitted} [οι]{.greek-omitted} [προσκυνουντες]{.greek-omitted} [το]{.greek-omitted} [θηριον]{.greek-omitted} [και]{.greek-omitted} [την]{.greek-omitted} [εικονα]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [ει]{.greek-omitted} [τις]{.greek-omitted} [λαμβανει]{.greek-omitted} [το]{.greek-omitted} [χαραγμα]{.greek-omitted} [του]{.greek-omitted} [ονοματος]{.greek-omitted} [αυτου]{.greek-omitted}[14:11]{.aside}

[και]{.greek-omitted} [ο]{.greek-omitted} [καπνος]{.greek-omitted} [του]{.greek-omitted} [βασανισμου]{.greek-omitted} [νισμου]{.greek-added} [αυτων]{.greek-omitted} [αυτου]{.greek-added} εις [αιωνας]{.greek-omitted} [αιωνα]{.greek-added} αιωνων αναβαινει και ουκ εχουσιν αναπαυσιν ημερας και νυκτος οι προσκυνουντες το θηριον και την εικονα αυτου και ει τις λαμβανει το χαραγμα του ονοματος αυτου[14:11 | instance no. 2]{.aside}

ωδε η υπομονη των αγιων εστιν οι τηρουντες τας εντολας του [θεου]{.greek-abbr} και την πιστιν [ιησου]{.greek-abbr}[14:12]{.aside}

και ηκουσα φωνης εκ του [ουρανου]{.greek-abbr} λεγουσης [μοι]{.greek-added} γραψον μακαριοι οι νεκροι οι εν [κυριω]{.greek-abbr} αποθνησκοντες [απ]{.greek-omitted} [αρτι]{.greek-omitted} [ἀπάρτι]{.greek-added} [ναι]{.greek-added} λεγει [ναι]{.greek-omitted} το [πνευμα]{.greek-abbr} ινα [αναπαυσωνται]{.greek-omitted} [αναπαυσονται]{.greek-added} εκ των κοπων αυτων τα δε εργα αυτων [ακολουθει]{.greek-omitted} [μετ]{.greek-omitted} [αυτων]{.greek-omitted}[14:13]{.aside}

[και]{.greek-omitted} [ηκουσα]{.greek-omitted} [φωνης]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [λεγουσης]{.greek-omitted} [γραψον]{.greek-omitted} [μακαριοι]{.greek-omitted} [οι]{.greek-omitted} [νεκροι]{.greek-omitted} [οι]{.greek-omitted} [εν]{.greek-omitted} [κυριω]{.greek-omitted} [αποθνησκοντες]{.greek-omitted} [απ]{.greek-omitted} [αρτι]{.greek-omitted} [λεγει]{.greek-omitted} [ναι]{.greek-omitted} [το]{.greek-omitted} [πνευμα]{.greek-omitted} [ινα]{.greek-omitted} [αναπαυσωνται]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [κοπων]{.greek-omitted} [αυτων]{.greek-omitted} [τα]{.greek-omitted} [δε]{.greek-omitted} [εργα]{.greek-omitted} [αυτων]{.greek-omitted} [ακολουθει]{.greek-omitted} [ακολουθειν]{.greek-added} μετ αυτων[14:13 | instance no. 2]{.aside}

και ειδον και ιδου νεφελη λευκη και επι την νεφελην [καθημενον]{.greek-omitted} [καθημενος]{.greek-added} [ομοιον]{.greek-omitted} [ομοιος]{.greek-added} υιω [ανθρωπου]{.greek-abbr} εχων επι [της]{.greek-omitted} [την]{.greek-added} [κεφαλης]{.greek-omitted} [κεφαλην]{.greek-added} αυτου στεφανον χρυσουν και εν τη χειρι αυτου δρεπανον οξυ[14:14]{.aside}

και αλλος αγγελος εξηλθεν εκ του [ναου]{.greek-omitted} [[ουρανου]{.greek-abbr}]{.greek-added} κραζων εν φωνη μεγαλη τω καθημενω επι της νεφελης πεμψον το δρεπανον σου και θερισον οτι ηλθεν η ωρα [του]{.greek-added} θερισαι οτι [εξηλ]{.greek-added} [εξηρανθη]{.corr} ο θερισμος της γης[14:15]{.aside}

και εβαλεν ο καθημενος επι [την]{.greek-omitted} [της]{.greek-added} [νεφελην]{.greek-omitted} [νεφελης]{.greek-added} το δρεπανον αυτου επι την γην και εθερισθη η γη[14:16]{.aside}

και αλλος αγγελος εξηλθεν εκ του ναου [του]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ουρανω]{.greek-omitted} [εχων]{.greek-omitted} [και]{.greek-omitted} [αυτος]{.greek-omitted} [δρεπανον]{.greek-omitted} [οξυ]{.greek-omitted}[14:17]{.aside}

[και]{.greek-omitted} [αλλος]{.greek-omitted} [αγγελος]{.greek-omitted} [εξηλθεν]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [ναου]{.greek-omitted} του εν τω [ουρανω]{.greek-abbr} εχων και αυτος δρεπανον οξυ[14:17 | instance no. 2]{.aside}

και αλλος αγγελος εξηλθεν εκ του θυσιαστηριου εχων εξουσιαν επι του πυρος και εφωνησεν [εν]{.greek-added} κραυγη μεγαλη τω εχοντι το δρεπανον το οξυ λεγων πεμψον σου το δρεπανον το οξυ και τρυγησον τους βοτρυας της αμπελου της γης οτι ηκμασαν αι σταφυλαι αυτης[14:18]{.aside}

και εβαλεν ο αγγελος το δρεπανον αυτου εις την γην και [ετρυγησεν]{.greek-omitted} [ετρυγησε]{.greek-added} την αμπελον της γης και εβαλεν εις την ληνον του θυμου του [θεου]{.greek-abbr} [τον]{.greek-omitted} [την]{.greek-added} [μεγαν]{.greek-omitted} [μεγαλην]{.greek-added}[14:19]{.aside}

και επατηθη η ληνος εξωθεν της πολεως [και]{.greek-omitted} [εξηλθεν]{.greek-omitted} [αιμα]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [ληνου]{.greek-omitted} [αχρι]{.greek-omitted} [των]{.greek-omitted} [χαλινων]{.greek-omitted} [των]{.greek-omitted} [ιππων]{.greek-omitted} [απο]{.greek-omitted} [σταδιων]{.greek-omitted} [χιλιων]{.greek-omitted} [εξακοσιων]{.greek-omitted}[14:20]{.aside}

[και]{.greek-omitted} [επατηθη]{.greek-omitted} [η]{.greek-omitted} [ληνος]{.greek-omitted} [εξωθεν]{.greek-omitted} [της]{.greek-omitted} [πολεως]{.greek-omitted} και εξηλθεν αιμα εκ της ληνου αχρι των χαλινων των ιππων απο σταδιων χιλιων εξακοσιων[14:20 | instance no. 2]{.aside}

### Chapter 15

και ειδον αλλο σημειον εν τω [ουρανω]{.greek-abbr} μεγα και θαυμαστον αγγελους επτα εχοντας [επτα]{.greek-added} πληγας [επτα]{.greek-omitted} τας εσχατας οτι εν αυταις ετελεσθη ο θυμος του [θεου]{.greek-abbr}[15:1]{.aside}

και ειδον ως θαλασσαν [υαλινην]{.greek-omitted} [υελινην]{.greek-added} μεμιγμενην [[μιμιγμενην]{.corr}]{.greek-added} πυρι και τους νικωντας εκ του θηριου και εκ της εικονος αυτου και εκ του [χαραγματος]{.greek-added} [αυτου]{.greek-added} [και]{.greek-added} [εκ]{.greek-added} [του]{.greek-added} αριθμου του ονοματος αυτου εστωτας επι την θαλασσαν την [υαλινην]{.greek-omitted} [υελινην]{.greek-added} εχοντας κιθαρας του [θεου]{.greek-abbr}[15:2]{.aside}

και [αδουσιν]{.greek-omitted} [αδοσιν]{.greek-added} [την]{.greek-omitted} [ωδην]{.greek-omitted} [μωυσεως]{.greek-omitted} [του]{.greek-omitted} [δουλου]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [και]{.greek-omitted} την ωδην του αρνιου λεγοντες [μεγαλα]{.greek-omitted} [και]{.greek-omitted} [θαυμαστα]{.greek-omitted} [τα]{.greek-omitted} [εργα]{.greek-omitted} [σου]{.greek-omitted} [κυριε]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [ο]{.greek-omitted} [παντοκρατωρ]{.greek-omitted} [δικαιαι]{.greek-omitted} [και]{.greek-omitted} [αληθιναι]{.greek-omitted} [αι]{.greek-omitted} [οδοι]{.greek-omitted} [σου]{.greek-omitted} [ο]{.greek-omitted} [βασιλευς]{.greek-omitted} [των]{.greek-omitted} [εθνων]{.greek-omitted}[15:3]{.aside}

[και]{.greek-omitted} [αδουσιν]{.greek-omitted} [την]{.greek-omitted} [ωδην]{.greek-omitted} [μωυσεως]{.greek-omitted} [του]{.greek-omitted} [δουλου]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [και]{.greek-omitted} [την]{.greek-omitted} [ωδην]{.greek-omitted} [του]{.greek-omitted} [αρνιου]{.greek-omitted} [λεγοντες]{.greek-omitted} μεγαλα και θαυμαστα τα εργα σου [κυριε]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ δικαιαι και αληθιναι αι οδοι σου [ο]{.greek-omitted} [βασιλευς]{.greek-omitted} [βασιλ[ευ]{.unclear}]{.greek-added} των εθνων[15:3 | instance no. 2]{.aside}

τις ου μη φοβηθη [σε]{.greek-omitted} [κυριε]{.greek-abbr} και [δοξαση]{.greek-omitted} [δοξασει]{.greek-added} το ονομα σου οτι μονος [αγιος]{.greek-omitted} [ει]{.greek-added} [οσιος]{.greek-added} οτι [παντες]{.greek-added} [παντα]{.greek-omitted} [τα]{.greek-omitted} [εθνη]{.greek-omitted} [ηξουσιν]{.greek-omitted} [ηξουσι]{.greek-added} και προσκυνησουσιν ενωπιον σου οτι τα δικαιωματα σου εφανερωθησαν[15:4]{.aside}

και μετα ταυτα ειδον και ηνοιγη ο ναος της σκηνης του μαρτυριου εν τω [ουρανω]{.greek-abbr}[15:5]{.aside}

και εξηλθον οι επτα αγγελοι οι εχοντες τας επτα πληγ[α]{.unclear}ς εκ του ναου οι ησαν ενδεδυμενοι λινον καθαρον λαμπρον και περιεζωσμενοι περι τα στηθη [ζωνας]{.greek-omitted} [χρυσας]{.greek-omitted}[15:6]{.aside}

[και]{.greek-omitted} [εξηλθον]{.greek-omitted} [οι]{.greek-omitted} [επτα]{.greek-omitted} [αγγελοι]{.greek-omitted} [οι]{.greek-omitted} [εχοντες]{.greek-omitted} [τας]{.greek-omitted} [επτα]{.greek-omitted} [πληγας]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [ναου]{.greek-omitted} [οι]{.greek-omitted} [ησαν]{.greek-omitted} [ενδεδυμενοι]{.greek-omitted} [λινον]{.greek-omitted} [καθαρον]{.greek-omitted} [λαμπρον]{.greek-omitted} [και]{.greek-omitted} [περιεζωσμενοι]{.greek-omitted} [περι]{.greek-omitted} [τα]{.greek-omitted} [στηθη]{.greek-omitted} ζωνας χρυσας[15:6 | instance no. 2]{.aside}

και [εν]{.greek-omitted} εκ των τεσσαρων ζωων [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} τοις επτα αγγελοις επτα φιαλας χρυσας γεμουσας του θυμου του [θεου]{.greek-abbr} του ζωντος εις τους [α]{.unclear}ιωνας των αιωνων[15:7]{.aside}

και εγεμισθη ο ναος καπνου εκ της δοξης του [θεου]{.greek-abbr} και εκ της δυναμεως αυτου και ουδεις [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} εισελθειν εις τον ναον αχρι τελεσθωσιν αι επτα πληγαι των επτα αγγελων[15:8]{.aside}

### Chapter 16

και ηκουσα φωνης μεγαλης [εκ]{.greek-omitted} [του]{.greek-omitted} [ναου]{.greek-omitted} λεγουσης τοις επτα αγγελοις υπαγετε και εκχεατε τας επτα φιαλας του θυμου του [θεου]{.greek-abbr} εις την γην[16:1]{.aside}

και απηλθεν ο πρωτος και [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου εις την γην και [εγενετο]{.greek-omitted} [ελκος]{.greek-omitted} [κακον]{.greek-omitted} [και]{.greek-omitted} [πονηρον]{.greek-omitted} [επι]{.greek-omitted} [τους]{.greek-omitted} [ανθρωπους]{.greek-omitted} [τους]{.greek-omitted} [εχοντας]{.greek-omitted} [το]{.greek-omitted} [χαραγμα]{.greek-omitted} [του]{.greek-omitted} [θηριου]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [προσκυνουντας]{.greek-omitted} [τη]{.greek-omitted} [εικονι]{.greek-omitted} [αυτου]{.greek-omitted}[16:2]{.aside}

[και]{.greek-omitted} [απηλθεν]{.greek-omitted} [ο]{.greek-omitted} [πρωτος]{.greek-omitted} [και]{.greek-omitted} [εξεχεεν]{.greek-omitted} [την]{.greek-omitted} [φιαλην]{.greek-omitted} [αυτου]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [γην]{.greek-omitted} [και]{.greek-omitted} εγενετο ελκος κακον και πονηρον επι τους [ανθρωπους]{.greek-abbr} τους εχοντας το χαραγμα του θηριου και τους προσκυνουντας τη εικονι αυτου[16:2 | instance no. 2]{.aside}

και ο δευτερος αγγελος [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου εις την θαλασσαν και εγενετο αιμα ως νεκρου και πασα ψυχη [ζωσα]{.greek-omitted} απεθανεν εν τη θαλασση[16:3]{.aside}

και ο τριτος [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου εις τους ποταμους και εις τας πηγας των υδατων και εγενετο αιμα[16:4]{.aside}

και ηκουσα του αγγελου των υδατων λεγοντος δικαιος ει ο ων και ο ην ο οσιος οτι ταυτα εκρινας[16:5]{.aside}

οτι αιμα [αγιων]{.greek-omitted} [ἁγίων]{.greek-added} και προφητων εξεχεαν και αιμα αυτοις εδωκας πιειν [αξιοι]{.greek-omitted} [εισιν]{.greek-omitted}[16:6]{.aside}

[οτι]{.greek-omitted} [αιμα]{.greek-omitted} [αγιων]{.greek-omitted} [και]{.greek-omitted} [προφητων]{.greek-omitted} [εξεχεαν]{.greek-omitted} [και]{.greek-omitted} [αιμα]{.greek-omitted} [αυτοις]{.greek-omitted} [εδωκας]{.greek-omitted} [πιειν]{.greek-omitted} αξιοι [εισιν]{.greek-omitted} [εισι]{.greek-added}[16:6 | instance no. 2]{.aside}

και ηκουσα του θυσιαστηριου λεγοντος ναι [κυριε]{.greek-omitted} [[κυριος]{.greek-abbr}]{.greek-added} ο [θεος]{.greek-abbr} ο παντοκρατωρ αληθιναι και δικαιαι αι κρισεις σου[16:7]{.aside}

και ο τεταρτος αγγελος [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου επι τον ηλιον και εδοθη αυτω καυματισαι εν πυρι τους [ανθρωπους]{.greek-abbr}[16:8]{.aside}

και εκαυματισθησαν οι [ανθρωποι]{.greek-abbr} καυμα μεγα και εβλασφημησαν οι [ανθρωποι]{.greek-abbr} το ονομα [του[θεου]{.greek-abbr}]{.greek-added} [του]{.greek-omitted} [θεου]{.greek-omitted} του εχοντος εξουσιαν επι τας πληγας ταυτας και ου μετενοησαν δουναι [δοξαν]{.greek-added} αυτω [δοξαν]{.greek-omitted}[16:9]{.aside}

και ο πεμπτος [αγγελος]{.greek-added} [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου επι τον θρονον του θηριου και εγενετο η βασιλεια αυτου εσκοτωμενη και [εμασωντο]{.greek-omitted} [εμασσωντο]{.greek-added} τας γλωσσας αυτων εκ [του]{.greek-omitted} [πονου]{.greek-omitted}[16:10]{.aside}

[και]{.greek-omitted} [ο]{.greek-omitted} [πεμπτος]{.greek-omitted} [εξεχεεν]{.greek-omitted} [την]{.greek-omitted} [φιαλην]{.greek-omitted} [αυτου]{.greek-omitted} [επι]{.greek-omitted} [τον]{.greek-omitted} [θρονον]{.greek-omitted} [του]{.greek-omitted} [θηριου]{.greek-omitted} [και]{.greek-omitted} [εγενετο]{.greek-omitted} [η]{.greek-omitted} [βασιλεια]{.greek-omitted} [αυτου]{.greek-omitted} [εσκοτωμενη]{.greek-omitted} [και]{.greek-omitted} [εμασωντο]{.greek-omitted} [τας]{.greek-omitted} [γλωσσας]{.greek-omitted} [αυτων]{.greek-omitted} [εκ]{.greek-omitted} [τ]{.unclear}ου πονου[16:10 | instance no. 2]{.aside}

και εβλασφημησαν τον [θεον]{.greek-abbr} του [ουρανου]{.greek-abbr} εκ των πονων αυτων και εκ των ελκων αυτων και ου μετενοησαν εκ των εργων αυτων[16:11]{.aside}

και ο εκτος [αγγελος]{.greek-added} [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου επι τον ποταμον τον μεγαν ευφρατην και εξηρανθη το υδωρ αυτου ινα ετοιμασθη η οδος των βασιλεων των απο ανατολης ηλιου[16:12]{.aside}

και ειδον εκ του στοματος του δρακοντος και εκ του στοματος του θηριου και εκ του στοματος του ψευδοπροφητου πνευματα ακαθαρτα τρια ως βατραχοι [εκπορευθεντα]{.greek-added}[16:13]{.aside}

[εισιν]{.greek-omitted} [εισι]{.greek-added} γαρ πνευματα δαιμονιων ποιουντα σημεια [α]{.greek-omitted} [εκπορευεται]{.greek-omitted} [επι]{.greek-omitted} [τους]{.greek-omitted} [βασιλεις]{.greek-omitted} [της]{.greek-omitted} [οικουμενης]{.greek-omitted} [ολης]{.greek-omitted} [συναγαγειν]{.greek-omitted} [αυτους]{.greek-omitted} [εις]{.greek-omitted} [τον]{.greek-omitted} [πολεμον]{.greek-omitted} [της]{.greek-omitted} [ημερας]{.greek-omitted} [εκεινης]{.greek-omitted} [της]{.greek-omitted} [μεγαλης]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [του]{.greek-omitted} [παντοκρατορος]{.greek-omitted}[16:14]{.aside}

[εισιν]{.greek-omitted} [γαρ]{.greek-omitted} [πνευματα]{.greek-omitted} [δαιμονιων]{.greek-omitted} [ποιουντα]{.greek-omitted} [σημεια]{.greek-omitted} α εκπορευεται επι τους βασιλεις της οικουμενης [ολης]{.greek-omitted} [ολλης]{.greek-added} συναγαγειν αυτους εις τον πολεμον της ημερας εκεινης της μεγαλης του [θεου]{.greek-abbr} του παντοκρατορος[16:14 | instance no. 2]{.aside}

ιδου [ερχομαι]{.greek-omitted} [ερχεται]{.greek-added} ως κλεπτης [και]{.greek-added} μακαριος ο γρηγορων και τηρων τα ιματια αυτου ινα μη γυμνος [περιπατη]{.greek-omitted} [περιπατησει]{.greek-added} και [βλεπωσιν]{.greek-omitted} [βλεπωσι]{.greek-added} [τ]{.unclear}ην ασχημοσυνην αυτου[16:15]{.aside}

και συνηγαγεν αυτους εις τον τοπον τον καλουμενον εβραιστι [αρμαγεδων]{.greek-omitted} [ἀρμαγεδῶν]{.greek-added}[16:16]{.aside}

και ο [εβδομος]{.greek-omitted} [ευδομος]{.greek-added} [αγγελος]{.greek-added} [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου επι τον αερα και [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} φωνη μεγαλη απο [του]{.greek-omitted} [ναου]{.greek-omitted} του [ουρανου]{.greek-abbr} απο του θρονου λεγουσα [γεγονεν]{.greek-omitted} [γεγονε]{.greek-added}[16:17]{.aside}

και εγενοντο αστραπαι και βρονται και φωναι και σεισμος μεγας οιος ουκ εγενετο αφ ου [οι]{.greek-omitted} [ανθρωποι]{.greek-omitted} [εγενοντο]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [τηλικουτος]{.greek-omitted} [σεισμος]{.greek-omitted} [ουτως]{.greek-omitted} [μεγας]{.greek-omitted}[16:18]{.aside}

[και]{.greek-omitted} [εγενοντο]{.greek-omitted} [αστραπαι]{.greek-omitted} [και]{.greek-omitted} [βρονται]{.greek-omitted} [και]{.greek-omitted} [φωναι]{.greek-omitted} [και]{.greek-omitted} [σεισμος]{.greek-omitted} [μεγας]{.greek-omitted} [οιος]{.greek-omitted} [ουκ]{.greek-omitted} [εγενετο]{.greek-omitted} [αφ]{.greek-omitted} [ου]{.greek-omitted} οι [ανθρωποι]{.greek-abbr} εγενοντο επι της γης τηλικουτος σεισμος [ουτως]{.greek-omitted} [ουτω]{.greek-added} μεγας[16:18 | instance no. 2]{.aside}

και εγενετο η πολις η μεγαλη εις τρια μερη και αι πολεις των εθνων επεσον και βαβυλων η μεγαλη εμνησθη ενωπιον του [θεου]{.greek-abbr} [του]{.greek-added} δουναι αυτη το ποτηριον του οινου του θυμου της οργης αυτου[16:19]{.aside}

και πασα νησος [εφυγεν]{.greek-omitted} [εφυγε]{.greek-added} και ορη ουχ ευρεθησαν[16:20]{.aside}

και χαλαζα μεγαλη ως ταλαντιαια καταβαινει εκ του [ουρανου]{.greek-abbr} επι τους [ανθρωπους]{.greek-abbr} και εβλασφημησαν οι [ανθρωποι]{.greek-abbr} τον [θεον]{.greek-abbr} [εκ]{.greek-omitted} [απο]{.greek-added} της πληγης της χαλαζης οτι μεγαλη [αυτης]{.greek-added} εστιν η πληγη [αυτης]{.greek-omitted} σφοδρα[16:21]{.aside}

### Chapter 17

και ηλθεν εις εκ των επτα αγγελων των εχοντων τας επτα φιαλας και [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} [μετ]{.greek-omitted} [εμου]{.greek-omitted} [λεγων]{.greek-omitted} [δευρο]{.greek-omitted} [δειξω]{.greek-omitted} [σοι]{.greek-omitted} [το]{.greek-omitted} [κριμα]{.greek-omitted} [της]{.greek-omitted} [πορνης]{.greek-omitted} [της]{.greek-omitted} [μεγαλης]{.greek-omitted} [της]{.greek-omitted} [καθημενης]{.greek-omitted} [επι]{.greek-omitted} [των]{.greek-omitted} [υδατων]{.greek-omitted} [των]{.greek-omitted} [πολλων]{.greek-omitted}[17:1]{.aside}

[και]{.greek-omitted} [ηλθεν]{.greek-omitted} [εις]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [επτα]{.greek-omitted} [αγγελων]{.greek-omitted} [των]{.greek-omitted} [εχοντων]{.greek-omitted} [τας]{.greek-omitted} [επτα]{.greek-omitted} [φιαλας]{.greek-omitted} [και]{.greek-omitted} [ελαλησεν]{.greek-omitted} μετ εμου λεγων δευρο δειξω σοι το κριμα της πορνης της μεγαλης της καθημενης επι των υδατων των πολλων[17:1 | instance no. 2]{.aside}

μεθ ης επορνευσαν οι βασιλεις της γης και εμεθυσθησαν οι κατοικουντες την γην εκ του οινου της πορνειας αυτης[17:2]{.aside}

και [απηνεγκεν]{.greek-omitted} [απηνεγκε]{.greek-added} [με]{.greek-omitted} [μει]{.greek-added} εις ερημον εν [πνευματι]{.greek-abbr} και ειδον γυναικα καθημενην επι θηριον κοκκινον γεμον ονοματα βλασφημιας εχον κεφαλας επτα και κερατα δεκα[17:3]{.aside}

και η γυνη [ην]{.greek-omitted} [ἦν]{.greek-added} περιβεβλημενη πορφυρουν και κοκκινον κεχρυσωμενη χρυσιω και λιθω τιμιω και μαργαριταις εχουσα ποτηριον χρυσουν εν τη χειρι αυτης [γεμον]{.greek-omitted} [βδελυγματων]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} [ακαθαρτα]{.greek-omitted} [της]{.greek-omitted} [πορνειας]{.greek-omitted} [αυτης]{.greek-omitted}[17:4]{.aside}

[και]{.greek-omitted} [η]{.greek-omitted} [γυνη]{.greek-omitted} [ην]{.greek-omitted} [περιβεβλημενη]{.greek-omitted} [πορφυρουν]{.greek-omitted} [και]{.greek-omitted} [κοκκινον]{.greek-omitted} [κεχρυσωμενη]{.greek-omitted} [χρυσιω]{.greek-omitted} [και]{.greek-omitted} [λιθω]{.greek-omitted} [τιμιω]{.greek-omitted} [και]{.greek-omitted} [μαργαριταις]{.greek-omitted} [εχουσα]{.greek-omitted} [ποτηριον]{.greek-omitted} [χρυσουν]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [χειρι]{.greek-omitted} [αυτης]{.greek-omitted} [γεμον]{.greek-omitted} [γεμων]{.greek-added} βδελυγματων και τα ακαθαρτα της πορνειας αυτης[17:4 | instance no. 2]{.aside}

και επι το μετωπον αυτης ονομα γεγραμμενον μυστηριον βαβυλων η μεγαλη η [μητηρ]{.greek-abbr} των [πορνων]{.greek-omitted} [πορνῶν]{.greek-added} και των βδελυγματων της γης[17:5]{.aside}

και ειδον την γυναικα μεθυουσαν εκ του αιματος των αγιων [και]{.greek-added} εκ του αιματος των μαρτυρων [ιησου]{.greek-abbr} και εθαυμασα ιδων αυτην θαυμα μεγα[17:6]{.aside}

και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} μοι ο αγγελος [δια]{.greek-omitted} [διατι]{.greek-added} [τι]{.greek-omitted} εθαυμασας εγω ερω σοι το μυστηριον της γυναικος και του [θηριου]{.greek-omitted} [θυριου]{.greek-added} του βασταζοντος αυτην του εχοντος τας επτα κεφαλας και τα δεκα κερατα[17:7]{.aside}

το θηριον ο ειδες ην και ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} και μελλει [αναβαινειν]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [αβυσσου]{.greek-omitted} [και]{.greek-omitted} [εις]{.greek-omitted} [απωλειαν]{.greek-omitted} [υπαγειν]{.greek-omitted} [και]{.greek-omitted} [θαυμασονται]{.greek-omitted} [οι]{.greek-omitted} [κατοικουντες]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [ων]{.greek-omitted} [ου]{.greek-omitted} [γεγραπται]{.greek-omitted} [τα]{.greek-omitted} [ονοματα]{.greek-omitted} [επι]{.greek-omitted} [το]{.greek-omitted} [βιβλιον]{.greek-omitted} [της]{.greek-omitted} [ζωης]{.greek-omitted} [απο]{.greek-omitted} [καταβολης]{.greek-omitted} [κοσμου]{.greek-omitted} [βλεποντων]{.greek-omitted} [οτι]{.greek-omitted} [ην]{.greek-omitted} [το]{.greek-omitted} [θηριον]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [εστιν]{.greek-omitted} [και]{.greek-omitted} [παρεσται]{.greek-omitted}[17:8]{.aside}

[το]{.greek-omitted} [θηριον]{.greek-omitted} [ο]{.greek-omitted} [ειδες]{.greek-omitted} [ην]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [εστιν]{.greek-omitted} [και]{.greek-omitted} [μελλει]{.greek-omitted} αναβαινειν εκ της αβυσσου και εις απωλειαν υπαγειν και θαυμασονται οι κατοικουντες [την]{.greek-added} [γην]{.greek-added} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} ων ου γεγραπται τα ονοματα επι [το]{.greek-omitted} [του]{.greek-added} [βιβλιον]{.greek-omitted} [βιβλιου]{.greek-added} της ζωης απο καταβολης κοσμου βλεποντων οτι ην το θηριον και ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} και [παρεσται]{.greek-omitted} [παρεστιν]{.greek-added}[17:8 | instance no. 2]{.aside}

ωδε ο νους ο εχων σοφιαν αι επτα κεφαλαι επτα ορη εισιν οπου η γυνη καθηται επ αυτων [και]{.greek-added} [βασιλεις]{.greek-added} [επτα]{.greek-added} [εισιν]{.greek-added}[17:9]{.aside}

[και]{.greek-omitted} [βασιλεις]{.greek-omitted} [εισιν]{.greek-omitted} [επτα]{.greek-omitted} οι πεντε επεσον ο εις εστιν ο αλλος ουπω [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και οταν ελθη ολιγον δει αυτον μειναι[17:10]{.aside}

και το θηριον ο ην και ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} και αυτος ογδοος [εστιν]{.greek-omitted} [εστι]{.greek-added} και εκ των επτα [εστιν]{.greek-omitted} [εστι]{.greek-added} και εις απωλειαν υπαγει[17:11]{.aside}

και τα δεκα κερατα α ειδες δεκα βασιλεις εισιν [οιτινες]{.greek-omitted} [αιτινες]{.greek-added} βασιλειαν ουπω ελαβον αλλ εξουσιαν ως βασιλεις μιαν ωραν [λαμβανουσιν]{.greek-omitted} [λαμβανουσι]{.greek-added} μετα του θηριου[17:12]{.aside}

ουτοι μιαν [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} γνωμην και την δυναμιν και [την]{.greek-omitted} εξουσιαν αυτων τω θηριω διδοασιν[17:13]{.aside}

ουτοι μετα του αρνιου [πολεμησουσιν]{.greek-omitted} [πολεμησουσι]{.greek-added} και το αρνιον νικησει αυτους οτι [κυριος]{.greek-abbr} κυριων [εστιν]{.greek-omitted} [εστι]{.greek-added} και βασιλευς βασιλεων και οι μετ αυτου κλητοι και εκλεκτοι και πιστοι[17:14]{.aside}

και λεγει μοι τα υδατα α ειδες ου η πορνη καθηται λαοι και οχλοι [εισιν]{.greek-omitted} [εισι]{.greek-added} και εθνη και γλωσσαι[17:15]{.aside}

και τα δεκα κερατα α ειδες και το θηριον ουτοι [μισησουσιν]{.greek-omitted} [την]{.greek-omitted} [πορνην]{.greek-omitted} [και]{.greek-omitted} [ηρημωμενην]{.greek-omitted} [ποιησουσιν]{.greek-omitted} [αυτην]{.greek-omitted} [και]{.greek-omitted} [γυμνην]{.greek-omitted} [ποιησουσιν]{.greek-omitted} [αυτην]{.greek-omitted} [και]{.greek-omitted} [τας]{.greek-omitted} [σαρκας]{.greek-omitted} [αυτης]{.greek-omitted} [φαγονται]{.greek-omitted} [και]{.greek-omitted} [αυτην]{.greek-omitted} [κατακαυσουσιν]{.greek-omitted} [εν]{.greek-omitted} [πυρι]{.greek-omitted}[17:16]{.aside}

[και]{.greek-omitted} [τα]{.greek-omitted} [δεκα]{.greek-omitted} [κερατα]{.greek-omitted} [α]{.greek-omitted} [ειδες]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [θηριον]{.greek-omitted} [ουτοι]{.greek-omitted} [μισησουσιν]{.greek-omitted} [μισησουσι]{.greek-added} την πορνην και ηρημωμενην ποιησουσιν αυτην και γυμνην [ποιησουσιν]{.greek-omitted} [αυτην]{.greek-omitted} και τας σαρκας [φαγονται]{.greek-added} αυτης [φαγονται]{.greek-omitted} και αυτην κατακαυσουσιν εν πυρι[17:16 | instance no. 2]{.aside}

ο γαρ [θεος]{.greek-abbr} εδωκεν εις τας καρδιας αυτων ποιησαι την γνωμην αυτου και ποιησαι γνωμην μιαν και δουναι την βασιλειαν αυτων τω θηριω αχρι τελεσθωσιν οι λογοι του [θεου]{.greek-abbr}[17:17]{.aside}

και η γυνη ην ειδες εστιν η πολις η μεγαλη η εχουσα βασιλειαν επι των βασιλεων της γης[17:18]{.aside}

### Chapter 18

μετα ταυτα ειδον αλλον αγγελον καταβαινοντα εκ του [ουρανου]{.greek-abbr} εχοντα εξουσιαν μεγαλην και η γη εφωτισθη εκ της δοξης αυτου[18:1]{.aside}

και εκραξεν [ισχυρα]{.greek-omitted} [ισχυραν]{.greek-added} [φωνη]{.greek-omitted} [φωνην]{.greek-added} [λεγων]{.greek-omitted} [επεσεν]{.greek-omitted} [βαβυλων]{.greek-omitted} [η]{.greek-omitted} [μεγαλη]{.greek-omitted} [και]{.greek-omitted} [εγενετο]{.greek-omitted} [κατοικητηριον]{.greek-omitted} [δαιμονων]{.greek-omitted} [και]{.greek-omitted} [φυλακη]{.greek-omitted} [παντος]{.greek-omitted} [πνευματος]{.greek-omitted} [ακαθαρτου]{.greek-omitted} [και]{.greek-omitted} [φυλακη]{.greek-omitted} [παντος]{.greek-omitted} [ορνεου]{.greek-omitted} [ακαθαρτου]{.greek-omitted} [και]{.greek-omitted} [μεμισημενου]{.greek-omitted}[18:2]{.aside}

[και]{.greek-omitted} [εκραξεν]{.greek-omitted} [ισχυρα]{.greek-omitted} [φωνη]{.greek-omitted} λεγων [επεσεν]{.greek-added} επεσεν βαβυλων η μεγαλη και εγενετο κατοικητηριον δαιμονων και φυλακη παντος [πνευματος]{.greek-abbr} ακαθαρτου και [φυλακη]{.greek-omitted} [παντος]{.greek-omitted} ορνεου ακαθαρτου και μεμισημενου[18:2 | instance no. 2]{.aside}

οτι εκ του [θυμου]{.greek-added} [του]{.greek-added} οινου [του]{.greek-omitted} [θυμου]{.greek-omitted} της πορνειας αυτης [πεπτωκασιν]{.greek-omitted} [πεπτωκασι]{.greek-added} παντα τα εθνη και οι βασιλεις της γης μετ αυτης επορνευσαν και οι εμποροι της γης εκ της δυναμεως του στρηνους αυτης επλουτησαν[18:3]{.aside}

και ηκουσα αλλην φωνην εκ του [ουρανου]{.greek-abbr} λεγουσαν εξελθε εξ αυτης ο λαος μου ινα μη συγκοινωνησητε ταις αμαρτιαις αυτης και εκ των πληγων αυτης ινα μη λαβητε[18:4]{.aside}

οτι εκολληθησαν αυτης [αι]{.greek-omitted} [αμαρτιαι]{.greek-omitted} [αχρι]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [και]{.greek-omitted} [εμνημονευσεν]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [τα]{.greek-omitted} [αδικηματα]{.greek-omitted} [αυτης]{.greek-omitted}[18:5]{.aside}

[οτι]{.greek-omitted} [εκολληθησαν]{.greek-omitted} [αυτης]{.greek-omitted} αι αμαρτιαι αχρι του [ουρανου]{.greek-abbr} και εμνημονευσεν ο [θεος]{.greek-abbr} τα αδικηματα αυτης[18:5 | instance no. 2]{.aside}

αποδοτε αυτη ως και αυτη απεδωκεν [υμιν]{.greek-added} [[ημιν]{.corr}]{.greek-added} και διπλωσατε αυτη διπλα κατα τα εργα αυτης εν τω ποτηριω [αυτης]{.greek-added} ω εκερασεν [υμιν]{.greek-added} [κερασατε]{.greek-omitted} [αυτη]{.greek-omitted} [διπλουν]{.greek-omitted}[18:6]{.aside}

[και]{.greek-omitted} [εβαλον]{.greek-omitted} [χουν]{.greek-omitted} [επι]{.greek-omitted} [τας]{.greek-omitted} [κεφαλας]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [εκραζον]{.greek-omitted} [κλαιοντες]{.greek-omitted} [και]{.greek-omitted} [πενθουντες]{.greek-omitted} [και]{.greek-omitted} [λεγοντες]{.greek-omitted} [ουαι]{.greek-omitted} [ουαι]{.greek-omitted} [η]{.greek-omitted} [πολις]{.greek-omitted} [η]{.greek-omitted} [μεγαλη]{.greek-omitted} [εν]{.greek-omitted} [η]{.greek-omitted} [επλουτησαν]{.greek-omitted} παντες οι εχοντες τα πλοια εν τη θαλασση εκ της τιμιοτητος αυτης οτι μια ωρα ηρημωθη[18:19]{.aside}

ευφραινου επ αυτη [ουρανε]{.greek-abbr} και οι αγιοι και οι αποστολοι και οι [προφηται]{.greek-omitted} [προφητες]{.greek-added} οτι εκρινεν ο [θεος]{.greek-abbr} το κριμα υμων εξ αυτης[18:20]{.aside}

και ηρεν εις αγγελος ισχυρος λιθον ως μυλον μεγαν και εβαλεν εις την θαλασσαν λεγων ουτως ορμηματι βληθησεται βαβυλων [η]{.greek-omitted} [μεγαλη]{.greek-omitted} [πολις]{.greek-omitted} [και]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [ευρεθη]{.greek-omitted} [ετι]{.greek-omitted}[18:21]{.aside}

[και]{.greek-omitted} [ηρεν]{.greek-omitted} [εις]{.greek-omitted} [αγγελος]{.greek-omitted} [ισχυρος]{.greek-omitted} [λιθον]{.greek-omitted} [ως]{.greek-omitted} [μυλον]{.greek-omitted} [μεγαν]{.greek-omitted} [και]{.greek-omitted} [εβαλεν]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [θαλασσαν]{.greek-omitted} [λεγων]{.greek-omitted} [ουτως]{.greek-omitted} [ορμηματι]{.greek-omitted} [βληθησεται]{.greek-omitted} [βαβυλων]{.greek-omitted} η μεγαλη πολις και [ουκ]{.greek-added} [ετι]{.greek-added} ου μη ευρεθη ετι[18:21 | instance no. 2]{.aside}

και φωνη κιθαρωδων και μουσικων και αυλητων και σαλπιστων ου μη ακουσθη εν σοι ετι και πας τεχνιτης πασης τεχνης ου μη ευρεθη εν σοι ετι και φωνη μυλου ου μη ακουσθη εν σοι ετι[18:22]{.aside}

και φως λυχνου ου μη [φανη]{.greek-omitted} [φανὴ]{.greek-added} εν σοι ετι και φωνη νυμφιου και νυμφης ου μη ακουσθη εν σοι ετι [οτι]{.greek-omitted} [και]{.greek-added} οι εμποροι σου ησαν οι μεγιστανες της γης οτι εν τη φαρμακεια σου επλανηθησαν παντα τα εθνη[18:23]{.aside}

και εν αυτη αιματα προφητων και αγιων ευρεθη και παντων των εσφαγμενων επι της γης[18:24]{.aside}

### Chapter 19

μετα ταυτα ηκουσα [ως]{.greek-omitted} φωνην [μεγαλην]{.greek-omitted} [οχλου]{.greek-omitted} [πολλου]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ουρανω]{.greek-omitted} [λεγοντων]{.greek-omitted} [αλληλουια]{.greek-omitted} [η]{.greek-omitted} [σωτηρια]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [δυναμις]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [δοξα]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [ημων]{.greek-omitted}[19:1]{.aside}

[μετα]{.greek-omitted} [ταυτα]{.greek-omitted} [ηκουσα]{.greek-omitted} [ως]{.greek-omitted} [φωνην]{.greek-omitted} μεγαλην οχλου πολλου [ε]{.unclear}ν [τ]{.unclear}ω [ουρανω]{.greek-abbr} λεγοντων [αλληλουια]{.greek-omitted} [ἀλληλούια]{.greek-added} η [σωτηρια]{.greek-abbr} και η [δυναμις]{.greek-omitted} [δοξα]{.greek-added} και η [δοξα]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [τιμη]{.greek-added} [και]{.greek-added} [η]{.greek-added} [δυναμις]{.greek-added} [τω]{.greek-added} [[θεω]{.greek-abbr}]{.greek-added} ημων[19:1 | instance no. 2]{.aside}

οτι αληθιναι και δικαιαι αι κρισεις αυτου οτι [εκρινεν]{.greek-omitted} [εκρινε]{.greek-added} την [πορνην]{.greek-omitted} [πολιν]{.greek-added} την μεγαλην ητις [διεφθειρεν]{.greek-omitted} [εφθειρε]{.greek-added} την γην εν τη πορνεια αυτης και [εξεδικησεν]{.greek-omitted} [εξεδικησε]{.greek-added} το αιμα των δουλων αυτου εκ [της]{.greek-added} χειρος αυτης[19:2]{.aside}

και δευτερον ειρηκεν αλληλουια και ο καπνος [αυτης]{.greek-omitted} αναβαινει εις τους αιωνας των αιωνων[19:3]{.aside}

και επεσον οι πρεσβυτεροι οι εικοσι τεσσαρες και τα τεσσαρα ζωα και προσεκυνησαν τω [θεω]{.greek-abbr} τω καθημενω επι του θρονου λεγοντες αμην αλληλουια[19:4]{.aside}

και φωνη [εκ]{.greek-added} [απο]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [εξηλθεν]{.greek-omitted} [λεγουσα]{.greek-omitted} [αινειτε]{.greek-omitted} [τον]{.greek-omitted} [θεον]{.greek-omitted} [ημων]{.greek-omitted} [παντες]{.greek-omitted} [οι]{.greek-omitted} [δουλοι]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [φοβουμενοι]{.greek-omitted} [αυτον]{.greek-omitted} [οι]{.greek-omitted} [μικροι]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [μεγαλοι]{.greek-omitted}[19:5]{.aside}

[και]{.greek-omitted} [φωνη]{.greek-omitted} [απο]{.greek-omitted} του θρονου εξηλθεν [λεγουσα]{.greek-omitted} αινειτε τον [θεον]{.greek-abbr} ημων παντες οι δουλοι αυτου και οι φοβουμενοι αυτον οι μικροι και οι μεγαλοι[19:5 | instance no. 2]{.aside}

και ηκουσα ως φωνην οχλου πολλου και ως φωνην υδατων πολλων και ως φωνην βροντων ισχυρων [λεγοντες]{.greek-omitted} [λεγοντας]{.greek-added} αλληλουια οτι [εβασιλευσεν]{.greek-omitted} [εβασιλευσε]{.greek-added} [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ημων ο παντοκρατωρ[19:6]{.aside}

χαιρωμεν και αγαλλιωμεθα και δωμεν την δοξαν αυτω οτι ηλθεν ο γαμος του αρνιου και η γυνη αυτου ητοιμασεν εαυτην[19:7]{.aside}

και εδοθη αυτη ινα περιβαληται βυσσινον λαμπρον και καθαρον το γαρ βυσσινον τα δικαιωματα των αγιων [εστιν]{.greek-omitted} [εστι]{.greek-added}[19:8]{.aside}

και λεγει μοι γραψον μακαριοι οι εις [το]{.greek-omitted} [τον]{.greek-added} [δειπνον]{.greek-omitted} [του]{.greek-omitted} [γαμου]{.greek-omitted} [του]{.greek-omitted} [αρνιου]{.greek-omitted} [κεκλημενοι]{.greek-omitted} [και]{.greek-omitted} [λεγει]{.greek-omitted} [μοι]{.greek-omitted} [ουτοι]{.greek-omitted} [οι]{.greek-omitted} [λογοι]{.greek-omitted} [αληθινοι]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [εισιν]{.greek-omitted}[19:9]{.aside}

[και]{.greek-omitted} [λεγει]{.greek-omitted} [μοι]{.greek-omitted} [γραψον]{.greek-omitted} [μακαριοι]{.greek-omitted} [οι]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} δειπνον του γαμου του αρνιου κεκλημενοι και λεγει μοι ουτοι οι λογοι αληθινοι του [θεου]{.greek-abbr} [εισιν]{.greek-omitted} [εισι]{.greek-added}[19:9 | instance no. 2]{.aside}

και [επεσα]{.greek-omitted} [επεσον]{.greek-added} εμπροσθεν των ποδων αυτου προσκυνησαι αυτω και λεγει μοι ορα μη [συνδουλος]{.greek-omitted} [συνδουλον]{.greek-added} σου ειμι και των αδελφων σου των εχοντων την [μαρτυριαν]{.greek-omitted} [μαρτυρια]{.greek-added} [του]{.greek-added} [ιησου]{.greek-abbr} τω [θεω]{.greek-abbr} προσκυνησον η γαρ μαρτυρια του [ιησου]{.greek-abbr} [εστιν]{.greek-omitted} [εστι]{.greek-added} το [πνευμα]{.greek-abbr} της προφητειας[19:10]{.aside}

και ειδον τον [ουρανον]{.greek-abbr} ανεωγμενον και ιδου ιππος λευκος και ο καθημενος επ αυτον [καλουμενος]{.greek-omitted} [καουμενος]{.greek-added} πιστος και αληθινος και εν δικαιοσυνη κρινει και πολεμει[19:11]{.aside}

οι δε οφθαλμοι αυτου φλοξ πυρος και επι την κεφαλην [αυτου]{.greek-omitted} [διαδηματα]{.greek-omitted} [πολλα]{.greek-omitted} [εχων]{.greek-omitted} [ονοματα]{.greek-omitted} [γεγραμμενα]{.greek-omitted} [και]{.greek-omitted} [ονομα]{.greek-omitted} [γεγραμμενον]{.greek-omitted} [ο]{.greek-omitted} [ουδεις]{.greek-omitted} [οιδεν]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [αυτος]{.greek-omitted}[19:12]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [οφθαλμοι]{.greek-omitted} [αυτου]{.greek-omitted} [φλοξ]{.greek-omitted} [πυρος]{.greek-omitted} [και]{.greek-omitted} [επι]{.greek-omitted} [την]{.greek-omitted} [κεφαλην]{.greek-omitted} αυτου διαδηματα πολλα εχων [ονοματα]{.greek-omitted} [γεγραμμενα]{.greek-omitted} [και]{.greek-omitted} ονομα γεγραμμενον ο ουδεις [οιδεν]{.greek-omitted} [ειδεν]{.greek-added} ει μη αυτος[19:12 | instance no. 2]{.aside}

και περιβεβλημενος ιματιον [βεβαμμενον]{.greek-omitted} [βεβαμενον]{.greek-added} αιματι και [καλειται]{.greek-omitted} [κεκληται]{.greek-added} το ονομα αυτου ο λογος του [θεου]{.greek-abbr}[19:13]{.aside}

και τα [στρατευματα]{.greek-omitted} [γραμματα]{.greek-added} τα εν τω [ουρανω]{.greek-abbr} ηκολουθει αυτω επι ιπποις λευκοις [ενδεδυμενοι]{.greek-omitted} [ενδεδυμενα]{.greek-added} βυσσινον λευκον καθαρον[19:14]{.aside}

και εκ του στοματος αυτου εκπορευεται ρομφαια διστομος οξεια ινα εν αυτη παταξη τα εθνη και αυτος ποιμανει αυτους εν ραβδω σιδηρα και αυτος πατει [την]{.greek-omitted} [τον]{.greek-added} ληνον του οινου του θυμου της οργης του [θεου]{.greek-abbr} του παντοκρατορος[19:15]{.aside}

και εχει επι το ιματιον και επι τον μηρον αυτου ονομα γεγραμμενον βασιλευς βασιλεων και [κυριος]{.greek-abbr} κυριων[19:16]{.aside}

και ειδον [ενα]{.greek-added} αγγελον εστωτα εν τω ηλιω και [εκραξεν]{.greek-omitted} [εκραξε]{.greek-added} φωνη μεγαλη λεγων [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις ορνεοις τοις πετομενοις εν μεσουρανηματι δευτε συναχθητε εις [τον]{.greek-added} [το]{.corr} δειπνον το μεγα του [θεου]{.greek-abbr}[19:17]{.aside}

ινα φαγητε σαρκας βασιλεων και σαρκας χιλιαρχων και σαρκας ισχυρων και σαρκας ιππων και των καθημενων [επ]{.greek-omitted} [υπ]{.greek-added} αυτων και [τας]{.greek-added} σαρκας παντων ελευθερων τε και δουλων [και]{.greek-omitted} μικρων τε και μεγαλων[19:18]{.aside}

και ειδον το θηριον και τους βασιλεις της γης και τα στρατευματα αυτων συνηγμενα ποιησαι [τον]{.greek-added} πολεμον μετα του καθημενου επι [του]{.greek-omitted} [ιππου]{.greek-omitted} [και]{.greek-omitted} [μετα]{.greek-omitted} [του]{.greek-omitted} [στρατευματος]{.greek-omitted} [αυτου]{.greek-omitted}[19:19]{.aside}

[και]{.greek-omitted} [ειδον]{.greek-omitted} [το]{.greek-omitted} [θηριον]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [βασιλεις]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} [στρατευματα]{.greek-omitted} [αυτων]{.greek-omitted} [συνηγμενα]{.greek-omitted} [ποιησαι]{.greek-omitted} [πολεμον]{.greek-omitted} [μετα]{.greek-omitted} [του]{.greek-omitted} [καθημενου]{.greek-omitted} [επι]{.greek-omitted} του ιππου και μετα του στρατευματος αυτου[19:19 | instance no. 2]{.aside}

και επιασθη το θηριον και ο μετ αυτου ψευδοπροφητης ο ποιησας τα σημεια ενωπιον αυτου εν οις [επλανησεν]{.greek-omitted} [επλανησε]{.greek-added} τους λαβοντας το χαραγμα του θηριου και τους προσκυνουντας τη εικονι αυτου ζωντες [εβληθησαν]{.greek-omitted} [ενεβληθησαν]{.greek-added} οι δυο εις την λιμνην του πυρος την καιομενην εν θειω[19:20]{.aside}

και οι λοιποι απεκτανθησαν εν τη ρομφαια του καθημενου επι του ιππου τη εξελθουση εκ του στοματος αυτου και παντα τα ορνεα εχορτασθησαν [εκ]{.greek-omitted} [απο]{.greek-added} των σαρκων αυτων[19:21]{.aside}

### Chapter 20

και ειδον αγγελον καταβαινοντα εκ του [ουρανου]{.greek-abbr} εχοντα την κλειν της αβυσσου και αλυσιν [μεγαλην]{.greek-omitted} [επι]{.greek-omitted} [την]{.greek-omitted} [χειρα]{.greek-omitted} [αυτου]{.greek-omitted}[20:1]{.aside}

[και]{.greek-omitted} [ειδον]{.greek-omitted} [αγγελον]{.greek-omitted} [καταβαινοντα]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [εχοντα]{.greek-omitted} [την]{.greek-omitted} [κλειν]{.greek-omitted} [της]{.greek-omitted} [αβυσσου]{.greek-omitted} [και]{.greek-omitted} [αλυσιν]{.greek-omitted} μεγαλην επι την χειρα αυτου[20:1 | instance no. 2]{.aside}

και [εκρατησεν]{.greek-omitted} [εκρατησε]{.greek-added} τον δρακοντα τον οφιν τον αρχαιον ος [εστιν]{.greek-omitted} [εστι]{.greek-added} διαβολος και [ο]{.greek-omitted} σατανας [ο]{.greek-omitted} [πλανων]{.greek-omitted} [την]{.greek-omitted} [οικουμενην]{.greek-omitted} [ολην]{.greek-omitted} και εδησεν αυτον χιλια ετη[20:2]{.aside}

και εβαλεν αυτον εις την αβυσσον και [εκλεισεν]{.greek-omitted} [εκλεισε]{.greek-added} και εσφραγισεν επανω αυτου ινα μη πλανα ετι τα εθνη αχρι [τελεσθη]{.greek-omitted} [τελεσθωσι]{.greek-added} τα χιλια ετη [και]{.greek-omitted} μετα ταυτα δει [λυθηναι]{.greek-added} αυτον [λυθηναι]{.greek-omitted} μικρον χρονον[20:3]{.aside}

και ειδον θρονους και εκαθισαν επ αυτους και κριμα εδοθη αυτοις και τας ψυχας των πεπελεκισμενων δια την μαρτυριαν [ιησου]{.greek-abbr} και δια τον λογον του [θεου]{.greek-abbr} και οιτινες ου προσεκυνησαν το θηριον ουδε την εικονα αυτου και ουκ ελαβον το χαραγμα επι το μετωπον και επι την χειρα [αυτων]{.greek-omitted} [και]{.greek-omitted} [εζησαν]{.greek-omitted} [και]{.greek-omitted} [εβασιλευσαν]{.greek-omitted} [μετα]{.greek-omitted} [του]{.greek-omitted} [χριστου]{.greek-omitted} [τα]{.greek-omitted} [χιλια]{.greek-omitted} [ετη]{.greek-omitted}[20:4]{.aside}

[και]{.greek-omitted} [ειδον]{.greek-omitted} [θρονους]{.greek-omitted} [και]{.greek-omitted} [εκαθισαν]{.greek-omitted} [επ]{.greek-omitted} [αυτους]{.greek-omitted} [και]{.greek-omitted} [κριμα]{.greek-omitted} [εδοθη]{.greek-omitted} [αυτοις]{.greek-omitted} [και]{.greek-omitted} [τας]{.greek-omitted} [ψυχας]{.greek-omitted} [των]{.greek-omitted} [πεπελεκισμενων]{.greek-omitted} [δια]{.greek-omitted} [την]{.greek-omitted} [μαρτυριαν]{.greek-omitted} [ιησου]{.greek-omitted} [και]{.greek-omitted} [δια]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [και]{.greek-omitted} [οιτινες]{.greek-omitted} [ου]{.greek-omitted} [προσεκυνησαν]{.greek-omitted} [το]{.greek-omitted} [θηριον]{.greek-omitted} [ουδε]{.greek-omitted} [την]{.greek-omitted} [εικονα]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [ελαβον]{.greek-omitted} [το]{.greek-omitted} [χαραγμα]{.greek-omitted} [επι]{.greek-omitted} [το]{.greek-omitted} [μετωπον]{.greek-omitted} [και]{.greek-omitted} [επι]{.greek-omitted} [την]{.greek-omitted} [χειρα]{.greek-omitted} αυτων και εζησαν και εβασιλευσαν μετα του [χριστου]{.greek-abbr} τα χιλια ετη[20:4 | instance no. 2]{.aside}

[και]{.greek-omitted} [οι]{.greek-omitted} [λοιποι]{.greek-omitted} [των]{.greek-omitted} [νεκρων]{.greek-omitted} [ουκ]{.greek-omitted} [εζησαν]{.greek-omitted} [αχρι]{.greek-omitted} [τελεσθη]{.greek-omitted} [τα]{.greek-omitted} [χιλια]{.greek-omitted} [ετη]{.greek-omitted} αυτη η αναστασις η πρωτη[20:5]{.aside}

[και]{.greek-added} μακαριος και αγιος ο εχων μερος εν τη αναστασει τη πρωτη επι τουτων ο δευτερος θανατος ουκ εχει εξουσιαν αλλ εσονται ιερεις του [θεου]{.greek-abbr} και του [χριστου]{.greek-abbr} και [βασιλευσουσιν]{.greek-omitted} [βασιλευσουσι]{.greek-added} μετ αυτου [τα]{.greek-added} χιλια ετη[20:6]{.aside}

και [μετα]{.greek-added} [οταν]{.greek-omitted} [τελεσθη]{.greek-omitted} τα χιλια ετη λυθησεται ο σατανας εκ της φυλακης αυτου[20:7]{.aside}

και [εξελευσεται]{.greek-omitted} [εξελε[ω]{.unclear}σεται]{.greek-added} πλανησαι τα εθνη τα εν ταις [τεσσαρσιν]{.greek-omitted} [τεσσαρσι]{.greek-added} γωνιαις της γης τον γωγ και τον μαγωγ συναγαγειν αυτους εις τον πολεμον ων ο αριθμος [αυτων]{.greek-added} ως η αμμος της θαλασσης[20:8]{.aside}

και ανεβησαν επι το πλατος της γης και [εκυκλωσαν]{.greek-omitted} [την]{.greek-omitted} [παρεμβολην]{.greek-omitted} [των]{.greek-omitted} [αγιων]{.greek-omitted} [και]{.greek-omitted} [την]{.greek-omitted} [πολιν]{.greek-omitted} [την]{.greek-omitted} [ηγαπημενην]{.greek-omitted} [και]{.greek-omitted} [κατεβη]{.greek-omitted} [πυρ]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [και]{.greek-omitted} [κατεφαγεν]{.greek-omitted} [αυτους]{.greek-omitted}[20:9]{.aside}

[και]{.greek-omitted} [ανεβησαν]{.greek-omitted} [επι]{.greek-omitted} [το]{.greek-omitted} [πλατος]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [και]{.greek-omitted} εκυκλωσαν την παρεμβολην των αγιων και την πολιν την ηγαπημενην και κατεβη πυρ εκ του [ουρανου]{.greek-abbr} απο του [θεου]{.greek-abbr} [και]{.greek-omitted} κατεφαγεν αυτους[20:9 | instance no. 2]{.aside}

και ο διαβολος ο πλανων αυτους εβληθη εις την λιμνην του πυρος και [του]{.greek-added} θειου οπου και το θηριον και ο ψευδοπροφητης και [βασανισθησονται]{.greek-omitted} [βασανισθησαντα]{.greek-added} ημερας και νυκτος εις τους αιωνας [των]{.greek-omitted} [αιωνων]{.greek-omitted}[20:10]{.aside}

και ειδον θρονον μεγαν λευκον και τον καθημενον επ [αυτον]{.greek-omitted} [αυτο]{.greek-added} ου απο προσωπου εφυγεν η γη και ο [ουρανος]{.greek-abbr} και τοπος ουχ ευρεθη αυτοις[20:11]{.aside}

και ειδον τους νεκρους [τους]{.greek-omitted} [μεγαλους]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [μικρους]{.greek-omitted} εστωτας ενωπιον του θρονου και βιβλια ηνεωχθησαν και αλλο βιβλιον ηνεωχθη ο [εστιν]{.greek-omitted} [εστι]{.greek-added} της ζωης και εκριθησαν οι [νεκροι]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [γεγραμμενων]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} [βιβλιοις]{.greek-omitted} [κατα]{.greek-omitted} [τα]{.greek-omitted} [εργα]{.greek-omitted} [αυτων]{.greek-omitted}[20:12]{.aside}

[και]{.greek-omitted} [ειδον]{.greek-omitted} [τους]{.greek-omitted} [νεκρους]{.greek-omitted} [τους]{.greek-omitted} [μεγαλους]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [μικρους]{.greek-omitted} [εστωτας]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [και]{.greek-omitted} [βιβλια]{.greek-omitted} [ηνεωχθησαν]{.greek-omitted} [και]{.greek-omitted} [αλλο]{.greek-omitted} [βιβλιον]{.greek-omitted} [ηνεωχθη]{.greek-omitted} [ο]{.greek-omitted} [εστιν]{.greek-omitted} [της]{.greek-omitted} [ζωης]{.greek-omitted} [και]{.greek-omitted} [εκριθησαν]{.greek-omitted} [οι]{.greek-omitted} νεκροι εκ των γεγραμμενων εν τοις βιβλιοις κατα τα εργα αυτων[20:12 | instance no. 2]{.aside}

και εδωκεν η θαλασσα τους νεκρους τους εν αυτη και ο θανατος και ο αδης εδ[ω]{.unclear}καν τους νεκρους τους εν αυτοις και εκριθησαν εκαστος κατα τα εργα [αυτων]{.greek-omitted} [αυτου]{.greek-added}[20:13]{.aside}

και ο θανατος και ο αδης εβληθησαν εις την λιμνην του πυρος ουτος ο θανατος ο δευτερος εστιν η λιμνη του πυρος[20:14]{.aside}

και ε[ι]{.unclear} [τ]{.unclear}ις ουχ ευρεθη εν τω βιβλιω της ζωης γεγραμμενος εβληθη εις την λιμνην του πυρος[20:15]{.aside}

### Chapter 21

και ειδον [ουρανον]{.greek-abbr} καινον και γην καινην ο γαρ πρωτος [ουρανος]{.greek-abbr} και η πρωτη γη [απηλθον]{.greek-omitted} [απηλθε]{.greek-added} και η θαλασσα ουκ εστιν ετι[21:1]{.aside}

και την πολιν την αγιαν [ιερουσαλημ]{.greek-abbr} [και]{.greek-added} [καινην]{.greek-omitted} [ειδον]{.greek-omitted} [καταβαινουσαν]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [ητοιμασμενην]{.greek-omitted} [ως]{.greek-omitted} [νυμφην]{.greek-omitted} [κεκοσμημενην]{.greek-omitted} [τω]{.greek-omitted} [ανδρι]{.greek-omitted} [αυτης]{.greek-omitted}[21:2]{.aside}

[νην]{.greek-added} [και]{.greek-omitted} [την]{.greek-omitted} [πολιν]{.greek-omitted} [την]{.greek-omitted} [αγιαν]{.greek-omitted} [ιερουσαλημ]{.greek-omitted} [καινην]{.greek-omitted} ειδον [καταβαινουσαν]{.greek-omitted} [καταβαινουσα]{.greek-added} εκ του [ουρανου]{.greek-abbr} απο του [θεου]{.greek-abbr} ητοιμασμενην ως νυμφην [κεκοσμημενην]{.greek-omitted} τω ανδρι αυτης[21:2 | instance no. 2]{.aside}

και ηκουσα φωνης μεγαλης εκ του [ουρανου]{.greek-abbr} λεγουσης ιδου η σκηνη του [θεου]{.greek-abbr} μετα των [ανθρωπων]{.greek-abbr} και σκηνωσει μετ αυτων και αυτοι λαος αυτου εσονται και αυτος ο [θεος]{.greek-abbr} εσται μετ αυτων [[θεος]{.greek-abbr}]{.greek-added} [αυτων]{.greek-added}[21:3]{.aside}

και εξαλειψει παν δακρυον απο των οφθαλμων αυτων και [ο]{.greek-omitted} θανατος ουκ εσται ετι ουτε πενθος ουτε κραυγη ουτε [πονος]{.greek-omitted} [πορνος]{.greek-added} ουκ εσται ετι οτι τα πρωτα [απηλθον]{.greek-omitted} [απηλθε]{.greek-added}[21:4]{.aside}

και ειπεν ο καθημενος επι τω θρονω ιδου παντα καινα ποιω και [λεγει]{.greek-omitted} [ειπε]{.greek-added} μοι γραψον [οτι]{.greek-omitted} ουτοι οι λογοι [πιστοι]{.greek-added} [και]{.greek-added} αλ[η]{.unclear}θινοι [και]{.greek-omitted} [πιστοι]{.greek-omitted} [εισιν]{.greek-omitted} [εισι]{.greek-added}[21:5]{.aside}

και [ειπεν]{.greek-omitted} [λεγει]{.greek-added} μοι γεγονα [το]{.greek-omitted} [αλφα]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [ω]{.greek-omitted} [η]{.greek-omitted} [αρχη]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [τελος]{.greek-omitted} [εγω]{.greek-omitted} [τω]{.greek-omitted} [διψωντι]{.greek-omitted} [δωσω]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [πηγης]{.greek-omitted} [του]{.greek-omitted} [υδατος]{.greek-omitted} [της]{.greek-omitted} [ζωης]{.greek-omitted} [δωρεαν]{.greek-omitted}[21:6]{.aside}

[εγω]{.greek-added} [και]{.greek-omitted} [ειπεν]{.greek-omitted} [μοι]{.greek-omitted} [γεγονα]{.greek-omitted} το [αλφα]{.greek-omitted} [ἄλφα]{.greek-added} και το [ω]{.greek-omitted} [ὦ]{.greek-added} η αρχη και το τελος εγω [τω]{.greek-omitted} [των]{.greek-added} διψωντι δωσω εκ της πηγης του υδατος της ζωης δωρεαν[21:6 | instance no. 2]{.aside}

ο νικων κληρονομησει ταυτα και εσομαι αυτω [θεος]{.greek-abbr} και αυτος εσται μοι υιος[21:7]{.aside}

τοις δε δειλοις και απιστοις και αμαρτωλοις και εβδελυγμενοις και [φονευσιν]{.greek-omitted} [φονευσι]{.greek-added} και πορνοις και φαρμακοις και ειδ[ω]{.unclear}λολατραις και [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις [ψευδεσιν]{.greek-omitted} [ψευδεσι]{.greek-added} το μερος αυτων εν τη λιμνη [του]{.greek-added} [πυρος]{.greek-added} τη καιομενη πυρι και θειω ο εστιν ο θανατος ο δευτερος[21:8]{.aside}

και ηλθεν εις [εκ]{.greek-omitted} των επτα αγγελων των εχοντων τας επτα φιαλας [τας]{.greek-added} γεμουσας των επτα πληγων των εσχατων και [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} [μετ]{.greek-omitted} [εμου]{.greek-omitted} [λεγων]{.greek-omitted} [δευρο]{.greek-omitted} [δειξω]{.greek-omitted} [σοι]{.greek-omitted} [την]{.greek-omitted} [γυναικα]{.greek-omitted} [την]{.greek-omitted} [νυμφην]{.greek-omitted} [του]{.greek-omitted} [αρνιου]{.greek-omitted}[21:9]{.aside}

[και]{.greek-omitted} [ηλθεν]{.greek-omitted} [εις]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [επτα]{.greek-omitted} [αγγελων]{.greek-omitted} [των]{.greek-omitted} [εχοντων]{.greek-omitted} [τας]{.greek-omitted} [επτα]{.greek-omitted} [φιαλας]{.greek-omitted} [γεμουσας]{.greek-omitted} [των]{.greek-omitted} [επτα]{.greek-omitted} [πληγων]{.greek-omitted} [των]{.greek-omitted} [εσχατων]{.greek-omitted} [και]{.greek-omitted} [ελαλησεν]{.greek-omitted} μετ εμου λεγων δευρο δειξω σοι την γυναικα την νυμφην του αρνιου[21:9 | instance no. 2]{.aside}

και [απηνεγκεν]{.greek-omitted} [απηγαγε]{.greek-added} με εν [πνευματι]{.greek-abbr} επ ορος μεγα και υψηλον και [εδειξεν]{.greek-omitted} [εδειξε]{.greek-added} μοι την πολιν την [μεγαλην]{.greek-omitted} [την]{.greek-omitted} αγιαν [ιερουσαλημ]{.greek-abbr} [καταβαινουσαν]{.greek-omitted} [καταξαινουσαν]{.greek-added} εκ [του]{.greek-omitted} [ουρανου]{.greek-omitted} [του[ουρανου]{.greek-abbr}]{.greek-added} απο του [θεου]{.greek-abbr}[21:10]{.aside}

εχουσαν την δοξαν του [θεου]{.greek-abbr} ο φωστηρ αυτης ομοιος λιθω τιμιωτατω [ως]{.greek-omitted} [λιθω]{.greek-omitted} ιασπιδι [κρυσταλλιζοντι]{.greek-omitted} [κρυσταλιζοντι]{.greek-added}[21:11]{.aside}

εχουσα τειχος μεγα και υψηλον εχουσα πυλωνας δωδεκα και επι τοις πυλωσιν αγγελους δωδεκα και ονοματα επιγεγραμμενα α [εστιν]{.greek-omitted} [εστι]{.greek-added} [ονοματα]{.greek-omitted} των δωδεκα φυλων [των]{.greek-omitted} υιων [ισραηλ]{.greek-abbr}[21:12]{.aside}

απο ανατολων πυλωνες τρεις και απο βορρα πυλωνες τρεις και απο νοτου πυλωνες τρεις [και]{.greek-omitted} [απο]{.greek-omitted} [δυσμων]{.greek-omitted} [πυλωνες]{.greek-omitted} [τρεις]{.greek-omitted}[21:13]{.aside}

και το τειχος της πολεως εχον [θεμελιους]{.greek-omitted} [δωδεκα]{.greek-omitted} [και]{.greek-omitted} [επ]{.greek-omitted} [αυτων]{.greek-omitted} [δωδεκα]{.greek-omitted} [ονοματα]{.greek-omitted} [των]{.greek-omitted} [δωδεκα]{.greek-omitted} [αποστολων]{.greek-omitted} [του]{.greek-omitted} [αρνιου]{.greek-omitted}[21:14]{.aside}

[και]{.greek-omitted} [το]{.greek-omitted} [τειχος]{.greek-omitted} [της]{.greek-omitted} [πολεως]{.greek-omitted} [εχον]{.greek-omitted} θεμελιους δωδεκα και επ αυτων δωδεκα ονοματα των δωδεκα αποστολων του αρνιου[21:14 | instance no. 2]{.aside}

και ο λαλων μετ εμου [ειχεν]{.greek-omitted} [ειχε]{.greek-added} μετρον καλαμον χρυσουν ινα μετρηση την πολιν και τους πυλωνας αυτης και το τειχος αυτης[21:15]{.aside}

και η πολις τετραγωνος κειται και το μηκος αυτης οσον το πλατος και [εμετρησεν]{.greek-omitted} [εμετρησε]{.greek-added} την πολιν τω καλαμω επι σταδιους δωδεκα χιλιαδων [δωδεκα]{.greek-omitted} το μηκος και το πλατος και το υψος αυτης ισα [εστιν]{.greek-omitted} [εστι]{.greek-added}[21:16]{.aside}

και [εμετρησεν]{.greek-omitted} το τειχος αυτης εκατον τεσσαρακοντα τεσσαρων πηχων μετρον [ανθρωπου]{.greek-abbr} ο εστιν [αγγελου]{.greek-omitted} [αγγελος]{.greek-added}[21:17]{.aside}

και ην η ενδομησις του τειχους [αυτης]{.greek-omitted} [ιασπις]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [πολις]{.greek-omitted} [χρυσιον]{.greek-omitted} [καθαρον]{.greek-omitted} [ομοιον]{.greek-omitted} [υελω]{.greek-omitted} [καθαρω]{.greek-omitted}[21:18]{.aside}

[και]{.greek-omitted} [ην]{.greek-omitted} [η]{.greek-omitted} [ενδομησις]{.greek-omitted} [του]{.greek-omitted} [τειχους]{.greek-omitted} αυτης ιασπις και η πολις χρυσιον καθαρον ομοιον [υελω]{.greek-omitted} [υελην]{.greek-added} καθαρω[21:18 | instance no. 2]{.aside}

[και]{.greek-added} οι θεμελιοι του τειχους της πολεως παντι λιθω τιμιω κεκοσμημενοι ο θεμελιος ο πρωτος ιασπις ο δευτερος σαπφειρος ο τριτος χαλκηδων ο τεταρτος σμαραγδος[21:19]{.aside}

ο πεμπτος σαρδονυξ ο εκτος σαρδιον ο [εβδομος]{.greek-omitted} [ευδομος]{.greek-added} χρυσολιθος ο ογδοος [βηρυλλος]{.greek-omitted} [βηρηλλος]{.greek-added} ο [ενατος]{.greek-omitted} [εννατος]{.greek-added} τοπαζιον ο δεκατος χρυσοπρασος ο ενδεκατος υακινθος ο δωδεκατος αμεθυσος[21:20]{.aside}

και οι δωδεκα πυλωνες δωδεκα μαργαριται ανα εις εκαστος των [πυλωνων]{.greek-omitted} [πυλων]{.greek-added} ην εξ ενος μαργαριτου και η πλατεια της πολεως [χρυσιον]{.greek-omitted} [καθαρον]{.greek-omitted} [ως]{.greek-omitted} [υελος]{.greek-omitted} [διαυγης]{.greek-omitted}[21:21]{.aside}

[και]{.greek-omitted} [οι]{.greek-omitted} [δωδεκα]{.greek-omitted} [πυλωνες]{.greek-omitted} [δωδεκα]{.greek-omitted} [μαργαριται]{.greek-omitted} [ανα]{.greek-omitted} [εις]{.greek-omitted} [εκαστος]{.greek-omitted} [των]{.greek-omitted} [πυλωνων]{.greek-omitted} [ην]{.greek-omitted} [εξ]{.greek-omitted} [ενος]{.greek-omitted} [μαργαριτου]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [πλατεια]{.greek-omitted} [της]{.greek-omitted} [πολεως]{.greek-omitted} χρυσιον καθαρον ως υελος διαυγης[21:21 | instance no. 2]{.aside}

και ναον ουκ ειδον εν αυτη ο γαρ [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ ναος αυτης [εστιν]{.greek-omitted} [εστι]{.greek-added} και το αρνιον[21:22]{.aside}

και η πολις ου χρειαν εχει του ηλιου ουδε της σεληνης ινα φαινωσιν αυτη [γαρ]{.greek-added} η [γαρ]{.greek-omitted} δοξα του [θεου]{.greek-abbr} εφωτισεν αυτην και ο λυχνος αυτης το αρνιον[21:23]{.aside}

και [περιπατησουσιν]{.greek-omitted} [περιπατησουσι]{.greek-added} τα εθνη δια του φωτος αυτης και οι βασιλεις της γης [φερουσιν]{.greek-omitted} [φερουσι]{.greek-added} [αυτω]{.greek-omitted} [την]{.greek-added} δοξαν [και]{.greek-omitted} [τιμην]{.greek-omitted} [των]{.greek-omitted} [αυτων]{.greek-added} [εθνων]{.greek-omitted} εις αυτην[21:24]{.aside}

και οι πυλωνες αυτης ου μη κλεισθωσιν ημερας νυξ γαρ ουκ εσται εκει[21:25]{.aside}

και [οισουσιν]{.greek-omitted} [οισουσι]{.greek-added} την δοξαν και την τιμην των εθνων εις αυτην[21:26]{.aside}

και ου μη εισελθη εις αυτην παν κοινον [και]{.greek-omitted} [ποιουν]{.greek-omitted} [βδελυγμα]{.greek-omitted} [και]{.greek-omitted} [ψευδος]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [οι]{.greek-omitted} [γεγραμμενοι]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [βιβλιω]{.greek-omitted} [της]{.greek-omitted} [ζωης]{.greek-omitted} [του]{.greek-omitted} [αρνιου]{.greek-omitted}[21:27]{.aside}

και [ο]{.greek-added} [ποιων]{.greek-added} [ου]{.greek-omitted} [μη]{.greek-omitted} [εισελθη]{.greek-omitted} [εις]{.greek-omitted} [αυτην]{.greek-omitted} [παν]{.greek-omitted} [κοινον]{.greek-omitted} [και]{.greek-omitted} [ποιουν]{.greek-omitted} βδελυγμα και ψευδος ει μη οι [γεγραμμενοι]{.greek-omitted} [εγγεγραμμενοι]{.greek-added} εν [τω]{.greek-omitted} [τη]{.greek-added} [βιβλιω]{.greek-omitted} [βιβλω]{.greek-added} της ζωης του αρνιου[21:27 | instance no. 2]{.aside}

### Chapter 22

και [εδειξεν]{.greek-omitted} [εδειξε]{.greek-added} μοι ποταμον [καθαρον]{.greek-omitted} υδατος ζωης λαμπρον ως [κρυσταλλον]{.greek-omitted} [κρυσταλον]{.greek-added} εκπορευομενον εκ του θρονου του [θεου]{.greek-abbr} και του αρνιου[22:1]{.aside}

εν μεσω της πλατειας αυτης και του ποταμου εντευθεν και [εκειθεν]{.greek-omitted} [εντευθεν]{.greek-added} ξυλον ζωης ποιουν καρπους δωδεκα κατα μηνα [αποδιδουναι]{.greek-added} εκαστον [αποδιδους]{.greek-omitted} τον καρπον αυτου και τα φυλλα του ξυλου εις θεραπειαν των εθνων[22:2]{.aside}

και παν καταθεμα ουκ εσται [ετι]{.greek-omitted} [εκει]{.greek-added} και ο θρονος του [θεου]{.greek-abbr} και του αρνιου εν αυτη εσται και οι δουλοι [αυτου]{.greek-omitted} [του]{.greek-added} [[θεου]{.greek-abbr}]{.greek-added} λατρευσουσιν αυτω[22:3]{.aside}

και [οψονται]{.greek-omitted} [το]{.greek-omitted} [προσωπον]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [ονομα]{.greek-omitted} [αυτου]{.greek-omitted} [επι]{.greek-omitted} [των]{.greek-omitted} [μετωπων]{.greek-omitted} [αυτων]{.greek-omitted}[22:4]{.aside}

[και]{.greek-omitted} οψονται το προσωπον αυτου και το ονομα αυτου επι των μετωπων αυτων[22:4 | instance no. 2]{.aside}

και νυξ ουκ εσται εκει και χρειαν ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} [φωτος]{.greek-added} λυχνου και φωτος ηλιου οτι [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} φωτιει αυτους και βασιλευσουσιν εις τους αιωνας των αιωνων[22:5]{.aside}

και λεγει μοι ουτοι οι λογοι πιστοι και αληθινοι και [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} των [πνευματων]{.greek-abbr} των προφητων [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} τον αγγελον αυτου δειξαι τοις δουλοις αυτου α δει γενεσθαι εν ταχει[22:6]{.aside}

και ιδου ερχομαι ταχυ μακαριος ο τηρων τους λογους της προφητειας του βιβλιου τουτου[22:7]{.aside}

καγω ιωαννης ο ακουων και βλεπων ταυτα και [οτε]{.greek-omitted} [οτι]{.greek-added} ηκουσα και [εβλεψα]{.greek-omitted} [επεσον]{.greek-omitted} [προσκυνησαι]{.greek-omitted} [εμπροσθεν]{.greek-omitted} [των]{.greek-omitted} [ποδων]{.greek-omitted} [του]{.greek-omitted} [αγγελου]{.greek-omitted} [του]{.greek-omitted} [δεικνυοντος]{.greek-omitted} [μοι]{.greek-omitted} [ταυτα]{.greek-omitted}[22:8]{.aside}

[καγω]{.greek-omitted} [ιωαννης]{.greek-omitted} [ο]{.greek-omitted} [ακουων]{.greek-omitted} [και]{.greek-omitted} [βλεπων]{.greek-omitted} [ταυτα]{.greek-omitted} [και]{.greek-omitted} οτε [ειδον]{.greek-added} [ηκουσα]{.greek-omitted} [και]{.greek-omitted} [εβλεψα]{.greek-omitted} επεσον προσκυνησαι εμπροσθεν των ποδων του αγγελου του δεικνυοντος μοι ταυτα[22:8 | instance no. 2]{.aside}

και λεγει μοι ορα μη [συνδουλος]{.greek-omitted} [συνδουλου]{.greek-added} σου ειμι και των αδελφων σου των προφητων [και]{.greek-omitted} των τηρουντων τους λογους του βιβλιου τουτου τω [θεω]{.greek-abbr} προσκυνησον[22:9]{.aside}

και λεγει μοι μη σφραγισης τους λογους της προφητειας του βιβλιου τουτου ο καιρος γαρ εγγυς εστιν[22:10]{.aside}

ο αδικων αδικησατω ετι και ο ρυπαρος ρυπαρευθητω ετι και ο δικαιος δικαιοσυνην ποιησατω ετι και ο αγιος αγιασθητω ετι[22:11]{.aside}

ιδου ερχομαι ταχυ και ο μισθος μου μετ εμου αποδουναι [ε]{.greek-added} [εκαστω]{.greek-omitted} [ως]{.greek-omitted} [το]{.greek-omitted} [εργον]{.greek-omitted} [εσται]{.greek-omitted} [αυτου]{.greek-omitted}[22:12]{.aside}

[ιδου]{.greek-omitted} [ερχομαι]{.greek-omitted} [ταχυ]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [μισθος]{.greek-omitted} [μου]{.greek-omitted} [μετ]{.greek-omitted} [εμου]{.greek-omitted} [αποδουναι]{.greek-omitted} [εκαστω]{.greek-omitted} [καστω]{.greek-added} ως το εργον εσται αυτου[22:12 | instance no. 2]{.aside}

εγω το [αλφα]{.greek-omitted} [ἄλφα]{.greek-added} και το [ω]{.greek-abbr} ο πρωτος και ο εσχατος η αρχη και το τελος[22:13]{.aside}

μακαριοι οι ποιουντες τας εντολας αυτου ινα εσται η εξουσια αυτων επι το ξυλον της ζωης και τοις [πυλωσιν]{.greek-omitted} [πυλωνις]{.greek-added} εισελθωσιν εις την πολιν[22:14]{.aside}

εξω οι κυνες και οι φαρμακοι και οι πορνοι και οι φονεις και οι ειδωλολατραι και [πας]{.greek-omitted} [πασων]{.greek-added} [ο]{.greek-added} φιλων και ποιων ψευδος[22:15]{.aside}

εγω [ιησους]{.greek-abbr} επεμψα τον αγγελον μου μαρτυρησαι υμιν ταυτα [επι]{.greek-omitted} ταις εκκλησιαις εγω ειμι η ριζα και το γενος [δαυιδ]{.greek-abbr} ο αστηρ ο λαμπρος ο πρωινος[22:16]{.aside}

και το [πνευμα]{.greek-abbr} και η νυμφη [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} ερχου και ο ακουων [ειπατω]{.greek-omitted} [ειπαται]{.greek-added} ερχου και ο διψων ερχεσθω ο θελων λαβετω υδωρ ζωης δωρεαν[22:17]{.aside}

μαρτυρω εγω παντι τω ακουοντι τους λογους της προφητειας του βιβλιου τουτου εαν τις επιθη επ [αυτα]{.greek-omitted} [αυτω]{.greek-added} [επιθησαι]{.greek-omitted} [επιθησοι]{.greek-added} ο [θεος]{.greek-abbr} επ αυτον τας πληγας τας γεγραμμενας εν τω βιβλιω τουτω[22:18]{.aside}

και εαν τις [αφελη]{.greek-omitted} [αφελοι]{.greek-added} απο των λογων του βιβλιου της προφητειας ταυτης αφελοι ο [θεος]{.greek-abbr} το μερος αυτου απο του ξυλου της ζωης και εκ της πολεως της αγιας των γεγραμμενων εν τω βιβλιω τουτω[22:19]{.aside}

λεγει ο μαρτυρων ταυτα ναι ερχομαι ταχυ αμην ναι ερχου [κυριε]{.greek-abbr} [ιησου]{.greek-abbr}[22:20]{.aside}

η χαρις του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} [χριστου]{.greek-omitted} μετα παντων των αγιων αμην [τελος]{.greek-added} [αριθμος]{.greek-added} [διακοσιοστος]{.greek-added} [δεκατος]{.greek-added} [εννατος]{.greek-added} [φυλλα]{.greek-added} [εκατον]{.greek-added} [εικοσιν]{.greek-added} [εν]{.greek-added} [εμετρηθη]{.greek-added} [τω]{.greek-added} [1898]{.greek-added}[22:21]{.aside}

