---
title: "Collation of Byz^RP^ vs 32718 (2718)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 2718 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=32718).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 2718                                   	| λογος                              	|
| 2718 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 2718 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 2718               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 2718                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 2718 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 2718                                                     	| [―]{.gap}                        	|
:::

## Acts

### Chapter 1

τον μεν πρωτον λογον εποιησαμην περι παντων ω θεοφιλε ων ηρξατο ο [ιησους]{.greek-abbr} ποιειν τε και διδασκειν[1:1]{.aside}

αχρι ης ημερας εντειλαμενος τοις αποστολοις δια [πνευματος]{.greek-abbr} αγιου [ους]{.greek-omitted} [εξελεξατο]{.greek-omitted} ανεληφθη[1:2]{.aside}

οις και παρεστησεν εαυτον [ζωντα]{.greek-omitted} [μετα]{.greek-omitted} [το]{.greek-omitted} [παθειν]{.greek-omitted} [αυτον]{.greek-omitted} [εν]{.greek-omitted} [πολλοις]{.greek-omitted} [τεκμηριοις]{.greek-omitted} [δι]{.greek-omitted} [ημερων]{.greek-omitted} [τεσσαρακοντα]{.greek-omitted} [οπτανομενος]{.greek-omitted} [αυτοις]{.greek-omitted} [και]{.greek-omitted} [λεγων]{.greek-omitted} [τα]{.greek-omitted} [περι]{.greek-omitted} [της]{.greek-omitted} [βασιλειας]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted}[1:3]{.aside}

[οις]{.greek-omitted} [και]{.greek-omitted} [παρεστησεν]{.greek-omitted} [εαυτον]{.greek-omitted} ζωντα μετα το παθειν αυτον εν πολλοις τεκμηριοις δι ημερων τεσσαρακοντα οπτανομενος αυτοις και λεγων τα περι της βασιλειας του [θεου]{.greek-abbr}[1:3 | instance no. 2]{.aside}

και συναλιζομενος παρηγγειλεν αυτοις απο ιεροσολυμων μη χωριζεσθαι αλλα περιμενειν την επαγγελιαν του [πατρος]{.greek-abbr} ην ηκουσατε μου[1:4]{.aside}

οτι ιωαννης μεν εβαπτισεν υδατι υμεις δε βαπτισθησεσθε εν [πνευματι]{.greek-abbr} αγιω ου μετα πολλας ταυτας ημερας[1:5]{.aside}

οι μεν ουν συνελθοντες επηρωτων αυτον λεγοντες [κυριε]{.greek-abbr} ει εν τω χρονω τουτω αποκαθιστανεις την βασιλειαν τω [ισραηλ]{.greek-abbr}[1:6]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε προς αυτους ουχ υμων [εστιν]{.greek-omitted} [εστι]{.greek-added} [γνωναι]{.greek-omitted} [γνοναι]{.greek-added} χρονους η καιρους ους ο [πατηρ]{.greek-abbr} εθετο εν τη ιδια εξουσια[1:7]{.aside}

αλλα ληψεσθε δυναμιν [εξ]{.greek-added} [υψους]{.greek-added} επελθοντος του αγιου [πνευματος]{.greek-abbr} εφ υμας και εσεσθε μοι μαρτυρες εν τε [ιερουσαλημ]{.greek-abbr} και εν παση τη ιουδαια και σαμαρεια και εως εσχατου της γης[1:8]{.aside}

και ταυτα ειπων βλεποντων αυτων επηρθη και νεφελη υπελαβεν αυτον απο των οφθαλμων αυτων[1:9]{.aside}

και ως ατενιζοντες ησαν εις τον [ουρανον]{.greek-abbr} πορευομενου αυτου και ιδου ανδρες δυο [παρειστηκεισαν]{.greek-omitted} [παριστηκεισαν]{.greek-added} αυτοις εν εσθητι λευκη[1:10]{.aside}

οι και ειπον ανδρες γαλιλαιοι τι εστηκατε [εμβλεποντες]{.greek-omitted} [βλεποντες]{.greek-added} [εις]{.greek-omitted} [τον]{.greek-omitted} [ουρανον]{.greek-omitted} [ουτος]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [ο]{.greek-omitted} [αναληφθεις]{.greek-omitted} [αφ]{.greek-omitted} [υμων]{.greek-omitted} εις τον [ουρανον]{.greek-abbr} ουτως ελευσεται [παλιν]{.greek-added} ον τροπον εθεασασθε αυτον πορευομενον εις τον [ουρανον]{.greek-abbr}[1:11]{.aside}

τοτε υπεστρεψαν εις [ιερουσαλημ]{.greek-abbr} απο ορους του καλουμενου ελαιωνος ο εστιν εγγυς [ιερουσαλημ]{.greek-abbr} σαββατου [εχον]{.greek-omitted} [εχων]{.greek-added} οδον[1:12]{.aside}

και οτε εισηλθον ανεβησαν εις το υπερωον ου ησαν καταμενοντες ο τε πετρος και ιακωβος και ιωαννης και ανδρεας φιλιππος και θωμας βαρθολομαιος και ματθαιος ιακωβος [ο]{.greek-added} [του]{.greek-added} αλφαιου και σιμων ο ζηλωτης και ιουδας ιακωβου[1:13]{.aside}

ουτοι παντες ησαν προσκαρτερουντες ομοθυμαδον τη προσευχη και τη δεησει συν [γυναιξιν]{.greek-omitted} [γυναιξι]{.greek-added} και μαρια τη [μητρι]{.greek-abbr} του [ιησου]{.greek-abbr} και συν τοις αδελφοις αυτου[1:14]{.aside}

και εν [ταις]{.greek-omitted} [ημεραις]{.greek-omitted} [ταυταις]{.greek-omitted} [αναστας]{.greek-omitted} [πετρος]{.greek-omitted} [εν]{.greek-omitted} [μεσω]{.greek-omitted} [των]{.greek-omitted} [μαθητων]{.greek-omitted} [ειπεν]{.greek-omitted} [ην]{.greek-omitted} [τε]{.greek-omitted} [οχλος]{.greek-omitted} [ονοματων]{.greek-omitted} [επι]{.greek-omitted} [το]{.greek-omitted} [αυτο]{.greek-omitted} [ως]{.greek-omitted} [εκατον]{.greek-omitted} [εικοσι]{.greek-omitted}[1:15]{.aside}

[και]{.greek-omitted} [εν]{.greek-omitted} ταις ημεραις ταυταις αναστας πετρος εν μεσω των μαθητων ειπεν ην τε οχλος ονοματων επι το αυτο ως εκατον εικοσι[1:15 | instance no. 2]{.aside}

ανδρες αδελφοι εδει πληρωθηναι την γραφην ταυτην ην [προειπεν]{.greek-omitted} [προειπε]{.greek-added} το [πνευμα]{.greek-abbr} το αγιον δια στοματος [δαυιδ]{.greek-abbr} περι ιουδα του γενομενου οδηγου τοις [συλλαβουσιν]{.greek-omitted} [συλλαβουσι]{.greek-added} τον [ιησουν]{.greek-abbr}[1:16]{.aside}

οτι κατηριθμημενος ην συν ημιν και [ελαχεν]{.greek-omitted} [ελαχε]{.greek-added} τον κληρον της διακονιας ταυτης[1:17]{.aside}

ουτος μεν ουν εκτησατο χωριον εκ μισθου της αδικιας και πρηνης γενομενος [ελακησεν]{.greek-omitted} [ελακησε]{.greek-added} μεσος και εξεχυθη παντα τα σπλαγχνα αυτου[1:18]{.aside}

και γνωστον εγενετο [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις κατοικουσιν [ιερουσαλημ]{.greek-abbr} ωστε κληθηναι το χωριον εκεινο τη ιδια διαλεκτω αυτων ακελδαμα τουτ [εστιν]{.greek-omitted} [εστι]{.greek-added} χωριον αιματος[1:19]{.aside}

γεγραπται γαρ εν βιβλω ψαλμων γενηθητω η επαυλις αυτου ερημος και μη εστω ο κατοικων εν αυτη και την επισκοπην αυτου λαβοι ετερος[1:20]{.aside}

δει ουν των συνελθοντων ημιν ανδρων εν παντι χρονω εν ω [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} και εξηλθεν εφ ημας ο [κυριος]{.greek-abbr} [ιησους]{.greek-abbr}[1:21]{.aside}

αρξαμενος απο του βαπτισματος ιωαννου εως της ημερας ης ανεληφθη αφ ημων μαρτυρα της αναστασεως αυτου γενεσθαι συν ημιν ενα τουτων[1:22]{.aside}

και εστησαν δυο ιωσηφ τον καλουμενον βαρσαβαν ος επεκληθη ιουστος και ματθιαν[1:23]{.aside}

και προσευξαμενοι ειπον συ [κυριε]{.greek-abbr} καρδιογνωστα παντων αναδειξον ον εξελεξω εκ τουτων των δυο ενα[1:24]{.aside}

λαβειν τον κληρον της διακονιας ταυτης και αποστολης εξ ης παρεβη ιουδας πορευθηναι εις τον τοπον τον ιδιον[1:25]{.aside}

και εδωκαν κληρους αυτων και επεσεν ο κληρος επι ματθιαν και συγκατεψηφισθη μετα των ενδεκα αποστολων[1:26]{.aside}

### Chapter 2

και εν τω συμπληρουσθαι την ημεραν της πεντηκοστης ησαν [απαντες]{.greek-omitted} [παντες]{.greek-added} [οι]{.greek-added} [αποστολοι]{.greek-added} ομοθυμαδον επι το αυτο[2:1]{.aside}

και εγενετο αφνω εκ του [ουρανου]{.greek-abbr} ηχος ωσπερ φερομενης πνοης βιαιας και επληρωσεν [ολον]{.greek-omitted} [τον]{.greek-omitted} [οικον]{.greek-omitted} [ου]{.greek-omitted} [ησαν]{.greek-omitted} [καθημενοι]{.greek-omitted}[2:2]{.aside}

[και]{.greek-omitted} [εγενετο]{.greek-omitted} [αφνω]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [ηχος]{.greek-omitted} [ωσπερ]{.greek-omitted} [φερομενης]{.greek-omitted} [πνοης]{.greek-omitted} [βιαιας]{.greek-omitted} [και]{.greek-omitted} [επληρωσεν]{.greek-omitted} ολον τον οικον ου ησαν καθημενοι[2:2 | instance no. 2]{.aside}

και ωφθησαν αυτοις διαμεριζομεναι γλωσσαι ωσει πυρος [εκαθισεν]{.greek-omitted} [εκαθισε]{.greek-added} τε εφ ενα εκαστον αυτων[2:3]{.aside}

και επλησθησαν απαντες [πνευματος]{.greek-abbr} αγιου και ηρξαντο λαλειν ετεραις γλωσσαις καθως το [πνευμα]{.greek-abbr} εδιδου αυτοις [αποφθεγγεσθαι]{.greek-omitted} [αποφθεγγεσθε]{.greek-added}[2:4]{.aside}

ησαν δε εν [ιερουσαλημ]{.greek-abbr} κατοικουντες ιουδαιοι ανδρες ευλαβεις απο παντος εθνους των υπο [τον]{.greek-omitted} [των]{.greek-added} [ουρανον]{.greek-omitted} [[ουρανων]{.greek-abbr}]{.greek-added}[2:5]{.aside}

γενομενης δε της φωνης ταυτης [συνηλθεν]{.greek-omitted} [συνηλθε]{.greek-added} το πληθος και συνεχυθη οτι ηκουον εις εκαστος [αυτων]{.greek-added} τη ιδια διαλεκτω λαλουντων αυτων[2:6]{.aside}

εξισταντο δε παντες και εθαυμαζον λεγοντες προς αλληλους ουκ ιδου παντες ουτοι εισιν οι λαλουντες γαλιλαιοι[2:7]{.aside}

και πως ημεις ακουομεν εκαστος τη ιδια διαλεκτω ημων εν η [εγεννηθημεν]{.greek-omitted} [εγενηθημεν]{.greek-added}[2:8]{.aside}

παρθοι [και]{.greek-omitted} μηδοι και ελαμιται και οι κατοικουντες την μεσοποταμιαν ιουδαιαν τε και καππαδοκιαν ποντον και την ασιαν[2:9]{.aside}

φρυγιαν τε και παμφυλιαν αιγυπτον και τα μερη της λιβυης της κατα κυρηνην και οι επιδημουντες ρωμαιοι [ιουδαιοι]{.greek-omitted} [τε]{.greek-omitted} [και]{.greek-omitted} [προσηλυτοι]{.greek-omitted}[2:10]{.aside}

[ιουδαιοι]{.greek-added} [τε]{.greek-added} [και]{.greek-added} [προσηλυτοι]{.greek-added} κρητες και αραβες ακουομεν λαλουντων αυτων ταις ημετεραις γλωσσαις τα μεγαλεια του [θεου]{.greek-abbr}[2:11]{.aside}

εξισταντο δε παντες και διηπορουν αλλος προς αλλον λεγοντες τι αν θελοι τουτο ειναι[2:12]{.aside}

ετεροι δε χλευαζοντες ελεγον οτι γλευκους μεμεστωμενοι [εισιν]{.greek-omitted} [εισι]{.greek-added}[2:13]{.aside}

σταθεις δε [ο]{.greek-added} πετρος συν τοις ενδεκα [επηρεν]{.greek-omitted} [επηρε]{.greek-added} την φωνην αυτου και απεφθεγξατο αυτοις ανδρες ιουδαιοι και οι κατοικουντες [ιερουσαλημ]{.greek-abbr} απαντες τουτο υμιν γνωστον εστω και [ενωτισασθε]{.greek-omitted} [ενωτισασθαι]{.greek-added} τα ρηματα μου[2:14]{.aside}

ου γαρ ως υμεις υπολαμβανετε ουτοι μεθυουσιν [εστιν]{.greek-omitted} [εστι]{.greek-added} γαρ ωρα τριτη της ημερας[2:15]{.aside}

αλλα τουτο [εστιν]{.greek-omitted} [εστι]{.greek-added} το ειρημενον δια του προφητου ιωηλ[2:16]{.aside}

και εσται εν ταις εσχαταις ημεραις λεγει ο [θεος]{.greek-abbr} εκχεω απο του [πνευματος]{.greek-abbr} μου επι πασαν σαρκα και προφητευσουσιν οι υιοι υμων και αι [θυγατερες]{.greek-omitted} [θυγατεραις]{.greek-added} υμων και οι νεανισκοι υμων ορασεις οψονται και οι πρεσβυτεροι υμων ενυπνια [ενυπνιασθησονται]{.greek-omitted} [ενυπνιασθη]{.greek-added}[2:17]{.aside}

[και]{.greek-omitted} [εσται]{.greek-omitted} [εν]{.greek-omitted} [ταις]{.greek-omitted} [εσχαταις]{.greek-omitted} [ημεραις]{.greek-omitted} [λεγει]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [εκχεω]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [πνευματος]{.greek-omitted} [μου]{.greek-omitted} [επι]{.greek-omitted} [πασαν]{.greek-omitted} [σαρκα]{.greek-omitted} [και]{.greek-omitted} [προφητευσουσιν]{.greek-omitted} [οι]{.greek-omitted} [υιοι]{.greek-omitted} [υμων]{.greek-omitted} [και]{.greek-omitted} [αι]{.greek-omitted} [θυγατερες]{.greek-omitted} [υμων]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [νεανισκοι]{.greek-omitted} [υμων]{.greek-omitted} [ορασεις]{.greek-omitted} [οψονται]{.greek-omitted} [σονται]{.greek-added} [και]{.greek-omitted} [οι]{.greek-omitted} [πρεσβυτεροι]{.greek-omitted} [υμων]{.greek-omitted} [ενυπνια]{.greek-omitted} [ενυπνιασθησονται]{.greek-omitted}[2:17 | instance no. 2]{.aside}

και γε επι τους δουλους μου και επι τας δουλας μου εν ταις ημεραις εκειναις εκχεω απο του [πνευματος]{.greek-abbr} μου και [προφητευσουσιν]{.greek-omitted} [προφητευσουσι]{.greek-added}[2:18]{.aside}

και δωσω τερατα εν τω [ουρανω]{.greek-abbr} ανω και σημεια επι της γης κατω αιμα και πυρ και ατμιδα καπνου[2:19]{.aside}

ο ηλιος μεταστραφησεται εις σκοτος και η σεληνη εις αιμα πριν [η]{.greek-omitted} ελθειν την ημεραν [κυριου]{.greek-abbr} την μεγαλην και επιφανη[2:20]{.aside}

και εσται πας ος αν επικαλεσηται το ονομα [κυριου]{.greek-abbr} σωθησεται[2:21]{.aside}

ανδρες ισραηλιται ακουσατε τους λογους τουτους [ιησουν]{.greek-abbr} τον ναζωραιον ανδρα απο του [θεου]{.greek-abbr} αποδεδειγμενον εις [υμας]{.greek-omitted} [ημας]{.greek-added} [δυναμεσιν]{.greek-omitted} [δυναμεσι]{.greek-added} και [τερασιν]{.greek-omitted} [τερασι]{.greek-added} και σημειοις οις εποιησεν [ο]{.greek-added} [[θεος]{.greek-abbr}]{.greek-added} δι αυτου [ο]{.greek-omitted} [θεος]{.greek-omitted} εν μεσω υμων καθως και αυτοι οιδατε[2:22]{.aside}

τουτον τη ωρισμενη βουλη και προγνωσει του [θεου]{.greek-abbr} εκδοτον λαβοντες δια χειρων ανομων προσπηξαντες [ανειλετε]{.greek-omitted} [ανειλατε]{.greek-added}[2:23]{.aside}

ον ο [θεος]{.greek-abbr} ανεστησεν [εκ]{.greek-added} [νεκρων]{.greek-added} λυσας τας ωδινας του θανατου καθοτι ουκ ην δυνατον κρατεισθαι αυτον υπ αυτου[2:24]{.aside}

[δαυιδ]{.greek-abbr} γαρ λεγει εις αυτον [προωρωμην]{.greek-omitted} [προορωμην]{.greek-added} τον [κυριον]{.greek-abbr} ενωπιον μου δια παντος οτι εκ δεξιων μου εστιν ινα μη σαλευθω[2:25]{.aside}

δια τουτο [ευφρανθη]{.greek-omitted} [ηυφρανθη]{.greek-added} η καρδια μου και ηγαλλιασατο η γλωσσα μου ετι δε και η σαρξ μου κατασκηνωσει επ ελπιδι[2:26]{.aside}

οτι ουκ εγκαταλειψεις την ψυχην μου εις αδου ουδε δωσεις τον οσιον σου ιδειν διαφθοραν[2:27]{.aside}

εγνωρισας μοι οδους ζωης πληρωσεις με ευφροσυνης μετα του προσωπου σου[2:28]{.aside}

ανδρες αδελφοι εξον ειπειν μετα παρρησιας προς υμας περι του πατριαρχου [δαυιδ]{.greek-abbr} οτι και [ετελευτησεν]{.greek-omitted} [ετελευτησε]{.greek-added} και εταφη και το μνημα αυτου εστιν εν ημιν αχρι της ημερας ταυτης[2:29]{.aside}

προφητης ουν υπαρχων και [ειδως]{.greek-omitted} [ιδως]{.greek-added} οτι ορκω ωμοσεν αυτω ο [θεος]{.greek-abbr} εκ καρπου της οσφυος αυτου το κατα σαρκα αναστησειν τον [χριστον]{.greek-abbr} καθισαι επι του θρονου αυτου[2:30]{.aside}

προιδων [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} περι της αναστασεως [του]{.greek-omitted} [αυτου]{.greek-added} [χριστου]{.greek-omitted} οτι [ου]{.greek-omitted} [ουκ]{.greek-added} [κατελειφθη]{.greek-omitted} [εγκατελειφθη]{.greek-added} η ψυχη αυτου εις [αδου]{.greek-omitted} [αδην]{.greek-added} ουδε η σαρξ αυτου [ειδεν]{.greek-omitted} [ειδε]{.greek-added} διαφθοραν[2:31]{.aside}

τουτον τον [ιησουν]{.greek-abbr} [ανεστησεν]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [ου]{.greek-omitted} [παντες]{.greek-omitted} [ημεις]{.greek-omitted} [εσμεν]{.greek-omitted} [μαρτυρες]{.greek-omitted}[2:32]{.aside}

[τουτον]{.greek-omitted} [τον]{.greek-omitted} [ιησουν]{.greek-omitted} ανεστησεν ο [θεος]{.greek-abbr} ου παντες ημεις εσμεν μαρτυρες[2:32 | instance no. 2]{.aside}

τη δεξια ουν του [θεου]{.greek-abbr} υψωθεις την τε επαγγελιαν του αγιου [πνευματος]{.greek-abbr} λαβων παρα του [πατρος]{.greek-abbr} [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} τουτο ο νυν υμεις βλεπετε και ακουετε[2:33]{.aside}

ου γαρ [δαυιδ]{.greek-abbr} ανεβη εις τους [ουρανους]{.greek-abbr} λεγει δε αυτος ειπεν ο [κυριος]{.greek-abbr} τω [κυριω]{.greek-abbr} μου καθου εκ δεξιων μου[2:34]{.aside}

εως αν θω τους εχθρους σου υποποδιον των ποδων σου[2:35]{.aside}

ασφαλως ουν γινωσκετω πας οικος [ισραηλ]{.greek-abbr} οτι και [κυριον]{.greek-abbr} και [χριστον]{.greek-abbr} αυτον ο [θεος]{.greek-abbr} [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} τουτον τον [ιησουν]{.greek-abbr} ον υμεις [εσταυρωσατε]{.greek-abbr}[2:36]{.aside}

ακουσαντες δε κατενυγησαν τη καρδια ειπον τε προς τον πετρον και τους λοιπους αποστολους τι ποιησομεν ανδρες αδελφοι[2:37]{.aside}

πετρος δε [εφη]{.greek-omitted} προς αυτους [ειπε]{.greek-added} μετανοησατε και βαπτισθητω εκαστος υμων επι τω ονοματι [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} εις αφεσιν αμαρτιων και ληψεσθε την δωρεαν του αγιου [πνευματος]{.greek-abbr}[2:38]{.aside}

υμιν γαρ εστιν η επαγγελια και τοις τεκνοις υμων και [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις εις μακραν οσους αν προσκαλεσηται [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ημων[2:39]{.aside}

ετεροις τε λογοις [πλειοσιν]{.greek-omitted} [πλειοσι]{.greek-added} διεμαρτυρετο και παρεκαλει λεγων σωθητε απο της γενεας της σκολιας ταυτης[2:40]{.aside}

οι μεν ουν [ασμενως]{.greek-omitted} αποδεξαμενοι τον λογον αυτου εβαπτισθησαν [και]{.greek-omitted} [προσετεθησαν]{.greek-omitted} τη ημερα εκεινη ψυχαι ωσει τρισχιλιαι[2:41]{.aside}

ησαν δε προσκαρτερουντες τη διδαχη των αποστολων και τη κοινωνια και τη κλασει του αρτου και ταις προσευχαις[2:42]{.aside}

εγενετο δε παση ψυχη φοβος πολλα τε τερατα και σημεια δια των αποστολων εγινετο[2:43]{.aside}

παντες δε οι πιστευοντες ησαν επι το αυτο και ειχον απαντα κοινα[2:44]{.aside}

και τα κτηματα και τας υπαρξεις επιπρασκον και διεμεριζον αυτα [πασιν]{.greek-omitted} [πασι]{.greek-added} καθοτι αν τις χρειαν [ειχεν]{.greek-omitted} [ειχε]{.greek-added}[2:45]{.aside}

καθ ημεραν τε προσκαρτερουντες ομοθυμαδον εν τω ιερω κλωντες τε κατ οικον αρτον μετελαμβανον τροφης εν αγαλλιασει και αφελοτητι καρδιας[2:46]{.aside}

αινουντες τον [θεον]{.greek-abbr} και εχοντες χαριν προς ολον τον λαον ο δε [κυριος]{.greek-abbr} [προσετιθει]{.greek-omitted} [προσετιθη]{.greek-added} τους σωζομενους [καθ]{.greek-omitted} [ημεραν]{.greek-omitted} [τη]{.greek-omitted} [εκκλησια]{.greek-omitted}[2:47]{.aside}

[αινουντες]{.greek-omitted} [τον]{.greek-omitted} [θεον]{.greek-omitted} [και]{.greek-omitted} [εχοντες]{.greek-omitted} [χαριν]{.greek-omitted} [προς]{.greek-omitted} [ολον]{.greek-omitted} [τον]{.greek-omitted} [λαον]{.greek-omitted} [ο]{.greek-omitted} [δε]{.greek-omitted} [κυριος]{.greek-omitted} [προσετιθει]{.greek-omitted} [τους]{.greek-omitted} [σωζομενους]{.greek-omitted} καθ ημεραν τη εκκλησια[2:47 | instance no. 2]{.aside}

### Chapter 3

[πετρος]{.greek-added} [επι]{.greek-omitted} [το]{.greek-omitted} [αυτο]{.greek-omitted} δε [πετρος]{.greek-omitted} και ιωαννης ανεβαινον εις το ιερον επι την ωραν της προσευχης την [ενατην]{.greek-omitted} [εννατην]{.greek-added}[3:1]{.aside}

και τις ανηρ χωλος εκ κοιλιας [μητρος]{.greek-abbr} αυτου υπαρχων εβασταζετο ον ετιθουν καθ ημεραν προς την θυραν του ιερου την λεγομενην ωραιαν του αιτειν ελεημοσυνην παρα των εισπορευομενων εις το ιερον[3:2]{.aside}

ος ιδων πετρον και ιωαννην μελλοντας εισιεναι εις το ιερον ηρωτα ελεημοσυνην[3:3]{.aside}

ατενισας δε πετρος εις αυτον συν τω ιωαννη [ειπεν]{.greek-omitted} [ειπε]{.greek-added} βλεψον εις ημας[3:4]{.aside}

ο δε επειχεν αυτοις προσδοκων τι παρ αυτων λαβειν[3:5]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε πετρος αργυριον και χρυσιον ουχ υπαρχει μοι ο δε εχω τουτο σοι διδωμι εν τω ονοματι [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} του ναζωραιου [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} και περιπατει[3:6]{.aside}

και [κρατησας]{.greek-added} [πιασας]{.greek-omitted} [αυτον]{.greek-omitted} της δεξιας χειρος [αυτου]{.greek-added} ηγειρεν [αυτον]{.greek-added} παραχρημα δε εστερεωθησαν αυτου αι βασεις και τα σφυρα[3:7]{.aside}

και εξαλλομενος εστη και περιεπατει και [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} συν αυτοις εις το ιερον περιπατων και αλλομενος και αινων τον [θεον]{.greek-abbr}[3:8]{.aside}

και ειδεν αυτον πας ο λαος περιπατουντα και αινουντα τον [θεον]{.greek-abbr}[3:9]{.aside}

επεγινωσκον τε αυτον οτι [ουτος]{.greek-omitted} [αυτος]{.greek-added} ην ο προς την ελεημοσυνην καθημενος επι τη ωραια πυλη του ιερου και επλησθησαν θαμβους και εκστασεως επι τω συμβεβηκοτι αυτω[3:10]{.aside}

κρατουντος δε του ιαθεντος χωλου τον πετρον και ιωαννην [συνεδραμεν]{.greek-omitted} [συνεδραμον]{.greek-added} προς αυτους πας ο λαος επι τη στοα τη καλουμενη σολομωντος εκθαμβοι[3:11]{.aside}

ιδων δε πετρος απεκρινατο προς τον λαον ανδρες ισραηλιται τι θαυμαζετε επι τουτω η ημιν τι ατενιζετε ως ιδια δυναμει η ευσεβεια [πεποιηκοσιν]{.greek-omitted} [πεποιηκοσι]{.greek-added} του περιπατειν αυτον[3:12]{.aside}

ο [θεος]{.greek-abbr} αβρααμ και ισαακ και ιακωβ ο [θεος]{.greek-abbr} των [πατερων]{.greek-abbr} ημων [εδοξασεν]{.greek-omitted} [εδοξασε]{.greek-added} τον παιδα αυτου [ιησουν]{.greek-abbr} ον [υμεις]{.greek-omitted} [ημεις]{.greek-added} μεν παρεδωκατε και ηρνησασθε αυτον [κα]{.greek-added} [κατα]{.greek-omitted} [προσωπον]{.greek-omitted} [πιλατου]{.greek-omitted} [κριναντος]{.greek-omitted} [εκεινου]{.greek-omitted} [απολυειν]{.greek-omitted}[3:13]{.aside}

[τα]{.greek-added} [ο]{.greek-omitted} [θεος]{.greek-omitted} [αβρααμ]{.greek-omitted} [και]{.greek-omitted} [ισαακ]{.greek-omitted} [και]{.greek-omitted} [ιακωβ]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [των]{.greek-omitted} [πατερων]{.greek-omitted} [ημων]{.greek-omitted} [εδοξασεν]{.greek-omitted} [τον]{.greek-omitted} [παιδα]{.greek-omitted} [αυτου]{.greek-omitted} [ιησουν]{.greek-omitted} [ον]{.greek-omitted} [υμεις]{.greek-omitted} [μεν]{.greek-omitted} [παρεδωκατε]{.greek-omitted} [και]{.greek-omitted} [ηρνησασθε]{.greek-omitted} [αυτον]{.greek-omitted} [κατα]{.greek-omitted} προσωπον πιλατου κριναντος εκεινου απολυειν[3:13 | instance no. 2]{.aside}

υμεις δε τον αγιον και δικαιον ηρνησασθε και ητησασθε ανδρα φονεα χαρισθηναι υμιν[3:14]{.aside}

τον δε αρχηγον της ζωης απεκτεινατε ον ο [θεος]{.greek-abbr} ηγειρεν εκ νεκρων ου ημεις μαρτυρες εσμεν[3:15]{.aside}

και επι τη πιστει του ονοματος αυτου τουτον ον θεωρειτε και οιδατε [εστερεωσεν]{.greek-omitted} [εστερεωσε]{.greek-added} το ονομα αυτου και η πιστις η δι αυτου εδωκεν αυτω την ολοκληριαν ταυτην απεναντι παντων υμων[3:16]{.aside}

και νυν αδελφοι οιδα οτι κατα αγνοιαν επραξατε ωσπερ και οι αρχοντες υμων[3:17]{.aside}

ο δε [θεος]{.greek-abbr} α [προκατηγγειλεν]{.greek-omitted} [προκατηγγειλε]{.greek-added} δια στοματος παντων των προφητων [αυτου]{.greek-omitted} παθειν τον [χριστον]{.greek-abbr} [αυτου]{.greek-added} επληρωσεν ουτως[3:18]{.aside}

μετανοησατε ουν και επιστρεψατε εις το εξαλειφθηναι υμων τας αμαρτιας [οπως]{.greek-omitted} [αν]{.greek-omitted} [ελθωσιν]{.greek-omitted} [καιροι]{.greek-omitted} [αναψυξεως]{.greek-omitted} [απο]{.greek-omitted} [προσωπου]{.greek-omitted} [του]{.greek-omitted} [κυριου]{.greek-omitted}[3:19]{.aside}

[οπως]{.greek-added} [αν]{.greek-added} [ελθωσι]{.greek-added} [καιροι]{.greek-added} [αναψυξεως]{.greek-added} [απο]{.greek-added} [προσωπου]{.greek-added} [[κυριου]{.greek-abbr}]{.greek-added} και [αποστειλη]{.greek-omitted} [αποστειλει]{.greek-added} τον προκεχειρισμενον [υμιν]{.greek-omitted} [ημιν]{.greek-added} [[ιησουν]{.greek-abbr}]{.greek-added} [χριστον]{.greek-abbr} [ιησουν]{.greek-omitted}[3:20]{.aside}

ον δει [ουρανον]{.greek-abbr} μεν δεξασθαι αχρι χρονων αποκαταστασεως παντων [ων]{.greek-omitted} [ελαλησεν]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [δια]{.greek-omitted} [στοματος]{.greek-omitted} [παντων]{.greek-omitted} των αγιων αυτου προφητων [των]{.greek-added} απ αιωνος[3:21]{.aside}

[μωσης]{.greek-omitted} [μωυσης]{.greek-added} μεν γαρ προς τους [πατερας]{.greek-abbr} ειπεν οτι προφητην υμιν αναστησει [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} [ημων]{.greek-omitted} [υμων]{.greek-added} εκ των αδελφων υμων ως εμε αυτου ακουσεσθε κατα παντα οσα αν λαληση προς υμας[3:22]{.aside}

εσται δε πασα ψυχη [ητις]{.greek-omitted} [ειτις]{.greek-added} εαν μη ακουση του προφητου εκεινου εξολοθρευθησεται εκ του λαου[3:23]{.aside}

και παντες δε οι προφηται απο σαμουηλ και των καθεξης οσοι ελαλησαν και [κατηγγειλαν]{.greek-omitted} [απηγγειλαν]{.greek-added} τας ημερας ταυτας[3:24]{.aside}

υμεις εστε υιοι των προφητων και της διαθηκης ης διεθετο ο [θεος]{.greek-abbr} προς τους [πατερας]{.greek-abbr} [ημων]{.greek-omitted} [υμων]{.greek-added} λεγων προς αβρααμ και εν τω σπερματι σου ενευλογηθησονται πασαι αι πατριαι της γης[3:25]{.aside}

υμιν πρωτον ο [θεος]{.greek-abbr} αναστησας τον παιδα αυτου [ιησουν]{.greek-abbr} απεστειλεν αυτον ευλογουντα υμας εν τω αποστρεφειν εκαστον απο των πονηριων υμων[3:26]{.aside}

### Chapter 4

λαλουντων [δε]{.greek-omitted} [αυτων]{.greek-omitted} [προς]{.greek-omitted} [τον]{.greek-omitted} [λαον]{.greek-omitted} [επεστησαν]{.greek-omitted} [αυτοις]{.greek-omitted} [οι]{.greek-omitted} [ιερεις]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [στρατηγος]{.greek-omitted} [του]{.greek-omitted} [ιερου]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [σαδδουκαιοι]{.greek-omitted}[4:1]{.aside}

[λαλουντων]{.greek-omitted} δε αυτων προς τον λαον επεστησαν αυτοις οι ιερεις και ο στρατηγος του ιερου και οι σαδδουκαιοι[4:1 | instance no. 2]{.aside}

διαπονουμενοι δια το διδασκειν αυτους τον [λαον]{.greek-omitted} [λογον]{.greek-added} και καταγγελλειν εν τω [ιησου]{.greek-abbr} [την]{.greek-omitted} αναστασιν των νεκρων[4:2]{.aside}

και επεβαλον αυτοις τας χειρας και εθεντο εις τηρησιν εις την αυριον ην γαρ εσπερα ηδη[4:3]{.aside}

πολλοι δε των ακουσαντων τον λογον επιστευσαν και εγενηθη ο αριθμος των ανδρων ωσει χιλιαδες πεντε[4:4]{.aside}

εγενετο δε επι την αυριον συναχθηναι αυτων τους αρχοντας και [τους]{.greek-added} πρεσβυτερους και γραμματεις εις [ιερουσαλημ]{.greek-abbr}[4:5]{.aside}

και ανναν τον αρχιερεα και καιαφαν και ιωαννην και αλεξανδρον και οσοι ησαν εκ γενους [αρχιερατικου]{.greek-omitted} [ιερατικου]{.greek-added}[4:6]{.aside}

και στησαντες αυτους εν μεσω επυνθανοντο εν ποια δυναμει η εν ποιω ονοματι εποιησατε τουτο υμεις[4:7]{.aside}

τοτε πετρος πλησθεις [πνευματος]{.greek-abbr} αγιου [ειπεν]{.greek-omitted} [ειπε]{.greek-added} προς αυτους αρχοντες του λαου και πρεσβυτεροι του [ισραηλ]{.greek-abbr}[4:8]{.aside}

ει ημεις σημερον ανακρινομεθα επι ευεργεσια [ανθρωπου]{.greek-abbr} ασθενους εν τινι ουτος σεσωσται[4:9]{.aside}

γνωστον εστω πασιν υμιν και παντι τω λαω [ισραηλ]{.greek-abbr} οτι εν τω ονοματι [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} του ναζωραιου ον υμεις εσταυρωσατε ον ο [θεος]{.greek-abbr} ηγειρεν εκ νεκρων εν τουτω ουτος παρεστηκεν ενωπιον υμων υγιης[4:10]{.aside}

ουτος εστιν ο λιθος ο εξουθενηθεις υφ υμων των οικοδομουντων ο γενομενος εις κεφαλην γωνιας[4:11]{.aside}

και ουκ εστιν εν αλλω [εν]{.greek-added} ουδενι η σωτηρια ουτε [γαρ]{.greek-omitted} ονομα εστιν ετερον το δεδομενον εν [ανθρωποις]{.greek-abbr} εν ω δει σωθηναι ημας[4:12]{.aside}

[θεωρουντες]{.greek-omitted} [θεωρουντος]{.greek-added} δε [του]{.greek-added} [λαου]{.greek-added} την του πετρου παρρησιαν και ιωαννου [και]{.greek-omitted} καταλαβομενοι οτι [ανθρωποι]{.greek-abbr} αγραμματοι [εισιν]{.greek-omitted} [εισι]{.greek-added} και ιδιωται εθαυμαζον [επεγινωσκον]{.greek-omitted} [επιγινωσκοντες]{.greek-added} [τε]{.greek-omitted} αυτους οτι συν τω [ιησου]{.greek-abbr} ησαν[4:13]{.aside}

τον δε [ανθρωπον]{.greek-abbr} βλεποντες συν αυτοις εστωτα τον τεθεραπευμενον ουδεν ειχον αντειπειν[4:14]{.aside}

κελευσαντες δε αυτους εξω του συνεδριου απελθειν συνεβαλλον προς αλληλους[4:15]{.aside}

λεγοντες τι [ποιησομεν]{.greek-omitted} [ποιησωμεν]{.greek-added} τοις [ανθρωποις]{.greek-abbr} [τουτοις]{.greek-omitted} [οτι]{.greek-omitted} [μεν]{.greek-omitted} [γαρ]{.greek-omitted} [γνωστον]{.greek-omitted} [σημειον]{.greek-omitted} [γεγονεν]{.greek-omitted} [δι]{.greek-omitted} [αυτων]{.greek-omitted} [πασιν]{.greek-omitted} [τοις]{.greek-omitted} [κατοικουσιν]{.greek-omitted} [ιερουσαλημ]{.greek-omitted} [φανερον]{.greek-omitted} [και]{.greek-omitted} [ου]{.greek-omitted} [του]{.greek-added} [δυναμεθα]{.greek-omitted} [αρνησασθαι]{.greek-omitted}[4:16]{.aside}

[λεγοντες]{.greek-omitted} [τι]{.greek-omitted} [ποιησομεν]{.greek-omitted} τοις [ανθρωποις]{.greek-omitted} [τουτοις]{.greek-omitted} οτι μεν γαρ γνωστον σημειον [γεγονεν]{.greek-omitted} [γεγονε]{.greek-added} δι αυτων [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις κατοικουσιν [ιερουσαλημ]{.greek-abbr} [και]{.greek-added} φανερον και ου δυναμεθα αρνησασθαι[4:16 | instance no. 2]{.aside}

αλλ ινα μη επι πλειον διανεμηθη εις τον λαον απειλη απειλησομεθα αυτοις μηκετι λαλειν επι τω ονοματι τουτω μηδενι [ανθρωπων]{.greek-abbr}[4:17]{.aside}

και καλεσαντες αυτους παρηγγειλαν αυτοις το καθολου μη φθεγγεσθαι μηδε διδασκειν επι τω ονοματι του [ιησου]{.greek-abbr}[4:18]{.aside}

ο δε πετρος και ιωαννης αποκριθεντες προς αυτους ειπον ει δικαιον εστιν ενωπιον του [θεου]{.greek-abbr} υμων ακουειν μαλλον η του [θεου]{.greek-abbr} κρινατε[4:19]{.aside}

ου δυναμεθα γαρ ημεις α [ειδομεν]{.greek-omitted} [ιδωμεν]{.greek-added} και ηκουσαμεν μη λαλειν[4:20]{.aside}

οι δε προσαπειλησαμενοι απελυσαν αυτους μηδεν ευρισκοντες το πως κολασονται αυτους δια τον λαον οτι παντες εδοξαζον τον [θεον]{.greek-abbr} επι τω γεγονοτι[4:21]{.aside}

ετων γαρ ην πλειονων τεσσαρακοντα ο [ανθρωπος]{.greek-abbr} εφ ον εγεγονει το σημειον τουτο της ιασεως[4:22]{.aside}

απολυθεντες δε [οι]{.greek-added} [αποστολοι]{.greek-added} ηλθον προς τους ιδιους και απηγγειλαν οσα προς αυτους οι αρχιερεις και οι πρεσβυτεροι ειπον[4:23]{.aside}

οι δε ακουσαντες ομοθυμαδον ηραν φωνην προς τον [θεον]{.greek-abbr} και ειπον δεσποτα συ [ει]{.greek-added} ο [θεος]{.greek-abbr} ο ποιησας τον [ουρανον]{.greek-abbr} και την γην και την θαλασσαν και παντα τα εν αυτοις[4:24]{.aside}

[ο]{.greek-omitted} δια στοματος [δαυιδ]{.greek-abbr} παιδος σου ειπων [ινα]{.greek-omitted} [ινατι]{.greek-added} [τι]{.greek-omitted} εφρυαξαν εθνη και λαοι εμελετησαν κενα[4:25]{.aside}

παρεστησαν οι βασιλεις της γης και οι αρχοντες συνηχθησαν επι το αυτο κατα του [κυριου]{.greek-abbr} και κατα του [χριστου]{.greek-abbr} αυτου[4:26]{.aside}

συνηχθησαν γαρ επ αληθειας επι τον [αγιον]{.greek-omitted} παιδα σου [ιησουν]{.greek-abbr} ον εχρισας ηρωδης τε και ποντιος πιλατος συν [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} και [λαοις]{.greek-omitted} [λαος]{.greek-added} [ισραηλ]{.greek-abbr}[4:27]{.aside}

ποιησαι οσα η χειρ σου και η βουλη σου [προωρισεν]{.greek-omitted} [προωρισε]{.greek-added} γενεσθαι[4:28]{.aside}

και τα νυν [κυριε]{.greek-abbr} [επιδε]{.greek-omitted} [επειδε]{.greek-added} επι τας απειλας αυτων και δος τοις δουλοις σου μετα παρρησιας πασης λαλειν τον λογον σου[4:29]{.aside}

εν τω την χειρα σου εκτεινειν σε εις ιασιν και σημεια και τερατα γινεσθαι δια [του]{.greek-omitted} [ονοματος]{.greek-omitted} [του]{.greek-omitted} [αγιου]{.greek-omitted} [παιδος]{.greek-omitted} [σου]{.greek-omitted} [ιησου]{.greek-omitted}[4:30]{.aside}

[εν]{.greek-omitted} [τω]{.greek-omitted} [την]{.greek-omitted} [χειρα]{.greek-omitted} [σου]{.greek-omitted} [εκτεινειν]{.greek-omitted} [σε]{.greek-omitted} [εις]{.greek-omitted} [ιασιν]{.greek-omitted} [και]{.greek-omitted} [σημεια]{.greek-omitted} [και]{.greek-omitted} [τερατα]{.greek-omitted} [γινεσθαι]{.greek-omitted} [δια]{.greek-omitted} του ονοματος του αγιου παιδος σου [ιησου]{.greek-abbr}[4:30 | instance no. 2]{.aside}

και δεηθεντων αυτων εσαλευθη ο τοπος εν ω ησαν συνηγμενοι και επλησθησαν απαντες [πνευματος]{.greek-abbr} αγιου και ελαλουν τον λογον του [θεου]{.greek-abbr} μετα παρρησιας[4:31]{.aside}

του δε πληθους των πιστευσαντων ην η καρδια και η ψυχη μια και [ουδε]{.greek-omitted} [ουδεις]{.greek-added} [εις]{.greek-omitted} τι των υπαρχοντων αυτων ελεγεν ιδιον ειναι αλλ ην αυτοις απαντα κοινα[4:32]{.aside}

και μεγαλη δυναμει απεδιδουν το μαρτυριον οι αποστολοι της αναστασεως του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} χαρις τε μεγαλη ην επι παντας αυτους[4:33]{.aside}

ουδε γαρ ενδεης τις υπηρχεν εν αυτοις οσοι γαρ κτητορες χωριων η οικιων υπηρχον πωλουντες εφερον τας τιμας των πιπρασκομενων[4:34]{.aside}

και ετιθουν παρα τους ποδας των αποστολων [διεδιδοτο]{.greek-omitted} [διεδιδωτο]{.greek-added} δε εκαστω [καθοτι]{.greek-omitted} [καθο]{.greek-added} [αν]{.greek-omitted} τις χρειαν ειχεν[4:35]{.aside}

[ιωσης]{.greek-omitted} [ιωσηφ]{.greek-added} δε ο επικληθεις βαρναβας απο των αποστολων ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον υιος παρακλησεως λευιτης κυπριος τω γενει[4:36]{.aside}

υπαρχοντος [αυτω]{.greek-omitted} [αυτου]{.greek-added} αγρου πωλησας [ηνεγκεν]{.greek-omitted} [ηνεγκε]{.greek-added} το χρημα και [εθηκεν]{.greek-omitted} [παρεθηκε]{.greek-added} παρα τους ποδας των αποστολων[4:37]{.aside}

### Chapter 5

ανηρ δε τις ανανιας ονοματι συν σαπφειρη τη γυναικι αυτου [επωλησεν]{.greek-omitted} [επωλησε]{.greek-added} κτημα[5:1]{.aside}

και [ενοσφισατο]{.greek-omitted} [ενοσφησατο]{.greek-added} απο της τιμης συνειδυιας και της γυναικος αυτου και ενεγκας μερος τι παρα τους ποδας των αποστολων εθηκεν[5:2]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε πετρος ανανια δια τι επληρωσεν ο σατανας την καρδιαν σου ψευσασθαι σε το [πνευμα]{.greek-abbr} το αγιον και νοσφισασθαι σε απο της τιμης του χωριου[5:3]{.aside}

ουχι μενον σοι [εμενεν]{.greek-omitted} [εμενε]{.greek-added} και πραθεν εν τη ση εξουσια υπηρχεν τι οτι εθου εν τη καρδια σου το πραγμα τουτο ουκ εψευσω [ανθρωποις]{.greek-abbr} αλλα τω [θεω]{.greek-abbr}[5:4]{.aside}

ακουων δε [ο]{.greek-omitted} [ανανιας]{.greek-omitted} τους λογους τουτους [ο]{.greek-added} [ανανιας]{.greek-added} πεσων [εξεψυξεν]{.greek-omitted} [εξεψυξε]{.greek-added} και εγενετο φοβος μεγας επι παντας τους ακουοντας ταυτα[5:5]{.aside}

ανασταντες δε οι νεωτεροι συνεστειλαν αυτον και εξενεγκαντες εθαψαν[5:6]{.aside}

εγενετο δε ως ωρων τριων [διαστημα]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [γυνη]{.greek-omitted} [αυτου]{.greek-omitted} [μη]{.greek-omitted} [ειδυια]{.greek-omitted} [το]{.greek-omitted} [γεγονος]{.greek-omitted} [εισηλθεν]{.greek-omitted}[5:7]{.aside}

[εγενετο]{.greek-omitted} [δε]{.greek-omitted} [ως]{.greek-omitted} [ωρων]{.greek-omitted} [τριων]{.greek-omitted} διαστημα και η γυνη αυτου μη ειδυια το [γεγονος]{.greek-omitted} [γεγονως]{.greek-added} εισηλθεν[5:7 | instance no. 2]{.aside}

απεκριθη δε αυτη ο πετρος ειπε μοι ει τοσουτου το χωριον απεδοσθε η δε [ειπεν]{.greek-omitted} [ειπε]{.greek-added} ναι τοσουτου[5:8]{.aside}

ο δε πετρος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} προς αυτην τι οτι συνεφωνηθη υμιν πειρασαι το [πνευμα]{.greek-abbr} [κυριου]{.greek-abbr} ιδου οι ποδες των θαψαντων τον ανδρα σου επι [τη]{.greek-omitted} [την]{.greek-added} θυρα και [εξοισουσιν]{.greek-omitted} [εξοισουσι]{.greek-added} σε[5:9]{.aside}

[επεσεν]{.greek-omitted} [επεσε]{.greek-added} δε παραχρημα παρα τους ποδας αυτου και εξεψυξεν εισελθοντες δε οι νεανισκοι ευρον αυτην νεκραν και εξενεγκαντες εθαψαν [αυτην]{.greek-added} προς τον ανδρα αυτης[5:10]{.aside}

και εγενετο φοβος μεγας εφ ολην την εκκλησιαν και επι παντας τους ακουοντας ταυτα[5:11]{.aside}

δια δε των χειρων των αποστολων εγινετο σημεια και τερατα εν τω λαω πολλα και ησαν ομοθυμαδον απαντες εν τη στοα σολομωντος[5:12]{.aside}

των δε λοιπων ουδεις ετολμα κολλασθαι αυτοις αλλ εμεγαλυνεν αυτους ο λαος[5:13]{.aside}

μαλλον δε [προσετιθεντο]{.greek-omitted} [προσετιθοντο]{.greek-added} πιστευοντες τω [κυριω]{.greek-abbr} πληθη ανδρων τε και γυναικων[5:14]{.aside}

ωστε κατα τας πλατειας εκφερειν τους ασθενεις και τιθεναι επι κλινων και κραββατων ινα [ερχομενου]{.greek-omitted} [ερχωμενου]{.greek-added} πετρου καν η σκια επισκιαση τινι αυτων[5:15]{.aside}

[συνηρχετο]{.greek-omitted} [συνηρχοντο]{.greek-added} δε και το πληθος των περιξ πολεων εις ιερουσαλημ φεροντες ασθενεις και οχλουμενους υπο [πνευματων]{.greek-abbr} ακαθαρτων οιτινες εθεραπευοντο απαντες[5:16]{.aside}

αναστας δε ο αρχιερευς και παντες οι συν αυτω η ουσα αιρεσις των σαδδουκαιων επλησθησαν ζηλου[5:17]{.aside}

και επεβαλον τας χειρας αυτων επι τους αποστολους και εθεντο αυτους εν τηρησει δημοσια[5:18]{.aside}

αγγελος δε [κυριου]{.greek-abbr} δια της νυκτος [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} τας θυρας της φυλακης εξαγαγων τε αυτους [ειπεν]{.greek-omitted} [ειπε]{.greek-added}[5:19]{.aside}

πορευεσθε και σταθεντες λαλειτε εν τω ιερω τω λαω παντα τα ρηματα της ζωης ταυτης[5:20]{.aside}

ακουσαντες δε [οι]{.greek-added} [αποστολοι]{.greek-added} εισηλθον υπο τον ορθρον εις το ιερον και εδιδασκον παραγενομενος δε ο αρχιερευς και οι συν αυτω συνεκαλεσαν το [συνε]{.greek-added} [συνεδριον]{.greek-omitted} [και]{.greek-omitted} [πασαν]{.greek-omitted} [την]{.greek-omitted} [γερουσιαν]{.greek-omitted} [των]{.greek-omitted} [υιων]{.greek-omitted} [ισραηλ]{.greek-omitted} [και]{.greek-omitted} [απεστειλαν]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [δεσμωτηριον]{.greek-omitted} [αχθηναι]{.greek-omitted} [αυτους]{.greek-omitted}[5:21]{.aside}

[δριον]{.greek-added} [ακουσαντες]{.greek-omitted} [δε]{.greek-omitted} [εισηλθον]{.greek-omitted} [υπο]{.greek-omitted} [τον]{.greek-omitted} [ορθρον]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [ιερον]{.greek-omitted} [και]{.greek-omitted} [εδιδασκον]{.greek-omitted} [παραγενομενος]{.greek-omitted} [δε]{.greek-omitted} [ο]{.greek-omitted} [αρχιερευς]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [συν]{.greek-omitted} [αυτω]{.greek-omitted} [συνεκαλεσαν]{.greek-omitted} [το]{.greek-omitted} [συνεδριον]{.greek-omitted} και πασαν την γερουσιαν των υιων [ισραηλ]{.greek-abbr} και απεστειλαν εις το δεσμωτηριον αχθηναι αυτους[5:21 | instance no. 2]{.aside}

οι δε υπηρεται παραγενομενοι ουχ ευρον αυτους εν τη φυλακη αναστρεψαντες δε απηγγειλαν[5:22]{.aside}

λεγοντες οτι το μεν δεσμωτηριον ευρομεν κεκλεισμενον εν παση ασφαλεια και τους φυλακας εστωτας προ των θυρων ανοιξαντες δε εσω ουδενα ευρομεν[5:23]{.aside}

ως δε ηκουσαν τους λογους τουτους ο τε ιερευς και ο στρατηγος του ιερου και οι αρχιερεις διηπορουν περι αυτων τι αν γενοιτο τουτο[5:24]{.aside}

παραγενομενος δε τις απηγγειλεν αυτοις οτι ιδου οι ανδρες ους εθεσθε εν τη φυλακη εισιν εν τω ιερω εστωτες και διδασκοντες τον λαον[5:25]{.aside}

τοτε απελθων ο στρατηγος συν τοις υπηρεταις ηγαγεν αυτους ου μετα βιας εφοβουντο γαρ τον λαον ινα μη λιθασθωσιν[5:26]{.aside}

αγαγοντες δε αυτους εστησαν εν τω συνεδριω και επηρωτησεν αυτους ο αρχιερευς[5:27]{.aside}

λεγων ου παραγγελια παρηγγειλαμεν υμιν μη διδασκειν επι τω ονοματι τουτω και ιδου πεπληρωκατε την [ιερουσαλημ]{.greek-abbr} της διδαχης υμων και βουλεσθε επαγαγειν εφ [ημας]{.greek-omitted} [υμας]{.greek-added} το αιμα του [ανθρωπου]{.greek-abbr} τουτου[5:28]{.aside}

αποκριθεις δε πετρος και οι αποστολοι ειπον πειθαρχειν δει [θεω]{.greek-abbr} μαλλον η [ανθρωποις]{.greek-abbr}[5:29]{.aside}

ο [θεος]{.greek-abbr} των [πατερων]{.greek-abbr} ημων [ον]{.greek-added} ηγειρεν [ιησουν]{.greek-abbr} ον υμεις διεχειρισασθε κρεμασαντες επι ξυλου[5:30]{.aside}

τουτον ο [θεος]{.greek-abbr} αρχηγον και [σωτηρα]{.greek-abbr} [υψωσεν]{.greek-omitted} [υψωσε]{.greek-added} τη δεξια αυτου δουναι μετανοιαν τω [ισραηλ]{.greek-abbr} και αφεσιν αμαρτιων[5:31]{.aside}

και ημεις εσμεν αυτου μαρτυρες των ρηματων τουτων και το πνευμα δε το αγιον ο εδωκεν ο [θεος]{.greek-abbr} τοις πειθαρχουσιν αυτω[5:32]{.aside}

οι δε [ακουοντες]{.greek-omitted} [ακουσαντες]{.greek-added} διεπριοντο και [εβουλευοντο]{.greek-omitted} [εβουλοντο]{.greek-added} ανελειν αυτους[5:33]{.aside}

αναστας δε τις εν τω συνεδριω φαρισαιος ονοματι γαμαλιηλ νομοδιδασκαλος τιμιος παντι τω λαω εκελευσεν εξω βραχυ τι τους αποστολους ποιησαι[5:34]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} [τε]{.greek-omitted} [δε]{.greek-added} προς αυτους ανδρες ισραηλιται προσεχετε εαυτοις [επι]{.greek-omitted} [τοις]{.greek-omitted} [ανθρωποις]{.greek-omitted} [τουτοις]{.greek-omitted} [τι]{.greek-omitted} [μελλετε]{.greek-omitted} [πρασσειν]{.greek-omitted}[5:35]{.aside}

[ειπεν]{.greek-omitted} [τε]{.greek-omitted} [προς]{.greek-omitted} [αυτους]{.greek-omitted} [ανδρες]{.greek-omitted} [ισραηλιται]{.greek-omitted} [προσεχετε]{.greek-omitted} [εαυτοις]{.greek-omitted} επι τοις [ανθρωποις]{.greek-abbr} τουτοις τι μελλετε πρασσειν[5:35 | instance no. 2]{.aside}

προ γαρ τουτων των ημερων ανεστη θευδας λεγων ειναι τινα εαυτον [ω]{.greek-omitted} [ο]{.greek-added} [προσεκληθη]{.greek-omitted} [προσεκολληθη]{.greek-added} αριθμος ανδρων ωσει τετρακοσιων ος ανηρεθη και παντες οσοι επειθοντο αυτω διελυθησαν και εγενοντο εις ουδεν[5:36]{.aside}

μετα τουτον ανεστη ιουδας ο γαλιλαιος εν ταις ημεραις της απογραφης και [απεστησεν]{.greek-omitted} [απεστησε]{.greek-added} λαον ικανον οπισω αυτου κακεινος απωλετο και παντες οσοι επειθοντο αυτω διεσκορπισθησαν[5:37]{.aside}

και τα νυν λεγω υμιν αποστητε απο των [ανθρωπων]{.greek-abbr} τουτων και εασατε [αυτους]{.greek-omitted} [εαυτους]{.greek-added} οτι εαν [η]{.greek-omitted} [ει]{.greek-added} εξ [ανθρωπων]{.greek-abbr} η βουλη η το εργον τουτο καταλυθησεται[5:38]{.aside}

ει δε εκ [θεου]{.greek-abbr} εστιν ου δυνασθε καταλυσαι αυτο μηποτε [και]{.greek-omitted} θεομαχοι ευρεθητε [επεισθησαν]{.greek-added} [δε]{.greek-added} [αυτω]{.greek-added}[5:39]{.aside}

[επεισθησαν]{.greek-omitted} [δε]{.greek-omitted} [αυτω]{.greek-omitted} και προσκαλεσαμενοι τους αποστολους [δειραντες]{.greek-omitted} [δηραντες]{.greek-added} παρηγγειλαν μη λαλειν επι τω ονοματι του [ιησου]{.greek-abbr} και απελυσαν αυτους[5:40]{.aside}

οι μεν ουν επορευοντο χαιροντες απο προσωπου του συνεδριου οτι υπερ του ονοματος του [ιησου]{.greek-abbr} κατηξιωθησαν ατιμασθηναι[5:41]{.aside}

πασαν τε ημεραν εν τω ιερω και κατ οικον ουκ επαυοντο διδασκοντες και ευαγγελιζομενοι [ιησουν]{.greek-abbr} τον [χριστον]{.greek-abbr}[5:42]{.aside}

### Chapter 6

εν δε ταις ημεραις ταυταις πληθυνοντων των μαθητων εγενετο γογγυσμος των ελληνιστων προς τους εβραιους οτι παρεθεωρουντο εν τη διακονια τη καθημερινη αι χηραι αυτων[6:1]{.aside}

προσκαλεσαμενοι δε οι δωδεκα το πληθος των μαθητων ειπον ουκ αρεστον εστιν ημας καταλειψαντας τον λογον του [θεου]{.greek-abbr} διακονειν τραπεζαις[6:2]{.aside}

επισκεψασθε ουν [αδελφοι]{.greek-omitted} ανδρας εξ υμων μαρτυρουμενους επτα [πληρεις]{.greek-omitted} [πληρης]{.greek-added} [πνευματος]{.greek-abbr} αγιου και σοφιας ους καταστησωμεν επι της χρειας ταυτης[6:3]{.aside}

ημεις δε τη προσευχη και τη διακονια του λογου [προσκαρτερησομεν]{.greek-omitted} [προσκαρτερησωμεν]{.greek-added}[6:4]{.aside}

και ηρεσεν ο λογος ενωπιον [παν]{.greek-added} [παντος]{.greek-omitted} [του]{.greek-omitted} [πληθους]{.greek-omitted} [και]{.greek-omitted} [εξελεξαντο]{.greek-omitted} [στεφανον]{.greek-omitted} [ανδρα]{.greek-omitted} [πληρης]{.greek-omitted} [πιστεως]{.greek-omitted} [και]{.greek-omitted} [πνευματος]{.greek-omitted} [αγιου]{.greek-omitted} [και]{.greek-omitted} [φιλιππον]{.greek-omitted} [και]{.greek-omitted} [προχορον]{.greek-omitted} [και]{.greek-omitted} [νικανορα]{.greek-omitted} [και]{.greek-omitted} [τιμωνα]{.greek-omitted} [και]{.greek-omitted} [παρμεναν]{.greek-omitted} [και]{.greek-omitted} [νικολαον]{.greek-omitted} [προσηλυτον]{.greek-omitted} [αντιοχεα]{.greek-omitted}[6:5]{.aside}

[τος]{.greek-added} [και]{.greek-omitted} [ηρεσεν]{.greek-omitted} [ο]{.greek-omitted} [λογος]{.greek-omitted} [ενωπιον]{.greek-omitted} [παντος]{.greek-omitted} του πληθους και εξελεξαντο στεφανον ανδρα πληρης πιστεως και [πνευματος]{.greek-abbr} αγιου και φιλιππον και προχορον και νικανορα και [τιμωνα]{.greek-omitted} [τιμονα]{.greek-added} και παρμεναν και νικολαον προσηλυτον αντιοχεα[6:5 | instance no. 2]{.aside}

ους εστησαν ενωπιον των αποστολων και προσευξαμενοι επεθηκαν αυτοις τας χειρας[6:6]{.aside}

και ο λογος του [θεου]{.greek-abbr} [ηυξανεν]{.greek-omitted} [ηυξανε]{.greek-added} και επληθυνετο ο αριθμος των μαθητων εν ιερουσαλημ σφοδρα πολυς τε οχλος των [ιερεων]{.greek-omitted} [ιουδαιων]{.greek-added} υπηκουον τη πιστει[6:7]{.aside}

στεφανος δε πληρης [πιστεως]{.greek-omitted} [χαριτος]{.greek-added} και δυναμεως εποιει τερατα και σημεια μεγαλα εν τω λαω[6:8]{.aside}

ανεστησαν δε τινες των εκ της συναγωγης της λεγομενης λιβερτινων και κυρηναιων και αλεξανδρεων και των απο κιλικιας και ασιας συζητουντες τω στεφανω[6:9]{.aside}

και ουκ ισχυον αντιστηναι τη σοφια και τω [πνευματι]{.greek-abbr} [ω]{.greek-omitted} [ο]{.greek-added} ελαλει[6:10]{.aside}

τοτε υπεβαλον ανδρας λεγοντας οτι ακηκοαμεν αυτου λαλουντος ρηματα βλασφημα εις [μωσην]{.greek-omitted} [μωυσην]{.greek-added} και τον [θεον]{.greek-abbr}[6:11]{.aside}

συνεκινησαν τε τον λαον και τους πρεσβυτερους και τους γραμματεις και επισταντες συνηρπασαν [συνηρπασαν]{.greek-added} αυτον και ηγαγον εις το συνεδριον[6:12]{.aside}

εστησαν τε μαρτυρας ψευδεις λεγοντας ο [ανθρωπος]{.greek-abbr} ουτος ου παυεται ρηματα βλασφημα λαλων κατα του τοπου του αγιου και του νομου[6:13]{.aside}

ακηκοαμεν γαρ αυτου λεγοντος οτι [ιησους]{.greek-abbr} ο ναζωραιος ουτος καταλυσει τον τοπον τουτον και [αλλαξει]{.greek-omitted} [αλλαξη]{.greek-added} τα εθη α παρεδωκεν ημιν [μωσης]{.greek-omitted} [μωυσης]{.greek-added}[6:14]{.aside}

και ατενισαντες εις αυτον απαντες οι καθεζομενοι εν τω συνεδριω ειδον το προσωπον αυτου ωσει προσωπον αγγελου[6:15]{.aside}

### Chapter 7

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε ο αρχιερευς ει αρα ταυτα ουτως εχει[7:1]{.aside}

ο δε εφη ανδρες αδελφοι και πατερες ακουσατε ο [θεος]{.greek-abbr} της δοξης ωφθη τω [πατρι]{.greek-abbr} ημων αβρααμ οντι εν τη μεσοποταμια πριν η κατοικησαι αυτον [εν]{.greek-omitted} [χαρραν]{.greek-omitted}[7:2]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [εφη]{.greek-omitted} [ανδρες]{.greek-omitted} [αδελφοι]{.greek-omitted} [και]{.greek-omitted} [πατερες]{.greek-omitted} [ακουσατε]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [της]{.greek-omitted} [δοξης]{.greek-omitted} [ωφθη]{.greek-omitted} [τω]{.greek-omitted} [πατρι]{.greek-omitted} [ημων]{.greek-omitted} [αβρααμ]{.greek-omitted} [οντι]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [μεσοποταμια]{.greek-omitted} [πριν]{.greek-omitted} [η]{.greek-omitted} [κατοικησαι]{.greek-omitted} [αυτον]{.greek-omitted} εν χαρραν[7:2 | instance no. 2]{.aside}

[τοτε]{.greek-omitted} [εξελθων]{.greek-omitted} [εκ]{.greek-omitted} [γης]{.greek-omitted} [χαλδαιων]{.greek-omitted} [κατωκησεν]{.greek-omitted} [εν]{.greek-omitted} [χαρραν]{.greek-omitted} [κακειθεν]{.greek-omitted} [εκειθεν]{.greek-added} [τε]{.greek-added} μετα το αποθανειν τον [πατερα]{.greek-abbr} αυτου [μετωκισεν]{.greek-omitted} [μετωκησεν]{.greek-added} αυτον εις την γην ταυτην εις ην υμεις νυν κατοικειτε[7:4]{.aside}

και ουκ εδωκεν αυτω κληρονομιαν εν αυτη ουδε βημα ποδος και επηγγειλατο δουναι αυτω εις κατασχεσιν αυτην και τω σπερματι αυτου μετ αυτον ουκ οντος αυτω τεκνου[7:5]{.aside}

[ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} δε ουτως [ο]{.greek-omitted} [θεος]{.greek-omitted} οτι εσται το σπερμα αυτου παροικον εν γη αλλοτρια και δουλωσουσιν αυτο και κακωσουσιν [αυτο]{.greek-added} ετη τετρακοσια[7:6]{.aside}

και το εθνος [ω]{.greek-omitted} [ο]{.greek-added} εαν [δουλευσωσιν]{.greek-omitted} [δουλευσωσι]{.greek-added} κρινω εγω ειπεν ο [θεος]{.greek-abbr} και μετα ταυτα εξελευσονται και [λατρευσουσιν]{.greek-omitted} [λατρευσουσι]{.greek-added} μοι εν τω τοπω τουτω[7:7]{.aside}

και εδωκεν αυτω διαθηκην περιτομης και [ουτως]{.greek-omitted} [ουτος]{.greek-added} [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ισαακ και περιετεμεν αυτον τη ημερα τη ογδοη και ο ισαακ τον ιακωβ και ο ιακωβ τους δωδεκα πατριαρχας[7:8]{.aside}

και οι πατριαρχαι ζηλωσαντες τον ιωσηφ απεδοντο εις αιγυπτον και ην ο [θεος]{.greek-abbr} μετ αυτου[7:9]{.aside}

και εξειλετο αυτον εκ πασων των θλιψεων αυτου και εδωκεν αυτω χαριν και σοφιαν εναντιον φαραω βασιλεως αιγυπτου και κατεστησεν αυτον ηγουμενον επ αιγυπτον και [εφ]{.greek-added} ολον τον οικον αυτου[7:10]{.aside}

[ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} δε λιμος εφ ολην την γην αιγυπτου και χανααν και θλιψις μεγαλη και ουχ ευρισκον χορτασματα οι πατερες ημων[7:11]{.aside}

ακουσας δε [ο]{.greek-added} ιακωβ οντα σιτα εν αιγυπτω [εξαπεστειλεν]{.greek-omitted} [εξαπεστειλε]{.greek-added} τους πατερας ημων πρωτον[7:12]{.aside}

και εν τω δευτερω ανεγνωρισθη ιωσηφ τοις αδελφοις αυτου και φανερον εγενετο τω φαραω το γενος του ιωσηφ[7:13]{.aside}

αποστειλας δε ιωσηφ μετεκαλεσατο [τον]{.greek-omitted} [πατερα]{.greek-omitted} [αυτου]{.greek-omitted} ιακωβ και πασαν την συγγενειαν εν ψυχαις εβδομηκοντα πεντε[7:14]{.aside}

κατεβη δε ιακωβ εις αιγυπτον και ετελευτησεν αυτος και οι πατερες ημων[7:15]{.aside}

και μετετεθησαν εις συχεμ [και]{.greek-omitted} [ετεθησαν]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [μνηματι]{.greek-omitted} [ο]{.greek-omitted} [ωνησατο]{.greek-omitted} [αβρααμ]{.greek-omitted} [τιμης]{.greek-omitted} [αργυριου]{.greek-omitted} [παρα]{.greek-omitted} [των]{.greek-omitted} [υιων]{.greek-omitted} [εμμορ]{.greek-omitted} [του]{.greek-omitted} [συχεμ]{.greek-omitted}[7:16]{.aside}

καθως δε ηγγιζεν ο χρονος της επαγγελιας ης ωμοσεν ο [θεος]{.greek-abbr} τω αβρααμ ηυξησεν ο λαος και επληθυνθη εν αιγυπτω[7:17]{.aside}

[αχρι]{.greek-omitted} [αχρις]{.greek-added} ου ανεστη βασιλευς ετερος ος ουκ ηδει τον ιωσηφ[7:18]{.aside}

ουτος κατασοφισαμενος το γενος ημων [εκακωσεν]{.greek-omitted} [εκακωσε]{.greek-added} τους [πατερας]{.greek-abbr} ημων του ποιειν εκθετα τα βρεφη αυτων εις το μη ζωογονεισθαι[7:19]{.aside}

εν ω καιρω [εγεννηθη]{.greek-omitted} [εγενηθη]{.greek-added} [μωσης]{.greek-omitted} [μωυσης]{.greek-added} και ην αστειος τω [θεω]{.greek-abbr} ος ανετραφη μηνας τρεις εν τω οικω του [πατρος]{.greek-abbr} [αυτου]{.greek-added}[7:20]{.aside}

εκτεθεντα δε αυτον ανειλετο [αυτον]{.greek-added} η θυγατηρ φαραω και ανεθρεψατο αυτον [εαυτη]{.greek-omitted} [αυτη]{.greek-added} εις υιον[7:21]{.aside}

και επαιδευθη [μωσης]{.greek-omitted} [μωυσης]{.greek-added} παση σοφια αιγυπτιων ην δε δυνατος εν λογοις και εργοις[7:22]{.aside}

ως δε επληρουτο αυτω [τεσσαρακονταετης]{.greek-omitted} [τεσσαρακονετης]{.greek-added} χρονος ανεβη επι την καρδιαν αυτου επισκεψασθαι τους αδελφους αυτου τους υιους [ισραηλ]{.greek-abbr}[7:23]{.aside}

και ιδων τινα αδικουμενον ημυνατο και εποιησεν εκδικησιν τω καταπονουμενω παταξας τον αιγυπτιον[7:24]{.aside}

[ενομιζεν]{.greek-omitted} [ενομιζε]{.greek-added} δε συνιεναι τους αδελφους αυτου οτι ο [θεος]{.greek-abbr} δια χειρος αυτου διδωσιν αυτοις σωτηριαν οι δε ου συνηκαν[7:25]{.aside}

τη τε επιουση ημερα ωφθη αυτοις μαχομενοις και [συνηλασεν]{.greek-omitted} [συνειλασεν]{.greek-added} αυτους εις ειρηνην ειπων ανδρες αδελφοι εστε υμεις [ινα]{.greek-omitted} [ινατι]{.greek-added} [τι]{.greek-omitted} αδικειτε αλληλους[7:26]{.aside}

ο δε αδικων τον πλησιον απωσατο αυτον ειπων τις σε κατεστησεν αρχοντα και δικαστην εφ [ημας]{.greek-omitted} [ημων]{.greek-added}[7:27]{.aside}

μη ανελειν με συ θελεις ον τροπον ανειλες χθες τον αιγυπτιον[7:28]{.aside}

[εφυγεν]{.greek-omitted} [εφυγε]{.greek-added} δε [μωσης]{.greek-omitted} [μωυσης]{.greek-added} εν τω λογω τουτω και εγενετο παροικος εν γη μαδιαμ ου εγεννησεν υιους δυο[7:29]{.aside}

και πληρωθεντων ετων τεσσαρακοντα ωφθη αυτω εν τη ερημω του ορους σινα αγγελος [κυριου]{.greek-abbr} εν φλογι πυρος βατου[7:30]{.aside}

ο δε μωσης ιδων [εθαυμαζεν]{.greek-omitted} [εθαυμαζε]{.greek-added} το οραμα προσερχομενου δε αυτου κατανοησαι εγενετο φωνη [κυριου]{.greek-abbr} προς αυτον[7:31]{.aside}

εγω ο [θεος]{.greek-abbr} των πατερων σου ο [θεος]{.greek-abbr} αβρααμ και [ο]{.greek-omitted} [θεος]{.greek-omitted} ισαακ και [ο]{.greek-omitted} [θεος]{.greek-omitted} ιακωβ εντρομος δε γενομενος μωσης ουκ ετολμα κατανοησαι[7:32]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε αυτω ο [κυριος]{.greek-abbr} λυσον το υποδημα των ποδων σου ο γαρ τοπος εν ω εστηκας γη αγια εστιν[7:33]{.aside}

ιδων ειδον την κακωσιν του λαου μου του εν αιγυπτω και του στεναγμου αυτων ηκουσα και [κατεβην]{.greek-omitted} [εξελεσθαι]{.greek-omitted} [αυτους]{.greek-omitted} [και]{.greek-omitted} [νυν]{.greek-omitted} [δευρο]{.greek-omitted} [αποστελω]{.greek-omitted} [σε]{.greek-omitted} [εις]{.greek-omitted} [αιγυπτον]{.greek-omitted}[7:34]{.aside}

[κατεβην]{.greek-added} [ιδων]{.greek-omitted} [ειδον]{.greek-omitted} [την]{.greek-omitted} [κακωσιν]{.greek-omitted} του [λαου]{.greek-omitted} [μου]{.greek-omitted} [του]{.greek-omitted} [εν]{.greek-omitted} [αιγυπτω]{.greek-omitted} [και]{.greek-omitted} [του]{.greek-omitted} [στεναγμου]{.greek-omitted} [αυτων]{.greek-omitted} [ηκουσα]{.greek-omitted} [και]{.greek-omitted} [κατεβην]{.greek-omitted} εξελεσθαι αυτους και νυν δευρο αποστελω σε εις αιγυπτον[7:34 | instance no. 2]{.aside}

τουτον τον μωσην ον ηρνησαντο ειποντες τις σε κατεστησεν αρχοντα και δικαστην τουτον ο [θεος]{.greek-abbr} αρχοντα και λυτρωτην απεστειλεν εν χειρι αγγελου του οφθεντος αυτω εν τη βατω[7:35]{.aside}

ουτος εξηγαγεν αυτους ποιησας τερατα και σημεια εν γη αιγυπτω και εν ερυθρα θαλασση και εν τη ερημω ετη τεσσαρακοντα[7:36]{.aside}

ουτος εστιν ο [μωσης]{.greek-omitted} [μωυσης]{.greek-added} ο ειπων τοις υιοις [ισραηλ]{.greek-abbr} προφητην υμιν αναστησει [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ημων εκ των αδελφων υμων ως εμε[7:37]{.aside}

ουτος εστιν ο γενομενος εν τη εκκλησια εν τη ερημω μετα του αγγελου του λαλουντος αυτω εν τω ορει σινα και των [πατερων]{.greek-abbr} ημων ος εδεξατο [λογον]{.greek-omitted} [λογια]{.greek-added} ζωντα δουναι ημιν[7:38]{.aside}

ω ουκ ηθελησαν υπηκοοι γενεσθαι οι [πατερες]{.greek-abbr} ημων αλλ απωσαντο και εστραφησαν τη καρδια αυτων εις αιγυπτον[7:39]{.aside}

ειποντες τω ααρων ποιησον ημιν θεους οι προπορευσονται ημων ο γαρ μωσης ουτος ος εξηγαγεν ημας εκ γης αιγυπτου ουκ οιδαμεν τι γεγονεν αυτω[7:40]{.aside}

και εμοσχοποιησαν εν ταις ημεραις [εκειναις]{.greek-omitted} [αυτων]{.greek-added} και ανηγαγον θυσιαν τω ειδωλω και ευφραινοντο εν τοις εργοις των χειρων αυτων[7:41]{.aside}

[εστρεψεν]{.greek-omitted} [εστρεψε]{.greek-added} δε ο [θεος]{.greek-abbr} και παρεδωκεν αυτους λατρευειν τη στρατια του [ουρανου]{.greek-abbr} καθως γεγραπται εν βιβλω των προφητων μη σφαγια και θυσιας προσηνεγκατε μοι ετη τεσσαρακοντα εν τη ερημω οικος [ισραηλ]{.greek-abbr}[7:42]{.aside}

και ανελαβετε την σκηνην του μολοχ και το αστρον του [θεου]{.greek-abbr} υμων [ρεμφαν]{.greek-omitted} [ρεφφαν]{.greek-added} τους τυπους ους εποιησατε [προσκυνειν]{.greek-omitted} [προσκ[α]{.unclear}νειν]{.greek-added} αυτοις και μετοικιω υμας επεκεινα βαβυλωνος[7:43]{.aside}

η σκηνη του μαρτυριου ην τοις πατρασιν [ημων]{.greek-omitted} [υμων]{.greek-added} εν τη ερημω καθως διεταξατο ο λαλων τω [μωση]{.greek-omitted} [μωυση]{.greek-added} ποιησαι αυτην κατα τον τυπον ον εωρακει[7:44]{.aside}

ην και εισηγαγον διαδεξαμενοι οι πατερες ημων μετα ιησου εν τη [κατα]{.greek-added} [κατασχεσει]{.greek-omitted} [των]{.greek-omitted} [εθνων]{.greek-omitted} [ων]{.greek-omitted} [εξωσεν]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [απο]{.greek-omitted} [προσωπου]{.greek-omitted} [των]{.greek-omitted} [πατερων]{.greek-omitted} [ημων]{.greek-omitted} [εως]{.greek-omitted} [των]{.greek-omitted} [ημερων]{.greek-omitted} [δαυιδ]{.greek-omitted}[7:45]{.aside}

[ην]{.greek-omitted} [και]{.greek-omitted} [εισηγαγον]{.greek-omitted} [διαδεξαμενοι]{.greek-omitted} [οι]{.greek-omitted} [πατερες]{.greek-omitted} [ημων]{.greek-omitted} [μετα]{.greek-omitted} [ιησου]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [κατασχεσει]{.greek-omitted} [σχεσει]{.greek-added} των εθνων ων εξωσεν ο [θεος]{.greek-abbr} απο προσωπου των πατερων ημων εως των ημερων [δαυιδ]{.greek-abbr}[7:45 | instance no. 2]{.aside}

ος [ευρεν]{.greek-omitted} [ευρε]{.greek-added} χαριν ενωπιον του [θεου]{.greek-abbr} και ητησατο ευρειν σκηνωμα τω [θεω]{.greek-abbr} ιακωβ[7:46]{.aside}

σολομων δε ωκοδομησεν αυτω οικον[7:47]{.aside}

αλλ ουχ ο υψιστος εν χειροποιητοις ναοις κατοικει καθως ο προφητης λεγει[7:48]{.aside}

ο [ουρανος]{.greek-abbr} μοι θρονος η δε γη υποποδιον των ποδων μου ποιον οικον [οικοδομησετε]{.greek-omitted} [οικοδομησατε]{.greek-added} μοι λεγει [κυριος]{.greek-abbr} η τις τοπος της καταπαυσεως μου[7:49]{.aside}

ουχι η χειρ μου [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} ταυτα παντα[7:50]{.aside}

σκληροτραχηλοι και απεριτμητοι τη καρδια [και]{.greek-omitted} [τοις]{.greek-omitted} [ωσιν]{.greek-omitted} υμεις αει τω [πνευματι]{.greek-abbr} τω αγιω αντιπιπτετε ως οι [πατερες]{.greek-abbr} υμων και υμεις[7:51]{.aside}

τινα των προφητων ουκ εδιωξαν οι [πατερες]{.greek-abbr} υμων και απεκτειναν τους προκαταγγειλαντας περι της ελευσεως του δικαιου ου νυν υμεις προδοται και φονεις [γεγενησθε]{.greek-omitted} [γεγονατε]{.greek-added}[7:52]{.aside}

οιτινες ελαβετε τον νομον εις διαταγας αγγελων και ουκ εφυλαξατε[7:53]{.aside}

ακουοντες δε ταυτα διεπριοντο ταις καρδιαις αυτων και εβρυχον τους οδοντας επ αυτον[7:54]{.aside}

υπαρχων δε πληρης [πνευματος]{.greek-abbr} αγιου ατενισας εις τον [ουρανον]{.greek-abbr} [ειδεν]{.greek-omitted} [ειδε]{.greek-added} δοξαν [θεου]{.greek-abbr} και [ιησουν]{.greek-abbr} εστωτα εκ δεξιων του [θεου]{.greek-abbr}[7:55]{.aside}

και ειπεν ιδου θεωρω τους [ουρανους]{.greek-abbr} ανεωγμενους και τον υιον του [ανθρωπου]{.greek-abbr} εκ δεξιων εστωτα του [θεου]{.greek-abbr}[7:56]{.aside}

κραξαντες δε φωνη μεγαλη συνεσχον τα ωτα αυτων και ωρμησαν ομοθυμαδον επ αυτον[7:57]{.aside}

και εκβαλοντες εξω της πολεως ελιθοβολουν και οι μαρτυρες απεθεντο τα ιματια παρα τους ποδας νεανιου καλουμενου σαυλου[7:58]{.aside}

και ελιθοβολουν τον στεφανον επικαλουμενον και λεγοντα [κυριε]{.greek-abbr} [ιησου]{.greek-abbr} δεξαι το [πνευμα]{.greek-abbr} μου[7:59]{.aside}

θεις δε τα γονατα [εκραξεν]{.greek-omitted} [εκραξε]{.greek-added} φωνη μεγαλη [κυριε]{.greek-abbr} μη στησης αυτοις την αμαρτιαν ταυτην και τουτο ειπων εκοιμηθη[7:60]{.aside}

### Chapter 8

σαυλος δε ην συνευδοκων τη αναιρεσει αυτου εγενετο δε [εν]{.greek-omitted} [εκεινη]{.greek-omitted} [τη]{.greek-omitted} [ημερα]{.greek-omitted} [διωγμος]{.greek-omitted} [μεγας]{.greek-omitted} [επι]{.greek-omitted} [την]{.greek-omitted} [εκκλησιαν]{.greek-omitted} [την]{.greek-omitted} [εν]{.greek-omitted} [ιεροσολυμοις]{.greek-omitted} [παντες]{.greek-omitted} [δε]{.greek-omitted} [διεσπαρησαν]{.greek-omitted} [κατα]{.greek-omitted} [τας]{.greek-omitted} [χωρας]{.greek-omitted} [της]{.greek-omitted} [ιουδαιας]{.greek-omitted} [και]{.greek-omitted} [σαμαρειας]{.greek-omitted} [πλην]{.greek-omitted} [των]{.greek-omitted} [αποστολων]{.greek-omitted}[8:1]{.aside}

[σαυλος]{.greek-omitted} [δε]{.greek-omitted} [ην]{.greek-omitted} [συνευδοκων]{.greek-omitted} [τη]{.greek-omitted} [αναιρεσει]{.greek-omitted} [αυτου]{.greek-omitted} [εγενετο]{.greek-omitted} [δε]{.greek-omitted} εν εκεινη τη ημερα διωγμος μεγας επι την εκκλησιαν την εν ιεροσολυμοις παντες δε διεσπαρησαν κατα τας χωρας της ιουδαιας και σαμαρειας πλην των αποστολων[8:1 | instance no. 2]{.aside}

συνεκομισαν δε τον στεφανον ανδρες ευλαβεις και εποιησαντο κοπετον μεγαν επ [αυτω]{.greek-omitted} [αυτον]{.greek-added}[8:2]{.aside}

σαυλος δε ελυμαινετο την εκκλησιαν κατα τους οικους [εισπορευομενος]{.greek-omitted} [πορευομενος]{.greek-added} συρων τε ανδρας και γυναικας παρεδιδου εις φυλακην[8:3]{.aside}

οι μεν ουν διασπαρεντες διηλθον ευαγγελιζομενοι τον λογον[8:4]{.aside}

φιλιππος δε κατελθων εις πολιν της σαμαρειας εκηρυσσεν αυτοις τον [χριστον]{.greek-abbr}[8:5]{.aside}

προσειχον τε οι οχλοι τοις λεγομενοις υπο του φιλιππου ομοθυμαδον εν τω ακουειν αυτους και βλεπειν τα σημεια α εποιει[8:6]{.aside}

πολλων γαρ των εχοντων πνευματα ακαθαρτα βοωντα φωνη μεγαλη [εξηρχετο]{.greek-omitted} [εξηρχοντο]{.greek-added} πολλοι δε παραλελυμενοι και χωλοι εθεραπευθησαν[8:7]{.aside}

[και]{.greek-omitted} εγενετο [δε]{.greek-added} χαρα μεγαλη εν τη πολει εκεινη[8:8]{.aside}

ανηρ δε τις ονοματι σιμων προυπηρχεν εν τη πολει μαγευων και εξιστων το εθνος της σαμαρειας λεγων ειναι τινα εαυτον μεγαν[8:9]{.aside}

ω προσειχον απο μικρου εως μεγαλου λεγοντες ουτος εστιν η δυναμις του [θεου]{.greek-abbr} η μεγαλη[8:10]{.aside}

προσειχον δε αυτω δια [το]{.greek-omitted} [τω]{.greek-added} ικανω χρονω ταις μαγειαις εξεστακεναι αυτους[8:11]{.aside}

οτε δε επιστευσαν τω φιλιππω ευαγγελιζομενω [τα]{.greek-omitted} περι της βασιλειας του [θεου]{.greek-abbr} και του ονοματος [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} εβαπτιζοντο ανδρες τε και γυναικες[8:12]{.aside}

ο δε σιμων και αυτος [επιστευσεν]{.greek-omitted} [επιστευσε]{.greek-added} και βαπτισθεις ην προσκαρτερων τω φιλιππω θεωρων τε δυναμεις και σημεια [γινομενα]{.greek-omitted} [γενομενα]{.greek-added} εξιστατο[8:13]{.aside}

ακουσαντες δε οι εν ιεροσολυμοις αποστολοι οτι δεδεκται η σαμαρεια τον λογον του [θεου]{.greek-abbr} απεστειλαν προς αυτους τον πετρον και ιωαννην[8:14]{.aside}

οιτινες καταβαντες προσηυξαντο περι αυτων οπως [λαβωσιν]{.greek-omitted} [λαβωσι]{.greek-added} [πνευμα]{.greek-abbr} αγιον[8:15]{.aside}

ουπω γαρ ην επ ουδενι αυτων [επιπεπτωκος]{.greek-omitted} [πεπτωκως]{.greek-added} μονον δε βεβαπτισμενοι υπηρχον εις το ονομα του [χριστου]{.greek-omitted} [[κυριου]{.greek-abbr}]{.greek-added} [ιησου]{.greek-abbr}[8:16]{.aside}

τοτε επετιθουν τας χειρας επ αυτους και ελαμβανον [πνευμα]{.greek-abbr} αγιον[8:17]{.aside}

θεασαμενος δε ο σιμων οτι δια της επιθεσεως των χειρων των αποστολων διδοται το [πνευμα]{.greek-abbr} το αγιον προσηνεγκεν αυτοις χρηματα[8:18]{.aside}

λεγων δοτε καμοι την εξουσιαν ταυτην ινα ω εαν επιθω τας χειρας [λαμβανη]{.greek-omitted} [λαμβανει]{.greek-added} [πνευμα]{.greek-abbr} αγιον[8:19]{.aside}

πετρος δε [ειπεν]{.greek-omitted} [ειπε]{.greek-added} προς αυτον το αργυριον σου συν σοι [ειη]{.greek-omitted} εις απωλειαν οτι την δωρεαν του [θεου]{.greek-abbr} ενομισας δια χρηματων κτασθαι[8:20]{.aside}

ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} σοι μερις ουδε κληρος εν τω λογω τουτω η γαρ καρδια σου ουκ εστιν ευθεια ενωπιον του [θεου]{.greek-abbr}[8:21]{.aside}

μετανοησον ουν απο της κακιας σου ταυτης και δεηθητι του [θεου]{.greek-abbr} ει αρα αφεθησεται σοι η επινοια της καρδιας σου[8:22]{.aside}

εις γαρ χολην πικριας και συνδεσμον αδικιας ορω σε οντα[8:23]{.aside}

αποκριθεις δε ο σιμων [ειπεν]{.greek-omitted} [ειπε]{.greek-added} δεηθητε υμεις υπερ εμου προς [τον]{.greek-omitted} [κυριον]{.greek-abbr} οπως μηδεν επελθη επ εμε ων ειρηκατε[8:24]{.aside}

οι μεν ουν διαμαρτυραμενοι και λαλησαντες τον λογον [του]{.greek-omitted} [κυριου]{.greek-omitted} υπεστρεψαν εις [ιερουσαλημ]{.greek-abbr} πολλας τε κωμας των σαμαρειτων ευηγγελισαντο[8:25]{.aside}

αγγελος δε [κυριου]{.greek-abbr} [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} προς φιλιππον λεγων αναστηθι και πορευου κατα μεσημβριαν επι την οδον την καταβαινουσαν απο [ιερουσαλημ]{.greek-abbr} εις γαζαν αυτη εστιν ερημος[8:26]{.aside}

και αναστας επορευθη και ιδου ανηρ αιθιοψ ευνουχος δυναστης κανδακης της βασιλισσης αιθιοπων ος ην επι πασης της γαζης αυτης ος εληλυθει προσκυνησων εις [ιερουσαλημ]{.greek-abbr}[8:27]{.aside}

ην τε υποστρεφων και καθημενος επι του αρματος αυτου και [ανεγινωσκεν]{.greek-omitted} [ανεγινωσκε]{.greek-added} τον προφητην ησαιαν[8:28]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε το [πνευμα]{.greek-abbr} τω φιλιππω προσελθε και κολληθητι τω αρματι τουτω[8:29]{.aside}

προσδραμων δε ο φιλιππος ηκουσεν αυτου αναγινωσκοντος τον προφητην ησαιαν και ειπεν αρα [γε]{.greek-omitted} γινωσκεις α αναγινωσκεις[8:30]{.aside}

ο δε [ειπεν]{.greek-omitted} [ειπε]{.greek-added} πως γαρ αν δυναιμην εαν μη τις οδηγηση με [παρεκαλεσεν]{.greek-omitted} [παρεκαλεσε]{.greek-added} τε τον φιλιππον αναβαντα [και]{.greek-added} καθισαι συν αυτω[8:31]{.aside}

η δε περιοχη της γραφης [ην]{.greek-omitted} [ης]{.greek-added} ανεγινωσκεν ην αυτη ως προβατον επι σφαγην ηχθη και ως αμνος εναντιον του κειροντος αυτον αφωνος [ουτως]{.greek-omitted} [ουτος]{.greek-added} ουκ [α]{.greek-added} [ανοιγει]{.greek-omitted} [το]{.greek-omitted} [στομα]{.greek-omitted} [αυτου]{.greek-omitted}[8:32]{.aside}

[η]{.greek-omitted} [δε]{.greek-omitted} [περιοχη]{.greek-omitted} [της]{.greek-omitted} [γραφης]{.greek-omitted} [ην]{.greek-omitted} [ανεγινωσκεν]{.greek-omitted} [ην]{.greek-omitted} [αυτη]{.greek-omitted} [ως]{.greek-omitted} [προβατον]{.greek-omitted} [επι]{.greek-omitted} [σφαγην]{.greek-omitted} [ηχθη]{.greek-omitted} [και]{.greek-omitted} [ως]{.greek-omitted} [αμνος]{.greek-omitted} [εναντιον]{.greek-omitted} [του]{.greek-omitted} [κειροντος]{.greek-omitted} [αυτον]{.greek-omitted} [αφωνος]{.greek-omitted} [ουτως]{.greek-omitted} [ουκ]{.greek-omitted} [ανοιγει]{.greek-omitted} [νοιγει]{.greek-added} το στομα αυτου[8:32 | instance no. 2]{.aside}

εν τη ταπεινωσει αυτου η κρισις αυτου ηρθη την δε γενεαν αυτου τις διηγησεται οτι αιρεται απο της γης η ζωη αυτου[8:33]{.aside}

αποκριθεις δε ο ευνουχος τω φιλιππω [ειπεν]{.greek-omitted} [ειπε]{.greek-added} δεομαι σου περι τινος ο προφητης [τουτο]{.greek-added} λεγει [τουτο]{.greek-omitted} περι [εαυτου]{.greek-omitted} [αυτου]{.greek-added} η περι ετερου τινος[8:34]{.aside}

ανοιξας δε ο φιλιππος το στομα αυτου και αρξαμενος απο της γραφης ταυτης ευηγγελισατο αυτω τον [ιησουν]{.greek-abbr}[8:35]{.aside}

ως δε επορευοντο κατα την οδον ηλθον επι τι υδωρ και φησιν ο ευνουχος ιδου υδωρ τι κωλυει με βαπτισθηναι[8:36]{.aside}

και [εκελευσεν]{.greek-omitted} [εκελευσε]{.greek-added} στηναι το αρμα και κατεβησαν αμφοτεροι εις το υδωρ ο τε φιλιππος και ο ευνουχος και εβαπτισεν αυτον[8:38]{.aside}

οτε δε ανεβησαν εκ του υδατος [πνευμα]{.greek-abbr} [κυριου]{.greek-abbr} [ηρπασεν]{.greek-omitted} [ηρπασε]{.greek-added} τον φιλιππον και ουκ ειδεν αυτον ουκετι ο ευνουχος επορευετο γαρ την οδον αυτου χαιρων[8:39]{.aside}

φιλιππος δε ευρεθη εις αζωτον και διερχομενος ευηγγελιζετο τας πολεις πασας εως του ελθειν αυτον εις καισαρειαν[8:40]{.aside}

### Chapter 9

ο δε σαυλος ετι εμπνεων απειλης και φονου εις τους μαθητας του [κυριου]{.greek-abbr} προσελθων τω αρχιερει[9:1]{.aside}

ητησατο παρ αυτου επιστολας εις δαμασκον προς τας συναγωγας οπως εαν τινας ευρη της οδου οντας ανδρας τε και γυναικας δεδεμενους [αγαγη]{.greek-omitted} [αγαγει]{.greek-added} εις [ιερουσαλημ]{.greek-abbr}[9:2]{.aside}

εν δε τω πορευεσθαι εγενετο αυτον εγγιζειν τη δαμασκω και εξαιφνης περιηστραψεν αυτον φως απο του [ουρανου]{.greek-abbr}[9:3]{.aside}

και πεσων επι την γην [ηκουσεν]{.greek-omitted} [ηκουσε]{.greek-added} φωνην λεγουσαν αυτω σαουλ σαουλ τι με διωκεις[9:4]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε τις ει [κυριε]{.greek-abbr} ο δε [κυριος]{.greek-abbr} ειπεν εγω ειμι [ιησους]{.greek-abbr} ον συ διωκεις[9:5]{.aside}

[αλλα]{.greek-omitted} [αλλ]{.greek-added} αναστηθι και εισελθε εις την πολιν και λαληθησεται σοι τι σε δει ποιειν[9:6]{.aside}

οι δε ανδρες οι συνοδευοντες αυτω ειστηκεισαν [ενεοι]{.greek-omitted} [εννεοι]{.greek-added} ακουοντες μεν της φωνης μηδενα δε θεωρουντες[9:7]{.aside}

ηγερθη δε ο σαυλος απο της γης ανεωγμενων τε των οφθαλμων [αυτου]{.greek-omitted} [αυτων]{.greek-added} ουδενα [εβλεπεν]{.greek-omitted} [εβλεπε]{.greek-added} χειραγωγουντες [δε]{.greek-omitted} [αυτον]{.greek-omitted} [εισηγαγον]{.greek-omitted} [εις]{.greek-omitted} [δαμασκον]{.greek-omitted}[9:8]{.aside}

[ηγερθη]{.greek-omitted} [δε]{.greek-omitted} [ο]{.greek-omitted} [σαυλος]{.greek-omitted} [απο]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [ανεωγμενων]{.greek-omitted} [τε]{.greek-omitted} [των]{.greek-omitted} [οφθαλμων]{.greek-omitted} [αυτου]{.greek-omitted} [ουδενα]{.greek-omitted} [εβλεπεν]{.greek-omitted} [χειραγωγουντες]{.greek-omitted} δε αυτον εισηγαγον εις δαμασκον[9:8 | instance no. 2]{.aside}

και ην ημερας τρεις μη βλεπων και ουκ εφαγεν ουδε επιεν[9:9]{.aside}

ην δε τις μαθητης εν δαμασκω ονοματι ανανιας και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} προς αυτον ο [κυριος]{.greek-abbr} εν οραματι ανανια ο δε ειπεν ιδου εγω [κυριε]{.greek-abbr}[9:10]{.aside}

ο δε [κυριος]{.greek-abbr} προς αυτον αναστας πορευθητι επι την ρυμην την καλουμενην ευθειαν και ζητησον εν οικια ιουδα σαυλον ονοματι ταρσεα ιδου γαρ προσευχεται[9:11]{.aside}

και ειδεν εν οραματι ανδρα ονοματι ανανιαν εισελθοντα και επιθεντα αυτω χειρα οπως αναβλεψη[9:12]{.aside}

απεκριθη δε ανανιας [κυριε]{.greek-abbr} ακηκοα απο πολλων περι του ανδρος τουτου οσα κακα [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} τοις αγιοις σου εν [ιερουσαλημ]{.greek-abbr}[9:13]{.aside}

και ωδε εχει εξουσιαν παρα των αρχιερεων δησαι παντας τους επικαλουμενους το ονομα σου[9:14]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε προς αυτον ο [κυριος]{.greek-abbr} πορευου οτι σκευος εκλογης μοι εστιν ουτος του βαστασαι το ονομα μου ενωπιον εθνων και βασιλεων υιων τε [ισραηλ]{.greek-abbr}[9:15]{.aside}

εγω γαρ υποδειξω αυτω οσα δει αυτον υπερ του ονοματος μου παθειν[9:16]{.aside}

[απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} δε ανανιας και εισηλθεν εις την οικιαν και επιθεις επ αυτον τας χειρας [ειπεν]{.greek-omitted} [ειπε]{.greek-added} σαουλ αδελφε ο [κυριος]{.greek-abbr} [απεσταλκεν]{.greek-omitted} [απεσταλκε]{.greek-added} με ο οφθεις σοι εν τη οδω η ηρχου οπως αναβλεψης και [πλησθης]{.greek-omitted} [πλησθεις]{.greek-added} [πνευματος]{.greek-abbr} αγιου[9:17]{.aside}

και ευθεως απεπεσον απο των οφθαλμων αυτου ωσει λεπιδες [ανεβλεψεν]{.greek-omitted} [ανεβλεψε]{.greek-added} τε και αναστας εβαπτισθη[9:18]{.aside}

και λαβων τροφην ενισχυσεν εγενετο δε ο σαυλος μετα των [οντων]{.greek-added} εν δαμασκω μαθητων ημερας τινας[9:19]{.aside}

και ευθεως εν ταις συναγωγαις [εκηρυσσεν]{.greek-omitted} [εκηρυσσε]{.greek-added} τον [χριστον]{.greek-abbr} οτι ουτος εστιν ο υιος του [θεου]{.greek-abbr}[9:20]{.aside}

εξισταντο δε παντες οι ακουοντες και ελεγον ουχ ουτος εστιν ο πορθησας εν [ιερουσαλημ]{.greek-abbr} τους επικαλουμενους το ονομα τουτο και ωδε εις τουτο εληλυθεν ινα δεδεμενους αυτους αγαγη επι τους αρχιερεις[9:21]{.aside}

σαυλος δε μαλλον ενεδυναμουτο και [συνεχυνεν]{.greek-omitted} [συνεχυνε]{.greek-added} τους ιουδαιους τους κατοικουντας [εν]{.greek-omitted} [δαμασκω]{.greek-omitted} [συμβιβαζων]{.greek-omitted} [οτι]{.greek-omitted} [ουτος]{.greek-omitted} [εστιν]{.greek-omitted} [ο]{.greek-omitted} [χριστος]{.greek-omitted}[9:22]{.aside}

[σαυλος]{.greek-omitted} [δε]{.greek-omitted} [μαλλον]{.greek-omitted} [ενεδυναμουτο]{.greek-omitted} [και]{.greek-omitted} [συνεχυνεν]{.greek-omitted} [τους]{.greek-omitted} [ιουδαιους]{.greek-omitted} [τους]{.greek-omitted} [κατοικουντας]{.greek-omitted} εν δαμασκω συμβιβαζων οτι ουτος εστιν ο [χριστος]{.greek-abbr}[9:22 | instance no. 2]{.aside}

ως δε επληρουντο ημεραι ικαναι συνεβουλευσαντο οι ιουδαιοι ανελειν αυτον[9:23]{.aside}

εγνωσθη δε τω σαυλω η επιβουλη αυτων παρετηρουν τε τας πυλας ημερας τε και νυκτος οπως αυτον ανελωσιν[9:24]{.aside}

λαβοντες δε αυτον οι μαθηται νυκτος καθηκαν δια του τειχους χαλασαντες εν σπυριδι[9:25]{.aside}

παραγενομενος δε ο σαυλος εν [ιερουσαλημ]{.greek-abbr} επειρατο κολλασθαι τοις μαθηταις και παντες εφοβουντο αυτον μη πιστευοντες οτι [εστιν]{.greek-omitted} [εστι]{.greek-added} μαθητης[9:26]{.aside}

βαρναβας δε επιλαβομενος αυτον [ηγαγεν]{.greek-omitted} [ηγαγε]{.greek-added} προς τους αποστολους και διηγησατο αυτοις πως εν τη οδω [ειδεν]{.greek-omitted} [ειδε]{.greek-added} τον [κυριον]{.greek-abbr} και οτι ελαλησεν αυτω και πως εν δαμασκω επαρρησιασατο εν τω ονοματι του [ιησου]{.greek-abbr}[9:27]{.aside}

και ην μετ αυτων εισπορευομενος εις [ιερουσαλημ]{.greek-abbr} και παρρησιαζομενος εν τω ονοματι του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr}[9:28]{.aside}

ελαλει τε και συνεζητει προς τους ελληνιστας οι δε επεχειρουν αυτον ανελειν[9:29]{.aside}

[επιγνοντες]{.greek-omitted} [επιγνωντες]{.greek-added} δε οι αδελφοι κατηγαγον αυτον εις καισαρειαν και εξαπεστειλαν αυτον εις ταρσον[9:30]{.aside}

αι μεν ουν εκκλησιαι καθ ολης της ιουδαιας και γαλιλαιας και σαμαρειας ειχον ειρηνην οικοδομουμεναι και πορευομεναι τω φοβω του [κυριου]{.greek-abbr} και τη παρακλησει του αγιου [πνευματος]{.greek-abbr} επληθυνοντο[9:31]{.aside}

εγενετο δε πετρον διερχομενον δια παντων κατελθειν και προς τους αγιους τους κατοικουντας λυδδαν[9:32]{.aside}

[ευρεν]{.greek-omitted} [ευρε]{.greek-added} δε εκει [ανθρωπον]{.greek-abbr} τινα [αινεαν]{.greek-omitted} [ενεαν]{.greek-added} ονοματι εξ ετων οκτω κατακειμενον επι [κραββατω]{.greek-omitted} [κραββατου]{.greek-added} ος ην παραλελυμενος[9:33]{.aside}

και ειπεν αυτω ο πετρος [αινεα]{.greek-omitted} [ενεα]{.greek-added} ιαται σε [ιησους]{.greek-abbr} ο [χριστος]{.greek-abbr} αναστηθι και στρωσον σεαυτω και ευθεως ανεστη[9:34]{.aside}

και ειδον αυτον παντες οι κατοικουντες λυδδαν και τον [ασσαρωνα]{.greek-omitted} [σαρωνα]{.greek-added} οιτινες επεστρεψαν επι [τον]{.greek-omitted} [κυριον]{.greek-abbr}[9:35]{.aside}

εν ιοππη δε τις ην μαθητρια ονοματι [ταβηθα]{.greek-omitted} [ταβιθα]{.greek-added} η διερμηνευομενη λεγεται δορκας αυτη ην πληρης αγαθων εργων και ελεημοσυνων ων εποιει[9:36]{.aside}

εγενετο δε [εν]{.greek-omitted} [ταις]{.greek-omitted} [ημεραις]{.greek-omitted} [εκειναις]{.greek-omitted} [ασθενησασαν]{.greek-omitted} [αυτην]{.greek-omitted} [αποθανειν]{.greek-omitted} [λουσαντες]{.greek-omitted} [δε]{.greek-omitted} [αυτην]{.greek-omitted} [εθηκαν]{.greek-omitted} [εν]{.greek-omitted} [υπερωω]{.greek-omitted}[9:37]{.aside}

[εγενετο]{.greek-omitted} [δε]{.greek-omitted} εν ταις ημεραις εκειναις ασθενησασαν αυτην αποθανειν λουσαντες δε αυτην εθηκαν εν υπερωω[9:37 | instance no. 2]{.aside}

εγγυς δε ουσης λυδδης τη ιοππη οι μαθηται ακουσαντες οτι πετρος εστιν εν αυτη απεστειλαν προς αυτον παρακαλουντες μη [οκνησαι]{.greek-omitted} [οκνισαι]{.greek-added} διελθειν εως αυτων[9:38]{.aside}

αναστας δε πετρος συνηλθεν αυτοις ον παραγενομενον ανηγαγον εις το υπερωον και παρεστησαν αυτω πασαι αι χηραι κλαιουσαι και επιδεικνυμεναι χιτωνας και ιματια οσα εποιει μετ αυτων ουσα η δορκας[9:39]{.aside}

εκβαλων δε εξω παντας ο πετρος θεις τα γονατα προσηυξατο και επιστρεψας προς το σωμα [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [ταβηθα]{.greek-omitted} [ταβιθα]{.greek-added} αναστηθι η δε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} τους οφθαλμους αυτης και ιδουσα τον πετρον [ανεκαθισεν]{.greek-omitted} [ανεκαθισε]{.greek-added}[9:40]{.aside}

δους δε αυτη χειρα ανεστησεν αυτην φωνησας δε τους αγιους και τας χηρας παρεστησεν αυτην ζωσαν[9:41]{.aside}

γνωστον δε εγενετο καθ ολης της ιοππης και πολλοι επιστευσαν επι τον [κυριον]{.greek-abbr}[9:42]{.aside}

εγενετο δε ημερας ικανας [μειναι]{.greek-omitted} [ειναι]{.greek-added} αυτον εν ιοππη παρα τινι σιμωνι βυρσει[9:43]{.aside}

### Chapter 10

ανηρ δε τις ην εν καισαρεια ονοματι κορνηλιος εκατονταρχης εκ σπειρης της καλουμενης ιταλικης[10:1]{.aside}

ευσεβης και φοβουμενος τον [θεον]{.greek-abbr} συν παντι τω οικω αυτου ποιων τε ελεημοσυνας πολλας τω λαω και δεομενος του [θεου]{.greek-abbr} δια παντος[10:2]{.aside}

ειδεν εν οραματι φανερως ωσει ωραν [ενατην]{.greek-omitted} [εννατην]{.greek-added} της ημερας αγγελον του [θεου]{.greek-abbr} εισελθοντα προς αυτον και ειποντα αυτω κορνηλιε[10:3]{.aside}

ο δε ατενισας αυτω και εμφοβος γενομενος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τι [εστιν]{.greek-omitted} [εστι]{.greek-added} [κυριε]{.greek-abbr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε αυτω αι προσευχαι σου και αι ελεημοσυναι σου ανεβησαν εις μνημοσυνον ενωπιον του [θεου]{.greek-abbr}[10:4]{.aside}

και νυν πεμψον εις ιοππην ανδρας και [μεταπεμψαι]{.greek-omitted} [μεταπεμψε]{.greek-added} σιμωνα τον επικαλουμενον πετρον[10:5]{.aside}

ουτος ξενιζεται παρα τινι σιμωνι βυρσει [ω]{.greek-omitted} [ου]{.greek-added} εστιν [η]{.greek-added} οικια παρα θαλασσαν[10:6]{.aside}

ως δε απηλθεν ο αγγελος ο λαλων τω κορνηλιω φωνησας δυο των οικετων [αυτου]{.greek-omitted} [και]{.greek-omitted} [στρατιωτην]{.greek-omitted} [ευσεβη]{.greek-omitted} [των]{.greek-omitted} [προσκαρτερουντων]{.greek-omitted} [αυτω]{.greek-omitted}[10:7]{.aside}

[ως]{.greek-omitted} [δε]{.greek-omitted} [απηλθεν]{.greek-omitted} [ο]{.greek-omitted} [αγγελος]{.greek-omitted} [ο]{.greek-omitted} [λαλων]{.greek-omitted} [τω]{.greek-omitted} [κορνηλιω]{.greek-omitted} [φωνησας]{.greek-omitted} [δυο]{.greek-omitted} [των]{.greek-omitted} [οικετων]{.greek-omitted} αυτου και στρατιωτην ευσεβη των προσκαρτερουντων αυτω[10:7 | instance no. 2]{.aside}

και εξηγησαμενος αυτοις απαντα απεστειλεν αυτους εις την ιοππην[10:8]{.aside}

τη δε επαυριον οδοιπορουντων εκεινων και τη πολει εγγιζοντων ανεβη πετρος επι το δωμα προσευξασθαι περι ωραν εκτην[10:9]{.aside}

εγενετο δε προσπεινος και [ηθελεν]{.greek-omitted} [ηθελε]{.greek-added} γευσασθαι παρασκευαζοντων δε εκεινων επεπεσεν επ αυτον εκστασις[10:10]{.aside}

και θεωρει τον [ουρανον]{.greek-abbr} ανεωγμενον και καταβαινον επ αυτον σκευος τι ως οθονην μεγαλην τεσσαρσιν αρχαις δεδεμενον και καθιεμενον επι της γης[10:11]{.aside}

εν ω [υπηρχεν]{.greek-omitted} [υπηρχε]{.greek-added} παντα τα τετραποδα της γης και τα θηρια και τα ερπετα και τα πετεινα του [ουρανου]{.greek-abbr}[10:12]{.aside}

και εγενετο φωνη προς αυτον [αναστας]{.greek-omitted} [αναστα]{.greek-added} πετρε θυσον και φαγε[10:13]{.aside}

ο δε πετρος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} μηδαμως [κυριε]{.greek-abbr} οτι ουδεποτε εφαγον παν κοινον η ακαθαρτον[10:14]{.aside}

και φωνη παλιν εκ δευτερου [εγενετο]{.greek-added} προς αυτον α ο [θεος]{.greek-abbr} [εκαθαρισεν]{.greek-omitted} [εκαθαρισε]{.greek-added} συ μη κοινου[10:15]{.aside}

τουτο δε εγενετο επι τρις και παλιν ανεληφθη το σκευος εις τον [ουρανον]{.greek-abbr}[10:16]{.aside}

ως δε [εν]{.greek-omitted} [επ]{.greek-added} [εαυτω]{.greek-omitted} [αυτω]{.greek-added} διηπορει ο πετρος τι αν ειη το οραμα ο [ειδεν]{.greek-omitted} [ειδε]{.greek-added} και ιδου οι ανδρες οι [απεσταλμενοι]{.greek-omitted} [αποσταλμενοι]{.greek-added} [απο]{.greek-omitted} [υπο]{.greek-added} του κορνηλιου διερωτησαντες την οικιαν σιμωνος επεστησαν επι τον πυλωνα[10:17]{.aside}

και φωνησαντες επυνθανοντο ει σιμων ο επικαλουμενος πετρος ενθαδε ξενιζεται[10:18]{.aside}

του δε πετρου διενθυμουμενου περι του οραματος ειπεν αυτω το πνευμα ιδου ανδρες [ζητουσιν]{.greek-omitted} [ζητουσι]{.greek-added} σε[10:19]{.aside}

αλλα αναστας καταβηθι και πορευου συν αυτοις μηδεν διακρινομενος διοτι εγω απεσταλκα αυτους[10:20]{.aside}

καταβας δε πετρος προς τους ανδρας [τους]{.greek-added} [αποσταλμενους]{.greek-added} [υπο]{.greek-added} [κορνηλιου]{.greek-added} ειπεν ιδου εγω ειμι ον ζητειτε τις η αιτια δι ην παρεστε[10:21]{.aside}

οι δε ειπον κορνηλιος [ο]{.greek-added} εκατονταρχης ανηρ δικαιος και φοβουμενος [τον]{.greek-omitted} [θεον]{.greek-omitted} [μαρτυρουμενος]{.greek-omitted} [τε]{.greek-omitted} [υπο]{.greek-omitted} [ολου]{.greek-omitted} [του]{.greek-omitted} [εθνους]{.greek-omitted} [των]{.greek-omitted} [ιουδαιων]{.greek-omitted} [εχρηματισθη]{.greek-omitted} [υπο]{.greek-omitted} [αγγελου]{.greek-omitted} [αγιου]{.greek-omitted} [μεταπεμψασθαι]{.greek-omitted} [σε]{.greek-omitted} [εις]{.greek-omitted} [τον]{.greek-omitted} [οικον]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [ακουσαι]{.greek-omitted} [ρηματα]{.greek-omitted} [παρα]{.greek-omitted} [σου]{.greek-omitted}[10:22]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [ειπον]{.greek-omitted} [κορνηλιος]{.greek-omitted} [εκατονταρχης]{.greek-omitted} [ανηρ]{.greek-omitted} [δικαιος]{.greek-omitted} [και]{.greek-omitted} [φοβουμενος]{.greek-omitted} τον [θεον]{.greek-abbr} μαρτυρουμενος τε υπο ολου του εθνους των ιουδαιων εχρηματισθη υπο αγγελου αγιου μεταπεμψασθαι σε εις τον οικον αυτου και ακουσαι ρηματα παρα σου[10:22 | instance no. 2]{.aside}

εισκαλεσαμενος ουν αυτους [εξενισεν]{.greek-omitted} [εξενησε]{.greek-added} τη δε επαυριον ο πετρος [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} συν αυτοις και τινες των αδελφων των απο ιοππης συνηλθον αυτω[10:23]{.aside}

και τη επαυριον [εισηλθον]{.greek-omitted} [συνηλθον]{.greek-added} εις την καισαρειαν ο δε κορνηλιος ην προσδοκων αυτους συγκαλεσαμενος τους συγγενεις αυτου και [τους]{.greek-omitted} αναγκαιους φιλους[10:24]{.aside}

ως δε εγενετο του εισελθειν τον πετρον συναντησας αυτω ο κορνηλιος πεσων επι τους ποδας προσεκυνησεν[10:25]{.aside}

ο δε πετρος [ηγειρεν]{.greek-added} αυτον [ηγειρεν]{.greek-omitted} λεγων αναστηθι καγω αυτος [ανθρωπος]{.greek-abbr} ειμι[10:26]{.aside}

και συνομιλων αυτω [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} και ευρισκει συνεληλυθοτας πολλους[10:27]{.aside}

εφη τε προς αυτους υμεις επιστασθε ως αθεμιτον εστιν ανδρι ιουδαιω κολλασθαι η προσερχεσθαι αλλοφυλω και εμοι ο [θεος]{.greek-abbr} [εδειξεν]{.greek-omitted} [εδειξε]{.greek-added} μηδενα κοινον η ακαθαρτον λεγειν [ανθρωπον]{.greek-abbr}[10:28]{.aside}

διο και [αναντιρρητως]{.greek-omitted} [αναντηρρητως]{.greek-added} ηλθον μεταπεμφθεις πυνθανομαι ουν τινι λογω μετεπεμψασθε με[10:29]{.aside}

και ο κορνηλιος εφη απο τεταρτης ημερας μεχρι ταυτης της ωρας ημην νηστευων και την [ενατην]{.greek-omitted} [εννατην]{.greek-added} ωραν προσευχομενος εν τω οικω μου και ιδου ανηρ εστη ενωπιον μου εν εσθητι λαμπρα[10:30]{.aside}

και [φησιν]{.greek-omitted} [φησι]{.greek-added} κορνηλιε εισηκουσθη σου η προσευχη και αι ελεημοσυναι σου εμνησθησαν ενωπιον του [θεου]{.greek-abbr}[10:31]{.aside}

πεμψον ουν εις ιοππην και [μετακαλεσαι]{.greek-omitted} [μετακαλεσε]{.greek-added} σιμωνα ος επικαλειται πετρος ουτος ξενιζεται εν οικια σιμωνος βυρσεως παρα θαλασσαν [ος]{.greek-omitted} [παραγενομενος]{.greek-omitted} [λαλησει]{.greek-omitted} [σοι]{.greek-omitted}[10:32]{.aside}

εξαυτης ουν επεμψα προς σε συ τε καλως εποιησας παραγενομενος νυν ουν παντες ημεις ενωπιον του [θεου]{.greek-abbr} παρεσμεν ακουσαι παντα τα προστεταγμενα σοι υπο του [θεου]{.greek-abbr}[10:33]{.aside}

ανοιξας δε πετρος το στομα ειπεν επ αληθειας καταλαμβανομαι οτι [ουκ]{.greek-omitted} [ου]{.greek-added} [εστιν]{.greek-omitted} [προσωποληπτης]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted}[10:34]{.aside}

[κ]{.greek-added} [ανοιξας]{.greek-omitted} [δε]{.greek-omitted} [πετρος]{.greek-omitted} [το]{.greek-omitted} [στομα]{.greek-omitted} [ειπεν]{.greek-omitted} [επ]{.greek-omitted} [αληθειας]{.greek-omitted} [καταλαμβανομαι]{.greek-omitted} [οτι]{.greek-omitted} [ουκ]{.greek-omitted} [εστιν]{.greek-omitted} [εστι]{.greek-added} προσωποληπτης ο [θεος]{.greek-abbr}[10:34 | instance no. 2]{.aside}

αλλ εν παντι εθνει ο φοβουμενος αυτον και εργαζομενος δικαιοσυνην δεκτος αυτω [εστιν]{.greek-omitted} [εστι]{.greek-added}[10:35]{.aside}

τον λογον ον [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} τοις υιοις [ισραηλ]{.greek-abbr} ευαγγελιζομενος ειρηνην δια [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} ουτος [εστιν]{.greek-omitted} [εστι]{.greek-added} παντων [κυριος]{.greek-abbr}[10:36]{.aside}

υμεις οιδατε το γενομενον ρημα καθ ολης της ιουδαιας αρξαμενον απο της γαλιλαιας μετα το βαπτισμα ο εκηρυξεν [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added}[10:37]{.aside}

[ιησουν]{.greek-abbr} τον απο ναζαρετ ως εχρισεν αυτον ο [θεος]{.greek-abbr} [πνευματι]{.greek-abbr} αγιω και δυναμει ος διηλθεν ευεργετων και ιωμενος παντας τους καταδυναστευομενους υπο του διαβολου οτι ο [θεος]{.greek-abbr} ην μετ αυτου[10:38]{.aside}

και ημεις εσμεν μαρτυρες παντων ων εποιησεν εν τε τη χωρα των ιουδαιων και [εν]{.greek-omitted} [ιερουσαλημ]{.greek-abbr} ον και ανειλον κρεμασαντες επι ξυλου[10:39]{.aside}

τουτον ο [θεος]{.greek-abbr} ηγειρεν τη τριτη ημερα και εδωκεν αυτον εμφανη γενεσθαι[10:40]{.aside}

ου παντι τω λαω αλλα [μαρτυσιν]{.greek-omitted} [μαρτυσι]{.greek-added} τοις [προκεχειροτονημενοις]{.greek-omitted} [προκεχειροτονιμενοις]{.greek-added} υπο του [θεου]{.greek-abbr} ημιν οιτινες [συνεφαγομεν]{.greek-omitted} [συνεφαγωμεν]{.greek-added} και [συνεπιομεν]{.greek-omitted} [συνεπιωμεν]{.greek-added} αυτω μετα το αναστηναι αυτον εκ νεκρων[10:41]{.aside}

και παρηγγειλεν ημιν κηρυξαι τω λαω και διαμαρτυρασθαι οτι αυτος εστιν ο ωρισμενος υπο του [θεου]{.greek-abbr} κριτης ζωντων και νεκρων[10:42]{.aside}

τουτω παντες οι προφηται μαρτυρουσιν αφεσιν αμαρτιων λαβειν δια του ονοματος αυτου παντα τον πιστευοντα εις αυτον[10:43]{.aside}

ετι λαλουντος του πετρου [προς]{.greek-added} [τον]{.greek-added} [λαον]{.greek-added} τα ρηματα ταυτα [επεπεσεν]{.greek-omitted} [επεπεσε]{.greek-added} το [πνευμα]{.greek-abbr} το αγιον επι παντας τους ακουοντας τον λογον[10:44]{.aside}

και εξεστησαν οι εκ περιτομης πιστοι οσοι συνηλθον τω πετρω οτι και επι τα εθνη η δωρεα του αγιου [πνευματος]{.greek-abbr} εκκεχυται[10:45]{.aside}

ηκουον γαρ αυτων λαλουντων γλωσσαις και μεγαλυνοντων τον [θεον]{.greek-abbr} τοτε απεκριθη ο πετρος[10:46]{.aside}

μητι το υδωρ κωλυσαι δυναται τις του μη [βαπτισθηναι]{.greek-omitted} [βαπισθηναι]{.greek-added} τουτους οιτινες το [πνευμα]{.greek-abbr} το αγιον ελαβον καθως και ημεις[10:47]{.aside}

[προσεταξεν]{.greek-omitted} [προσεταξε]{.greek-added} [τε]{.greek-omitted} [δε]{.greek-added} αυτους βαπτισθηναι εν τω ονοματι του [κυριου]{.greek-abbr} τοτε ηρωτησαν αυτον επιμειναι ημερας τινας[10:48]{.aside}

### Chapter 11

ηκουσαν δε οι αποστολοι και οι αδελφοι οι οντες κατα την [ιουδαιαν]{.greek-omitted} [οτι]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} [εθνη]{.greek-omitted} [εδεξαντο]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted}[11:1]{.aside}

[ηκουσαν]{.greek-omitted} [δε]{.greek-omitted} [οι]{.greek-omitted} [αποστολοι]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [αδελφοι]{.greek-omitted} [οι]{.greek-omitted} [οντες]{.greek-omitted} [κατα]{.greek-omitted} [την]{.greek-omitted} ιουδαιαν οτι και τα εθνη εδεξαντο τον λογον του [θεου]{.greek-abbr}[11:1 | instance no. 2]{.aside}

και οτε ανεβη πετρος εις ιεροσολυμα διεκρινοντο προς αυτον οι εκ περιτομης[11:2]{.aside}

λεγοντες οτι προς ανδρας ακροβυστιαν εχοντας εισηλθες και συνεφαγες αυτοις[11:3]{.aside}

αρξαμενος δε ο πετρος εξετιθετο αυτοις καθεξης λεγων[11:4]{.aside}

εγω ημην εν πολει ιοππη προσευχομενος και ειδον εν εκστασει οραμα καταβαινον σκευος τι ως οθονην μεγαλην τεσσαρσιν αρχαις καθιεμενην εκ του [ουρανου]{.greek-abbr} και ηλθεν [αχρι]{.greek-omitted} [αχρις]{.greek-added} εμου[11:5]{.aside}

εις ην ατενισας κατενοουν και ειδον τα τετραποδα [της]{.greek-omitted} [γης]{.greek-omitted} και τα θηρια και τα ερπετα και τα πετεινα του [ουρανου]{.greek-abbr}[11:6]{.aside}

ηκουσα δε φωνης λεγουσης μοι [αναστας]{.greek-omitted} [αναστα]{.greek-added} πετρε θυσον και φαγε[11:7]{.aside}

ειπον δε μηδαμως [κυριε]{.greek-abbr} οτι παν κοινον η ακαθαρτον ουδεποτε εισηλθεν εις το στομα μου[11:8]{.aside}

απεκριθη δε μοι φωνη εκ δευτερου εκ του [ουρανου]{.greek-abbr} α ο [θεος]{.greek-abbr} [εκαθαρισεν]{.greek-omitted} [εκαθερισε]{.greek-added} συ μη κοινου[11:9]{.aside}

τουτο δε εγενετο επι τρις και παλιν ανεσπασθη απαντα εις τον [ουρανον]{.greek-abbr}[11:10]{.aside}

και ιδου εξαυτης τρεις ανδρες επεστησαν επι την οικιαν εν η ημην [απεσταλμενοι]{.greek-omitted} [αποσταλμενοι]{.greek-added} απο καισαρειας προς με[11:11]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε μοι το [πνευμα]{.greek-abbr} συνελθειν αυτοις μηδεν διακρινομενον ηλθον δε συν εμοι και οι εξ αδελφοι ουτοι και εισηλθομεν εις τον οικον του ανδρος[11:12]{.aside}

[απηγγειλεν]{.greek-omitted} [απηγγειλε]{.greek-added} [τε]{.greek-omitted} [δε]{.greek-added} ημιν πως [ειδεν]{.greek-omitted} [ειδε]{.greek-added} τον αγγελον εν τω οικω αυτου σταθεντα και ειποντα αυτω αποστειλον εις ιοππην ανδρας και [μεταπεμψαι]{.greek-omitted} [μεταπεμψε]{.greek-added} σιμωνα τον επικαλουμενον πετρον[11:13]{.aside}

ος λαλησει ρηματα προς σε εν οις σωθηση συ και πας ο οικος σου[11:14]{.aside}

εν δε [τω]{.greek-omitted} [το]{.greek-added} αρξασθαι με λαλειν [επεπεσεν]{.greek-omitted} [επεπεσε]{.greek-added} το [πνευμα]{.greek-abbr} το αγιον επ αυτους ωσπερ και εφ ημας εν αρχη[11:15]{.aside}

εμνησθην δε του ρηματος [κυριου]{.greek-abbr} ως ελεγεν ιωαννης μεν εβαπτισεν υδατι υμεις δε βαπτισθησεσθε εν [πνευματι]{.greek-abbr} αγιω[11:16]{.aside}

ει ουν την [ισην]{.greek-omitted} [ισιν]{.greek-added} δωρεαν εδωκεν αυτοις ο [θεος]{.greek-abbr} ως και ημιν πιστευσασιν επι τον [κυριον]{.greek-abbr} [ημων]{.greek-added} [ιησουν]{.greek-abbr} [χριστον]{.greek-abbr} εγω δε τις ημην δυνατος κωλυσαι τον [θεον]{.greek-abbr}[11:17]{.aside}

ακουσαντες δε ταυτα [ησυ]{.greek-added} [ησυχασαν]{.greek-omitted} [και]{.greek-omitted} [εδοξαζον]{.greek-omitted} [τον]{.greek-omitted} [θεον]{.greek-omitted} [λεγοντες]{.greek-omitted} [αρα]{.greek-omitted} [γε]{.greek-omitted} [και]{.greek-omitted} [τοις]{.greek-omitted} [εθνεσιν]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [την]{.greek-omitted} [μετανοιαν]{.greek-omitted} [εδωκεν]{.greek-omitted} [εις]{.greek-omitted} [ζωην]{.greek-omitted}[11:18]{.aside}

[ακουσαντες]{.greek-omitted} [δε]{.greek-omitted} [ταυτα]{.greek-omitted} [ησυχασαν]{.greek-omitted} [χασαν]{.greek-added} και εδοξαζον τον [θεον]{.greek-abbr} λεγοντες αρα γε και τοις εθνεσιν ο [θεος]{.greek-abbr} την μετανοιαν εδωκεν εις ζωην[11:18 | instance no. 2]{.aside}

οι μεν ουν διασπαρεντες απο της θλιψεως της γενομενης επι στεφανω διηλθον εως φοινικης και κυπρου και αντιοχειας μηδενι λαλουντες τον λογον ει μη μονον ιουδαιοις[11:19]{.aside}

ησαν δε τινες εξ αυτων ανδρες κυπριοι και κυρηναιοι οιτινες εισελθοντες εις αντιοχειαν ελαλουν προς τους ελληνιστας ευαγγελιζομενοι τον [κυριον]{.greek-abbr} [ιησουν]{.greek-abbr}[11:20]{.aside}

και ην χειρ [κυριου]{.greek-abbr} μετ αυτων πολυς τε αριθμος πιστευσας επεστρεψεν επι τον [κυριον]{.greek-abbr}[11:21]{.aside}

ηκουσθη δε ο λογος εις τα ωτα της εκκλησιας της εν ιεροσολυμοις περι αυτων και εξαπεστειλαν βαρναβαν διελθειν εως αντιοχειας[11:22]{.aside}

ος παραγενομενος και ιδων την χαριν του [θεου]{.greek-abbr} εχαρη και παρεκαλει παντας τη προθεσει της καρδιας προσμενειν τω [κυριω]{.greek-abbr}[11:23]{.aside}

οτι ην ανηρ αγαθος και πληρης [πνευματος]{.greek-abbr} αγιου και πιστεως και προσετεθη οχλος ικανος τω [κυριω]{.greek-abbr}[11:24]{.aside}

[εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} δε εις ταρσον ο βαρναβας αναζητησαι σαυλον[11:25]{.aside}

και ευρων [αυτον]{.greek-added} ηγαγεν [αυτον]{.greek-omitted} εις αντιοχειαν εγενετο δε αυτους ενιαυτον ολον συναχθηναι [εν]{.greek-added} τη εκκλησια και διδαξαι οχλον ικανον χρηματισαι τε πρωτον εν αντιοχεια τους μαθητας χριστιανους[11:26]{.aside}

εν ταυταις δε ταις ημεραις κατηλθον απο ιεροσολυμων προφηται εις αντιοχειαν[11:27]{.aside}

αναστας δε εις εξ αυτων ονοματι αγαβος [εσημανεν]{.greek-omitted} [εσημανε]{.greek-added} δια του [πνευματος]{.greek-abbr} λιμον [μεγαν]{.greek-omitted} [μεγα]{.greek-added} μελλειν εσεσθαι εφ ολην την οικουμενην οστις και εγενετο επι κλαυδιου καισαρος[11:28]{.aside}

των δε μαθητων καθως [ευπορειτο]{.greek-omitted} [ηυπορειτο]{.greek-added} τις ωρισαν εκαστος αυτων εις διακονιαν πεμψαι τοις κατοικουσιν εν τη ιουδαια αδελφοις[11:29]{.aside}

ο και εποιησαν αποστειλαντες προς τους πρεσβυτερους δια χειρος βαρναβα και σαυλου[11:30]{.aside}

### Chapter 12

κατ εκεινον δε τον καιρον επεβαλεν ηρωδης ο βασιλευς τας χειρας κακωσαι τινας των απο της [εκκλησιας]{.greek-omitted}[12:1]{.aside}

[κατ]{.greek-omitted} [εκεινον]{.greek-omitted} [δε]{.greek-omitted} [τον]{.greek-omitted} [καιρον]{.greek-omitted} [επεβαλεν]{.greek-omitted} [ηρωδης]{.greek-omitted} [ο]{.greek-omitted} [βασιλευς]{.greek-omitted} [τας]{.greek-omitted} [χειρας]{.greek-omitted} [κακωσαι]{.greek-omitted} [τινας]{.greek-omitted} [των]{.greek-omitted} [απο]{.greek-omitted} [της]{.greek-omitted} εκκλησιας[12:1 | instance no. 2]{.aside}

[ανειλεν]{.greek-omitted} [ανειλε]{.greek-added} δε ιακωβον τον αδελφον ιωαννου μαχαιρα[12:2]{.aside}

και ιδων οτι αρεστον [εστιν]{.greek-omitted} [εστι]{.greek-added} τοις ιουδαιοις προσεθετο συλλαβειν και πετρον ησαν δε αι ημεραι των αζυμων[12:3]{.aside}

ον και πιασας εθετο εις φυλακην παραδους [τεσσαρσιν]{.greek-omitted} [τεσσαρσι]{.greek-added} τετραδιοις στρατιωτων φυλασσειν αυτον βουλομενος μετα το πασχα αναγαγειν αυτον τω λαω[12:4]{.aside}

ο μεν ουν πετρος ετηρειτο εν τη φυλακη προσευχη δε ην εκτενης γινομενη υπο της εκκλησιας προς τον [θεον]{.greek-abbr} υπερ αυτου[12:5]{.aside}

οτε δε εμελλεν αυτον προαγειν ο ηρωδης τη νυκτι εκεινη ην ο πετρος κοιμωμενος μεταξυ δυο στρατιωτων δεδεμενος [αλυσεσιν]{.greek-omitted} [αλυσεσι]{.greek-added} [δυσιν]{.greek-omitted} [δυσι]{.greek-added} φυλακες τε προ της θυρας ετηρουν την φυλακην[12:6]{.aside}

και ιδου αγγελος [κυριου]{.greek-abbr} επεστη και φως ελαμψεν εν τω οικηματι παταξας δε την πλευραν του πετρου ηγειρεν αυτον λεγων αναστα εν ταχει και εξεπεσον αυτου αι αλυσεις εκ των χειρων[12:7]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} τε ο αγγελος προς αυτον [περιζωσαι]{.greek-omitted} [περιζωσε]{.greek-added} και [υποδησαι]{.greek-omitted} [υποδησε]{.greek-added} τα σανδαλια σου [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} δε ουτως και λεγει αυτω περιβαλου το ιματιον σου και ακολουθει μοι[12:8]{.aside}

και εξελθων ηκολουθει αυτω και ουκ ηδει οτι αληθες [εστιν]{.greek-omitted} [εστι]{.greek-added} το [γινομενον]{.greek-omitted} [γενομενον]{.greek-added} [δια]{.greek-omitted} [υπο]{.greek-added} του αγγελου εδοκει δε οραμα βλεπειν[12:9]{.aside}

διελθοντες δε πρωτην φυλακην και δευτεραν ηλθον επι την πυλην την σιδηραν την φερουσαν εις την πολιν ητις [αυτοματη]{.greek-omitted} [αυτοματι]{.greek-added} ηνοιχθη αυτοις και εξελθοντες προηλθον ρυμην μιαν και ευθεως απεστη ο αγγελος απ αυτου[12:10]{.aside}

και ο πετρος γενομενος εν εαυτω [ειπεν]{.greek-omitted} [ειπε]{.greek-added} νυν οιδα αληθως οτι [εξαπεστειλεν]{.greek-omitted} [εξαπεστειλε]{.greek-added} [κυριος]{.greek-abbr} τον αγγελον αυτου και [εξειλετο]{.greek-omitted} [εξειλατο]{.greek-added} με εκ χειρος ηρωδου και πασης της προσδοκιας του λαου των ιουδαιων[12:11]{.aside}

συνιδων τε [ο]{.greek-added} [πετρος]{.greek-added} ηλθεν επι την οικιαν μαριας της [μητρος]{.greek-abbr} [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} του επικαλουμενου μαρκου ου ησαν ικανοι [συνηθροισμενοι]{.greek-omitted} [συνηγμενοι]{.greek-added} και προσευχομενοι[12:12]{.aside}

κρουσαντος δε του [πε]{.greek-added} [πετρου]{.greek-omitted} [την]{.greek-omitted} [θυραν]{.greek-omitted} [του]{.greek-omitted} [πυλωνος]{.greek-omitted} [προσηλθεν]{.greek-omitted} [παιδισκη]{.greek-omitted} [υπακουσαι]{.greek-omitted} [ονοματι]{.greek-omitted} [ροδη]{.greek-omitted}[12:13]{.aside}

[κρουσαντος]{.greek-omitted} [δε]{.greek-omitted} [του]{.greek-omitted} [τρου]{.greek-added} [πετρου]{.greek-omitted} την θυραν του πυλωνος [προσηλθεν]{.greek-omitted} [προσηλθε]{.greek-added} παιδισκη υπακουσαι ονοματι ροδη[12:13 | instance no. 2]{.aside}

και επιγνουσα την φωνην του πετρου απο της χαρας ουκ [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} τον πυλωνα εισδραμουσα δε απηγγειλεν εσταναι τον πετρον προ του πυλωνος[12:14]{.aside}

οι δε προς αυτην ειπον [μαινη]{.greek-omitted} [μαινει]{.greek-added} η δε διισχυριζετο ουτως εχειν οι δε ελεγον ο αγγελος αυτου εστιν[12:15]{.aside}

ο δε πετρος [επεμενεν]{.greek-omitted} [επεμενε]{.greek-added} κρουων ανοιξαντες δε ειδον αυτον και εξεστησαν[12:16]{.aside}

κατασεισας δε αυτοις [τη]{.greek-omitted} [την]{.greek-added} [χειρι]{.greek-omitted} [χειρα]{.greek-added} σιγαν διηγησατο αυτοις πως ο [κυριος]{.greek-abbr} αυτον εξηγαγεν εκ της φυλακης [ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε απαγγειλατε ιακωβω και τοις αδελφοις ταυτα και εξελθων επορευθη εις ετερον τοπον[12:17]{.aside}

γενομενης δε ημερας ην ταραχος ουκ ολιγος εν τοις στρατιωταις τι αρα ο πετρος εγενετο[12:18]{.aside}

ηρωδης δε επιζητησας αυτον και μη ευρων ανακρινας τους φυλακας εκελευσεν απαχθηναι και κατελθων απο της ιουδαιας εις την καισαρειαν διετριβεν[12:19]{.aside}

ην δε ο ηρωδης θυμομαχων τυριοις και σιδωνιοις ομοθυμαδον δε παρησαν προς αυτον και πεισαντες βλαστον τον επι του κοιτωνος του βασιλεως ητουντο ειρηνην δια το τρεφεσθαι αυτων την χωραν απο της βασιλικης[12:20]{.aside}

τακτη δε ημερα [ο]{.greek-omitted} ηρωδης ενδυσαμενος εσθητα βασιλικην και καθισας επι του βηματος εδημηγορει προς αυτους[12:21]{.aside}

ο δε δημος επεφωνει [[θεου]{.greek-abbr}]{.greek-added} φωνη [θεου]{.greek-omitted} και ουκ [ανθρωπου]{.greek-abbr}[12:22]{.aside}

παραχρημα δε επαταξεν αυτον αγγελος [κυριου]{.greek-abbr} ανθ ων ουκ [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} δοξαν τω [θεω]{.greek-abbr} και γενομενος σκωληκοβρωτος εξεψυξεν[12:23]{.aside}

βαρναβας δε και σαυλος υπεστρεψαν [εις]{.greek-omitted} [απο]{.greek-added} [ιερουσαλημ]{.greek-abbr} πληρωσαντες την διακονιαν συμπαραλαβοντες και ιωαννην τον επικληθεντα μαρκον[12:25]{.aside}

### Chapter 13

ησαν δε [τινες]{.greek-omitted} εν αντιοχεια κατα την ουσαν εκκλησιαν προφηται και διδασκαλοι ο τε βαρναβας και συμεων ο [καλουμενος]{.greek-omitted} [επικαλουμενος]{.greek-added} νιγερ και λουκιος ο κυρηναιος μαναην τε ηρωδου του τετραρχου συντροφος [και]{.greek-omitted} [σαυλος]{.greek-omitted}[13:1]{.aside}

[ησαν]{.greek-omitted} [δε]{.greek-omitted} [τινες]{.greek-omitted} [εν]{.greek-omitted} [αντιοχεια]{.greek-omitted} [κατα]{.greek-omitted} [την]{.greek-omitted} [ουσαν]{.greek-omitted} [εκκλησιαν]{.greek-omitted} [προφηται]{.greek-omitted} [και]{.greek-omitted} [διδασκαλοι]{.greek-omitted} [ο]{.greek-omitted} [τε]{.greek-omitted} [βαρναβας]{.greek-omitted} [και]{.greek-omitted} [συμεων]{.greek-omitted} [ο]{.greek-omitted} [καλουμενος]{.greek-omitted} [νιγερ]{.greek-omitted} [και]{.greek-omitted} [λουκιος]{.greek-omitted} [ο]{.greek-omitted} [κυρηναιος]{.greek-omitted} [μαναην]{.greek-omitted} [τε]{.greek-omitted} [ηρωδου]{.greek-omitted} [του]{.greek-omitted} [τετραρχου]{.greek-omitted} [συντροφος]{.greek-omitted} και σαυλος[13:1 | instance no. 2]{.aside}

λειτουργουντων δε αυτων τω [κυριω]{.greek-abbr} και νηστευοντων [ειπεν]{.greek-omitted} [ειπε]{.greek-added} το [πνευμα]{.greek-abbr} το αγιον αφορισατε [δη]{.greek-omitted} μοι τον βαρναβαν και τον σαυλον εις το εργον ο προσκεκλημαι αυτους[13:2]{.aside}

τοτε νηστευσαντες και προσευξαμενοι και επιθεντες τας χειρας αυτοις απελυσαν[13:3]{.aside}

[ουτοι]{.greek-omitted} [αυτοι]{.greek-added} μεν ουν εκπεμφθεντες υπο του [αγιου]{.greek-added} [πνευματος]{.greek-abbr} [του]{.greek-omitted} [αγιου]{.greek-omitted} κατηλθον εις [την]{.greek-omitted} σελευκειαν εκειθεν [δε]{.greek-omitted} [τε]{.greek-added} απεπλευσαν εις [την]{.greek-omitted} κυπρον[13:4]{.aside}

και γενομενοι εν [σαλαμινι]{.greek-omitted} [σαλαμηνη]{.greek-added} κατηγγελλον τον λογον του [θεου]{.greek-abbr} εν ταις συναγωγαις των ιουδαιων ειχον δε και ιωαννην υπηρετην[13:5]{.aside}

διελθοντες δε [ολην]{.greek-added} την νησον αχρι παφου ευρον [εκει]{.greek-added} τινα μαγον ψευδοπροφητην ιουδαιον [ω]{.greek-omitted} ονομα [βαριησους]{.greek-omitted} [βαριιησουν]{.greek-added}[13:6]{.aside}

ος ην συν τω ανθυπατω σεργιω παυλω ανδρι συνετω ουτος προσκαλεσαμενος βαρναβαν και σαυλον επεζητησεν ακουσαι τον λογον του [θεου]{.greek-abbr}[13:7]{.aside}

ανθιστατο δε αυτοις ελυμας ο μαγος ουτως γαρ μεθερμηνευεται το ονομα αυτου ζητων διαστρεψαι τον ανθυπατον απο της πιστεως[13:8]{.aside}

σαυλος δε ο και παυλος πλησθεις [πνευματος]{.greek-abbr} αγιου [και]{.greek-omitted} ατενισας εις αυτον[13:9]{.aside}

ειπεν ω πληρης παντος δολου και πασης ραδιουργιας υιε διαβολου εχθρε πασης δικαιοσυνης ου [παυση]{.greek-omitted} [παυει]{.greek-added} διαστρεφων τας οδους [κυριου]{.greek-abbr} τας ευθειας[13:10]{.aside}

και νυν ιδου χειρ [κυριου]{.greek-abbr} επι σε και εση τυφλος μη βλεπων τον ηλιον [αχρι]{.greek-omitted} [μεχρι]{.greek-added} καιρου παραχρημα δε [επεπεσεν]{.greek-omitted} [επεσεν]{.greek-added} επ αυτον αχλυς και σκοτος και περιαγων εζητει χειραγωγους[13:11]{.aside}

τοτε ιδων ο ανθυπατος το γεγονος επιστευσεν εκπλησσομενος επι τη διδαχη του [κυριου]{.greek-abbr}[13:12]{.aside}

αναχθεντες δε απο της παφου οι περι τον παυλον ηλθον εις [την]{.greek-added} περγην της παμφυλιας ιωαννης δε [αποχωρησας]{.greek-omitted} [αποχωρισας]{.greek-added} απ αυτων υπεστρεψεν εις [ιεροσολυμ[οις]{.unclear}]{.greek-added} [ιεροσολυμα]{.corr}[13:13]{.aside}

αυτοι δε διελθοντες απο της περγης παρεγενοντο εις αντιοχειαν της πισιδιας και εισελθοντες εις την συναγωγην τη ημερα των σαββατων εκαθισαν[13:14]{.aside}

μετα δε την αναγνωσιν του νομου και των προφητων [απεστειλαν]{.greek-omitted} [οι]{.greek-omitted} [αρχισυναγωγοι]{.greek-omitted} [προς]{.greek-omitted} [αυτους]{.greek-omitted} [λεγοντες]{.greek-omitted} [ανδρες]{.greek-omitted} [αδελφοι]{.greek-omitted} [ει]{.greek-omitted} [εστιν]{.greek-omitted} [λογος]{.greek-omitted} [εν]{.greek-omitted} [υμιν]{.greek-omitted} [παρακλησεως]{.greek-omitted} [προς]{.greek-omitted} [τον]{.greek-omitted} [λαον]{.greek-omitted} [λεγετε]{.greek-omitted}[13:15]{.aside}

[μετα]{.greek-omitted} [δε]{.greek-omitted} [την]{.greek-omitted} [αναγνωσιν]{.greek-omitted} [του]{.greek-omitted} [νομου]{.greek-omitted} [και]{.greek-omitted} [των]{.greek-omitted} [προφητων]{.greek-omitted} απεστειλαν οι αρχισυναγωγοι προς αυτους λεγοντες ανδρες αδελφοι ει [τις]{.greek-added} εστιν [λογος]{.greek-omitted} εν υμιν [λογος]{.greek-added} παρακλησεως προς τον λαον λεγετε[13:15 | instance no. 2]{.aside}

αναστας δε παυλος και κατασεισας τη χειρι ειπεν ανδρες ισραηλιται και οι φοβουμενοι τον [θεον]{.greek-abbr} ακουσατε[13:16]{.aside}

ο [θεος]{.greek-abbr} του λαου τουτου εξελεξατο τους [πατερας]{.greek-abbr} ημων και τον λαον υψωσεν εν τη παροικια εν γη αιγυπτω και μετα βραχιονος υψηλου εξηγαγεν αυτους εξ αυτης[13:17]{.aside}

και ως τεσσαρακονταετη χρονον ετροποφορησεν αυτους εν τη ερημω[13:18]{.aside}

και καθελων εθνη επτα εν γη χανααν κατεκληρονομησεν αυτοις την γην αυτων[13:19]{.aside}

[ως]{.greek-added} [ετεσι]{.greek-added} [τετρακοσιοις]{.greek-added} [και]{.greek-added} [πεντηκοντα]{.greek-added} και μετα ταυτα [ως]{.greek-omitted} [ετεσιν]{.greek-omitted} [τετρακοσιοις]{.greek-omitted} [και]{.greek-omitted} [πεντηκοντα]{.greek-omitted} [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} κριτας εως σαμουηλ του προφητου[13:20]{.aside}

κακειθεν ητησαντο βασιλεα και εδωκεν αυτοις ο [θεος]{.greek-abbr} τον σαουλ [τον]{.greek-added} υιον κις ανδρα εκ φυλης βενιαμιν ετη τεσσαρακοντα[13:21]{.aside}

και μεταστησας αυτον ηγειρεν αυτοις τον [δαυιδ]{.greek-abbr} εις βασιλεα ω και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} μαρτυρησας ευρον [δαυιδ]{.greek-abbr} τον του ιεσσαι ανδρα κατα την καρδιαν μου ος ποιησει παντα τα θεληματα μου[13:22]{.aside}

τουτου ο [θεος]{.greek-abbr} απο του σπερματος κατ επαγγελιαν [ηγαγεν]{.greek-omitted} [ηγειρε]{.greek-added} τω [ισραηλ]{.greek-abbr} [σωτηριαν]{.greek-omitted} [[σωτηρα]{.greek-abbr}]{.greek-added} [[ιησουν]{.greek-abbr}]{.greek-added}[13:23]{.aside}

προκηρυξαντος ιωαννου προ προσωπου της εισοδου αυτου βαπτισμα μετανοιας [παντι]{.greek-added} τω [ισραηλ]{.greek-omitted} [λαω]{.greek-added}[13:24]{.aside}

ως δε επληρου [ο]{.greek-omitted} ιωαννης τον δρομον [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} τινα με υπονοειτε ειναι ουκ ειμι εγω αλλ ιδου ερχεται μετ εμε ου ουκ ειμι αξιος το υποδημα των ποδων λυσαι[13:25]{.aside}

ανδρες αδελφοι υιοι γενους αβρααμ και οι εν υμιν φοβουμενοι τον [θεον]{.greek-abbr} υμιν ο λογος της [σωτηριας]{.greek-abbr} ταυτης [απεσταλη]{.greek-omitted} [εξαπεσταλη]{.greek-added}[13:26]{.aside}

οι γαρ κατοικουντες εν [ιερουσαλημ]{.greek-abbr} και οι αρχοντες αυτων τουτον αγνοησαντες και τας φωνας των προφητων τας κατα παν σαββατον αναγινωσκομενας κριναντες επληρωσαν[13:27]{.aside}

και μηδεμιαν αιτιαν θανατου ευροντες ητησαντο πιλατον αναιρεθηναι αυτον[13:28]{.aside}

ως δε ετελεσαν παντα τα περι αυτου [γεγραμμενα]{.greek-omitted} [καθελοντες]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [ξυλου]{.greek-omitted} [εθηκαν]{.greek-omitted} [εις]{.greek-omitted} [μνημειον]{.greek-omitted}[13:29]{.aside}

[ως]{.greek-omitted} [δε]{.greek-omitted} [ετελεσαν]{.greek-omitted} [παντα]{.greek-omitted} [τα]{.greek-omitted} [περι]{.greek-omitted} [αυτου]{.greek-omitted} γεγραμμενα καθελοντες απο του ξυλου εθηκαν εις μνημειον[13:29 | instance no. 2]{.aside}

ο δε [θεος]{.greek-abbr} ηγειρεν αυτον εκ νεκρων[13:30]{.aside}

ος ωφθη επι ημερας πλειους τοις συναναβασιν αυτω απο της γαλιλαιας εις [ιερουσαλημ]{.greek-abbr} οιτινες [νυν]{.greek-added} [εισιν]{.greek-omitted} [εισι]{.greek-added} μαρτυρες αυτου προς τον λαον[13:31]{.aside}

και ημεις υμας ευαγγελιζομεθα τ[η]{.unclear}ν προς τους [πατερας]{.greek-abbr} επαγγελιαν γενομενην [οτι]{.greek-omitted} [ταυτην]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [εκπεπληρωκεν]{.greek-omitted} [τοις]{.greek-omitted} [τεκνοις]{.greek-omitted} [αυτων]{.greek-omitted} [ημιν]{.greek-omitted} [αναστησας]{.greek-omitted} [ιησουν]{.greek-omitted}[13:32]{.aside}

[οτι]{.greek-added} [ταυτην]{.greek-added} [ο]{.greek-added} [[θεος]{.greek-abbr}]{.greek-added} [εκπεπληρωκε]{.greek-added} [τοις]{.greek-added} [τεκνοις]{.greek-added} [αυτων]{.greek-added} [ημιν]{.greek-added} [αναστησας]{.greek-added} [[ιησουν]{.greek-abbr}]{.greek-added} ως και εν τω ψαλμω [γεγραπται]{.greek-added} τω δευτερω [γεγραπται]{.greek-omitted} υιος μου ει συ εγω σημερον γεγεννηκα σε[13:33]{.aside}

οτι δε ανεστησεν αυτον [ο]{.greek-added} [[θεος]{.greek-abbr}]{.greek-added} εκ νεκρων μηκετι μελλοντα υποστρεφειν εις διαφθοραν ουτως ειρηκεν οτι δωσω υμιν τα οσια [δαυιδ]{.greek-abbr} τα πιστα[13:34]{.aside}

διο και εν ετερω λεγει ου [δωσεις]{.greek-omitted} [δοσεις]{.greek-added} τον οσιον σου ιδειν διαφθοραν[13:35]{.aside}

[δαυιδ]{.greek-abbr} μεν γαρ ιδια γενεα υπηρετησας τη του [θεου]{.greek-abbr} βουλη εκοιμηθη και προσετεθη προς τους [πατερας]{.greek-abbr} αυτου και [ειδεν]{.greek-omitted} [ειδε]{.greek-added} διαφθοραν[13:36]{.aside}

ον δε ο [θεος]{.greek-abbr} ηγειρεν ουκ [ειδεν]{.greek-omitted} [ειδε]{.greek-added} διαφθοραν[13:37]{.aside}

γνωστον ουν εστω υμιν ανδρες αδελφοι οτι [δια]{.greek-omitted} [δι]{.greek-added} [αυτου]{.greek-added} [τουτου]{.greek-omitted} [υμιν]{.greek-omitted} αφεσις αμαρτιων [υμιν]{.greek-added} καταγγελλεται [και]{.greek-added} [απο]{.greek-added} [παντων]{.greek-added} [ων]{.greek-added} [ουκ]{.greek-added} [ηδυνηθητε]{.greek-added} [εν]{.greek-added} [νομω]{.greek-added} [μωσεως]{.greek-added} [δικαιωθηναι]{.greek-added}[13:38]{.aside}

[και]{.greek-omitted} [απο]{.greek-omitted} [παντων]{.greek-omitted} [ων]{.greek-omitted} [ουκ]{.greek-omitted} [ηδυνηθητε]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [νομω]{.greek-omitted} [μωυσεως]{.greek-omitted} [δικαιωθηναι]{.greek-omitted} εν τουτω πας ο πιστευων δικαιουται[13:39]{.aside}

βλεπετε ουν μη επελθη εφ υμας το ειρημενον εν τοις προφηταις[13:40]{.aside}

ιδετε οι καταφρονηται [και]{.greek-added} [επιβλεψατε]{.greek-added} και θαυμασατε και αφανισθητε οτι εργον εγω εργαζομαι εν ταις ημεραις υμων [εργον]{.greek-added} ο ου μη [πιστευσητε]{.greek-omitted} [πιστευσηται]{.greek-added} εαν τις εκδιηγηται υμιν[13:41]{.aside}

εξιοντων δε [εκ]{.greek-omitted} [της]{.greek-omitted} [συναγωγης]{.greek-omitted} [των]{.greek-omitted} [αυτων]{.greek-added} [ιουδαιων]{.greek-omitted} παρεκαλουν [τα]{.greek-omitted} [εθνη]{.greek-omitted} εις το μεταξυ σαββατον λαληθηναι αυτοις τα ρηματα [ταυτα]{.greek-added}[13:42]{.aside}

[λυθεισης]{.greek-omitted} [λυθησης]{.greek-added} δε της συναγωγης ηκολουθησαν [πολλοι]{.greek-omitted} [πολυ]{.greek-added} των ιουδαιων και των σεβομενων προσηλυτων τω παυλω και τω βαρναβα οιτινες προσλαλουντες [αυτοις]{.greek-added} επειθον αυτους [επιμενειν]{.greek-omitted} [προσμενειν]{.greek-added} τη χαριτι του [θεου]{.greek-abbr}[13:43]{.aside}

τω [τε]{.greek-omitted} [δε]{.greek-added} ερχομενω σαββατω σχεδον πασα η πολις συνηχθη ακουσαι τον λογον του [θεου]{.greek-omitted} [[κυριου]{.greek-abbr}]{.greek-added}[13:44]{.aside}

ιδοντες δε οι ιουδαιοι τους οχλους επλησθησαν ζηλου [και]{.greek-omitted} [αντελεγον]{.greek-omitted} [τοις]{.greek-omitted} [υπο]{.greek-omitted} [του]{.greek-omitted} [παυλου]{.greek-omitted} [λεγομενοις]{.greek-omitted} [αντιλεγοντες]{.greek-omitted} [και]{.greek-omitted} [βλασφημουντες]{.greek-omitted}[13:45]{.aside}

[ιδοντες]{.greek-omitted} [δε]{.greek-omitted} [οι]{.greek-omitted} [ιουδαιοι]{.greek-omitted} [τους]{.greek-omitted} [οχλους]{.greek-omitted} [επλησθησαν]{.greek-omitted} [ζηλου]{.greek-omitted} και αντελεγον τοις υπο του παυλου λεγομενοις [αντιλεγοντες]{.greek-omitted} [και]{.greek-omitted} βλασφημουντες[13:45 | instance no. 2]{.aside}

παρρησιασαμενοι [δε]{.greek-omitted} [τε]{.greek-added} ο παυλος και [ο]{.greek-omitted} βαρναβας ειπον υμιν [αναγκαιον]{.greek-added} ην [αναγκαιον]{.greek-omitted} πρωτον λαληθηναι τον λογον του [θεου]{.greek-abbr} επειδη δε [απωθεισθε]{.greek-omitted} [αποθεισθε]{.greek-added} αυτον και ουκ αξιους κρινετε εαυτους της αιωνιου ζωης ιδου στρεφομεθα εις τα εθνη[13:46]{.aside}

ουτως γαρ [υμιν]{.greek-added} εντεταλται [ημιν]{.greek-omitted} ο [κυριος]{.greek-abbr} τεθεικα σε εις φως εθνων του ειναι σε εις [σωτηριαν]{.greek-abbr} εως εσχατου της γης[13:47]{.aside}

ακουοντα δε τα εθνη [εχαιρεν]{.greek-omitted} [εχαιρον]{.greek-added} και εδοξαζον τον λογον του [κυριου]{.greek-omitted} [[θεου]{.greek-abbr}]{.greek-added} και επιστευσαν οσοι ησαν τεταγμενοι εις ζωην αιωνιον[13:48]{.aside}

διεφερετο δε ο λογος του [κυριου]{.greek-abbr} δι ολης της χωρας[13:49]{.aside}

οι δε ιουδαιοι παρωτρυναν τας σεβομενας γυναικας και τας ευσχημονας και τους πρωτους της πολεως και επηγειραν διωγμον επι τον παυλον και [τον]{.greek-omitted} βαρναβαν και εξεβαλον αυτους απο των οριων αυτων[13:50]{.aside}

οι δε [εκτιναξαμενοι]{.greek-omitted} [εκτειναξαμενοι]{.greek-added} τον κονιορτον των ποδων [αυτων]{.greek-omitted} επ αυτους ηλθον εις ικονιον[13:51]{.aside}

οι δε μαθηται επληρουντο χαρας και [πνευματος]{.greek-abbr} αγιου[13:52]{.aside}

### Chapter 14

εγενετο δε εν ικονιω κατα το αυτο εισελθειν αυτους εις την συναγωγην των ιουδαιων και λαλησαι ουτως ωστε πιστευσαι ιουδαιων τε και ελληνων πολυ πληθος[14:1]{.aside}

οι δε [απειθουντες]{.greek-omitted} [απειθησαντες]{.greek-added} ιουδαιοι επηγειραν και εκακωσαν τας ψυχας των εθνων κατα των αδελφων[14:2]{.aside}

ικανον [μεν]{.greek-omitted} ουν χρονον διετριψαν παρρησιαζομενοι επι τω [κυριω]{.greek-abbr} τω μαρτυρουντι τω λογω της χαριτος αυτου [και]{.greek-added} διδοντι σημεια και τερατα γινεσθαι δια των χειρων αυτων[14:3]{.aside}

εσχισθη δε το πληθος της πολεως και οι μεν ησαν συν τοις ιουδαιοις οι δε συν τοις αποστολοις[14:4]{.aside}

ως δε εγενετο ορμη των εθνων τε και ιουδαιων συν τοις αρχουσιν αυτων υβρισαι και λιθοβολησαι αυτους[14:5]{.aside}

συνιδοντες κατεφυγον εις τας πολεις της λυκαονιας λυστραν και δερβην και την περιχωρον[14:6]{.aside}

κακει [ευαγγελιζομενοι]{.greek-added} ησαν [ευαγγελιζομενοι]{.greek-omitted}[14:7]{.aside}

και τις ανηρ εν λυστροις αδυνατος τοις ποσιν εκαθητο χωλος εκ κοιλιας [μητρος]{.greek-abbr} αυτου [υπαρχων]{.greek-omitted} ος ουδεποτε [περιπεπατηκει]{.greek-omitted} [περιεπατησεν]{.greek-added}[14:8]{.aside}

ουτος [ηκουσεν]{.greek-omitted} [ηκουσε]{.greek-added} του παυλου λαλουντος ος ατενισας αυτω [και]{.greek-omitted} [ιδων]{.greek-omitted} [οτι]{.greek-omitted} [πιστιν]{.greek-omitted} [εχει]{.greek-omitted} [του]{.greek-omitted} [σωθηναι]{.greek-omitted}[14:9]{.aside}

[ουτος]{.greek-omitted} [ηκουσεν]{.greek-omitted} [του]{.greek-omitted} [παυλου]{.greek-omitted} [λαλουντος]{.greek-omitted} [ος]{.greek-omitted} [ατενισας]{.greek-omitted} [αυτω]{.greek-omitted} και ιδων οτι [εχει]{.greek-added} πιστιν [εχει]{.greek-omitted} του σωθηναι[14:9 | instance no. 2]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} μεγαλη τη φωνη [σοι]{.greek-added} [λεγω]{.greek-added} [εν]{.greek-added} [τω]{.greek-added} [ονοματι]{.greek-added} [του]{.greek-added} [[κυριου]{.greek-abbr}]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} [[χριστου]{.greek-abbr}]{.greek-added} αναστηθι επι τους ποδας σου ορθως και [ηλλετο]{.greek-omitted} [ηλλατο]{.greek-added} και περιεπατει[14:10]{.aside}

οι δε οχλοι ιδοντες ο εποιησεν ο παυλος επηραν την φωνην αυτων λυκαονιστι λεγοντες οι θεοι ομοιωθεντες [ανθρωποις]{.greek-abbr} κατεβησαν προς ημας[14:11]{.aside}

εκαλουν τε τον μεν βαρναβαν δια τον δε παυλον ερμην επειδη αυτος ην ο ηγουμενος του λογου[14:12]{.aside}

ο [δε]{.greek-omitted} [τε]{.greek-added} ιερευς του διος του οντος προ της πολεως [αυτων]{.greek-omitted} ταυρους και στεμματα επι τους πυλωνας ενεγκας συν τοις οχλοις [ηθελεν]{.greek-omitted} [ηθελον]{.greek-added} θυειν[14:13]{.aside}

ακουσαντες δε οι αποστολοι βαρναβας και παυλος διαρρηξαντες τα ιματια αυτων [εισεπηδησαν]{.greek-omitted} [εξεπηδησαν]{.greek-added} εις τον οχλον κραζοντες[14:14]{.aside}

και λεγοντες ανδρες τι ταυτα ποιειτε και ημεις ομοιοπαθεις εσμεν υμιν [ανθρωποι]{.greek-abbr} ευαγγελιζομενοι υμας απο [τουτων]{.greek-omitted} των ματαιων [τουτων]{.greek-added} επιστρεφειν επι [τον]{.greek-omitted} [θεον]{.greek-abbr} [τον]{.greek-omitted} ζωντα ος [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} τον [ουρανον]{.greek-abbr} και την γην και την θαλασσαν και παντα τα εν αυτοις[14:15]{.aside}

ος εν ταις [παρωχημεναις]{.greek-omitted} [παροχημεναις]{.greek-added} γενεαις [ειασεν]{.greek-omitted} [ειασε]{.greek-added} παντα τα εθνη πορευεσθαι [ταις]{.greek-omitted} [τοις]{.greek-added} οδοις αυτων[14:16]{.aside}

[καιτοιγε]{.greek-omitted} [καιτοι]{.greek-added} ουκ αμαρτυρον [εαυτον]{.greek-omitted} [αυτον]{.greek-added} αφηκεν [αγαθοποιων]{.greek-omitted} [αγαθουργων]{.greek-added} [ουρανοθεν]{.greek-abbr} υμιν [υετους]{.greek-omitted} [υιετους]{.greek-added} διδους και καιρους καρποφορους εμπιπλων τροφης και ευφροσυνης τας καρδιας [ημων]{.greek-omitted} [υμων]{.greek-added}[14:17]{.aside}

και ταυτα λεγοντες μολις κατεπαυσαν τους οχλους του μη θυειν αυτοις [αλλ]{.greek-added} [ινα]{.greek-added} [πορευωνται]{.greek-added} [εκαστος]{.greek-added} [εις]{.greek-added} [τα]{.greek-added} [ιδια]{.greek-added} [αυτων]{.greek-added}[14:18]{.aside}

[διατριβοντων]{.greek-added} [δε]{.greek-added} [αυτων]{.greek-added} [και]{.greek-added} [διδασκοντων]{.greek-added} επηλθον [δε]{.greek-omitted} [οι]{.greek-added} απο αντιοχειας και ικονιου ιουδαιοι και [πεισαντες]{.greek-omitted} [διαλεγομενων]{.greek-added} [αυτων]{.greek-added} [παρρησια]{.greek-added} [ανεπεισαν]{.greek-added} τους οχλους [αποστηναι]{.greek-added} [απ]{.greek-added} [αυτων]{.greek-added} [λεγοντες]{.greek-added} [οτι]{.greek-added} [ουδεν]{.greek-added} [αληθες]{.greek-added} [λεγουσιν]{.greek-added} [αλλα]{.greek-added} [ψευδονται]{.greek-added} και λιθασαντες τον παυλον εσυρον εξω της πολεως [νομισαντες]{.greek-omitted} [νομιζοντες]{.greek-added} αυτον [τεθναναι]{.greek-omitted} [τεθνηκεναι]{.greek-added}[14:19]{.aside}

κυκλωσαντων δε [αυτον]{.greek-omitted} των μαθητων [αυτον]{.greek-added} αναστας εισηλθεν εις την πολιν και τη επαυριον εξηλθεν [εις]{.greek-added} [δερβην]{.greek-added} συν τω βαρναβα [εις]{.greek-omitted} [δερβην]{.greek-omitted}[14:20]{.aside}

ευαγγελισαμενοι τε την πολιν εκεινην και μαθητευσαντες ικανους υπεστρεψαν εις την λυστραν [και]{.greek-omitted} [ικονιον]{.greek-omitted} [και]{.greek-omitted} [αντιοχειαν]{.greek-omitted}[14:21]{.aside}

[ευαγγελισαμενοι]{.greek-omitted} [τε]{.greek-omitted} [την]{.greek-omitted} [πολιν]{.greek-omitted} [εκεινην]{.greek-omitted} [και]{.greek-omitted} [μαθητευσαντες]{.greek-omitted} [ικανους]{.greek-omitted} [υπεστρεψαν]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [λυστραν]{.greek-omitted} και ικονιον και [εις]{.greek-added} αντιοχειαν[14:21 | instance no. 2]{.aside}

επιστηριζοντες τας ψυχας των μαθητων [και]{.greek-added} παρακαλουντες εμμενειν τη πιστει και οτι δια πολλων θλιψεων δει [ημας]{.greek-omitted} [υμας]{.greek-added} εισελθειν εις την βασιλειαν του [θεου]{.greek-abbr}[14:22]{.aside}

χειροτονησαντες δε αυτοις [πρεσβυτερους]{.greek-omitted} κατ εκκλησιαν [πρεσβυτερους]{.greek-added} [και]{.greek-added} προσευξαμενοι μετα νηστειων παρεθεντο αυτους τω [κυριω]{.greek-abbr} εις ον πεπιστευκεισαν[14:23]{.aside}

και διελθοντες την πισιδιαν ηλθον εις [την]{.greek-added} παμφυλιαν[14:24]{.aside}

και λαλησαντες εν περγη τον λογον κατεβησαν εις [ατταλειαν]{.greek-omitted} [αταλειαν]{.greek-added}[14:25]{.aside}

κακειθεν απεπλευσαν εις αντιοχειαν οθεν ησαν παραδεδομενοι τη χαριτι του [θεου]{.greek-abbr} εις [το]{.greek-omitted} εργον ο επληρωσαν[14:26]{.aside}

παραγενομενοι δε και συναγαγοντες την εκκλησιαν [ανηγγειλαν]{.greek-omitted} [ανηγγελλον]{.greek-added} οσα εποιησεν ο [θεος]{.greek-abbr} μετ αυτων και οτι [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} θυραν πιστεως[14:27]{.aside}

διετριβον δε [εκει]{.greek-omitted} χρονον ουκ ολιγον συν τοις μαθηταις[14:28]{.aside}

### Chapter 15

και τινες κατελθοντες απο της ιουδαιας εδιδασκον τους αδελφους οτι εαν μη [περιτεμνησθε]{.greek-omitted} [περιτμηθητε]{.greek-added} τω εθει [μωυσεως]{.greek-omitted} [μωυσεος]{.greek-added} ου δυνασθε σωθηναι[15:1]{.aside}

γενομενης [ουν]{.greek-omitted} [δε]{.greek-added} στασεως και ζητησεως ουκ ολιγης τω παυλω και τω βαρναβα προς αυτους εταξαν αναβαινειν παυλον και βαρναβαν και τινας αλλους εξ αυτων προς τους αποστολους και [τους]{.greek-added} πρεσβυτερους [εις]{.greek-omitted} [ιερουσαλημ]{.greek-abbr} περι του ζητηματος τουτου[15:2]{.aside}

οι μεν ουν προπεμφθεντες υπο της εκκλησιας διηρχοντο την [τε]{.greek-added} φοινικην και σαμαρειαν εκδιηγουμενοι την επιστροφην των εθνων και εποιουν χαραν μεγαλην [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις [αδελφοις]{.greek-omitted} [εθνεσι]{.greek-added}[15:3]{.aside}

παραγενομενοι δε εις [ιερουσαλημ]{.greek-omitted} [ιεροσολυμα]{.greek-added} [απεδεχθησαν]{.greek-omitted} [παρεδεχθησαν]{.greek-added} υπο της εκκλησιας και των αποστολων και των [πρεσβυτερων]{.greek-omitted} [αποστολων]{.greek-added} ανηγγειλαν τε οσα ο [θεος]{.greek-abbr} [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} μετ αυτων[15:4]{.aside}

εξανεστησαν δε τινες των απο της αιρεσεως των φαρισαιων πεπιστευκοτες λεγοντες οτι δει περιτεμνειν αυτους παραγγελλειν τε τηρειν τον νομον [μωυσεως]{.greek-omitted} [μωυσεος]{.greek-added}[15:5]{.aside}

συνηχθησαν [δε]{.greek-omitted} [τε]{.greek-added} οι αποστολοι και οι πρεσβυτεροι ιδειν περι του λογου τουτου[15:6]{.aside}

πολλης δε [συζητησεως]{.greek-omitted} [ζητησεως]{.greek-added} γενομενης αναστας πετρος [ειπεν]{.greek-omitted} [προς]{.greek-omitted} [αυτους]{.greek-omitted} [ανδρες]{.greek-omitted} [αδελφοι]{.greek-omitted} [υμεις]{.greek-omitted} [επιστασθε]{.greek-omitted} [οτι]{.greek-omitted} [αφ]{.greek-omitted} [ημερων]{.greek-omitted} [αρχαιων]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [εν]{.greek-omitted} [ημιν]{.greek-omitted} [εξελεξατο]{.greek-omitted} [δια]{.greek-omitted} [του]{.greek-omitted} [στοματος]{.greek-omitted} [μου]{.greek-omitted} [ακουσαι]{.greek-omitted} [τα]{.greek-omitted} [εθνη]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted} [του]{.greek-omitted} [ευαγγελιου]{.greek-omitted} [και]{.greek-omitted} [πιστευσαι]{.greek-omitted}[15:7]{.aside}

[πολλης]{.greek-omitted} [δε]{.greek-omitted} [συζητησεως]{.greek-omitted} [γενομενης]{.greek-omitted} [αναστας]{.greek-omitted} [πετρος]{.greek-omitted} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} προς αυτους ανδρες αδελφοι υμεις επιστασθε οτι αφ ημερων αρχαιων [εν]{.greek-added} [υμιν]{.greek-added} [εξελεξατο]{.greek-added} ο [θεος]{.greek-abbr} [εν]{.greek-omitted} [ημιν]{.greek-omitted} [εξελεξατο]{.greek-omitted} δια του στοματος μου ακουσαι τα εθνη τον λογον του ευαγγελιου και πιστευσαι[15:7 | instance no. 2]{.aside}

και ο καρδιογνωστης [θεος]{.greek-abbr} εμαρτυρησεν αυτοις δους [αυτοις]{.greek-omitted} το [πνευμα]{.greek-abbr} το αγιον καθως [και]{.greek-omitted} ημιν[15:8]{.aside}

και ουδεν [διεκρινεν]{.greek-omitted} [διεκρινε]{.greek-added} μεταξυ ημων τε και αυτων τη πιστει καθαρισας τας καρδιας αυτων[15:9]{.aside}

νυν ουν τι πειραζετε τον [θεον]{.greek-abbr} [επιθειναι]{.greek-omitted} [επιθηναι]{.greek-added} ζυγον επι τον τραχηλον των μαθητων ον ουτε οι [πατερες]{.greek-abbr} ημων ουτε ημεις ισχυσαμεν βαστασαι[15:10]{.aside}

[αλλα]{.greek-omitted} [αλλ]{.greek-added} [η]{.greek-added} δια της χαριτος του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} πιστευομεν σωθηναι καθ ον τροπον κακεινοι[15:11]{.aside}

[εσιγησεν]{.greek-omitted} [εσιγησε]{.greek-added} δε [παν]{.greek-omitted} [απαν]{.greek-added} το πληθος και ηκουον βαρναβα και παυλου εξηγουμενων οσα εποιησεν ο [θεος]{.greek-abbr} σημεια και τερατα εν τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} δι αυτων[15:12]{.aside}

μετα δε το σιγησαι αυτους απεκριθη ιακωβος λεγων ανδρες αδελφοι ακουσατε μου[15:13]{.aside}

συμεων εξηγησατο καθως πρωτον ο [θεος]{.greek-abbr} επεσκεψατο λαβειν εξ εθνων λαον [επι]{.greek-omitted} τω ονοματι αυτου[15:14]{.aside}

και τουτω συμφωνουσιν οι λογοι των προφητων καθως γεγραπται[15:15]{.aside}

μετα ταυτα αναστρεψω και ανοικοδομησω την σκηνην [δαυιδ]{.greek-abbr} την πεπτωκυιαν και τα κατεσκαμμενα αυτης ανοικοδομησω και ανορθωσω αυτην[15:16]{.aside}

οπως αν εκζητησωσιν οι καταλοιποι των [ανθρωπων]{.greek-abbr} τον [κυριον]{.greek-abbr} και παντα τα εθνη εφ ους επικεκληται το ονομα μου επ αυτους λεγει [κυριος]{.greek-abbr} ο ποιων ταυτα [παντα]{.greek-omitted}[15:17]{.aside}

γνωστα απ αιωνος [εστιν]{.greek-omitted} [τω]{.greek-omitted} [θεω]{.greek-omitted} [παντα]{.greek-omitted} [τα]{.greek-omitted} [εργα]{.greek-omitted} [αυτου]{.greek-omitted}[15:18]{.aside}

διο εγω κρινω μη παρενοχλειν τοις απο των εθνων επιστρεφουσιν επι τον [θεον]{.greek-abbr}[15:19]{.aside}

[αλλα]{.greek-omitted} [αλλ]{.greek-added} επιστειλαι [αυτοις]{.greek-omitted} [αυτους]{.greek-added} του απεχεσθαι [απο]{.greek-omitted} των αλισγηματων των ειδωλων και της πορνειας και του πνικτου και του αιματος[15:20]{.aside}

μωυσης γαρ εκ γενεων αρχαιων κατα πολιν τους κηρυσσοντας αυτον [εχει]{.greek-omitted} [ειχεν]{.greek-added} εν ταις συναγωγαις κατα παν σαββατον αναγινωσκομενος[15:21]{.aside}

τοτε [εδοξεν]{.greek-omitted} [εδοξε]{.greek-added} τοις αποστολοις και τοις πρεσβυτεροις συν ολη τη εκκλησια εκλεξαμενους ανδρας εξ αυτων πεμψαι εις αντιοχειαν συν [τω]{.greek-added} παυλω [και]{.greek-omitted} [βαρναβα]{.greek-omitted} [ιουδαν]{.greek-omitted} [τον]{.greek-omitted} [επικαλουμενον]{.greek-omitted} [βαρσαββαν]{.greek-omitted} [και]{.greek-omitted} [σιλαν]{.greek-omitted} [ανδρας]{.greek-omitted} [ηγουμενους]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} [αδελφοις]{.greek-omitted}[15:22]{.aside}

[τοτε]{.greek-omitted} [εδοξεν]{.greek-omitted} [τοις]{.greek-omitted} [αποστολοις]{.greek-omitted} [και]{.greek-omitted} [τοις]{.greek-omitted} [πρεσβυτεροις]{.greek-omitted} [συν]{.greek-omitted} [ολη]{.greek-omitted} [τη]{.greek-omitted} [εκκλησια]{.greek-omitted} [εκλεξαμενους]{.greek-omitted} [ανδρας]{.greek-omitted} [εξ]{.greek-omitted} [αυτων]{.greek-omitted} [πεμψαι]{.greek-omitted} [εις]{.greek-omitted} [αντιοχειαν]{.greek-omitted} [συν]{.greek-omitted} [παυλω]{.greek-omitted} και βαρναβα ιουδαν τον [επικαλουμενον]{.greek-omitted} [καλουμενον]{.greek-added} [βαρσαββαν]{.greek-omitted} [βαρσαβαν]{.greek-added} και σιλαν ανδρας ηγουμενους [εν]{.greek-omitted} τοις αδελφοις[15:22 | instance no. 2]{.aside}

γραψαντες δια χειρος αυτων ταδε οι αποστολοι και οι πρεσβυτεροι και οι αδελφοι τοις κατα την αντιοχειαν και συριαν και κιλικιαν αδελφοις τοις εξ εθνων χαιρειν[15:23]{.aside}

επειδη ηκουσαμεν οτι τινες εξ ημων [εξελθοντες]{.greek-omitted} εταραξαν υμας λογοις ανασκευαζοντες τας ψυχας υμων [λεγοντες]{.greek-omitted} [περιτεμνεσθαι]{.greek-omitted} [και]{.greek-omitted} [τηρειν]{.greek-omitted} [τον]{.greek-omitted} [νομον]{.greek-omitted} οις ου διεστειλαμεθα[15:24]{.aside}

εδοξεν ημιν γενομενοις ομοθυμαδον [εκλεξαμενους]{.greek-omitted} [εκλεξαμενοις]{.greek-added} ανδρας πεμψαι προς υμας συν τοις αγαπητοις ημων βαρναβα και παυλω[15:25]{.aside}

[ανθρωποις]{.greek-abbr} [παραδεδωκοσιν]{.greek-omitted} [παραδεδοκοσι]{.greek-added} τας ψυχας αυτων υπερ του ονοματος του [κυριου]{.greek-abbr} ημων [ιησου]{.greek-abbr} [χριστου]{.greek-abbr}[15:26]{.aside}

απεσταλκαμεν ουν ιουδαν και σιλαν και αυτους δια λογου απαγγελλοντας [τα]{.greek-omitted} [αυτα]{.greek-omitted} [ταυτα]{.greek-added}[15:27]{.aside}

[εδοξεν]{.greek-omitted} [εδοξε]{.greek-added} γαρ τω αγιω [πνευματι]{.greek-abbr} και ημιν μηδεν πλεον επιτιθεσθαι υμιν βαρος πλην των επαναγκες [τουτων]{.greek-omitted}[15:28]{.aside}

απεχεσθαι ειδωλοθυτων και αιματος και πνικτου και πορνειας εξ ων διατηρουντες εαυτους ευ πραξετε ερρωσθε[15:29]{.aside}

οι μεν ουν απολυθεντες [ηλθον]{.greek-omitted} [κατηλθον]{.greek-added} εις αντιοχειαν και συναγαγοντες το πληθος επεδωκαν την επιστολην[15:30]{.aside}

αναγνοντες δε εχαρησαν επι τη παρακλησει[15:31]{.aside}

ιουδας τε και σιλας και αυτοι προφηται [οντες]{.greek-omitted} δια λογου πολλου [οντες]{.greek-added} παρεκαλεσαν τους αδελφους και επεστηριξαν[15:32]{.aside}

ποιησαντες δε χρονον απελυθησαν μετ ειρηνης [απο]{.greek-omitted} [υπο]{.greek-added} των αδελφων προς τους [αποστολους]{.greek-omitted} [αποστειλαντας]{.greek-added} [αυτους]{.greek-added}[15:33]{.aside}

[εδοξε]{.greek-added} [δε]{.greek-added} [τω]{.greek-added} [σιλα]{.greek-added} [επιμειναι]{.greek-added} [αυτου]{.greek-added}[15:34]{.aside}

παυλος δε και βαρναβας διετριβον εν αντιοχεια διδασκοντες και ευαγγελιζομενοι μετα και ετερων πολλων τον λογον του [κυριου]{.greek-abbr}[15:35]{.aside}

μετα δε τινας ημερας [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [παυλος]{.greek-omitted} προς βαρναβαν [ο]{.greek-added} [παυλος]{.greek-added} επιστρεψαντες δη επισκεψωμεθα τους αδελφους [ημων]{.greek-omitted} κατα πασαν πολιν εν αις [κατηγγειλαμεν]{.greek-omitted} [εκηρυξαμεν]{.greek-added} τον λογον του [κυριου]{.greek-abbr} πως [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added}[15:36]{.aside}

βαρναβας δε [εβουλευσατο]{.greek-omitted} [εβουλετο]{.greek-added} συμπαραλαβειν [τον]{.greek-omitted} [και]{.greek-added} ιωαννην τον [καλουμενον]{.greek-omitted} [επικαλουμενον]{.greek-added} μαρκον[15:37]{.aside}

παυλος δε ηξιου τον αποσταντα απ αυτων απο παμφυλιας και μη συνελθοντα αυτοις εις το εργον [μη]{.greek-omitted} [συμπαραλαβειν]{.greek-omitted} [τουτον]{.greek-omitted}[15:38]{.aside}

[παυλος]{.greek-omitted} [δε]{.greek-omitted} [ηξιου]{.greek-omitted} [τον]{.greek-omitted} [αποσταντα]{.greek-omitted} [απ]{.greek-omitted} [αυτων]{.greek-omitted} [απο]{.greek-omitted} [παμφυλιας]{.greek-omitted} [και]{.greek-omitted} μη [συνελθοντα]{.greek-omitted} [αυτοις]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [εργον]{.greek-omitted} [μη]{.greek-omitted} [συμπαραλαβειν]{.greek-omitted} [συμπαραλαμβανειν]{.greek-added} τουτον[15:38 | instance no. 2]{.aside}

εγενετο [ουν]{.greek-omitted} [δε]{.greek-added} παροξυσμος ωστε αποχωρισθηναι αυτους απ αλληλων τον τε βαρναβαν παραλαβοντα τον μαρκον εκπλευσαι εις κυπρον[15:39]{.aside}

παυλος δε επιλεξαμενος σιλαν [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} παραδοθεις τη χαριτι του [θεου]{.greek-abbr} υπο των αδελφων[15:40]{.aside}

διηρχετο δε την συριαν και [κιλικιαν]{.greek-omitted} [την]{.greek-added} [λυκιαν]{.greek-added} επιστηριζων τας εκκλησιας[15:41]{.aside}

### Chapter 16

[κατηντησεν]{.greek-omitted} [κατηντησε]{.greek-added} δε [και]{.greek-added} εις δερβην και [εις]{.greek-added} λυστραν και ιδου μαθητης τις ην εκει ονοματι τιμοθεος υιος γυναικος [τινος]{.greek-omitted} ιουδαιας πιστης πατρος δε ελληνος[16:1]{.aside}

ος εμαρτυρειτο υπο των εν λυστροις και ικονιω αδελφων[16:2]{.aside}

τουτον ηθελησεν ο παυλος συν αυτω εξελθειν και λαβων περιετεμεν αυτον δια τους ιουδαιους τους οντας εν τοις τοποις εκεινοις ηδεισαν γαρ απαντες τον [πατερα]{.greek-abbr} αυτου οτι ελλην υπηρχεν[16:3]{.aside}

ως δε διεπορευοντο τας πολεις [παρεδιδουν]{.greek-omitted} [παρεδιδοσαν]{.greek-added} αυτοις φυλασσειν τα δογματα τα κεκριμενα υπο των αποστολων και [των]{.greek-omitted} πρεσβυτερων των εν [ιερουσαλημ]{.greek-omitted} [ιεροσολυμοις]{.greek-added}[16:4]{.aside}

αι μεν [ουν]{.greek-omitted} εκκλησιαι εστερεουντο τη πιστει και [επερισσευον]{.greek-omitted} [περιεσσευον]{.greek-added} τω αριθμω καθ ημεραν[16:5]{.aside}

[διελθοντες]{.greek-omitted} [διηλθον]{.greek-added} δε την φρυγιαν και [την]{.greek-omitted} γαλατικην χωραν κωλυθεντες υπο του αγιου [πνευματος]{.greek-abbr} λαλησαι τον λογον εν τη ασια[16:6]{.aside}

ελθοντες [δε]{.greek-added} κατα την μυσιαν επειραζον [κατα]{.greek-omitted} [εις]{.greek-added} την βιθυνιαν πορευεσθαι και ουκ ειασεν αυτους το [πνευμα]{.greek-abbr}[16:7]{.aside}

παρελθοντες δε την μυσιαν κατεβησαν εις τρωαδα[16:8]{.aside}

και οραμα δια της νυκτος ωφθη τω παυλω ανηρ τις [μακεδων]{.greek-added} ην [μακεδων]{.greek-omitted} εστως [και]{.greek-added} παρακαλων αυτον [και]{.greek-omitted} λεγων διαβας εις μακεδονιαν βοηθησον ημιν[16:9]{.aside}

ως δε το οραμα ειδεν ευθεως εζητησαμεν εξελθειν εις [την]{.greek-omitted} μακεδονιαν συμβιβαζοντες οτι προσκεκληται ημας ο [κυριος]{.greek-abbr} ευαγγελισασθαι [αυτους]{.greek-omitted} [αυτοις]{.greek-added}[16:10]{.aside}

αναχθεντες ουν απο [της]{.greek-omitted} τρωαδος ευθυδρομησαμεν εις σαμοθρακην τη [τε]{.greek-omitted} [δε]{.greek-added} επιουση εις νεαπολιν[16:11]{.aside}

[εκειθεν]{.greek-omitted} [κακειθεν]{.greek-added} [τε]{.greek-omitted} εις φιλιππους ητις [εστιν]{.greek-omitted} [εστι]{.greek-added} πρωτη της μεριδος της μακεδονιας πολις [κολωνεια]{.greek-omitted} [κολονια]{.greek-added} ημεν δε εν [αυτη]{.greek-omitted} [ταυτη]{.greek-added} τη πολει διατριβοντες ημερας τινας[16:12]{.aside}

τη τε ημερα των σαββατων [εξηλ]{.greek-added} [εξηλθομεν]{.greek-omitted} [εξω]{.greek-omitted} [της]{.greek-omitted} [πολεως]{.greek-omitted} [παρα]{.greek-omitted} [ποταμον]{.greek-omitted} [ου]{.greek-omitted} [ενομιζετο]{.greek-omitted} [προσευχη]{.greek-omitted} [ειναι]{.greek-omitted} [και]{.greek-omitted} [καθισαντες]{.greek-omitted} [ελαλουμεν]{.greek-omitted} [ταις]{.greek-omitted} [συνελθουσαις]{.greek-omitted} [γυναιξιν]{.greek-omitted}[16:13]{.aside}

[θομεν]{.greek-added} [τη]{.greek-omitted} [τε]{.greek-omitted} [ημερα]{.greek-omitted} [των]{.greek-omitted} [σαββατων]{.greek-omitted} [εξηλθομεν]{.greek-omitted} εξω της πολεως παρα ποταμον ου ενομιζετο προσευχη ειναι και καθισαντες ελαλουμεν ταις [συνελθουσαις]{.greek-omitted} [συνελθουσαι]{.greek-added} [γυναιξιν]{.greek-omitted} [γυναιξι]{.greek-added}[16:13 | instance no. 2]{.aside}

και τις γυνη ονοματι λυδια [πορφυροπωλις]{.greek-omitted} [πορφυροπολις]{.greek-added} πολεως [θυατειρων]{.greek-omitted} [θυατηρων]{.greek-added} σεβομενη τον [θεον]{.greek-abbr} ηκουεν ης ο [κυριος]{.greek-abbr} [διηνοιξεν]{.greek-omitted} [διηνοιξε]{.greek-added} την καρδιαν προσεχειν τοις λαλουμενοις υπο του παυλου[16:14]{.aside}

ως δε εβαπτισθη και ο οικος αυτης [παρεκαλεσεν]{.greek-omitted} [παρεκαλεσε]{.greek-added} λεγουσα ει κεκρικατε με πιστην τω [κυριω]{.greek-abbr} ειναι εισελθοντες εις τον οικον μου μεινατε και παρεβιασατο ημας[16:15]{.aside}

εγενετο δε πορευομενων ημων εις προσευχην παιδισκην τινα εχουσαν [πνευμα]{.greek-abbr} [πυθωνος]{.greek-omitted} [πυθονος]{.greek-added} [απαντησαι]{.greek-omitted} [υπαντησαι]{.greek-added} ημιν ητις εργασιαν πολλην [παρειχεν]{.greek-omitted} [παρειχε]{.greek-added} τοις κυριοις αυτης μαντευομενη[16:16]{.aside}

αυτη κατακολουθησασα [τω]{.greek-omitted} [παυλω]{.greek-omitted} [και]{.greek-omitted} ημιν [εκραζεν]{.greek-omitted} [εκραζε]{.greek-added} λεγουσα ουτοι οι [ανθρωποι]{.greek-abbr} δουλοι του [θεου]{.greek-abbr} του υψιστου εισιν οιτινες καταγγελλουσιν ημιν οδον σωτηριας[16:17]{.aside}

τουτο δε εποιει επι πολλας ημερας διαπονηθεις δε ο παυλος και επιστρεψας τω [πνευματι]{.greek-abbr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} παραγγελλω σοι εν [τω]{.greek-omitted} ονοματι [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} εξελθειν απ αυτης και εξηλθεν αυτη τη ωρα[16:18]{.aside}

ιδοντες δε οι κυριοι αυτης οτι εξηλθεν η ελπις της εργασιας αυτων επιλαβομενοι τον παυλον και τον σιλαν ειλκυσαν εις την αγοραν επι τους αρχοντας[16:19]{.aside}

και προσαγαγοντες αυτους τοις στρατηγοις ειπον ουτοι οι [ανθρωποι]{.greek-abbr} εκταρασσουσιν ημων την πολιν ιουδαιοι υπαρχοντες[16:20]{.aside}

και καταγγελλουσιν εθη α ουκ εξεστιν ημιν παραδεχεσθαι ουδε ποιειν ρωμαιοις [ουσιν]{.greek-omitted} [ουσι]{.greek-added}[16:21]{.aside}

και συνεπεστη ο οχλος κατ αυτων και οι στρατηγοι περιρρηξαντες αυτων τα ιματια εκελευον ραβδιζειν[16:22]{.aside}

πολλας τε επιθεντες αυτοις πληγας εβαλον εις φυλακην παραγγειλαντες τω δεσμοφυλακι ασφαλως τηρειν αυτους[16:23]{.aside}

ος παραγγελιαν τοιαυτην ειληφως εβαλεν αυτους εις την [εσωτεραν]{.greek-omitted} [εσσοτεραν]{.greek-added} φυλακην και τους ποδας αυτων [ησφαλισατο]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [ξυλον]{.greek-omitted}[16:24]{.aside}

[ος]{.greek-omitted} [παραγγελιαν]{.greek-omitted} [τοιαυτην]{.greek-omitted} [ειληφως]{.greek-omitted} [εβαλεν]{.greek-omitted} [αυτους]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [εσωτεραν]{.greek-omitted} [φυλακην]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [ποδας]{.greek-omitted} [αυτων]{.greek-omitted} ησφαλισατο εις το ξυλον[16:24 | instance no. 2]{.aside}

[κατα]{.greek-omitted} [περι]{.greek-added} δε το μεσονυκτιον παυλος και σιλας προσευχομενοι υμνουν τον [θεον]{.greek-abbr} [επηκροωντο]{.greek-omitted} [επεκροωντο]{.greek-added} δε αυτων οι δεσμιοι[16:25]{.aside}

αφνω δε σεισμος εγενετο μεγας ωστε σαλευθηναι τα θεμελια του δεσμωτηριου [ανεωχθησαν]{.greek-omitted} [ηνεωχθησαν]{.greek-added} τε παραχρημα αι θυραι πασαι και παντων τα δεσμα ανεθη[16:26]{.aside}

εξυπνος δε γενομενος ο δεσμοφυλαξ και ιδων ανεωγμενας τας θυρας της φυλακης σπασαμενος μαχαιραν [εμελλεν]{.greek-omitted} [ημελλεν]{.greek-added} [εαυτον]{.greek-omitted} [αυτον]{.greek-added} αναιρειν νομιζων εκπεφευγεναι τους δεσμιους[16:27]{.aside}

[εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added} δε φωνη μεγαλη ο παυλος λεγων μηδεν [πραξης]{.greek-omitted} [πραξεις]{.greek-added} σεαυτω κακον απαντες γαρ εσμεν ενθαδε[16:28]{.aside}

αιτησας δε φωτα εισεπηδησεν και εντρομος γενομενος [προσεπεσεν]{.greek-omitted} [προσεπεσε]{.greek-added} τω παυλω και τω σιλα[16:29]{.aside}

και προαγαγων αυτους εξω εφη κυριοι τι με δει ποιειν ινα σωθω[16:30]{.aside}

οι δε ειπον πιστευσον επι τον [κυριον]{.greek-abbr} [ιησουν]{.greek-abbr} [χριστον]{.greek-abbr} και σωθηση συ και ο οικος σου[16:31]{.aside}

και [ελαλησαν]{.greek-omitted} [ελαλησεν]{.greek-added} αυτω τον λογον του [κυριου]{.greek-abbr} και [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις εν τη οικια αυτου[16:32]{.aside}

και παραλαβων αυτους εν εκεινη τη ωρα [της]{.greek-omitted} [νυκτος]{.greek-omitted} ελουσεν απο των πληγων και εβαπτισθη αυτος και οι αυτου παντες παραχρημα[16:33]{.aside}

αναγαγων τε αυτους εις τον οικον [αυτου]{.greek-omitted} [παρεθηκεν]{.greek-omitted} [παρεθηκε]{.greek-added} τραπεζαν και [ηγαλλιατο]{.greek-omitted} [ηγαλλιασατο]{.greek-added} πανοικι πεπιστευκως τω [θεω]{.greek-omitted} [[κυριω]{.greek-abbr}]{.greek-added}[16:34]{.aside}

ημερας δε γενομενης απεστειλαν οι στρατηγοι τους ραβδουχους λεγοντες απολυσον τους [ανθρωπους]{.greek-abbr} εκεινους[16:35]{.aside}

[απηγγειλεν]{.greek-omitted} [απηγγειλε]{.greek-added} δε ο δεσμοφυλαξ τους λογους [τουτους]{.greek-omitted} προς τον παυλον οτι απεσταλκασιν οι στρατηγοι ινα απολυθητε νυν ουν εξελθοντες πορευεσθε εν ειρηνη[16:36]{.aside}

ο δε παυλος εφη προς αυτους δειραντες ημας δημοσια ακατακριτους [ανθρωπους]{.greek-abbr} ρωμαιους υπαρχοντας εβαλον εις φυλακην και νυν λαθρα ημας [εκβαλλουσιν]{.greek-omitted} [εκβαλουσιν]{.greek-added} ου γαρ αλλα ελθοντες αυτοι [ημας]{.greek-added} εξαγαγετωσαν[16:37]{.aside}

[ανηγγειλαν]{.greek-omitted} [απηγγειλαν]{.greek-added} δε τοις στρατηγοις οι ραβδουχοι τα ρηματα [ταυτα]{.greek-omitted} [και]{.greek-omitted} [εφοβηθησαν]{.greek-omitted} [ακουσαντες]{.greek-omitted} [οτι]{.greek-omitted} [ρωμαιοι]{.greek-omitted} [εισιν]{.greek-omitted}[16:38]{.aside}

[ανηγγειλαν]{.greek-omitted} [δε]{.greek-omitted} [τοις]{.greek-omitted} [στρατηγοις]{.greek-omitted} [οι]{.greek-omitted} [ραβδουχοι]{.greek-omitted} [τα]{.greek-omitted} [ρηματα]{.greek-omitted} ταυτα και εφοβηθησαν ακουσαντες οτι ρωμαιοι [εισιν]{.greek-omitted} [εισι]{.greek-added}[16:38 | instance no. 2]{.aside}

και ελθοντες παρεκαλεσαν αυτους και [εξαγαγοντες]{.greek-omitted} [εξελθοντες]{.greek-added} ηρωτων εξελθειν [εκ]{.greek-added} της πολεως[16:39]{.aside}

εξελθοντες δε εκ της φυλακης [εισηλθον]{.greek-omitted} [ηλθον]{.greek-added} προς την λυδιαν και ιδοντες [παρεκαλεσαν]{.greek-added} τους αδελφους [παρεκαλεσαν]{.greek-omitted} [αυτους]{.greek-omitted} και εξηλθον[16:40]{.aside}

### Chapter 17

διοδευσαντες δε την αμφιπολιν και [την]{.greek-added} [απολλωνιαν]{.greek-omitted} [απολωνιαν]{.greek-added} ηλθον εις θεσσαλονικην οπου ην η συναγωγη των ιουδαιων[17:1]{.aside}

κατα δε το [ειωθος]{.greek-omitted} [ειωθως]{.greek-added} τω παυλω [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} προς αυτους και επι σαββατα τρια [διελεξατο]{.greek-omitted} [διελεγετο]{.greek-added} αυτοις απο των γραφων[17:2]{.aside}

διανοιγων και παρατιθεμενος οτι τον [χριστον]{.greek-abbr} εδει παθειν και αναστηναι εκ νεκρων και οτι ουτος [εστιν]{.greek-omitted} [εστι]{.greek-added} [ο]{.greek-omitted} [χριστος]{.greek-abbr} [ιησους]{.greek-abbr} ον εγω καταγγελλω υμιν[17:3]{.aside}

και τινες εξ αυτων επεισθησαν και [προσεκληρωθησαν]{.greek-omitted} [προσεκολληθησαν]{.greek-added} τω παυλω και τω σιλα των τε σεβομενων ελληνων [πληθος]{.greek-added} πολυ [πληθος]{.greek-omitted} γυναικων τε των πρωτων ουκ ολιγαι[17:4]{.aside}

[προσλαβομενοι]{.greek-omitted} [ζηλωσαντες]{.greek-added} δε οι ιουδαιοι [οι]{.greek-omitted} [απειθουντες]{.greek-omitted} [και]{.greek-added} [προσλαβομενοι]{.greek-added} των αγοραιων [ανδρας]{.greek-added} τινας [ανδρας]{.greek-omitted} πονηρους και οχλοποιησαντες εθορυβουν την πολιν επισταντες [τε]{.greek-omitted} [δε]{.greek-added} τη οικια [ιασονος]{.greek-omitted} [ιασωνος]{.greek-added} εζητουν αυτους [αγαγειν]{.greek-omitted} [παραγαγειν]{.greek-added} εις τον δημον[17:5]{.aside}

μη ευροντες δε αυτους [εσυρον]{.greek-omitted} [εσυραν]{.greek-added} τον [ιασονα]{.greek-omitted} [ιασωνα]{.greek-added} και τινας αδελφους επι τους πολιταρχας βοωντες οτι οι την οικουμενην αναστατωσαντες ουτοι και ενθαδε παρεισιν[17:6]{.aside}

ους υποδεδεκται ιασων και ουτοι παντες απεναντι των δογματων καισαρος [πρασσουσιν]{.greek-omitted} [πρασσουσι]{.greek-added} βασιλεα [ετερον]{.greek-added} λεγοντες [ετερον]{.greek-omitted} ειναι [ιησουν]{.greek-abbr}[17:7]{.aside}

εταραξαν δε τον οχλον και τους πολιταρχας [ακουοντας]{.greek-omitted} [ακουοντες]{.greek-added} ταυτα[17:8]{.aside}

και λαβοντες το ικανον παρα του [ιασονος]{.greek-omitted} [ιασωνος]{.greek-added} και των λοιπων απελυσαν αυτους[17:9]{.aside}

οι δε αδελφοι ευθεως δια της νυκτος εξεπεμψαν τον τε παυλον και τον σιλαν εις βεροιαν οιτινες παραγενομενοι εις την συναγωγην [απηεσαν]{.greek-omitted} των ιουδαιων [απειεσαν]{.greek-added}[17:10]{.aside}

ουτοι δε ησαν ευγενεστεροι των εν θεσσαλονικη οιτινες εδεξαντο τον λογον μετα πασης προθυμιας το καθ ημεραν ανακρινοντες τας γραφας [ει]{.greek-omitted} [εχοι]{.greek-omitted} [ταυτα]{.greek-omitted} [ουτως]{.greek-omitted}[17:11]{.aside}

[ουτοι]{.greek-omitted} [δε]{.greek-omitted} [ησαν]{.greek-omitted} [ευγενεστεροι]{.greek-omitted} [των]{.greek-omitted} [εν]{.greek-omitted} [θεσσαλονικη]{.greek-omitted} [οιτινες]{.greek-omitted} [εδεξαντο]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted} [μετα]{.greek-omitted} [πασης]{.greek-omitted} [προθυμιας]{.greek-omitted} [το]{.greek-omitted} [καθ]{.greek-omitted} [ημεραν]{.greek-omitted} [ανακρινοντες]{.greek-omitted} [τας]{.greek-omitted} [γραφας]{.greek-omitted} ει [εχοι]{.greek-omitted} ταυτα ουτως [εχει]{.greek-added}[17:11 | instance no. 2]{.aside}

πολλοι μεν [ουν]{.greek-omitted} εξ αυτων επιστευσαν και των ελληνιδων γυναικων των ευσχημονων και ανδρων ουκ ολιγοι[17:12]{.aside}

ως δε εγνωσαν οι απο της θεσσαλονικης ιουδαιοι οτι και εν τη βεροια [κατηγγελη]{.greek-omitted} [κατηγγελθη]{.greek-added} υπο του παυλου ο λογος του [θεου]{.greek-abbr} ηλθον κακει σαλευοντες [και]{.greek-added} [ταρασσοντες]{.greek-added} τους οχλους[17:13]{.aside}

ευθεως δε τοτε τον παυλον εξαπεστειλαν οι αδελφοι πορευεσθαι ως επι την θαλασσαν [υπεμενον]{.greek-omitted} [δε]{.greek-omitted} [επεμειναν]{.greek-added} [τε]{.greek-added} ο τε σιλας και [ο]{.greek-omitted} τιμοθεος εκει[17:14]{.aside}

οι δε καθιστωντες τον παυλον ηγαγον [αυτον]{.greek-omitted} εως αθηνων και λαβοντες εντολην προς τον σιλαν και τιμοθεον ινα ως ταχιστα [ελθωσιν]{.greek-omitted} [ελθωσι]{.greek-added} προς αυτον [εξηεσαν]{.greek-omitted} [εξιεσαν]{.greek-added}[17:15]{.aside}

εν δε ταις αθηναις εκδεχομενου αυτους του παυλου παρωξυνετο το [πνευμα]{.greek-abbr} αυτου εν αυτω [θεωρουντι]{.greek-omitted} [θεωρουντος]{.greek-added} κατειδωλον ουσαν την πολιν[17:16]{.aside}

διελεγετο μεν ουν εν τη συναγωγη τοις ιουδαιοις και τοις σεβομενοις [και]{.greek-omitted} εν [δε]{.greek-added} τη αγορα κατα πασαν ημεραν προς τους παρατυγχανοντας[17:17]{.aside}

τινες δε [των]{.greek-added} [επικουριων]{.greek-added} και [των]{.greek-omitted} [επικουρειων]{.greek-omitted} [και]{.greek-omitted} [των]{.greek-omitted} στοικων φιλοσοφων [συνεβαλλον]{.greek-omitted} [συνεβαλον]{.greek-added} αυτω και τινες ελεγον τι αν θελοι ο σπερμολογος ουτος λεγειν οι δε ξενων δαιμονιων δοκει [καταγγελευς]{.greek-omitted} [καταγγελλευς]{.greek-added} ειναι οτι τον [ιησουν]{.greek-abbr} και την αναστασιν ευηγγελιζετο[17:18]{.aside}

επιλαβομενοι τε αυτου [επι]{.greek-omitted} [πι]{.greek-added} τον αρειον παγον ηγαγον λεγοντες δυναμεθα γνωναι τις η καινη αυτη η υπο σου λαλουμενη διδαχη[17:19]{.aside}

ξενιζοντα γαρ τινα [εισφερει]{.greek-added} [εισφερεις]{.corr} εις τας ακοας ημων βουλομεθα ουν γνωναι [τινα]{.greek-added} [τι]{.greek-omitted} [αν]{.greek-omitted} [θελοι]{.greek-omitted} [θελει]{.greek-added} ταυτα ειναι[17:20]{.aside}

αθηναιοι δε παντες και οι επιδημουντες ξενοι εις ουδεν ετερον ευκαιρουν η λεγειν τι και ακουειν καινοτερον[17:21]{.aside}

σταθεις δε ο παυλος εν μεσω του αρειου παγου εφη ανδρες αθηναιοι κατα παντα ως [δεισιδαιμονεστερους]{.greek-omitted} [δισιδαιμονεστερους]{.greek-added} υμας θεωρω[17:22]{.aside}

διερχομενος γαρ και αναθεωρων τα σεβασματα υμων ευρον και βωμον εν ω [επεγεγραπτο]{.greek-omitted} [επεγεγραπτω]{.greek-added} αγνωστω [θεω]{.greek-abbr} ον ουν αγνοουντες ευσεβειτε τουτον εγω καταγγελλω υμιν[17:23]{.aside}

ο [θεος]{.greek-abbr} ο ποιησας τον [κοσμον]{.greek-omitted} [και]{.greek-omitted} [παντα]{.greek-omitted} [τα]{.greek-omitted} [εν]{.greek-omitted} [αυτω]{.greek-omitted} [ουτος]{.greek-omitted} [ουρανου]{.greek-omitted} [και]{.greek-omitted} [γης]{.greek-omitted} [κυριος]{.greek-omitted} [υπαρχων]{.greek-omitted} [ουκ]{.greek-omitted} [εν]{.greek-omitted} [χειροποιητοις]{.greek-omitted} [ναοις]{.greek-omitted} [κατοικει]{.greek-omitted}[17:24]{.aside}

[ο]{.greek-omitted} [θεος]{.greek-omitted} [ο]{.greek-omitted} [ποιησας]{.greek-omitted} [τον]{.greek-omitted} κοσμον και παντα τα εν αυτω ουτος [ουρανου]{.greek-abbr} και γης [υπαρχων]{.greek-added} [κυριος]{.greek-abbr} [υπαρχων]{.greek-omitted} ουκ εν χειροποιητοις ναοις κατοικει[17:24 | instance no. 2]{.aside}

ουδε υπο χειρων [ανθρωπων]{.greek-abbr} θεραπευεται [τινος]{.greek-added} προσδεομενος [τινος]{.greek-omitted} αυτος διδους [πασιν]{.greek-omitted} [απασι]{.greek-added} ζωην [και]{.greek-omitted} [πνοην]{.greek-omitted} κατα παντα[17:25]{.aside}

[εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} τε εξ ενος [αιματος]{.greek-omitted} παν εθνος [ανθρωπων]{.greek-abbr} κατοικειν επι [παντος]{.greek-added} [παν]{.greek-omitted} [το]{.greek-omitted} [προσωπον]{.greek-omitted} [προσωπου]{.greek-added} [πασης]{.greek-added} της γης ορισας προστεταγμενους καιρους και τας οροθεσιας της κατοικιας αυτων[17:26]{.aside}

ζητειν τον [κυριον]{.greek-omitted} [[θεον]{.greek-abbr}]{.greek-added} ει αρα γε ψηλαφησειαν αυτον και ευροιεν και γε ου μακραν απο ενος εκαστου [ημων]{.greek-omitted} [υμων]{.greek-added} υπαρχοντα[17:27]{.aside}

εν αυτω γαρ ζωμεν και κινουμεθα και εσμεν ως και τινες των καθ [υμας]{.greek-omitted} [ημας]{.greek-added} ποιητων [ειρηκασιν]{.greek-omitted} [ειρηκασι]{.greek-added} του γαρ και γενος εσμεν[17:28]{.aside}

γενος ουν υπαρχοντες του [θεου]{.greek-abbr} ουκ οφειλομεν νομιζειν χρυσω η αργυρω η λιθω χαραγματι τεχνης και ενθυμησεως [ανθρωπου]{.greek-abbr} το θειον ειναι ομοιον[17:29]{.aside}

τους μεν ουν χρονους της αγνοιας υπεριδων ο [θεος]{.greek-abbr} τα νυν παραγγελλει τοις [ανθρωποις]{.greek-abbr} [πασιν]{.greek-omitted} πανταχου μετανοειν[17:30]{.aside}

[διοτι]{.greek-omitted} [καθοτι]{.greek-added} εστησεν ημεραν εν η μελλει κρινειν την οικουμενην εν δικαιοσυνη εν ανδρι ω [ωρισεν]{.greek-omitted} [ωρισε]{.greek-added} πιστιν παρασχων πασιν αναστησας αυτον εκ νεκρων[17:31]{.aside}

[και]{.greek-added} [ακουσαντες]{.greek-omitted} [δε]{.greek-omitted} [αναστασιν]{.greek-omitted} [νεκρων]{.greek-omitted} οι μεν εχλευαζον οι δε ειπον [ακουσομεθα]{.greek-omitted} [ακουσωμεθα]{.greek-added} σου [παλιν]{.greek-omitted} [και]{.greek-added} περι τουτου [παλιν]{.greek-added}[17:32]{.aside}

και ουτως ο παυλος εξηλθεν εκ μεσου αυτων[17:33]{.aside}

τινες δε ανδρες κολληθεντες αυτω επιστευσαν εν οις και διονυσιος ο αρεοπαγιτης και γυνη ονοματι δαμαρις και ετεροι συν αυτοις[17:34]{.aside}

### Chapter 18

μετα δε ταυτα χωρισθεις ο παυλος εκ των αθηνων ηλθεν εις κορινθον[18:1]{.aside}

και ευρων τινα ιουδαιον ονοματι ακυλαν ποντικον τω γενει προσφατως εληλυθοτα απο της ιταλιας και πρισκιλλαν γυναικα αυτου δια το [τεταχεναι]{.greek-omitted} [διατεταχεναι]{.greek-added} κλαυδιον χωριζεσθαι παντας τους ιουδαιους [εκ]{.greek-omitted} [απο]{.greek-added} της [ρωμης]{.greek-omitted} [ρωμη]{.greek-added} προσηλθεν αυτοις[18:2]{.aside}

και δια το ομοτεχνον ειναι [εμενεν]{.greek-omitted} [εμεινε]{.greek-added} παρ αυτοις και ειργαζετο ησαν γαρ σκηνοποιοι την τεχνην[18:3]{.aside}

διελεγετο δε εν τη συναγωγη κατα παν σαββατον [επειθεν]{.greek-omitted} [τε]{.greek-omitted} [ιουδαιους]{.greek-omitted} [και]{.greek-omitted} [ελληνας]{.greek-omitted}[18:4]{.aside}

[διελεγετο]{.greek-omitted} [δε]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [συναγωγη]{.greek-omitted} [κατα]{.greek-omitted} [παν]{.greek-omitted} [σαββατον]{.greek-omitted} [επειθεν]{.greek-omitted} [επειθε]{.greek-added} τε ιουδαιους και ελληνας[18:4 | instance no. 2]{.aside}

ως δε κατηλθον απο της μακεδονιας ο τε σιλας και [ο]{.greek-omitted} τιμοθεος συνειχετο τω [πνευματι]{.greek-omitted} [λογω]{.greek-added} ο παυλος διαμαρτυρομενος τοις ιουδαιοις [ειναι]{.greek-added} τον [χριστον]{.greek-abbr} [ιησουν]{.greek-abbr}[18:5]{.aside}

αντιτασσομενων δε αυτων και βλασφημουντων [εκτιναξαμενος]{.greek-omitted} [εκτειναξαμενος]{.greek-added} [αυτου]{.greek-added} τα ιματια [ειπεν]{.greek-omitted} [ειπε]{.greek-added} προς αυτους το αιμα υμων επι την κεφαλην υμων καθαρος εγω απο του νυν εις τα εθνη πορευσομαι[18:6]{.aside}

και μεταβας εκειθεν [ηλθεν]{.greek-omitted} [εισηλθεν]{.greek-added} εις οικιαν τινος ονοματι [τιτου]{.greek-added} ιουστου σεβομενου τον [θεον]{.greek-abbr} ου η οικια ην συνομορουσα τη συναγωγη[18:7]{.aside}

κρισπος δε ο αρχισυναγωγος [επιστευσεν]{.greek-omitted} [επιστευσε]{.greek-added} τω [κυριω]{.greek-abbr} συν ολω τω οικω αυτου και πολλοι των κορινθιων ακουοντες επιστευον και εβαπτιζοντο[18:8]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε ο [κυριος]{.greek-abbr} δι οραματος εν νυκτι τω παυλω μη φοβου αλλα λαλει και μη σιωπησης[18:9]{.aside}

διοτι εγω ειμι μετα σου και ουδεις επιθησεται σοι του κακωσαι σε διοτι λαος [εστιν]{.greek-omitted} [εστι]{.greek-added} μοι πολυς εν τη πολει ταυτη[18:10]{.aside}

[εκαθισεν]{.greek-omitted} [εκαθισε]{.greek-added} [τε]{.greek-omitted} [δε]{.greek-added} ενιαυτον και μηνας εξ διδασκων εν αυτοις τον λογον του [θεου]{.greek-abbr}[18:11]{.aside}

γαλλιωνος δε ανθυπατευοντος της [αχαιας]{.greek-omitted} [ιταλιας]{.greek-added} κατεπεστησαν ομοθυμαδον οι ιουδαιοι τω παυλω και ηγαγον αυτον επι το βημα[18:12]{.aside}

λεγοντες οτι παρα τον νομον ουτος αναπειθει τους ανθρωπους σεβεσθαι τον [θεον]{.greek-abbr}[18:13]{.aside}

μελλοντος δε του παυλου ανοιγειν το στομα ειπεν ο γαλλιων προς τους ιουδαιους ει μεν [ουν]{.greek-omitted} ην αδικημα τι η [ραδοουργημα]{.greek-added} [ραδιουργημα]{.corr} πονηρον ω ιουδαιοι κατα λογον αν ηνεσχομην υμων[18:14]{.aside}

ει δε [ζητημα]{.greek-omitted} [ζητηματα]{.greek-added} [εστιν]{.greek-omitted} [εστι]{.greek-added} περι λογου και ονοματων και νομου του καθ υμας οψεσθε αυτοι κριτης γαρ εγω τουτων ου βουλομαι ειναι[18:15]{.aside}

και απηλασεν αυτους απο του βηματος[18:16]{.aside}

επιλαβομενοι δε παντες οι ελληνες σωσθενην τον αρχισυναγωγον ετυπτον εμπροσθεν του βηματος και ουδεν τουτων [εμελλε]{.greek-added} τω γαλλιωνι [εμελλεν]{.greek-omitted}[18:17]{.aside}

ο δε παυλος ετι προσμεινας ημερας ικανας τοις αδελφοις αποταξαμενος [εξεπλει]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [συριαν]{.greek-omitted} [και]{.greek-omitted} [συν]{.greek-omitted} [αυτω]{.greek-omitted} [πρισκιλλα]{.greek-omitted} [και]{.greek-omitted} [ακυλας]{.greek-omitted} [κειραμενος]{.greek-omitted} [την]{.greek-omitted} [κεφαλην]{.greek-omitted} [εν]{.greek-omitted} [κεγχρεαις]{.greek-omitted} [ειχεν]{.greek-omitted} [γαρ]{.greek-omitted} [ευχην]{.greek-omitted}[18:18]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [παυλος]{.greek-omitted} [ετι]{.greek-omitted} [προσμεινας]{.greek-omitted} [ημερας]{.greek-omitted} [ικανας]{.greek-omitted} [τοις]{.greek-omitted} [αδελφοις]{.greek-omitted} [αποταξαμενος]{.greek-omitted} [εξεπλει]{.greek-omitted} [εξεπλη]{.greek-added} εις την συριαν και συν αυτω πρισκιλλα και ακυλας κειραμενος την κεφαλην εν [κεγχρεαις]{.greek-omitted} [κεχρεαις]{.greek-added} [ειχεν]{.greek-omitted} [ειχε]{.greek-added} γαρ ευχην[18:18 | instance no. 2]{.aside}

[κατηντησεν]{.greek-omitted} [κατηντησε]{.greek-added} δε εις εφεσον [και]{.greek-omitted} [εκεινους]{.greek-omitted} [κακεινους]{.greek-added} κατελιπεν αυτου αυτος δε εισελθων εις την συναγωγην διελεχθη τοις ιουδαιοις[18:19]{.aside}

ερωτωντων δε [αυτων]{.greek-omitted} [αυτον]{.greek-added} επι πλειονα χρονον μειναι [παρ]{.greek-omitted} [αυτοις]{.greek-omitted} ουκ επενευσεν[18:20]{.aside}

αλλ απεταξατο αυτοις ειπων δει με παντως την εορτην την ερχομενην ποιησαι εις ιεροσολυμα παλιν δε ανακαμψω προς υμας του [θεου]{.greek-abbr} θελοντος [και]{.greek-added} ανηχθη απο της εφεσου[18:21]{.aside}

και κατελθων εις καισαρειαν αναβας και ασπασαμενος την εκκλησιαν κατεβη εις αντιοχειαν[18:22]{.aside}

και ποιησας χρονον τινα [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} διερχομενος καθεξης την γαλατικην χωραν και φρυγιαν επιστηριζων παντας τους μαθητας[18:23]{.aside}

ιουδαιος δε τις απολλως ονοματι αλεξανδρευς τω γενει ανηρ λογιος κατηντησεν εις εφεσον δυνατος ων εν ταις γραφαις[18:24]{.aside}

ουτος ην κατηχημενος την οδον του [κυριου]{.greek-abbr} και ζεων τω [πνευματι]{.greek-abbr} ελαλει και εδιδασκεν ακριβως τα περι του [κυριου]{.greek-omitted} [[ιησου]{.greek-abbr}]{.greek-added} επισταμενος μονον το βαπτισμα ιωαννου[18:25]{.aside}

ουτος τε ηρξατο παρρησιαζεσθαι εν τη συναγωγη ακουσαντες δε αυτου ακυλας και πρισκιλλα προσελαβοντο [αυτον]{.greek-omitted} [αυτου]{.greek-added} και ακριβεστερον αυτω εξεθεντο την [οδον]{.greek-added} του [[κυριου]{.greek-abbr}]{.greek-added} [θεου]{.greek-omitted} [οδον]{.greek-omitted}[18:26]{.aside}

βουλομενου δε αυτου [διελθειν]{.greek-omitted} [ελθειν]{.greek-added} εις την αχαιαν προτρεψαμενοι οι αδελφοι εγραψαν τοις μαθηταις αποδεξασθαι αυτον ος παραγενομενος συνεβαλετο πολυ τοις [πεπιστευκοσιν]{.greek-omitted} [πεπιστευκοσι]{.greek-added} δια της χαριτος[18:27]{.aside}

ευτονως γαρ τοις ιουδαιοις διακατηλεγχετο δημοσια επιδεικνυς δια των γραφων ειναι τον [χριστον]{.greek-abbr} [ιησουν]{.greek-abbr}[18:28]{.aside}

### Chapter 19

εγενετο δε εν τω τον απολλω ειναι εν κορινθω παυλον διελθοντα τα ανωτερικα μερη ελθειν εις εφεσον και ευρων τινας μαθητας[19:1]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} προς αυτους ει [πνευμα]{.greek-abbr} αγιον ελαβετε πιστευσαντες οι δε ειπον προς αυτον αλλ ουδε ει [πνευμα]{.greek-abbr} αγιον εστιν ηκουσαμεν[19:2]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} [δε]{.greek-added} [τε]{.greek-omitted} [προς]{.greek-omitted} [αυτους]{.greek-omitted} εις τι ουν εβαπτισθητε οι δε ειπον [εις]{.greek-omitted} [το]{.greek-omitted} [ιωαννου]{.greek-omitted} [βαπτισμα]{.greek-omitted}[19:3]{.aside}

[ειπεν]{.greek-omitted} [τε]{.greek-omitted} [προς]{.greek-omitted} [αυτους]{.greek-omitted} [εις]{.greek-omitted} [τι]{.greek-omitted} [ουν]{.greek-omitted} [εβαπτισθητε]{.greek-omitted} [οι]{.greek-omitted} [δε]{.greek-omitted} [ειπον]{.greek-omitted} εις το ιωαννου βαπτισμα[19:3 | instance no. 2]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε παυλος ιωαννης μεν [εβαπτισεν]{.greek-omitted} [εβαπτισε]{.greek-added} βαπτισμα μετανοιας τω λαω λεγων εις τον ερχομενον μετ αυτον ινα [πιστευσωσιν]{.greek-omitted} [πιστευσωσι]{.greek-added} τουτ εστιν εις τον [χριστον]{.greek-abbr} [ιησουν]{.greek-abbr}[19:4]{.aside}

ακουσαντες δε εβαπτισθησαν εις το ονομα του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr}[19:5]{.aside}

και επιθεντος αυτοις του παυλου τας χειρας [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} το [πνευμα]{.greek-abbr} το αγιον επ αυτους ελαλουν τε γλωσσαις και προεφητευον[19:6]{.aside}

ησαν δε οι παντες ανδρες ωσει [δεκαδυο]{.greek-omitted} [δεκα]{.greek-added} [και]{.greek-added} [δυο]{.greek-added}[19:7]{.aside}

εισελθων δε εις την συναγωγην επαρρησιαζετο επι μηνας τρεις διαλεγομενος και πειθων τα περι της βασιλειας του [θεου]{.greek-abbr}[19:8]{.aside}

ως δε τινες εσκληρυνοντο και ηπειθουν κακολογουντες την οδον ενωπιον του πληθους αποστας απ αυτων [αφωρισεν]{.greek-omitted} [αφωρισε]{.greek-added} τους μαθητας [το]{.greek-added} καθ ημεραν διαλεγομενος εν τη σχολη τυραννου τινος[19:9]{.aside}

τουτο δε εγενετο επι ετη δυο ωστε παντας τους κατοικουντας την ασιαν ακουσαι τον λογον του [κυριου]{.greek-abbr} [ιησου]{.greek-omitted} ιουδαιους τε και ελληνας[19:10]{.aside}

δυναμεις τε ου τας τυχουσας [εποιει]{.greek-omitted} ο [θεος]{.greek-abbr} [εποιει]{.greek-added} δια των χειρων παυλου[19:11]{.aside}

ωστε [κα]{.greek-supplied}ι επι τους ασθενουντας [επιφερεσθαι]{.greek-omitted} [αποφερεσθαι]{.greek-added} απο του χρωτος αυτου σουδαρια [η]{.greek-omitted} [και]{.greek-added} σιμικινθια και [απαλλασσεσθαι]{.greek-omitted} [απαλλαττεσθαι]{.greek-added} [τας]{.greek-added} [νοσσους]{.greek-added} απ αυτων [τας]{.greek-omitted} [νοσους]{.greek-omitted} τα τε πνευματα τα πονηρα [εκπορευεσθαι]{.greek-added} [εξερχεσθαι]{.greek-omitted} [απ]{.greek-omitted} [αυτων]{.greek-omitted}[19:12]{.aside}

επεχειρησαν δε τινες [απο]{.greek-omitted} [και]{.greek-added} των περιερχομενων ιουδαιων εξορκιστων ονομαζειν επι τους εχοντας τα [πνευματα]{.greek-abbr} τα πονηρα [το]{.greek-omitted} [τω]{.greek-added} [ονομα]{.greek-omitted} [ονοματι]{.greek-added} του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} [[χριστου]{.greek-abbr}]{.greek-added} λεγοντες [ορκιζομεν]{.greek-omitted} [ορκιζω]{.greek-added} υμας τον [ιησουν]{.greek-abbr} ον [ο]{.greek-omitted} παυλος κηρυσσει[19:13]{.aside}

ησαν δε [τινες]{.greek-omitted} [τινος]{.greek-added} [υιοι]{.greek-omitted} σκευα ιουδαιου αρχιερεως επτα [υιοι]{.greek-added} οι τουτο ποιουντες[19:14]{.aside}

αποκριθεν δε [ποτε]{.greek-added} το [πνευμα]{.greek-abbr} το πονηρον ειπεν [αυτοις]{.greek-added} τον [ιησουν]{.greek-abbr} γινωσκω και τον παυλον επισταμαι υμεις δε τινες εστε[19:15]{.aside}

και εφαλλομενος [ο]{.greek-added} [[ανθρωπος]{.greek-abbr}]{.greek-added} επ αυτους [ο]{.greek-omitted} [ανθρωπος]{.greek-omitted} εν ω ην το [πνευμα]{.greek-abbr} το πονηρον [και]{.greek-omitted} [κατακυριευσαν]{.greek-omitted} [κατακυριευσας]{.greek-added} [αυτων]{.greek-omitted} [αμφοτερων]{.greek-added} [ισχυσεν]{.greek-omitted} [ισχυσε]{.greek-added} κατ αυτων ωστε γυμνους και τετραυματισμενους εκφυγειν εκ του οικου εκεινου[19:16]{.aside}

τουτο δε εγενετο γνωστον πασιν ιουδαιοις τε και [ελλησιν]{.greek-omitted} [ελλησι]{.greek-added} τοις κατοικουσιν [την]{.greek-omitted} εφεσον και [επεπεσεν]{.greek-omitted} [επεπεσε]{.greek-added} φοβος επι παντας αυτους και εμεγαλυνετο το ονομα του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr}[19:17]{.aside}

### Chapter 25

[ημερων]{.greek-omitted} [αγριππας]{.greek-added} δε [διαγενομενων]{.greek-omitted} [τινων]{.greek-omitted} [αγριππας]{.greek-omitted} ο βασιλευς και βερνικη κατηντησαν εις καισαρειαν ασπασαμενοι τον [φηστον]{.greek-omitted} [φιστον]{.greek-added}[25:13]{.aside}

ως δε πλειους ημερας [διετριβεν]{.greek-omitted} [διετριβον]{.greek-added} εκει ο [φηστος]{.greek-omitted} [φιστος]{.greek-added} τω βασιλει ανεθετο τα κατα τον παυλον λεγων ανηρ τις [εστιν]{.greek-omitted} [εστι]{.greek-added} καταλελειμμενος υπο [φηλικος]{.greek-omitted} [φιλικος]{.greek-added} δεσμιος[25:14]{.aside}

περι ου γενομενου μου εις ιεροσολυμα [ενεφανισαν]{.greek-omitted} [ενεφανησαν]{.greek-added} οι αρχιερεις και οι πρεσβυτεροι των ιουδαιων αιτουμενοι [κατ]{.greek-omitted} [παρ]{.greek-added} αυτου δικην[25:15]{.aside}

προς ους απεκριθην οτι ουκ εστιν εθος ρωμαιοις χαριζεσθαι τινα [ανθρωπον]{.greek-abbr} [εις]{.greek-omitted} [απωλειαν]{.greek-omitted} πριν η ο κατηγορουμενος κατα προσωπον εχοι τους κατηγορους τοπον τε απολογιας [λαβοι]{.greek-omitted} [λαβων]{.greek-added} περι του εγκληματος[25:16]{.aside}

συνελθοντων ουν αυτων ενθαδε αναβολην μηδεμιαν ποιησαμενος τη εξης καθισας επι του βηματος εκελευσα αχθηναι τον ανδρα[25:17]{.aside}

περι ου σταθεντες οι κατηγοροι ουδεμιαν αιτιαν [επεφερον]{.greek-omitted} [εφερον]{.greek-added} ων υπενοουν εγω [πονηραν]{.greek-added}[25:18]{.aside}

ζητηματα δε τινα περι της ιδιας [δεισιδαιμονιας]{.greek-omitted} [δησιδαιμονιας]{.greek-added} ειχον προς αυτον και περι τινος [ιησου]{.greek-abbr} τεθνηκοτος ον εφασκεν ο παυλος ζην[25:19]{.aside}

απορουμενος δε εγω [εις]{.greek-added} την περι [τουτου]{.greek-omitted} [τουτων]{.greek-added} ζητησιν ελεγον ει βουλοιτο πορευεσθαι εις [ιερουσαλημ]{.greek-omitted} [ιεροσολυμα]{.greek-added} κακει κρινεσθαι περι τουτων[25:20]{.aside}

του δε παυλου επικαλεσαμενου [τηρηθηναι]{.greek-omitted} [αυτον]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [του]{.greek-omitted} [σεβαστου]{.greek-omitted} [διαγνωσιν]{.greek-omitted} [εκελευσα]{.greek-omitted} τηρεισθαι αυτον εως ου [πεμψω]{.greek-omitted} [αναπεμψω]{.greek-added} αυτον προς καισαρα[25:21]{.aside}

αγριππας δε προς τον [φηστον]{.greek-omitted} [φιστον]{.greek-added} εφη εβουλομην και αυτος του [ανθρωπου]{.greek-abbr} ακουσαι ο δε αυριον φησιν ακουση αυτου[25:22]{.aside}

τη ουν επαυριον ελθοντος του αγριππα και της βερνικης μετα πολλης φαντασιας και εισελθοντων εις το [ακροατηριον]{.greek-omitted} [ακροτηριον]{.greek-added} συν τε [τοις]{.greek-omitted} χιλιαρχοις και [ανδρασιν]{.greek-omitted} [ανδρασι]{.greek-added} τοις κατ εξοχην [ουσιν]{.greek-omitted} [ουσι]{.greek-added} της πολεως και κελευσαντος του [φηστου]{.greek-omitted} [φιστου]{.greek-added} ηχθη ο παυλος[25:23]{.aside}

και φησιν ο [φηστος]{.greek-omitted} [φιστος]{.greek-added} αγριππα βασιλευ και παντες οι συμπαροντες ημιν ανδρες θεωρειτε τουτον περι ου [παν]{.greek-omitted} [απαν]{.greek-added} το πληθος των ιουδαιων ενετυχον μοι εν τε ιεροσολυμοις και ενθαδε επιβοωντες μη δειν [αυτον]{.greek-added} ζην [αυτον]{.greek-omitted} μηκετι[25:24]{.aside}

εγω δε [καταλαβομενος]{.greek-omitted} [κατελαβομην]{.greek-added} μηδεν αξιον θανατου [πεπραχεναι]{.greek-added} αυτον [πεπραχεναι]{.greek-omitted} και αυτου δε τουτου επικαλεσαμενου τον σεβαστον εκρινα [πεμπειν]{.greek-omitted} [αυτον]{.greek-omitted}[25:25]{.aside}

[εγω]{.greek-omitted} [δε]{.greek-omitted} [καταλαβομενος]{.greek-omitted} [μηδεν]{.greek-omitted} [αξιον]{.greek-omitted} [θανατου]{.greek-omitted} [αυτον]{.greek-omitted} [πεπραχεναι]{.greek-omitted} [και]{.greek-omitted} [αυτου]{.greek-omitted} [δε]{.greek-omitted} [τουτου]{.greek-omitted} [επικαλεσαμενου]{.greek-omitted} [τον]{.greek-omitted} [σεβαστον]{.greek-omitted} [εκρινα]{.greek-omitted} πεμπειν [αυτον]{.greek-omitted}[25:25 | instance no. 2]{.aside}

περι ου ασφαλες τι γραψαι τω [κυριω]{.greek-abbr} ουκ εχω διο προηγαγον αυτον [εφ]{.greek-omitted} [υφ]{.greek-added} υμων και μαλιστα επι σου βασιλευ αγριππα οπως της ανακρισεως γενομενης [σχω]{.greek-omitted} [εχω]{.greek-added} τι γραψαι[25:26]{.aside}

αλογον γαρ [ειναι]{.greek-added} μοι δοκει πεμποντα δεσμιον μη και τας κατ αυτου αιτιας σημαναι[25:27]{.aside}

### Chapter 26

αγριππας δε προς τον παυλον εφη [επιτρεπεται]{.greek-omitted} [επιτρεπται]{.greek-added} σοι [λεγειν]{.greek-added} υπερ σεαυτου [λεγειν]{.greek-omitted} τοτε ο παυλος απελογειτο εκτεινας την χειρα[26:1]{.aside}

περι παντων ων [εγκαλουμαι]{.greek-omitted} [εγκαλουμε]{.greek-added} υπο ιουδαιων βασιλευ αγριππα ηγημαι εμαυτον μακαριον επι σου μελλων απολογεισθαι σημερον[26:2]{.aside}

μαλιστα γνωστην οντα σε παντων των κατα ιουδαιους [ηθων]{.greek-omitted} [εθων]{.greek-added} τε και ζητηματων διο δεομαι [σου]{.greek-omitted} μακροθυμως ακουσαι μου[26:3]{.aside}

την μεν ουν βιωσιν [μου]{.greek-omitted} την εκ νεοτητος την απ αρχης γενομενην εν τω εθνει μου εν ιεροσολυμοις [ισασιν]{.greek-omitted} [ισασι]{.greek-added} παντες [οι]{.greek-omitted} ιουδαιοι[26:4]{.aside}

προγινωσκοντες με ανωθεν εαν [θελωσιν]{.greek-omitted} [θελωσι]{.greek-added} μαρτυρειν οτι κατα την ακριβεστατην αιρεσιν της ημετερας θρησκειας εζησα φαρισαιος[26:5]{.aside}

και νυν επ ελπιδι της προς τους [πατερας]{.greek-abbr} [ημων]{.greek-added} επαγγελιας [γενομενης]{.greek-omitted} [γινομενης]{.greek-added} υπο του [θεου]{.greek-abbr} εστηκα κρινομενος[26:6]{.aside}

εις ην το δωδεκαφυλον ημων εν [εκτενεια]{.greek-omitted} [εκτενια]{.greek-added} νυκτα και [ημεραν]{.greek-omitted} [ημερα]{.greek-added} [λατρευον]{.greek-omitted} [λατρευων]{.greek-added} ελπιζει καταντησαι περι ης ελπιδος εγκαλουμαι βασιλευ [αγριππα]{.greek-omitted} υπο ιουδαιων[26:7]{.aside}

τι απιστον κρινεται παρ υμιν ει ο [θεος]{.greek-abbr} νεκρους εγειρει[26:8]{.aside}

εγω μεν ουν εδοξα εμαυτω προς το ονομα [ιησου]{.greek-abbr} του ναζωραιου δειν πολλα εναντια πραξαι[26:9]{.aside}

ο και [εποιησα]{.greek-omitted} [εποιησας]{.greek-added} εν ιεροσολυμοις και πολλους των αγιων [εγω]{.greek-omitted} [εν]{.greek-added} φυλακαις [κατεκλεισα]{.greek-omitted} [κατακλεισας]{.greek-added} την παρα των αρχιερεων εξουσιαν [λαβων]{.greek-omitted} [αναλαβων]{.greek-added} αναιρουμενων τε αυτων [κατηνεγκα]{.greek-omitted} [κατηνεγκον]{.greek-added} ψηφον[26:10]{.aside}

και κατα πασας τας συναγωγας πολλακις τιμωρων αυτους ηναγκαζον βλασφημειν περισσως τε [εμμαινομενος]{.greek-omitted} [εμμενομενος]{.greek-added} αυτοις εδιωκον εως και εις τας εξω πολεις[26:11]{.aside}

εν οις [και]{.greek-omitted} πορευομενος εις την δαμασκον [μετ]{.greek-omitted} [μετα]{.greek-added} εξουσιας και επιτροπης της παρα των [αρχιερεων]{.greek-omitted}[26:12]{.aside}

[εν]{.greek-omitted} [οις]{.greek-omitted} [και]{.greek-omitted} [πορευομενος]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [δαμασκον]{.greek-omitted} [μετ]{.greek-omitted} [εξουσιας]{.greek-omitted} [και]{.greek-omitted} [επιτροπης]{.greek-omitted} [της]{.greek-omitted} [παρα]{.greek-omitted} [των]{.greek-omitted} αρχιερεων[26:12 | instance no. 2]{.aside}

ημερας μεσης κατα την οδον ειδον βασιλευ [ουρανοθεν]{.greek-abbr} υπερ την λαμπροτητα του ηλιου [περιλαμψαν]{.greek-omitted} [υπερλαμψαν]{.greek-added} με φως και [τους]{.greek-omitted} [τοις]{.greek-added} συν εμοι [πορευομενους]{.greek-omitted} [πορευομενοις]{.greek-added}[26:13]{.aside}

παντων [δε]{.greek-omitted} [τε]{.greek-added} καταπεσοντων ημων εις την γην ηκουσα [φωνην]{.greek-omitted} [φωνης]{.greek-added} [λαλουσαν]{.greek-omitted} [λεγουσης]{.greek-added} προς με [και]{.greek-omitted} [λεγουσαν]{.greek-omitted} τη εβραιδι διαλεκτω σαουλ σαουλ τι με διωκεις σκληρον σοι προς κεντρα λακτιζειν[26:14]{.aside}

εγω δε [ειπον]{.greek-omitted} [ειπα]{.greek-added} τις ει [κυριε]{.greek-abbr} ο δε [[κυριος]{.greek-abbr}]{.greek-added} ειπεν εγω ειμι [ιησους]{.greek-abbr} [ο]{.greek-added} [ναζωραιος]{.greek-added} ον συ διωκεις[26:15]{.aside}

αλλα αναστηθι και στηθι επι τους ποδας σου εις τουτο γαρ ωφθην σοι προχειρισασθαι σε υπηρετην και μαρτυρα ων τε ειδες [με]{.greek-added} ων τε οφθησομαι σοι[26:16]{.aside}

εξαιρουμενος σε εκ του λαου και των εθνων εις ους εγω [αποστελω]{.greek-added} σε [αποστελλω]{.greek-omitted}[26:17]{.aside}

ανοιξαι οφθαλμους αυτων του [υποστρεψαι]{.greek-omitted} [επιστρεψαι]{.greek-added} απο σκοτους εις φως και [απο]{.greek-added} της εξουσιας του σατανα επι τον [θεον]{.greek-abbr} του λαβειν αυτους αφεσιν αμαρτιων και κληρον εν τοις ηγιασμενοις πιστει τη εις εμε[26:18]{.aside}

οθεν βασιλευ αγριππα ουκ εγενομην απειθης τη [ουρανιω]{.greek-abbr} οπτασια[26:19]{.aside}

αλλα τοις εν δαμασκω πρωτον και [εν]{.greek-added} ιεροσολυμοις εις πασαν τε την χωραν της ιουδαιας και τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} [απαγγελλων]{.greek-omitted} [παρηγγελλον]{.greek-added} μετανοειν και επιστρεφειν επι τον [θεον]{.greek-abbr} αξια της μετανοιας εργα πρασσοντας[26:20]{.aside}

ενεκα τουτων οι [ιου]{.greek-added} [ιουδαιοι]{.corr} [συλλαβομενοι]{.greek-added} με [συλλαβομενοι]{.greek-omitted} [οντα]{.greek-added} εν τω ιερω επειρωντο διαχειρισασθαι[26:21]{.aside}

επικουριας ουν τυχων της παρα του [θεου]{.greek-abbr} αχρι της ημερας ταυτης εστηκα [μαρτυρομενος]{.greek-omitted} [μαρτυρωμενος]{.greek-added} μικρω τε και μεγαλω ουδεν εκτος [λεγων]{.greek-omitted} [λεγω]{.greek-added} ων τε οι προφηται ελαλησαν μελλοντων γινεσθαι και [μωυσης]{.greek-omitted} [μωσης]{.greek-added}[26:22]{.aside}

ει παθητος ο [χριστος]{.greek-abbr} ει πρωτος εξ αναστασεως νεκρων φως μελλει καταγγελλειν τω [τε]{.greek-added} λαω και τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added}[26:23]{.aside}

ταυτα δε αυτου απολογουμενου ο [φηστος]{.greek-omitted} [φιστος]{.greek-added} μεγαλη τη φωνη [εφη]{.greek-omitted} [φησι]{.greek-added} μαινη παυλε τα πολλα σε γραμματα εις μανιαν περιτρεπει[26:24]{.aside}

ο δε [παυλος]{.greek-added} ου μαινομαι [φησιν]{.greek-omitted} [φησι]{.greek-added} κρατιστε φηστε αλλα αληθειας και σωφροσυνης ρηματα [εγω]{.greek-added} [αποφθεγγομαι]{.greek-omitted} [φθεγγομαι]{.greek-added}[26:25]{.aside}

επισταται γαρ περι τουτων ο βασιλευς προς ον [και]{.greek-omitted} παρρησιαζομενος λαλω λανθανειν γαρ αυτον [τι]{.greek-omitted} [τουτων]{.greek-omitted} [ου]{.greek-omitted} [πειθομαι]{.greek-omitted} [ουδεν]{.greek-omitted} [ου]{.greek-omitted} [γαρ]{.greek-omitted} [εν]{.greek-omitted} [γωνια]{.greek-omitted} [πεπραγμενον]{.greek-omitted} [τουτο]{.greek-omitted}[26:26]{.aside}

[επισταται]{.greek-omitted} [γαρ]{.greek-omitted} [περι]{.greek-omitted} [τουτων]{.greek-omitted} [ο]{.greek-omitted} [βασιλευς]{.greek-omitted} [προς]{.greek-omitted} [ον]{.greek-omitted} [και]{.greek-omitted} [παρρησιαζομενος]{.greek-omitted} [λαλω]{.greek-omitted} [λανθανειν]{.greek-omitted} [γαρ]{.greek-omitted} [αυτον]{.greek-omitted} [τι]{.greek-omitted} [τουτων]{.greek-omitted} ου πειθομαι [ουδεν]{.greek-omitted} [ου]{.greek-added} [[θεος]{.greek-abbr}]{.greek-added} ου γαρ [εστιν]{.greek-added} εν [γωνια]{.greek-omitted} [γονια]{.greek-added} πεπραγμενον τουτο[26:26 | instance no. 2]{.aside}

πιστευεις βασιλευ αγριππα τοις προφηταις οιδα οτι πιστευεις[26:27]{.aside}

ο δε αγριππας προς τον παυλον [εφη]{.greek-omitted} εν ολιγω με πειθεις χριστιανον γενεσθαι[26:28]{.aside}

ο δε παυλος [ειπεν]{.greek-omitted} [ευξαιμην]{.greek-omitted} [ευξαμην]{.greek-added} αν τω [θεω]{.greek-abbr} και εν ολιγω και εν πολλω ου μονον σε αλλα και παντας τους ακουοντας μου σημερον γενεσθαι τοιουτους οποιος καγω ειμι παρεκτος των δεσμων τουτων[26:29]{.aside}

[και]{.greek-omitted} [ταυτα]{.greek-omitted} [ειποντος]{.greek-omitted} [αυτου]{.greek-omitted} ανεστη [τε]{.greek-added} ο βασιλευς και ο ηγεμων η τε βερνικη και οι συγκαθημενοι αυτοις[26:30]{.aside}

και αναχωρησαντες ελαλουν προς αλληλους λεγοντες οτι ουδεν [αξιον]{.greek-added} θανατου [αξιον]{.greek-omitted} η δεσμων πρασσει [τι]{.greek-added} ο [ανθρωπος]{.greek-abbr} ουτος[26:31]{.aside}

αγριππας δε τω [φηστω]{.greek-omitted} [φιστω]{.greek-added} εφη απολελυσθαι [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} ο [ανθρωπος]{.greek-abbr} ουτος ει μη [επεκεκλητο]{.greek-omitted} [επικεκλητο]{.greek-added} καισαρα[26:32]{.aside}

### Chapter 27

ως δε εκριθη του αποπλειν ημας εις την ιταλιαν παρεδιδουν τον τε παυλον και τινας ετερους [δεσμωτας]{.greek-omitted} [δεσμοτας]{.greek-added} εκατονταρχη ονοματι ιουλιω [σπειρης]{.greek-omitted} [σπειρεις]{.greek-added} σεβαστης[27:1]{.aside}

επιβαντες δε πλοιω [αδραμυττηνω]{.greek-omitted} [αδραμυτινω]{.greek-added} μελλοντες πλειν [επι]{.greek-added} τους κατα την ασιαν τοπους ανηχθημεν οντος συν ημιν αρισταρχου μακεδονος [θεσσαλονικεως]{.greek-omitted} [θεσαλονικεως]{.greek-added}[27:2]{.aside}

τη [τε]{.greek-omitted} [δε]{.greek-added} ετερα κατηχθημεν εις σιδωνα φιλανθρωπως τε ο ιουλιος τω παυλω χρησαμενος [επετρεψεν]{.greek-omitted} [επετρεψε]{.greek-added} προς τους φιλους [πορευθεντα]{.greek-omitted} [πορευθεντι]{.greek-added} επιμελειας τυχειν[27:3]{.aside}

κακειθεν αναχθεντες υπεπλευσαμεν την κυπρον δια το τους ανεμους ειναι εναντιους[27:4]{.aside}

το τε πελαγος το κατα την [κιλιαν]{.greek-added} [κιλικιαν]{.corr} και παμφυλιαν διαπλευσαντες κατηλθομεν εις μυρα της λυκιας[27:5]{.aside}

κακει ευρων ο [εκατονταρχος]{.greek-omitted} [εκατονταρχης]{.greek-added} πλοιον [αλεξανδρινον]{.greek-omitted} [αλεξανδρεινον]{.greek-added} πλεον εις την ιταλιαν [ενεβιβασεν]{.greek-omitted} [ανεβιβασεν]{.greek-added} ημας εις αυτο[27:6]{.aside}

εν ικαναις δε ημεραις βραδυπλοουντες και μολις γενομενοι κατα την κνιδον μη [προσεωντος]{.greek-omitted} [προσ[ι]{.unclear}οντος]{.greek-added} ημας του ανεμου υπεπλευσαμεν την κρητην κατα σαλμωνην[27:7]{.aside}

μολις τε παραλεγομενοι αυτην ηλθομεν εις τοπον τινα καλουμενον καλους λιμενας ω εγγυς ην πολις [λασαια]{.greek-omitted} [λασσεα]{.greek-added}[27:8]{.aside}

ικανου δε χρονου διαγενομενου και οντος ηδη [επισφαλους]{.greek-omitted} [του]{.greek-omitted} [πλοος]{.greek-omitted} [δια]{.greek-omitted} [το]{.greek-omitted} [και]{.greek-omitted} [την]{.greek-omitted} [νηστειαν]{.greek-omitted} [ηδη]{.greek-omitted} [παρεληλυθεναι]{.greek-omitted} [παρηνει]{.greek-omitted} [ο]{.greek-omitted} [παυλος]{.greek-omitted}[27:9]{.aside}

[ικανου]{.greek-omitted} [δε]{.greek-omitted} [χρονου]{.greek-omitted} [διαγενομενου]{.greek-omitted} [και]{.greek-omitted} [οντος]{.greek-omitted} [ηδη]{.greek-omitted} [επισφαλους]{.greek-omitted} του πλοος [επισφαλους]{.greek-added} δια το και την νηστειαν ηδη παρεληλυθεναι παρηνει ο παυλος[27:9 | instance no. 2]{.aside}

λεγων αυτοις ανδρες θεωρω οτι μετα υβρεως και πολλης ζημιας ου μονον του [φορτιου]{.greek-omitted} [φορτειου]{.greek-added} και του πλοιου αλλα και των ψυχων ημων μελλειν [εσεσθαι]{.greek-omitted} [εσεσθε]{.greek-added} τον πλουν[27:10]{.aside}

ο δε εκατονταρχης τω [κυβερνητη]{.greek-omitted} [κυβερνιτη]{.greek-added} και τω ναυκληρω επειθετο μαλλον η τοις υπο του παυλου λεγομενοις[27:11]{.aside}

ανευθετου δε του λιμενος υπαρχοντος προς παραχειμασιαν οι [πλειους]{.greek-omitted} [πλειονες]{.greek-added} εθεντο βουλην αναχθηναι [κακειθεν]{.greek-omitted} [εκειθεν]{.greek-added} [ει]{.greek-omitted} [η]{.greek-added} πως δυναιντο καταντησαντες εις φοινικα παραχειμασαι λιμενα της κρητης βλεποντα κατα λιβα και κατα χωρον[27:12]{.aside}

υποπνευσαντος δε νοτου δοξαντες της προθεσεως κεκρατηκεναι αραντες ασσον παρελεγοντο την κρητην[27:13]{.aside}

μετ ου πολυ δε [εβαλεν]{.greek-omitted} [εβαλε]{.greek-added} κατ αυτης ανεμος τυφωνικος ο καλουμενος ευροκλυδων[27:14]{.aside}

συναρπασθεντος δε του πλοιου και μη [δυναμενου]{.greek-omitted} [δυναμενων]{.greek-added} αντοφθαλμειν τω ανεμω [επιδοντες]{.greek-omitted} [επιδιδοντος]{.greek-added} εφερομεθα[27:15]{.aside}

νησιον δε τι υποδραμοντες καλουμενον κλαυδην [ισχυσαμεν]{.greek-added} μολις [ισχυσαμεν]{.greek-omitted} περικρατεις γενεσθαι της σκαφης[27:16]{.aside}

ην αραντες [βοηθειαις]{.greek-omitted} [βοηθειας]{.greek-added} εχρωντο υποζωννυντες το πλοιον φοβουμενοι τε μη εις την συρτην εκπεσωσιν χαλασαντες το σκευος ουτως εφεροντο[27:17]{.aside}

σφοδρως δε χειμαζομενων ημων τη εξης εκβολην εποιουντο[27:18]{.aside}

και τη τριτη αυτοχειρες την σκευην του πλοιου [ερριψαμεν]{.greek-omitted} [ερριψαν]{.greek-added}[27:19]{.aside}

μητε δε ηλιου μητε αστρων επιφαινοντων επι πλειονας ημερας χειμωνος τε ουκ ολιγου επικειμενου λοιπον περιηρειτο πασα [η]{.greek-added} ελπις του σωζεσθαι ημας[27:20]{.aside}

πολλης [δε]{.greek-omitted} [τε]{.greek-added} ασιτιας υπαρχουσης τοτε σταθεις ο παυλος εν μεσω αυτων ειπεν εδει μεν ω ανδρες πειθαρχησαντας μοι μη αναγεσθαι απο της κρητης κερδησαι τε την υβριν ταυτην και την ζημιαν[27:21]{.aside}

και τα νυν παραινω υμας ευθυμειν αποβολη γαρ ψυχης [ουδεμια]{.greek-omitted} [ουδεμιας]{.greek-added} εσται εξ υμων πλην του πλοιου[27:22]{.aside}

παρεστη γαρ μοι ταυτη τη νυκτι [αγγελος]{.greek-omitted} του [θεου]{.greek-abbr} [ου]{.greek-omitted} [ειμι]{.greek-omitted} [ω]{.greek-omitted} [και]{.greek-omitted} [λατρευω]{.greek-omitted}[27:23]{.aside}

[παρεστη]{.greek-omitted} [γαρ]{.greek-omitted} [μοι]{.greek-omitted} [ταυτη]{.greek-omitted} [τη]{.greek-omitted} [νυκτι]{.greek-omitted} [αγγελος]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} ου ειμι [και]{.greek-added} ω [και]{.greek-omitted} λατρευω [αγγελος]{.greek-added}[27:23 | instance no. 2]{.aside}

λεγων μη φοβου παυλε καισαρι σε δει παραστηναι και ιδου κεχαρισται σοι ο [θεος]{.greek-abbr} παντας τους πλεοντας μετα σου[27:24]{.aside}

διο ευθυμειτε ανδρες πιστευω γαρ τω [θεω]{.greek-abbr} οτι ουτως εσται καθ ον τροπον λελαληται μοι[27:25]{.aside}

εις νησον δε τινα δει [υμας]{.greek-added} [ημας]{.corr} εκπεσειν[27:26]{.aside}

ως δε τεσσαρεσκαιδεκατη νυξ εγενετο διαφερομενων ημων εν τω αδρια κατα μεσον της νυκτος [υπενοουν]{.greek-omitted} [υπονοουν]{.greek-added} οι ναυται προσαγειν τινα αυτοις χωραν[27:27]{.aside}

και βολισαντες ευρον οργυιας εικοσι βραχυ δε διαστησαντες και παλιν βολισαντες ευρον οργυιας δεκαπεντε[27:28]{.aside}

φοβουμενοι τε [μηπως]{.greek-omitted} [εις]{.greek-omitted} [μη]{.greek-added} [που]{.greek-added} [κατα]{.greek-added} τραχεις τοπους εκπεσωμεν εκ πρυμνης ριψαντες αγκυρας τεσσαρας ηυχοντο ημεραν γενεσθαι[27:29]{.aside}

των δε ναυτων ζητουντων [φυγειν]{.greek-omitted} [εκφυγειν]{.greek-added} εκ του πλοιου και χαλασαντων την σκαφην εις την θαλασσαν προφασει ως εκ πρωρας μελλοντων αγκυρας εκτεινειν[27:30]{.aside}

ειπεν ο παυλος τω εκατονταρχη και τοις στρατιωταις εαν μη ουτοι [μεινωσιν]{.greek-omitted} εν τω πλοιω [μεινωσιν]{.greek-added} [υμεις]{.greek-omitted} [ημεις]{.greek-added} σωθηναι ου [δυνασθε]{.greek-omitted} [δυναμεθα]{.greek-added}[27:31]{.aside}

τοτε [απεκοψαν]{.greek-added} οι στρατιωται [απεκοψαν]{.greek-omitted} τα σχοινια της σκαφης και ειασαν αυτην εκπεσειν[27:32]{.aside}

αχρι δε ου ημελλεν ημερα [γενεσθαι]{.greek-added} [γινεσθαι]{.corr} παρεκαλει ο παυλος απαντας μεταλαβειν τροφης λεγων τεσσαρεσκαιδεκατην σημερον ημεραν προσδοκωντες ασιτοι [διατελειτε]{.greek-omitted} [διατελειται]{.greek-added} μηδεν προσλαβομενοι[27:33]{.aside}

διο παρακαλω υμας προσλαβειν τροφης τουτο γαρ προς της [υμετερας]{.greek-omitted} [ημετερας]{.greek-added} [σωτηριας]{.greek-omitted} υπαρχει ουδενος γαρ υμων θριξ [εκ]{.greek-omitted} [απο]{.greek-added} της κεφαλης [πεσειται]{.greek-omitted} [απολειται]{.greek-added}[27:34]{.aside}

ειπων δε ταυτα και λαβων αρτον [ευχαριστησεν]{.greek-omitted} [ηυχαριστησε]{.greek-added} τω [θεω]{.greek-abbr} ενωπιον παντων και κλασας ηρξατο εσθιειν[27:35]{.aside}

ευθυμοι δε γενομενοι παντες και αυτοι [προσελαβοντο]{.greek-omitted} [ελαβον]{.greek-added} τροφης[27:36]{.aside}

ημεν δε εν τω πλοιω αι πασαι ψυχαι διακοσιαι [εβδομηκοτα]{.greek-added} [εβδομηκοντα]{.corr} εξ[27:37]{.aside}

κορεσθεντες δε [της]{.greek-omitted} τροφης εκουφιζον το πλοιον εκβαλλομενοι τον σιτον εις την θαλασσαν[27:38]{.aside}

οτε δε ημερα εγενετο την γην ουκ επεγινωσκον κολπον δε τινα κατενοουν εχοντα αιγιαλον [εις]{.greek-omitted} [ον]{.greek-omitted} [εβουλευσαντο]{.greek-omitted} [ει]{.greek-omitted} [δυνατον]{.greek-omitted} [εξωσαι]{.greek-omitted} [το]{.greek-omitted} [πλοιον]{.greek-omitted}[27:39]{.aside}

[οτε]{.greek-omitted} [δε]{.greek-omitted} [ημερα]{.greek-omitted} [εγενετο]{.greek-omitted} [την]{.greek-omitted} [γην]{.greek-omitted} [ουκ]{.greek-omitted} [επεγινωσκον]{.greek-omitted} [κολπον]{.greek-omitted} [δε]{.greek-omitted} [τινα]{.greek-omitted} [κατενοουν]{.greek-omitted} [εχοντα]{.greek-omitted} [αιγιαλον]{.greek-omitted} εις ον εβουλευσαντο ει δυνατον εξωσαι το πλοιον[27:39 | instance no. 2]{.aside}

και τας αγκυρας περιελοντες ειων εις την θαλασσαν αμα ανεντες τας ζευκτηριας των πηδαλιων και επαραντες τον αρτεμονα τη πνεουση κατειχον εις τον αιγιαλον[27:40]{.aside}

περιπεσοντες δε εις τοπον διθαλασσον [επωκειλαν]{.greek-omitted} [εποκιλαν]{.greek-added} την ναυν και η μεν πρωρα ερεισασα εμεινεν ασαλευτος η δε πρυμνα [ελυετο]{.greek-omitted} [διελυετο]{.greek-added} υπο της βιας των κυματων[27:41]{.aside}

των δε στρατιωτων βουλη εγενετο ινα τους δεσμωτας αποκτεινωσιν μη τις εκκολυμβησας διαφυγη[27:42]{.aside}

ο δε [εκατονταρχος]{.greek-omitted} [εκατονταρχης]{.greek-added} βουλομενος [διασωσαι]{.greek-omitted} [διασωθηναι]{.greek-added} τον παυλον εκωλυσεν αυτους του βουληματος [εκελευσεν]{.greek-omitted} [εκελευσε]{.greek-added} τε τους δυναμενους [κολυμβων]{.greek-added} [κολυμβαν]{.corr} απορριψαντας πρωτους επι την γην εξιεναι[27:43]{.aside}

και τους λοιπους ους μεν επι σανισιν ους δε επι τινων των απο του πλοιου και ουτως εγενετο παντας διασωθηναι επι [την]{.greek-omitted} [γην]{.greek-omitted} [της]{.greek-added} [γης]{.greek-added}[27:44]{.aside}

### Chapter 28

και διασωθεντες τοτε επεγνωσαν οτι μελιτη η νησος καλειται[28:1]{.aside}

οι δε βαρβαροι παρειχον ου [την]{.greek-omitted} [τη]{.greek-added} τυχουσαν [φιλανθρωπιαν]{.greek-abbr} ημιν [αναψαντες]{.greek-omitted} [αψαντες]{.greek-added} γαρ πυραν προσελαβοντο παντας ημας δια τον υετον τον εφεστωτα και [δια]{.greek-omitted} το ψυχος[28:2]{.aside}

[συστρεψαντος]{.greek-omitted} [συστρεψαντο]{.greek-added} δε του παυλου φρυγανων πληθος και επιθεντος επι την πυραν εχιδνα [εκ]{.greek-omitted} [απο]{.greek-added} της θερμης [διεξελθουσα]{.greek-omitted} [εξελθουσα]{.greek-added} [καθηψεν]{.greek-omitted} [καθηψατο]{.greek-added} της χειρος αυτου[28:3]{.aside}

ως δε ειδον οι βαρβαροι κρεμαμενον το θηριον εκ της χειρος αυτου [ελεγον]{.greek-omitted} προς αλληλους [ελεγον]{.greek-added} παντως φονευς εστιν ο [ανθρωπος]{.greek-abbr} ουτος ον διασωθεντα εκ της θαλασσης η δικη ζην ουκ ειασεν[28:4]{.aside}

ο μεν ουν [αποτιναξας]{.greek-omitted} [αποτιναξαμενος]{.greek-added} το θηριον εις το πυρ επαθεν ουδεν [κακον]{.greek-omitted}[28:5]{.aside}

οι δε προσεδοκων αυτον μελλειν πιμπρασθαι η καταπιπτειν αφνω νεκρον επι πολυ δε αυτων προσδοκωντων και θεωρουντων μηδεν ατοπον εις αυτον [γινομενον]{.greek-omitted} [γενομενον]{.greek-added} μεταβαλλομενοι ελεγον [θεον]{.greek-abbr} αυτον ειναι[28:6]{.aside}

εν δε τοις περι τον τοπον εκεινον [υπηρχεν]{.greek-omitted} [υπηρχε]{.greek-added} χωρια τω πρωτω της νησου ονοματι ποπλιω ος αναδεξαμενος ημας τρεις ημερας φιλοφρονως εξενισεν[28:7]{.aside}

εγενετο δε τον [πατερα]{.greek-abbr} του [ποπλιου]{.greek-omitted} [πυρετοις]{.greek-omitted} [και]{.greek-omitted} [δυσεντερια]{.greek-omitted} [συνεχομενον]{.greek-omitted} [κατακεισθαι]{.greek-omitted} [προς]{.greek-omitted} [ον]{.greek-omitted} [ο]{.greek-omitted} [παυλος]{.greek-omitted} [εισελθων]{.greek-omitted} [και]{.greek-omitted} [προσευξαμενος]{.greek-omitted} [επιθεις]{.greek-omitted} [τας]{.greek-omitted} [χειρας]{.greek-omitted} [αυτω]{.greek-omitted} [ιασατο]{.greek-omitted} [αυτον]{.greek-omitted}[28:8]{.aside}

[εγενετο]{.greek-omitted} [δε]{.greek-omitted} [τον]{.greek-omitted} [πατερα]{.greek-omitted} [του]{.greek-omitted} ποπλιου πυρετοις και [δυσεντερια]{.greek-omitted} [δυσεντεριω]{.greek-added} [νοσω]{.greek-added} συνεχομενον κατακεισθαι προς ον ο παυλος εισελθων και προσευξαμενος επιθεις [τε]{.greek-added} τας χειρας αυτω ιασατο αυτον[28:8 | instance no. 2]{.aside}

τουτου [ουν]{.greek-omitted} [δε]{.greek-added} γενομενου και οι λοιποι οι εχοντες ασθενειας [εν]{.greek-omitted} [τη]{.greek-omitted} [νησω]{.greek-omitted} προσηρχοντο και εθεραπευοντο[28:9]{.aside}

οι και πολλαις τιμαις ετιμησαν ημας και αναγομενοις επεθεντο [τα]{.greek-omitted} [τας]{.greek-added} προς [την]{.greek-omitted} χρειαν[28:10]{.aside}

μετα δε τρεις μηνας [ηχθημεν]{.greek-omitted} [ανηχθημεν]{.greek-added} εν πλοιω [παρακεχειμακοτι]{.greek-omitted} [παρακεχιμακοτι]{.greek-added} εν τη νησω αλεξανδρινω [παρασημω]{.greek-omitted} [παρασιμο]{.greek-added} [διοσκουροις]{.greek-omitted} [διοσκοροις]{.greek-added}[28:11]{.aside}

και καταχθεντες εις συρακουσας επεμειναμεν ημερας τρεις[28:12]{.aside}

οθεν περιελθοντες κατηντησαμεν εις ρηγιον και μετα μιαν ημεραν επιγενομενου νοτου δευτεραιοι ηλθομεν εις ποτιολους[28:13]{.aside}

ου ευροντες αδελφους παρεκληθημεν [επ]{.greek-omitted} [παρ]{.greek-added} αυτοις επιμειναι ημερας επτα και ουτως εις την ρωμην ηλθομεν[28:14]{.aside}

κακειθεν οι αδελφοι ακουσαντες τα περι ημων εξηλθον εις [απαντησιν]{.greek-omitted} [συναντησιν]{.greek-added} [ημιν]{.greek-omitted} [ημων]{.greek-added} [αχρι]{.greek-omitted} [αχρις]{.greek-added} [αππιου]{.greek-omitted} [απιου]{.greek-added} φορου και τριων ταβερνων ους ιδων ο παυλος ευχαριστησας τω [θεω]{.greek-abbr} [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added} θαρσος[28:15]{.aside}

οτε δε [ηλθομεν]{.greek-omitted} [εισηλθωμεν]{.greek-added} εις [την]{.greek-added} ρωμην [επετραπη]{.greek-added} [ο]{.greek-omitted} [εκατονταρχος]{.greek-omitted} [παρεδωκεν]{.greek-omitted} [τους]{.greek-omitted} [δεσμιους]{.greek-omitted} τω [στρατοπεδαρχη]{.greek-omitted} [τω]{.greek-omitted} [δε]{.greek-omitted} παυλω [επετραπη]{.greek-omitted} μενειν καθ εαυτον συν τω φυλασσοντι αυτον στρατιωτη[28:16]{.aside}

εγενετο δε μετα ημερας τρεις συγκαλεσασθαι [τον]{.greek-omitted} [αυτον]{.greek-added} [παυλον]{.greek-omitted} τους οντας των ιουδαιων πρωτους συνελθοντων δε αυτων [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} προς αυτους [εγω]{.greek-added} ανδρες αδελφοι [εγω]{.greek-omitted} ουδεν εναντιον ποιησας τω λαω η τοις [εθεσιν]{.greek-omitted} [εθεσι]{.greek-added} τοις πατρωοις δεσμιος εξ ιεροσολυμων παρεδοθην εις τας χειρας των ρωμαιων[28:17]{.aside}

οιτινες ανακριναντες με εβουλοντο απολυσαι δια το μηδεμιαν αιτιαν θανατου υπαρχειν εν εμοι[28:18]{.aside}

αντιλεγοντων δε των ιουδαιων ηναγκασθην επικαλεσασθαι καισαρα ουχ ως του εθνους μου εχων τι [κατηγορησαι]{.greek-omitted} [κατηγορειν]{.greek-added}[28:19]{.aside}

δια ταυτην ουν την αιτιαν παρεκαλεσα υμας ιδειν και προσλαλησαι [ενεκεν]{.greek-omitted} [ενεκε]{.greek-added} γαρ της ελπιδος του [ισραηλ]{.greek-abbr} την αλυσιν ταυτην περικειμαι[28:20]{.aside}

οι δε προς αυτον ειπον ημεις ουτε γραμματα [εδεξαμεθα]{.greek-added} περι σου [εδεξαμεθα]{.greek-omitted} απο της ιουδαιας ουτε παραγενομενος τις των αδελφων [απηγγειλεν]{.greek-omitted} [η]{.greek-omitted} [ελαλησεν]{.greek-omitted} [τι]{.greek-omitted} [περι]{.greek-omitted} [σου]{.greek-omitted} [πονηρον]{.greek-omitted}[28:21]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted} [ειπον]{.greek-omitted} [ημεις]{.greek-omitted} [ουτε]{.greek-omitted} [γραμματα]{.greek-omitted} [περι]{.greek-omitted} [σου]{.greek-omitted} [εδεξαμεθα]{.greek-omitted} [απο]{.greek-omitted} [της]{.greek-omitted} [ιουδαιας]{.greek-omitted} [ουτε]{.greek-omitted} [παραγενομενος]{.greek-omitted} [τις]{.greek-omitted} [των]{.greek-omitted} [αδελφων]{.greek-omitted} απηγγειλεν η [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} τι περι σου πονηρον[28:21 | instance no. 2]{.aside}

αξιουμεν δε παρα σου ακουσαι α φρονεις περι μεν γαρ της αιρεσεως ταυτης γνωστον [ημιν]{.greek-added} εστιν [ημιν]{.greek-omitted} οτι πανταχου αντιλεγεται[28:22]{.aside}

ταξαμενοι δε αυτω ημεραν [ηκον]{.greek-omitted} [ηλθον]{.greek-added} προς αυτον εις την ξενιαν πλειονες οις εξετιθετο διαμαρτυρομενος την βασιλειαν του [θεου]{.greek-abbr} πειθων τε αυτους [τα]{.greek-omitted} περι του [ιησου]{.greek-abbr} απο τε του νομου [μωυσεως]{.greek-omitted} [μωυσεος]{.greek-added} και των προφητων απο πρωι εως εσπερας[28:23]{.aside}

και οι μεν επειθοντο τοις λεγομενοις οι δε ηπιστουν[28:24]{.aside}

ασυμφωνοι δε οντες προς αλληλους απελυοντο ειποντος του παυλου ρημα εν οτι καλως το [πνευμα]{.greek-abbr} το αγιον [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} δια ησαιου του προφητου προς τους [πατερας]{.greek-abbr} [ημων]{.greek-omitted} [υμων]{.greek-added}[28:25]{.aside}

[λεγον]{.greek-omitted} [λεγων]{.greek-added} πορευθητι προς τον λαον τουτον και ειπον ακοη [ακουσετε]{.greek-omitted} [ακουσητε]{.greek-added} και ου μη συνητε και βλεποντες [βλεψετε]{.greek-omitted} [βλεψητε]{.greek-added} και ου μη ιδητε[28:26]{.aside}

επαχυνθη γαρ η καρδια του λαου τουτου και τοις [ωσιν]{.greek-omitted} [ωσι]{.greek-added} βαρεως ηκουσαν και τους οφθαλμους αυτων εκαμμυσαν μηποτε [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} τοις οφθαλμοις και τοις ωσιν [ακουσωσιν]{.greek-omitted} [ακουσωσι]{.greek-added} και τη καρδια [συνωσιν]{.greek-omitted} [συνωσι]{.greek-added} και [επιστρεψωσιν]{.greek-omitted} [επιστρεψωσι]{.greek-added} και [ιασομαι]{.greek-omitted} [ιασωμαι]{.greek-added} αυτους[28:27]{.aside}

γνωστον ουν εστω υμιν οτι τοις εθνεσιν απεσταλη το σωτηριον του [θεου]{.greek-abbr} αυτοι και ακουσονται[28:28]{.aside}

[εμεινεν]{.greek-omitted} [εμεινε]{.greek-added} δε [ο]{.greek-omitted} [παυλος]{.greek-omitted} διετιαν ολην εν ιδιω μισθωματι και απεδεχετο παντας τους εισπορευομενους [προς]{.greek-omitted} [εις]{.greek-added} αυτον[28:30]{.aside}

κηρυσσων την βασιλειαν του [θεου]{.greek-abbr} και διδασκων τα περι του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} μετα [πασης]{.greek-omitted} παρρησιας ακωλυτως [αμην]{.greek-added}[28:31]{.aside}

