---
title: "Collation of Byz^RP^ vs 32805 (2805)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 2805 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=32805).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 2805                                   	| λογος                              	|
| 2805 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 2805 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 2805               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 2805                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 2805 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 2805                                                     	| [―]{.gap}                        	|
:::

## Acts

### Chapter 1

τον μεν πρωτον λογον εποιησαμην περι παν[τω]{.unclear}ν ω θεοφιλε ων ηρ[ξα]{.unclear}το ο [ιησους]{.greek-abbr} ποιειν τε και διδ[ασ]{.unclear}κειν[1:1]{.aside}

αχρι ης ημερ[ας]{.unclear} εντειλαμενος τοις αποστολοις δια [πνευματος]{.greek-abbr} αγιου ους εξελεξατο ανεληφθ[η]{.unclear}[1:2]{.aside}

οις και παρεστησεν εαυτον ζωντα μετα το παθειν αυτον εν πολλοις τεκμ[η]{.unclear}ριοις δι ημερων τεσσαρακοντα οπτανομενος αυ[τοι]{.unclear}ς [κ]{.unclear}α[ι]{.greek-supplied} λεγων τα περι της βασιλειας του [θεου]{.greek-abbr}[1:3]{.aside}

και συναλιζομενος παρηγγ[ει]{.unclear}λε[ν]{.unclear} αυτοις απο ιεροσολυμων μη χωριζεσθαι [α]{.unclear}λλα περιμενειν την επαγγελιαν του [πατρος]{.greek-abbr} ην ηκουσατε μου[1:4]{.aside}

οτι ιωαννης μεν εβαπτισεν [εν]{.greek-added} υδατι υμεις δε βαπτι[σθ]{.unclear}ησεσθε εν [πνευματι]{.greek-abbr} αγιω ου μετα πολλας ταυτας ημερας[1:5]{.aside}

οι μεν ουν συνελθοντες επηρωτ[ω]{.unclear}ν αυτον λεγοντες [κυριε]{.greek-abbr} ει εν τω χρονω τουτω αποκαθ[ι]{.unclear}στανεις την βασιλειαν τω [ισραηλ]{.greek-abbr}[1:6]{.aside}

ειπεν δε προς αυτους ουχ υμων [εστιν]{.greek-omitted} [εστι]{.greek-added} γνωναι χρονους η καιρους ους ο [πατηρ]{.greek-abbr} εθετο εν τη ιδια εξουσια[1:7]{.aside}

αλλα ληψεσθε δυναμιν επελθοντος του αγιου [πνευματος]{.greek-abbr} εφ υμας και εσεσθε μοι μαρτυρες εν τε [ιερουσαλημ]{.greek-abbr} και εν παση τη ιουδαια και [σαμαρεια]{.greek-omitted} [σαμαρια]{.greek-added} και εως εσχα[το]{.unclear}υ της γης[1:8]{.aside}

και ταυτα ειπων βλ[επ]{.unclear}οντων αυτων επηρθη [κα]{.unclear}[ι]{.greek-supplied} νεφελη υπελαβεν αυ[τ]{.unclear}ον απο των οφθαλμων αυτων[1:9]{.aside}

και ως ατενιζοντες ησαν [πορευομενου]{.greek-added} [αυτου]{.greek-added} εις τον [ουρανον]{.greek-abbr} [πορευομενου]{.greek-omitted} [αυτου]{.greek-omitted} και ιδου ανδρες δυο [παρειστηκεισαν]{.greek-omitted} [παριστηκεισαν]{.greek-added} αυτοις εν εσθητι λευκη[1:10]{.aside}

οι και ειπον ανδρες γαλιλαιοι τι εστηκατε ε[μ]{.unclear}βλεποντες [[και]{.corr}]{.greek-added} [[βλεποντες]{.corr}]{.greek-added} εις τον [ουρανον]{.greek-abbr} ουτος ο [ιησους]{.greek-abbr} ο αναληφθεις αφ υμων εις τον [ουρανον]{.greek-abbr} ουτως ελευσεται ον τροπον εθεασασθε αυτον [πορευομενον]{.greek-omitted} [πορευομε]{.greek-added} [νον]{.greek-added} εις τον [ουρανον]{.greek-abbr}[1:11]{.aside}

τοτε υπεστρεψαν εις [ιερουσαλημ]{.greek-abbr} απο ορους του καλουμενου ελαιωνος ο εστιν εγγυς [ιερουσαλημ]{.greek-abbr} σαβ[β]{.unclear}ατου [εχον]{.greek-omitted} [εχων]{.greek-added} οδον[1:12]{.aside}

και οτε εισηλθον ανεβησαν εις το υπερωον ου ησαν κ[α]{.unclear}ταμενοντες ο τε πετρος και ιακωβος και ιωαννης και ανδρεας φιλιππος και θωμας βαρθολομαιος και ματθαιος ιακ[ω]{.unclear}βος αλφ[αι]{.unclear}ου και σιμων ο ζηλωτης και ιουδας ιακωβου[1:13]{.aside}

ουτοι παντες ησαν προσκαρτερουντες ομοθυμαδον τη προσευχη και [τη]{.unclear} δεησει συν γυναιξιν [και]{.unclear} μαρια τη [μητρι]{.greek-abbr} του [ιησου]{.greek-abbr} και συν τοις αδελφοις αυτου[1:14]{.aside}

και εν ταις ημεραις ταυταις αναστας πετρ[ο]{.unclear}ς εν μεσω των μαθητων ειπεν ην τε οχλος ον[ο]{.unclear}ματων επι το αυτο ως εκατον εικοσι[1:15]{.aside}

ανδρες αδελφοι εδει πληρωθηναι την γραφην ταυτην ην προειπεν το [πνευμα]{.greek-abbr} το αγιον δια στοματος [δαυιδ]{.greek-abbr} περι ιουδα του γενομενου οδηγου τοις συλλαβουσιν τον [ιησουν]{.greek-abbr}[1:16]{.aside}

[οτε]{.greek-added} [οτι]{.corr} κατηριθμημενος ην συν ημ[ι]{.unclear}ν και ελαχεν τον κ[λη]{.unclear}ρον της διακονιας ταυτης[1:17]{.aside}

ουτος μεν ου[ν]{.unclear} εκτησατο χωριον εκ [[μι]{.unclear}]{.greek-added} [μισθου]{.greek-omitted} [σθου]{.greek-added} της αδικιας και πρηνης γενομενος [ελακησεν]{.greek-omitted} [ελακισεν]{.greek-added} μεσος και εξεχυθη παντα τα [σπλαγχνα]{.greek-omitted} [σπλαχνα]{.greek-added} αυτου[1:18]{.aside}

και γνωστον εγενετο [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις κατοικουσιν [ιερουσαλημ]{.greek-abbr} ωστε κληθηνα[ι]{.unclear} το χωριον εκεινο τη ιδια [αυτων]{.greek-added} διαλεκτω [αυτων]{.greek-omitted} ακελδαμα τουτ εστιν χωριον αιματος[1:19]{.aside}

γεγραπται γαρ εν βιβλω ψαλμων γενηθητω η επαυλις αυτου ερημος και μη εστω ο κατοικων εν αυτη και την επισκοπην αυτου λαβοι ετερος[1:20]{.aside}

δει ουν των συνελθοντ[ω]{.unclear}ν ημιν ανδρων εν παντι χρονω εν ω εισηλθεν [και]{.unclear} [ε]{.unclear}ξ[η]{.unclear}λθεν εφ ημας ο [κυριος]{.greek-abbr} [ιησους]{.greek-abbr}[1:21]{.aside}

αρξαμενος απο του βαπτισματος ιωαννου ε[ω]{.unclear}ς της ημερας ης ανελ[η]{.unclear}φθη αφ ημων μαρτυρα της [αναστασεως]{.greek-omitted} [αναστασεος]{.greek-added} αυτου γενεσθαι συν ημιν ενα τουτων[1:22]{.aside}

και εστησαν δυο ιωσηφ τον καλουμενον [βαρσαβαν]{.greek-omitted} [βαρσαββαν]{.greek-added} ος επεκληθη ιουστος και [μαθθιαν]{.greek-added} [ματθιαν]{.corr}[1:23]{.aside}

και προσευξαμενοι ειπον συ [κυριε]{.greek-abbr} καρδιογνωστα παντω[ν]{.unclear} αναδειξον ον εξελεξω εκ τουτων των δυο ενα[1:24]{.aside}

λαβειν τον κληρον της διακονιας ταυτης και αποστολης εξ ης παρεβη ιουδας πορευθηναι εις τον τοπον τον ιδιον[1:25]{.aside}

και εδωκαν κληρους αυτων και επεσεν ο [κληρος]{.greek-omitted} [κλιρος]{.greek-added} επι μα[τ]{.unclear}θιαν και [συγκατεψηφισθη]{.greek-omitted} [συνκατεψ[η]{.unclear}φ[ισθη]{.unclear}]{.greek-added} μετα των ενδε[κα]{.unclear} [αποσ]{.greek-supplied}τολων[1:26]{.aside}

### Chapter 2

και εν τω [συμπληρουσθαι]{.greek-omitted} [σ[υ]{.unclear}νπληρουσθαι]{.greek-added} την ημεραν της πεντηκοστης ησαν απαντες ομοθυμαδον επι το αυτο[2:1]{.aside}

κ[α]{.unclear}ι εγενετο αφνω εκ του [ουρανου]{.greek-abbr} ηχος ωσπ[ε]{.unclear}ρ φερομενης πν[ο]{.unclear}ης βιαιας και επληρωσεν ολον τον οικον ου ησαν καθημενοι[2:2]{.aside}

και ωφθησαν αυτοις διαμεριζομεναι γλωσσαι ωσει πυρος εκαθισεν τε εφ ενα εκαστον αυτων[2:3]{.aside}

και επλησθησαν απαντες [πνευματος]{.greek-abbr} αγιου και ηρξαντο λαλειν ετεραις γλωσσαις καθως το [πνευμα]{.greek-abbr} εδιδου αυτοις αποφθεγγεσθαι[2:4]{.aside}

ησαν δε εν [ιερουσαλημ]{.greek-abbr} κατοικουντες ιουδαιοι ανδρες ευλαβεις απο παντος εθνους των υπο τον [ουρανον]{.greek-abbr}[2:5]{.aside}

γενομενης δε της φωνης ταυτη[ς]{.unclear} συνηλθεν το πληθος και συνεχυθη οτι ηκουον εις εκαστος τη ιδια διαλεκτω λαλουντων αυτων[2:6]{.aside}

εξ[ι]{.unclear}σταντο δε παντες και εθαυμαζον λεγοντες προς αλληλους ουκ ιδου παντες ουτοι [εισιν]{.greek-omitted} οι λαλουντες [εισι]{.greek-added} γαλιλαιοι[2:7]{.aside}

και πως ημεις ακουομεν εκαστος τη ιδια διαλεκτω ημων εν η εγεννηθημεν[2:8]{.aside}

παρθοι και μηδοι και [ελαμιται]{.greek-omitted} [ελαμειται]{.greek-added} και οι κατοικουντες την μεσοποταμιαν ιουδαιαν τε και καππαδοκιαν ποντον και την ασιαν[2:9]{.aside}

φρυγιαν τε και παμφυλιαν αιγυπτον και τα μερη της λιβυης της κατα [κυρηνην]{.greek-omitted} [κυρινην]{.greek-added} και οι επιδημουντες ρωμαιοι [ιουδαιοι]{.greek-omitted} [τε]{.greek-omitted} [και]{.greek-omitted} [προσηλυτοι]{.greek-omitted}[2:10]{.aside}

[κρητες]{.greek-omitted} [ιουδαιοι]{.greek-added} [τε]{.greek-added} [και]{.greek-added} [προσηλυτοι]{.greek-added} [κρηται]{.greek-added} και αραβες ακουομεν λαλουντων αυτων ταις ημετεραις γλωσσαις τα μεγαλεια του [θεου]{.greek-abbr}[2:11]{.aside}

εξισταντο δε παντες και διηπορουν αλλος προς αλλον λεγοντες τι αν θελοι τουτο ειναι[2:12]{.aside}

ετεροι δε χλευαζοντες ελεγον οτι γλευκους [μεμεστωμενοι]{.greek-omitted} [μεμεστομενοι]{.greek-added} εισιν[2:13]{.aside}

σταθεις δε [ο]{.greek-added} πετρος συν τοις ενδεκα επηρεν την φωνην αυτου και [απε]{.greek-added} [απεφθεγξατο]{.greek-omitted} [φθεγξατο]{.greek-added} αυτοις ανδρες ιουδαιοι και οι κατοικουντες [ιερουσαλημ]{.greek-abbr} απαντες τουτο υμιν γνωστον εστω και ενωτισασθε τα ρηματα μου[2:14]{.aside}

ου γαρ ως υμεις υπολαμβανετε ουτοι μεθυουσιν εστιν γαρ ωρα τριτη της ημερας[2:15]{.aside}

αλλα τουτο [εστιν]{.greek-omitted} [εστι]{.greek-added} το ειρημενον δια του προφητου ιωηλ[2:16]{.aside}

και εσται εν ταις εσχαταις ημεραις λεγει ο [θεος]{.greek-abbr} εκχεω απο του [πνευματος]{.greek-abbr} μου επι πασαν σαρκα και προφητευσουσιν οι υιοι [υμων]{.greek-omitted} [ημων]{.greek-added} και αι θυγατερες υμων και οι νεανισκοι υμων ορασεις οψονται και οι πρεσβυτεροι υμων ενυπνια ενυπνιασθησονται[2:17]{.aside}

και γε επι τους δουλους μου και επι τας δουλας μου εν ταις ημεραις εκειναις εκχεω απο του [πνευματος]{.greek-abbr} μου και προφητευσουσιν[2:18]{.aside}

και δωσω τερατα εν τω [ουρανω]{.greek-abbr} ανω και σημεια επι της γης κατω αιμα και πυρ και ατμιδα καπνου[2:19]{.aside}

ο ηλιος μεταστραφησεται εις σκοτος και η σεληνη εις αιμα πριν η ελθειν την ημεραν [κυριου]{.greek-abbr} την μεγαλην και επιφανη[2:20]{.aside}

και εσται πας ος αν επικαλεσηται το ονομα [κυριου]{.greek-abbr} σωθησεται[2:21]{.aside}

ανδρες ισραηλιται ακουσατε τους λογους τουτους [ιησουν]{.greek-abbr} τον ναζωραιον ανδρα [αποδεδειγμενον]{.greek-added} απο του [θεου]{.greek-abbr} [αποδεδειγμενον]{.greek-omitted} εις υμας [δυναμεσιν]{.greek-omitted} [δυναμεσι]{.greek-added} και [τερασιν]{.greek-omitted} [τερασι]{.greek-added} και σημειοις οις εποιησεν δι αυτου ο [θεος]{.greek-abbr} εν μεσ[ω]{.unclear} υμων καθως και αυτοι οιδατε[2:22]{.aside}

τουτον τη ωρισμενη βουλη και προγνωσει του [θεου]{.greek-abbr} εκδοτον λαβοντες δια [χειρων]{.greek-omitted} [χειρος]{.greek-added} ανομων προσπηξαντες [ανειλετε]{.greek-omitted} [ανειλατε]{.greek-added}[2:23]{.aside}

ον ο [θεος]{.greek-abbr} ανεστησεν λυσας τας ωδινας του θανατου καθοτι ουκ ην δυνατον [κρα]{.greek-added} [κρατεισθαι]{.greek-omitted} [τεισθαι]{.greek-added} αυ[τ]{.unclear}ον υπ αυτου[2:24]{.aside}

[δαυιδ]{.greek-abbr} γαρ λεγει εις αυτον προωρωμην τον [κυριον]{.greek-abbr} ενωπιον μου δια παντος οτι εκ δεξιων μου εστιν ινα μη σαλευθω[2:25]{.aside}

δια τουτο ευφρανθη η καρδια μου και ηγαλλιασατο η γλωσσα μου ετι δε και η σαρξ μου κατασκηνωσει επ ελπιδι[2:26]{.aside}

οτι ουκ εγκαταλειψεις την ψυχην μου εις [αδου]{.greek-omitted} [αδην]{.greek-added} ουδε δωσεις τον οσιον σου ιδειν διαφθοραν[2:27]{.aside}

εγνωρισας μοι οδους ζωης πληρωσεις με [ευφροσυνης]{.greek-omitted} [ευφροσυνην]{.greek-added} μετα του προσωπου σου[2:28]{.aside}

ανδρες αδελφοι εξον ειπειν μετα παρρησιας προς υμας περι του πατριαρχου [δαυιδ]{.greek-abbr} οτι και ετελευτησεν και εταφη και το μνημα αυτου εστιν εν ημιν αχρι της ημερας ταυτης[2:29]{.aside}

προφητης ουν υπαρχων και ειδως οτι ορκω ωμοσεν αυτω ο [θεος]{.greek-abbr} εκ καρπου της οσφυος αυτου το κατα σαρκα αναστησειν τον [χριστον]{.greek-abbr} καθισαι επι [του]{.greek-omitted} [τον]{.greek-added} [θρονου]{.greek-omitted} [θρονον]{.greek-added} αυτου[2:30]{.aside}

προιδων ε[λ]{.unclear}αλησεν περι της αναστασεως του [χριστου]{.greek-abbr} οτι [ου]{.greek-omitted} [ουκ]{.greek-added} [κατελειφθη]{.greek-omitted} [εγκατεληφθη]{.greek-added} η ψυχη αυτου εις αδου ουδε η σαρξ αυτου ειδεν διαφθοραν[2:31]{.aside}

τουτον τον [ιησουν]{.greek-abbr} ανεστησεν ο [θεος]{.greek-abbr} ου παντες ημεις εσμεν μαρτυρες[2:32]{.aside}

τη δεξια ουν του [θεου]{.greek-abbr} υψωθεις την τε επαγγελιαν του αγιου [πνευματος]{.greek-abbr} λαβων παρα του [πατρος]{.greek-abbr} εξεχεεν τουτο ο νυν υμεις βλεπετε και ακουετε[2:33]{.aside}

ου γαρ [δαυιδ]{.greek-abbr} ανεβη εις [τους]{.greek-omitted} [τον]{.greek-added} [ουρανους]{.greek-omitted} [[ουρανον]{.greek-abbr}]{.greek-added} λεγει δε αυτος ειπεν ο [κυριος]{.greek-abbr} τω κυριω μου καθου εκ δεξιων μου[2:34]{.aside}

εως αν θω τους εχθρους σου υποποδιον των ποδων σου[2:35]{.aside}

ασφαλως ουν γινωσκετω πας οικος [ισραηλ]{.greek-abbr} οτι και [κυριον]{.greek-abbr} [αυτον]{.greek-added} και [χριστον]{.greek-abbr} [αυτον]{.greek-omitted} ο [θεος]{.greek-abbr} [εποιησεν]{.greek-omitted} [εποιη]{.greek-added} [σεν]{.greek-added} τουτον τον [ιησουν]{.greek-abbr} ον υμεις [εσταυρωσατε]{.greek-abbr}[2:36]{.aside}

ακουσαντες δε κατενυγησαν τη καρδια ειπον τε προς τον πετρον και τους λοιπους αποστολους τι [ποιησομεν]{.greek-omitted} [ποιησωμεν]{.greek-added} ανδρες αδελφοι[2:37]{.aside}

πετρος δε εφη προς αυτους μετανοησατε και βαπτισθητω εκαστος υμων επι τω ονοματι [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} εις αφεσιν αμαρτιων και ληψεσθε την δωρεαν του αγιου [πνευματος]{.greek-abbr}[2:38]{.aside}

υμιν γαρ εστιν η επαγγελια και τοις [τοις]{.greek-added} τεκνοις υμων και [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις εις μακραν οσους αν προσκαλεσηται [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ημων[2:39]{.aside}

ετεροις τε λογοις πλειοσιν [διεμαρτυρετο]{.greek-omitted} [διεμαρτυρατο]{.greek-added} και παρεκαλει [αυτους]{.greek-added} λεγων σωθητε απο της γενεας της σκολιας ταυτης[2:40]{.aside}

οι μεν ουν ασμενως αποδεξαμενοι τον λογον αυτου εβαπτισθησαν και προσετεθησαν τη ημερα εκεινη ψυχαι ωσει τρισχιλιαι[2:41]{.aside}

ησαν [δε]{.greek-omitted} [ουν]{.greek-added} προσκαρτερουντες τη διδαχη των αποστολων και τη κοινωνια και τη κλασει του αρτου και ταις προσευχαις[2:42]{.aside}

εγενετο δε παση ψυχη φοβος πολλα [τε]{.greek-omitted} τερατα και σημεια δια των [χειρων]{.greek-added} [των]{.greek-added} αποστολων [εγινετο]{.greek-omitted} [εγενετο]{.greek-added} [εν]{.greek-added} [[ιερουσαλημ]{.greek-abbr}]{.greek-added} [φοβος]{.greek-added} [τε]{.greek-added} [ην]{.greek-added} [μεγας]{.greek-added} [επι]{.greek-added} [παντας]{.greek-added} [αυτους]{.greek-added}[2:43]{.aside}

[και]{.greek-added} παντες δε οι πιστευοντες ησαν επι το αυτο και ειχον απαντα κοινα[2:44]{.aside}

και τα κτηματα και τας υπαρξεις επιπρασκον και διεμεριζον αυτα πασιν καθοτι αν τις χρειαν ειχεν[2:45]{.aside}

καθ ημεραν τε προσκαρτερουντες ομοθυμαδον εν τω ιερω κλωντες τε [αρτον]{.greek-added} κατ οικον [αρτον]{.greek-omitted} [μετελαμβανον]{.greek-omitted} [μετελαμβανων]{.greek-added} τροφης εν αγαλλι[α]{.unclear}[σει]{.greek-supplied} και αφελοτητι καρδιας[2:46]{.aside}

αινουντες τον [θεον]{.greek-abbr} και εχοντες χαριν προς ολον τον λαον ο δε [κυριος]{.greek-abbr} [προσετιθει]{.greek-omitted} [προσετιθη]{.greek-added} τους σωζομενους καθ ημεραν τη εκκλησια[2:47]{.aside}

### Chapter 3

επι το αυτο δε πετρος και ιωαννης ανεβαινον εις το ιερον επι την ωραν της προσευχης την ενατην[3:1]{.aside}

και τις ανηρ χωλος εκ κοιλιας [μητρος]{.greek-abbr} αυτου υπαρχων εβασταζετο ον ετιθουν καθ ημεραν προς την θυραν του ιερου την λεγομενην ωραιαν του αιτειν ελεημοσυνην παρα των [εισπορευομενων]{.greek-omitted} [εισπορευομενον]{.greek-added} εις το ιερον[3:2]{.aside}

ος ιδων πετρον και ιωαννην μελλοντας εισιεναι εις το ιερον ηρωτα ελεημοσυνην [λαβειν]{.greek-added}[3:3]{.aside}

ατενισας δε πετρος εις αυτον συν τω ιωαννη ειπεν βλεψον εις ημας[3:4]{.aside}

ο δε επειχεν αυτοις προσδοκων τι παρ αυτων λαβειν[3:5]{.aside}

ειπεν δε πετρος αργυριον και χρυσιον ουχ υπαρχει μοι ο δε εχω τουτο σοι [διδωμι]{.greek-omitted} [διδομι]{.greek-added} εν τω ονοματι [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} του ναζωραιου [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} και περιπατει[3:6]{.aside}

και πιασας αυτον της δεξιας χειρος ηγειρεν παραχρημα δε εστερεωθησαν αυτου αι βασεις και τα σφυρα[3:7]{.aside}

και εξαλλομενος εστη και περιεπατει και εισηλθεν συν αυτοις [περιπατων]{.greek-added} εις το ιερον [περιπατων]{.greek-omitted} [και]{.greek-omitted} αλλομενος και αινων τον [θεον]{.greek-abbr}[3:8]{.aside}

και ειδεν αυτον πας ο λαος περιπατουντα και αινουντα τον [θεον]{.greek-abbr}[3:9]{.aside}

επεγινωσκον τε αυτον οτι ουτος ην ο προς την ελεημοσυνην καθημενος επι τη ωραια πυλη του ιερου και επλησθησαν θαμβους και εκστασεως επι τω συμβεβηκοτι αυτω[3:10]{.aside}

κρατουντος δε [του]{.greek-omitted} [αυτου]{.greek-added} [ιαθεντος]{.greek-omitted} [χωλου]{.greek-omitted} τον πετρον και [τον]{.greek-added} ιωαννην συνεδραμεν προς αυτους πας ο λαος επι τη στοα τη καλουμενη σολομωντος εκθαμβοι[3:11]{.aside}

[ι]{.unclear}δων δε πετρος απεκρινατο προς τον λαον ανδρες ισραηλιται τι θαυμαζετε επι [τουτω]{.greek-omitted} [τουτο]{.greek-added} η ημιν τι ατενιζετε ως ιδια δυναμει η ευσεβεια [πεποιηκοσιν]{.greek-omitted} [πεποιηκωσιν]{.greek-added} του περιπατειν αυτον[3:12]{.aside}

ο [θεος]{.greek-abbr} αβρααμ και ισαακ και ιακωβ ο [θεος]{.greek-abbr} των [πατερων]{.greek-abbr} ημων εδοξασεν τον παιδα αυτου [ιησουν]{.greek-abbr} ον υμεις μεν παρεδωκατε και ηρνησασθε [αυτον]{.greek-omitted} κατα προσωπον πιλατου κριναντος εκεινου απολυειν[3:13]{.aside}

υμεις δε τον αγιον και δικαιον ηρνησασθε και ητησασθε ανδρα φονεα χαρισθηναι υμιν[3:14]{.aside}

τον δε αρχηγον της ζωης απεκτεινατε ον ο [θεος]{.greek-abbr} ηγειρεν εκ νεκρων ου ημεις μαρτυρες εσμεν[3:15]{.aside}

και επι τη πιστει του ονοματος αυτου τουτον ον θεωρειτε και οιδατε εστερεωσεν το ονομα αυτου και η πιστις η δι αυτου εδωκεν αυτω την ολοκληριαν ταυτην απεναντι παντων υμων[3:16]{.aside}

και νυν αδελφοι οιδα οτι κατα αγνοιαν επραξ[α]{.unclear}τε ωσπερ και οι [αρχοντες]{.greek-omitted} [[πατερες]{.greek-abbr}]{.greek-added} υμων[3:17]{.aside}

ο δε [θεος]{.greek-abbr} α προκατηγγειλεν δια στοματος παντων των προφητων [αυτου]{.greek-omitted} παθειν τον [χριστον]{.greek-abbr} [αυτου]{.greek-added} επληρωσεν ουτως[3:18]{.aside}

[ω]{.greek-added} μετανοησατε ουν και επιστρεψατε εις το [εξαλειφθηναι]{.greek-omitted} [εξαληφθηναι]{.greek-added} υμων τας αμαρτιας [οπως]{.greek-omitted} [αν]{.greek-omitted} [ελθωσιν]{.greek-omitted} [καιροι]{.greek-omitted} [αναψυξεως]{.greek-omitted} [απο]{.greek-omitted} [προσωπου]{.greek-omitted} [του]{.greek-omitted} [κυριου]{.greek-omitted}[3:19]{.aside}

[οπως]{.greek-added} [αν]{.greek-added} [ελθωσιν]{.greek-added} [κ[αι]{.unclear}ροι]{.greek-added} [αναψυξεως]{.greek-added} [απο]{.greek-added} [προσωπου]{.greek-added} [του]{.greek-added} [[κυριου]{.greek-abbr}]{.greek-added} και αποστειλη τον προκεχειρισμενον υμιν [χριστον]{.greek-abbr} [ιησουν]{.greek-abbr}[3:20]{.aside}

ον δει [ουρανον]{.greek-abbr} μεν [δεξασθαι]{.greek-omitted} [δεξασθε]{.greek-added} αχρ[ι]{.unclear} χρονων αποκαταστασεω[ς]{.unclear} παντων ων ελαλησεν ο [θεος]{.greek-abbr} δια στοματος παντων των [αγιων]{.greek-omitted} [αγι]{.greek-added} [ων]{.greek-added} [απ]{.greek-added} [αιωνος]{.greek-added} αυτου προφητων [απ]{.greek-omitted} [αιωνος]{.greek-omitted}[3:21]{.aside}

[μωσης]{.greek-omitted} [μωυσης]{.greek-added} μεν γαρ [ειπεν]{.greek-added} προς τους [πατερας]{.greek-abbr} [ειπεν]{.greek-omitted} οτι προφητην υμιν αναστησει [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ημων εκ των αδελφων υμων ως εμε αυτου ακουσεσθε κατα παντα οσα αν λαληση προς υμας[3:22]{.aside}

εσται δε πασα ψυχη ητις [εαν]{.greek-omitted} [αν]{.greek-added} μη ακουση του προφητου εκεινου εξολοθρευθησεται εκ του λαου[3:23]{.aside}

και παντες δε οι προφητα[ι]{.unclear} απο σαμουηλ και των καθεξης οσοι ελαλησαν και [κατηγγειλαν]{.greek-omitted} [προκατηγγειλαν]{.greek-added} τας ημερας ταυτας[3:24]{.aside}

υμεις εστε [οι]{.greek-added} υιοι των προφητων και της διαθηκης ης διεθετο ο [θεος]{.greek-abbr} προς τ[ο]{.unclear}υς [πατερας]{.greek-abbr} ημων λεγων προς αβρααμ και εν τω σπερματι σου ενευλογηθησονται πασαι αι πατριαι της γης[3:25]{.aside}

υμιν πρωτον ο [θεος]{.greek-abbr} αναστησας τον παιδα αυτου [ιησουν]{.greek-abbr} απεστειλεν αυτον ευλογουντα υμας εν τω αποστρεφειν εκαστον απο των πονηριων υμων[3:26]{.aside}

### Chapter 4

λαλουντων δε αυτων προς τον λαον επεστησαν αυτοις οι ιερεις και ο στρατηγος του ιερου και οι σαδδουκαιοι[4:1]{.aside}

διαπονουμενοι δια το διδασκειν αυτους τον λαον και καταγγελλειν εν τω [ιησου]{.greek-abbr} την αναστασιν των νεκρων[4:2]{.aside}

και επεβαλον [επ]{.greek-added} [αυτοις]{.greek-omitted} [αυτους]{.greek-added} τας χειρας και εθεντο [αυτους]{.greek-added} εις τηρησιν εις την αυριον ην γαρ εσπερα ηδη[4:3]{.aside}

πολλοι [δε]{.greek-omitted} [μεν]{.greek-added} των ακουσαντων τον λογον επιστευσαν και εγενηθη ο αριθμος των ανδρων [ωσει]{.greek-omitted} [ως]{.greek-added} χιλιαδες πεντε[4:4]{.aside}

εγενετο δε επι την αυριον συναχθηναι αυτων τους αρχοντας και πρεσβυτερους και γραμματεις [εις]{.greek-omitted} [εν]{.greek-added} [ιερουσαλημ]{.greek-abbr}[4:5]{.aside}

και ανναν τον αρχιερεα και καιαφαν και ιωαννην και αλεξανδρον και οσοι ησαν εκ γενους αρχιερατικου[4:6]{.aside}

και στησαντες αυτους εν [τω]{.greek-added} μεσω επυνθανοντο εν ποια δυναμει η εν ποιω ονοματι εποιησατε τουτο υμεις[4:7]{.aside}

τοτε πετρος πλησθεις [πνευματος]{.greek-abbr} αγιου ειπεν προς αυτους αρχοντες του λαου και πρεσβυτεροι του [ισραηλ]{.greek-abbr}[4:8]{.aside}

ει ημεις σημερον ανακρινομεθα [επι]{.greek-omitted} [επ]{.greek-added} ευεργεσια [ανθρωπου]{.greek-abbr} ασθενους εν τινι ουτος σεσωσται[4:9]{.aside}

γνωστον εστω πασιν υμιν και παντι τω λαω [ισραηλ]{.greek-abbr} οτι εν τω ονοματι [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} του ναζωραιου ον υμεις [εσταυρωσατε]{.greek-abbr} ον ο [θεος]{.greek-abbr} ηγειρεν εκ νεκρων εν τουτω ουτος παρεστηκεν ενωπιον υμων υγιης[4:10]{.aside}

ουτος εστιν ο λιθος ο εξουθενηθεις υφ υμων των οικοδομουντων ο γενομενος εις κεφαλην γωνιας[4:11]{.aside}

και ουκ εστιν εν αλλω ουδενι η [σωτηρια]{.greek-abbr} ουτε γαρ ονομα [ετερον]{.greek-added} εστιν [ετερον]{.greek-omitted} [υπο]{.greek-added} [τον]{.greek-added} [[ουρανον]{.greek-abbr}]{.greek-added} το δεδομενον εν [ανθρωποις]{.greek-abbr} εν ω δει σωθηναι ημας[4:12]{.aside}

θεωρουντες δε την του πετρου παρρησιαν και ιωαννου και καταλαβομενοι οτι [ανθρωποι]{.greek-abbr} αγραμματοι εισιν και ιδιωται εθαυμαζον επεγινωσκον τε αυτους οτι συν τω [ιησου]{.greek-abbr} ησαν[4:13]{.aside}

τον [δε]{.greek-omitted} [τε]{.greek-added} [ανθρωπον]{.greek-abbr} βλεποντες συν αυτοις εστωτα τον τεθεραπευμενον ουδεν ειχον αντειπειν[4:14]{.aside}

κελευσαντες δε αυτους εξω του συνεδριου απελθειν συνεβαλλον προς αλληλους[4:15]{.aside}

λεγοντες τι [ποιησομεν]{.greek-omitted} [ποιησωμεν]{.greek-added} τοις [ανθρωποις]{.greek-abbr} τουτοις οτι μεν γαρ γνωστον σημειον γεγονεν δι αυτων [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις κατοικουσιν [ιερουσαλημ]{.greek-abbr} φανερον και ου δυναμεθα [αρνησασθαι]{.greek-omitted} [αρνεισασθαι]{.greek-added}[4:16]{.aside}

αλλ ινα μη επι πλειον διανεμηθη εις τον λαον [α]{.greek-added} [απειλη]{.greek-omitted} [[πει]{.unclear}λη]{.greek-added} [απειλησομεθα]{.greek-omitted} [απειλησωμεθα]{.greek-added} αυτοις μηκετι λαλειν επι τω ονοματι τουτω μηδενι [ανθρωπων]{.greek-abbr}[4:17]{.aside}

και καλεσαντες αυτους παρηγγειλαν [αυτοις]{.greek-omitted} το καθολου μη φθεγγεσθαι μηδε διδασκειν επι τω ονοματι του [ιησου]{.greek-abbr}[4:18]{.aside}

ο δε πετρος και ιωαννης αποκριθεντες [ειπον]{.greek-added} προς αυτους [ειπον]{.greek-omitted} ει δικαιον εστιν ενωπιον του [θεου]{.greek-abbr} υμων ακουειν μαλλον η του [θεου]{.greek-abbr} κρινατε[4:19]{.aside}

ου δυναμεθα γαρ ημεις α [ειδομεν]{.greek-omitted} [ειδαμεν]{.greek-added} και ηκουσαμεν μη λαλειν[4:20]{.aside}

οι δε προσαπειλησαμενοι απελυσαν αυτους μηδεν ευρισκοντες το πως [κολασονται]{.greek-omitted} [κολασωνται]{.greek-added} αυτους δια τον λαον οτι παντες εδοξαζον τον [θεον]{.greek-abbr} επι τω γεγονοτι[4:21]{.aside}

ετων γαρ ην πλειονων τεσσαρακοντα ο [ανθρωπος]{.greek-abbr} εφ ον εγεγονει το σημειον τουτο της ιασεως[4:22]{.aside}

απολυθεντες δε ηλθον προς τους ιδιους και απηγγειλαν οσα προς αυτους οι αρχιερεις και οι πρεσβυτεροι ειπον[4:23]{.aside}

οι δε ακουσαντες ομοθυμαδον ηραν φωνην προς τον [θεον]{.greek-abbr} και [ειπον]{.greek-omitted} [ειπαν]{.greek-added} δεσποτα συ ο [θεος]{.greek-abbr} ο ποιησας τον [ουρανον]{.greek-abbr} και την γην και την θαλασσαν και παντα τα εν αυτοις[4:24]{.aside}

ο [του]{.greek-added} [[πατρος]{.greek-abbr}]{.greek-added} [ημων]{.greek-added} δια [[πνευματος]{.greek-abbr}]{.greek-added} [αγιου]{.greek-added} στοματος [δαυιδ]{.greek-abbr} παιδος σου ειπων [ινα]{.greek-omitted} [ινατι]{.greek-added} [τι]{.greek-omitted} εφρυαξαν εθνη και λαοι εμελετησαν κενα[4:25]{.aside}

παρεστησαν οι βασιλεις της γης και οι αρχοντες συνηχθησαν επι το αυτο κατα του [κυριου]{.greek-abbr} και κατα του [χριστου]{.greek-abbr} αυτου[4:26]{.aside}

συνηχθησαν γαρ επ αληθειας [εν]{.greek-added} [τη]{.greek-added} [πολει]{.greek-added} [ταυτη]{.greek-added} επι τον αγιον παιδα σου [ιησουν]{.greek-abbr} ον εχρισας ηρωδης τε και ποντιος πιλατος συν εθνεσιν και λαοις [ισραηλ]{.greek-abbr}[4:27]{.aside}

ποιησαι οσα η χειρ σου και η βουλη σου προωρισεν γενεσθαι[4:28]{.aside}

και τα νυν [κυριε]{.greek-abbr} [επιδε]{.greek-omitted} [εφιδε]{.greek-added} επι τας απειλας αυτων και δος τοις δουλοις σου μετα παρρησιας πασης λαλειν τον λογον σου[4:29]{.aside}

εν τω την χειρα σου εκτεινειν σε εις ιασιν και σημεια και τερατα γινεσθαι δια του ονοματος του αγιου παιδος σου [ιησου]{.greek-abbr}[4:30]{.aside}

και δεηθεντων αυτων εσαλευθη ο τοπος εν ω ησαν συνηγμενοι και επλησθησαν απαντες [του]{.greek-added} [αγιου]{.greek-added} [πνευματος]{.greek-abbr} [αγιου]{.greek-omitted} και ελαλουν τον λογον του [θεου]{.greek-abbr} μετα παρρησιας[4:31]{.aside}

του δε πληθους των πιστευσαντων ην η καρδια και η ψυχη μια και ουδε εις τι των υπαρχοντων [αυτων]{.greek-omitted} [αυτω]{.greek-added} [ελεγεν]{.greek-omitted} [ελεγον]{.greek-added} ιδιον ειναι αλλ ην αυτοις απαντα κοινα[4:32]{.aside}

και μεγαλη δυναμει [απεδιδουν]{.greek-omitted} [απεδιδο[υ]{.unclear}]{.greek-added} το μαρτυριον οι αποστολοι της αναστασεως του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} [[χριστου]{.greek-abbr}]{.greek-added} χαρις τε μεγαλη ην επι παντας αυτους[4:33]{.aside}

ουδε γαρ ενδεης τις [υπηρχεν]{.greek-omitted} [ην]{.greek-added} εν αυτοις οσοι γαρ κτητορες χωριων η οικιων υπηρχον πωλουντες εφερον τας τιμας των πιπρασκομενων[4:34]{.aside}

και ετιθουν παρα τους ποδας των αποστολων [διεδιδοτο]{.greek-omitted} [διεδεδετω]{.greek-added} δε εκαστω καθοτι αν τις χρειαν ειχεν[4:35]{.aside}

ιωσης δε ο επικληθεις βαρναβας [απο]{.greek-omitted} [υπο]{.greek-added} των αποστολων [ο]{.unclear} [εστιν]{.greek-omitted} [εστ[ι]{.greek-supplied}]{.greek-added} μεθερμηνευομενον [υιος]{.greek-abbr} παρακλησεως λευιτης κυπριος τω γενει[4:36]{.aside}

υπαρχοντος αυτ[ω]{.unclear} αγρου πωλησας ηνεγκεν το χρημα και εθηκεν παρα τους ποδας των αποστολων[4:37]{.aside}

### Chapter 5

ανηρ δε τις [ονοματι]{.greek-added} [ανανανας]{.greek-added} [ανανιας]{.corr} [συμ]{.greek-added} [ονοματι]{.greek-omitted} [συν]{.greek-omitted} σαπφειρη τη γυναικι αυτου επωλ[η]{.unclear}σεν κτημα[5:1]{.aside}

και ενοσφισατο απο της τιμης συνειδυιας και τη[ς]{.unclear} γυναικος αυτου και ενεγκας μερος τι παρα τους ποδας των αποστολων εθηκεν[5:2]{.aside}

ειπεν δε [ο]{.greek-added} πετρος ανανια δια τι επληρωσεν ο σατανας την καρδιαν σου ψευσασθαι σε το [πνευμα]{.greek-abbr} το αγιον και νοσφισασθαι [σε]{.greek-omitted} απο της τιμης του χωριου[5:3]{.aside}

ουχι μενον σοι εμενεν και πραθεν εν τη ση εξουσια υπηρχεν τι οτι εθου εν τη καρδια σου το πραγμα τουτο ουκ εψευσω [ανθρωποις]{.greek-abbr} αλλα τω [θεω]{.greek-abbr}[5:4]{.aside}

ακουων δε ο ανανιας τους λογους τουτους πεσων εξεψυξεν και εγενετο φοβος μεγας επι παντας τους ακουοντας ταυτα[5:5]{.aside}

ανασταντες δε οι νεωτεροι συνεστειλαν αυτον και εξενεγκαντες εθαψαν[5:6]{.aside}

εγενετο δε ως ωρων τριων διαστημα και η γυνη αυτου μη ειδυια το [γεγονος]{.greek-omitted} [γεγονως]{.greek-added} εισηλθεν[5:7]{.aside}

απεκριθη δε [προς]{.greek-added} [αυτη]{.greek-omitted} [αυτην]{.greek-added} ο πετρος ειπε μοι ει τοσουτου το χωριον απεδοσθε η δε ειπεν ναι τοσουτου[5:8]{.aside}

ο δε πετρος ειπεν προς αυτην τι οτι συνεφωνηθη υμιν πειρασαι το [πνευμα]{.greek-abbr} [κυριου]{.greek-abbr} ιδου οι ποδες των θαψαντων τον ανδρα σου επι [τη]{.greek-omitted} [της]{.greek-added} [θυρα]{.greek-omitted} [θυρας]{.greek-added} και εξοισουσιν σε[5:9]{.aside}

επεσεν δε παραχρημα παρα τους ποδας αυτου και εξεψυξεν εισελθοντες δε οι νεανισκοι ευρον αυτην νεκραν και εξενεγκαντες εθαψαν προς τον [αν]{.greek-supplied}δρα αυτης[5:10]{.aside}

και εγενετο φοβος μεγας εφ ολην την εκκλησιαν και επι παντας τους ακουοντας ταυτα[5:11]{.aside}

δια δε των χειρων των αποστολων [εγινετο]{.greek-omitted} [εγενοντο]{.greek-added} σημεια και τερατα εν τω λαω πολλα και ησαν [ομοθυ]{.greek-added} [ομοθυμαδον]{.greek-omitted} [απαντες]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [στοα]{.greek-omitted} [σολομωντος]{.greek-omitted}[5:12]{.aside}

### Chapter 6

[τεις]{.greek-added} [συνεκινησαν]{.greek-omitted} [τε]{.greek-omitted} [τον]{.greek-omitted} [λαον]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [πρεσβυτερους]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [γραμματεις]{.greek-omitted} και επισταντες συνηρπασαν αυτον και ηγαγον εις το συνεδριον[6:12]{.aside}

εστησαν τε μαρτυρας ψευδεις λεγοντας ο ανθρωπος ουτος ου παυεται ρηματα βλασφημα λαλων κατα του τοπου του αγιου και του νομου[6:13]{.aside}

ακηκοαμεν γαρ αυτου λεγοντος οτι [ιησους]{.greek-abbr} ο ναζωραιος ουτος καταλυσει τον τοπον τουτον και αλλαξει τα εθη α παρεδωκεν ημιν [μωσης]{.greek-omitted} [μωυσης]{.greek-added}[6:14]{.aside}

και ατενισαντες εις αυτον απαντες οι καθεζομενοι εν τω συνεδριω [ειδον]{.greek-omitted} [ειδαν]{.greek-added} το προσωπον αυτου [ωσει]{.greek-omitted} [ως]{.greek-added} προσωπον αγγελου[6:15]{.aside}

### Chapter 7

ειπεν δε ο αρχιερευς ει αρα ταυτα ουτως εχει[7:1]{.aside}

ο δε εφη ανδρες αδελφοι και [πατερες]{.greek-abbr} ακουσατε ο [θεος]{.greek-abbr} της δοξης ωφθη τω [πατρι]{.greek-abbr} ημων αβρααμ οντι εν τη μεσοποταμια πριν η κατοικησαι αυτον εν χαρραν[7:2]{.aside}

και ειπεν προς αυτον εξελθε εκ της γης σου και εκ της συγγενειας σου και δευρο εις γην ην αν σοι δειξω[7:3]{.aside}

τοτε εξελθων εκ γης χαλδαιων κατωκησεν εν χαρραν κακειθεν μετα το αποθανειν τον [πατερα]{.greek-abbr} αυτου [μετωκισεν]{.greek-omitted} [μετωκησεν]{.greek-added} αυτον εις την γην ταυτην εις ην υμεις νυν κατοικειτε[7:4]{.aside}

και ουκ εδωκεν αυτω κληρονομιαν εν αυτη ουδε βημα ποδος και επηγγειλατο δουναι [αυτω]{.greek-omitted} [αυτην]{.greek-added} εις κατασχεσιν [αυτην]{.greek-omitted} [αυτω]{.greek-added} και τω σπερματι αυτου μετ αυτον ουκ οντος αυτω τεκνου[7:5]{.aside}

ελαλησεν δε ουτως ο [θεος]{.greek-abbr} οτι εσται το σπερμα αυτου παροικον εν γη αλλ[ο]{.unclear}τρια και δουλωσουσιν αυτο και κακωσουσιν ετη τετρα[κο]{.unclear}σια[7:6]{.aside}

και το εθνος [ω]{.greek-omitted} [ο]{.greek-added} εαν δουλ[ε]{.unclear}υσωσιν κριν[ω]{.unclear} εγω [[ει]{.unclear}]{.greek-added} [ειπεν]{.greek-omitted} [πεν]{.greek-added} ο [θεος]{.greek-abbr} και μετα ταυτα εξελευσονται και [λατρευσουσιν]{.greek-omitted} [λατρευσωσιν]{.greek-added} μοι εν τω τοπω τουτω[7:7]{.aside}

και εδωκεν αυτω διαθηκην περιτομης και ουτως εγεννησεν τον ισ[α]{.unclear}ακ και περιετεμεν αυτον τη ημερα τη ογδοη και ο ισαακ τον ιακωβ και ο ιακωβ τους δωδεκα πατριαρχας[7:8]{.aside}

και οι πατριαρχαι ζηλωσαντες τον ιωσηφ απεδοντο εις αιγυπτον και ην ο [θεος]{.greek-abbr} μετ αυτου[7:9]{.aside}

και [εξειλετο]{.greek-omitted} [εξειλατο]{.greek-added} αυτον εκ πασων των θλιψεων αυτου και εδωκεν αυτω χαριν και σοφιαν εναντιον φαραω βασιλεως αιγυπτου και κατεστησεν αυτον ηγουμενον επ αιγυπτον και [εφ]{.greek-added} ολον τον οικον αυτου[7:10]{.aside}

ηλθεν δε λιμος εφ ολην την [γην]{.greek-omitted} [αιγυπτου]{.greek-omitted} [αιγυπτον]{.greek-added} και χανααν και [θλιψις]{.greek-omitted} [θλιψης]{.greek-added} μεγαλη και [ουχ]{.greek-omitted} [ουκ]{.greek-added} [ευρισκον]{.greek-omitted} [ηυρισκον]{.greek-added} [[ηυυρισκον]{.corr}]{.greek-added} χορτασματα οι [πατερες]{.greek-abbr} ημων[7:11]{.aside}

ακουσας δε ιακωβ οντα σιτα εν αιγυπτω εξαπεστειλεν τους [πατερας]{.greek-abbr} ημων πρωτον[7:12]{.aside}

και εν τω δευτερω ανεγνωρισθη ιωσηφ τοις αδελφοις αυτου και φανερον εγενετο τω φαραω το γενος του ιωσηφ[7:13]{.aside}

[αποστειλας]{.greek-omitted} [αποστιλας]{.greek-added} δε ιωσηφ μετεκαλεσατο τον [πατερα]{.greek-abbr} αυτου ιακωβ και πασαν την συγγενειαν [αυτου]{.greek-added} εν [ψυχαις]{.greek-omitted} εβδομηκοντα πεντε [ψυχαις]{.greek-added}[7:14]{.aside}

[και]{.greek-added} κατεβη δε ιακωβ εις αιγυπτον και ετελευτησεν αυτος και οι [πατερες]{.greek-abbr} ημων[7:15]{.aside}

και μετετεθησαν εις συχεμ και ετεθησαν εν τω μνηματι [ο]{.greek-omitted} [ω]{.greek-added} [ωνησατο]{.greek-omitted} [ωνισατο]{.greek-added} αβρααμ τιμης αργυριου παρα των [υιων]{.greek-omitted} [υιον]{.greek-added} εμμορ του συχεμ[7:16]{.aside}

καθως δε ηγγιζεν ο χρονος της επαγγελιας ης ωμοσεν ο [θεος]{.greek-abbr} τω αβρααμ ηυξησεν ο λαος και επληθυνθη εν αιγυπτω[7:17]{.aside}

[αχρι]{.greek-omitted} [αχρις]{.greek-added} ου ανεστη βασιλευς ετερος ος ουκ ηδει τον ιωσηφ[7:18]{.aside}

ουτος κατασοφισαμενος το γενος ημων εκακωσεν τους [πατερας]{.greek-abbr} ημων του ποιειν εκθετα τα βρεφη αυτων εις το μη ζωογονεισθαι[7:19]{.aside}

εν ω καιρω εγεννηθη [μωσης]{.greek-omitted} [μωυσης]{.greek-added} και η[ν]{.unclear} αστειος τω [θεω]{.greek-abbr} ος ανετραφη μηνας τρεις εν τω οικω του [πατρος]{.greek-abbr} [αυτου]{.greek-added}[7:20]{.aside}

εκτεθεντα δε αυτον [ανειλετο]{.greek-omitted} [ανειλατο]{.greek-added} [αυτον]{.greek-added} η θυγατηρ φαραω και ανεθρεψατο αυτον εαυτη εις [υιον]{.greek-abbr}[7:21]{.aside}

και επαιδευθη [μωσης]{.greek-omitted} [μωυσης]{.greek-added} παση σοφια αιγυπτιων ην δε δυνατος εν λογοις και [εν]{.greek-added} εργοις[7:22]{.aside}

ως δε [επληρουτο]{.greek-omitted} [επληρουτω]{.greek-added} αυτω τεσσαρακονταετης χρονος ανεβη επι την καρδιαν αυτου επισκεψασθαι τους αδελφους αυτου τους υιους [ισραηλ]{.greek-abbr}[7:23]{.aside}

και ιδων τινα αδικουμενον ημυνατο και εποιησεν εκδικησιν τω καταπονουμενω παταξας τον αιγυπτιον[7:24]{.aside}

ενομιζεν δε συνιεναι τους αδελφους αυτου οτι ο [θεος]{.greek-abbr} δια χειρος αυτου διδωσιν αυτοις [σωτηριαν]{.greek-abbr} οι δε ου συνηκαν[7:25]{.aside}

τη τε [ημερα]{.greek-added} [τη]{.greek-added} επιουση [ημερα]{.greek-omitted} ωφθη αυτοις μαχομενοις και [συνηλασεν]{.greek-omitted} [συνηλασσεν]{.greek-added} αυτους εις ειρηνην ειπων ανδρες αδελφοι εστε υμεις [ινα]{.greek-omitted} [ινατι]{.greek-added} [τι]{.greek-omitted} [αδικειτε]{.greek-omitted} [αδικητε]{.greek-added} αλληλους[7:26]{.aside}

ο δε αδικων τον πλησιον [απωσατο]{.greek-omitted} [αποσατο]{.greek-added} αυτον ειπων τις σε κατεστησεν αρχοντα και δικαστην εφ [ημας]{.greek-omitted} [ημων]{.greek-added}[7:27]{.aside}

μη ανελειν με συ θελεις ον τροπον ανειλες χθες τον αιγυπτιον[7:28]{.aside}

εφυγεν δε [μωσης]{.greek-omitted} [μωυσης]{.greek-added} εν τω λογω τουτω και εγενετο παροικος εν γη μαδιαμ ου εγεννησεν υιους δυο[7:29]{.aside}

και πληρωθεντων ετων τεσσαρακοντα ωφθη αυτω εν τη ερημω του ορους σινα αγγελος [κυριου]{.greek-abbr} εν φλογι πυρος βατου[7:30]{.aside}

ο δε [μωσης]{.greek-omitted} [μωυσης]{.greek-added} ιδων [εθαυμαζεν]{.greek-omitted} [εθαυμασεν]{.greek-added} το οραμα προσερχομενου δε αυτου κατανοησαι εγενετο φωνη [κυριου]{.greek-abbr} προς αυτον[7:31]{.aside}

εγω ο [θεος]{.greek-abbr} των [πατερων]{.greek-abbr} σου ο [θεος]{.greek-abbr} αβρααμ και ο [θεος]{.greek-abbr} ισαακ και ο [θεος]{.greek-abbr} ιακωβ εντρομος δε γενομενος [μωσης]{.greek-omitted} [μωυσης]{.greek-added} ουκ ετολμα κατανοησαι[7:32]{.aside}

ειπεν δε αυτω ο [κυριος]{.greek-abbr} λυσον το υποδημα των ποδων σου ο γαρ τοπος [εν]{.greek-omitted} [εφ]{.greek-added} ω εστηκας γη αγια εστιν[7:33]{.aside}

ιδων ειδον την κακωσιν του λαου μου του εν αιγυπτω και του στεναγμου αυτων ηκουσα και κατεβην εξελεσθαι αυτους και νυν δευρο [αποστελω]{.greek-omitted} [αποστελλω]{.greek-added} σε εις αιγυπτον[7:34]{.aside}

τουτον τον [μωσην]{.greek-omitted} [μωυσην]{.greek-added} ον ηρνησαντο ειποντες τις σε κατεστησεν αρχοντα και δικαστην [εφ]{.greek-added} [ημων]{.greek-added} τουτον ο [θεος]{.greek-abbr} αρχοντα και λυτρωτην απεστειλεν [εν]{.greek-omitted} [συν]{.greek-added} χειρι αγγελου του οφθεντος αυτω εν τη βατω[7:35]{.aside}

ουτος εξηγαγεν αυτους ποιησας τερατα και σημεια εν γη αιγυπτω και εν ερυθρα θαλασση και εν τη ερημω ετη τεσσαρακοντα[7:36]{.aside}

ουτος εστιν ο μωσης ο ειπων τοις υιοις [ισραηλ]{.greek-abbr} προφητην υμιν αναστησει [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} [ημων]{.greek-omitted} εκ των αδελφων υμων ως εμε [αυτου]{.greek-added} [ακουσεσθε]{.greek-added}[7:37]{.aside}

ουτος εστιν ο γενομενος εν τη εκκλησια εν τη ερημω μετα του αγγελου του λαλουντος αυτω εν τω ορει σινα και των [πατερων]{.greek-abbr} ημων ος εδεξατο [λογον]{.greek-omitted} [λογια]{.greek-added} ζωντα δουναι ημιν[7:38]{.aside}

ω ουκ ηθελησαν υπηκοοι γενεσθαι οι [πατερες]{.greek-abbr} ημων [αλλ]{.greek-omitted} [αλλα]{.greek-added} απωσαντο και εστραφησαν τη καρδια αυτων εις αιγυπτον[7:39]{.aside}

[ειποντες]{.greek-omitted} [ειπον]{.greek-added} [τες]{.greek-added} τω ααρων ποιησον ημιν θεους οι προπορευσονται ημων ο γαρ [μωσης]{.greek-omitted} [μωυσης]{.greek-added} ουτος ος εξηγαγεν ημας εκ γης αιγυπτου ουκ οιδαμεν τι γεγονεν αυτω[7:40]{.aside}

και εμοσχοποιησαν εν ταις ημεραις εκειναις και ανηγαγον θυσιαν τω [ειδωλω]{.greek-omitted} [ειδολω]{.greek-added} και [ευφραινοντο]{.greek-omitted} [ηυφραινοντο]{.greek-added} [[και]{.corr}]{.greek-added} [[φραινοντο]{.corr}]{.greek-added} εν τοις εργοις των χειρων αυτων[7:41]{.aside}

εστρεψεν δε ο [θεος]{.greek-abbr} και παρεδωκεν αυτους λατρευειν τη στρατια του [ουρανου]{.greek-abbr} καθως γεγραπται εν βιβλω των προφητων μη σφαγια [και]{.greek-omitted} [η]{.greek-added} θυσιας προσηνεγκατε μοι ετη τεσσαρακοντα εν τη ερημω οικος [ισραηλ]{.greek-abbr}[7:42]{.aside}

και ανελαβετε την σκηνην του [μολοχ]{.greek-omitted} [μολωχ]{.greek-added} [[μολωχε]{.corr}]{.greek-added} και το αστρον του [θεου]{.greek-abbr} υμων [ρεμφαν]{.greek-omitted} [ρεφφαν]{.greek-added} τους τυπους ους εποιησατε προσκυνειν [εν]{.greek-added} αυτοις και μετοικιω υμας επεκεινα βαβυλωνος[7:43]{.aside}

η σκηνη του μαρτυριου ην τοις πατρασιν ημων εν τη ερημω καθως διεταξατο ο λαλων τω [μωση]{.greek-omitted} [μωυσει]{.greek-added} ποιησαι αυτην κατα τον τυπον ον [εωρακει]{.greek-omitted} [εωρακεν]{.greek-added}[7:44]{.aside}

ην και εισηγαγον διαδεξαμενοι οι [πατερες]{.greek-abbr} ημων μετα [ιησου]{.greek-abbr} εν τη κατασχεσει των εθνων ων εξωσεν ο [θεος]{.greek-abbr} απο προσωπου των [πατερων]{.greek-abbr} ημων εως των ημερων [δαυιδ]{.greek-abbr}[7:45]{.aside}

ος ευρεν χαριν ενωπιον του [θεου]{.greek-abbr} και ητησατο ευρειν σκηνωμα τω [θεω]{.greek-abbr} ιακωβ[7:46]{.aside}

σολομων δε ωκοδομησεν [αυτω]{.greek-omitted} [εαυτω]{.greek-added} οικον[7:47]{.aside}

αλλ ουχ ο υψιστος εν χειροποιητοις ναοις κατοικει καθως ο προφητης λεγει[7:48]{.aside}

ο [ουρανος]{.greek-abbr} μοι θρονος η δε γη υποποδιον των ποδων μου ποιον οικον [οικοδομησετε]{.greek-omitted} [οικοδομησεται]{.greek-added} μοι λεγει [κυριος]{.greek-abbr} η τις τοπος της καταπαυσεω[ς]{.unclear} [μου]{.unclear}[7:49]{.aside}

ουχι η χειρ μου εποιησεν [παντα]{.greek-added} ταυτα [παντα]{.greek-omitted}[7:50]{.aside}

σκληροτραχηλοι και απεριτμητοι τη καρδια και τοις ωσιν υμεις [αει]{.greek-omitted} τω [πνευματι]{.greek-abbr} τω αγιω [αει]{.greek-added} αντιπιπτετε ως οι [πατερες]{.greek-abbr} υμων και υμεις[7:51]{.aside}

τινα των προφητων ουκ εδιωξαν οι [πατερες]{.greek-abbr} υμων και απεκτειναν τους προκαταγγειλαντας περι της ελευσεως του δικαιου ου νυν υμεις [προδοται]{.greek-omitted} [προδοτε]{.greek-added} και φονεις [γεγενησθε]{.greek-omitted} [εγενεσθε]{.greek-added}[7:52]{.aside}

οιτινες ελαβετε τον νομον εις διαταγας αγγελων και ουκ εφυλαξατε[7:53]{.aside}

ακουοντες δε ταυτα διεπριοντο ταις καρδιαις αυτων και εβ[ρ]{.unclear}υχον τους οδοντας επ αυτον[7:54]{.aside}

υπαρχων δε πληρης [πνευματος]{.greek-abbr} αγιου ατενισας εις τον [ουρανον]{.greek-abbr} [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} δοξαν [θεου]{.greek-abbr} και [ιησουν]{.greek-abbr} εστωτα εκ δεξ[ι]{.unclear}ων του [θεου]{.greek-abbr}[7:55]{.aside}

και ειπεν ιδου [θεωρω]{.greek-omitted} [θεορον]{.greek-added} τους [[ουρανους]{.greek-abbr}]{.greek-added} [ουρανους]{.corr} ανεωγμενους και τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εκ δεξιων εστωτα του [θεου]{.greek-abbr}[7:56]{.aside}

κραξαντες δε φωνη μεγαλη [συνεσχον]{.greek-omitted} [συνεσχων]{.greek-added} τα ωτα αυτων και ωρμησαν ομοθυμαδον επ αυτον[7:57]{.aside}

και εκβαλοντες εξω της πολεως ελιθοβολουν και οι μαρτυρες απεθεντο τα ιματια [αυτων]{.greek-added} παρα τους ποδας νεανιου καλουμενου σαυλου[7:58]{.aside}

και ελιθοβολουν τον στεφανον επικαλουμενον και λεγοντα [κυριε]{.greek-abbr} [ιησου]{.greek-abbr} δεξαι το [πνευμα]{.greek-abbr} μου[7:59]{.aside}

θεις δε τα γονατα εκραξεν φωνη μεγαλη [κυριε]{.greek-abbr} μη στησης αυτοις την αμαρτιαν ταυτην και τουτο ειπων εκοιμηθη[7:60]{.aside}

### Chapter 8

[σαυλος]{.greek-omitted} [παυλος]{.greek-added} δε ην συνε[υ]{.unclear}δοκων τη αναιρεσει [αυτου]{.greek-omitted} [στεφανου]{.greek-added} εγενετο δε εν εκεινη τη ημερα διωγμος μεγας επι την εκκλησιαν την εν ιεροσολυμοις παντες δε διεσπαρησαν [κατα]{.greek-omitted} [κα]{.greek-added} [τα]{.greek-added} τας [χωρας]{.greek-omitted} [πολεις]{.greek-added} της ιουδαιας και σαμαρειας πλην των αποστολων[8:1]{.aside}

[συνεκομισαν]{.greek-omitted} [συνεκομησαν]{.greek-added} δε τον στεφανον ανδρες ευλαβεις και εποιησαντο κοπετον μεγαν επ αυτω[8:2]{.aside}

σαυλος δε ελυμαινετο την εκκλησιαν κατα τους οικους εισπορευομενος συρων τε ανδρας και γυναικας παρεδιδου εις φυλακην[8:3]{.aside}

οι μεν ουν διασπαρεντ[ες]{.unclear} [διηλθον]{.greek-omitted} [ηλθον]{.greek-added} ευαγγελιζομενοι τον λογον[8:4]{.aside}

φιλιππος δε κατελθων εις πολιν της σαμαρειας εκηρυσσεν αυτοις τον [χριστον]{.greek-abbr}[8:5]{.aside}

προσειχον [τε]{.greek-omitted} [δε]{.greek-added} οι οχλοι τοις λεγομενοις υπο [του]{.greek-omitted} φιλιππου ομοθυμαδον εν τω ακουειν αυτους και βλεπειν τα σημεια α εποιει[8:6]{.aside}

πολλων γαρ των εχοντων [πνευματα]{.greek-abbr} ακαθαρτα βοωντα φωνη μεγαλη [εξηρχετο]{.greek-omitted} [εξηρχοντο]{.greek-added} πολλοι δε [και]{.greek-added} παραλελυμενοι και χωλοι εθεραπευθησαν[8:7]{.aside}

και εγενετο χαρα μεγαλη εν τη πολει εκεινη[8:8]{.aside}

ανηρ δε τις ονοματι σιμων προυπηρχεν εν τη πολει μαγευων και εξιστων το εθνος της σαμαρειας λεγων ειναι τινα εαυτον μεγαν[8:9]{.aside}

ω προσειχον [παντες]{.greek-added} απο μικρου εως μεγαλου λεγοντες ουτος εστιν η δυναμις του [θεου]{.greek-abbr} η [καλουμενη]{.greek-added} μεγαλη[8:10]{.aside}

προσειχον δε αυτω δια [το]{.greek-omitted} [τω]{.greek-added} ικανω χρονω ταις [μαγειαις]{.greek-omitted} [μαγιαις]{.greek-added} [εξεστακεναι]{.greek-omitted} [εξιστακεναι]{.greek-added} αυτους[8:11]{.aside}

οτε δε επιστευσαν τω φιλιππω ευαγγελιζομενω [τα]{.greek-omitted} περι της βασιλειας του [θεου]{.greek-abbr} και του ονοματος [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} εβαπτιζοντο ανδρες τε και γυναικες[8:12]{.aside}

ο δε σιμων και αυτος επιστευσεν και βαπτισθεις ην προσκαρτερων τω φιλιππω θεωρων [τε]{.greek-omitted} δυναμεις [[μεγα]{.greek-supplied}]{.greek-added} [λας]{.greek-added} και σημεια [γινομενα]{.greek-omitted} [γενωμενα]{.greek-added} εξιστατο[8:13]{.aside}

ακουσαντες δε οι εν ιεροσολυμοις αποστολοι οτι δεδεκται η σαμαρεια τον λογον του [θεου]{.greek-abbr} απεστειλαν προς αυτους τον πετρον και ιωαννην[8:14]{.aside}

οιτινες καταβαντες προσηυξαντο περι αυτων οπως λαβωσιν [πνευμα]{.greek-abbr} αγιον[8:15]{.aside}

[ουπω]{.greek-omitted} [ουδεπω]{.greek-added} γαρ ην επ ουδενι αυτων επιπεπτωκος μονον δε [βεβαπτισμενοι]{.greek-omitted} [βαπτιζομενοι]{.greek-added} υπηρχον εις το ονομα του [[κυριου]{.greek-abbr}]{.greek-added} [ημων]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} [χριστου]{.greek-abbr} [ιησου]{.greek-omitted}[8:16]{.aside}

τοτε [επετιθουν]{.greek-omitted} [επετιθοσαν]{.greek-added} τας χειρας επ αυτους και ελαμβανον [πνευμα]{.greek-abbr} αγιον[8:17]{.aside}

θεασαμενος δε ο σιμων οτι δια της επιθεσεως των χειρων των αποστολων διδοται το [πνευμα]{.greek-abbr} το αγιον προσηνεγκεν αυτοις χρηματα[8:18]{.aside}

λεγων δοτε καμοι την εξουσιαν ταυτην ινα ω εαν επιθω τας χειρας λαμβανη [πνευμα]{.greek-abbr} αγιον[8:19]{.aside}

πετρος δε ειπεν προς αυτον το αργυριον σου συν σοι ειη εις απωλειαν οτι την δωρεαν του [θεου]{.greek-abbr} [ενομισας]{.greek-omitted} [ενωμησας]{.greek-added} [δι[―]{.gap}]{.greek-added} [δια]{.corr} χρηματων κτασθαι[8:20]{.aside}

ουκ εστιν σοι μερις ουδε κληρος εν τω λογω τουτω η γαρ καρδια σου ουκ εστιν ευθεια ενωπιον του [θεου]{.greek-abbr}[8:21]{.aside}

μετανοησον ουν απο της κακιας σου ταυτης και δεηθητι του [θεου]{.greek-abbr} ει αρα αφεθησεται σοι η επινοια της καρδιας σου[8:22]{.aside}

εις γαρ χολην πικριας και [εις]{.greek-added} συνδεσμον αδικιας ορω σε οντα[8:23]{.aside}

αποκριθεις δε ο σιμων ειπεν δεηθητε υμεις υπερ εμου προς τον [κυριον]{.greek-abbr} οπως μηδεν επελθη επ εμε ων ειρηκατε[8:24]{.aside}

οι μεν ουν διαμαρτυραμενοι και λαλησαντες τον λογον του [κυριου]{.greek-abbr} υπεστρεψαν εις [ιερουσαλημ]{.greek-omitted} [ιερου]{.greek-added} [σαλημ]{.greek-added} πολλας τε κωμας των [σαμαρειτων]{.greek-omitted} [σαμαριτων]{.greek-added} ευηγγελισαντο[8:25]{.aside}

αγγελος δε [κυριου]{.greek-abbr} ελαλησεν προς φιλιππον λεγων αναστηθι και πορευου κατα μεσημβριαν επι την οδον την καταβαινουσαν απο [ιερουσαλημ]{.greek-abbr} εις γαζαν αυτη εστιν ερημος[8:26]{.aside}

και αναστας επορευθη και ιδου ανηρ [αιθιοψ]{.greek-omitted} [αιθιωψ]{.greek-added} ευνουχος δυναστης κανδακης [της]{.greek-omitted} βασιλισσης αιθιοπων ος ην επι πασης της γαζης αυτης ος [εληλυθει]{.greek-omitted} [εληλυθεν]{.greek-added} προσκυνησων εις [ιερουσαλημ]{.greek-abbr}[8:27]{.aside}

ην τε υποστρεφων και καθημενος επι του αρματος αυτου [και]{.greek-omitted} ανεγινωσκεν τον προφητην ησαιαν[8:28]{.aside}

ειπεν δε το [πνευμα]{.greek-abbr} τω φιλιππω προσελθε και κολληθητι τω αρματι τουτω[8:29]{.aside}

προσδραμων δε ο φιλιππος ηκουσεν αυτου αναγινωσκοντος τον προφητην ησαιαν και ειπεν αρα γε γινωσκεις α αναγινωσκεις[8:30]{.aside}

ο δε ειπεν πως γαρ αν δυναιμην εαν μη τις οδηγηση με παρεκαλεσεν τε τον φιλιππον αναβαντα καθισαι συν αυτω[8:31]{.aside}

η δε περιοχη [της]{.greek-omitted} [γραφης]{.greek-omitted} ην ανεγινωσκεν ην αυτη ως προβατον επι σφαγην ηχθη και ως αμνος εναντιον του [κειροντος]{.greek-omitted} [κειραντος]{.greek-added} αυτον αφωνος ουτως ουκ ανοιγει το στομα αυτου[8:32]{.aside}

εν τη ταπεινωσει αυτου η κρισις αυτου ηρθη την δε γενεαν αυτου τις διηγησεται οτι αιρεται απο της γης η ζωη αυτου[8:33]{.aside}

αποκριθεις δε ο ευνουχος τω φιλιππω ειπεν δεομαι σου πε[ρ]{.unclear}ι τινος ο προφητης λεγει τουτο περι εαυτου η περι ετερου τινος[8:34]{.aside}

ανοιξας δε ο φιλιππος το στομα αυτου και αρξαμενος απο της γραφης ταυτης ευηγγελισατο αυτω τον [ιησουν]{.greek-abbr}[8:35]{.aside}

ως δε επορευοντο κατα την οδον ηλθον επι τι υδωρ και φησιν ο ευνουχος ιδου υδωρ τι κωλυει με βαπτισθηναι[8:36]{.aside}

[ειπεν]{.greek-added} [δε]{.greek-added} [αυτω]{.greek-added} [ει]{.greek-added} [πιστευεις]{.greek-added} [εξ]{.greek-added} [ολης]{.greek-added} [της]{.greek-added} [καρδιας]{.greek-added} [σου]{.greek-added} [εξεστιν]{.greek-added} [αποκριθεις]{.greek-added} [δε]{.greek-added} [ο]{.greek-added} [ευνουχος]{.greek-added} [ειπεν]{.greek-added} [αυτω]{.greek-added} [πιστευω]{.greek-added} [τον]{.greek-added} [[υιον]{.greek-abbr}]{.greek-added} [του]{.greek-added} [[θεου]{.greek-abbr}]{.greek-added} [ειναι]{.greek-added} [[ιησουν]{.greek-abbr}]{.greek-added} [[χριστον]{.greek-abbr}]{.greek-added}[8:37]{.aside}

και εκελευσεν στηναι το αρμα και κατεβησαν [αμφοτεροι]{.greek-omitted} εις το υδωρ [αμφοτεροι]{.greek-added} ο τε φιλιππος και ο ευνουχος και εβαπτισεν αυτον[8:38]{.aside}

οτε δε ανεβησαν [εκ]{.greek-omitted} [απο]{.greek-added} του υδατος [πνευμα]{.greek-abbr} [[θεου]{.greek-abbr}]{.greek-added} [επεπεσεν]{.greek-added} [επι]{.greek-added} [τον]{.greek-added} [ευνουχον]{.greek-added} [αγγελος]{.greek-added} [δε]{.greek-added} [κυριου]{.greek-abbr} ηρπασεν τον φιλιππον και ουκ [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} αυτον ουκετι ο ευνουχος επορευετο γαρ την οδον αυτου χαιρων[8:39]{.aside}

φιλιππος δε ευρεθη εις αζωτον και διερχομενος ευηγγελιζετο τας πολεις πασας εως του ελθειν αυτον εις καισαρειαν[8:40]{.aside}

### Chapter 9

ο δε σαυλος ετι εμπνεων απειλης και φονου εις τους μαθητας του [κυριου]{.greek-abbr} προσελθων τω αρχιερει[9:1]{.aside}

ητησατο παρ αυτου επιστολας εις [δασμακον]{.greek-added} [δαμασκον]{.corr} προς τας συναγωγας οπως εαν τινας ευρη της οδου οντας ανδρας τε και γυναικας δεδεμενους [αγαγη]{.greek-omitted} [αγαγει]{.greek-added} εις [ιερουσαλημ]{.greek-abbr}[9:2]{.aside}

εν δε [τω]{.greek-omitted} [το]{.greek-added} πορευεσθαι [αυτον]{.greek-added} εγενετο αυτον εγγιζειν τη δαμασκω και [εξαιφνης]{.greek-omitted} [εξεφνης]{.greek-added} περιηστραψεν αυτον φως απο του [ουρανου]{.greek-abbr}[9:3]{.aside}

και πεσων επι την γην ηκουσεν φωνην λεγουσαν αυτω σαουλ σαουλ τι με διωκεις[9:4]{.aside}

ειπεν δε τις ει [κυριε]{.greek-abbr} ο δε [κυριος]{.greek-abbr} ειπεν εγω ειμι [ιησους]{.greek-abbr} [ο]{.greek-added} [ναζωραιος]{.greek-added} ον συ διωκεις[9:5]{.aside}

αλλα αναστηθι και εισελθε εις την πολιν και [εκει]{.greek-added} λαληθησεται σοι [ο]{.greek-added} τι σε δει ποιειν[9:6]{.aside}

οι δε ανδρες οι συνοδευοντες αυτω [ειστηκεισαν]{.greek-omitted} [ιστηκησαν]{.greek-added} ενεοι ακουοντες μεν της φωνης μηδενα δε θεωρουντες[9:7]{.aside}

ηγερθη δε ο σαυλος απο της γης [ανεωγμενων]{.greek-omitted} [ηνεωγμενων]{.greek-added} [τε]{.greek-omitted} [δε]{.greek-added} των οφθαλμων αυτου ουδενα εβλεπεν χειραγωγουντες δε αυτον εισηγαγον εις δαμασκον[9:8]{.aside}

και ην ημερας τρεις μη βλεπων και ουκ εφαγ[ε]{.unclear}ν ουδε επιεν[9:9]{.aside}

ην δε τις μαθητης εν δαμασκω ονοματι ανανιας και ειπεν προς αυτον [εν]{.greek-added} [οραματι]{.greek-added} ο [κυριος]{.greek-abbr} [εν]{.greek-omitted} [οραματι]{.greek-omitted} ανανια ο δε ειπεν ιδου εγω [κυριε]{.greek-abbr}[9:10]{.aside}

ο δε [κυριος]{.greek-abbr} προς αυτον αναστας πορευθητι επι την ρυμην την καλουμενην ευθειαν και ζητησον εν οικια ιουδα σαυλον ονοματι ταρσεα ιδου γαρ προσευχεται[9:11]{.aside}

και [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} εν οραματι [ανδρα]{.greek-omitted} [ονοματι]{.greek-omitted} ανανιαν εισελθοντα και επιθεντα αυτω χειρα οπως αναβλεψη[9:12]{.aside}

απεκριθη δε ανανιας [και]{.greek-added} [ειπεν]{.greek-added} [κυριε]{.greek-abbr} ακηκοα απο πολλων περι του ανδρος τουτου οσα κακα εποιησεν τοις αγιοις σου εν [ιερουσαλημ]{.greek-abbr}[9:13]{.aside}

και ωδε εχει εξουσιαν παρα των αρχιερεων δησαι παντας τους επικαλουμενους το ονομα σου[9:14]{.aside}

ειπεν δε προς αυτον ο [κυριος]{.greek-abbr} πορευου οτι σκευος εκλογης [εστιν]{.greek-added} μοι [εστιν]{.greek-omitted} ουτος του βαστασαι το ονομα μου ενωπιον εθνων και βασιλεων υιων τε [ισραηλ]{.greek-abbr}[9:15]{.aside}

εγω γαρ υποδειξω αυτω οσα δει αυτον υπερ του ονοματος μου παθειν[9:16]{.aside}

απηλθεν δε ανανιας και εισηλθεν εις την οικιαν [ιουδα]{.greek-added} και επιθεις επ αυτον τας χειρας ειπεν σαουλ αδελφε ο [κυριος]{.greek-abbr} [απε]{.greek-added} [απεσταλκεν]{.greek-omitted} [σταλκεν]{.greek-added} με [[ιησους]{.greek-abbr}]{.greek-added} ο [οφθεις]{.greek-omitted} [ωφθεις]{.greek-added} σοι εν τη οδω η ηρχου οπως αναβλεψης και [πλησθης]{.greek-omitted} [πλησθεις]{.greek-added} [πνευματος]{.greek-abbr} αγιου[9:17]{.aside}

και ευθεως [απεπεσον]{.greek-omitted} [απεπεσαν]{.greek-added} απο των οφθαλμων αυτου ωσει λεπιδες ανεβλεψεν τε [παραχρημα]{.greek-added} και αναστας εβαπτισθη[9:18]{.aside}

και λαβων τροφην ενισχυσεν εγενετο δε ο σαυλος μετα των εν δαμασκω μαθητων ημερας τινας[9:19]{.aside}

και ευθεως εν ταις συναγωγαις εκηρυσσεν τον [χριστον]{.greek-abbr} οτι ουτος εστιν ο [υιος]{.greek-abbr} του [θεου]{.greek-abbr}[9:20]{.aside}

εξισταντο δε παντες οι ακουοντες και ελεγον ουχ ουτος εστιν ο πορθησας εν [ιερουσαλημ]{.greek-abbr} τους επικαλουμενους το ονομα τουτο και ωδε εις τουτο εληλυθεν ινα δεδεμενους αυτους αγαγη επι τους αρχιερεις[9:21]{.aside}

σαυλος δε μαλλον ενεδυναμουτο και [συνεχυνεν]{.greek-omitted} [συνεχεεν]{.greek-added} τους ιουδαιους τους κατοικουντας εν δαμασκω συμβιβαζων οτι ουτος εστιν ο [χριστος]{.greek-abbr}[9:22]{.aside}

ως δε επληρουντο ημεραι ικαναι συνεβουλευσαντο οι ιουδαιοι ανελειν αυτον[9:23]{.aside}

εγνωσθη δε τω σαυλω η επιβουλη αυτων παρετηρουν [τε]{.greek-omitted} [δε]{.greek-added} τας πυλας ημερας [τε]{.greek-omitted} και νυκτος οπως αυτον ανελωσιν[9:24]{.aside}

λαβοντες δε αυτον οι μαθηται νυκτος [καθηκαν]{.greek-omitted} [καθεικαν]{.greek-added} δια του τειχους χαλασαντες εν σπυριδι[9:25]{.aside}

παραγενομενος δε ο σαυλος εν [ιερουσαλημ]{.greek-abbr} επειρατο κολλασθαι τοις μαθηταις και παντες εφοβουντο αυτον μη πιστευοντες οτι εστιν μαθητης[9:26]{.aside}

βαρναβας δε επιλαβομενος αυτον ηγαγεν προς τους αποστολους και διηγησατο αυτοις πως εν τη οδω ειδεν τον [κυριον]{.greek-abbr} και οτι ελαλησεν αυτω και πως εν δαμασκω επαρρησιασατο εν τω ονοματι του [ιησου]{.greek-abbr}[9:27]{.aside}

και ην μετ αυτων εισπορευομενος [και]{.greek-added} [εκπορευομενο[ς]{.unclear}]{.greek-added} εις [ιερουσαλημ]{.greek-abbr} και παρρησιαζομενος εν τω ονοματι του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr}[9:28]{.aside}

ελαλει τε και συνεζητει προς τους ελληνιστας οι δε επεχειρουν αυτον ανελειν[9:29]{.aside}

επιγνοντες δε οι αδελφοι κατηγαγον αυτον εις καισαρειαν και εξαπεστειλαν αυτον εις ταρσον[9:30]{.aside}

αι μεν ουν εκκλησιαι καθ ολης της ιουδαιας και γαλιλαιας και [σαμαρειας]{.greek-omitted} [σαμαριας]{.greek-added} ειχον ειρηνην οικοδομουμεναι και πορευομεναι τω φοβω του [κυριου]{.greek-abbr} και τη παρακλησει του αγιου [πνευματος]{.greek-abbr} επληθυνοντο[9:31]{.aside}

εγενετο δε πετρον διερχομενον δια παντων κατελθειν και προς τους αγιους τους κατοικουντας λυδδαν[9:32]{.aside}

ευρεν δε εκει [ανθρωπον]{.greek-abbr} τινα [ονοματι]{.greek-added} αινεαν [ονοματι]{.greek-omitted} εξ ετων οκτω κατακειμενον επι [κραββατω]{.greek-omitted} [κραβαττω]{.greek-added} ος ην παραλελυμενος[9:33]{.aside}

και ειπεν αυτω [ο]{.greek-omitted} πετρος αινεα ιαται σε [ιησους]{.greek-abbr} ο [χριστος]{.greek-abbr} αναστηθι και στρωσον σεαυτω και ευθεως ανεστη[9:34]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} αυτον παντες οι κατοικουντες λυδδαν και τον ασσαρωνα οιτινες επεστρεψαν επι τον [κυριον]{.greek-abbr}[9:35]{.aside}

εν ιοππη δε τις ην μαθητρια ονοματι ταβηθα η διερμηνευομενη λεγεται δορκας αυτη ην πληρης αγαθων εργων και ελεημοσυνων ων εποιει[9:36]{.aside}

εγενετο δε εν ταις ημεραις εκειναις ασθενησασαν αυτην αποθανειν λουσαντες δε αυτην εθηκαν εν υπερωω[9:37]{.aside}

εγγυς δε ουσης λυδδης τη ιοππη οι μαθηται ακουσαντες οτι πετρος εστιν εν αυτη απεστειλαν [δυο]{.greek-added} [ανδρας]{.greek-added} προς αυτον παρακαλουντες μη οκνησαι διελθειν εως [αυτων]{.greek-omitted} [ημων]{.greek-added}[9:38]{.aside}

αναστας δε πετρος συνηλθεν αυτοις ον παραγενομενον ανηγαγον εις το υπερωον και [παρεστησαν]{.greek-omitted} [περιεστησαν]{.greek-added} αυτω πασαι αι χηραι κλαιουσαι και επιδεικνυμεναι χιτωνας και ιματια οσα εποιει μετ αυ[τ]{.unclear}ων ουσα η δορκας[9:39]{.aside}

εκβαλων δε [παντας]{.greek-added} εξω [παντας]{.greek-omitted} ο πετρος [και]{.greek-added} θεις τα γονατα προσηυξατο και επιστρεψας προς το σωμα ειπεν ταβηθα αναστηθι η δε [ηνοιξεν]{.greek-omitted} [ηνυξεν]{.greek-added} τους οφθαλμους αυτης και ιδουσα τον πετρον ανεκαθισεν[9:40]{.aside}

δους δε αυτη χειρα ανεστησεν αυτην φωνησας [δε]{.greek-omitted} [τε]{.greek-added} τους αγιους και τας χηρας παρεστησεν αυτην ζωσαν[9:41]{.aside}

γνωστον δε εγενετο καθ ολης της ιοππης και πολλοι επιστευσαν επι τον [κυριον]{.greek-abbr}[9:42]{.aside}

εγενετο δε ημερας ικανας μειναι αυτον εν [ιοππη]{.greek-omitted} [ιοππι]{.greek-added} παρα τινι σιμωνι βυρσ[ει]{.unclear}[9:43]{.aside}

### Chapter 10

ανηρ δε τις ην εν καισαρεια ονοματι κορνηλιος εκατονταρχης εκ σπειρης της καλουμενης ιταλικης[10:1]{.aside}

ευσεβης και φοβουμενος τον [θεον]{.greek-abbr} συν παντι τω οικω αυτου ποιων τε ελεημοσυνας πολλας τω λαω και δεομενος του [θεου]{.greek-abbr} δια παντος[10:2]{.aside}

ειδεν εν οραματι φανερως ωσει ωραν ενατην της ημερας αγγελον του [θεου]{.greek-abbr} εισελθοντα προς αυτον και ειποντα αυτω κορνηλιε[10:3]{.aside}

ο δε ατενισας αυτω και εμφοβος γενομενος ειπεν τι [εστιν]{.greek-omitted} [εστι]{.greek-added} [κυριε]{.greek-abbr} ειπεν δε αυτω αι προσευχαι σου και [αι]{.greek-omitted} ελεημοσυναι σου ανεβησαν εις μνημοσυνον ενωπιον του [θεου]{.greek-abbr}[10:4]{.aside}

και νυν πεμψον εις ιοππην ανδρας και μεταπεμψαι σιμωνα [τινα]{.greek-added} τον επικαλουμενον πετρον[10:5]{.aside}

[και]{.greek-added} [ουτος]{.greek-omitted} [αυτο[ς]{.unclear}]{.greek-added} [ξενιζεται]{.greek-omitted} [εστι]{.greek-added} [ξενιζομενος]{.greek-added} παρα [τινι]{.greek-omitted} [τι]{.greek-added} [νι]{.greek-added} σιμωνι βυρσει ω εστιν οικια παρα θαλασσαν [ος]{.greek-added} [λαλησει]{.greek-added} [ρηματα]{.greek-added} [προς]{.greek-added} [σε]{.greek-added} [εν]{.greek-added} [οις]{.greek-added} [σωθηση]{.greek-added} [συ]{.greek-added} [και]{.greek-added} [πας]{.greek-added} [ο]{.greek-added} [οικος]{.greek-added} [σου]{.greek-added}[10:6]{.aside}

ως δε απηλθεν ο αγγελος ο λαλων τω κορνηλιω φωνησας δυο των οικετων αυτου και στρατιωτην ευσεβη των προσκαρτερουντων αυτω[10:7]{.aside}

και εξηγησαμενος αυτοις απαντα απεστειλεν αυτους εις την ιοππην[10:8]{.aside}

τη δε επαυριον [οδοιπορουντων]{.greek-omitted} [οδυπορουντων]{.greek-added} εκεινων και τη πολει εγγιζοντων ανεβη πετρος επι το δωμα [προσευξασθαι]{.greek-omitted} [προσευξα[θαι]{.greek-supplied}]{.greek-added} [[προσευξα]{.corr}]{.greek-added} [[ω]{.corr}]{.greek-added} [[και]{.corr}]{.greek-added} περι ωραν εκτην[10:9]{.aside}

εγενετο δε [προσπεινος]{.greek-omitted} [προσπινος]{.greek-added} και ηθελεν γευσασθαι παρασκευαζοντων δε εκεινων επεπεσεν επ αυτον εκστασις[10:10]{.aside}

και θεωρει τον [ουρανον]{.greek-abbr} ανεωγμενον και καταβαινον επ αυτον σκευος τι ως οθονην μεγαλην τεσσαρσιν αρχαις δεδεμενον και καθιεμενον επι της γης[10:11]{.aside}

εν [ω]{.unclear} υπηρχεν παντα τα τετραποδα της γης και τα θηρια και τα ερπετα και τα πετεινα του [ουρανου]{.greek-abbr}[10:12]{.aside}

και εγενετο φωνη προς αυτον αναστα[ς]{.unclear} πετρε θυσον και φαγε[10:13]{.aside}

ο δε πετρος ειπεν μηδαμως [κυριε]{.greek-abbr} οτι ουδεποτε εφαγον παν κοινον η ακαθαρτον[10:14]{.aside}

και φωνη παλιν εκ δευτερου προς αυτον α ο [θεος]{.greek-abbr} [εκαθαρισεν]{.greek-omitted} [εκαθαιρισεν]{.greek-added} συ μη κοινου[10:15]{.aside}

τουτο δε εγενετο επι τρις και [παλιν]{.greek-omitted} [ευθυς]{.greek-added} ανεληφθη το σκευος εις τον [ουρανον]{.greek-abbr}[10:16]{.aside}

ως δε εν εαυτω διηπορει ο πετρος τι αν ειη το οραμα ο ειδεν και [ιδου]{.greek-omitted} [οιδου]{.greek-added} οι ανδρες οι [απετ[―]{.gap}οι]{.greek-added} [απεστ[α]{.unclear}λ[μεν]{.unclear}οι]{.corr} [απο]{.greek-omitted} [υπο]{.greek-added} του κορνηλιου διερωτησαντες την οικιαν σιμ[ω]{.unclear}νος επεσ[τ]{.unclear}ησαν επι τον πυλωνα[10:17]{.aside}

και φωνησαν[τ]{.unclear}ες επυνθαν[ον]{.unclear}τ[ο]{.unclear} [ει]{.unclear} σιμ[ω]{.unclear}ν ο [[ε]{.unclear}]{.greek-added} [επικαλουμενος]{.greek-omitted} [πικαλουμενος]{.greek-added} πετρος ενθαδε ξενιζεται[10:18]{.aside}

του δε πετρου διενθυμουμενου περι του οραματος ειπεν αυτω το [πνευμα]{.greek-abbr} ιδου ανδρες [τρεις]{.greek-added} ζητουσιν σε[10:19]{.aside}

αλλα αναστας καταβηθι και πορευου συν αυτοις μηδεν διακρινομενος διοτι εγω απεσταλκα αυτους[10:20]{.aside}

καταβας δε πετρος προς τους ανδρας [τους]{.greek-added} [απεσταλμενους]{.greek-added} [υπο]{.greek-added} [κορνηλιου]{.greek-added} ειπεν ιδου εγω ειμι ον ζητειτε τις η αιτια δι ην παρεστε[10:21]{.aside}

οι δε ειπον κορνηλιος εκατονταρχης ανηρ δικαιος και φοβουμενος τον [θεον]{.greek-abbr} μαρτυρουμενος [τε]{.greek-omitted} υπο ολου του εθνους των ιουδαιων εχρηματισθη υπο αγγελου αγιου μεταπεμψασθαι σε εις τον οικον αυτου και ακουσαι ρηματα παρα σου[10:22]{.aside}

εισκαλεσαμενος [ο]{.unclear}υν αυτους εξενισεν τη δε επαυριον [αναστας]{.greek-added} ο πετρος εξηλθεν συν αυτοις και τινες των αδελφων των απο ιοππης συνηλθον αυτω[10:23]{.aside}

και τη επαυριον εισηλθον εις την καισαρειαν ο δε κορνηλιος ην προσδοκων αυτους συγκαλεσαμενος τους συγγενεις αυτου και τους αναγκαιους φιλους[10:24]{.aside}

ως δε εγενετο του εισελθειν τον πετρον συναντησας αυτω ο κορνηλιος πεσων επι τους ποδας προσεκυνησεν[10:25]{.aside}

ο δε πετρος [ηγειρεν]{.greek-added} αυτον [ηγειρεν]{.greek-omitted} λεγων αναστηθι [καγω]{.greek-omitted} [και]{.greek-added} [γαρ]{.greek-added} αυτος [εγω]{.greek-added} [ανθρωπος]{.greek-abbr} ειμι[10:26]{.aside}

και συνομιλων αυτω εισηλθεν και ευρισκει συνεληλυθοτας πολλους[10:27]{.aside}

εφη τε προς αυτους υμεις επιστασθε ως [αθεμιτον]{.greek-omitted} [αθεμητον]{.greek-added} εστιν ανδρι ιουδαιω κολλασθαι η προσερχεσθαι αλλοφυλω και εμοι ο [θεος]{.greek-abbr} εδειξεν μηδενα κοινον η ακαθαρτον λεγειν [ανθρωπον]{.greek-abbr}[10:28]{.aside}

διο και [αναντιρρητως]{.greek-omitted} [αναντηρρητως]{.greek-added} [ηλ]{.greek-added} [ηλθον]{.greek-omitted} [θον]{.greek-added} μεταπεμφθεις πυνθανομαι ουν τινι λογω μετεπεμψασθε με[10:29]{.aside}

και ο κορνηλιος εφη απο τεταρτης ημερας μεχρι ταυτης της ωρας ημην νηστευων και την [ενατην]{.greek-omitted} [εννατην]{.greek-added} ωραν προσευχομενος εν τω οικω μου και ιδου ανηρ εστη ενωπιον μου εν εσθητι λαμπρα[10:30]{.aside}

και φησιν κορνηλιε εισηκουσθη σου η προσευχη και αι ελεημοσυναι σου εμνησθησαν ενωπιον του [θεου]{.greek-abbr}[10:31]{.aside}

πεμψον ουν εις ιοππην και μετακαλεσαι σιμωνα ος επικαλειται πετρος ουτος ξενιζεται εν οικια σιμωνος βυρσεως παρα θαλασσαν ος [παραγενομενος]{.greek-omitted} [παραγεναμενος]{.greek-added} λαλησει σοι[10:32]{.aside}

εξαυτης ουν επεμψα προς σε συ τε καλως εποιησας παραγενομενος νυν ουν παντες ημεις ενωπιον του [θεου]{.greek-abbr} παρεσμεν ακουσαι παντα τα προστεταγμενα σοι υπο του [θεου]{.greek-abbr}[10:33]{.aside}

ανοιξας δε πετρος το στομα [αυτου]{.greek-added} ειπεν επ αληθειας καταλαμβανομαι οτι ουκ εστιν προσωποληπτης ο [θεος]{.greek-abbr}[10:34]{.aside}

αλλ εν παντι εθνει ο φοβουμενος αυτον και εργαζομενος δικαιοσυνην δεκτος αυτω εστιν[10:35]{.aside}

τον λογον ον απεστειλεν τοις υιοις [ισραηλ]{.greek-abbr} ευαγγελιζομενος ειρηνην δια [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} ουτος εστιν [ο]{.greek-added} παντων [κυριος]{.greek-abbr}[10:36]{.aside}

υμεις οιδατε το γενομενον ρημα καθ ολης της ιουδαιας αρξαμενον απο της γαλιλαιας μετα το βαπτισμα ο εκηρυξεν ιωαννης[10:37]{.aside}

[ιησουν]{.greek-abbr} τον απο [ναζαρετ]{.greek-omitted} [ναζαρεθ]{.greek-added} ως εχρισεν αυτον ο [θεος]{.greek-abbr} [πνευματι]{.greek-abbr} αγιω και δυναμει ος διηλθεν ευεργετων και ιωμενος παντας τους καταδυναστευομενους υπο του διαβολου οτι ο [θεος]{.greek-abbr} ην μετ αυτου[10:38]{.aside}

και ημεις εσμεν μαρτυρες παντων ων εποιησεν εν τε τη χωρα των ιουδαιων και εν [ιερουσαλημ]{.greek-abbr} ον και [ανειλον]{.greek-omitted} [ανειλαν]{.greek-added} κρεμασαντες επι ξυλου[10:39]{.aside}

τουτον ο [θεος]{.greek-abbr} ηγειρεν τη τριτη ημερα και εδωκεν αυτον εμφανη γενεσθαι[10:40]{.aside}

ου παντι τω λαω αλλα μαρτυσιν τοις προκεχειροτονημενοις υπο του [θεου]{.greek-abbr} ημιν οιτινες συνεφαγομεν και συνεπιομεν αυτω μετα το αναστηναι αυτον εκ νεκρων[10:41]{.aside}

και παρηγγειλεν ημιν κηρυξαι τω λαω και διαμαρτυρασθαι οτι [αυτος]{.greek-omitted} [ουτος]{.greek-added} εστιν ο [ωρισμενος]{.greek-omitted} [ορισμενος]{.greek-added} υπο του [θεου]{.greek-abbr} κριτης ζωντων και νεκρων[10:42]{.aside}

τουτω παντες οι προφηται μαρτυρουσιν αφεσιν αμαρτιων λαβειν δια του ονοματος αυτου παντα τον πιστευοντα εις αυτον[10:43]{.aside}

ετι λαλουντος του πετρου τα ρηματα ταυτα επεπεσεν το [πνευμα]{.greek-abbr} το αγιον επι παντας τους ακουοντας τον λογον[10:44]{.aside}

και εξεστησαν οι εκ περιτομης πιστοι οσοι συνηλθον τω πετρω [λεγοντες]{.greek-added} οτι και επι τα εθνη η δωρεα του αγιου [πνευματος]{.greek-abbr} εκκεχυται[10:45]{.aside}

ηκουον γαρ αυτων λαλουντων γλωσσαις και μεγαλυνοντων τον [θεον]{.greek-abbr} τοτε απεκριθη ο πετρος[10:46]{.aside}

μητι το υδωρ [κωλυσαι]{.greek-omitted} [κολυσαι]{.greek-added} δυναται τις του μη βαπτισθηναι τουτους οιτινες το [πνευμα]{.greek-abbr} το αγιον ελαβον καθως και ημεις[10:47]{.aside}

προσεταξεν [τε]{.greek-omitted} [δε]{.greek-added} αυτους βαπτισθηναι εν τω ονοματι [του]{.greek-omitted} [κυριου]{.greek-omitted} [[ιησου]{.greek-abbr}]{.greek-added} [[χριστου]{.greek-abbr}]{.greek-added} τοτε ηρωτησαν αυτον επιμειναι ημερας τινας[10:48]{.aside}

### Chapter 11

ηκουσαν δε οι αποστολοι και οι αδελφοι οι οντες κατα την ιουδαιαν οτι και τα εθνη εδεξαντο τον λογον του [θεου]{.greek-abbr}[11:1]{.aside}

[και]{.greek-omitted} οτε [δε]{.greek-added} ανεβη πετρος εις [ιεροσολυμα]{.greek-omitted} [[ιερουσαλημ]{.greek-abbr}]{.greek-added} διεκρινοντο προς αυτον οι εκ περιτομης[11:2]{.aside}

λεγοντες οτι προς ανδρας ακροβυστιαν εχοντας εισηλθες και συνεφαγες αυτοις[11:3]{.aside}

αρξαμενος δε ο πετρος εξετιθετο αυτοις καθεξης λεγων[11:4]{.aside}

εγω ημην εν πολει ιοππη προσευχομενος και ειδον εν εκστασει οραμα καταβαινον σκευος τι ως οθονην μεγαλην τεσσαρσιν αρχαις καθιεμενην εκ του [ουρανου]{.greek-abbr} και ηλθεν [αχρι]{.greek-omitted} [αχρις]{.greek-added} εμου[11:5]{.aside}

εις ην ατενισας κατενοουν και ειδον τα τετραποδα της γης και τα θηρια και τα ερπετα και τα πετεινα του [ουρανου]{.greek-abbr}[11:6]{.aside}

ηκουσα δε [και]{.greek-added} φωνης λεγουσης μοι αναστας πετρε θυσον και φαγε[11:7]{.aside}

ειπον δε μηδαμως [κυριε]{.greek-abbr} οτι παν κοινον η ακαθαρτον ουδεποτε εισηλθεν εις το στομα μου[11:8]{.aside}

απεκριθη δε μοι [φωνη]{.greek-omitted} εκ δευτερου [φωνη]{.greek-added} εκ του [ουρανου]{.greek-abbr} α ο [θεος]{.greek-abbr} [εκαθαρισεν]{.greek-omitted} [εκαθαιρισεν]{.greek-added} συ μη κοινου[11:9]{.aside}

τουτο δε εγενετο επι τρις και παλιν ανεσπασθη απαντα εις τον [ουρανον]{.greek-abbr}[11:10]{.aside}

και ιδου εξαυτης τρεις ανδρες επεστησαν επι την οικιαν εν η ημην απεσταλμενοι [υπο]{.greek-added} [κορνηλιου]{.greek-added} απο καισαρειας προς με[11:11]{.aside}

ειπεν δε μοι το [πνευμα]{.greek-abbr} συνελθειν αυτοις μηδεν διακρινομενον ηλθον δε συν εμοι και οι εξ αδελφοι [ο]{.unclear}υτοι και εισηλθομεν εις τον οικον του ανδρος[11:12]{.aside}

απηγγειλεν [τε]{.greek-omitted} [δε]{.greek-added} ημιν πως [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} [τον]{.greek-omitted} αγγελον [εισελθοντα]{.greek-added} εν τω οικω αυτου [σταθεντα]{.greek-omitted} και ειποντα αυτω αποστειλον εις ιοππην ανδρας και μεταπεμψαι σιμωνα τον επικαλουμενον πετρον[11:13]{.aside}

ος λαλησει ρηματα προς σε εν οις σωθηση συ και πας ο οικος σου[11:14]{.aside}

εν δε τω αρξασθαι με λαλειν επεπεσεν το [πνευμα]{.greek-abbr} το αγιον επ αυτους ωσπερ και εφ ημας εν αρχη[11:15]{.aside}

εμνησθην δε του ρηματος [του]{.greek-added} [κυριου]{.greek-abbr} ως ελεγεν ιωαννης μεν εβαπτισεν υδατι υμεις δε βαπτισθησεσθε εν [πνευματι]{.greek-abbr} αγιω[11:16]{.aside}

ει ουν την ισην δωρεαν εδωκεν αυτοις ο [θεος]{.greek-abbr} ως και ημιν πιστευσασιν επι τον [κυριον]{.greek-abbr} [ιησουν]{.greek-abbr} [χριστον]{.greek-abbr} εγω [δε]{.greek-omitted} τις ημην δυνατος κωλυσαι τον [θεον]{.greek-abbr}[11:17]{.aside}

ακουσαντες δε ταυτα ησυχασαν και [εδοξαζον]{.greek-omitted} [εδοξασαν]{.greek-added} τον [θεον]{.greek-abbr} λεγοντες αρα γε και τοις εθνεσιν ο [θεος]{.greek-abbr} την μετανοιαν εδωκεν εις ζωην[11:18]{.aside}

οι μεν ουν διασπαρεντες απο της θλιψεως της [γενομενης]{.greek-omitted} [γεναμενης]{.greek-added} επι στεφανω διηλθον εως φοινικης και κυπρου και αντιοχειας μηδενι λαλουντες τον λογον ει μη [μονον]{.greek-omitted} [μονοις]{.greek-added} ιουδαιοις[11:19]{.aside}

ησαν δε τινες εξ αυτων ανδρες κυπριοι και [κυρηναιοι]{.greek-omitted} [κυριναιοι]{.greek-added} οιτινες εισελθοντες εις αντιοχειαν ελαλουν προς τους ελληνιστας ευαγγελιζομενοι τον [κυριον]{.greek-abbr} [ιησουν]{.greek-abbr}[11:20]{.aside}

και ην χειρ [κυριου]{.greek-abbr} μετ αυτων πολυς τε αριθμος πιστευσας επεστρεψεν επι τον [κυριον]{.greek-abbr}[11:21]{.aside}

ηκουσθη δε ο λογος εις τα ωτα της εκκλησιας της [ουσης]{.greek-added} εν [ιεροσολυμοις]{.greek-omitted} [[ιερουσαλημ]{.greek-abbr}]{.greek-added} [τα]{.greek-added} περι αυτων και εξαπεστειλαν βαρναβαν διελθειν εως αντιοχειας[11:22]{.aside}

ος παραγενομενος και ιδων την χαριν του [θεου]{.greek-abbr} εχαρη και [παρεκαλει]{.greek-omitted} [παρεκαλη]{.greek-added} παντας τη προθεσει της καρδιας [προσμενειν]{.greek-omitted} [προσμενην]{.greek-added} τω [κυριω]{.greek-abbr}[11:23]{.aside}

οτι ην ανηρ αγαθος και πληρης [πνευματος]{.greek-abbr} αγιου και πιστεως και προσετεθη οχλος ικανος τω [κυριω]{.greek-abbr}[11:24]{.aside}

εξηλθεν [δ]{.greek-supplied}[ε]{.unclear} εις ταρσον ο βαρναβας αναζητησαι σαυλον[11:25]{.aside}

και ευρων [αυτον]{.greek-added} ηγαγεν αυτον εις αντιοχειαν εγενετο δε [αυτους]{.greek-omitted} [αυτοις]{.greek-added} ενιαυτον ολον συναχθηναι [εν]{.greek-added} τη εκκλησια και διδαξαι οχλον ικανον χρηματισαι τε πρωτον εν αντιοχεια τους μαθητας χριστιανους[11:26]{.aside}

εν ταυταις δε ταις ημεραις κατηλθον απο ιεροσολυμων προφηται εις αντιοχειαν[11:27]{.aside}

αναστας δε εις εξ αυτων ονοματι αγαβος εσημανεν δια του [πνευματος]{.greek-abbr} λιμον μεγαν μελλειν εσεσθαι εφ ολην την οικουμενην οστις και εγενετο επι κλαυδιου καισαρος[11:28]{.aside}

των δε μαθητων καθως ευπορειτο τις ωρισαν εκαστος αυτων εις διακονιαν πεμψαι τοις κατοικουσιν εν τη ιουδαια αδελφοις[11:29]{.aside}

[ο]{.greek-omitted} [οι]{.greek-added} και εποιησαν αποστειλαντες προς τους πρεσβυτερους δια χειρος βαρναβα και σαυλου[11:30]{.aside}

### Chapter 12

κατ εκεινον δε τον καιρον επεβαλεν ηρωδης ο βασιλευς τας χειρας κακωσαι τινας των απο της εκκλησιας[12:1]{.aside}

ανειλεν δε ιακωβον τον αδελφον ιωαννου μαχαιρα[12:2]{.aside}

[και]{.greek-omitted} ιδων [δε]{.greek-added} οτι αρεστον [εστιν]{.greek-omitted} [εστι]{.greek-added} τοις ιουδαιοις προσεθετο συλλαβειν και πετρον ησαν δε αι ημεραι των αζυμων[12:3]{.aside}

ον και πιασας εθετο εις φυλακην παραδους [τεσσαρσιν]{.greek-omitted} [τεσσαρσι]{.greek-added} τετραδιοις στρατιωτων φυλασσειν αυτον βουλομενος μετα το πασχα αναγαγειν αυτον τω λαω[12:4]{.aside}

ο μεν ουν πετρος ετηρειτο εν τη φυλακη προσευχη δε ην εκτενης γινομενη υπο της εκκλησιας προς τον [θεον]{.greek-abbr} υπερ αυτου[12:5]{.aside}

οτε δε [εμελλεν]{.greek-omitted} [ημελλεν]{.greek-added} [προαγειν]{.greek-added} αυτον [προαγειν]{.greek-omitted} ο ηρωδης τη νυκτι εκεινη ην ο πετρος κοιμωμενος μεταξυ δυο στρατιωτων δεδεμενος αλυσεσιν δυσιν φυλακες τε προ της θυρας ετηρουν την φυλακην[12:6]{.aside}

και ιδου αγγελος [κυριου]{.greek-abbr} επεστη και φως ελαμψεν εν τω οικηματι παταξας δε την πλευραν του πετρου ηγειρεν αυτον λεγων αναστα εν ταχει και [εξεπεσον]{.greek-omitted} [εξεπεσαν]{.greek-added} αυτου αι αλυσεις εκ των χειρων[12:7]{.aside}

ειπεν [τε]{.greek-omitted} [δε]{.greek-added} ο αγγελος προς αυτον [περιζωσαι]{.greek-omitted} [ζωσαι]{.greek-added} και υποδησαι τα σανδαλια σου εποιησεν δε ουτως και λεγει αυτω περιβαλου το ιματιον σου και ακολουθει μοι[12:8]{.aside}

και εξελθων [ηκολουθει]{.greek-omitted} [ηκολουθη]{.greek-added} αυτω και ουκ ηδει οτι αληθες εστιν το γινομενον δια του αγγελου εδοκει δε οραμα βλεπειν[12:9]{.aside}

διελθοντες δε πρωτην φυλακην και δευτεραν ηλθον επι την πυλην την σιδηραν την φερουσαν [εις]{.greek-omitted} [επι]{.greek-added} την πολιν ητις [αυτοματη]{.greek-omitted} [αυτοματι]{.greek-added} [ηνοιχθη]{.greek-omitted} [ηνοιγη]{.greek-added} αυτοις και εξελθοντες προηλθον ρυμην μιαν και ευθεως απεστη ο αγγελος απ αυτου[12:10]{.aside}

και ο πετρος γενομενος εν εαυτω ειπεν νυν οιδα [οτι]{.greek-added} αληθως [οτι]{.greek-omitted} εξαπεστειλεν [ο]{.greek-added} [κυριος]{.greek-abbr} τον αγγελον αυτου και εξειλετο με εκ χειρος ηρωδου και πα[σης]{.unclear} της προσδοκιας [τ]{.greek-supplied}[ου]{.unclear} λαου των ιουδαιων[12:11]{.aside}

[συνιδων]{.greek-omitted} [συ[ν]{.greek-supplied}[ειδω]{.unclear}ν]{.greek-added} τε [η]{.unclear}λθεν επι τ[η]{.unclear}[ν]{.greek-supplied} [οι]{.greek-supplied}κιαν [μ]{.greek-supplied}αριας της [μητρος]{.greek-abbr} ιωαννου του επικαλουμενου μαρκου ου ησαν ικανοι συνηθροισμενοι και προσευχομενοι[12:12]{.aside}

κρουσαντος δε του πετρου την θυραν του πυλωνος προσηλθεν παιδισκη [υπα]{.greek-added} [υπακουσαι]{.greek-omitted} [κουσαι]{.greek-added} ονοματι ροδη[12:13]{.aside}

και επιγνουσα την φωνην του πετρου απο της χαρας ουκ ηνοιξεν τον πυλωνα εισδραμουσα δε απηγγειλεν εσταναι τον πετρον προ του πυλωνος[12:14]{.aside}

οι δε προς αυτην [ειπον]{.greek-omitted} [ειπαν]{.greek-added} [μαινη]{.greek-omitted} [μαινει]{.greek-added} η δε διισχυριζετο ουτως εχειν οι δε ελεγον ο αγγελος αυτου εστιν[12:15]{.aside}

ο δε πετρος επεμενεν κρουων ανοιξαντες δε [ειδον]{.greek-omitted} [ιδον]{.greek-added} αυτον και εξεστησαν[12:16]{.aside}

κατασεισας δε αυτοις τη χειρι σιγαν διηγησατο αυτοις πως ο [κυριος]{.greek-abbr} αυτον εξη[γ]{.unclear}[αγεν]{.greek-supplied} εκ της φυλακης ειπεν [δε]{.greek-omitted} [[τε]{.unclear}]{.greek-added} απαγγειλατε [ιακ]{.unclear}[ωβ]{.greek-supplied}[ω]{.unclear} [κ]{.greek-supplied}αι τοις αδελφοις ταυτα και εξελθων επορευθη εις ετερον τοπον[12:17]{.aside}

γενομενης δε ημερας ην ταραχος ουκ ολιγος εν τοις στρατιωταις τι αρα ο πετρος εγενετο[12:18]{.aside}

ηρωδης δε επιζητησας αυτον και μη ευρων ανακρινας τους φυλακας εκελευσεν απαχθηναι [και]{.greek-omitted} [κατελθων]{.greek-omitted} [κατελθον]{.greek-added} [δε]{.greek-added} απο τη[ς]{.unclear} ιουδαιας εις [την]{.greek-omitted} καισαρειαν διετριβεν[12:19]{.aside}

ην δε ο ηρωδης θυμομαχων τυριοις και [σιδωνιοις]{.greek-omitted} [σιδονιοις]{.greek-added} ομοθυμαδον δε παρησαν προς αυτον και πεισαντες βλαστον τον επι του κοιτωνος του βασιλεως ητουντο ειρηνην δια το τρεφεσθαι αυτων την χωραν απο της βασιλικης[12:20]{.aside}

τακτη δε ημερα ο ηρωδης ενδυσαμενος [εσθητα]{.greek-omitted} [αισθητα]{.greek-added} βασιλικην και [καθισας]{.greek-omitted} [καθησας]{.greek-added} επι του βηματος [εδημηγορει]{.greek-omitted} [εδημιγορει]{.greek-added} προς αυτους[12:21]{.aside}

ο δε δημος επεφωνει [[θεου]{.greek-abbr}]{.greek-added} φωνη [θεου]{.greek-omitted} και ουκ [ανθρωπου]{.greek-abbr}[12:22]{.aside}

παραχρημα δε επαταξεν αυτον αγγελος [κυριου]{.greek-abbr} ανθ ων ουκ εδωκεν δοξαν τω [θεω]{.greek-abbr} και γενομενος σκωληκοβρωτος εξεψυξεν[12:23]{.aside}

ο δε λογος του [θεου]{.greek-abbr} ηυξανεν και επληθυνετο[12:24]{.aside}

βαρναβας δε και σαυλος υπεστρεψαν [εις]{.greek-omitted} [απο]{.greek-added} [ιερουσαλημ]{.greek-abbr} πληρωσαντες την διακονιαν [συμπαραλαβοντες]{.greek-omitted} [συνπαραλαβοντες]{.greek-added} και ιωαννην τον επικληθεντα μαρκον[12:25]{.aside}

### Chapter 13

ησαν δε [τινες]{.greek-omitted} εν αντιοχεια κατα την ουσαν εκκλησιαν προφηται και διδασκαλοι ο τε βαρναβας και συμεων ο καλουμενος [νιγερ]{.greek-omitted} [νηγερ]{.greek-added} και λουκιος ο [κυρηναιος]{.greek-omitted} [κυριναιος]{.greek-added} μαναην τε ηρωδου του τετραρχου συντροφος και σαυλος[13:1]{.aside}

λειτουργουντων δε αυτων τω [κυριω]{.greek-abbr} και νηστευοντων ειπεν το [πνευμα]{.greek-abbr} το αγιον [αφορισατε]{.greek-omitted} [αφορησατε]{.greek-added} δη μοι τον βαρναβαν και [τον]{.greek-omitted} σαυλον εις το εργον ο προσκεκλημαι αυτους[13:2]{.aside}

τοτε νηστευσαντες και προσευξαμενοι και επιθεντες τας χειρας αυτοις απελυσαν[13:3]{.aside}

ουτοι μεν ουν εκπεμφθεντες υπο του [πνευματος]{.greek-abbr} του αγιου κατηλθον εις την σελευκειαν εκειθεν [δε]{.greek-omitted} [τε]{.greek-added} απεπλευσαν εις την κυπρον[13:4]{.aside}

και γενομενοι εν [σαλαμινι]{.greek-omitted} [σαλαμινη]{.greek-added} [κατηγγελλον]{.greek-omitted} [κατηγγελον]{.greek-added} τον λογον του [θεου]{.greek-abbr} εν ταις συναγωγαις των ιουδαιων ειχον δε και ιωαννην υπηρετην[13:5]{.aside}

διελθοντες δε [ολην]{.greek-added} την νησον αχρι παφου ευρον [ανδρα]{.greek-added} τινα μαγον ψευδοπροφητην ιουδαιον ω ονομα [βαριησους]{.greek-omitted} [βαριυσουν]{.greek-added}[13:6]{.aside}

ος ην συν τω ανθυπατω σεργιω παυλω ανδρι συνετω ουτος προσκαλεσαμενος βαρναβαν και σαυλον επεζητησεν ακουσαι τον λογον του [θεου]{.greek-abbr}[13:7]{.aside}

ανθιστατο δε αυτοις ελυμας ο μαγος ουτως γαρ μεθερμηνευεται το ονομα αυτου ζητων διαστρεψαι τον ανθυπατον απο της πιστεως[13:8]{.aside}

σαυλος δε ο και παυλος πλησθεις [πνευματος]{.greek-abbr} αγιου και ατενισας εις αυτον[13:9]{.aside}

ειπεν ω πληρης παντος δολου και πασης ραδιουργιας υιε διαβολου εχθρε πασης δικαιοσυνης ου παυση διαστρεφων τας οδους [κυριου]{.greek-abbr} τας ευθειας[13:10]{.aside}

και [νυν]{.greek-omitted} ιδου χειρ [κυριου]{.greek-abbr} επι σε και εση τυφλος μη βλεπων [τον]{.greek-omitted} ηλιον αχρι καιρου παραχρημα δε επεπεσεν επ αυτον αχλυς και σκοτος και περιαγων [εζητει]{.greek-omitted} [εζητη]{.greek-added} χειραγωγους[13:11]{.aside}

τοτε ιδων ο ανθυπατος το γεγονος επιστευσεν εκπλησσομενος επι τη διδαχη του [κυριου]{.greek-abbr}[13:12]{.aside}

αναχθεντες δε απο της παφου οι περι τον παυλον ηλθον εις περγην της παμφυλιας ιωαννης δε [αποχωρησας]{.greek-omitted} [αναχωρησας]{.greek-added} απ αυτων υπεστρεψεν εις ιεροσολυμα[13:13]{.aside}

αυτοι δε διελθοντες απο της περγης παρεγενοντο εις αντιοχειαν της πισιδιας και εισελθοντες εις την συναγωγην τη ημερα των σαββατων εκαθισαν[13:14]{.aside}

μετα δε την αναγνωσιν του νομου και των προφητων απεστειλαν οι αρχισυναγωγοι προς αυτους λεγοντες ανδρες αδελφοι ει [εστιν]{.greek-omitted} [εστι]{.greek-added} λογος εν υμιν παρακλησεως προς τον λαον λεγετε[13:15]{.aside}

αναστας δε παυλος και κατασεισας τη χειρι ειπεν ανδρες ισραηλιται και οι φοβουμενοι τον [θεον]{.greek-abbr} ακουσατε[13:16]{.aside}

ο [θεος]{.greek-abbr} του λαου τουτου εξελεξατο τους [πατερας]{.greek-abbr} ημων και τον λαον υψωσεν εν τη παροικια εν γη αιγυπτω και μετα βραχιονος υψηλου εξηγαγεν αυτους εξ αυτης[13:17]{.aside}

και ως τεσσαρακονταετη χρονον [ετροποφορησεν]{.greek-omitted} [ετροφοφορησεν]{.greek-added} αυτους εν τη ερημω[13:18]{.aside}

και καθελων εθνη επτα εν γη χανααν κατεκληρονομησεν αυτοις την γην αυτων[13:19]{.aside}

και μετα ταυτα ως [ετεσιν]{.greek-omitted} [ετεσι]{.greek-added} τετρακοσιοις και πεντηκοντα εδωκεν κριτας εως σαμουηλ του προφητου[13:20]{.aside}

κακειθεν ητησαντο βασιλεα και εδωκεν αυτοις ο [θεος]{.greek-abbr} τον σαουλ υιον κις ανδρα εκ φυλης [βενιαμιν]{.greek-omitted} [βενιαμην]{.greek-added} ετη τεσσαρακοντα[13:21]{.aside}

και μεταστησας αυτον ηγειρεν αυτοις τον [δαυιδ]{.greek-abbr} εις βασιλεα ω και ειπεν μαρτυρησας ευρον [δαυιδ]{.greek-abbr} τον του ιεσσαι ανδρα κατα την καρδιαν μου ος ποιησει παντα τα θεληματα μου[13:22]{.aside}

τουτου ο [θεος]{.greek-abbr} απο του σπερματος κατ επαγγελιαν [ηγαγεν]{.greek-omitted} [ηγειρεν]{.greek-added} [[σωτηρα]{.greek-abbr}]{.greek-added} [[ιησουν]{.greek-abbr}]{.greek-added} τω [ισραηλ]{.greek-abbr} [σωτηριαν]{.greek-omitted}[13:23]{.aside}

προκηρυξαντος ιωαννου προ προσωπου της εισοδου αυτου βαπτισμα μετανοιας [παντι]{.greek-added} τω [λαω]{.greek-added} [ισραηλ]{.greek-abbr}[13:24]{.aside}

ως δε επληρου [ο]{.greek-omitted} ιωαννης τον δρομον ελεγεν τινα με υπονοειτε ειναι ουκ ειμι εγω αλλ ιδου ερχεται μετ εμε ου ουκ ειμι αξιος το υποδημα των ποδων λυσαι[13:25]{.aside}

ανδρες αδελφοι υιοι γενους αβρααμ και οι εν υμιν φοβουμενοι τον [θεον]{.greek-abbr} υμιν ο λογος της [σωτηριας]{.greek-abbr} ταυτης [απεσταλη]{.greek-omitted} [εξαπεσταλη]{.greek-added}[13:26]{.aside}

οι γαρ κατοικουντες [εν]{.greek-omitted} [ιερουσαλημ]{.greek-abbr} και οι αρχοντες αυτων τουτον αγνοησαντες και τας φωνας των προφητων τας κατα παν σαββατον αναγινωσκομενας κριναντες επληρωσαν[13:27]{.aside}

και μηδεμιαν αιτιαν θανατου ευροντες ητησαντο πιλατον αναιρεθηναι αυτον[13:28]{.aside}

ως δε [ετελεσαν]{.greek-omitted} [ετελε]{.greek-added} [σαν]{.greek-added} παντα τα περι αυτου γεγραμμενα καθελοντες απο του ξυλου εθηκαν εις [μνημειον]{.greek-omitted} [μνημειων]{.greek-added}[13:29]{.aside}

ο δε [θεος]{.greek-abbr} ηγειρεν αυτον εκ νεκρων[13:30]{.aside}

ος ωφθη επι ημερας πλειους τοις συναναβασιν αυτω απο της γαλιλαιας εις [ιερουσαλημ]{.greek-abbr} οιτινες [νυν]{.greek-added} [εισιν]{.greek-omitted} [εισι]{.greek-added} μαρτυρες αυτου προς τον λαον[13:31]{.aside}

και ημεις υμας ευαγγελιζομεθα την προς τους [πατερας]{.greek-abbr} επαγγελιαν γενομενην [οτι]{.greek-omitted} [ταυτην]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [εκπεπληρωκεν]{.greek-omitted} [τοις]{.greek-omitted} [τεκνοις]{.greek-omitted} [αυτων]{.greek-omitted} [ημιν]{.greek-omitted} [αναστησας]{.greek-omitted} [ιησουν]{.greek-omitted}[13:32]{.aside}

[οτι]{.greek-added} [ταυτην]{.greek-added} [ο]{.greek-added} [[θεος]{.greek-abbr}]{.greek-added} [εκπεπληρωκεν]{.greek-added} [τοις]{.greek-added} [τεκνοις]{.greek-added} [αυτων]{.greek-added} [ημιν]{.greek-added} [αναστησας]{.greek-added} [[ιησουν]{.greek-abbr}]{.greek-added} ως και εν τω ψαλμω τω δευτερω γεγραπται [υιος]{.greek-abbr} μου ει συ εγω σημερον γεγεννηκα σε[13:33]{.aside}

οτι δε [αυτον]{.greek-added} ανεστησεν [αυτον]{.greek-omitted} εκ νεκρων μηκετι μελλοντα [υποστρεφειν]{.greek-omitted} [αυτον]{.greek-added} [αναστρεφειν]{.greek-added} εις διαφθοραν ουτως ειρηκεν οτι [δωσω]{.greek-omitted} [δοσω]{.greek-added} υμιν τα οσια [δαυιδ]{.greek-abbr} τα πιστα[13:34]{.aside}

διο και εν ετερω λεγει ου δωσεις τον οσιον σου ιδειν διαφθοραν[13:35]{.aside}

[δαυιδ]{.greek-abbr} μεν γαρ ιδια γενεα υπηρετησας τη του [θεου]{.greek-abbr} βουλη εκοιμηθη και προσετεθη προς τους [πατερας]{.greek-abbr} αυτου και ειδεν διαφθοραν[13:36]{.aside}

ον δε ο [θεος]{.greek-abbr} ηγειρεν ουκ ειδεν διαφθοραν[13:37]{.aside}

γνωστον ουν [υμιν]{.greek-added} εστω [υμιν]{.greek-omitted} ανδρες αδελφοι οτι δια τουτου υμιν αφεσις αμαρτιων καταγγελλεται [και]{.greek-added} [απο]{.greek-added} [παντων]{.greek-added} [ων]{.greek-added} [ουκ]{.greek-added} [εδυνηθητε]{.greek-added} [εν]{.greek-added} [τω]{.greek-added} [νομω]{.greek-added} [μωσεως]{.greek-added} [δικαιωθηναι]{.greek-added}[13:38]{.aside}

[και]{.greek-omitted} [απο]{.greek-omitted} [παντων]{.greek-omitted} [ων]{.greek-omitted} [ουκ]{.greek-omitted} [ηδυνηθητε]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [νομω]{.greek-omitted} [μωυσεως]{.greek-omitted} [δικαιωθηναι]{.greek-omitted} εν τουτω πας ο πιστευων δικαιουται[13:39]{.aside}

βλεπετε ουν [μη]{.greek-omitted} [επελθη]{.greek-omitted} [εφ]{.greek-omitted} [υμας]{.greek-omitted} το ειρημενον εν τοις προφηταις [μη]{.greek-added} [επελθη]{.greek-added} [εφ]{.greek-added} [υμας]{.greek-added}[13:40]{.aside}

ιδετε οι καταφρονηται [και]{.greek-added} [επιβλεψατε]{.greek-added} και θαυμασατε και αφανισθητε οτι εργον [εγω]{.greek-omitted} εργαζομαι εν ταις ημεραις υμων [εργον]{.greek-added} ο ου μη πιστε[υ]{.unclear}σητε εαν τις [εκδιηγηται]{.greek-omitted} [εκδιηγειται]{.greek-added} υμιν[13:41]{.aside}

εξιοντων δε [εκ]{.greek-omitted} [της]{.greek-omitted} [συναγωγης]{.greek-omitted} [των]{.greek-omitted} [αυτων]{.greek-added} [ιουδαιων]{.greek-omitted} παρεκαλουν [τα]{.greek-omitted} [εθνη]{.greek-omitted} εις το μεταξυ σαββατον λαληθηναι αυτοις τα ρηματα [ταυτα]{.greek-added}[13:42]{.aside}

[λυθεισης]{.greek-omitted} [λυθησης]{.greek-added} δε της συναγωγης ηκολουθησαν πολλοι των ιουδαιων και των σεβομενων προσηλυτων τω παυλω και τω βαρναβα οιτινες προσλαλουντες [αυτοις]{.greek-added} επειθον αυτους [επιμενειν]{.greek-omitted} [προσμενειν]{.greek-added} τη χαριτι του [θεου]{.greek-abbr}[13:43]{.aside}

τω [τε]{.greek-omitted} [δε]{.greek-added} ερχομενω σαββατω σχεδον πασα η πολις συνηχθη ακουσαι τον λογον του [θεου]{.greek-abbr}[13:44]{.aside}

ιδοντες δε οι ιουδαιοι τους οχλους επλησθησαν ζηλου και αντελεγον τοις υπο του παυλου λεγομενοις [αντιλεγοντες]{.greek-omitted} [και]{.greek-omitted} βλασφημουντες[13:45]{.aside}

παρρησιασαμενοι [δε]{.greek-omitted} [τε]{.greek-added} ο παυλος και ο βαρναβας ειπον υμιν ην αναγκαιον πρωτον λαληθηναι τον λογον του [θεου]{.greek-abbr} [επειδη]{.greek-omitted} [επει]{.greek-added} δε [απωθεισθε]{.greek-omitted} [αποθεισθε]{.greek-added} αυτον και ουκ αξιους [κρινετε]{.greek-omitted} [κρινεται]{.greek-added} εαυτους της αιωνιου ζωης ιδου στρεφομεθα εις τα εθνη[13:46]{.aside}

ουτως γαρ [ημιν]{.greek-added} εντεταλται ημιν ο [κυριος]{.greek-abbr} [τεθεικα]{.greek-omitted} [τεθηκα]{.greek-added} σε εις φως εθνων του ειναι σε εις [σωτηριαν]{.greek-abbr} εως εσχατου της γης[13:47]{.aside}

ακουοντα δε τα εθνη [εχαιρεν]{.greek-omitted} [εχαιρον]{.greek-added} και εδοξαζον τον λογον του [κυριου]{.greek-abbr} και επιστευσαν οσοι ησαν τεταγμενοι εις ζωην αιωνιον[13:48]{.aside}

διεφερετο δε ο λογος του [κυριου]{.greek-abbr} δι ολης της χωρας[13:49]{.aside}

οι δε ιουδαιοι παρωτρυναν τας σεβομενας γυναικας και τας ευσχημονας και τους πρωτους της πολεως και επηγειραν διωγμον επι τον παυλον και [τον]{.greek-omitted} βαρναβαν και εξεβαλον αυτους απο των [οριων]{.greek-omitted} [ωριων]{.greek-added} αυτων[13:50]{.aside}

οι δε εκτιναξαμενοι τον κονιορτον των ποδων [αυτων]{.greek-omitted} επ αυτους ηλθον εις ικονιον[13:51]{.aside}

οι [δε]{.greek-omitted} [τε]{.greek-added} μαθηται επληρουντο χαρας και [πνευματος]{.greek-abbr} αγιου[13:52]{.aside}

### Chapter 14

εγενετο δε εν ικονιω κατα το αυτο εισελθειν αυτους εις την συναγωγην των ιουδαιων και λαλησαι ουτως ωστε πιστευσαι ιουδαιων [τε]{.greek-omitted} και ελληνων πολυ πληθος[14:1]{.aside}

οι δε απειθουντες ιουδαιοι επηγειραν και εκακωσαν τας ψυχας των εθνων κατα των αδελφων[14:2]{.aside}

ικανον μεν ουν χρονον διετριψαν [παρρησιαζομενοι]{.greek-omitted} [παρρησιασαμενοι]{.greek-added} επι τω [κυριω]{.greek-abbr} τω μαρτυρουντι τω λογω της χαριτος αυτου διδοντι σημεια και τερατα γινεσθαι δια των χειρων αυτων[14:3]{.aside}

εσχισθη δε το πληθος της πολεως και οι μεν ησαν συν τοις ιουδαιοις οι δε συν τοις αποστολοις[14:4]{.aside}

ως δε εγενετο ορμη των εθνων τε και ιουδαιων συν τοις αρχουσιν αυτων υβρισαι και [λιθοβολησαι]{.greek-omitted} [λιθοβολισαι]{.greek-added} αυτους[14:5]{.aside}

συνιδοντες [κατεφυγον]{.greek-omitted} [κατεφυγαν]{.greek-added} εις τας πολεις της λυκαονιας λυστραν και δερβην και την περιχωρον[14:6]{.aside}

κακει ησαν ευαγγελιζομενοι[14:7]{.aside}

και τις ανηρ εν λυστροις αδυνατος τοις ποσιν εκαθητο χωλος εκ κοιλιας [μητρος]{.greek-abbr} αυτου υπαρχων ος ουδεποτε περιπεπατηκει[14:8]{.aside}

ουτος ηκουσεν του παυλου λαλουντο[ς]{.unclear} [ος]{.greek-omitted} [ο]{.greek-added} [δε]{.greek-added} ατενισας αυτω και ιδων οτι πιστιν εχει του σωθηναι[14:9]{.aside}

ειπεν μεγαλη τη φωνη αναστηθι επι τους ποδας σου [ορθως]{.greek-omitted} [ορθος]{.greek-added} και [ηλλετο]{.greek-omitted} [ηλλατο]{.greek-added} και περιεπατει[14:10]{.aside}

οι δε οχλοι ιδοντες ο εποιησεν ο παυλος επηραν την φωνην αυτων λυκαονιστι λεγοντες οι θεοι ομοιωθε[ντ]{.unclear}[ες]{.greek-supplied} [ανθρωποις]{.greek-abbr} κατεβησαν προς ημας[14:11]{.aside}

εκαλουν τε τον μεν βαρναβαν [δια]{.greek-omitted} [διαν]{.greek-added} τον δε παυλον ερμην επειδη αυτος ην [ο]{.greek-omitted} ηγουμενος του λογου[14:12]{.aside}

ο [δε]{.greek-omitted} [τε]{.greek-added} ιερευς του διος του οντος προ της πολεως [αυτων]{.greek-omitted} ταυρους και στεμματα [αυτοις]{.greek-added} επι [τους]{.greek-omitted} [του]{.greek-added} [πυλωνας]{.greek-omitted} [πυλωνος]{.greek-added} ενεγκας συν τοις οχλοις [ηθελεν]{.greek-omitted} [ηθελον]{.greek-added} θυειν[14:13]{.aside}

ακουσαντες δε οι αποστολοι βαρναβας και παυλος διαρρηξαντες τα ιματια αυτων εισεπηδησαν εις τον οχλον κραζοντες[14:14]{.aside}

και λεγοντες ανδρες τι ταυτα ποιειτε και ημεις ομοιοπαθεις εσμεν υμ[ι]{.unclear}ν [ανθρωποι]{.greek-abbr} ευαγγελιζομενοι υμας απο τουτων των ματαιων επ[ι]{.unclear}στρεφειν επι [τον]{.greek-omitted} [θεον]{.greek-abbr} [τον]{.greek-omitted} ζωντα ος εποιησεν τον [ουρανον]{.greek-abbr} και την γην και την θαλασσαν και παντα τα εν αυτοις[14:15]{.aside}

ος εν ταις παρωχημεναις γενεαις ειασεν παντα τα εθνη πορευεσθαι ταις οδοις αυτων[14:16]{.aside}

καιτοιγε ουκ αμαρτυρον εαυτον αφηκεν [αγαθοποιων]{.greek-omitted} [αγαθουργον]{.greek-added} [ουρανοθεν]{.greek-abbr} υμιν [διδους]{.greek-added} υετους [διδους]{.greek-omitted} και καιρους καρποφορους εμπιπλων τροφης και ευφροσυνης τας καρδιας ημων[14:17]{.aside}

και ταυτα λεγοντες μολις κατεπαυσαν τους οχλους του μη θυειν αυτοις [αλλα]{.greek-added} [πορευεσθαι]{.greek-added} [εκαστον]{.greek-added} [εις]{.greek-added} [τα]{.greek-added} [ιδια]{.greek-added}[14:18]{.aside}

[διατριβοντων]{.greek-added} [δε]{.greek-added} [αυτων]{.greek-added} [και]{.greek-added} [διδασκοντων]{.greek-added} επηλθον [δε]{.greek-omitted} απο αντιοχειας και ικονιου ιουδαι[ο]{.unclear}ι [[ιουδαιαι]{.corr}]{.greek-added} [και]{.greek-added} [διαλεγομενων]{.greek-added} [αυτω[ν]{.greek-supplied}]{.greek-added} [παρρησια]{.greek-added} [επεισαντα]{.greek-added} [οχλους]{.greek-added} [αποστηναι]{.greek-added} [απ]{.greek-added} [α[υ]{.unclear}των]{.greek-added} [λεγοντες]{.greek-added} [[οτι]{.unclear}]{.greek-added} [[αρα]{.corr}]{.greek-added} [ουδεν]{.greek-added} [αληθες]{.greek-added} [λεγουσιν]{.greek-added} [αλλα]{.greek-added} [παντα]{.greek-added} [ψευδονται]{.greek-added} και πεισαντες τους οχλου[ς]{.unclear} και λιθασαντες τον [παυλον]{.greek-omitted} [π[αυ]{.greek-supplied}]{.greek-added} [πε]{.greek-added} [λ[ον]{.unclear}]{.greek-added} [τρον]{.greek-added} [εσυρον]{.greek-omitted} [εσυραν]{.greek-added} [αυτον]{.greek-added} εξω της πολεως νομισαντες αυτον [τεθναναι]{.greek-omitted} [τεθνηκεναι]{.greek-added}[14:19]{.aside}

κυκλωσαντων δε [αυτον]{.greek-omitted} των μαθητων [αυτων]{.greek-added} αναστας εισηλθεν εις την πολιν και τη επαυριον εξηλθεν [[αυτω]{.corr}]{.greek-added} [συν]{.greek-omitted} [τω]{.greek-omitted} βαρναβα εις δερ[β]{.unclear}ην [[δερμην]{.corr}]{.greek-added}[14:20]{.aside}

ευαγγελισαμενοι [τε]{.greek-omitted} [δε]{.greek-added} την πολιν εκεινην και μαθητευσαντες [ικανους]{.greek-omitted} [ικαινους]{.greek-added} υπεστρεψαν εις την λυστραν και ικονιον και αντι[ο]{.greek-supplied}χειαν [[αν]{.corr}]{.greek-added} [[τις]{.corr}]{.greek-added} [[χαραν]{.corr}]{.greek-added}[14:21]{.aside}

επιστηριζοντες τας ψυχας των μαθητων παρακαλουντες εμμενειν τη πιστει και οτι δια πολλων θλιψεων δει ημας εισελθειν εις την βασιλειαν του [θεου]{.greek-abbr}[14:22]{.aside}

χειροτονησαντες δε αυτοις πρεσβυτερους κατ εκκλησιαν προσευξαμεν[οι]{.unclear} [[προσευξαμενους]{.corr}]{.greek-added} μετα νηστειων παρεθεντ[ο]{.unclear} αυτ[ο]{.unclear}υς τω [κυριω]{.greek-abbr} ει[ς]{.unclear} ον [πεπιστευκεισαν]{.greek-omitted} [πιστεφτυκεισαν]{.greek-added}[14:23]{.aside}

και διελθοντες την πισιδιαν ηλθον εις [την]{.greek-added} παμφυλιαν[14:24]{.aside}

και λαλησαντες εν περγη τον λογον [του]{.greek-added} [[κυριου]{.greek-abbr}]{.greek-added} κατεβησαν [εις]{.unclear} [ατταλειαν]{.greek-omitted} [[ατ]{.greek-supplied}ταλιαν]{.greek-added} [[στην]{.corr}]{.greek-added} [[υταλιαν]{.corr}]{.greek-added}[14:25]{.aside}

κακειθεν απεπλ[ε]{.unclear}υσαν εις [αντιοχειαν]{.greek-omitted} [αντιοχηαν]{.greek-added} οθεν ησαν παραδ[ε]{.unclear}δομενοι τη χαριτι του [θεου]{.greek-abbr} εις το εργον ο επληρωσαν[14:26]{.aside}

παραγενομενοι δε και συναγαγοντες την [εκκλησιαν]{.greek-omitted} [εκκλισιαν]{.greek-added} [ανηγγειλαν]{.greek-omitted} [απηγγειλαν]{.greek-added} οσα εποιησεν ο [θεος]{.greek-abbr} μετ αυτων και οτι [ηνοιξεν]{.greek-omitted} [ην[υ]{.unclear}ξεν]{.greek-added} τοις εθνεσιν θυραν πιστεως[14:27]{.aside}

διετριβον [δε]{.greek-omitted} [τε]{.greek-added} εκ[ε]{.unclear}ι χρονον ουκ [ο]{.unclear}λιγον συν το[ι]{.unclear}ς μαθηται[ς]{.unclear}[14:28]{.aside}

### Chapter 15

και τινες κατελθοντες απο της ιουδαιας εδιδασκον τους αδελφους οτι εαν μη [περιτεμνησθε]{.greek-omitted} [περ[ι]{.unclear}τμηθητε]{.greek-added} τω εθει [μ]{.unclear}ωυσε[ω]{.unclear}ς [[[α]{.unclear}]{.corr}]{.greek-added} [[ωμοσης]{.corr}]{.greek-added} ου δυνασθε σ[ω]{.greek-supplied}θηναι [[σελθηναι]{.corr}]{.greek-added}[15:1]{.aside}

γενομενης ουν στασεως και ζητησ[εω]{.unclear}ς ουκ ολ[ι]{.unclear}γης τω [παυ]{.unclear}λω και τω βαρναβα προς αυτους εταξα[ν]{.greek-supplied} αναβαινειν παυλον και βαρναβαν και τινας αλλους εξ αυτων προς τους αποστολους και πρεσβυτερους εις [ιερουσαλημ]{.greek-abbr} περι του ζητηματος τουτου[15:2]{.aside}

οι μεν ουν προπεμφθεντες υπο της εκκλησιας διηρχοντο την φοινικην και σαμαρειαν εκδιηγουμενοι την επιστροφην των εθνων και εποιουν χαραν μεγαλην πασιν τοις αδελφοις[15:3]{.aside}

παραγενομενοι δε εις [ιερουσαλημ]{.greek-omitted} [ιεροσολυμα]{.greek-added} απεδεχθησαν υπο της εκκλησιας και των αποστολων και των πρεσβυτερων ανηγγειλαν τε οσα ο [θεος]{.greek-abbr} εποιησεν μετ αυτων[15:4]{.aside}

εξανεστησαν δε τινες των απο της αιρεσεως των φαρισαιων πεπιστευκοτες λεγοντες οτι δει περιτεμνειν αυτους παραγγελλειν τε τηρειν τον νομον μωυσεως[15:5]{.aside}

συνηχθησαν δε οι αποστολοι και οι πρεσβυτεροι ιδειν περι του λογου τουτου[15:6]{.aside}

πολλης δε [συζητησεως]{.greek-omitted} [ζητησεως]{.greek-added} γενομενης αναστας πετρος ειπεν προς αυτους ανδρες αδελφοι υμεις επιστασθε οτι αφ ημερων αρχαιων ο [θεος]{.greek-abbr} εν [ημιν]{.greek-omitted} [υμιν]{.greek-added} εξελεξατο δια του στοματος μου ακουσαι τα εθνη τον λογον του ευαγγελιου και πιστευσαι[15:7]{.aside}

και ο καρδιογνωστης [θεος]{.greek-abbr} εμαρτυρησεν αυτοις δους αυτοις το [πνευμα]{.greek-abbr} το αγιον καθως και ημιν[15:8]{.aside}

και [ουδεν]{.greek-omitted} [ουθεν]{.greek-added} διεκρινεν μεταξυ ημων τε και αυτων τη πιστει καθαρισας τας καρδιας αυτων[15:9]{.aside}

νυν ουν τι πειραζετε τον [θεον]{.greek-abbr} [επιθειναι]{.greek-omitted} [επιθηναι]{.greek-added} ζυγον επι τον τραχηλον των μαθητων ον ουτε οι [πατερες]{.greek-abbr} ημων ουτε ημεις ισχυσαμεν βαστασαι[15:10]{.aside}

αλλα δια της χαριτος του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} [[χριστου]{.greek-abbr}]{.greek-added} πιστευομεν σωθηναι καθ ον τροπον κακεινοι[15:11]{.aside}

[εσιγησεν]{.greek-omitted} [εσηγησεν]{.greek-added} δε παν το πληθος και ηκουον βαρναβα και παυλου εξηγουμενων οσα εποιησεν ο [θεος]{.greek-abbr} σημεια και τερατα εν τοις εθνεσιν δι αυτων[15:12]{.aside}

μετα δε το σιγησαι αυτους απεκριθη ιακωβος λεγων ανδρες αδελφοι ακουσατε μου[15:13]{.aside}

συμεων εξηγησατο καθως πρωτον ο [θεος]{.greek-abbr} επεσκεψατο λαβειν εξ εθνων λαον [επι]{.greek-omitted} τω ονοματι αυτου[15:14]{.aside}

και [τουτω]{.greek-omitted} [τουτο]{.greek-added} συμφωνουσιν οι λογοι των προφητων καθως γεγραπται[15:15]{.aside}

μετα ταυτα αναστρεψω και ανοικοδομησω την σκηνην [δαυιδ]{.greek-abbr} την πεπτωκυιαν και τα κατεσκαμμενα αυτης ανοικοδομησω και ανορθωσω αυτην[15:16]{.aside}

οπως αν [εκζητησωσιν]{.greek-omitted} [ζητησωσιν]{.greek-added} οι καταλοιποι των [ανθρωπων]{.greek-abbr} τον [κυριον]{.greek-abbr} και παντα τα εθνη εφ ους επικεκληται το ονομα μου επ αυτους λεγει [κυριος]{.greek-abbr} ο ποιων [παντα]{.greek-added} ταυτα [παντα]{.greek-omitted}[15:17]{.aside}

γνωστα απ αιωνος εστιν τω [θεω]{.greek-abbr} παντα τα εργα αυτου[15:18]{.aside}

διο εγω κρινω μη παρενοχλειν τοις απο των εθνων επιστρεφουσιν επι τον [θεον]{.greek-abbr}[15:19]{.aside}

αλλα επιστειλαι αυτοις του απεχεσθαι απο των αλισγηματων των [ειδωλων]{.greek-omitted} [ειδολων]{.greek-added} και της [πορνειας]{.greek-omitted} [πορνιας]{.greek-added} και του πνικτου και του αιματος[15:20]{.aside}

[μωυσης]{.greek-omitted} [μωσης]{.greek-added} γαρ εκ γενεων αρχαιων κατα πολιν τους κηρυσσοντας αυτον εχει εν ταις συναγωγαις κατα παν σαββατον αναγινωσκομενος[15:21]{.aside}

τοτε [εδοξεν]{.greek-omitted} [εδοξε]{.greek-added} τοις αποστολοις και τοις πρεσβυτεροις συν ολη τη εκκλησια εκλεξαμενους ανδρας εξ αυτων πεμψαι εις αντιοχειαν συν [τω]{.greek-added} παυλω και [τω]{.greek-added} βαρναβα ιουδαν τον [επικαλουμενον]{.greek-omitted} [καλουμενον]{.greek-added} [βαρσαββαν]{.greek-omitted} [βαρσαβαν]{.greek-added} και σιλαν ανδρας ηγουμενους εν τοις αδελφοις[15:22]{.aside}

γραψαντες δια χειρος αυτων [επιστολην]{.greek-added} [εχουσαν]{.greek-added} ταδε οι αποστολοι και οι πρεσβυτεροι και οι αδελφοι τοις κατα την αντιοχειαν και συριαν και κιλικιαν αδελφοις τοις εξ εθνων χαιρειν[15:23]{.aside}

επειδη ηκουσαμεν οτι τινες εξ ημων εξελθοντες εταραξαν υμας λογοις ανασκευαζοντες τας ψυχας υμων λεγοντες περιτεμνεσθαι και τηρειν τον νομον οις ου διεστειλαμεθα[15:24]{.aside}

εδοξεν ημιν γενομενοις ομοθυμαδον εκλεξαμενους ανδρας πεμψαι προς υμας συν τοις αγαπητοις ημων βαρναβα [τε]{.greek-added} και παυλω[15:25]{.aside}

[ανθρωποις]{.greek-abbr} [παραδεδωκοσιν]{.greek-omitted} [παραδεδωκοσι]{.greek-added} τας ψυχας αυτων υπερ του ονοματος του [κυριου]{.greek-abbr} ημων [ιησου]{.greek-abbr} [χριστου]{.greek-abbr}[15:26]{.aside}

απεσταλκαμεν ουν ιουδαν και σιλαν και αυτους δια λογου απαγγελλοντας τα αυτα[15:27]{.aside}

[εδοξεν]{.greek-omitted} [εδοξε]{.greek-added} γαρ τω [[πνευματι]{.greek-abbr}]{.greek-added} [τω]{.greek-added} αγιω [πνευματι]{.greek-omitted} και ημιν μηδεν πλεον επιτιθεσθαι υμιν βαρος πλην [τουτων]{.greek-added} των επαναγκες [τουτων]{.greek-omitted}[15:28]{.aside}

απεχεσθαι [ειδωλοθυτων]{.greek-omitted} [ειδολοθυτων]{.greek-added} και αιματος και πνικτου και πορνειας εξ ων [διατηρουντες]{.greek-omitted} [διατηρησαντες]{.greek-added} εαυτους ευ [πραξετε]{.greek-omitted} [πραξητε]{.greek-added} ερρωσθε[15:29]{.aside}

οι μεν ουν απολυθεντες [ηλθον]{.greek-omitted} [κατηλθον]{.greek-added} εις αντιοχειαν και συναγαγοντες το πληθος επεδωκαν την επιστολην[15:30]{.aside}

αναγνοντες δε εχαρησαν επι τη παρακλησει[15:31]{.aside}

ιουδας [τε]{.greek-omitted} [δε]{.greek-added} και σιλας και αυτοι προφηται οντες δια λογου πολλου παρεκαλεσαν τους αδελφους και επεστηριξαν[15:32]{.aside}

ποιησαντες δε χρονον απελυθησαν μετ ειρηνης απο των αδελφων προς τους αποστολους[15:33]{.aside}

[εδοξε]{.greek-added} [δε]{.greek-added} [τω]{.greek-added} [σιλα]{.greek-added} [επιμειναι]{.greek-added} [αυτου]{.greek-added}[15:34]{.aside}

παυλος δε και βαρναβας διετριβον εν αντιοχεια διδασκοντες και ευαγγελιζομενοι μετα και ετερων πολλων τον λογον του [κυριου]{.greek-abbr}[15:35]{.aside}

μετα δε τινας ημερας ειπεν παυλος προς βαρναβαν επιστρεψαντες δη επισκεψωμεθα τους αδελφους ημων κατα πασαν πολιν εν αις κατηγγειλαμεν τον λογον του [κυριου]{.greek-abbr} πως εχουσιν[15:36]{.aside}

βαρναβας δε εβουλευσατο [συμπαραλαβειν]{.greek-omitted} [συνπαραλαβειν]{.greek-added} [και]{.greek-added} τον ιωαννην τον καλουμενον μαρκον[15:37]{.aside}

παυλος δε ηξιου τον αποσταντα απ αυτων απο παμφυλιας και μη συνελθοντα αυτοις εις το εργον μη [συμπαραλαβειν]{.greek-omitted} [συμπαραλαμβανειν]{.greek-added} τουτον[15:38]{.aside}

εγενετο ουν παροξυσμος ωστε αποχωρισθηναι αυτους απ αλληλων τον τε βαρναβαν παραλαβοντα τον μαρκον εκπλευσαι εις κυπρον[15:39]{.aside}

παυλος δε επιλεξαμενος σιλαν εξηλθεν παραδοθεις τη χαριτι του [θεου]{.greek-abbr} υπο των αδελφων[15:40]{.aside}

[διηρχετο]{.greek-omitted} [διηρχοντο]{.greek-added} δε την συριαν και [την]{.greek-added} κιλικιαν [επιστηριζων]{.greek-omitted} [επιστηριζοντες]{.greek-added} τας εκκλησιας[15:41]{.aside}

### Chapter 16

[κατηντησεν]{.greek-omitted} [κατηντησαν]{.greek-added} δε [και]{.greek-added} εις δερβην και λυστραν και ιδου μαθητης τις ην εκει ονοματι τιμοθεος [υιος]{.greek-abbr} γυναικος [τινος]{.greek-omitted} ιουδαιας πιστης [πατρος]{.greek-abbr} δε ελληνος[16:1]{.aside}

ος εμαρτυρειτο υπο των εν λυστροις και ικονιω αδελφων[16:2]{.aside}

τουτον ηθελησεν ο παυλος συν αυτω εξελθειν και λαβων περιετεμεν αυτον δια τους ιουδαιους τους οντας εν τοις τοποις εκεινοις ηδεισαν γαρ απαντες τον [πατερα]{.greek-abbr} αυτου οτι ελλην υπηρχεν[16:3]{.aside}

ως δε διεπορευοντο τας πολεις παρεδιδουν αυτοις φυλασσειν τα δογματα τα κεκριμενα υπο των αποστολων και των πρεσβυτερων [των]{.greek-omitted} εν [ιερουσαλημ]{.greek-abbr}[16:4]{.aside}

αι μεν ουν εκκλησιαι εστερεουντο τη πιστει και [επερισσευον]{.greek-omitted} [περιεσσευον]{.greek-added} τω αριθμω καθ ημεραν[16:5]{.aside}

[διελθοντες]{.greek-omitted} [διηλθον]{.greek-added} δε την φρυγιαν και την γαλατικην χωραν κωλυθεντες υπο του αγιου [πνευματος]{.greek-abbr} [μη]{.greek-added} λαλησαι τον λογον εν τη ασια[16:6]{.aside}

ελθοντες [δε]{.greek-added} κατα την μυσιαν [επειραζον]{.greek-omitted} [επηραζον]{.greek-added} [κατα]{.greek-omitted} [εις]{.greek-added} την [βιθυνιαν]{.greek-omitted} [βηθυνιαν]{.greek-added} πορευεσθαι και ουκ [ειασεν]{.greek-omitted} [ιασεν]{.greek-added} αυτους το [πνευμα]{.greek-abbr} [[ιησου]{.greek-abbr}]{.greek-added}[16:7]{.aside}

παρελθοντες δε την μυσιαν κατεβησαν εις τρωαδα[16:8]{.aside}

και οραμα δια της νυκτος ωφθη τω παυλω ανηρ τις [μακεδων]{.greek-added} ην [μακεδων]{.greek-omitted} εστως [και]{.greek-added} παρακαλων αυτον και λεγων διαβας εις μακεδονιαν βοηθησον ημιν[16:9]{.aside}

ως δε το οραμα ειδεν ευθεως [εζητησαμεν]{.greek-omitted} [εξητησαμεν]{.greek-added} εξελθειν εις την μακεδονιαν συμβιβαζοντες οτι προσκεκληται ημας ο [κυριος]{.greek-abbr} ευαγγελισασθαι [αυτους]{.greek-omitted} [αυτοις]{.greek-added}[16:10]{.aside}

αναχθεντες [ουν]{.greek-omitted} [δε]{.greek-added} απο [της]{.greek-omitted} [τρωαδος]{.greek-omitted} [τροαδος]{.greek-added} ευθυδρομησαμεν εις σαμοθρακην τη [τε]{.greek-omitted} [δε]{.greek-added} επιουση εις νεαπολιν[16:11]{.aside}

εκειθεν τε εις φιλιππους ητις εστιν πρωτη της μεριδος της μακεδονιας πολις [κολωνεια]{.greek-omitted} [κωλωνια]{.greek-added} ημεν δε εν [αυτη]{.greek-omitted} [ταυτη]{.greek-added} τη πολει διατριβοντες ημερας τινας[16:12]{.aside}

τη τε ημερα των σαββατων εξηλθομεν εξω της πολεως παρα ποταμον ου ενομιζετο [προσευχη]{.greek-omitted} [προσευχην]{.greek-added} ειναι και [καθι]{.greek-added} [καθισαντες]{.greek-omitted} [σαντες]{.greek-added} ελαλουμεν ταις συνελθουσαις γυναιξιν[16:13]{.aside}

και τις γυνη ονοματι λυδια πορφυροπωλις πολεως [θυατειρων]{.greek-omitted} [θυατειρ]{.greek-added} σεβομενη τον [θεον]{.greek-abbr} [ηκουεν]{.greek-omitted} [ηκουσεν]{.greek-added} ης ο [κυριος]{.greek-abbr} διηνοιξεν την καρδιαν προσεχειν τοις λαλουμενοις υπο του παυλου[16:14]{.aside}

ως δε εβαπτισθη και [πας]{.greek-added} ο οικος αυτης παρεκαλεσεν λεγουσα ει κεκρικατε με πιστην τω [κυριω]{.greek-abbr} ειναι εισελθοντες εις τον οικον μου μεινατε και παρεβιασατο ημας[16:15]{.aside}

εγενετο δε πορευομενων ημων εις [την]{.greek-added} προσευχην παιδισκην τινα εχουσαν [πνευμα]{.greek-abbr} [πυθωνος]{.greek-omitted} [ποιθωνος]{.greek-added} απαντησαι ημιν ητις εργασιαν πολλην παρειχεν τοις κυριοις αυτης μαντευομενη[16:16]{.aside}

αυτη κατακολουθησασα τω παυλω και ημιν εκραζεν λεγουσα ουτοι οι [ανθρωποι]{.greek-abbr} δουλοι του [θεου]{.greek-abbr} του υψιστου εισιν οιτινες καταγγελλουσιν ημιν οδον [σωτηριας]{.greek-abbr}[16:17]{.aside}

τουτο δε [εποιει]{.greek-omitted} [εποιησεν]{.greek-added} επι πολλας ημερας διαπονηθεις δε ο παυλος και επιστρεψας [ειπεν]{.greek-added} τω [πνευματι]{.greek-abbr} [ειπεν]{.greek-omitted} παραγγελλω σοι εν [τω]{.greek-omitted} ονοματι [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} εξελθειν απ αυτης και εξηλθεν αυτη τη ωρα[16:18]{.aside}

ιδοντες δε οι κυριοι αυτης οτι εξηλθεν η ελπις της εργασιας αυτων επιλαβομενοι τ[ο]{.unclear}ν παυλον και τον σιλαν ειλκυσαν εις την αγοραν επι τους αρχοντας[16:19]{.aside}

και προσαγαγοντες αυτους τοις στρατηγοις ειπον ουτοι οι [ανθρωποι]{.greek-abbr} εκταρασσουσιν ημων την πολιν ιουδαιοι υπαρχοντες[16:20]{.aside}

και καταγγελλουσιν εθη α ουκ εξεστιν ημιν π[α]{.unclear}[ρα]{.greek-supplied}δεχεσθαι ουδε ποιειν ρωμαιοις ουσιν[16:21]{.aside}

και συνεπεστη ο οχλος κατ αυτων και οι στρατηγοι περιρρηξαντες αυτων τα ιματια εκελευον ραβδιζειν[16:22]{.aside}

πολλας τε επιθεντες αυτοις πληγας εβαλον εις φυλακην παραγγειλαντες τω δεσμοφυλακι ασφαλως τηρειν αυτους[16:23]{.aside}

ος παραγγελιαν τοιαυτην [ειληφως]{.greek-omitted} [λαβων]{.greek-added} εβαλεν αυτους εις την εσωτεραν φυλακην και τους ποδας αυτων [ησφαλισατο]{.greek-omitted} [ησφαλησατο]{.greek-added} εις το ξυλον[16:24]{.aside}

κατα δε το μεσονυκτιον παυλος και σιλας προσευχομενοι υμνουν τον [θεον]{.greek-abbr} [και]{.greek-added} [επηκροωντο]{.greek-omitted} [επικροωντο]{.greek-added} [δε]{.greek-omitted} αυτων οι δεσμιοι[16:25]{.aside}

αφνω δε [σεισμος]{.greek-omitted} [σισμος]{.greek-added} εγενετο μεγας ωστε σαλευθηναι τα θεμελια του δεσμωτηριου ανεωχθησαν [τε]{.greek-omitted} [δε]{.greek-added} παραχρημα αι θυραι πασαι και παντων τα δεσμα ανεθη[16:26]{.aside}

εξυπνος δε γενομενος ο δεσμοφυλαξ και ιδων ανεωγμενας τας θυρας της φυλακης σπασαμενος μαχαιραν [εμελλεν]{.greek-omitted} [ημελλεν]{.greek-added} εαυτον αναιρειν νομιζων εκπεφευγεναι τους δεσμιους[16:27]{.aside}

εφωνησεν δε φωνη μεγαλη [ο]{.greek-omitted} παυλος λεγων μηδεν πραξης σεαυτω κακον απαντες γαρ εσμεν ενθαδε[16:28]{.aside}

αιτησας δε φωτα εισεπηδησεν και εντρομος [γενομενος]{.greek-omitted} [υπαρχων]{.greek-added} προσεπεσεν τω παυλω και τω σιλα[16:29]{.aside}

και προαγαγων αυτους εξω εφη κυριοι τι με δει ποιειν ινα σωθω[16:30]{.aside}

οι δε ειπον πιστευσον επι τον [κυριον]{.greek-abbr} [ιησουν]{.greek-abbr} [χριστον]{.greek-abbr} και σωθηση συ και ο οικος σου[16:31]{.aside}

και ελαλησαν αυτω τον λογον του [κυριου]{.greek-abbr} και πασιν τοις εν τη οικια αυτου[16:32]{.aside}

και παραλαβων αυτους εν εκεινη τη ωρα της [νυ]{.greek-added} [νυκτος]{.greek-omitted} [κτος]{.greek-added} ελουσεν απο των πληγων και εβαπτισθη αυτος και οι αυτου παντες παραχρημα[16:33]{.aside}

αναγαγων [τε]{.greek-omitted} [δε]{.greek-added} αυτους εις τον οικον [αυτου]{.greek-omitted} παρεθηκεν τραπεζαν και [ηγαλλιατο]{.greek-omitted} [ηγαλλιασατο]{.greek-added} [πανοικι]{.greek-omitted} [πανοικη]{.greek-added} πεπιστευκως τω [θεω]{.greek-abbr}[16:34]{.aside}

ημερας δε γενο[μ]{.unclear}ενης απεστειλαν οι στρατηγοι τους ραβδουχους λεγοντες απολυσον τους [ανθρωπους]{.greek-abbr} εκεινους[16:35]{.aside}

απηγγειλεν δε ο δεσμοφυλαξ τους λογους τουτους προς τον παυλον οτι απεσταλκασιν οι στρατηγοι ινα απολυθητε νυν ουν εξελθοντες πορευεσθε εν ειρηνη[16:36]{.aside}

ο δε παυλος εφη προς αυτους δειραντες ημας δημοσια ακατακριτους [ανθρωπους]{.greek-abbr} ρωμαιους υπαρχοντας εβαλον εις φυλακην και νυν λαθρα ημας εκβαλλου[σι]{.unclear}ν ου γαρ αλλα ελθοντες αυτοι [ημας]{.greek-added} εξαγαγετωσαν[16:37]{.aside}

[ανηγγειλαν]{.greek-omitted} [απηγγειλαν]{.greek-added} δε τοις στρατηγοις οι ραβδουχοι τα ρηματα ταυτα και εφοβηθησαν ακουσαντες οτι ρωμαιοι εισιν[16:38]{.aside}

και ελθοντες παρεκαλεσαν αυτους και εξαγαγοντες [ηρωτων]{.greek-omitted} [ηρωτουν]{.greek-added} [εξελθειν]{.greek-omitted} [απελθειν]{.greek-added} [απο]{.greek-added} της πολεως[16:39]{.aside}

εξελθοντες δε εκ της φυλακης εισηλθον προς την λυδιαν και ιδοντες τους αδελφους παρεκαλεσαν αυτους και εξηλθον[16:40]{.aside}

### Chapter 17

διοδευσαντες δε την αμφιπολιν και απολλωνιαν ηλθον εις θεσσαλονικην οπου ην η συναγωγη των ιουδαιων[17:1]{.aside}

κατα δε το ειωθος τω παυλω εισηλθεν προς αυτους και επι σαββατα τρια [διελεξατο]{.greek-omitted} [διελεγετο]{.greek-added} αυτοις απο των γραφων[17:2]{.aside}

διανοιγων και [παρατιθεμενος]{.greek-omitted} [παρατιθεμε]{.greek-added} [νος]{.greek-added} [αυτοις]{.greek-added} οτι τον [χριστον]{.greek-abbr} εδει παθειν και αναστηναι εκ νεκρων και οτι ουτος εστιν ο [χριστος]{.greek-abbr} [ιησους]{.greek-abbr} ον εγω καταγγελλω υμιν[17:3]{.aside}

και τινες εξ αυτων επεισθησαν και προσεκληρωθησαν τω παυλω και τω σιλα των [τε]{.greek-omitted} [δε]{.greek-added} σεβομενων ελληνων [πληθος]{.greek-added} πολυ [πληθος]{.greek-omitted} γυναικων τε των πρωτων ουκ ολιγαι[17:4]{.aside}

[προσλαβομενοι]{.greek-omitted} [ζηλωσαντες]{.greek-added} δε οι [απειθουντες]{.greek-added} ιουδαιοι [οι]{.greek-omitted} [απειθουντες]{.greek-omitted} [και]{.greek-added} [προσλα[βο]{.unclear}μενοι]{.greek-added} [τινας]{.greek-added} των αγορ[α]{.unclear}ιων [τινας]{.greek-omitted} ανδρας πονηρους και οχλοποιησαντες εθορυβουν την πολιν [και]{.greek-added} επισταντες [τε]{.greek-omitted} τη οικια [ιασονος]{.greek-omitted} [ιασωνος]{.greek-added} εζητουν αυτους [αγαγειν]{.greek-omitted} [προαγαγειν]{.greek-added} εις τον δημον[17:5]{.aside}

μη ευροντες δε αυτους εσυρον τον ιασονα και τινας αδελφους επι τους πολιταρχας βοωντες οτι οι την οικουμενην αναστατωσαντες ουτοι και [ενθαδε]{.greek-omitted} [ενταυθα]{.greek-added} παρεισιν[17:6]{.aside}

ους υποδεδεκται ιασων και ουτοι παντες απεναντι των δογματων καισαρος πρασσουσιν βασιλεα λεγοντες ετερον ειναι [ιησουν]{.greek-abbr}[17:7]{.aside}

εταραξαν δε τον οχλον και τους πολιταρχας ακουοντας ταυτα[17:8]{.aside}

και λαβοντες το ικανον παρα του ιασονος και των λοιπων απελυσαν αυτους[17:9]{.aside}

οι δε αδελφοι ευθεως δια [της]{.greek-omitted} νυκτος εξεπεμψαν τον τε παυλον και τον σιλαν εις βεροιαν οιτινες παραγενομενοι εις την συναγωγην [απηεσαν]{.greek-omitted} [απιεσαν]{.greek-added} των ιουδαιων[17:10]{.aside}

ουτοι δε ησαν ευγενεστεροι των εν θεσσαλονικη ο[ι]{.unclear}τινες εδεξαντο τον λογον μετα πασης προθυμιας [το]{.greek-omitted} καθ ημεραν ανακρινοντες τας γραφας ει [εχοι]{.greek-omitted} [εχει]{.greek-added} ταυτα ουτως[17:11]{.aside}

πολλοι μεν ουν εξ αυτων επιστευσαν και των ελληνιδων γυναικων των ευσχημονων και ανδρων ουκ ολιγοι[17:12]{.aside}

ως δε εγνωσαν οι απο της θεσσαλονικης ιουδαιοι οτι και εν τη βεροια [κατηγγελη]{.greek-omitted} [κατηγγελλη]{.greek-added} υπο του παυλου ο λογος του [θεου]{.greek-abbr} ηλθον κακει σαλευοντες [και]{.greek-added} [ταρασσοντες]{.greek-added} τους οχλους[17:13]{.aside}

ευθεως δε τοτε τον παυλον εξαπεστειλαν οι αδελφοι πορευεσθαι ως επι την θαλασσαν [υπεμενον]{.greek-omitted} [υπεμειναν]{.greek-added} [δε]{.greek-omitted} [τε]{.greek-added} ο τε σιλας και ο τιμοθεος εκει[17:14]{.aside}

οι δε [καθιστωντες]{.greek-omitted} [αποκαθιστωντες]{.greek-added} τον παυλον ηγαγον αυτον εως αθηνων και λαβοντες εντολην προς τον σιλαν και τιμοθεον ινα ως ταχιστα ελθωσι[ν]{.unclear} προς αυτον [εξηεσαν]{.greek-omitted} [εξιεσαν]{.greek-added}[17:15]{.aside}

εν δε ταις [αθηναις]{.greek-omitted} [αθηναι]{.greek-added} εκδεχομενου αυτους του παυλου παρωξυνετο το [πνευμα]{.greek-abbr} αυτου εν αυτω [θεωρουντι]{.greek-omitted} [θεωρουντος]{.greek-added} κατειδωλον ουσαν την πολιν[17:16]{.aside}

διελεγετο μεν ουν εν τη συναγωγη τοις ιουδαιοις και τοις σεβομενοις και εν τη αγορα κατα πασαν ημεραν προς τους παρατυγχανοντας[17:17]{.aside}

τινες δε [και]{.greek-omitted} των [επικουρειων]{.greek-omitted} [επικουριων]{.greek-added} και των στοικων φιλοσοφων [συνεβαλλον]{.greek-omitted} [συνεβαλον]{.greek-added} αυτω και τινες ελεγον τι αν θελοι ο σπερμολογος ουτος λεγειν οι δε ξενων δαιμονιων δοκει καταγγελευς ειναι οτι τον [ιησουν]{.greek-abbr} και την αναστασιν ευηγγελιζετο [αυτοις]{.greek-added}[17:18]{.aside}

επιλαβομενοι [τε]{.greek-omitted} [δε]{.greek-added} αυτου επι τον αρειον παγον ηγαγον λεγοντες δυναμεθα γνωναι τις η καινη αυτη η υπο σου λαλουμενη διδαχη[17:19]{.aside}

ξενιζοντα γαρ τινα εισφερεις εις τας ακοας ημων [βου]{.greek-added} [βουλομεθα]{.greek-omitted} [λομεθα]{.greek-added} ουν γνωναι τι αν θελοι [ταυτα]{.greek-omitted} [αυτη]{.greek-added} [η]{.greek-added} [διδαχη]{.greek-added} ειναι[17:20]{.aside}

αθηναιοι δε παντες και οι επιδημουντες ξενοι εις ουδεν ετερον [ευκαιρουν]{.greek-omitted} [ηυκαιρουν]{.greek-added} η λεγειν τι και ακουειν καινοτερον[17:21]{.aside}

σταθεις δε ο παυλος εν μεσω του αρειου παγου εφη ανδρες αθηναιοι κατα παντα ως [δεισιδαιμονεστερους]{.greek-omitted} [δισιδαιμονεστερους]{.greek-added} υμας θεωρω[17:22]{.aside}

διερχομενος γαρ και αναθεωρων τα σεβασματα υμων ευρον και βωμον εν ω [επεγεγραπτο]{.greek-omitted} [εγεγραπτω]{.greek-added} αγνωστω [θεω]{.greek-abbr} ον ουν αγνοουντες ευσεβειτε τουτον εγω καταγγελλω υμιν[17:23]{.aside}

ο [θεος]{.greek-abbr} ο ποιησας τον κοσμον και παντα τα εν αυτω ουτος [ουρανου]{.greek-abbr} και γης κυριος υπαρχων ουκ εν χειροποιητοις ναοις κατοικει[17:24]{.aside}

ουδε υπο χειρων [ανθρωπων]{.greek-abbr} θεραπευεται προσδεομενος τινος αυτος διδους [πασιν]{.greek-omitted} [πασι]{.greek-added} ζωην και πνοην κατα παντα[17:25]{.aside}

εποιησεν τε εξ ενος αιματος παν εθνος [ανθρωπων]{.greek-abbr} κατοικειν επι παν το προσωπον της γης [ορισας]{.greek-omitted} [ωρισας]{.greek-added} προστεταγμενους καιρους και τας οροθεσιας της κατοικιας αυτων[17:26]{.aside}

ζητειν τον [κυριον]{.greek-abbr} ει αρα γε [ψηλαφησειαν]{.greek-omitted} [ψηλαφισειαν]{.greek-added} αυτον και ευροιεν και γε ου μακραν απο ενος εκαστου ημων υπαρχοντα[17:27]{.aside}

εν αυτω γαρ ζωμεν και κινουμεθα και εσμεν ως και τινες των καθ υμας ποιητων ειρηκασιν του γαρ και γενος εσμεν[17:28]{.aside}

γενος ουν [υπαρχοντες]{.greek-omitted} του [θεου]{.greek-abbr} [υπαρχοντες]{.greek-added} ουκ οφειλομεν νομιζειν χρυσω η αργυρω η λιθω χαραγματι τεχνης και ενθυμησεως [ανθρωπου]{.greek-abbr} το θειον ειναι ομοιον[17:29]{.aside}

τους μεν ουν χρονους της αγνοιας υπεριδων ο [θεος]{.greek-abbr} τα νυν παραγγελλει τοις [ανθρωποις]{.greek-abbr} πασιν πανταχου μετανοειν[17:30]{.aside}

[διοτι]{.greek-omitted} [καθοτι]{.greek-added} εστησεν ημεραν εν η μελλει κρινειν την οικουμενην εν δικαιοσυνη εν ανδρι ω ωρισεν πιστιν παρασχων πασιν αναστησας αυτον εκ νεκρων[17:31]{.aside}

ακουσαντες δε αναστασιν νεκρων οι μεν εχλευαζον οι δε ειπον ακουσομεθα σου [και]{.greek-added} παλιν περι τουτου[17:32]{.aside}

και ουτως ο παυλος εξηλθεν εκ μεσου αυτων[17:33]{.aside}

τινες δε ανδρες κολληθεντες αυτω επιστευσαν εν οις και διονυσιος ο αρεοπαγιτης και γυνη ονοματι δαμαρις και ετεροι συν αυτοις[17:34]{.aside}

### Chapter 18

μετα δε ταυτα χωρισθεις ο παυλος εκ των αθηνων ηλθεν εις κορινθον[18:1]{.aside}

και ευρων τινα ιουδαιον ονοματι ακυλαν ποντικον τω γενει προσφατως εληλυθοτα απο της [ιταλιας]{.greek-omitted} [ηταλειας]{.greek-added} και πρισκιλλαν γυναικα αυτου δια το [τεταχεναι]{.greek-omitted} [διατεταχθεναι]{.greek-added} κλαυδιον χωριζεσθαι παντας τους ιουδαιους [εκ]{.greek-omitted} [απο]{.greek-added} της ρωμης προσηλθεν αυτοις[18:2]{.aside}

και δια το ομοτεχνον ειναι εμενεν παρ αυτοις και ειργαζετο ησαν γαρ σκηνοποιοι [την]{.greek-omitted} [τη]{.greek-added} [τεχνην]{.greek-omitted} [τεχνη]{.greek-added}[18:3]{.aside}

διελεγετο δε εν τη συναγωγη κατα παν σαββατον επειθεν τε ιουδαιους και ελληνας[18:4]{.aside}

ως δε κατηλθον απο της μακεδονιας ο τε σιλας και [ο]{.greek-omitted} τιμοθεος συνειχετο τω [πνευματι]{.greek-omitted} [λογω]{.greek-added} ο παυλος διαμαρτυρομενος τοις ιουδαιοις [ειναι]{.greek-added} τον [χριστον]{.greek-abbr} [ιησουν]{.greek-abbr}[18:5]{.aside}

αντιτασσομενων δε αυτων και βλασφημουντων ε[κ]{.unclear}τιναξαμενος τα ιματια [αυτου]{.greek-added} ειπεν προς αυτους το αιμα υμων επι την κεφαλην υμων καθαρος εγω απο του νυν εις τα εθνη πορευσομαι[18:6]{.aside}

και μεταβας εκειθεν ηλθεν εις οικιαν τινος ονοματι ιουστου σεβομενου τον [θεον]{.greek-abbr} ου η οικια ην συνομορουσα τη συναγωγη[18:7]{.aside}

κρισπος δε ο αρχισυναγωγος επιστευσεν τω [κυριω]{.greek-abbr} συν ολω τω οικω αυτου και πολλοι των κορινθιων ακουοντες επιστευον και εβαπτιζοντο[18:8]{.aside}

ειπεν δε ο [κυριος]{.greek-abbr} δι οραματος εν νυκτι τω παυλω μη φοβου αλλα λαλει και μη σιωπησης[18:9]{.aside}

διοτι εγω ειμι μετα σου και ουδεις επιθησεται σ[ο]{.unclear}ι του κακωσαι σε διοτι λαος εστιν μοι πολυς εν τη πολει ταυτη[18:10]{.aside}

εκαθισεν τε ενιαυτον και μηνας εξ διδασκων [εν]{.greek-omitted} αυτοις τον λογον του [θεου]{.greek-abbr}[18:11]{.aside}

γαλλιωνος δε ανθυπατευοντος της αχαιας κατεπεστησαν ομοθυμαδον οι ιουδαιοι τω παυλω και ηγαγον αυτον επι το βημα[18:12]{.aside}

λεγοντες οτι παρα τον νομον ουτος αναπειθει τους [ανθρωπους]{.greek-abbr} σεβεσθαι τον [θεον]{.greek-abbr}[18:13]{.aside}

μελλοντος δε του παυλου ανοιγειν το στομα ειπεν ο γαλλιων προς τους ιουδαιους ει μεν [ουν]{.greek-omitted} ην αδικημα τι η ραδιουργημα πονηρον ω ιουδαιοι κατα λογον αν ηνεσχομην υμων[18:14]{.aside}

ει δε [ζητημα]{.greek-omitted} [ζητηματα]{.greek-added} εστιν περι λογου και ονοματων και νομου του καθ υμας [αυτοι]{.greek-added} [υμεις]{.greek-added} οψεσθε [αυτοι]{.greek-omitted} κριτης γαρ εγω τουτων ου βουλομαι ειναι[18:15]{.aside}

και απηλασεν αυτους απο του βηματος[18:16]{.aside}

επιλαβομενοι δε παντες οι ελληνες σωσθενην τον αρχισυναγωγον ετυπτον εμπροσθεν του βηματος και ουδεν τουτων τω γαλλιωνι εμελλεν[18:17]{.aside}

ο δε παυλος ετι προσμεινας ημερας ικανας τοις αδελφοις αποταξαμενος εξεπλει εις την συριαν και συν αυτω πρισκιλλα και ακυλας κειραμενος [εν]{.greek-added} [κεχρεαις]{.greek-added} την κεφαλην [εν]{.greek-omitted} [κεγχρεαις]{.greek-omitted} ειχεν γαρ ευχην[18:18]{.aside}

[κατηντησεν]{.greek-omitted} [κατηντησαν]{.greek-added} δε εις εφεσον [και]{.greek-omitted} [εκεινους]{.greek-omitted} [κακεινους]{.greek-added} κατελιπεν [αυτου]{.greek-omitted} [εκει]{.greek-added} αυτος δε [εισελθων]{.greek-omitted} [εισελθον]{.greek-added} εις την συναγωγην διελεχθη τοις ιουδαιοις[18:19]{.aside}

[ερωτωντων]{.greek-omitted} [ερωτοντων]{.greek-added} δε [αυτων]{.greek-omitted} [αυτον]{.greek-added} επι πλειονα χρονον μειναι παρ αυτοις ουκ επενευσεν[18:20]{.aside}

[αλλ]{.greek-omitted} [αλλα]{.greek-added} απεταξατο αυτοις ειπων δει με παντως την εορτην την ερχομενην [ποιησαι]{.greek-omitted} [ποιεισαι]{.greek-added} εις ιεροσολυμα παλιν δε ανακαμψω προς υμας του [θεου]{.greek-abbr} θελοντος [και]{.greek-added} ανηχθη απο της εφεσου[18:21]{.aside}

και κατελθων εις καισαρειαν αναβας και ασπασαμενος την εκκλησιαν κατεβη εις αντιοχειαν[18:22]{.aside}

και ποιησας χρονον τινα εξηλθεν διερχομενος καθεξης την γαλατικην χωραν και φρυγιαν επιστηριζων παντας τους μαθητας[18:23]{.aside}

ιουδαιος δε τις απολλως ονοματι αλεξανδρευς τω γενει ανηρ λογιος κατηντησεν εις εφεσον δυνατος ων εν ταις γραφαις[18:24]{.aside}

ουτος ην κατηχημενος την οδον του [κυριου]{.greek-abbr} και ζεων τω [πνευματι]{.greek-abbr} ελαλει και εδιδασκεν ακριβως τα περι του [κυριου]{.greek-omitted} [[ιησου]{.greek-abbr}]{.greek-added} επισταμενος μονον το βαπτισμα ιωαννου[18:25]{.aside}

ουτος τε ηρξατο παρρησιαζεσθαι εν τη συναγωγη ακουσαντες δε αυτου ακυλας και πρισκιλλα προσελαβοντο αυτον και ακριβεστερον αυτω εξεθεντο την του [θεου]{.greek-abbr} οδον[18:26]{.aside}

βουλομενου δε αυτου [διελθειν]{.greek-omitted} [διελ]{.greek-added} [θειν]{.greek-added} εις την αχαιαν προτρεψαμενοι οι αδελφοι εγραψαν τοις μαθηταις αποδεξασθαι αυτον ος παραγενομενος συνεβαλετο πολυ τοις [πεπιστευκοσιν]{.greek-omitted} [πεπιστευκωσιν]{.greek-added} δια της χαριτος[18:27]{.aside}

ευτονως γαρ τοις ιουδαιοις διακατηλεγχετο δημοσια επιδεικνυς δια των γραφων ειναι τον [χριστον]{.greek-abbr} [ιησουν]{.greek-abbr}[18:28]{.aside}

### Chapter 19

εγενετο δε εν τω τον απολλω ειναι εν κορινθω παυλον διελθοντα τα ανωτερικα μερη [ελθειν]{.greek-omitted} [κατελθειν]{.greek-added} εις εφεσον και ευρων τινας μαθητας[19:1]{.aside}

ειπεν προς αυτους ει [πνευμα]{.greek-abbr} αγιον ελαβετε πιστευσαντες οι δε ειπον προς αυτον αλλ ουδε ει [πνευμα]{.greek-abbr} αγιον εστι[ν]{.unclear} ηκουσαμεν[19:2]{.aside}

[ο]{.greek-added} [δε]{.greek-added} ειπ[ε]{.unclear}ν [τε]{.greek-omitted} [προς]{.greek-omitted} [αυτους]{.greek-omitted} εις τι ουν εβαπτισθητε οι δε [ειπον]{.greek-omitted} [ειπαν]{.greek-added} εις το [βαπτισμα]{.greek-added} ιωαννου [βαπτισμα]{.greek-omitted}[19:3]{.aside}

ειπεν δε παυλος ιωαννης μεν εβαπτισεν βαπτισμα μετανοιας [παντι]{.greek-added} τω λαω λεγων εις τον ερχομενον μετ αυτον ι[ν]{.unclear}α πιστευσωσιν τουτ εστ[ι]{.unclear}ν εις τον [χριστον]{.greek-abbr} [ιησουν]{.greek-abbr}[19:4]{.aside}

ακουσαντες δε εβαπτισθησαν εις το ονομα του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr}[19:5]{.aside}

και επιθεντος αυτοις του παυλου τας χειρας ηλθεν το [πνευμα]{.greek-abbr} το αγιον επ αυτους ελαλουν τε γλωσσαις και [προεφητευον]{.greek-omitted} [επροφητευον]{.greek-added}[19:6]{.aside}

ησαν δε οι παντες ανδρες ωσει δεκαδυο[19:7]{.aside}

εισελθων δε εις την συναγωγην επαρρησιαζετο επι μηνας τρεις διαλεγομενος και πειθων τα περι τ[η]{.unclear}ς [[τας]{.corr}]{.greek-added} βασιλειας του [θεου]{.greek-abbr}[19:8]{.aside}

ως δε τινες εσκληρυνοντο και ηπειθουν κακολογουντες την οδον [του]{.greek-added} [[θεου]{.greek-abbr}]{.greek-added} ενωπιον του πληθο[υ]{.unclear}ς αποστας απ αυτων [αφωρισεν]{.unclear} [[εχωρισεν]{.corr}]{.greek-added} τους μαθητας [το]{.greek-added} καθ [ημεραν]{.greek-omitted} [ημε]{.greek-added} [ραν]{.greek-added} διαλεγομενος εν τη σχολη τυραννου τινος[19:9]{.aside}

τουτο δε εγενετο επι ετη δυο ωστε παντας τους κατοικουντας την ασιαν ακουσαι τον λογον του [κυριου]{.greek-abbr} [ιησου]{.greek-omitted} ιουδαιους τε και ελλην[ας]{.unclear}[19:10]{.aside}

δυναμεις τε ου τας τυχουσας [εποιει]{.greek-omitted} ο [θεος]{.greek-abbr} [εποιει]{.greek-added} δια των χειρων παυλου[19:11]{.aside}

ωστε και επι τους ασθενουντας [επιφερεσθαι]{.greek-omitted} [αποφερεσθαι]{.greek-added} απο του χρωτος αυτου σουδαρι[α]{.unclear} η σιμικινθια και [αλλασσεσθαι]{.greek-added} [απαλλασσεσθαι]{.corr} απ αυτων τας νοσους τα τε [πνευματα]{.greek-abbr} τα [ακαθαρτα]{.greek-added} [εκπορευεσθαι]{.greek-added} [πονηρα]{.greek-omitted} [εξερχεσθαι]{.greek-omitted} [απ]{.greek-omitted} [αυτων]{.greek-omitted}[19:12]{.aside}

επεχειρησαν δε τινες [και]{.greek-added} απο των περιερχομενων ιουδαιων εξορ[κι]{.unclear}στων ονομαζειν επι τους εχοντας τα [πνευματα]{.greek-abbr} τα πονηρα το ονομα του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} [[χριστου]{.greek-abbr}]{.greek-added} λεγοντες ορκιζομεν υμας τον [ιησουν]{.greek-abbr} ον [ο]{.greek-omitted} παυλος κηρυσσει[19:13]{.aside}

ησαν δε τινες υιοι σκευα [αρχιερεως]{.greek-added} ιουδαιου [αρχιερεως]{.greek-omitted} επτα οι τουτο ποιουντες[19:14]{.aside}

αποκριθεν δε το [πνευμα]{.greek-abbr} το πονηρον ειπεν [αυτοις]{.greek-added} τον [ιησουν]{.greek-abbr} γινωσκω και τον παυλον επισταμαι υμεις δε τινες εστε[19:15]{.aside}

και [ε]{.unclear}φαλλομενος [[ο]{.corr}]{.greek-added} [[φαλλομενος]{.corr}]{.greek-added} [ο]{.greek-added} [[ανθρωπος]{.greek-abbr}]{.greek-added} επ αυτους [ο]{.greek-omitted} [ανθρωπος]{.greek-omitted} εν ω ην το [πνευμα]{.greek-abbr} το πονηρον και [κατακυριευσαν]{.greek-omitted} [κατακυριευσας]{.greek-added} [αυτων]{.greek-omitted} [α[μ]{.unclear}φοτερων]{.greek-added} ισχυσεν κατ αυτων ωστε γυμνους και τετραυματισμενους εκφυγειν εκ του οικου εκεινου[19:16]{.aside}

τουτο δε εγενετο γνωστον πασιν ιουδαιοις τε και ελλησιν τοις κατοικουσιν την εφεσον και επεπεσεν φοβος επι παντας αυτους και εμεγαλυνετο το ονομα του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr}[19:17]{.aside}

πολλοι [τε]{.greek-omitted} [δε]{.greek-added} των πεπιστευκοτων ηρχοντο εξ[ο]{.unclear}μολογουμενοι [[εξεμολογουμενοι]{.corr}]{.greek-added} και αναγγελλ[ο]{.unclear}ντες τας πραξεις αυτων[19:18]{.aside}

ικανοι [δε]{.greek-omitted} [τε]{.greek-added} των τα περιεργα πραξαντων συνενεγκαντες τας βιβλους κατεκαιον ενωπιον παντων και [συνεψηφισαν]{.greek-omitted} [συνεψηφησαν]{.greek-added} τας τιμας αυτων και ευρον αργυριου μυριαδας πεντε[19:19]{.aside}

ουτως κατα κρατος ο λογος του [κυριου]{.greek-abbr} ηυξανεν και ισχυεν[19:20]{.aside}

ως δε επληρωθη ταυτα εθετο ο παυλος εν τω [πνευματι]{.greek-abbr} διελθων την μακεδονιαν και αχαιαν πορευεσθαι εις [ιερουσαλημ]{.greek-omitted} [ιεροσολυμα]{.greek-added} ειπων οτι μετα το γενεσθαι με εκει δει με και ρωμην ιδειν[19:21]{.aside}

αποστειλας δε εις την μακεδονιαν δυο των διακονουντων αυτω τιμοθεον και εραστον αυτος επεσχεν χρονον εις την ασιαν[19:22]{.aside}

εγενετο δε κατα τον καιρον εκεινον ταραχος ουκ ολιγος περι της οδου[19:23]{.aside}

δημητριος γαρ τις [ονοματι]{.greek-omitted} αργυροκοπος ποιων ναους αργυρους αρτεμιδος παρειχετο τοις τεχνιταις εργασιαν ουκ ολιγην[19:24]{.aside}

ους συναθροισας και τους περι τα τοιαυτα εργατας ειπεν ανδρες επιστασθε οτι εκ ταυτης της εργασιας η ευπορια [ημων]{.greek-omitted} [ημιν]{.greek-added} εστιν[19:25]{.aside}

και θεωρειτε και ακουετε οτι ου μονον [της]{.greek-added} εφεσου αλλα σχεδον πασης της ασιας ο παυλος ουτος πεισας μετεστησεν ικανον οχλον λεγων [ο]{.unclear}τι ουκ εισιν θεοι οι δια χειρων γινομενοι[19:26]{.aside}

ου μονον δε τουτο κινδυνευει ημιν το μερος εις απελεγμον ελθειν αλλα και το της μεγαλης θεας ιερον αρτεμιδος εις [ουθεν]{.greek-omitted} [ουδεν]{.greek-added} [λογισθηναι]{.greek-omitted} [λογισθησεται]{.greek-added} μελλειν [δε]{.greek-omitted} [τε]{.greek-added} και καθαιρεισθαι [την]{.greek-omitted} [απο]{.greek-added} [της]{.greek-added} [μεγαλειοτητα]{.greek-omitted} [μεγαλιοτητος]{.greek-added} αυτης ην ολη η ασια και η οικουμενη σεβεται[19:27]{.aside}

[ταυτα]{.greek-added} ακουσαντες [δε]{.greek-omitted} και γενομενοι [πληρεις]{.greek-omitted} [πλη]{.greek-added} [ρης]{.greek-added} θυμου εκραζον λεγοντες μεγαλη η αρτεμις εφεσιων[19:28]{.aside}

και επλησθη η πολις ολη της συγχυσεως ωρμησαν τε ομοθυμαδον εις το θεατρον συναρπασαντες γαιον και αρισταρχον [μακεδονας]{.greek-omitted} [μακεδωνας]{.greek-added} συνεκδημους παυλου[19:29]{.aside}

του δε παυλου βουλομενου εισελθειν εις τον δημον ουκ ειων αυτον οι μαθηται[19:30]{.aside}

τινες δε και των ασιαρχων οντες [αυτω]{.greek-omitted} [αυτου]{.greek-added} φιλοι πεμψαντες προς αυτον παρεκαλουν μη δουναι εαυτον εις το θεατρον[19:31]{.aside}

αλλοι μεν ουν αλλο τι εκραζον ην γαρ η εκκλησια συγκεχυμενη και οι πλειους ουκ ηδεισαν τινος ενεκεν [συνεληλυθεισαν]{.greek-omitted} [συνεληλυθησαν]{.greek-added}[19:32]{.aside}

εκ δε του οχλου [προεβιβασαν]{.greek-omitted} [συνεβιβασαν]{.greek-added} αλεξανδρον [προβαλοντων]{.greek-omitted} [προβαλλοντων]{.greek-added} αυτον των ιουδαιων ο δε αλεξανδρος κατασεισας [την]{.greek-omitted} [τη]{.greek-added} [χειρα]{.greek-omitted} [χειρι]{.greek-added} ηθελεν απολογεισθαι τω δημω[19:33]{.aside}

[επιγνοντες]{.greek-omitted} [επιγνοντων]{.greek-added} δε οτι ιουδαιος εστιν φωνη εγενετο μια εκ παντων ως επι ωρας δυο [κραζοντων]{.greek-omitted} [κραζοντες]{.greek-added} μεγαλη η αρτεμις εφεσιων[19:34]{.aside}

καταστειλας δε ο γραμματευς τον οχλον φησιν ανδρες εφεσιοι τις γαρ εστιν [ανθρωπος]{.greek-omitted} [[ανθρωπων]{.greek-abbr}]{.greek-added} ος ου γινωσκει την εφεσιων πολιν νεωκορον ουσαν της μεγαλης [θεας]{.greek-omitted} αρτεμιδος και του διοπετους[19:35]{.aside}

[αναντιρρητων]{.greek-omitted} [αναντηρρητων]{.greek-added} ουν οντων τουτων δεον εστιν υμας κατεσταλμενους υπαρχειν και μηδεν προπετες πρασσειν[19:36]{.aside}

ηγαγετε γαρ τους ανδρας τουτους ουτε ιεροσυλους ουτε βλασφημουντας την θεον υμων[19:37]{.aside}

ει μεν ουν δημητριος και οι συν αυτω τεχνιται [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} προς τινα λογον αγοραιοι αγονται και ανθυπατοι εισιν [εγκαλειτωσαν]{.greek-omitted} [εγκαλητωσαν]{.greek-added} αλληλοις[19:38]{.aside}

ει δε τι περι ετερων επιζητειτε εν τη εννομω εκκλησια επιλυθησεται[19:39]{.aside}

και γαρ κινδυνευομεν εγκαλεισθαι στασεως περι της σημερον μηδενος αιτιου υπαρχοντος περι ου [ου]{.greek-omitted} δυνησομεθα [δουναι]{.greek-omitted} [αποδουναι]{.greek-added} λογον [περι]{.greek-added} της συστροφης ταυτης [και]{.greek-added} [ταυτα]{.greek-added} [ειπων]{.greek-added} [απελυσεν]{.greek-added} [την]{.greek-added} [εκκλησιαν]{.greek-added}[19:40]{.aside}

### Chapter 20

μετα δε το παυσασθαι τον θορυβον προσκαλεσαμενος ο παυλος τους μαθητας και [παρακαλεσας]{.greek-added} [και]{.greek-added} ασπασαμενος εξηλθεν πορευθηναι εις την μακεδονιαν[20:1]{.aside}

διελθων δε τα μερη εκεινα και παρακαλεσας αυτους λογω πολλω ηλθεν εις την ελλαδα[20:2]{.aside}

ποιησας τε μηνας τρεις γενομενης αυτω επιβουλης υπο των ιουδαιων μελλοντι αναγεσθαι εις την συριαν εγενετο γνωμη του υποστρεφειν δια μακεδονιας[20:3]{.aside}

συνειπετο δε αυτω αχρι της ασιας σωπατρος [πυρρου]{.greek-added} βεροιαιος [θεσσαλονικεων]{.greek-omitted} [θεσσαλονικειων]{.greek-added} δε αρισταρχος και σεκουνδος και γαιος δερβαιος και τιμοθεος ασιανοι δε τυχικος και [τροφιμος]{.greek-omitted} [τροφημος]{.greek-added}[20:4]{.aside}

ουτοι [προσελθοντες]{.greek-omitted} [προελθοντες]{.greek-added} εμενον ημας εν τρωαδι[20:5]{.aside}

ημεις δε εξεπλευσαμεν μετα τας ημερας των αζυμων απο φιλιππων και ηλθομεν προς αυτους εις την τρωαδα [αχρι]{.greek-omitted} [μεχρις]{.greek-added} ημερων πεντε ου [και]{.greek-added} διετριψαμεν ημερας επτα[20:6]{.aside}

εν δε τη μια των σαββατων συνηγμενων [των]{.greek-omitted} [μαθητων]{.greek-omitted} [ημων]{.greek-added} [του]{.greek-added} κλασαι αρτον ο παυλος διελεγετο αυτοις [μελλων]{.greek-omitted} [μελλον]{.greek-added} εξιεναι τη επαυριον παρετεινεν τε τον λογον μεχρι μεσονυκτιου[20:7]{.aside}

ησαν δε λαμπαδες ικαναι εν τω υπερωω ου ημεν συνηγμενοι[20:8]{.aside}

[καθημενος]{.greek-omitted} [καθεζομενος]{.greek-added} δε τις νεανιας ονοματι ευτυχος επι της θυριδος καταφερομενος υπνω βαθει διαλεγομενου του παυλου επι πλειον κατενεχθεις απο του υπνου επεσεν απο του τριστεγου κατω και ηρθη νεκρος[20:9]{.aside}

καταβας δε ο παυλος επεπεσεν αυτω και συμπεριλαβων ειπεν μη θορυβεισθε η γαρ ψυχη αυτου εν αυτω εστιν[20:10]{.aside}

[αναβας]{.greek-omitted} [αναστας]{.greek-added} δε και κλασας αρτον και γευσαμενος [εφ]{.greek-omitted} [αφ]{.greek-added} ικανον τε ομιλησας [αχρι]{.greek-omitted} [αχρις]{.greek-added} αυγης ουτως εξηλθεν[20:11]{.aside}

ηγαγον [δε]{.greek-omitted} [τε]{.greek-added} τον παιδα ζωντα και παρεκληθησαν ου μετριως[20:12]{.aside}

ημεις δε [προσελθοντες]{.greek-omitted} [προελθοντες]{.greek-added} επι το πλοιον ανηχθημεν [εις]{.greek-omitted} [επι]{.greek-added} την [ασσον]{.greek-omitted} [θασσον]{.greek-added} εκειθεν μελλοντες αναλαμβανειν τον παυλον ουτως γαρ ην διατεταγμενος μελλων αυτος πεζευειν[20:13]{.aside}

ως δε [συνεβαλεν]{.greek-omitted} [συνεβαλλεν]{.greek-added} ημιν εις την [ασσον]{.greek-omitted} [θασσον]{.greek-added} αναλαβοντες αυτον ηλθομεν εις [μιτυληνην]{.greek-omitted} [μιτυλινην]{.greek-added}[20:14]{.aside}

κακειθεν αποπλευσαντες τη επιουση κατηντησαμεν [αντικρυ]{.greek-omitted} [αντικρυς]{.greek-added} χιου τη [δε]{.greek-omitted} [τε]{.greek-added} ετερα παρεβαλομεν εις σαμον και μειναντες εν [τρωγυλλιω]{.greek-omitted} [τρογυλλιω]{.greek-added} τη εχομενη [ηλθομεν]{.greek-omitted} [ηλθαμεν]{.greek-added} εις μιλητον[20:15]{.aside}

[εκρινεν]{.greek-omitted} [κεκρικει]{.greek-added} γαρ ο παυλος παραπλευσαι την εφεσον οπως μη γενηται αυτω χρονοτριβησαι εν τη ασια εσπευδεν γαρ ει δυνατον ην αυτω την ημεραν της πεντηκοστης γενεσθαι εις ιεροσολυμα[20:16]{.aside}

απο δε της μιλητου πεμψας εις εφεσον μετεκαλεσατο τους πρεσβυτερους της εκκλησιας[20:17]{.aside}

ως δε παρεγενοντο προς αυτον [ομοθυμαδον]{.greek-added} ειπεν αυτοις υμεις επιστασθε [αδελφοι]{.greek-added} απο πρωτης [ημερας]{.greek-omitted} αφ ης [ημερας]{.greek-added} επεβην εις την ασιαν [πως]{.greek-omitted} [ως]{.greek-added} μεθ υμων τον παντα χρονον εγενομην[20:18]{.aside}

δουλευων τω [κυριω]{.greek-abbr} μετα πασης ταπεινοφροσυνης και πολλων δακρυων και πειρασμων των συμβαντων μοι εν ταις επιβουλαις των ιουδαιων[20:19]{.aside}

ως ουδεν υπεστειλαμην των συμφεροντων του μη αναγγειλαι υμιν και διδαξαι υμας δημοσια και κατ οικους[20:20]{.aside}

διαμαρτυρομενος ιουδαιοις τε και ελλησιν την εις τον [θεον]{.greek-abbr} μετανοιαν και π[ι]{.unclear}στιν την εις τον [κυριον]{.greek-abbr} ημων [ιησουν]{.greek-abbr} [[χριστον]{.greek-abbr}]{.greek-added}[20:21]{.aside}

και νυν ιδου εγω δεδεμενος τω [πνευματι]{.greek-abbr} πορευομαι εις [ιερουσαλημ]{.greek-abbr} τα εν αυτη συναντησοντα μοι μη ειδως[20:22]{.aside}

πλην οτι [μοι]{.greek-added} το [πνευμα]{.greek-abbr} το αγιον κατα πολιν διαμαρτυρεται [μοι]{.greek-added} [λεγον]{.greek-omitted} [λεγων]{.greek-added} οτι δεσμα [με]{.greek-omitted} και θλιψεις [με]{.greek-added} μενουσιν[20:23]{.aside}

αλλ ουδενος λογον ποιουμαι ουδε εχω την ψυχην μου τιμιαν εμαυτω ως τελειωσαι τον δρομον μου μετα χαρας και την διακονιαν ην ελαβον παρα του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} διαμαρτυρασθαι το ευαγγελιον της χαριτος του [θεου]{.greek-abbr}[20:24]{.aside}

και νυν ιδου εγω οιδα οτι ουκετι οψεσθε το προσωπον μου υμεις παντες εν οις διηλθον κηρυσσων την βασιλειαν του [θεου]{.greek-abbr}[20:25]{.aside}

[διοτι]{.greek-omitted} [διο]{.greek-added} μαρτυρομαι υμιν εν τη σημερον ημερα οτι καθαρος [εγω]{.greek-omitted} [ειμι]{.greek-added} απο του [αιματος]{.greek-omitted} [αιμα]{.greek-added} [τος]{.greek-added} παντων[20:26]{.aside}

ου γαρ υπεστειλαμην του μη αναγγειλαι υμιν πασαν την βουλην του [θεου]{.greek-abbr}[20:27]{.aside}

προσεχετε [ουν]{.greek-omitted} εαυτοις και παντι τω ποιμνιω εν ω υμας το [πνευμα]{.greek-abbr} το αγιον εθετο επισκοπους ποιμαινειν την εκκλησιαν του [κυριου]{.greek-abbr} και [θεου]{.greek-abbr} ην περιεποιησατο δια του [αιματος]{.greek-added} [του]{.greek-added} ιδιου [αιματος]{.greek-omitted}[20:28]{.aside}

εγω γαρ οιδα [τουτο]{.greek-omitted} οτι εισελευσονται μετα την [αφιξιν]{.greek-omitted} [αφηξιν]{.greek-added} μου λυκοι βαρεις εις υμας μη φειδομενοι του ποιμνιου[20:29]{.aside}

και εξ υμων αυτων αναστησονται ανδρες λαλουντες διεστραμμενα του αποσπαν τους μαθητας οπισω αυτων[20:30]{.aside}

διο γρηγορειτε μνημονευοντες οτι τριετιαν νυκτα και ημεραν ουκ επαυσαμην μετα δακρυων νουθετων ενα εκαστον [υμων]{.greek-added}[20:31]{.aside}

και τα νυν παρατιθεμαι υμας αδελφοι τω [θεω]{.greek-abbr} και τω λογω της χαριτος αυτου τω δυναμενω εποικοδομησαι και δουναι υμιν κληρονομιαν εν τοις ηγιασμενοις πασιν[20:32]{.aside}

αργυριου η χρυσιου η ιματισμου ουδενος επεθυμησα[20:33]{.aside}

αυτοι γινωσκετε οτι ταις χρειαις μου και τοις ουσιν μετ εμου υπηρετησαν αι χειρες αυται[20:34]{.aside}

παντα υπεδειξα υμιν οτι ουτως κοπιωντας δει αντιλαμβανεσθαι των ασθενουντων μνημονευειν τε των λογων του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} οτι αυτος ειπεν μακαριον εστιν μαλλον διδοναι η λαμβανειν[20:35]{.aside}

και ταυτα ειπων θεις τα γονατα αυτου συν πασιν αυτοις προσηυξατο[20:36]{.aside}

[εγενετο]{.greek-added} [δε]{.greek-added} ικανος [δε]{.greek-omitted} [εγενετο]{.greek-omitted} κλαυθμος παντων και [επι]{.greek-added} [επιπεσοντες]{.greek-omitted} [πεσοντες]{.greek-added} επι τον τραχηλον του παυλου κατεφιλουν αυτον[20:37]{.aside}

[οδυνωμενοι]{.greek-omitted} [οδυνομενοι]{.greek-added} μαλιστα επι τω λογω ω ειρηκει οτι ουκετι μελλουσιν το προσωπον αυτου θεωρειν προεπεμπον δε αυτον εις το πλοιον[20:38]{.aside}

### Chapter 21

ως δε εγενετο αναχθηναι ημας αποσπασθεντας απ αυτων ευθυδρομησαντες ηλθομεν εις την [κων]{.greek-omitted} [κω]{.greek-added} τη δε εξης εις [την]{.greek-omitted} ροδον κακειθεν εις παταρα[21:1]{.aside}

και [ευροντες]{.greek-omitted} [ευρωντες]{.greek-added} πλοιον [διαπερων]{.greek-omitted} [διαπερον]{.greek-added} εις φοινικην επιβαντες ανηχθημεν[21:2]{.aside}

αναφανεντες δε την κυπρον και [καταλιποντες]{.greek-omitted} [καταλειποντες]{.greek-added} αυτην ευωνυμον [επλεομεν]{.greek-omitted} [επλεωμεν]{.greek-added} εις συριαν και κατηχθημεν εις τυρον [εκεισε]{.greek-omitted} [εκεισαι]{.greek-added} γαρ ην το πλοιον αποφορτιζομενον τον γομον[21:3]{.aside}

[και]{.greek-omitted} [ου]{.greek-added} ανευροντες μαθητας επεμειναμεν αυτου ημερας επτα οιτινες [δια]{.greek-added} [του]{.greek-added} [[πνευματος]{.greek-abbr}]{.greek-added} τω παυλω ελεγον [δια]{.greek-omitted} [του]{.greek-omitted} [πνευματος]{.greek-omitted} μη αναβαινειν εις [ιερουσαλημ]{.greek-omitted} [ιεροσολυμα]{.greek-added}[21:4]{.aside}

οτε δε εγενετο ημας εξαρτισαι τας ημερας εξελθοντες επορευομεθα προπεμποντων ημας παντων συν [γυναιξιν]{.greek-omitted} [γυναιξι]{.greek-added} και τεκνοις εως εξω της πολεως και θεντες τα γονατα επι τον αιγιαλον προσηυξαμεθα[21:5]{.aside}

και ασπασαμενοι αλληλους [επεβημεν]{.greek-omitted} [ανεβημεν]{.greek-added} εις το πλοιον εκεινοι δε υπεστρεψαν εις τα ιδια[21:6]{.aside}

ημεις δε τον πλουν [διανυσαντες]{.greek-omitted} [διανοισαντες]{.greek-added} απο τυρου κατηντησαμεν εις πτολεμαιδα και ασπασαμενοι τους αδελφους εμειναμεν ημεραν μιαν παρ αυτοις[21:7]{.aside}

τη δε επαυριον εξελθοντες [οι]{.greek-omitted} [περι]{.greek-omitted} [τον]{.greek-omitted} [παυλον]{.greek-omitted} [ηλθον]{.greek-omitted} [ηλθομεν]{.greek-added} εις καισαρειαν και εισελθοντες εις τον οικον [φι]{.greek-added} [φιλιππου]{.greek-omitted} [λιππου]{.greek-added} του ευαγγελιστου οντος εκ των επτα εμειναμεν παρ αυτω[21:8]{.aside}

τουτω δε ησαν θυγατερες παρθενοι τεσσαρες προφητευουσαι[21:9]{.aside}

επιμενοντων δε ημων ημερας πλειους κατηλθεν τις απο της ιουδαιας προφητης ονοματι αγαβος[21:10]{.aside}

και ελθων προς ημας και αρας την ζωνην του παυλου δησας [τε]{.greek-omitted} [αυτου]{.greek-omitted} [εαυτου]{.greek-added} τους ποδας και τας χειρας ειπεν ταδε λεγει το [πνευμα]{.greek-abbr} το αγιον τον ανδρα ου εστιν η ζωνη αυτη ουτως δησουσιν εν [ιερουσαλημ]{.greek-abbr} οι ιουδαιοι και παραδωσουσιν εις χειρας εθνων[21:11]{.aside}

ως δε ηκουσαμεν ταυτα παρεκαλουμεν ημεις τε και οι εντοπιοι του μη αναβαινειν αυτον εις [ιερουσαλημ]{.greek-abbr}[21:12]{.aside}

[τοτε]{.greek-added} απεκριθη [τε]{.greek-omitted} [δε]{.greek-added} ο παυλος [και]{.greek-added} [ειπεν]{.greek-added} τι ποιειτε κλαιοντες και συνθρυπτοντες μου την καρδιαν εγω γαρ ου μονον δεθηναι αλλα και αποθανειν εις [ιερουσαλημ]{.greek-abbr} ετοιμως εχω υπερ του ονοματος του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr}[21:13]{.aside}

μη πειθομενου δε αυτου ησυχασαμεν ειποντες το θελημα του [κυριου]{.greek-abbr} [γενεσθω]{.greek-omitted} [γινεσθω]{.greek-added}[21:14]{.aside}

μετα δε τας ημερας ταυτας επισκευασαμενοι [ανεβαινομεν]{.greek-omitted} [ανεβαινωμεν]{.greek-added} εις [ιερουσαλημ]{.greek-omitted} [ιεροσολυμα]{.greek-added}[21:15]{.aside}

συνηλθον δε και [τινες]{.greek-added} των μαθητων απο καισαρειας συν ημιν αγοντες παρ ω ξενισθωμεν μνασωνι τινι κυπριω αρχαιω μαθητη[21:16]{.aside}

γενομενων δε ημων εις ιεροσολυμα ασμενως [εδεξαντο]{.greek-omitted} [απεδεξαντο]{.greek-added} ημας οι αδελφοι[21:17]{.aside}

τη δε επιουση [εισηει]{.greek-omitted} [εισιη]{.greek-added} ο παυλος συν ημιν προς ιακωβον παντες [τε]{.greek-omitted} [δε]{.greek-added} παρεγενοντο οι πρεσβυτεροι[21:18]{.aside}

και ασπασαμενος αυτους εξηγειτο καθ εν εκαστον ων εποιησεν ο [θεος]{.greek-abbr} εν τοις εθνεσιν δια της διακονιας αυτου[21:19]{.aside}

οι δε [ακουσαντες]{.greek-omitted} [ακουοντες]{.greek-added} εδοξαζον τον [κυριον]{.greek-abbr} ειποντες αυτω θεωρεις αδελφε ποσαι μυριαδες εισιν ιουδαιων των πεπιστευκοτων και παντες ζηλωται του νομου υπαρχουσιν[21:20]{.aside}

κατηχηθησαν δε περι σου οτι αποστασιαν διδασκεις απο μωυσεως τους κατα τα εθνη παντας ιουδαιους λεγων μη περιτεμνειν αυτους τα τεκνα μηδε τοις [εθεσιν]{.greek-omitted} [εθεσι]{.greek-added} περιπατειν[21:21]{.aside}

τι ουν εστιν παντως δει πλ[η]{.unclear}θος συνελθειν ακουσονται γαρ οτι εληλυθας[21:22]{.aside}

τουτο ουν ποιησον ο [λεγομεν]{.greek-added} σοι [λεγομεν]{.greek-omitted} εισιν ημιν ανδρες τεσσαρες ευχην εχοντες εφ εαυτων[21:23]{.aside}

τουτους παραλαβων αγνισθητι συν αυτοις και δαπανησον επ [αυτοις]{.greek-omitted} [αυτους]{.greek-added} ινα [ξυρησωνται]{.greek-omitted} [ξυρισονται]{.greek-added} την κεφαλην και [γνωσιν]{.greek-omitted} [γνωσονται]{.greek-added} παντες οτι ων [κατηχηνται]{.greek-omitted} [κατηχεινται]{.greek-added} περι σου ουδεν εστιν αλλα στοιχεις και αυτος τον νομον φυλασσων[21:24]{.aside}

περι δε των πεπιστευκοτων εθνων ημεις επεστειλαμεν κριναντες [φυλασσεσθαι]{.greek-added} μηδεν [τοιουτον]{.greek-omitted} [τοιουτο]{.greek-added} τηρειν αυτους ει μη φυλασσεσθαι αυτους [αλλα]{.greek-added} το τε [ειδωλοθυτον]{.greek-omitted} [ειδολοθυτον]{.greek-added} και το αιμα και [πνικτον]{.greek-omitted} [πνηκτον]{.greek-added} και πορνειαν[21:25]{.aside}

τοτε ο παυλος παραλαβων τους ανδρας τη εχομενη ημερα συν αυτοις αγνισθεις εισηει εις το ιερον διαγγελλων την εκπληρωσιν των ημερων του αγνισμου εως ου [προσηνεχθη]{.greek-omitted} [προσενεχθη]{.greek-added} υπερ ενος εκαστου αυτων η προσφορα[21:26]{.aside}

ως δε εμελλον αι επτα ημεραι [συντελεισθαι]{.greek-omitted} [συμπληρου]{.greek-added} [σθαι]{.greek-added} οι απο της ασιας ιουδαιοι θεασαμενοι αυτον εν τω ιερω συνεχεον παντα τον οχλον και επεβαλον [επ]{.greek-added} [αυτον]{.greek-added} τας χειρας [επ]{.greek-omitted} [αυτον]{.greek-omitted}[21:27]{.aside}

κραζοντες ανδρες ισραηλιται βοηθειτε ουτος εστιν ο [ανθρωπος]{.greek-abbr} ο κατα του λαου και του νομου και του τοπου τουτου παντας πανταχου διδασκων ετι τε και ελληνας εισηγαγεν εις το ιερον και κεκοινωκεν τον αγιον τοπον τουτον[21:28]{.aside}

ησαν γαρ [εωρακοτες]{.greek-omitted} [προεωρακοτες]{.greek-added} [τροφιμον]{.greek-omitted} [τροφημον]{.greek-added} τον εφεσιον εν τη πολει συν αυτω ον ενομιζον οτι εις το ιερον εισηγαγεν ο παυλος[21:29]{.aside}

εκινηθη τε η πολις ολη και εγενετο συνδρομη του λαου και επιλαβομενοι του παυλου ειλκον αυτον εξω του ιερου και ευθεως εκλεισθησαν αι θυραι[21:30]{.aside}

ζητουντων δε αυτον αποκτειναι ανεβη φασις τω χιλιαρχω της σπειρης οτι [ολη]{.greek-omitted} συγκεχυται [η]{.greek-added} [ιερουσαλημ]{.greek-abbr}[21:31]{.aside}

ος εξαυτης παραλαβων στρατιωτας και εκατονταρχους [κατεδραμεν]{.greek-omitted} [επ]{.greek-omitted} [επεδραμεν]{.greek-added} [προς]{.greek-added} αυτους οι δε ιδοντες τον χιλιαρχον και τους στρατιωτας επαυσαντο τυπτοντες τον παυλον[21:32]{.aside}

[τοτε]{.greek-added} εγγισας [δε]{.greek-omitted} ο χιλιαρχος επελαβετο αυτου και εκελευσεν δεθηναι [αλυσεσιν]{.greek-omitted} [αλυσεσι]{.greek-added} δυσιν και επυνθανετο τις αν ειη και τι εστιν πεποιηκως[21:33]{.aside}

αλλοι δε αλλο τι [εβοων]{.greek-omitted} [επεβοων]{.greek-added} εν τω οχλω μη [δυναμενος]{.greek-omitted} [δυναμενου]{.greek-added} δε [αυτου]{.greek-added} γνωναι το ασφαλες δια τον θορυβον εκελευσεν αγεσθαι αυτον εις την παρεμβολην[21:34]{.aside}

οτε δε εγενετο επι τους αναβαθμους συνεβη βασταζεσθαι αυτον υπο των στρατιωτων δια την βιαν του οχλου[21:35]{.aside}

[ηκολουθει]{.greek-omitted} [ηκολουθη]{.greek-added} γαρ το πληθος του λαου [κραζον]{.greek-omitted} [κραζοντες]{.greek-added} αιρε αυτον[21:36]{.aside}

μελλων τε [εισαγεσθαι]{.greek-omitted} εις την παρεμβολην [αγεσθαι]{.greek-added} ο παυλος λεγει τω χιλιαρχω ει εξεστιν μοι ειπειν [τι]{.greek-added} προς σε ο δε εφη ελληνιστι γινωσκεις[21:37]{.aside}

ουκ αρα συ ει ο αιγυπτιος ο προ τουτων των ημερων αναστατωσας και εξαγαγων εις την ερημον τους τετρακισχιλιους ανδρας των σικαριων[21:38]{.aside}

ειπεν δε ο παυλος εγω [ανθρωπος]{.greek-omitted} μεν ειμι [[ανθρωπος]{.greek-abbr}]{.greek-added} ιουδαιος ταρσευς της [κιλικιας]{.greek-omitted} [κιληκιας]{.greek-added} ουκ [ασημου]{.greek-omitted} [ασιμου]{.greek-added} πολεως πολιτης δεομαι δε σου [επιτρεψον]{.greek-omitted} [επιτρεψαι]{.greek-added} μοι λαλησαι προς τον λαον[21:39]{.aside}

επιτρεψαντος δε αυτου ο παυλος εστως επι των αναβαθμων [κατεσεισεν]{.greek-omitted} [κατεσεισε]{.greek-added} τη χειρι τω λαω πολλης δε σιγης γενομενης [προσεφωνει]{.greek-omitted} [προσεφωνησεν]{.greek-added} τη εβραιδι δι[α]{.unclear}λεκτω λεγων[21:40]{.aside}

### Chapter 22

ανδρες αδελφοι και [πατερες]{.greek-abbr} ακουσατε μου της προς υμας νυνι απολογιας[22:1]{.aside}

ακουσαντες δε οτι τη εβραιδι διαλεκτω προσεφωνει αυτοις μαλλον παρεσχον ησυχιαν και φησιν[22:2]{.aside}

εγω μεν ειμι ανηρ ιουδαιος γεγεννημενος εν ταρσω της κιλικιας ανατεθραμμενος δε εν τη πολει ταυτη παρα τους ποδας γαμαλιηλ πεπαιδευμενος κατα ακριβειαν του πατρωου νομου ζηλωτης υπαρχων του [θεου]{.greek-abbr} καθως παντες υμεις εστε σημερον[22:3]{.aside}

ος ταυτην την οδον εδιωξα αχρι θανατου δεσμευων και παραδιδους εις φυλακας ανδρας τε και γυναικας[22:4]{.aside}

ως και ο αρχιερευς μαρτυρει μοι και παν το [πρεσβυτεριον]{.greek-omitted} [πρεσβυτερειον]{.greek-added} παρ ων και επιστολας [δε]{.greek-added} [δεξαμενος]{.greek-omitted} [ξαμενος]{.greek-added} προς τους αδελφους εις δαμασκον επορευομην αξων και τους [εκεισε]{.greek-omitted} [εκεισαι]{.greek-added} οντας δεδεμενους εις [ιερουσαλημ]{.greek-abbr} ινα [τιμωρηθωσιν]{.greek-omitted} [τιμωριθωσιν]{.greek-added}[22:5]{.aside}

εγενετο δε [πορευομενω]{.greek-added} μοι [πορευομενω]{.greek-omitted} και εγγιζοντι τη δαμασκω περι μεσημβριαν εξαιφνης εκ του [ουρανου]{.greek-abbr} [περιαστραψαι]{.greek-omitted} [περιηστραψεν]{.greek-added} φως ικανον περι εμε[22:6]{.aside}

επεσα τε εις το εδαφος και ηκουσα φωνης λεγουσης μοι σαουλ σαουλ τι με διωκεις[22:7]{.aside}

εγω δε απεκριθην τις ει [κυριε]{.greek-abbr} ειπεν [τε]{.greek-omitted} [δε]{.greek-added} προς με εγω ειμι [ιησους]{.greek-abbr} ο ναζωραιος ον συ διωκεις[22:8]{.aside}

οι δε συν εμοι οντες το μεν φως εθεασαντο και εμφοβοι εγενοντο την δε φωνην ουκ ηκουσαν του λαλουντος μοι[22:9]{.aside}

ειπον δε τι ποιησω [κυριε]{.greek-abbr} ο δε [κυριος]{.greek-abbr} ειπεν προς με αναστας πορευου εις δαμασκον κακει σοι λαληθησεται περι παντων ων τετακται σοι ποιησαι[22:10]{.aside}

ως δε ουκ ενεβλεπον απο της δοξης του φωτος εκεινου χειραγωγουμενος υπο των συνοντων μοι [ηλθον]{.greek-omitted} [εισηλθον]{.greek-added} εις δαμασκον[22:11]{.aside}

ανανιας δε τις ανηρ [ευσεβης]{.greek-omitted} [ευλαβης]{.greek-added} κατα τον νομον μαρτυρουμενος υπο παντων των κατοικουντων [εν]{.greek-added} [δαμασκω]{.greek-added} ιουδαιων[22:12]{.aside}

ελθων προς με και επιστας ειπεν μοι σαουλ αδελφε αναβλεψον καγω αυτη τη ωρα ανεβλεψα εις αυτον[22:13]{.aside}

ο δε ειπεν ο [θεος]{.greek-abbr} των [πατερων]{.greek-abbr} ημων [προεχειρισατο]{.greek-omitted} [προεχειρησατο]{.greek-added} σε γνωναι το θελημα αυτου και ιδειν τον δικαιον και ακουσαι φωνην εκ του στοματος αυτου[22:14]{.aside}

οτι εση μαρτυς αυτω προς παντας [ανθρωπους]{.greek-abbr} ων εωρακας και ηκουσας[22:15]{.aside}

και νυν τι μελλεις αναστας βαπτισαι και απολουσαι τας αμαρτιας σου επικαλεσαμενος το ονομα [του]{.greek-omitted} [αυτου]{.greek-added} [κυριου]{.greek-omitted}[22:16]{.aside}

εγενετο δε μοι υποστρεψαντι εις [ιερουσαλημ]{.greek-abbr} και προσευχομενου μου εν τω ιερω γενεσθαι με εν εκστασει[22:17]{.aside}

και ιδειν αυτον λεγοντα μοι σπευσον και εξελθε εν ταχει εξ [ιερουσαλημ]{.greek-abbr} διοτι ου παραδεξονται σου την [μαρτυριαν]{.greek-omitted} [μαρτυρειαν]{.greek-added} περι εμου[22:18]{.aside}

καγω ειπον [κυριε]{.greek-abbr} αυτοι επιστανται οτι εγω ημην φυλακιζων και δερων κατα τας συναγωγας τους πιστευοντας επι σε[22:19]{.aside}

και οτε [εξεχειτο]{.greek-omitted} [εξεχυνετο]{.greek-added} το αιμα στεφανου του μαρτυρος σου και αυτος ημην εφεστως και συνευδοκων τη αναιρεσει αυτου [φυλασσων]{.greek-omitted} [φυλασσον]{.greek-added} τα ιματια των αναιρουντων αυτον[22:20]{.aside}

και ειπεν προς με πορευ[ου]{.greek-supplied} οτι εγω εις εθνη μακραν εξαποστελω σε[22:21]{.aside}

ηκουον δε αυτου αχρι τουτου του λογου και επηραν την φωνην αυτων λεγοντες αιρε απο της γης τον τοιουτον ου γαρ [καθηκεν]{.greek-omitted} [καθηκει]{.greek-added} αυτον ζην[22:22]{.aside}

[κραζοντων]{.greek-omitted} [κραυγαζοντων]{.greek-added} δε αυτων και ριπτουντων τα ιματια και κονιορτον βαλλοντων εις τον αερα[22:23]{.aside}

εκελευσεν [αυτον]{.greek-omitted} ο χιλιαρχος [αγεσθαι]{.greek-omitted} [εισαγεσθαι]{.greek-added} [αυτον]{.greek-added} εις την παρεμβολην ειπων μαστιξιν ανεταζεσθαι αυτον ινα επιγνω δι ην αιτιαν ουτως επεφωνουν [αυτω]{.greek-omitted} [αυτον]{.greek-added}[22:24]{.aside}

ως δε [προετεινεν]{.greek-omitted} [προετεινον]{.greek-added} αυτον τοις ιμασιν ειπεν προς τον εστωτα εκατονταρχον ο παυλος ει [ανθρωπον]{.greek-abbr} ρωμαιον και ακατακριτον εξεστιν υμιν μαστιζειν[22:25]{.aside}

ακουσας δε ο εκατονταρχος προσελθων [απηγγειλεν]{.greek-omitted} τω χιλιαρχω [απηγγειλεν]{.greek-added} [αυτω]{.greek-added} λεγων [ορα]{.greek-omitted} τι μελλεις ποιειν ο γαρ [ανθρωπος]{.greek-abbr} ουτος ρωμα[ι]{.greek-supplied}[ο]{.unclear}ς εστιν[22:26]{.aside}

προσελθων δε ο χιλιαρχος ειπεν αυτω λεγε μοι [ει]{.greek-omitted} συ ρωμαιος ει ο δε εφη ναι[22:27]{.aside}

απεκριθη [τε]{.greek-omitted} [δε]{.greek-added} ο χιλιαρχος εγω πολλου κεφαλαιου την πολιτειαν ταυτην εκτησαμην ο δε παυλος εφη εγω δε και γεγεννημαι[22:28]{.aside}

ευθεως ουν απεστησαν απ αυτου οι μελλοντες αυτον ανεταζειν και ο χιλιαρχος δε εφοβηθη επιγνους οτι ρωμαιος εστιν και οτι ην αυτον δεδεκως[22:29]{.aside}

τη δε επαυριον βουλομενος γνωναι το ασφαλες το τι [κατηγορειται]{.greek-omitted} [κατηγορειτο]{.greek-added} [παρα]{.greek-omitted} [υπο]{.greek-added} των ιουδαιων ελυσεν αυτον [απο]{.greek-omitted} [των]{.greek-omitted} [δεσμων]{.greek-omitted} και εκελευσεν [ελθειν]{.greek-omitted} [συνελθειν]{.greek-added} τους αρχιερεις και [ολον]{.greek-omitted} [παν]{.greek-added} το συνεδριον [αυτων]{.greek-omitted} και καταγαγων τον παυλον εστησεν [εις]{.greek-omitted} [αυτους]{.greek-omitted} [αυτον]{.greek-added} [εν]{.greek-added} [μεσω]{.greek-added} [αυτων]{.greek-added}[22:30]{.aside}

### Chapter 23

ατενισας δε ο παυλος τω συνεδριω ειπεν ανδρες αδελφοι εγω παση συνειδησει αγαθη πεπολιτευμαι τω [θεω]{.greek-abbr} αχρι ταυτης της ημερας[23:1]{.aside}

ο δε αρχιερευς ανανιας [επεταξεν]{.greek-omitted} τοις παρεστωσιν αυτω [επεταξεν]{.greek-added} τυπτειν αυτου το στομα[23:2]{.aside}

τοτε ο παυλος προς αυτον ειπεν τυπτειν σε μελλει ο [θεος]{.greek-abbr} τοιχε κεκονιαμενε και συ καθη κρινων με κατα τον νομον και παρανομων κελευεις με τυπτεσθαι[23:3]{.aside}

οι δε παρεστωτες ειπον τον αρχιερεα του [θεου]{.greek-abbr} [λοιδορεις]{.greek-omitted} [λοιδωρεις]{.greek-added}[23:4]{.aside}

εφη τε ο παυλος ουκ ηδειν αδελφοι οτι εστιν αρχιερευς γεγραπται γαρ [οτι]{.greek-added} αρχοντα του λαου σου ουκ ερεις κακως[23:5]{.aside}

γνους δε ο παυλος οτι το εν μερος [εστιν]{.greek-omitted} [εστι]{.greek-added} σαδδουκαιων το δε ετερον φαρισαιων εκραξεν εν τω συνεδριω ανδρες αδελφοι εγω φαρισαιος ειμι [υιος]{.greek-abbr} [φαρισαιου]{.greek-omitted} [φαρισαιων]{.greek-added} περι ελπιδος και αναστασεως νεκρ[ω]{.unclear}ν εγω [κρινομαι]{.greek-omitted} [κρινωμαι]{.greek-added}[23:6]{.aside}

τουτο δε αυτου [λαλησαντος]{.greek-omitted} [ειπον[τ]{.unclear}ος]{.greek-added} εγενετο στασις των φαρισαιων και [σαδδουκαιων]{.greek-added} [και]{.greek-added} εσχισθη το πληθος[23:7]{.aside}

σαδδουκαιοι μεν γαρ λεγουσιν μη ειναι αναστασιν [μηδε]{.greek-omitted} [μητε]{.greek-added} αγγελον μητε [πνευμα]{.greek-abbr} φαρισαιοι δε [ομολογουσιν]{.greek-omitted} [ομολογουσι]{.greek-added} τα α[μ]{.unclear}φοτερα[23:8]{.aside}

εγενετο δε κραυγη μεγαλη και ανασταντες [οι]{.greek-omitted} [τινες]{.greek-added} [των]{.greek-added} [γραμματεις]{.greek-omitted} [γραμματεων]{.greek-added} του μερους των φαρισαιων διεμαχοντο [προς]{.greek-added} [αλληλους]{.greek-added} λεγοντες ουδεν κακον ευρισκομεν εν τω [ανθρωπω]{.greek-abbr} τουτω ει δε [πνευμα]{.greek-abbr} ελαλησεν αυτω η αγγελος μη θεομαχωμεν[23:9]{.aside}

πολλης δε γενομενης στασεως [ευλαβηθεις]{.greek-omitted} [φοβηθεις]{.greek-added} ο χιλιαρχος μη διασπασθη ο παυλος υπ αυτων εκελευσεν το στρατευμα [καταβηναι]{.greek-omitted} [καταβαν]{.greek-added} [και]{.greek-omitted} αρπασαι αυτον εκ μεσου αυτων αγειν τε εις την παρεμβολην[23:10]{.aside}

τη δε επιουση νυκτι επιστας αυτω ο [κυριος]{.greek-abbr} ειπεν θαρσει παυλε ως γαρ διεμαρτυρω τα περι εμου εις [ιερουσαλημ]{.greek-abbr} ουτως σε δει και [εις]{.greek-omitted} [εν]{.greek-added} [τη]{.greek-added} [ρωμην]{.greek-omitted} [ρωμη]{.greek-added} [μαρτυρησαι]{.greek-omitted} [μαρτυρισαι]{.greek-added}[23:11]{.aside}

γενομενης δε ημερας ποιησαντες [τινες]{.greek-omitted} [των]{.greek-omitted} [ιουδαιων]{.greek-omitted} συστροφην [οι]{.greek-added} [ιουδαιοι]{.greek-added} [ανεθεματισαν]{.greek-omitted} [ανεθεματ[η]{.unclear}σαν]{.greek-added} εαυτους [λεγοντες]{.greek-omitted} μητε φαγειν μητε πιειν εως ου [αποκτεινωσιν]{.greek-omitted} [αποκτενωσι]{.greek-added} τον παυλον[23:12]{.aside}

ησαν δε πλειους τεσσαρακοντα οι ταυτην την [συνωμοσιαν]{.greek-omitted} [συνομοσιαν]{.greek-added} πεποιηκοτες[23:13]{.aside}

οιτινες προσελθοντες τοις αρχιερευσιν και τοις πρεσβυτεροις ειπον αναθεματι [ανεθεματισαμεν]{.greek-omitted} [αναθεματησαμεν]{.greek-added} εαυτους μηδενος γευσασθαι εως ου αποκτεινωμεν τον παυλον[23:14]{.aside}

νυν ουν υμεις [εμφα]{.greek-added} [εμφανισατε]{.greek-omitted} [νισατε]{.greek-added} τω χιλιαρχω συν τω συνεδριω οπως αυριον αυτον καταγαγη προς υμας ως μελλοντας διαγινωσκειν ακριβεστερον τα περι αυτου ημεις δε προ του εγγισαι αυτον ετοιμοι εσμεν του ανελειν αυτον[23:15]{.aside}

ακουσας δε ο [υιος]{.greek-abbr} της αδελφης παυλου [το]{.greek-omitted} [την]{.greek-added} [ενεδρον]{.greek-omitted} [ενεδραν]{.greek-added} παραγενομενος και εισελθων εις την παρεμβολην απηγγειλεν τω παυλω[23:16]{.aside}

προσκαλεσαμενος δε ο παυλος ενα των εκατονταρχων εφη τον νεανιαν τουτον απαγαγε προς τον [χιλιαρχον]{.unclear} [[ταριαρχον]{.corr}]{.greek-added} εχει γαρ [απαγγειλαι]{.greek-added} τι [απαγγειλαι]{.greek-omitted} αυτω[23:17]{.aside}

ο μεν ουν παραλαβων αυτον ηγαγεν προς τον χιλιαρχον και φησιν ο δεσμιος παυλος προσκαλεσαμενος με ηρωτησεν τουτον τον νεανιαν αγαγειν προς σε εχοντα τι λαλησαι σοι[23:18]{.aside}

επιλαβομενος δε [της]{.greek-added} της χειρος αυτου ο χιλιαρχος και αναχωρησας κατ ιδιαν επυνθανετο τι εστιν ο εχεις απαγγειλαι μοι[23:19]{.aside}

ειπεν δε οτι οι ιουδαιοι συνεθεντο του ερωτησαι σε οπως αυριον [τον]{.greek-added} [παυλον]{.greek-added} [καταγαγης]{.greek-added} εις το συνεδριον [αυτων]{.greek-added} [καταγαγης]{.greek-omitted} [τον]{.greek-omitted} [παυλον]{.greek-omitted} ως [μελλοντα]{.greek-omitted} [μελλοντων]{.greek-added} τι ακριβεστερον πυνθανεσθαι περι αυτου[23:20]{.aside}

συ ουν μη πεισθης αυτοις [ενεδρευουσιν]{.greek-omitted} [ενεδρευουσι]{.greek-added} γαρ αυτον εξ αυτων ανδρες πλειους τεσσαρακοντα οιτινες [ανεθεματισαν]{.greek-omitted} [ανεθεματησαν]{.greek-added} εαυτους [μητε]{.greek-omitted} [μη]{.greek-added} φαγειν μητε πιειν εως ου ανελωσιν αυτον και νυν ετοιμοι εισιν προσδεχομενοι την απο σου επαγγελιαν[23:21]{.aside}

ο μεν ουν χιλιαρχος απελυσεν τον νεανιαν παραγγειλας μηδενι εκλαλησαι οτι ταυτα [ενεφανισας]{.greek-omitted} [ενεφανησας]{.greek-added} προς με[23:22]{.aside}

και προσκαλεσαμενος δυο τινας των εκατονταρχων ειπεν ετοιμασατε στρατιωτας διακοσιους οπως πορευθωσιν [εως]{.greek-omitted} [εις]{.greek-added} [καισαρειας]{.greek-omitted} [καισαρειαν]{.greek-added} και ιππεις εβδομηκοντα και δεξιολαβους διακοσιους απο τριτης ωρας της νυκτος[23:23]{.aside}

κτηνη τε παραστησαι ινα επιβιβασαντες τον παυλον [διασωσωσιν]{.greek-omitted} [διασωσωσι]{.greek-added} προς [φηλικα]{.greek-omitted} [φιλικα]{.greek-added} τον ηγεμονα[23:24]{.aside}

γραψας επιστολην [περιεχουσαν]{.greek-omitted} [εχουσαν]{.greek-added} τον τυπον τουτον[23:25]{.aside}

κλαυδιος λυσιας τω κρατιστω ηγεμονι [φηλικι]{.greek-omitted} [φιλικι]{.greek-added} χαιρειν[23:26]{.aside}

τον ανδρα τουτον συλληφθεντα υπο των ιουδαιων και μελλοντα αναιρεισθαι υπ αυτων επιστας συν τω στρατευματι [εξειλομην]{.greek-omitted} [εξειλαμην]{.greek-added} [αυτον]{.greek-omitted} μαθων οτι ρωμαιος εστιν[23:27]{.aside}

βουλομενος δε γνωναι την αιτιαν δι ην ενεκαλουν αυτω κατηγαγον αυτον εις το συνεδριον αυτων[23:28]{.aside}

ον [ευρον]{.greek-omitted} [ηυρον]{.greek-added} εγκαλουμενον περι ζητηματων του νομου αυτων μηδεν αξιον θανατου η δεσμων εγκλημα εχοντα[23:29]{.aside}

[μηνυθεισης]{.greek-omitted} [μηνυθησης]{.greek-added} δε μοι επιβουλης εις τον ανδρα μελλειν εσεσθαι [υπο]{.greek-omitted} [των]{.greek-omitted} [ιουδαιων]{.greek-omitted} εξαυτης επεμψα προς σε παραγγειλας και τοις κατηγοροις λεγειν τα προς αυτον επι σου ερρωσο[23:30]{.aside}

οι μεν ουν στρατιωται κατα το διατεταγμενον αυτοις αναλαβοντες τον παυλον ηγαγον δια [της]{.greek-omitted} νυκτος εις την αντιπατριδα[23:31]{.aside}

τη δε επαυριον εασαντες τους ιππεις πορευεσθαι συν αυτω υπεστρεψαν εις την παρεμβολην[23:32]{.aside}

οιτινες [εισελθοντες]{.greek-omitted} [ελθοντες]{.greek-added} εις την καισαρειαν και αναδοντες την επιστολην τω ηγεμονι παρεστησαν και τον παυλον αυτω[23:33]{.aside}

αναγνους δε ο ηγεμων και επερωτησας εκ ποιας επαρχιας εστιν και [πυθομενος]{.greek-omitted} [ποιθομενος]{.greek-added} οτι απο κιλικιας[23:34]{.aside}

διακουσομαι σου εφη οταν και οι κατηγοροι σου παραγενωνται [κελευσας]{.greek-added} [εκελευσεν]{.greek-omitted} [τε]{.greek-omitted} [αυτον]{.greek-omitted} εν τω [πραιτωριω]{.greek-omitted} [πραιτοριω]{.greek-added} ηρωδου φυλασσεσθαι [αυτον]{.greek-added}[23:35]{.aside}

### Chapter 24

μετα δε πεντε ημερας κατεβη ο αρχιερευς ανανιας μετα [των]{.greek-omitted} πρεσβυτερων [τινων]{.greek-added} και ρητορος τερτυλλου τινος οιτινες [ενεφανισαν]{.greek-omitted} [ενεφανησαν]{.greek-added} τω [ηγεμονι]{.greek-omitted} [ηγεμωνι]{.greek-added} κατα του παυλου[24:1]{.aside}

κληθεντος δε αυτου ηρξατο κατηγορειν ο τερτυλλος λεγων πολλης ειρηνης τυγχανοντες δια σου και κατορθωματων γινομενων τω εθνει τουτω δια της σης προνοιας[24:2]{.aside}

[παντοτε]{.greek-added} [παντη]{.greek-omitted} [τε]{.greek-omitted} και πανταχου αποδεχομεθα κρατιστε [φηλιξ]{.greek-omitted} [φιλιξ]{.greek-added} μετα πασης [ευχαριστιας]{.greek-omitted} [ευχαριστειας]{.greek-added}[24:3]{.aside}

ινα [μη]{.greek-added} δε [μη]{.greek-omitted} επι πλειον σε εγκοπτω παρακαλω ακουσαι σε [συντομως]{.greek-added} ημων [συντομως]{.greek-omitted} τη ση επιεικεια[24:4]{.aside}

ευροντες γαρ τον ανδρα τουτον λοιμον και κινουντα [στασιν]{.greek-omitted} [στασεις]{.greek-added} [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις ιουδαιοις τοις κατα την οικουμενην πρωτοστατην τε της των ναζωραιων αιρεσεως[24:5]{.aside}

ος και το ιερον επειρασεν βεβηλωσαι ον και [ευροντες]{.greek-added} εκρατησαμεν [και]{.greek-added} [κατα]{.greek-added} [τον]{.greek-added} [ημετερον]{.greek-added} [νομον]{.greek-added} [ηθελησαμεν]{.greek-added} [κριναι]{.greek-added}[24:6]{.aside}

[παρελθων]{.greek-added} [δε]{.greek-added} [λυσιας]{.greek-added} [ο]{.greek-added} [χιλιαρχος]{.greek-added} [μετα]{.greek-added} [πολλης]{.greek-added} [βιας]{.greek-added} [εκ]{.greek-added} [των]{.greek-added} [χειρων]{.greek-added} [ημων]{.greek-added} [απηγαγεν]{.greek-added}[24:7]{.aside}

[κελευσας]{.greek-added} [τους]{.greek-added} [κατηγορους]{.greek-added} [αυτου]{.greek-added} [ερχεσθαι]{.greek-added} [επι]{.greek-added} [[σ]{.unclear}ε]{.greek-added} παρ ου [δυνηση]{.greek-omitted} [δυνασαι]{.greek-added} αυτος ανακρινας περι παντων τουτων επιγνωναι ων ημεις κατηγορουμεν αυτου[24:8]{.aside}

συνεπεθεντο δε και οι ιουδαιοι φασκοντες ταυτα ουτως εχειν[24:9]{.aside}

απεκριθη [δε]{.greek-omitted} [τε]{.greek-added} ο παυλος νευσαντος αυτω του ηγεμονος λεγειν εκ πολλων ετων οντα σε κριτην [δικαιον]{.greek-added} τω εθνει τουτω επισταμενος [ευθυμοτερον]{.greek-omitted} [ευθυμως]{.greek-added} τα περι εμαυτου απολογουμαι[24:10]{.aside}

δυναμενου σου [γνωναι]{.greek-omitted} [επιγνωναι]{.greek-added} οτι ου πλειους εισιν μοι ημεραι [δεκαδυο]{.greek-omitted} [δωδεκα]{.greek-added} αφ ης ανεβην προσκυνησων [εν]{.greek-omitted} [εις]{.greek-added} [ιερουσαλημ]{.greek-abbr}[24:11]{.aside}

και ουτε εν τω ιερω ευρον με προς τινα διαλεγομενον η επισυστασιν ποιουντα [οχλου]{.greek-omitted} [οχλων]{.greek-added} ουτε εν ταις συναγωγαις ουτε κατα την πολιν[24:12]{.aside}

ουτε παραστησαι [με]{.greek-omitted} δυνανται [σοι]{.greek-added} περι ων [νυν]{.greek-omitted} [νυνι]{.greek-added} κατηγορουσιν μου[24:13]{.aside}

ομολογω δε τουτο σοι οτι κατα την οδον ην λεγουσιν αιρεσιν ουτως λατρευω τω πατρωω [θεω]{.greek-abbr} πιστευων [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις κατα τον νομον και τοις [εν]{.greek-added} [τοις]{.greek-added} προφηταις γεγραμμενοις[24:14]{.aside}

ελπιδα εχων εις τον [θεον]{.greek-abbr} ην και αυτοι ουτοι προσδεχονται αναστασιν μελλειν εσεσθαι νεκρων δικαιων τε και αδικων[24:15]{.aside}

εν τουτω [δε]{.greek-omitted} [και]{.greek-added} αυτος ασκω απροσκοπον [εχων]{.greek-added} συνειδησιν [εχων]{.greek-omitted} [δια]{.greek-added} [παντος]{.greek-added} προς [τε]{.greek-added} τον [θεον]{.greek-abbr} και [τους]{.greek-omitted} [προς]{.greek-added} ανθρωπους [δια]{.greek-omitted} [παντος]{.greek-omitted}[24:16]{.aside}

δι ετων δε πλειονων [παρεγενομην]{.greek-omitted} ελεημοσυνας ποιησων εις το εθνος μου και προσφορας [παρεγενομην]{.greek-added}[24:17]{.aside}

εν [οις]{.greek-omitted} [αις]{.greek-added} ευρον με ηγνισμενον εν τω ιερω ου μετα οχλου ουδε μετα θορυβου [τινες]{.greek-omitted} [απο]{.greek-omitted} [της]{.greek-omitted} [ασιας]{.greek-omitted} [ιουδαιοι]{.greek-omitted}[24:18]{.aside}

[τινες]{.greek-added} [δε]{.greek-added} [των]{.greek-added} [απο]{.greek-added} [της]{.greek-added} [ασιας]{.greek-added} [ιουδαιων]{.greek-added} ους [δει]{.greek-omitted} [εδει]{.greek-added} [παρειναι]{.greek-added} επι σου [παρειναι]{.greek-omitted} και κατηγορειν ει τι εχοιεν προς με[24:19]{.aside}

η αυτοι ουτοι ειπατωσαν τι ευρον εν εμοι αδικημα σταντος μου επι του συνεδριου[24:20]{.aside}

η περι μιας [φωνης]{.greek-added} ταυτης [φωνης]{.greek-omitted} ης εκραξα [εστως]{.greek-omitted} εν αυτοις [εστως]{.greek-added} οτι περι αναστασεως νεκρων εγω [σημερον]{.greek-added} κρινομαι [εφ]{.greek-added} [σημερον]{.greek-omitted} [υφ]{.greek-omitted} υμων[24:21]{.aside}

[ακουσας]{.greek-omitted} [ανεβαλετο]{.greek-added} δε [ταυτα]{.greek-omitted} ο [φηλιξ]{.greek-omitted} [φιλιξ]{.greek-added} [αυτον]{.greek-added} [ανεβαλετο]{.greek-omitted} [αυτους]{.greek-omitted} ακριβεστερον ειδως τα περι της οδου ειπων οταν λυσιας ο χιλιαρχος [καταβη]{.greek-omitted} [καταλαβη]{.greek-added} διαγνωσομαι τα καθ υμας[24:22]{.aside}

διαταξαμενος [τε]{.greek-omitted} τω [εκατονταρχη]{.greek-omitted} [εκατονταρχω]{.greek-added} τηρεισθαι [τον]{.greek-omitted} [αυτον]{.greek-added} [παυλον]{.greek-omitted} εχειν τε ανεσιν και μηδενα κωλυειν των ιδιων αυτου υπηρετειν [η]{.greek-omitted} [προσερχεσθαι]{.greek-omitted} αυτω[24:23]{.aside}

μετα δε ημερας τινας παραγενομενος ο [φηλιξ]{.greek-omitted} [φιλιξ]{.greek-added} συν δρουσιλλη τη γυναικι [αυτου]{.greek-added} ουση ιουδαια μετεπεμψατο τον παυλον και ηκουσεν αυτου [τα]{.greek-added} περι της εις [χριστον]{.greek-abbr} [[ιησουν]{.greek-abbr}]{.greek-added} πιστεως[24:24]{.aside}

διαλεγομενου δε αυτου περι δικαιοσυνης και εγκρατειας και του κριματος του μελλοντος εσεσθαι εμφοβος γενομενος ο [φηλιξ]{.greek-omitted} [φιλιξ]{.greek-added} απεκριθη το νυν [εχον]{.greek-omitted} [εχων]{.greek-added} πορευου καιρον δε [μεταλαβων]{.greek-omitted} [παραλαβων]{.greek-added} μετακαλεσομαι σε[24:25]{.aside}

αμα και ελπιζων οτι χρηματα δοθησεται αυτω υπο του παυλου οπως λυση αυτον διο και πυκνοτερον [μεταπεμπομενος]{.greek-added} αυτον [μεταπεμπομενος]{.greek-omitted} ωμιλει αυτω[24:26]{.aside}

[διετιας]{.greek-omitted} [διετειας]{.greek-added} δε πληρωθεισης ελαβεν διαδοχον ο [φηλιξ]{.greek-omitted} [φιλιξ]{.greek-added} πορκιον φηστον θελων [τε]{.greek-omitted} [χαριτας]{.greek-omitted} [δε]{.greek-added} [χαριν]{.greek-added} καταθεσθαι τοις ιουδαιοις ο [φηλιξ]{.greek-omitted} [φιλιξ]{.greek-added} κατελιπεν [αυτοις]{.greek-added} τον παυλον δεδεμενον[24:27]{.aside}

### Chapter 25

φηστος ουν επιβας τη επαρχια μετα τρεις ημερας ανεβη εις ιεροσολυμα απο καισαρειας[25:1]{.aside}

[ενεφανισαν]{.greek-omitted} [ενεφανησαν]{.greek-added} [δε]{.greek-omitted} [τε]{.greek-added} αυτω [ο]{.greek-omitted} [οι]{.greek-added} [αρχιερευς]{.greek-omitted} [αρχιερεις]{.greek-added} και οι πρωτοι των ιουδαιων κατα του παυλου και παρεκαλουν αυτον[25:2]{.aside}

αιτουμενοι χαριν κατ αυτου οπως μεταπεμψηται αυτον εις [ιερουσαλημ]{.greek-omitted} [ιεροσολυμα]{.greek-added} ενεδραν ποιουντες ανελειν αυτον κατα την οδον[25:3]{.aside}

ο μεν ουν φηστος απεκριθη τηρεισθαι τον παυλον εν καισαρεια εαυτον δε μελλειν εν ταχει εκπορευεσθαι[25:4]{.aside}

οι ουν δυνατοι εν υμιν φησιν συγκαταβαντες ει τι εστιν εν τω ανδρι τουτω [ατοπον]{.greek-added} [κατηγορειτωσαν]{.greek-omitted} [κατηγορητωσαν]{.greek-added} αυτου[25:5]{.aside}

διατριψας δε εν αυτοις ημερας πλειους [οκτω]{.greek-added} η δεκα καταβας εις καισαρειαν τη επαυριον [καθισας]{.greek-omitted} [καθησας]{.greek-added} επι του βηματος εκελευσεν τον παυλον αχθηναι[25:6]{.aside}

παραγενομενου δε αυτου περιεστησαν οι απο ιεροσολυμων καταβεβηκοτες ιουδαιοι πολλα και βαρεα αιτιωματα [καταφωνουντες]{.greek-added} [φεροντες]{.greek-omitted} [κατα]{.greek-omitted} του παυλου α ουκ ισχυον αποδειξαι[25:7]{.aside}

απολογουμενου [αυτου]{.greek-omitted} οτι ουτε εις τον νομον των ιουδαιων ουτε εις το ιερον ουτε εις καισαρα τ[ι]{.unclear} [ημ]{.unclear}αρτον[25:8]{.aside}

ο φηστος δε [[θε]{.unclear}λων]{.greek-added} τοις ιουδαιο[ις]{.greek-supplied} [θελων]{.greek-omitted} χαριν καταθεσθαι [α]{.unclear}ποκριθεις [ειπεν]{.greek-added} τω παυλω [ειπεν]{.greek-omitted} θελεις εις ιεροσολυμα αναβας εκει περι τουτων [κρινεσθαι]{.greek-omitted} [κριθηναι]{.greek-added} επ εμου[25:9]{.aside}

ειπεν δε ο παυλος [εστως]{.greek-added} επι του βηματος καισαρος [εστως]{.greek-omitted} ειμι ου [δει]{.greek-added} με [δει]{.greek-omitted} κρινεσθαι ιουδαιους ουδεν [ηδικησα]{.greek-omitted} [ηδικη]{.greek-added} [σα]{.greek-added} ως και συ [καλλιον]{.greek-omitted} [καλλειω]{.greek-added} επιγινωσκεις[25:10]{.aside}

ει μεν γαρ αδικω [και]{.greek-omitted} [η]{.greek-added} αξιον θανατου πεπραχα τι ου παραιτουμαι το αποθανειν ει δε ουδεν εστιν ων ουτοι κατηγορουσιν μου ουδεις με δυναται αυτοις χαρισασθαι καισαρα επικαλουμαι[25:11]{.aside}

τοτε ο φηστος συλλαλησας μετα του συμβουλιου απεκριθη καισαρα επικεκλησαι επι καισαρα πορευση[25:12]{.aside}

ημερων δε διαγενομενων τινων αγριππας ο βασιλευς και βερνικη κατηντησαν εις καισαρειαν [ασπασαμενοι]{.greek-omitted} [ασπασομενοι]{.greek-added} τον φηστον[25:13]{.aside}

ως δε πλειους ημερας [διετριβεν]{.greek-omitted} [διετριβον]{.greek-added} εκει ο φηστος τω βασιλει ανεθετο τα κατα τον παυλον λεγων ανηρ τις εστιν καταλελειμμενος υπο [φηλικος]{.greek-omitted} [φιλικος]{.greek-added} δεσμιος[25:14]{.aside}

περι ου γενομενου μου εις [ιεροσολυμα]{.greek-omitted} [[ιερουσαλημ]{.greek-abbr}]{.greek-added} [ενεφανισαν]{.greek-omitted} [ενεφανησαν]{.greek-added} οι αρχιερεις και οι πρεσβυτεροι των ιουδαιων αιτουμενοι κατ αυτου δικην[25:15]{.aside}

προς ους απεκριθην οτι [ουκ]{.greek-omitted} [εστιν]{.greek-omitted} εθος ρωμαιοις [ουκ]{.greek-added} [εξεστιν]{.greek-added} χαριζεσθαι τινα [ανθρωπον]{.greek-abbr} εις απωλειαν πριν η ο κατηγορουμενος κατα προσωπον εχοι τους κατηγορους τοπον [τε]{.greek-omitted} [δε]{.greek-added} απολογιας λαβοι περι του εγκληματος[25:16]{.aside}

συνελθοντων ουν αυτων ενθαδε αναβολην μηδεμιαν ποιησαμενος τη εξης [καθισας]{.greek-omitted} [καθησας]{.greek-added} επι του βηματος εκελευσα αχθηναι τον ανδρα[25:17]{.aside}

περι ου σταθεντες οι κατηγοροι ουδεμιαν αιτιαν [επεφερον]{.greek-omitted} [εφερον]{.greek-added} ων υπενοουν εγω [πονηραν]{.greek-added}[25:18]{.aside}

ζητηματα δε τινα περι της ιδιας δεισιδαιμονιας ειχον προς αυτον και περι [τι]{.greek-added} [τινος]{.greek-omitted} [νος]{.greek-added} [ιησου]{.greek-abbr} τεθνηκοτος ον εφασκεν ο παυλος ζην[25:19]{.aside}

[α]{.unclear}πορουμενος δε εγω [εις]{.greek-added} την περι [τουτου]{.greek-omitted} [τουτων]{.greek-added} ζητησιν ελεγον ει βουλοιτο πορευεσθαι εις [ιερουσαλημ]{.greek-omitted} [ιεροσολυμα]{.greek-added} κακει κρινεσθαι περι τουτων[25:20]{.aside}

του δε παυλου επικαλεσαμενου τηρηθηναι αυτον εις την του σεβαστου διαγνωσιν εκελευσα [αυτον]{.greek-added} τηρεισθαι [αυτον]{.greek-omitted} εως ου [πεμψω]{.greek-omitted} [αναπεμψω]{.greek-added} αυτον προς καισαρα[25:21]{.aside}

αγριππας δε προς τον φηστον εφη εβουλομην και αυτος του [ανθρωπου]{.greek-abbr} ακουσαι ο δε αυριον φησιν ακουση αυτου[25:22]{.aside}

τη ουν επαυριον ελθοντος του αγριππα και της βερνικης μετα πολλης φαντασιας και εισελθοντων εις το ακροατηριον συν τε [τοις]{.greek-omitted} χιλιαρχοις και ανδρασιν τοις κατ εξοχην ουσιν της πολεως και κελευσαντος του φηστου ηχθη ο παυλος[25:23]{.aside}

και φησιν ο φηστος αγριππα βασιλευ και παντες οι συμπαροντες ημιν ανδρες θεωρειτε τουτον περι [ου]{.greek-omitted} [τουτου]{.greek-added} [παν]{.greek-omitted} [απαν]{.greek-added} το πληθος των ιουδαιων ενετυχον μοι εν τε ιεροσολυμοις και ενθαδε επιβοωντες μη δειν ζην αυτον μηκετι[25:24]{.aside}

εγω δε καταλαβομενος μηδεν αξιον θανατου [πεπραχεναι]{.greek-added} αυτον [πεπραχεναι]{.greek-omitted} και αυτου δε τουτου επικαλεσαμενου τον σεβαστον εκρινα πεμπειν αυτον[25:25]{.aside}

περι ου ασφαλες τι γραψαι τω κυριω [μου]{.greek-added} ουκ εχω διο προηγαγον αυτον εφ υμων και μαλιστα επι σου βασιλευ αγριππα οπως της ανακρισεως [γενομενης]{.greek-omitted} [γινομενης]{.greek-added} [σχω]{.greek-omitted} [εχω]{.greek-added} τι [γραψαι]{.greek-omitted} [γραψω]{.greek-added}[25:26]{.aside}

αλογον γαρ [δοκει]{.greek-added} μοι [δοκει]{.greek-omitted} πεμποντα δεσμιον μη και τας κατ αυτου αιτιας σημαναι[25:27]{.aside}

### Chapter 26

αγριππας δε προς τον παυλον εφη επιτρεπεται σοι [λεγειν]{.greek-added} υπερ σεαυτου [λεγειν]{.greek-omitted} τοτε ο παυλος απελογειτο εκτεινας την χειρα [αυτου]{.greek-added}[26:1]{.aside}

περι παντων ων εγκαλουμαι υπο ιουδαιων βασιλευ αγριππα ηγημαι εμαυτον μακαριον επι σου μελλων απολογεισθαι σημερον[26:2]{.aside}

μαλιστα γνωστην οντα σε παντων των κατα ιουδαιους [ηθων]{.greek-omitted} [εθων]{.greek-added} τε και ζητηματων [επισταμενος]{.greek-added} διο δεομαι [σου]{.greek-omitted} μακροθυμως ακουσαι μου[26:3]{.aside}

την μεν ουν βιωσιν μου την εκ νεοτητος την απ αρχης γενομενην εν τω εθνει μου εν ιεροσολυμοις [ισασιν]{.greek-omitted} [ισασι]{.greek-added} παντες οι ιουδαιοι[26:4]{.aside}

προγινωσκοντες με ανωθεν εαν [θελωσιν]{.greek-omitted} [θελωσι]{.greek-added} μαρτυρειν οτι κατα την ακριβεστατην αιρεσιν της ημετερας θρησκειας εζησα φαρισαιος[26:5]{.aside}

και νυν [επ]{.greek-omitted} ελπιδι της προς τους [πατερας]{.greek-abbr} [ημων]{.greek-added} επαγγελιας γενομενης υπο του [θεου]{.greek-abbr} εστηκα κρινομενος[26:6]{.aside}

εις ην το δωδεκαφυλον ημων εν [εκτενεια]{.greek-omitted} [εκτενια]{.greek-added} νυκτα και ημεραν λατρευον ελπιζει καταντησαι περι ης ελπιδος εγκαλουμαι βασιλευ αγριππα υπο ιουδαιων[26:7]{.aside}

τι απιστον κρινεται παρ υμιν ει ο [θεος]{.greek-abbr} νεκρους εγειρει[26:8]{.aside}

εγω μεν ουν εδοξα εμαυτω προς το ονομα [ιησου]{.greek-abbr} του ναζωραιου δειν πολλα εναντια πραξαι[26:9]{.aside}

ο και εποιησα εν ιεροσολυμοις και πολλους των αγιων εγω φυλακαις κατεκλεισα την παρα των αρχιερεων εξουσιαν λαβων [αναιρουμενων]{.greek-omitted} [αναιρουμε]{.greek-added} [νων]{.greek-added} τε αυτων κατηνεγκα ψηφον[26:10]{.aside}

και κατα πασας τας συναγωγας πολλακις τιμωρων αυτους ηναγκαζον βλασφημειν περισσως τε εμμαινομενος αυτοις εδιωκον εως και εις τας εξω πολεις[26:11]{.aside}

εν οις [και]{.greek-omitted} πορευομενος εις την δαμασκον μετ εξουσιας και επιτροπης της παρα των αρχιερεων[26:12]{.aside}

ημερας μεσης κατα την οδον [ειδον]{.greek-omitted} [ιδον]{.greek-added} βασιλευ [ουρανοθεν]{.greek-abbr} υπερ την λαμπροτητα του ηλιου περιλαμψαν [με]{.greek-omitted} φως και τους συν εμοι πορευομενους[26:13]{.aside}

παντων [δε]{.greek-omitted} [τε]{.greek-added} καταπεσοντων ημων εις την γην ηκουσα [φωνην]{.greek-omitted} [φωνης]{.greek-added} [λαλουσαν]{.greek-omitted} [λεγουσης]{.greek-added} προς με [και]{.greek-omitted} [λεγουσαν]{.greek-omitted} τη εβραιδι διαλεκτω σαουλ σαουλ τι με διωκεις σκληρον σοι προς κεντρα λακτιζειν[26:14]{.aside}

εγω δε ειπον τις ει [κυριε]{.greek-abbr} ο δε [[κυριος]{.greek-abbr}]{.greek-added} ειπεν εγω ειμι [ιησους]{.greek-abbr} ον συ διωκεις[26:15]{.aside}

αλλα αναστηθι και στηθι επι τους ποδας σου εις τουτο γαρ ωφθην σοι προχειρισασθαι σε υπηρετην και μαρτυρα ων τε [ειδες]{.greek-omitted} [ιδες]{.greek-added} ων τε οφθησομαι σοι[26:16]{.aside}

εξαιρουμενος σε εκ του λαου [των]{.greek-added} [ιουδαιων]{.greek-added} και των εθνων εις ους εγω [σε]{.greek-omitted} αποστελλω [σαι]{.greek-added}[26:17]{.aside}

ανοιξαι οφθαλμους αυτων του [υποστρεψαι]{.greek-omitted} [επιστρεψαι]{.greek-added} απο σκοτους εις φως και [απο]{.greek-added} της εξουσιας του σατανα επι τον [θεον]{.greek-abbr} του λαβειν αυτους αφεσιν αμαρτιων και κληρον εν τοις ηγιασμενοις πιστει τη εις εμε[26:18]{.aside}

οθεν βασιλευ αγριππα ουκ εγενομην απειθης τη [ουρανιω]{.greek-abbr} οπτασια[26:19]{.aside}

αλλα τοις εν δαμασκω πρωτον και [εν]{.greek-added} ιεροσολυμοις εις πασαν τε την χωραν της ιουδαιας και τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} [απαγγελλων]{.greek-omitted} μετανοειν [επηγγελ]{.greek-added} [λον]{.greek-added} και επιστρεφειν επι τον [ζωντα]{.greek-added} [θεον]{.greek-abbr} αξια της μετανοιας εργα πρασσοντας[26:20]{.aside}

ενεκα τουτων [με]{.greek-added} οι ιουδαιοι [με]{.greek-omitted} συλλαβομενοι [οντα]{.greek-added} εν τω ιερω επειρωντο διαχειρισασθαι[26:21]{.aside}

[επικουριας]{.greek-omitted} [επηκουριας]{.greek-added} ουν τυχων της [παρα]{.greek-omitted} [απο]{.greek-added} του [θεου]{.greek-abbr} αχρι της ημερας ταυτης εστηκα μαρτυρομενος μικρω τε και μεγαλω ουδεν εκτος λεγων ων τε οι προφηται ελαλησαν μελλοντων γινεσθαι και μωυσης[26:22]{.aside}

ει παθητος ο [χριστος]{.greek-abbr} ει πρωτος εξ αναστασεως νεκρων φως μελλει καταγγελλειν τω λαω και τοις εθνεσιν[26:23]{.aside}

ταυτα δε αυτου απολογουμενου ο φηστος μεγαλη τη φωνη [εφη]{.greek-omitted} [φησιν]{.greek-added} μαινη παυλε τα πολλα σε γραμματα εις μανιαν περιτρεπει[26:24]{.aside}

ο δε [παυλος]{.greek-added} ου μαινομαι φησιν κρατιστε φηστε [αλλα]{.greek-omitted} [αλλ]{.greek-added} αληθειας και σωφροσυνης ρηματα αποφθεγγομαι[26:25]{.aside}

επισταται γαρ περι τουτων ο βασιλευς προς ον και παρρησιαζομενος λαλω [λανθανειν]{.greek-omitted} [λανθανει]{.greek-added} γαρ αυτον τι τουτων ου πειθομαι [ουδεν]{.greek-omitted} [ουδε]{.greek-added} [ου]{.greek-omitted} γαρ [εστιν]{.greek-added} εν γωνια πεπραγμενον τουτο[26:26]{.aside}

πιστευεις βασιλευ αγριππα τοις προφηταις οιδα οτι πιστευεις[26:27]{.aside}

[ο]{.greek-omitted} [αγριππας]{.greek-added} δε [αγριππας]{.greek-omitted} προς τον παυλον εφη εν ολιγω με πειθεις χριστιανον γενεσθαι[26:28]{.aside}

ο δε παυλος [ειπεν]{.greek-omitted} ευξαιμην αν τω [θεω]{.greek-abbr} και εν ολιγω και εν [πολλω]{.greek-omitted} [μεγαλω]{.greek-added} ου μονον σε αλλα και παντας τους ακουοντας μου σημερον γενεσθαι τοιουτους οποιος [καγω]{.greek-omitted} [και]{.greek-added} [εγω]{.greek-added} ειμι παρεκτος των δεσμων τουτων[26:29]{.aside}

και ταυτα ειποντος αυτου ανεστη [δε]{.greek-added} ο βασιλευς και ο ηγεμων η τε βερνικη και οι συγκαθημενοι αυτοις[26:30]{.aside}

και αναχωρησαντες ελαλουν προς αλληλους λεγοντες οτι ουδεν θανατου αξιον η δεσμων [πρασσει]{.greek-omitted} [πραττει]{.greek-added} ο [ανθρωπος]{.greek-abbr} ουτος[26:31]{.aside}

αγριππας δε τω φηστω εφη απολελυσθαι εδυνατο ο [ανθρωπος]{.greek-abbr} ουτος ει μη [επεκεκλητο]{.greek-omitted} [επικεκλητο]{.greek-added} καισαρα[26:32]{.aside}

### Chapter 27

ως δε εκριθη του αποπλειν ημας εις την [ιταλιαν]{.greek-omitted} [ιταλειαν]{.greek-added} παρεδιδουν τον τε παυλον και τινας ετερους δεσμωτας εκατονταρχη ονοματι ιουλιω σπειρης σεβαστης[27:1]{.aside}

επιβαντες δε πλοιω [αδραμυττηνω]{.greek-omitted} [αδραμυντηνω]{.greek-added} [μελλοντες]{.greek-omitted} [μελλοντι]{.greek-added} πλειν [επι]{.greek-added} τους κατα την ασιαν τοπους ανηχθημεν οντος συν ημιν αρισταρχου μακεδονος [θεσσαλονικεως]{.greek-omitted} [θεσαλονικεως]{.greek-added}[27:2]{.aside}

τη τε ετερα κατηχθημεν εις σιδωνα φιλανθρωπως τε ο ιουλιος [χρησαμενος]{.greek-added} τω παυλω [χρησαμενος]{.greek-omitted} επετρεψεν προς τους φιλους πορευθεντα επιμελειας τυχειν[27:3]{.aside}

κακειθεν αναχθεντες υπεπλευσαμεν την κυπρον δια το τους ανεμους ειναι εναντιους[27:4]{.aside}

το τε πελαγος το κατα την κιλικιαν και παμφυλιαν διαπλευσαντες [κατηλθομεν]{.greek-omitted} [κατηχθημεν]{.greek-added} εις [μυρα]{.greek-omitted} [μυραν]{.greek-added} της λυκιας[27:5]{.aside}

κακει ευρων ο εκατονταρχος πλοιον αλεξανδρινον πλεον εις την ιταλιαν [ενεβιβασεν]{.greek-omitted} [ανεβιβασεν]{.greek-added} ημας εις αυτο[27:6]{.aside}

εν ικαναις δε ημεραις βραδυπλοουντες και μολις γενομενοι κατα την κνιδον μη προσεωντος ημας του ανεμου υπεπλευσαμεν την κρητην κατα σαλμωνην[27:7]{.aside}

μολις τε παραλεγομενοι αυτην [ηλθομεν]{.greek-omitted} [ηκομεν]{.greek-added} εις τοπον τινα καλουμενον καλους λιμενας ω εγγυς ην πολις [λασαια]{.greek-omitted} [λασσεα]{.greek-added}[27:8]{.aside}

ικανου δε χρονου διαγενομενου και [ηδη]{.greek-added} οντος [ηδη]{.greek-omitted} [επισφαλους]{.greek-omitted} του πλοος [επισφαλους]{.greek-added} δια το και την νηστειαν ηδη παρεληλυθεναι παρηνει ο παυλος[27:9]{.aside}

λεγων αυτοις ανδρες θεωρω οτι μετα υβρεως και πολλης ζημιας ου μονον του φορτιου και του πλοιου αλλα και των ψυχων ημων μελλειν εσεσθαι τον πλουν[27:10]{.aside}

ο δε [εκατονταρχης]{.greek-omitted} [εκατονταρχος]{.greek-added} τω [κυβερνητη]{.greek-omitted} [κυβερνιτη]{.greek-added} και τω ναυκληρω επειθετο μαλλον η τοις υπο του παυλου λεγομενοις[27:11]{.aside}

ανευθετου δε του λιμενος υπαρχοντος προς παραχειμασιαν οι [πλειους]{.greek-omitted} [πλειονες]{.greek-added} εθεντο βουλην αναχθηναι κακειθεν ει πως δυναιντο καταντησαντες εις φοινικα παραχειμασαι λιμενα της κρητης βλεποντα κατα λιβα και κατα χωρον[27:12]{.aside}

υποπνευσαντος δε νοτου δοξαντες της προθεσεως κεκρατηκεναι αραντες ασσον παρελεγοντο την κρητην[27:13]{.aside}

μετ ου πολυ δε εβαλεν κατ αυτης ανεμος τυφωνικος ο καλουμενος [ευροκλυδων]{.greek-omitted} [ευροκλυδιων]{.greek-added}[27:14]{.aside}

συναρπασθεντος δε του πλοιου και μη δυναμενου αντοφθαλμειν τω ανεμω επιδοντες εφερομεθα[27:15]{.aside}

νησιον δε τι υποδραμοντες καλουμενον [κλαυδην]{.greek-omitted} [κλαυδιν]{.greek-added} μολις ισχυσαμεν [περικρατεις]{.greek-omitted} [περικρατης]{.greek-added} γενεσθαι της σκαφης[27:16]{.aside}

ην αραντες βοηθειαις εχρωντο υποζωννυντες το πλοιον φοβουμενοι τε μη εις την συρτην εκπεσωσιν χαλασαντες το σκευος ουτως εφεροντο[27:17]{.aside}

σφοδρως δε χειμαζομενων ημων τη εξης εκβολην εποιουντο[27:18]{.aside}

και τη τριτη [αυτο]{.greek-added} [αυτοχειρες]{.greek-omitted} [χειρες]{.greek-added} την σκευην του πλοιου [ερριψαμεν]{.greek-omitted} [ερριψαν]{.greek-added}[27:19]{.aside}

μητε δε ηλιου μητε αστρων επιφαινοντων επι πλειονας ημερας [χειμωνος]{.greek-omitted} [χειμονος]{.greek-added} τε ουκ ολιγου επικειμενου λοιπον περιηρειτο πασα ελπις του σωζεσθαι ημας[27:20]{.aside}

πολλης [δε]{.greek-omitted} [τε]{.greek-added} ασιτιας υπαρχουσης τοτε σταθεις ο παυλος εν μεσω αυτων ειπεν εδει μεν ω ανδρες πειθαρχησαντας μοι μη αναγεσθαι απο της κρητης κερδησαι τε την υβριν ταυτην και την ζημιαν[27:21]{.aside}

και τα νυν παραινω υμας ευθυμειν αποβολη γαρ ψυχης [ουδεμια]{.greek-omitted} [ουδεμιας]{.greek-added} εσται εξ υμων πλην του πλοιου[27:22]{.aside}

παρεστη γαρ μοι ταυτη τη νυκτι [αγγελος]{.greek-omitted} του [θεου]{.greek-abbr} ου ειμι ω και λατρευω [αγγελος]{.greek-added}[27:23]{.aside}

λεγων μη φοβου παυλε καισαρι σε δει παραστηναι και ιδου κεχαρισται σοι ο [θεος]{.greek-abbr} παντας τους πλεοντας μετα σου[27:24]{.aside}

διο ευθυμειτε ανδρες πιστευω γαρ τω [θεω]{.greek-abbr} οτι ουτως εσται καθ ον τροπον λελαληται μοι[27:25]{.aside}

εις νησον δε τινα δει ημας εκπεσειν[27:26]{.aside}

ως δε τεσσαρεσκαιδεκατη νυξ εγενετο διαφερομενων ημων εν τω αδρια κατα μεσον της νυκτος υπενοουν οι ναυται προσαγειν τινα αυτοις χωραν[27:27]{.aside}

και βολισαντες ευρον οργυιας εικοσι βραχυ δε διαστησαντες και παλιν βολισαντες ευρον οργυιας δεκαπεντε[27:28]{.aside}

φοβουμενοι τε [μηπως]{.greek-omitted} [εις]{.greek-omitted} [μη]{.greek-added} [που]{.greek-added} [κατα]{.greek-added} τραχεις τοπους εκπεσωμεν εκ πρυμνης ριψαντες αγκυρας τεσσαρας ηυχοντο ημεραν γενεσθαι[27:29]{.aside}

των δε ναυτων ζητουντων φυγειν εκ του πλοιου και χαλασαντων την σκαφην εις την [θα]{.greek-added} [θαλασσαν]{.greek-omitted} [προφασει]{.greek-omitted} [ως]{.greek-omitted} [εκ]{.greek-omitted} [πρωρας]{.greek-omitted} [μελλοντων]{.greek-omitted} [αγκυρας]{.greek-omitted} [εκτεινειν]{.greek-omitted}[27:30]{.aside}

### Chapter 28

[οι]{.greek-omitted} [δε]{.greek-omitted} [προσεδοκων]{.greek-omitted} [αυτον]{.greek-omitted} [μελλειν]{.greek-omitted} [πιμπρασθαι]{.greek-omitted} [η]{.greek-omitted} [καταπιπτειν]{.greek-omitted} αφνω νεκρον επι πολυ δε αυτων [προσδοκωντων]{.greek-omitted} [προσδοκοντων]{.greek-added} και θεωρουντων μηδεν ατοπον εις αυτον [γινομενον]{.greek-omitted} [γενομενον]{.greek-added} [μεταβαλλομενοι]{.greek-omitted} [μεταβαλομενοι]{.greek-added} ελεγον [θεον]{.greek-abbr} αυτον ειναι[28:6]{.aside}

εν δε τοις περι τον τοπον εκεινον [υπηρχεν]{.greek-omitted} [υπηρχε]{.greek-added} χωρια τω πρωτω της νησου ονοματι ποπλιω ος αναδεξαμενος ημας [ημερας]{.greek-added} τρεις [ημερας]{.greek-omitted} φ[ι]{.unclear}λοφρονως εξενισεν[28:7]{.aside}

εγενετο δε τον [πατερα]{.greek-abbr} του ποπλιου πυρετοις και [δυσεντερια]{.greek-omitted} [δυσεντεριω]{.greek-added} συνεχομενον κατακεισθαι προς ον ο παυλος εισελθων και προσευξαμενος επιθεις [τε]{.greek-added} τας χειρας αυτω ιασατο αυτον[28:8]{.aside}

τουτου [ουν]{.greek-omitted} [δε]{.greek-added} γενομενου και οι λοιποι οι εχοντες ασθενειας εν τη νησω προσηρχοντο και εθεραπευοντο[28:9]{.aside}

οι και πολλαις τιμαις ετιμησαν ημας και αναγομενοις επεθεντο τα προς [την]{.greek-omitted} [τας]{.greek-added} [χρειαν]{.greek-omitted} [χρειας]{.greek-added}[28:10]{.aside}

μετα δε τρεις μηνας [ηχθημεν]{.greek-omitted} [ανηχθημεν]{.greek-added} εν πλοιω παρακεχειμακοτι εν τη νησω αλεξανδρινω παρασημω διοσκουροις[28:11]{.aside}

και καταχθεντες εις συρακουσας επεμειναμεν ημερας τρεις[28:12]{.aside}

οθεν περιελθοντες κατηντησαμεν εις ρηγιον και μετα μιαν ημεραν επιγενομενου νοτου [δευτεραιοι]{.greek-omitted} [δευτερεοι]{.greek-added} ηλθομεν εις ποτιολους[28:13]{.aside}

ου ευροντες αδελφους παρεκληθημεν επ αυτοις [επιμειναι]{.greek-omitted} [επιμειναντες]{.greek-added} ημερας επτα και ουτως εις [την]{.greek-omitted} ρωμην [ηλθομεν]{.greek-omitted} [εισηλθομεν]{.greek-added}[28:14]{.aside}

κακειθεν οι αδελφοι ακουσαντες τα περ[ι]{.unclear} ημων εξηλθον εις απαντησιν ημιν [αχρι]{.greek-omitted} [αχρις]{.greek-added} αππιου φορου και τριων ταβερνων ους ιδων ο παυλος ευχαριστησας τω [θεω]{.greek-abbr} ελαβεν θαρσος[28:15]{.aside}

οτε δε ηλθομεν εις ρωμην ο εκατονταρχος [παρεδωκεν]{.greek-omitted} [παρεδωκε]{.greek-added} τους δεσμιους τω [στρατοπεδαρχη]{.greek-omitted} [στρατοπεδαρχω]{.greek-added} τω δε παυλω επετραπη μενειν καθ εαυτον συν τω φυλασσοντι αυτον στρατιωτη[28:16]{.aside}

εγενετο δε μετα ημερας τρεις συγκαλεσασθαι [τον]{.greek-omitted} [αυτον]{.greek-added} [παυλον]{.greek-omitted} τους οντας των ιουδαιων πρωτους συνελθοντων δε αυτων ελεγεν προς αυτους [εγω]{.greek-added} ανδρες αδελφοι [εγω]{.greek-omitted} ουδεν εναντιον ποιησας τω λαω η τοις [εθεσιν]{.greek-omitted} [εθεσι]{.greek-added} τοις πατρωοις δεσμιος [εξ]{.greek-omitted} [ιεροσολυμων]{.greek-omitted} [εν]{.greek-added} [[ιερουσαλημ]{.greek-abbr}]{.greek-added} παρεδοθην εις τας χειρας των ρωμαιων[28:17]{.aside}

οιτινες ανακριναντες με εβουλοντο απολυσαι δια το μηδεμιαν αιτιαν θανατου υπαρχειν εν εμοι[28:18]{.aside}

αντιλεγοντων δε των ιουδαιων ηναγκασθην επικαλεσασθαι καισαρα ουχ ως του εθνους μου [εχων]{.greek-omitted} [εχον]{.greek-added} τι [κατηγορησαι]{.greek-omitted} [κατηγοριαν]{.greek-added}[28:19]{.aside}

δια ταυτην ουν την αιτιαν παρεκαλεσα υμας ιδειν και προσλαλησαι ενεκεν γαρ της ελπιδος του [ισραηλ]{.greek-abbr} την αλυσιν ταυτην περικειμαι[28:20]{.aside}

οι δε προς αυτον ειπον ημεις ουτε γραμματα περι σου εδεξαμεθα απο της ιουδαιας ουτε παραγενομενος τις των αδελφων απηγγειλεν η ελαλησεν [τι]{.greek-omitted} περι σου [τι]{.greek-added} πονηρον[28:21]{.aside}

αξιουμεν δε παρα σου ακουσαι α φρονεις περι μεν γαρ της αιρεσεως ταυτης γνωστον εστιν ημιν οτι πανταχου αντιλεγεται[28:22]{.aside}

ταξαμενοι [δε]{.greek-omitted} [ουν]{.greek-added} αυτω ημεραν ηκον προς αυτον εις την ξενιαν πλειονες οις εξετιθετο διαμαρτυρομενος την βασιλειαν του [θεου]{.greek-abbr} πειθων τε αυτους τα περι του [ιησου]{.greek-abbr} απο [τε]{.greek-omitted} του νομου [μωυσεως]{.greek-omitted} [μωσεως]{.greek-added} και των προφητων απο πρωι εως εσπερας[28:23]{.aside}

και οι μεν επειθοντο τοις λεγομενοις οι δε ηπιστουν[28:24]{.aside}

ασυμφωνοι δε οντες προς αλληλους απελυοντο ειποντος του παυλου ρημα εν οτι καλως το [πνευμα]{.greek-abbr} το αγιον ελαλησεν δια ησαιου του προφητου προς τους [πατερας]{.greek-abbr} ημων[28:25]{.aside}

[λεγον]{.greek-omitted} [λεγων]{.greek-added} πορευθητι προς τον λαον τουτον και ειπον ακοη [ακουσετε]{.greek-omitted} [ακουσητε]{.greek-added} και ου μη συνητε και βλεποντες [βλεψετε]{.greek-omitted} [βλεψητε]{.greek-added} και ου μη ιδητε[28:26]{.aside}

επαχυνθη γαρ η καρδια του λαου τουτου και τοις ωσιν βαρεως ηκουσαν και τους οφθαλμους [αυτων]{.greek-omitted} εκαμμυσαν μηποτε [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} τοις οφθαλμοις και τοις ωσιν ακουσωσιν και τη καρδια [συνωσιν]{.greek-omitted} [συνωσι]{.greek-added} και επιστρεψωσιν και ιασομαι αυτους[28:27]{.aside}

γνωστον ουν εστω υμιν οτι τοις εθνεσιν απεσταλη [τουτο]{.greek-added} το [σωτηριον]{.greek-abbr} του [θεου]{.greek-abbr} αυτοι και ακουσονται[28:28]{.aside}

και ταυτα αυτου ειποντος απηλθον οι ιουδαιοι πολλην εχοντες εν εαυτοις [συζητησιν]{.greek-omitted} [συνζητησιν]{.greek-added}[28:29]{.aside}

[εμεινεν]{.greek-omitted} [επεμεινεν]{.greek-added} δε ο παυλος διετιαν ολην εν ιδιω μισθωματι και απεδεχετο παντας τους εισπορευομενους προς αυτον[28:30]{.aside}

κηρυσσων την βασιλειαν του [θεου]{.greek-abbr} και διδασκων τα περι του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} μετα πασης παρρησιας ακωλυτως [αμην]{.greek-added}[28:31]{.aside}

