---
title: "Collation of Byz^RP^ vs 32831 (2831)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 2831 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=32831).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 2831                                   	| λογος                              	|
| 2831 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 2831 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 2831               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 2831                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 2831 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 2831                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Matthew

### Chapter 1

[εζεκιας]{.greek-omitted} [δε]{.greek-omitted} [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον μανασση μ[ανασσης]{.greek-supplied} δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αμων [αμων]{.greek-omitted} [αμω[ς]{.greek-supplied}]{.greek-added} [δε]{.greek-supplied} [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιωσιαν[1:10]{.aside}

ιωσιας δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον [ιωακειμ]{.greek-added} [ιωακειμ]{.greek-added} [δε]{.greek-added} [εγεννησε]{.greek-added} [τον]{.greek-added} [ιεχονιαν]{.greek-omitted} [ιεχωνιαν]{.greek-added} και τους αδελφους αυτου επι της μετοικεσιας βαβυλωνος[1:11]{.aside}

μετα δε την μετοικεσιαν βαβυλωνος ιεχονιας [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον σαλαθιηλ σαλαθιηλ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ζοροβαβελ[1:12]{.aside}

ζοροβαβελ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αβιουδ αβιουδ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ελιακειμ ελιακειμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αζωρ[1:13]{.aside}

αζωρ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον σαδωκ σαδωκ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αχειμ αχειμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ελιουδ[1:14]{.aside}

ελιουδ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ελεαζαρ ελεαζαρ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ματθαν ματθαν δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιακωβ[1:15]{.aside}

ιακωβ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιωσηφ τον ανδρα μαριας εξ ης εγεννηθη [ιησους]{.greek-abbr} ο λεγομενος χριστος[1:16]{.aside}

πασαι ουν αι γενεαι απο αβρααμ εως [δαυιδ]{.greek-abbr} γενεαι δεκατεσσαρες [και]{.greek-supplied} [α]{.greek-supplied}[πο]{.unclear} [δαυιδ]{.greek-abbr} εως της μετοικεσιας [βα]{.greek-supplied}[β]{.unclear}υλωνος γενεαι δεκατεσσαρες και απο της μετοικεσιας βαβυλωνος εως [του]{.corr} [[χριστου]{.greek-abbr}]{.corr} γενεαι δεκατεσσαρες[1:17]{.aside}

του δε [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} η γεννησις ουτως ην μνηστευθεισης γαρ της [μητρος]{.greek-abbr} αυτου μαριας τω ιωσ[η]{.unclear}φ πριν η συνελθειν αυτους ευρεθη εν γαστρι εχουσα εκ [πνευματος]{.greek-abbr} αγιου[1:18]{.aside}

ιωσηφ δε ο ανηρ αυτης δικαιος ων και μη θελων αυτην παραδειγματισαι [εβουληθη]{.greek-omitted} [ηβουληθη]{.greek-added} λαθρα απολυσαι αυτην[1:19]{.aside}

ταυτα δε αυτου ενθυμηθεντος ιδου αγγελ[ο]{.unclear}ς [κυριου]{.greek-abbr} κατ οναρ εφανη αυτω λεγων ιωσηφ υιος [δαυιδ]{.greek-abbr} μη [φοβηθης]{.greek-omitted} [φοβηθεις]{.greek-added} παραλαβειν [μαριαμ]{.greek-omitted} [μαριαν]{.greek-added} την γυναικα σου το γαρ εν αυτη γεννηθεν εκ [πνευματος]{.greek-abbr} εστιν αγιου[1:20]{.aside}

τεξεται δε υιον και καλεσεις το ονομα αυτου [ιησουν]{.greek-abbr} αυτος γαρ σωσει τον λαον αυτου απο των αμαρτιων αυτων[1:21]{.aside}

τουτο δε ολον γεγονεν ινα πληρωθη το ρηθεν υπο του [κυριου]{.greek-abbr} δια του προφητου λεγοντος[1:22]{.aside}

ιδου η παρθενος εν γαστρι εξει και τεξεται υιον και [καλεσουσιν]{.greek-omitted} [καλεσουσι]{.greek-added} το ονομα αυτου εμμανουηλ ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον μεθ [υμων]{.greek-added} [ημων]{.corr} ο [θεος]{.greek-abbr}[1:23]{.aside}

διεγερθεις δε ο ιω[σηφ]{.greek-supplied} απο του υπνου εποιησεν ως προσεταξεν αυτω ο αγγελος [κυριου]{.greek-abbr} και [παρελαβεν]{.greek-omitted} [παρελαβε]{.greek-added} την γυναικα αυτου[1:24]{.aside}

και ουκ εγινωσκεν αυτην εως ου [ετεκεν]{.greek-omitted} [ετεκε]{.greek-added} τον υιον αυτης τον πρωτοτοκον και [εκαλεσεν]{.greek-omitted} [εκαλεσε]{.greek-added} το ονομα αυτου [ιησουν]{.greek-abbr}[1:25]{.aside}

### Chapter 2

του δε [ιησου]{.greek-abbr} γεννηθεντος εν βηθλεεμ της ιουδαιας εν ημεραις ηρωδου του βασιλεως ιδου μαγοι απο ανατολων παρεγενοντο εις ιεροσολυμα[2:1]{.aside}

λεγοντες που εστιν ο τεχθεις βασιλευς των ιουδαιων [ειδομεν]{.greek-omitted} [ιδομεν]{.greek-added} γαρ αυτου τον αστερα εν τη ανατολη και ηλθομεν προσκυνησαι αυτω[2:2]{.aside}

ακουσας δε ηρωδης ο βασιλευς εταραχθη και πασα ιεροσολυμα μετ αυτου[2:3]{.aside}

και συναγαγων παντας τους αρχιερεις και [τους]{.greek-added} γραμματεις του λαου ε[πυνθ]{.unclear}ανετο παρ αυτων που ο [χριστος]{.greek-abbr} γενναται[2:4]{.aside}

οι δε ειπον αυτω εν βηθλεεμ της ιουδαιας ουτως γαρ γεγραπται δια του προφητου [λεγοντος]{.greek-added}[2:5]{.aside}

και συ βηθλεεμ γη ιουδα ουδαμως ελαχιστη ει εν τοις ηγεμοσιν ιουδα [ε]{.unclear}κ σου γαρ εξελευσεται ηγουμενος οστις ποιμανει τον λαον μου τον [ισραηλ]{.greek-abbr}[2:6]{.aside}

τοτε ηρωδης λαθρα καλεσας τους μαγους [ηκριβωσεν]{.greek-omitted} [ηκριβωσε]{.greek-added} παρ αυτων τον χρονον του φαινομενου αστερος[2:7]{.aside}

και πεμψας αυτους εις βηθλεεμ ειπεν πορευθεντες ακριβως εξετασατε περι του παιδιου επαν δε ευρητε απαγγειλατε μοι οπως καγω ελθων προσκυνησω αυτω[2:8]{.aside}

οι δε ακουσαντες του βασιλεως επορευθησαν και ιδου ο αστηρ ον ειδον εν τη ανατολη προηγεν αυτους εως ελθων εστη επανω ου ην το παιδιον[2:9]{.aside}

ιδοντες δε τον αστερα εχαρησαν χαραν μεγαλην σφοδρα[2:10]{.aside}

και ελθοντες εις την οικιαν ειδον το παιδιον μετα μαριας της [μητρος]{.greek-abbr} αυτου και πεσοντες προσεκυνησαν αυτω και ανοιξαντες τους θησαυρους αυτων προσηνεγκαν αυτω δωρα χρυσον και λιβανον και σμυρναν[2:11]{.aside}

και χρηματισθεντες κατ οναρ μη [ανακαμψαι]{.greek-omitted} [αναγκαψαι]{.greek-added} προς ηρωδην δι αλλης οδου [αν]{.greek-supplied}[ε]{.unclear}χωρησαν εις την χωραν αυτων[2:12]{.aside}

αναχωρησαντων δε αυτων ιδου αγγελος [κυριου]{.greek-abbr} φαινεται κατ οναρ τω ιωσηφ λεγων εγερθεις παραλαβε το παιδιον και την [μητερα]{.greek-abbr} αυτου και φευγε εις αιγυπτον και ισθι εκει εως αν ειπω σοι μελλει γαρ ηρωδης ζητειν το παιδιον του απολεσαι αυτο[2:13]{.aside}

ο δε εγερθεις [παρελαβεν]{.greek-omitted} [παρελαβε]{.greek-added} το παιδιον και την [μητερα]{.greek-abbr} αυτου νυκτος και ανεχωρησεν εις αιγυπτον[2:14]{.aside}

και ην εκει εως της τελευτης ηρωδου ινα πληρωθη το ρηθεν υπο του [κυριου]{.greek-abbr} δια του προφητου λεγοντος εξ αιγυπτου εκαλεσα τον υιον μου[2:15]{.aside}

τοτε ηρωδης ιδων οτι ενεπαιχθη υπο των μαγων εθυμωθη λιαν και αποστ[ει]{.unclear}λ[ας]{.unclear} [ανειλεν]{.greek-omitted} [ανειλε]{.greek-added} παντας τους παιδας τους εν βηθλεεμ και εν [πασιν]{.greek-omitted} [παση]{.greek-added} τοις οριοις αυτης απο διετους και κατωτερω κατα τον χρονον ον [ηκριβωσεν]{.greek-omitted} [ηκριβωσε]{.greek-added} παρα των μαγων[2:16]{.aside}

τοτε επληρωθη το ρηθεν υπο ιερεμιου του [π]{.greek-supplied}[ρο]{.unclear}φητου λεγοντος[2:17]{.aside}

φωνη εν ραμα ηκουσθη θρηνος και κλαυθμος και οδυρμος πολυς ραχηλ κλαιουσα τα τεκνα αυτης και ουκ [ηθελεν]{.greek-omitted} [ηθελ[ε]{.unclear}]{.greek-added} παρακληθηναι οτι ουκ [εισιν]{.greek-omitted} [εισι]{.greek-added}[2:18]{.aside}

τελ[ε]{.unclear}υτησαντος δε του ηρωδου ιδου αγγελος [κυριου]{.greek-abbr} κατ οναρ φαινεται τω ιωσηφ εν αιγυπτω[2:19]{.aside}

λεγων [εγερθεις]{.greek-omitted} [αναστας]{.greek-added} παραλαβε το παιδιον και την [μητερα]{.greek-abbr} αυτου και πορευου εις γην [ισραηλ]{.greek-abbr} [τεθνηκασιν]{.greek-omitted} [τεθνηκασι]{.greek-added} γαρ οι ζητουντες την ψυχην του παιδιου[2:20]{.aside}

ο δε εγερθεις [παρελαβεν]{.greek-omitted} [παρελαβε]{.greek-added} το παιδιον και την [μητερα]{.greek-abbr} αυτου και ηλθεν εις γην [ισραηλ]{.greek-abbr}[2:21]{.aside}

ακουσας δε οτι αρχελαος βασιλευει επι της ιουδαιας αντι ηρωδου του [πατρος]{.greek-abbr} αυτου εφοβηθη εκει απελθειν χρηματισθεις δε κατ οναρ ανεχωρησεν εις τα μερη της γαλιλαιας[2:22]{.aside}

και ελθων κατωκησεν εις πολιν λεγομενην ναζαρετ οπως πληρωθη το ρηθεν δια των προφητων οτι ναζωραιος κληθησεται[2:23]{.aside}

### Chapter 3

εν [δε]{.greek-omitted} ταις ημεραις εκειναις παραγινεται ιωαννης ο βαπτ[ι]{.unclear}σ[της]{.greek-supplied} [κη]{.greek-supplied}ρυσσων εν τη ερημω της ιουδαιας[3:1]{.aside}

και λεγων μετανοειτε [ηγγικεν]{.greek-omitted} [ηγγικε]{.greek-added} γαρ η βασιλεια των [ουρανων]{.greek-abbr}[3:2]{.aside}

ουτος γαρ εστιν ο ρηθεις υπο ησαιου του προφητου λεγοντος φωνη βοωντος εν τη ερημω ετοιμασατε την οδον [κυριου]{.greek-abbr} ευθειας ποιειτε τας τριβους αυτου[3:3]{.aside}

αυτος δε ο ιωαννης [ειχεν]{.greek-omitted} [ειχε]{.greek-added} το ενδυμα αυτου απο τριχων καμηλου και ζωνην δερματινην περι την οσφυν αυτου η δε τροφη αυτου ην ακριδες και μελι αγριον[3:4]{.aside}

τοτε εξεπορευετο προς αυτον ιεροσολυμα και πασα η ιουδαια και πασα η περιχωρος του ιορδανου[3:5]{.aside}

και εβαπτιζοντο εν τω ιορδανη [ποταμω]{.greek-added} υπ αυτου εξομολογουμενοι τας αμαρτιας αυτων[3:6]{.aside}

ιδων δε πολλους των φαρισαιων και σαδδουκαιων ερχομενους επι το βαπτισμα αυτου ειπεν αυτοις γεννηματα εχιδνων τις υπεδειξεν υμιν φυγειν απο της μελλουσης οργης[3:7]{.aside}

ποιησατε ουν καρπον αξιον [της]{.greek-supplied} μετανοιας[3:8]{.aside}

και μη δοξητε λεγειν [εν]{.greek-supplied} [ε]{.greek-supplied}[α]{.unclear}υτοις [πατερα]{.greek-abbr} εχομεν τον αβρααμ λεγω γαρ υμιν οτι δυναται ο [θεος]{.greek-abbr} εκ των λιθων τουτων εγειρα[ι]{.unclear} τεκνα τω αβρααμ[3:9]{.aside}

ηδη δε και η αξινη προς την ριζαν των δενδρων κειται παν ουν δενδρον μη ποιουν καρπον καλον εκκοπτεται και εις πυρ βαλλεται[3:10]{.aside}

εγω μεν βαπτιζω υμας εν υδατι εις μετανοιαν ο δε οπισω μου ερχομενος ισχυροτερος μου εστιν ου ουκ ειμι ικανος τα υποδηματα βαστασαι αυτος υμας βαπτισει εν [πνευματι]{.greek-abbr} αγιω [και]{.greek-added} [πυρι]{.greek-added}[3:11]{.aside}

ου το πτυον εν τη χειρι αυτου και διακαθαριει την αλωνα αυτου και συναξει τον σιτον [αυτου]{.greek-omitted} εις την αποθηκην [αυτου]{.greek-added} το δε αχυρον κατακαυσει πυρι ασβεστω[3:12]{.aside}

τοτε παραγινεται ο [ιησους]{.greek-abbr} απο της γαλιλαιας επι τον ιορδανην προς τον ιωαννην του βαπτισθηναι υπ αυτου[3:13]{.aside}

ο δε ιωαννης διεκωλυεν αυτον λεγων [εχ]{.greek-added} [εγω]{.corr} χρειαν εχω υπο σου βαπτισθηναι και συ ερχη προς με[3:14]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν προς αυτον αφες αρτι ουτως γαρ πρεπον εστιν ημιν πληρωσαι πασαν δικαιοσυνην τοτε αφιησιν αυτον[3:15]{.aside}

και βαπτισθεις ο [ιησους]{.greek-abbr} ανεβη ευθυς απο του υδατος και ιδου ανεωχθησαν αυτω οι [ουρανοι]{.greek-abbr} και ειδεν το [πνευμα]{.greek-abbr} του [θεου]{.greek-abbr} καταβαινον ωσει περιστεραν και ερχομενον επ αυτον[3:16]{.aside}

και ιδου φωνη εκ των [ουρανων]{.greek-abbr} λεγουσα ουτος εστιν ο υιος μου ο αγαπητος εν ω ευδοκησα[3:17]{.aside}

### Chapter 4

τοτε [ανηχθη]{.greek-added} ο [ιησους]{.greek-abbr} [ανηχθη]{.greek-omitted} εις την ερημον υπο του [πνευματος]{.greek-abbr} πειρασθηναι υπο του διαβολου[4:1]{.aside}

και νηστευσας ημερας τεσσαρακοντα και νυκτας τεσσαρακοντα υστερον [επεινασεν]{.greek-omitted} [επεινασε]{.greek-added}[4:2]{.aside}

και προσελθων αυτω ο πειραζων ειπεν ει υιος ει του [θεου]{.greek-abbr} ειπε ινα οι λιθοι ουτοι αρτοι γενωνται[4:3]{.aside}

ο δε αποκριθεις ειπεν γεγραπται ουκ επ αρτω μονω ζησεται [ο]{.greek-added} [ανθρωπος]{.greek-abbr} αλλ [επι]{.greek-omitted} [εν]{.greek-added} παντι ρηματι εκπορευομενω δια στοματος [θεου]{.greek-abbr}[4:4]{.aside}

τοτε παραλαμβανει αυτον ο διαβολος εις την αγιαν πολιν και ιστησιν αυτον επι το πτερυγιον του ιερου[4:5]{.aside}

και λεγει αυτω ει υιος ει του [θεου]{.greek-abbr} βαλε σεαυτον κατω γεγραπται γαρ οτι τοις αγγελοις αυτου [εντελειται]{.greek-omitted} [εντελειτε]{.greek-added} περι σου και επι χειρων [αρουσιν]{.greek-omitted} [αρουσι]{.greek-added} σε μηποτε προσκοψης προς λιθον τον ποδα σου[4:6]{.aside}

εφη αυτω ο [ιησους]{.greek-abbr} παλιν γεγραπται ουκ [εκπειρασεις]{.greek-omitted} [εκπειρασης]{.greek-added} [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου[4:7]{.aside}

παλιν παραλαμβανει αυτον ο διαβολος εις ορος υψηλον λιαν και δεικνυσιν αυτω πασας τας βασιλειας του κοσμου και την δοξαν αυτων[4:8]{.aside}

και λεγει αυτω ταυτα παντα σοι δωσω εαν πε[σω]{.unclear}ν προσκυνησης μοι[4:9]{.aside}

τοτε λεγει αυτω ο [ιησους]{.greek-abbr} υπαγε οπισω μου σατανα γεγραπται γαρ [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου προσκυνησεις και αυτω μονω [λατρευσεις]{.greek-omitted} [λατρευσης]{.greek-added}[4:10]{.aside}

τοτε αφιησιν αυτον ο διαβολος και ιδου αγγελοι προσηλθον και διηκονουν αυτω[4:11]{.aside}

ακουσας δε [ο]{.greek-omitted} [ιησους]{.greek-omitted} οτι ιωαννης παρεδοθη ανεχωρησεν εις την γαλιλαιαν[4:12]{.aside}

και καταλιπων την ναζαρετ ελθων κατωκησεν εις καπερναουμ την παραθαλασσιαν εν οριοις ζαβουλων και νεφθαλειμ[4:13]{.aside}

ινα πληρωθη το [ρη]{.greek-added} [ρηθεν]{.greek-omitted} [θεν]{.greek-added} δια ησαιου του προφητου λεγ[οντος]{.greek-supplied}[4:14]{.aside}

γη ζαβουλων και γη νεφθαλειμ οδον θαλασσης περαν του ιορδανου γαλιλαια των εθνων[4:15]{.aside}

ο λαος ο καθημενος εν σκοτει ειδεν φως μεγα και τοις καθημενοις εν χωρα και σκια θανατου φως ανετειλεν αυτοις[4:16]{.aside}

απο τοτε ηρξατο ο [ιησους]{.greek-abbr} κηρυσσειν και λεγειν μετανοειτε [ηγγικεν]{.greek-omitted} [ηγγικε]{.greek-added} γαρ η βασιλεια των [ουρανων]{.greek-abbr}[4:17]{.aside}

περιπατων δε παρα την θαλασσαν της γαλιλαιας ειδεν δυο αδελφους σιμωνα τον [λεγομενον]{.greek-omitted} [καλουμενον]{.greek-added} πετρον και ανδρεαν τον αδελφον αυτου βαλλοντας [αμφιβλιστρον]{.greek-added} [αμφιβληστρον]{.corr} εις την θαλασσαν ησαν γαρ αλιεις[4:18]{.aside}

και λεγει αυτοις δευτε οπισω μου και ποιησω υμας αλιεις [ανθρωπων]{.greek-abbr} [γενεσθαι]{.greek-added}[4:19]{.aside}

οι δε ευθεως αφεντες τα δικτυα ηκολουθησαν αυτω[4:20]{.aside}

και προβας εκειθεν [ολιγον]{.greek-added} ειδεν αλλους δυο αδελφους ιακωβον τον του ζεβεδαιου και ιωαννην τον αδελφον αυτου εν τω πλοιω μετα ζεβεδαιου του [πατρος]{.greek-abbr} αυτων καταρτιζοντας [τ]{.unclear}α δικτυα αυτων και εκαλεσεν αυτους[4:21]{.aside}

οι δε ευθεως αφεντες το πλοιον και τον [πατερα]{.greek-abbr} αυτων ηκολουθησαν αυτω[4:22]{.aside}

και περιηγεν ολην την γαλιλαιαν ο [ιησους]{.greek-abbr} διδασκων εν ταις συναγωγαις αυτων και κηρυσσων το ευαγγελιον της βασιλειας και θεραπευων πασαν νοσον και πασαν μαλακιαν εν τω λαω[4:23]{.aside}

και απηλθεν η ακοη αυτου εις ολην την συριαν και προσηνεγκαν αυτω παντας τους κακως εχοντας ποικιλαις [νοσοις]{.greek-omitted} [νοσσοις]{.greek-added} και βασανοις συνεχομενους και δαιμονιζομενους και σεληνιαζομενους και παραλυτικους και εθεραπευσεν αυτους[4:24]{.aside}

και ηκολουθησαν αυτω οχλοι πολλοι απο της γαλιλαιας και δεκαπολεως και ιεροσολυμων και ιουδαιας και περαν του ιορδανου[4:25]{.aside}

### Chapter 5

ιδων δε τους οχλους ανεβη εις το ορος και [καθισαντος]{.greek-omitted} [καθησαντος]{.greek-added} αυτου προσηλθον αυτω οι μαθητα[ι]{.greek-supplied} αυτου[5:1]{.aside}

και ανοιξας το στομα αυτου [ε]{.unclear}διδασκεν α[υτους]{.greek-supplied} [λ]{.greek-supplied}[ε]{.unclear}γων[5:2]{.aside}

μακαρ[ιοι]{.greek-supplied} [οι]{.greek-supplied} πτωχοι [τ]{.unclear}ω [πνευματι]{.greek-abbr} ο[τι]{.greek-supplied} [α]{.greek-supplied}υτων εστιν η βασιλεια των [ουρανων]{.greek-abbr}[5:3]{.aside}

μακαριοι οι πενθουντες οτι αυτοι παρακληθησονται[5:4]{.aside}

μακαριοι οι πραεις οτι αυτοι [κληρονομησουσιν]{.greek-omitted} [κληρονομησουσι]{.greek-added} την γην[5:5]{.aside}

μακαριοι οι πεινωντες και διψωντες την δικαιοσυνην οτι αυτοι χορτασθησονται[5:6]{.aside}

μακ[α]{.greek-supplied}ριοι οι ελεημονες οτι αυτοι ελεηθησονται[5:7]{.aside}

μακαριοι οι καθαροι τη καρδια οτι αυτοι τον [θεον]{.greek-abbr} οψονται[5:8]{.aside}

μακαριοι οι ειρηνοποιοι οτι αυτοι υιοι [θεου]{.greek-abbr} κληθησονται[5:9]{.aside}

μακαριοι οι δεδιωγμενοι [ενεκεν]{.greek-omitted} [ενεκε]{.greek-added} δικαιοσυνης οτι αυτων εστιν η βασιλεια των [ουρανων]{.greek-abbr}[5:10]{.aside}

μακαριοι εστε οταν ονειδισωσιν υμας και διωξωσιν και [ειπωσιν]{.greek-omitted} [ειπωσι]{.greek-added} παν πονηρον ρημα καθ [υμων]{.greek-omitted} [ημων]{.greek-added} ψευδομενοι ενεκεν εμου[5:11]{.aside}

χαιρετε και αγαλλιασθε οτι ο μισθος υμων πολυς εν τοις [ουρανοις]{.greek-abbr} ουτως γαρ εδιωξαν τους προφητας τους προ υμων[5:12]{.aside}

υμεις εστε το αλας της γης εαν δε το αλας μωρανθη εν τι[ν]{.unclear}ι αλισθησεται εις ουδεν ισχυει ετι ει μη βληθηναι εξω και καταπατεισθαι υπο των [ανθρωπων]{.greek-abbr}[5:13]{.aside}

υμεις εστε το φως του κοσμου ου δυναται πολις κρυβηναι επανω ορους κειμενη[5:14]{.aside}

ουδε [καιουσιν]{.greek-omitted} [καιουση]{.greek-added} λυχνον και τιθεασιν αυτον υπο τον μοδιον αλλ επι την λυχνιαν και λαμπει [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις εν τη οικια[5:15]{.aside}

ουτως λαμψατω το φως υμων [εμπροσθεν]{.greek-omitted} [εμπροσθε]{.greek-added} των [ανθρωπων]{.greek-abbr} οπως ιδωσιν υμων τα καλα εργα και [δοξασωσιν]{.greek-omitted} [δοξασουσι]{.greek-added} τον [πατερα]{.greek-abbr} υμων τον εν τοις [ουρανοις]{.greek-abbr}[5:16]{.aside}

μη νομισητε οτι ηλθον καταλυσαι τον νομον η τους προφητας ουκ ηλθον καταλυσαι αλλα πληρωσαι[5:17]{.aside}

αμην γαρ λεγω υμιν εως αν παρελθη ο [ουρανος]{.greek-abbr} και η γη ιωτα εν η μια κεραια ου μη παρελθη απο του νομου εως αν παντα γενηται[5:18]{.aside}

ος εαν ουν λυση μιαν των εντολων τουτων των ελαχιστων και διδαξη ουτως τους [ανθρωπους]{.greek-abbr} ελαχιστος κληθησεται εν τη βασιλεια των [ουρανων]{.greek-abbr} ος δ αν ποιηση και διδαξη ουτος μεγας κληθησεται εν τη βασιλεια των [ουρανων]{.greek-abbr}[5:19]{.aside}

λεγω γαρ υμιν οτι εαν μη περισσευση η δικαιοσυνη υμων πλειον των γραμματεων και φαρισαιων ου μη εισελθητε εις την βασιλειαν των [ουρανων]{.greek-abbr}[5:20]{.aside}

ηκουσατε οτι ερρεθη τοις αρχαιοις ου [φονευσεις]{.greek-omitted} [φονευσης]{.greek-added} ος δ αν φονευση ενοχος εσται τη κρισει[5:21]{.aside}

εγω δε λεγω υμιν οτι πας ο οργιζομενος τω αδελφω αυτου εικη ενοχος εσται τη κρισει ος δ αν ειπη τω αδελφω αυτου ρακα ενοχος εσται τω συνεδριω ος δ αν ειπη μωρε ενοχος εσται εις την γεενναν του πυρος[5:22]{.aside}

εαν ουν προσφερης το δωρον σου επι το θυσιαστηριον και εκει μνησθης οτι ο αδελφος σου εχει τι κατα σου[5:23]{.aside}

αφες εκει το δωρον σου εμπροσθεν του θυσιαστηριου και υπαγε πρωτον διαλλαγηθι τω αδελφω σου και τοτε ελθων προσφερε το δωρον σου[5:24]{.aside}

ισθι ευνοων τω αντιδικω σου ταχυ εως οτου ει εν τη οδω μετ αυτου μηποτε σε παραδω ο αντιδικος τω κριτη και ο κριτης σε παραδω τω υπηρετη και εις φυλακην βληθηση[5:25]{.aside}

αμην λεγω σοι [οτι]{.greek-added} ου μη εξελθης εκειθεν εως αν αποδως τον εσχατον κοδραντην[5:26]{.aside}

ηκουσατε οτι ερρεθη ου [μοιχευσεις]{.greek-omitted} [μοιχευσης]{.greek-added}[5:27]{.aside}

εγω δε λεγω υμιν οτι πας ο βλεπων γυναικα προς το επιθυμησαι αυτην ηδη εμοιχευσεν αυτην εν τη καρδια αυτου[5:28]{.aside}

ει δε ο οφθαλμος σου ο δεξιο[ς]{.unclear} σκανδαλιζει σε εξελε αυτον και βαλε απο σου συμφερει γαρ σοι ινα [αποληται]{.greek-omitted} [απολειται]{.greek-added} εν των μελων σου και μη ολον το σωμα σου [βληθη]{.greek-omitted} [βληθει]{.greek-added} εις [την]{.greek-added} γεενναν[5:29]{.aside}

και ει η δεξια σου χειρ σκανδαλιζει σε εκκοψον αυτην και βαλε απο σου συμφερει γαρ σοι ινα [αποληται]{.greek-omitted} [απολητε]{.greek-added} εν των μελων σου και μη ολον το σωμα σου βληθη εις γεενναν[5:30]{.aside}

ερρεθη δε οτι ος αν απολυση την γυναικα αυτου δοτω αυτη [βιβλιον]{.greek-added} [αποστασιον]{.greek-omitted} [αποστασιου]{.greek-added}[5:31]{.aside}

εγω δε λεγω υμιν οτι [ος]{.greek-omitted} [αν]{.greek-omitted} [απολυση]{.greek-omitted} [πας]{.greek-added} [ο]{.greek-added} [απολυων]{.greek-added} την γυναικα αυτου παρεκτος λογου πορνειας ποιει αυτην [μοιχασθε]{.greek-added} [μοιχασθαι]{.corr} και ος εαν απολελυμενην γαμηση μοιχαται[5:32]{.aside}

παλιν ηκουσατε οτι ερρεθη τοις αρχαιοις ουκ επιορκησεις αποδωσεις δε [τω]{.greek-omitted} [κυριω]{.greek-abbr} τους ορκους σου[5:33]{.aside}

εγω δε λεγω υμιν μη ομοσαι ολως μητε εν τω [ουρανω]{.greek-abbr} οτι θρονος [εστιν]{.greek-omitted} [εστι]{.greek-added} του [θεου]{.greek-abbr}[5:34]{.aside}

μητε εν τη γη οτι υποποδιον [εστιν]{.greek-omitted} [εστι]{.greek-added} των ποδων αυτου μητε εις ιεροσολυμα οτι πολις [εστιν]{.greek-omitted} [εστι]{.greek-added} του μεγαλου βασιλεως[5:35]{.aside}

μητε εν τη κεφαλη σου ομοσης οτι ου δυνασαι μιαν [τριχα]{.greek-omitted} [τριχαν]{.greek-added} λευκην η [μελαιναν]{.greek-omitted} [μελεναν]{.greek-added} ποιησαι[5:36]{.aside}

εστω δε ο λογος υμων ναι ναι ου ου το δε περισσον τουτων εκ του πονηρου εστιν[5:37]{.aside}

ηκουσατε οτι ερρεθη οφθαλμον αντι [οφθαλμον]{.greek-added} [οφθαλμου]{.corr} και οδοντα αντι οδοντος[5:38]{.aside}

εγω δε λεγω υμιν μη αντιστηναι τω πονηρω αλλ οστις σε [ραπισει]{.greek-omitted} [ραπιση]{.greek-added} επι την δεξιαν [σου]{.greek-added} σιαγονα στρεψον αυτω και την αλλην[5:39]{.aside}

και τω θελοντι σοι κριθηναι και τον χιτωνα σου λαβειν αφες αυτω και [το]{.greek-omitted} [τω]{.greek-added} ιματιον[5:40]{.aside}

και οστις σε [αγγαρευσει]{.greek-omitted} [αγγαρευση]{.greek-added} μιλιον εν υπαγε μετ αυτου δυο[5:41]{.aside}

τω αιτουντι σε διδου και τον θελοντα απο σου δανεισασθαι μη αποστραφης[5:42]{.aside}

ηκουσατε οτι ερρεθη [αγαπησεις]{.greek-omitted} [αγαπησης]{.greek-added} τον πλησιον σου και [μισησεις]{.greek-omitted} [μησησης]{.greek-added} τον εχθρον σου[5:43]{.aside}

εγω δε λεγω υμιν αγαπατε τους εχθρους υμων [ευλογειτε]{.greek-omitted} [ευλογητε]{.greek-added} τους καταρωμενους υμας καλως ποιειτε τοις μισουσιν υμας και [προσευχεσθε]{.greek-omitted} [προσευχεσθαι]{.greek-added} υπερ των [επηρεαζοντων]{.greek-omitted} [επερεαζοντων]{.greek-added} υμας και διωκοντων υμας[5:44]{.aside}

οπως γενησθε υιοι του [πατρος]{.greek-abbr} υμων του εν [τοις]{.greek-omitted} [ουρανοις]{.greek-abbr} οτι τον ηλιον αυτου ανατελλει επι πονηρους και αγαθους και βρεχει επι δικαιους και αδικους[5:45]{.aside}

εαν γαρ αγαπησητε τους αγαπωντας υμας τινα μισθον εχετε ουχι και οι τελωναι [τουτο]{.greek-added} [το]{.greek-omitted} [αυτο]{.greek-omitted} [ποιουσιν]{.greek-omitted} [ποιουσι]{.greek-added}[5:46]{.aside}

και εαν ασπασησθε τους φιλους υμων μονον τι περισσον ποιειτε ουχι και οι [τελωναι]{.greek-omitted} [ουτως]{.greek-omitted} [εθνηκοι]{.greek-added} [[εθνικοι]{.corr}]{.greek-added} [τουτο]{.greek-added} [ποιουσιν]{.greek-omitted} [ποιουσι]{.greek-added}[5:47]{.aside}

εσεσθε ουν υμεις τελειοι ωσπερ ο [πατηρ]{.greek-abbr} υμων ο [εν]{.greek-omitted} [τοις]{.greek-omitted} [ουρανοις]{.greek-omitted} [[ουρανιος]{.greek-abbr}]{.greek-added} τελειος [εστιν]{.greek-omitted} [εστι]{.greek-added}[5:48]{.aside}

### Chapter 6

προσεχετε [δε]{.greek-added} την ελεημοσυνην υμων μη ποιειν εμπροσθεν των [ανθρωπων]{.greek-abbr} προς το θεαθηναι αυτοις ει δε [μηγε]{.greek-omitted} [μη]{.greek-added} [γε]{.greek-added} μισθον ουκ εχετε παρα τω [πατρι]{.greek-abbr} υμων τω εν τοις [ουρανοις]{.greek-abbr}[6:1]{.aside}

οταν ουν [ποιης]{.greek-omitted} [ποιεις]{.greek-added} ελεημοσυνην μη σαλπισης εμπροσθεν σου ωσπερ οι υποκριται ποιουσιν εν ταις [συ]{.greek-added} [συναγωγαις]{.greek-omitted} [ναγωγαις]{.greek-added} και εν ταις ρυμαις οπως δοξασθωσιν υπο των [ανθρωπων]{.greek-abbr} αμην λεγω υμιν [απεχουσιν]{.greek-omitted} [απεχουσι]{.greek-added} τον μισθον αυτων[6:2]{.aside}

σου δε ποιουντος ελεημοσυνην μη γνωτω η αριστερα σου τι ποιει η δεξια σου[6:3]{.aside}

οπως η σου η ελεημοσυνη εν τω κρυπτω και ο [πατηρ]{.greek-abbr} σου ο βλεπων εν τω κρυπτω αυτος αποδωσει σοι εν τω φανερω[6:4]{.aside}

και οταν προσευχη ουκ εση ωσπερ οι υποκριται οτι φιλουσιν εν ταις συναγωγαις και εν ταις γωνιαις των πλατειων εστωτες προσευχεσθαι οπως αν φανωσιν τοις [ανθρωποις]{.greek-abbr} αμην λεγω υμιν οτι [απεχουσιν]{.greek-omitted} [απεχουσι]{.greek-added} τον μισθον αυτων[6:5]{.aside}

συ δε οταν προσευχη εισελθε εις το [ταμιειον]{.greek-omitted} [ταμειον]{.greek-added} σου και κλεισας την θυραν σου προσευξαι τω [πατρι]{.greek-abbr} σου [τω]{.greek-omitted} εν τω κρυπτω και ο [πατηρ]{.greek-abbr} σου ο βλεπων εν τω κρυπτω αποδωσει σοι εν τω φανερω[6:6]{.aside}

προσευχομενοι δε μη [βαττολογησητε]{.greek-omitted} [βαττολογειτε]{.greek-added} ωσπερ οι [εθνηκοι]{.greek-added} [εθνικοι]{.corr} [δοκουσιν]{.greek-omitted} [δοκουσι]{.greek-added} γαρ οτι εν τη πολυλογια αυτων εισακουσθησονται[6:7]{.aside}

μη ουν [ομοιωθητε]{.greek-omitted} [ωμοιωθητε]{.greek-added} αυτοις οιδεν γαρ ο [πατηρ]{.greek-abbr} υμων ων χρειαν εχετε προ του υμας αιτησαι αυτον[6:8]{.aside}

ουτως ουν [προσευχεσθε]{.greek-omitted} [προσευχεσθαι]{.greek-added} υμεις [πατερ]{.greek-abbr} ημων ο εν τοις [ουρανοις]{.greek-abbr} αγιασθητω το [ο]{.unclear}νομα σου[6:9]{.aside}

ελθετω η βασιλεια σου γενηθητω το θελημα σου ως εν [ουρανω]{.greek-abbr} και επι της γης[6:10]{.aside}

τον αρτον ημων τον επιουσιον δος ημιν σημερον[6:11]{.aside}

και αφες ημιν τα οφειληματα ημων ως και ημεις αφιεμεν τοις οφειλεταις ημων[6:12]{.aside}

και μη εισενεγκης ημας εις πειρασμον αλλα ρυσαι ημας απο του πονηρου οτι σου εστιν η βασιλεια και η δυναμις και η δοξα εις τους αιωνας αμην[6:13]{.aside}

εαν γαρ αφητε τοις [ανθρωποις]{.greek-abbr} τα παραπτωματα αυτων αφησει και υμιν ο [πατηρ]{.greek-abbr} υμων ο [ουρανιος]{.greek-abbr} [τα]{.greek-added} [παραπτωματα]{.greek-added} [υμων]{.greek-added}[6:14]{.aside}

εαν δε μη αφητε τοις [ανθρωποις]{.greek-abbr} τα παραπτωματα αυτων ουδε ο [πατηρ]{.greek-abbr} υμων αφησει τα παραπτωματα υμων[6:15]{.aside}

οταν δε νηστευητε μη [γινεσθε]{.greek-omitted} [γινεσθαι]{.greek-added} ωσπερ οι υποκριται σκυθρωποι [αφανιζουσιν]{.greek-omitted} [αφανιζουσι]{.greek-added} γαρ τα προσωπα αυτων οπως [φανωσιν]{.greek-omitted} [φανωσι]{.greek-added} τοις [ανθρωποις]{.greek-abbr} νηστευοντες αμην λεγω υμιν οτι [απεχουσιν]{.greek-omitted} [απεχουσι]{.greek-added} τον μισθον αυτων[6:16]{.aside}

συ δε νηστευων αλειψαι σου την κεφαλην και το προσωπον σου νιψαι[6:17]{.aside}

οπως μη φανης τοις [ανθρωποις]{.greek-abbr} νηστευων αλλα τω [πατρι]{.greek-abbr} σου τω εν τω κρυπτω και ο [πατηρ]{.greek-abbr} σου ο βλεπων εν τω κρυπτω αποδωσει σοι [εν]{.greek-added} [τω]{.greek-added} [φανερω]{.greek-added}[6:18]{.aside}

μη θησαυριζετε υμιν θησαυρους επι της γης οπου σης [διαφθειρει]{.greek-added} και βρωσις αφανιζει και οπου κλεπται [διορυσσουσιν]{.greek-omitted} [διορυσσουσι]{.greek-added} και [κλεπτουσιν]{.greek-omitted} [κλεπτουσι]{.greek-added}[6:19]{.aside}

θησαυριζετε δε υμιν θησαυρους εν [ουρανω]{.greek-abbr} οπου ουτε σης ουτε βρωσις αφανιζει και οπου κλεπται ου διορυσσουσιν ουδε κλεπτουσιν[6:20]{.aside}

οπου γαρ εστιν ο θησαυρος υμων εκει εσται και η καρδια υμων[6:21]{.aside}

ο λυχνος του σωματος εστιν ο οφθαλμος εαν ουν ο οφθαλμος σου απλους η ολον το σωμα σου φωτεινον εσται[6:22]{.aside}

εαν δε ο οφθαλμος σου πονηρος η ολον το σωμα σου σκοτεινον εσται ει ουν το φως το εν σοι σκοτος [εστιν]{.greek-omitted} [εστι]{.greek-added} το σκοτος ποσον[6:23]{.aside}

ουδεις [δυ]{.greek-added} [δυναται]{.greek-omitted} [ναται]{.greek-added} [δυσιν]{.greek-omitted} [δυσι]{.greek-added} κυριοις δουλευειν η γαρ τον ενα μισησει και τον ετερον αγαπησει η ενος ανθεξεται και του ετερου καταφρονησει ου [δυνασθε]{.greek-omitted} [δυνασθαι]{.greek-added} [θεω]{.greek-abbr} δουλευ[ει]{.greek-supplied}ν και μαμωνα[6:24]{.aside}

δια τουτο λεγω υμιν μη μεριμνατε τη ψυχη υμων τι [φαγητε]{.greek-omitted} [φαγετε]{.greek-added} και τι [πιητε]{.greek-omitted} [πιετε]{.greek-added} μηδε τω σωματι υμων τι ενδυσησθε ουχι η ψυχη πλειον [εστιν]{.greek-omitted} [εστι]{.greek-added} της τροφης και το σωμα του ενδυματος[6:25]{.aside}

εμβλεψατε εις τα πετεινα του [ουρανου]{.greek-abbr} οτι ου σπειρουσιν ουδε θεριζουσιν ουδε συναγουσιν εις αποθηκας και ο [πατηρ]{.greek-abbr} [ημων]{.greek-added} [υμων]{.corr} ο [ουρανιος]{.greek-abbr} τρεφει αυτα ουχ υμεις μαλλον διαφερετε αυτων[6:26]{.aside}

τις δε εξ υμων μεριμνων δυναται [προσθειναι]{.greek-omitted} [προσθηναι]{.greek-added} επι την ηλικιαν αυτου πηχυν ενα[6:27]{.aside}

και περι ενδυματος τι μεριμνατε καταμαθετε τα κρινα του αγρου πως αυξανει ου κοπια ουδε νηθει[6:28]{.aside}

λεγω δε υμιν οτι ουδε σολομων εν παση τη δοξη αυτου περιεβαλετο ως εν τουτων[6:29]{.aside}

ει δε τον χορτον του αγρου σημερον οντα και αυριον εις κλιβανον βαλλομενον ο [θεος]{.greek-abbr} ουτως αμφιεννυσιν ου πολλω μαλλον υμας ολιγοπιστοι[6:30]{.aside}

μη ουν μεριμνησητε λεγοντες τι φαγωμεν η τι πιωμεν η τι [περιβαλωμεθα]{.greek-omitted} [περιβαλομεθα]{.greek-added}[6:31]{.aside}

παντα γαρ ταυτα τα εθνη επιζητει οιδεν γαρ ο [πατηρ]{.greek-abbr} υμων ο [ουρανιος]{.greek-abbr} οτι χρηζετε τουτων απαντων[6:32]{.aside}

ζητειτε δε πρωτον την βασιλειαν του [θεου]{.greek-abbr} και την δικαιοσυνην αυτου και ταυτα παντα προστεθησεται υμιν[6:33]{.aside}

μη ουν μεριμνησητε εις την αυριον η γαρ αυριον [μεριμνησει]{.greek-omitted} [μεριμνηση]{.greek-added} τα εαυτης αρκετον τη ημερα η κακια αυτης[6:34]{.aside}

### Chapter 7

μη κρινετε ινα μη κριθητε[7:1]{.aside}

εν ω γαρ κριματι κρινετε [κριθησεσθε]{.greek-omitted} [κριθησεσθαι]{.greek-added} και εν ω μετρω μετρειτε μετρηθησεται υμιν[7:2]{.aside}

τι δε βλεπεις το καρφος το εν τω οφθαλμω [του]{.greek-omitted} [αδελφου]{.greek-omitted} [σου]{.greek-omitted} [την]{.greek-omitted} [δε]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [σω]{.greek-omitted} [οφθαλμω]{.greek-omitted} δοκον ου κατανοεις[7:3]{.aside}

η πως ερεις τω αδελφω σου αφες εκβαλω το καρφος απο του οφθαλμου σου και ιδου η δοκος εν τω οφθαλμω σου[7:4]{.aside}

υποκριτα εκβαλε πρωτον την δοκον εκ του οφθαλμου σου και τοτε διαβλεψεις εκβαλειν το καρφος εκ του οφθαλμου του αδελφου σου[7:5]{.aside}

μη δωτε το αγιον τοις [κυσιν]{.greek-omitted} [κυσι]{.greek-added} μηδε βαλητε τους μαργαριτας υμων εμπροσθεν των χοιρων μηποτε [καταπατησωσιν]{.greek-omitted} [καταπατησουσιν]{.greek-added} αυτους εν τοις ποσιν αυτων και στραφεντες [ρηξωσιν]{.greek-omitted} [ρηξουσιν]{.greek-added} υμας[7:6]{.aside}

αιτειτε και δοθησεται υμιν ζητειτε και [ευρησετε]{.greek-omitted} [ευρησεται]{.greek-added} κρουετε και ανοιγησεται υμιν[7:7]{.aside}

πας γαρ ο αιτων λαμβανει και ο ζητων ευρισκει και τω κρουοντι ανοιγησεται[7:8]{.aside}

η τις εστιν εξ υμων [ανθρωπος]{.greek-abbr} ον εαν αιτηση ο υιος αυτου αρτον μη λιθον επιδωσει αυτω[7:9]{.aside}

και εαν ιχθυν αιτηση μη οφιν επιδωσει αυτω[7:10]{.aside}

ει ουν υμεις πονηροι οντες οιδατε δοματα αγαθα διδοναι τοις τεκνοις υμων ποσω μαλλον ο [πατηρ]{.greek-abbr} υμων ο εν τοις [ουρανοις]{.greek-abbr} δωσει αγαθα τοις αιτουσιν αυτον[7:11]{.aside}

παντα ουν οσα [αν]{.greek-omitted} [θελητε]{.greek-omitted} [θελειτε]{.greek-added} ινα ποιωσιν υμιν οι [ανθρωποι]{.greek-abbr} ουτως και υμεις ποιειτε αυτοις ουτος γαρ εστιν ο νομος και οι προφηται[7:12]{.aside}

[εισελθετε]{.greek-omitted} [εισελθητε]{.greek-added} δια της στενης πυλης οτι πλατεια η πυλη και ευρυχωρος η οδος η απαγουσα εις την απωλειαν και πολλοι εισιν οι εισερχομενοι δι αυτης[7:13]{.aside}

τι στενη η πυλη και τεθλιμμενη η οδος η απαγουσα εις την ζωην και ολιγοι εισιν οι ευρισκοντες αυτην[7:14]{.aside}

προσεχετε δε απο των ψευδοπροφητων οιτινες ερχονται προς υμας εν [ενδυμασιν]{.greek-omitted} [ενδυμασι]{.greek-added} προβατων εσωθεν δε εισιν λυκοι αρπαγες[7:15]{.aside}

απο των καρπων αυτων επιγνωσεσθε αυτους μητι συλλεγουσιν απο ακανθων σταφυλην η απο τριβολων συκα[7:16]{.aside}

[ουτως]{.greek-omitted} [ουτος]{.greek-added} παν δενδρον αγαθον καρπους καλους ποιει το δε σαπρον δενδρον καρπους πονηρους ποιει[7:17]{.aside}

ου δυναται δενδρον αγαθον καρπους πονηρους ποιειν ουδε δενδρον σαπρον καρπους καλους ποιειν[7:18]{.aside}

παν δενδρον μη ποιουν καρπον καλον εκκοπτεται και εις πυρ βαλλεται[7:19]{.aside}

αρα γε απο των καρπων αυτων επιγνωσεσθε αυτους[7:20]{.aside}

ου πας ο λεγων μοι [κυριε]{.greek-abbr} [κυριε]{.greek-abbr} εισελευσεται εις την βασιλειαν των [ουρανων]{.greek-abbr} αλλ ο ποιων το θελημα του [πατρος]{.greek-abbr} μου του εν [ουρανοις]{.greek-abbr}[7:21]{.aside}

πολλοι [ερουσιν]{.greek-omitted} [ερουσι]{.greek-added} μοι εν εκεινη τη ημερα [κυριε]{.greek-abbr} [κυριε]{.greek-abbr} ου τω σω ονοματι προεφητευσαμεν και τω σω ονοματι δαιμονια εξεβαλομεν και τω σω ονοματι δυναμεις πολλας εποιησαμεν[7:22]{.aside}

και τοτε [ομολογησω]{.greek-omitted} [ωμολογησω]{.greek-added} αυτοις οτι ουδεποτε εγνων υμας αποχωρειτε απ εμου οι εργαζομενοι την ανομιαν[7:23]{.aside}

[πας]{.greek-omitted} [ουν]{.greek-omitted} οστις ακουει μου τους λογους τουτους και ποιει αυτους ομοιωσω αυτον ανδρι φρονιμω οστις [ωκοδομησεν]{.greek-omitted} [ωκοδομησε]{.greek-added} την οικιαν αυτου επι την πετραν[7:24]{.aside}

και κατεβη η βροχη και ηλθον οι ποταμοι και επνευσαν οι ανεμοι και [προσεπεσον]{.greek-omitted} [προσεπεσαν]{.greek-added} τη οικια εκεινη και ουκ [επεσεν]{.greek-omitted} [επεσε]{.greek-added} τεθεμελιωτο γαρ επι την πετραν[7:25]{.aside}

και πας ο ακουων μου τους λογους τουτους και μη ποιων αυτους ομοιωθησεται ανδρι μωρω οστις [ωκοδομησεν]{.greek-omitted} [ωκοδομησε]{.greek-added} την οικιαν αυτου επι την αμμον[7:26]{.aside}

και κατεβη η βροχη και ηλθον οι ποταμοι και επνευσαν οι ανεμοι και προσεκοψαν τη οικια εκεινη και [επεσεν]{.greek-omitted} [επεσε]{.greek-added} και ην η πτωσις αυτης μεγαλη[7:27]{.aside}

και εγενετο οτε συνετελεσεν ο [ιησους]{.greek-abbr} τους λογους τουτους εξεπλησσοντο οι οχλοι επι τη διδαχη αυτου[7:28]{.aside}

ην γαρ διδασκων αυτους ως εξουσιαν εχων και ουχ ως οι γραμματεις [αυτων]{.greek-added}[7:29]{.aside}

### Chapter 8

καταβαντι δε αυτω απο του ορους ηκολουθησαν αυτω οχλοι πολλοι[8:1]{.aside}

και ιδου [προσελθων]{.greek-added} λεπρος [ελθων]{.greek-omitted} προσεκυνει αυτω λεγων [κυριε]{.greek-abbr} εαν θελης δυνασαι με καθαρισαι[8:2]{.aside}

και εκτεινας την χειρα ηψατο αυτου ο [ιησους]{.greek-abbr} λεγων θελω καθαρισθητι και ευθεως εκαθαρισθη αυτου η λεπρα[8:3]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} ορα μηδενι ειπης αλλα υπαγε σεαυτον δειξον τω ιερει και προσενεγκε το δωρον ο [προσεταξεν]{.greek-omitted} [προσεταξε]{.greek-added} μωσης εις μαρτυριον αυτοις[8:4]{.aside}

εισελθοντι δε αυτω εις καπερναουμ προσηλθεν αυτω [εκατονταρχος]{.greek-omitted} [εκατονταρχης]{.greek-added} παρακαλων αυτον[8:5]{.aside}

και λεγων [κυριε]{.greek-abbr} ο παις μου [βεβληται]{.greek-omitted} [βεβλητε]{.greek-added} εν τη οικια [παραλυτικος]{.greek-omitted} δεινως βασανιζομενος [παραλυτικος]{.greek-added}[8:6]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} εγω ελθων θεραπευσω αυτον[8:7]{.aside}

και αποκριθεις ο εκατονταρχος εφη [κυριε]{.greek-abbr} ουκ ειμι ικανος ινα μου υπο την στεγην εισελθης αλλα μονον ειπε λογω και ιαθησεται ο παις μου[8:8]{.aside}

και γαρ εγω [ανθρωπος]{.greek-abbr} ειμι υπο εξουσιαν εχων υπ εμαυτον στρατιωτας και λεγω τουτω πορευθητι και πορευεται και αλλω ερχου και ερχεται και τω δουλω μου ποιησον τουτο και ποιει[8:9]{.aside}

ακουσας δε ο [ιησους]{.greek-abbr} [εθαυμασεν]{.greek-omitted} [εθαυμασε]{.greek-added} και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τοις ακολουθουσιν αμην λεγω υμιν ουδε εν τω [ισραηλ]{.greek-abbr} τοσαυτην πιστιν ευρον[8:10]{.aside}

λεγω δε υμιν οτι πολλοι απο ανατολων και δυσμων [ηξουσιν]{.greek-omitted} [ηξουσι]{.greek-added} και [ανακλιθησονται]{.greek-omitted} [ανακληθησονται]{.greek-added} μετα αβρααμ και ισαακ και ιακωβ εν τη βασιλεια των [ουρανων]{.greek-abbr}[8:11]{.aside}

οι δε υιοι της βασιλειας εκβληθησονται εις το σκοτος το εξωτερον εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[8:12]{.aside}

και ειπεν ο [ιησους]{.greek-abbr} τω εκατονταρχη υπαγε και ως επιστευσας γενηθητω σοι και ιαθη ο παις αυτου εν τη ωρα εκεινη[8:13]{.aside}

και ελθων ο [ιησους]{.greek-abbr} εις την οικιαν πετρου ειδεν την πενθεραν αυτου βεβλημενην και πυρεσσουσαν[8:14]{.aside}

και ηψατο της χειρος αυτης και αφηκεν αυτην ο πυρετος και [ηγερθη]{.greek-omitted} [ηγερ]{.greek-added} [θη]{.greek-added} και διηκονει αυτω[8:15]{.aside}

οψιας δε γενομενης προσηνεγκαν αυτω δαιμονιζομενους πολλους και [εξεβαλεν]{.greek-omitted} [εξεβαλε]{.greek-added} τα [πνευματα]{.greek-abbr} λογω και παντας τους κακως εχοντας εθεραπευσεν[8:16]{.aside}

οπως πληρωθη το ρηθεν δια ησαιου του προφητου λεγοντος αυτος τας ασθενειας ημων [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added} και τας [νοσους]{.greek-omitted} [νοσσους]{.greek-added} εβαστασεν[8:17]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} πολλους οχλους περι αυτον εκελευσεν απελθειν εις το περαν[8:18]{.aside}

και προσελθων εις γραμματευς ειπεν αυτω διδασκαλε ακολουθησω σοι οπου εαν απερχη[8:19]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} αι αλωπεκες φωλεους [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} και τα πετεινα του [ουρανου]{.greek-abbr} κατασκηνωσεις ο δε υιος του [ανθρωπου]{.greek-abbr} ουκ εχει που την κεφαλην [κλινη]{.greek-omitted} [κλιναι]{.greek-added}[8:20]{.aside}

ετερος δε των μαθητων αυτου ειπεν αυτω [κυριε]{.greek-abbr} επιτρεψον μοι πρωτον απελθειν και θαψαι τον [πατερα]{.greek-abbr} μου[8:21]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω ακολουθει μοι και αφες τους νεκρους θαψαι τους εαυτων νεκρους[8:22]{.aside}

και εμβαντι αυτω εις το πλοιον ηκολουθησαν αυτω οι μαθηται αυτου[8:23]{.aside}

και ιδου σεισμος μεγας εγενετο εν τη θαλασση ωστε το πλοιον καλυπτεσθαι υπο των κυματων [ην]{.greek-added} [γαρ]{.greek-added} [και]{.greek-added} [ο]{.greek-added} [ανεμος]{.greek-added} [εναντιος]{.greek-added} [αυτοις]{.greek-added} αυτος δε εκαθευδεν[8:24]{.aside}

και προσελθοντες οι μαθηται [αυτου]{.greek-added} ηγειραν αυτον λεγοντες [κυριε]{.greek-abbr} σωσον ημας απολλυμεθα[8:25]{.aside}

και λεγει αυτοις τι δειλοι εστε ολιγοπιστοι τοτε εγερθεις [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τοις ανεμοις και τη θαλασση και εγενετο γαληνη μεγαλη[8:26]{.aside}

οι δε [ανθρωποι]{.greek-abbr} εθαυμασαν λεγοντες ποταπος εστιν ουτος οτι και οι ανεμοι και η θαλασσα υπακουουσιν αυτω[8:27]{.aside}

και ελθον[τ]{.greek-supplied}ι αυτω εις το περαν εις την χωραν των γεργεσηνων υπηντησαν αυτω δυο δαιμονιζομενοι εκ των μνημειων εξερχομενοι χαλεποι λιαν ωστε μη [ισχυειν]{.greek-omitted} [ισχυν]{.greek-added} τινα παρελθειν δια της οδου εκεινης[8:28]{.aside}

και ιδου εκραξαν λεγοντες τι [ημιν]{.greek-omitted} [υμιν]{.greek-added} και [σοι]{.greek-omitted} [συ]{.greek-added} [ιησου]{.greek-abbr} υιε του [θεου]{.greek-abbr} ηλθες [ωδε]{.greek-omitted} προ καιρου βασανισαι ημας[8:29]{.aside}

ην δε μακραν απ αυτων αγελη χοιρων [π]{.greek-supplied}ολλων βοσκομενη[8:30]{.aside}

οι δε δαιμονες παρεκαλουν αυτον λεγοντες ει εκβαλλεις ημας [επιτρεψον]{.greek-omitted} [επιτρεψων]{.greek-added} ημιν απελθειν εις την αγελην των χοιρων[8:31]{.aside}

και ειπεν αυτοις υπαγετε οι δε εξελθοντες απηλθον εις την αγελην των χοιρων και ιδου ωρμησεν πασα η αγελη [των]{.greek-omitted} [χοιρων]{.greek-omitted} κατα του κρημνου εις την θαλασσαν και απεθανον εν τοις υδασιν[8:32]{.aside}

οι δε βοσκοντες εφυγον και απελθοντες εις την πολιν απηγγειλαν παντα και τα των δαιμονιζομενων[8:33]{.aside}

και ιδου πασα η πολις εξηλθεν εις συναντησιν τω [ιησου]{.greek-abbr} και ιδοντες αυτον παρεκαλεσαν οπως μεταβη απο των οριων αυτων[8:34]{.aside}

### Chapter 9

και εμβας εις [το]{.greek-omitted} πλοιον [διεπερασεν]{.greek-omitted} [διεπερασε]{.greek-added} και ηλθεν εις την ιδιαν πολιν[9:1]{.aside}

και ιδου προσεφερον αυτω παραλυτικον επι κλινης βεβλημενον και ιδων ο [ιησους]{.greek-abbr} την πιστιν αυτων ειπεν τω παραλυτικω θαρσει τεκνον αφεωνται [σοι]{.greek-omitted} [σου]{.greek-added} αι αμαρτιαι [σου]{.greek-omitted}[9:2]{.aside}

και ιδου τινες των [γραμματαιων]{.greek-added} [γραμματεων]{.corr} ειπον εν εαυτοις ουτος βλασφημει[9:3]{.aside}

και [ιδων]{.greek-omitted} [ειδως]{.greek-added} ο [ιησους]{.greek-abbr} τας ενθυμησεις αυτων ειπεν [ινα]{.greek-omitted} [ινατι]{.greek-added} [τι]{.greek-omitted} [υμεις]{.greek-omitted} ενθυμεισθε πονηρα εν ταις καρδιαις υμων[9:4]{.aside}

τι γαρ εστιν [ευκοπωτερον]{.greek-omitted} [ευκοποτερον]{.greek-added} ειπειν αφεωνται σου αι αμαρτιαι η ειπειν [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} και περιπατει[9:5]{.aside}

ινα δε [ειδητε]{.greek-omitted} [ηδειτε]{.greek-added} οτι εξουσιαν εχει ο υιος του [ανθρωπου]{.greek-abbr} επι της γης αφιεναι αμαρτιας τοτε λεγει τω παραλυτικω εγερθεις αρον σου την κλινην και υπαγε εις τον οικον σου[9:6]{.aside}

και εγερθεις απηλθεν εις τον οικον αυτου[9:7]{.aside}

ιδοντες δε οι οχλοι εθαυμασαν και εδοξασαν τον [θεον]{.greek-abbr} τον δοντα εξουσιαν τοιαυτην τοις [ανθρωποις]{.greek-abbr}[9:8]{.aside}

και παραγων ο [ιησους]{.greek-abbr} εκειθεν ειδεν [ανθρωπον]{.greek-abbr} καθημενον επι το τελωνιον ματθαιον λεγομενον και λεγει αυτω ακολουθει μοι και αναστας [ηκολουθησεν]{.greek-omitted} [ηκολουθει]{.greek-added} αυτω[9:9]{.aside}

και εγενετο αυτου ανακειμενου εν τη οικια και ιδου πολλοι τελωναι και αμαρτωλοι ελθοντες συνανεκειντο τω [ιησου]{.greek-abbr} και τοις μαθηταις αυτου[9:10]{.aside}

και ιδοντες οι φαρισαιοι [ειπον]{.greek-omitted} [ελεγον]{.greek-added} τοις μαθηταις αυτου δια τι μετα των τελωνων και αμαρτωλων [εσθιει]{.greek-omitted} ο διδασκαλος υμων [εσθιει]{.greek-added}[9:11]{.aside}

ο δε [ιησους]{.greek-abbr} ακουσας ειπεν αυτοις ου χρειαν εχουσιν οι ισχυοντες ιατρου αλλ οι κακως εχοντες[9:12]{.aside}

πορευθεντες δε μαθετε τι εστιν ελεον θελω και ου θυσιαν ου γαρ ηλθον καλεσαι δικαιους αλλα αμαρτωλους [εις]{.greek-omitted} [μετανοιαν]{.greek-omitted}[9:13]{.aside}

τοτε προσερχονται αυτω οι μαθηται ιωαννου λεγοντες δια τι ημεις και οι φαρισαιοι νηστευομεν πολλα οι δε μαθηται σου ου νηστευουσιν[9:14]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} μη δυνανται οι υιοι του νυμφωνος πενθειν εφ οσον μετ αυτων εστιν ο νυμφιος ελευσονται δε ημεραι οταν απαρθη απ αυτων ο νυμφιος και τοτε νηστευσουσιν[9:15]{.aside}

ουδεις δε επιβαλλει επιβλημα ρακους αγναφου επι ιματιω παλαιω αιρει γαρ το πληρωμα αυτου απο του ιματιου και χειρον σχισμα γινεται[9:16]{.aside}

ουδε βαλλουσιν οινον νεον εις ασκους παλαιους ει δε [μηγε]{.greek-omitted} [μη]{.greek-added} [γε]{.greek-added} ρηγνυνται οι ασκοι και ο οινος [εκχειται]{.greek-omitted} [εκχυται]{.greek-added} και οι ασκοι απολουνται [αλλα]{.greek-omitted} [αλλ]{.greek-added} [βαλλουσιν]{.greek-omitted} οινον νεον εις ασκους καινους [βλητεον]{.greek-added} και αμφοτεροι συντηρουνται[9:17]{.aside}

ταυτα αυτου λαλουντος αυτοις ιδου [αρχων]{.greek-omitted} [αρχον]{.greek-added} [εις]{.greek-omitted} [τις]{.greek-added} ελθων προσεκυνει αυτω λεγων οτι η θυγατηρ μου αρτι ετελευτησεν αλλα ελθων επιθες την χειρα σου επ αυτην και ζησεται[9:18]{.aside}

και εγερθεις ο [ιησους]{.greek-abbr} [ηκολουθησεν]{.greek-omitted} [ηκολουθει]{.greek-added} αυτω και οι μαθηται αυτου[9:19]{.aside}

και ιδου γυνη αιμορροουσα δωδεκα ετη προσελθουσα οπισθεν ηψατο του κρασπεδου του ιματιου αυτου[9:20]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ εν εαυτη εαν μονον αψωμαι του ιματιου αυτου σωθησομαι[9:21]{.aside}

ο δε [ιησους]{.greek-abbr} [επιστραφεις]{.greek-omitted} [στραφεις]{.greek-added} και ιδων αυτην ειπεν θαρσει θυγατερ η πιστις σου [σεσωκεν]{.greek-omitted} [σεσωκε]{.greek-added} σε και εσωθη η γυνη απο της ωρας εκεινης[9:22]{.aside}

και ελθων ο [ιησους]{.greek-abbr} εις την οικιαν του αρχοντος και ιδων τους αυλητας και τον οχλον θορυβουμενον[9:23]{.aside}

[ελεγεν]{.greek-added} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} αναχωρειτε ου γαρ απεθανεν το κορασιον αλλα καθευδει και κατεγελων αυτου[9:24]{.aside}

οτε δε εξεβληθη ο οχλος εισελθων [εκρατησεν]{.greek-omitted} [εκρατησε]{.greek-added} της χειρος αυτης και ηγερθη το κορασιον[9:25]{.aside}

και εξηλθεν η φημη [αυτη]{.greek-omitted} [αὕτη]{.greek-added} εις ολην την γην εκεινην[9:26]{.aside}

και [παραγοντι]{.greek-omitted} [παραγωντι]{.greek-added} εκειθεν τω [ιησου]{.greek-abbr} ηκολουθησαν αυτω δυο τυφλοι κραζοντες και λεγοντες ελεησον ημας υιε [δαυιδ]{.greek-abbr}[9:27]{.aside}

ελθοντι δε [αυτω]{.greek-added} εις την οικιαν [προσηλθον]{.greek-omitted} [προσηλ]{.greek-added} [θον]{.greek-added} αυτω οι τυφλοι και λεγει αυτοις ο [ιησους]{.greek-abbr} πιστευετε οτι δυναμαι τουτο ποιησαι λεγουσιν αυτω ναι [κυριε]{.greek-abbr}[9:28]{.aside}

τοτε ηψατο των οφθαλμων αυτων λεγων κατα την πιστιν υμων γενηθητω υμιν[9:29]{.aside}

και ανεωχθησαν αυτων οι οφθαλμοι και ενεβριμησατο αυτοις ο [ιησους]{.greek-abbr} λεγων ορατε μηδεις γινωσκετω[9:30]{.aside}

οι δε εξελθοντες [διεφημισαν]{.greek-omitted} [διεφημησαν]{.greek-added} αυτον εν ολη τη γη εκεινη[9:31]{.aside}

αυτων δε εξερχομενων ιδου προσηνεγκαν αυτω [ανθρωπον]{.greek-abbr} κωφον δαιμονιζομενον[9:32]{.aside}

και εκβληθεντος του δαιμονιου ελαλησεν ο κωφος και εθαυμασαν οι οχλοι λεγοντες [ουδεποτε]{.greek-omitted} [ουδεπωτε]{.greek-added} εφανη ουτως εν τω [ισραηλ]{.greek-abbr}[9:33]{.aside}

οι δε φαρισαιοι ελεγον εν τω αρχοντι των δαιμονιων εκβαλλει τα δαιμονια[9:34]{.aside}

και περιηγεν ο [ιησους]{.greek-abbr} τας πολεις πασας και τας κωμας διδασκων εν ταις συναγωγαις αυτων και κηρυσσων το ευαγγελιον της βασιλειας και θεραπευων πασαν νοσον και πασαν μαλακιαν [εν]{.greek-omitted} [τω]{.greek-omitted} [λαω]{.greek-omitted}[9:35]{.aside}

ιδων δε τους οχλους εσπλαγχνισθη περι αυτων οτι ησαν εσκυλμενοι και ερριμμενοι [ωσει]{.greek-omitted} [ως]{.greek-added} προβατα μη εχοντα ποιμενα[9:36]{.aside}

τοτε λεγει τοις μαθηταις αυτου ο μεν θερισμος πολυς οι δε εργαται ολιγοι[9:37]{.aside}

δεηθητε ουν του [κυριου]{.greek-abbr} του θερισμου οπως [εκβαλη]{.greek-omitted} [εκβαλλη]{.greek-added} εργατας εις τον θερισμον αυτου[9:38]{.aside}

### Chapter 10

και προσκαλεσαμενος τους δωδεκα μαθητας αυτου εδωκεν αυτοις εξουσιαν [πνευματων]{.greek-abbr} ακαθαρτων ωστε [αυτα]{.greek-added} εκβαλλειν [αυτα]{.greek-omitted} και θεραπευειν πασαν νοσον και πασαν μαλακιαν[10:1]{.aside}

των δε δωδεκα αποστολων τα ονοματα εστιν ταυτα πρωτος σιμων ο λεγομενος πετρος και ανδρεας ο αδελφος αυτου [ο]{.greek-added} ιακωβος ο του ζεβεδαιου και ιωαννης ο αδελφος αυτου[10:2]{.aside}

φιλιππος και βαρθολομαιος θωμας και ματθαιος ο τελωνης ιακωβος ο του αλφαιου και λεββαιος ο επικληθεις θαδδαιος[10:3]{.aside}

σιμων ο κανανιτης και ιουδας [ο]{.greek-added} ισκαριωτης ο και παραδους αυτον[10:4]{.aside}

τουτους τους δωδεκα απεστειλεν ο [ιησους]{.greek-abbr} παραγγειλας αυτοις λεγων εις οδον εθνων μη απελθητε και εις πολιν σαμαρειτων μη εισελθητε[10:5]{.aside}

[πορευεσθε]{.greek-omitted} [πορευεσθαι]{.greek-added} δε μαλλον προς τα προβατα τα απολωλοτα οικου [ισραηλ]{.greek-abbr}[10:6]{.aside}

πορευομενοι δε [κηρυσσετε]{.greek-omitted} [κηρυσσεται]{.greek-added} λεγοντες [οτι]{.greek-omitted} [μετανοειτε]{.greek-added} [ηγγικεν]{.greek-omitted} [ηγγικε]{.greek-added} [γαρ]{.greek-added} η βασιλεια των [ουρανων]{.greek-abbr}[10:7]{.aside}

ασθενουντας θεραπευετε λεπρους καθαριζετε δαιμονια εκβαλλετε δωρεαν ελαβετε δωρεαν [δοτε]{.greek-omitted} [δωτε]{.greek-added}[10:8]{.aside}

μη κτησησθε χρυσον μηδε αργυρον μηδε χαλκον εις τας ζωνας υμων[10:9]{.aside}

μη πηραν εις οδον [μηδε]{.greek-omitted} [μη]{.greek-added} δυο χιτωνας μηδε υποδηματα μηδε [ραβδους]{.greek-omitted} [ραβδον]{.greek-added} αξιος γαρ ο εργατης της τροφης αυτου εστιν[10:10]{.aside}

εις ην δ αν πολιν η κωμην εισελθητε [εξετασατε]{.greek-omitted} [εξετασετε]{.greek-added} τις [αξιος]{.greek-added} [εστιν]{.greek-added} εν αυτη [αξιος]{.greek-omitted} [εστιν]{.greek-omitted} κακει μεινατε εως αν εξελθητε[10:11]{.aside}

εισερχομενοι δε εις την οικιαν ασπασασθε αυτην [λεγοντες]{.greek-added} [ειρηνη]{.greek-added} [τω]{.greek-added} [οικω]{.greek-added} [τουτω]{.greek-added}[10:12]{.aside}

και εαν μεν η η οικια αξια [ελθετω]{.greek-omitted} [ελθατω]{.greek-added} η ειρηνη υμων επ αυτην εαν δε μη η αξια η ειρηνη υμων [προς]{.greek-omitted} [εφ]{.greek-added} υμας επιστραφητω[10:13]{.aside}

και ος εαν μη δεξηται υμας μηδε ακουση τους λογους υμων εξερχομενοι [εξω]{.greek-added} της οικιας η της πολεως εκεινης εκτιναξατε τον κονιορτον [εκ]{.greek-added} των ποδων υμων[10:14]{.aside}

αμην λεγω υμιν [ανεκτοτερον]{.greek-omitted} [ανεκτωτερον]{.greek-added} εσται γη σοδομων και γομορρων εν ημερα κρισεως η τη πολει εκεινη[10:15]{.aside}

ιδου εγω αποστελλω υμας ως προβατα εν μεσω λυκων [γινεσθε]{.greek-omitted} [γινεσθαι]{.greek-added} ουν φρονιμοι ως οι οφεις και ακεραιοι ως αι περιστεραι[10:16]{.aside}

προσεχετε δε απο των [ανθρωπων]{.greek-abbr} [παραδωσουσιν]{.greek-omitted} [παραδωσουσι]{.greek-added} γαρ υμας εις συνεδρια και εν ταις συναγωγαις αυτων μαστιγωσουσιν υμας[10:17]{.aside}

και επι ηγεμονας δε και βασιλεις αχθησεσθε ενεκεν εμου εις μαρτυριον αυτοις και τοις εθνεσιν[10:18]{.aside}

οταν δε [παραδιδωσιν]{.greek-omitted} [παραδωσουσιν]{.greek-added} υμας μη [μεριμνησητε]{.greek-omitted} [μεριμναται]{.greek-added} πως η τι [λαλησητε]{.greek-omitted} [απολογησησθε]{.greek-added} δοθησεται γαρ υμιν εν εκεινη τη ωρα τι [λαλησετε]{.greek-omitted} [λαλησητε]{.greek-added}[10:19]{.aside}

ου γαρ υμεις εστε οι λαλουντες αλλα το [πνευμα]{.greek-abbr} του [πατρος]{.greek-abbr} υμων το λαλουν εν υμιν[10:20]{.aside}

παραδωσει δε αδελφος αδελφον εις θανατον και [πατηρ]{.greek-abbr} τεκνον και επαναστησονται τεκνα επι γονεις και θανατωσουσιν αυτους[10:21]{.aside}

και εσεσθε μισουμενοι υπο παντων δια το ονομα μου ο δε υπομεινας εις τελος ουτος σωθησεται[10:22]{.aside}

οταν δε διωκωσιν υμας εν τη πολει ταυτη φευγετε εις την αλλην αμην γαρ λεγω υμιν ου μη τελεσητε τας πολεις του [ισραηλ]{.greek-abbr} εως αν ελθη ο υιος του [ανθρωπου]{.greek-abbr}[10:23]{.aside}

ουκ εστιν μαθητης υπερ τον διδασκαλον [αυτου]{.greek-added} ουδε δουλος υπερ τον κυριον αυτου[10:24]{.aside}

αρκετον τω μαθητη ινα γενηται ως ο διδασκαλος αυτου και ο δουλος ως ο κυριος αυτου ει τον οικοδεσποτην βεελζεβουλ [εκαλεσαν]{.greek-omitted} [επεκαλεσαντο]{.greek-added} ποσω μαλλον τους [οικειακους]{.greek-omitted} [οικιακους]{.greek-added} αυτου[10:25]{.aside}

μη ουν [φοβηθητε]{.greek-omitted} [φοβηθειτε]{.greek-added} αυτους ουδεν γαρ εστιν κεκαλυμμενον ο ουκ αποκαλυφθησεται και κρυπτον ο ου γνωσθησεται[10:26]{.aside}

ο λεγω υμιν εν τη σκοτια ειπατε εν τω φωτι και ο εις το ους ακουετε κηρυξατε επι των [δωματων]{.greek-omitted} [δοματων]{.greek-added}[10:27]{.aside}

και μη φοβεισθε απο των αποκτενοντων το σωμα την δε ψυχην μη δυναμενων αποκτειναι φοβηθητε δε [δε]{.greek-added} μαλλον τον δυναμενον και την ψυχην και το σωμα απολεσαι εν γεεννη[10:28]{.aside}

ουχι δυο στρουθια ασσαριου πωλειται και εν εξ αυτων ου πεσειται [επι]{.greek-omitted} [εις]{.greek-added} την γην ανευ του [πατρος]{.greek-abbr} υμων [του]{.greek-added} [εν]{.greek-added} [τοις]{.greek-added} [[ουρανοις]{.greek-abbr}]{.greek-added}[10:29]{.aside}

υμων δε και αι τριχες της κεφαλης πασαι ηριθμημεναι εισιν[10:30]{.aside}

μη ουν [φοβηθητε]{.greek-omitted} [φοβεισθε]{.greek-added} πολλων στρουθιων διαφερετε υμεις[10:31]{.aside}

πας ουν οστις [ομολογησει]{.greek-omitted} [ομολογηση]{.greek-added} εν εμοι εμπροσθεν των [ανθρωπων]{.greek-abbr} ομολογησω καγω εν αυτω εμπροσθεν του [πατρος]{.greek-abbr} μου του εν [τοις]{.greek-added} [ουρανοις]{.greek-abbr}[10:32]{.aside}

οστις δ αν αρνησηται με εμπροσθεν των [ανθρωπων]{.greek-abbr} αρνησομαι αυτον καγω εμπροσθεν του [πατρος]{.greek-abbr} μου του εν [ουρανοις]{.greek-abbr}[10:33]{.aside}

μη [νομισητε]{.greek-omitted} [νομησητε]{.greek-added} οτι ηλθον βαλειν ειρηνην επι την γην ουκ ηλθον βαλειν ειρηνην αλλα μαχαιραν[10:34]{.aside}

ηλθον γαρ διχασαι [ανθρωπον]{.greek-abbr} κατα του [πατρος]{.greek-abbr} αυτου και θυγατερα κατα της [μητρος]{.greek-abbr} αυτης και νυμφην κατα της πενθερας αυτης[10:35]{.aside}

και [οι]{.greek-added} εχθροι του [ανθρωπου]{.greek-abbr} οι [οικειακοι]{.greek-omitted} [οικιακοι]{.greek-added} αυτου[10:36]{.aside}

ο φιλων [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} υπερ εμε ουκ εστιν μου αξιος και ο φιλων υιον η [θυγατεραν]{.greek-added} [θυγατερα]{.corr} υπερ εμε ουκ εστιν μου αξιος[10:37]{.aside}

και ος ου λαμβανει τον [σταυρον]{.greek-abbr} αυτου και ακολουθει οπισω μου ουκ εστιν μου αξιος[10:38]{.aside}

ο ευρων την ψυχην αυτου απολεσει αυτην και ο απολεσας την ψυχην αυτου ενεκεν εμου ευρησει αυτην[10:39]{.aside}

ο δεχομενος υμας εμε δεχεται και ο εμε δεχομενος δεχεται τον αποστειλαντα με[10:40]{.aside}

ο δεχομενος προφητην εις ονομα προφητου μισθον προφητου ληψεται και ο δεχομενος δικαιον εις ονομα δικαιου μισθον δικαιου ληψεται[10:41]{.aside}

και ος εαν ποτιση ενα των μικρων τουτων ποτηριον ψυχρου μονον εις ονομα μαθητου αμην λεγω υμιν ου μη απολεση τον μισθον αυτου[10:42]{.aside}

### Chapter 11

και εγενετο οτε ετελεσεν ο [ιησους]{.greek-abbr} διατασσων τοις δωδεκα μαθηταις αυτου μετεβη εκειθεν του διδασκειν και κηρυσσειν εν ταις πολεσιν αυτων[11:1]{.aside}

ο δε ιωαννης ακουσας εν τω δεσμωτηριω τα εργα του [χριστου]{.greek-omitted} [[ιησου]{.greek-abbr}]{.greek-added} πεμψας δυο των μαθητων αυτου[11:2]{.aside}

ειπεν αυτω συ ει ο ερχομενος η ετερον προσδοκωμεν[11:3]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις πορευθεντες απαγγειλατε ιωαννη α ακουετε και βλεπετε[11:4]{.aside}

τυφλοι [αναβλεπουσιν]{.greek-omitted} [αναβλεπουσι]{.greek-added} και χωλοι [περιπατουσιν]{.greek-omitted} [περιπατουσι]{.greek-added} λεπροι καθαριζονται και κωφοι [ακουουσιν]{.greek-omitted} [ακουουσι]{.greek-added} νεκροι εγειρονται και πτωχοι ευαγγελιζονται[11:5]{.aside}

και μακαριος εστιν ος εαν μη σκανδαλισθη εν εμοι[11:6]{.aside}

τουτων δε πορευομενων ηρξατο ο [ιησους]{.greek-abbr} λεγειν τοις οχλοις περι ιωαννου τι [εξηλθετε]{.greek-omitted} [εξηλθατε]{.greek-added} εις την ερημον θεασασθαι καλαμον υπο ανεμου σαλευομενον[11:7]{.aside}

αλλα τι [εξηλθετε]{.greek-omitted} [εξηλθατε]{.greek-added} ιδειν [ανθρωπον]{.greek-abbr} εν μαλακοις ιματιοις ημφιεσμενον ιδου οι τα μαλακα φορουντες εν τοις οικοις των [βασιλειων]{.greek-omitted} [βασιλεων]{.greek-added} εισιν[11:8]{.aside}

αλλα τι [εξηλθετε]{.greek-omitted} [εξηλθατε]{.greek-added} ιδειν προφητην ναι λεγω υμιν και περισσοτερον προφητου[11:9]{.aside}

ουτος γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} περι ου γεγραπται ιδου εγω αποστελλω τον αγγελον μου προ προσωπου σου ος κατασκευασει την οδον σου εμπροσθεν σου[11:10]{.aside}

αμην λεγω υμιν ουκ εγηγερται εν γεννητοις γυναικων μειζων ιωαννου του βαπτιστου ο δε μικροτερος εν τη βασιλεια των [ουρανων]{.greek-abbr} μειζων αυτου εστιν[11:11]{.aside}

απο δε των ημερων ιωαννου του βαπτιστου εως αρτι η βασιλεια των [ουρανων]{.greek-abbr} βιαζεται και βιασται αρπαζουσιν αυτην[11:12]{.aside}

παντες γαρ οι προφηται και ο νομος εως ιωαννου προεφητευσαν[11:13]{.aside}

και ει θελετε δεξασθαι αυτος εστιν ηλιας ο μελλων ερχεσθαι[11:14]{.aside}

ο εχων ωτα ακουειν ακουετω[11:15]{.aside}

τινι δε ομοιωσω την γενεαν ταυτην ομοια [εστιν]{.greek-omitted} [εστι]{.greek-added} παιδιοις εν αγοραις καθημενοις και προσφωνουσιν τοις εταιροις αυτων[11:16]{.aside}

και λεγουσιν [ηυλησαμεν]{.greek-omitted} [ηυλισαμεν]{.greek-added} υμιν και ουκ [ωρχησασθε]{.greek-omitted} [ορχησασθαι]{.greek-added} εθρηνησαμεν [υμιν]{.greek-omitted} [ημιν]{.greek-added} και ουκ [εκοψασθε]{.greek-omitted} [εκλαυσατε]{.greek-added}[11:17]{.aside}

[ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} γαρ ιωαννης μητε εσθιων μητε πινων και λεγουσιν [[λεγουσι]{.corr}]{.greek-added} δαιμονιον εχει[11:18]{.aside}

ηλθεν ο υιος του [ανθρωπου]{.greek-abbr} εσθιων και πινων και λεγουσιν ιδου [ανθρωπος]{.greek-abbr} φαγος και οινοποτης τελωνων φιλος και αμαρτωλων και εδικαιωθη η σοφια απο των τεκνων αυτης[11:19]{.aside}

τοτε ηρξατο [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} ονειδιζειν τας πολεις εν αις εγενοντο αι πλεισται δυναμεις αυτου οτι ου μετενοησαν[11:20]{.aside}

ουαι σοι [χοραζιν]{.greek-omitted} [χωραζιν]{.greek-added} ουαι σοι βηθσαιδα οτι ει εν τυρω και σιδωνι εγενοντο αι δυναμεις αι γενομεναι εν υμιν παλαι [αν]{.greek-omitted} εν σακκω και σποδω [καθημεναι]{.greek-added} μετενοησαν[11:21]{.aside}

πλην λεγω υμιν τυρω και σιδωνι [ανεκτοτερον]{.greek-omitted} [ανεκτωτερον]{.greek-added} εσται εν ημερα κρισεως η υμιν[11:22]{.aside}

και συ καπερναουμ η εως του [ουρανου]{.greek-abbr} υψωθεισα εως αδου καταβιβασθηση οτι ει εν σοδομοις [εγενοντο]{.greek-omitted} [εγενηθησαν]{.greek-added} αι δυναμεις αι γενομεναι εν σοι εμειναν αν μεχρι της σημερον[11:23]{.aside}

πλην λεγω υμιν οτι [γη]{.greek-omitted} σοδομων [και]{.greek-added} [γομορρας]{.greek-added} [ανεκτοτερον]{.greek-omitted} [ανεκτωτερον]{.greek-added} εσται εν ημερα κρισεως η σοι[11:24]{.aside}

εν εκεινω τω καιρω αποκριθεις ο [ιησους]{.greek-abbr} ειπεν εξομολογουμαι σοι [πατερ]{.greek-abbr} [κυριε]{.greek-abbr} του [ουρανου]{.greek-abbr} και της γης οτι απεκρυψας ταυτα απο σοφων και συνετων και απεκαλυψας αυτα νηπιοις[11:25]{.aside}

ναι ο [πατηρ]{.greek-abbr} οτι ουτως εγενετο ευδοκια εμπροσθεν σου[11:26]{.aside}

παντα μοι [πα]{.greek-added} [παρεδοθη]{.greek-omitted} [ρεδοθη]{.greek-added} υπο του [πατρος]{.greek-abbr} μου και ουδεις επιγινωσκει τον υιον ει μη ο [πατηρ]{.greek-abbr} ουδε τον [πατερα]{.greek-abbr} τις επιγινωσκει ει μη ο υιος και [ω]{.greek-omitted} [ο]{.greek-added} εαν βουληται ο υιος αποκαλυψαι[11:27]{.aside}

δευτε προς με παντες οι κοπιωντες και πεφορτισμενοι καγω αναπαυσω υμας[11:28]{.aside}

αρατε τον ζυγον μου εφ υμας και μαθετε απ εμου οτι πραος ειμι και ταπεινος [τη]{.corr} καρδια και ευρησετε αναπαυσιν ταις ψυχαις υμων[11:29]{.aside}

ο γαρ ζυγος μου χρηστος και το φορτιον μου ελαφρον εστιν[11:30]{.aside}

### Chapter 12

εν εκεινω τω καιρω επορευθη ο [ιησους]{.greek-abbr} τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} δια των σποριμων οι δε μαθηται αυτου επεινασαν και [ηρξαντο]{.greek-omitted} [ηρξατο]{.greek-added} τιλλειν σταχυας και εσθιειν[12:1]{.aside}

οι δε φαρισαιοι ιδοντες [ειπον]{.greek-omitted} [ειπαν]{.greek-added} αυτω ιδου οι μαθηται σου ποιουσιν ο ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} ποιειν εν σαββατω[12:2]{.aside}

ο δε ειπεν αυτοις ουκ ανεγνωτε τι [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} [δαυιδ]{.greek-abbr} οτε επεινασεν αυτος και οι μετ αυτου[12:3]{.aside}

πως εισηλθεν εις τον οικον του [θεου]{.greek-abbr} και τους αρτους της προθεσεως εφαγεν ους ουκ εξον ην αυτω φαγειν ουδε τοις μετ αυτου ει μη τοις [ιερευσιν]{.greek-omitted} [ιερευσι]{.greek-added} μονοις[12:4]{.aside}

η ουκ ανεγνωτε εν τω νομω οτι τοις σαββασιν οι ιερεις εν τω ιερω το σαββατον βεβηλουσιν και αναιτιοι [εισιν]{.greek-omitted} [εισι]{.greek-added}[12:5]{.aside}

λεγω δε υμιν οτι του ιερου [μειζον]{.greek-omitted} [μειζων]{.greek-added} εστιν ωδε[12:6]{.aside}

ει δε εγνωκειτε τι εστιν [ελεον]{.greek-omitted} [ελαιον]{.greek-added} θελω και ου θυσιαν ουκ αν κατεδικασατε τους αναιτιους[12:7]{.aside}

[κυριος]{.greek-abbr} γαρ εστιν [του]{.greek-omitted} [σαββατου]{.greek-omitted} ο υιος του [ανθρωπου]{.greek-abbr} [και]{.greek-added} [του]{.greek-added} [σαββατου]{.greek-added}[12:8]{.aside}

και μεταβας εκειθεν ηλθεν εις την συναγωγην αυτων[12:9]{.aside}

και ιδου [ην]{.greek-added} [εκει]{.greek-added} [ανθρωπος]{.greek-abbr} [ην]{.greek-omitted} την χειρα εχων ξηραν και [επηρωτησαν]{.greek-omitted} [επηρωτησεν]{.greek-added} αυτον λεγοντες ει [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} τοις σαββασιν θεραπευειν ινα [κατηγορησωσιν]{.greek-omitted} [κατηγωρησωσιν]{.greek-added} αυτου[12:10]{.aside}

ο δε ειπεν αυτοις τις εσται εξ υμων [ανθρωπος]{.greek-abbr} ος εξει προβατον εν και εαν εμπεση τουτο τοις σαββασιν εις βοθυνον ουχι κρατησει αυτο και εγερει[12:11]{.aside}

ποσω ουν διαφερει [ανθρωπος]{.greek-abbr} προβατου ωστε [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} καλως ποιειν[12:12]{.aside}

τοτε λεγει τω [ανθρωπω]{.greek-abbr} εκτεινον την χειρα σου και [εξετεινεν]{.greek-omitted} [εξετεινε]{.greek-added} και [αποκατεσταθη]{.greek-omitted} [απεκατεσταθη]{.greek-added} υγιης ως η αλλη[12:13]{.aside}

[εξελθοντες]{.greek-added} [δε]{.greek-added} οι [δε]{.greek-omitted} φαρισαιοι συμβουλιον ελαβον κατ αυτου [εξελθοντες]{.greek-omitted} οπως αυτον απολεσωσιν[12:14]{.aside}

ο δε [ιησους]{.greek-abbr} γνους ανεχωρησεν εκειθεν και ηκολουθησαν αυτω οχλοι πολλοι και εθεραπευσεν αυτους παντας[12:15]{.aside}

και επετιμησεν αυτοις ινα μη φανερον αυτον ποιησωσιν[12:16]{.aside}

[οπως]{.greek-omitted} [ινα]{.greek-added} πληρωθη το ρηθεν δια ησαιου του προφητου λεγοντος[12:17]{.aside}

ιδου ο παις μου ον ηρετισα ο αγαπητος μου εις ον ευδοκησεν η ψυχη μου θησω το [πνευμα]{.greek-abbr} μου επ αυτον και κρισιν τοις εθνεσιν απαγγελει[12:18]{.aside}

ουκ ερισει ουδε κραυγασει ουδε ακουσει τις εν ταις πλατειαις την φωνην αυτου[12:19]{.aside}

καλαμον συντετριμμενον ου κατεαξει και λινον τυφομενον ου σβεσει εως αν εκβαλη εις νικος την κρισιν[12:20]{.aside}

και τω ονοματι αυτου εθνη ελπιουσιν[12:21]{.aside}

τοτε προσηνεχθη αυτω δαιμονιζομενος τυφλος και κωφος και εθεραπευσεν αυτον ωστε τον [κωφον]{.greek-added} [και]{.greek-added} τυφλον [και]{.greek-omitted} [κωφον]{.greek-omitted} και λαλειν και βλεπειν[12:22]{.aside}

και εξισταντο παντες οι οχλοι και ελεγον μητι ουτος εστιν ο υιος [δαυιδ]{.greek-abbr}[12:23]{.aside}

οι δε φαρισαιοι ακουσαντες [ειπον]{.greek-omitted} [ειπαν]{.greek-added} ουτος ουκ εκβαλλει τα δαιμονια ει μη εν τω βεελζεβουλ αρχοντι των δαιμονιων[12:24]{.aside}

ειδως δε ο [ιησους]{.greek-abbr} τας ενθυμησεις αυτων ειπεν αυτοις πασα βασιλεια μερισθεισα καθ [εαυτης]{.greek-omitted} [εαυτην]{.greek-added} ερημουται και πασα πολις η οικια μερισθεισα καθ [εαυτης]{.greek-omitted} [εαυτην]{.greek-added} ου σταθησεται[12:25]{.aside}

και ει ο σατανας τον σαταναν εκβαλλει εφ εαυτον εμερισθη πως ουν σταθησεται η βασιλεια αυτου[12:26]{.aside}

και ει εγω εν [βελζεβουλ]{.greek-added} [βεελζεβουλ]{.corr} εκβαλλω τα δαιμονια οι υιοι υμων εν τινι εκβαλλουσιν δια τουτο αυτοι υμων εσονται κριται[12:27]{.aside}

ει δε εν [πνευματι]{.greek-abbr} [θεου]{.greek-abbr} εγω εκβαλλω τα δαιμονια αρα εφθασεν εφ υμας η βασιλεια του [θεου]{.greek-abbr}[12:28]{.aside}

η πως δυναται τις εισελθειν εις την οικιαν του ισχυρου και τα σκευη αυτου διαρπασαι εαν μη πρωτον δηση τον ισχυρον και τοτε την οικιαν αυτου [διαρπασει]{.greek-omitted} [διαρπαση]{.greek-added}[12:29]{.aside}

ο μη ων μετ εμου κατ εμου [εστιν]{.greek-omitted} [εστι]{.greek-added} και ο μη συναγων μετ εμου σκορπιζει[12:30]{.aside}

δια τουτο λεγω υμιν πασα αμαρτια και βλασφημια [α]{.greek-added} [αφεθησεται]{.greek-omitted} [φεθησεται]{.greek-added} τοις [ανθρωποις]{.greek-abbr} η δε του [πνευματος]{.greek-abbr} βλασφημια ουκ αφεθησεται τοις [ανθρωποις]{.greek-abbr}[12:31]{.aside}

και ος εαν ειπη λογον κατα του υιου του [ανθρωπου]{.greek-abbr} αφεθησεται αυτω ος δ αν ειπη κατα του [πνευματος]{.greek-abbr} του αγιου ουκ αφεθησεται αυτω ουτε εν τω [νυν]{.greek-omitted} αιωνι [τουτω]{.greek-added} ουτε εν τω μελλοντι[12:32]{.aside}

η ποιησατε το δενδρον καλον και τον καρπον αυτου καλον η ποιησατε το δενδρον σαπρον και τον καρπον αυτου σαπρον εκ γαρ του καρπου το δενδρον γινωσκεται[12:33]{.aside}

γεννηματα εχιδνων πως [δυνασθε]{.greek-omitted} [δυνασθαι]{.greek-added} αγαθα λαλειν πονηροι οντες εκ γαρ του περισσευματος της καρδιας το στομα λαλει[12:34]{.aside}

ο αγαθος [ανθρωπος]{.greek-abbr} εκ του αγαθου θησαυρου εκβαλλει [τα]{.greek-added} αγαθα και ο πονηρος [ανθρωπος]{.greek-abbr} εκ του πονηρου θησαυρου [εκβαλλει]{.greek-omitted} [της]{.greek-added} [καρδιας]{.greek-added} [προφερει]{.greek-added} [τα]{.greek-added} πονηρα[12:35]{.aside}

λεγω [δε]{.greek-omitted} [γαρ]{.greek-added} υμιν οτι παν ρημα αργον ο εαν λαλησωσιν οι [ανθρωποι]{.greek-abbr} [αποδωσουσιν]{.greek-omitted} [αποδωσουσι]{.greek-added} περι αυτου λογον εν ημερα κρισεως[12:36]{.aside}

εκ γαρ των λογων σου δικαιωθηση και εκ των λογων σου καταδικασθηση[12:37]{.aside}

τοτε [απεκριθησαν]{.greek-omitted} [απεκριθη]{.greek-added} [σαν]{.greek-added} [αυτω]{.greek-added} τινες των γραμματεων και φαρισαιων λεγοντες διδασκαλε [θελομεν]{.greek-omitted} [θελωμεν]{.greek-added} απο σου σημειον ιδειν[12:38]{.aside}

[και]{.greek-added} [ο]{.greek-omitted} [δε]{.greek-omitted} αποκριθεις ειπεν αυτοις γενεα πονηρα και μοιχαλις σημειον επιζητει και σημειον ου δοθησεται αυτη ει μη το σημειον ιωνα του προφητου[12:39]{.aside}

ωσπερ γαρ ην ιωνας εν τη κοιλια του κητους τρεις ημερας και τρεις νυκτας ουτως εσται ο υιος του [ανθρωπου]{.greek-abbr} εν τη καρδια της γης τρεις ημερας και τρεις νυκτας[12:40]{.aside}

ανδρες νινευιται αναστησονται εν τη κρισει μετα της γενεας ταυτης και κατακρινουσιν αυτην οτι μετενοησαν εις το κηρυγμα ιωνα και ιδου πλειον ιωνα ωδε[12:41]{.aside}

βασιλισσα νοτου εγερθησεται εν τη κρισει μετα της γενεας ταυτης και κατακρινει αυτην οτι ηλθεν εκ των περατων της γης ακουσαι την σοφιαν σολομωνος και ιδου πλειον σολομωνος ωδε[12:42]{.aside}

οταν δε το ακαθαρτον [πνευμα]{.greek-abbr} εξελθη απο του [ανθρωπου]{.greek-abbr} διερχεται δι ανυδρων τοπων ζητουν [ανα]{.greek-added} [αναπαυσιν]{.greek-omitted} [παυσιν]{.greek-added} κα[ι]{.greek-supplied} [ου]{.greek-supplied}χ ευρισκει[12:43]{.aside}

τοτε λεγει [επιστρεψω]{.greek-omitted} [υποστρεψ[ω]{.unclear}]{.greek-added} [ει]{.greek-supplied}ς τον οικον μου οθεν εξηλθον και ελθ[ο]{.unclear}[ν]{.greek-supplied} [ε]{.greek-supplied}υρισκει σχολαζοντα σεσαρωμ[ε]{.unclear}[ν]{.greek-supplied}ον και κεκοσμημενον[12:44]{.aside}

τοτε πορευεται και παραλαμβανει μεθ εαυτου επτα ετερα [πνευματα]{.greek-abbr} πονηροτερα εαυτου και εισελθοντα κατοικει εκει και γινεται τα εσχατα του [ανθρωπου]{.greek-abbr} εκεινου [χειρονα]{.greek-omitted} [χειρωνα]{.greek-added} των πρωτων ουτως εσται και τη γενεα ταυτη τη πονηρα[12:45]{.aside}

ετι δε αυτου λαλουντος τοις οχλοις ιδου η [μητηρ]{.greek-abbr} και οι αδελφοι αυτου [ειστηκεισαν]{.greek-omitted} [ειστηκησαν]{.greek-added} εξω ζητουντες αυτω λαλησαι[12:46]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε τις αυτω ιδου η [μητηρ]{.greek-abbr} σου και οι αδελφοι σου εξω [εστηκασιν]{.greek-omitted} [εστηκασι]{.greek-added} ζητουντες σοι λαλησαι[12:47]{.aside}

ο δε αποκριθεις ειπεν τω ειποντι αυτω τις εστιν η [μητηρ]{.greek-abbr} μου και τινες εισιν οι αδελφοι μου[12:48]{.aside}

και εκτεινας την χειρα αυτου επι τους μαθητας αυτου ειπεν ιδου η [μητηρ]{.greek-abbr} μου και οι αδελφοι μου[12:49]{.aside}

οστις γαρ αν ποιηση το θελημα του [πατρος]{.greek-abbr} μου του εν [ουρανοις]{.greek-abbr} [αυτος]{.greek-omitted} [ουτος]{.greek-added} μου αδελφος και αδελφη και [μητηρ]{.greek-abbr} εστιν[12:50]{.aside}

### Chapter 13

εν δε τη [η]{.greek-added} [ημερα]{.greek-omitted} [μερα]{.greek-added} εκεινη εξελθ[ω]{.unclear}[ν]{.greek-supplied} [ο]{.unclear} [ιησους]{.greek-abbr} απο της οικιας εκαθητο παρ[α]{.greek-supplied} την θαλασσαν[13:1]{.aside}

και συνηχθησαν [π]{.unclear}[ρ]{.greek-supplied}ος αυτον οχλοι πολλοι ωστε αυτο[ν]{.unclear} [ει]{.greek-supplied}ς [το]{.greek-omitted} πλοιον εμβαντα [καθησθ[―]{.gap}]{.greek-added} [καθησθαι]{.corr} και πας ο οχλος επι τον αιγιαλον ειστηκει[13:2]{.aside}

και ελαλησεν αυτοις πολλα εν παραβολαις λεγων ιδου εξηλθεν ο σπειρων του σπειρειν[13:3]{.aside}

και εν τω σπειρειν αυτον α μεν [επεσεν]{.greek-omitted} [επεσε]{.greek-added} παρα την οδον και ηλθεν τα πετεινα [του]{.greek-added} [[ουρανου]{.greek-abbr}]{.greek-added} και κατεφαγεν αυτα[13:4]{.aside}

αλλα δε επεσεν επι τα πετρωδη οπου ουκ [ειχεν]{.greek-omitted} [ειχε]{.greek-added} γην πολλην και ευθεως [εξανετειλεν]{.greek-omitted} [εξανετειλε]{.greek-added} δια το μη εχειν βαθος γης[13:5]{.aside}

ηλιου δε ανατειλαντος [εκαυματισθη]{.greek-omitted} [εκκαυματισθη]{.greek-added} και δια το μη εχειν ριζαν εξηρανθη[13:6]{.aside}

αλλα δε επεσεν επι τας ακανθας και ανεβησαν αι ακανθαι και απεπνιξαν αυτα[13:7]{.aside}

αλλα δε επεσεν επι την γην την καλην και εδιδου καρπον ο μεν εκατον ο δε εξηκοντα ο δε τριακοντα[13:8]{.aside}

ο εχων ωτα ακουειν [α]{.greek-added} [ακουετω]{.greek-omitted} [κουετω]{.greek-added}[13:9]{.aside}

και προσελθοντες οι μαθηται ειπον αυτω δια τι εν παραβολαις λαλεις αυτοις[13:10]{.aside}

ο δε αποκριθεις ειπεν αυτοις οτι υμιν δεδοται γνωναι τα μυστηρια της βασιλειας των [ουρανων]{.greek-abbr} εκεινοις δε ου δεδοται[13:11]{.aside}

οστις γαρ εχει δοθησεται αυτω και περισσευθησεται οστις δε ουκ εχει και ο [δοκει]{.greek-added} [εχει]{.greek-omitted} [εχειν]{.greek-added} αρθησεται απ αυτου[13:12]{.aside}

δια τουτο εν παραβολαις αυτοις λαλω οτι βλεποντες ου [βλεπουσιν]{.greek-omitted} [βλεπουσι]{.greek-added} και ακουοντες ουκ ακουουσιν ουδε συνιουσιν[13:13]{.aside}

και αναπληρουται αυτοις η προφητεια ησαιου η λεγουσα ακοη [ακουσετε]{.greek-omitted} [ακουσητε]{.greek-added} και ου μη συνητε και βλεποντες [βλεψετε]{.greek-omitted} [βλεψητε]{.greek-added} και ου μη ιδητε[13:14]{.aside}

επαχυνθη γαρ η καρδια του λαου τουτου και τοις ωσιν [αυτων]{.greek-added} βαρεως ηκουσαν και τους οφθαλμους αυτων εκαμμυσαν μηποτε [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} τοις οφθαλμοις και τοις ωσιν [ακουσωσιν]{.greek-omitted} [ακουσωσι]{.greek-added} και τη καρδια [συνωσιν]{.greek-omitted} [συνωσι]{.greek-added} και [επιστρεψωσιν]{.greek-omitted} [επιστραφωσι]{.greek-added} και ιασομαι αυτους[13:15]{.aside}

υμων δε μακαριοι οι οφθαλμοι οτι [βλεπουσιν]{.greek-omitted} [βλεπουσι]{.greek-added} και τα ωτα υμων οτι [ακουει]{.greek-omitted} [ακουουσιν]{.greek-added}[13:16]{.aside}

αμην γαρ λεγω υμιν οτι πολλοι προφηται και δικαιοι επεθυμησαν ιδειν α βλεπετε και ουκ ειδον και ακουσαι α ακουετε και ουκ ηκουσαν[13:17]{.aside}

υμεις ουν ακουσατε την παραβολην του σπειροντος[13:18]{.aside}

παντος ακουοντος τον λογον της βασιλειας [των]{.greek-added} [[ουρανων]{.greek-abbr}]{.greek-added} και μη συνιεντος ερχεται ο πονηρος και αρπαζει το εσπαρμενον εν τη καρδια αυτου ουτος εστιν ο παρα την οδον σπαρεις[13:19]{.aside}

ο δε επι τα πετρωδη σπαρεις ουτος εστιν ο τον λογον ακουων και [ευθυς]{.greek-omitted} [ευθεως]{.greek-added} μετα χαρας λαμβανων αυτον[13:20]{.aside}

ουκ εχει δε ριζαν εν εαυτω αλλα προσκαιρος εστιν [γενομενης]{.greek-omitted} [γινομενης]{.greek-added} δε θλιψεως η διωγμου δια τον λογον [ευθυς]{.greek-omitted} [ευθεως]{.greek-added} σκανδαλιζεται[13:21]{.aside}

ο δε εις τας ακανθας σπαρεις ουτος εστιν ο τον λογον ακουων και η μεριμνα του αιωνος τουτου και η απατη του πλουτου συμπνιγει τον λογον και ακαρπος γινεται[13:22]{.aside}

ο δε επι την γην την καλην σπαρεις ουτος εστιν ο τον λογον ακουων και συνιων ος [δη]{.greek-omitted} [δει]{.greek-added} καρποφορει και ποιει ο μεν εκατον ο δε εξηκοντα ο δε τριακοντα[13:23]{.aside}

αλλην παραβολην παρεθηκεν αυτοις λεγων [ωμοιωθη]{.greek-omitted} [ομοια]{.greek-added} [εστιν]{.greek-added} η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} [σπειροντι]{.greek-omitted} [σπειραντι]{.greek-added} καλον σπερμα εν τω αγρω αυτου[13:24]{.aside}

εν δε τω καθευδειν τους [ανθρωπους]{.greek-abbr} ηλθεν αυτου ο εχθρος και εσπειρεν ζιζανια ανα μεσον του σιτου και απηλθεν[13:25]{.aside}

οτε δε εβλαστησεν ο χορτος και [καρπο[―]{.gap}]{.greek-added} [καρπον]{.corr} εποιησεν τοτε εφανη και τα ζιζανια[13:26]{.aside}

[και]{.greek-added} προσελθοντες [δε]{.greek-omitted} οι δουλοι του οικοδεσποτου ειπον αυτω [κυριε]{.greek-abbr} ουχι καλον σπερμα [εσπειρας]{.greek-omitted} [εσπειρες]{.greek-added} εν τω σω αγρω ποθεν ουν εχει ζιζανια[13:27]{.aside}

ο δε εφη αυτοις εχθρος [ανθρωπος]{.greek-abbr} τουτο εποιησεν οι δε δουλοι ειπον αυτω θελεις ουν απελθοντες [συλλεξομεν]{.greek-omitted} [συλλεξωμεν]{.greek-added} αυτα[13:28]{.aside}

ο δε εφη ου μηποτε συλλεγοντες τα ζιζανια εκριζωσητε αμα αυτοις τον σιτον[13:29]{.aside}

αφετε συναυξανεσθαι αμφοτερα μεχρι του θερισμου και εν καιρω του θερισμου ερω τοις θερισταις συλλεξατε πρωτον τα [ζι]{.greek-added} [ζιζανια]{.greek-omitted} [ζανια]{.greek-added} και δησατε αυτα εις δεσμας προς το κατακαυσαι αυτα τον δε σιτον συναγαγετε εις την αποθηκην μου[13:30]{.aside}

αλλην παραβολην παρεθηκεν αυτοις λεγων ομοια εστιν η βασιλεια των [ουρανων]{.greek-abbr} κοκκω σιναπεως ον λαβων [ανθρωπος]{.greek-abbr} εσπειρεν εν τω αγρω αυτου[13:31]{.aside}

ο μικροτερον μεν [εστιν]{.greek-omitted} [εστι]{.greek-added} παντων των σπερματων οταν δε [αυξηθη]{.greek-omitted} [αυξανθη]{.greek-added} μειζον των λαχανων εστιν και γινεται δενδρον ωστε ελθειν τα πετεινα του [ουρανου]{.greek-abbr} και κατασκηνουν εν τοις κλαδοις αυτου[13:32]{.aside}

αλλην παραβολην [ελαλησεν]{.greek-omitted} [παρεθηκεν]{.greek-added} αυτοις ομοια εστιν η βασιλεια των ουρανων ζυμη ην λαβουσα γυνη [εκρυψεν]{.greek-omitted} [ενεκρυψεν]{.greek-added} εις αλευρου σατα τρια εως ου εζυμωθη ολον[13:33]{.aside}

ταυτα παντα ελαλησεν ο [ιησους]{.greek-abbr} εν παραβολαις τοις οχλοις και χωρις παραβολης [ουκ]{.greek-omitted} [ουδεν]{.greek-added} ελαλει αυτοις[13:34]{.aside}

οπως πληρωθη το ρηθεν δια του προφητου λεγοντος ανοιξω εν παραβολαις το στομα μου ερευξομαι κεκρυμμενα απο καταβολης κοσμου[13:35]{.aside}

τοτε αφεις τους οχλους ηλθεν εις την οικιαν ο [ιησους]{.greek-abbr} και προσηλθον αυτω οι μαθηται αυτου λεγοντες φρασον ημιν την παραβολην των ζιζανιων του αγρου[13:36]{.aside}

ο δε αποκριθεις ειπεν αυτοις ο σπειρων το καλον σπερμα εστιν ο υιος του [ανθρωπου]{.greek-abbr}[13:37]{.aside}

ο δε αγρος εστιν ο κοσμος το δε καλον σπερμα ουτοι εισιν οι υιοι της βασιλειας τα δε ζιζανια εισιν οι υιοι του πονηρου[13:38]{.aside}

ο δε εχθρος ο σπειρας αυτα εστιν ο διαβολος ο δε θερισμος συντελεια του αιωνος εστιν οι δε θερισται αγγελοι εισιν[13:39]{.aside}

ωσπερ ουν συλλεγεται τα ζιζανια και πυρι καιεται ουτως εσται εν τη συντελεια του αιωνος [τουτου]{.greek-omitted}[13:40]{.aside}

αποστελει ο υιος του [ανθρωπου]{.greek-abbr} τους αγγελους αυτου και συλλεξουσιν εκ της βασιλειας αυτου παντα τα σκανδαλα και τους ποιουντας την ανομιαν[13:41]{.aside}

και [βαλουσιν]{.greek-omitted} [εμβαλουσιν]{.greek-added} αυτους εις την καμινον του πυρος εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[13:42]{.aside}

τοτε οι δικαιοι εκλαμψουσιν ως ο ηλιος εν τη βασιλεια του [πατρος]{.greek-abbr} αυτων ο εχων ωτα ακουειν ακουετω[13:43]{.aside}

παλιν ομοια εστιν η βασιλεια των [ουρανων]{.greek-abbr} θησαυρω κεκρυμμενω εν [τω]{.greek-omitted} αγρω ον ευρων [ανθρωπος]{.greek-abbr} εκρυψεν και απο της χαρας αυτου υπαγει και [πωλει]{.greek-added} παντα οσα εχει [πωλει]{.greek-omitted} και αγοραζει τον αγρον εκεινον[13:44]{.aside}

παλιν ομοια εστιν η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} εμπορω ζητουντι καλους μαργαριτας[13:45]{.aside}

ος ευρων ενα πολυτιμον μαργαριτην απελθων [πεπρακεν]{.greek-omitted} [πεπρακε]{.greek-added} παντα οσα [ειχεν]{.greek-omitted} [ειχε]{.greek-added} και ηγορασεν αυτον[13:46]{.aside}

παλιν ομοια εστιν η βασιλεια των ουρανων σαγηνη βληθειση εις την θαλασσαν και εκ παντος γενους συναγαγουση[13:47]{.aside}

[η]{.unclear}ν οτε επληρωθη αναβιβασαντες επι τον αιγιαλον και καθισαντες συνελεξαν τα καλα εις αγγεια τα δε σαπρα εξω εβαλον[13:48]{.aside}

ουτως εσται εν τη συντελεια του αιωνος εξελευσονται οι αγγελοι και αφοριουσιν τους πονηρους εκ μεσου των δικαιων[13:49]{.aside}

και βαλουσιν αυτους εις την καμινον του πυρος εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[13:50]{.aside}

λεγει αυτοις ο [ιησους]{.greek-abbr} συνηκατε ταυτα παντα λεγουσιν αυτω ναι [κυριε]{.greek-abbr}[13:51]{.aside}

ο δε [ειπεν]{.greek-omitted} [λεγει]{.greek-added} αυτοις δια τουτο πας γραμματευς μαθητευθεις εις την βασιλειαν των [ουρανων]{.greek-abbr} ομοιος εστιν [ανθρωπω]{.greek-abbr} οικοδεσποτη οστις [εκβαλλει]{.greek-omitted} [εκβαλλη]{.greek-added} εκ του θησαυρου αυτου καινα και παλαια[13:52]{.aside}

και εγενετο οτε ετελεσεν ο [ιησους]{.greek-abbr} τας παραβολας ταυτας μετηρεν εκειθεν[13:53]{.aside}

και ελθων εις την [πατριδα]{.greek-abbr} αυτου εδιδασκεν αυτους εν τη συναγωγη αυτων ωστε [εκπληττεσθαι]{.greek-omitted} [εκπλησεσθαι]{.greek-added} αυτους και λεγειν ποθεν τουτω η σοφια [αυτη]{.greek-omitted} [αὕτη]{.greek-added} και αι δυναμεις[13:54]{.aside}

ουχ ουτος εστιν ο του [τεκτονος]{.greek-omitted} [τεκτωνος]{.greek-added} υιος ουχι η [μητηρ]{.greek-abbr} αυτου λεγεται μαριαμ και οι αδελφοι αυτου ιακωβος και [ιωσης]{.greek-omitted} [ιωση]{.greek-added} και σιμων και ιουδας[13:55]{.aside}

και αι αδελφαι αυτου ουχι πασαι προς ημας [εισιν]{.greek-omitted} [εισι]{.greek-added} ποθεν ουν τουτω ταυτα παντα[13:56]{.aside}

και εσκανδαλιζοντο εν αυτω ο δε [ιησους]{.greek-abbr} [αποκριθεις]{.greek-added} ειπεν αυτοις ουκ εστιν προφητης ατιμος ει μη εν τη [πατριδι]{.greek-abbr} αυτου και εν τη οικια [αυτου]{.greek-omitted}[13:57]{.aside}

και ουκ εποιησεν εκει δυναμεις πολλας δια την απιστιαν αυτων[13:58]{.aside}

### Chapter 14

εν εκεινω τω καιρω ηκουσεν ηρωδης ο τετραρχης την ακοην [ιησου]{.greek-abbr}[14:1]{.aside}

και ειπεν τοις παισιν αυτου ουτος εστιν ιωαννης ο βαπτιστης αυτος ηγερθη απο των νεκρων και δια τουτο αι δυναμεις ενεργουσιν εν αυτω[14:2]{.aside}

ο γαρ ηρωδης [τοτε]{.greek-added} κρατησας τον ιωαννην εδησεν αυτον και [εθετο]{.greek-omitted} [απεθετο]{.greek-added} εν [τη]{.greek-added} φυλακη δια ηρωδιαδα την γυναικα φιλιππου του αδελφου αυτου[14:3]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ αυτω ο ιωαννης ουκ εξεστιν σοι εχειν αυτην[14:4]{.aside}

και θελων αυτον αποκτειναι εφοβηθη τον οχλον οτι ως προφητην αυτον ειχον[14:5]{.aside}

γενεσιων δε [αγομενων]{.greek-omitted} [γενομενων]{.greek-added} του ηρωδου ωρχησατο η θυγατηρ της ηρωδιαδος εν τω μεσω και [ηρεσεν]{.greek-omitted} [ηρεσε]{.greek-added} τω ηρωδη[14:6]{.aside}

οθεν μεθ ορκου [ωμολογησεν]{.greek-omitted} [ωμοσεν]{.greek-added} αυτη δουναι ο εαν αιτησηται[14:7]{.aside}

η δε προβιβασθεισα υπο της [μητρος]{.greek-abbr} αυτης [ειπεν]{.greek-added} δος [μοι]{.greek-omitted} φησιν ωδε επι πινακι την κεφαλην ιωαννου του βαπτιστου[14:8]{.aside}

και ελυπηθη ο βασιλευς δια δε τους ορκους και τους συνανακειμενους [εκελευσεν]{.greek-omitted} [εκελευσε]{.greek-added} δοθηναι[14:9]{.aside}

και πεμψας [απεκεφαλισεν]{.greek-omitted} [απεκεφαλισε]{.greek-added} τον ιωαννην εν τη φυλακη[14:10]{.aside}

και ηνεχθη η κεφαλη αυτου επι πινακι και εδοθη τω κορασιω και [ηνεγκεν]{.greek-omitted} [ηνεγκε]{.greek-added} τη [μητρι]{.greek-abbr} αυτης[14:11]{.aside}

και προσελθοντες οι μαθηται αυτου ηραν το [σωμα]{.greek-omitted} [πτωμα]{.greek-added} [αυτου]{.greek-added} και εθαψαν αυτο και ελθοντες απηγγειλαν τω [ιησου]{.greek-abbr}[14:12]{.aside}

[και]{.greek-omitted} ακουσας [δε]{.greek-added} ο [ιησους]{.greek-abbr} ανεχωρησεν εκειθεν εν πλοιω εις ερημον τοπον κατ ιδιαν και ακουσαντες οι οχλοι ηκολουθησαν αυτω πεζη απο των πολεων[14:13]{.aside}

και εξελθων ο [ιησους]{.greek-abbr} ειδεν πολυν οχλον και [εσπλαγχνισθη]{.greek-omitted} [εσπλαχνισθη]{.greek-added} επ αυτοις και [εθεραπευσεν]{.greek-omitted} [εθεραπευσε]{.greek-added} τους αρρωστους αυτων[14:14]{.aside}

οψιας δε γενομενης προσηλθον αυτω οι μαθηται αυτου λεγοντες ερημος εστιν ο τοπος και η ωρα ηδη παρηλθεν απολυσον τους οχλους ινα απελθοντες εις τας κωμας αγορασωσιν εαυτοις βρωματα[14:15]{.aside}

ο δε [φησιν]{.greek-added} [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} ου χρειαν εχουσιν απελθειν δοτε αυτοις υμεις φαγειν[14:16]{.aside}

οι δε λεγουσιν αυτω ουκ εχομεν ωδε ει μη πεντε αρτους και δυο ιχθυας[14:17]{.aside}

ο δε [ειπεν]{.greek-omitted} [ειπε]{.greek-added} φερετε μοι αυτους ωδε[14:18]{.aside}

και κελευσας τους οχλους ανακλιθηναι επι [τους]{.greek-omitted} [του]{.greek-added} [χορτους]{.greek-omitted} [χορτου]{.greek-added} λαβων τους πεντε αρτους και τους δυο ιχθυας αναβλεψας εις τον [ουρανον]{.greek-abbr} [ευλογησεν]{.greek-omitted} [ευλογησε]{.greek-added} και κλασας [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} τοις μαθηταις τους αρτους οι δε μαθηται τοις οχλοις[14:19]{.aside}

και εφαγον παντες και εχορτασθησαν και ηραν το περισσευον των κλασματων δωδεκα κοφινους πληρεις[14:20]{.aside}

οι δε εσθιοντες ησαν ανδρες [ωσει]{.greek-omitted} [ως]{.greek-added} πεντακισχιλιοι χωρις γυναικων και παιδιων[14:21]{.aside}

και ευθεως ηναγκασεν [ο]{.greek-omitted} [ιησους]{.greek-omitted} τους μαθητας εμβηναι εις το πλοιον και προαγειν αυτον εις το περαν εως ου απολυση τους οχλους[14:22]{.aside}

[και]{.greek-omitted} [απολυσας]{.greek-omitted} [τους]{.greek-omitted} [οχλους]{.greek-omitted} ανεβη εις το ορος [προσευξασθαι]{.greek-added} κατ ιδιαν [προσευξασθαι]{.greek-omitted} οψιας δε γενομενης [μονος]{.greek-omitted} ην εκει[14:23]{.aside}

το δε πλοιον ηδη μεσον της θαλασσης ην βασανιζομενον υπο των κυματων ην γαρ εναντιος ο ανεμος[14:24]{.aside}

τεταρτη δε φυλακη της νυκτος [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} προς αυτους ο [ιησους]{.greek-abbr} περιπατων επι [της]{.greek-omitted} [την]{.greek-added} [θαλασσης]{.greek-omitted} [θαλασσαν]{.greek-added}[14:25]{.aside}

[[και]{.unclear}]{.greek-added} [[ιδον]{.unclear}τες]{.greek-added} [α[υ]{.unclear}τον]{.greek-added} [ο[ι]{.unclear}]{.greek-added} [[μαθ]{.unclear}[η]{.greek-supplied}ται]{.greek-added} [ε[πι]{.greek-supplied}]{.greek-added} [[τη]{.greek-supplied}ν]{.greek-added} [θ[α]{.greek-supplied}λα[σσ]{.unclear}αν]{.greek-added} και ιδοντες αυτον οι μαθηται επι την θαλασσαν περιπατουντα εταραχθησαν λεγοντες [οτι]{.greek-omitted} [φαντασμα]{.greek-omitted} [εστιν]{.greek-omitted} [και]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [φοβου]{.greek-omitted} [εκραξαν]{.greek-omitted}[14:26]{.aside}

### Chapter 15

και μεταβας εκειθεν ο [ιησους]{.greek-abbr} [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} παρα την θαλασσαν της γαλιλαιας και αναβας εις το ορος [εκαθητο]{.greek-omitted} [εκαθειτο]{.greek-added} εκει[15:29]{.aside}

και προσηλθον αυτω οχλοι πολλοι εχοντες μεθ εαυτων χωλους τυφλους κωφους κυλλους και ετερους πολλους και ερριψαν αυτους παρα τους ποδας του [ιησου]{.greek-abbr} και εθεραπευσεν αυτους[15:30]{.aside}

ωστε τους οχλους θαυμασαι βλεποντας κωφους [λαλουντας]{.greek-omitted} [ακουοντας]{.greek-added} κυλλους υγιεις χωλους περιπατουντας και τυφλους βλεποντας και [εδοξασαν]{.greek-omitted} [εδοξαζον]{.greek-added} τον [θεον]{.greek-abbr} [ισραηλ]{.greek-abbr}[15:31]{.aside}

ο δε [ιησους]{.greek-abbr} προσκαλεσαμενος τους μαθητας αυτου ειπεν σπλαγχνιζομαι επι τον οχλον [τουτον]{.greek-added} οτι ηδη [ημεραι]{.greek-omitted} [ημερας]{.greek-added} τρεις [προσμενουσιν]{.greek-omitted} [προσμενουσι]{.greek-added} μοι και ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} τι [φαγωσιν]{.greek-omitted} [φαγωσι]{.greek-added} και απολυσαι αυτους [νηστεις]{.greek-omitted} [νηστις]{.greek-added} ου θελω μηποτε εκλυθωσιν εν τη οδω[15:32]{.aside}

και λεγουσιν αυτω οι μαθηται αυτου ποθεν ημιν εν ερημια [τοσουτοι]{.greek-added} αρτοι [τοσουτοι]{.greek-omitted} ωστε χορτασαι οχλον τοσουτον[15:33]{.aside}

και λεγει αυτοις ο [ιησους]{.greek-abbr} ποσους αρτους εχετε οι δε ειπον επτα και ολιγα ιχθυδια[15:34]{.aside}

και εκελευσεν [τοις]{.greek-omitted} [τους]{.greek-added} [οχλοις]{.greek-omitted} [οχλους]{.greek-added} αναπεσειν επι την γην[15:35]{.aside}

και λαβων τους επτα αρτους και τους ιχθυας ευχαριστησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} τοις μαθηταις αυτου οι δε μαθηται τω οχλω[15:36]{.aside}

και εφαγον παντες και εχορτασθησαν και ηραν το περισσευον των κλασματων επτα σπυριδας [πληρεις]{.greek-omitted} [πληρης]{.greek-added}[15:37]{.aside}

οι δε εσθιοντες ησαν τετρακισχιλιοι ανδρες χωρις γυναικων και παιδιων[15:38]{.aside}

και απολυσας τους οχλους [ενεβη]{.greek-omitted} [ανεβη]{.greek-added} εις το πλοιον και ηλθεν εις τα ορια μαγδαλα[15:39]{.aside}

### Chapter 16

και προσελθοντες οι φαρισαιοι και [οι]{.greek-added} σαδδουκαιοι πειραζοντες επηρωτησαν αυτον σημειον εκ του [ουρανου]{.greek-abbr} επιδειξαι αυτοις[16:1]{.aside}

ο δε αποκριθεις ειπεν αυτοις οψιας γενομενης λεγετε ευδια πυρραζει γαρ ο [ουρανος]{.greek-abbr}[16:2]{.aside}

[και]{.greek-omitted} πρωι σημερον [χειμων]{.greek-omitted} [χιμων]{.greek-added} [πυρραζει]{.greek-omitted} [πειρραζει]{.greek-added} γαρ στυγναζων ο [ουρανος]{.greek-abbr} υποκριται το μεν προσωπον του [ουρανου]{.greek-abbr} γινωσκετε διακρινειν τα δε σημεια των καιρων ου δυνασθε[16:3]{.aside}

γενεα πονηρα και μοιχαλις σημειον επιζητει και σημειον ου δοθησεται αυτη ει μη το σημειον ιωνα του προφητου και καταλιπων αυτους [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added}[16:4]{.aside}

και ελθοντες οι μαθηται αυτου εις το περαν [επε]{.greek-added} [επελαθοντο]{.greek-omitted} [αρτους]{.greek-omitted} [λαβειν]{.greek-omitted}[16:5]{.aside}

### Chapter 17

[και]{.greek-omitted} [επηρωτησαν]{.greek-omitted} [αυτον]{.greek-omitted} [οι]{.greek-omitted} [μαθηται]{.greek-omitted} [αυτου]{.greek-omitted} [λεγοντες]{.greek-omitted} [τι]{.greek-omitted} [ουν]{.greek-omitted} [οι]{.greek-omitted} [γραμματεις]{.greek-omitted} [μματεις]{.greek-added} λεγουσιν οτι ηλιαν δει ελθειν πρωτον[17:10]{.aside}

ο δε [ιησους]{.greek-abbr} αποκριθεις ειπεν αυτοις ηλιας μεν ερχεται πρωτον και αποκαταστησει παντα[17:11]{.aside}

λεγω δε υμιν οτι ηλιας ηδη ηλθεν και ουκ επεγνωσαν αυτον [αλλα]{.greek-omitted} [αλλ]{.greek-added} εποιησαν [εν]{.greek-omitted} αυτω οσα ηθελησαν ουτως και ο υιος του [ανθρωπου]{.greek-abbr} μελλει πασχειν υπ αυτων[17:12]{.aside}

τοτε συνηκαν οι μαθηται οτι περι ιωαννου του βαπτιστου ειπεν αυτοις[17:13]{.aside}

και ελθοντων αυτων προς τον οχλον προσηλθεν αυτω [ανθρωπος]{.greek-abbr} γονυπετων αυτον[17:14]{.aside}

και λεγων [κυριε]{.greek-abbr} ελεησον μου τον υιον οτι σεληνιαζεται και κακως πασχει πολλακις γαρ πιπτει εις το πυρ και πολλακις εις το υδωρ[17:15]{.aside}

και προσηνεγκα αυτον τοις μαθηταις σου και ουκ ηδυνηθησαν αυτον θεραπευσαι[17:16]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν ω γενεα απιστος και διεστραμμενη εως ποτε εσομαι μεθ [υμων]{.greek-omitted} [ημων]{.greek-added} εως ποτε ανεξομαι υμων φερετε μοι αυτον ωδε[17:17]{.aside}

και επετιμησεν αυτω ο [ιησους]{.greek-abbr} και εξηλθεν απ αυτου το δαιμονιον και εθεραπευθη ο παις απο της ωρας εκεινης[17:18]{.aside}

τοτε [προσελθοντες]{.greek-omitted} [προσελ]{.greek-added} [θοντες]{.greek-added} οι μαθηται τω [ιησου]{.greek-abbr} κατ ιδιαν ειπον δια τι ημεις ουκ ηδυνηθημεν εκβαλειν αυτο[17:19]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις δια την απιστιαν υμων αμην γαρ λεγω υμιν εαν εχητε πιστιν ως κοκκον σιναπεως ερειτε τω ορει τουτω μεταβηθι εντευθεν εκει και μεταβησεται και ουδεν αδυνατησει υμιν[17:20]{.aside}

τουτο δε το γενος ουκ εκπορευεται ει μη εν προσευχη και νηστεια[17:21]{.aside}

αναστρεφομενων δε αυτων εν τη γαλιλαια ειπεν αυτοις ο [ιησους]{.greek-abbr} μελλει ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοσθαι εις χειρας [ανθρωπων]{.greek-abbr}[17:22]{.aside}

και αποκτενουσιν αυτον και τη τριτη ημερα εγερθησεται και ελυπηθησαν σφοδρα[17:23]{.aside}

ελθοντων δε αυτων εις καπερναουμ προσηλθον οι τα [διδραχμα]{.greek-omitted} [διδραγμα]{.greek-added} λαμβανοντες τω πετρω και ειπον ο διδασκαλος υμων [ου]{.greek-omitted} [ευ]{.greek-added} τελει τα [διδραχμα]{.greek-omitted} [διδραγμα]{.greek-added}[17:24]{.aside}

λεγει ναι και οτε εισηλθεν εις την οικιαν προεφθασεν αυτον ο [ιησους]{.greek-abbr} λεγων τι σοι δοκει σιμων οι βασιλεις της γης απο τινων [λαμβανουσιν]{.greek-omitted} [λαμβανουσι]{.greek-added} [τελη]{.greek-omitted} [τελει]{.greek-added} η κηνσον απο των υιων αυτων η απο των αλλοτριων[17:25]{.aside}

λεγει αυτω ο πετρος απο των αλλοτριων εφη αυτω ο [ιησους]{.greek-abbr} αρα γε ελευθεροι εισιν οι υιοι[17:26]{.aside}

ινα δε μη [σκαν]{.greek-added} [σκανδαλισωμεν]{.greek-omitted} [αυτους]{.greek-omitted} [πορευθεις]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [θαλασσαν]{.greek-omitted} [βαλε]{.greek-omitted} [αγκιστρον]{.greek-omitted} [και]{.greek-omitted} [τον]{.greek-omitted} [αναβαινοντα]{.greek-omitted} [πρωτον]{.greek-omitted} [ιχθυν]{.greek-omitted} [αρον]{.greek-omitted} [και]{.greek-omitted} [ανοιξας]{.greek-omitted} [το]{.greek-omitted} [στομα]{.greek-omitted} [αυτου]{.greek-omitted} [ευρησεις]{.greek-omitted} [στατηρα]{.greek-omitted} [εκεινον]{.greek-omitted} [λαβων]{.greek-omitted} [δος]{.greek-omitted} [αυτοις]{.greek-omitted} [αντι]{.greek-omitted} [εμου]{.greek-omitted} [και]{.greek-omitted} [σου]{.greek-omitted}[17:27]{.aside}

### Chapter 22

[περι]{.greek-omitted} [δε]{.greek-omitted} [της]{.greek-omitted} [αναστασεως]{.greek-omitted} [των]{.greek-omitted} νεκρων ουκ [ανεγνωτε]{.greek-omitted} [ανεγνωται]{.greek-added} το ρηθεν υμιν υπο του [θεου]{.greek-abbr} λεγοντος[22:31]{.aside}

εγω ειμι ο [θεος]{.greek-abbr} αβρααμ και ο [θεος]{.greek-abbr} ισαακ και ο [θεος]{.greek-abbr} ιακωβ ουκ εστιν ο [θεος]{.greek-abbr} [θεος]{.greek-abbr} νεκρων αλλα ζωντων[22:32]{.aside}

και ακουσαντες οι οχλοι εξεπλησσοντο επι τη διδαχη αυτου[22:33]{.aside}

οι δε φαρισαιοι ακουσαντες οτι εφιμωσεν τους σαδδουκαιους συνηχθησαν επι το αυτο[22:34]{.aside}

και επηρωτησεν εις εξ αυτων νομικος πειραζων αυτον και λεγων[22:35]{.aside}

διδασκαλε ποια εντολη μεγαλη εν τω νομω[22:36]{.aside}

ο δε [ιησους]{.greek-abbr} εφη αυτω αγαπησεις [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου εν ολη [τη]{.greek-added} καρδια σου και εν ολη [τη]{.greek-added} ψυχη σου και εν ολη τη διανοια σου[22:37]{.aside}

αυτη [εστιν]{.greek-omitted} [εστι]{.greek-added} πρωτη και μεγαλη εντολη[22:38]{.aside}

δευτερα δε ομοια [αυτη]{.greek-omitted} [αὕτη]{.greek-added} αγαπησεις τον πλησιον [σον]{.greek-added} [σου]{.corr} ως [σεαυτον]{.greek-omitted} [εαυτον]{.greek-added}[22:39]{.aside}

εν ταυταις ταις δυσιν εντολαις ολος ο νομος και οι προφηται κρεμανται[22:40]{.aside}

συνηγμενων δε των φαρισαιων επηρωτησεν αυτους ο [ιησους]{.greek-abbr}[22:41]{.aside}

λεγων τι υμιν δοκει περι του [χριστου]{.greek-abbr} τινος υιος [εστιν]{.greek-omitted} [εστι]{.greek-added} λεγουσιν αυτω του [δαυιδ]{.greek-abbr}[22:42]{.aside}

[λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [πως]{.greek-omitted} [ουν]{.greek-omitted} [δαυιδ]{.greek-omitted} εν [πνευματι]{.greek-abbr} [κυριον]{.greek-abbr} αυτον καλει λεγων[22:43]{.aside}

ειπεν ο [κυριος]{.greek-abbr} τω [κυριω]{.greek-abbr} μου καθου εκ [δεξιων]{.greek-omitted} [δεξι]{.greek-added} [ων]{.greek-added} μου εως αν θω τους εχθρους σου υποποδιον των ποδων σου[22:44]{.aside}

ει ουν [δαυιδ]{.greek-abbr} [[κυριον]{.greek-abbr}]{.greek-added} [αυτον]{.greek-added} καλει [αυτον]{.greek-omitted} [κυριον]{.greek-omitted} πως υιος αυτου εστιν[22:45]{.aside}

και ουδεις [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} αυτω αποκριθηναι λογον ουδε [ετολμησεν]{.greek-omitted} [ετολμησε]{.greek-added} τις απ εκεινης της ημερας επερωτησαι αυτον ουκετι[22:46]{.aside}

### Chapter 23

τοτε ο [ιησους]{.greek-abbr} [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} τοις οχλοις και τοις μαθηταις αυτου[23:1]{.aside}

λεγων επι της μωσεως καθεδρας εκαθισαν οι γραμματεις και οι φαρισαιοι[23:2]{.aside}

παντα ουν οσα εαν ειπωσιν υμιν τηρειν τηρειτε και ποιειτε κατα δε τα εργα αυτων μη [ποιειτε]{.greek-omitted} [ποιητε]{.greek-added} [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} γαρ και ου ποιουσιν[23:3]{.aside}

[δεσμευουσιν]{.greek-omitted} [δεσμευουσι]{.greek-added} γαρ φορτια βαρεα και δυσβαστακτα και επιτιθεασιν επι τους ωμους των [ανθρωπων]{.greek-abbr} τω δε δακτυλω αυτων ου [θελουσιν]{.greek-omitted} [θελουσι]{.greek-added} κινησαι αυτα[23:4]{.aside}

παντα δε τα εργα αυτων [ποιουσιν]{.greek-omitted} [ποιουσι]{.greek-added} προς το θεαθηναι τοις [ανθρωποις]{.greek-abbr} [πλατυνουσιν]{.greek-omitted} [πλατυνουσι]{.greek-added} [δε]{.greek-omitted} [γαρ]{.greek-added} τα φυλακτηρια αυτων και [μεγαλυνουσιν]{.greek-omitted} [μεγαλυνουσι]{.greek-added} τα κρασπεδα των ιματιων αυτων[23:5]{.aside}

[φιλουσιν]{.greek-omitted} [φιλουσι]{.greek-added} [τε]{.greek-omitted} [δε]{.greek-added} την πρωτοκλισιαν εν τοις δειπνοις και τας πρωτοκαθεδριας εν ταις συναγωγαις[23:6]{.aside}

και τους ασπασμους εν ταις αγοραις και καλεισθαι υπο των [ανθρωπων]{.greek-abbr} ραββι ραββι[23:7]{.aside}

υμεις δε μη κληθητε ραββι εις γαρ εστιν υμων ο καθηγητης [ο]{.greek-omitted} [χριστος]{.greek-abbr} παντες δε υμεις αδελφοι εστε[23:8]{.aside}

και [πατερα]{.greek-abbr} μη καλεσητε υμων επι της γης εις γαρ εστιν ο [πατηρ]{.greek-abbr} υμων ο εν τοις [ουρανοις]{.greek-abbr}[23:9]{.aside}

μηδε κληθητε καθηγηται εις γαρ [εστιν]{.greek-added} υμων [εστιν]{.greek-omitted} ο καθηγητης ο [χριστος]{.greek-abbr}[23:10]{.aside}

ο δε μειζων υμων [εσται]{.greek-omitted} [εστω]{.greek-added} υμων διακονος[23:11]{.aside}

οστις δε υψωσει εαυτον ταπεινωθησεται και οστις ταπεινωσει εαυτον υψωθησεται[23:12]{.aside}

ουαι δε υμιν γραμματεις και φαρισαιοι υποκριται οτι [κατεσθιετε]{.greek-omitted} [τας]{.greek-omitted} [οικιας]{.greek-omitted} [κλειετε]{.greek-added} [την]{.greek-added} [βασιλειαν]{.greek-added} των [χηρων]{.greek-omitted} [και]{.greek-omitted} [προφασει]{.greek-omitted} [μακρα]{.greek-omitted} [προσευχομενοι]{.greek-omitted} [δια]{.greek-omitted} [τουτο]{.greek-omitted} [ληψεσθε]{.greek-omitted} [περισσοτερον]{.greek-omitted} [κριμα]{.greek-omitted} [[ουρανων]{.greek-abbr}]{.greek-added} [εμπροσθεν]{.greek-added} [των]{.greek-added} [[ανθρωπων]{.greek-abbr}]{.greek-added} [υμεις]{.greek-added} [γαρ]{.greek-added} [ουκ]{.greek-added} [εισερχεσθε]{.greek-added} [ουδε]{.greek-added} [τους]{.greek-added} [εισερχομενους]{.greek-added} [αφιετε]{.greek-added} [εισελθειν]{.greek-added}[23:13]{.aside}

ουαι [δε]{.greek-added} υμιν γραμματεις και φαρισαιοι υποκριται οτι [κλειετε]{.greek-omitted} [την]{.greek-omitted} [βασιλειαν]{.greek-omitted} [κατεσθιετε]{.greek-added} [τας]{.greek-added} [οικιας]{.greek-added} των [χηρων]{.greek-added} [και]{.greek-added} [προφα]{.greek-added} [μακρα]{.greek-added} [προσευχομενοι]{.greek-added} [δια]{.greek-added} [τουτο]{.greek-added} [ληψεσθαι]{.greek-added} [περισσοτερον]{.greek-added} [κριμα]{.greek-added} [ουρανων]{.greek-omitted} [εμπροσθεν]{.greek-omitted} [των]{.greek-omitted} [ανθρωπων]{.greek-omitted} [υμεις]{.greek-omitted} [γαρ]{.greek-omitted} [ουκ]{.greek-omitted} [εισερχεσθε]{.greek-omitted} [ουδε]{.greek-omitted} [τους]{.greek-omitted} [εισερχομενους]{.greek-omitted} [αφιετε]{.greek-omitted} [εισελθειν]{.greek-omitted}[23:14]{.aside}

ουαι [δε]{.greek-added} υμιν γραμματεις και φαρισαιοι υποκριται οτι περιαγετε την θαλασσαν και την ξηραν ποιησαι ενα [προ]{.greek-added} [προσηλυτον]{.greek-omitted} [σηλυτον]{.greek-added} και οταν γενηται ποιειτε αυτον υιον γεεννης διπλοτερον υμων[23:15]{.aside}

ουαι υμιν οδηγοι τυφλοι οι λεγοντες ος αν ομοση εν τω ναω ουδεν εστιν ος δ αν ομοση εν τω χρυσω του ναου οφειλει[23:16]{.aside}

μωροι και τυφλοι τις γαρ μειζων εστιν ο χρυσος η ο ναος ο αγιαζων τον χρυσον[23:17]{.aside}

και ος εαν ομοση εν τω θυσιαστηριω ουδεν εστιν ος δ αν ομοση εν τω δωρω τω επανω αυτου οφειλει[23:18]{.aside}

μωροι και τυφλοι [τι]{.greek-omitted} [τις]{.greek-added} γαρ [μειζον]{.greek-omitted} [μειζων]{.greek-added} το δωρον η το θυσιαστηριον το αγιαζον το δωρον[23:19]{.aside}

ο ουν ομοσας εν τω θυσιαστηριω ομνυει εν αυτω και εν [παση]{.greek-added} [πασιν]{.greek-omitted} [[πασι]{.corr}]{.greek-added} τοις επανω αυτου[23:20]{.aside}

και ο [ομοσας]{.greek-omitted} [ομνυων]{.greek-added} εν τω ναω ομνυει εν αυτω και εν τω κατοικησαντι αυτον[23:21]{.aside}

και ο ομοσας εν τω [ουρανω]{.greek-abbr} ομνυει εν τω θρονω του [θεου]{.greek-abbr} και εν τω καθημενω επανω αυτου[23:22]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι αποδεκατουτε το ηδυοσμον και το ανηθον και το [κοιμηνον]{.greek-added} [κυμινον]{.greek-omitted} [[κοιμινον]{.corr}]{.greek-added} και αφηκατε τα βαρυτερα του νομου την κρισιν και τον [ε]{.greek-added} [ελεον]{.greek-omitted} [λεον]{.greek-added} και την πιστιν ταυτα εδει ποιησαι κακεινα μη αφιεναι[23:23]{.aside}

οδηγοι τυφλοι οι διυλιζοντες τον κωνωπα την δε [καμηλον]{.greek-omitted} [καμιλον]{.greek-added} καταπινοντες[23:24]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι [καθαριζετε]{.greek-omitted} [καθαριζεται]{.greek-added} το εξωθεν του ποτηριου και της παροψιδος εσωθεν δε γεμουσιν εξ αρπαγης και αδικιας[23:25]{.aside}

φαρισαιε τυφλε καθαρισον πρωτον το εντος του ποτηριου και της παροψιδος ινα [γενηται]{.greek-omitted} [γενητε]{.greek-added} και το [ε[―]{.gap}τος]{.greek-added} [εκτος]{.corr} αυτων καθαρον[23:26]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι παρομοιαζετε ταφοις κεκονιαμενοις οιτινες εξωθεν μεν φαινονται ωραιοι εσωθεν δε γεμουσιν οστεων νεκρων και πασης ακαθαρσιας[23:27]{.aside}

ουτως και υμεις εξωθεν μεν [φαινεσθε]{.greek-omitted} [φαινεσθαι]{.greek-added} τοις [ανθρωποις]{.greek-abbr} δικαιοι εσωθεν δε μεστοι εστε υποκρισεως και ανομιας[23:28]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι [οικοδομειτε]{.greek-omitted} [οικοδομειται]{.greek-added} [τους]{.greek-omitted} [ταφους]{.greek-omitted} [των]{.greek-omitted} [προφητων]{.greek-omitted} [και]{.greek-omitted} [κοσμειτε]{.greek-omitted} τα μνημεια των δικαιων[23:29]{.aside}

και λεγετε ει [ημεν]{.greek-omitted} [ημεθα]{.greek-added} εν ταις ημεραις των [πατερων]{.greek-abbr} ημων ουκ αν ημεν κοινωνοι αυτων εν τω αιματι των προφητων[23:30]{.aside}

ωστε μαρτυρειτε εαυτοις οτι υιοι εστε των φονευσαντων τους προφητας[23:31]{.aside}

και υμεις [πληρωσατε]{.greek-omitted} [αναπληρωσατε]{.greek-added} το μετρον των [πατερων]{.greek-abbr} [ημων]{.greek-added} [υμων]{.corr}[23:32]{.aside}

οφεις γεννηματα εχιδνων πως φυγητε απο της κρισεως της γεεννης[23:33]{.aside}

δια τουτο ιδου εγω αποστελλω προς υμας προφητας και σοφους και γραμματεις και εξ αυτων αποκτενειτε και [σταυρωσετε]{.greek-abbr} και εξ αυτων μαστιγωσετε εν ταις συναγωγαις υμων και διωξετε απο πολεως εις πολιν[23:34]{.aside}

οπως ελθη εφ υμας παν αιμα δικαιον εκχυνομενον επι της γης απο του αιματος αβελ του δικαιου εως του αιματος ζαχαριου υιου βαραχιου ον εφονευσατε μεταξυ του ναου και του θυσιαστηριου[23:35]{.aside}

αμην λεγω υμιν οτι ηξει [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} επι την γενεαν ταυτην[23:36]{.aside}

[ιερουσαλημ]{.greek-abbr} [ιερουσαλημ]{.greek-abbr} η αποκτενουσα τους προφητας και λιθοβολουσα τους απεσταλμενους προς αυτην ποσακις ηθελησα επισυναγαγειν τα τεκνα σου ον τροπον επισυναγει ορνις τα νοσσια εαυτης υπο τας πτερυγας και ουκ ηθελησατε[23:37]{.aside}

ιδου [αφιεται]{.greek-omitted} [αφιετε]{.greek-added} υμιν ο οικος υμων ερημος[23:38]{.aside}

λεγω γαρ υμιν [οτι]{.greek-added} ου μη με ιδητε απ αρτι εως αν ειπητε ευλογημενος ο ερχομενος εν ονοματι [κυριου]{.greek-abbr}[23:39]{.aside}

### Chapter 24

και εξελθων ο [ιησους]{.greek-abbr} επορευετο απο του ιερου και προσηλθον οι μαθηται αυτου επιδειξαι αυτω τας οικοδομας του ιερου[24:1]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ου βλεπετε [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} αμην λεγω υμιν ου μη αφεθη ωδε λιθος επι [λιθον]{.greek-omitted} [λιθου]{.greek-added} ος ου καταλυθησεται[24:2]{.aside}

καθημενου δε αυτου επι του ορους των ελαιων προσηλθον αυτω οι μαθηται κατ ιδιαν λεγοντες ειπε ημιν ποτε ταυτα εσται και τι το σημειον της σης παρουσιας και της συντελειας του αιωνος [τουτου]{.greek-added}[24:3]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις βλεπετε μη τις υμας πλανηση[24:4]{.aside}

πολλοι γαρ ελευσονται επι τω ονοματι μου λεγοντες εγω ειμι ο [χριστος]{.greek-abbr} και πολλους [πλανησουσιν]{.greek-omitted} [πλανησουσι]{.greek-added}[24:5]{.aside}

μελλησετε δε ακουειν πολεμους και ακοας πολεμων [ορατε]{.greek-omitted} [ορασθαι]{.greek-added} μη [θροεισθε]{.greek-omitted} [θροεισθαι]{.greek-added} δει γαρ παντα γενεσθαι αλλ ουπω [εστιν]{.greek-omitted} [εστι]{.greek-added} το τελος[24:6]{.aside}

εγερθησεται γαρ εθνος επι εθνος και βασιλεια επι βασιλειαν και εσονται λιμοι και [λοιμοι]{.greek-omitted} [λιμοι]{.greek-added} και σεισμοι κατα τοπους[24:7]{.aside}

παντα δε ταυτα αρχη ωδινων[24:8]{.aside}

τοτε παραδωσουσιν υμας εις θλιψιν και αποκτενουσιν υμας και [εσεσθε]{.greek-omitted} [εσεσθαι]{.greek-added} μισουμενοι υπο παντων των εθνων δια το ονομα μου[24:9]{.aside}

και τοτε σκανδαλισθησονται πολλοι και αλληλους παραδωσουσιν και μισησουσιν αλληλους[24:10]{.aside}

και πολλοι ψευδοπροφηται εγερθησονται και [πλανησουσιν]{.greek-omitted} [πλανησουσι]{.greek-added} πολλους[24:11]{.aside}

και δια το πληθυνθηναι την ανομιαν ψυγησεται η αγαπη των πολλων[24:12]{.aside}

ο δε υπομεινας εις τελος ουτος σωθησεται[24:13]{.aside}

και κηρυχθησεται τουτο το ευαγγελιον της βασιλειας εν ολη τη οικουμενη εις μαρτυριον [παση]{.greek-added} [πασιν]{.greek-omitted} [[πασι]{.corr}]{.greek-added} τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} και τοτε ηξει το τελος[24:14]{.aside}

οταν ουν ιδητε το βδελυγμα της ερημωσεως το ρηθεν δια δανιηλ του προφητου [εστως]{.greek-omitted} [εστος]{.greek-added} εν τοπω αγιω ο αναγινωσκων νοειτω[24:15]{.aside}

τοτε οι εν τη ιουδαια [φευγετωσαν]{.greek-omitted} [φευγε]{.greek-added} [τωσαν]{.greek-added} επι τα ορη[24:16]{.aside}

[και]{.greek-added} ο επι του δωματος μη καταβαινετω αραι τα εκ της οικιας [αυτης]{.greek-added} [αυτ[ου]{.unclear}]{.corr}[24:17]{.aside}

και ο εν τω αγρω μη επιστρεψατω οπισω αραι τα ιματια αυτου[24:18]{.aside}

ουαι δε ταις εν γαστρι εχουσαις και ταις θηλαζουσαις εν εκειναις ταις ημεραις[24:19]{.aside}

[προσευχεσθε]{.greek-omitted} [προσευχεσθαι]{.greek-added} δε ινα μη γενηται η φυγη υμων χειμωνος μηδε σαββατω[24:20]{.aside}

εσται γαρ τοτε [θλιψις]{.greek-omitted} [θλιψεις]{.greek-added} μεγαλη οια ου γεγονεν απ αρχης κοσμου [εως]{.greek-omitted} [του]{.greek-omitted} [νυν]{.greek-omitted} ουδ ου μη γενηται[24:21]{.aside}

και ει μη εκολοβωθησαν αι ημεραι εκειναι ουκ αν εσωθη πασα σαρξ δια δε τους εκλεκτους κολοβωθησονται αι ημεραι εκειναι[24:22]{.aside}

τοτε εαν τις υμιν ειπη ιδου ωδε ο [χριστος]{.greek-abbr} η ωδε μη πιστευσητε[24:23]{.aside}

εγερθησονται γαρ ψευδοχριστοι και ψευδοπροφηται και [δωσουσιν]{.greek-omitted} [δωσουσι]{.greek-added} σημεια μεγαλα και τερατα ωστε πλανησαι ει δυνατον και τους εκλεκτους[24:24]{.aside}

ιδου προειρηκα υμιν[24:25]{.aside}

εαν ουν ειπωσιν υμιν ιδου εν τη ερημω εστιν μη εξελθητε ιδου εν τοις [ταμειοις]{.greek-omitted} [ταμιοις]{.greek-added} μη πιστευσητε[24:26]{.aside}

ωσπερ γαρ η αστραπη εξερχεται απο ανατολων και φαινεται εως δυσμων ουτως εσται και η παρουσια του υιου του [ανθρωπου]{.greek-abbr}[24:27]{.aside}

οπου γαρ εαν η το πτωμα εκει συναχθησονται [και]{.greek-added} οι αετοι[24:28]{.aside}

ευθεως δε μετα την θλιψιν των ημερων εκεινων ο ηλιος σκοτισθησεται και η σεληνη ου δωσει το φεγγος αυτης και οι αστερες πεσουνται απο του [ουρανου]{.greek-abbr} και αι δυναμεις των [ουρανων]{.greek-abbr} σαλευθησονται[24:29]{.aside}

και τοτε φανησεται το σημειον του υιου του [ανθρωπου]{.greek-abbr} εν τω [ουρανω]{.greek-abbr} και τοτε κοψονται πασαι αι φυλαι της γης και οψονται τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ερχομενον επι των νεφελων του [ουρανου]{.greek-abbr} μετα δυναμεως και δοξης πολλης[24:30]{.aside}

και αποστελει τους αγγελους αυτου μετα σαλπιγγος φωνης μεγαλης και [επισυναξουσιν]{.greek-omitted} [επισυναξουσι]{.greek-added} τους εκλεκτους αυτου εκ των τεσσαρων ανεμων απ ακρων [ουρανων]{.greek-omitted} [[ουρανου]{.greek-abbr}]{.greek-added} εως ακρων [αυτων]{.greek-omitted} [αυτου]{.greek-added}[24:31]{.aside}

απο δε της συκης μαθετε την παραβολην οταν ηδη ο κλαδος αυτης γενηται απαλος και τα φυλλα εκφυη γινωσκετε οτι εγγυς το θερος[24:32]{.aside}

ουτως και υμεις οταν ιδητε [παντα]{.greek-added} ταυτα [παντα]{.greek-omitted} γινωσκετε οτι εγγυς εστιν επι θυραις[24:33]{.aside}

αμην λεγω υμιν ου μη παρελθη η γενεα αυτη εως αν παντα ταυτα γενηται[24:34]{.aside}

ο [ουρανος]{.greek-abbr} και η γη παρελευσονται οι δε λογοι μου ου μη παρελθωσιν[24:35]{.aside}

περι δε της ημερας εκεινης και ωρας ουδεις οιδεν ουδε οι αγγελοι των [ουρανων]{.greek-abbr} ει μη ο [πατηρ]{.greek-abbr} μου μονος[24:36]{.aside}

ωσπερ δε αι ημεραι του νωε ουτως εσται και η παρουσια του υιου του [ανθρωπου]{.greek-abbr}[24:37]{.aside}

ωσπερ γαρ ησαν εν ταις ημεραις [ταις]{.greek-omitted} [του]{.greek-added} [νωε]{.greek-added} προ του κατακλυσμου τρωγοντες και πινοντες γαμουντες και εκγαμιζοντες αχρι ης ημερας [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} νωε εις την κιβωτον[24:38]{.aside}

και ουκ εγνωσαν εως ηλθεν ο κατακλυσμος και ηρεν απαντας ουτως εσται και η παρουσια του υιου του [ανθρωπου]{.greek-abbr}[24:39]{.aside}

τοτε δυο εσονται εν τω αγρω ο εις παραλαμβανεται και ο εις αφιεται[24:40]{.aside}

δυο αληθουσαι εν τω μυλωνι μια παραλαμβανεται και μια αφιεται[24:41]{.aside}

γρηγορειτε ουν οτι ουκ οιδατε ποια ωρα ο [κυριος]{.greek-abbr} υμων ερχεται[24:42]{.aside}

εκεινο δε γινωσκετε οτι ει [ηδει]{.greek-omitted} [ηδη]{.greek-added} ο οικοδεσποτης ποια φυλακη ο κλεπτης ερχεται εγρηγορησεν αν και ουκ αν ειασεν διορυγηναι την οικιαν αυτου[24:43]{.aside}

δια τουτο και υμεις [γινεσθε]{.greek-omitted} [γινεσθαι]{.greek-added} ετοιμοι οτι η ωρα ου [δοκειτε]{.greek-omitted} [δοκειται]{.greek-added} ο υιος του [ανθρωπου]{.greek-abbr} ερχεται[24:44]{.aside}

τις αρα εστιν ο πιστος δουλος και φρονιμος ον κατεστησεν ο κυριος αυτου επι της θεραπειας αυτου του διδοναι αυτοις την τροφην εν καιρω[24:45]{.aside}

μακαριος ο δουλος εκεινος ον ελθων ο κυριος αυτου ευρησει ποιουντα ουτως[24:46]{.aside}

αμην λεγω υμιν οτι επι [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις υπαρχουσιν αυτου καταστησει αυτον[24:47]{.aside}

εαν δε ειπη ο κακος δουλος εκεινος εν τη καρδια αυτου χρονιζει ο κυριος μου [του]{.greek-added} ελθειν[24:48]{.aside}

και αρξηται τυπτειν τους συνδουλους [αυτου]{.greek-added} εσθιειν [δε]{.greek-omitted} [τε]{.greek-added} και πινειν μετα των μεθυοντων[24:49]{.aside}

ηξει ο κυριος του δουλου εκεινου εν [η]{.greek-added} [αν]{.greek-added} [ημερα]{.greek-omitted} [ημεραν]{.greek-added} η ου προσδοκα και [εν]{.greek-omitted} ωρα η ου γινωσκει[24:50]{.aside}

και διχοτομησει αυτον και το μερος αυτου μετα των υποκριτων θησει εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[24:51]{.aside}

### Chapter 25

τοτε ομοιωθησεται η βασιλεια των [ουρανων]{.greek-abbr} δεκα παρθενοις αιτινες λαβουσαι τας λαμπαδας αυτων εξηλθον εις απαντησιν του νυμφιου[25:1]{.aside}

πεντε δε [ησαν]{.greek-omitted} εξ αυτων [ησαν]{.greek-added} [φρο]{.greek-added} [φρονιμοι]{.greek-omitted} [νιμοι]{.greek-added} και αι πεντε μωραι[25:2]{.aside}

αιτινες μωραι λαβουσαι τας λαμπαδας αυτων ουκ ελαβον μεθ εαυτων ελαιον[25:3]{.aside}

αι δε φρονιμοι ελαβον ελαιον εν τοις αγγειοις αυτων μετα των λαμπαδων αυτων[25:4]{.aside}

χρονιζοντος δε του νυμφιου ενυσταξαν πασαι και εκαθευδον[25:5]{.aside}

μεσης δε νυκτος κραυγη γεγονεν ιδου ο νυμφιος ερχεται [εξερχεσθε]{.greek-omitted} [εξερχεσθαι]{.greek-added} εις απαντησιν αυτου[25:6]{.aside}

τοτε ηγερθησαν πασαι αι παρθενοι εκειναι και εκοσμησαν τας λαμπαδας αυτων[25:7]{.aside}

αι δε μωραι ταις φρονιμοις ειπον δοτε ημιν εκ του ελαιου υμων οτι αι λαμπαδες ημων σβεννυνται[25:8]{.aside}

απεκριθησαν δε αι φρονιμοι λεγουσαι μηποτε ουκ αρκεση ημιν και υμιν [πορευεσθε]{.greek-omitted} [πορευεσθαι]{.greek-added} δε μαλλον προς τους πωλουντας και αγορασατε εαυταις[25:9]{.aside}

απερχομενων δε αυτων αγορασαι ηλθεν ο νυμφιος και αι ετοιμοι εισηλθον μετ αυτου εις τους γαμους και εκλεισθη η θυρα[25:10]{.aside}

υστερον δε ερχονται και αι λοιπαι παρθενοι λεγουσαι [κυριε]{.greek-abbr} [κυριε]{.greek-abbr} ανοιξον ημιν[25:11]{.aside}

ο δε αποκριθεις ειπεν [αμην]{.greek-added} αμην λεγω υμιν ουκ οιδα υμας[25:12]{.aside}

γρηγορειτε ουν οτι ουκ οιδατε την [ημεραν]{.greek-omitted} [ωραν]{.greek-added} ουδε την [ωραν]{.greek-omitted} [ημεραν]{.greek-added} εν η ο υιος του [ανθρωπου]{.greek-abbr} ερχεται[25:13]{.aside}

ωσπερ γαρ [ανθρωπος]{.greek-abbr} αποδημων εκαλεσεν τους ιδιους δουλους και παρεδωκεν αυτοις τα υπαρχοντα αυτου[25:14]{.aside}

και ω μεν εδωκεν πεντε ταλαντα ω δε δυο ω δε εν εκαστω κατα την ιδιαν δυναμιν και απεδημησεν ευθεως[25:15]{.aside}

πορευθεις δε ο τα πεντε ταλαντα λαβων ειργασατο εν αυτοις και εποιησεν αλλα πεντε ταλαντα[25:16]{.aside}

ωσαυτως και ο τα δυο εκερδησεν και αυτος αλλα δυο[25:17]{.aside}

ο δε το εν λαβων απελθων ωρυξεν εν τη γη και απεκρυψεν το αργυριον του κυριου αυτου[25:18]{.aside}

μετα δε χρονον πολυν ερχεται ο κυριος των δουλων εκεινων και συναιρει μετ αυτων λογον[25:19]{.aside}

και προσελθων ο τα πεντε ταλαντα λαβων προσηνεγκεν αλλα πεντε ταλαντα λεγων [κυριε]{.greek-abbr} πεντε ταλαντα μοι παρεδωκας ιδε αλλα πεντε ταλαντα εκερδησα επ αυτοις[25:20]{.aside}

εφη δε [αυτω]{.greek-omitted} ο κυριος αυτου ευ δουλε αγαθε και πιστε επι ολιγα [ης]{.greek-omitted} [εις]{.greek-added} πιστος επι πολλων σε καταστησω εισελθε εις την χαραν του κυριου σου[25:21]{.aside}

προσελθων δε και ο τα δυο ταλαντα λαβων ειπεν [κυριε]{.greek-abbr} δυο ταλαντα μοι παρεδωκας ιδε αλλα δυο ταλαντα εκερδησα επ αυτοις[25:22]{.aside}

εφη αυτω ο [κυριος]{.greek-abbr} αυτου ευ δουλε αγαθε και πιστε επι ολιγα [ης]{.greek-omitted} [εις]{.greek-added} πιστος επι πολλων σε καταστησω εισελθε εις την χαραν του κυριου σου[25:23]{.aside}

προσελθων δε και ο το εν ταλαντον [ειληφως]{.greek-omitted} [λαβων]{.greek-added} ειπεν [κυριε]{.greek-abbr} εγνων σε οτι σκληρος ει [ανθρωπος]{.greek-abbr} θεριζων οπου ουκ εσπειρας και συναγων οθεν ου διεσκορπισας[25:24]{.aside}

και φοβηθεις απελθων εκρυψα το ταλαντον σου εν τη γη [ιδε]{.greek-omitted} [ιδου]{.greek-added} εχεις το σον[25:25]{.aside}

αποκριθεις δε ο κυριος αυτου ειπεν αυτω πονηρε δουλε και οκνηρε ηδεις οτι θεριζω οπου ουκ εσπειρα και [συναγω]{.greek-omitted} [συναγων]{.greek-added} οθεν ου διεσκορπισα[25:26]{.aside}

εδει ουν σε βαλειν το αργυριον μου τοις τραπεζιταις και ελθων εγω εκομισαμην αν το εμον συν τοκω[25:27]{.aside}

αρατε ουν απ αυτου το ταλαντον και δοτε τω εχοντι τα δεκα ταλαντα[25:28]{.aside}

τω γαρ εχοντι παντι δοθησεται και περισσευθησεται απο δε του μη εχοντος και ο [δοκει]{.greek-added} [εχει]{.greek-omitted} [εχειν]{.greek-added} αρθησεται απ αυτου[25:29]{.aside}

και τον αχρειον δουλον [εκεινον]{.greek-added} εκβαλετε εις το σκοτος το εξωτερον εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[25:30]{.aside}

οταν [δε]{.greek-omitted} ελθη ο υιος του [ανθρωπου]{.greek-abbr} εν τη δοξη αυτου και παντες οι αγιοι αγγελοι [αυτου]{.greek-added} μετ αυτου τοτε [καθισει]{.greek-omitted} [καθηση]{.greek-added} επι θρονου δοξης αυτου[25:31]{.aside}

και [συναχθησεται]{.greek-omitted} [συναχθησονται]{.greek-added} εμπροσθεν αυτου παντα τα εθνη και αφοριει αυτους απ αλληλων ωσπερ ο ποιμην αφοριζει τα προβατα απο των εριφων[25:32]{.aside}

και στησει τα μεν προβατα εκ δεξιων αυτου τα δε [εριφια]{.greek-omitted} [εριφεια]{.greek-added} εξ ευωνυμων[25:33]{.aside}

τοτε ερει ο βασιλευς τοις εκ δεξιων αυτου δευτε οι [ευλογημενοι]{.greek-omitted} [ευλογημενη]{.greek-added} του [πατρος]{.greek-abbr} μου κληρονομησατε την ητοιμασμενην υμιν βασιλειαν απο καταβολης κοσμου[25:34]{.aside}

επεινασα γαρ και εδωκατε μοι φαγειν εδιψησα και εποτισατε με ξενος ημην και συνηγαγετε με[25:35]{.aside}

γυμνος και περιεβαλετε με ησθενησα και [επεσκεψασθε]{.greek-omitted} [επεσκεψασθαι]{.greek-added} με εν φυλακη ημην και ηλθετε προς με[25:36]{.aside}

τοτε αποκριθησον[ται]{.greek-supplied} αυτω οι δικαιοι λεγοντες [κυριε]{.greek-abbr} ποτε σε ειδομεν πεινωντα και εθρεψαμεν η διψωντα και εποτισαμεν[25:37]{.aside}

ποτε δε σε ειδομεν ξενον και [συνηγαγομεν]{.greek-omitted} [συνηγαγωμεν]{.greek-added} η γυμνον και περιεβαλομεν[25:38]{.aside}

ποτε δε σε ειδομεν ασθενη η εν φυλακη και ηλθομεν προς σε[25:39]{.aside}

και αποκριθεις ο βασιλευς ερει αυτοις αμην λεγω υμιν εφ οσον εποιησατε ενι τουτων των αδελφων μου των ελαχιστων εμοι εποιησατε[25:40]{.aside}

τοτε ερει και τοις εξ ευωνυμων [πορευεσθε]{.greek-omitted} [πορευεσθαι]{.greek-added} απ εμου οι κατηραμενοι εις το πυρ το αιωνιον το ητοιμασμενον τω διαβολω και τοις αγγελοις αυτου[25:41]{.aside}

επεινασα γαρ και ουκ εδωκατε μοι φαγειν εδιψησα και ουκ εποτισατε με[25:42]{.aside}

ξενος ημην και ου συνηγαγετε με γυμνος και ου περιεβαλετε με ασθενης και εν φυλακη και ουκ [επεσκεψασθε]{.greek-omitted} [ηλθετε]{.greek-added} [προς]{.greek-added} με[25:43]{.aside}

τοτε αποκριθησονται και αυτοι λεγοντες [κυριε]{.greek-abbr} ποτε σε ειδομεν πεινωντα η διψωντα η ξενον η γυμνον η ασθενη η εν φυλακη και ου διηκονησαμεν σοι[25:44]{.aside}

τοτε αποκριθησεται αυτοις λεγων αμην λεγω υμιν εφ οσον ουκ εποιησατε ενι τουτων των ελαχιστων ουδε εμοι εποιησατε[25:45]{.aside}

και απελευσονται ουτοι εις κολασιν αιωνιον οι δε δικαιοι εις ζωην αιωνιον[25:46]{.aside}

### Chapter 26

και εγενετο οτε ετελεσεν ο [ιησους]{.greek-abbr} παντας τους λογους τουτους ειπεν τοις μαθηταις αυτου[26:1]{.aside}

οιδατε οτι μετα δυο ημερας το πασχα γινεται και ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοται εις το [σταυρωθηναι]{.greek-abbr}[26:2]{.aside}

τοτε συνηχθησαν οι αρχιερεις [και]{.greek-omitted} [οι]{.greek-omitted} [γραμματεις]{.greek-omitted} και οι πρεσβυτεροι του λαου εις την αυλην του αρχιερεως του λεγομενου καιαφα[26:3]{.aside}

και συνεβουλευσαντο ινα τον [ιησουν]{.greek-abbr} δολω κρατησωσιν και αποκτεινωσιν[26:4]{.aside}

ελεγον δε μη εν τη εορτη ινα μη [θορυβος]{.greek-omitted} [θωρυβος]{.greek-added} γενηται εν τω λαω[26:5]{.aside}

του δε [ιησου]{.greek-abbr} γενομενου εν βηθανια εν οικια σιμωνος του λεπρου[26:6]{.aside}

προσηλθεν αυτω γυνη αλαβαστρον μυρου εχουσα βαρυτιμου και κατεχεεν επι την κεφαλην αυτου ανακειμενου[26:7]{.aside}

ιδοντες δε οι μαθηται αυτου ηγανακτησαν λεγοντες εις τι η απωλεια αυτη[26:8]{.aside}

ηδυνατο γαρ τουτο το μυρον πραθηναι πολλου και δοθηναι πτωχοις[26:9]{.aside}

γνους δε ο [ιησους]{.greek-abbr} ειπεν αυτοις τι κοπους παρεχετε τη γυναικι εργον γαρ καλον ειργασατο εις εμε[26:10]{.aside}

[παντοτε]{.greek-omitted} [γαρ]{.greek-omitted} τους πτωχους [γαρ]{.greek-added} [παντοτε]{.greek-added} εχετε μεθ [εαυτων]{.greek-omitted} [εαυτον]{.greek-added} εμε δε ου παντοτε εχετε[26:11]{.aside}

βαλουσα γαρ αυτη το μυρον τουτο επι του σωματος μου προς το ενταφιασαι με εποιησεν[26:12]{.aside}

αμην λεγω υμιν οπου εαν κηρυχθη το ευαγγελιον τουτο εν ολω τω κοσμω λαληθησεται και ο εποιησεν αυτη εις μνημοσυνον αυτης[26:13]{.aside}

τοτε πορευθεις εις των δωδεκα ο λεγομενος ιουδας ισκαριωτης προς τους αρχιερεις[26:14]{.aside}

ειπεν τι θελετε μοι δουναι [καγω]{.greek-omitted} [και]{.greek-added} [εγω]{.greek-added} υμιν παραδωσω αυτον οι δε εστησαν αυτω τριακοντα αργυρια[26:15]{.aside}

και απο τοτε [εζητει]{.greek-omitted} [εζητη]{.greek-added} ευκαιριαν ινα αυτον παραδω[26:16]{.aside}

τη δε πρωτη των αζυμων προσηλθον οι μαθηται τω [ιησου]{.greek-abbr} λεγοντες αυτω που θελεις ετοιμασομεν σοι φαγειν το πασχα[26:17]{.aside}

ο δε ειπεν υπαγετε εις την πολιν προς τον δεινα και ειπατε αυτω ο διδασκαλος λεγει ο καιρος μου εγγυς εστιν προς σε ποιω το πασχα μετα των μαθητων μου[26:18]{.aside}

και εποιησαν οι μαθηται ως [συνεταξεν]{.greek-omitted} [προσεταξεν]{.greek-added} αυτοις ο [ιησους]{.greek-abbr} και ητοιμασαν το πασχα[26:19]{.aside}

οψιας δε γενομενης ανεκειτο μετα των δωδεκα[26:20]{.aside}

και εσθιοντων αυτων ειπεν αμην λεγω υμιν οτι εις εξ υμων παραδωσει με[26:21]{.aside}

και λυπουμενοι σφοδρα ηρξαντο λεγειν αυτω εκαστος αυτων μητι εγω ειμι [κυριε]{.greek-abbr}[26:22]{.aside}

ο δε αποκριθεις ειπεν ο εμβαψας μετ εμου εν τω τρυβλιω την χειρα ουτος με παραδωσει[26:23]{.aside}

[και]{.greek-added} ο μεν υιος του [ανθρωπου]{.greek-abbr} υπαγει καθως γεγραπται περι αυτου ουαι δε τω [ανθρωπω]{.greek-abbr} εκεινω δι ου ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοται καλον ην αυτω ει ουκ εγεννηθη ο [ανθρωπος]{.greek-abbr} εκεινος[26:24]{.aside}

αποκριθεις δε ιουδας ο παραδιδους αυτον ειπεν μητι εγω ειμι ραββι λεγει αυτω συ ειπας[26:25]{.aside}

εσθιοντων δε αυτων λαβων ο [ιησους]{.greek-abbr} τον αρτον και ευχαριστησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και εδιδου τοις μαθηταις [και]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτου]{.greek-added} [λεγων]{.greek-added} [λαβετε]{.greek-omitted} [λαβε]{.greek-added} [τε]{.greek-added} φαγετε τουτο [εστιν]{.greek-omitted} [εστι]{.greek-added} το σωμα μου[26:26]{.aside}

και λαβων το ποτηριον και ευχαριστησας εδωκεν αυτοις [λεγων]{.greek-omitted} [ειπων]{.greek-added} πιετε εξ αυτου παντες[26:27]{.aside}

τουτο γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} το αιμα μου το της καινης διαθηκης το περι πολλων [εκχυνομενον]{.greek-omitted} [εκχυννομενον]{.greek-added} εις αφεσιν αμαρτιων[26:28]{.aside}

λεγω δε υμιν οτι ου μη πιω απ αρτι εκ τουτου του γεννηματος της αμπελου εως της ημερας εκεινης οταν αυτο πινω μεθ υμων καινον εν τη βασιλεια του [πατρος]{.greek-abbr} μου[26:29]{.aside}

και υμνησαντες εξηλθον εις το ορος των ελαιων[26:30]{.aside}

τοτε λεγει αυτοις ο [ιησους]{.greek-abbr} παντες υμεις σκανδαλισθησεσθε εν εμοι εν τη νυκτι ταυτη γεγραπται γαρ παταξω τον ποιμενα και διασκορπισθησεται τα προβατα της ποιμνης[26:31]{.aside}

μετα δε το εγερθηναι με προαξω υμας εις την γαλιλαιαν[26:32]{.aside}

αποκριθεις δε ο πετρος ειπεν αυτω ει παντες σκανδαλισθησονται εν σοι εγω [δε]{.greek-omitted} ουδεποτε σκανδαλισθησομαι[26:33]{.aside}

εφη αυτω ο [ιησους]{.greek-abbr} αμην λεγω σοι οτι εν ταυτη τη νυκτι πριν αλεκτορα φωνησαι τρις απαρνηση με[26:34]{.aside}

λεγει αυτω ο πετρος καν δεη με συν σοι αποθανειν ου μη σε [απαρνησωμαι]{.greek-omitted} [απαρνησομαι]{.greek-added} ομοιως δε και παντες οι μαθηται ειπον[26:35]{.aside}

τοτε ερχεται [μετ]{.greek-omitted} [μετα]{.greek-added} [αυτων]{.greek-omitted} [των]{.greek-added} [μαθητων]{.greek-added} [αυτου]{.greek-added} ο [ιησους]{.greek-abbr} εις χωριον λεγομενον γεθσημανη και λεγει τοις μαθηταις καθισατε αυτου εως ου απελθων προσευξωμαι εκει[26:36]{.aside}

και παραλαβων τον πετρον και τους δυο υιους ζεβεδαιου ηρξατο λυπεισθαι και αδημονειν[26:37]{.aside}

τοτε λεγει αυτοις ο [ιησους]{.greek-abbr} περιλυπος εστιν η ψυχη μου εως θανατου μεινατε ωδε και γρηγορειτε μετ εμου[26:38]{.aside}

και προσελθων μικρον επεσεν επι προσωπον αυτου προσευχομενος και λεγων [πατερ]{.greek-abbr} μου ει δυνατον εστιν παρελθετω απ εμου το ποτηριον τουτο πλην ουχ ως εγω θελω αλλ ως συ[26:39]{.aside}

και ερχεται προς τους μαθητας και ευρισκει αυτους καθευδοντας και λεγει τω πετρω ουτως ουκ ισχυσατε μιαν ωραν [γρηγορησαι]{.greek-omitted} [αγρυπνησαι]{.greek-added} μετ εμου[26:40]{.aside}

γρηγορειτε και [προσευχεσθε]{.greek-omitted} [προσευχεσθαι]{.greek-added} ινα μη εισελθητε εις πειρασμον το μεν [πνευμα]{.greek-abbr} προθυμον η δε σαρξ ασθενης[26:41]{.aside}

παλιν εκ δευτερου απελθων προσηυξατο λεγων [πατερ]{.greek-abbr} μου ει ου δυναται τουτο το ποτηριον παρελθειν απ εμου εαν μη αυτο πιω γενηθητ[ω]{.unclear} τ[ο]{.unclear} θελημα σου[26:42]{.aside}

και ελθων [ευρι]{.unclear}σκει αυτους παλιν καθευδοντας ησαν γαρ αυτων οι οφθαλμοι βεβαρημενοι[26:43]{.aside}

και αφεις αυτους απελθων παλιν προσηυξατο εκ τριτου τον αυτον λογον ειπων[26:44]{.aside}

τοτε ερχεται προ[ς]{.unclear} τους μαθητας αυτου και λεγει αυτοις [καθευδετε]{.greek-omitted} [καθευδεσθαι]{.greek-added} το λοιπον και αναπαυεσθε ιδου ηγγικεν η ωρα και ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοται εις χειρας αμαρτωλων[26:45]{.aside}

[εγειρεσθε]{.greek-omitted} [εγειρεσθαι]{.greek-added} αγωμεν [εντευθεν]{.greek-added} ιδου ηγγικεν [ο]{.greek-omitted} [ος]{.greek-added} παραδιδους με[26:46]{.aside}

και ετι αυτου λαλουντος ιδου ιουδας εις των δωδεκα ηλθεν και μετ αυτου οχλος πολυς μετα μαχαιρων και ξυλων απο των αρχιερε[ω]{.unclear}ν και πρεσβυτερων του λαου[26:47]{.aside}

ο δε παραδιδους αυτον εδωκεν αυτοις σημειον λεγων ον [αν]{.greek-omitted} [εαν]{.greek-added} φιλησω αυτος εστιν κρατησατε αυτον[26:48]{.aside}

και ευθεως προσελθων τω [ιησου]{.greek-abbr} ειπεν χαιρε ραββι και κατεφιλησεν αυτον[26:49]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω εταιρε εφ [ω]{.greek-omitted} [ο]{.greek-added} παρει τοτε προσελθοντες επεβαλον τας χειρας επι τον [ιησουν]{.greek-abbr} και εκρατησαν αυτον[26:50]{.aside}

και ιδου εις των μετα [ιησου]{.greek-abbr} εκτεινας την χειρα απεσπασεν την μαχαιραν αυτου και παταξας τον δουλον του αρχιερεως αφειλεν αυτου το ωτιον[26:51]{.aside}

τοτε λεγει αυτω ο [ιησους]{.greek-abbr} απ[ο]{.unclear}στρεψον [σου]{.greek-omitted} την μαχαιραν εις τον τοπον αυτης παντες γαρ οι λαβοντες μαχαιραν εν μαχαιρα αποθανουνται[26:52]{.aside}

η δοκεις οτι ου δυναμαι αρτι παρακαλεσαι τον [πατερα]{.greek-abbr} μου και παραστησει μοι πλειους η δωδεκα λεγεωνας αγγελων[26:53]{.aside}

πως ουν πληρωθωσιν αι γραφαι οτι ουτως δει γενεσθαι[26:54]{.aside}

εν εκεινη τη ωρα ειπεν ο [ιησους]{.greek-abbr} τοις οχλοις ως επι ληστην εξηλθετε μετα μαχαιρων και ξυλων συλλαβειν με καθ ημεραν προς υμας εκαθεζομην διδασκων εν τω ιερω και ουκ εκρατησατε με[26:55]{.aside}

τουτο δε ολον γεγονεν ινα πληρωθωσιν αι γραφαι των προφητων τοτε οι μαθηται παντες [αφεγ[ε]{.unclear}νες]{.greek-added} [αφεντες]{.corr} αυτον εφυγον[26:56]{.aside}

οι δε κρατησαντες τον [ιησουν]{.greek-abbr} απηγαγον προς καιαφαν τον αρχιερεα οπου οι γραμματεις και οι πρεσβυτεροι συνηχθησαν[26:57]{.aside}

ο δε πετρος ηκολουθει αυτω απο μακροθεν εως της αυλης του αρχιερεως και εισελθων εσω [εκαθητο]{.greek-omitted} [εκαθητω]{.greek-added} μετα των υπηρετων ιδειν το τελος[26:58]{.aside}

οι δε αρχιερεις και οι πρεσβυτεροι και το συνεδριον ολον εζητουν ψευδομαρτυριαν κατα του [ιησου]{.greek-abbr} οπως [θανατωσωσιν]{.greek-omitted} [θανατωσουσιν]{.greek-added} αυτον[26:59]{.aside}

και ουχ ευρον και πολλων ψευδομαρτυρων προσελθοντων ουχ ευρον [υστερον]{.greek-added} [δε]{.greek-added} [προσελθοντες]{.greek-added} [δυο]{.greek-added} [ψευδομαρτυρες]{.greek-added}[26:60]{.aside}

[υστερον]{.greek-omitted} [δε]{.greek-omitted} [προσελθοντες]{.greek-omitted} [δυο]{.greek-omitted} [ψευδομαρτυρες]{.greek-omitted} ειπον ουτος εφη δυναμαι καταλυσαι τον ναον του [θεου]{.greek-abbr} και δια τριων ημερων οικοδομησαι αυτον[26:61]{.aside}

και αναστας ο αρχιερευς ειπεν αυτω ουδεν αποκρινη τι ουτοι σου καταμαρτυρουσιν[26:62]{.aside}

ο δε [ιησους]{.greek-abbr} εσιωπα και αποκριθεις ο αρχιερευς ειπεν αυτω εξορκιζω σε κατα του [θεου]{.greek-abbr} του ζωντος ινα ημιν ειπης ει συ ει ο [χριστος]{.greek-abbr} ο υιος του [θεου]{.greek-abbr}[26:63]{.aside}

λεγει αυτω ο [ιησους]{.greek-abbr} συ ειπας πλην λεγω υμιν απ αρτι [οψεσθε]{.greek-omitted} [οψεσθαι]{.greek-added} τον υιον του [ανθρωπου]{.greek-abbr} καθημενον εκ δεξιων της δυναμεως και ερχομενον επι των νεφελων του [ουρανου]{.greek-abbr}[26:64]{.aside}

τοτε ο αρχιερευς [διερρηξεν]{.greek-omitted} [διερρηξε]{.greek-added} τα ιματια αυτου λεγων οτι εβλασφημησεν τι ετι χρειαν εχομεν μαρτυρων ιδε νυν ηκουσατε την βλασφημιαν αυτου[26:65]{.aside}

τι υμιν δοκει οι δε αποκριθεντες ειπον [οτι]{.greek-added} ενοχος θανατου εστιν[26:66]{.aside}

τοτε ενεπτυσαν εις το προσωπον αυτου και εκολαφισαν αυτον οι δε ερραπισαν[26:67]{.aside}

λεγοντες προφητευσον ημιν [χριστε]{.greek-abbr} τις εστιν ο παισας σε[26:68]{.aside}

ο δε πετρος εξω εκαθητο εν τη αυλη και προσηλθεν αυτω μια παιδισκη λεγουσα και συ ησθα μετα [ιησου]{.greek-abbr} του γαλιλαιου[26:69]{.aside}

ο δε ηρνησατο εμπροσθεν αυτων παντων λεγων [οτι]{.greek-added} ουκ οιδα τι λεγεις[26:70]{.aside}

εξελθοντα δε αυτον εις τον πυλωνα ειδεν αυτον αλλη και λεγει αυτοις εκει και ουτος ην μετα [ιησου]{.greek-abbr} του ναζωραιου[26:71]{.aside}

και παλιν ηρνησατο μεθ ορκου οτι ουκ οιδα τον [ανθρωπον]{.greek-abbr}[26:72]{.aside}

μετα μικρον δε προσελθοντες οι εστωτες ειπον τω πετρω αληθως και συ εξ αυτων ει και γαρ η λαλια σου δηλον σε ποιει[26:73]{.aside}

τοτε ηρξατο καταθεματιζειν και ομνυειν οτι ουκ οιδα τον [ανθρωπον]{.greek-abbr} και ευθεως αλεκτωρ εφωνησεν[26:74]{.aside}

και εμνησθη ο [πε]{.greek-added} [πετρος]{.greek-omitted} [τρος]{.greek-added} του ρηματος του [ιησου]{.greek-abbr} ειρηκοτος αυτω οτι πριν αλεκτορα φωνησαι τρις απαρνηση με και εξελθων εξω [εκλαυσεν]{.greek-omitted} [εκλαυσε]{.greek-added} πικρως[26:75]{.aside}

### Chapter 27

πρωιας δε γενομενης συμβουλιον ελαβον παντες οι αρχιερεις και οι πρεσβυτεροι του λαου κατα του [ιησου]{.greek-abbr} ωστε θανατωσαι αυτον[27:1]{.aside}

και δησαντες αυτον απηγαγον και παρεδωκαν [αυτον]{.greek-omitted} ποντιω πιλατω τω ηγεμονι[27:2]{.aside}

τοτε ιδων ιουδας ο παραδιδους αυτον οτι κατεκριθη μεταμεληθεις [απεστρεψεν]{.greek-omitted} [απεστρεψε]{.greek-added} τα τριακοντα αργυρια τοις [αρχιερευσιν]{.greek-omitted} [αρχιερευσι]{.greek-added} και [τοις]{.greek-omitted} πρεσβυτεροις[27:3]{.aside}

λεγων ημαρτον παραδους αιμα αθωον οι δε ειπον τι προς [ημας]{.greek-omitted} [υμας]{.greek-added} συ οψει[27:4]{.aside}

και ριψας τα αργυρια εν τω ναω ανεχωρησεν και απελθων απηγξατο[27:5]{.aside}

οι δε αρχιερεις λαβοντες τα αργυρια ειπον ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} βαλειν αυτα εις τον [κορβαναν]{.greek-omitted} [κορβοναν]{.greek-added} επει τιμη αιματος εστιν[27:6]{.aside}

συμβουλιον δε λαβοντες ηγορασαν εξ αυτων τον αγρον του κεραμεως εις ταφην τοις ξενοις[27:7]{.aside}

διο εκληθη ο αγρος εκεινος αγρος αιματος εως της σημερον[27:8]{.aside}

τοτε επληρωθη το ρηθεν δια ιερεμιου του προφητου λεγοντος και ελαβον τα τριακοντα αργυρια την τιμην του τετιμημενου ον ετιμησαντο απο υιων [ισραηλ]{.greek-abbr}[27:9]{.aside}

και εδωκαν αυτα εις τον αγρον του κεραμεως καθα [συνεταξεν]{.greek-omitted} [συνεταξε]{.greek-added} μοι [κυριος]{.greek-abbr}[27:10]{.aside}

ο δε [ιησους]{.greek-abbr} εστη εμπροσθεν του ηγεμονος και επηρωτησεν αυτον ο ηγεμων λεγων συ ει ο βασιλευς των ιουδαιων ο δε [ιησους]{.greek-abbr} εφη αυτω συ λεγεις[27:11]{.aside}

και εν τω κατηγορεισθαι αυτον υπο των αρχιερεων και [των]{.greek-omitted} πρεσβυτερων ουδεν απεκρινατο[27:12]{.aside}

τοτε λεγει αυτω ο πιλατος ουκ ακουεις ποσα σου καταμαρτυρουσιν[27:13]{.aside}

και ουκ απεκριθη αυτω προς ουδε εν ρημα ωστε θαυμαζειν τον ηγεμονα λιαν[27:14]{.aside}

κατα δε εορτην ειωθει ο ηγεμων απολυειν ενα τω οχλω δεσμιον ον ηθελον[27:15]{.aside}

ειχον δε τοτε δεσμιον επισημον λεγομενον βαραββαν[27:16]{.aside}

συνηγμενων ουν αυτων ειπεν αυτοις ο πιλατος τινα θελετε απολυσω υμιν βαραββαν η [ιησουν]{.greek-abbr} τον λεγομενον [χριστον]{.greek-abbr}[27:17]{.aside}

ηδει γαρ οτι δια φθονον παρεδωκαν αυτον[27:18]{.aside}

καθημενου δε αυτου επι του βηματος απεστειλεν προς αυτον η γυνη αυτου λεγουσα μηδεν σοι και τω δικαιω εκεινω πολλα γαρ επαθον σημερον κατ οναρ δι αυτον[27:19]{.aside}

οι δε αρχιερεις και οι πρεσβυτεροι επεισαν τους οχλους ινα αιτησωνται τον βαραββαν τον δε [ιησουν]{.greek-abbr} απολεσωσιν[27:20]{.aside}

αποκριθεις δε ο ηγεμων ειπεν αυτοις τινα θελετε απο των δυο απολυσω υμιν οι δε ειπον βαραββαν[27:21]{.aside}

λεγει αυτοις ο πιλατος τι ουν ποιησω [ιησουν]{.greek-abbr} τον λεγομενον [χριστον]{.greek-abbr} λεγουσιν αυτω παντες [σταυρωθητω]{.greek-abbr}[27:22]{.aside}

ο δε ηγεμων εφη τι γαρ κακον εποιησεν οι δε περισσως εκραζον λεγοντες [σταυρωθητω]{.greek-abbr}[27:23]{.aside}

ιδων δε ο πιλατος οτι ουδεν ωφελει αλλα μαλλον θορυβος γινεται λαβων υδωρ απενιψατο τας χειρας απεναντι του οχλου λεγων αθωος ειμι απο του αιματος του δικαιου τουτου υμεις [οψεσθαι]{.greek-added} [οψεσθε]{.corr}[27:24]{.aside}

και αποκριθεις πας ο [λαος]{.greek-omitted} [οχλος]{.greek-added} ειπεν το αιμα αυτου εφ ημας και επι τα τεκνα ημων[27:25]{.aside}

τοτε απελυσεν αυτοις τον βαραββαν τον δε [ιησουν]{.greek-abbr} [φραγελλωσας]{.greek-omitted} [φραγελωσας]{.greek-added} [πα]{.greek-added} [παρεδωκεν]{.greek-omitted} [ρεδωκεν]{.greek-added} ινα [σταυρωθη]{.greek-abbr}[27:26]{.aside}

τοτε οι στρατιωται του ηγεμονος παραλαβοντες τον [ιησουν]{.greek-abbr} εις το πραιτωριον συνηγαγον επ αυτον ολην την σπειραν[27:27]{.aside}

και εκδυσαντες αυτον περιεθηκαν αυτω χλαμυδα κοκκινην[27:28]{.aside}

και πλεξαντες στεφανον εξ ακανθων επεθηκαν επι την κεφαλην αυτου και καλαμον επι την δεξιαν αυτου και γονυπετησαντες εμπροσθεν αυτου ενεπαιζον αυτω λεγοντες χαιρε ο βασιλευς των ιουδαιων[27:29]{.aside}

και εμπτυσαντες εις αυτον ελαβον τον καλαμον και ετυπτον εις την κεφαλην αυτου[27:30]{.aside}

και οτε ενεπαιξαν αυτω εξεδυσαν αυτον την χλαμυδα και ενεδυσαν αυτον τα ιματια αυτου και απηγαγον αυτον εις το [σταυρωσαι]{.greek-abbr}[27:31]{.aside}

εξερχομενοι δε ευρον [ανθρωπον]{.greek-abbr} κυρηναιον ονοματι σιμωνα τουτον ηγγαρευσαν ινα αρη τον [σταυρον]{.greek-abbr} αυτου[27:32]{.aside}

και ελθοντες εις τοπον λεγομενον γολγοθα [ο]{.greek-omitted} [ος]{.greek-added} [εστιν]{.greek-omitted} [εστι]{.greek-added} λεγομενος κρανιου τοπος[27:33]{.aside}

εδωκαν αυτω πιειν οξος μετα χολης μεμιγμενον και γευσαμενος ουκ ηθελεν πιειν[27:34]{.aside}

[σταυρωσαντες]{.greek-abbr} δε αυτον διεμερισαντο τα ιματια αυτου βαλλοντες κληρον[27:35]{.aside}

και καθημενοι ετηρουν αυτον εκει[27:36]{.aside}

κ[αι]{.greek-supplied} [επεθηκαν]{.greek-supplied} [ε]{.greek-supplied}[πανω]{.unclear} [της]{.greek-supplied} [κ]{.unclear}εφαλης [αυτου]{.greek-omitted} [την]{.greek-omitted} [αυτην]{.greek-added} αιτιαν αυτου γεγραμμενην ουτος εστιν [ιησους]{.greek-omitted} ο βασιλευς των ιουδαιων[27:37]{.aside}

τοτε [σταυρουνται]{.greek-abbr} συν αυτω δυο λησται εις εκ δεξιων και εις εξ ευωνυμων[27:38]{.aside}

οι δε παραπορευομενοι εβλασφημουν αυτον κινουντες τας κεφαλας αυτων[27:39]{.aside}

και λεγοντες ο καταλυων τον ναον και εν τρισιν ημεραις οικοδομων σωσον σεαυτον ει υιος ει του [θεου]{.greek-abbr} καταβηθι απο του [σταυρου]{.greek-abbr}[27:40]{.aside}

ομοιως δε και οι αρχιερεις εμπαιζοντες μετα των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} και πρεσβυτερων και φαρισαιων ελεγον[27:41]{.aside}

αλλους εσωσεν εαυτον ου [δυναται]{.greek-omitted} [δυνατε]{.greek-added} σωσαι ει βασιλευς [ισραηλ]{.greek-abbr} [εστιν]{.greek-omitted} [εστι]{.greek-added} καταβατω νυν απο του [σταυρου]{.greek-abbr} και [πιστευσομεν]{.greek-omitted} [πιστευσωμεν]{.greek-added} επ [αυτω]{.greek-omitted} [αυτον]{.greek-added}[27:42]{.aside}

πεποιθεν επι τον [θεον]{.greek-abbr} ρυσασθω [νυν]{.greek-omitted} αυτον ει θελει αυτον ειπεν γαρ οτι [θεου]{.greek-abbr} ειμι υιος[27:43]{.aside}

το δ [αυτο]{.greek-omitted} [αυτω]{.greek-added} και οι λησται οι [συσταυρωθεντες]{.greek-abbr} αυτω ωνειδιζον αυτον[27:44]{.aside}

απο δε εκτης ωρας σκοτος εγενετο επι πασαν την γην εως ωρας [ενατης]{.greek-omitted} [εννατης]{.greek-added}[27:45]{.aside}

περι δε την [ενατην]{.greek-omitted} [εννατην]{.greek-added} ωραν ανεβοησεν ο [ιησους]{.greek-abbr} φωνη μεγαλη λεγων ηλι ηλι λιμα σαβαχθανι τουτ [εστιν]{.greek-omitted} [εστι]{.greek-added} θεε μου θεε μου [ινα]{.greek-omitted} [ινατι]{.greek-added} [τι]{.greek-omitted} με εγκατελιπες[27:46]{.aside}

τινες δε των εκει εστωτων ακουσαντες ελεγον οτι ηλιαν [φωνει]{.greek-omitted} [φωνη]{.greek-added} ουτος[27:47]{.aside}

και ευθεως δραμων εις εξ αυτων και λαβων [σπογγον]{.greek-omitted} [σπονγον]{.greek-added} πλησας τε οξους και περιθεις καλαμω εποτιζεν αυτον[27:48]{.aside}

οι δε λοιποι ελεγον αφες ιδωμεν ει ερχεται ηλιας [σωσων]{.greek-omitted} [σωσον]{.greek-added} αυτον[27:49]{.aside}

ο δε [ιησους]{.greek-abbr} παλιν κραξας φωνη μεγαλη [αφηκεν]{.greek-omitted} [αφηκε]{.greek-added} το [πνευμα]{.greek-abbr}[27:50]{.aside}

και ιδου το καταπετασμα του ναου εσχισθη εις δυο απο ανωθεν εως κατω και η γη [εσεισθη]{.greek-omitted} [εσισθη]{.greek-added} και αι πετραι εσχισθησαν[27:51]{.aside}

και τα μνημεια [ανεωχθησαν]{.greek-omitted} [ηνεωχθησαν]{.greek-added} και πολλα σωματα των κεκοιμημενων αγιων ηγερθη[27:52]{.aside}

και εξελθοντες εκ των μνημειων μετα την εγερσιν αυτου εισηλθον εις την [αγιαν]{.greek-omitted} [αγιον]{.greek-added} πολιν και ενεφανισθησαν πολλοις[27:53]{.aside}

ο δε εκατονταρχος και οι μετ αυτου τηρουντες τον [ιησουν]{.greek-abbr} ιδοντες τον [σεισμον]{.greek-omitted} [σισμον]{.greek-added} και τα γενομενα εφοβηθησαν σφοδρα λεγοντες αληθως [θεου]{.greek-abbr} υιος ην ουτος[27:54]{.aside}

ησαν δε εκει γυναικες πολλαι απο μακροθεν θεωρουσαι αιτινες ηκολουθησαν τω [ιησου]{.greek-abbr} απο της γαλιλαιας διακονουσαι αυτω[27:55]{.aside}

εν αις ην μαρια η [μαγδαληνη]{.greek-omitted} [μαγδα]{.greek-added} [ληνη]{.greek-added} και μαρια η του ιακωβου και ιωση [μητηρ]{.greek-abbr} και η [μητηρ]{.greek-abbr} των υιων ζεβεδαιου[27:56]{.aside}

οψιας δε γενομενης ηλθεν [ανθρωπος]{.greek-abbr} πλουσιος απο αριμαθαιας τουνομα ιωσηφ ος και αυτος [εμαθητευσεν]{.greek-omitted} [εμαθητευσε]{.greek-added} τω [ιησου]{.greek-abbr}[27:57]{.aside}

ουτος προσελθων τω πιλατω ητησατο το σωμα του [ιησου]{.greek-abbr} τοτε ο πιλατος εκελευσεν αποδοθηναι το σωμα[27:58]{.aside}

και λαβων το σωμα [ο]{.greek-omitted} ιωσηφ ενετυλιξεν [αυτο]{.greek-omitted} [αυτω]{.greek-added} σινδονι καθαρα[27:59]{.aside}

και εθηκεν αυτο εν τω καινω αυτου μνημειω ο [ελατομησεν]{.greek-omitted} [ελατομισεν]{.greek-added} [εκ]{.greek-added} [εν]{.greek-omitted} [τη]{.greek-omitted} [πετρα]{.greek-omitted} [πετρας]{.greek-added} και προσκυλισας λιθον μεγαν τη θυρα του μνημειου απηλθεν[27:60]{.aside}

ην δε εκει μαρια η [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} και η αλλη μαρια καθημεναι απεναντι του ταφου[27:61]{.aside}

τη δε επαυριον ητις [εστιν]{.greek-omitted} [εστι]{.greek-added} μετα την παρασκευην συνηχθησαν οι αρχιερεις και οι φαρισαιοι [προς]{.corr} [πιλατον]{.corr}[27:62]{.aside}

λεγοντες [κυριε]{.greek-abbr} εμνησθημεν οτι εκεινος ο πλανος ειπεν ετι ζων μετα τρεις ημερας εγειρομαι[27:63]{.aside}

κελευσον ουν ασφαλισθηναι τον ταφον εως [της]{.corr} τριτης ημερας μηποτε ελθοντες οι μαθηται αυτου [νυκτος]{.greek-omitted} κλεψωσιν αυτον [νυκτος]{.greek-added} και [ειπωσιν]{.greek-omitted} [ειπωσι]{.greek-added} τω λαω ηγερθη απο των νεκρων και εσται η εσχατη πλανη χειρ[ων]{.unclear} της πρωτης[27:64]{.aside}

εφη δε αυτοις ο πιλατος εχετε [κουστωδιαν]{.greek-omitted} [κουστοδιαν]{.greek-added} υπαγετε [ασφαλισασθε]{.greek-omitted} [ασφαλισασθαι]{.greek-added} ως οιδατε[27:65]{.aside}

οι δε πορευθεντες ησφαλισαντο τον ταφον σφραγισαντες τον λιθον μετα της κουστωδιας[27:66]{.aside}

### Chapter 28

οψε [δε]{.greek-omitted} σαββατων τη [επιφωσκουση]{.greek-omitted} [επιφασκουση]{.greek-added} εις μιαν σαββατων ηλθεν μαρια η μαγδαληνη και η αλλη μαρια θεωρησαι τον ταφον[28:1]{.aside}

και ιδου σεισμος εγενετο μεγας αγγελος γαρ [κυριου]{.greek-abbr} καταβας εξ [ουρανου]{.greek-abbr} προσελθων απεκυλισεν τον λιθον απο της θυρας [του]{.greek-added} [μνημειου]{.greek-added} και εκαθητο επανω αυτου[28:2]{.aside}

ην δε η ιδεα αυτου [ως]{.greek-omitted} [ωσει]{.greek-added} αστραπη και το ενδυμα αυτου λευκον ωσει χιων[28:3]{.aside}

απο δε του φοβου αυτου εσεισθησαν οι τηρουντες και εγενοντο ωσει νεκροι[28:4]{.aside}

αποκριθεις δε ο αγγελος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} ταις [γυναιξιν]{.greek-omitted} [γυναιξι]{.greek-added} μη [φοβεισθε]{.greek-omitted} [φοβησθε]{.greek-added} υμεις οιδα γαρ οτι [ιησουν]{.greek-abbr} τον [εσταυρωμενον]{.greek-abbr} ζητειτε[28:5]{.aside}

ουκ εστιν ωδε ηγερθη γαρ καθως ειπεν δευτε ιδετε τον τοπον οπου εκειτο ο [κυριος]{.greek-abbr}[28:6]{.aside}

κα[ι]{.greek-supplied} ταχυ πορευθεισαι ειπατε τοις μαθηταις αυτ[ο]{.unclear}υ οτι ηγερθη απο των νεκρων και ιδου προαγει υμας εις την γαλιλαιαν εκει αυτον [οψεσθε]{.greek-omitted} [οψεσθαι]{.greek-added} ιδου ειπον υμιν[28:7]{.aside}

και εξελθουσαι ταχυ απο του μνημειου μετα φοβου και χαρας μεγαλης εδραμον απαγγειλαι τοις μαθηταις αυτου[28:8]{.aside}

ως δε επορευοντο απαγγειλαι τοις μαθηταις αυτου και ιδου [ιησους]{.greek-abbr} απηντησεν αυταις λεγων χαιρετε αι [δε]{.greek-omitted} [δαι]{.greek-added} προσελθουσαι εκρατησαν αυτου τους ποδας και προσεκυνησαν αυτω[28:9]{.aside}

τοτε λεγει αυταις ο [ιησους]{.greek-abbr} μη φοβεισθε υπαγετε απαγγειλατε τοις αδελφοις μου ινα απελθωσιν εις την γαλιλαιαν [και]{.greek-omitted} [κακει]{.greek-added} [εκει]{.greek-omitted} με οψονται[28:10]{.aside}

πορευομενων δε αυτων ιδου τινες της κουστωδιας ελθοντες εις την πολιν απηγγειλαν τοις αρχιερευσιν απαντα τα γενομενα[28:11]{.aside}

και συναχθεντες μετα των πρεσβυτερων συμβουλιον τε λαβοντες αργυρια ικανα εδωκαν τοις στρατιωταις[28:12]{.aside}

λεγοντες ειπατε οτι οι μαθηται αυτου νυκτος ελθοντες εκλεψαν αυτον ημων κοιμωμενων[28:13]{.aside}

και εαν ακουσθη τουτο επι του ηγεμονος ημεις πεισομεν αυτον και υμας αμεριμνους ποιησομεν[28:14]{.aside}

οι δε λαβοντες τα αργυρια εποιησαν ως εδιδαχθησαν και διεφημισθη ο λογος ουτος παρα ιουδαιοις μεχρι της σημερον[28:15]{.aside}

οι δε ενδεκα μαθηται [επορευθησαν]{.greek-omitted} [επορευθεισαν]{.greek-added} εις την γαλιλαιαν εις το ορος ου εταξατο αυτοις ο [ιησους]{.greek-abbr}[28:16]{.aside}

και ιδοντες αυτον προσεκυνησαν [αυτω]{.greek-omitted} [αυτον]{.greek-added} οι δε εδιστασαν[28:17]{.aside}

και προσελθων ο [ιησους]{.greek-abbr} ελαλησεν αυτοις λεγων εδοθη μοι πασα εξουσια εν [ουρανω]{.greek-abbr} και επι γης[28:18]{.aside}

πορευθεντες μαθητευσατε παντα τα εθνη βαπτιζοντες αυτους εις το ονομα του [πατρος]{.greek-abbr} και του υιου και του αγιου [πνευματος]{.greek-abbr}[28:19]{.aside}

διδασκοντες αυτους τηρειν παντα οσα ενετειλαμην υμιν και ιδου εγω μεθ υμων ειμι πασας τας ημερας εως της συντελειας του αιωνος αμην[28:20]{.aside}

