---
title: "Collation of Byz^RP^ vs 32847 (2847)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 2847 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=32847).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 2847                                   	| λογος                              	|
| 2847 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 2847 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 2847               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 2847                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 2847 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 2847                                                     	| [―]{.gap}                        	|
:::

## Revelation

### Chapter 1

αποκαλυψις [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} ην εδωκεν αυτω ο [θεος]{.greek-abbr} δειξαι τοις δουλοις αυτου α δει γενεσθαι εν [ταχει]{.greek-omitted} [ταχη]{.greek-added} και εσημανεν [αποστειλας]{.greek-omitted} [αποστηλας]{.greek-added} δια του αγγελου αυτου τω δουλω αυτου ιωαννη[1:1]{.aside}

ος [εμαρτυρησεν]{.greek-omitted} [εμαρτυρισεν]{.greek-added} τον λογον του [θεου]{.greek-abbr} και την μαρτυριαν [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} οσα ειδεν[1:2]{.aside}

[μ]{.unclear}ακαριος ο [αναγινωσκων]{.greek-omitted} [αναγινωσκον]{.greek-added} και [οι]{.greek-omitted} ακουοντες τους λογους της [προφητειας]{.greek-omitted} [προφητιας]{.greek-added} και [τηρουντες]{.greek-omitted} [τυρουντες]{.greek-added} τα [εν]{.greek-omitted} [αυτη]{.greek-omitted} [ε]{.greek-added} [αυτοις]{.greek-added} γεγραμμενα ο γαρ καιρος εγγυς[1:3]{.aside}

ιωαννης ταις επτα εκκλησιαις ταις εν τη ασια χαρις [υμιν]{.greek-omitted} [ημιν]{.greek-added} και [ειρηνη]{.greek-omitted} [ηρυνη]{.greek-added} απο [θεου]{.greek-abbr} ο ων και ο ην και ο ερχομενος και απο των επτα [πνευματων]{.greek-abbr} α [ενωπιον]{.greek-omitted} [ενοπιον]{.greek-added} του θρονου αυτου[1:4]{.aside}

και απο [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} ο μαρτυς ο πιστος ο [πρωτοτοκος]{.greek-omitted} [προτοτοκος]{.greek-added} των νεκρων και ο αρχων των βασιλεων της γης τω [αγαπωντι]{.greek-omitted} [αγαποντι]{.greek-added} ημας και λουσαντι ημας απο των αμαρτιων ημων εν τω αιματι αυτου[1:5]{.aside}

και εποιησεν ημας βασιλειαν ιερεις τω [θεω]{.greek-abbr} και [πατρι]{.greek-abbr} αυτου αυτω η δοξα και [το]{.greek-omitted} [τω]{.greek-added} κρατος εις τους αιωνας των αιωνων αμην[1:6]{.aside}

ιδου ερχεται μετα των νεφελων και [οψεται]{.greek-omitted} [οψετε]{.greek-added} αυτον πας οφθαλμος και [οιτινες]{.greek-omitted} [ητιναις]{.greek-added} αυτον εξεκεντησαν και κοψονται επ αυτον πασαι αι φυλαι της γης ναι αμην[1:7]{.aside}

εγω ειμι το [αλφα]{.greek-omitted} [ἄλφα]{.greek-added} και το [ω]{.greek-abbr} λεγει [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο ων και ο ην και ο ερχομενος ο παντοκρατωρ[1:8]{.aside}

εγω ιωαννης ο αδελφος [υμων]{.greek-omitted} [ημων]{.greek-added} και κοινωνος εν τη θλιψει και βασιλεια και υπομονη εν [χριστω]{.greek-abbr} [ιησου]{.greek-abbr} εγενομην εν τη [νησω]{.greek-omitted} [νυσω]{.greek-added} τη καλουμενη πατμω δια τον λογον του [θεου]{.greek-abbr} και δια την μαρτυριαν [ιησου]{.greek-abbr} [χριστου]{.greek-abbr}[1:9]{.aside}

εγενομην εν [πνευματι]{.greek-abbr} εν τη κυριακη ημερα και ηκουσα φωνην οπισω μου μεγαλην ως σαλπιγγος[1:10]{.aside}

λεγουσης ο [βλεπεις]{.greek-omitted} [βλεπης]{.greek-added} γραψον εις βιβλιον και πεμψον ταις [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} [εκκλησιαις]{.greek-omitted} [εκκλισιαις]{.greek-added} εις εφεσον και εις [σμυρναν]{.greek-omitted} [σμηρναν]{.greek-added} και εις περγαμον και εις [θυατειρα]{.greek-omitted} [θυαπυρα]{.greek-added} και εις σαρδεις και εις [φιλαδελφειαν]{.greek-omitted} [φιλαδελφιαν]{.greek-added} και εις [λαοδικειαν]{.greek-omitted} [λαοδικιαν]{.greek-added}[1:11]{.aside}

και εκει [επεστρεψα]{.greek-omitted} [επεστραψα]{.greek-added} [βλεπειν]{.greek-omitted} [βλεπην]{.greek-added} την φωνην ητις [ελαλει]{.greek-omitted} [ελαλη]{.greek-added} μετ εμου και επιστρεψας [ειδον]{.greek-omitted} [οιδον]{.greek-added} [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} λυχνιας χρυσας[1:12]{.aside}

και εν μεσω [των]{.greek-omitted} [επτα]{.greek-omitted} [τον]{.greek-added} [[ζ]{.greek-abbr}]{.greek-added} λυχνιων ομοιον [υιω]{.greek-omitted} [[υιον]{.greek-abbr}]{.greek-added} [ανθρωπου]{.greek-abbr} [ενδεδυμενον]{.greek-omitted} [ενδεδημενον]{.greek-added} [ποδηρη]{.greek-omitted} [ποδηροι]{.greek-added} και [περιεζωσμενον]{.greek-omitted} [περιεζοσμενον]{.greek-added} προς τοις μαστοις ζωνην [χρυσην]{.greek-omitted} [χρησην]{.greek-added}[1:13]{.aside}

η δε [κεφαλη]{.greek-omitted} [καιφαλει]{.greek-added} αυτου και [ετρυχες]{.greek-added} [λευκε]{.greek-added} [αι]{.greek-omitted} [και]{.greek-added} [ος]{.greek-added} [τριχες]{.greek-omitted} [λευκαι]{.greek-omitted} [ως]{.greek-omitted} εριον λευκον [ως]{.greek-omitted} [ος]{.greek-added} [χιων]{.greek-omitted} [χιον]{.greek-added} και οι οφθαλμοι αυτου [ως]{.greek-omitted} [ος]{.greek-added} φλοξ πυρος[1:14]{.aside}

και οι ποδες αυτου ομοιοι [χαλκολιβανω]{.greek-omitted} [χαλκολυβανω]{.greek-added} [ως]{.greek-omitted} [ος]{.greek-added} εν καμινω [πεπυρωμενοι]{.greek-omitted} [πεπυρομενη]{.greek-added} και η φωνη αυτου [ως]{.greek-omitted} [ος]{.greek-added} φωνη υδατων πολλων[1:15]{.aside}

και [εχων]{.greek-omitted} [εχον]{.greek-added} εν τη δεξια αυτου χειρι αστερας [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} και εκ του στοματος αυτου ρομφαια διστομος οξεια εκπορευομενη και [η]{.greek-omitted} [ι]{.greek-added} οψις αυτου [ως]{.greek-omitted} [ος]{.greek-added} ο ηλιος [φαινει]{.greek-omitted} [φαινη]{.greek-added} εν τη δυναμει αυτου[1:16]{.aside}

και οτε [ειδον]{.greek-omitted} [οιδον]{.greek-added} αυτον επεσα προς τους ποδας αυτου [ως]{.greek-omitted} [ος]{.greek-added} νεκρος και [εθηκεν]{.greek-omitted} [εθυκεν]{.greek-added} την δεξιαν αυτου επ εμε λεγων μη φοβου εγω ειμι ο [πρωτος]{.greek-omitted} [προτος]{.greek-added} και ο εσχατος[1:17]{.aside}

και ο ζων και εγενομην νεκρος και ιδου ζων [ειμι]{.greek-omitted} [ειμει]{.greek-added} εις τους αιωνας των αιωνων αμην και εχω τας [κλεις]{.greek-omitted} [κλιδας]{.greek-added} του θανατου και του αδου[1:18]{.aside}

γραψον ουν α [ειδες]{.greek-omitted} [ειδαις]{.greek-added} και α εισιν και α μελλει γινεσθαι μετα ταυτα[1:19]{.aside}

το [μυστηριον]{.greek-omitted} [μυστυριον]{.greek-added} των επτα αστερων ων ειδες επι της δεξιας μου και τας [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} λυχνιας τας [χρυσας]{.greek-omitted} [χρισας]{.greek-added} οι επτα αστερες αγγελοι των επτα εκκλησιων εισιν και αι λυχνιαι αι επτα επτα εκκλησιαι [εισιν]{.greek-omitted} [ησιν]{.greek-added}[1:20]{.aside}

### Chapter 2

τω αγγελω της εν εφεσω εκκλησιας γραψον ταδε λεγει ο κρατων τους επτα αστερας εν τη δεξια αυτου ο περιπατων εν μεσω [των]{.greek-omitted} [τον]{.greek-added} επτα λυχνιων των [χρυσων]{.greek-omitted} [χρησον]{.greek-added}[2:1]{.aside}

οιδα τα εργα σου και τον κοπον σου και την υπομονην σου και οτι [ου]{.greek-omitted} [ουκ]{.greek-added} [η]{.greek-added} δυνη βαστασαι κακους και [επειρασας]{.greek-omitted} [επυρασας]{.greek-added} τους λεγοντας εαυτους αποστολους [ειναι]{.greek-omitted} [οιναι]{.greek-added} και ουκ εισιν και ευρες αυτους [ψευδεις]{.greek-omitted} [ψευδης]{.greek-added}[2:2]{.aside}

και υπομονην [εχεις]{.greek-omitted} [εχης]{.greek-added} και εβαστασας δια το ονομα μου και [ουκ]{.greek-omitted} [οὐ]{.greek-added} [εκοπιασας]{.greek-omitted} [κεκοπίασας]{.greek-added}[2:3]{.aside}

[αλλα]{.greek-omitted} [αλα]{.greek-added} εχω κατα σου οτι την αγαπην σου την [πρωτην]{.greek-omitted} [προτην]{.greek-added} [αφηκας]{.greek-omitted} [αφικας]{.greek-added}[2:4]{.aside}

μνημονευε ουν ποθεν πεπτωκας και μετανοησον και τα πρωτα εργα ποιησον ει δε [μη]{.greek-omitted} [ερχομαι]{.greek-omitted} [σοι]{.greek-omitted} [ταχυ]{.greek-omitted} [και]{.greek-omitted} [κινησω]{.greek-omitted} [την]{.greek-omitted} [λυχνιαν]{.greek-omitted} [σου]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [τοπου]{.greek-omitted} [αυτης]{.greek-omitted} [εαν]{.greek-omitted} [μη]{.greek-omitted} [μετανοησης]{.greek-omitted}[2:5]{.aside}

[μηδεν]{.greek-omitted} [φοβου]{.greek-omitted} [α]{.greek-omitted} [μελλεις]{.greek-omitted} [παθειν]{.greek-omitted} [ιδου]{.greek-omitted} [δη]{.greek-omitted} [μελλει]{.greek-omitted} [βαλειν]{.greek-omitted} [ο]{.greek-omitted} [διαβολος]{.greek-omitted} [εξ]{.greek-omitted} [υμων]{.greek-omitted} [εις]{.greek-omitted} [φυλακην]{.greek-omitted} [ινα]{.greek-omitted} [πειρασθητε]{.greek-omitted} [και]{.greek-omitted} [εξετε]{.greek-omitted} [θλιψιν]{.greek-omitted} [ημερων]{.greek-omitted} [δεκα]{.greek-omitted} γινου πιστος αχρι θανατου και δωσω σοι τον στεφανον της ζωης[2:10]{.aside}

ο [εχων]{.greek-omitted} [εχον]{.greek-added} ους ακουσατω [τι]{.corr} [το]{.greek-omitted} [τω]{.greek-added} [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις ο [νικων]{.greek-omitted} [νεικων]{.greek-added} ου μη [αδικηθη]{.greek-omitted} [αδικηθι]{.greek-added} εκ του θανατου του δευτερου[2:11]{.aside}

και τω αγγελω της εν περγαμω εκκλησιας [γραψον]{.greek-omitted} [γραψων]{.greek-added} ταδε λεγει ο εχων την ρομφαιαν την [διστομων]{.greek-added} [διστομον]{.corr} την οξειαν[2:12]{.aside}

οιδα τα εργα σου και που κατοικεις οπου ο θρονος του σατανα και [κρατεις]{.greek-omitted} [κρατοις]{.greek-added} [το]{.greek-omitted} [τω]{.greek-added} ονομα μου και ουκ ηρνησω την [πιστιν]{.greek-omitted} [πιστην]{.greek-added} μου εν ταις ημεραις [εν]{.greek-omitted} αις [αντιπας]{.greek-omitted} [ἀντίπας]{.greek-added} ο [μαρτυς]{.greek-omitted} [μαρτις]{.greek-added} μου ο πιστος ος απεκτανθη παρ [υμιν]{.greek-omitted} [ημιν]{.greek-added} οπου ο σατανας [κατοικει]{.greek-omitted} [κατοικοι]{.greek-added}[2:13]{.aside}

[αλλ]{.greek-omitted} [αλα]{.greek-added} εχω κατα σου ολιγα οτι [εχεις]{.greek-omitted} [εχις]{.greek-added} εκει κρατουντας την διδαχην βαλααμ ος εδιδαξεν τον βαλακ βαλειν [σκανδαλον]{.greek-omitted} [σκανδαλων]{.greek-added} [ενωπιον]{.greek-omitted} [ενοπιον]{.greek-added} των υιων [ισραηλ]{.greek-abbr} και φαγειν [ειδωλοθυτα]{.greek-omitted} [οιδωλωθητα]{.greek-added} και [πορνευσαι]{.greek-omitted} [πορνευσ[ες]{.unclear}]{.greek-added}[2:14]{.aside}

[ουτως]{.greek-omitted} [ουτος]{.greek-added} εχεις και συ κρατουντας την διδαχην [των]{.greek-omitted} [νικολαιτων]{.greek-omitted} [νικολαιητων]{.greek-added} ομοιως[2:15]{.aside}

μετανοησον ουν [ει]{.greek-omitted} [δε]{.greek-omitted} [μη]{.greek-omitted} [οι]{.greek-added} [δαι]{.greek-added} [μοι]{.greek-added} ερχομαι σοι [ταχυ]{.greek-omitted} [ταχει]{.greek-added} και πολεμησω μετ αυτων εν τη ρομφαια του στοματος μου[2:16]{.aside}

ο εχων ους ακουσατω τι [το]{.greek-omitted} [τω]{.greek-added} [πνευμα]{.greek-abbr} λεγει ταις [εκκλησιαις]{.greek-omitted} [εκκλισιαις]{.greek-added} τω νικωντι δωσω αυτω του [μαννα]{.greek-omitted} [μανα]{.greek-added} του [κεκρυμμενου]{.greek-omitted} [κεκριμενου]{.greek-added} και δωσω [αυτω]{.greek-omitted} [αυτον]{.greek-added} [ψηφον]{.greek-omitted} [ψιφον]{.greek-added} λευκην και επι την [ψηφον]{.greek-omitted} [ψιφον]{.greek-added} ονομα [καινον]{.greek-omitted} [κενον]{.greek-added} γεγραμμενον ο ουδεις οιδεν [ει]{.greek-omitted} [οι]{.greek-added} μη ο λαμβανων[2:17]{.aside}

και τω αγγελω της εν [θυατειροις]{.greek-omitted} [θυατυρι]{.greek-added} εκκλησιας γραψον ταδε λεγει ο υιος του [θεου]{.greek-abbr} ο εχων τους οφθαλμους αυτου [ως]{.greek-omitted} [ος]{.greek-added} φλογα πυρος και οι ποδες αυτου ομοιοι [χαλκολιβανω]{.greek-omitted} [χαλκολυβανω]{.greek-added}[2:18]{.aside}

οιδα σου τα εργα και την αγαπην και την [πιστιν]{.greek-omitted} [πιστην]{.greek-added} και την [διακονιαν]{.greek-omitted} [διακονειαν]{.greek-added} και την υπομονην [σου]{.corr} και τα εργα σου τα εσχατα [πλειονα]{.greek-omitted} [πλειωνα]{.greek-added} των πρωτων[2:19]{.aside}

[αλλ]{.greek-omitted} [αλλα]{.greek-added} εχω κατα σου οτι αφεις την γυναικα σου ιεζαβελ η λεγει εαυτην [προφητιν]{.greek-omitted} [προφητι]{.greek-added} και διδασκει και πλανα τους εμους δουλους πορνευσαι και φαγειν [ειδωλοθυτα]{.greek-omitted} [οιδολωθητα]{.greek-added}[2:20]{.aside}

και εδωκα [οι]{.greek-added} αυτη [χρονον]{.greek-omitted} [χρονω]{.greek-added} ινα [μετανοηση]{.greek-omitted} [μετανοησαι]{.greek-added} και ου [θελει]{.greek-omitted} [θελι]{.greek-added} μετανοησαι εκ της πορνειας αυτης[2:21]{.aside}

ιδου [βαλλω]{.greek-omitted} [βαλω]{.greek-added} αυτην εις κλινην και τους [μοιχευοντας]{.greek-omitted} [μηχευοντας]{.greek-added} μετ αυτης εις θλιψιν μεγαλην εαν μη μετανοησωσιν εκ των εργων αυτης[2:22]{.aside}

και τα τεκνα αυτης αποκτενω εν θανατω και γνωσονται πασαι [αι]{.greek-omitted} [ε]{.greek-added} [εκκλησιαι]{.greek-omitted} [αικλησιαι]{.greek-added} οτι εγω ειμι ο ερευνων νεφρους και καρδιας και [δωσω]{.greek-omitted} [δοσω]{.greek-added} [υμιν]{.greek-omitted} [ημιν]{.greek-added} [εκαστω]{.greek-omitted} [εκαστος]{.greek-added} κατα τα εργα [υμων]{.greek-omitted} [ημων]{.greek-added}[2:23]{.aside}

[υμιν]{.greek-omitted} [ημιν]{.greek-added} [δε]{.greek-omitted} [δαι]{.greek-added} λεγω τοις λοιποις τοις εν [θυατειροις]{.greek-omitted} [θυατυροις]{.greek-added} οσοι ουκ εχουσιν την διδαχην ταυτην οιτινες ουκ εγνωσαν τα [βαθεα]{.greek-omitted} [βαθέα]{.greek-added} του σατανα [ως]{.greek-omitted} [ος]{.greek-added} λεγουσιν ου [βαλλω]{.greek-omitted} [βαλω]{.greek-added} εφ υμας αλλο βαρος[2:24]{.aside}

[πλην]{.greek-omitted} [ο]{.greek-omitted} [πλειν]{.greek-added} [ω]{.greek-added} εχετε κρατησατε [αχρι]{.greek-omitted} [αχρις]{.greek-added} ου αν [ηξω]{.greek-omitted} [οιξω]{.greek-added}[2:25]{.aside}

και ο [νικων]{.greek-omitted} [νεικων]{.greek-added} και ο [τηρων]{.greek-omitted} [τυρων]{.greek-added} αχρι τελους τα εργα μου δωσω αυτω εξουσιαν επι των εθνων[2:26]{.aside}

και ποιμανει αυτους εν ραβδω σιδηρα [ως]{.greek-omitted} [ος]{.greek-added} τα σκευη τα κεραμικα συντριβησεται [ως]{.greek-omitted} [καγω]{.greek-omitted} [ειληφα]{.greek-omitted} [παρα]{.greek-omitted} [του]{.greek-omitted} [πατρος]{.greek-omitted} [μου]{.greek-omitted}[2:27]{.aside}

[ος]{.greek-added} [καγω]{.greek-added} [ειληφα]{.greek-added} [παρα]{.greek-added} [του]{.greek-added} [[πατρος]{.greek-abbr}]{.greek-added} [μου]{.greek-added} και δωσω [αυτω]{.greek-omitted} [αυτον]{.greek-added} τον αστερα [τον]{.greek-omitted} [των]{.greek-added} πρωινον[2:28]{.aside}

ο εχων ους ακουσατω τι [το]{.greek-omitted} [τω]{.greek-added} [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[2:29]{.aside}

### Chapter 3

και τω αγγελω της εν σαρδεσιν εκκλησιας γραψον ταδε λεγει ο εχων τα επτα [πνευματα]{.greek-abbr} του [θεου]{.greek-abbr} και τους επτα αστερας οιδα σου τα εργα οτι ονομα εχεις [οτι]{.greek-omitted} [ζης]{.greek-omitted} [και]{.greek-added} [ζεις]{.greek-added} και νεκρος ει[3:1]{.aside}

γινου γρηγορων και [στηρισον]{.greek-omitted} [στηρισων]{.greek-added} τα λοιπα α [εμελλες]{.greek-omitted} [ειμελλες]{.greek-added} [αποβαλλειν]{.greek-omitted} [αποβαλειν]{.greek-added} ου γαρ [ευρηκα]{.greek-omitted} [ευρικα]{.greek-added} σου τα εργα πεπληρωμενα [ενωπιον]{.greek-omitted} [ενοπιον]{.greek-added} του [θεου]{.greek-abbr} μου[3:2]{.aside}

μνημονευε ουν πως ειληφας [και]{.greek-omitted} [ηκουσας]{.greek-omitted} [και]{.greek-omitted} [τηρει]{.greek-omitted} και μετανοησον εαν ουν μη γρηγορησης ηξω επι σε [ως]{.greek-omitted} [ος]{.greek-added} κλεπτης και ου μη γνως ποιαν ωραν ηξω επι [σε]{.greek-omitted} [σαι]{.greek-added}[3:3]{.aside}

αλλ ολιγα εχεις ονοματα εν σαρδεσιν α ουκ εμολυναν τα ιματια αυτων και [περιπαροισουσιν]{.greek-added} [περιπατησουσιν]{.greek-omitted} [[περιπατοισουσιν]{.corr}]{.greek-added} μετ εμου εν [λευκοις]{.greek-omitted} [λευκις]{.greek-added} οτι [αξιοι]{.greek-omitted} [αξοι]{.greek-added} [οι]{.greek-added} εισιν[3:4]{.aside}

ο [νικων]{.greek-omitted} [νεικων]{.greek-added} ουτος περιβαλειται εν [ιματιοις]{.greek-omitted} [ιματοι]{.greek-added} [εις]{.greek-added} [λευκοις]{.greek-omitted} [λευκις]{.greek-added} και ου μη εξαλειψω [το]{.greek-omitted} [τω]{.greek-added} ονομα αυτου εκ της βιβλου της ζωης και ομολογησω [το]{.greek-omitted} [τω]{.greek-added} ονομα αυτου [ενωπιον]{.greek-omitted} [ενοπιον]{.greek-added} του [πατρος]{.greek-abbr} μου και [ενωπιον]{.greek-omitted} [ενοπιον]{.greek-added} των αγγελων αυτου[3:5]{.aside}

ο εχων ους ακουσατω τι [το]{.greek-omitted} [τω]{.greek-added} [πνευμα]{.greek-abbr} [λεγει]{.greek-omitted} [λελεγει]{.greek-added} ταις εκκλησιαις[3:6]{.aside}

και τω αγγελω της εν [φιλαδελφεια]{.greek-omitted} [φιλαδελφια]{.greek-added} εκκλησιας γραψον ταδε λεγει ο αγιος ο αληθινος ο εχων την [κλειν]{.greek-omitted} [κλην]{.greek-added} του [δαυιδ]{.greek-abbr} [ο]{.greek-added} [ανειγων]{.greek-added} [και]{.greek-added} [ουδεις]{.greek-added} [και]{.greek-added} [ουδεις]{.greek-added} [κλησει]{.greek-added} [αυτην]{.greek-added} [οι]{.greek-added} [μει]{.greek-added} ο ανοιγων και ουδεις [κλεισει]{.greek-omitted} [αυτην]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [ο]{.greek-omitted} [ανοιγων]{.greek-omitted} [και]{.greek-omitted} [ουδεις]{.greek-omitted} [ανοιξει]{.greek-omitted} [ανοιξοι]{.greek-added}[3:7]{.aside}

οιδα σου τα εργα [ιδου]{.greek-omitted} [οιδου]{.greek-added} δεδωκα [ενωπιον]{.greek-omitted} [ενοπιον]{.greek-added} σου θυραν ανεωγμενην ην ουδεις [δυναται]{.greek-omitted} [δυνατε]{.greek-added} κλεισαι αυτην οτι [μι]{.greek-added} [μικραν]{.greek-omitted} [κραν]{.greek-added} εχεις δυναμιν και [ετηρησας]{.greek-omitted} [ετοιρησας]{.greek-added} μου τον λογον και ουκ ηρνησω [το]{.greek-omitted} [τω]{.greek-added} ονομα μου[3:8]{.aside}

ιδου [διδωμι]{.greek-omitted} [διδωμοι]{.greek-added} εκ της συναγωγης του σατανα των [λεγοντων]{.greek-omitted} [λεγωντων]{.greek-added} εαυτους ιουδαιους [ειναι]{.greek-omitted} [οιναι]{.greek-added} και ουκ [εισιν]{.greek-omitted} [ησιν]{.greek-added} αλλα [ψευδονται]{.greek-omitted} [ψευδοντε]{.greek-added} ιδου ποιησω αυτους ινα ηξωσιν και προσκυνησωσιν ενωπιον των ποδων [σου]{.corr} και γνωσιν οτι ηγαπησα σε[3:9]{.aside}

οτι [ετυρης]{.greek-added} [ετηρησας]{.greek-omitted} [[ετυρησας]{.corr}]{.greek-added} τον λογον της υπομονης μου καγω σε [τηρησω]{.greek-omitted} [τηροισω]{.greek-added} εκ της ωρας του πειρασμου της μελλουσης ερχεσθαι επι της οικουμενης ολης πειρασαι τους κατοικουντας επι της γης[3:10]{.aside}

ερχομαι [ταχυ]{.greek-omitted} [κρατει]{.greek-omitted} [ταχει]{.greek-added} [κρατη]{.greek-added} ο εχεις ινα μηδεις λαβη τον στεφανον σου[3:11]{.aside}

ο [νικων]{.greek-omitted} [νεικων]{.greek-added} ποιησω αυτον στυλον εν τω ναω του [θεου]{.greek-abbr} μου και εξω ου μη [εξελθη]{.greek-omitted} [εξελθω]{.greek-added} ετι και [καψω]{.greek-added} [γραψω]{.corr} επ [αυτον]{.greek-omitted} [αυτων]{.greek-added} το ονομα του [θεου]{.greek-abbr} μου και το ονομα της [πολεως]{.greek-omitted} [πολεος]{.greek-added} του [θεου]{.greek-abbr} μου της [καινης]{.greek-omitted} [κενης]{.greek-added} [ιερουσαλημ]{.greek-abbr} η καταβαινει [εκ]{.greek-omitted} [απο]{.greek-added} του [ουρανου]{.greek-abbr} [απο]{.corr} του [θεου]{.greek-abbr} μου και το ονομα [μου]{.greek-omitted} το [καινον]{.greek-omitted} [κενον]{.greek-added}[3:12]{.aside}

ο εχων ους ακουσατω τι [το]{.greek-omitted} [τω]{.greek-added} [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[3:13]{.aside}

και τω [αγγελω]{.greek-omitted} [αγγελλω]{.greek-added} της εν [λαοδικεια]{.greek-omitted} [λαωδικια]{.greek-added} [οι]{.greek-added} εκκλησιας γραψον ταδε λεγει ο αμην ο [μαρτυς]{.greek-omitted} [μαρτις]{.greek-added} ο πιστος και αληθινος η [αρχη]{.greek-omitted} [αρχι]{.greek-added} της κτισεως του [θεου]{.greek-abbr}[3:14]{.aside}

οιδα σου τα εργα οτι ουτε ψυχρος ει ουτε ζεστος [οφελον]{.greek-omitted} [οφελων]{.greek-added} [ζηστος]{.greek-added} [ψυχρος]{.corr} ης [η]{.greek-omitted} [ει]{.greek-added} ζεστος[3:15]{.aside}

[ουτως]{.greek-omitted} [ουτος]{.greek-added} οτι χλιαρος ει και ου ζεστος ουτε ψυχρος [μελλω]{.greek-omitted} [μελλο]{.greek-added} σε [εμεσαι]{.greek-omitted} [εμεσε]{.greek-added} εκ του στοματος μου[3:16]{.aside}

οτι λεγεις πλουσιος ειμι και [πεπλουτηκα]{.greek-omitted} [πεπλουτοικα]{.greek-added} και ουδενος [χρειαν]{.greek-omitted} [χριαν]{.greek-added} εχω και ουκ [οιδας]{.greek-omitted} [ειδας]{.greek-added} οτι συ ει ο [ταλαιπωρος]{.greek-omitted} [ταλαιπορος]{.greek-added} και ο [ελεεινος]{.greek-omitted} [ελεηνος]{.greek-added} και [πτωχος]{.greek-omitted} [πτοχος]{.greek-added} και τυφλος και γυμνος[3:17]{.aside}

συμβουλευω σοι [αγορασαι]{.greek-omitted} [αγωρασαι]{.greek-added} [χρυσιον]{.greek-omitted} [χρησιων]{.greek-added} παρ εμου [πεπυρωμενον]{.greek-omitted} [πεπυρομενον]{.greek-added} εκ πυρος ινα [πλουτησης]{.greek-omitted} [πλουτισις]{.greek-added} και ιματια λευκα ινα περιβαλη και μη φανερωθη [η]{.greek-omitted} [ι]{.greek-added} αισχυνη [της]{.greek-omitted} [τοις]{.greek-added} γυμνοτητος σου και [κολλυριον]{.greek-omitted} [κολυριον]{.greek-added} ινα [εγχριση]{.greek-omitted} [εγχρισι]{.greek-added} τους οφθαλμους σου ινα [βλεπης]{.greek-omitted} [βλεπις]{.greek-added}[3:18]{.aside}

εγω οσους [ε]{.greek-added} [εαν]{.greek-omitted} [φιλω]{.greek-omitted} [ελεγχω]{.greek-omitted} [και]{.greek-omitted} [παιδευω]{.greek-omitted} [ζηλωσον]{.greek-omitted} [ουν]{.greek-omitted} [και]{.greek-omitted} [μετανοησον]{.greek-omitted}[3:19]{.aside}

### Chapter 4

ομοιος [ορασει]{.greek-omitted} [λιθω]{.greek-omitted} [ιασπιδι]{.greek-omitted} [και]{.greek-omitted} [σαρδιω]{.greek-omitted} [και]{.greek-omitted} [ιρις]{.greek-omitted} [κυκλοθεν]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [ομοιως]{.greek-omitted} [ορασις]{.greek-omitted} [ωρασις]{.greek-added} σμαραγδινων[4:3]{.aside}

[και]{.greek-omitted} [κυκλοθεν]{.greek-omitted} [κυκλωθεν]{.greek-added} του θρονου [θρονοι]{.greek-omitted} [θρωνοι]{.greek-added} [[κδ]{.greek-abbr}]{.greek-added} [εικοσι]{.greek-omitted} [τεσσαρες]{.greek-omitted} και επι τους [θρονους]{.greek-omitted} [θρωνους]{.greek-added} [τους]{.greek-omitted} [τοις]{.greek-added} [[κδ]{.greek-abbr}]{.greek-added} [εικοσι]{.greek-omitted} [τεσσαρας]{.greek-omitted} [πρεσβυτερους]{.greek-omitted} [πρεσβιτερους]{.greek-added} καθημενους περιβεβλημενους εν ιματιοις [λευκοις]{.greek-omitted} [λευκις]{.greek-added} και επι τας κεφαλας [αυτων]{.greek-omitted} [αυτον]{.greek-added} στεφανους [χρυσους]{.greek-omitted} [χρησσους]{.greek-added}[4:4]{.aside}

και εκ του θρονου εκπορευονται αστραπαι και φωναι και βρονται και επτα λαμπαδες πυρος [καιομεναι]{.greek-omitted} [και]{.greek-added} [ομενε]{.greek-added} [ενωπιον]{.greek-omitted} [ενοπιον]{.greek-added} του θρονου αυτου αι εισιν επτα [πνευμα]{.greek-abbr}[τα]{.greek-abbr} του [θεου]{.greek-abbr}[4:5]{.aside}

και [ενωπιον]{.greek-omitted} [ενοπιον]{.greek-added} του θρονου [ως]{.greek-omitted} [ος]{.greek-added} θαλασσα [υαλινη]{.greek-omitted} [ομοια]{.greek-omitted} [ηλινι]{.greek-added} [ωμια]{.greek-added} [κρυσταλλω]{.greek-omitted} [κρυσταλω]{.greek-added} και εν μεσω του θρονου και κυκλω του θρονου [τεσσαρα]{.greek-omitted} [τεσαρα]{.greek-added} ζωα γεμοντα οφθαλμων εμπροσθεν και οπισθεν[4:6]{.aside}

και το [ζωον]{.greek-omitted} [ζωων]{.greek-added} το πρωτον [ομοιον]{.greek-omitted} [ομοιων]{.greek-added} [λεοντι]{.greek-omitted} [λεωντι]{.greek-added} και το δευτερον [ζωον]{.greek-omitted} [ζωων]{.greek-added} [ομοιον]{.greek-omitted} [ομοιων]{.greek-added} μοσχω και το τριτον ζωον [εχον]{.greek-omitted} [εχων]{.greek-added} προσωπον [ανθρωπου]{.greek-abbr} και το [[δ]{.greek-abbr}]{.greek-added} [τεταρτον]{.greek-omitted} [ζωον]{.greek-omitted} ομοιον αετω [πετομενω]{.greek-omitted} [πετωμενω]{.greek-added}[4:7]{.aside}

και [τα]{.greek-omitted} [τεσσαρα]{.greek-omitted} [τεσαρα]{.greek-added} ζωα εν καθ εν [εχον]{.greek-omitted} [εχοντα]{.greek-added} ανα [πτερυγας]{.greek-omitted} [πτεριγας]{.greek-added} εξ [κυκλοθεν]{.greek-omitted} [κυκλωθεν]{.greek-added} και εσωθεν γεμουσιν οφθαλμων και αναπαυσιν ουκ εχουσιν ημερας και νυκτος λεγοντες [αγιος]{.greek-added} [αγιος]{.greek-added} [αγιος]{.greek-added} [αγιος]{.greek-added} [αγιος]{.greek-added} [αγιος]{.greek-added} αγιος αγιος αγιος [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ ο ην και ο ων και ο ερχομενος[4:8]{.aside}

και οταν δωσιν τα ζωα δοξαν και τιμην και ευχαριστιαν τω καθημενω επι του θρονου τω ζωντι εις τους αιωνας των αιωνων[4:9]{.aside}

πεσουνται οι [[κδ]{.greek-abbr}]{.greek-added} [εικοσι]{.greek-omitted} [τεσσαρες]{.greek-omitted} [πρεσβυτεροι]{.greek-omitted} [πρεσβιτεροι]{.greek-added} [ενωπιον]{.greek-omitted} [ενοπιον]{.greek-added} του καθημενου επι του θρονου και [προσκυνησουσιν]{.greek-omitted} [προσκυνησουσι]{.greek-added} τω ζωντι εις τους αιωνας των αιωνων και [βαλουσιν]{.greek-omitted} [βαλοῦσιν]{.greek-added} τους στεφανους [αυτων]{.greek-omitted} [αυτον]{.greek-added} [ενωπιον]{.greek-omitted} [ενοπιον]{.greek-added} του θρονου λεγοντες[4:10]{.aside}

αξιος ει ο [κυριος]{.greek-abbr} και ο [θεος]{.greek-abbr} ημων ο αγιος λαβειν την δοξαν και την τιμην και την δυναμιν οτι συ εκτισας [παν]{.greek-added} [παντα]{.corr} και δια το θελημα σου ησαν και εκτισθησαν[4:11]{.aside}

### Chapter 5

και [ειδον]{.greek-omitted} [οιδον]{.greek-added} επι την δεξιαν του καθημενου επι του θρονου βιβλιον γεγραμμενον εσωθεν και εξωθεν [κατεσφαγισμενον]{.greek-added} [κατεσφραγισμενον]{.corr} σφραγισιν επτα[5:1]{.aside}

και [ειδον]{.greek-omitted} [οιδον]{.greek-added} αγγελον ισχυρον [κηρυσσοντα]{.greek-omitted} [κυρισσωντα]{.greek-added} εν φωνη μεγαλη [τις]{.greek-omitted} [τίς]{.greek-added} αξιος εστιν ανοιξαι το βιβλιον και λυσαι τας σφραγιδας αυτου[5:2]{.aside}

και ουδεις εδυνατο εν [τω]{.greek-omitted} [το]{.greek-added} [ουρανω]{.greek-abbr} ανω ουτε επι της γης ουτε [υποκατω]{.greek-omitted} [οιποκατω]{.greek-added} της [γης]{.greek-omitted} ανοιξαι το βιβλιον ουτε βλεπειν [αυτο]{.greek-omitted} [αυτω]{.greek-added}[5:3]{.aside}

και εγω εκλαιον [πολυ]{.greek-omitted} [πολη]{.greek-added} οτι ουδεις [αξιος]{.greek-omitted} [αξοιος]{.greek-added} ευρεθη ανοιξαι το βιβλιον ουτε [βλεπειν]{.greek-omitted} [βλαιπειν]{.greek-added} [αυτο]{.greek-omitted} [αυτω]{.greek-added}[5:4]{.aside}

και εις εκ των [πρεσβυτερων]{.greek-omitted} [πρεσβιτερων]{.greek-added} λεγει μοι μη κλαιε ιδου ενικησεν ο λεων ο εκ της φυλης ιουδα η ριζα [δαυιδ]{.greek-abbr} ο ανοιγων το βιβλιον και τας επτα σφραγιδας αυτου[5:5]{.aside}

και [ειδον]{.greek-omitted} [οιδων]{.greek-added} εν μεσω του θρονου και των [τεσσαρων]{.greek-omitted} [[δ]{.greek-abbr}]{.greek-added} [ζωων]{.greek-omitted} [ζωον]{.greek-added} και εν μεσω [των]{.greek-omitted} [τον]{.greek-added} [πρεσβυτερων]{.greek-omitted} [πρεσβιτερων]{.greek-added} [αρνιον]{.greek-omitted} [αρνιων]{.greek-added} εστηκος ως [εσφαγμενον]{.greek-omitted} [εσφαγμενων]{.greek-added} [εχον]{.greek-omitted} [εχων]{.greek-added} κερατα [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} και οφθαλμους [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} α εισιν τα [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} [πνευματα]{.greek-omitted} [[πνευμα]{.greek-abbr}]{.greek-added} [τα]{.greek-added} του [θεου]{.greek-abbr} [αποστελλομενα]{.greek-omitted} [αποστελομενα]{.greek-added} εις πασαν την γην[5:6]{.aside}

και ηλθεν και ειληφεν εκ της δεξιας του καθημενου επι του θρονου[5:7]{.aside}

και οτε ελαβεν το βιβλιον τα [τεσσαρα]{.greek-omitted} [[δ]{.greek-abbr}]{.greek-added} ζωα και οι [[κδ]{.greek-abbr}]{.greek-added} [εικοσι]{.greek-omitted} [τεσσαρες]{.greek-omitted} [πρεσβυτεροι]{.greek-omitted} [πρεσβιτεροι]{.greek-added} επεσον [ενωπιον]{.greek-omitted} [ενοπιον]{.greek-added} του αρνιου εχοντες εκαστος κιθαραν και φιαλας [χρυσας]{.greek-omitted} [χρησας]{.greek-added} γεμουσας [θυμιαματων]{.greek-omitted} [θημιαματων]{.greek-added} αι [εισιν]{.greek-omitted} [προσευχαι]{.greek-omitted} [ησιν]{.greek-added} [πρωσευχων]{.greek-added} των αγιων[5:8]{.aside}

και αδουσιν ωδην [καινην]{.greek-omitted} [κενην]{.greek-added} λεγοντες αξιος ει λαβειν το βιβλιον και ανοιξαι τας σφραγιδας αυτου οτι εσφαγης και ηγορασας τω [θεω]{.greek-abbr} ημας εν [τω]{.greek-omitted} [το]{.greek-added} αιματι σου εκ πασης [φυλης]{.greek-omitted} [φιλης]{.greek-added} και γλωσσης και λαου και εθνους[5:9]{.aside}

και εποιησας αυτους τω [θεω]{.greek-abbr} ημων βασιλεις και ιερεις και [βασιλευσουσιν]{.greek-omitted} [βασιλευουσιν]{.greek-added} επι της γης[5:10]{.aside}

και [ειδον]{.greek-omitted} [οιδον]{.greek-added} και [ηκουσα]{.greek-omitted} [οικουσα]{.greek-added} [ως]{.greek-omitted} [ος]{.greek-added} φωνην αγγελων [πολλων]{.greek-omitted} [πολων]{.greek-added} κυκλω του θρονου και των ζωων και των [πρεσβυτερων]{.greek-omitted} [πρεσβιτερων]{.greek-added} και ην ο αριθμος αυτων μυριαδες μυριαδων και [χι]{.greek-added} [χιλιαδες]{.greek-omitted} [λιαδες]{.greek-added} χιλιαδων[5:11]{.aside}

λεγοντες φωνη μεγαλη αξιον [εστιν]{.greek-omitted} [εστι]{.greek-added} το [αρνιον]{.greek-omitted} [αρνιων]{.greek-added} το εσφαγμενον λαβειν την δυναμιν και τον πλουτον και [την]{.greek-added} σοφιαν και [την]{.greek-added} [ισχυν]{.greek-omitted} [ισχην]{.greek-added} και [την]{.greek-added} τιμην και [την]{.greek-added} δοξαν και [την]{.greek-added} [ευλογιαν]{.greek-omitted} [ευλογειαν]{.greek-added}[5:12]{.aside}

και παν [κτισμα]{.greek-omitted} [κτοισμα]{.greek-added} ο εν τω [ουρανω]{.greek-abbr} και επι της γης και υποκατω της γης και επι της θαλασσης εστιν και τα εν [αυτοις]{.greek-omitted} [αυτης]{.greek-added} [παν]{.greek-added} [παντας]{.corr} ηκουσα λεγοντας τω καθημενω επι [του]{.greek-omitted} [θρονου]{.greek-omitted} [τω]{.greek-added} [θρωνω]{.greek-added} και τω αρνιω η ευλογια και η τιμη και η δοξα και το κρατος εις τους αιωνας των αιωνων αμην[5:13]{.aside}

και τα [τεσσαρα]{.greek-omitted} [[δ]{.greek-abbr}]{.greek-added} ζωα λεγοντα το αμην και οι [πρεσβυτεροι]{.greek-omitted} [πρεσβιτεροι]{.greek-added} επεσον και προσεκυνησαν[5:14]{.aside}

### Chapter 6

και [ειδον]{.greek-omitted} [οιδον]{.greek-added} οτι [ηνοιξεν]{.greek-omitted} [οινοιξαι]{.greek-added} το [αρνιον]{.greek-omitted} [αρνιων]{.greek-added} μιαν εκ των [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} σφραγιδων και [ηκουσα]{.greek-omitted} [οικουσα]{.greek-added} ενος εκ των [τεσσαρων]{.greek-omitted} [[δ]{.greek-abbr}]{.greek-added} ζωων λεγοντος [ως]{.greek-omitted} [ος]{.greek-added} [φωνη]{.greek-omitted} [φωνή]{.greek-added} βροντης ερχου [και]{.greek-omitted} [ιδε]{.greek-omitted}[6:1]{.aside}

[και]{.greek-added} [οιδαι]{.greek-added} και ιδου ιππος λευκος και ο καθημενος επ αυτον [εχων]{.greek-omitted} [εχoν]{.greek-added} τοξον και [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} [αυτω]{.greek-omitted} [αυτο]{.greek-added} στεφανος και εξηλθεν νικων και ινα [νικηση]{.greek-omitted} [νηκηση]{.greek-added}[6:2]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξαι]{.greek-added} την [δευτεραν]{.greek-omitted} [[β]{.greek-abbr}]{.greek-added} [σφραγιδα]{.greek-omitted} [σφραγιδαν]{.greek-added} [ηκουσα]{.greek-omitted} [ικουσα]{.greek-added} του δευτερου ζωου λεγοντος ερχου[6:3]{.aside}

και εξηλθεν [αλλος]{.greek-omitted} [αλος]{.greek-added} [ιππος]{.greek-omitted} [ειππος]{.greek-added} πυρος και [τω]{.greek-omitted} [το]{.greek-added} καθημενω επ [αυτον]{.greek-omitted} [εδοθη]{.greek-omitted} αυτω [λαβειν]{.greek-omitted} [εδωθη]{.greek-added} [αυτω]{.greek-added} [βαλειν]{.greek-added} την ειρηνην εκ της γης ινα αλληλους σφαξωσιν και [εδοθη]{.greek-omitted} [εδωθι]{.greek-added} αυτω μαχαιρα μεγαλη[6:4]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [οινοιξε]{.greek-added} την σφραγιδα την τριτην [ηκουσα]{.greek-omitted} [οικου]{.greek-added} του τριτου ζωου λεγοντος ερχου και [ιδε]{.greek-omitted} [οιδαι]{.greek-added} και ιδου ιππος μελας και ο καθημενος επ αυτον [εχων]{.greek-omitted} [εχον]{.greek-added} [ζυγον]{.greek-omitted} [ζυγων]{.greek-added} εν τη χειρι αυτου[6:5]{.aside}

και [ηκουσα]{.greek-omitted} [οικουσα]{.greek-added} φωνην εν μεσω των τεσσαρων ζωων λεγουσαν [χοινιξ]{.greek-omitted} [χινιξ]{.greek-added} σιτου [δηναριου]{.greek-omitted} [δυναροιου]{.greek-added} και [τρεις]{.greek-omitted} [τροις]{.greek-added} [χοινικες]{.greek-omitted} [χινικες]{.greek-added} κριθης [δηναριου]{.greek-omitted} [δυναριου]{.greek-added} και το [ελαιον]{.greek-omitted} [ελεον]{.greek-added} και [τον]{.greek-omitted} [των]{.greek-added} [οινον]{.greek-omitted} [οινων]{.greek-added} μη αδικησης[6:6]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [οινοιξαι]{.greek-added} την σφραγιδα την τεταρτην [ηκουσα]{.greek-omitted} [οικουσα]{.greek-added} του [τεταρτου]{.greek-omitted} [[δ]{.greek-abbr}]{.greek-added} ζωου λεγοντος ερχου [και]{.greek-omitted} [ιδε]{.greek-omitted}[6:7]{.aside}

[και]{.greek-added} [οιδε]{.greek-added} και ιδου [ιππος]{.greek-omitted} [οιπος]{.greek-added} [χλωρος]{.greek-omitted} [χλορος]{.greek-added} και ο καθημενος επανω αυτου ονομα αυτω ο θανατος και ο αδης [ηκολουθει]{.greek-omitted} [οικωλουθει]{.greek-added} αυτω και [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} αυτω εξουσια επι το [τεταρτον]{.greek-omitted} [[δ]{.greek-abbr}]{.greek-added} της γης [αποκτειναι]{.greek-omitted} [αποκτινε]{.greek-added} εν ρομφαια και εν [λιμω]{.greek-omitted} [λοιμω]{.greek-added} και εν θανατω και υπο των [θηριων]{.greek-omitted} [θυριων]{.greek-added} της γης[6:8]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [οινοιξε]{.greek-added} την [πεμπτην]{.greek-omitted} [[ε]{.greek-abbr}]{.greek-added} σφραγιδα ειδον [υποκατω]{.greek-omitted} [οιποκατω]{.greek-added} του θυσιαστηριου τας ψυχας των εσφαγμενων δια τον λογον του [θεου]{.greek-abbr} και δια την μαρτυριαν του αρνιου ην [ειχον]{.greek-omitted} [ηχον]{.greek-added}[6:9]{.aside}

και εκραξαν [φωνη]{.greek-omitted} [φωνην]{.greek-added} [μεγαλη]{.greek-omitted} [μεγαλην]{.greek-added} λεγοντες εως [ποτε]{.greek-omitted} [ποται]{.greek-added} ο δεσποτης ο αγιος και [αληθινος]{.greek-omitted} [αληθεινος]{.greek-added} ου κρινεις και [εκδικεις]{.greek-omitted} [εκδικης]{.greek-added} το αιμα ημων εκ των κατοικουντων επι της γης[6:10]{.aside}

και [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} αυτοις [εκαστω]{.greek-omitted} στολη λευκη και [ερρεθη]{.greek-omitted} [ερηθη]{.greek-added} αυτοις ινα αναπαυσωνται ετι [χρονον]{.greek-omitted} [χρονων]{.greek-added} εως πληρωσωσιν και οι [συνδουλοι]{.greek-omitted} [συνδωλοι]{.greek-added} αυτων και οι αδελφοι αυτων και οι [μελλοντες]{.greek-omitted} [μελωντες]{.greek-added} αποκτενεσθαι [ως]{.greek-omitted} [ος]{.greek-added} και αυτοι[6:11]{.aside}

και [ειδον]{.greek-omitted} [ειδων]{.greek-added} οτε [ηνοιξεν]{.greek-omitted} [οινοιξαι]{.greek-added} την σφραγιδα την εκτην και [σεισμος]{.greek-omitted} [σισμος]{.greek-added} μεγας εγενετο και ο ηλιος [μελας]{.greek-omitted} [μεγας]{.greek-added} εγενετο [ως]{.greek-omitted} [ος]{.greek-added} σακκος τριχινος και η σεληνη ολη εγενετο [ως]{.greek-omitted} [ος]{.greek-added} αιμα[6:12]{.aside}

και οι αστερες του [ουρανου]{.greek-abbr} επεσον εις την γην [ως]{.greek-omitted} [ος]{.greek-added} συκη βαλουσα τους [ολυνθους]{.greek-omitted} [οληνθους]{.greek-added} αυτης υπο ανεμου μεγαλου [σειομενη]{.greek-omitted} [σηομενη]{.greek-added}[6:13]{.aside}

και ο [ουρανος]{.greek-abbr} [απεχωρισθη]{.greek-omitted} [αποχωρισθη]{.greek-added} [ως]{.greek-omitted} [ος]{.greek-added} βιβλιον [ελισσομενον]{.greek-omitted} [ελυσομενος]{.greek-added} και παν [ορος]{.greek-omitted} [ωρος]{.greek-added} και [νησος]{.greek-omitted} [νισος]{.greek-added} εκ των τοπων αυτων [εκινηθησαν]{.greek-omitted} [εκυνηθησαν]{.greek-added}[6:14]{.aside}

και οι βασιλεις της γης και οι [μεγιστανες]{.greek-omitted} [μεγισταναις]{.greek-added} και οι [χιλιαρχοι]{.greek-omitted} [χιλιαρχι]{.greek-added} και οι πλουσιοι και οι [ισχυροι]{.greek-omitted} [οισχυροι]{.greek-added} και πας δουλος και ελευθερος [εκρυψαν]{.greek-omitted} [εκριψαν]{.greek-added} εαυτους εις τα [σπηλαια]{.greek-omitted} [σπιλεα]{.greek-added} και εις τας πετρας των [ορεων]{.greek-omitted} [ωραιων]{.greek-added}[6:15]{.aside}

και λεγουσιν [τοις]{.greek-omitted} [ταις]{.greek-added} [ορεσιν]{.greek-omitted} [ωρεσιν]{.greek-added} και ταις πετραις [πεσετε]{.greek-omitted} [πεσεται]{.greek-added} εφ ημας και [κρυψατε]{.greek-omitted} [κριψαται]{.greek-added} ημας απο προσωπου του καθημενου επι [του]{.greek-omitted} [θρονου]{.greek-omitted} [τω]{.greek-added} [θρωνω]{.greek-added} και απο της [οργης]{.greek-omitted} [ωργης]{.greek-added} του αρνιου[6:16]{.aside}

οτι ηλθεν η ημερα η μεγαλη της [οργης]{.greek-omitted} [ωργης]{.greek-added} αυτου και [τις]{.greek-omitted} [της]{.greek-added} δυναται [σταθηναι]{.greek-omitted} [σταθυναι]{.greek-added}[6:17]{.aside}

### Chapter 7

και μετα τουτο [ειδον]{.greek-omitted} [οιδων]{.greek-added} τεσσαρας αγγελους εστωτας επι τας [τεσσαρας]{.greek-omitted} [[δ]{.greek-abbr}]{.greek-added} γωνιας της γης κρατουντας τους [τεσσαρας]{.greek-omitted} [[δ]{.greek-abbr}]{.greek-added} ανεμους της γης ινα μη πνεη ανεμος επι της γης μητε επι της θαλασσης μητε επι [τι]{.greek-omitted} [τη]{.greek-added} δενδρον[7:1]{.aside}

και ειδον [αλλον]{.greek-omitted} [αλον]{.greek-added} αγγελον [αναβαινοντα]{.greek-omitted} [ναβαινοντα]{.greek-added} απο ανατολης [ηλιου]{.greek-omitted} [ιλιου]{.greek-added} εχοντα σφραγιδα [θεου]{.greek-abbr} ζωντος και εκραξεν φωνη μεγαλη τοις [τεσσαρσιν]{.greek-omitted} [τεσαρσιν]{.greek-added} αγγελοις οις [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} αυτοις αδικησαι την γην και την θαλασσαν[7:2]{.aside}

[λεγων]{.greek-omitted} [μη]{.greek-omitted} [αδικησητε]{.greek-omitted} [την]{.greek-omitted} [γην]{.greek-omitted} [μητε]{.greek-omitted} [την]{.greek-omitted} [θαλασσαν]{.greek-omitted} μητε τα δενδρα [αχρι]{.greek-omitted} [αχρις]{.greek-added} ου [σφραγισωμεν]{.greek-omitted} [σφραγισομεν]{.greek-added} τους δουλους του [θεου]{.greek-abbr} ημων επι των μετωπων αυτων[7:3]{.aside}

και ηκουσα [τον]{.greek-omitted} [αριθμον]{.greek-omitted} των [αριθμων]{.greek-added} [των]{.greek-added} [εσφραγισμενων]{.greek-omitted} [εσφραγισμενον]{.greek-added} [εκατον]{.greek-omitted} [[ρ]{.greek-abbr}]{.greek-added} και [τεσσαρακοντα]{.greek-omitted} [τεσσαρες]{.greek-omitted} [τε]{.greek-added} [[μδ]{.greek-abbr}]{.greek-added} χιλιαδες [εσφραγισμενων]{.greek-omitted} [εσφραγισμενον]{.greek-added} εκ πασης φυλης υιων [ισραηλ]{.greek-abbr}[7:4]{.aside}

[εκ]{.greek-added} [φυ]{.greek-added} [λης]{.greek-added} [ιουδα]{.greek-added} [[ιβ]{.greek-abbr}]{.greek-added} [χιλιαδες]{.greek-added} [εσφραγισμενοι]{.greek-added} εκ φυλης [ιουδα]{.greek-omitted} [δωδεκα]{.greek-omitted} [χιλιαδες]{.greek-omitted} [εσφραγισμεναι]{.greek-omitted} [εκ]{.greek-omitted} [φυλης]{.greek-omitted} [ρουβιμ]{.greek-omitted} [ρουβημ]{.greek-added} [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εκ φυλης γαδ [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες[7:5]{.aside}

εκ φυλης ασηρ [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εκ φυλης [νεφθαλειμ]{.greek-omitted} [νεφθαλημ]{.greek-added} [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εκ φυλης [μανασση]{.greek-omitted} [μαναση]{.greek-added} [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες[7:6]{.aside}

εκ φυλης συμεων [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εκ φυλης [λευι]{.greek-omitted} [λευη]{.greek-added} [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εκ φυλης ισαχαρ [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες[7:7]{.aside}

εκ φυλης ζαβουλων [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εκ φυλης ιωσηφ [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εκ φυλης [βενιαμιν]{.greek-omitted} [βενιαμην]{.greek-added} [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες [εσφραγισμεναι]{.greek-omitted} [εσφραγισμενε]{.greek-added}[7:8]{.aside}

μετα ταυτα [ειδον]{.greek-omitted} [οιδον]{.greek-added} και [ιδου]{.greek-omitted} [οιδον]{.greek-added} οχλος [πολυς]{.greek-omitted} [πολης]{.greek-added} ον αριθμησαι ουδεις εδυνατο εκ παντος εθνους και φυλων και [λαων]{.greek-omitted} [και]{.greek-omitted} γλωσσων [εστωτας]{.greek-omitted} [εστωτες]{.greek-added} [ενωπιον]{.greek-omitted} [ενοπιον]{.greek-added} του θρονου και [ενωπιον]{.greek-omitted} [ενοπιον]{.greek-added} του αρνιου [περιβεβλημενους]{.greek-omitted} [περιβεβλιμενους]{.greek-added} στολας λευκας και [φοινικας]{.greek-omitted} [φοινοικας]{.greek-added} εν [ταις]{.greek-omitted} [τες]{.greek-added} χερσιν αυτων[7:9]{.aside}

και [κραζουσιν]{.greek-omitted} [κραζουσι]{.greek-added} φωνη μεγαλη λεγοντες η [σωτηρια]{.greek-abbr} τω [θεω]{.greek-abbr} ημων τω καθημενω επι τω [θρονω]{.greek-omitted} [θρωνω]{.greek-added} και τω αρνιω[7:10]{.aside}

και παντες οι αγγελοι [ειστηκεισαν]{.greek-omitted} [οιστηκοισαν]{.greek-added} κυκλω του θρονου και των [πρεσβυτερων]{.greek-omitted} [πρεσβιτερων]{.greek-added} και των [τεσσαρων]{.greek-omitted} [[δ]{.greek-abbr}]{.greek-added} ζωων και επεσον [ενωπιον]{.greek-omitted} [ενοπιον]{.greek-added} του θρονου [αυτου]{.greek-added} επι τα [προσωπα]{.greek-omitted} [πρωσωπα]{.greek-added} αυτων και προσεκυνησαν τω [θεω]{.greek-abbr}[7:11]{.aside}

[λεγοντες]{.greek-omitted} [λεγωντες]{.greek-added} αμην η ευλογια και η δοξα και η σοφια και η ευχαριστια και η τιμη και η δυναμις και [η]{.greek-omitted} [ι]{.greek-added} [ισχυς]{.greek-omitted} [ησχυς]{.greek-added} τω [θεω]{.greek-abbr} ημων εις τους αιωνας των αιωνων αμην[7:12]{.aside}

και απεκριθη εις εκ των [πρεσβυτερων]{.greek-omitted} [πρεσβιτερων]{.greek-added} [λεγων]{.greek-omitted} [λεγει]{.greek-added} μοι ουτοι οι [περιβεβλημενοι]{.greek-omitted} [περιβεβλιμενη]{.greek-added} τας στολας τας λευκας τινες [εισιν]{.greek-omitted} [οισιν]{.greek-added} και ποθεν ηλθον[7:13]{.aside}

και ειπον αυτω κυριε μου συ οιδας και ειπεν μοι ουτοι εισιν οι ερχομενοι [εκ]{.greek-omitted} [υπο]{.greek-added} της θλιψεως της μεγαλης και [επλυναν]{.greek-omitted} [επλατοιναν]{.greek-added} τας στολας αυτων και ελευκαναν εν τω αιματι του αρνιου[7:14]{.aside}

δια [τουτο]{.greek-omitted} [τουτω]{.greek-added} εισιν [ενωπιον]{.greek-omitted} [ενοπιον]{.greek-added} του θρονου του [θεου]{.greek-abbr} και λατρευουσιν αυτω ημερας και νυκτος εν τω ναω αυτου και ο καθημενος επι τω [θρονω]{.greek-omitted} [θρωνω]{.greek-added} [σκηνωσει]{.greek-omitted} [σκυνωσι]{.greek-added} επ αυτους[7:15]{.aside}

ου πεινασουσιν ετι [ουδε]{.greek-omitted} [ουδαι]{.greek-added} [διψησουσιν]{.greek-omitted} [δηψησουσιν]{.greek-added} ετι ουδ ου μη πεση επ αυτους ο ηλιος ουδε παν καυμα[7:16]{.aside}

οτι το [αρνιον]{.greek-omitted} [αρνιων]{.greek-added} [το]{.greek-omitted} [τω]{.greek-added} ανα μεσον του θρονου [ποιμαινει]{.greek-omitted} [ποιμενει]{.greek-added} αυτους και [οδηγει]{.greek-omitted} [οδηγη]{.greek-added} αυτους επι ζωης πηγας [υδατων]{.greek-omitted} [οιδατων]{.greek-added} και [εξαλειψει]{.greek-omitted} [εξαληψει]{.greek-added} ο [θεος]{.greek-abbr} παν [δακρυον]{.greek-omitted} [δακριων]{.greek-added} εκ των οφθαλμων αυτων[7:17]{.aside}

### Chapter 8

και οτε [ηνοιξεν]{.greek-omitted} [οινοιξαι]{.greek-added} την σφραγιδα την [εβδομην]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} εγενετο σιγη εν τω [ουρανω]{.greek-abbr} [ως]{.greek-omitted} [ημιωριον]{.greek-omitted} [oς]{.greek-added} [ἠμιῶριὀν]{.greek-added}[8:1]{.aside}

και [ειδον]{.greek-omitted} [οιδον]{.greek-added} τους επτα αγγελους οι [ενωπιον]{.greek-omitted} [ενοπιον]{.greek-added} του [θεου]{.greek-abbr} εστηκασιν και [εδοθησαν]{.greek-omitted} [εδωθησαν]{.greek-added} [αυτοις]{.greek-omitted} [αυτης]{.greek-added} επτα σαλπιγγες[8:2]{.aside}

και [αλλος]{.greek-omitted} [αλος]{.greek-added} αγγελος ηλθεν και [εσταθη]{.greek-omitted} [εσταθην]{.greek-added} επι του θυσιαστηριου [εχων]{.greek-omitted} [εχον]{.greek-added} [λιβανωτον]{.greek-omitted} [λυβανωτον]{.greek-added} [χρυσουν]{.greek-omitted} [χρησουν]{.greek-added} και [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} αυτω θυμιαματα [πολλα]{.greek-omitted} [πολα]{.greek-added} ινα δωση ταις προσευχαις των αγιων παντων επι το [θυσιαστηριον]{.greek-omitted} [θυσιαστυριον]{.greek-added} το χρυσουν το [ενωπιον]{.greek-omitted} [ενοπιον]{.greek-added} του [θρονου]{.greek-omitted} [θρωνου]{.greek-added}[8:3]{.aside}

και ανεβη ο καπνος των θυμιαματων ταις προσευχαις των αγιων εκ χειρος του αγγελου [ενωπιον]{.greek-omitted} [ενοπιον]{.greek-added} του [θεου]{.greek-abbr}[8:4]{.aside}

και ειληφεν ο αγγελος τον λιβανωτον και εγεμισεν αυτον εκ του πυρος του [θυσιαστηριου]{.greek-omitted} [θυσιαστυριου]{.greek-added} και εβαλεν εις την γην και εγενοντο βρονται και φωναι και αστραπαι και σεισμος[8:5]{.aside}

και οι [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} αγγελοι οι [εχοντες]{.greek-omitted} [εχωντες]{.greek-added} τας επτα [σαλπιγγας]{.greek-omitted} [σαλπιγκας]{.greek-added} ητοιμασαν εαυτους ινα σαλπισωσιν[8:6]{.aside}

και ο [πρωτος]{.greek-omitted} [προτος]{.greek-added} εσαλπισεν και εγενετο χαλαζα και πυρ μεμιγμενα [εν]{.greek-omitted} [αιν]{.greek-added} αιματι και [εβληθη]{.greek-omitted} [εβλιθη]{.greek-added} εις την γην και το τριτον της γης κατεκαη και το [τριτον]{.greek-omitted} [τριτων]{.greek-added} [των]{.greek-omitted} [το]{.greek-added} δενδρων [κατεκαη]{.greek-omitted} [κατεκαι]{.greek-added} και πας χορτος [χλωρος]{.greek-omitted} [χλορος]{.greek-added} [κατεκαη]{.greek-omitted} [κατεκαι]{.greek-added}[8:7]{.aside}

και ο [δευτερος]{.greek-omitted} [[β]{.greek-abbr}]{.greek-added} αγγελος εσαλπισεν και [ως]{.greek-omitted} [ος]{.greek-added} [ορος]{.greek-omitted} [ωρος]{.greek-added} [μεγα]{.greek-omitted} [μεγας]{.greek-added} [καιομενον]{.greek-omitted} [γενομενον]{.greek-added} εβληθη εις την θαλασσαν και εγενετο το τριτον της θαλασσης αιμα[8:8]{.aside}

και απεθανεν το [τριτον]{.greek-omitted} [τριτων]{.greek-added} των κτισματων εν τη [θαλασση]{.greek-omitted} [θαλασσοι]{.greek-added} τα [εχοντα]{.greek-omitted} [εχωντα]{.greek-added} ψυχας και το [τριτον]{.greek-omitted} [τριτων]{.greek-added} των πλοιων [διεφθαρη]{.greek-omitted} [διεφθαρει]{.greek-added}[8:9]{.aside}

και ο τριτος αγγελος εσαλπισεν και επεσεν εκ του [ουρανου]{.greek-abbr} αστηρ μεγας καιομενος [ως]{.greek-omitted} [ος]{.greek-added} λαμπας και επεσεν επι το τριτον [των]{.greek-omitted} [τον]{.greek-added} ποταμων και επι τας πηγας των [υδατων]{.greek-omitted} [ιδατων]{.greek-added}[8:10]{.aside}

και το ονομα του αστερος [λεγεται]{.greek-omitted} [λεγετε]{.greek-added} ο αψινθος και εγενετο το τριτον [των]{.greek-omitted} [τον]{.greek-added} υδατων εις αψινθον και [πολλοι]{.greek-omitted} [πολοι]{.greek-added} των [ανθρωπων]{.greek-abbr} [απεθανον]{.greek-omitted} [απεθανων]{.greek-added} εκ των [υδατων]{.greek-omitted} [οιδατων]{.greek-added} οτι επικρανθησαν[8:11]{.aside}

[και]{.greek-added} [και]{.corr} ο [τεταρτος]{.greek-omitted} [[δ]{.greek-abbr}]{.greek-added} αγγελος εσαλπισεν και επληγη το τριτον του ηλιου και το τριτον της σεληνης και το [τριτον]{.greek-omitted} [τριτων]{.greek-added} των αστερων ινα σκοτισθη το τριτον αυτων και το [τριτον]{.greek-omitted} [τριτων]{.greek-added} [αυτης]{.greek-omitted} [αυτοις]{.greek-added} μη [φανη]{.greek-omitted} [φανοι]{.greek-added} η ημερα και η νυξ ομοιως[8:12]{.aside}

και [ειδον]{.greek-omitted} [οιδων]{.greek-added} [και]{.greek-omitted} [αι]{.greek-added} ηκουσα ενος αετου πετομενου εν [μεσουρανηματι]{.greek-omitted} [μεσουρανιματι]{.greek-added} [λεγοντος]{.greek-omitted} [λεγωντος]{.greek-added} φωνη μεγαλη ουαι ουαι ουαι [τοις]{.greek-omitted} [τους]{.greek-added} [κατοικουσιν]{.greek-omitted} [κατοικουντας]{.greek-added} επι της γης εκ των [λοιπων]{.greek-omitted} φωνων [λυπων]{.greek-added} της σαλπιγγος [των]{.greek-omitted} [τον]{.greek-added} τριων αγγελων των [μελλοντων]{.greek-omitted} [μελωντων]{.greek-added} σαλπιζειν[8:13]{.aside}

### Chapter 9

και ο πεμπτος αγγελος εσαλπισεν και [ειδον]{.greek-omitted} [οιδων]{.greek-added} αστερα εκ του [ουρανου]{.greek-abbr} [πεπτωκοτα]{.greek-omitted} [πεπτωκωτα]{.greek-added} εις την γην και [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} αυτω η [κλεις]{.greek-omitted} [κλις]{.greek-added} του φρεατος της αβυσσου[9:1]{.aside}

[και]{.greek-omitted} [ηνοιξεν]{.greek-omitted} [το]{.greek-omitted} [φρεαρ]{.greek-omitted} [της]{.greek-omitted} [αβυσσου]{.greek-omitted} και ανεβη καπνος εκ του φρεατος [ως]{.greek-omitted} [ος]{.greek-added} καπνος καμινου [καιομενης]{.greek-omitted} [κεομενης]{.greek-added} και εσκοτισθη ο ηλιος και ο αηρ εκ του καπνου του φρεατος[9:2]{.aside}

και εκ του καπνου εξηλθον ακριδες εις την γην και [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} αυταις εξουσια [ως]{.greek-omitted} [ος]{.greek-added} εχουσιν εξουσιαν οι σκορπιοι της γης[9:3]{.aside}

και [ερρεθη]{.greek-omitted} [ερριθι]{.greek-added} αυταις ινα μη αδικησωσιν [τον]{.greek-omitted} [των]{.greek-added} [χορτον]{.greek-omitted} [χορτων]{.greek-added} της γης [ουδε]{.greek-omitted} [ουδαι]{.greek-added} παν [χλωρον]{.greek-omitted} [ουδε]{.greek-omitted} [χλορων]{.greek-added} [ουδαι]{.greek-added} παν [δενδρον]{.greek-omitted} [δενδρων]{.greek-added} [ει]{.greek-omitted} [οι]{.greek-added} μη τους [ανθρωπους]{.greek-abbr} οιτινες ουκ εχουσιν την σφραγιδα του [θεου]{.greek-abbr} επι των μετωπων αυτων[9:4]{.aside}

και [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} αυταις [ταις]{.greek-added} ινα μη [αποκτεινωσιν]{.greek-omitted} [αποκτινωσιν]{.greek-added} αυτους [αλλ]{.greek-omitted} [αλ]{.greek-added} ινα [βασανισθωσιν]{.greek-omitted} [βασανεισθωσιν]{.greek-added} μηνας [πεντε]{.greek-omitted} [[ε]{.greek-abbr}]{.greek-added} και ο βασανισμος αυτων [ως]{.greek-omitted} [ος]{.greek-added} βασανισμος σκορπιου οταν παιση [ανθρωπον]{.greek-omitted} [[ανθρωπων]{.greek-abbr}]{.greek-added}[9:5]{.aside}

και εν ταις ημεραις [εκειναις]{.greek-omitted} [εκυναις]{.greek-added} [ζητησουσιν]{.greek-omitted} [ζητουσιν]{.greek-added} οι [ανθρωποι]{.greek-abbr} τον θανατον και ου μη [ευρησουσιν]{.greek-omitted} [εὐρίσουσιν]{.greek-added} [αυτον]{.greek-omitted} [αυτων]{.greek-added} και επιθυμησουσιν αποθανειν και [φευξεται]{.greek-omitted} [φευξαιται]{.greek-added} απ αυτων ο θανατος[9:6]{.aside}

και τα ομοιωματα των ακριδων ομοια [ιπποις]{.greek-omitted} [οιπποις]{.greek-added} [ητοιμασμενοις]{.greek-omitted} [οιτοιμασμενοις]{.greek-added} εις [πολεμον]{.greek-omitted} [πολεμων]{.greek-added} και επι τας κεφαλας αυτων [ως]{.greek-omitted} [ος]{.greek-added} στεφανοι [χρυσοι]{.greek-omitted} [χρησοι]{.greek-added} και τα [προσωπα]{.greek-omitted} [προσοπα]{.greek-added} αυτων [ως]{.greek-omitted} [ος]{.greek-added} [προσωπα]{.greek-omitted} [πρωσωπα]{.greek-added} [ανθρωπων]{.greek-abbr}[9:7]{.aside}

και [ειχον]{.greek-omitted} [οιχων]{.greek-added} τριχας ως τριχας γυναικων και οι [οδοντες]{.greek-omitted} [ωδωντες]{.greek-added} αυτων [ως]{.greek-omitted} [ος]{.greek-added} [λεοντων]{.greek-omitted} [λεωντων]{.greek-added} ησαν[9:8]{.aside}

και [ειχον]{.greek-omitted} [οιχον]{.greek-added} θωρακας ως θωρακας [σιδηρους]{.greek-omitted} [σηδηρους]{.greek-added} και [η]{.greek-omitted} [οι]{.greek-added} φωνη των [πτερυγων]{.greek-omitted} [πτεριγων]{.greek-added} αυτων [ως]{.greek-omitted} [ος]{.greek-added} φωνη αρματων ιππων [πολλων]{.greek-omitted} [πολων]{.greek-added} [τρεχοντων]{.greek-omitted} [τρεχωντων]{.greek-added} εις πολεμον[9:9]{.aside}

και εχουσιν ουρας ομοιας σκορπιοις και [κεντρα]{.greek-omitted} [κενδρα]{.greek-added} και εν ταις ουραις αυτων εξουσιαν εχουσιν του [αυτων]{.greek-added} [εξουσιαν]{.greek-added} [εχουσιν]{.greek-added} [του]{.greek-added} αδικησαι τους [ανθρωπους]{.greek-abbr} μηνας [πεντε]{.greek-omitted} [[ε]{.greek-abbr}]{.greek-added}[9:10]{.aside}

εχουσαι βασιλεα επ αυτων αγγελον της [αβυσσου]{.greek-omitted} [αβισου]{.greek-added} ονομα αυτω [εβραιστι]{.greek-omitted} [εβραηστι]{.greek-added} [αββαδων]{.greek-omitted} [αβαδδων]{.greek-added} εν [δε]{.greek-omitted} [δαι]{.greek-added} τη [ελληνικη]{.greek-omitted} [ελινικη]{.greek-added} ονομα εχει [απολλυων]{.greek-omitted} [απολυων]{.greek-added}[9:11]{.aside}

η ουαι η μια απηλθεν ιδου ερχεται ετι [δυο]{.greek-omitted} [διω]{.greek-added} ουαι μετα ταυτα[9:12]{.aside}

και ο εκτος αγγελος εσαλπισεν και [ηκουσα]{.greek-omitted} [οικουσα]{.greek-added} φωνην μιαν εκ των [τεσσαρων]{.greek-omitted} [[δ]{.greek-abbr}]{.greek-added} κερατων του θυσιαστηριου του [χρυσου]{.greek-omitted} [χρησου]{.greek-added} του [ενωπιον]{.greek-omitted} [ενοπιον]{.greek-added} του [θεου]{.greek-abbr}[9:13]{.aside}

[λεγουσαν]{.greek-omitted} [λεγοντος]{.greek-added} τω [εκτω]{.greek-omitted} [[ϛ]{.greek-abbr}]{.greek-added} αγγελω ο εχων την σαλπιγγα [λυσον]{.greek-omitted} [λυσσον]{.greek-added} τους [τεσσαρας]{.greek-omitted} [[δ]{.greek-abbr}]{.greek-added} αγγελους τους δεδεμενους επι τω ποταμω τω μεγαλω [ευφρατη]{.greek-omitted} [ευφρατι]{.greek-added}[9:14]{.aside}

και [ελυθησαν]{.greek-omitted} [ελυθυσαν]{.greek-added} οι [τεσσαρες]{.greek-omitted} [τεσσαροις]{.greek-added} αγγελοι οι ητοιμασμενοι εις την ωραν και εις την ημεραν και μηνα και ενιαυτον ινα [αποκτεινωσιν]{.greek-omitted} [αποκτινωσι]{.greek-added} [το]{.greek-omitted} [τριτον]{.greek-omitted} [τω]{.greek-added} [τριτω]{.greek-added} των [ανθρωπων]{.greek-abbr}[9:15]{.aside}

και ο αριθμος των [στρατευματων]{.greek-omitted} [στρατευματου]{.greek-added} του ιππου μυριαδες μυριαδων [ηκουσα]{.greek-omitted} [οικουσα]{.greek-added} [τον]{.greek-omitted} [των]{.greek-added} [αριθμον]{.greek-omitted} [αριθμων]{.greek-added} αυτων[9:16]{.aside}

και [ουτως]{.greek-omitted} [ουτος]{.greek-added} [ειδον]{.greek-omitted} [οιδον]{.greek-added} τους [ιππους]{.greek-omitted} [οιππους]{.greek-added} εν τη [ορασει]{.greek-omitted} [ωρασση]{.greek-added} και τους καθημενους επ [αυτων]{.greek-omitted} [αυτον]{.greek-added} εχοντας θωρακας πυρινους και [υακινθινους]{.greek-omitted} [οιακηνθινους]{.greek-added} και [θειωδεις]{.greek-omitted} [θειωδης]{.greek-added} και αι κεφαλαι των ιππων ως κεφαλαι [λεοντων]{.greek-omitted} [λεωντων]{.greek-added} και εκ των στοματων αυτων [εκπορευεται]{.greek-omitted} [εκπορευσεται]{.greek-added} πυρ και καπνος και [θειον]{.greek-omitted} [θειων]{.greek-added}[9:17]{.aside}

απο των τριων πληγων [τουτων]{.greek-omitted} [τουτον]{.greek-added} απεκτανθησαν το [τριτον]{.greek-omitted} [τριτων]{.greek-added} των [ανθρωπων]{.greek-abbr} απο του πυρος και του καπνου και του θειου του εκπορευομενου εκ των στοματων αυτων[9:18]{.aside}

η γαρ εξουσια των [ιππων]{.greek-omitted} [ιπων]{.greek-added} εν τω στοματι αυτων εστιν και εν ταις ουραις αυτων αι γαρ ουραι αυτων ομοιαι οφεων εχουσαι κεφαλας και εν αυταις αδικουσιν[9:19]{.aside}

και οι λοιποι των [ανθρωπων]{.greek-abbr} οι ουκ απεκτανθησαν εν ταις πληγαις ταυταις ου μετενοησαν εκ των εργων των χειρων αυτων ινα μη προσκυνησωσιν τα [δαιμονια]{.greek-omitted} [δεμονια]{.greek-added} και τα [ειδωλα]{.greek-omitted} [οιδωλα]{.greek-added} τα [χρυσα]{.greek-omitted} [χρησα]{.greek-added} και τα αργυρα και τα [ληθηνα]{.greek-added} [χαλκα]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} [λιθινα]{.greek-omitted} και τα ξυλινα α ουτε βλεπειν [δυναται]{.greek-omitted} [δυνανται]{.greek-added} ουτε ακουειν ουτε [περιπατειν]{.greek-omitted} [περιπατην]{.greek-added}[9:20]{.aside}

και ου μετενοησαν εκ των [φονων]{.greek-omitted} [φωνων]{.greek-added} αυτων ουτε εκ των [φαρμακειων]{.greek-omitted} [φαρμακων]{.greek-added} αυτων ουτε εκ της πορνειας αυτων ουτε εκ των [κλεμματων]{.greek-omitted} [κρεματων]{.greek-added} αυτων[9:21]{.aside}

### Chapter 10

και [ειδον]{.greek-omitted} [οιδον]{.greek-added} [αγγελον]{.greek-omitted} [αγγελων]{.greek-added} [ισχυρον]{.greek-omitted} [οισχυρον]{.greek-added} καταβαινοντα εκ [του]{.greek-omitted} [των]{.greek-added} [ουρανου]{.greek-omitted} [[ουρανον]{.greek-abbr}]{.greek-added} [περιβεβλημενον]{.greek-omitted} [περιβεβλιμενην]{.greek-added} νεφελην και η ιρις επι της κεφαλης αυτου και το προσωπον αυτου [ως]{.greek-omitted} [ος]{.greek-added} ο ηλιος και οι ποδες αυτου [ως]{.greek-omitted} [ος]{.greek-added} στυλοι πυρος[10:1]{.aside}

και [εχων]{.greek-omitted} [εχον]{.greek-added} εν τη χειρι αυτου βιβλιον ανεωγμενον και [εθηκεν]{.greek-omitted} [εθεικε]{.greek-added} τον ποδα αυτου τον [δεξιον]{.greek-omitted} [δεξιων]{.greek-added} επι της θαλασσης τον [δε]{.greek-omitted} [ευωνυμον]{.greek-omitted} [δαι]{.greek-added} [εβονημον]{.greek-added} επι της γης[10:2]{.aside}

και [εκραξεν]{.greek-omitted} [εκραξαι]{.greek-added} φωνη μεγαλη [ωσπερ]{.greek-omitted} [οσπερ]{.greek-added} λεων [μυκαται]{.greek-omitted} [μηκαται]{.greek-added} και [οτε]{.greek-omitted} [οται]{.greek-added} εκραξεν ελαλησαν αι επτα βρονται τας εαυτων φωνας[10:3]{.aside}

και οτε ελαλησαν αι επτα βρονται [εμελλον]{.greek-omitted} [ημελον]{.greek-added} [γραφειν]{.greek-omitted} [γραφην]{.greek-added} και ηκουσα φωνην εκ του [ουρανου]{.greek-abbr} λεγουσαν σφραγισον α [ελαλησαν]{.greek-omitted} [αιλαλησαν]{.greek-added} αι επτα βρονται και μη αυτα γραψης[10:4]{.aside}

και ο αγγελος [ον]{.greek-omitted} [ων]{.greek-added} [ειδον]{.greek-omitted} [οιδον]{.greek-added} εστωτα επι της θαλασσης και επι της γης ηρεν την χειρα αυτου την δεξιαν εις τον [ουρανον]{.greek-abbr}[10:5]{.aside}

και [ωμοσεν]{.greek-omitted} [ωμωσε]{.greek-added} τω ζωντι εις τους αιωνας των αιωνων ος εκτισεν τον [ουρανον]{.greek-abbr} και τα εν αυτω και την γην και τα εν αυτη και την θαλασσαν και τα εν αυτη οτι χρονος ουκετι [εσται]{.greek-omitted} [εστε]{.greek-added}[10:6]{.aside}

[αλλ]{.greek-omitted} [αλ]{.greek-added} εν ταις ημεραις της φωνης του [εβδομου]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} [του]{.greek-added} αγγελου οταν [μελλη]{.greek-omitted} [μελη]{.greek-added} [σαλπιζειν]{.greek-omitted} [σαλπιζην]{.greek-added} και ετελεσθη το [μυστηριον]{.greek-omitted} [μυστυριον]{.greek-added} του [θεου]{.greek-abbr} [ως]{.greek-omitted} [ος]{.greek-added} ευηγγελισεν τους δουλους αυτου τους προφητας[10:7]{.aside}

και η φωνη ην ηκουσα εκ του [ουρανου]{.greek-abbr} παλιν [λαλουσα]{.greek-omitted} [λεγουσα]{.greek-added} μετ εμου και λεγουσα [υπαγε]{.greek-omitted} [υπαγαι]{.greek-added} λαβε το βιβλιδαριον [το]{.greek-omitted} [του]{.greek-added} ανεωγμενον εν τη χειρι του αγγελου του εστωτος επι της θαλασσης και επι της γης[10:8]{.aside}

και [απηλθον]{.greek-omitted} [απηλθα]{.greek-added} προς τον αγγελον [λεγων]{.greek-omitted} [λεγον]{.greek-added} αυτω δουναι μοι [το]{.greek-omitted} [τω]{.greek-added} βιβλιδαριον και λεγει μοι [λαβε]{.greek-omitted} [λαβαι]{.greek-added} και καταφαγε [αυτο]{.greek-omitted} [αυτω]{.greek-added} και [πικρανει]{.greek-omitted} [πικρανι]{.greek-added} σου την κοιλιαν [αλλ]{.greek-omitted} [αλ]{.greek-added} εν [τω]{.greek-omitted} [το]{.greek-added} στοματι σου [εσται]{.greek-omitted} [γλυκυ]{.greek-omitted} [ως]{.greek-omitted} [εστε]{.greek-added} [γλυκοι]{.greek-added} [ος]{.greek-added} μελι[10:9]{.aside}

και ελαβον το βιβλιον εκ της χειρος του αγγελου και κατεφαγον [αυτο]{.greek-omitted} [αὐτῶ]{.greek-added} και ην εν [τω]{.greek-omitted} [το]{.greek-added} στοματι μου [ως]{.greek-omitted} [ος]{.greek-added} μελι [γλυκυ]{.greek-omitted} [γλικη]{.greek-added} και οτε εφαγον [αυτο]{.greek-omitted} [αυτω]{.greek-added} επικρανθη η [κοιλια]{.greek-omitted} [κοιλοια]{.greek-added} μου[10:10]{.aside}

και λεγουσιν μοι [δει]{.greek-omitted} [δοι]{.greek-added} σε παλιν προφητευσαι επι λαοις και επι εθνεσιν και γλωσσαις και βασιλευσιν [πολλοις]{.greek-omitted} [πολοις]{.greek-added}[10:11]{.aside}

### Chapter 11

και [εδοθη]{.greek-omitted} [εδωθοι]{.greek-added} μοι καλαμος ομοιος ραβδω λεγων εγειραι και [μετρησον]{.greek-omitted} [μετρισον]{.greek-added} [τον]{.greek-omitted} [το]{.greek-added} ναον του [θεου]{.greek-abbr} και το [θυσιαστηριον]{.greek-omitted} [θυσιαστυριον]{.greek-added} και τους προσκυνουντας εν αυτω[11:1]{.aside}

και την αυλην την εξωθεν του ναου [εκβαλε]{.greek-omitted} [εκβαλαι]{.greek-added} εξω και μη αυτην [μετρησης]{.greek-omitted} [μετρισις]{.greek-added} οτι [εδοθη]{.greek-omitted} [εδωθοι]{.greek-added} τοις εθνεσιν και την πολιν την αγιαν πατησουσιν μηνας [τεσσαρακοντα]{.greek-omitted} [τε]{.greek-added} [[μ]{.greek-abbr}]{.greek-added} και [δυο]{.greek-omitted} [[β]{.greek-abbr}]{.greek-added}[11:2]{.aside}

και δωσω τοις δυσιν μαρτυσιν μου και [προφητευσουσιν]{.greek-omitted} [προφητευσοσιν]{.greek-added} ημερας [[αϛξ]{.greek-abbr}]{.greek-added} [χιλιας]{.greek-omitted} [διακοσιας]{.greek-omitted} [εξηκοντα]{.greek-omitted} περιβεβλημενοι [σακκους]{.greek-omitted} [σακους]{.greek-added}[11:3]{.aside}

ουτοι εισιν αι δυο [ελαιαι]{.greek-omitted} [ελαιε]{.greek-added} και αι δυο λυχνιαι αι [ενωπιον]{.greek-omitted} [ενοπιον]{.greek-added} του [κυριου]{.greek-abbr} της γης [εστωσαι]{.greek-omitted} [εστωτες]{.greek-added}[11:4]{.aside}

και [ει]{.greek-omitted} [οι]{.greek-added} τις [αυτους]{.greek-omitted} [αυτος]{.greek-added} [θελει]{.greek-omitted} [αδικησαι]{.greek-omitted} [θελη]{.greek-added} [δοκημασαι]{.greek-added} πυρ εκπορευεται εκ του στοματος αυτων και κατεσθιει τους εχθρους αυτων και [ει]{.greek-omitted} [οι]{.greek-added} τις θελει αυτους αδικησαι [ουτως]{.greek-omitted} [ουτος]{.greek-added} [δει]{.greek-omitted} [δι]{.greek-added} [αυτον]{.greek-omitted} [αυτων]{.greek-added} [αποκτανθηναι]{.greek-omitted} [αποκτανθυναι]{.greek-added}[11:5]{.aside}

ουτοι εχουσιν [τον]{.greek-omitted} [των]{.greek-added} [ουρανον]{.greek-omitted} [[ουρανων]{.greek-abbr}]{.greek-added} εξουσιαν [κλεισαι]{.greek-omitted} [κλησαι]{.greek-added} ινα μη [υετος]{.greek-omitted} [ιετος]{.greek-added} [βρεχη]{.greek-omitted} [βρεχει]{.greek-added} τας ημερας της [προφητειας]{.greek-omitted} [προφητιας]{.greek-added} αυτων και εξουσιαν εχουσιν επι [των]{.greek-omitted} [τον]{.greek-added} υδατων [στρεφειν]{.greek-omitted} [στρεφην]{.greek-added} αυτα εις αιμα και παταξαι την γην οσακις εαν θελησωσιν [εν]{.greek-omitted} [εκ]{.greek-added} παση πληγη[11:6]{.aside}

και οταν τελεσωσιν την μαρτυριαν αυτων το [θηριον]{.greek-omitted} [θυριον]{.greek-added} το [αναβαινον]{.greek-omitted} [ἀνὰβαίνων]{.greek-added} εκ της [αβυσσου]{.greek-omitted} [αβυσου]{.greek-added} [ποιησει]{.greek-omitted} [ποιησι]{.greek-added} μετ αυτων [πολεμον]{.greek-omitted} [πολαιμων]{.greek-added} και [νικησει]{.greek-omitted} [νικησι]{.greek-added} αυτους και [αποκτενει]{.greek-omitted} [αποκτενι]{.greek-added} αυτους[11:7]{.aside}

και το πτωμα αυτων επι της [πλατειας]{.greek-omitted} [πλατιας]{.greek-added} της [πολεως]{.greek-omitted} [πολεος]{.greek-added} της μεγαλης [ητις]{.greek-omitted} [ειτις]{.greek-added} καλειται [πνευματικως]{.greek-omitted} [[πνευματι]{.greek-abbr}[κος]{.greek-abbr}]{.greek-added} [σοδομα]{.greek-omitted} [σοδωμα]{.greek-added} και αιγυπτος οπου και ο [κυριος]{.greek-abbr} αυτων [εσταυρωθη]{.greek-abbr}[11:8]{.aside}

και βλεπουσιν εκ των λαων και [φυλων]{.greek-omitted} [φιλων]{.greek-added} και [γλωσσων]{.greek-omitted} [γλωσων]{.greek-added} και εθνων το πτωμα αυτων ημερας [τρεις]{.greek-omitted} [τρις]{.greek-added} [ημισυ]{.greek-omitted} [ημισι]{.greek-added} και τα πτωματα αυτων ουκ αφησουσιν [τεθηναι]{.greek-omitted} [τεθυναι]{.greek-added} εις μνημα[11:9]{.aside}

και οι κατοικουντες επι της γης χαιρουσιν [αυτης]{.greek-added} [επ]{.greek-omitted} [αυτοις]{.greek-omitted} και ευφρανθησονται και δωρα δωσουσιν [αλληλοις]{.greek-omitted} [αληλοις]{.greek-added} οτι ουτοι [ο]{.greek-added} [δυο]{.greek-added} οι [δυο]{.greek-omitted} προφηται εβασανισαν τους κατοικουντας επι της γης[11:10]{.aside}

και μετα τας [τρεις]{.greek-omitted} [τρις]{.greek-added} ημερας και [ημισυ]{.greek-omitted} [οιμοισοι]{.greek-added} [πνευμα]{.greek-abbr} ζωης εκ του [θεου]{.greek-abbr} εισηλθεν εις αυτους και [εστησαν]{.greek-omitted} [εστισαν]{.greek-added} επι τους ποδας αυτων και φοβος μεγας [επεσεν]{.greek-omitted} επι τους [θεωρουντας]{.greek-omitted} [θεορουντας]{.greek-added} αυτους[11:11]{.aside}

και [ηκουσα]{.greek-omitted} [οικουσα]{.greek-added} φωνην μεγαλην εκ του [ουρανου]{.greek-abbr} λεγουσαν αυτοις [αναβητε]{.greek-omitted} [ἀνέβηται]{.greek-added} ωδε και ανεβησαν εις τον [ουρανον]{.greek-abbr} εν τη νεφελη και εθεωρησαν αυτους οι εχθροι αυτων[11:12]{.aside}

[και]{.greek-omitted} εν [εκεινη]{.greek-omitted} [εκηνη]{.greek-added} τη ημερα εγενετο [σεισμος]{.greek-omitted} [σισμος]{.greek-added} μεγας και το δεκατον της [πολεως]{.greek-omitted} [πολεος]{.greek-added} επεσεν και απεκτανθησαν εν τω [σεισμω]{.greek-omitted} [σισμω]{.greek-added} ονοματα [ανθρωπων]{.greek-abbr} χιλιαδες [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} και οι λοιποι [εμφοβοι]{.greek-omitted} [εμφωβη]{.greek-added} εγενοντο και [εδωκαν]{.greek-omitted} [εδοκαν]{.greek-added} δοξαν τω [θεω]{.greek-abbr} του [ουρανου]{.greek-abbr}[11:13]{.aside}

η ουαι η [δευτερα]{.greek-omitted} [[β]{.greek-abbr}]{.greek-added} απηλθεν η ουαι η τριτη ιδου ερχεται [ταχυ]{.greek-omitted} [ταχη]{.greek-added}[11:14]{.aside}

και ο [εβδομος]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} αγγελος εσαλπισεν και εγενοντο φωναι μεγαλαι εν τω [ουρανω]{.greek-abbr} λεγουσαι εγενετο η βασιλεια του κοσμου του [κυριου]{.greek-abbr} [ημων]{.greek-omitted} [ημον]{.greek-added} και του [χριστου]{.greek-abbr} αυτου και [βασιλευσει]{.greek-omitted} [βασιλευσι]{.greek-added} εις τους αιωνας των αιωνων[11:15]{.aside}

και οι [[κδ]{.greek-abbr}]{.greek-added} [εικοσι]{.greek-omitted} [τεσσαρες]{.greek-omitted} πρεσβυτεροι οι [ενωπιον]{.greek-omitted} [ενοπιον]{.greek-added} του θρονου του [θεου]{.greek-abbr} [καθημενοι]{.greek-omitted} [οι]{.greek-added} [καθηνται]{.greek-added} επι [τους]{.greek-omitted} [του]{.greek-added} θρονους αυτων επεσον επι τα προσωπα αυτων και προσεκυνησαν τω [θεω]{.greek-abbr}[11:16]{.aside}

λεγοντες ευχαριστουμεν σοι [κυριε]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ ο ων και ο ην οτι [ειληφας]{.greek-omitted} [ηληφας]{.greek-added} την δυναμιν σου την μεγαλην και εβασιλευσας[11:17]{.aside}

και τα εθνη ωργισθησαν και ηλθεν η [οργη]{.greek-omitted} [οργι]{.greek-added} σου και ο [καιρος]{.greek-omitted} [κερος]{.greek-added} των νεκρων κριθηναι και δουναι τον μισθον τοις δουλοις σου τοις προφηταις και τοις αγιοις και τοις [φοβουμενοις]{.greek-omitted} [φοβουμενης]{.greek-added} το ονομα σου τοις [μικροιςκροις]{.greek-added} [μικροις]{.corr} και [τοις]{.greek-omitted} [τις]{.greek-added} [μεγαλοις]{.greek-omitted} [μεγαλης]{.greek-added} και [διαφθειραι]{.greek-omitted} [διαφθειρε]{.greek-added} τους διαφθειροντας την γην[11:18]{.aside}

και [ηνοιγη]{.greek-omitted} [οινοιχθη]{.greek-added} ο ναος του [θεου]{.greek-abbr} εν τω ουρανω και ωφθη [η]{.greek-omitted} [οι]{.greek-added} [κιβωτος]{.greek-omitted} [κοιβωτος]{.greek-added} της [διαθηκης]{.greek-omitted} [διαθυκης]{.greek-added} του [κυριου]{.greek-abbr} εν τω ναω αυτου και εγενοντο αστραπαι και φωναι και βρονται και χαλαζα μεγαλη[11:19]{.aside}

### Chapter 12

και σημειον μεγα ωφθη εν τω [ουρανω]{.greek-abbr} γυνη περιβεβλημενη τον ηλιον και η σεληνη υποκατω των ποδων αυτης και επι της κεφαλης αυτης στεφανος αστερων [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added}[12:1]{.aside}

και εν γαστρι εχουσα εκραζεν [ωδινουσα]{.greek-omitted} [οδινουσα]{.greek-added} και [βασανιζομενη]{.greek-omitted} [βασανιζομενοι]{.greek-added} [τεκειν]{.greek-omitted} [τεκην]{.greek-added}[12:2]{.aside}

και ωφθη αλλο [σημειον]{.greek-omitted} [σημιων]{.greek-added} εν τω [ουρανω]{.greek-abbr} και ιδου δρακων πυρος μεγας [εχων]{.greek-omitted} [εχον]{.greek-added} κεφαλας [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} και κερατα [δεκα]{.greek-omitted} [[ι]{.greek-abbr}]{.greek-added} και επι τας κεφαλας αυτου επτα διαδηματα[12:3]{.aside}

και [η]{.greek-omitted} [οι]{.greek-added} ουρα αυτου [συρει]{.greek-omitted} [συροι]{.greek-added} [το]{.greek-omitted} [τω]{.greek-added} τριτον των αστερων του [ουρανου]{.greek-abbr} και εβαλεν αυτους εις την γην και [ο]{.corr} [δρακων]{.greek-omitted} [δρακον]{.greek-added} [εστηκεν]{.greek-omitted} [ἔστικεν]{.greek-added} [ενωπιον]{.greek-omitted} [ενοπιον]{.greek-added} της γυναικος της [μελλουσης]{.greek-omitted} [μελουσης]{.greek-added} [τεκειν]{.greek-omitted} [τεκην]{.greek-added} ινα οταν [τεκη]{.greek-omitted} [τεκοι]{.greek-added} το τεκνον αυτης καταφαγη[12:4]{.aside}

και ετεκεν υιον αρρενα ος [μελλει]{.greek-omitted} [ποιμαινειν]{.greek-omitted} [μελλη]{.greek-added} [πιμενην]{.greek-added} παντα τα εθνη εν ραβδω [σιδηρα]{.greek-omitted} [σηδηρα]{.greek-added} και ηρπασθη το τεκνον αυτης προς τον [θεον]{.greek-abbr} και προς τον θρονον αυτου[12:5]{.aside}

και η γυνη [εφυγεν]{.greek-omitted} [εφηγεν]{.greek-added} εις την [ερημον]{.greek-omitted} [εριμον]{.greek-added} οπου εχει εκει τοπον [ητοιμασμενον]{.greek-omitted} [ητιμασμενον]{.greek-added} υπο του [θεου]{.greek-abbr} ινα εκει [εκ]{.greek-added} [εκτρεφωσιν]{.greek-omitted} [τρεφωσιν]{.greek-added} αυτην ημερας χιλιας διακοσιας εξηκοντα[12:6]{.aside}

και εγενετο πολεμος εν τω [ουρανω]{.greek-abbr} ο μιχαηλ και οι αγγελοι αυτου πολεμησαι μετα του δρακοντος και ο [δρακων]{.greek-omitted} [δρακκων]{.greek-added} επολεμησεν και οι αγγελοι αυτου[12:7]{.aside}

και ουκ [ισχυσεν]{.greek-omitted} [ησχησεν]{.greek-added} ουδε τοπος ευρεθη [αυτω]{.greek-omitted} [ετι]{.greek-omitted} εν τω [ουρανω]{.greek-abbr}[12:8]{.aside}

και [εβληθη]{.greek-omitted} [εκκληθει]{.greek-added} ο δρακων ο μεγας ο οφις [ο]{.greek-omitted} [ω]{.greek-added} αρχαιος ο καλουμενος διαβολος και σατανας ο πλανων την οικουμενην [ολην]{.greek-omitted} [ωλην]{.greek-added} [εβληθη]{.greek-omitted} [εκληθη]{.greek-added} εις την γην και οι αγγελοι αυτου μετ αυτου εβληθησαν[12:9]{.aside}

και ηκουσα φωνην μεγαλην εν τω [ουρανω]{.greek-abbr} λεγουσαν αρτι εγενετο η [σωτηρια]{.greek-abbr} και η δυναμις και η βασιλεια του [θεου]{.greek-abbr} ημων και [η]{.greek-omitted} [οι]{.greek-added} εξουσια του [χριστου]{.greek-abbr} αυτου οτι [εβληθη]{.greek-omitted} [εβληθι]{.greek-added} ο κατηγορος των [αδελφων]{.greek-omitted} [αδελφον]{.greek-added} ημων ο [κατηγορων]{.greek-omitted} [κατοιγορων]{.greek-added} αυτων [ενωπιον]{.greek-omitted} [ενοπιον]{.greek-added} του [θεου]{.greek-abbr} ημων ημερας και νυκτος[12:10]{.aside}

και αυτοι [ενικησαν]{.greek-omitted} [ενοικησαν]{.greek-added} [αυτον]{.greek-omitted} [αυτων]{.greek-added} δια το αιμα του αρνιου και δια τον λογον της μαρτυριας αυτων και ουκ ηγαπησαν την ψυχην αυτων αχρι θανατου[12:11]{.aside}

δια τουτο [ευφραινεσθε]{.greek-omitted} [ευφραινεσθαι]{.greek-added} [οι]{.greek-added} [ουρανοι]{.greek-abbr} και οι εν [αυτοις]{.greek-omitted} [αυτοι]{.greek-added} σκηνουντες ουαι τη γη και τη θαλασση οτι [κατεβη]{.greek-omitted} [εκατεβη]{.greek-added} ο διαβολος προς [υμας]{.greek-omitted} [ημας]{.greek-added} εχων [θυμον]{.greek-omitted} [θυμων]{.greek-added} μεγαν [ειδως]{.greek-omitted} [οιδος]{.greek-added} οτι ολιγον [καιρον]{.greek-omitted} [κερον]{.greek-added} εχει[12:12]{.aside}

και οτε [ειδεν]{.greek-omitted} [οιδεν]{.greek-added} ο δρακων οτι [εβληθη]{.greek-omitted} [εβλυθη]{.greek-added} εις την γην εδιωξεν την [γυναικα]{.greek-omitted} [γυναικαν]{.greek-added} [ητις]{.greek-omitted} [οιτις]{.greek-added} ετεκεν τον αρρενα[12:13]{.aside}

και [εδοθησαν]{.greek-omitted} [εδωθησαν]{.greek-added} τη γυναικι δυο [πτερυγες]{.greek-omitted} [πτεριγες]{.greek-added} του αετου του μεγαλου ινα [πετηται]{.greek-omitted} [πετιται]{.greek-added} εις την [ερημον]{.greek-omitted} [εριμον]{.greek-added} εις τον τοπον αυτης [οπως]{.greek-omitted} [οπος]{.greek-added} [τρεφηται]{.greek-omitted} [τρεχειται]{.greek-added} εκει [καιρον]{.greek-omitted} [κερον]{.greek-added} και [καιρους]{.greek-omitted} [κερους]{.greek-added} και [ημισυ]{.greek-omitted} [καιρου]{.greek-omitted} [ημεισι]{.greek-added} [κερου]{.greek-added} απο προσωπου του [οφεως]{.greek-omitted} [ωφεως]{.greek-added}[12:14]{.aside}

και εβαλεν ο οφις εκ του στοματος αυτου [οπισω]{.greek-omitted} [οποισω]{.greek-added} της γυναικος υδωρ [ως]{.greek-omitted} [ος]{.greek-added} [ποταμον]{.greek-omitted} [ποταμων]{.greek-added} ινα αυτην [ποταμοφορητον]{.greek-omitted} [ποταμοφωρητον]{.greek-added} [ποιηση]{.greek-omitted} [ποιησι]{.greek-added}[12:15]{.aside}

και εβοηθησεν η γη τη [γυναικι]{.greek-omitted} [γυναικη]{.greek-added} και ηνοιξεν η γη το στομα αυτης και [κατεπιενεν]{.greek-added} [κατεπιεν]{.corr} τον [ποταμον]{.greek-omitted} [ποταμων]{.greek-added} ον εβαλεν ο δρακων εκ του στοματος αυτου[12:16]{.aside}

και ωργισθη ο δρακων επι τη [γυναικι]{.greek-omitted} [γυναικη]{.greek-added} και απηλθεν [ποιησαι]{.greek-omitted} [ποιησε]{.greek-added} πολεμον μετα [των]{.greek-omitted} [τον]{.greek-added} λοιπων του σπερματος αυτης των [τηρουντων]{.greek-omitted} [τυρουντων]{.greek-added} τας εντολας του [θεου]{.greek-abbr} και [εχοντων]{.greek-omitted} [εχωντων]{.greek-added} την μαρτυριαν [ιησου]{.greek-abbr}[12:17]{.aside}

[και]{.greek-added} [εσταθην]{.greek-added} [επι]{.greek-added} [την]{.greek-added} [αμον]{.greek-added} [της]{.greek-added} [θαλασσης]{.greek-added}[12:18]{.aside}

### Chapter 13

και [εσταθην]{.greek-omitted} [επι]{.greek-omitted} [την]{.greek-omitted} [αμμον]{.greek-omitted} [της]{.greek-omitted} [θαλασσης]{.greek-omitted} [και]{.greek-omitted} [ειδον]{.greek-omitted} [οιδον]{.greek-added} εκ της θαλασσης [θηριον]{.greek-omitted} [θυριον]{.greek-added} αναβαινον [εχον]{.greek-omitted} [εχων]{.greek-added} κερατα [δεκα]{.greek-omitted} [[ι]{.greek-abbr}]{.greek-added} και κεφαλας [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} και επι των κερατων αυτου [δεκα]{.greek-omitted} [[ι]{.greek-abbr}]{.greek-added} διαδηματα και επι τας κεφαλας αυτου ονοματα βλασφημιας[13:1]{.aside}

και το [θηριον]{.greek-omitted} [θυριον]{.greek-added} ο ειδον ην [ομοιον]{.greek-omitted} [ομοιων]{.greek-added} [παρδαλει]{.greek-omitted} [παρδαλη]{.greek-added} και οι ποδες αυτου [ως]{.greek-omitted} [ος]{.greek-added} αρκου και το στομα αυτου [ως]{.greek-omitted} [ος]{.greek-added} στομα [λεοντος]{.greek-omitted} [λεωντος]{.greek-added} και εδωκεν αυτω ο [δρακων]{.greek-omitted} [δρακον]{.greek-added} την δυναμιν αυτου και τον [θρονον]{.greek-omitted} [θρονων]{.greek-added} αυτου και εξουσιαν μεγαλην[13:2]{.aside}

και μιαν εκ των κεφαλων αυτου ωσει εσφαγμενην εις θανατον και η πληγη του θανατου αυτου εθεραπευθη και εθαυμασεν ολη η γη οπισω του [θηριου]{.greek-omitted} [θυριου]{.greek-added}[13:3]{.aside}

και προσεκυνησαν τω [δρακοντι]{.greek-omitted} [δρακωντι]{.greek-added} τω [δεδωκοτι]{.greek-omitted} [δεδωμενα]{.greek-added} την εξουσιαν τω [θηριω]{.greek-omitted} [τω]{.greek-added} [θειριω]{.greek-added} και προσεκυνησαν τω [θηριω]{.greek-omitted} [θυριω]{.greek-added} λεγοντες τις [ομοιος]{.greek-omitted} [ωμοιος]{.greek-added} τω [[κυριω]{.greek-abbr}]{.greek-added} [θηριω]{.greek-omitted} [και]{.greek-omitted} τις δυνατος [πολεμησαι]{.greek-omitted} [πολεμοισαι]{.greek-added} μετ αυτου[13:4]{.aside}

και [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} αυτω στομα λαλουν μεγαλα και βλασφημιαν και [εδοθη]{.greek-omitted} [εδωθι]{.greek-added} αυτω εξουσια πολεμον ποιησαι μηνας [[μβ]{.greek-abbr}]{.greek-added} [τεσσαρακοντα]{.greek-omitted} [δυο]{.greek-omitted}[13:5]{.aside}

και [ηνοιξεν]{.greek-omitted} [οινοιξεν]{.greek-added} το στομα αυτου [εις]{.greek-omitted} [ως]{.greek-added} βλασφημιαν προς τον [θεον]{.greek-abbr} [βλασφημησαι]{.greek-omitted} [βλασφημεισαι]{.greek-added} το ονομα αυτου και την σκηνην αυτου τους εν τω [ουρανω]{.greek-abbr} [σκηνουντας]{.greek-omitted} [σκυνουντας]{.greek-added}[13:6]{.aside}

και [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} αυτω ποιησαι πολεμον μετα [των]{.greek-omitted} [τον]{.greek-added} αγιων και νικησαι αυτους και [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} αυτω [εξουσια]{.greek-omitted} [εξουσιαν]{.greek-added} επι πασαν φυλην και λαον και [λαον]{.greek-added} [και]{.greek-added} γλωσσαν και εθνος[13:7]{.aside}

και προσκυνησουσιν αυτω παντες οι κατοικουντες επι της γης [ων]{.greek-omitted} [ου]{.greek-omitted} [ον]{.greek-added} [ουτε]{.greek-added} γεγραπται το ονομα εν [τω]{.greek-omitted} [το]{.greek-added} βιβλιω της ζωης του αρνιου του [εσφαγμενου]{.greek-omitted} [εσφραγισμενου]{.greek-added} απο καταβολης κοσμου[13:8]{.aside}

ει τις εχει ους ακουσατω[13:9]{.aside}

ει τις εχει αιχμαλωσιαν [υπαγει]{.greek-omitted} [υπαγη]{.greek-added} ει τις εν μαχαιρα [αποκτενει]{.greek-omitted} [δει]{.greek-omitted} [δι]{.greek-added} αυτον [εν]{.greek-omitted} [μαχαιρα]{.greek-omitted} αποκτανθηναι ωδε εστιν η υπομονη και [η]{.greek-omitted} [πιστις]{.greek-omitted} [υπιστις]{.greek-added} των αγιων[13:10]{.aside}

και [ειδον]{.greek-omitted} [οιδον]{.greek-added} [αλλο]{.greek-omitted} [αλον]{.greek-added} [θηριον]{.greek-omitted} [θυριων]{.greek-added} [αναβαινον]{.greek-omitted} [ἀναβαίνον]{.greek-added} εκ της γης και [ειχεν]{.greek-omitted} [οιχεν]{.greek-added} κερατα [δυο]{.greek-omitted} [ομοια]{.greek-omitted} [ομια]{.greek-added} αρνιω και [ελαλει]{.greek-omitted} [ως]{.greek-omitted} [ελαλη]{.greek-added} [ος]{.greek-added} δρακων[13:11]{.aside}

και την εξουσιαν του [πρωτου]{.greek-omitted} [προτου]{.greek-added} [θηριου]{.greek-omitted} [θυριου]{.greek-added} πασαν ποιει [ενωπιον]{.greek-omitted} [ενοπιον]{.greek-added} αυτου και [εποιει]{.greek-omitted} [εποιη]{.greek-added} την γην και τους εν αυτη κατοικουντας ινα προσκυνησωσιν [τω]{.greek-added} [θυριων]{.greek-added} το [θηριον]{.greek-omitted} [το]{.greek-omitted} [πρωτον]{.greek-omitted} [προτον]{.greek-added} ου εθεραπευθη η πληγη του θανατου αυτου[13:12]{.aside}

και ποιει σημεια μεγαλα και πυρ ινα εκ του [ουρανου]{.greek-abbr} [καταβαινη]{.greek-omitted} [καταβενη]{.greek-added} επι την γην [ενωπιον]{.greek-omitted} [ενοπιον]{.greek-added} των ανθρωπων[13:13]{.aside}

και πλανα τους εμους [δουλους]{.greek-added} τους κατοικουντας επι της γης δια τα σημεια α [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} αυτω ποιησαι [ενωπιον]{.greek-omitted} [ενοπιον]{.greek-added} του [θηριου]{.greek-omitted} [θυριου]{.greek-added} λεγων τοις κατοικουσιν επι της γης ποιησαι [εικονα]{.greek-omitted} [οικονα]{.greek-added} τω [θηριω]{.greek-omitted} [θυριω]{.greek-added} [ο]{.greek-omitted} [ὃ]{.greek-added} ειχεν [την]{.greek-omitted} πληγην και εζησεν απο της μαχαιρας[13:14]{.aside}

και [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} αυτω [πνευμα]{.greek-abbr} δουναι τη [εικονι]{.greek-omitted} [οικονη]{.greek-added} του [θηριου]{.greek-omitted} [θυριου]{.greek-added} ινα και [λαληση]{.greek-omitted} [λαλησοι]{.greek-added} η [εικων]{.greek-omitted} [οικων]{.greek-added} του [θηριου]{.greek-omitted} [θυριου]{.greek-added} και [ποιηση]{.greek-omitted} [ποιησει]{.greek-added} [οσοι]{.greek-omitted} [οσει]{.greek-added} εαν [μη]{.greek-omitted} [μοι]{.greek-added} προσκυνησωσιν τη [εικονι]{.greek-omitted} [οικονη]{.greek-added} του [θηριου]{.greek-omitted} [θυριου]{.greek-added} αποκτανθωσιν[13:15]{.aside}

και [ποιει]{.greek-omitted} [πιει]{.greek-added} παντας τους μικρους και τους μεγαλους και τους [πτωχους]{.greek-added} [και]{.greek-added} [τους]{.greek-added} πλουσιους και τους [πτωχους]{.greek-omitted} [δουλους]{.greek-added} και τους ελευθερους [και]{.greek-omitted} [τους]{.greek-omitted} [δουλους]{.greek-omitted} ινα δωσωσιν αυτοις χαραγματα επι της χειρος αυτων της δεξιας η επι το [μετωπον]{.greek-omitted} [μετοπον]{.greek-added} αυτων[13:16]{.aside}

και ινα μη τις [δυναται]{.greek-omitted} [δυνατε]{.greek-added} αγορασαι η [πωλησαι]{.greek-omitted} [πολησαι]{.greek-added} ει μη ο εχων το χαραγμα το ονομα του [θηριου]{.greek-omitted} [θυριου]{.greek-added} η [τον]{.greek-omitted} [των]{.greek-added} [αριθμον]{.greek-omitted} [αριθμων]{.greek-added} του ονοματος αυτου[13:17]{.aside}

[ωδε]{.greek-omitted} [ωδαι]{.greek-added} η σοφια εστιν [ο]{.greek-omitted} [ω]{.greek-added} εχων νουν [ψηφισατω]{.greek-omitted} [ψυφισατω]{.greek-added} τον αριθμον του [θηριου]{.greek-omitted} [θυριου]{.greek-added} αριθμος γαρ [ανθρωπου]{.greek-abbr} εστιν [και]{.greek-omitted} ο αριθμος αυτου [[χξϛ]{.greek-abbr}]{.greek-added} [εστιν]{.greek-omitted} [εξακοσια]{.greek-omitted} [εξηκοντα]{.greek-omitted} [εξ]{.greek-omitted}[13:18]{.aside}

### Chapter 14

και [ειδον]{.greek-omitted} [οιδον]{.greek-added} και [ιδου]{.greek-omitted} [ειδου]{.greek-added} [το]{.greek-omitted} [τω]{.greek-added} [αρνιον]{.greek-omitted} [αρνιων]{.greek-added} εστηκος επι το [ορος]{.greek-omitted} [ωρος]{.greek-added} σιων και μετ αυτου αριθμος [[ρμδ]{.greek-abbr}]{.greek-added} [εκατον]{.greek-omitted} [τεσσαρακοντα]{.greek-omitted} [τεσσαρες]{.greek-omitted} [χιλιαδες]{.greek-omitted} [χιλιαδαις]{.greek-added} εχουσαι το ονομα αυτου και το ονομα του [πατρος]{.greek-abbr} αυτου γεγραμμενον επι [των]{.greek-omitted} [μετωπων]{.greek-omitted} [τον]{.greek-added} [μετοπον]{.greek-added} αυτων[14:1]{.aside}

και [ηκουσα]{.greek-omitted} [οικουσα]{.greek-added} φωνην εκ του [ουρανου]{.greek-abbr} ως φωνην υδατων [πολλων]{.greek-omitted} [πολων]{.greek-added} και [ως]{.greek-omitted} [ος]{.greek-added} [φωνην]{.greek-omitted} [φωνης]{.greek-added} [βροντης]{.greek-omitted} [βροντις]{.greek-added} μεγαλης και η φωνη ην ηκουσα ως [κιθαρωδων]{.greek-omitted} [κιθαρωδον]{.greek-added} [κιθαριζοντων]{.greek-omitted} [κιθαριζωντων]{.greek-added} εν ταις [κιθαραις]{.greek-omitted} [κιθαρες]{.greek-added} αυτων[14:2]{.aside}

και αδουσιν ωδην [καινην]{.greek-omitted} [κενην]{.greek-added} [ενωπιον]{.greek-omitted} [ενοπιον]{.greek-added} του [θρονου]{.greek-omitted} [θρωνου]{.greek-added} και [ενωπιον]{.greek-omitted} [ενοπιων]{.greek-added} των τεσσαρων ζωων και των [πρεσβυτερων]{.greek-omitted} [πρεσβιτερων]{.greek-added} και [ουδεις]{.greek-omitted} [ουδε]{.greek-added} [εις]{.greek-added} εδυνατο μαθειν την ωδην ει μη αι [[ρμδ]{.greek-abbr}]{.greek-added} [εκατον]{.greek-omitted} [τεσσαρακοντα]{.greek-omitted} [τεσσαρες]{.greek-omitted} [χιλιαδες]{.greek-omitted} [χιλιαδαις]{.greek-added} [οι]{.greek-omitted} [η]{.greek-added} ηγορασμενοι [απο]{.greek-omitted} [επι]{.greek-added} της γης[14:3]{.aside}

ουτοι εισιν οι μετα [γυναικων]{.greek-omitted} [γυνεκων]{.greek-added} ουκ [εμολυνθησαν]{.greek-omitted} [εμολυνθισαν]{.greek-added} παρθενοι γαρ [εισιν]{.greek-omitted} [ησιν]{.greek-added} ουτοι εισιν οι ακολουθουντες τω αρνιω οπου [αν]{.greek-omitted} [εαν]{.greek-added} υπαγη ουτοι υπο [ιησου]{.greek-abbr} ηγορασθησαν απο των [ανθρωπων]{.greek-abbr} απαρχη τω [θεω]{.greek-abbr} και τω [αρνιω]{.greek-omitted} [αρνειω]{.greek-added}[14:4]{.aside}

και ουχ [ευρεθη]{.greek-omitted} [ευρεθει]{.greek-added} εν τω στοματι αυτων ψευδος αμωμοι γαρ εισιν[14:5]{.aside}

και [ειδον]{.greek-omitted} [οιδον]{.greek-added} αγγελον [πετομενον]{.greek-omitted} [πετωμενον]{.greek-added} εν [μεσουρανηματι]{.greek-omitted} [μεσουρανιματι]{.greek-added} εχοντα ευαγγελιον αιωνιον [ευαγγελισαι]{.greek-omitted} [ευηγγελισαι]{.greek-added} τους καθημενους επι της γης και [επι]{.greek-omitted} [παν]{.greek-omitted} [επαν]{.greek-added} εθνος και φυλην και γλωσσαν και λαον[14:6]{.aside}

[λεγων]{.greek-omitted} [λεγον]{.greek-added} εν φωνη μεγαλη [φοβηθητε]{.greek-omitted} [φωβηθηται]{.greek-added} τον [κυριον]{.greek-abbr} και [δοτε]{.greek-omitted} [δοται]{.greek-added} αυτω δοξαν οτι ηλθεν η ωρα της κρισεως αυτου και [προσκυνησατε]{.greek-omitted} [προσκυνησαται]{.greek-added} αυτον τον [ποιησαντα]{.greek-omitted} [πιησαντα]{.greek-added} τον [ουρανον]{.greek-abbr} και την γην και την θαλασσαν και [πηγας]{.greek-omitted} [πυγας]{.greek-added} υδατων[14:7]{.aside}

και αλλος δευτερος αγγελος [ηκολουσεν]{.greek-added} [ηκολουθησεν]{.greek-omitted} [[ηκολουθισεν]{.corr}]{.greek-added} [λεγων]{.greek-omitted} [λεγον]{.greek-added} επεσεν [βαβυλων]{.greek-omitted} [βαβυλον]{.greek-added} η μεγαλη εκ του οινου του [θυμου]{.greek-omitted} [θειμου]{.greek-added} της πορνειας [αυτης]{.greek-omitted} [ταυτης]{.greek-added} [πεποτικεν]{.greek-omitted} [ποτικεν]{.greek-added} παντα τα εθνη[14:8]{.aside}

και [αλλος]{.greek-omitted} [αλος]{.greek-added} αγγελος τριτος ηκολουθησεν αυτοις λεγων εν φωνη μεγαλη ει τις [προσκυνει]{.greek-omitted} [προσκυνη]{.greek-added} [το]{.greek-omitted} [θηριον]{.greek-omitted} [τω]{.greek-added} [θυριων]{.greek-added} και την [εικονα]{.greek-omitted} [οικονα]{.greek-added} αυτου και λαμβανει χαραγμα επι του [μετωπου]{.greek-omitted} [μετοπου]{.greek-added} αυτου η επι την χειρα αυτου[14:9]{.aside}

και αυτος [πιεται]{.greek-omitted} [πιετε]{.greek-added} εκ του οινου του θυμου του [θεου]{.greek-abbr} του [κεκερασμενου]{.greek-omitted} [καικερασμενου]{.greek-added} ακρατου εν τω [ποτηριω]{.greek-omitted} [ποτυριω]{.greek-added} της [οργης]{.greek-omitted} [ωργης]{.greek-added} αυτου και [βασανισθησεται]{.greek-omitted} [βασανισθησετε]{.greek-added} εν πυρι και θειω [ενωπιον]{.greek-omitted} [ενοπιον]{.greek-added} των αγιων [αγγελων]{.greek-omitted} [αγγελον]{.greek-added} και [ενωπιον]{.greek-omitted} [ενοπιον]{.greek-added} του αρνιου[14:10]{.aside}

και ο καπνος του βασανισμου αυτων εις αιωνας αιωνων αναβαινει και ουκ εχουσιν αναπαυσιν ημερας και νυκτος οι προσκυνουντες το [θηριον]{.greek-omitted} [θυριων]{.greek-added} και την [εικονα]{.greek-omitted} [οικονα]{.greek-added} αυτου και ει τις λαμβανει το χαραγμα του ονοματος αυτου[14:11]{.aside}

[ωδε]{.greek-omitted} [ωδαι]{.greek-added} η υπομονη των αγιων εστιν οι [τηρουντες]{.greek-omitted} [τυρουντες]{.greek-added} τας εντολας του [θεου]{.greek-abbr} και την πιστιν [ιησου]{.greek-abbr}[14:12]{.aside}

και ηκουσα φωνης εκ του [ουρανου]{.greek-abbr} λεγουσης γραψον [μακαρο]{.greek-added} [μακαριοι]{.greek-omitted} [[μακαροι]{.corr}]{.greek-added} οι [η]{.greek-added} νεκροι οι εν [κυριω]{.greek-abbr} αποθνησκοντες [ἀπάρτι]{.greek-added} [απ]{.greek-omitted} [αρτι]{.greek-omitted} λεγει ναι το [πνευμα]{.greek-abbr} ινα [αναπαυσωνται]{.greek-omitted} [αναπαυσονται]{.greek-added} εκ των κοπων αυτων τα δε εργα αυτων [ακολουθει]{.greek-omitted} [ακολουθι]{.greek-added} μετ αυτων[14:13]{.aside}

και [ειδον]{.greek-omitted} [οιδον]{.greek-added} και [ιδου]{.greek-omitted} [οιδου]{.greek-added} νεφελη λευκη και επι την νεφελην καθημενον ομοιον [υιω]{.greek-omitted} [[υιον]{.greek-abbr}]{.greek-added} [ανθρωπου]{.greek-abbr} [εχων]{.greek-omitted} [εχον]{.greek-added} επι της κεφαλης αυτου στεφανον [χρυσουν]{.greek-omitted} [χρυσσουν]{.greek-added} και εν τη χειρι αυτου [δρεπανον]{.greek-omitted} [δρεπανων]{.greek-added} οξυ[14:14]{.aside}

και [αλλος]{.greek-omitted} [αλος]{.greek-added} αγγελος εξηλθεν εκ του ναου κραζων εν φωνη μεγαλη τω καθημενω επι της νεφελης πεμψον το δρεπανον σου και θερισον οτι ηλθεν η ωρα θερισαι οτι [εξηρανθη]{.greek-omitted} [εξυρανθη]{.greek-added} ο θερισμος της γης[14:15]{.aside}

και εβαλεν ο καθημενος επι [την]{.greek-omitted} [τη]{.greek-added} [νεφελην]{.greek-omitted} [νεφελη]{.greek-added} το δρεπανον αυτου επι την γην και εθερισθη η γη[14:16]{.aside}

και αλλος αγγελος εξηλθεν εκ του ναου του εν τω [ουρανω]{.greek-abbr} εχων και αυτος δρεπανον οξυ[14:17]{.aside}

και αλλος αγγελος εξηλθεν εκ του [θυσιαστηριου]{.greek-omitted} [θυσιαστυριου]{.greek-added} [εχων]{.greek-omitted} [εχον]{.greek-added} εξουσιαν επι του πυρος και εφωνησεν [εν]{.greek-added} κραυγη μεγαλη [τω]{.greek-omitted} [το]{.greek-added} εχοντι το δρεπανον το οξυ λεγων [πεμψον]{.greek-omitted} [πεμψω]{.greek-added} σου το δρεπανον το οξυ και [τρυγησον]{.greek-omitted} [τρυγισσον]{.greek-added} τους [βοτρυας]{.greek-omitted} [βοτριας]{.greek-added} της αμπελου της γης [οτι]{.greek-omitted} [ηκμασαν]{.greek-omitted} [αι]{.greek-omitted} [σταφυλαι]{.greek-omitted} [αυτης]{.greek-omitted}[14:18]{.aside}

και [εβαλεν]{.greek-omitted} [εξεβαλεν]{.greek-added} ο αγγελος [το]{.greek-omitted} [των]{.greek-added} δρεπανον αυτου εις την γην και [ετρυγησεν]{.greek-omitted} [ετρυγισεν]{.greek-added} την αμπελον της γης και εβαλεν εις την [ληνον]{.greek-omitted} [λυνον]{.greek-added} του θυμου του [θεου]{.greek-abbr} τον μεγαν[14:19]{.aside}

και [επατηθη]{.greek-omitted} [επατηθι]{.greek-added} η [ληνος]{.greek-omitted} [λινος]{.greek-added} εξωθεν της [πολεως]{.greek-omitted} [πολεος]{.greek-added} και εξηλθεν αιμα εκ της [ληνου]{.greek-omitted} [λινου]{.greek-added} αχρι των [χαλινων]{.greek-omitted} [χαληνων]{.greek-added} [και]{.greek-added} των ιππων απο σταδιων [[αχ]{.greek-abbr}]{.greek-added} [χιλιων]{.greek-omitted} [εξακοσιων]{.greek-omitted}[14:20]{.aside}

### Chapter 15

και [ειδον]{.greek-omitted} [οιδον]{.greek-added} [αλλο]{.greek-omitted} [αλο]{.greek-added} [σημειον]{.greek-omitted} [σιμιων]{.greek-added} εν τω [ουρανω]{.greek-abbr} μεγα και [θαυμαστον]{.greek-omitted} [θαυμαστων]{.greek-added} αγγελους επτα [εχοντας]{.greek-omitted} [εχωντας]{.greek-added} πληγας επτα τας εσχατας οτι εν αυταις ετελεσθη ο θυμος του [θεου]{.greek-abbr}[15:1]{.aside}

και [ειδον]{.greek-omitted} [οιδον]{.greek-added} [ως]{.greek-omitted} [ος]{.greek-added} θαλασσαν υαλινην μεμιγμενην πυρι και τους νικωντας εκ [του]{.greek-omitted} [θηριου]{.greek-omitted} [της]{.greek-added} [οικονος]{.greek-added} και εκ [της]{.greek-omitted} [εικονος]{.greek-omitted} [του]{.greek-added} [θυριου]{.greek-added} αυτου και εκ του αριθμου του ονοματος αυτου [εστωτας]{.greek-omitted} [εστοτας]{.greek-added} επι την θαλασσαν την [υαλινην]{.greek-omitted} [υαλυνην]{.greek-added} εχοντας [κιθαρας]{.greek-omitted} [κυθαρας]{.greek-added} του [θεου]{.greek-abbr}[15:2]{.aside}

και αδουσιν την ωδην [μωησεος]{.greek-added} [μωυσεως]{.greek-omitted} [του]{.greek-omitted} δουλου του [θεου]{.greek-abbr} και την ωδην του αρνιου λεγοντες μεγαλα και θαυμαστα τα εργα σου [κυριε]{.greek-abbr} ο [θεος]{.greek-abbr} ο [παντοκρατωρ]{.greek-omitted} [παντωκρατωρ]{.greek-added} δικαιαι και αληθιναι αι [οδοι]{.greek-omitted} [ωδι]{.greek-added} σου ο βασιλευς των εθνων[15:3]{.aside}

τις ου μη [φοβηθη]{.greek-omitted} [φωβηθει]{.greek-added} σε [κυριε]{.greek-abbr} και [δοξαση]{.greek-omitted} [δοξασοι]{.greek-added} [το]{.greek-omitted} [τω]{.greek-added} [ονομα]{.greek-omitted} [ωνομα]{.greek-added} σου οτι μονος αγιος οτι [παντες]{.greek-added} [οιξουσι]{.greek-added} [παντα]{.greek-omitted} [τα]{.greek-omitted} [εθνη]{.greek-omitted} [ηξουσιν]{.greek-omitted} και προσκυνησουσιν [ενωπιον]{.greek-omitted} [ενοπιον]{.greek-added} σου οτι τα δικαιωματα σου εφανερωθησαν[15:4]{.aside}

και μετα ταυτα [ειδον]{.greek-omitted} [οιδον]{.greek-added} και [ηνοιγη]{.greek-omitted} [οινοιγι]{.greek-added} ο ναος της σκηνης του μαρτυριου εν τω [ουρανω]{.greek-abbr}[15:5]{.aside}

και εξηλθον οι επτα αγγελοι οι εχοντες τας [επτα]{.greek-omitted} [ε]{.greek-added} [[ζ]{.greek-abbr}]{.greek-added} πληγας [εκ]{.greek-omitted} [του]{.greek-omitted} [ναου]{.greek-omitted} οι ησαν [ενδεδυμενοι]{.greek-omitted} [ενδεδημενοι]{.greek-added} [λινον]{.greek-omitted} [λυνον]{.greek-added} καθαρον λαμπρον και περιεζωσμενοι περι τα [στηθη]{.greek-omitted} [στηθει]{.greek-added} ζωνας [χρυσας]{.greek-omitted} [χρησας]{.greek-added}[15:6]{.aside}

και εν εκ των τεσσαρων ζωων εδωκεν τοις [εδωκεν]{.greek-added} [τοις]{.greek-added} επτα αγγελοις επτα φιαλας [χρυσας]{.greek-omitted} [χρησας]{.greek-added} γεμουσας του θυμου του [θεου]{.greek-abbr} του [ζωντος]{.greek-omitted} [ζωντας]{.greek-added} εις τους αιωνας των αιωνων[15:7]{.aside}

και [εγεμισθη]{.greek-omitted} [εγεμισθι]{.greek-added} ο ναος [εκ]{.greek-added} [του]{.greek-added} καπνου εκ της δοξης του [θεου]{.greek-abbr} και εκ της δυναμεως αυτου και [ουδεις]{.greek-omitted} [ουδης]{.greek-added} εδυνατο [εισελθειν]{.greek-omitted} [ησελθην]{.greek-added} εις [τον]{.greek-omitted} [το]{.greek-added} ναον αχρι τελεσθωσιν αι επτα πληγαι των επτα αγγελων[15:8]{.aside}

### Chapter 16

και [ηκουσα]{.greek-omitted} [οικουσα]{.greek-added} [μεγαλης]{.greek-added} φωνης [μεγαλης]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [ναου]{.greek-omitted} λεγουσης τοις επτα αγγελοις υπαγετε και εκχεατε τας επτα φιαλας του θυμου του [θεου]{.greek-abbr} εις την γην[16:1]{.aside}

και απηλθεν ο [πρωτος]{.greek-omitted} [προτος]{.greek-added} και εξεχεεν την φιαλην αυτου εις την γην και εγενετο ελκος κακον και πονηρον επι τους [ανθρωπους]{.greek-abbr} τους εχοντας [το]{.greek-omitted} [τα]{.greek-added} [χαραγμα]{.greek-omitted} [χαραγματα]{.greek-added} του [θηριου]{.greek-omitted} [θυριου]{.greek-added} και τους προσκυνουντας τη [εικονι]{.greek-omitted} [οικονι]{.greek-added} αυτου[16:2]{.aside}

και ο δευτερος αγγελος εξεχεεν την φιαλην αυτου εις την θαλασσαν και εγενετο αιμα [ως]{.greek-omitted} [ος]{.greek-added} νεκρου και [πασα]{.greek-omitted} [πασσα]{.greek-added} ψυχη [ζωσα]{.greek-omitted} απεθανεν εν τη θαλασση[16:3]{.aside}

και ο τριτος [αγγελος]{.greek-added} εξεχεεν την φιαλην αυτου εις τους ποταμους και εις τας πηγας των υδατων και εγενετο αιμα[16:4]{.aside}

και [ηκουσα]{.greek-omitted} [οικουσα]{.greek-added} [των]{.greek-added} [υδατων]{.greek-added} του αγγελου [των]{.greek-omitted} [υδατων]{.greek-omitted} λεγοντος δικαιος [ει]{.greek-omitted} [ο]{.greek-omitted} ων [και]{.greek-omitted} ο ην [ο]{.greek-omitted} [και]{.greek-added} [ω]{.greek-added} [ων]{.greek-added} [οσιος]{.greek-omitted} [ωσιος]{.greek-added} οτι ταυτα εκρινας[16:5]{.aside}

οτι αιμα [αγιων]{.greek-omitted} [ἀγίων]{.greek-added} και προφητων εξεχεαν και αιμα αυτοις [εδωκας]{.greek-omitted} [εδοκας]{.greek-added} πιειν [αξιοι]{.greek-omitted} [αξοιοι]{.greek-added} [εισιν]{.greek-omitted} [ησιν]{.greek-added}[16:6]{.aside}

και [ηκουσα]{.greek-omitted} [οικουσα]{.greek-added} του [θυσιαστηριου]{.greek-omitted} [θυσιαστυριου]{.greek-added} λεγοντος ναι [κυριε]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ αληθιναι και δικαιαι αι [κρισεις]{.greek-omitted} [κρισις]{.greek-added} σου[16:7]{.aside}

και ο τεταρτος αγγελος εξεχεεν την φιαλην αυτου επι τον ηλιον και [εδοθη]{.greek-omitted} [εδωθι]{.greek-added} αυτω καυματισαι εν πυρι τους [ανθρωπους]{.greek-abbr}[16:8]{.aside}

και εκαυματισθησαν οι [ανθρωποι]{.greek-abbr} καυμα μεγα και [εβλασφημησαν]{.greek-omitted} [εβλασφημισαν]{.greek-added} οι [ανθρωποι]{.greek-abbr} το ονομα του [θεου]{.greek-abbr} του εχοντος εξουσιαν επι τας πληγας ταυτας και ου [μετενοησαν]{.greek-omitted} [μετενωησαν]{.greek-added} δουναι αυτω δοξαν[16:9]{.aside}

και ο πεμπτος [αγγελος]{.greek-added} εξεχεεν την φιαλην αυτου επι τον [θρονον]{.greek-omitted} [θρονων]{.greek-added} του [θηριου]{.greek-omitted} [θυριου]{.greek-added} και εγενετο η βασιλεια αυτου [εσκοτωμενη]{.greek-omitted} [εσκοτωμενονης]{.greek-added} και εμασωντο τας [γλωσσας]{.greek-omitted} [γλωσας]{.greek-added} αυτων εκ του πονου[16:10]{.aside}

και εβλασφημησαν τον [θεον]{.greek-abbr} του [ουρανου]{.greek-abbr} εκ των πονων αυτων και εκ των ελκων αυτων και ου μετενοησαν εκ των εργων αυτων[16:11]{.aside}

και ο εκτος [αγγελος]{.greek-added} εξεχεεν [αυτου]{.greek-added} την φιαλην [αυτου]{.greek-omitted} επι τον [ποταμον]{.greek-omitted} [ποταμων]{.greek-added} τον μεγαν ευφρατην και εξηρανθη το υδωρ αυτου ινα [ετοιμασθη]{.greek-omitted} [ετοιμασθει]{.greek-added} η οδος των βασιλεων των απο ανατολης ηλιου[16:12]{.aside}

και [ειδον]{.greek-omitted} [οιδον]{.greek-added} εκ του στοματος του [δρακοντος]{.greek-omitted} [δρακκωντος]{.greek-added} και εκ του στοματος του [θηριου]{.greek-omitted} [θυριου]{.greek-added} και εκ του στοματος του ψευδοπροφητου [πνευματα]{.greek-abbr} ακαθαρτα τρια [ως]{.greek-omitted} [ος]{.greek-added} [βατραχοι]{.greek-omitted} [βατραχι]{.greek-added}[16:13]{.aside}

[εισιν]{.greek-omitted} [εισι]{.greek-added} γαρ [πνευματα]{.greek-abbr} [δαιμονιων]{.greek-omitted} [δαιμονιον]{.greek-added} ποιουντα σημεια α εκπορευεται επι τους βασιλεις της οικουμενης [ολης]{.greek-omitted} [ωλης]{.greek-added} συναγαγειν αυτους εις τον [πολεμον]{.greek-omitted} [πολεμων]{.greek-added} της ημερας εκεινης της μεγαλης του [θεου]{.greek-abbr} του παντοκρατορος[16:14]{.aside}

[ιδου]{.greek-omitted} [οιδου]{.greek-added} ερχομαι ως κλεπτης μακαριος ο γρηγορων και [τηρων]{.greek-omitted} [κατ]{.greek-added} [οιων]{.greek-added} τα [ιμαται]{.greek-added} [ιματια]{.corr} αυτου ινα μη [γυμνος]{.greek-omitted} [γιμνος]{.greek-added} περιπατη και βλεπωσιν την ασχημοσυνην αυτου[16:15]{.aside}

και συνηγαγεν αυτους εις τον τοπον τον [καλουμεν]{.greek-added} [καλουμενον]{.corr} εβραιστι [αρμαγεδων]{.greek-omitted} [μαγεδῶν]{.greek-added}[16:16]{.aside}

και ο εβδομος [αγγελος]{.greek-added} εξεχεεν την φιαλην αυτου επι τον αερα και εξηλθεν φωνη μεγαλη απο του ναου του [ουρανου]{.greek-abbr} απο του [θρονου]{.greek-omitted} [θρωνου]{.greek-added} λεγουσα γεγονεν[16:17]{.aside}

και [εγενοντο]{.greek-omitted} [εγενωντο]{.greek-added} αστραπαι και βρονται και φωναι και [σεισμος]{.greek-omitted} [σισμος]{.greek-added} μεγας οιος ουκ εγενετο αφ ου οι [ανθρωποι]{.greek-abbr} [εγενοντο]{.greek-omitted} [εγενετο]{.greek-added} επι [της]{.greek-omitted} [τοις]{.greek-added} γης [τηλικουτος]{.greek-omitted} [τιλικουτο]{.greek-added} [σεισμος]{.greek-omitted} [σισμος]{.greek-added} [ουτως]{.greek-omitted} [ουτω]{.greek-added} μεγας[16:18]{.aside}

και εγενετο η πολις η μεγαλη εις τρια [μερη]{.greek-omitted} [μερι]{.greek-added} και [αι]{.greek-omitted} [ε]{.greek-added} [πολεις]{.greek-omitted} [πολις]{.greek-added} των εθνων επεσον και [βαβυλων]{.greek-omitted} [βαβυλον]{.greek-added} η μεγαλη εμνησθη [ενωπιον]{.greek-omitted} [ενοπιον]{.greek-added} του [θεου]{.greek-abbr} δουναι αυτη [το]{.greek-omitted} ποτηριον του οινου του θυμου της [οργης]{.greek-omitted} [ωργης]{.greek-added} αυτου[16:19]{.aside}

και [πασα]{.greek-omitted} [πασσα]{.greek-added} νησος εφυγεν και [ορη]{.greek-omitted} [ωρη]{.greek-added} ουχ ευρεθησαν[16:20]{.aside}

και χαλαζα μεγαλη ως ταλαντιαια [καταβαινει]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [επι]{.greek-omitted} [τους]{.greek-omitted} [ανθρωπους]{.greek-omitted} και εβλασφημησαν οι [ανθρωποι]{.greek-abbr} τον [θεον]{.greek-abbr} εκ της πληγης της χαλαζης οτι μεγαλη εστιν η πληγη [αυτης]{.greek-omitted} [αυτη]{.greek-added} σφοδρα[16:21]{.aside}

### Chapter 17

και ηλθεν εις εκ των [επτα]{.greek-omitted} [ε[ζ]{.greek-abbr}]{.greek-added} αγγελων των [εχων]{.greek-added} [εχοντων]{.greek-omitted} [[εχωντων]{.corr}]{.greek-added} τας [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} φιαλας και ελαλησεν μετ εμου λεγων δευρο [διξωσι]{.greek-added} [τω]{.greek-added} [δειξω]{.greek-omitted} [σοι]{.greek-omitted} [το]{.greek-omitted} κριμα της πορνης της μεγαλης της [καθημενης]{.greek-omitted} [καθημενοις]{.greek-added} επι των υδατων των [πολλων]{.greek-omitted} [πολων]{.greek-added}[17:1]{.aside}

μεθ ης επορνευσαν οι βασιλεις της γης και εμεθυσθησαν οι κατοικουντες την γην εκ του οινου της πορνειας αυτης[17:2]{.aside}

και απηνεγκεν [με]{.corr} εις ερημον [εν]{.greek-omitted} [πνευματι]{.greek-abbr} και [ειδον]{.greek-omitted} [οιδον]{.greek-added} γυναικα [καθημενην]{.greek-omitted} [καθηεμενην]{.greek-added} επι [θηριον]{.greek-omitted} [θυριον]{.greek-added} [το]{.greek-added} [κοκκινον]{.greek-omitted} [κοκινον]{.greek-added} γεμον ονοματα βλασφημιας εχον κεφαλας επτα και κερατα δεκα[17:3]{.aside}

και η [γυνη]{.greek-omitted} [γυνι]{.greek-added} [ην]{.greek-omitted} [ἧν]{.greek-added} περιβεβλημενη πορφυρουν και [κοκκινον]{.greek-omitted} [κοκινον]{.greek-added} [κεχρυσωμενη]{.greek-omitted} [κεχρησσομενη]{.greek-added} [χρησι]{.greek-added} [χρυσιω]{.greek-omitted} [[χρησιω]{.corr}]{.greek-added} και λιθω τιμιω και μαργαριταις εχουσα ποτηριον [χρυσουν]{.greek-omitted} [χρησουν]{.greek-added} εν τη χειρι αυτης γεμον [βδελυγματων]{.greek-omitted} [βδελλιγματων]{.greek-added} και τα ακαθαρτα της πορνειας [αυτης]{.greek-omitted} [της]{.greek-added} [γης]{.greek-added}[17:4]{.aside}

και επι το [μετωπον]{.greek-omitted} [μετοπον]{.greek-added} αυτης ονομα [γεγραμμενον]{.greek-omitted} [γεγραμενον]{.greek-added} [μυστηριον]{.greek-omitted} [μυστυριων]{.greek-added} βαβυλων η μεγαλη η [μητηρ]{.greek-abbr} των [πορνων]{.greek-omitted} [πόρνων]{.greek-added} και των [βδελυγματων]{.greek-omitted} [βδελιγματων]{.greek-added} της γης[17:5]{.aside}

και [ειδον]{.greek-omitted} [οιδων]{.greek-added} την γυναικα μεθυουσαν [εκ]{.greek-omitted} του αιματος των αγιων εκ του αιματος των μαρτυρων [ιησου]{.greek-abbr} και [εθαυμασα]{.greek-omitted} [εθαυμασαν]{.greek-added} [ιδων]{.greek-omitted} [οιδων]{.greek-added} αυτην θαυμα μεγα[17:6]{.aside}

και [ειπεν]{.greek-omitted} [οιπεν]{.greek-added} μοι [ο]{.greek-omitted} [ω]{.greek-added} αγγελος δια τι εθαυμασας εγω ερω σοι [το]{.greek-omitted} [τω]{.greek-added} [μυστηριον]{.greek-omitted} [μυστυριον]{.greek-added} της γυναικος και του [θηριου]{.greek-omitted} [θυριου]{.greek-added} του [βασταζοντος]{.greek-omitted} [βασταζωντος]{.greek-added} αυτην του εχοντος τας [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} κεφαλας και τα [δεκα]{.greek-omitted} [[ι]{.greek-abbr}]{.greek-added} κερατα[17:7]{.aside}

το [θηριον]{.greek-omitted} [θυριον]{.greek-added} ο [ειδες]{.greek-omitted} [ειδαις]{.greek-added} ην και ουκ εστιν και [μελλει]{.greek-omitted} [μελει]{.greek-added} αναβαινειν εκ της [αβυσσου]{.greek-omitted} [αβυσου]{.greek-added} και εις [απωλειαν]{.greek-omitted} [απολιαν]{.greek-added} υπαγειν και [θαυμασονται]{.greek-omitted} [θαυμασωνται]{.greek-added} οι κατοικουντες [την]{.greek-added} [γην]{.greek-added} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} ων ου γεγραπται [τα]{.greek-omitted} [το]{.greek-added} [ονοματα]{.greek-omitted} [ονομα]{.greek-added} επι [το]{.greek-omitted} [του]{.greek-added} [βιβλιον]{.greek-omitted} [βιβλιου]{.greek-added} της ζωης απο καταβολης κοσμου βλεποντων οτι ην το [θηριον]{.greek-omitted} [θυριων]{.greek-added} και ουκ εστιν και [παρεσται]{.greek-omitted} [παρεστε]{.greek-added}[17:8]{.aside}

[ωδε]{.greek-omitted} [ωδαι]{.greek-added} ο νους ο εχων σοφιαν αι επτα κεφαλαι επτα [ορη]{.greek-omitted} [εισιν]{.greek-omitted} [ωρη]{.greek-added} [ησιν]{.greek-added} οπου [η]{.greek-omitted} [ει]{.greek-added} γυνη καθηται επ αυτων [και]{.greek-added} [βασιλεις]{.greek-added} [εισιν]{.greek-added} [επτα]{.greek-added}[17:9]{.aside}

[και]{.greek-omitted} [βασιλεις]{.greek-omitted} [εισιν]{.greek-omitted} [επτα]{.greek-omitted} οι [πεντε]{.greek-omitted} [πεντ]{.greek-added} [επι]{.greek-added} [σον]{.greek-added} [επεσον]{.corr} ο εις εστιν ο [αλλος]{.greek-omitted} [αλος]{.greek-added} [ουπω]{.greek-omitted} [ουπο]{.greek-added} ηλθεν και οταν [ελθη]{.greek-omitted} [ελθι]{.greek-added} ολιγον [δει]{.greek-omitted} [δι]{.greek-added} αυτον [μειναι]{.greek-omitted} [μηναι]{.greek-added}[17:10]{.aside}

και το [θηριον]{.greek-omitted} [θυριων]{.greek-added} ο ην και ουκ εστιν και [ου]{.greek-added} [αυτος]{.greek-omitted} [τος]{.greek-added} [ογδοος]{.greek-omitted} [ωγδωος]{.greek-added} εστιν και εκ των επτα εστιν και εις [απωλειαν]{.greek-omitted} [απολειαν]{.greek-added} υπαγει[17:11]{.aside}

[και]{.greek-omitted} τα δεκα κερατα α ειδες δεκα βασιλεις [εισιν]{.greek-omitted} [ησιν]{.greek-added} οιτινες βασιλειαν ουπω [ελαβον]{.greek-omitted} [ελαβων]{.greek-added} αλλ εξουσιαν ως βασιλεις μιαν ωραν [λαμβανουσιν]{.greek-omitted} [λαμβανουσι]{.greek-added} μετα του [θηριου]{.greek-omitted} [θυριου]{.greek-added}[17:12]{.aside}

ουτοι μιαν [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} γνωμην και την δυναμιν και [την]{.greek-omitted} εξουσιαν αυτων τω [θηριω]{.greek-omitted} [θυριω]{.greek-added} [διδοασιν]{.greek-omitted} [διδωασιν]{.greek-added}[17:13]{.aside}

ουτοι μετα του αρνιου πολεμησουσιν και το [αρνιον]{.greek-omitted} [αρνιων]{.greek-added} [νικησει]{.greek-omitted} [νικηση]{.greek-added} αυτους οτι [κυριος]{.greek-abbr} κυριων εστιν και βασιλευς βασιλεων και οι μετ αυτου κλητοι και εκλεκτοι και πιστοι[17:14]{.aside}

και λεγει μοι τα υδατα α ειδες ου η πορνη καθηται λαοι και οχλοι εισιν και εθνη και [γλωσσαι]{.greek-omitted} [γλωσσαις]{.greek-added}[17:15]{.aside}

και τα δεκα κερατα α ειδες και το [θηριον]{.greek-omitted} [θυριον]{.greek-added} ουτοι [μισησουσιν]{.greek-omitted} [μισισουσιν]{.greek-added} την πορνην και [ηρημωμενην]{.greek-omitted} [ηροιμωμενην]{.greek-added} ποιησουσιν αυτην και [γυμνην]{.greek-omitted} [γιμνην]{.greek-added} ποιησουσιν αυτην και τας σαρκας αυτης φαγονται και αυτην κατακαυσουσιν εν πυρι[17:16]{.aside}

ο γαρ [θεος]{.greek-abbr} εδωκεν [εις]{.greek-omitted} [τας]{.greek-omitted} [αυτας]{.greek-added} καρδιας αυτων [ποιησαι]{.greek-omitted} [πιησε]{.greek-added} την γνωμην αυτου και [ποιησαι]{.greek-omitted} [ποιησε]{.greek-added} [γνωμην]{.greek-omitted} [γνωμιν]{.greek-added} μιαν και δουναι την βασιλειαν αυτων τω [θηριω]{.greek-omitted} [θυριω]{.greek-added} αχρι τελεσθωσιν οι λογοι του [θεου]{.greek-abbr}[17:17]{.aside}

και η [γυνη]{.greek-omitted} [γυνι]{.greek-added} ην [ειδες]{.greek-omitted} [οιδες]{.greek-added} εστιν [η]{.greek-omitted} [οι]{.greek-added} πολις η μεγαλη η εχουσα βασιλειαν επι των βασιλεων [επι]{.greek-added} της γης[17:18]{.aside}

### Chapter 18

μετα ταυτα ειδον αλλον αγγελον καταβαινοντα εκ του [ουρανου]{.greek-abbr} εχοντα εξουσιαν μεγαλην και η γη εφωτισθη εκ της [δοξης]{.greek-omitted} [δωξης]{.greek-added} αυτου[18:1]{.aside}

και εκραξεν [ισχυρα]{.greek-omitted} [ησχυραν]{.greek-added} [φωνη]{.greek-omitted} [φωνην]{.greek-added} λεγων επεσεν βαβυλων η μεγαλη και εγενετο [κατοικητηριον]{.greek-omitted} [κατοικοιτυριων]{.greek-added} δαιμονων και φυλακη παντος [πνευματος]{.greek-abbr} ακαθαρτου και φυλακη παντος [ορνεου]{.greek-omitted} [ωρνεου]{.greek-added} ακαθαρτου και [μεμισημενου]{.greek-omitted} [μεμησιμενου]{.greek-added}[18:2]{.aside}

οτι εκ του οινου του θυμου της πορνειας αυτης [πεπτωκασιν]{.greek-omitted} [πεπωκασιν]{.greek-added} παντα τα εθνη και οι βασιλεις της γης μετ αυτης επορνευσαν και οι εμποροι της γης εκ της δυναμεως του στρηνους αυτης [επλουτησαν]{.greek-omitted} [επλουτισαν]{.greek-added}[18:3]{.aside}

και ηκουσα αλλην φωνην εκ του [ουρανου]{.greek-abbr} λεγουσαν εξελθε εξ αυτης ο λαος μου ινα μη [συγκοινωνησητε]{.greek-omitted} [κοινωνοισητε]{.greek-added} ταις αμαρτιαις αυτης και εκ των πληγων αυτης ινα μη [λαβητε]{.greek-omitted} [λαβηται]{.greek-added}[18:4]{.aside}

οτι [εκολληθησαν]{.greek-omitted} [αικολασθισαν]{.greek-added} αυτης αι αμαρτιαι αχρι του [ουρανου]{.greek-abbr} και εμνημονευσεν [αυτης]{.greek-added} ο [θεος]{.greek-abbr} τα αδικηματα αυτης[18:5]{.aside}

[αποδοτε]{.greek-omitted} [αποδωται]{.greek-added} αυτη [ως]{.greek-omitted} [ος]{.greek-added} και [αυτη]{.greek-omitted} [αυτοι]{.greek-added} απεδωκεν και [διπλωσατε]{.greek-omitted} [διπλωσαται]{.greek-added} [αυτη]{.greek-omitted} [τα]{.greek-added} διπλα [ος]{.greek-added} [και]{.greek-added} [αυτοι]{.greek-added} [και]{.greek-added} κατα τα εργα αυτης εν τω ποτηριω [αυτης]{.greek-added} ω εκερασεν [κερασατε]{.greek-omitted} [κερασαται]{.greek-added} [αυτη]{.greek-omitted} [αυτην]{.greek-added} διπλουν[18:6]{.aside}

οσα εδοξασεν αυτην και [εστρηνιασεν]{.greek-omitted} [εστρινιασεν]{.greek-added} τοσουτον [δοτε]{.greek-omitted} [δοται]{.greek-added} [αυτη]{.greek-omitted} [αυτην]{.greek-added} βασανισμον και πενθος οτι εν τη καρδια αυτης λεγει οτι [καθημαι]{.greek-omitted} [καθος]{.greek-added} [βασιλισσα]{.greek-omitted} [βασιλεισα]{.greek-added} και [χηρα]{.greek-omitted} [χειρα]{.greek-added} ουκ ειμι και πενθος ου μη [ιδω]{.greek-omitted} [οιδων]{.greek-added}[18:7]{.aside}

δια τουτο εν μια ημερα ηξουσιν αι πληγαι αυτης θανατος [και]{.greek-omitted} πενθος και λιμος και εν πυρι κατακαυθησεται οτι ισχυρος [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο κρινας αυτην[18:8]{.aside}

και κλαυσουσιν [και]{.greek-omitted} [κοψονται]{.greek-omitted} επ αυτην οι βασιλεις της γης οι μετ αυτης πορνευσαντες και [στρηνιασαντες]{.greek-omitted} [στρινιασσαντες]{.greek-added} οταν [βλεπωσιν]{.greek-omitted} [τον]{.greek-omitted} [βλεποντες]{.greek-added} [των]{.greek-added} [καπνον]{.greek-omitted} [καπνων]{.greek-added} της πυρωσεως αυτης[18:9]{.aside}

απο [μακροθεν]{.greek-omitted} [μακρωθεν]{.greek-added} [εστηκοτες]{.greek-omitted} [εστηκωτες]{.greek-added} δια τον [φοβον]{.greek-omitted} [φωβον]{.greek-added} του βασανισμου αυτης λεγοντες ουαι ουαι [η]{.greek-omitted} [υ]{.greek-added} πολις η μεγαλη βαβυλων η πολις [η]{.greek-omitted} [ι]{.greek-added} [ισχυρα]{.greek-omitted} [ησχυρα]{.greek-added} οτι μια ωρα ηλθεν η [κρισις]{.greek-omitted} [κρισσις]{.greek-added} σου[18:10]{.aside}

και [οι]{.greek-omitted} [η]{.greek-added} εμποροι της γης κλαυσουσιν και [πενθησουσιν]{.greek-omitted} [πενθυσουσιν]{.greek-added} επ [αυτη]{.greek-omitted} [αυτην]{.greek-added} οτι τον γομον [αυτων]{.greek-omitted} [αυτον]{.greek-added} ουδεις [αγοραζει]{.greek-omitted} [αγοραζη]{.greek-added} ουκετι[18:11]{.aside}

γομον [χρυσου]{.greek-omitted} [χρσου]{.greek-added} και αργυρου και λιθου τιμιου και μαργαριτου και βυσσινου και [πορφυρου]{.greek-omitted} [πορφηρου]{.greek-added} και [σηρικου]{.greek-omitted} [συρικου]{.greek-added} και [κοκκινου]{.greek-omitted} [κκοκινου]{.greek-added} και παν ξυλον [θυινον]{.greek-omitted} [θυηνον]{.greek-added} και παν σκευος ελεφαντινον και παν σκευος εκ ξυλου [τιμιωτατου]{.greek-omitted} [τιμιωττατου]{.greek-added} και χαλκου και [σιδηρου]{.greek-omitted} [σηδηρου]{.greek-added} και μαρμαρου[18:12]{.aside}

και [κιναμωμον]{.greek-omitted} [κιναμομου]{.greek-added} και θυμιαματα και [μυρον]{.greek-omitted} [μμυρων]{.greek-added} και [λιβανον]{.greek-omitted} [λυβανον]{.greek-added} και [οινον]{.greek-omitted} [ελεον]{.greek-added} και [ελαιον]{.greek-omitted} [και]{.greek-omitted} [σεμιδαλιν]{.greek-omitted} [σεμιδαλην]{.greek-added} και σιτον και προβατα και [κτηνη]{.greek-omitted} [κτινι]{.greek-added} και ιππων και ραιδων και σωματων και ψυχας [ανθρωπων]{.greek-abbr}[18:13]{.aside}

και η [οπωρα]{.greek-omitted} [οπορα]{.greek-added} της επιθυμιας της ψυχης σου απηλθεν απο σου και παντα τα [λιπαρα]{.greek-omitted} [ληπαρα]{.greek-added} και τα λαμπρα [απωλετο]{.greek-omitted} [απολετο]{.greek-added} απο σου και ουκετι αυτα ου μη [ευρης]{.greek-omitted} [ευρις]{.greek-added}[18:14]{.aside}

οι εμποροι τουτων οι πλουτησαντες απ αυτης απο μακροθεν στησονται δια τον [φοβον]{.greek-omitted} [φωβον]{.greek-added} του βασανισμου αυτης [κλαιοντες]{.greek-omitted} [και]{.greek-added} [κλεωντες]{.greek-added} και πενθουντες[18:15]{.aside}

[και]{.greek-omitted} λεγοντες ουαι [ουαι]{.greek-omitted} η [πολις]{.greek-omitted} [πολης]{.greek-added} η μεγαλη η [περιβεβλημενη]{.greek-omitted} [περιβεβλιμενοι]{.greek-added} [βυσσινον]{.greek-omitted} [βυσσον]{.greek-added} και πορφυρουν και [κοκκινον]{.greek-omitted} [κοκκινων]{.greek-added} και [κεχρυσωμενη]{.greek-omitted} [χρυσομενη]{.greek-added} [χρυσιω]{.greek-omitted} [χρησιω]{.greek-added} και λιθω τιμιω και μαργαριταις[18:16]{.aside}

οτι μια ωρα ηρημωθη ο τοσουτος πλουτος και πας [κυβερνητης]{.greek-omitted} [κυβερνητις]{.greek-added} και πας ο επι τοπον [πλεων]{.greek-omitted} [πλεον]{.greek-added} και ναυται και [οσοι]{.greek-omitted} [ωσοι]{.greek-added} την θαλασσαν [εργαζονται]{.greek-omitted} [εργαζωνται]{.greek-added} απο [μακροθεν]{.greek-omitted} [μακρωθεν]{.greek-added} εστησαν[18:17]{.aside}

και [εκραζον]{.greek-omitted} [εκραζων]{.greek-added} βλεποντες [τον]{.greek-omitted} [των]{.greek-added} [καπνον]{.greek-omitted} [καπνων]{.greek-added} της πυρωσεως αυτης λεγοντες τις ομοια τη [πολει]{.greek-omitted} [πολη]{.greek-added} τη μεγαλη[18:18]{.aside}

και εβαλον χουν επι τας κεφαλας αυτων και [εκραζον]{.greek-omitted} [εκραζων]{.greek-added} [κλαιοντες]{.greek-omitted} [κλεωντες]{.greek-added} και πενθουντες και λεγοντες ουαι ουαι η [πολις]{.greek-omitted} [πολης]{.greek-added} η μεγαλη εν [η]{.greek-omitted} [οι]{.greek-added} [επλουτησαν]{.greek-omitted} [επλουτισαν]{.greek-added} παντες οι εχοντες τα [πλοια]{.greek-omitted} [πληα]{.greek-added} εν τη θαλασση εκ της [τιμιοτητος]{.greek-omitted} [τιμιωτητος]{.greek-added} αυτης οτι μια ωρα [ηρημωθη]{.greek-omitted} [ηρημωθι]{.greek-added}[18:19]{.aside}

ευφραινου επ αυτη [ουρανε]{.greek-abbr} και οι αγιοι και οι αποστολοι και οι προφηται οτι εκρινεν ο [θεος]{.greek-abbr} το κριμα [υμων]{.greek-omitted} [ημων]{.greek-added} εξ αυτης[18:20]{.aside}

και ηρεν εις αγγελος ισχυρος λιθον [ως]{.greek-omitted} [ος]{.greek-added} [μυλον]{.greek-omitted} [μιλον]{.greek-added} μεγαν και εβαλεν εις την θαλασσαν [λεγων]{.greek-omitted} [λεγον]{.greek-added} ουτως [ορμηματι]{.greek-omitted} [ωρμηματι]{.greek-added} [βληθησεται]{.greek-omitted} [βλιθησεται]{.greek-added} [βαβυλων]{.greek-omitted} [βαβυλον]{.greek-added} η μεγαλη πολις και ου μη ευρεθη ετι[18:21]{.aside}

[και]{.greek-omitted} [η]{.greek-added} φωνη κιθαρωδων και μουσικων και [αυλητων]{.greek-omitted} [αυλιτων]{.greek-added} και σαλπιστων ου μη ακουσθη εν σοι ετι και πας τεχνιτης πασης τεχνης ου μη ευρεθη εν σοι ετι και φωνη μυλου ου μη ακουσθη εν σοι ετι[18:22]{.aside}

και φως [λυχνου]{.greek-omitted} [λιχνου]{.greek-added} ου μη [φανη]{.greek-omitted} [φανῆ]{.greek-added} εν σοι ετι και φωνη νυμφιου και νυμφης ου μη ακουσθη εν σοι ετι [οτι]{.greek-omitted} οι εμποροι [σου]{.corr} [ησαν]{.greek-omitted} [οισαν]{.greek-added} οι [μεγιστανες]{.greek-omitted} [μεγισταναις]{.greek-added} της γης οτι εν τη [φαρμακεια]{.greek-omitted} [φαρμακια]{.greek-added} σου επλανηθησαν παντα τα εθνη[18:23]{.aside}

και εν αυτη αιματα προφητων και αγιων ευρεθη και παντων των [εσφαγμενων]{.greek-omitted} [εσφαγμενον]{.greek-added} επι της γης[18:24]{.aside}

### Chapter 19

μετα ταυτα [ηκουσα]{.greek-omitted} [οικουσα]{.greek-added} ως φωνην μεγαλην [οχλου]{.greek-omitted} [ωχλου]{.greek-added} πολλου εν τω [ουρανω]{.greek-abbr} λεγοντων [αλληλουια]{.greek-omitted} [ἀλληλοῦια]{.greek-added} η [σωτηρια]{.greek-abbr} και η δυναμις και η δοξα του [θεου]{.greek-abbr} ημων[19:1]{.aside}

οτι [αληθιναι]{.greek-omitted} [αληθειναι]{.greek-added} και δικαιαι αι [κρισεις]{.greek-omitted} [κρισις]{.greek-added} αυτου οτι [εκρινεν]{.greek-omitted} [εκριν]{.greek-added} την πορνην την μεγαλην ητις [δι]{.greek-added} [διεφθειρεν]{.greek-omitted} [εφθειρεν]{.greek-added} την γην εν τη πορνεια αυτης και εξεδικησεν το αιμα των δουλων [αυτου]{.greek-omitted} [αυτων]{.greek-added} εκ χειρος αυτης[19:2]{.aside}

και [δευτερον]{.greek-omitted} [δευτερων]{.greek-added} [ειρηκεν]{.greek-omitted} [ηρηκεν]{.greek-added} αλληλουια και ο καπνος αυτης [αναβαινει]{.greek-omitted} [ανεβη]{.greek-added} εις τους αιωνας των αιωνων[19:3]{.aside}

και [επεσον]{.greek-omitted} [επεσων]{.greek-added} οι [πρεσβυτεροι]{.greek-omitted} [πρεσβιτεροι]{.greek-added} οι [[κδ]{.greek-abbr}]{.greek-added} [εικοσι]{.greek-omitted} [τεσσαρες]{.greek-omitted} και τα [τεσσαρα]{.greek-omitted} [[δ]{.greek-abbr}]{.greek-added} ζωα και προσεκυνησαν τω [θεω]{.greek-abbr} τω καθημενω επι [του]{.greek-omitted} [θρονου]{.greek-omitted} [τω]{.greek-added} [θρωνω]{.greek-added} λεγοντες αμην αλληλουια[19:4]{.aside}

και φωνη απο του [θρονου]{.greek-omitted} [θρωνου]{.greek-added} εξηλθεν λεγουσα αινειτε τον [θεον]{.greek-omitted} [[κυριον]{.greek-abbr}]{.greek-added} ημων παντες οι δουλοι αυτου και οι φοβουμενοι αυτον οι [μικροι]{.greek-omitted} [μικρι]{.greek-added} και οι μεγαλοι[19:5]{.aside}

και ηκουσα [ως]{.greek-omitted} [ος]{.greek-added} φωνην [οχλου]{.greek-omitted} [ωχλου]{.greek-added} [πολλου]{.greek-omitted} [πολου]{.greek-added} και [ως]{.greek-omitted} [ος]{.greek-added} φωνην υδατων [πολλων]{.greek-omitted} [πολων]{.greek-added} και [ως]{.greek-omitted} [ος]{.greek-added} φωνην βροντων ισχυρων λεγοντες αλληλουια οτι εβασιλευσεν [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ημων ο [παντοκρατωρ]{.greek-omitted} [παντωκρατορ]{.greek-added}[19:6]{.aside}

χαιρωμεν και [αγαλλιωμεν]{.greek-added} [αγαλλιωμεθα]{.corr} και δωμεν την δοξαν αυτω οτι ηλθεν ο [γαμος]{.greek-omitted} [γαμως]{.greek-added} του αρνιου και η γυνη αυτου [ητοιμασεν]{.greek-omitted} [ητιμασεν]{.greek-added} [αι]{.greek-added} [εαυτην]{.greek-omitted} [αυτην]{.greek-added}[19:7]{.aside}

και [εδοθη]{.greek-omitted} [εδωθι]{.greek-added} αυτη ινα περιβαληται βυσσινον [λαμπρον]{.greek-omitted} [λαμπρων]{.greek-added} και [καθαρον]{.greek-omitted} [καθαρων]{.greek-added} [το]{.greek-omitted} [τω]{.greek-added} γαρ βυσσινον τα δικαιωματα των αγιων εστιν[19:8]{.aside}

και λεγει μοι γραψον [μακαριοι]{.greek-omitted} [μακαροι]{.greek-added} οι [η]{.greek-added} εις το δειπνον του γαμου του αρνιου [κεκλημενοι]{.greek-omitted} [κεκλημενη]{.greek-added} και λεγει μοι ουτοι οι λογοι [αληθινοι]{.greek-omitted} [αληθηνοι]{.greek-added} του [θεου]{.greek-abbr} εισιν[19:9]{.aside}

και επεσα εμπροσθεν των ποδων αυτου προσκυνησαι αυτω και λεγει μοι [ορα]{.greek-omitted} [ωρα]{.greek-added} μη συνδουλος σου ειμι και των αδελφων σου των [εχοντων]{.greek-omitted} [εχωντων]{.greek-added} [την]{.greek-omitted} μαρτυριαν [ιησου]{.greek-abbr} τω [θεω]{.greek-abbr} προσκυνησον η γαρ μαρτυρια του [ιησου]{.greek-abbr} εστιν το [πνευμα]{.greek-abbr} της [προφητειας]{.greek-omitted} [προφητιας]{.greek-added}[19:10]{.aside}

και ειδον τον [ουρανον]{.greek-abbr} ανεωγμενον και ιδου [ιππος]{.greek-omitted} [ιππως]{.greek-added} λευκος και ο καθημενος επ [αυτον]{.greek-omitted} [αυτων]{.greek-added} καλουμενος πιστος και αληθινος και εν δικαιοσυνη κρινει και πολεμει[19:11]{.aside}

οι [δε]{.greek-omitted} [δαι]{.greek-added} οφθαλμοι αυτου φλοξ πυρος και επι την κεφαλην αυτου διαδηματα [πολλα]{.greek-omitted} [πολα]{.greek-added} εχων ονοματα [γεγραμμενα]{.greek-omitted} [γεγραμενα]{.greek-added} και ονομα γεγραμμενον ο ουδεις οιδεν ει μη αυτος[19:12]{.aside}

και [περιβεβλημενος]{.greek-omitted} [περιβεβλιμενος]{.greek-added} ιματιον [βεβαμμενον]{.greek-omitted} [βεβαμενον]{.greek-added} αιματι και [καλειται]{.greek-omitted} [κεκληται]{.greek-added} το ονομα αυτου ο λογος του [θεου]{.greek-abbr}[19:13]{.aside}

και τα στρατευματα τα [τα]{.greek-added} εν τω [ουρανω]{.greek-abbr} [ηκολουθει]{.greek-omitted} [ηκολουθι]{.greek-added} αυτω επι [ιπποις]{.greek-omitted} [οιππις]{.greek-added} [λευκοις]{.greek-omitted} [λευκις]{.greek-added} [ενδεδυμενοι]{.greek-omitted} [ενδεδιμενην]{.greek-added} βυσσινον λευκον καθαρον[19:14]{.aside}

και εκ του στοματος αυτου [εκπορευεται]{.greek-omitted} [πορευσεται]{.greek-added} ρομφαια διστομος οξεια ινα εν αυτη [παταξη]{.greek-omitted} [παταξει]{.greek-added} τα εθνη και αυτος ποιμανει αυτους εν ραβδω σιδηρα και αυτος [πατει]{.greek-omitted} [πατη]{.greek-added} την [ληνον]{.greek-omitted} [λινον]{.greek-added} του οινου του θυμου της [οργης]{.greek-omitted} [ωργης]{.greek-added} του [θεου]{.greek-abbr} του παντοκρατορος[19:15]{.aside}

και εχει επι το ιματιον και επι τον [μηρον]{.greek-omitted} [αυτου]{.greek-omitted} [μυρων]{.greek-added} [αυτων]{.greek-added} ονομα [γεγραμμενον]{.greek-omitted} [γεγραμενον]{.greek-added} βασιλευς βασιλεων και [κυριος]{.greek-abbr} κυριων[19:16]{.aside}

και [ειδον]{.greek-omitted} [οιδον]{.greek-added} αγγελον εστωτα εν τω [ηλιω]{.greek-omitted} [οιλιω]{.greek-added} και εκραξεν [εν]{.greek-added} φωνη μεγαλη λεγων πασιν τοις [ορνεοις]{.greek-omitted} [ωρναιοις]{.greek-added} [και]{.greek-added} τοις [πετομενοις]{.greek-omitted} [πετομενης]{.greek-added} εν [μεσουρανηματι]{.greek-omitted} [μεσουρανιματι]{.greek-added} δευτε [συναχθητε]{.greek-omitted} [συναχθηται]{.greek-added} εις το δειπνον το μεγα του [θεου]{.greek-abbr}[19:17]{.aside}

ινα [φαγητε]{.greek-omitted} [φαγηται]{.greek-added} σαρκας βασιλεων και σαρκας χιλιαρχων και σαρκας [ισχυρων]{.greek-omitted} [ισχυρον]{.greek-added} και σαρκας ιππων και των [καθημενων]{.greek-omitted} [καθημενον]{.greek-added} επ αυτων και σαρκας παντων [ελευθερων]{.greek-omitted} [ελευθερονται]{.greek-added} [τε]{.greek-omitted} και δουλων και [μικρονται]{.greek-added} [μικρων]{.greek-omitted} [τε]{.greek-omitted} και μεγαλων[19:18]{.aside}

και ειδον το [θηριον]{.greek-omitted} [θυριων]{.greek-added} και τους βασιλεις της γης και τα στρατευματα αυτων συνηγμενα ποιησαι [τον]{.greek-added} πολεμον μετα του καθημενου επι του ιππου και μετα του στρατευματος αυτου[19:19]{.aside}

και επιασθη το [θηριον]{.greek-omitted} [θυριον]{.greek-added} και ο μετ αυτου ψευδοπροφητης ο ποιησας τα [σημεια]{.greek-omitted} [ενωπιον]{.greek-omitted} [σιμια]{.greek-added} [ενοπι]{.greek-added} [ον]{.greek-added} αυτου εν οις επλανησεν τους [λαβοντας]{.greek-omitted} [λαβωντας]{.greek-added} το χαραγμα του [θηριου]{.greek-omitted} [θυριου]{.greek-added} και τους προσκυνουντας τη [εικονι]{.greek-omitted} [οικονι]{.greek-added} αυτου ζωντες [εβλισαν]{.greek-added} [εβληθησαν]{.greek-omitted} [[εβλιθισαν]{.corr}]{.greek-added} οι δυο εις την λιμνην του πυρος την [καιομενην]{.greek-omitted} [κεωμενην]{.greek-added} εν θειω[19:20]{.aside}

και οι λοιποι απεκτανθησαν εν τη ρομφαια του καθημενου επι του ιππου τη εξελθουση εκ του στοματος αυτου και παντα τα ορνεα εχορτασθησαν εκ των σαρκων αυτων[19:21]{.aside}

### Chapter 20

και [ειδον]{.greek-omitted} [οιδον]{.greek-added} αγγελον καταβαινοντα εκ του [ουρανου]{.greek-abbr} εχοντα την [κλειν]{.greek-omitted} [κλην]{.greek-added} της αβυσσου [και]{.greek-omitted} [αλυσιν]{.greek-omitted} [αλυσσιν]{.greek-added} μεγαλην επι την χειρα αυτου[20:1]{.aside}

και εκρατησεν τον [δρακοντα]{.greek-omitted} [δρακωντα]{.greek-added} [τον]{.greek-omitted} [οφιν]{.greek-omitted} [των]{.greek-added} [ωφην]{.greek-added} τον αρχαιον ος [εστιν]{.greek-omitted} [εστι]{.greek-added} διαβολος και ο σατανας ο πλανων την οικουμενην ολην και εδησεν αυτον [χιλια]{.greek-omitted} [ετη]{.greek-omitted} [[α]{.greek-abbr}]{.greek-added} [ετι]{.greek-added}[20:2]{.aside}

και εβαλεν αυτον εις την [αβυσσον]{.greek-omitted} [αβησον]{.greek-added} και [εκλεισεν]{.greek-omitted} [εκλισεν]{.greek-added} και [εσφραγισεν]{.greek-omitted} [εσφαλησεν]{.greek-added} επανω αυτου ινα μη πλανα ετι τα εθνη αχρι τελεσθη τα [[α]{.greek-abbr}]{.greek-added} [ετι]{.greek-added} [χιλια]{.greek-omitted} [ετη]{.greek-omitted} [και]{.greek-omitted} μετα ταυτα [δει]{.greek-omitted} [δη]{.greek-added} [ληθηναι]{.greek-added} αυτον [λυθηναι]{.greek-omitted} μικρον χρονον[20:3]{.aside}

και [ειδον]{.greek-omitted} [οιδον]{.greek-added} θρονους και [εκαθισαν]{.greek-omitted} [εκαθησαν]{.greek-added} επ αυτους και κριμα [εδοθη]{.greek-omitted} [εδωθι]{.greek-added} αυτοις και τας ψυχας των [πεπελεκισμενων]{.greek-omitted} [πεπελεκισμενον]{.greek-added} δια την μαρτυριαν [ιησου]{.greek-abbr} και δια τον λογον του [θεου]{.greek-abbr} και οιτινες ου [προσεκυνησαν]{.greek-omitted} [προσεκινισαν]{.greek-added} [το]{.greek-omitted} [θηριον]{.greek-omitted} [ουδε]{.greek-omitted} [τω]{.greek-added} [θυριων]{.greek-added} [ουδαι]{.greek-added} την [εικονα]{.greek-omitted} [οικονα]{.greek-added} αυτου και ουκ [ελαβον]{.greek-omitted} [ελαβεν]{.greek-added} το χαραγμα επι το [μετωπον]{.greek-omitted} [μετοπον]{.greek-added} και [επι]{.greek-omitted} [εποι]{.greek-added} την χειρα αυτων και εζησαν και εβασιλευσαν μετα του [χριστου]{.greek-abbr} τα χιλια [ετη]{.greek-omitted} [ετι]{.greek-added}[20:4]{.aside}

[και]{.greek-omitted} [οι]{.greek-omitted} [λοιποι]{.greek-omitted} [των]{.greek-omitted} [νεκρων]{.greek-omitted} [ουκ]{.greek-omitted} [εζησαν]{.greek-omitted} [αχρι]{.greek-omitted} [τελεσθη]{.greek-omitted} [τα]{.greek-omitted} [χιλια]{.greek-omitted} [ετη]{.greek-omitted} αυτη η αναστασις [η]{.greek-omitted} [οι]{.greek-added} πρωτη[20:5]{.aside}

μακαριος και αγιος [ο]{.greek-omitted} [ω]{.greek-added} εχων μερος εν τη αναστασει τη πρωτη επι τουτων ο δευτερος θανατος ουκ [εχει]{.greek-omitted} [εχι]{.greek-added} εξουσιαν [αλλ]{.greek-omitted} [αλ]{.greek-added} εσονται ιερεις του [θεου]{.greek-abbr} και του [χριστου]{.greek-abbr} και βασιλευσουσιν [μετ]{.greek-omitted} [μετα]{.greek-added} [αυτου]{.greek-omitted} [χιλια]{.greek-omitted} [ετη]{.greek-omitted} [ταυτα]{.greek-added} [[α]{.greek-abbr}]{.greek-added} [ετι]{.greek-added}[20:6]{.aside}

και [μετα]{.greek-added} [οταν]{.greek-omitted} [τελεσθη]{.greek-omitted} τα [χιλια]{.greek-omitted} [ετη]{.greek-omitted} [[α]{.greek-abbr}]{.greek-added} [ετι]{.greek-added} [λυθησεται]{.greek-omitted} [λιθησεται]{.greek-added} ο σατανας εκ της φυλακης αυτου[20:7]{.aside}

και εξελευσεται πλανησαι τα εθνη τα εν ταις [τεσσαρσιν]{.greek-omitted} [τεσαρσιν]{.greek-added} [γωνιαις]{.greek-omitted} [γονιας]{.greek-added} της γης τον γωγ και [τον]{.greek-omitted} [των]{.greek-added} μαγωγ συναγαγειν αυτους εις τον πολεμον ων ο αριθμος [αυτων]{.greek-added} ως [η]{.greek-omitted} [ι]{.greek-added} [αμμος]{.greek-omitted} [αμος]{.greek-added} της [θαλασσης]{.greek-omitted} [θαλασης]{.greek-added}[20:8]{.aside}

και ανεβησαν επι το πλατος της γης και [εκυκλωσαν]{.greek-omitted} [εκυκλευσαν]{.greek-added} την παρεμβολην των αγιων και την πολιν την [ηγαπημενην]{.greek-omitted} [ιγαπημενην]{.greek-added} και κατεβη πυρ εκ του [ουρανου]{.greek-abbr} απο του [θεου]{.greek-abbr} και κατεφαγεν αυτους[20:9]{.aside}

και ο διαβολος ο πλανων αυτους [εβληθη]{.greek-omitted} [εβληθι]{.greek-added} εις την λιμνην του πυρος και θειου οπου και το [θηριον]{.greek-omitted} [θυριον]{.greek-added} και ο ψευδοπροφητης και βασανισθησονται ημερας και νυκτος εις τους αιωνας των αιωνων[20:10]{.aside}

και [ειδον]{.greek-omitted} [οιδον]{.greek-added} θρονον μεγαν [και]{.greek-added} λευκον και τον καθημενον επ [αυτον]{.greek-omitted} [αυτω]{.greek-added} ου απο προσωπου [εφυγεν]{.greek-omitted} [εφηγεν]{.greek-added} η γη και ο [ουρανος]{.greek-abbr} και τοπος ουχ ευρεθη αυτοις[20:11]{.aside}

και [ειδον]{.greek-omitted} [οιδον]{.greek-added} τους νεκρους [εστω]{.greek-added} [τας]{.greek-added} [τους]{.greek-omitted} [μεγαλους]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [μικρους]{.greek-omitted} [εστωτας]{.greek-omitted} [ενωπιον]{.greek-omitted} [ενοπιον]{.greek-added} του [θρονου]{.greek-omitted} [θρωνου]{.greek-added} και βιβλια [ηνεωχθησαν]{.greek-omitted} [οινειξαν]{.greek-added} και [αλλο]{.greek-omitted} [αλο]{.greek-added} βιβλιον ηνεωχθη [ο]{.greek-omitted} [ω]{.greek-added} εστιν της ζωης και εκριθησαν οι νεκροι εκ των γεγραμμενων εν τοις βιβλιοις κατα τα εργα αυτων[20:12]{.aside}

και [εδωκεν]{.greek-omitted} [εδω]{.greek-added} η θαλασσα τους νεκρους τους εν αυτη και ο θανατος και [ο]{.greek-omitted} [ω]{.greek-added} αδης εδωκαν τους νεκρους [τους]{.greek-omitted} [τοις]{.greek-added} εν [αυτοις]{.greek-omitted} [αυτης]{.greek-added} και εκριθησαν εκαστος κατα τα εργα αυτων[20:13]{.aside}

και ο θανατος και ο αδης εβληθησαν εις την λιμνην του πυρος ουτος ο θανατος ο δευτερος εστιν η λιμνη του πυρος[20:14]{.aside}

και ει τις ουχ [ευρεθη]{.greek-omitted} [ευρεθι]{.greek-added} εν τω βιβλιω της ζωης [γεγραμμενος]{.greek-omitted} [γεγραμενος]{.greek-added} [εβληθη]{.greek-omitted} [εβλιθι]{.greek-added} εις την λιμνην του πυρος[20:15]{.aside}

### Chapter 21

και [ειδον]{.greek-omitted} [οιδον]{.greek-added} [ουρανον]{.greek-abbr} καινον και γην καινην ο γαρ [πρωτος]{.greek-omitted} [προτος]{.greek-added} [ουρανος]{.greek-abbr} και η [πρωτη]{.greek-omitted} [πρωτι]{.greek-added} γη απηλθον και η θαλασσα ουκ εστιν ετι[21:1]{.aside}

και την πολιν την αγιαν ιερουσαλημ καινην [ειδον]{.greek-omitted} [οιδον]{.greek-added} καταβαινουσαν εκ του [ουρανου]{.greek-abbr} απο [του]{.greek-omitted} [θεου]{.greek-abbr} [ητοιμασμενην]{.greek-omitted} [ητιμασμενην]{.greek-added} ως νυμφην [κεκοσμημενην]{.greek-omitted} [καικοσμιμενην]{.greek-added} τω ανδρι αυτης[21:2]{.aside}

και ηκουσα φωνης [μεγαλης]{.greek-omitted} [μεγαλις]{.greek-added} [εκ]{.greek-omitted} [του]{.greek-omitted} [εν]{.greek-added} [τω]{.greek-added} [ουρανου]{.greek-omitted} [[ουρανω]{.greek-abbr}]{.greek-added} λεγουσης ιδου [η]{.greek-omitted} [ι]{.greek-added} σκηνη του [θεου]{.greek-abbr} μετα των [ανθρωπων]{.greek-abbr} και σκηνωσει μετ αυτων και αυτοι λαος αυτου εσονται και αυτος ο [θεος]{.greek-abbr} [εσται]{.greek-omitted} μετ αυτων [εστε]{.greek-added}[21:3]{.aside}

και εξαλειψει [επ]{.greek-added} [αυτων]{.greek-added} παν [δακρυον]{.greek-omitted} [δακριον]{.greek-added} απο των οφθαλμων αυτων και ο θανατος ουκ [εσται]{.greek-omitted} [εστι]{.greek-added} ετι ουτε πενθος ουτε κραυγη ουτε πονος [ουκ]{.greek-omitted} [εσται]{.greek-omitted} [ετι]{.greek-omitted} οτι τα [πρωτα]{.greek-omitted} [προτα]{.greek-added} [απηλθον]{.greek-omitted} [απηλθεν]{.greek-added}[21:4]{.aside}

[και]{.greek-omitted} ειπεν ο καθημενος επι τω [θρονω]{.greek-omitted} [θρωνω]{.greek-added} ιδου παντα [καινα]{.greek-omitted} [κενα]{.greek-added} [ποιω]{.greek-omitted} [πιω]{.greek-added} και λεγει [μοι]{.greek-omitted} γραψον οτι ουτοι οι λογοι [αληθινοι]{.greek-omitted} [πιστι]{.greek-added} και [πιστοι]{.greek-omitted} [αληθηνοι]{.greek-added} [του]{.greek-added} [[θεου]{.greek-abbr}]{.greek-added} εισιν[21:5]{.aside}

και ειπεν μοι γεγονα το [αλφα]{.greek-omitted} [ἄλφα]{.greek-added} και [το]{.greek-omitted} [ω]{.greek-omitted} [τω]{.greek-added} [ὦ]{.greek-added} [και]{.greek-added} η [αρχη]{.greek-omitted} [αρχι]{.greek-added} και το τελος εγω τω [διψωντι]{.greek-omitted} [διψοντι]{.greek-added} δωσω [αυτω]{.greek-added} εκ της [πηγης]{.greek-omitted} [γης]{.greek-added} του υδατος της ζωης δωρεαν[21:6]{.aside}

ο νικων [κληρονομησει]{.greek-omitted} [δωσω]{.greek-added} [αυτων]{.greek-added} ταυτα και [εσομαι]{.greek-omitted} [εσωμαι]{.greek-added} [αυτω]{.greek-omitted} [αυτων]{.greek-added} [θεος]{.greek-abbr} και αυτος [εσται]{.greek-omitted} [μοι]{.greek-omitted} [εστε]{.greek-added} [μου]{.greek-added} υιος[21:7]{.aside}

τοις [δε]{.greek-omitted} [δαι]{.greek-added} [δειλοις]{.greek-omitted} [διλοις]{.greek-added} και απιστοις και αμαρτωλοις και [εβδελυγμενοις]{.greek-omitted} [εβδελυγμενης]{.greek-added} και [φονευσιν]{.greek-omitted} [φωνευσην]{.greek-added} και [πορνοις]{.greek-omitted} [πορνης]{.greek-added} και [φαρμακοις]{.greek-omitted} [φαρμακις]{.greek-added} και [ειδωλολατραις]{.greek-omitted} [οιδωλολατραις]{.greek-added} και πασιν τοις ψευδεσιν το μερος αυτων εν τη λιμνη τη [καιομενη]{.greek-omitted} [κεωμενη]{.greek-added} πυρι και θειω ο εστιν ο θανατος [ο]{.greek-omitted} [ω]{.greek-added} δευτερος[21:8]{.aside}

και ηλθεν εις εκ των επτα αγγελων των [εχοντων]{.greek-omitted} [εχωντον]{.greek-added} τας [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} φιαλας γεμουσας [των]{.greek-omitted} επτα πληγων των εσχατων και ελαλησεν μετ εμου λεγων δευρο δειξω σοι την [γυναικα]{.greek-omitted} [γυναικαν]{.greek-added} την [νυμφην]{.greek-omitted} [νιφην]{.greek-added} του αρνιου[21:9]{.aside}

και απηνεγκεν με εν [πνευματι]{.greek-abbr} επ ορος μεγα και [υψηλον]{.greek-omitted} [υψιλον]{.greek-added} και εδειξεν μοι την πολιν [την]{.greek-omitted} [μεγαλην]{.greek-omitted} την αγιαν ιερουσαλημ καταβαινουσαν εκ του [ουρανου]{.greek-abbr} [απο]{.greek-omitted} [εκ]{.greek-added} του [θεου]{.greek-abbr}[21:10]{.aside}

εχουσαν την δοξαν του [θεου]{.greek-abbr} ο φωστηρ αυτης ομοιος λιθω τιμιωτατω ως λιθω ιασπιδι [κρυσταλλιζοντι]{.greek-omitted} [κρισταλιζωντι]{.greek-added}[21:11]{.aside}

εχουσα [τειχος]{.greek-omitted} [τιχος]{.greek-added} μεγα και [υψηλον]{.greek-omitted} [υψιλον]{.greek-added} εχουσα πυλωνας δωδεκα και επι τοις πυλωσιν [αγγελους]{.greek-omitted} [αγγελοις]{.greek-added} [δωδεκα]{.greek-omitted} [δεκα]{.greek-added} [δυο]{.greek-added} και ονοματα επιγεγραμμενα α εστιν ονοματα των δωδεκα [υιων]{.greek-added} φυλων [των]{.greek-omitted} [υιων]{.greek-omitted} [ισραηλ]{.greek-abbr}[21:12]{.aside}

απο ανατολων πυλωνες τρεις και απο βορρα [πυλωνες]{.greek-omitted} [πυλονες]{.greek-added} [τρεις]{.greek-omitted} [[γ]{.greek-abbr}]{.greek-added} και απο νοτου πυλωνες [τρεις]{.greek-omitted} [[γ]{.greek-abbr}]{.greek-added} και απο [δυσμων]{.greek-omitted} [δισμων]{.greek-added} [πυλωνες]{.greek-omitted} [πυλονες]{.greek-added} [τρεις]{.greek-omitted} [[γ]{.greek-abbr}]{.greek-added}[21:13]{.aside}

και το [τειχος]{.greek-omitted} [τυχος]{.greek-added} της [πολεως]{.greek-omitted} [πολεος]{.greek-added} εχον θεμελιους δωδεκα και επ αυτων [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} ονοματα των δωδεκα αποστολων του αρνιου[21:14]{.aside}

και ο λαλων μετ εμου ειχεν μετρον καλαμον [χρυσουν]{.greek-omitted} [χρυσσουν]{.greek-added} ινα [μετρηση]{.greek-omitted} [μετρισι]{.greek-added} την πολιν και τους πυλωνας αυτης [και]{.greek-omitted} [το]{.greek-omitted} [τειχος]{.greek-omitted} [αυτης]{.greek-omitted}[21:15]{.aside}

και [η]{.greek-omitted} [οι]{.greek-added} πολις [τετραγωνος]{.greek-omitted} [τετραγονος]{.greek-added} κειται και το μηκος αυτης [οσον]{.greek-omitted} [ωσον]{.greek-added} το πλατος και εμετρησεν την πολιν τω καλαμω επι σταδιους [δωδεκα]{.greek-omitted} [δεκα]{.greek-added} [δυο]{.greek-added} χιλιαδων δωδεκα το μηκος και το πλατος και το υψος αυτης [ισα]{.greek-omitted} [εισα]{.greek-added} [εστιν]{.greek-omitted} [εστι]{.greek-added}[21:16]{.aside}

και [εμετρησεν]{.greek-omitted} το [τειχος]{.greek-omitted} [τυχος]{.greek-added} αυτης [[ρμδ]{.greek-abbr}]{.greek-added} [εκατον]{.greek-omitted} [τεσσαρακοντα]{.greek-omitted} [τεσσαρων]{.greek-omitted} [πηχων]{.greek-omitted} [πυχων]{.greek-added} μετρον [ανθρωπου]{.greek-abbr} ο εστιν αγγελου[21:17]{.aside}

και ην [η]{.greek-omitted} [οι]{.greek-added} [ενδομησις]{.greek-omitted} [ενδωμησις]{.greek-added} του [τειχους]{.greek-omitted} [τυχου]{.greek-added} αυτης ιασπις και [η]{.greek-omitted} [υ]{.greek-added} πολις [χρυσιον]{.greek-omitted} [χρυσιων]{.greek-added} [καθαρον]{.greek-omitted} [καθαρων]{.greek-added} [ομοιον]{.greek-omitted} [ομιον]{.greek-added} [υελω]{.greek-omitted} [υαλω]{.greek-added} καθαρω[21:18]{.aside}

οι θεμελιοι του [τειχους]{.greek-omitted} [τιχους]{.greek-added} της [πολεως]{.greek-omitted} [πολεος]{.greek-added} παντι λιθω [τιμιω]{.greek-omitted} [κεκοσμημενοι]{.greek-omitted} [καικοσμημενη]{.greek-added} ο θεμελιος ο πρωτος ιασπις ο [δευτερος]{.greek-omitted} [[β]{.greek-abbr}]{.greek-added} [σαπφειρος]{.greek-omitted} [σαπφηρος]{.greek-added} ο [τριτος]{.greek-omitted} [[γ]{.greek-abbr}]{.greek-added} [χαλκηδων]{.greek-omitted} [χαλκηδον]{.greek-added} ο [τεταρτος]{.greek-omitted} [[δ]{.greek-abbr}]{.greek-added} σμαραγδος[21:19]{.aside}

ο [πεμπτος]{.greek-omitted} [[ε]{.greek-abbr}]{.greek-added} [σαρδονυξ]{.greek-omitted} [σαλδονυξ]{.greek-added} ο [εκτος]{.greek-omitted} [[ϛ]{.greek-abbr}]{.greek-added} σαρδιον ο [εβδομος]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} [χρυσολιθος]{.greek-omitted} [χρυσσολιθος]{.greek-added} ο [ογδοος]{.greek-omitted} [[η]{.greek-abbr}]{.greek-added} [βηρυλλος]{.greek-omitted} [βηρυλος]{.greek-added} ο [ενατος]{.greek-omitted} [[θ]{.greek-abbr}]{.greek-added} τοπαζιον ο [δεκατος]{.greek-omitted} [[ι]{.greek-abbr}]{.greek-added} [χρυσοπρασος]{.greek-omitted} [χρησοπατος]{.greek-added} ο [ενδεκατος]{.greek-omitted} [[ια]{.greek-abbr}]{.greek-added} υακινθος ο [δωδεκατος]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} [αμεθυσος]{.greek-omitted} [αμεθιστος]{.greek-added}[21:20]{.aside}

και οι [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} [πυλωνες]{.greek-omitted} [πυλωναις]{.greek-added} [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} μαργαριται ανα εις εκαστος των πυλωνων ην εξ ενος μαργαριτου και η [πλατεια]{.greek-omitted} [πλατια]{.greek-added} της [πολεως]{.greek-omitted} [πολεος]{.greek-added} χρυσιον καθαρον [ως]{.greek-omitted} [ος]{.greek-added} [υελος]{.greek-omitted} [υαλος]{.greek-added} διαυγης[21:21]{.aside}

και ναον ουκ ειδον εν αυτη ο γαρ [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ ναος αυτης εστιν και το [αρνιον]{.greek-omitted} [αρνιων]{.greek-added}[21:22]{.aside}

και η πολις ου [χρειαν]{.greek-omitted} [χριαν]{.greek-added} εχει του [ηλιου]{.greek-omitted} [ιλιου]{.greek-added} [ουδε]{.greek-omitted} [δαι]{.greek-added} της σεληνης ινα φαινωσιν αυτη [γαρ]{.greek-added} [εφωτησεν]{.greek-added} η [γαρ]{.greek-omitted} [δοξα]{.greek-omitted} [δωξα]{.greek-added} του [θεου]{.greek-abbr} [εφωτισεν]{.greek-omitted} αυτην και ο [λυχνος]{.greek-omitted} [λιχνος]{.greek-added} αυτης το αρνιον[21:23]{.aside}

και περιπατησουσιν τα εθνη δια του φωτος αυτης και οι βασιλεις της γης φερουσιν [αυτω]{.greek-omitted} [αυτων]{.greek-added} δοξαν και τιμην των εθνων εις αυτην[21:24]{.aside}

και οι πυλωνες αυτης ου μη [κλεισθωσιν]{.greek-omitted} [κλισθωσιν]{.greek-added} ημερας νυξ γαρ ουκ εσται εκει[21:25]{.aside}

και οισουσιν την δοξαν και την τιμην των εθνων εις αυτην [ινα]{.greek-added} [ησελθωσιν]{.greek-added}[21:26]{.aside}

και ου μη [εισελθη]{.greek-omitted} [εισελθοι]{.greek-added} εις αυτην παν κοινον και [ο]{.greek-added} [ποιουν]{.greek-omitted} [πιον]{.greek-added} [βδελυγμα]{.greek-omitted} [βδελιγμα]{.greek-added} και ψευδος ει μη οι [γεγραμμενοι]{.greek-omitted} [γεγραμενοι]{.greek-added} εν τω βιβλιω της ζωης του αρνιου[21:27]{.aside}

### Chapter 22

και εδειξεν μοι ποταμον [καθαρον]{.greek-omitted} υδατος ζωης λαμπρον [ως]{.greek-omitted} [ος]{.greek-added} [κρυσταλλον]{.greek-omitted} [κρισταλον]{.greek-added} εκπορευομενον εκ του θρονου του [θεου]{.greek-abbr} και του αρνιου[22:1]{.aside}

εν μεσω της [πλατειας]{.greek-omitted} [πλατιας]{.greek-added} αυτης και του ποταμου εντευθεν και εκειθεν ξυλον ζωης ποιουν καρπους [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} κατα μηνα [εκαστον]{.greek-omitted} αποδιδους [τον]{.greek-omitted} [εκαστος]{.greek-added} [των]{.greek-added} καρπον αυτου και τα [φυλλα]{.greek-omitted} [φυλα]{.greek-added} του ξυλου εις [θεραπειαν]{.greek-omitted} [θεραπιαν]{.greek-added} των εθνων[22:2]{.aside}

και παν καταθεμα ουκ εσται ετι και ο θρονος του [θεου]{.greek-abbr} και του αρνιου εν αυτη εσται και οι [και]{.greek-added} [οι]{.greek-added} δουλοι αυτου λατρευσουσιν αυτω[22:3]{.aside}

και οψονται το [προσωπον]{.greek-omitted} [πρωσωπον]{.greek-added} αυτου και το ονομα αυτου επι [των]{.greek-omitted} [μετωπων]{.greek-omitted} [τον]{.greek-added} [μετοπον]{.greek-added} αυτων[22:4]{.aside}

και νυξ ουκ [εστε]{.greek-added} [εσται]{.greek-omitted} [εκει]{.greek-omitted} και [ου]{.greek-added} χρειαν [ουκ]{.greek-omitted} [εχουσιν]{.greek-omitted} λυχνου και φωτος [ηλιου]{.greek-omitted} οτι [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} φωτιει αυτους και βασιλευσουσιν εις τους αιωνας των αιωνων[22:5]{.aside}

και λεγει μοι ουτοι οι λογοι πιστοι και [αληθινοι]{.greek-omitted} [αληθηνοι]{.greek-added} και [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} των [πνευματων]{.greek-abbr} των προφητων [απεστειλεν]{.greek-omitted} [απεστηλεν]{.greek-added} [τον]{.greek-omitted} [των]{.greek-added} αγγελον [αυτου]{.greek-omitted} [δειξαι]{.greek-omitted} [τοις]{.greek-omitted} [δουλοις]{.greek-omitted} αυτου α δει γενεσθαι εν [ταχει]{.greek-omitted} [ταχη]{.greek-added}[22:6]{.aside}

και ιδου ερχομαι [ταχυ]{.greek-omitted} [ταχη]{.greek-added} μακαριος ο [τηρων]{.greek-omitted} [τυρων]{.greek-added} τους λογους της [προφητειας]{.greek-omitted} [προφητιας]{.greek-added} του βιβλιου τουτου[22:7]{.aside}

καγω [ιωαννης]{.greek-abbr} [ο]{.greek-omitted} ακουων [και]{.greek-omitted} [βλεπων]{.greek-omitted} [βλεπον]{.greek-added} ταυτα και οτε [ηκουσα]{.greek-omitted} [εικουσα]{.greek-added} και [εβλεψα]{.greek-omitted} [οτε]{.greek-added} [ειδων]{.greek-added} επεσον προσκυνησαι εμπροσθεν [των]{.greek-omitted} [τον]{.greek-added} ποδων του αγγελου του [δεικνυοντος]{.greek-omitted} [δικνυντος]{.greek-added} μοι ταυτα[22:8]{.aside}

και λεγει μοι ορα μη συνδουλος σου [ειμι]{.greek-omitted} [ειμη]{.greek-added} και των αδελφων σου των προφητων και [των]{.greek-omitted} [τον]{.greek-added} [τηρουντων]{.greek-omitted} [τυρουντων]{.greek-added} τους λογους του βιβλιου τουτου τω [θεω]{.greek-abbr} προσκυνησον[22:9]{.aside}

και λεγει μοι μη [σφραγισης]{.greek-omitted} [σφραγισις]{.greek-added} τους λογους της [προφητειας]{.greek-omitted} [προφητιας]{.greek-added} του βιβλιου τουτου ο καιρος γαρ εγγυς εστιν[22:10]{.aside}

ο αδικων αδικησατω ετι και ο ρυπαρος [ρυπαρευθητω]{.greek-omitted} [ρηπαρευθιτω]{.greek-added} ετι και ο δικαιος [δικαιοσυνην]{.greek-omitted} [δικαιωσυνην]{.greek-added} ποιησατω ετι και ο αγιος αγιασθητω ετι[22:11]{.aside}

ιδου ερχομαι [ταχυ]{.greek-omitted} [ταχη]{.greek-added} και ο [μισθος]{.greek-omitted} [μισθως]{.greek-added} μου μετ εμου αποδουναι [εκαστω]{.greek-omitted} [εκαστος]{.greek-added} ως [το]{.greek-omitted} [τω]{.greek-added} εργον εσται αυτου[22:12]{.aside}

εγω [το]{.greek-omitted} [τω]{.greek-added} [αλφα]{.greek-omitted} [ἄλφα]{.greek-added} και [το]{.greek-omitted} [ω]{.greek-omitted} [τω]{.greek-added} [ὦ]{.greek-added} ο [πρωτος]{.greek-omitted} [προτος]{.greek-added} και ο εσχατος η [αρχη]{.greek-omitted} [αρχι]{.greek-added} και το τελος[22:13]{.aside}

μακαριοι [οι]{.greek-omitted} [η]{.greek-added} [ποιουντες]{.greek-omitted} [ποιοουντες]{.greek-added} τας εντολας αυτου ινα [εσται]{.greek-omitted} [εστε]{.greek-added} η εξουσια αυτων επι το ξυλον της ζωης και τοις πυλωσιν εισελθωσιν εις την [πολιν]{.greek-omitted} [πολην]{.greek-added}[22:14]{.aside}

εξω οι [κυνες]{.greek-omitted} [κοινες]{.greek-added} και οι φαρμακοι και οι πορνοι και οι [φονεις]{.greek-omitted} [φωνης]{.greek-added} και οι [ειδωλολατραι]{.greek-omitted} [οιδολολατραι]{.greek-added} και πας φιλων και ποιων ψευδος[22:15]{.aside}

εγω [ιησους]{.greek-abbr} επεμψα τον αγγελον μου [μαρτυρησαι]{.greek-omitted} [μαρτυρισαι]{.greek-added} [υμιν]{.greek-omitted} [ημιν]{.greek-added} ταυτα επι ταις εκκλησιαις εγω ειμι η ριζα και το γενος [δαυιδ]{.greek-omitted} [δαυυδ]{.greek-added} ο αστηρ ο λαμπρος ο [πρωινος]{.greek-omitted} [προινος]{.greek-added}[22:16]{.aside}

και το [πνευμα]{.greek-abbr} και η [νυμφη]{.greek-omitted} [νυμφι]{.greek-added} λεγουσιν ερχου και ο ακουων ειπατω ερχου και ο [διψων]{.greek-omitted} [διψον]{.greek-added} ερχεσθω ο θελων λαβετω υδωρ ζωης δωρεαν[22:17]{.aside}

[μαρτυρω]{.greek-omitted} [μαρτυρο]{.greek-added} εγω παντι τω [ακουοντι]{.greek-omitted} [ακουωντι]{.greek-added} τους λογους της [προφητειας]{.greek-omitted} [προφητιας]{.greek-added} του βιβλιου τουτου εαν τις [επιθη]{.greek-omitted} [επιθι]{.greek-added} επ αυτα επιθησαι ο [θεος]{.greek-abbr} επ αυτον τας πληγας τας γεγραμμενας εν τω βιβλιω τουτω[22:18]{.aside}

και εαν τις αφελη απο των [λογων]{.greek-omitted} [λογον]{.greek-added} του βιβλιου της [προφητειας]{.greek-omitted} [προφητιας]{.greek-added} ταυτης [αφελοι]{.greek-omitted} [αφελη]{.greek-added} ο [θεος]{.greek-abbr} το μερος αυτου απο του ξυλου της ζωης και εκ της [πολεως]{.greek-omitted} [πολεος]{.greek-added} της αγιας των [γεγραμμενων]{.greek-omitted} [γεγραμμενον]{.greek-added} εν τω βιβλιω τουτω[22:19]{.aside}

[λεγει]{.greek-omitted} [λαιγει]{.greek-added} ο μαρτυρων ταυτα ναι ερχομαι [ταχυ]{.greek-omitted} [ταχη]{.greek-added} αμην ναι ερχου [κυριε]{.greek-abbr} [ιησου]{.greek-abbr}[22:20]{.aside}

η χαρις του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} μετα παντων των αγιων αμην[22:21]{.aside}

