---
title: "Collation of Byz^RP^ vs 32845 (2845)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 2845 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=32845).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 2845                                   	| λογος                              	|
| 2845 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 2845 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 2845               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 2845                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 2845 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 2845                                                     	| [―]{.gap}                        	|
:::

## Revelation

### Chapter 1

αποκαλυψις [ιωαννου]{.greek-added} [ιησου]{.greek-omitted} [χριστου]{.greek-omitted} ην εδωκεν αυτω [[κυριος]{.greek-abbr}]{.greek-added} ο [θεος]{.greek-abbr} δειξαι τοις δουλοις αυτου α δει γενεσθαι εν ταχει και εσημανεν αποστειλας δια του αγγελου αυτου τω δουλω αυτου ιωαννη[1:1]{.aside}

ος [εμαρτυρησεν]{.greek-omitted} [εμαρτυρησε]{.greek-added} τον λογον του [θεου]{.greek-abbr} και την μαρτυριαν [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} οσα [ειδεν]{.greek-omitted} [ειδε]{.greek-added}[1:2]{.aside}

μακαριος ο αναγινωσκων και οι ακουοντες [τους]{.greek-omitted} [λογους]{.greek-omitted} της προφητειας [τον]{.greek-added} [λογον]{.greek-added} και τηρουντες τα εν αυτη γεγραμμενα ο γαρ καιρος εγγυς[1:3]{.aside}

ιωαννης ταις επτα εκκλησιαις ταις εν τη ασια χαρις υμιν και ειρηνη απο [θεου]{.greek-abbr} ο ων και ο ην και ο ερχομενος και απο των επτα [πνευματων]{.greek-abbr} α ενωπιον του θρονου αυτου[1:4]{.aside}

και απο [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} ο μαρτυς ο πιστος ο πρωτοτοκος των νεκρων και ο αρχων των βασιλεων της γης τω [αγαπωντι]{.greek-omitted} [αγαποντι]{.greek-added} ημας και [λουσαντι]{.greek-omitted} [λυσαντι]{.greek-added} ημας [απο]{.greek-omitted} [εκ]{.greek-added} των αμαρτιων ημων εν τω αιματι αυτου[1:5]{.aside}

και εποιησεν ημας βασιλειαν ιερεις τω [θεω]{.greek-abbr} και [πατρι]{.greek-abbr} αυτου αυτω η δοξα και το κρατος εις τους αιωνας των αιωνων αμην[1:6]{.aside}

ιδου ερχεται μετα των νεφελων και οψεται αυτον πας οφθαλμος και οιτινες αυτον [εξεκεντησαν]{.greek-omitted} [εξεκεντισαν]{.greek-added} και κοψονται επ αυτον πασαι αι φυλαι της γης ναι αμην[1:7]{.aside}

εγω ειμι το [αλφα]{.greek-omitted} [[α]{.greek-abbr}]{.greek-added} και το [ω]{.greek-abbr} λεγει [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο ων και ο ην και ο ερχομενος ο παντοκρατωρ[1:8]{.aside}

εγω ιωαννης ο αδελφος υμων και [ω]{.greek-added} [κοινωνος]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [θλιψει]{.greek-omitted} [και]{.greek-omitted} [βασιλεια]{.greek-omitted} [και]{.greek-omitted} [υπομονη]{.greek-omitted} [εν]{.greek-omitted} [χριστω]{.greek-omitted} [ιησου]{.greek-omitted} [εγενομην]{.greek-omitted} [εν]{.greek-omitted} τη νησω τη καλουμενη πατμω δια τον λογον του [θεου]{.greek-abbr} και [δια]{.greek-omitted} την μαρτυριαν [ιησου]{.greek-abbr} [χριστου]{.greek-abbr}[1:9]{.aside}

εγενομην εν [πνευματι]{.greek-abbr} εν τη κυριακη ημερα και ηκουσα φωνην οπισω μου μεγαλην ως [σαλπιγγος]{.greek-omitted} [σαλπιγκος]{.greek-added}[1:10]{.aside}

λεγουσης ο βλεπεις γραψον εις βιβλιον [περγαμο]{.greek-added} και πεμψον ταις επτα εκκλησιαις εις εφεσον και εις [σμυρναν]{.greek-omitted} [μυρναν]{.greek-added} και εις περγαμον και εις [θυατειρα]{.greek-omitted} [θυατεραν]{.greek-added} και εις σαρδεις και εις [φιλαδελφειαν]{.greek-omitted} [και]{.greek-omitted} [εις]{.greek-omitted} λαοδικειαν[1:11]{.aside}

και εκει επεστρεψα βλεπειν την φωνην ητις [ελαλει]{.greek-omitted} [μετ]{.greek-omitted} [εμου]{.greek-omitted} [και]{.greek-omitted} [επιστρεψας]{.greek-omitted} [ειδον]{.greek-omitted} [επτα]{.greek-omitted} [λυχνιας]{.greek-omitted} [χρυσας]{.greek-omitted}[1:12]{.aside}

[και]{.greek-omitted} [εκει]{.greek-omitted} [επεστρεψα]{.greek-omitted} [βλεπειν]{.greek-omitted} [την]{.greek-omitted} [φωνην]{.greek-omitted} [ητις]{.greek-omitted} ελαλει μετ εμου και επιστρεψας ειδον επτα λυχνιας χρυσας[1:12 | instance no. 2]{.aside}

και εν μεσω των επτα λυχνιων ομοιον [υιω]{.greek-abbr} [ανθρωπου]{.greek-abbr} [ενδεδυμενον]{.greek-omitted} [ενδεδυμενο]{.greek-added} [ποδηρη]{.greek-omitted} [ποδυρη]{.greek-added} και περιεζωσμενον προς τοις μαστοις ζωνην χρυσην[1:13]{.aside}

η δε κεφαλη αυτου και [αι]{.greek-omitted} [ε]{.greek-added} τριχες λευκαι ως [εριον]{.greek-omitted} [εργον]{.greek-added} λευκον [ως]{.greek-omitted} [ωσι]{.greek-added} [χιων]{.greek-omitted} [χειων]{.greek-added} και οι οφθαλμοι αυτου [ως]{.greek-omitted} φλοξ πυρος[1:14]{.aside}

και οι ποδες αυτου ομοιοι [χαλκολιβανω]{.greek-omitted} [χαλκολιβανοι]{.greek-added} ως [εν]{.greek-omitted} [ει]{.greek-added} καμινω πεπυρωμενοι και η φωνη αυτου ως φωνη υδατων πολλων[1:15]{.aside}

και εχων εν τη δεξια αυτου χειρι αστερας επτα και εκ του στοματος αυτου ρομφαια διστομος οξεια εκπορευομενη και η οψις αυτου ως ο ηλιος φαινει εν τη δυναμει αυτου[1:16]{.aside}

και οτε ειδον αυτον επεσα [προς]{.greek-omitted} [περι]{.greek-added} τους ποδας αυτου ως νεκρος και εθηκεν την δεξιαν αυτου επ εμε λεγων μη φοβου εγω ειμι ο πρωτος και ο εσχατος[1:17]{.aside}

και ο ζων και εγενομην νεκρος και ιδου ζων ειμι εις τους αιωνας των αιωνων αμην και εχω τας [κλεις]{.greek-omitted} [κλειδας]{.greek-added} του θανατου και του αδου[1:18]{.aside}

γραψον ουν α ειδες και α [εισιν]{.greek-omitted} [εισι]{.greek-added} και α μελλει [γινεσθαι]{.greek-omitted} [γενεσθαι]{.greek-added} μετα ταυτα[1:19]{.aside}

το μυστηριον των επτα αστερων ων ειδες επι της δεξιας μου και τας επτα λυχνιας τας χρυσας οι επτα αστερες αγγελοι των επτα εκκλησιων [εισιν]{.greek-omitted} [εισι]{.greek-added} και αι λυχνιαι αι επτα επτα εκκλησιαι [εισιν]{.greek-omitted} [εισι]{.greek-added}[1:20]{.aside}

### Chapter 2

τω αγγελω [της]{.greek-omitted} [τη]{.greek-added} [εν]{.greek-omitted} εφεσω εκκλησιας γραψον ταδε λεγει ο κρατων τους επτα αστερας εν τη δεξια αυτου ο περιπατων εν μεσω των επτα λυχνιων των χρυσων[2:1]{.aside}

οιδα τα εργα σου και τον κοπον σου και την υπομονην σου και οτι ου δυνη βαστασαι κακους και επειρασας τους λεγοντας εαυτους αποστολους ειναι και ουκ [εισιν]{.greek-omitted} [εισι]{.greek-added} και ευρες αυτους ψευδεις[2:2]{.aside}

και υπομονην εχεις και εβαστασας δια το ονομα μου και [ουκ]{.greek-omitted} [οὐ]{.greek-added} [εκοπιασας]{.greek-omitted} [κεκοπίασας]{.greek-added}[2:3]{.aside}

[αλλα]{.greek-omitted} [αλλ]{.greek-added} εχω κατα σου οτι την αγαπην σου την πρωτην αφηκας[2:4]{.aside}

μνημονευε ουν ποθεν πεπτωκας και μετανοησον [και]{.greek-omitted} [τα]{.greek-omitted} [πρωτα]{.greek-omitted} [εργα]{.greek-omitted} [ποιησον]{.greek-omitted} ει δε μη ερχομαι σοι ταχυ και κινησω την λυχνιαν σου εκ του τοπου αυτης [εαν]{.greek-omitted} [μη]{.greek-omitted} [μετανοησης]{.greek-omitted}[2:5]{.aside}

[οιδα]{.greek-omitted} [σου]{.greek-omitted} [τα]{.greek-omitted} [εργα]{.greek-omitted} και [την]{.greek-omitted} [αγαπην]{.greek-omitted} [και]{.greek-omitted} [την]{.greek-omitted} [πιστιν]{.greek-omitted} [και]{.greek-omitted} [την]{.greek-omitted} διακονιαν και την υπομονην σου και τα εργα σου τα εσχατα πλειονα των πρωτων[2:19]{.aside}

[αλλ]{.greek-omitted} [αλλα]{.greek-added} εχω κατα σου οτι αφεις την [γυναικα]{.greek-omitted} [γυναικαν]{.greek-added} [σου]{.greek-omitted} ιεζαβελ η [λεγει]{.greek-omitted} [λεγη]{.greek-added} εαυτην προφητιν και διδασκει και πλανα τους εμους δουλους πορνευσαι και φαγειν ειδωλοθυτα[2:20]{.aside}

και εδωκα αυτη χρονον ινα μετανοηση και ου θελει μετανοησαι εκ της [πορνειας]{.greek-omitted} [πορνιας]{.greek-added} αυτης[2:21]{.aside}

ιδου [βαλλω]{.greek-omitted} [βαλω]{.greek-added} αυτην εις κλινην και τους [μοιχευοντας]{.greek-omitted} [μηχεβοντας]{.greek-added} μετ αυτης εις θλιψιν μεγαλην εαν μη μετανοησωσιν εκ των εργων αυτης[2:22]{.aside}

και τα τεκνα αυτης [αποκτενω]{.greek-omitted} [απωκτενω]{.greek-added} εν θανατω και γνωσονται πασαι [αι]{.greek-omitted} εκκλησιαι οτι εγω ειμι ο ερευνων νεφρους και καρδιας και [δωσω]{.greek-omitted} [αποδωσω]{.greek-added} υμιν εκαστω κατα τα εργα υμων[2:23]{.aside}

υμιν δε λεγω τοις [λοιποις]{.greek-omitted} [λυποις]{.greek-added} τοις εν θυατειροις [οσοι]{.greek-omitted} [οτι]{.greek-added} ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} την διδαχην ταυτην οιτινες [ουκ]{.greek-omitted} [ου]{.greek-added} [εγνωσαν]{.greek-omitted} [γνωσονται]{.greek-added} τα [βαθεα]{.greek-omitted} [βαθέα]{.greek-added} του σατανα ως λεγουσιν ου βαλλω εφ υμας αλλο βαρος[2:24]{.aside}

πλην ο [εχετε]{.greek-omitted} [εχεται]{.greek-added} κρατησατε [αχρι]{.greek-omitted} [αχρις]{.greek-added} ου [ανοιξω]{.greek-added} [αν]{.greek-omitted} [ηξω]{.greek-omitted}[2:25]{.aside}

και ο νικων και ο τηρων αχρι τελους τα εργα μου δωσω αυτω εξουσιαν επι των εθνων[2:26]{.aside}

και ποιμανει αυτους εν ραβδω σιδηρα ως τα σκευη τα κεραμικα συντριβησεται [ως]{.greek-omitted} [καγω]{.greek-omitted} [ειληφα]{.greek-omitted} [παρα]{.greek-omitted} [του]{.greek-omitted} [πατρος]{.greek-omitted} [μου]{.greek-omitted}[2:27]{.aside}

[ως]{.greek-added} [καγω]{.greek-added} [ειληφα]{.greek-added} [παρα]{.greek-added} [του]{.greek-added} [[πατρος]{.greek-abbr}]{.greek-added} [μου]{.greek-added} και δωσω αυτω τον αστερα τον πρωινον[2:28]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[2:29]{.aside}

### Chapter 3

και τω αγγελω της εν σαρδεσιν εκκλησιας γραψον ταδε λεγει ο εχων τα επτα [πνευματα]{.greek-omitted} [[πνευμα]{.greek-abbr}]{.greek-added} του [θεου]{.greek-abbr} και τους επτα αστερας οιδα σου τα εργα οτι ονομα εχεις [οτι]{.greek-omitted} [και]{.greek-added} ζης και [νεκρος]{.greek-omitted} [νεκρους]{.greek-added} ει[3:1]{.aside}

γινου γρηγορων και [στηρισον]{.greek-omitted} [τηρησον]{.greek-added} τα [λοιπα]{.greek-omitted} [λυπα]{.greek-added} α [εμελλες]{.greek-omitted} [ημελλες]{.greek-added} αποβαλλειν ου γαρ ευρηκα σου τα εργα πεπληρωμενα ενωπιον του [θεου]{.greek-abbr} μου[3:2]{.aside}

μνημονευε ουν πως ειληφας [και]{.greek-omitted} [ηκουσας]{.greek-omitted} [και]{.greek-omitted} [τηρει]{.greek-omitted} και μετανοησον εαν ουν μη γρηγορησης ηξω [επεσε]{.greek-added} [επι]{.greek-omitted} [σε]{.greek-omitted} ως κλεπτης και ου μη [γνως]{.greek-omitted} [γνωση]{.greek-added} ποιαν ωραν ηξω επι σε[3:3]{.aside}

αλλ ολιγα εχεις ονοματα εν σαρδεσιν α ουκ εμολυναν τα ιματια αυτων και περιπατησουσιν μετ εμου εν λευκοις οτι αξιοι εισιν[3:4]{.aside}

ο νικων [ουτος]{.greek-omitted} [ουτως]{.greek-added} περιβαλειται εν ιματιοις λευκοις και ου μη εξαλειψω το ονομα αυτου εκ της βιβλου της ζωης και ομολογησω το ονομα αυτου ενωπιον του [πατρος]{.greek-abbr} μου και ενωπιον των αγγελων αυτου[3:5]{.aside}

### Chapter 22

[και]{.greek-omitted} [λεγει]{.greek-omitted} [μοι]{.greek-omitted} [ουτοι]{.greek-omitted} [οι]{.greek-omitted} [λογοι]{.greek-omitted} πιστοι και αληθινοι και [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} των [πνευματων]{.greek-abbr} των προφητων απεστειλεν τον αγγελον αυτου δειξαι τοις δουλοις αυτου α δει [γενεσθαι]{.greek-omitted} [γενεσται]{.greek-added} εν ταχει[22:6]{.aside}

και ιδου ερχομαι ταχυ μακαριος ο τηρων τους λογους της προφητειας του βιβλιου τουτου[22:7]{.aside}

καγω [[ιω]{.greek-abbr}]{.greek-added} [ιωαννης]{.greek-omitted} [ο]{.greek-omitted} ακουων και βλεπων ταυτα και οτε ηκουσα και [εβλεψα]{.greek-omitted} [οτε]{.greek-added} [ειδον]{.greek-added} επεσον προσκυνησαι εμπροσθεν των ποδων του αγγελου του [δεικνυοντος]{.greek-omitted} [δυκναντος]{.greek-added} μοι ταυτα[22:8]{.aside}

και λεγει μοι ορα μη συνδουλος σου ειμι και των αδελφων σου των προφητων και των [τηρουντων]{.greek-omitted} [τυρουντων]{.greek-added} τους λογους [της]{.greek-added} [προφητειας]{.greek-added} του βιβλιου τουτου τω [θεω]{.greek-abbr} προσκυνησον[22:9]{.aside}

και λεγει μοι μη σφραγισης τους λογους της προφητειας του βιβλιου τουτου ο [καιρος]{.greek-omitted} γαρ [κερος]{.greek-added} εγγυς εστιν[22:10]{.aside}

ο αδικων αδικησατω ετι και ο ρυπαρος [ρυπαρευθητω]{.greek-omitted} [ρυπανθηται]{.greek-added} [ετι]{.greek-added} [και]{.greek-added} [ο]{.greek-added} [αγιος]{.greek-added} [αγιασθητω]{.greek-added} ετι και ο δικαιος δικαιοσυνην ποιησατω ετι [και]{.greek-omitted} [ο]{.greek-omitted} [αγιος]{.greek-omitted} [αγιασθητω]{.greek-omitted} [ετι]{.greek-omitted}[22:11]{.aside}

ιδου ερχομαι ταχυ και ο μισθος μου μετ εμου αποδουναι εκαστω ως το εργον εσται αυτου[22:12]{.aside}

εγω το [αλφα]{.greek-omitted} [[α]{.greek-abbr}]{.greek-added} και το [ω]{.greek-abbr} ο πρωτος και ο εσχατος η αρχη και το τελος[22:13]{.aside}

μακαριοι οι ποιουντες τας εντολας αυτου ινα εσται η εξουσια αυτων επι το ξυλον της ζωης και τοις πυλωσιν εισελθωσιν εις την πολιν[22:14]{.aside}

εξω οι κυνες και οι φαρμακοι και οι πορνοι και οι φονεις και οι ειδωλολατραι και πας φιλων και ποιων ψευδος[22:15]{.aside}

εγω [ιησους]{.greek-abbr} επεμψα τον αγγελον μου μαρτυρησαι υμιν ταυτα επι ταις [εκκλησιαις]{.greek-omitted} [εκκλησιες]{.greek-added} εγω ειμι η ριζα και το γενος [δαυιδ]{.greek-abbr} ο αστηρ ο λαμπρος ο πρωινος[22:16]{.aside}

και το [πνευμα]{.greek-abbr} και η νυμφη λεγουσιν ερχου και ο ακουων [ειπατω]{.greek-omitted} [ειπατε]{.greek-added} ερχου και ο διψων ερχεσθω ο θελων λαβετω υδωρ ζωης δωρεαν[22:17]{.aside}

μαρτυρω εγω παντι τω ακουοντι τους λογους της [προφητειας]{.greek-omitted} [προφητιας]{.greek-added} του βιβλιου τουτου εαν τις επιθη επ αυτα [επιθησαι]{.greek-omitted} [επιθειη]{.greek-added} ο [θεος]{.greek-abbr} επ αυτον τας πληγας τας γεγραμμενας εν τω βιβλιω τουτω[22:18]{.aside}

και εαν τις αφελη απο των λογων του βιβλιου της προφητειας ταυτης αφελοι ο [θεος]{.greek-abbr} το μερος αυτου απο του ξυλου της ζωης και εκ της πολεως της αγιας των γεγραμμενων εν τω βιβλιω τουτω[22:19]{.aside}

λεγει ο μαρτυρων ταυτα ναι ερχομαι ταχυ αμην ναι ερχου [κυριε]{.greek-abbr} [ιησου]{.greek-abbr}[22:20]{.aside}

η χαρις του [κυριου]{.greek-abbr} [ημων]{.greek-added} [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} μετα παντων των αγιων αμην [-]{.greek-added}[22:21]{.aside}

