---
title: "Collation of Byz^RP^ vs 32900 (2900)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 2900 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=32900).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 2900                                   	| λογος                              	|
| 2900 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 2900 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 2900               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 2900                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 2900 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 2900                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Mark

### Chapter 1

αρχη του ευαγγελιου [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} υιου του [θεου]{.greek-abbr}[1:1]{.aside}

ως γεγραπται εν τοις προφηταις ιδου εγω αποστελλω τον αγγελον μου προ προσωπου σου ος κατασκευασει την οδον σου εμπροσθεν σου[1:2]{.aside}

φωνη βοωντος εν τη ερημω ετοιμασατε την οδον [κυριου]{.greek-abbr} ευθειας ποιειτε τας τριβους αυτου[1:3]{.aside}

[εγενετο]{.greek-omitted} [εγενετω]{.greek-added} [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} βαπτιζων εν τη ερημω και [κηρυσσων]{.greek-omitted} [κηρυσσον]{.greek-added} [βαπτισμα]{.greek-omitted} [βαπτησμα]{.greek-added} μετανοιας εις αφεσιν αμαρτιων[1:4]{.aside}

και [εξεπορευετο]{.greek-omitted} [εξεπορευετω]{.greek-added} προς αυτον πασα [η]{.greek-omitted} [οι]{.greek-added} ιουδαια χωρα και [οι]{.greek-omitted} [ιεροσολυμιται]{.greek-omitted} [ιεροσολυμηται]{.greek-added} και [εβαπτιζοντο]{.greek-omitted} [εβαπτιζωντω]{.greek-added} παντες εν τω ιορδανη ποταμω υπ αυτου εξομολογουμενοι τας αμαρτιας αυτων[1:5]{.aside}

ην δε ο [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ενδεδυμενος τριχας καμηλου και ζωνην [δερματινην]{.greek-omitted} [δερματηνην]{.greek-added} περι την οσφυν αυτου και [εσθιων]{.greek-omitted} [εσθιον]{.greek-added} ακριδας και [μελι]{.greek-omitted} [μελλι]{.greek-added} αγριον[1:6]{.aside}

και [εκηρυσσεν]{.greek-omitted} [εκηρυσε]{.greek-added} λεγων ερχεται ο ισχυροτερος μου οπισω μου ου ουκ [ειμι]{.greek-omitted} [ειμη]{.greek-added} ικανος κυψας λυσαι [τον]{.greek-omitted} [των]{.greek-added} ιμαντα των υποδηματων [αυτου]{.greek-omitted}[1:7]{.aside}

εγω μεν [εβαπτισα]{.greek-omitted} [εβαπτησα]{.greek-added} υμας εν υδατι αυτος δε [βαπτισει]{.greek-omitted} [βαπτησει]{.greek-added} υμας εν [πνευματι]{.greek-abbr} αγιω[1:8]{.aside}

και εγενετο εν εκειναις ταις ημεραις ηλθεν [[ο]{.corr}]{.greek-added} [ιησους]{.greek-abbr} απο [ναζαρετ]{.greek-omitted} [ναζαρεθ]{.greek-added} της γαλιλαιας και [εβαπτισθη]{.greek-omitted} [εβαπτιστη]{.greek-added} υπο [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} εις τον ιορδανην[1:9]{.aside}

[και]{.corr} [ευθεως]{.greek-omitted} [[ευθυς]{.corr}]{.greek-added} [αναβαινων]{.corr} απο του υδατος [ειδεν]{.greek-omitted} [ειδε]{.greek-added} σχιζομενους τους [ουρανους]{.greek-abbr} και το [πνευμα]{.greek-abbr} ωσει περιστεραν καταβαινον [επ]{.greek-omitted} [αυτον]{.greek-omitted} [εις]{.greek-added} [αυτω]{.greek-added}[1:10]{.aside}

και φωνη [εγενετο]{.greek-omitted} [εγενετω]{.greek-added} εκ [των]{.greek-omitted} [τον]{.greek-added} [ουρανων]{.greek-omitted} [[ουρανον]{.greek-abbr}]{.greek-added} συ ει ο υιος μου ο αγαπητος εν ω [ευδοκησα]{.greek-omitted} [ηυδοκησα]{.greek-added}[1:11]{.aside}

και [ευθυς]{.greek-omitted} [ευθεις]{.greek-added} το [πνευμα]{.greek-abbr} αυτον εκβαλλει εις την [ερημον]{.greek-omitted} [ερρημον]{.greek-added}[1:12]{.aside}

και ην εκει εν τη ερημω ημερας τεσσαρακοντα πειραζομενος υπο του σατανα και ην μετα των θηριων και οι αγγελοι διηκονουν αυτω[1:13]{.aside}

μετα δε το παραδοθηναι τον [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ηλθεν ο [ιησους]{.greek-abbr} εις την γαλιλαιαν κηρυσσων το ευαγγελιον της [βασιλειας]{.greek-omitted} [βασιειας]{.greek-added} του [θεου]{.greek-abbr}[1:14]{.aside}

και λεγων οτι πεπληρωται ο καιρος και [ηγγικεν]{.greek-omitted} [ηγγηκεν]{.greek-added} η βασιλεια του [θεου]{.greek-abbr} [μετανοειτε]{.greek-omitted} [μετανοητε]{.greek-added} και πιστευετε εν τω ευαγγελιω[1:15]{.aside}

περιπατων δε παρα την θαλασσαν της γαλιλαιας [ειδεν]{.greek-omitted} [ειδε]{.greek-added} σιμωνα και ανδρεαν τον αδελφον αυτου του σιμωνος βαλλοντας [αμφιβληστρον]{.greek-omitted} [αφιβληστρον]{.greek-added} εν τη θαλασση ησαν γαρ αλιεις[1:16]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} δευτε οπισω μου και ποιησω υμας γενεσθαι αλιεις [ανθρωπων]{.greek-abbr}[1:17]{.aside}

και ευθεως αφεντες τα δικτυα αυτων ηκολουθησαν αυτω[1:18]{.aside}

και προβας εκειθεν ολιγον ειδεν ιακωβον [τον]{.greek-omitted} [των]{.greek-added} του ζεβεδαιου και [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} τον αδελφον αυτου και αυτους εν τω πλοιω [καταρτιζοντας]{.greek-omitted} [καταρτιζωντας]{.greek-added} τα [δικτυα]{.greek-omitted} [δικτια]{.greek-added}[1:19]{.aside}

και ευθεως [εκαλεσεν]{.greek-omitted} [αυτους]{.greek-omitted} [και]{.greek-omitted} αφεντες τον [πατερα]{.greek-abbr} αυτων ζεβεδαιον εν τω πλοιω μετα των μισθωτων απηλθον οπισω αυτου[1:20]{.aside}

και [εισπορευονται]{.greek-omitted} [εισπορευεται]{.greek-added} εις καπερναουμ και ευθεως τοις σαββασιν εισελθων εις την συναγωγην εδιδασκεν[1:21]{.aside}

και [εξεπλησσοντο]{.greek-omitted} [εξεπλησοντω]{.greek-added} επι τη διδαχη αυτου ην γαρ [διδασκων]{.greek-omitted} [διδασκον]{.greek-added} αυτους ως εξουσιαν εχων και ουχ ως οι γραμματεις[1:22]{.aside}

και ην εν τη συναγωγη αυτων [ανθρωπος]{.greek-abbr} εν [πνευματι]{.greek-abbr} ακαθαρτω και ανεκραξεν[1:23]{.aside}

λεγων εα τι [ημιν]{.greek-omitted} [υμιν]{.greek-added} και σοι [ιησου]{.greek-abbr} [ναζαρηνε]{.greek-omitted} [ναζαρινε]{.greek-added} ηλθες απολεσαι [ημας]{.greek-omitted} [υμας]{.greek-added} οιδα σε τις ει ο αγιος του [θεου]{.greek-abbr}[1:24]{.aside}

και [επετιμησεν]{.greek-omitted} [επετημησεν]{.greek-added} αυτω ο [ιησους]{.greek-abbr} λεγων φιμωθητι και εξελθε εξ αυτου[1:25]{.aside}

και σπαραξαν αυτον το [πνευμα]{.greek-abbr} το ακαθαρτον και κραξαν φωνη μεγαλη εξηλθεν [εξ]{.greek-omitted} [απ]{.greek-added} αυτου[1:26]{.aside}

και εθαμβηθησαν παντες ωστε συζητειν προς [εαυτους]{.greek-omitted} [αυτους]{.greek-added} [λεγοντας]{.greek-omitted} [λεγωντας]{.greek-added} τι [εστιν]{.greek-omitted} [εστι]{.greek-added} τουτο τις η διδαχη η [καινη]{.greek-omitted} [κενη]{.greek-added} αυτη οτι κατ εξουσιαν και τοις πνευμασιν τοις [ακαθαρτοις]{.greek-omitted} [επιτασσει]{.greek-omitted} [και]{.greek-omitted} [υπακουουσιν]{.greek-omitted} [αυτω]{.greek-omitted}[1:27]{.aside}

[εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} δε η ακοη αυτου ευθυς εις ολην την περιχωρον της γαλιλαιας[1:28]{.aside}

και ευθεως εκ της συναγωγης [εξελθοντες]{.greek-omitted} [εξελθων]{.greek-added} [ηλθον]{.greek-omitted} [ηλθεν]{.greek-added} εις την οικιαν σιμωνος και ανδρεου μετα ιακωβου και [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added}[1:29]{.aside}

η δε πενθερα σιμωνος [κατεκειτο]{.greek-omitted} [κατεκειτω]{.greek-added} [πυρεσσουσα]{.greek-omitted} [πηρεσουσα]{.greek-added} και ευθεως λεγουσιν αυτω περι αυτης[1:30]{.aside}

και προσελθων [ηγειρεν]{.greek-omitted} [ηγυρεν]{.greek-added} αυτην κρατησας της χειρος [αυτης]{.greek-omitted} και αφηκεν αυτην ο [πυρετος]{.greek-omitted} [πηρετος]{.greek-added} ευθεως και διηκονει αυτοις[1:31]{.aside}

οψιας δε γενομενης οτε [εδυ]{.greek-omitted} [εδη]{.greek-added} ο ηλιος εφερον προς αυτον παντας τους [κακως]{.greek-omitted} [κακος]{.greek-added} [εχοντας]{.greek-omitted} [εχωντας]{.greek-added} και τους [δαιμονιζομενους]{.greek-omitted} [δαιμονιζωμενους]{.greek-added}[1:32]{.aside}

και η πολις ολη [επισυνηγμενη]{.greek-omitted} [επισυνηγμενην]{.greek-added} [ην]{.greek-omitted} προς την θυραν[1:33]{.aside}

και εθεραπευσεν πολλους [κακως]{.greek-omitted} [κακος]{.greek-added} [εχοντας]{.greek-omitted} [εχωντας]{.greek-added} [ποικιλαις]{.greek-omitted} [ποικηλαις]{.greek-added} νοσοις και δαιμονια πολλα [εξεβαλεν]{.greek-omitted} [εξεβαλε]{.greek-added} και ουκ [ηφιεν]{.greek-omitted} [ηφιε]{.greek-added} λαλειν τα δαιμονια οτι ηδεισαν αυτον [[χριστον]{.greek-abbr}]{.greek-added} [ειναι]{.greek-added}[1:34]{.aside}

και πρωι εννυχον λιαν αναστας [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} και απηλθεν εις ερημον τοπον κακει [προσηυχετο]{.greek-omitted} [προσηυχετω]{.greek-added}[1:35]{.aside}

και κατεδιωξαν αυτον ο σιμων και οι μετ αυτου[1:36]{.aside}

και ευροντες αυτον λεγουσιν αυτω οτι παντες σε ζητουσιν[1:37]{.aside}

και λεγει αυτοις αγωμεν εις τας [εχομενας]{.greek-omitted} [εχωμενας]{.greek-added} [κωμοπολεις]{.greek-omitted} [κωμωπολις]{.greek-added} ινα και εκει κηρυξω εις τουτο γαρ [εξεληλυθα]{.greek-omitted} [εξηληλυθα]{.greek-added}[1:38]{.aside}

και ην [κηρυσσων]{.greek-omitted} [κηρυσσον]{.greek-added} [εν]{.greek-omitted} [εις]{.greek-added} [ταις]{.greek-omitted} [τας]{.greek-added} [συναγωγαις]{.greek-omitted} [συναγωγας]{.greek-added} [αυτων]{.greek-omitted} εις ολην την γαλιλαιαν και τα δαιμονια εκβαλλων[1:39]{.aside}

και ερχεται προς αυτον λεπρος παρακαλων αυτον και [γονυπετων]{.greek-omitted} [γωνυπετων]{.greek-added} αυτον και λεγων αυτω οτι εαν θελης δυνασαι με καθαρισαι[1:40]{.aside}

ο δε [ιησους]{.greek-abbr} [σπλαγχνισθεις]{.greek-omitted} [σπλαγχνισθης]{.greek-added} εκτεινας την χειρα [ηψατο]{.greek-omitted} [ηψατω]{.greek-added} αυτου και λεγει αυτω θελω καθαρισθητι[1:41]{.aside}

και ειποντος [αυτου]{.greek-omitted} ευθεως απηλθεν απ αυτου η λεπρα και εκαθαρισθη[1:42]{.aside}

και [εμβριμησαμενος]{.greek-omitted} [ευρημησαμενος]{.greek-added} αυτω ευθεως [εξεβαλεν]{.greek-omitted} [εξεβαλλεν]{.greek-added} αυτον[1:43]{.aside}

και λεγει αυτω ορα [μηδενι]{.greek-omitted} μηδεν ειπης αλλ υπαγε σεαυτον δειξον τω ιερει και [προσενεγκε]{.greek-omitted} [προσενεγκεν]{.greek-added} περι του καθαρισμου σου α προσεταξεν μωσης εις μαρτυριον αυτοις[1:44]{.aside}

ο δε εξελθων [ηρξατο]{.greek-omitted} [ηρξατω]{.greek-added} [κηρυσσειν]{.greek-omitted} [κηρυσσιν]{.greek-added} πολλα και διαφημιζειν τον λογον ωστε μηκετι αυτον [δυνασθαι]{.greek-omitted} [δυνασται]{.greek-added} [αυτον]{.greek-added} [φανερως]{.greek-omitted} [φανερος]{.greek-added} εις πολιν [εισελθειν]{.greek-omitted} [ελθειν]{.greek-added} αλλ εξω [εν]{.greek-omitted} [εμ]{.greek-added} ερημοις τοποις ην και [ηρχοντο]{.greek-omitted} [ηρχοντω]{.greek-added} προς αυτον [πανταχοθεν]{.greek-omitted} [πανταχωθεν]{.greek-added}[1:45]{.aside}

[επιτασσοι]{.greek-added} [και]{.greek-added} [υπακουουσιν]{.greek-added} [αυτω]{.greek-added}[1:ακαθαρ]{.aside}

### Chapter 2

και εισηλθεν [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} παλιν εις καπερναουμ [δι]{.greek-omitted} [δη]{.greek-added} ημερων [και]{.greek-omitted} ηκουσθη οτι εις οικον [εστιν]{.greek-omitted} [εστι]{.greek-added}[2:1]{.aside}

και ευθεως συνηχθησαν πολλοι ωστε μηκετι χωρειν μηδε τα προς την θυραν και ελαλει αυτοις τον λογον[2:2]{.aside}

και ερχονται προς αυτον [παραλυτικον]{.greek-omitted} [παραλυτηκον]{.greek-added} [φεροντες]{.greek-omitted} [φερωντες]{.greek-added} αιρομενον υπο τεσσαρων[2:3]{.aside}

και μη δυναμενοι προσεγγισαι [αυτω]{.greek-omitted} δια τον οχλον απεστεγασαν την στεγην οπου ην και [εξορυξαντες]{.greek-omitted} [εξωρυξαντες]{.greek-added} χαλωσιν τον κραββατον εφ ω ο [παραλυτικος]{.greek-omitted} [κατεκειτο]{.greek-omitted}[2:4]{.aside}

