---
title: "Collation of Byz^RP^ vs 32919 (2919)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 2919 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=32919).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 2919                                   	| λογος                              	|
| 2919 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 2919 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 2919               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 2919                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 2919 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 2919                                                     	| [―]{.gap}                        	|
:::

## Revelation

### Chapter 1

αποκαλυψις [του]{.greek-added} [[κυριου]{.greek-abbr}]{.greek-added} [ημων]{.greek-added} [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} ην εδωκεν [αυτω]{.greek-omitted} [αυτο[υ]{.unclear}]{.greek-added} ο [θεος]{.greek-abbr} δειξαι τοις δουλοις αυτου α δει γενεσθαι εν ταχει και [εσημανεν]{.greek-omitted} [εσημαν]{.greek-added} αποστειλας δια του αγγελου αυτου τω δουλω αυτου ιωαννη[1:1]{.aside}

ος εμαρτυρησεν τον λογον του [θεου]{.greek-abbr} και την μαρτυριαν [ιησου]{.greek-abbr} [χριστου]{.greek-omitted} οσα [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} [και]{.greek-added} [ατινα]{.greek-added} [εισιν]{.greek-added} [και]{.greek-added} [ατινα]{.greek-added} [χρη]{.greek-added} [γενεσθαι]{.greek-added} [μετα]{.greek-added} [ταυτα]{.greek-added}[1:2]{.aside}

μακαριος ο [αναγινωσκων]{.greek-omitted} [αναγινωσκον]{.greek-added} και οι ακουοντες τους λογους της [προφητειας]{.greek-omitted} [προφητιας]{.greek-added} και τηρουντες τα εν αυτη γεγραμμενα ο γαρ καιρος εγγυς[1:3]{.aside}

ιωαννης ταις επτα εκκλησιαις ταις εν τη ασια χαρις υμιν και ειρηνη απο [θεου]{.greek-omitted} ο ων και ο ην και ο ερχομενος και απο των επτα [πνευματων]{.greek-abbr} α [εστιν]{.greek-added} [ενωπιον]{.greek-omitted} [ενοπιον]{.greek-added} του θρονου αυτου[1:4]{.aside}

και απο [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} ο μαρτυς ο πιστος ο πρωτοτοκος [εκ]{.greek-added} [των]{.greek-added} των νεκρων και ο [αρχων]{.greek-omitted} [αρχον]{.greek-added} των βασιλεων της γης [τω]{.greek-omitted} [αγαπωντι]{.greek-omitted} [του]{.greek-added} [αγαπησαντος]{.greek-added} ημας και [λουσαντι]{.greek-omitted} [λυσαντι]{.greek-added} [[ως]{.corr}]{.greek-added} ημας [απο]{.greek-omitted} [εκ]{.greek-added} των αμαρτιων [ημων]{.greek-omitted} εν τω αιματι αυτου[1:5]{.aside}

και εποιησεν ημας [βασιλειαν]{.greek-omitted} [βασιλεις]{.greek-added} [και]{.greek-added} ιερεις τω [θεω]{.greek-abbr} και [πατρι]{.greek-abbr} αυτου αυτω η δοξα και το κρατος εις τους [αιωνας]{.greek-omitted} [αινας]{.greek-added} των αιωνων αμην[1:6]{.aside}

ιδου ερχεται μετα των νεφελων και [οψεται]{.greek-omitted} [οψονται]{.greek-added} αυτον πας οφθαλμος και οιτινες αυτον εξεκεντησαν και κοψονται επ αυτον πασαι αι φυλαι της γης ναι αμην[1:7]{.aside}

εγω ειμι το [αλφα]{.greek-omitted} [ἄλφα]{.greek-added} και το ω [αρχη]{.greek-added} [και]{.greek-added} [τελος]{.greek-added} λεγει [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο ων και ο ην και ο ερχ[ομενος]{.unclear} ο παντοκρατωρ[1:8]{.aside}

εγω [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ο αδελφος υμων και [κοινωνος]{.greek-omitted} [συνκοινωνος]{.greek-added} εν τη [θλιψει]{.greek-omitted} [θλιψη]{.greek-added} και [εν]{.greek-added} [τη]{.greek-added} βασιλεια και υπομονη [εν]{.greek-omitted} [χριστω]{.greek-omitted} [ιησου]{.greek-abbr} [[χριστου]{.greek-abbr}]{.greek-added} [εγενομην]{.greek-omitted} [εγεναμην]{.greek-added} εν τη νησω τη καλουμενη πατμω δια τον λογον του [θεου]{.greek-abbr} και δια την μαρτυριαν [ιησου]{.greek-abbr} [οπτασια]{.greek-added} [εν]{.greek-added} [η]{.greek-added} [τον]{.greek-added} [χριστου]{.greek-omitted} [[χριστον]{.greek-abbr}]{.greek-added} [εθεασατο]{.greek-added} [εν]{.greek-added} [μεσεν]{.greek-added} [επτα]{.greek-added} [λυχνιαν]{.greek-added} [χρυσων]{.greek-added} [εν]{.greek-added} [δε]{.greek-added} [δυμενον]{.greek-added} [ποδηρη]{.greek-added}[1:9]{.aside}

[εγενομην]{.greek-omitted} [εγεναμην]{.greek-added} εν [πνευματι]{.greek-abbr} εν τη κυριακη ημερα και ηκουσα [φωνην]{.greek-omitted} οπισω μου [φωνην]{.greek-added} μεγαλην ως σαλπιγγος [ηχουσης]{.greek-added} [εγω]{.greek-added} [ειμι]{.greek-added} [το]{.greek-added} [ἄλφα]{.greek-added} [και]{.greek-added} [το]{.greek-added} [[ω]{.greek-abbr}]{.greek-added} [ο]{.greek-added} [πρωτος]{.greek-added} [και]{.greek-added} [ο]{.greek-added} [εσχατος]{.greek-added} [και]{.greek-added}[1:10]{.aside}

[λεγουσης]{.greek-omitted} ο βλεπεις γραψον εις βιβλιον και πεμψον ταις επτα εκκλησιαις εις εφεσον και εις [σμυρναν]{.greek-omitted} [σμυρνην]{.greek-added} και εις περγαμον και εις [θυατειρα]{.greek-omitted} [θυατηρας]{.greek-added} και εις σαρδεις και εις [φιλαδελφειαν]{.greek-omitted} [φιλαδελφιαν]{.greek-added} και εις [λαοδικειαν]{.greek-omitted} [λαοδικιαν]{.greek-added}[1:11]{.aside}

και [εκει]{.greek-omitted} επεστρεψα [βλεπειν]{.greek-omitted} [ιδειν]{.greek-added} την φωνην ητις [ελαλει]{.greek-omitted} [ελαλησεν]{.greek-added} μετ εμου και [επιστρεψας]{.greek-omitted} [επεστρεψας]{.greek-added} [ειδον]{.greek-omitted} [ιδον]{.greek-added} επτα λυχνιας χρυσας[1:12]{.aside}

και εν μεσω των [επτα]{.greek-omitted} λυχνιων ομοιον [υιω]{.greek-abbr} [ανθρωπου]{.greek-abbr} ενδεδυμενον ποδηρη και περιεζωσμενον προς τοις [μαστοις]{.greek-omitted} [μασθοις]{.greek-added} ζωνην χρυσην[1:13]{.aside}

η δε κεφαλη αυτου και αι τριχες λευκαι ως [εριον]{.greek-omitted} [ιερειον]{.greek-added} λευκον ως χιων και οι οφθαλμοι αυτο[υ]{.unclear} ως φλοξ πυρος[1:14]{.aside}

και οι ποδες αυτου ομοιοι χαλκολιβανω ως εν καμινω πεπυρωμενοι και η φωνη αυτου ως φωνη υδατων πολλων[1:15]{.aside}

και εχων εν τη δεξια [χειρι]{.greek-added} αυτου [χειρι]{.greek-omitted} αστερας επτα και εκ του στοματος αυτου ρομφαια διστομος οξεια εκπορευομενη και η οψις αυτου ως ο ηλιος φαινει εν τη δυναμει αυτου[1:16]{.aside}

και οτε [ειδον]{.greek-omitted} [ιδον]{.greek-added} αυτον επεσα προς τους ποδας αυτου ως νεκρος και [εθηκεν]{.greek-omitted} [επεθηκε]{.greek-added} την δεξιαν αυτου [χειρα]{.greek-added} επ εμε λεγων μη φοβου εγω ειμι ο πρωτος και ο εσχατος[1:17]{.aside}

και ο ζων και εγενομην νεκρος και ιδου ζων ειμι εις τους αιωνας των αιωνων αμην και εχω τας κλεις του [θανατου]{.greek-omitted} [αδου]{.greek-added} και του [αδου]{.greek-omitted} [θανατου]{.greek-added} [αντι]{.greek-added} [του]{.greek-added} [την]{.greek-added} [εξουσιαν]{.greek-added} [του]{.greek-added} [σωματικου]{.greek-added} [και]{.greek-added} [ψυχικου]{.greek-added} [θαλατου]{.greek-added}[1:18]{.aside}

γραψον ουν α [ειδες]{.greek-omitted} [ιδες]{.greek-added} και α εισιν και α μελλει γινεσθαι μετα ταυτα[1:19]{.aside}

το μυστηριον των επτα αστερων [ων]{.greek-omitted} [ους]{.greek-added} [ειδες]{.greek-omitted} [ιδες]{.greek-added} επι της δεξιας μου και τας επτα λυχνιας τας χρυσας οι επτα αστερες αγγελοι των επτα εκκλησιων εισιν και αι [[επτα]{.unclear}]{.greek-added} λυχνιαι [αι]{.greek-omitted} [ας]{.greek-added} [ιδες]{.greek-added} επτα [εκ]{.greek-added} [επτα]{.greek-omitted} [εκκλησιαι]{.greek-omitted} [εισιν]{.greek-omitted}[1:20]{.aside}

[κλησιαι]{.greek-added} [το]{.greek-omitted} [μυστηριον]{.greek-omitted} [των]{.greek-omitted} [επτα]{.greek-omitted} [αστερων]{.greek-omitted} [ων]{.greek-omitted} [ειδες]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [δεξιας]{.greek-omitted} [μου]{.greek-omitted} [και]{.greek-omitted} [τας]{.greek-omitted} [επτα]{.greek-omitted} [λυχνιας]{.greek-omitted} [τας]{.greek-omitted} [χρυσας]{.greek-omitted} [οι]{.greek-omitted} [επτα]{.greek-omitted} [αστερες]{.greek-omitted} [αγγελοι]{.greek-omitted} [των]{.greek-omitted} [επτα]{.greek-omitted} [εκκλησιων]{.greek-omitted} εισιν [και]{.greek-omitted} [αι]{.greek-omitted} [λυχνιαι]{.greek-omitted} [αι]{.greek-omitted} [επτα]{.greek-omitted} [επτα]{.greek-omitted} [εκκλησιαι]{.greek-omitted} [εισιν]{.greek-omitted}[1:20 | instance no. 2]{.aside}

### Chapter 2

τω αγγελω της εν εφεσω εκκλησιας γραψον ταδε λεγει ο κρατων τους επτα αστερας εν τη δεξια αυτου ο περιπατων εν μεσω των επτα λυχνιων των χρυσων[2:1]{.aside}

οιδα τα εργα σου και τον κοπον [σου]{.greek-omitted} και την υπομονην σου και οτι ου δυνη [βαστασαι]{.greek-omitted} [βασταξαι]{.greek-added} κακους και επειρασας τους λεγοντας [εαυτους]{.greek-omitted} αποστολους ειναι και ουκ εισιν και ευρες αυτους ψευδεις[2:2]{.aside}

[και]{.greek-added} [εβαστασας]{.greek-added} και υπομονην εχεις [και]{.greek-omitted} [εβαστασας]{.greek-omitted} δια το ονομα μου και [ουκ]{.greek-omitted} [ου]{.greek-added} [εκοπιασας]{.greek-omitted} [κεκοπίασας]{.greek-added}[2:3]{.aside}

[αλλα]{.greek-omitted} [αλλ]{.greek-added} εχω κατα σου οτι την αγαπην [σου]{.greek-omitted} την πρωτην αφηκας[2:4]{.aside}

μνημονευε ουν ποθεν [εκ]{.greek-added} πεπτωκας και μετανοησον και τα πρωτα εργα ποιησον ει δε μη ερχομαι [σοι]{.greek-omitted} ταχυ και κινησω την λυχνιαν σου εκ του τοπου αυτης εαν μη μετανοησης[2:5]{.aside}

αλλα τουτο εχεις οτι μισεις τα εργα των νικολαιτων α [καγω]{.greek-omitted} [εγω]{.greek-added} μισω[2:6]{.aside}

ο εχων ους [ακουσατω]{.greek-omitted} [ακουσατο]{.greek-added} τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις τω [νικωντι]{.greek-omitted} [νικοντι]{.greek-added} δωσω αυτω φαγειν εκ του ξυλου της ζωης ο εστιν εν [τω]{.greek-omitted} [μεσω]{.greek-added} [του]{.greek-added} [παραδεισω]{.greek-omitted} [παραδεισου]{.greek-added} του [θεου]{.greek-abbr} [μου]{.greek-omitted}[2:7]{.aside}

και τω αγγελω της εν σμυρνη εκκλησιας γραψον ταδε λεγει ο πρωτος και ο εσχατος ος εγενετο νεκρος και [εζησεν]{.greek-omitted} [εξησεν]{.greek-added}[2:8]{.aside}

οιδα σου τα εργα και την θλιψιν και [την]{.greek-omitted} πτωχειαν αλλα πλουσιος ει και την βλασφημιαν [εκ]{.greek-omitted} των λεγοντων [ιουδαιους]{.greek-omitted} [ιουδαιοι]{.greek-added} ειναι εαυτους και ουκ εισιν αλλα συναγωγη του σατανα[2:9]{.aside}

μηδεν φοβου α μελλεις [παθειν]{.greek-omitted} [πασχειν]{.greek-added} ιδου [δη]{.greek-omitted} μελλει [βαλειν]{.greek-omitted} [βάλλειν]{.greek-added} ο διαβολος εξ υμων εις [φυλακην]{.greek-omitted} [φυλακειν]{.greek-added} ινα πειρασθητε και [εξετε]{.greek-omitted} [εχετε]{.greek-added} θλιψιν ημερων δεκα γινου πιστος [αχρι]{.greek-omitted} [αχρη]{.greek-added} θανατου και δωσω σοι τον στεφανον της ζωης[2:10]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις ο νικων ου μη αδικηθη εκ του [τουτου]{.greek-added} [θανατου]{.greek-omitted} [του]{.greek-omitted} δευτερου[2:11]{.aside}

και τω αγγελω της εν περγαμω εκκλησιας γραψον ταδε λεγει ο εχων την ρομφαιαν την διστομον την οξειαν[2:12]{.aside}

οιδα τα εργα σου και που κατοικεις οπου ο θρονος του σατανα και κρατεις το ονομα μου και ουκ ηρνησω την [πιστιν]{.greek-omitted} [πιστην]{.greek-added} μου εν ταις ημεραις εν αις [αντιπας]{.greek-omitted} [ἆντι]{.greek-added} [πᾶς]{.greek-added} ο μαρτυς [μου]{.greek-omitted} ο πιστος [οτι]{.greek-added} [πας]{.greek-added} [μαρ]{.greek-added} [ος]{.greek-omitted} [απεκτανθη]{.greek-omitted} [παρ]{.greek-omitted} [υμιν]{.greek-omitted} [οπου]{.greek-omitted} [ο]{.greek-omitted} [σατανας]{.greek-omitted} [κατοικει]{.greek-omitted}[2:13]{.aside}

[τυς]{.greek-added} [οιδα]{.greek-omitted} [τα]{.greek-omitted} [εργα]{.greek-omitted} [σου]{.greek-omitted} [και]{.greek-omitted} [που]{.greek-omitted} [κατοικεις]{.greek-omitted} [οπου]{.greek-omitted} [ο]{.greek-omitted} [θρονος]{.greek-omitted} [του]{.greek-omitted} [σατανα]{.greek-omitted} [και]{.greek-omitted} [κρατεις]{.greek-omitted} [το]{.greek-omitted} [ονομα]{.greek-omitted} [μου]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [ηρνησω]{.greek-omitted} [την]{.greek-omitted} [πιστιν]{.greek-omitted} [μου]{.greek-omitted} [εν]{.greek-omitted} [ταις]{.greek-omitted} [ημεραις]{.greek-omitted} [εν]{.greek-omitted} [αις]{.greek-omitted} [αντιπας]{.greek-omitted} [ο]{.greek-omitted} [μαρτυς]{.greek-omitted} [μου]{.greek-omitted} ο πιστος ος απεκτανθη παρ υμιν οπου ο σατανας κατοικει[2:13 | instance no. 2]{.aside}

αλλ εχω κατα σου ολιγα οτι εχεις εκει κρατουντας την διδαχην βαλααμ ος [εδιδαξεν]{.greek-omitted} [εδιδασκεν]{.greek-added} [ο]{.greek-added} [βαλααμ]{.greek-added} τον [βαλακ]{.greek-omitted} [βαλαακ]{.greek-added} βαλειν σκανδαλον ενωπιον των υιων [ισραηλ]{.greek-abbr} [και]{.greek-omitted} φαγειν [ειδωλοθυτα]{.greek-omitted} [ειδολοθυτα]{.greek-added} και πορνευσαι[2:14]{.aside}

ουτως [εχεις]{.greek-omitted} και συ κρατουντας την διδαχην των νικολαιτων ομοιως [ομισω]{.greek-added}[2:15]{.aside}

μετανοησον [ουν]{.greek-omitted} ει δε μη ερχομαι σοι ταχυ και πολεμησω μετ αυτων εν τη ρομφαια του στοματος μου[2:16]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις τω [νικωντι]{.greek-omitted} [νικοντι]{.greek-added} δωσω αυτω [φαγειν]{.greek-added} [απο]{.greek-added} του μαννα του κεκρυμμενου και δωσω αυτω ψηφον λευκην και επι την ψηφον ονομα καινον γεγραμμενον ο ουδεις οιδεν ει μη ο λαμβανων[2:17]{.aside}

και τω αγγελω της εν [θυατειροις]{.greek-omitted} [θυατηριοις]{.greek-added} εκκλησιας γραψον ταδε λεγει ο [υιος]{.greek-abbr} του [θεου]{.greek-abbr} ο εχων τους οφθαλμους αυτου ως [φλογα]{.greek-omitted} [φλοξ]{.greek-added} πυρος και οι ποδες αυτου ομοιοι χαλκολιβανω[2:18]{.aside}

οιδα σου τα [εργα]{.greek-omitted} και την αγαπην και την [πιστιν]{.greek-omitted} [πιστην]{.greek-added} και την διακονιαν και την υπομονην σου και τα εργα σου [και]{.greek-added} τα εσχατα πλειονα των πρωτων[2:19]{.aside}

αλλ εχω κατα σου [πολυ]{.greek-added} οτι αφεις την γυναικα [σου]{.greek-omitted} ιεζαβελ [η]{.greek-omitted} [λεγει]{.greek-omitted} [την]{.greek-added} [λεγουσαν]{.greek-added} εαυτην [προφητιν]{.greek-omitted} [προφητην]{.greek-added} και διδασκει και πλανα τους εμους δουλους πορνευσαι και φαγειν ειδωλοθυτα[2:20]{.aside}

και [εδωκα]{.greek-omitted} [εδοκα]{.greek-added} αυτη χρονον ινα μετανοηση [και]{.greek-omitted} [ου]{.greek-omitted} [θελει]{.greek-omitted} [μετανοησαι]{.greek-omitted} εκ της πορνειας αυτης[2:21]{.aside}

ιδου βαλλω αυτην εις κλινην και τους μοιχευοντας μετ αυτης εις θλιψιν μεγαλην εαν μη μετανοησωσιν εκ των εργων [αυτης]{.greek-omitted} [αυτων]{.greek-added}[2:22]{.aside}

και τα τεκνα αυτης αποκτενω εν θανατω και γνωσονται πασαι αι εκκλησιαι οτι εγω ειμι ο ερευνων νεφρους και καρδιας και δωσω υμιν εκαστω κατα τα εργα υμων[2:23]{.aside}

υμιν [δε]{.greek-omitted} λεγω τοις λοιποις τοις εν [θυατειροις]{.greek-omitted} [θυατηριοις]{.greek-added} οσοι ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} την διδαχην ταυτην οιτινες ουκ εγνωσαν τα [βαθεα]{.greek-omitted} [βαθη]{.greek-added} του σατανα ως λεγουσιν ου βαλλω εφ υμας αλλο βαρος[2:24]{.aside}

πλην ο εχετε κρατησατε [αχρι]{.greek-omitted} [αχρις]{.greek-added} ου αν ηξω[2:25]{.aside}

και ο νικων και ο τηρων αχρι τελους τα εργα μου δωσω αυτω εξουσιαν επι των εθνων[2:26]{.aside}

και ποιμανει αυτους εν ραβδω σιδηρα ως τα [σκευη]{.greek-omitted} [σκευει]{.greek-added} τα κεραμικα [συντριβησεται]{.greek-omitted} [συντριβεται]{.greek-added} [ως]{.greek-omitted} [καγω]{.greek-omitted} [ειληφα]{.greek-omitted} [παρα]{.greek-omitted} [του]{.greek-omitted} [πατρος]{.greek-omitted} [μου]{.greek-omitted}[2:27]{.aside}

[και]{.greek-omitted} [δωσω]{.greek-omitted} [αυτω]{.greek-omitted} [τον]{.greek-omitted} [αστερα]{.greek-omitted} [τον]{.greek-omitted} [πρωινον]{.greek-omitted} [ως]{.greek-added} [καγω]{.greek-added} [ειληφα]{.greek-added} [παρα]{.greek-added} [του]{.greek-added} [[πατρος]{.greek-abbr}]{.greek-added} [μου]{.greek-added}[2:28]{.aside}

και δωσω αυτω τον αστερα τον πρωινον[2:28 | instance no. 2]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[2:29]{.aside}

### Chapter 3

και τω αγγελω της εν σαρδεσιν εκκλησιας γραψον ταδε λεγει ο εχων τα [επτα]{.greek-omitted} [πνευματα]{.greek-abbr} του [θεου]{.greek-abbr} και τους επτα αστερας οιδα σου τα εργα οτι ονομα εχεις οτι [ζης]{.greek-omitted} [ζεις]{.greek-added} και νεκρος ει[3:1]{.aside}

γινου [γρηγορων]{.greek-omitted} [γριγορων]{.greek-added} και [στηρισον]{.greek-omitted} [τηρισον]{.greek-added} τα λοιπα [α]{.greek-omitted} [εμελλες]{.greek-omitted} [αποβαλλειν]{.greek-omitted} [αμελλον]{.greek-added} [[εμελλον]{.corr}]{.greek-added} [αποθανειν]{.greek-added} ου γαρ ευρηκα σου τα εργα πεπληρωμενα ενωπιον του [[θεου]{.greek-abbr}]{.unclear} [μου]{.greek-omitted}[3:2]{.aside}

μνημονευε ουν πως ειληφας και ηκουσας και τηρει και μετανοησον εαν ουν μη [γρηγορησης]{.greek-omitted} [γρηγορησις]{.greek-added} ηξω [επι]{.greek-omitted} [σε]{.greek-omitted} ως κλεπτης και ου μη γνως [ποιαν]{.greek-omitted} [ποια]{.greek-added} [ωραν]{.greek-omitted} [ωρα]{.greek-added} ηξω επι σε[3:3]{.aside}

[αλλ]{.greek-omitted} [εχεις]{.greek-added} ολιγα [εχεις]{.greek-omitted} ονοματα εν σαρδεσιν [α]{.greek-omitted} [οι]{.greek-added} ουκ εμολυναν τα ιματια αυτων και περιπατησουσιν μετ εμου εν λευκοις οτι αξιοι εισιν[3:4]{.aside}

ο νικων [ουτος]{.greek-omitted} [ουτως]{.greek-added} περιβαλειται εν ιματιοις λευκοις και ου μη εξαλειψω το ονομα αυτου εκ της βιβλου της ζωης [και]{.greek-omitted} [ομολογησω]{.greek-omitted} [το]{.greek-omitted} [ονομα]{.greek-omitted} [αυτου]{.greek-omitted} ενωπιον του [πατρος]{.greek-abbr} μου και ενωπιον [των]{.greek-omitted} αγγελων αυτου[3:5]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[3:6]{.aside}

και τω αγγελω της εν [φιλαδελφεια]{.greek-omitted} [φιλαδελφια]{.greek-added} εκκλησιας γραψον ταδε λεγει ο αγιος ο αληθινος ο εχων την [κλειν]{.greek-omitted} [κλειδα]{.greek-added} του [δαυιδ]{.greek-abbr} ο [ανοιγων]{.greek-omitted} [ανογων]{.greek-added} [ουδεις]{.greek-added} [κλειει]{.greek-added} [και]{.greek-added} [κλειον]{.greek-added} και ουδεις [κλεισει]{.greek-omitted} [αυτην]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [ο]{.greek-omitted} [ανοιγων]{.greek-omitted} [και]{.greek-omitted} [ουδεις]{.greek-omitted} [ανοιξει]{.greek-omitted} [ανοιγει]{.greek-added}[3:7]{.aside}

οιδα σου τα εργα ιδου δεδωκα ενωπιον σου θυραν [ανεωγμενην]{.greek-omitted} [ηνεωγμενην]{.greek-added} ην ουδεις δυναται κλεισαι αυτην οτι μικραν εχεις δυναμιν και ετηρησας μου τον λογον και ουκ ηρνησω το ονομα μου[3:8]{.aside}

ιδου [διδωμι]{.greek-omitted} [διδω]{.greek-added} [μοι]{.greek-added} εκ της συναγωγης του σατανα των λεγοντων εαυτους ιουδαιους ειναι και ουκ εισιν αλλα ψευδονται [ιδου]{.greek-omitted} [και]{.greek-added} ποιησω αυτους ινα [ηξωσιν]{.greek-omitted} [ηξωσι]{.greek-added} και προσκυνησωσιν ενωπιον των ποδων σου και γνωσιν οτι [εγω]{.greek-added} ηγαπησα σε[3:9]{.aside}

οτι [ετηρησας]{.greek-omitted} [ετηρισας]{.greek-added} τον λογον της υπομονης μου καγω σε [τηρησω]{.greek-omitted} [τηρισω]{.greek-added} εκ της ωρας του πειρασμου της μελλουσης ερχεσθαι επι της οικουμενης ολης πειρασαι τους κατοικουντας επι της γης[3:10]{.aside}

ερχομαι ταχυ κρατει ο εχεις ινα μηδεις λαβη τον στεφανον σου[3:11]{.aside}

ο νικων ποιησω αυτον στυλον εν τω ναω του [θεου]{.greek-abbr} μου και εξω ου μη εξελθη ετι και γραψω επ αυτον το [ονομα]{.greek-omitted} [ονα]{.greek-added} [του]{.greek-omitted} [θεου]{.greek-omitted} [μου]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [ονομα]{.greek-omitted} [της]{.greek-omitted} [πολεως]{.greek-omitted} του [θεου]{.greek-abbr} μου της καινης [ιερουσαλημ]{.greek-abbr} η [καταβαινει]{.greek-omitted} [καταβαινουσα]{.greek-added} εκ του [ουρανου]{.greek-abbr} απο του [θεου]{.greek-abbr} μου και [το]{.greek-omitted} ονομα μου το καινον[3:12]{.aside}

ο εχων ους [ακουσατω]{.greek-omitted} [τι]{.greek-omitted} [το]{.greek-omitted} [πνευμα]{.greek-omitted} [λεγει]{.greek-omitted} [ταις]{.greek-omitted} [εκκλησιαις]{.greek-omitted}[3:13]{.aside}

[ο]{.greek-omitted} [εχων]{.greek-omitted} [ους]{.greek-omitted} ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[3:13 | instance no. 2]{.aside}

και τω αγγελω της εν [λαοδικεια]{.greek-omitted} [λαοδικια]{.greek-added} εκκλησιας γραψον ταδε λεγει ο αμην ο μαρτυς ο πιστος και αληθινος [η]{.greek-omitted} [αρχη]{.greek-omitted} [της]{.greek-omitted} [κτισεως]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted}[3:14]{.aside}

οιδα σου τα εργα οτι ουτε ψυχρος ει ουτε ζεστος [οφελον]{.greek-omitted} [οφελε]{.greek-added} [ει]{.greek-added} ψυχρος [ης]{.greek-omitted} η ζεστος[3:15]{.aside}

ουτως οτι χλιαρος ει και [ου]{.greek-omitted} [ουτε]{.greek-added} ζεστος ουτε ψυχρος μελλω σε [εμεσαι]{.greek-omitted} [αιμεσαι]{.greek-added} εκ του στοματος μου[3:16]{.aside}

οτι λεγεις πλουσιος ειμι και πεπλουτηκα και [ουδενος]{.greek-omitted} [ουδεν]{.greek-added} χρειαν εχω και ουκ οιδας οτι συ ει ο ταλαιπωρος και [ο]{.greek-omitted} ελεεινος και πτωχος και [γυμνος]{.greek-added} [και]{.greek-added} τυφλος [και]{.greek-omitted} [γυμνος]{.greek-omitted}[3:17]{.aside}

συμβουλευω σοι αγορασαι [χρυσιον]{.greek-omitted} παρ εμου [χρυσιον]{.greek-added} [πεπυρωμενον]{.greek-omitted} [πεπυρομενον]{.greek-added} εκ πυρος ινα πλουτησης και ιματια λευκα ινα περιβαλη και μη φανερωθη η αισχυνη της γυμνοτητος σου και [κολλυριον]{.greek-omitted} [κολλουριον]{.greek-added} [ενχρισον]{.greek-added} [ινα]{.greek-omitted} [εγχριση]{.greek-omitted} τους οφθαλμους σου ινα βλεπης[3:18]{.aside}

εγω οσους εαν φιλω ελεγχω και παιδευω ζηλωσον [ουν]{.greek-omitted} και μετανοησον[3:19]{.aside}

ιδου εστηκα επι την θυραν και κρουω εαν τις ακουση της φωνης μου και [ανοιξη]{.greek-omitted} [ανοιξει]{.greek-added} την θυραν και [εισελευσομαι]{.greek-omitted} [εισελευσωμαι]{.greek-added} προς αυτον και δειπνησω μετ αυτου και αυτος μετ εμου[3:20]{.aside}

ο νικων δωσω αυτω [καθισαι]{.greek-omitted} [καθησαι]{.greek-added} μετ εμου εν τω θρονω μου ως καγω ενικησα και [εκαθισα]{.greek-omitted} [εκαθησα]{.greek-added} μετα του [πατρος]{.greek-abbr} μου εν τω θρονω αυτου[3:21]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[3:22]{.aside}

### Chapter 4

μετα ταυτα [ειδον]{.greek-omitted} [ιδων]{.greek-added} και ιδου θυρα ανεωγμενη εν τω [ουρανω]{.greek-abbr} και η φωνη η πρωτη ην ηκουσα ως σαλπιγγος λαλουσης μετ εμου [λεγων]{.greek-omitted} [λεγουσα]{.greek-added} αναβα ωδε και δειξω σοι α δει γενεσθαι μετα ταυτα[4:1]{.aside}

και ευθεως εγενομην εν [πνευματι]{.greek-abbr} και ιδου θρονος εκειτο εν τω [ουρανω]{.greek-abbr} και επι [τον]{.greek-omitted} [του]{.greek-added} [θρονον]{.greek-omitted} [θρονου]{.greek-added} καθημενος[4:2]{.aside}

ομοιος ορασει λιθω ιασπιδι και [σαρδιω]{.greek-omitted} [σαρδινω]{.greek-added} και [ιρις]{.greek-omitted} [ἴρις]{.greek-added} [κυκλοθεν]{.greek-omitted} [κυκλο]{.greek-added} του θρονου [ομοιως]{.greek-omitted} [ομοιος]{.greek-added} [ορασις]{.greek-omitted} [ορασει]{.greek-added} [σμαραγδινων]{.greek-omitted} [σμαραγδινω]{.greek-added}[4:3]{.aside}

και [κυκλοθεν]{.greek-omitted} [κυκλωθεν]{.greek-added} του θρονου [θρονοι]{.greek-omitted} εικοσι [τεσσαρες]{.greek-omitted} [τεσσαρις]{.greek-added} και επι τους θρονους [καθημενους]{.greek-added} [τους]{.greek-omitted} [εικοσι]{.greek-omitted} [τεσσαρας]{.greek-omitted} πρεσβυτερους [καθημενους]{.greek-omitted} περιβεβλημενους εν ιματιοις λευκοις και επι τας κεφαλας αυτων στεφανους χρυσους[4:4]{.aside}

και εκ του θρονου εκπορευονται αστραπαι και φωναι και βρονται και επτα [λαμπαδες]{.greek-omitted} [λαμπαδαις]{.greek-added} πυρος καιομεναι ενωπιον του θρονου [α]{.greek-added} [αυτου]{.greek-omitted} [αι]{.greek-omitted} εισιν [τα]{.greek-added} επτα [πνευματα]{.greek-abbr} του [θεου]{.greek-abbr}[4:5]{.aside}

και ενωπιον του θρονου [ως]{.greek-omitted} θαλασσα υαλινη ομοια κρυσταλλω και εν μεσω του θρονου και κυκλω του θρονου τεσσαρα [ζωα]{.greek-omitted} [γεμοντα]{.greek-omitted} [οφθαλμων]{.greek-omitted} [εμπροσθεν]{.greek-omitted} [και]{.corr} [οπισθεν]{.greek-omitted} [[εν]{.corr}]{.greek-added} [[μεσω]{.corr}]{.greek-added} [[του]{.corr}]{.greek-added} [[θρονου]{.corr}]{.greek-added} [[και]{.corr}]{.greek-added} [[κυκλω]{.corr}]{.greek-added} [[του]{.corr}]{.greek-added} [[θρονου]{.corr}]{.greek-added} [[τεσσαρα]{.corr}]{.greek-added}[4:6]{.aside}

[ζωα]{.greek-added} [και]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [ως]{.greek-omitted} [θαλασσα]{.greek-omitted} [υαλινη]{.greek-omitted} [ομοια]{.greek-omitted} [κρυσταλλω]{.greek-omitted} [και]{.greek-omitted} [εν]{.greek-omitted} [μεσω]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} και κυκλω του θρονου τεσσαρα ζωα [γεμοντα]{.greek-omitted} [γεμωντα]{.greek-added} οφθαλμων [οπισθεν]{.greek-added} [και]{.greek-added} εμπροσθεν [και]{.greek-omitted} [οπισθεν]{.greek-omitted}[4:6 | instance no. 2]{.aside}

και το ζωον το [πρωτον]{.greek-omitted} [προτων]{.greek-added} ομοιον λεοντι και το δευτερον ζωον ομοιον μοσχω και το τριτον ζωον [εχον]{.greek-omitted} [εχων]{.greek-added} [το]{.greek-added} προσωπον [ως]{.greek-added} [ανθρωπου]{.greek-abbr} [[[ανθρωπος]{.greek-abbr}]{.corr}]{.greek-added} και το τεταρτον ζωον ομοιον αετω πετομενω[4:7]{.aside}

και [τα]{.greek-omitted} τεσσαρα ζωα εν καθ εν [αυτων]{.greek-added} [εχον]{.greek-omitted} [εχων]{.greek-added} ανα πτερυγας εξ [κυκλοθεν]{.greek-omitted} [κυκλωθεν]{.greek-added} [εξωθεν]{.greek-added} και εσωθεν [γεμουσιν]{.greek-omitted} [γεμωσιν]{.greek-added} οφθαλμων και αναπαυσιν ουκ εχουσιν ημερας και νυκτος λεγοντες [αγιος]{.greek-omitted} [το]{.greek-added} αγιος αγιος [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ ο ην και ο ων και ο ερχομενος[4:8]{.aside}

και οταν [δωσιν]{.greek-omitted} [δωσωσι]{.greek-added} τα ζωα δοξαν και τιμην και ευχαριστιαν τω καθημενω επι του θρονου τω ζωντι εις τους αιωνας των αιωνων[4:9]{.aside}

πεσουνται οι εικοσι [τεσσαρες]{.greek-omitted} [τεσσαρις]{.greek-added} πρεσβυτεροι ενωπιον του καθημενου επι [του]{.greek-omitted} θρονου και προσκυνησουσιν τω ζωντι εις τους αιωνας των αιωνων και [βαλουσιν]{.greek-omitted} [βάλλουσιν]{.greek-added} [τους]{.greek-added} τους στεφανους αυτων ενωπιον του θρονου λεγοντες[4:10]{.aside}

αξιος ει [[κυριε]{.greek-abbr}]{.greek-added} [ο]{.greek-omitted} [κυριος]{.greek-omitted} [και]{.greek-omitted} ο [θεος]{.greek-abbr} ημων [ο]{.greek-omitted} [αγιος]{.greek-omitted} λαβειν την δοξαν και την τιμην και την [δυναμιν]{.greek-omitted} [δυναμειν]{.greek-added} οτι συ εκτισας [τα]{.greek-added} παντα και δια το θελημα σου [ησαν]{.greek-omitted} [εισιν]{.greek-added} και εκτισθησαν[4:11]{.aside}

### Chapter 5

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} επι την δεξιαν του καθημενου επι του θρονου βιβλιον γεγραμμενον εσωθεν και [εξωθεν]{.greek-omitted} [οπισθεν]{.greek-added} κατεσφραγισμενον [σφραγισιν]{.greek-omitted} [σφραγισι]{.greek-added} επτα[5:1]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} αγγελον ισχυρον κηρυσσοντα [εν]{.greek-omitted} φωνη μεγαλη τις αξιος [εστιν]{.greek-omitted} ανοιξαι το βιβλιον και λυσαι τας σφραγιδας αυτου[5:2]{.aside}

και ουδεις [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} εν τω [ουρανω]{.greek-abbr} [ανω]{.greek-omitted} [ουτε]{.greek-omitted} [ουδε]{.greek-added} επι [της]{.greek-omitted} [γης]{.greek-omitted} [ουτε]{.greek-omitted} [υποκατω]{.greek-omitted} της γης ανοιξαι το βιβλιον [ουτε]{.greek-omitted} [ουδε]{.greek-added} βλεπειν αυτο[5:3]{.aside}

και [εγω]{.greek-omitted} [εκλαιον]{.greek-omitted} [εκλεον]{.greek-added} πολυ οτι ουδεις [ηυρεθει]{.greek-added} [αξιος]{.greek-omitted} [ευρεθη]{.greek-omitted} ανοιξαι [και]{.greek-added} [αναγνωναι]{.greek-added} το βιβλιον ουτε βλεπειν αυτο[5:4]{.aside}

και εις εκ των πρεσβυτερων λεγει μοι μη [κλαιε]{.greek-omitted} [κλεε]{.greek-added} ιδου ενικησεν ο λεων ο εκ της φυλης ιουδα η ριζα [δαυιδ]{.greek-abbr} [ανοιξαι]{.greek-added} [ο]{.greek-omitted} [ανοιγων]{.greek-omitted} το βιβλιον και [τας]{.greek-omitted} [τα]{.greek-added} επτα σφραγιδας αυτου[5:5]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} εν μεσω του θρονου και των τεσσαρων ζωων και εν μεσω των πρεσβυτερων αρνιον εστηκος ως [εσφαγμενον]{.greek-omitted} [εσφαγμενων]{.greek-added} [εχον]{.greek-omitted} [εχων]{.greek-added} κερατα επτα και οφθαλμους επτα [α]{.greek-omitted} [οι]{.greek-added} εισιν τα [επτα]{.greek-omitted} [πνευματα]{.greek-abbr} [του]{.greek-omitted} [θεου]{.greek-omitted} [αποστελλομενα]{.greek-omitted} [εις]{.greek-omitted} [πασαν]{.greek-omitted} [την]{.greek-omitted} [γην]{.greek-omitted}[5:6]{.aside}

[και]{.greek-omitted} [ειδον]{.greek-omitted} [εν]{.greek-omitted} [μεσω]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [και]{.greek-omitted} [των]{.greek-omitted} [τεσσαρων]{.greek-omitted} [ζωων]{.greek-omitted} [και]{.greek-omitted} [εν]{.greek-omitted} [μεσω]{.greek-omitted} [των]{.greek-omitted} [πρεσβυτερων]{.greek-omitted} [αρνιον]{.greek-omitted} [εστηκος]{.greek-omitted} [ως]{.greek-omitted} [εσφαγμενον]{.greek-omitted} [εχον]{.greek-omitted} [κερατα]{.greek-omitted} [επτα]{.greek-omitted} [και]{.greek-omitted} [οφθαλμους]{.greek-omitted} [επτα]{.greek-omitted} [α]{.greek-omitted} [εισιν]{.greek-omitted} [τα]{.greek-omitted} [επτα]{.greek-omitted} [πνευματα]{.greek-omitted} του [θεου]{.greek-abbr} [τα]{.greek-added} [αποστελλομενα]{.greek-omitted} [αποσταλμενα]{.greek-added} εις πασαν την γην[5:6 | instance no. 2]{.aside}

και ηλθεν και ειληφεν εκ της δεξιας του καθημενου επι του θρονου[5:7]{.aside}

και οτε ελαβεν το βιβλιον τα τεσσαρα ζωα και οι εικοσι [τεσσαρες]{.greek-omitted} [[τεσσαρις]{.corr}]{.greek-added} πρεσβυτεροι [επεσον]{.greek-omitted} [επεσαν]{.greek-added} ενωπιον του αρνιου [εχοντες]{.greek-omitted} [εχοντας]{.greek-added} εκαστος [κιθαραν]{.greek-omitted} [κιθαρας]{.greek-added} και φιαλας χρυσας γεμουσας θυμιαματων αι εισιν [αι]{.greek-added} προσευχαι των αγιων[5:8]{.aside}

και αδουσιν ωδην καινην λεγοντες αξιος ει λαβειν το βιβλιον και ανοιξαι τας σφραγιδας αυτου οτι εσφαγης και ηγορασας τω [θεω]{.greek-abbr} ημας εν τω αιματι σου εκ πασης φυλης και γλωσσης και λαου και εθνους[5:9]{.aside}

και εποιησας αυτους τω [θεω]{.greek-abbr} ημων βασιλεις και ιερεις και βασιλευσουσιν επι της γης[5:10]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} και ηκουσα [ως]{.greek-omitted} φωνην αγγελων πολλων κυκλω του θρονου και των ζωων και των πρεσβυτερων και ην ο αριθμος αυτων μυριαδες μυριαδων και χιλιαδες χιλιαδων[5:11]{.aside}

λεγοντες φωνη μεγαλη αξιον εστιν το αρνιον το [εσφαγμενον]{.greek-omitted} [εσφαγμενων]{.greek-added} λαβειν την [δυναμιν]{.greek-omitted} [δυναμειν]{.greek-added} και [τον]{.greek-omitted} πλουτον και σοφιαν και ισχυν και τιμην και δοξαν και ευλογιαν[5:12]{.aside}

και παν κτισμα ο [εστιν]{.greek-added} εν τω [ουρανω]{.greek-abbr} και επι της γης και [υποκατω]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [και]{.greek-omitted} [επι]{.greek-omitted} της θαλασσης [α]{.greek-added} εστιν και τα εν αυτοις [παντας]{.greek-omitted} [παντα]{.greek-added} ηκουσα λεγοντας [[λεγοντα]{.corr}]{.greek-added} τω καθημενω επι του θρονου και [τω]{.greek-omitted} [αρνιω]{.greek-omitted} [του]{.greek-added} [αρνιου]{.greek-added} η ευλογια και η τιμη [και]{.greek-omitted} [η]{.greek-omitted} [δοξα]{.greek-omitted} και το κρατος εις τους αιωνας των αιωνων αμην[5:13]{.aside}

και τα τεσσαρα ζωα [λεγοντα]{.greek-omitted} [ελεγον]{.greek-added} [το]{.greek-omitted} αμην και οι πρεσβυτεροι [επεσον]{.greek-omitted} [επεσαν]{.greek-added} και προσεκυνησαν[5:14]{.aside}

### Chapter 6

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} [οτι]{.greek-omitted} [οτε]{.greek-added} [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} το αρνιον μιαν εκ των [επτα]{.greek-omitted} σφραγιδων και ηκουσα ενος εκ των τεσσαρων [ζωων]{.greek-omitted} λεγοντος ως [φωνη]{.greek-omitted} [φωνῆς]{.greek-added} βροντης ερχου [και]{.greek-omitted} [ιδε]{.greek-omitted}[6:1]{.aside}

[και]{.greek-added} [ιδον]{.greek-added} και ιδου ιππος λευκος και ο καθημενος επ αυτον [εχων]{.greek-omitted} [εχον]{.greek-added} τοξον και [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} αυτω στεφανος και εξηλθεν νικων και ινα νικηση[6:2]{.aside}

και οτε ηνοιξεν την [σφραγιδα]{.greek-added} [την]{.greek-added} δευτεραν [σφραγιδα]{.greek-omitted} ηκουσα [του]{.greek-omitted} δευτερου ζωου λεγοντος ερχου[6:3]{.aside}

και εξηλθεν αλλος ιππος [πυρος]{.greek-omitted} [πυρρος]{.greek-added} και τω καθημενω επ [αυτον]{.greek-omitted} [αυτων]{.greek-added} [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} αυτω λαβειν την ειρηνην εκ της γης [και]{.greek-added} ινα αλληλους [σφαξωσιν]{.greek-omitted} [σφαξουσιν]{.greek-added} και [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} αυτω μαχαιρα μεγαλη[6:4]{.aside}

και οτε ηνοιξεν [την]{.greek-omitted} [σφραγιδα]{.greek-omitted} την τριτην ηκουσα του τριτου ζωου [λεγοντος]{.greek-omitted} [ερχου]{.greek-omitted} [και]{.greek-omitted} [ιδε]{.greek-omitted} [και]{.greek-omitted} [ιδου]{.greek-omitted} [ιππος]{.greek-omitted} [μελας]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [καθημενος]{.greek-omitted} [επ]{.greek-omitted} [αυτον]{.greek-omitted} [εχων]{.greek-omitted} [ζυγον]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [χειρι]{.greek-omitted} [αυτου]{.greek-omitted}[6:5]{.aside}

[και]{.greek-omitted} [οτε]{.greek-omitted} [ηνοιξεν]{.greek-omitted} [την]{.greek-omitted} [σφραγιδα]{.greek-omitted} [την]{.greek-omitted} [τριτην]{.greek-omitted} [ηκουσα]{.greek-omitted} [του]{.greek-omitted} [τριτου]{.greek-omitted} [ζωου]{.greek-omitted} λεγοντος ερχου και [ιδε]{.greek-omitted} [ιδον]{.greek-added} και ιδου ιππος μελας και ο καθημενος [ε]{.greek-added} επ αυτον εχων ζυγον εν τη χειρι αυτου[6:5 | instance no. 2]{.aside}

και ηκουσα [ως]{.greek-added} φωνην εν μεσω των τεσσαρων ζωων λεγουσαν χοινιξ σιτου [δηναριου]{.greek-omitted} [διναριου]{.greek-added} και τρεις χοινικες [κριθων]{.greek-added} [κριθης]{.greek-omitted} [δηναριου]{.greek-omitted} και το [ελαιον]{.greek-omitted} [ελεον]{.greek-added} και τον οινον μη αδικησης[6:6]{.aside}

και οτε ηνοιξεν την σφραγιδα την τεταρτην ηκουσα [φωνην]{.greek-added} του τεταρτου ζωου λεγοντος ερχου [και]{.greek-omitted} [ιδε]{.greek-omitted}[6:7]{.aside}

και [ιδου]{.greek-omitted} [ιδον]{.greek-added} [και]{.greek-added} ιππος [χλωρος]{.greek-omitted} [χλορος]{.greek-added} και ο καθημενος επανω [ονομα]{.greek-added} αυτου [ονομα]{.greek-omitted} [αυτω]{.greek-omitted} ο θανατος και ο αδης [ηκολουθει]{.greek-omitted} [ακολουθει]{.greek-added} [αυτω]{.greek-omitted} [μετ]{.greek-added} [αυτου]{.greek-added} και [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} [αυτω]{.greek-omitted} [αυτοις]{.greek-added} εξουσια επι το τεταρτον της γης αποκτειναι εν ρομφαια και εν λιμω και εν θανατω και υπο των θηριων της γης[6:8]{.aside}

και οτε ηνοιξεν την πεμπτην σφραγιδα [ειδον]{.greek-omitted} [ιδον]{.greek-added} υποκατω του θυσιαστηριου τας ψυχας [των]{.greek-added} [[ανθρωπων]{.greek-abbr}]{.greek-added} των εσφαγμενων δια τον λογον του [θεου]{.greek-abbr} και δια την μαρτυριαν [του]{.greek-omitted} [αρνιου]{.greek-omitted} ην ειχον[6:9]{.aside}

και [εκραξαν]{.greek-omitted} [εκραζον]{.greek-added} φωνη μεγαλη λεγοντες εως ποτε ο δεσποτης ο αγιος και αληθινος ου κρινεις και εκδικεις το αιμα ημων [εκ]{.greek-omitted} [απο]{.greek-added} των κατοικουντων επι της γης[6:10]{.aside}

και [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} αυτοις εκαστω στολη λευκη και ερρεθη αυτοις ινα [αναπαυσωνται]{.greek-omitted} [αναπαυσονται]{.greek-added} ετι χρονον [μικρον]{.greek-added} εως [ου]{.greek-added} [πληρωσωσιν]{.greek-omitted} [πληρωσωσι]{.greek-added} [και]{.greek-omitted} οι συνδουλοι αυτων και οι αδελφοι αυτων [και]{.greek-omitted} οι μελλοντες [αποκτενεσθαι]{.greek-omitted} [αποκτεννεσθαι]{.greek-added} ως και αυτοι[6:11]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} οτε ηνοιξεν την σφραγιδα την εκτην και [σεισμος]{.greek-omitted} [σισμος]{.greek-added} μεγας εγενετο και ο ηλιος [εγενετο]{.greek-added} μελας [εγενετο]{.greek-omitted} ως σακκος τριχινος και η σεληνη [ολη]{.greek-omitted} εγενετο ως αιμα[6:12]{.aside}

και οι αστερες του ουρανου [επεσον]{.greek-omitted} [επεσαν]{.greek-added} εις την γην ως συκη [βαλουσα]{.greek-omitted} [βαλλει]{.greek-added} τους ολυνθους αυτης υπο ανεμου [μεγαλου]{.greek-omitted} [σειομενη]{.greek-omitted} [σαλευομενη]{.greek-added}[6:13]{.aside}

και ο [ουρανος]{.greek-abbr} απεχωρισθη ως βιβλιον [ελισσομενον]{.greek-omitted} [ειλισσομενον]{.greek-added} και παν ορος και νησος εκ των τοπων αυτων [εκινηθησαν]{.greek-omitted} [εκηνηθησαν]{.greek-added}[6:14]{.aside}

και οι βασιλεις της γης και οι μεγιστανες και οι χιλιαρχοι και [οι]{.greek-omitted} [πλουσιοι]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [ισχυροι]{.greek-omitted} [και]{.greek-omitted} πας δουλος και [πας]{.greek-added} ελευθερος εκρυψαν εαυτους εις τα [εις]{.greek-added} [τα]{.greek-added} σπηλαια και εις [τας]{.greek-omitted} πετρας των ορεων[6:15]{.aside}

και [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} τοις [ορεσιν]{.greek-omitted} [ορεσι]{.greek-added} και ταις πετραις πεσετε εφ ημας και κρυψατε ημας απο προσωπου του [καθημενου]{.greek-omitted} [καθημενο]{.greek-added} επι [του]{.greek-omitted} θρονου και απο της οργης του αρνιου[6:16]{.aside}

οτι ηλθεν η ημερα η μεγ[α]{.unclear}λη της οργης αυτου και τις δυναται σταθηναι[6:17]{.aside}

### Chapter 7

και μετ[α]{.unclear} [τουτο]{.greek-omitted} [[τ]{.unclear}αυτα]{.greek-added} [ειδον]{.greek-omitted} [ιδον]{.greek-added} [τεσσαρας]{.greek-omitted} [αγγελους]{.greek-omitted} [εστωτας]{.greek-omitted} [επι]{.greek-omitted} [τας]{.greek-omitted} [τεσσαρας]{.greek-omitted} [γωνιας]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [κρατουντας]{.greek-omitted} [τους]{.greek-omitted} [τεσσαρας]{.greek-omitted} [ανεμους]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [ινα]{.greek-omitted} [μη]{.greek-omitted} [πνεη]{.greek-omitted} [ανεμος]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [μητε]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [θαλασσης]{.greek-omitted} [μητε]{.greek-omitted} [επι]{.greek-omitted} [τι]{.greek-omitted} [δενδρον]{.greek-omitted}[7:1]{.aside}

[και]{.greek-omitted} [μετα]{.greek-omitted} [τουτο]{.greek-omitted} [ειδον]{.greek-omitted} τεσσαρας αγγελους εστωτας επι τας [τεσσαρας]{.greek-omitted} [τεσσαρεις]{.greek-added} γωνιας της γης κρατουντας τους [τεσσαρας]{.greek-omitted} [τεσσαρεις]{.greek-added} ανεμους της γης ινα μη πνεη [και]{.greek-added} ανεμος επι της γης μητε επι της θαλασσης μητε επι [τι]{.greek-omitted} [παν]{.greek-added} δενδρον[7:1 | instance no. 2]{.aside}

και [ειδον]{.greek-omitted} [αλλον]{.greek-omitted} [ιδου]{.greek-added} [αγιον]{.greek-added} αγγελον αναβαινοντα απο ανατολης ηλιου εχοντα [σφραγιδα]{.greek-omitted} [σφραγιδας]{.greek-added} [θεου]{.greek-abbr} ζωντος και [εκραξεν]{.greek-omitted} [εκραξαι]{.greek-added} φωνη μεγαλη τοις τεσσαρσιν αγγελοις οις [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} αυτοις αδικησαι την γην και την θαλασσαν[7:2]{.aside}

λεγων μη [αδικησητε]{.greek-omitted} [αδικησηται]{.greek-added} την γην μητε την θαλασσαν μητε τα δενδρα αχρι [ου]{.greek-omitted} σφραγισωμεν τους δουλους του [θεου]{.greek-abbr} ημων επι των μετωπων αυτων[7:3]{.aside}

και ηκουσα τον αριθμον των εσφραγισμενων εκατον [και]{.greek-omitted} [τεσσαρακοντα]{.greek-omitted} [σερακοντα]{.greek-added} [τεσσαρες]{.greek-omitted} χιλιαδες [εσφραγισμενων]{.greek-omitted} [εσφραγισμενοι]{.greek-added} εκ πασης φυλης υιων [ισραηλ]{.greek-abbr}[7:4]{.aside}

εκ φυλης ιουδα δωδεκα χιλιαδες [εσφραγισμεναι]{.greek-omitted} [εσφραγισμενοι]{.greek-added} [εκ]{.greek-omitted} [φυλης]{.greek-omitted} [ρουβιμ]{.greek-omitted} [δωδεκα]{.greek-omitted} [χιλιαδες]{.greek-omitted} εκ φυλης γαδ δωδεκα χιλιαδες[7:5]{.aside}

εκ φυλης [ασηρ]{.greek-omitted} [ασιρ]{.greek-added} δωδεκα χιλιαδες εκ φυλης νεφθαλειμ δωδεκα χιλιαδες εκ φυλης μανασση δωδεκα χιλιαδες[7:6]{.aside}

εκ φυλης συμεων δωδεκα χιλιαδες εκ φυλης λευι [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εκ φυλης ισαχαρ [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες[7:7]{.aside}

εκ φυλης ζαβουλων [δωδεκα]{.greek-omitted} [χιλιαδες]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} [[χι]{.greek-abbr}]{.greek-added} εκ φυλης ιωσηφ δωδεκα χιλιαδες εκ φυλης [βενιαμιν]{.greek-omitted} [βενιαμην]{.greek-added} δωδεκα χιλιαδες [εσφραγισμεναι]{.greek-omitted} [εσφραγισμενοι]{.greek-added}[7:8]{.aside}

μετα ταυτα [ειδον]{.greek-omitted} [ιδον]{.greek-added} και ιδου οχλος [πολυς]{.greek-omitted} ον αριθμησαι [ουδεις]{.greek-omitted} [αυτον]{.greek-added} [ου]{.greek-added} [εδυνατο]{.greek-omitted} [δυνατο]{.greek-added} εκ παντος εθνους και φυλων και λαων και γλωσσων [εστωτας]{.greek-omitted} [εστωτες]{.greek-added} ενωπιον του θρονου και ενωπιον του αρνιου [περιβεβλημενους]{.greek-omitted} [περιβεβλημενοι]{.greek-added} στολας λευκας και [φοινικας]{.greek-omitted} [φοινικες]{.greek-added} εν ταις χερσιν αυτων[7:9]{.aside}

και [κραζουσιν]{.greek-omitted} [κραζουσι]{.greek-added} φωνη μεγαλη λεγοντες η [σωτηρια]{.greek-abbr} τω [θεω]{.greek-abbr} ημων τω καθημενω επι τω θρονω και τω αρνιω[7:10]{.aside}

και παντες οι αγγελοι [ειστηκεισαν]{.greek-omitted} [ιστηκησαν]{.greek-added} κυκλω του θρονου και των πρεσβυτερων και των τεσσαρων ζωων και [επεσον]{.greek-omitted} [επεσαν]{.greek-added} ενωπιον του θρονου [επι]{.greek-omitted} [τα]{.greek-omitted} [προσωπα]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [προσεκυνησαν]{.greek-omitted} [τω]{.greek-omitted} [θεω]{.greek-omitted}[7:11]{.aside}

και απεκριθη εις εκ των πρεσβυτερων λεγων μοι ουτοι οι περιβεβλημενοι τας στολας τας λευκας [και]{.greek-added} τινες [εισιν]{.greek-omitted} και ποθεν ηλθον[7:13]{.aside}

και [ειπον]{.greek-omitted} [ειρηκα]{.greek-added} αυτω [κυριε]{.greek-abbr} [σοι]{.greek-added} [μου]{.greek-omitted} [συ]{.greek-omitted} οιδας και ειπεν μοι ουτοι εισιν οι ερχομενοι εκ της θλιψεως της μεγαλης και επλυναν [τας]{.greek-omitted} [στολας]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [ελευκαναν]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [αιματι]{.greek-omitted} [του]{.greek-omitted} [αρνιου]{.greek-omitted}[7:14]{.aside}

[και]{.greek-omitted} [ειπον]{.greek-omitted} [αυτω]{.greek-omitted} [κυριε]{.greek-omitted} [μου]{.greek-omitted} [συ]{.greek-omitted} [οιδας]{.greek-omitted} [και]{.greek-omitted} [ειπεν]{.greek-omitted} [μοι]{.greek-omitted} [ουτοι]{.greek-omitted} [εισιν]{.greek-omitted} [οι]{.greek-omitted} [ερχομενοι]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [θλιψεως]{.greek-omitted} [της]{.greek-omitted} [μεγαλης]{.greek-omitted} [και]{.greek-omitted} [επλυναν]{.greek-omitted} τας στολας αυτων και ελευκαναν [αυτας]{.greek-added} εν τω αιματι του αρνιου[7:14 | instance no. 2]{.aside}

δι[α]{.unclear} τουτο εισιν ενωπιον του θρονου του [θεου]{.greek-abbr} και λατρευουσιν αυτω ημερας [και]{.unclear} νυκτος εν τω ναω αυτου και ο καθημενος επι [τω]{.greek-omitted} [θρονω]{.greek-omitted} [του]{.greek-added} [θρονου]{.greek-added} σκηνωσει επ αυτους[7:15]{.aside}

ου πεινασουσιν ετι ουδε [διψεισωσιν]{.greek-added} [διψησουσιν]{.greek-omitted} [ετι]{.greek-omitted} [ουδ]{.greek-omitted} [ουδε]{.greek-added} [ου]{.greek-omitted} μη [πεση]{.greek-omitted} [πεσει]{.greek-added} επ αυτους ο ηλιος ουδε παν καυμα[7:16]{.aside}

οτι το αρνιον το ανα μεσον του θρονου [ποιμαινει]{.greek-omitted} [ποιμανει]{.greek-added} αυτους και [οδηγει]{.greek-omitted} [οδιγησει]{.greek-added} αυτους επι [ζωης]{.greek-omitted} [ζωσας]{.greek-added} πηγας υδατων και [εξαλειψει]{.greek-omitted} [εξελει]{.greek-added} ο [θεος]{.greek-abbr} παν δακρυον εκ των οφθαλμων αυτων[7:17]{.aside}

### Chapter 8

και οτε ηνοιξεν την σφραγιδα την εβδομην εγενετο σιγη εν τω [ουρανω]{.greek-abbr} ως [ημιωριον]{.greek-omitted} [ἡμιόριον]{.greek-added}[8:1]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} τους επτα αγγελους οι ενωπιον του [θεου]{.greek-abbr} εστηκασιν και [εδοθησαν]{.greek-omitted} [εδωθησαν]{.greek-added} αυτοις επτα σαλπιγγες[8:2]{.aside}

και αλλος αγγελος ηλθεν και εσταθη επι [του]{.greek-omitted} [το]{.greek-added} [θυσιαστηριου]{.greek-omitted} [θυσιαστηριον]{.greek-added} εχων λιβανωτον χρυσουν [και]{.greek-omitted} [εδοθη]{.greek-omitted} [αυτω]{.greek-omitted} [θυμιαματα]{.greek-omitted} [πολλα]{.greek-omitted} [ινα]{.greek-omitted} [δωση]{.greek-omitted} [ταις]{.greek-omitted} [προσευχαις]{.greek-omitted} [των]{.greek-omitted} [αγιων]{.greek-omitted} [παντων]{.greek-omitted} [επι]{.greek-omitted} [το]{.greek-omitted} [θυσιαστηριον]{.greek-omitted} [το]{.greek-omitted} [χρυσουν]{.greek-omitted} [το]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted}[8:3]{.aside}

και ανεβη ο καπνος των θυμιαματων ταις προσευχαις των αγιων εκ χειρος του αγγελου ενωπιον του [θεου]{.greek-abbr}[8:4]{.aside}

και ειληφεν ο αγγελος τον [λιβανωντον]{.greek-added} [λιβανωτον]{.corr} [και]{.unclear} [εγεμισεν]{.greek-omitted} [εγεμησεν]{.greek-added} αυτον εκ [του]{.greek-omitted} [πυρος]{.greek-omitted} του θυσιαστηριου και εβαλεν εις την γην και εγενοντο [φωναι]{.greek-added} [και]{.greek-added} βρονται [και]{.greek-omitted} [φωναι]{.greek-omitted} και αστραπαι και σεισμος[8:5]{.aside}

και οι επτα αγγελοι οι εχοντες τας επτα σαλπιγγας [ητοιμασαν]{.greek-omitted} [ετοιμασαν]{.greek-added} εαυτους ινα σαλπισωσιν[8:6]{.aside}

και ο πρωτος [αγγελος]{.greek-added} εσαλπισεν και εγενετο χαλαζα και [[ο]{.unclear}]{.greek-added} πυρ [μεμιγμενα]{.greek-omitted} [μεμιγμενον]{.greek-added} [εν]{.greek-omitted} αιματι και [εβληθη]{.greek-omitted} [εβληη]{.greek-added} [εις]{.greek-omitted} [την]{.greek-omitted} [γην]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [τριτον]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [κατεκαη]{.greek-omitted} και το τριτον των δενδρων [κατεκαη]{.greek-omitted} [κατεκη]{.greek-added} και πας χορτος [χλωρος]{.greek-omitted} [χλορος]{.greek-added} κατεκαη[8:7]{.aside}

και ο δευτερος αγγελος εσαλπισεν και ως ορος μεγα [πυρι]{.greek-added} καιομενον εβληθη εις την θαλασσαν και εγενετο το τριτον της θαλασσης αιμα[8:8]{.aside}

και απεθανεν το τριτον [των]{.greek-omitted} κτισματων [εν]{.greek-omitted} [τη]{.greek-omitted} [θαλασση]{.greek-omitted} τα εχοντα ψυχας και το τριτον των πλοιων [διεφθαρη]{.greek-omitted} [διεφθαρισαν]{.greek-added}[8:9]{.aside}

και ο τριτος αγγελος εσαλπισεν και επεσεν εκ του ουρανου αστηρ μεγας καιομενος ως λαμπας και [επεσεν]{.greek-omitted} [επεστεν]{.greek-added} επι το τριτον των ποταμων και επι τας πηγας των υδατων[8:10]{.aside}

και το ονομα του αστερος λεγεται [ο]{.greek-omitted} αψινθος και [εγενετο]{.greek-omitted} [γινε[ται]{.unclear}]{.greek-added} το τριτον των υδατων [εις]{.greek-omitted} αψινθον και πολλοι των [ανθρωπων]{.greek-abbr} [απεθανον]{.greek-omitted} [απεθανων]{.greek-added} εκ των υδατων οτι επικρανθησαν[8:11]{.aside}

και ο τεταρτος αγγελος εσαλπισεν και [επλ]{.unclear}ηγη το τριτον του ηλιου και το τριτον της σεληνης και το τριτον των αστερων ινα [σκοτισθη]{.greek-omitted} [σκοτισ]{.greek-added} [το]{.greek-omitted} [τριτον]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [τριτον]{.greek-omitted} [αυτης]{.greek-omitted} [μη]{.greek-omitted} [φανη]{.greek-omitted} [η]{.greek-omitted} [ημερα]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [νυξ]{.greek-omitted} [ομοιως]{.greek-omitted}[8:12]{.aside}

[θη]{.greek-added} [και]{.greek-omitted} [ο]{.greek-omitted} [τεταρτος]{.greek-omitted} [αγγελος]{.greek-omitted} [εσαλπισεν]{.greek-omitted} [και]{.greek-omitted} [επληγη]{.greek-omitted} [το]{.greek-omitted} [τριτον]{.greek-omitted} [του]{.greek-omitted} [ηλιου]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [τριτον]{.greek-omitted} [της]{.greek-omitted} [σεληνης]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [τριτον]{.greek-omitted} [των]{.greek-omitted} [αστερων]{.greek-omitted} [ινα]{.greek-omitted} [σκοτισθη]{.greek-omitted} το τριτον αυτων και [η]{.greek-added} [ημερα]{.greek-added} [μη]{.greek-added} [φαινει]{.greek-added} το τριτον αυτης [μη]{.greek-omitted} [φανη]{.greek-omitted} [η]{.greek-omitted} [ημερα]{.greek-omitted} και η νυξ [ομοιως]{.greek-omitted}[8:12 | instance no. 2]{.aside}

και [ειδον]{.greek-omitted} [ιδου]{.greek-added} και ηκουσα ενος [αετου]{.greek-omitted} [αγγελου]{.greek-added} πετομενου εν μεσουρανηματι λεγοντος φωνη μεγαλη ουαι ουαι ουαι τοις κατοικουσιν επι της γης εκ των λοιπων φωνων της σαλπιγγος των τριων αγγελων των μελλοντων σαλπιζειν[8:13]{.aside}

### Chapter 9

και ο πεμπτος αγγελος εσαλπισεν και [ειδον]{.greek-omitted} [ιδον]{.greek-added} αστερα εκ του [ουρανου]{.greek-abbr} πεπτωκοτα εις την γην και εδοθη αυτω η κλεις του φρεατος της αβυσσου[9:1]{.aside}

και [ανεστη]{.greek-added} [ηνοιξεν]{.greek-omitted} [το]{.greek-omitted} [φρεαρ]{.greek-omitted} [της]{.greek-omitted} [αβυσσου]{.greek-omitted} [και]{.greek-omitted} [ανεβη]{.greek-omitted} καπνος εκ του φρεατος ως καπνος [καμινου]{.greek-omitted} [καμηνου]{.greek-added} [καιομενης]{.greek-omitted} [μεγαλης]{.greek-added} και [εσκοτισθη]{.greek-omitted} [εσκοτ[ω]{.unclear}θη]{.greek-added} ο ηλιος και ο [αηρ]{.greek-omitted} [αστηρ]{.greek-added} εκ του καπνου του φρεατος[9:2]{.aside}

και εκ του καπνου [εξηλθον]{.greek-omitted} [εξηλθεν]{.greek-added} ακριδες εις την γην και εδοθη αυταις [εξουσια]{.corr} [ως]{.corr} [εχουσιν]{.corr} εξουσιαν οι σκορπιοι της γης[9:3]{.aside}

και ερρεθη [αυταις]{.greek-omitted} [αυαυταις]{.greek-added} ινα μη αδικησωσιν τον χορτον της γης ουδε παν [χλωρον]{.greek-omitted} [χλορον]{.greek-added} ουδε παν δενδρον ει [μη]{.greek-omitted} [μι]{.greek-added} τους [ανθρωπους]{.greek-abbr} οιτινες ουκ εχουσιν [την]{.greek-omitted} [της]{.greek-added} σφραγιδα [του]{.greek-omitted} [θεου]{.greek-omitted} επι των [μετωπων]{.greek-omitted} [μετοπων]{.greek-added} [αυτων]{.greek-omitted}[9:4]{.aside}

και εδοθη [αυταις]{.greek-omitted} [αυτοις]{.greek-added} ινα μη [αποκτεινωσιν]{.greek-omitted} [αποκτηνουσιν]{.greek-added} αυτους αλλ ινα [βασανισθωσιν]{.greek-omitted} [βασανισθησονται]{.greek-added} μηνας πεντε και ο βασανισμος αυτων ως βασανισμος σκορπιου οταν [παιση]{.greek-omitted} [πεση]{.greek-added} [ανθρωπον]{.greek-abbr}[9:5]{.aside}

και εν ταις ημεραις εκειναις ζητησουσιν οι [ανθρωποι]{.greek-abbr} τον θανατον και ου μη [ευρησουσιν]{.greek-omitted} [ευρωσιν]{.greek-added} αυτον και επιθυμησουσιν αποθανειν και [φευξεται]{.greek-omitted} [φευγει]{.greek-added} [ο]{.greek-added} [θανατος]{.greek-added} απ αυτων [ο]{.greek-omitted} [θανατος]{.greek-omitted}[9:6]{.aside}

και τα ομοιωματα των ακριδων ομοια ιπποις ητοιμασμενοις εις πολεμον και επι τας κεφαλας αυτων ως στεφανοι [ομοιοι]{.greek-added} [χρυσω]{.greek-added} [χρυσοι]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} [προσωπα]{.greek-omitted} [αυτων]{.greek-omitted} [ως]{.greek-omitted} [προσωπα]{.greek-omitted} [ανθρωπων]{.greek-omitted}[9:7]{.aside}

[και]{.greek-omitted} [ειχον]{.greek-omitted} [θωρακας]{.greek-omitted} [ως]{.greek-omitted} [θωρακας]{.greek-omitted} [σιδηρους]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} φωνη των πτερυγων αυτων ως φωνη αρματων [ιππων]{.greek-omitted} [ιππον]{.greek-added} πολλων τρεχοντων εις πολεμον[9:9]{.aside}

και εχουσιν ουρας ομοιας [σκορπιοις]{.greek-omitted} [σκορπιους]{.greek-added} και κεντρα [και]{.greek-omitted} εν ταις ουραις αυτων [και]{.greek-added} [η]{.greek-added} [εξουσιαν]{.greek-omitted} [εξουσια]{.greek-added} [αυτων]{.greek-added} [εχουσιν]{.greek-omitted} [του]{.greek-omitted} αδικησαι τους [ανθρωπους]{.greek-abbr} μηνας πεντε[9:10]{.aside}

[και]{.greek-added} [εχουσαι]{.greek-omitted} [εχουσιν]{.greek-added} [βασιλεα]{.greek-omitted} επ αυτων [βασιλεα]{.greek-added} [τον]{.greek-added} αγγελον της αβυσσου ονομα αυτω εβραιστι αββαδων [και]{.greek-added} εν [δε]{.greek-omitted} τη ελληνικη ονομα εχει απολλυων[9:11]{.aside}

η ουαι η [μια]{.greek-omitted} [μι]{.greek-added} απηλθεν ιδου [ερχεται]{.greek-omitted} [ερχονται]{.greek-added} [ετι]{.greek-omitted} δυο ουαι μετα [ταυ]{.greek-added} ταυτα[9:12]{.aside}

και ο εκτος αγγελος εσαλπισεν και ηκουσα φωνην μιαν εκ των τεσσαρων κερατων του θυσιαστηριου του χρυσου του ενωπιον του [θεου]{.greek-abbr}[9:13]{.aside}

λεγουσαν τω εκτω αγγελω ο εχων την σαλπιγγα λυσον τους [τεσσαρας]{.greek-omitted} [τεσσαρις]{.greek-added} αγγελους [τους]{.greek-added} τους δεδεμενους επι τω ποταμω τω μεγαλω [ευφρατη]{.greek-omitted} [ευφρα]{.greek-added}[9:14]{.aside}

[λεγουσαν]{.greek-omitted} [τω]{.greek-omitted} [εκτω]{.greek-omitted} [αγγελω]{.greek-omitted} [ο]{.greek-omitted} [εχων]{.greek-omitted} [την]{.greek-omitted} [τη]{.greek-added} [σαλπιγγα]{.greek-omitted} [λυσον]{.greek-omitted} [τους]{.greek-omitted} [τεσσαρας]{.greek-omitted} [αγγελους]{.greek-omitted} [τους]{.greek-omitted} [δεδεμενους]{.greek-omitted} [επι]{.greek-omitted} [τω]{.greek-omitted} [ποταμω]{.greek-omitted} [τω]{.greek-omitted} [μεγαλω]{.greek-omitted} [ευφρατη]{.greek-omitted}[9:14 | instance no. 2]{.aside}

και ελυθησαν οι [τεσσαρες]{.greek-omitted} [τεσσαρι[ς]{.unclear}]{.greek-added} αγγελοι οι [ητοιμασμενοι]{.greek-omitted} [ετοιμασμενοι]{.greek-added} εις την ωραν και [εις]{.greek-omitted} [την]{.greek-omitted} ημεραν και μηνα και [ενιαυτον]{.greek-omitted} [ενιαυτων]{.greek-added} ινα [αποκτεινωσιν]{.greek-omitted} [αποκτηνωσιν]{.greek-added} το τριτον των [ανθρωπων]{.greek-abbr}[9:15]{.aside}

και ο αριθμος των στρατευματων του [[νωτυ]{.unclear}]{.greek-added} [ιππου]{.greek-omitted} [[ιππ]{.unclear}ικου]{.greek-added} [μυριαδες]{.greek-omitted} [δισμυριαδες]{.greek-added} μυριαδων ηκουσα [τον]{.greek-omitted} [των]{.greek-added} αριθμον [αυτον]{.greek-added} [αυτων]{.corr}[9:16]{.aside}

και ουτως [ειδον]{.greek-omitted} [ιδον]{.greek-added} τους ιππους εν τη ορασει και τους καθημενους επ αυτων εχοντας θωρακας πυρινους και υακινθινους και [θειωδεις]{.greek-omitted} [θειωδους]{.greek-added} και αι κεφαλαι των ιππων ως κεφαλαι λεοντων και εκ των σ[τομα]{.unclear}των αυτων εκπορευεται πυρ και καπνος και θειον[9:17]{.aside}

απο των τριων [πληγων]{.greek-omitted} [του]{.unclear}των απεκτανθησαν το τριτον των [ανθρωπων]{.greek-abbr} [απο]{.greek-omitted} [εκ]{.greek-added} του πυρος και [του]{.greek-omitted} [εκ]{.greek-added} καπνου και [εκ]{.greek-added} του θειου του εκπορευομενου εκ των στοματων αυτων[9:18]{.aside}

η γαρ εξουσια [των]{.greek-omitted} [αυτων]{.greek-added} [ιππων]{.greek-omitted} εν [τω]{.greek-omitted} [το]{.greek-added} στοματι αυτων εστιν [και]{.greek-omitted} [εν]{.greek-omitted} [ταις]{.greek-omitted} [ουραις]{.greek-omitted} [αυτων]{.greek-omitted} αι γαρ ουραι αυτων ομοιαι [οφεων]{.greek-omitted} [οφεσιν]{.greek-added} [εχουσαι]{.greek-omitted} [εχουσαις]{.greek-added} κεφαλ[ας]{.unclear} και εν αυταις [αδικουσιν]{.greek-omitted} [αδικησουσιν]{.greek-added}[9:19]{.aside}

και οι λοιποι των [ανθρωπων]{.greek-abbr} οι ουκ απεκτανθησαν εν ταις πληγαις ταυταις [ου]{.greek-omitted} [ουτε]{.greek-added} [μετενοησαν]{.greek-omitted} [εμετενοησαν]{.greek-added} εκ των εργων των χειρων αυτων ινα μη προσκυνησωσιν [τα]{.greek-omitted} [δαιμονια]{.greek-omitted} [και]{.greek-omitted} τα ειδωλα τα χρυσα και τα αργυρα και τα χαλκα και τα [λιθινα]{.greek-omitted} [λιθεινα]{.greek-added} και τα [ξ]{.unclear}υλινα α ουτε βλεπειν δυναται ουτε ακουειν ουτε περιπατειν[9:20]{.aside}

και ου μετενοησαν εκ των φονων αυτων ουτε εκ των [φαρμακειων]{.greek-omitted} [φαρμακιων]{.greek-added} αυτων ουτε εκ της πορνειας αυτων ουτε εκ των κλεμματων αυτων[9:21]{.aside}

### Chapter 10

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} [αλλον]{.greek-added} αγγελον ισχυρον καταβαινοντα εκ του [ουρανου]{.greek-abbr} [περιβεβλημενον]{.greek-omitted} [περιβλημενον]{.greek-added} νεφελην και [η]{.greek-omitted} ιρις επι της κεφαλης αυτου και το προσωπον αυτου ως ο ηλιος και οι ποδες αυτου ως στυλοι πυρος[10:1]{.aside}

και [εχων]{.greek-omitted} [ειχεν]{.greek-added} εν τη χειρι αυτου [βιβλιον]{.greek-omitted} [βιβλαριδιον]{.greek-added} ανεωγμενον και εθηκεν τον ποδα αυτου τον δεξιον επι [της]{.greek-omitted} [την]{.greek-added} [θαλασσης]{.greek-omitted} [[θα]{.unclear}λασσαν]{.greek-added} τον δε ευων[υμον]{.unclear} επι της γης[10:2]{.aside}

και εκραξεν φωνη μεγαλη ωσπερ λεων μυκαται και οτε εκραξεν [ελαλησαν]{.greek-omitted} [ελαλεισαν]{.greek-added} αι επτα βρονται τας εαυτων φωνας[]{.unclear}[10:3]{.aside}

και οτε ελαλησαν αι επτα βρονται [εμελλον]{.greek-omitted} [ημελλον]{.greek-added} γραφειν και ηκουσα φων[ην]{.unclear} εκ του [ουρανου]{.greek-abbr} λεγουσαν σφραγισον α ελαλησαν αι επτα βρονται και [μη]{.greek-omitted} [μετα]{.greek-added} [αυτα]{.greek-omitted} [ταυτα]{.greek-added} [γραψης]{.greek-omitted} [γραφεις]{.greek-added}[10:4]{.aside}

και ο αγγελος ον [ειδον]{.greek-omitted} [ι[δον]{.unclear}]{.greek-added} εστωτα επι της [θαλ]{.unclear}ασσης και επι της γης [ηρεν]{.greek-omitted} [ειρ[εν]{.unclear}]{.greek-added} [την]{.unclear} χειρα αυτου [την]{.greek-omitted} [δεξιαν]{.greek-omitted} εις τον [ουρανον]{.greek-abbr}[10:5]{.aside}

και [ωμοσεν]{.greek-omitted} [ωμωσεν]{.greek-added} [εν]{.greek-added} τω ζωντι εις τους [εις]{.greek-added} [τους]{.greek-added} αιωνας [ως]{.greek-added} [των]{.greek-omitted} [αιωνων]{.greek-omitted} [ος]{.greek-omitted} [εκτισεν]{.greek-omitted} [εκτισε]{.greek-added} τον [ουρανον]{.greek-abbr} και τα [εν]{.unclear} [αυ]{.unclear}τω [και]{.corr} [την]{.corr} [γην]{.corr} [και]{.corr} [τα]{.corr} [εν]{.corr} [αυτη]{.corr} και την θ[αλασ]{.unclear}σαν και τα εν αυτη[]{.unclear} οτι χρονος ουκετι εσται[10:6]{.aside}

αλλ εν ταις ημεραις της [φωνης]{.greek-omitted} [φω[τι]{.unclear}νης]{.greek-added} του εβδομου αγγελου οταν [μελλη]{.greek-omitted} [μελλει]{.greek-added} σαλπιζειν και [ετελεσθη]{.greek-omitted} [τελεσθη]{.greek-added} το [μυστηριον]{.greek-omitted} [μυστηριοι]{.greek-added} του [θεου]{.greek-abbr} ως [ευηγγελισεν]{.greek-omitted} [ευηγγελισατο]{.greek-added} τους [εαυτου]{.greek-added} δουλους [αυτου]{.greek-omitted} τους προφητας[10:7]{.aside}

και η φωνη ην ηκουσα εκ του [ουρανου]{.greek-omitted} παλιν [λαλουσα]{.greek-omitted} [λαλουσαν]{.greek-added} μετ εμου και [λεγουσα]{.greek-omitted} [λεγ[ου]{.unclear}σαν]{.greek-added} υπ[αγε]{.unclear} λαβε το [βιβλιδαριον]{.greek-omitted} [βιβλαριδιον]{.greek-added} το [ανεωγμενον]{.greek-omitted} [ηνεωγμενον]{.greek-added} εν τη χειρι του αγγελου του εστωτος επι της θαλασσης και επι της γης[10:8]{.aside}

και ελαβον το [βιβλιον]{.greek-omitted} [βιβλαριδιον]{.greek-added} εκ της χειρος του αγγελου και κατεφαγον [αυτο]{.greek-omitted} [αὐτõυ]{.greek-added} και ην εν [τω]{.greek-omitted} [το]{.greek-added} στοματι μου ως μελι γλυκυ και οτε εφαγον [αυτο]{.greek-omitted} [αυτον]{.greek-added} επικρανθη η κοιλια μου[]{.unclear}[10:10]{.aside}

και [λεγουσιν]{.greek-omitted} [λεγει]{.greek-added} μοι δει [σαι]{.greek-added} [σε]{.corr} παλιν προφητευσαι επι λαοις και [επι]{.greek-omitted} [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} και γλωσσαις και [βασιλευσιν]{.greek-omitted} [βασ[ι]{.unclear}λευσι]{.greek-added} πολλοις[10:11]{.aside}

### Chapter 11

και [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} μοι καλαμος ομοιος ραβδω λεγων [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} και [μετρησον]{.greek-omitted} [μετρισον]{.greek-added} τον ναον του [θεου]{.greek-abbr} και το θυσιαστηριον και τους προσκυνουντας εν αυτω[11:1]{.aside}

και την αυλην την [εξωθεν]{.greek-omitted} [εσωθεν]{.greek-added} του ναου εκβαλε [εξω]{.greek-omitted} [εξωθεν]{.greek-added} και μη αυτην [μετρησης]{.greek-omitted} [μετρισης]{.greek-added} οτι [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} τοις εθνεσιν και την πολιν την αγιαν πατησουσιν μηνας [τεσσαρακοντα]{.greek-omitted} [τεσσαρακονταδυο]{.greek-added} [και]{.greek-omitted} [δυο]{.greek-omitted}[11:2]{.aside}

και δωσω τοις [δυσιν]{.greek-omitted} [δυσι]{.greek-added} [μαρτυσιν]{.greek-omitted} [μαρτυσι]{.greek-added} μου και [προφητευσουσιν]{.greek-omitted} [προφητευσουσι]{.greek-added} ημερας χιλιας διακοσιας εξηκοντα περιβεβλημενοι σακκους[11:3]{.aside}

ουτοι εισιν [αι]{.greek-omitted} [δυο]{.greek-omitted} [ελαιαι]{.greek-omitted} [και]{.greek-omitted} αι δυο λυχνιαι αι ενωπιον του [[θεου]{.greek-abbr}]{.greek-added} [κυριου]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} εστωσαι[11:4]{.aside}

και [ει]{.greek-omitted} [η]{.greek-added} τις αυτους θελει αδικησαι πυρ εκπορευεται εκ του στοματος [αυτων]{.greek-omitted} [αυτοις]{.greek-added} και κατεσθιει τους εχθρους αυτων και ει τις [[αυτους]{.unclear}]{.greek-added} [θ]{.unclear}ελει [αυτους]{.greek-omitted} αδικησαι ουτως δει αυτον αποκτανθηναι[11:5]{.aside}

ουτοι [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} [εξ[ουσ]{.unclear}ιαν]{.greek-added} [κ[λ]{.unclear}εισαι]{.greek-added} τον [ουρανον]{.greek-abbr} [εξουσιαν]{.greek-omitted} [κλεισαι]{.greek-omitted} ινα μη υετος βρεχη τας ημερας τη[ς]{.unclear} [προ]{.unclear}φητειας αυτων και εξουσιαν εχουσιν επι των υδατων στρεφειν [αυτα]{.greek-omitted} εις αιμα και παταξαι την γην [οσακις]{.greek-omitted} [εαν]{.greek-omitted} [θελησωσιν]{.greek-omitted} εν παση πληγη [οσακις]{.greek-added} [εαν]{.greek-added} [θελουσιν]{.greek-added}[11:6]{.aside}

και [οταν]{.greek-omitted} [οτε]{.greek-added} τελεσωσιν την μαρτυριαν αυτων το θηριον το αναβαινον εκ της αβυσσου ποιησει [πολεμον]{.greek-added} μετ αυτων [πολεμον]{.greek-omitted} και νικησει αυτους [και]{.greek-omitted} [αποκτενει]{.greek-omitted} [αυτους]{.greek-omitted}[11:7]{.aside}

και [το]{.greek-omitted} [τα]{.greek-added} [πτωμα]{.greek-omitted} [πτωματα]{.greek-added} αυτων επι της πλατειας της πολεως της μεγαλης ητις καλειτα[ι]{.unclear} [πνευματικως]{.greek-abbr} σοδομα και αιγυπτος οπου [και]{.greek-omitted} ο [κυριος]{.greek-abbr} αυτων [εσταυρωθη]{.greek-abbr}[11:8]{.aside}

και βλεπουσιν εκ των λαων και φυλων και γλωσσων και εθνων [το]{.greek-omitted} [πτωμα]{.greek-omitted} [αυτων]{.greek-omitted} ημερας τρεις [ημισυ]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} [πτωματα]{.greek-omitted} [αυτων]{.greek-omitted} [ουκ]{.greek-omitted} [αφησουσιν]{.greek-omitted} [τεθηναι]{.greek-omitted} [εις]{.greek-omitted} [μνημα]{.greek-omitted}[11:9]{.aside}

[και]{.greek-omitted} [βλεπουσιν]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [λαων]{.greek-omitted} [και]{.greek-omitted} [φυλων]{.greek-omitted} [και]{.greek-omitted} [γλωσσων]{.greek-omitted} [και]{.greek-omitted} [εθνων]{.greek-omitted} [το]{.greek-omitted} [πτωμα]{.greek-omitted} [αυτων]{.greek-omitted} [ημερας]{.greek-omitted} [τρεις]{.greek-omitted} ημισυ και τα πτωματα αυτων ουκ [αφησουσιν]{.greek-omitted} [αφιουσιν]{.greek-added} τεθηναι εις [μνημα]{.greek-omitted} [μνηματα]{.greek-added}[11:9 | instance no. 2]{.aside}

και οι κατοικουντες επι της γης χαιρουσιν επ αυτοις και [ευφρανθησονται]{.greek-omitted} [ευφραινονται]{.greek-added} και δωρα [δωσουσιν]{.greek-omitted} [πεμψουσιν]{.greek-added} [αλληλοις]{.greek-omitted} [αλλιλοις]{.greek-added} οτι ουτοι οι δυο προφηται [εβασανισαν]{.greek-omitted} [εβασανησαν]{.greek-added} τους κατοικουντας επι της γης[11:10]{.aside}

και μετα [τας]{.greek-omitted} τρεις ημερας και ημισυ[]{.unclear} [[πνευματα]{.greek-abbr}]{.greek-added} [[πνευμα]{.greek-abbr}]{.corr} [οι]{.greek-added} ζωης εκ του [θεου]{.greek-abbr} εισηλθεν [εις]{.greek-omitted} [αυτους]{.greek-omitted} [αυτοις]{.greek-added} και εστησαν επι τους ποδας αυτων και φοβος μεγας επεσεν επι τους [θεωρουντας]{.greek-omitted} [θεορουντας]{.greek-added} αυτους[11:11]{.aside}

και ηκουσα [φωνην]{.greek-omitted} [φωνης]{.greek-added} [μεγαλην]{.greek-omitted} [μεγαλης]{.greek-added} εκ του [ουρανου]{.greek-abbr} [λεγουσαν]{.greek-omitted} [λεγουσης]{.greek-added} αυτοις[]{.unclear} [αναβητε]{.greek-omitted} [ἀνάβητε]{.greek-added} ωδε και ανεβησαν εις τον [ουρανον]{.greek-abbr} εν τη νεφελη και [εθεωρησαν]{.greek-omitted} [εθεορησαν]{.greek-added} αυτους οι εχθροι αυτων[11:12]{.aside}

και εν εκεινη τη [ημερα]{.greek-omitted} [ωρα]{.greek-added} εγενετο [σεισμος]{.greek-omitted} [σισμος]{.greek-added} μεγας και το δεκατον της πολεως επεσεν και απεκτανθησαν [εν]{.greek-omitted} [τω]{.greek-omitted} [σεισμω]{.greek-omitted} ονοματα [ανθρωπων]{.greek-abbr} χιλιαδες επτα και οι λοιποι [εν]{.greek-added} [φοβοι]{.greek-added} εμφοβοι εγενοντο και εδωκαν δοξαν τω [θεω]{.greek-abbr} του [ουρανου]{.greek-abbr}[11:13]{.aside}

η ουαι η δευτερα απηλθεν [ιδου]{.greek-added} η ουαι η τριτη [ιδου]{.greek-omitted} ερχεται ταχυ[11:14]{.aside}

και ο εβδομος αγγελος εσαλπισεν και εγενοντο φωναι μεγαλαι εν τω [ουρανω]{.greek-abbr} λεγουσαι [εγενετο]{.greek-omitted} [εγενοντο]{.greek-added} [η]{.greek-omitted} [αι]{.greek-added} [βασιλεια]{.greek-omitted} [βασιλειαι]{.greek-added} του κοσμου του [κυριου]{.greek-abbr} ημων και του [χριστου]{.greek-abbr} αυτου και βασιλευσει εις τους αιωνας των αιωνων [αμην]{.greek-added}[11:15]{.aside}

και οι εικοσι τεσσαρες πρεσβυτεροι [οι]{.greek-omitted} ενωπιον [του]{.greek-omitted} [θρονου]{.greek-omitted} του [θεου]{.greek-abbr} καθημενοι επι τους θρονους αυτων [επεσον]{.greek-omitted} [επεσαν]{.greek-added} επι [τα]{.greek-omitted} προσωπα αυτων και προσεκυνησαν τω [θεω]{.greek-abbr}[11:16]{.aside}

λεγοντες ευχαριστουμεν σοι [κυριε]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ ο ων και ο ην οτι ειληφας την [δυναμιν]{.greek-omitted} [δυναμειν]{.greek-added} σου την μεγαλην και εβασιλευσας[11:17]{.aside}

και τα εθνη [ωργισθησαν]{.greek-omitted} [οργισθησαν]{.greek-added} [και]{.greek-added} [ηλθεν]{.greek-added} [η]{.greek-added} [οργη]{.greek-added} [σου]{.greek-added} [και]{.greek-added} [ο]{.greek-added} [καιρος]{.greek-added} [των]{.greek-added} [νεκρων]{.greek-added} [διοφησιν]{.greek-added} και ηλθεν η οργη σου και ο καιρος των νεκρων κριθηναι και δουναι τον μισθον τοις δουλοις σου τοις προφηταις και τοις αγιοις [και]{.greek-omitted} τοις φοβουμενοις το ονομα σου τοις μικροις και τοις μεγαλοις και [διαφθειραι]{.greek-omitted} [διαφθηραι]{.greek-added} τους [διαφθειροντας]{.greek-omitted} [διαφθειραντας]{.greek-added} την γην[11:18]{.aside}

και ηνοιγη ο ναος του [θεου]{.greek-abbr} εν τω [ουρανω]{.greek-abbr} και ωφθη η κιβωτος της διαθηκης [του]{.greek-omitted} [αυτου]{.greek-added} [κυριου]{.greek-omitted} εν τω ναω αυτου και εγενοντο αστραπαι και φωναι και βρονται και [ο]{.greek-added} [σισμος]{.greek-added} [και]{.greek-added} χαλαζα μεγαλη[11:19]{.aside}

### Chapter 12

και [σημειον]{.greek-omitted} [σιμειον]{.greek-added} μεγα ωφθη εν τω [ουρανω]{.greek-abbr} γυνη περιβεβλημενη τον ηλιον και η [σεληνη]{.greek-omitted} [σελεινη]{.greek-added} υποκατω των ποδων αυτης και επι της κεφαλης αυτης στεφανος αστερων [δωδεκα]{.greek-omitted} [δεκα]{.greek-added} [δυο]{.greek-added}[12:1]{.aside}

και ωφθη αλλ[ο]{.unclear} [σημειον]{.greek-omitted} [σιμειον]{.greek-added} εν τω [ουρανω]{.greek-abbr} και ιδου δρακων [πυρος]{.greek-omitted} μεγας [πυρρος]{.greek-added} εχων [κεφαλας]{.greek-omitted} [επτα]{.greek-omitted} [και]{.greek-omitted} [κερατα]{.greek-omitted} [δεκα]{.greek-omitted} [και]{.greek-omitted} [επι]{.greek-omitted} [τας]{.greek-omitted} [κεφαλας]{.greek-omitted} [αυτου]{.greek-omitted} [επτα]{.greek-omitted} [διαδηματα]{.greek-omitted}[12:3]{.aside}

[και]{.greek-omitted} [ωφθη]{.greek-omitted} [αλλο]{.greek-omitted} [σημειον]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ουρανω]{.greek-omitted} [και]{.greek-omitted} [ιδου]{.greek-omitted} [δρακων]{.greek-omitted} [πυρος]{.greek-omitted} [μεγας]{.greek-omitted} [εχων]{.greek-omitted} κεφαλας επτα και κερατα δεκα και επι τας [κεφαλας]{.greek-omitted} [κεφας]{.greek-added} αυτου [επτα]{.greek-omitted} διαδηματα[12:3 | instance no. 2]{.aside}

[και]{.greek-omitted} [η]{.greek-omitted} [ουρα]{.greek-omitted} [αυτου]{.greek-omitted} [συρει]{.greek-omitted} [το]{.greek-omitted} [τριτον]{.greek-omitted} [των]{.greek-omitted} [αστερων]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [και]{.greek-omitted} [εβαλεν]{.greek-omitted} [αυτους]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [γην]{.greek-omitted} και ο δρακων [εστηκεν]{.greek-omitted} [ἐστήκεν]{.greek-added} ενωπιον της γυναικος της μελλουσης τεκειν ινα οταν τεκη το τεκνον αυτης [καταφαγη]{.greek-omitted} [καταφαγει]{.greek-added}[12:4]{.aside}

και ετεκεν υιον αρρενα ος μελλει [ποιμαινειν]{.greek-omitted} [ποιμενειν]{.greek-added} παντα τα εθνη [εν]{.greek-omitted} ραβδω σιδηρα και [ηρπασθη]{.greek-omitted} [ηρπασθει]{.greek-added} το τεκνον αυτης προς τον [θεον]{.greek-abbr} και [προς]{.greek-omitted} τον θρονον αυτου[12:5]{.aside}

και η γυνη εφυγεν εις την ερημον οπου εχει [εκει]{.greek-omitted} τοπον ητοιμασμενον [υπο]{.greek-omitted} [απο]{.greek-added} του [θεου]{.greek-abbr} ινα εκει [εκτρεφωσιν]{.greek-omitted} [τρεφουτιν]{.greek-added} αυτην ημερας χιλιας διακοσιας εξηκοντα[12:6]{.aside}

και εγενετο πολεμος εν τω [ουρανω]{.greek-abbr} ο μιχαηλ και οι αγγελοι αυτου [του]{.greek-added} πολεμησαι μετα του δρακοντος και ο δρακων επολεμησεν και οι αγγελοι αυτου[12:7]{.aside}

και ουκ [ισχυσεν]{.greek-omitted} [ισχυσαν]{.greek-added} [ουδε]{.greek-omitted} [ουτε]{.greek-added} τοπος [ευρεθη]{.greek-omitted} [ηυρεθη]{.greek-added} [αυτω]{.greek-omitted} [αυτων]{.greek-added} ετι εν τω [ουρανω]{.greek-abbr}[12:8]{.aside}

και εβληθη ο δρακων ο μεγας [ο]{.greek-omitted} οφις ο αρχαιος ο καλουμενος διαβολος και [ο]{.greek-added} σατανας ο πλανων την οικουμενην ολην εβληθη εις την γην και οι αγγελοι αυτου [μετ]{.greek-omitted} [αυτου]{.greek-omitted} εβληθησαν[12:9]{.aside}

και ηκουσα φωνην μεγαλην εν τω ουρανω λεγουσαν αρτι εγενετο η [σωτηρια]{.greek-abbr} και η [δυναμις]{.greek-omitted} [δυναμεις]{.greek-added} και η βασιλεια του [θεου]{.greek-abbr} ημων και η εξουσια του [χριστου]{.greek-abbr} αυτου οτι [εβληθη]{.greek-omitted} [κατεβληθη]{.greek-added} ο κατηγορος των [αδελφων]{.corr} ημων [[ημων]{.corr}]{.greek-added} ο [κατηγορων]{.greek-omitted} [κατειγορων]{.greek-added} [αυτων]{.greek-omitted} [αυτους]{.greek-added} ενωπιον του [θεου]{.greek-abbr} [ημων]{.greek-omitted} ημερας και νυκτος[12:10]{.aside}

και αυτοι ενικησαν αυτον δια το αιμα του αρνιου και δια τον λογον της μαρτυριας αυτων και ουκ ηγαπησαν την ψυχην αυτων αχρι θανατου[12:11]{.aside}

δια τουτο [ευφραινεσθε]{.greek-omitted} [ευφραινεσθαι]{.greek-added} [οι]{.greek-added} [ουρανοι]{.greek-abbr} και οι εν αυτοις [σκηνουντες]{.greek-omitted} [συνοντες]{.greek-added} ουαι [τη]{.greek-omitted} [την]{.greek-added} [γη]{.greek-omitted} [γην]{.greek-added} και [τη]{.greek-omitted} [την]{.greek-added} [θαλασση]{.greek-omitted} [θαλασαν]{.greek-added} οτι κατεβη ο διαβολος προς υμας εχων θυμον μεγαν [[μεγα]{.corr}]{.greek-added} ειδως οτι ολιγον καιρον εχει[12:12]{.aside}

και οτε [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} ο δρακων οτι εβληθη εις την γην [εδιωξεν]{.greek-omitted} [εδιοξεν]{.greek-added} την γυναικα ητις ετεκεν τον αρρενα[12:13]{.aside}

και [εδοθησαν]{.greek-omitted} [εδωθησαν]{.greek-added} τη γυναικι [αι]{.greek-added} δυο πτερυγες του αετου [του]{.greek-omitted} μεγαλου ινα [πετηται]{.greek-omitted} [πεταται]{.greek-added} [εις]{.greek-omitted} [την]{.greek-omitted} [ερημον]{.greek-omitted} εις τον τοπον αυτης [οπως]{.greek-omitted} [οπου]{.greek-added} [τρεφηται]{.greek-omitted} [τρεφεται]{.greek-added} εκει καιρον και καιρους και ημισυ καιρου απο προσωπου του οφεως[12:14]{.aside}

[και]{.greek-omitted} εβαλεν ο οφις εκ του στοματος αυτου οπισω της γυναικος υδωρ ως ποταμον ινα [αυτην]{.greek-omitted} [ταυτην]{.greek-added} ποταμοφορητο[ν]{.unclear} [ποιηση]{.greek-omitted} [ποιησει]{.greek-added}[12:15]{.aside}

και εβοηθησεν η γη τη γυναικι και ηνοιξεν η γη το στομα αυτης και κατεπιεν [τον]{.greek-omitted} [[του]{.unclear}]{.greek-added} ποταμον ον εβαλεν ο δρακων εκ του στοματος αυτου[12:16]{.aside}

και [ωργισθη]{.greek-omitted} [οργισθη]{.greek-added} ο δρακων επι τη γυναικι και απηλθεν ποιησαι πολεμον μετα των λοιπων του σπερματος αυτης των [τηρουντων]{.greek-omitted} [τηρουν]{.greek-added} [τας]{.greek-omitted} [εντολας]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [και]{.greek-omitted} [εχοντων]{.greek-omitted} [την]{.greek-omitted} [μαρτυριαν]{.greek-omitted} [ιησου]{.greek-omitted}[12:17]{.aside}

[τον]{.greek-added} [και]{.greek-omitted} [ωργισθη]{.greek-omitted} [ο]{.greek-omitted} [δρακων]{.greek-omitted} [επι]{.greek-omitted} [τη]{.greek-omitted} [γυναικι]{.greek-omitted} [και]{.greek-omitted} [απηλθεν]{.greek-omitted} [ποιησαι]{.greek-omitted} [πολεμον]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} [λοιπων]{.greek-omitted} [του]{.greek-omitted} [σπερματος]{.greek-omitted} [αυτης]{.greek-omitted} [των]{.greek-omitted} [τηρουντων]{.greek-omitted} τας εντολας του [θεου]{.greek-abbr} και εχοντων την μαρτυριαν [ιησου]{.greek-abbr} [και]{.greek-added} [εσταθην]{.greek-added} [επι]{.greek-added} [την]{.greek-added} [αμμον]{.greek-added} [της]{.greek-added} [θαλασσης]{.greek-added}[12:17 | instance no. 2]{.aside}

### Chapter 13

και [ιδου]{.greek-added} [εσταθην]{.greek-omitted} [επι]{.greek-omitted} [την]{.greek-omitted} [αμμον]{.greek-omitted} [της]{.greek-omitted} [θαλασσης]{.greek-omitted} [και]{.greek-omitted} [ειδον]{.greek-omitted} εκ της θαλασσης θηριον αναβαινον [εχον]{.greek-omitted} [εχων]{.greek-added} κερατα δεκα και κεφαλας επτα και επι των κερατων αυτου δεκα διαδηματα και επι τας κεφαλας αυτου [ονοματα]{.greek-omitted} [ονομα]{.greek-added} βλασφημιας[13:1]{.aside}

και το θηριον ο [ειδον]{.greek-omitted} [οιδον]{.greek-added} [ην]{.greek-omitted} ομοιον παρδαλει και οι ποδες αυτου ως αρκου και το στομα αυτου ως στομα λεοντος και εδωκεν αυτω ο [δρακων]{.greek-omitted} [δρακον]{.greek-added} την δυναμιν αυτου και τον θρονον αυτου και εξουσιαν μεγαλην[13:2]{.aside}

και [μιαν]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [κεφαλων]{.greek-omitted} [αυτου]{.greek-omitted} [ωσει]{.greek-omitted} [εσφαγμενην]{.greek-omitted} [εις]{.greek-omitted} [θανατον]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [πληγη]{.greek-omitted} [του]{.greek-omitted} [θανατου]{.greek-omitted} [αυτου]{.greek-omitted} [εθεραπευθη]{.greek-omitted} [και]{.greek-omitted} [εθαυμασεν]{.greek-omitted} [εθαυμασθη]{.greek-added} [εν]{.greek-added} ολη [η]{.greek-omitted} [τη]{.greek-added} γη οπισω του θηριου[13:3]{.aside}

και προσεκυνησαν τω [δρακοντι]{.greek-omitted} [δρακωντι]{.greek-added} [τω]{.greek-omitted} [δεδωκοτι]{.greek-omitted} [οτι]{.greek-added} [εδωκεν]{.greek-added} την εξουσιαν [τω]{.greek-omitted} [θηριω]{.greek-omitted} [και]{.greek-omitted} [προσεκυνησαν]{.greek-omitted} τω θηριω λεγοντες τις ομοιος τω θηριω και τις [δυνατος]{.greek-omitted} [δυναται]{.greek-added} πολεμησαι μετ αυτου[13:4]{.aside}

και [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} αυτω στομα [λαλουν]{.greek-omitted} [λαλων]{.greek-added} μεγαλα και [βλασφημιαν]{.greek-omitted} [βλασφημα]{.greek-added} και [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} [αυτω]{.greek-omitted} [αυτου]{.greek-added} [εξουσια]{.greek-omitted} [εξουσιαν]{.greek-added} [πολεμον]{.greek-omitted} ποιησαι μηνας τεσσαρακοντα δυο[13:5]{.aside}

και ηνοιξεν το στομα αυτου εις βλασφημιαν προς τον [θεον]{.greek-abbr} βλασφημησαι το ονομα αυτου και την σκηνην αυτου [και]{.greek-added} τους εν τω [ουρανω]{.greek-abbr} σκηνουντας[13:6]{.aside}

και [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} αυτω [ποιησαι]{.greek-omitted} [πολεμον]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} [αγιων]{.greek-omitted} [και]{.greek-omitted} [νικησαι]{.greek-omitted} [αυτους]{.greek-omitted} [και]{.greek-omitted} [εδοθη]{.greek-omitted} [αυτω]{.greek-omitted} [εξουσια]{.greek-omitted} [εξουσιαν]{.greek-added} επι πασαν φυλην και [λαον]{.greek-omitted} [και]{.greek-omitted} γλωσσαν και εθνος[13:7]{.aside}

και προσκυνησουσιν αυτω παντες οι [κατοικουντες]{.greek-omitted} [κατοικουντεστ]{.greek-added} επι της γης ων ου γεγραπται το ονομα εν τω [βιβλιω]{.greek-omitted} [βιβλω]{.greek-added} της ζωης του αρνιου του [του]{.greek-added} εσφαγμενου απο καταβολης κοσμου[13:8]{.aside}

ει τις εχει ους ακουσατω[13:9]{.aside}

ει τις [εχει]{.greek-omitted} [εις]{.greek-added} αιχμαλωσιαν υπαγει ει τις εν μαχαιρα [αποκτενει]{.greek-omitted} [ἀποκτενεῖ]{.greek-added} δει αυτον εν μαχαιρα αποκτανθηναι ωδε εστιν [η]{.greek-omitted} υπομονη και η πιστις των αγιων[13:10]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} αλλο θηριον [αναβαινον]{.greek-omitted} [ἀναβαίνον]{.greek-added} εκ της γης και ειχεν κερατα [δυο]{.greek-omitted} [δεκαδυο]{.greek-added} [ομοια]{.greek-omitted} [ομοι]{.greek-added} αρνιω και [ελαλει]{.greek-omitted} [ελαλη]{.greek-added} ως δρακων[13:11]{.aside}

και την εξουσιαν του πρωτου θηριου πασαν ποιει ενωπιον αυτου και [εποιει]{.greek-omitted} [ποιει]{.greek-added} την γην και τους εν αυτη κατοικουντας ινα [προσκυνησωσιν]{.greek-omitted} [προσκυνησωσι]{.greek-added} το θηριον το πρωτον ου εθεραπευθη η πληγη του θανατου αυτου[13:12]{.aside}

και ποιει [σημεια]{.greek-omitted} [σιμεια]{.greek-added} μεγαλα [και]{.greek-omitted} [ινα]{.greek-added} πυρ [ινα]{.greek-omitted} [ποιει]{.greek-added} [καταβαινειν]{.greek-added} εκ του [ουρανου]{.greek-abbr} [εις]{.greek-added} [καταβαινη]{.greek-omitted} [επι]{.greek-omitted} την γην ενωπιον των [υιων]{.greek-added} [των]{.greek-added} [ανθρωπων]{.greek-abbr}[13:13]{.aside}

και πλανα [τους]{.greek-omitted} [εμους]{.greek-omitted} τους κατοικουντας επι της γης δια τα [σημεια]{.greek-omitted} [σιμεια]{.greek-added} α [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} αυτω ποιησαι ενωπιον του θηριου [λεγων]{.greek-omitted} [τοις]{.greek-omitted} [κατοικουσιν]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [ποιησαι]{.greek-omitted} [εικονα]{.greek-omitted} [τω]{.greek-omitted} [θηριω]{.greek-omitted} [ο]{.greek-omitted} [ειχεν]{.greek-omitted} [την]{.greek-omitted} [πληγην]{.greek-omitted} και εζησεν [απο]{.greek-omitted} [της]{.greek-omitted} [μαχαιρας]{.greek-omitted}[13:14]{.aside}

και [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} αυτω [δουναι]{.greek-added} πνευμα [δουναι]{.greek-omitted} [τη]{.greek-omitted} [εικονι]{.greek-omitted} [του]{.greek-omitted} [θηριου]{.greek-omitted} [ινα]{.greek-omitted} [και]{.greek-omitted} [λαληση]{.greek-omitted} [η]{.greek-omitted} [εικων]{.greek-omitted} [του]{.greek-omitted} [θηριου]{.greek-omitted} [και]{.greek-omitted} [ποιηση]{.greek-omitted} [οσοι]{.greek-omitted} [εαν]{.greek-omitted} [μη]{.greek-omitted} [προσκυνησωσιν]{.greek-omitted} τη εικονι του θηριου αποκτανθωσιν[13:15]{.aside}

και ποιει παντας τους μικρους και τους μεγαλους [και]{.greek-omitted} [τους]{.greek-omitted} [πλουσιους]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [πτωχους]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [ελευθερους]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [δουλους]{.greek-omitted} [ινα]{.greek-omitted} [δωσωσιν]{.greek-omitted} [αυτοις]{.greek-omitted} [χαραγματα]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [χειρος]{.greek-omitted} [αυτων]{.greek-omitted} [της]{.greek-omitted} [δεξιας]{.greek-omitted} [η]{.greek-omitted} [επι]{.greek-omitted} [το]{.greek-omitted} [μετωπον]{.greek-omitted} [αυτων]{.greek-omitted}[13:16]{.aside}

[και]{.greek-omitted} [ποιει]{.greek-omitted} [παντας]{.greek-omitted} [τους]{.greek-omitted} [μικρους]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [μεγαλους]{.greek-omitted} και τους πλουσιους και τους πτωχους και τους ελευθερους και τους δουλους ινα [δωσωσιν]{.greek-omitted} [δωσιν]{.greek-added} αυτοις [χαραγματα]{.greek-omitted} [χαραγμα]{.greek-added} επι της χειρος αυτων της δεξιας [η]{.greek-omitted} [και]{.greek-added} επι [το]{.greek-omitted} [των]{.greek-added} [μετωπον]{.greek-omitted} [μετωπων]{.greek-added} [[μετοπων]{.corr}]{.greek-added} αυτων[13:16 | instance no. 2]{.aside}

και ινα μη τις δυναται αγορασαι η [πωλησαι]{.greek-omitted} [πολεισαι]{.greek-added} ει [μη]{.greek-omitted} [μι]{.greek-added} ο εχων το χαραγμα το ονομα του θηριου η τον αριθμον του ονοματος αυτου[13:17]{.aside}

### Chapter 14

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} και ιδου [το]{.greek-omitted} αρνιον [εστηκος]{.greek-omitted} [εστως]{.greek-added} επι το ορος σιων και μετ αυτου [αριθμος]{.greek-omitted} εκατον [τεσσαρακοντα]{.greek-omitted} [σερακοντα]{.greek-added} [τεσσαρες]{.greek-omitted} [τεσσαρις]{.greek-added} χιλιαδες εχουσαι το ονομα αυτου και το ονομα του [πατρος]{.greek-abbr} αυτου γεγραμμενον επι των [μετωπων]{.greek-omitted} [μετοπων]{.greek-added} αυτων[14:1]{.aside}

και ηκουσα φωνην εκ του [ουρανου]{.greek-abbr} ως φωνην υδατων πολλων [και]{.greek-omitted} ως φωνην βροντης μεγαλης και [η]{.greek-omitted} [φωνη]{.greek-omitted} [φωνην]{.greek-added} [ην]{.greek-omitted} ηκουσα [ως]{.greek-omitted} [κιθαρωδων]{.greek-omitted} [κιθαροδων]{.greek-added} κιθαριζοντων εν ταις κιθαραις αυτων[14:2]{.aside}

και αδουσιν ωδην καινην ενωπιον του θρονου και ενωπιον των τεσσαρων ζωων και των πρεσβυτερων και ουδεις [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} μαθειν την ωδην ει [μη]{.greek-omitted} [μι]{.greek-added} αι εκατον [τεσσαρακοντα]{.greek-omitted} [σερακοντα]{.greek-added} [τεσσαρες]{.greek-omitted} [τεσσαρις]{.greek-added} χιλιαδες οι ηγορασμενοι απο της γης[14:3]{.aside}

ουτοι εισιν οι μετα γυναικων ουκ εμολυνθησαν [παρθενοι]{.greek-omitted} [παρθνοι]{.greek-added} γαρ εισιν ουτοι [εισιν]{.greek-omitted} οι ακολουθουντες τω αρνιω [οπου]{.greek-omitted} [ουπω]{.greek-added} αν [υπαγη]{.greek-omitted} [υπαγει]{.greek-added} ουτοι [υπο]{.greek-omitted} [ιησου]{.greek-omitted} ηγορασθησαν απο των [ανθρωπων]{.greek-abbr} απαρχη τω [θεω]{.greek-abbr} και τω [και]{.greek-added} [τω]{.greek-added} αρνιω[14:4]{.aside}

και [ουχ]{.greek-omitted} [ευρεθη]{.greek-omitted} εν [τω]{.greek-omitted} [το]{.greek-added} στοματι αυτων [ουκ]{.greek-added} [ηυρεθη]{.greek-added} ψευδος αμωμοι [γαρ]{.greek-omitted} εισιν[14:5]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} αγγελον πετομενον εν μεσουρανηματι εχοντα ευαγγελιον αιωνιον ευαγγελισαι τους καθημενους [τους]{.greek-added} [κατοικουντας]{.greek-added} επι της γης και [επι]{.greek-omitted} παν εθνος και φυλην και γλωσσαν και λαον[14:6]{.aside}

λεγων εν φωνη μεγαλη φοβηθητε τον [κυριον]{.greek-omitted} [[θεον]{.greek-abbr}]{.greek-added} και δοτε αυτω δοξαν οτι ηλθεν η ωρα της κρισεως αυτου και προσκυνησατε [τω]{.greek-added} [αυτον]{.greek-omitted} [τον]{.greek-omitted} [ποιησαντα]{.greek-omitted} [ποιησαντι]{.greek-added} τον [ουρανον]{.greek-abbr} και την γην και [την]{.greek-omitted} [θαλασσαν]{.greek-omitted} [θαλασσας]{.greek-added} και πηγας υδατων[14:7]{.aside}

και αλλος [αγγελος]{.greek-added} δευτερος [αγγελος]{.greek-omitted} ηκολουθησεν λεγων [επεσεν]{.greek-added} επεσεν βαβυλων η μεγαλη [οτι]{.greek-added} εκ του [οινου]{.greek-omitted} [[ουρανου]{.greek-abbr}]{.greek-added} του θυμου της πορνειας αυτης [αυτης]{.greek-added} [πεποτικεν]{.greek-omitted} [πεπτωκε]{.greek-added} παντα τα εθνη[14:8]{.aside}

και αλλος αγγελος [τριτος]{.greek-omitted} ηκολουθησεν αυτοις λεγων εν φωνη μεγαλη ει τις [προσκυνει]{.greek-omitted} [προσκυνη]{.greek-added} [το]{.greek-added} [θηριον]{.greek-added} [και]{.greek-added} [την]{.greek-added} [εικονα]{.greek-added} το θηριον και την εικονα αυτου και λαμβανει χαραγμα επι του [μετωπου]{.greek-omitted} [μετοπου]{.greek-added} αυτου η επι την χειρα αυτου[14:9]{.aside}

και αυτος πιεται εκ του οινου του θυμου του [θεου]{.greek-abbr} του [κεκερασμενου]{.greek-omitted} [κεκεραμενου]{.greek-added} ακρατου εν τω ποτηριω της οργης αυτου και βασανισθησεται εν πυρι και θειω ενωπιον [των]{.greek-omitted} [αγγελων]{.greek-added} αγιων [αγγελων]{.greek-omitted} και ενωπιον του αρνιου[14:10]{.aside}

και ο καπνος του βασανισμου αυτων εις [αιω]{.greek-added} [αιωνας]{.greek-omitted} [αιωνων]{.greek-omitted} [αναβαινει]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [εχουσιν]{.greek-omitted} [αναπαυσιν]{.greek-omitted} [ημερας]{.greek-omitted} [και]{.greek-omitted} [νυκτος]{.greek-omitted} [οι]{.greek-omitted} [προσκυνουντες]{.greek-omitted} [το]{.greek-omitted} [θηριον]{.greek-omitted} [και]{.greek-omitted} [την]{.greek-omitted} [εικονα]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [ει]{.greek-omitted} [τις]{.greek-omitted} [λαμβανει]{.greek-omitted} [το]{.greek-omitted} [χαραγμα]{.greek-omitted} [του]{.greek-omitted} [ονοματος]{.greek-omitted} [αυτου]{.greek-omitted}[14:11]{.aside}

[να]{.greek-added} [και]{.greek-omitted} [ο]{.greek-omitted} [καπνος]{.greek-omitted} [του]{.greek-omitted} [βασανισμου]{.greek-omitted} [αυτων]{.greek-omitted} [εις]{.greek-omitted} [αιωνας]{.greek-omitted} αιωνων [αναβαινει]{.greek-omitted} [αμην]{.greek-added} και ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} αναπαυσιν ημερας και νυκτος οι προσκυνουντες το θηριον και την εικονα αυτου και ει τις λαμβανει το χαραγμα του ονοματος αυτου[14:11 | instance no. 2]{.aside}

και ηκουσα φωνης εκ του ουρανου λεγουσης [μοι]{.greek-added} γραψον μακαριοι οι νεκροι οι εν [κυριω]{.greek-abbr} αποθνη[σ]{.unclear}κοντες [απ]{.greek-omitted} [αρτι]{.greek-omitted} [ἀπάρτι]{.greek-added} [ναι]{.greek-added} λεγει [ναι]{.greek-omitted} το [πνευμα]{.greek-abbr} ινα [αναπαυσωνται]{.greek-omitted} [αναπαυσονται]{.greek-added} εκ [των]{.greek-omitted} [τον]{.greek-added} [κοπων]{.greek-omitted} [κοπον]{.greek-added} αυτων [ταδε]{.greek-added} [τα]{.greek-omitted} [δε]{.greek-omitted} εργα [αυτων]{.greek-omitted} ακολουθει μετ αυτων[14:13]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} και ιδου νεφελη λευκη και επι την νεφελην [καθημενον]{.greek-omitted} [καθημενος]{.greek-added} [ομοιον]{.greek-omitted} [ομοιος]{.greek-added} υιω [ανθρωπου]{.greek-abbr} εχων επι της κεφαλης αυτου στεφανον χρυσουν και εν τη χειρι αυτου δρεπανον οξυ[14:14]{.aside}

και αλλος αγγελος εξηλθεν εκ του [ναου]{.greek-omitted} [[ουρανου]{.greek-abbr}]{.greek-added} [κραζων]{.greek-omitted} [κραζον]{.greek-added} εν φωνη μεγαλη τω καθημενω επι της νεφελης[]{.unclear} πεμψον το δρεπανον σου και θερισον οτι ηλθεν [σου]{.greek-added} η ωρα θερισαι οτι εξηρανθη ο θερισμος της γης[]{.unclear}[14:15]{.aside}

και εβαλεν ο καθημενος επι την νεφελην το δρεπανον αυτου επι την γην και εθερισθη η γη[14:16]{.aside}

και [ο]{.greek-added} αλλος αγγελος εξηλθεν εκ του ναου του [[ουρανου]{.greek-abbr}]{.greek-added} [[τω]{.corr}]{.greek-added} [εν]{.corr} [τω]{.corr} [[ουρανω]{.greek-abbr}]{.corr} εχων και αυτος δρεπανον οξυ[14:17]{.aside}

και αλλος αγγελος εξηλθεν εκ του [θυσιαστηριου]{.greek-omitted} [θυσιαστηριον]{.greek-added} εχων εξουσιαν επι του πυρος και εφωνησεν κραυγη μεγαλη τω [εχοντι]{.greek-omitted} [εχωντι]{.greek-added} το δρεπανον [το]{.greek-omitted} [οξυ]{.greek-omitted} λεγων [πεμψον]{.greek-omitted} [σου]{.greek-omitted} [το]{.greek-omitted} [δρεπανον]{.greek-omitted} [το]{.greek-omitted} [οξυ]{.greek-omitted} και τρυγησον τους βοτρυας της αμπελου της γης οτι [ηκμασαν]{.greek-omitted} [ηγμασεν]{.greek-added} αι σταφυλαι αυτης[14:18]{.aside}

και εβαλεν [ο]{.greek-added} [αγγελος]{.greek-added} ο αγγελος το δρεπανον αυτου εις την γην και ετρυγησεν την αμπελον της γης και εβαλεν εις [την]{.greek-omitted} [τον]{.greek-added} [ληνον]{.greek-omitted} [λινον]{.greek-added} [του]{.greek-omitted} [θυμου]{.greek-omitted} του [θεου]{.greek-abbr} τον μεγαν[14:19]{.aside}

[και]{.greek-omitted} [επατηθη]{.greek-omitted} [η]{.greek-omitted} [ληνος]{.greek-omitted} [εξωθεν]{.greek-omitted} [της]{.greek-omitted} [πολεως]{.greek-omitted} και εξηλθεν αιμα εκ της ληνου αχρι των [χαλινων]{.greek-omitted} [χαλ[η]{.unclear}νων]{.greek-added} των ιππων απο σταδιων χιλιων εξακοσιων[14:20]{.aside}

### Chapter 15

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} αλλο [σημειον]{.greek-omitted} [σιμειον]{.greek-added} εν τω [ουρανω]{.greek-abbr} μεγα και θαυμαστον αγγελους επτα εχοντας πληγας επτα τας [εσχατας]{.greek-omitted} [εσχαστας]{.greek-added} οτι εν αυταις ετελεσθη ο θυμος του [θεου]{.greek-abbr}[15:1]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} ως θαλασσαν υαλινην μεμιγμενην πυρι και τους νικωντας εκ του θηριου και εκ της εικονος αυτου και εκ του [χαραγματος]{.greek-added} [αυτου]{.greek-added} [και]{.greek-added} [εκ]{.greek-added} [του]{.greek-added} αριθμου του ονοματος [αυτου]{.greek-omitted} εστωτας επι την θαλασσαν την υαλινην εχοντας κιθαρας του [θεου]{.greek-abbr}[15:2]{.aside}

και αδουσιν την ωδην μωυσεως του δουλου του [θεου]{.greek-abbr} και την ωδην του αρνιου λεγοντες μεγαλα και θαυμαστα τα εργα σου [κυριε]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ δικαιαι και [αληθιναι]{.greek-omitted} [αληθηναι]{.greek-added} αι οδοι σου ο βασιλευς των εθνων[15:3]{.aside}

τις ου μη φοβηθη [σε]{.greek-omitted} [κυριε]{.greek-abbr} και [δοξαση]{.greek-omitted} [δοξασοι]{.greek-added} το ονομα σου [οτι]{.greek-omitted} [μονος]{.greek-omitted} [αγιος]{.greek-omitted} [οτι]{.greek-omitted} [παντα]{.greek-omitted} [τα]{.greek-omitted} [εθνη]{.greek-omitted} [ηξουσιν]{.greek-omitted} [και]{.greek-omitted} [προσκυνησουσιν]{.greek-omitted} [ενωπιον]{.greek-omitted} [σου]{.greek-omitted} [οτι]{.greek-omitted} [τα]{.greek-omitted} [δικαιωματα]{.greek-omitted} [σου]{.greek-omitted} [εφανερωθησαν]{.greek-omitted}[15:4]{.aside}

[τις]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [φοβηθη]{.greek-omitted} [σε]{.greek-omitted} [κυριε]{.greek-omitted} [και]{.greek-omitted} [δοξαση]{.greek-omitted} [το]{.greek-omitted} [ονομα]{.greek-omitted} [σου]{.greek-omitted} οτι μονος [αγιος]{.greek-omitted} [οσιος]{.greek-added} οτι παντα τα εθνη [ηξουσιν]{.greek-omitted} [ηξουσι]{.greek-added} και προσκυνησουσιν ενωπιον σου οτι τα [δικαιωματα]{.greek-omitted} [δικαιοματα]{.greek-added} σου εφανερωθησαν[15:4 | instance no. 2]{.aside}

και [μετα]{.greek-omitted} [ταυτα]{.greek-omitted} [μεταυτα]{.greek-added} [ειδον]{.greek-omitted} [ιδον]{.greek-added} και [ηνοιγη]{.greek-omitted} [ηνοιγει]{.greek-added} ο ναος της σκηνης του μαρτυριου εν τω ουρανω[15:5]{.aside}

και εξηλθον οι επτα αγγελοι οι [εχοντες]{.greek-omitted} [εχοντας]{.greek-added} [τας]{.greek-omitted} επτα πληγας εκ του ναου [οι]{.greek-omitted} [ησαν]{.greek-omitted} ενδεδυμενοι λινον καθαρον λαμπρον [και]{.greek-omitted} περιεζωσμενοι [περι]{.greek-omitted} τα στηθη ζωνας χρυσας[15:6]{.aside}

και [εν]{.greek-omitted} εκ των τεσσαρων ζωων εδωκεν τοις επτα αγγελοις επτα [φιαλας]{.greek-omitted} [φιαλαις]{.greek-added} χρυσας γεμουσας του θυμου του [θεου]{.greek-abbr} του ζωντος εις τους αιωνας [αμην]{.greek-added} [των]{.greek-omitted} [αιωνων]{.greek-omitted}[15:7]{.aside}

και εγεμισθη ο ναος καπνου εκ της δοξης του [θεου]{.greek-abbr} και εκ της δυναμεως αυτου και ουδεις [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} εισελθειν εις τον ναον αχρι τελεσθωσιν αι επτα πληγαι των [επτα]{.greek-omitted} αγγελων[15:8]{.aside}

### Chapter 16

και ηκουσα φωνης μεγαλης εκ του ναου λεγουσης τοις επτα αγγελοις [υπαγετε]{.greek-omitted} [υπαγεται]{.greek-added} και [εκχεατε]{.greek-omitted} [εκχεεται]{.greek-added} τας επτα φιαλας του θυμου [του]{.greek-omitted} [θεου]{.greek-omitted} εις την γην[16:1]{.aside}

και απηλθεν ο πρωτος [αγγελος]{.greek-added} και εξεχεεν την φιαλην αυτου [εις]{.greek-omitted} [επι]{.greek-added} την γην και εγενετο ελκος κακον και πονηρον επι τους [ανθρωπους]{.greek-abbr} τους εχοντας το χαραγμα του θηριου και τους προσκυνουντας τη εικονι αυτου[16:2]{.aside}

και ο δευτερος αγγελος εξεχεεν την φιαλην αυτου εις την θαλασσαν και εγενετο [ως]{.greek-added} αιμα [ως]{.greek-omitted} νεκρου και πασα ψυχη ζωσα απεθανεν [τα]{.greek-added} εν τη θαλασση[16:3]{.aside}

και ο τριτος εξεχεεν την φιαλην αυτου εις τους ποταμους και εις τας πηγας των υδατων και εγενετο αιμα[16:4]{.aside}

και ηκουσα του αγγελου των υδατων λεγοντος δικαιος [ει]{.greek-omitted} ο ων και ο ην ο [ο]{.greek-added} [οσιος]{.greek-omitted} [αμγοσιος]{.greek-added} οτι ταυτα εκρινας[16:5]{.aside}

οτι αιμα [αγιων]{.greek-omitted} [ἁγίων]{.greek-added} και προφητων εξεχεαν και αιμα αυτοις εδωκας πιειν αξιοι εισιν[16:6]{.aside}

[και]{.greek-omitted} [ηκουσα]{.greek-omitted} [του]{.greek-omitted} [θυσιαστηριου]{.greek-omitted} [λεγοντος]{.greek-omitted} ναι [κυριε]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ αληθιναι και δικαιαι αι [κρισεις]{.greek-omitted} [κρισις]{.greek-added} σου[16:7]{.aside}

και ο τεταρτος αγγελος εξεχεεν την φιαλην αυτου επι τον ηλιον και [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} αυτω καυματισαι [τους]{.greek-added} [[ανθρωπους]{.greek-abbr}]{.greek-added} εν πυρι [τους]{.greek-omitted} [ανθρωπους]{.greek-omitted}[16:8]{.aside}

και εκαυματισθησαν οι [ανθρωποι]{.greek-abbr} καυμα μεγα και εβλασφημησαν [οι]{.greek-omitted} [ανθρωποι]{.greek-omitted} το ονομα του [θεου]{.greek-abbr} του εχοντος [την]{.greek-added} εξουσιαν επι τας πληγας ταυτας και ου μετενοησαν δουναι αυτω δοξαν[16:9]{.aside}

και ο [πεμπτος]{.greek-omitted} [αγγελος]{.greek-added} εξεχεεν την φιαλην αυτου επι τον θρονον του θηριου και εγενετο η [βασιλεια]{.greek-omitted} [βασιλει]{.greek-added} αυτου εσκοτωμενη και εμασωντο τας γλωσσας αυτων εκ του πονου[16:10]{.aside}

και εβλασφημησαν τον [θεον]{.greek-abbr} του [ουρανου]{.greek-abbr} εκ των πονων [αυτων]{.greek-omitted} [και]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [ελκων]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [ου]{.greek-omitted} [μετενοησαν]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [εργων]{.greek-omitted} [αυτων]{.greek-omitted}[16:11]{.aside}

[και]{.greek-omitted} [εβλασφημησαν]{.greek-omitted} [τον]{.greek-omitted} [θεον]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [πονων]{.greek-omitted} αυτων και [εκ]{.greek-omitted} των ελκων αυτων και ου μετενοησαν εκ των εργων αυτων[16:11 | instance no. 2]{.aside}

και ο εκτος [αγγελος]{.greek-added} εξεχεεν την φιαλην αυτου επι τον ποταμον τον μεγαν [τον]{.greek-added} ευφρατην και εξηρανθη το υδωρ [αυτου]{.greek-omitted} ινα ετοιμασθη η οδος των βασιλεων των απο ανατολης ηλιου[16:12]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} εκ του στοματος του δρακοντος και εκ του στοματος του θηριου και εκ του στοματος του ψευδοπροφητου πνευματα [τρια]{.greek-added} ακαθαρτα [τρια]{.greek-omitted} [ως]{.greek-omitted} [βατραχοι]{.greek-omitted}[16:13]{.aside}

εισιν γαρ [πνευματα]{.greek-abbr} [δαιμονιων]{.greek-omitted} [δαιμονων]{.greek-added} ποιουντα [σημεια]{.greek-omitted} [σιμεια]{.greek-added} [α]{.greek-omitted} [εκπορευεται]{.greek-omitted} [εκπορευεσθαι]{.greek-added} επι τους βασιλεις της οικουμενης ολης συναγαγειν αυτους εις [τον]{.greek-omitted} πολεμον [της]{.greek-omitted} [ημερας]{.greek-omitted} [εκεινης]{.greek-omitted} της μεγαλης του [θεου]{.greek-abbr} [του]{.greek-omitted} [παντοκρατορος]{.greek-omitted} [παντοκρατωρος]{.greek-added}[16:14]{.aside}

ιδου ερχομαι ως κλεπτης μακαριος ο γρηγορων και τηρων τα ιματια αυτου [[εαυτου]{.corr}]{.greek-added} ινα μη γυμνος [περιπατη]{.greek-omitted} [περιπατει]{.greek-added} και [βλεπωσιν]{.greek-omitted} [βλεπουσιν]{.greek-added} την [ασχημοσυνην]{.greek-omitted} [ασχημωσυνην]{.greek-added} αυτου[16:15]{.aside}

και συνηγαγεν αυτους εις τον τοπον τον καλουμενον [εβραιστι]{.greek-omitted} [εβραιστη]{.greek-added} [αρμαγεδων]{.greek-omitted} [ἀρμαγεδών]{.greek-added}[16:16]{.aside}

και ο εβδομος [αγγελος]{.greek-added} εξεχεεν την φιαλην αυτου [επι]{.greek-omitted} [εις]{.greek-added} τον αερα και εξηλθεν φωνη [εκ]{.greek-added} [μεγαλη]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [ναου]{.greek-omitted} του [ουρανου]{.greek-abbr} απο του θρονου λεγουσα γεγονεν[16:17]{.aside}

και εγενοντο αστραπαι και βρονται και [φωναι]{.greek-omitted} [και]{.greek-omitted} σεισμος [εγενετο]{.greek-added} μεγας οιος ουκ εγενετο αφ ου [οι]{.greek-omitted} [ανθρωποι]{.greek-abbr} εγενοντο επι της γης [τηλικουτος]{.greek-omitted} [τιλικουτος]{.greek-added} σεισμος [ουτως]{.greek-omitted} [ουτος]{.greek-added} μεγας[16:18]{.aside}

και εγενετο η πολις η μεγαλη εις τρια μερη και αι πολεις των εθνων [επεσον]{.greek-omitted} [επεσαν]{.greek-added} και βαβυλων η μεγαλη εμνησθη ενωπιον του [θεου]{.greek-abbr} δουναι αυτη το ποτηριον του οινου του θυμου της οργης αυτου[16:19]{.aside}

και χαλαζα μεγαλη ως ταλαντιαια καταβαινει εκ του [ουρανου]{.greek-abbr} επι τους [ανθρωπους]{.greek-abbr} και εβλασφημησαν οι [ανθρωποι]{.greek-abbr} τον [θεον]{.greek-abbr} εκ της πληγης της χαλαζης οτι μεγαλη εστιν η πληγη [αυτης]{.greek-omitted} [αυτου]{.greek-added} σφοδρα[16:21]{.aside}

### Chapter 17

και ηλθεν εις εκ των επτα αγγελων [των]{.greek-omitted} [τω]{.greek-added} εχοντων τας επτα φιαλας και ελαλησεν μετ εμου λεγων [μοι]{.greek-added} [δευρο]{.greek-omitted} [δευρω]{.greek-added} δειξω σοι το κριμα της πορνης της μεγαλης της καθημενης επι [των]{.greek-omitted} υδατων [των]{.greek-omitted} πολλων[17:1]{.aside}

μεθ ης επορνευσαν οι βασιλεις [της]{.greek-omitted} [γης]{.greek-omitted} και εμεθυσθησαν οι κατοικουντες την γην εκ του οινου της πορνειας αυτης[17:2]{.aside}

και [απηνεγκεν]{.greek-omitted} [απηνενκεν]{.greek-added} με εις ερημον εν [πνευματι]{.greek-abbr} και [ειδον]{.greek-omitted} [ιδον]{.greek-added} γυναικα καθημενην επι θηριον κοκκινον γεμον [ονοματα]{.greek-omitted} [ονοματων]{.greek-added} βλασφημιας εχον κεφαλας επτα και κερατα δεκα[17:3]{.aside}

και η γυνη [ην]{.greek-omitted} [ἡν]{.greek-added} περιβεβλημενη [πορφυρουν]{.greek-omitted} [πορφυραν]{.greek-added} [και]{.greek-added} και κοκκινον [και]{.greek-added} [κεχρυσωμενη]{.greek-omitted} [χρυσομενη]{.greek-added} [χρυσιω]{.greek-omitted} [χρυσω]{.greek-added} και λιθω τιμιω και μαργαριταις [διο]{.greek-added} [λιθω]{.greek-added} [τιμιω]{.greek-added} [και]{.greek-added} [μαργαριταις]{.greek-added} [κεκοσμηται]{.greek-added} εχουσα [χρυσουν]{.greek-added} ποτηριον [χρυσουν]{.greek-omitted} εν τη χειρι αυτης γεμον [βδελυγματων]{.greek-omitted} [βδελλυγματων]{.greek-added} και τα ακαθαρτα της [πονη]{.greek-added} [πορνειας]{.greek-omitted} [αυτης]{.greek-omitted}[17:4]{.aside}

[ριας]{.greek-added} [και]{.greek-omitted} [η]{.greek-omitted} [γυνη]{.greek-omitted} [ην]{.greek-omitted} [περιβεβλημενη]{.greek-omitted} [πορφυρουν]{.greek-omitted} [και]{.greek-omitted} [κοκκινον]{.greek-omitted} [κεχρυσωμενη]{.greek-omitted} [χρυσιω]{.greek-omitted} [και]{.greek-omitted} [λιθω]{.greek-omitted} [τιμιω]{.greek-omitted} [και]{.greek-omitted} [μαργαριταις]{.greek-omitted} [εχουσα]{.greek-omitted} [ποτηριον]{.greek-omitted} [χρυσουν]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [χειρι]{.greek-omitted} αυτης [γεμον]{.greek-omitted} [βδελυγματων]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} [ακαθαρτα]{.greek-omitted} [της]{.greek-omitted} [πορνειας]{.greek-omitted} [αυτης]{.greek-omitted}[17:4 | instance no. 2]{.aside}

και επι το [μετωπον]{.greek-omitted} [μετοπον]{.greek-added} αυτης ονομα γεγραμμενον μυστηριον βαβυλων η μεγαλη η [μητηρ]{.greek-abbr} των [πορνων]{.greek-omitted} [πόρνων]{.greek-added} και των [βδελυγματων]{.greek-omitted} [βδελλυγματων]{.greek-added} της γης[17:5]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} την γυναικα μεθυουσαν εκ του αιματος των αγιων [και]{.greek-added} εκ του αιματος των μαρτυρων [ιησου]{.greek-omitted} και εθαυμασα [ιδων]{.greek-omitted} [ιδον]{.greek-added} αυτην θαυμα μεγα[17:6]{.aside}

και ειπεν μοι ο αγγελος δια τι εθαυμασας εγω [συ]{.greek-added} ερω [σοι]{.greek-omitted} το μυστηριον της γυναικος και του θηριου του [βασταζοντος]{.greek-omitted} [βαστοζοντος]{.greek-added} αυτην του εχοντος [τας]{.greek-omitted} επτα κεφαλας και τα δεκα κερατα[17:7]{.aside}

το θηριον ο [ειδες]{.greek-omitted} [ιδες]{.greek-added} ην και ουκ εστιν και μελλει αναβαινειν εκ της αβυσσου και εις [απωλειαν]{.greek-omitted} [απολειαν]{.greek-added} υπαγειν και θαυμασονται οι κατοικουντες επι της γης ων ου γεγραπται τα ονοματα [αυτων]{.greek-added} επι το βιβλιον της ζωης απο καταβολης κοσμου βλεποντων [το]{.greek-added} [θηριον]{.greek-added} οτι ην [το]{.greek-omitted} [θηριον]{.greek-omitted} και ουκ εστιν και [παρεσται]{.greek-omitted} [παρεστιν]{.greek-added}[17:8]{.aside}

και τα δεκα κερατα α [ειδες]{.greek-omitted} [ιδες]{.greek-added} και το θηριον ουτοι [μισησουσιν]{.greek-omitted} [μησισουσιν]{.greek-added} την πορνην και [ηρημωμενην]{.greek-omitted} [ερημωμενην]{.greek-added} [ποιησουσιν]{.greek-omitted} [αυτην]{.greek-omitted} [και]{.greek-omitted} [γυμνην]{.greek-omitted} ποιησουσιν αυτην και τας σαρκας αυτης φαγονται και αυτην [κατακαυσουσιν]{.greek-omitted} [καυσωσιν]{.greek-added} εν πυρι[17:16]{.aside}

ο γαρ [θεος]{.greek-abbr} εδωκεν εις τας καρδιας αυτων ποιησαι την γνωμην αυτου και ποιησαι [μιαν]{.greek-added} γνωμην [μιαν]{.greek-omitted} και δουναι την βασιλειαν [αυτων]{.greek-omitted} [αυτου]{.greek-added} τω θηριω αχρι [τελεσθωσιν]{.greek-omitted} [τελεσθησονται]{.greek-added} οι λογοι του [θεου]{.greek-abbr}[17:17]{.aside}

και η γυνη ην [ειδες]{.greek-omitted} [ιδες]{.greek-added} εστιν η πολις η μεγαλη η εχουσα βασιλειαν επι των βασιλεων της γης[17:18]{.aside}

### Chapter 18

[και]{.greek-added} μετα ταυτα [ειδον]{.greek-omitted} [ιδον]{.greek-added} αλλον [αγγελον]{.greek-omitted} καταβαινοντα εκ του [ουρανου]{.greek-abbr} εχοντα εξουσιαν μεγαλην και η γη εφωτισθη εκ της δοξης αυτου[18:1]{.aside}

και εκραξεν [εν]{.greek-added} ισχυρα φωνη [μεγαλη]{.greek-added} λεγων [επεσεν]{.greek-added} επεσεν βαβυλων η μεγαλη και εγενετο κατοικητηριον δαιμονων και φυλακη παντος [πνευματος]{.greek-abbr} ακαθαρτου και [φυλακη]{.greek-omitted} [παντος]{.greek-omitted} [ορνεου]{.greek-omitted} [ακαθαρτου]{.greek-omitted} [και]{.greek-omitted} [μεμισημενου]{.greek-omitted} [μεμισειμενου]{.greek-added}[18:2]{.aside}

οτι εκ του [θυμου]{.greek-added} [του]{.greek-added} οινου [του]{.greek-omitted} [θυμου]{.greek-omitted} της πορνειας αυτης [πεπτωκασιν]{.greek-omitted} [πεπωκε]{.greek-added} παντα τα εθνη και οι βασιλεις της γης μετ αυτης επορνευσαν και οι εμποροι της γης εκ της δυναμεως του [στρηνους]{.greek-omitted} [στρινους]{.greek-added} αυτης επλουτησαν[18:3]{.aside}

και ηκουσα αλλην φωνην εκ του [ουρανου]{.greek-abbr} λεγουσαν εξελθε [εξ]{.greek-omitted} [αυτης]{.greek-omitted} ο λαος μου [εξ]{.greek-added} [αυτης]{.greek-added} ινα μη [συγκοινωνησητε]{.greek-omitted} [συνκοινωνησειται]{.greek-added} ταις αμαρτιαις αυτης [και]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [πληγων]{.greek-omitted} [αυτης]{.greek-omitted} ινα μη [λαβητε]{.greek-omitted} [λαβειται]{.greek-added}[18:4]{.aside}

οτι [εκολληθησαν]{.greek-omitted} [εκολλυθησαν]{.greek-added} αυτης αι αμαρτιαι αχρι του [ουρανου]{.greek-abbr} και [ε]{.greek-added} [εμνημονευσεν]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [τα]{.greek-omitted} [αδικηματα]{.greek-omitted} [αυτης]{.greek-omitted}[18:5]{.aside}

[οτι]{.greek-omitted} [εκολληθησαν]{.greek-omitted} [αυτης]{.greek-omitted} [αι]{.greek-omitted} [αμαρτιαι]{.greek-omitted} [αχρι]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [και]{.greek-omitted} [εμνημονευσεν]{.greek-omitted} [μνημονευσεν]{.greek-added} ο [θεος]{.greek-abbr} τα αδικηματα αυτης[18:5 | instance no. 2]{.aside}

[αποδοτε]{.greek-omitted} [αποδωτε]{.greek-added} αυτη ως και αυτη απεδωκεν [υμιν]{.greek-added} και διπλωσατε αυτη διπλα κατα τα εργα αυτης εν τω ποτηριω ω εκερασεν κερασατε αυτη διπλουν[18:6]{.aside}

οσα εδοξασεν αυτην και [εστρηνιασεν]{.greek-omitted} [εστρινιασεν]{.greek-added} τοσουτον δοτε αυτη βασανισμον και [πενθος]{.greek-omitted} [οτι]{.greek-omitted} εν τη καρδια αυτης λεγει [οτι]{.greek-omitted} [καθημαι]{.greek-omitted} [καθημοι]{.greek-added} [βασιλισσα]{.greek-omitted} [βασιλεισσα]{.greek-added} και χηρα ουκ ειμι και πενθος ου μη ιδω[18:7]{.aside}

δια τουτο εν μια ημερα ηξουσιν αι πληγαι αυτης θανατος και πενθος και λιμος και εν πυρι κατακαυθησεται οτι ισχυρος [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο κρινας αυτην[18:8]{.aside}

και [κλαυσουσιν]{.greek-omitted} [κλαυσονται]{.greek-added} [αυτην]{.greek-added} και κοψονται επ [αυτην]{.greek-omitted} [αυτη]{.greek-added} [οι]{.greek-omitted} βασιλεις της γης οι μετ αυτης πορνευσαντες και στρηνιασαντες οταν βλεπωσιν τον καπνον της πυρωσεως αυτης[18:9]{.aside}

απο [μακροθεν]{.greek-omitted} [μακρωθεν]{.greek-added} εστηκοτες δια τον φοβον του βασανισμου αυτης λεγοντες [οι]{.greek-added} [ουαι]{.greek-omitted} [ουιαι]{.greek-added} [ουαι]{.greek-omitted} η πολις η μεγαλη βαβυλων η πολις η ισχυρα οτι μια ωρα [ηλθεν]{.greek-omitted} [ερχεται]{.greek-added} η κρισις σου[18:10]{.aside}

και οι εμποροι της γης [κλαυσουσιν]{.greek-omitted} [κλαιουσιν]{.greek-added} και [πενθησουσιν]{.greek-omitted} [πενθουσιν]{.greek-added} [επ]{.greek-omitted} [αυτη]{.greek-omitted} [εφ]{.greek-added} [εαυτους]{.greek-added} οτι τον [γομον]{.greek-omitted} [γωμον]{.greek-added} αυτων ουδεις αγοραζει ουκετι[18:11]{.aside}

[γομον]{.greek-omitted} [γωμον]{.greek-added} χρυσου και [αργυρου]{.greek-omitted} [αργυριου]{.greek-added} και λιθου τιμιου [και]{.greek-omitted} [η]{.greek-added} μαργαριτου και [βυσσινου]{.greek-omitted} [βυσσου]{.greek-added} και [πορφυρου]{.greek-omitted} [πορφυρας]{.greek-added} και [σηρικου]{.greek-omitted} [συρικου]{.greek-added} [και]{.greek-added} και κοκκινου και παν ξυλον θυινον και παν σκευος ελεφαντινον και παν σκευος εκ ξυλου [τιμιωτατου]{.greek-omitted} [τιμιου]{.greek-added} και χαλκου και σιδηρου και μαρμαρου[18:12]{.aside}

και [κιναμωμον]{.greek-omitted} [κινναμωμου]{.greek-added} [και]{.greek-added} [αμωμον]{.greek-added} και θυμιαματα και μυρον και λιβανον και οινον και [ελαιον]{.greek-omitted} [ελεον]{.greek-added} και [σεμιδαλιν]{.greek-omitted} [σεμιδαλην]{.greek-added} και σιτον και [κτινη]{.greek-added} [και]{.greek-added} προβατα [και]{.greek-omitted} [κτηνη]{.greek-omitted} και ιππων και [ραιδων]{.greek-omitted} [ρεδων]{.greek-added} και σωματων και ψυχας [ανθρωπων]{.greek-abbr}[18:13]{.aside}

και η οπωρα [σου]{.greek-added} της επιθυμιας της ψυχης σου απηλθεν απο σου και [παντα]{.greek-omitted} [τα]{.greek-omitted} [λιπαρα]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} [λαμπρα]{.greek-omitted} [απωλετο]{.greek-omitted} [απο]{.greek-omitted} [σου]{.greek-omitted} [και]{.greek-omitted} ουκετι [αυτα]{.greek-omitted} ου μη [ευρης]{.greek-omitted} [ευρισης]{.greek-added} [αυτα]{.greek-added}[18:14]{.aside}

οι εμποροι τουτων οι πλουτησαντες απ αυτης απο μακροθεν στησονται δια τον φοβον του βασανισμου αυτης κλαιοντες και πενθουντες[18:15]{.aside}

[και]{.greek-omitted} [λεγοντες]{.greek-omitted} ουαι ουαι η πολις η μεγαλη η περιβεβλημενη βυσσινον και [πορφυρουν]{.greek-omitted} [πορφυραν]{.greek-added} και κοκκινον [και]{.greek-omitted} κεχρυσωμενη [εν]{.greek-added} [χρυσιω]{.greek-omitted} [χρυσω]{.greek-added} και λιθω τιμιω και μαργαριταις[18:16]{.aside}

οτι μια ωρα [ηρημωθη]{.greek-omitted} [ερημωθη]{.greek-added} ο τοσουτος πλουτος και πας [κυβερνητης]{.greek-omitted} [κυβερνιτης]{.greek-added} και πας [ο]{.greek-omitted} επι [τοπον]{.greek-omitted} [των]{.greek-added} [πλοιων]{.greek-added} πλεων και ναυται και οσοι την θαλασσαν εργαζονται απο μακροθεν εστησαν[18:17]{.aside}

και [εκραζον]{.greek-omitted} [εκροζον]{.greek-added} βλεποντες τον καπνον της πυρωσεως αυτης λεγοντες τις ομοια τη πολει τη μεγαλη[18:18]{.aside}

και εβαλον χουν [επι]{.greek-omitted} [τας]{.greek-omitted} [κεφαλας]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [εκραζον]{.greek-omitted} [κλαιοντες]{.greek-omitted} [και]{.greek-omitted} [πενθουντες]{.greek-omitted} [και]{.greek-omitted} [λεγοντες]{.greek-omitted} [ουαι]{.greek-omitted} [ουαι]{.greek-omitted} [η]{.greek-omitted} [πολις]{.greek-omitted} [η]{.greek-omitted} [μεγαλη]{.greek-omitted} [εν]{.greek-omitted} [η]{.greek-omitted} [επλουτησαν]{.greek-omitted} [παντες]{.greek-omitted} [οι]{.greek-omitted} [εχοντες]{.greek-omitted} [τα]{.greek-omitted} [πλοια]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [θαλασση]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [τιμιοτητος]{.greek-omitted} [αυτης]{.greek-omitted} [οτι]{.greek-omitted} [μια]{.greek-omitted} [ωρα]{.greek-omitted} [ηρημωθη]{.greek-omitted}[18:19]{.aside}

[και]{.greek-omitted} [εβαλον]{.greek-omitted} [χουν]{.greek-omitted} επι τας κεφαλας αυτων και εκραζον [κλαιοντες]{.greek-omitted} [κλεοντες]{.greek-added} και πενθουντες και λεγοντες ουαι ουαι η [πολις]{.greek-omitted} [πολεις]{.greek-added} η μεγαλη εν η επλουτησαν παντες οι εχοντες τα πλοια εν τη θαλασση εκ της [τιμιοτητος]{.greek-omitted} [τιμιωτητος]{.greek-added} αυτης οτι μια ωρα [ηρημωθη]{.greek-omitted} [ερημωθη]{.greek-added}[18:19 | instance no. 2]{.aside}

ευφραινου επ αυτη [ουρανε]{.greek-abbr} και οι αγιοι και οι αποστολοι και οι προφηται οτι εκρινεν ο [θεος]{.greek-abbr} το κριμα υμων εξ αυτης[18:20]{.aside}

και ηρεν εις αγγελος ισχυρος λιθον ως μυλον μεγαν και εβαλεν εις την θαλασσαν λεγων ουτως ορμηματι βληθησεται βαβυλων η μεγαλη [πολις]{.greek-omitted} [πολεις]{.greek-added} και ου μη ευρεθη ετι[18:21]{.aside}

και φωνη [κιθαρωδων]{.greek-omitted} [κιθαραδων]{.greek-added} και μουσικων και αυλητων και σαλπιστων ου μη [εις]{.greek-added} ακουσθη εν σοι ετι και πας τεχνιτης πασης [τηνης]{.greek-added} [τεχνης]{.corr} [ου]{.greek-omitted} [ο]{.greek-added} μη [ευρεθη]{.greek-omitted} [ευρεθει]{.greek-added} εν σοι ετι και φωνη [κιθαρωδων]{.greek-added} μυλου ου μη ακουσθη εν σοι ετι[18:22]{.aside}

[και]{.greek-omitted} [φως]{.greek-omitted} [λυχνου]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [φανη]{.greek-omitted} [εν]{.greek-omitted} [σοι]{.greek-omitted} [ετι]{.greek-omitted} [και]{.greek-omitted} [φωνη]{.greek-omitted} [νυμφιου]{.greek-omitted} [και]{.greek-omitted} [νυμφης]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [ακουσθη]{.greek-omitted} [εν]{.greek-omitted} [σοι]{.greek-omitted} [ετι]{.greek-omitted} οτι οι εμποροι σου ησαν οι μεγιστανες της γης οτι εν τη [φαρμακεια]{.greek-omitted} [φαρμακια]{.greek-added} σου επλανηθησαν παντα τα εθνη[18:23]{.aside}

και εν αυτη αιματα προφητων και αγιων [ευρεθη]{.greek-omitted} [ηυρεθη]{.greek-added} και παντων των εσφαγμενων επι της γης[18:24]{.aside}

### Chapter 19

[και]{.greek-added} μετα ταυτα ηκουσα [ως]{.greek-omitted} φωνην [μεγαλην]{.greek-omitted} οχλου πολλου εν τω [ουρανω]{.greek-abbr} λεγοντων [αλληλουια]{.greek-omitted} [αλληλούια]{.greek-added} η [σωτηρια]{.greek-abbr} και η [δυναμις]{.greek-omitted} [δοξα]{.greek-added} και η [δοξα]{.greek-omitted} [τιμη]{.greek-added} [και]{.greek-added} [η]{.greek-added} [δυναμις]{.greek-added} του [θεου]{.greek-abbr} ημων[19:1]{.aside}

οτι αληθιναι και δικαιαι αι [κρισεις]{.greek-omitted} [κρισις]{.greek-added} αυτου οτι εκρινεν την πορνην την μεγαλην ητις [διεφθειρεν]{.greek-omitted} [εφθηρεν]{.greek-added} την γην εν τη [πορνεια]{.greek-omitted} [πορνια]{.greek-added} αυτης και εξεδικησεν το αιμα των δουλων αυτου εκ [της]{.greek-added} χειρος αυτης[19:2]{.aside}

και δευτερον [ειρηκεν]{.greek-omitted} [ειρηκαν]{.greek-added} [αλληλουια]{.greek-omitted} [αλλιλουια]{.greek-added} και ο καπνος [αυτης]{.greek-omitted} αναβαινει εις τους αιωνας των αιωνων [αμην]{.greek-added}[19:3]{.aside}

και [επεσον]{.greek-omitted} [επεσαν]{.greek-added} οι πρεσβυτεροι οι εικοσι [τεσσαρες]{.greek-omitted} [τεσσαρις]{.greek-added} και τα τεσσαρα ζωα και προσεκυνησαν τω [θεω]{.greek-abbr} τω καθημενω επι του θρονου λεγοντες αμην αλληλουια[19:4]{.aside}

και φωνη [απο]{.greek-omitted} [εκ]{.greek-added} του θρονου εξηλθεν [λεγουσα]{.greek-omitted} [αινειτε]{.greek-omitted} [αινειται]{.greek-added} [τον]{.greek-omitted} [θεον]{.greek-omitted} [τω]{.greek-added} [[θεω]{.greek-abbr}]{.greek-added} ημων [παντες]{.greek-omitted} οι δουλοι αυτου και οι [φοβουμενοι]{.greek-omitted} [φοβουμεν]{.greek-added} [αυτον]{.greek-omitted} [και]{.greek-added} οι μικροι και οι μεγαλοι[19:5]{.aside}

και ηκουσα ως φωνην οχλου πολλου και ως φωνην υδατων πολλων και ως [φωνην]{.greek-omitted} [φωνων]{.greek-added} βροντων ισχυρων [λεγοντες]{.greek-omitted} [λεγοντας]{.greek-added} [αλληλουια]{.greek-omitted} [αλλιλουια]{.greek-added} οτι εβασιλευσεν [κυριος]{.greek-omitted} ο [θεος]{.greek-abbr} ημων ο παντοκρατωρ[19:6]{.aside}

χαιρωμεν και [αγαλλιωμεθα]{.greek-omitted} [αγαλλιωμεν]{.greek-added} και [δωμεν]{.greek-omitted} [δωσωμεν]{.greek-added} την δοξαν [αυτω]{.greek-omitted} [αυτου]{.greek-added} οτι ηλθεν ο γαμος του αρνιου και η γυνη αυτου [ητοιμασεν]{.greek-omitted} [ετοιμασεν]{.greek-added} εαυτην[19:7]{.aside}

και [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} [αυτη]{.greek-omitted} [αυτην]{.greek-added} ινα [περιβαληται]{.greek-omitted} [περιβαλλειται]{.greek-added} βυσσινον [καθαρον]{.greek-added} λαμπρον [και]{.greek-omitted} [καθαρον]{.greek-omitted} [το]{.greek-added} [γαρ]{.greek-added} [βυσσινον]{.greek-added} το γαρ βυσσινον τα δικαιωματα των αγιων εστιν[19:8]{.aside}

[και]{.greek-omitted} [λεγει]{.greek-omitted} [μοι]{.greek-omitted} [γραψον]{.greek-omitted} [μακαριοι]{.greek-omitted} [οι]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [δειπνον]{.greek-omitted} [του]{.greek-omitted} [γαμου]{.greek-omitted} [του]{.greek-omitted} [αρνιου]{.greek-omitted} [κεκλημενοι]{.greek-omitted} και λεγει μοι ουτοι οι λογοι [αληθινοι]{.greek-omitted} [αληθηνοι]{.greek-added} [εισιν]{.greek-added} του [θεου]{.greek-abbr} [εισιν]{.greek-omitted}[19:9]{.aside}

και επεσα εμπροσθεν [των]{.greek-omitted} [ποδων]{.greek-omitted} αυτου προσκυνησαι αυτω και λεγει μοι ορα μη συνδουλος σου [ειμι]{.greek-omitted} [ημι]{.greek-added} και [των]{.greek-omitted} [αδελφων]{.greek-omitted} [σου]{.greek-omitted} [των]{.greek-omitted} [εχοντων]{.greek-omitted} [την]{.greek-omitted} [μαρτυριαν]{.greek-omitted} [ιησου]{.greek-omitted} [τω]{.greek-omitted} [θεω]{.greek-omitted} [προσκυνησον]{.greek-omitted} [η]{.greek-omitted} [γαρ]{.greek-omitted} [μαρτυρια]{.greek-omitted} [του]{.greek-omitted} [ιησου]{.greek-omitted} [εστιν]{.greek-omitted} [το]{.greek-omitted} [πνευμα]{.greek-omitted} [της]{.greek-omitted} [προφητειας]{.greek-omitted}[19:10]{.aside}

[και]{.greek-omitted} [επεσα]{.greek-omitted} [εμπροσθεν]{.greek-omitted} [των]{.greek-omitted} [ποδων]{.greek-omitted} [αυτου]{.greek-omitted} [προσκυνησαι]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [λεγει]{.greek-omitted} [μοι]{.greek-omitted} [ορα]{.greek-omitted} [μη]{.greek-omitted} [συνδουλος]{.greek-omitted} [σου]{.greek-omitted} [ειμι]{.greek-omitted} [και]{.greek-omitted} των αδελφων σου [και]{.greek-added} των εχοντων την μαρτυριαν [ιησου]{.greek-abbr} τω [θεω]{.greek-abbr} προσκυνησον [η]{.greek-omitted} [γαρ]{.greek-omitted} [μαρτυρια]{.greek-omitted} [του]{.greek-omitted} [ιησου]{.greek-omitted} [εστιν]{.greek-omitted} [το]{.greek-omitted} [πνευμα]{.greek-omitted} [της]{.greek-omitted} [προφητειας]{.greek-omitted}[19:10 | instance no. 2]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} τον [ουρανον]{.greek-abbr} ανεωγμενον και ιδου ιππος λευκος και ο καθημενος επ αυτον [καλουμενος]{.greek-omitted} πιστος και αληθινος και εν δικαιοσυνη κρινει και πολεμει[19:11]{.aside}

οι δε οφθαλμοι αυτου φλοξ πυρος και επι την κεφαλην αυτου διαδηματα πολλα εχων [ονοματα]{.greek-omitted} [γεγραμμενα]{.greek-omitted} [και]{.greek-omitted} ονομα γεγραμμενον ο ουδεις [οιδεν]{.greek-omitted} [ιδεν]{.greek-added} ει μη αυτος[19:12]{.aside}

και περιβεβλημενος ιματιον βεβαμμενον αιματι και καλειται το ονομα αυτου ο λογος του [θεου]{.greek-abbr}[19:13]{.aside}

και τα στρατευματα τα εν τω [ουρανω]{.greek-abbr} [ηκολουθει]{.greek-omitted} [ηκολουλων]{.greek-added} αυτω [επι]{.greek-omitted} [εφ]{.greek-added} [ιπποις]{.greek-omitted} [ιπποι]{.greek-added} [λευκοις]{.greek-omitted} [πολλοι]{.greek-added} ενδεδυμενοι [βυσσινον]{.greek-omitted} [βυσσον]{.greek-added} λευκον καθαρον[19:14]{.aside}

και εκ του στοματος αυτου εκπορευεται ρομφαια [διστομος]{.greek-omitted} οξεια ινα εν αυτη παταξη τα εθνη και αυτος ποιμανει αυτους εν [ραβδω]{.greek-omitted} [ρομφαια]{.greek-added} σιδηρα και αυτος πατει την [ληνον]{.greek-omitted} [λινον]{.greek-added} του οινου του θυμου [και]{.greek-added} της οργης του [θεου]{.greek-abbr} του [παντοκρατορος]{.greek-omitted} [παντωκρατωρος]{.greek-added}[19:15]{.aside}

και εχει επι το ιματιον [αυτου]{.greek-added} και [επι]{.greek-omitted} τον μηρον [αυτου]{.greek-omitted} ονομα γεγραμμενον βασιλευς βασιλεων και κυριος κυριων[19:16]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} [ενα]{.greek-added} αγγελον εστωτα εν τω ηλιω και εκραξεν [εν]{.greek-added} φωνη μεγαλη [λεγων]{.greek-omitted} πασιν τοις ορνεοις τοις πετομενοις εν [μεσουρανηματι]{.greek-omitted} [μεσουρανημασι]{.greek-added} [δευτε]{.greek-omitted} [συναχθητε]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [δειπνον]{.greek-omitted} [το]{.greek-omitted} [μεγα]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted}[19:17]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} το θηριον και τους βασιλεις της γης και τα στρατευματα αυτων συνηγμενα ποιησαι [τον]{.greek-added} πολεμον μετα του καθημενου επι του ιππου και μετα του [στρατευματος]{.greek-omitted} [στρατευμα]{.greek-added} αυτου[19:19]{.aside}

και επιασθη το θηριον και [μετα]{.greek-added} [τουτου]{.greek-added} ο [μετ]{.greek-omitted} [αυτου]{.greek-omitted} ψευδοπροφητης ο ποιησας τα [σημεια]{.greek-omitted} [σιμεια]{.greek-added} ενωπιον αυτου εν οις επλανησεν τους λαβοντας το χαραγμα του θηριου και τους προσκυνουντας τη εικονι αυτου ζωντες [εβληθησαν]{.greek-omitted} [βληθησονται]{.greek-added} οι δυο εις την λιμνην του πυρος την καιομενην εν θειω[19:20]{.aside}

και οι λοιποι απεκτανθησαν εν τη ρομφαια του καθημενου επι του ιππου τη εξελθουση εκ του στοματος αυτου και παντα [τα]{.greek-omitted} [ορνεα]{.greek-omitted} εχορτασθησαν εκ των σαρκων αυτων[19:21]{.aside}

### Chapter 20

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} αγγελον καταβαινοντα εκ του [ουρανου]{.greek-abbr} εχοντα την [κλειν]{.greek-omitted} [κλην]{.greek-added} της αβυσσου και αλυσιν μεγαλην επι την χειρα αυτου[20:1]{.aside}

και εκρατησεν [την]{.greek-added} [χειρω]{.greek-added} τον δρακοντα τον οφιν τον αρχαιον ος [εστιν]{.greek-omitted} [ετι]{.greek-added} διαβολος και [ο]{.greek-omitted} σατανας [ο]{.greek-omitted} [πλανων]{.greek-omitted} [την]{.greek-omitted} [οικουμενην]{.greek-omitted} [ολην]{.greek-omitted} και εδησεν αυτον χιλια ετη[20:2]{.aside}

και εβαλεν αυτον εις την αβυσσον και [εκλεισεν]{.greek-omitted} [εδησεν]{.greek-added} και εσφραγισεν επανω αυτου ινα μη [πλανησει]{.greek-added} [πλανα]{.greek-omitted} [ετι]{.greek-omitted} τα εθνη αχρι τελεσθη [τα]{.greek-omitted} χιλια ετη και μετα ταυτα δει αυτον λυθηναι [μικρον]{.greek-omitted} [μικρου]{.greek-added} [χρονον]{.greek-omitted} [χρονου]{.greek-added}[20:3]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} θρονους και [εκαθισαν]{.greek-omitted} [εκαθησαν]{.greek-added} επ αυτους και κριμα [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} αυτοις και τας ψυχας των [πεπελεκισμενων]{.greek-omitted} [[πε]{.unclear}πελεκησμενων]{.greek-added} δια την μαρτυριαν [ιησου]{.greek-abbr} και δια τον λογον του [θεου]{.greek-abbr} και οιτινες ου προσεκυνησαν [το]{.greek-omitted} [θηριον]{.greek-omitted} [τω]{.greek-added} [θηριω]{.greek-added} [ουδε]{.greek-omitted} [ουτε]{.greek-added} [την]{.greek-omitted} [τη]{.greek-added} [εικονα]{.greek-omitted} [εικονι]{.greek-added} αυτου και ουκ ελαβον το χαραγμα επι το [πων]{.greek-added} [[μετοπων]{.corr}]{.greek-added} [μετωπον]{.greek-omitted} [και]{.greek-omitted} [επι]{.greek-omitted} [την]{.greek-omitted} [χειρα]{.greek-omitted} αυτων και εζησαν και εβασιλευσαν μετα [του]{.greek-omitted} [χριστου]{.greek-abbr} [τα]{.greek-omitted} χιλια ετη[20:4]{.aside}

και οι λοιποι των νεκρων ουκ εζησαν αχρι τελεσθη τα χιλια ετη αυτη η αναστασις η πρωτη[20:5]{.aside}

μακαριος και αγιος ο [εχων]{.greek-omitted} [εχον]{.greek-added} μερος εν τη αναστασει τη πρωτη επι τουτων ο [θανατος]{.greek-added} [ο]{.greek-added} δευτερος [θανατος]{.greek-omitted} ουκ εχει εξουσιαν αλλ εσονται ιερεις του [θεου]{.greek-abbr} και του [χριστου]{.greek-abbr} και [βασιλευσουσιν]{.greek-omitted} [βασιλευσωσι]{.greek-added} μετ αυτου [τα]{.greek-added} χιλια ετη[20:6]{.aside}

και [οταν]{.greek-omitted} [οτε]{.greek-added} τελεσθη τα χιλια ετη [λυθησεται]{.greek-omitted} [λυθη]{.greek-added} ο σατανας εκ της φυλακης αυτου[20:7]{.aside}

και εξελευσεται πλανησαι τα εθνη [τα]{.greek-omitted} εν ταις τεσσαρσιν γωνιαις της γης [τον]{.greek-omitted} [των]{.greek-added} γωγ και [τον]{.greek-omitted} [μαγωγ]{.greek-omitted} [μαγων]{.greek-added} [[μαγογ]{.corr}]{.greek-added} [συναγαγειν]{.greek-omitted} [συναγαγει]{.greek-added} [αυτους]{.greek-omitted} [αυτου]{.greek-added} εις [τον]{.greek-omitted} πολεμον ων ο αριθμος ως η αμμος της θαλασσης[20:8]{.aside}

και ανεβησαν επι το πλατος της γης και εκυκλωσαν την παρεμβολην των αγιων και την πολιν την ηγαπημενην και κατεβη πυρ [απο]{.greek-added} [[θεου]{.greek-abbr}]{.greek-added} εκ του [ουρανου]{.greek-abbr} [απο]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} και κατεφαγεν αυτους[20:9]{.aside}

και ο διαβολος ο πλανων αυτους [εβληθη]{.greek-omitted} [εβλυθη]{.greek-added} εις την λιμνην του πυρος και θειου οπου [και]{.greek-omitted} το θηριον και ο ψευδοπροφητης και βασανισθησονται ημερας και νυκτος [εις]{.greek-omitted} [τους]{.greek-omitted} [αιωνας]{.greek-omitted} [των]{.greek-omitted} [αιωνων]{.greek-omitted}[20:10]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} θρονον [λευκον]{.greek-added} μεγαν [λευκον]{.greek-omitted} και τον καθημενον επ αυτον ου απο προσωπου εφυγεν η γη και [ο]{.greek-omitted} [ουρανος]{.greek-abbr} και τοπος [ουχ]{.greek-omitted} [ουκ]{.greek-added} [ευρεθη]{.greek-omitted} [ηυρεθη]{.greek-added} αυτοις[20:11]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} τους νεκρους τους μεγαλους και τους μικρους εστωτας ενωπιον του θρονου και βιβλια ηνεωχθησαν και αλλο βιβλιον [ηνεωχθη]{.greek-omitted} [ο]{.greek-omitted} [ηνοιχθη]{.greek-added} [ου]{.greek-added} εστιν της ζωης και εκριθησαν οι νεκροι εκ των γεγραμμενων εν τοις βιβλιοις κατα τα εργα αυτων[20:12]{.aside}

και εδωκεν η θαλασσα τους [νεκρους]{.greek-omitted} [τους]{.greek-omitted} εν αυτη [και]{.greek-omitted} [ο]{.greek-omitted} [θανατος]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [αδης]{.greek-omitted} [εδωκαν]{.greek-omitted} [τους]{.greek-omitted} νεκρους [τους]{.greek-omitted} [εν]{.greek-omitted} [αυτοις]{.greek-omitted} [και]{.greek-omitted} [εκριθησαν]{.greek-omitted} [εκαστος]{.greek-omitted} [κατα]{.greek-omitted} [τα]{.greek-omitted} [εργα]{.greek-omitted} [αυτων]{.greek-omitted}[20:13]{.aside}

και ο θανατος και ο αδης εβληθησαν εις την λιμνην του πυρος [ουτος]{.greek-omitted} [ο]{.greek-omitted} [θανατος]{.greek-omitted} [ο]{.greek-omitted} [δευτερος]{.greek-omitted} [εστιν]{.greek-omitted} [η]{.greek-omitted} [λιμνη]{.greek-omitted} [του]{.greek-omitted} [πυρος]{.greek-omitted}[20:14]{.aside}

### Chapter 21

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} [ουρανον]{.greek-abbr} καινον και γην καινην ο γαρ πρωτος [ουρανος]{.greek-abbr} και η πρωτη γη [απηλθον]{.greek-omitted} [παρηλθεν]{.greek-added} και η [θαλασσα]{.greek-omitted} [θαλας]{.greek-added} ουκ εστιν ετι[21:1]{.aside}

και την πολιν την αγιαν [ιερουσαλημ]{.greek-abbr} καινην [ειδον]{.greek-omitted} [καταβαινουσαν]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [ητοιμασμενην]{.greek-omitted} [ως]{.greek-omitted} [νυμφην]{.greek-omitted} [κεκοσμημενην]{.greek-omitted} [τω]{.greek-omitted} [ανδρι]{.greek-omitted} [αυτης]{.greek-omitted}[21:2]{.aside}

[και]{.greek-omitted} [την]{.greek-omitted} [πολιν]{.greek-omitted} [την]{.greek-omitted} [αγιαν]{.greek-omitted} [ιερουσαλημ]{.greek-omitted} [καινην]{.greek-omitted} [ειδον]{.greek-omitted} [ιδον]{.greek-added} καταβαινουσαν [απο]{.greek-added} [του]{.greek-added} [[θεου]{.greek-abbr}]{.greek-added} εκ του [ουρανου]{.greek-abbr} [απο]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} ητοιμασμενην ως νυμφην κεκοσμημενην τω ανδρι αυτης[21:2 | instance no. 2]{.aside}

και ηκουσα φωνης μεγαλης εκ του [ουρανου]{.greek-abbr} λεγουσης [ιδου]{.greek-omitted} [ιδε]{.greek-added} η σκηνη του [θεου]{.greek-abbr} μετα τ[ω]{.unclear}ν [ανθρωπων]{.greek-omitted} [ανθροπων]{.greek-added} και σκηνωσει μετ αυτων [και]{.greek-omitted} [αυτοι]{.greek-omitted} [λαος]{.greek-omitted} [αυτου]{.greek-omitted} [εσονται]{.greek-omitted} [και]{.greek-omitted} [αυτος]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-abbr} [ων]{.greek-added} [εσται]{.greek-omitted} [μετ]{.greek-omitted} αυτων[21:3]{.aside}

και [εξαλειψει]{.greek-omitted} [εξαλιψει]{.greek-added} παν [δακρυον]{.greek-omitted} [δακρυων]{.greek-added} απο των οφθαλμων αυτων [και]{.greek-omitted} [ο]{.greek-omitted} [θανατος]{.greek-omitted} [ουκ]{.greek-omitted} [εσται]{.greek-omitted} [ετι]{.greek-omitted} [ουτε]{.greek-omitted} [πενθος]{.greek-omitted} [ουτε]{.greek-omitted} [κραυγη]{.greek-omitted} [ουτε]{.greek-omitted} [πονος]{.greek-omitted} [ουκ]{.greek-omitted} [εσται]{.greek-omitted} [ετι]{.greek-omitted} [οτι]{.greek-omitted} [τα]{.greek-omitted} [πρωτα]{.greek-omitted} [απηλθον]{.greek-omitted}[21:4]{.aside}

και ειπεν ο καθημενος επι τω [θρονω]{.greek-omitted} [θρωνω]{.greek-added} ιδου [παντα]{.greek-omitted} καινα ποιω [παντα]{.greek-added} και λεγει μοι γραψον οτι ουτοι οι λογοι αληθινοι και πιστοι εισιν[21:5]{.aside}

και ειπεν μοι [γεγονα]{.greek-omitted} [γεγωνα]{.greek-added} [εγω]{.greek-added} το [αλφα]{.greek-omitted} [ἄλφα]{.greek-added} και το [ῶ]{.greek-added} [ω]{.greek-omitted} [η]{.greek-omitted} [αρχη]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [τελος]{.greek-omitted} εγω τω διψωντι [δωσω]{.greek-omitted} [δοσω]{.greek-added} εκ της πηγης του υδατος της ζωης δωρεαν[21:6]{.aside}

τοις δε [δειλοις]{.greek-omitted} [δηλοις]{.greek-added} και απιστοις [εβδελλυγμενοις]{.greek-added} και [αμαρτωλοις]{.greek-omitted} [και]{.greek-omitted} [εβδελυγμενοις]{.greek-omitted} [και]{.greek-omitted} [φονευσιν]{.greek-omitted} [φωνευσιν]{.greek-added} και πορνοις και φαρμακοις και [ειδωλολατραις]{.greek-omitted} [ειδολολατραις]{.greek-added} και πασιν τοις [ψευδεσιν]{.greek-omitted} [ψευδουσιν]{.greek-added} το μερος αυτων εν τη λιμνη τη καιομενη πυρι και θειω ο εστιν ο [δευτερος]{.greek-added} θανατος [ο]{.greek-omitted} [δευτερος]{.greek-omitted}[21:8]{.aside}

και ηλθεν [εις]{.greek-omitted} εκ των επτα αγγελων των εχοντων τας επτα [φιαλας]{.greek-omitted} [φιφιαλας]{.greek-added} [γεμουσας]{.greek-omitted} [των]{.greek-added} [γεμοντων]{.greek-added} των επτα πληγων των εσχατων και ελαλησεν μετ εμου λεγων δευρο δειξω σοι την [γυναικα]{.greek-omitted} [την]{.greek-omitted} νυμφην του αρνιου [την]{.greek-added} [γυναικα]{.greek-added}[21:9]{.aside}

και απηνεγκεν με εν [πνευματι]{.greek-abbr} επ ορος μεγα [και]{.greek-omitted} [υψηλον]{.greek-omitted} [υψιλον]{.greek-added} και εδειξεν μοι την πολιν την μεγαλην [την]{.greek-omitted} [και]{.greek-added} αγιαν [ιερουσαλημ]{.greek-omitted} [[ισραηλ]{.greek-abbr}]{.greek-added} καταβαινουσαν εκ του [ουρανου]{.greek-abbr} απο του [θεου]{.greek-abbr}[21:10]{.aside}

[εχου]{.greek-supplied}σαν την δοξαν του [θεου]{.greek-abbr} ο φωστηρ αυτης ομοιος [λι]{.greek-supplied}θω τιμιωτατω [ως]{.greek-omitted} [λιθω]{.greek-omitted} ιασπιδι κρυσταλλιζοντι[21:11]{.aside}

εχουσα τειχος μεγα κα[ι]{.greek-supplied} [υψηλον]{.greek-omitted} [[υ]{.greek-supplied}ψιλον]{.greek-added} εχουσα πυλωνας δωδεκα και επι τοις [πυλωσιν]{.greek-omitted} [πυλεωσιν]{.greek-added} αγγελους δωδεκα και ονοματα επιγεγραμμενα α εστιν [ονοματα]{.greek-omitted} των δωδεκα φυλων των [υιων]{.greek-omitted} [ισραηλ]{.greek-abbr}[21:12]{.aside}

απο [ανατολων]{.greek-omitted} [ανατολης]{.greek-added} πυλωνες τρεις [και]{.greek-omitted} απο βορρα [πυλωνες]{.greek-omitted} [πυλωναις]{.greek-added} τρεις [και]{.greek-omitted} απο [νοτου]{.greek-omitted} [νωτου]{.greek-added} [πυλωνες]{.greek-omitted} [πυλωναις]{.greek-added} τρεις [και]{.greek-omitted} απο δυσμων [πυλωνες]{.greek-omitted} [πυλωναι]{.greek-added} τρεις[21:13]{.aside}

και το τειχος της πολεως [εχον]{.greek-omitted} [εχων]{.greek-added} θεμελιους δωδεκα και επ αυτων δωδεκα ονοματα των δωδεκα αποστολων του αρνιου[21:14]{.aside}

και ο λαλων μετ εμου ειχεν [μετρον]{.greek-omitted} καλαμον χρυσουν ινα [μετρηση]{.greek-omitted} [μετρισει]{.greek-added} την πολιν και τους πυλωνας [αυτης]{.greek-omitted} και το τειχος αυτης[21:15]{.aside}

και η πολις τετραγωνος κειται και το [μηκος]{.greek-omitted} [μικος]{.greek-added} αυτης οσον [και]{.greek-added} το πλατος [αυτης]{.greek-added} και [εμετρησεν]{.greek-omitted} [εμετρισεν]{.greek-added} την πολιν τω καλαμω επι [σταδιους]{.greek-omitted} [σταδιων]{.greek-added} δωδεκα χιλιαδων [δωδεκα]{.greek-omitted} το [μηκος]{.greek-omitted} [μικος]{.greek-added} και το πλατος [και]{.greek-omitted} [το]{.greek-omitted} [υψος]{.greek-omitted} [αυτης]{.greek-omitted} [ισα]{.greek-omitted} [εστιν]{.greek-omitted}[21:16]{.aside}

[και]{.greek-omitted} [η]{.greek-omitted} [πολις]{.greek-omitted} [τετραγωνος]{.greek-omitted} [κειται]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [μηκος]{.greek-omitted} [αυτης]{.greek-omitted} [οσον]{.greek-omitted} [το]{.greek-omitted} [πλατος]{.greek-omitted} [και]{.greek-omitted} [εμετρησεν]{.greek-omitted} [την]{.greek-omitted} [πολιν]{.greek-omitted} [τω]{.greek-omitted} [καλαμω]{.greek-omitted} [επι]{.greek-omitted} [σταδιους]{.greek-omitted} [δωδεκα]{.greek-omitted} [χιλιαδων]{.greek-omitted} [δωδεκα]{.greek-omitted} [το]{.greek-omitted} [μηκος]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [πλατος]{.greek-omitted} και το υψος αυτης ισα εστιν[21:16 | instance no. 2]{.aside}

και [εμετρησεν]{.greek-omitted} [εμετρισεν]{.greek-added} το τειχος αυτης εκατον [τεσσαρακοντα]{.greek-omitted} [τεσσαρακοντω]{.greek-added} τεσσαρων πηχων μετρον [ανθρωπου]{.greek-abbr} ο εστιν αγγελου[21:17]{.aside}

και ην η [ενδομησις]{.greek-omitted} [ενδομησης]{.greek-added} του τειχους αυτης ιασπις και η πολις χρυσιον καθαρον [ομοιον]{.greek-omitted} [ομοια]{.greek-added} [υελω]{.greek-omitted} [υαλω]{.greek-added} καθαρω[21:18]{.aside}

[και]{.greek-added} οι θεμελιοι του τειχους της πολεως παντι λιθω τιμιω κεκοσμημενοι [και]{.greek-added} [η]{.greek-added} [πλατεια]{.greek-added} [της]{.greek-added} [πολεως]{.greek-added} [χρυσιον]{.greek-added} [καθαρον]{.greek-added} [ως]{.greek-added} [υαλον]{.greek-added} [διαυγης]{.greek-added} [ο]{.greek-omitted} [θεμελιος]{.greek-omitted} [ο]{.greek-omitted} [πρωτος]{.greek-omitted} [ιασπις]{.greek-omitted} [ο]{.greek-omitted} [δευτερος]{.greek-omitted} [σαπφειρος]{.greek-omitted} [ο]{.greek-omitted} [τριτος]{.greek-omitted} [χαλκηδων]{.greek-omitted} [ο]{.greek-omitted} [τεταρτος]{.greek-omitted} [σμαραγδος]{.greek-omitted}[21:19]{.aside}

και ναον ουκ [ειδον]{.greek-omitted} [ιδεν]{.greek-added} εν αυτη ο γαρ [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ ναος αυτης εστιν και το αρνιον[21:22]{.aside}

και η πολις ου χρειαν εχει του ηλιου ουδε της [σεληνης]{.greek-omitted} [σελινης]{.greek-added} ινα φαινωσιν αυτη η γαρ δοξα του [θεου]{.greek-abbr} εφωτισεν αυτην και ο λυχνος αυτης το αρνιον[21:23]{.aside}

και περιπατησουσιν τα εθνη δια του φωτος αυτης και οι βασιλεις της γης φερουσιν [αυτω]{.greek-omitted} [την]{.greek-added} δοξαν [και]{.greek-omitted} [τιμην]{.greek-omitted} [των]{.greek-omitted} [αυτων]{.greek-added} [εθνων]{.greek-omitted} εις αυτην[21:24]{.aside}

και οι [πυλωνες]{.greek-omitted} [πυλεωνες]{.greek-added} αυτης ου μη [κλεισθωσιν]{.corr} ημερας νυξ γαρ ουκ εσται εκει[21:25]{.aside}

και οισουσιν την δοξαν και την τιμην των εθνων εις αυτην[21:26]{.aside}

[παν]{.greek-added} [κοι]{.greek-added} [ποιων]{.greek-added} [[κονον]{.corr}]{.greek-added} [και]{.corr} [[ποιων]{.corr}]{.greek-added} [ου]{.greek-omitted} [μη]{.greek-omitted} [εισελθη]{.greek-omitted} [εις]{.greek-omitted} [αυτην]{.greek-omitted} [παν]{.greek-omitted} [κοινον]{.greek-omitted} [και]{.greek-omitted} [ποιουν]{.greek-omitted} [βδελυγμα]{.greek-omitted} [βδελλυμα]{.greek-added} και ψευδος [ει]{.greek-omitted} [οι]{.greek-added} μη [οι]{.greek-omitted} γεγραμμενοι εν τω βιβλιω της ζωης του αρνιου[21:27]{.aside}

### Chapter 22

και εδειξεν μοι ποταμον καθαρον υδατος ζωης λαμπρον ως κρυσταλλον [και]{.greek-added} εκπορευομενον εκ του θρονου του [θεου]{.greek-abbr} και του αρνιου[22:1]{.aside}

[εν]{.greek-omitted} [μεσω]{.greek-omitted} [εμμεσω]{.greek-added} της πλατειας αυτης και του ποταμου εντευθεν [και]{.greek-omitted} [εκειθεν]{.greek-omitted} ξυλον ζωης ποιουν [καρπους]{.greek-omitted} [καρπον]{.greek-added} δωδεκα κατα μηνα εκαστον [αποδιδους]{.greek-omitted} [αποδιδουν]{.greek-added} τον καρπον αυτου [και]{.greek-omitted} [τα]{.greek-omitted} [φυλλα]{.greek-omitted} [του]{.greek-omitted} [ξυλου]{.greek-omitted} [εις]{.greek-omitted} [θεραπειαν]{.greek-omitted} [των]{.greek-omitted} [εθνων]{.greek-omitted}[22:2]{.aside}

[και]{.greek-omitted} [παν]{.greek-omitted} [καταθεμα]{.greek-omitted} [ουκ]{.greek-omitted} [εσται]{.greek-omitted} [ετι]{.greek-omitted} και ο θρονος του [θεου]{.greek-abbr} και του αρνιου εν αυτη εσται και οι δουλοι αυτου λατρευσουσιν αυτω[22:3]{.aside}

και οψονται το προσωπον αυτου και το ονομα αυτου επι των [μετωπων]{.greek-omitted} [μετοπων]{.greek-added} αυτων[22:4]{.aside}

και νυξ ουκ εσται εκει και χρειαν ουκ εχουσιν [λυχνου]{.greek-omitted} [λυχνους]{.greek-added} και [φωτος]{.greek-omitted} [φως]{.greek-added} ηλιου οτι [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} [φωτιει]{.greek-omitted} [φωτισει]{.greek-added} αυτους και βασιλευσουσιν εις [τους]{.greek-omitted} [τον]{.greek-added} [αιωνας]{.greek-omitted} [αιωνα]{.greek-added} [των]{.greek-omitted} [αιωνων]{.greek-omitted} [του]{.greek-added} [αιωνος]{.greek-added}[22:5]{.aside}

και [λεγει]{.greek-omitted} [ειπεν]{.greek-added} μοι ουτοι οι λογοι [αληθινοι]{.greek-added} [και]{.greek-added} πιστοι [εισιν]{.greek-added} [και]{.greek-omitted} [αληθινοι]{.greek-omitted} και [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} των [πνευματων]{.greek-omitted} [των]{.greek-omitted} [αγιων]{.greek-added} [προφητων]{.greek-added} [αγιων]{.greek-added} προφητων απεστειλεν τον αγγελον αυτου δειξαι τοις δουλοις αυτου α δει γενεσθαι [εν]{.greek-omitted} [ταχει]{.greek-omitted}[22:6]{.aside}

[και]{.greek-omitted} [λεγει]{.greek-omitted} [μοι]{.greek-omitted} [ουτοι]{.greek-omitted} [οι]{.greek-omitted} [λογοι]{.greek-omitted} [πιστοι]{.greek-omitted} [και]{.greek-omitted} [αληθινοι]{.greek-omitted} [και]{.greek-omitted} [κυριος]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [των]{.greek-omitted} [πνευματων]{.greek-omitted} [των]{.greek-omitted} [προφητων]{.greek-omitted} [απεστειλεν]{.greek-omitted} [τον]{.greek-omitted} [αγγελον]{.greek-omitted} [αυτου]{.greek-omitted} [δειξαι]{.greek-omitted} [τοις]{.greek-omitted} [δουλοις]{.greek-omitted} [αυτου]{.greek-omitted} [α]{.greek-omitted} [δει]{.greek-omitted} [γενεσθαι]{.greek-omitted} εν ταχει[22:6 | instance no. 2]{.aside}

[και]{.greek-omitted} ιδου [ερχομαι]{.greek-omitted} [ταχυ]{.greek-omitted} [ερχεται]{.greek-added} [εν]{.greek-added} [ταχει]{.greek-added} μακαριος ο τηρων τους λογους της προφητειας του βιβλιου [τουτου]{.greek-omitted} [αυτου]{.greek-added}[22:7]{.aside}

[καγω]{.greek-omitted} [και]{.greek-added} [εγω]{.greek-added} ιωαννης ο [βλεπων]{.greek-added} [και]{.greek-added} ακουων [και]{.greek-omitted} [βλεπων]{.greek-omitted} ταυτα και οτε ηκουσα και εβλεψα [επεσον]{.greek-omitted} [επεσα]{.greek-added} προσκυνησαι εμπροσθεν των ποδων του αγγελου του δεικνυοντος μοι ταυτα[22:8]{.aside}

και λεγει μοι ορα μη συνδουλος σου ειμι και των αδελφων σου των προφητων και των τηρουντων τους λογους του βιβλιου τουτου τω [θεω]{.greek-abbr} προσκυνησον[22:9]{.aside}

και λεγει μοι μη [σφραγισης]{.greek-omitted} [σφραγησις]{.greek-added} τους λογους της προφητειας του βιβλιου τουτου [ο]{.greek-omitted} [οτι]{.greek-added} καιρος [γαρ]{.greek-omitted} εγγυς εστιν[22:10]{.aside}

ο αδικων αδικησατω ετι και ο ρυπαρος ρυπαρευθητω ετι και ο δικαιος δικαιοσυνην ποιησατω ετι και ο αγιος αγιασθητω ετι[22:11]{.aside}

[και]{.greek-added} ιδου ερχομαι ταχυ και ο μισθος μου μετ εμου αποδουναι εκαστω ως το εργον [αυτου]{.greek-added} εσται [αυτου]{.greek-omitted}[22:12]{.aside}

εγω το [αλφα]{.greek-omitted} [[α]{.greek-abbr}]{.greek-added} και το [ω]{.greek-abbr} [αρχη]{.greek-added} [και]{.greek-added} [τελος]{.greek-added} ο πρωτος και ο εσχατος [η]{.greek-omitted} [αρχη]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [τελος]{.greek-omitted}[22:13]{.aside}

μακαριοι οι ποιουντες τας εντολας αυτου ινα εσται η εξουσια αυτων επι το ξυλον της ζωης και τοις [πυλωσιν]{.greek-omitted} [πυλεωσιν]{.greek-added} εισελθωσιν εις την πολιν[22:14]{.aside}

εξω οι κυνες και οι φαρμακοι και [οι]{.greek-omitted} [και]{.greek-added} [αι]{.greek-added} [πορνοι]{.greek-omitted} [πορναι]{.greek-added} και οι φονεις και οι ειδωλολατραι και πας [ο]{.greek-added} φιλων και ποιων ψευδος[22:15]{.aside}

εγω [ιησους]{.greek-abbr} επεμψα τον αγγελον μου μαρτυρησαι υμιν ταυτα [επι]{.greek-omitted} ταις εκκλησιαις [εγω]{.greek-omitted} [ειμι]{.greek-omitted} [η]{.greek-omitted} [ριζα]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [γενος]{.greek-omitted} [δαυιδ]{.greek-omitted} [ο]{.greek-omitted} [αστηρ]{.greek-omitted} [ο]{.greek-omitted} [λαμπρος]{.greek-omitted} [ο]{.greek-omitted} [πρωινος]{.greek-omitted}[22:16]{.aside}

και το [πνευμα]{.greek-abbr} και η νυμφη [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} ερχου και ο ακουων ειπατω ερχου και ο διψων ερχεσθω ο θελων λαβετω υδωρ ζωης δωρεαν[22:17]{.aside}

λεγει ο μαρτυρων ταυτα ναι ερχομαι ταχυ αμην [ναι]{.greek-omitted} ερχου [κυριε]{.greek-abbr} [ιησου]{.greek-abbr} [[χριστε]{.greek-abbr}]{.greek-added}[22:20]{.aside}

η χαρις του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} μετα παντων [των]{.greek-omitted} αγιων αμην[22:21]{.aside}

