---
title: "Collation of Byz^RP^ vs 32924 (2924)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 2924 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=32924).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 2924                                   	| λογος                              	|
| 2924 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 2924 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 2924               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 2924                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 2924 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 2924                                                     	| [―]{.gap}                        	|
:::

## Revelation

### Chapter 14

[και]{.greek-omitted} [αυτος]{.greek-omitted} [πιεται]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [οινου]{.greek-omitted} [του]{.greek-omitted} [θυμου]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [του]{.greek-omitted} κεκερασμενου ακρατου εν τω ποτηριω της οργης αυτου και [βασανισθησεται]{.greek-omitted} [βασανισθησονται]{.greek-added} εν πυρι και θειω ενωπιον [των]{.greek-omitted} [αγγελων]{.greek-added} αγιων [αγγελων]{.greek-omitted} και ενωπιον του αρνιου[14:10]{.aside}

και ο καπνος του βασανισμου αυτων εις [αιωνας]{.greek-omitted} αιωνων αναβαινει και ουκ εχουσιν αναπαυσιν ημερας και νυκτος οι προσκυνουντες το θηριον και την εικονα αυτου και ει τις λαμβανει το χαραγμα του ονοματος αυτου[14:11]{.aside}

ωδε η υπομονη των αγιων [εστιν]{.greek-omitted} [εστι]{.greek-added} [οι]{.greek-omitted} [των]{.greek-added} [τηρουντες]{.greek-omitted} [τηρουντων]{.greek-added} τας εντολας του [θεου]{.greek-abbr} [και]{.greek-omitted} [την]{.greek-omitted} [πιστιν]{.greek-omitted} [ιησου]{.greek-omitted}[14:12]{.aside}

και ηκουσα φωνης εκ του [ουρανου]{.greek-abbr} λεγουσης γραψον μακαριοι οι νεκροι οι εν [κυριω]{.greek-abbr} [αποθνησκοντες]{.greek-omitted} [απ]{.greek-omitted} [απο]{.greek-added} [αρτι]{.greek-omitted} [λεγει]{.greek-omitted} [ναι]{.greek-omitted} [το]{.greek-omitted} [πνευμα]{.greek-omitted} [ινα]{.greek-omitted} [αναπαυσωνται]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [κοπων]{.greek-omitted} [αυτων]{.greek-omitted} [τα]{.greek-omitted} [δε]{.greek-omitted} [εργα]{.greek-omitted} [αυτων]{.greek-omitted} [ακολουθει]{.greek-omitted} [μετ]{.greek-omitted} [αυτων]{.greek-omitted}[14:13]{.aside}

[και]{.greek-omitted} [ηκουσα]{.greek-omitted} [φωνης]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [λεγουσης]{.greek-omitted} [γραψον]{.greek-omitted} [μακαριοι]{.greek-omitted} [οι]{.greek-omitted} [νεκροι]{.greek-omitted} [οι]{.greek-omitted} [εν]{.greek-omitted} [κυριω]{.greek-omitted} [αποθνησκοντες]{.greek-omitted} [θνησκοντες]{.greek-added} [απ]{.greek-omitted} [αρτι]{.greek-omitted} [ἀπάρτι]{.greek-added} [ναι]{.greek-added} λεγει [ναι]{.greek-omitted} το [πνευμα]{.greek-abbr} [το]{.greek-added} [αγιον]{.greek-added} ινα αναπαυσωνται εκ των κοπων αυτων τα [δε]{.greek-omitted} [γαρ]{.greek-added} εργα αυτων ακολουθει μετ αυτων[14:13 | instance no. 2]{.aside}

και ειδον και ιδου νεφελη λευκη και επι [την]{.greek-omitted} [τη]{.greek-added} [νεφελην]{.greek-omitted} [νεφελη]{.greek-added} καθημενον ομοιον υιω [ανθρωπου]{.greek-omitted} [εχων]{.greek-omitted} [αυτου]{.greek-added} [εχοντα]{.greek-added} επι της κεφαλης αυτου στεφανον χρυσουν και εν τη χειρι αυτου δρεπανον οξυ[14:14]{.aside}

[και]{.unclear} αλλος αγγελος εξηλθεν εκ του ναου κραζων εν φωνη μεγαλη τω καθημενω επι της νεφελης πεμψον το δρεπανον σου και θερισον οτι [ηλθεν]{.greek-omitted} [η]{.greek-omitted} [ωρα]{.greek-omitted} [θερισαι]{.greek-omitted} [οτι]{.greek-omitted} [εξηρανθη]{.greek-omitted} [ο]{.greek-omitted} [θερισμος]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted}[14:15]{.aside}

[και]{.greek-omitted} [αλλος]{.greek-omitted} [αγγελος]{.greek-omitted} [εξηλθεν]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [ναου]{.greek-omitted} [κραζων]{.greek-omitted} [εν]{.greek-omitted} [φωνη]{.greek-omitted} [μεγαλη]{.greek-omitted} [τω]{.greek-omitted} [καθημενω]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [νεφελης]{.greek-omitted} [πεμψον]{.greek-omitted} [το]{.greek-omitted} [δρεπανον]{.greek-omitted} [σου]{.greek-omitted} [και]{.greek-omitted} [θερισον]{.greek-omitted} [οτι]{.greek-omitted} ηλθεν η ωρα [του]{.greek-added} θερισαι οτι εξηρανθη ο θερισμος της γης[14:15 | instance no. 2]{.aside}

και εβαλεν ο καθημενος επι την νεφελην το δρεπανον αυτου επι την γην και εθερισθη η γη[14:16]{.aside}

και αλλος αγγελος εξηλθεν εκ του ναου του εν τω [ουρανω]{.greek-abbr} εχων και αυτος δρεπανον οξυ[14:17]{.aside}

και αλλος αγγελος εξηλθεν εκ του θυσιαστηριου εχων εξουσιαν επι του πυρος και [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added} [κραυγη]{.greek-omitted} [φωνη]{.greek-added} μεγαλη τω εχοντι το δρεπανον το οξυ λεγων πεμψον σου το δρεπανον το οξυ και τρυγησον τους βοτρυας της [αμπελου]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [οτι]{.greek-omitted} [ηκμασαν]{.greek-omitted} [αι]{.greek-omitted} [σταφυλαι]{.greek-omitted} [αυτης]{.greek-omitted}[14:18]{.aside}

[και]{.greek-omitted} [αλλος]{.greek-omitted} [αγγελος]{.greek-omitted} [εξηλθεν]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [θυσιαστηριου]{.greek-omitted} [εχων]{.greek-omitted} [εξουσιαν]{.greek-omitted} [επι]{.greek-omitted} [του]{.greek-omitted} [πυρος]{.greek-omitted} [και]{.greek-omitted} [εφωνησεν]{.greek-omitted} [κραυγη]{.greek-omitted} [μεγαλη]{.greek-omitted} [τω]{.greek-omitted} [εχοντι]{.greek-omitted} [το]{.greek-omitted} [δρεπανον]{.greek-omitted} [το]{.greek-omitted} [οξυ]{.greek-omitted} [λεγων]{.greek-omitted} [πεμψον]{.greek-omitted} [σου]{.greek-omitted} [το]{.greek-omitted} [δρεπανον]{.greek-omitted} [το]{.greek-omitted} [οξυ]{.greek-omitted} [και]{.greek-omitted} [τρυγησον]{.greek-omitted} [τους]{.greek-omitted} [βοτρυας]{.greek-omitted} [της]{.greek-omitted} αμπελου της γης οτι ηκμασαν αι σταφυλαι αυτης[14:18 | instance no. 2]{.aside}

και εβαλεν ο αγγελος το δρεπανον αυτου εις την γην και [ετρυγησεν]{.greek-omitted} [ετρυγησε]{.greek-added} την αμπελον της γης και εβαλεν εις την ληνον του [θυμου]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-abbr} [τον]{.greek-omitted} [την]{.greek-added} [μεγαν]{.greek-omitted} [μεγαλην]{.greek-added}[14:19]{.aside}

και επατηθη [η]{.greek-omitted} [ο]{.greek-added} ληνος εξωθεν της πολεως και εξηλθεν αιμα εκ της ληνου αχρι των χαλινων των ιππων απο σταδιων χιλιων εξακοσιων[14:20]{.aside}

### Chapter 15

και ειδον αλλο σημειον εν τω [ουρανω]{.greek-abbr} μεγα και θαυμαστον αγγελους επτα εχοντας πληγας επτα τας εσχατας οτι εν αυταις ετελεσθη ο θυμος του [θεου]{.greek-abbr}[15:1]{.aside}

και ειδον ως θαλασσαν [υαλινην]{.greek-omitted} [υελινην]{.greek-added} [μεμιγμενην]{.greek-omitted} [πυρι]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [νικωντας]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [θηριου]{.greek-omitted} [και]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [εικονος]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [αριθμου]{.greek-omitted} [του]{.greek-omitted} [ονοματος]{.greek-omitted} [αυτου]{.greek-omitted} [εστωτας]{.greek-omitted} [επι]{.greek-omitted} [την]{.greek-omitted} [θαλασσαν]{.greek-omitted} [την]{.greek-omitted} [υαλινην]{.greek-omitted} [εχοντας]{.greek-omitted} [κιθαρας]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted}[15:2]{.aside}

