---
title: "Collation of Byz^RP^ vs 40169 (*ℓ*-169)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read *ℓ*-169 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=40169).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and *ℓ*-169                                   	| λογος                              	|
| *ℓ*-169 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| *ℓ*-169 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of *ℓ*-169               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of *ℓ*-169                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| *ℓ*-169 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in *ℓ*-169                                                     	| [―]{.gap}                        	|
:::

## Second Timothy

### Chapter 1

παυλος αποστολος [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} δια θεληματος [θεου]{.greek-abbr} κατ επαγγελιαν ζωης της εν [χριστω]{.greek-abbr} [ιησου]{.greek-abbr}[1:1]{.aside}

τιμοθεω αγαπητω τεκνω χαρις ελεος ειρηνη απο [θεου]{.greek-abbr} [πατρος]{.greek-abbr} και [χριστου]{.greek-abbr} [ιησου]{.greek-abbr} του [κυριου]{.greek-abbr} ημων[1:2]{.aside}

μη [ουν]{.greek-omitted} επαισχυνθης το μαρτυριον του [κυριου]{.greek-abbr} ημων μηδε εμε τον δεσμιον αυτου αλλα συγκακοπαθησον τω ευαγγελιω κατα [δυναμιν]{.greek-omitted} [θεου]{.greek-omitted}[1:8]{.aside}

[μη]{.greek-omitted} [ουν]{.greek-omitted} [επαισχυνθης]{.greek-omitted} [το]{.greek-omitted} [μαρτυριον]{.greek-omitted} [του]{.greek-omitted} [κυριου]{.greek-omitted} [ημων]{.greek-omitted} [μηδε]{.greek-omitted} [εμε]{.greek-omitted} [τον]{.greek-omitted} [δεσμιον]{.greek-omitted} [αυτου]{.greek-omitted} [αλλα]{.greek-omitted} [συγκακοπαθησον]{.greek-omitted} [τω]{.greek-omitted} [ευαγγελιω]{.greek-omitted} [κατα]{.greek-omitted} δυναμιν [θεου]{.greek-abbr}[1:8 | instance no. 2]{.aside}

του σωσαντος ημας και καλεσαντος κλησει αγια ου κατα τα εργα ημων αλλα κατ ιδιαν προθεσιν και χαριν την δοθεισαν ημιν εν [χριστω]{.greek-abbr} [ιησου]{.greek-abbr} προ χρονων αιωνιων[1:9]{.aside}

φανερωθεισαν δε νυν δια της επιφανειας του [σωτηρος]{.greek-abbr} ημων [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} καταργησαντος μεν τον θανατον φωτισαντος δε ζωην και αφθαρσιαν δια του ευαγγελιου[1:10]{.aside}

εις ο ετεθην εγω κηρυξ και αποστολος και διδασκαλος εθνων[1:11]{.aside}

δι ην αιτιαν και ταυτα πασχω αλλ ουκ επαισχυνομαι οιδα γαρ ω πεπιστευκα και πεπεισμαι οτι δυνατος [εστιν]{.greek-omitted} [εστι]{.greek-added} την [παραθηκην]{.greek-omitted} [παρακαταθηκην]{.greek-added} μου [φυλαξαι]{.greek-omitted} [φυλαξε]{.greek-added} εις εκεινην την ημεραν[1:12]{.aside}

υποτυπωσιν εχε υγιαινοντων λογων ων παρ εμου ηκουσας εν πιστει και αγαπη τη εν [χριστω]{.greek-abbr} [ιησου]{.greek-abbr}[1:13]{.aside}

την καλην παραθηκην φυλαξον δια [πνευματος]{.greek-abbr} αγιου του ενοικουντος εν ημιν[1:14]{.aside}

οιδας τουτο οτι απεστραφησαν με παντες οι εν τη ασια ων [εστιν]{.greek-omitted} [εστι]{.greek-added} [φυγελος]{.greek-omitted} [φυγελλος]{.greek-added} και ερμογενης[1:15]{.aside}

δωη ελεος ο [κυριος]{.greek-abbr} τω ονησιφορου οικω οτι πολλακις με [ανεψυξεν]{.greek-omitted} [ανεψυξε]{.greek-added} και την αλυσιν μου ουκ επαισχυνθη[1:16]{.aside}

αλλα γενομενος εν ρωμη [σπουδαιοτερον]{.greek-omitted} [σπουδεοτερον]{.greek-added} εζητησεν με και [ευρεν]{.greek-omitted} [ευρε]{.greek-added}[1:17]{.aside}

[δωη]{.greek-omitted} [δωει]{.greek-added} αυτω ο [κυριος]{.greek-abbr} ευρειν [ελεος]{.greek-omitted} [ελεον]{.greek-added} παρα [κυριου]{.greek-abbr} εν εκεινη τη ημερα και οσα εν εφεσω [διηκονησεν]{.greek-omitted} [διηκονησε]{.greek-added} βελτιον συ γινωσκεις[1:18]{.aside}

### Chapter 2

[τεκνον]{.greek-added} [τιμοθεε]{.greek-added} εν μεγαλη [δε]{.greek-omitted} οικια ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} μονον σκευη χρυσα και αργυρα αλλα και ξυλινα και οστρακινα και α μεν εις τιμην α δε εις ατιμιαν[2:20]{.aside}

εαν ουν τις εκκαθαρη εαυτον απο τουτων εσται σκευος εις τιμην ηγιασμενον και ευχρηστον τω δεσποτη εις παν εργον αγαθον [ητοιμασμενον]{.greek-omitted} [ητοιμασμενος]{.greek-added}[2:21]{.aside}

τας δε νεωτερικας επιθυμιας φευγε διωκε δε δικαιοσυνην πιστιν αγαπην ειρηνην μετα των επικαλουμενων τον [κυριον]{.greek-abbr} εκ καθαρας καρδιας[2:22]{.aside}

τας δε μωρας και απαιδευτους ζητησεις παραιτου ειδως οτι [γεννωσιν]{.greek-omitted} [γεννωσι]{.greek-added} [μαχας]{.greek-omitted} [μαχεσθαι]{.greek-added}[2:23]{.aside}

[δουλον]{.greek-omitted} [δε]{.greek-omitted} [κυριου]{.greek-omitted} [ου]{.greek-omitted} [δει]{.greek-omitted} [μαχεσθαι]{.greek-omitted} αλλ ηπιον ειναι προς παντας διδακτικον ανεξικακον[2:24]{.aside}

εν πραοτητι παιδευοντα τους αντιδιατιθεμενους μηποτε δω αυτοις ο [θεος]{.greek-abbr} μετανοιαν εις επιγνωσιν αληθειας[2:25]{.aside}

και ανανηψωσιν εκ της του διαβολου παγιδος εζωγρημενοι υπ αυτου εις το εκεινου θελημα[2:26]{.aside}

### Chapter 3

[τεκνον]{.greek-added} [τιμοθεε]{.greek-added} πασα γραφη θεοπνευστος και ωφελιμος προς διδασκαλιαν προς ελεγχον προς επανορθωσιν προς παιδειαν την εν δικαιοσυνη[3:16]{.aside}

ινα [αρτιος]{.greek-omitted} [αρτι]{.greek-added} [η]{.greek-omitted} [ο]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [ανθρωπος]{.greek-omitted} [προς]{.greek-omitted} [παν]{.greek-omitted} [εργον]{.greek-omitted} [αγαθον]{.greek-omitted} [εξηρτισμενος]{.greek-omitted}[3:17]{.aside}

[ος]{.greek-added} [ινα]{.greek-omitted} [αρτιος]{.greek-omitted} η ο του [θεου]{.greek-abbr} [ανθρωπος]{.greek-abbr} προς παν εργον αγαθον εξηρτισμενος[3:17 | instance no. 2]{.aside}

### Chapter 4

διαμαρτυρομαι ουν εγω ενωπιον του [θεου]{.greek-abbr} και του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} του μελλοντος κρινειν ζωντας και νεκρους κατα την επιφανειαν αυτου και την βασιλειαν αυτου[4:1]{.aside}

κηρυξον τον λογον επιστηθι ευκαιρως ακαιρως ελεγξον επιτιμησον παρακαλεσον εν παση μακροθυμια και διδαχη[4:2]{.aside}

εσται γαρ καιρος οτε της υγιαινουσης διδασκαλιας ουκ ανεξονται αλλα κατα τας επιθυμιας τας ιδιας εαυτοις [επισωρευσουσιν]{.greek-omitted} [επισωρευσουσι]{.greek-added} διδασκαλους κνηθομενοι την ακοην[4:3]{.aside}

και απο μεν της αληθειας την ακοην αποστρεψουσιν επι δε τους μυθους εκτραπησονται[4:4]{.aside}

[τεκνον]{.greek-added} [τιμοθεε]{.greek-added} σπουδασον ελθειν προς με ταχεως[4:9]{.aside}

δημας γαρ με εγκατελιπεν αγαπησας τον νυν αιωνα και επορευθη εις [θεσσαλονικην]{.greek-omitted} [θεσαλονικην]{.greek-added} [κρησκης]{.greek-omitted} [κρισκης]{.greek-added} εις γαλατιαν τιτος εις δαλματιαν[4:10]{.aside}

λουκας [εστιν]{.greek-omitted} [εστι]{.greek-added} μονος μετ εμου μαρκον αναλαβων αγε μετα σεαυτου [εστιν]{.greek-omitted} [εστι]{.greek-added} γαρ μοι ευχρηστος εις διακονιαν[4:11]{.aside}

τυχικον δε απεστειλα εις εφεσον[4:12]{.aside}

τον φελονην ον απελιπον εν τρωαδι παρα [καρπω]{.greek-omitted} [καρπων]{.greek-added} ερχομενος φερε και τα βιβλια μαλιστα τας μεμβρανας[4:13]{.aside}

αλεξανδρος ο χαλκευς πολλα μοι κακα ενεδειξατο αποδωη αυτω ο [κυριος]{.greek-abbr} κατα τα [ερ]{.greek-added} [εργα]{.greek-omitted} [αυτου]{.greek-omitted}[4:14]{.aside}

[γα]{.greek-added} [αλεξανδρος]{.greek-omitted} [ο]{.greek-omitted} [χαλκευς]{.greek-omitted} [πολλα]{.greek-omitted} [μοι]{.greek-omitted} [κακα]{.greek-omitted} [ενεδειξατο]{.greek-omitted} [αποδωη]{.greek-omitted} [αυτω]{.greek-omitted} [ο]{.greek-omitted} [κυριος]{.greek-omitted} [κατα]{.greek-omitted} [τα]{.greek-omitted} [εργα]{.greek-omitted} αυτου[4:14 | instance no. 2]{.aside}

ον και συ φυλασσου λιαν γαρ [ανθεστηκεν]{.greek-omitted} [ανθεστηκε]{.greek-added} τοις ημετεροις λογοις[4:15]{.aside}

εν τη πρωτη μου απολογια ουδεις μοι συμπαρεγενετο αλλα παντες με [εγκατελιπον]{.greek-omitted} [εγκατελειπον]{.greek-added} μη αυτοις λογισθειη[4:16]{.aside}

ο δε [κυριος]{.greek-abbr} μοι παρεστη και ενεδυναμωσεν με ινα δι εμου το κηρυγμα [πληροφορηθη]{.greek-omitted} [πληρωθη]{.greek-added} και [ακουση]{.greek-omitted} [ακουσει]{.greek-added} παντα τα εθνη και ερρυσθην εκ στοματος λεοντος[4:17]{.aside}

και ρυσεται με ο [κυριος]{.greek-abbr} απο παντος εργου πονηρου και σωσει εις την βασιλειαν αυτου την [επουρανιον]{.greek-omitted} [επ[ουνιον]{.greek-abbr}]{.greek-added} ω η δοξα εις τους αιωνας των αιωνων αμην[4:18]{.aside}

ασπασαι [πρισκαν]{.greek-omitted} [πρισκιλλαν]{.greek-added} και ακυλαν και τον ονησιφορου οικον[4:19]{.aside}

εραστος εμεινεν εν κορινθω τροφιμον δε απελιπον εν μιλητω ασθενουντα[4:20]{.aside}

σπουδασον προ χειμωνος ελθειν ασπαζεται σε ευβουλος και πουδης και λινος και κλαυδια και οι αδελφοι παντες[4:21]{.aside}

ο [κυριος]{.greek-abbr} [ιησους]{.greek-abbr} [χριστος]{.greek-abbr} μετα του [πνευματος]{.greek-abbr} σου η χαρις μεθ υμων αμην[4:22]{.aside}

## Titus

### Chapter 1

[τεκνον]{.greek-added} [τιτε]{.greek-added} [τουτου]{.greek-omitted} [χαριν]{.greek-omitted} [κατελιπον]{.greek-omitted} [σε]{.greek-omitted} [εν]{.greek-omitted} [κρητη]{.greek-omitted} [ινα]{.greek-omitted} [τα]{.greek-omitted} [λειποντα]{.greek-omitted} [επιδιορθωση]{.greek-omitted} [και]{.greek-omitted} [καταστησης]{.greek-omitted} [καταστησον]{.greek-added} [πρεσβυτερους]{.greek-added} κατα πολιν [πρεσβυτερους]{.greek-omitted} ως εγω σοι διεταξαμην[1:5]{.aside}

ει τις εστιν ανεγκλητος μιας γυναικος ανηρ τεκνα εχων πιστα μη εν κατηγορια ασωτιας η ανυποτακτα[1:6]{.aside}

δει γαρ τον επισκοπον ανεγκλητον ειναι ως [θεου]{.greek-abbr} οικονομον μη αυθαδη μη οργιλον μη παροινον μη πληκτην μη αισχροκερδη[1:7]{.aside}

αλλα φιλοξενον φιλαγαθον σωφρονα δικαιον οσιον εγκρατη[1:8]{.aside}

[αντεχομενον]{.greek-omitted} [αντεχομε]{.greek-added} [του]{.greek-omitted} [κατα]{.greek-omitted} [την]{.greek-omitted} [διδαχην]{.greek-omitted} [πιστου]{.greek-omitted} [λογου]{.greek-omitted} [ινα]{.greek-omitted} [δυνατος]{.greek-omitted} [η]{.greek-omitted} [και]{.greek-omitted} [παρακαλειν]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [διδασκαλια]{.greek-omitted} [τη]{.greek-omitted} [υγιαινουση]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [αντιλεγοντας]{.greek-omitted} [ελεγχειν]{.greek-omitted}[1:9]{.aside}

