---
title: "Collation of Byz^RP^ vs 40844 (*ℓ*-844)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read *ℓ*-844 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=40844).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and *ℓ*-844                                   	| λογος                              	|
| *ℓ*-844 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| *ℓ*-844 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of *ℓ*-844               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of *ℓ*-844                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| *ℓ*-844 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in *ℓ*-844                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Matthew

### Chapter 1

βιβλος γενεσεως [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} υιου [δαυιδ]{.greek-abbr} υιου αβρααμ[1:1]{.aside}

αβρααμ εγεννησεν τον [ισαακ]{.greek-omitted} [ισαακ·]{.greek-added} ισαακ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιακωβ ιακωβ δε εγεννησεν τον ιουδαν και τους αδελφους αυτου[1:2]{.aside}

ιουδας δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον φαρες και τον ζαρα εκ [της]{.greek-omitted} [τη]{.greek-added} θαμαρ φαρες δε εγεννησεν τον [εσρομ]{.greek-added} [εσρωμ]{.corr} εσρωμ δε εγεννησεν τον αραμ[1:3]{.aside}

αραμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αμιναδαβ αμιναδαβ δε εγεννησεν τον ναασσων ναασσων δε εγεννησεν τον σαλμων[1:4]{.aside}

σαλμων δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον [βοοζ]{.greek-omitted} [βοες]{.greek-added} εκ της ραχαβ [βοοζ]{.greek-omitted} [βοες]{.greek-added} δε εγεννησεν τον ωβηδ [εκ]{.greek-omitted} [της]{.greek-omitted} [ρουθ]{.greek-omitted} ωβηδ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιεσσαι[1:5]{.aside}

ιεσσαι δε εγεννησεν [τον]{.greek-omitted} [δαυιδ]{.greek-abbr} τον βασιλεα [δαυιδ]{.greek-abbr} δε ο βασιλευς [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον [σολομωνα]{.greek-omitted} [σολομωντα]{.greek-added} εκ της του ουριου[1:6]{.aside}

σολομων δε εγεννησεν τον ροβοαμ ροβοαμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αβια αβια δε εγεννησεν τον [ασα]{.greek-omitted} [ασαφ]{.greek-added}[1:7]{.aside}

[ασα]{.greek-omitted} [ασαφ]{.greek-added} δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιωσαφατ ιωσαφατ δε εγεννησεν τον ιωραμ ιωραμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον οζιαν[1:8]{.aside}

οζιας δε εγεννησεν τον ιωαθαμ ιωαθαμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αχαζ αχαζ δε εγεννησεν τον εζεκιαν[1:9]{.aside}

εζεκιας δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον [μανασση]{.greek-omitted} [μανασσην]{.greek-added} μανασσης δε εγεννησεν τον αμων αμων δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιωσιαν[1:10]{.aside}

ιωσιας δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιεχονιαν και τους αδελφους αυτου επι της μετοικεσιας βαβυλωνος[1:11]{.aside}

μετα δε την μετοικεσιαν βαβυλωνος ιεχονιας εγεννησεν τον σαλαθιηλ σαλαθιηλ δε εγεννησεν τον ζοροβαβελ[1:12]{.aside}

ζοροβαβελ δε εγεννησεν τον αβιουδ αβιουδ δε εγεννησεν τον ελιακειμ ελιακειμ δε εγεννησεν τον αζωρ[1:13]{.aside}

αζωρ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον σαδωκ σαδωκ δε εγεννησεν τον [αχειμ]{.greek-omitted} [αχιμ]{.greek-added} [αχειμ]{.greek-omitted} [αχιμ]{.greek-added} δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ελιουδ[1:14]{.aside}

ελιουδ δε εγεννησεν τον ελεαζαρ ελεαζαρ δε εγεννησεν τον ματθαν ματθαν δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιακωβ[1:15]{.aside}

ιακωβ δε εγεννησεν τον ιωσηφ τον ανδρα μαριας εξ ης εγεννηθη [ιησους]{.greek-abbr} ο λεγομενος [χριστος]{.greek-abbr}[1:16]{.aside}

πασαι ουν αι γενεαι απο αβρααμ εως [δαυιδ]{.greek-abbr} γενεαι δεκατεσσαρες και απο [δαυιδ]{.greek-abbr} εως της μετοικεσιας βαβυλωνος γενεαι δεκατεσσαρες και απο της μετοικεσιας βαβυλωνος [εως]{.corr} του [χριστου]{.greek-abbr} γενεαι δεκατεσσαρες[1:17]{.aside}

του [δε]{.greek-omitted} [[κυριου]{.greek-abbr}]{.greek-added} [ημων]{.greek-added} [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} η γεννησις ουτως ην [μνηστευθεισης]{.greek-omitted} [μνηστευθησης]{.greek-added} γαρ της [μητρος]{.greek-abbr} αυτου μαριας τω ιωσηφ πριν η συνελθειν αυτους [ευρεθη]{.greek-omitted} [ηυρεθη]{.greek-added} εν [γα]{.greek-added} [γαστρι]{.greek-omitted} [στρι]{.greek-added} εχουσα εκ [πνευματος]{.greek-abbr} αγιου[1:18]{.aside}

ιωσηφ δε ο ανηρ αυτης δικαιος ων και μη θελων αυτην [παραδειγματισαι]{.greek-omitted} [παραδιγματισαι]{.greek-added} εβουληθη λαθρα απολυσαι αυτην[1:19]{.aside}

ταυτα δε αυτου ενθυμηθεντος ιδου αγγελος [κυριου]{.greek-abbr} [φαινετε]{.greek-added} [αυτω]{.greek-added} κατ οναρ [εφανη]{.greek-omitted} [αυτω]{.greek-omitted} λεγων ιωσηφ υιος [δαυιδ]{.greek-abbr} μη [φοβηθης]{.greek-omitted} [φοβηθεις]{.greek-added} παραλαβειν μαριαμ την γυναικα σου το γαρ εν αυτη γεννηθεν εκ [πνευματος]{.greek-abbr} [αγιου]{.greek-added} εστιν [αγιου]{.greek-omitted}[1:20]{.aside}

τεξεται δε υιον και καλεσεις το ονομα αυτου [ιησουν]{.greek-abbr} αυτος γαρ σωσει τον λαον αυτου απο των αμαρτιων αυτων[1:21]{.aside}

τουτο δε ολον γεγονεν ινα πληρωθη το ρηθεν υπο του [κυριου]{.greek-abbr} δια του προφητου λεγοντος[1:22]{.aside}

ιδου η παρθενος εν γαστρι εξει και τεξεται [υιον]{.greek-abbr} και καλεσουσιν το ονομα αυτου εμμανουηλ ο εστιν μεθερμηνευομενον μεθ ημων ο [θεος]{.greek-abbr}[1:23]{.aside}

διεγερθεις δε ο ιωσηφ απο του υπνου εποιησεν ως προσεταξεν αυτω ο αγγελος [κυριου]{.greek-abbr} και παρελαβεν την γυναικα αυτου[1:24]{.aside}

και ουκ εγινωσκεν αυτην εως ου ετεκεν τον υιον αυτης τον πρωτοτοκον και εκαλεσεν το ονομα αυτου [ιησουν]{.greek-abbr}[1:25]{.aside}

### Chapter 2

του [δε]{.greek-omitted} [[κυριου]{.greek-abbr}]{.greek-added} [ημων]{.greek-added} [ιησου]{.greek-abbr} [[χριστου]{.greek-abbr}]{.greek-added} γεννηθεντος εν βηθλεεμ της ιουδαιας εν ημεραις ηρωδου του βασιλεως ιδου μαγοι απο ανατολων παρεγενοντο εις ιεροσολυμα[2:1]{.aside}

λεγοντες που εστιν ο [τεχθεις]{.greek-omitted} [τεχθης]{.greek-added} βασιλευς των ιουδαιων ειδομεν γαρ αυτου τον αστερα εν τη ανατολη και ηλθομεν προσκυνησαι αυτω[2:2]{.aside}

ακουσας δε ηρωδης ο βασιλευς εταραχθη και πασα [η]{.greek-added} ιεροσολυμα μετ αυτου[2:3]{.aside}

και συναγαγων παντας τους αρχιερεις και γραμματεις του λαου επυνθανετο παρ αυτων που ο [χριστος]{.greek-abbr} γενναται[2:4]{.aside}

οι δε ειπον [αυτω]{.greek-omitted} εν βηθλεεμ της ιουδαιας ουτως γαρ γεγραπται δια του προφητου[2:5]{.aside}

και συ βηθλεεμ γη ιουδα ουδαμως ελαχιστη ει εν τοις ηγεμοσιν ιουδα εκ σου γαρ εξελευσεται ηγουμενος οστις ποιμανει τον λαον μου τον [ισραηλ]{.greek-abbr}[2:6]{.aside}

τοτε ηρωδης λαθρα καλεσας τους μαγους ηκριβωσεν παρ αυτων τον χρονον του φαινομενου αστερος[2:7]{.aside}

και πεμψας αυτους εις βηθλεεμ ειπεν πορευθεντες [εξετασαται]{.greek-added} ακριβως [εξετασατε]{.greek-omitted} περι του παιδιου επαν δε [ευρητε]{.greek-omitted} [ευρηται]{.greek-added} απαγγειλατε μοι οπως καγω ελθων προσκυνησω αυτω[2:8]{.aside}

οι δε ακουσαντες του βασιλεως επορευθησαν και ιδου ο αστηρ ον [ειδον]{.greek-omitted} [ιδον]{.greek-added} εν τη ανατολη προηγεν αυτους εως ελθων εστη επανω ου ην το παιδιον[2:9]{.aside}

ιδοντες δε τον αστερα εχαρησαν χαραν μεγαλην σφοδρα[2:10]{.aside}

και ελθοντες εις την οικιαν [ειδον]{.greek-omitted} [ιδον]{.greek-added} το παιδιον μετα μαριας της [μητρος]{.greek-abbr} αυτου και πεσοντες προσεκυνησαν αυτω και ανοιξαντες τους θησαυρους αυτων προσηνεγκαν αυτω δωρα χρυσον και λιβανον και σμυρναν[2:11]{.aside}

και χρηματισθεντες κατ οναρ μη ανακαμψαι προς ηρωδην δι αλλης οδου ανεχωρησαν εις την χωραν αυτων[2:12]{.aside}

### Chapter 3

εν [δε]{.greek-omitted} ταις ημεραις εκειναις παραγινεται ιωαννης ο βαπτιστης κηρυσσων εν τη ερημω της ιουδαιας[3:1]{.aside}

και λεγων μετανοειτε ηγγικεν γαρ η βασιλεια των [ουρανων]{.greek-abbr}[3:2]{.aside}

ουτος [γαρ]{.corr} εστιν ο ρηθεις υπο ησαιου του προφητου λεγοντος φωνη βοωντος εν τη ερημω ετοιμασατε την οδον [κυριου]{.greek-abbr} ευθειας [ποιειτε]{.greek-omitted} [ποιητε]{.greek-added} τας τριβους αυτου[3:3]{.aside}

αυτος δε ο ιωαννης ειχεν το ενδυμα αυτου απο τριχων καμηλου και ζωνην δερματινην περι την οσφυν αυτου η δε τροφη αυτου ην ακριδες και μελι αγριον[3:4]{.aside}

τοτε εξεπορευετο προς [αυ]{.greek-added} [αυτον]{.corr} [[πασα]{.corr}]{.greek-added} [ιεροσολυμα]{.corr} και πασα η ιουδαια και πασα η περιχωρος του ιορδανου[3:5]{.aside}

και εβαπτιζοντο εν τω ιορδανη υπ αυτου εξομολογουμενοι τας αμαρτιας αυτων[3:6]{.aside}

ιδων δε πολλους των φαρισαιων και σαδδουκαιων ερχομενους επι το βαπτισμα αυτου ειπεν αυτοις γεννηματα εχιδνων τις υπεδειξεν υμιν φυγειν απο της μελλουσης οργης[3:7]{.aside}

ποιησατε ουν καρπον αξιον της μετανοιας[3:8]{.aside}

και μη δοξητε λεγειν εν εαυτοις [πατερα]{.greek-abbr} εχομεν τον αβρααμ λεγω γαρ υμιν οτι δυναται ο [θεος]{.greek-abbr} εκ των λιθων τουτων εγειραι τεκνα τω αβρααμ[3:9]{.aside}

ηδη δε και η αξινη προς την ριζαν των δενδρων κειται παν ουν δενδρον μη ποιουν καρπον καλον εκκοπτεται και εις πυρ βαλλεται[3:10]{.aside}

εγω μεν βαπτιζω υμας εν υδατι εις μετανοιαν ο δε οπισω μου ερχομενος ισχυροτερος μου εστιν ου ουκ ειμι ικανος τα υποδηματα βαστασαι [α]{.unclear}υτος υμας βαπτισει εν [πνευματι]{.greek-abbr} αγιω [και]{.greek-added} [πυρι]{.greek-added}[3:11]{.aside}

ου το πτυον εν τη χειρι αυτου και διακαθαριει την αλωνα αυτου και συναξει τον σιτον [αυτου]{.greek-omitted} εις την αποθηκην [αυτου]{.greek-added} το δε αχυρον κατακαυσει πυρι ασβεστω[3:12]{.aside}

τοτε παραγινεται ο [ιησους]{.greek-abbr} απο της γαλιλαιας επι τον ιορδανην [προς]{.corr} [τον]{.corr} [ιωαννην]{.corr} του βαπτισθηναι υπ αυτου[3:13]{.aside}

ο δε ιωαννης [διεκωλυεν]{.greek-omitted} [διεκολυεν]{.greek-added} αυτον λεγων εγω [χρειαν]{.greek-omitted} [χριαν]{.greek-added} εχω υπο σου βαπτισθηναι και συ ερχη προς με[3:14]{.aside}

[και]{.greek-added} αποκριθεις [δε]{.greek-omitted} ο [ιησους]{.greek-abbr} ειπεν [αυτω]{.greek-added} [προς]{.greek-omitted} [αυτον]{.greek-omitted} αφες αρτι ουτως γαρ [πρεπον]{.greek-omitted} [πρεπων]{.greek-added} εστιν ημιν πληρωσαι πασαν δικ[αι]{.unclear}οσυνην τοτε αφιησιν αυτον[3:15]{.aside}

και [βαπτισθεις]{.greek-omitted} [βαπτισ]{.greek-added} [θεις]{.greek-added} ο [ιησους]{.greek-abbr} [ευθυς]{.greek-added} ανεβη [ευθυς]{.greek-omitted} απο του υδατος και ιδου ανεωχθησαν αυτω [οι]{.corr} [ουρανοι]{.greek-abbr} και [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} το [πνευμα]{.greek-abbr} του [θεου]{.greek-abbr} [καταβαινον]{.greek-omitted} [καταβαινων]{.greek-added} ωσει περιστεραν [εξ]{.greek-added} [[ουρανου]{.greek-abbr}]{.greek-added} και ερχομενον επ αυτον[3:16]{.aside}

και ιδου φωνη εκ των [ουρανων]{.greek-abbr} λεγουσα ουτος εστιν ο [υιος]{.greek-abbr} μου ο αγαπητος εν ω [ευδοκησα]{.greek-omitted} [ηυδοκησα]{.greek-added}[3:17]{.aside}

### Chapter 4

[τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} ακουσας [δε]{.greek-omitted} ο [[κυριος]{.greek-abbr}]{.greek-added} [ημων]{.greek-added} [ιησους]{.greek-abbr} [ο]{.greek-added} [[χριστος]{.greek-abbr}]{.greek-added} οτι ιωαννης [παρεδοθη]{.greek-omitted} [παρεδωθη]{.greek-added} ανεχωρησεν εις την γαλιλαιαν[4:12]{.aside}

και [καταλιπων]{.greek-omitted} [καταλειπων]{.greek-added} την ναζαρετ ελθων κατωκησεν εις καπερναουμ την παραθαλασσιαν εν οριοις ζαβουλων και [νεφθαλειμ]{.greek-omitted} [νεφθαλημ]{.greek-added}[4:13]{.aside}

ινα πληρωθη το ρηθεν δια ησαιου του προφητου λεγοντος[4:14]{.aside}

γη ζαβουλων και γη [νεφθαλιμ]{.greek-added} [νεφθαλειμ]{.corr} οδον θαλασσης περαν του ιορδανου γαλιλαια των εθνων[4:15]{.aside}

ο λαος ο καθημενος εν [σκοτει]{.greek-omitted} [σκοτι]{.greek-added} [φως]{.greek-added} ειδεν [φως]{.greek-omitted} μεγα και τοις καθημενοις εν χωρα και σκια θανατου φως ανετειλεν αυτοις[4:16]{.aside}

απο τοτε ηρξατο ο [ιησους]{.greek-abbr} κηρυσσειν και λεγειν μετανοειτε ηγγικεν γαρ η βασιλεια των [ουρανων]{.greek-abbr}[4:17]{.aside}

περιπατων δε παρα την θαλασσαν της γαλιλαιας ειδεν δυο αδελφους σιμωνα τον [λεγομενον]{.greek-omitted} [καλουμενων]{.greek-added} πετρον και ανδρεαν τον αδελφον αυτου βαλλοντας αμφιβληστρον εις την θαλασσαν ησαν γαρ αλιεις[4:18]{.aside}

και λεγει αυτοις δευτε οπισω μου και ποιησω υμας [αλιεις]{.greek-omitted} [γενεσθαι]{.greek-added} [αλι]{.greek-added} [εις]{.greek-added} [ανθρωπων]{.greek-abbr}[4:19]{.aside}

οι δε ευθεως αφεντες τα δικτυα ηκολουθησαν αυτω[4:20]{.aside}

και προβας εκειθεν ειδεν αλλους δυο αδελφους ιακωβον τον του ζεβεδαιου και ιωαννην τον αδελφον αυτου εν τω πλοιω μετα ζεβεδαιου του [πατρος]{.greek-abbr} αυτων καταρτιζοντας τα δικτυα αυτων και εκαλεσεν αυτους[4:21]{.aside}

οι δε ευθεως [αφεν]{.greek-added} [αφεντες]{.corr} το πλοιον και τον [πατερα]{.greek-abbr} αυτων ηκολουθησαν αυτω[4:22]{.aside}

και περιηγεν [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} ολην την γαλιλαιαν [ο]{.greek-omitted} [ιησους]{.greek-omitted} διδασκων εν ταις συναγωγαις αυτων και κηρυσσων το ευαγγελιον της βασιλειας και θεραπευων πασαν νοσον και πασαν μαλακιαν εν τω λαω[4:23]{.aside}

και απηλθεν η ακοη αυτου εις ολην την συριαν και προσηνεγκαν αυτω παντας τους κακως εχοντας ποικιλαις νοσοις και βασανοις συνεχομενους και δαιμονιζομενους και σεληνιαζομενους και παραλυτικους και εθεραπευσεν αυτους[4:24]{.aside}

και ηκολουθησαν αυτω οχλοι πολλοι απο της γαλιλαιας και δεκαπολεως και ιεροσολυμων και ιουδαιας και περαν του ιορδανου[4:25]{.aside}

### Chapter 5

[και]{.greek-omitted} [ανοιξας]{.greek-omitted} [το]{.greek-omitted} [στομα]{.greek-omitted} [ανελθων]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} [ημων]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [ο]{.greek-added} [[χριστος]{.greek-abbr}]{.greek-added} [εδιδασκεν]{.greek-added} [τους]{.greek-added} [μαθητας]{.greek-added} αυτου [εδιδασκεν]{.greek-omitted} [αυτους]{.greek-omitted} λεγων[5:2]{.aside}

μακαριοι οι πτωχοι [τω]{.greek-omitted} [το]{.greek-added} [πνευματι]{.greek-abbr} οτι αυτων εστιν η βασιλεια των [ουρανων]{.greek-abbr}[5:3]{.aside}

μακαριοι οι πενθουντες [νυν]{.greek-added} οτι αυτοι [παρακληθησονται]{.greek-omitted} [παρακληθησωνται]{.greek-added}[5:4]{.aside}

μακαριοι οι πραεις οτι αυτοι [κληρονομησουσιν]{.greek-omitted} [κληρονομησουσην]{.greek-added} την γην[5:5]{.aside}

μακαριοι οι πεινωντες και [διψωντες]{.greek-omitted} [δειψωντες]{.greek-added} την [δικαιοσυνην]{.greek-omitted} [δικαιωσυνην]{.greek-added} οτι αυτοι [χορτασθησονται]{.greek-omitted} [χορτασθησωνται]{.greek-added}[5:6]{.aside}

μακαριοι οι [ελεημονες]{.greek-omitted} [ελεημωνες]{.greek-added} οτι αυτοι ελεηθησονται[5:7]{.aside}

μακαριοι οι καθαροι τη καρδια οτι αυτοι τον [θεον]{.greek-abbr} [οψονται]{.greek-omitted} [οψωνται]{.greek-added}[5:8]{.aside}

μακαριοι οι [ειρηνοποιοι]{.greek-omitted} [ειρηνωποιοι]{.greek-added} οτι αυτοι υιοι [θεου]{.greek-abbr} κληθησονται[5:9]{.aside}

μακαριοι οι δεδιωγμενοι [ενεκεν]{.greek-omitted} [ενεκε]{.greek-added} δικαιοσυνης οτι αυτων [εστιν]{.greek-omitted} [εστην]{.greek-added} η βασιλεια των [ουρανων]{.greek-abbr}[5:10]{.aside}

μακαριοι [εστε]{.greek-omitted} [εσται]{.greek-added} οταν [ονειδισωσιν]{.greek-omitted} [ονηδεισωσιν]{.greek-added} υμας και διωξωσιν και ειπωσιν παν [πονηρον]{.greek-omitted} [ποειρον]{.greek-added} ρημα καθ υμων ψευδομενοι ενεκεν εμου[5:11]{.aside}

[χαιρετε]{.greek-omitted} [χαιρεται]{.greek-added} και [αγαλλιασθε]{.greek-omitted} [αγ[αλλι]{.unclear}ασθαι]{.greek-added} οτι ο [μισθος]{.greek-omitted} [μησθως]{.greek-added} υμων πολυς εν τοις [ουρανοις]{.greek-abbr} [ουτως]{.greek-omitted} [γαρ]{.greek-omitted} [εδιωξαν]{.greek-omitted} [τους]{.greek-omitted} [προφητας]{.greek-omitted} [τους]{.greek-omitted} [προ]{.greek-omitted} [υμων]{.greek-omitted}[5:12]{.aside}

[εν]{.greek-added} [εκεινω]{.greek-added} [τω]{.greek-added} [καιρω]{.greek-added} [ειπεν]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} [ημων]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [ο]{.greek-added} [[χριστος]{.greek-abbr}]{.greek-added} [τοις]{.greek-added} [εαυτου]{.greek-added} [μαθηταις]{.greek-added} [και]{.greek-added} [τοις]{.greek-added} [οχλοις]{.greek-added} μη [νομισητε]{.greek-omitted} [νομησηται]{.greek-added} οτι ηλθον καταλυσαι τον νομον η τους προφητας ουκ ηλθον καταλυσαι αλλα πληρωσαι[5:17]{.aside}

αμην γαρ λεγω υμιν εως αν παρελθη ο [ουρανος]{.greek-abbr} και η γη ιωτα εν η μια [κεραια]{.greek-omitted} [κερεα]{.greek-added} ου μη παρελθη απο του νομου εως αν παντα γενηται[5:18]{.aside}

ος εαν ουν λυση μιαν των εντολων τουτων των ελαχιστων και [διδαξη]{.greek-omitted} [διδαξει]{.greek-added} ουτως τους [ανθρωπους]{.greek-abbr} ελαχιστος κληθησεται εν τη βασιλεια των [ουρανων]{.greek-abbr} ος δ αν [ποιηση]{.greek-omitted} [ποιησει]{.greek-added} και [διδαξη]{.greek-omitted} [διδαξει]{.greek-added} ουτος μεγας κληθησεται εν τη βασιλεια των [ουρανων]{.greek-abbr}[5:19]{.aside}

λεγω γαρ υμιν οτι εαν μη περισσευση [υμων]{.greek-added} η δικαιοσυνη [υμων]{.greek-omitted} [πλειον]{.greek-omitted} [πλειων]{.greek-added} των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} και [φαρισαιων]{.greek-omitted} [φαρεισαιων]{.greek-added} ου μη εισελθητε εις την βασιλειαν των [ουρανων]{.greek-abbr}[5:20]{.aside}

ηκουσατε οτι ερρεθη τοις αρχαιοις ου φονευσεις ος δ αν φονευση ενοχος εσται τη κρισει[5:21]{.aside}

[εγω]{.greek-omitted} [δε]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [οτι]{.greek-omitted} [πας]{.greek-omitted} [ο]{.greek-omitted} [οργιζομενος]{.greek-omitted} [τω]{.greek-omitted} [αδελφω]{.greek-omitted} [αυτου]{.greek-omitted} [εικη]{.greek-omitted} [ενοχος]{.greek-omitted} [εσται]{.greek-omitted} [τη]{.greek-omitted} [κρισει]{.greek-omitted} ος δ αν [ειπη]{.greek-omitted} [ειπει]{.greek-added} τω αδελφω αυτου ρακα ενοχος [εσ]{.greek-added} [εσται]{.greek-omitted} [ται]{.greek-added} τω συνεδριω ος δ αν [ειπη]{.greek-omitted} [ειπει]{.greek-added} μωρε ενοχος εσται εις την [γεενναν]{.greek-omitted} [γεεναν]{.greek-added} του πυρος[5:22]{.aside}

εαν ουν [προσφερης]{.greek-omitted} [προσφερεις]{.greek-added} το δωρον σου επι το θυσιαστηριον [και]{.greek-omitted} [κακει]{.greek-added} [εκει]{.greek-omitted} [μνησθης]{.greek-omitted} [μνησθεις]{.greek-added} οτι ο αδελφος σου εχει τι κατα σου[5:23]{.aside}

αφες εκει το δωρον σου εμπροσθεν του θυσιαστηριου και υπαγε πρωτον [διαλλαγηθι]{.greek-omitted} [διαλλαγηθη]{.greek-added} τω αδελφω σου και τοτε ελθων προσφερε το δωρον σου[5:24]{.aside}

ισθι ευνοων τω αντιδικω σου ταχυ εως οτου ει [μετ]{.greek-added} [αυτου]{.greek-added} εν τη οδω [μετ]{.greek-omitted} [αυτου]{.greek-omitted} μηποτε σε παραδω ο αντιδικος τω κριτη και ο κριτης σε παραδω τω υπηρετη και εις φυλακην [βληθηση]{.greek-omitted} [βλη]{.greek-added} [θηση]{.greek-added}[5:25]{.aside}

αμην λεγω σοι ου μη εξελθης εκειθεν εως αν αποδως τον εσχατον κοδραντην[5:26]{.aside}

ηκουσατε οτι ερρεθη ου μοιχευσεις[5:27]{.aside}

εγω δε λεγω υμιν οτι πας ο βλεπων γυναικα [προ]{.greek-added} [προς]{.corr} το επιθυμησαι αυτην ηδη εμοιχευσεν αυτην εν τη καρδια αυτου[5:28]{.aside}

ει δε ο οφθαλμος σου ο δεξιος σκανδαλιζει σε εξελε αυτον και βαλε απο σου συμφερει γαρ σοι ινα [αποληται]{.greek-omitted} [απολειται]{.greek-added} εν των μελων σου και μη ολον το σωμα σου βληθη εις γεενναν[5:29]{.aside}

και ει η δεξια σου χειρ σκανδ[α]{.unclear}λιζει σε εκκοψον αυτην και βαλε απο σου συμφερει γαρ σοι ινα [αποληται]{.greek-omitted} [απολειται]{.greek-added} εν των μελων σου και μη ολον το σωμα σου βληθη εις γεενναν[5:30]{.aside}

ερρεθη [δε]{.greek-omitted} οτι ος αν [απολυση]{.greek-omitted} [απολυσει]{.greek-added} την γυναικα αυτου δοτω αυτη αποστασιον[5:31]{.aside}

εγω δε λεγω υμιν οτι [ος]{.greek-omitted} [αν]{.greek-omitted} [απολυση]{.greek-omitted} [πας]{.greek-added} [ο]{.greek-added} [απολυων]{.greek-added} την γυναικα αυτου παρεκτος λογου [πορνειας]{.greek-omitted} [πορνιας]{.greek-added} ποιει αυτην μοιχασθαι και ος εαν απολελυμενην [γαμηση]{.greek-omitted} [γαμειση]{.greek-added} μοιχαται[5:32]{.aside}

παλιν ηκουσατε οτι ερρεθη τοις αρχαιοις ουκ επιορκησεις αποδωσεις [δε]{.corr} τω [κυριω]{.greek-abbr} τους ορκους σου[5:33]{.aside}

εγω δε λεγω υμιν μη [ομοσαι]{.greek-omitted} [ομω[σ]{.unclear}ισαι]{.greek-added} ολως μητε εν τω [ουρανω]{.greek-abbr} οτι θρονος εστιν του [θεου]{.greek-abbr}[5:34]{.aside}

μητε εν τη γη οτι υποποδιον εστιν των ποδων αυτου μητε εις ιεροσολυμα οτι πολις εστιν του μεγαλου βασιλεως[5:35]{.aside}

μητε εν τη κεφαλη σου [ομοσης]{.greek-omitted} [ομωσεις]{.greek-added} οτι ου δυνασαι μιαν [τριχα]{.greek-omitted} [τριχαν]{.greek-added} λευκην [ποιησαι]{.greek-added} η μελαιναν [ποιησαι]{.greek-omitted}[5:36]{.aside}

εστω δε ο λογος υμων ναι ναι ου ου το δε περισσον τουτων εκ του πονηρου εστιν[5:37]{.aside}

ηκουσατε οτι ερρεθη οφθαλμον αντι οφθαλμου και οδοντα αντι οδοντος[5:38]{.aside}

εγω δε λεγω υμιν μη αντιστηναι τω πονηρω αλλ οστις σε [ραπισει]{.greek-omitted} [ραπιζει]{.greek-added} [επι]{.greek-omitted} [εις]{.greek-added} την δεξιαν [σου]{.greek-added} σιαγονα στρεψον αυτω και την αλλην[5:39]{.aside}

και τω [θελοντι]{.greek-omitted} [θελον]{.greek-added} [τι]{.greek-added} σοι κριθηναι και τον χιτωνα σου λαβειν αφες αυτω και το ιματιον[5:40]{.aside}

και οστις σε [αν]{.greek-added} αγγαρευσει [μιλιον]{.greek-omitted} [μηλιον]{.greek-added} εν υπαγε μετ αυτου δυο[5:41]{.aside}

τω αιτουντι σε διδου και τον θελοντα απο σου [δανεισασθαι]{.greek-omitted} [δανισασθαι]{.greek-added} μη [αποστραφης]{.greek-omitted} [αποστραφεις]{.greek-added}[5:42]{.aside}

ηκουσατε οτι ερρεθη αγαπησεις τον πλησιον σου και μισησεις τον εχθρον σου[5:43]{.aside}

εγω δε λεγω υμιν αγαπατε τους εχθρους υμων ευλογειτε τους καταρωμενους υμας καλως [ποιειτε]{.greek-omitted} [ποιητε]{.greek-added} τοις μισουσιν υμας και [προσευχεσθε]{.greek-omitted} [προσευχεσθαι]{.greek-added} υπερ των επηρεαζοντων υμας και διωκοντων υμας[5:44]{.aside}

οπως [γενησθε]{.greek-omitted} [γενεισθαι]{.greek-added} υιοι του [πατρος]{.greek-abbr} υμων του εν [τοις]{.greek-omitted} [ουρανοις]{.greek-abbr} οτι τον ηλιον αυτου ανατελλει επι πονηρους και αγαθους και βρεχει επι δικαιους και αδικους[5:45]{.aside}

εαν γαρ αγαπησητε τους αγαπωντας υμας τινα μισθον εχετε ουχι και οι τελωναι το αυτο ποιουσιν[5:46]{.aside}

και εαν [ασπασησθε]{.greek-omitted} [ασπασησθαι]{.greek-added} τους φιλους υμων μονον τι περισσον [ποιειτε]{.greek-omitted} [ποιητε]{.greek-added} ουχι και οι τελωναι ουτως ποιουσιν[5:47]{.aside}

[εσεσθε]{.greek-omitted} [εσεσθαι]{.greek-added} ουν υμεις [τελειοι]{.greek-omitted} [τελιοι]{.greek-added} [ωσπερ]{.greek-omitted} [ως]{.greek-added} ο [πατηρ]{.greek-abbr} υμων ο [εν]{.greek-omitted} [τοις]{.greek-omitted} [ουρανοις]{.greek-omitted} [[ουρανιος]{.greek-abbr}]{.greek-added} τελειος εστιν[5:48]{.aside}

### Chapter 6

[τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [ειπεν]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} [ημων]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [ο]{.greek-added} [[χριστος]{.greek-abbr}]{.greek-added} [τοις]{.greek-added} [εαυτου]{.greek-added} [μαθηταις]{.greek-added} [και]{.greek-added} [τοις]{.greek-added} [οχλοις]{.greek-added} προσεχετε την ελεημοσυνην υμων μη ποιειν εμπροσθεν των [ανθρωπων]{.greek-abbr} προς το θεαθηναι αυτοις ει δε [μηγε]{.greek-omitted} [μη]{.greek-added} [γε]{.greek-added} μισθον ουκ εχετε παρα τω [πατρι]{.greek-abbr} υμων τω εν τοις [ουρανοις]{.greek-abbr}[6:1]{.aside}

οταν ουν [ποιης]{.greek-omitted} [ποιεις]{.greek-added} ελεημοσυνην μη σαλπισης εμπροσθεν σου ωσπερ οι υποκριται ποιουσιν εν ταις συναγωγαις και εν ταις ρυμαις οπως δοξασθωσιν υπο των [ανθρωπων]{.greek-abbr} αμην λεγω υμιν απεχουσιν τον μισθον αυτων[6:2]{.aside}

σου δε ποιουντος ελεημοσυνην μη γνωτω η αριστερα σου τι ποιει η δεξια σου[6:3]{.aside}

οπως η σου η ελεημοσυνη εν τω κρυπτω και ο [πατηρ]{.greek-abbr} σου ο βλεπων εν τω κρυπτω [αυτος]{.greek-omitted} αποδωσει σοι εν τω φανερω[6:4]{.aside}

και οταν προσευχη ουκ εση ωσπερ οι υποκριται οτι φιλουσιν εν ταις συναγωγαις και εν ταις γωνιαις των πλατειων εστωτες προσευχεσθαι οπως αν [φανωσιν]{.greek-omitted} [φανωσι]{.greek-added} τοις [ανθρωποις]{.greek-abbr} αμην λεγω υμιν οτι [απεχουσιν]{.greek-omitted} [απεχουσι]{.greek-added} τον μισθον αυτων[6:5]{.aside}

συ δε οταν προσευχη εισελθε εις το ταμιειον σου και [κλεισας]{.greek-omitted} [κλισας]{.greek-added} την θυραν σου προσευξαι τω [πατρι]{.greek-abbr} [σου]{.corr} τω εν τω κρυπτω και ο [πατηρ]{.greek-abbr} σου ο βλεπων εν τω κρυπτω αποδωσει σοι εν τω φανερω[6:6]{.aside}

προσευχομενοι δε μη [βαττολογησητε]{.greek-omitted} [βαττωλογησειτε]{.greek-added} ωσπερ οι [εθνικοι]{.greek-omitted} [εθνηκοι]{.greek-added} [δοκουσιν]{.greek-omitted} [δοκουσι]{.greek-added} γαρ οτι εν τη πολυλογια αυτων εισακουσθησονται[6:7]{.aside}

μη ουν ομοιωθητε αυτοις οιδεν γαρ ο [πατηρ]{.greek-abbr} υμων ων [χρειαν]{.greek-omitted} [χριαν]{.greek-added} εχετε προ του υμας [αιτησαι]{.greek-omitted} [αιτισαι]{.greek-added} αυτον[6:8]{.aside}

ουτως ουν [προσευχεσθε]{.greek-omitted} [προσευχεσθαι]{.greek-added} υμεις [πατερ]{.greek-abbr} ημων ο εν τοις [ουρανοις]{.greek-abbr} αγιασθητω το ονομα σου[6:9]{.aside}

ελθετω η βασιλεια σου γενηθητω το θελημα σου ως εν [ουρανω]{.greek-abbr} και επι της γης[6:10]{.aside}

τον αρτον ημων [τον]{.corr} [ε]{.unclear}πιουσιον δος ημιν σημερον[6:11]{.aside}

και αφες ημιν τα [οφειληματα]{.greek-omitted} [οφιληματα]{.greek-added} ημων ως και ημεις αφιεμεν τοις [οφειλεταις]{.greek-omitted} [οφιλεταις]{.greek-added} ημων[6:12]{.aside}

και μη [εισενεγκης]{.greek-omitted} [εισενεγκεις]{.greek-added} ημας εις πειρασμον αλλα ρυσαι ημας απο του πονηρου οτι σου εστιν η βασιλεια και η δυναμις και η δοξα εις τους αιωνας αμην[6:13]{.aside}

εαν γαρ αφητε τοις ανθρωποις τα παραπτωματα αυτων αφησει και υμιν ο [πατηρ]{.greek-abbr} υμων ο [ουρανιος]{.greek-abbr} [τα]{.greek-added} [παραπτωματα]{.greek-added} [υμων]{.greek-added}[6:14]{.aside}

εαν δε μη αφητε τοις [ανθρωποις]{.greek-abbr} τα παραπτωματα αυτων ουδε ο [πατηρ]{.greek-abbr} υμων αφησει τα παραπτωματα υμων[6:15]{.aside}

[ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} [ημων]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [ο]{.greek-added} [[χριστος]{.greek-abbr}]{.greek-added} [ειπεν]{.greek-added} [τοις]{.greek-added} [εαυτου]{.greek-added} [μαθηταις]{.greek-added} [και]{.greek-added} [τοις]{.greek-added} [οχλοις]{.greek-added} οταν [δε]{.greek-omitted} [νηστευητε]{.greek-omitted} [νηστευηται]{.greek-added} μη [γινεσθε]{.greek-omitted} [γινεσθαι]{.greek-added} ωσπερ οι υποκριται σκυθρωποι [αφανιζουσιν]{.greek-omitted} [αφανιζουσι]{.greek-added} γαρ τα προσωπα αυτων οπως [φανωσιν]{.greek-omitted} [φανωσι]{.greek-added} τοις [ανθρωποις]{.greek-abbr} νηστευοντες αμην λεγω υμιν [οτι]{.greek-omitted} [απεχουσιν]{.greek-omitted} [απεχουσι]{.greek-added} τον μισθον αυτων[6:16]{.aside}

συ δε νηστευων [αλειψαι]{.greek-omitted} [αλιψαι]{.greek-added} σου την κεφαλην και το προσωπον σου νιψαι[6:17]{.aside}

οπως μη φανης τοις [ανθρωποις]{.greek-abbr} νηστευων αλλα τω [πατρι]{.greek-abbr} σου τω εν τω κρυπτω και ο [πατηρ]{.greek-abbr} σου ο βλεπων εν τω κρυπτω [αποδωσει]{.greek-omitted} [αποδωσι]{.greek-added} σοι[6:18]{.aside}

μη [θησαυριζετε]{.greek-omitted} [θησαυριζεται]{.greek-added} υμιν θησαυρους επι της γης οπου σης και βρωσις αφανιζει και οπου κλεπται [διορυσσ[ο]{.unclear}υσσουσιν]{.greek-added} [διορυσσουσιν]{.corr} και κλεπτουσιν[6:19]{.aside}

[θησαυριζετε]{.greek-omitted} [θησαυριζεται]{.greek-added} δε υμιν [θησαυρους]{.greek-omitted} [θησαυ]{.greek-added} [ρους]{.greek-added} εν [ουρανω]{.greek-abbr} οπου ουτε σης ουτε [βρωσις]{.greek-omitted} [βρωσης]{.greek-added} αφανιζει και οπου κλεπται ου διορυσσουσιν [ουδε]{.greek-omitted} [και]{.greek-added} κλεπτουσιν[6:20]{.aside}

οπου γαρ εστιν ο θησαυρος υμων εκει [εσται]{.greek-omitted} και η καρδια υμων [εσται]{.greek-added}[6:21]{.aside}

ο λυχνος του σωματος εστιν ο οφθαλμος εαν ουν ο οφθαλμος σου απλους [η]{.greek-omitted} ολον το σωμα σου [φωτεινον]{.greek-omitted} [φωτινον]{.greek-added} εσται[6:22]{.aside}

εαν δε ο οφθαλμος σου πονηρος η ολον το σωμα σου [σκοτεινον]{.greek-omitted} [σκοτινον]{.greek-added} εσται ει ουν το φως το εν σοι σκοτος εστιν το σκοτος ποσον[6:23]{.aside}

ουδεις δυναται [δυσιν]{.greek-omitted} [δυσι]{.greek-added} κυριοις δουλευειν η γαρ τον ενα μισησει και τον ετερον αγαπησει η ενος ανθεξεται και του ετερου καταφρονησει ου [δυνασθε]{.greek-omitted} [δυνασθαι]{.greek-added} [θεω]{.greek-abbr} δουλευειν και μαμωνα[6:24]{.aside}

δια τουτο λεγω υμιν μη μεριμνατε τη ψυχη υμων τι φαγητε και τι πιητε μηδε [το]{.greek-added} [τω]{.corr} σωματι υμων τι [ενδυσησθε]{.greek-omitted} [ενδυσησθαι]{.greek-added} ουχι η ψυχη πλειον εστιν της τροφης και το σωμα του ενδυματος[6:25]{.aside}

εμβλεψατε εις τα [πετεινα]{.greek-omitted} [πετινα]{.greek-added} του [ουρανου]{.greek-abbr} οτι ου σπειρουσιν ουδε θεριζουσιν ουδε συναγουσιν εις αποθηκας και ο [πατηρ]{.greek-abbr} υμων ο [ουρανιος]{.greek-abbr} τρεφει αυτα ουχ υμεις μαλλον [διαφερετε]{.greek-omitted} [διαφερεται]{.greek-added} αυτων[6:26]{.aside}

τις δε εξ υμων [μεριμνων]{.greek-omitted} [μεριμ]{.greek-added} [νων]{.greek-added} δυναται [προσθειναι]{.greek-omitted} [προσθηναι]{.greek-added} επι την ηλικιαν αυτου πηχυν ενα[6:27]{.aside}

και περι ενδυματος τι μεριμνατε καταμαθετε τα κρινα του αγρου πως αυξανει ου κοπια ουδε νηθει[6:28]{.aside}

[λε]{.greek-added} [λεγω]{.corr} [δε]{.greek-omitted} [γαρ]{.greek-added} υμιν [οτι]{.greek-omitted} ουδε σολομων εν παση τη δοξη αυτου [περιεβαλετο]{.greek-omitted} [περιεβαλλετο]{.greek-added} ως εν τουτων[6:29]{.aside}

ει δε τον χορτον του αγρου [σημερον]{.corr} οντα και αυριον εις [κλιβανον]{.greek-omitted} [κληβανον]{.greek-added} βαλλομενον ο [θεος]{.greek-abbr} [ουτως]{.greek-omitted} [ουτος]{.greek-added} αμφιεννυσιν ου πολλω μαλλον υμας ολιγοπιστοι[6:30]{.aside}

μη ουν [μεριμνησητε]{.greek-omitted} [μεριμνησειτε]{.greek-added} λεγοντες τι φαγωμεν η τι πιωμεν η τι [περιβαλλομεθα]{.greek-added} [περιβαλωμεθα]{.greek-omitted} [[περιβαλλωμεθα]{.corr}]{.greek-added}[6:31]{.aside}

παντα γαρ ταυτα τα εθνη [επιζητει]{.greek-omitted} [επιζητουσιν]{.greek-added} οιδεν γαρ ο [πατηρ]{.greek-abbr} υμων ο [ουρανιος]{.greek-abbr} οτι [χρηζετε]{.greek-omitted} [χριζετε]{.greek-added} τουτων απαντων[6:32]{.aside}

ζητειτε δε πρωτον την βασιλειαν του [θεου]{.greek-abbr} και την δικαιοσυνην αυτου και ταυτα παντα προστεθησεται υμιν[6:33]{.aside}

### Chapter 7

[εν]{.greek-added} [εκεινω]{.greek-added} [τω]{.greek-added} [καιρω]{.greek-added} [ειπεν]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} [ημων]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [ο]{.greek-added} [[χριστος]{.greek-abbr}]{.greek-added} [τοις]{.greek-added} [εαυτου]{.greek-added} [μαθηται]{.greek-added} [[μαθηταις]{.corr}]{.greek-added} [και]{.greek-added} [τοις]{.greek-added} [οχλοις]{.greek-added} μη κρινετε ινα μη κριθητε[7:1]{.aside}

εν ω γαρ κριματι κρινετε κριθησεσθε και εν ω μετρω μετρειτε [μετρηθησεται]{.greek-omitted} [μετριθησεται]{.greek-added} υμιν[7:2]{.aside}

τι δε βλεπεις το καρφος το εν τω οφθαλμω του αδελφου σου την δε εν τω σω οφθαλμω δοκον ου κατανοεις[7:3]{.aside}

η πω[ς]{.unclear} ερεις τω αδελφω σου αφες εκβαλω το καρφος [απο]{.greek-omitted} [εκ]{.greek-added} του οφθαλμου σου και ιδου η δοκος εν τω οφθαλμω σου[7:4]{.aside}

υποκριτα εκβαλε [πρωτον]{.greek-omitted} [πρω]{.greek-added} [τον]{.greek-added} την δοκον εκ του οφθαλμου σου και τοτε διαβλεψεις εκβαλειν το καρφος εκ του οφθαλμου του αδελφου σου[7:5]{.aside}

μη δωτε το αγιον τοις κυσιν μηδε [βαλητε]{.greek-omitted} [βαλειτε]{.greek-added} τους [μαργαρητας]{.greek-added} [μαργαριτας]{.greek-omitted} [[μαργαρειτας]{.corr}]{.greek-added} υμων εμπροσθεν των χοιρων μηποτε καταπατησωσιν αυτους [εν]{.greek-omitted} τοις ποσιν αυτων και στραφεντες ρηξωσιν υμας[7:6]{.aside}

αιτειτε και δοθησεται υμιν ζητειτε και [ευρησετε]{.greek-omitted} [ευρησεται]{.greek-added} κρουετε και ανοιγησεται υμιν[7:7]{.aside}

πας γαρ ο αιτων λαμβανει και ο ζητων ευρισκει και τω κρουοντι ανοιγησεται[7:8]{.aside}

η τις εστιν εξ υμων ανθρωπος ον εαν [αιτηση]{.greek-omitted} [αιτη]{.greek-added} [σει]{.greek-added} ο υιος αυτου αρτον μη λιθον επιδωσει αυτω[7:9]{.aside}

[η]{.greek-added} και [εαν]{.greek-omitted} ιχθυν [αιτηση]{.greek-omitted} [αιτησει]{.greek-added} μη οφιν επιδωσει αυτω[7:10]{.aside}

ει ουν υμεις πονηροι οντες οιδατε δοματα αγαθα διδοναι τοις τεκνοις υμων ποσω μαλλον ο [πατηρ]{.greek-abbr} υμων ο εν τοις [ουρανοις]{.greek-abbr} δωσει αγαθα τοις αιτουσιν αυτον[7:11]{.aside}

[εν]{.greek-added} [εκεινω]{.greek-added} [τω]{.greek-added} [καιρω]{.greek-added} [ειπεν]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} [ημων]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [ο]{.greek-added} [[χριστος]{.greek-abbr}]{.greek-added} [τοις]{.greek-added} [εαυτου]{.greek-added} [μαθηταις]{.greek-added} [και]{.greek-added} [τοις]{.greek-added} [οχλοις]{.greek-added} [εισελθετε]{.greek-omitted} [εισελθατε]{.greek-added} δια της στενης πυλης οτι πλατεια η πυλη και ευρυχωρος η οδος η απαγουσα εις την απωλειαν και πολλοι εισιν οι εισερ[χο]{.unclear}μενοι δι αυτης[7:13]{.aside}

[τι]{.greek-omitted} [τη]{.greek-added} στενη η πυλη και [τεθλιμμενη]{.greek-omitted} [τεθλημμενη]{.greek-added} η οδος η απαγουσα εις την ζωην και ολιγοι εισιν οι ευρισκοντες αυτην[7:14]{.aside}

[προσεχετε]{.greek-omitted} [προσεχεται]{.greek-added} δε απο των ψευδοπροφητων οιτινες ερχονται προς υμας εν [ενδυμασιν]{.greek-omitted} [ενδυμασι]{.greek-added} προβατων εσωθεν δε εισιν λυκοι αρπαγες[7:15]{.aside}

απο των καρπων αυτων [επιγνωσεσθε]{.greek-omitted} [επιγνωσεσθαι]{.greek-added} αυτους μητι συλλεγουσιν απο ακανθων σταφυλην η απο τριβολων συκα[7:16]{.aside}

ουτως παν δενδρον αγαθον καρπους καλους ποιει το δε σαπρον δενδρον καρπους πονηρους ποιει[7:17]{.aside}

ου [δυναται]{.greek-omitted} [δυνατε]{.greek-added} δενδρον αγαθον καρπους [πο]{.greek-added} [πονηρους]{.greek-omitted} [νηρους]{.greek-added} [ποι[―]{.gap}]{.greek-added} [ειν]{.greek-added} [ποιειν]{.corr} ουδε [δρον]{.greek-added} [δενδρον]{.corr} σαπρον καρπους καλους ποιειν[7:18]{.aside}

παν δενδρον μη ποιουν καρπον καλον εκκοπτεται και εις πυρ βαλλεται[7:19]{.aside}

αρα γε απο των καρπων αυτων επιγνωσεσθε αυτους[7:20]{.aside}

ου πας ο λεγων μοι [κυριε]{.greek-abbr} [κυριε]{.greek-abbr} εισελευσεται εις την βασιλειαν των [ουρανων]{.greek-abbr} αλλ ο ποιων το θελημα του [πατρος]{.greek-abbr} μου του εν [ουρανοις]{.greek-abbr}[7:21]{.aside}

πολλοι ερουσιν μοι εν εκεινη τη ημερα [κυριε]{.greek-abbr} [κυριε]{.greek-abbr} ου τω σω ονοματι προεφητευσαμεν και τω σω ονοματι δαιμονια εξεβαλομεν και τω σω ονοματι δυναμεις πολλας [εποιησαμεν]{.greek-omitted} [εποιη]{.greek-added} [σαμεν]{.greek-added}[7:22]{.aside}

και τοτε ομολογησω αυτοις οτι ουδεποτε εγνων υμας αποχωρειτε απ εμου οι [εργαζενοι]{.greek-added} [εργαζομενοι]{.corr} την ανομιαν[7:23]{.aside}

πας ουν οστις ακουει μου τους λογους τουτους και ποιει αυτους [ομοιωθησεται]{.greek-added} [ομοιωσω]{.greek-omitted} [αυτον]{.greek-omitted} ανδρι [φρονιμω]{.greek-omitted} [φρονημω]{.greek-added} οστις ωκοδομησεν την οικιαν αυτου επι την πετραν[7:24]{.aside}

και κατεβη η βροχη και ηλθον οι ποταμοι και επνευσαν οι ανεμοι και [προσεπεσον]{.greek-omitted} [προσεπεσαν]{.greek-added} τη οικια εκεινη και ουκ επεσεν τεθεμελιωτο γαρ επι την πετραν[7:25]{.aside}

και πας ο ακουων μου τους λογους τουτους και μη ποιων αυτους ομοιωθησεται ανδρι μωρω οστις ωκοδομησεν την οικιαν αυτου επι την αμμον [[αμμων]{.corr}]{.greek-added}[7:26]{.aside}

και κατεβη η βροχη και ηλθον οι ποταμοι και επνευσαν οι ανεμοι και προσεκοψαν τη οικια εκεινη και επεσεν και ην η πτωσις αυτης μεγαλη[7:27]{.aside}

και εγενετο οτε συνετελεσεν ο [ιησους]{.greek-abbr} τους λογους τουτους εξεπλησσοντο οι οχλοι επι τη διδαχη αυτου[7:28]{.aside}

ην γαρ διδασκων αυτους ως εξουσιαν εχων και ουχ ως οι γραμματεις [αυτων]{.greek-added}[7:29]{.aside}

### Chapter 8

[τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [καταβαντι]{.greek-omitted} [καταβαντος]{.greek-added} [δε]{.greek-omitted} [αυτω]{.greek-omitted} [του]{.greek-added} [[κυριου]{.greek-abbr}]{.greek-added} [ημων]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} [[χριστου]{.greek-abbr}]{.greek-added} απο του ορους ηκολουθησαν αυτω οχλοι πολλοι[8:1]{.aside}

και ιδου λεπρος ελθων προσεκυνει αυτω λεγων [κυριε]{.greek-abbr} εαν [θελης]{.greek-omitted} [θελεις]{.greek-added} δυνασαι με καθαρισαι[8:2]{.aside}

και εκτεινας την χειρα ηψατο αυτου ο [ιησους]{.greek-abbr} λεγων θελω καθαρισθητι και ευθεως εκαθαρισθη αυτου η λεπρα[8:3]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} ορα μηδενι [ειπης]{.greek-omitted} [ειπεις]{.greek-added} [αλλα]{.greek-omitted} [αλλ]{.greek-added} υπαγε σεαυτον δειξον τω ιερει και προσενεγκε το δωρον ο προσεταξεν [μωσης]{.greek-omitted} [μωυσης]{.greek-added} εις μαρτυριον αυτοις[8:4]{.aside}

εισελθοντι δε [αυτω]{.greek-omitted} [αυτου]{.greek-added} εις [καπερναουμ]{.greek-omitted} [καφαρναουμ]{.greek-added} προσηλθεν αυτω [εκατονταρχος]{.greek-omitted} [εκατονταρχης]{.greek-added} παρακαλων αυτον[8:5]{.aside}

και λεγων [κυριε]{.greek-abbr} ο παις μου βεβληται εν τη οικια παραλυτικος δεινως βασανιζομενος[8:6]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} εγω ελθων θεραπευσω αυτον[8:7]{.aside}

και αποκριθεις ο εκατονταρχος εφη [κυριε]{.greek-abbr} ουκ ειμι ικανος ινα μου υπο την στεγην εισελθης αλλα μονον ειπε λογω και ιαθησεται ο παις μου[8:8]{.aside}

και γαρ εγω [ανθρωπος]{.greek-abbr} ειμι υπο εξουσιαν εχων υπ εμαυτον στρατιωτας και λεγω τουτω πορευθητι και πορευεται και αλλω ερχου και ερχεται και τω δουλω μου ποιησον τουτο και ποιει[8:9]{.aside}

ακουσας δε ο [ιησους]{.greek-abbr} εθαυμασεν και ειπεν τοις ακολουθουσιν [αυτω]{.greek-added} αμην λεγω υμιν ουδε εν τω [ισραηλ]{.greek-abbr} τοσαυτην πιστιν ευρον[8:10]{.aside}

λεγω δε υμιν οτι πολλοι απο ανατολων και δυσμων ηξουσιν και [ανακλιθησονται]{.greek-omitted} [ανακληθησονται]{.greek-added} μετα αβρααμ και ισαακ και ιακωβ εν τη βασιλεια των [ουρανων]{.greek-omitted} [[ου]{.greek-abbr}νων]{.greek-added}[8:11]{.aside}

οι δε υιοι της βασιλειας εκβληθησονται εις το σκοτος το εξωτερον εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[8:12]{.aside}

και ειπεν ο [ιησους]{.greek-abbr} τω [εκατονταρχη]{.greek-omitted} [εκατονταρχω]{.greek-added} υπαγε και ως επιστευσας γενηθητω σοι και ιαθη ο παις αυτου εν τη ωρα εκεινη [και]{.greek-added} [παντες]{.greek-added} [εθαυμαζον]{.greek-added} [και]{.greek-added} [εδοξαζον]{.greek-added} [τον]{.greek-added} [[θεον]{.greek-abbr}]{.greek-added}[8:13]{.aside}

[τω]{.greek-added} [και]{.greek-omitted} [καιρω]{.greek-added} [εκεινω]{.greek-added} ελθων ο [[κυριος]{.greek-abbr}]{.greek-added} [ημων]{.greek-added} [ιησους]{.greek-abbr} [ο]{.greek-added} [[χριστος]{.greek-abbr}]{.greek-added} εις την οικιαν πετρου ειδεν την πενθεραν αυτου βεβλημενην και πυρεσσουσαν[8:14]{.aside}

και ηψατο της χειρος αυτης και αφηκεν αυτην ο πυρετος και ηγερθη και διηκονει [αυτω]{.greek-omitted} [αυτοις]{.greek-added}[8:15]{.aside}

οψιας δε γενομενης προσηνεγκαν αυτω δαιμονιζομενους πολλους και εξεβαλεν τα [πνευματα]{.greek-abbr} λογω και παντας τους κακως εχοντας εθεραπευσεν[8:16]{.aside}

οπως πληρωθη το ρηθεν δια ησαιου του προφητου λεγοντος αυτος τας ασθενειας ημων [ελαβεν]{.greek-omitted} [ελα]{.greek-added} [βεν]{.greek-added} και τας νοσους εβαστασεν[8:17]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} πολλους οχλους περι αυτον εκελευσεν απελθειν εις το περαν[8:18]{.aside}

και προσελθων εις γραμματευς ειπεν αυτω διδασκαλε ακολουθησω σοι οπου εαν απερχη[8:19]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} αι αλωπεκες φωλεους εχουσιν και τα πετεινα του [ουρανου]{.greek-abbr} κατασκηνωσεις ο δε υιος του [ανθρωπου]{.greek-abbr} ουκ εχει που την κεφαλην κλινη[8:20]{.aside}

ετερος δε των μαθητων αυτου ειπεν αυτω [κυριε]{.greek-abbr} επιτρεψον μοι πρωτον απελθειν και θαψαι τον [πατερα]{.greek-abbr} μου[8:21]{.aside}

ο δε [ιησους]{.greek-abbr} [ειπεν]{.greek-omitted} [λεγει]{.greek-added} αυτω ακολουθει μοι και αφες τους νεκρους θαψαι τους εαυτων [ν]{.greek-added} νεκρους[8:22]{.aside}

και εμβαντι αυτω εις [το]{.greek-omitted} πλοιον ηκολουθησαν αυτω οι μαθηται αυτου[8:23]{.aside}

και ιδου σεισμος μ[ε]{.unclear}γας εγενετο εν τη θαλασση ωστε το πλοιον καλυπτεσθαι υπο των κυματων αυτος δε εκαθευδεν[8:24]{.aside}

και προσελθοντες [οι]{.greek-omitted} [μαθηται]{.greek-omitted} ηγειραν αυτον λεγοντες [κυριε]{.greek-abbr} σωσον ημας απολλυμεθα[8:25]{.aside}

και λεγει αυτοις τι [δειλοι]{.greek-omitted} [δηλοι]{.greek-added} εστε ολιγοπιστοι τοτε εγερθεις επετιμησεν τοις ανεμοις και τη θαλασση και εγενετο γαληνη μεγαλη[8:26]{.aside}

οι δε [ανθρωποι]{.greek-abbr} εθαυμασαν λεγοντες ποταπος εστιν ουτος οτι και οι ανεμοι και η [θα]{.greek-added} [θαλασσα]{.greek-omitted} [λασσα]{.greek-added} υπακουουσιν αυτω[8:27]{.aside}

[και]{.greek-omitted} [ελθοντι]{.greek-omitted} [αυτω]{.greek-omitted} [ελθων]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} [ημων]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [ο]{.greek-added} [[χριστος]{.greek-abbr}]{.greek-added} εις το περαν εις την χωραν των γεργεσηνων υπηντησαν αυτω δυο δαιμονιζομενοι εκ των μνημειων εξερχομενοι χαλεποι λιαν ωστε μη ισχυειν τινα παρελθειν δια της οδου εκεινης[8:28]{.aside}

και ιδου εκραξαν λεγοντες τι ημιν και σοι [ιησου]{.greek-abbr} υιε του [θεου]{.greek-abbr} ηλθες ωδε προ καιρου βασανισαι ημας[8:29]{.aside}

ην δε μακραν απ αυτων αγελη χοιρων πολλων βοσκομενη[8:30]{.aside}

οι δε δαιμονες παρεκαλουν αυτον λεγοντες ει εκβαλλεις ημας [αποστειλον]{.greek-added} [ημας]{.greek-added} [επιτρεψον]{.greek-omitted} [ημιν]{.greek-omitted} [απελθειν]{.greek-omitted} εις την αγελην των χοιρων[8:31]{.aside}

και ειπεν αυτοις υπαγετε οι δε εξελθοντες απηλθον εις την αγελην των χοιρων και ιδου ωρμησεν [πασα]{.greek-omitted} η αγελη [πασα]{.greek-added} [των]{.greek-omitted} [χοιρων]{.greek-omitted} κατα του κρημνου εις την θαλασσαν και απεθανον εν τοις υδασιν[8:32]{.aside}

οι δε βοσκοντες εφυγον και απελθοντες εις την πολιν απηγγειλαν παντα και τα των δαιμονιζομενων[8:33]{.aside}

και ιδου πασα η πολις εξηλθεν [αντησιν]{.greek-added} [εις]{.corr} [συναντησιν]{.corr} τω [ιησου]{.greek-abbr} και ιδοντες αυτον παρεκαλεσαν [αυτον]{.greek-added} οπως μεταβη απο των οριων αυτων[8:34]{.aside}

### Chapter 9

και εμβας εις [το]{.greek-omitted} πλοιον διεπερασεν και ηλθεν εις την ιδιαν πολιν[9:1]{.aside}

και ιδου προσεφερον αυτω παραλυτικον επι κλινης βεβλημενον και ιδων ο [ιησους]{.greek-abbr} την πιστιν αυτων ειπεν τω παραλυτικω θαρσει τεκνον [αφεωνται]{.greek-omitted} [αφεονται]{.greek-added} [σοι]{.greek-omitted} [σου]{.greek-added} αι αμαρτιαι [σου]{.greek-omitted}[9:2]{.aside}

και ιδου τινες των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} ειπον εν εαυτοις ουτος βλασφημει[9:3]{.aside}

και [ιδων]{.greek-omitted} [ειδως]{.greek-added} ο [ιησους]{.greek-abbr} τας ενθυμησεις αυτων ειπεν [ινα]{.greek-omitted} [ινατι]{.greek-added} [τι]{.greek-omitted} υμεις ενθυμεισθε πονηρα εν ταις καρδιαις υμων[9:4]{.aside}

τι γαρ εστιν ευκοπωτερον ειπειν αφεωνται σου αι αμαρτιαι η ειπειν [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} και περιπατει[9:5]{.aside}

ινα δε ειδητε οτι εξουσιαν εχει ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} επι της γης αφιεναι αμαρτιας τοτε λεγει τω παραλυτικω εγερθεις αρον σου την κλινην και υπαγε εις τον οικον σου[9:6]{.aside}

και εγερθεις απηλθεν εις τον οικον αυτου[9:7]{.aside}

ιδοντες δε οι οχλοι εθαυμασαν και εδοξασαν τον [θεον]{.greek-abbr} [τον]{.greek-omitted} [δοντα]{.greek-omitted} [εξουσιαν]{.greek-omitted} [τοιαυτην]{.greek-omitted} [τοις]{.greek-omitted} [ανθρωποις]{.greek-omitted}[9:8]{.aside}

[και]{.greek-omitted} παραγων ο [[κυριος]{.greek-abbr}]{.greek-added} [ημων]{.greek-added} [ιησους]{.greek-abbr} [εκειθεν]{.greek-omitted} [ο]{.greek-added} [[χριστος]{.greek-abbr}]{.greek-added} ειδεν [ανθρωπον]{.greek-abbr} [καθημενον]{.greek-omitted} [καθιμενον]{.greek-added} επι το τελωνιον ματθαιον λεγομενον και λεγει αυτω ακολουθει μοι και αναστας ηκολουθησεν αυτω[9:9]{.aside}

και εγενετο αυτου ανακειμενου εν τη οικια και ιδ[ο]{.unclear}υ πολλοι [τελωναι]{.greek-omitted} [τελω]{.greek-added} [ναι]{.greek-added} και αμαρτωλοι [ελθοντες]{.greek-omitted} συνανεκειντο τω [ιησου]{.greek-abbr} και τοις μαθηταις αυτου[9:10]{.aside}

και ιδοντες οι [φαρισαιοι]{.greek-omitted} [φαρεισαιοι]{.greek-added} ειπον τοις μαθηταις αυτου δια τι μετα των τελωνων και αμαρτωλων [εσθιει]{.greek-omitted} ο διδασκαλος υμων [εσθιει]{.greek-added}[9:11]{.aside}

ο δε [ιησους]{.greek-abbr} ακουσας ειπεν αυτοις ου χρειαν εχουσιν οι ισχυοντες ιατρου αλλ οι κακως εχοντες[9:12]{.aside}

πορευθεντες δε μαθετε τι εστιν ελεον θελω και ου θυσιαν ου γαρ ηλθον [δικαιους]{.greek-added} καλεσαι [δικαιους]{.greek-omitted} αλλα αμαρτωλους [εις]{.greek-omitted} [μετανοιαν]{.greek-omitted}[9:13]{.aside}

τοτε προσερχονται αυτω οι μαθηται ιωαννου λεγοντες δια τι ημεις και οι [φαρισαιοι]{.greek-omitted} [φαρεισαιοι]{.greek-added} νηστευομεν πολλα οι δε μαθηται σου ου [νηστευτευουσιν]{.greek-added} [νηστευουσιν]{.corr}[9:14]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} μη δυνανται οι υιοι του νυμφωνος πενθειν εφ οσον μετ αυτων εστιν ο νυμφιος ελευσονται δε ημεραι οταν απαρθη απ αυτων ο νυμφιος και τοτε νηστευσουσιν[9:15]{.aside}

ουδεις δε επιβαλλει επιβλημα [ρακκου]{.greek-added} [ρακους]{.greek-omitted} [[ρακκους]{.corr}]{.greek-added} αγναφου επι ιματιω παλαιω αιρει γαρ το πληρωμα αυτου απο του ιματιου και χειρον σχισμα γινεται[9:16]{.aside}

ουδε βαλλουσιν οινον νεον εις ασκους παλαιους ει δε [μηγε]{.greek-omitted} [μη]{.greek-added} [γε]{.greek-added} ρηγνυνται οι ασκοι και ο οινος εκχειται και οι ασκοι απολουνται αλλα [βαλλουσιν]{.greek-omitted} οινον [νεον]{.corr} εις ασκους [βαλλουσιν]{.greek-added} καινους και αμφοτεροι συντηρουνται[9:17]{.aside}

[ταυτα]{.greek-omitted} [αυτου]{.greek-omitted} [λαλουντος]{.greek-omitted} [αυτοις]{.greek-omitted} [ιδου]{.greek-omitted} [προσελθων]{.greek-added} [τω]{.greek-added} [[κυριω]{.greek-abbr}]{.greek-added} [ημων]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} [[χριστω]{.greek-abbr}]{.greek-added} αρχων [εις]{.greek-omitted} [ελθων]{.greek-omitted} προσεκυνει αυτω λεγων οτι η θυγατηρ μου [ετελευτησεν]{.greek-added} αρτι [ετελευτησεν]{.greek-omitted} αλλα ελθων επιθες την χειρα σου επ αυτην και ζησεται[9:18]{.aside}

και εγερθεις ο [ιησους]{.greek-abbr} ηκολουθησεν αυτω και οι μαθηται αυτου[9:19]{.aside}

και ιδου γυνη αιμορροουσα δωδεκα ετη προσελθουσα οπισθεν ηψατο του κρασπεδου του ιματιου αυτου[9:20]{.aside}

ελεγεν γαρ εν εαυτη εαν μονον αψωμαι του ιματιου αυτου [σωθησωμαι]{.greek-added} [σωθησομαι]{.corr}[9:21]{.aside}

ο δε [ιησους]{.greek-abbr} [επιστραφεις]{.greek-omitted} [στραφεις]{.greek-added} και ιδων αυτην ειπεν θαρσει θυγατερ η πιστις σου σεσωκεν σε και [εσωθη]{.greek-omitted} [ιαθη]{.greek-added} η γυνη απο της ωρας εκεινης[9:22]{.aside}

και ελθων ο [ιησους]{.greek-abbr} εις την οικιαν του αρχοντος και ιδων τους αυλητας και τον οχλον θορυβουμενον[9:23]{.aside}

λεγει αυτοις αναχωρειτε ου γαρ απεθανεν το κορασιον αλλα καθευδει και κατεγελων αυτου[9:24]{.aside}

οτε δε εξεβληθη ο οχλος εισελθων εκρατησεν της χειρος αυτης και ηγερθη το κορασιον[9:25]{.aside}

και εξηλθεν η φημη [αυτη]{.greek-omitted} [αὕτη]{.greek-added} εις ολην την γην εκεινην [και]{.greek-added} [παντες]{.greek-added} [εθαυμαζον]{.greek-added} [και]{.greek-added} [εδοξαζον]{.greek-added} [τον]{.greek-added} [[θεον]{.greek-abbr}]{.greek-added}[9:26]{.aside}

[και]{.greek-omitted} [παραγοντι]{.greek-omitted} [παραγων]{.greek-added} [εκειθεν]{.greek-omitted} [τω]{.greek-omitted} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} [ημων]{.greek-added} [ιησου]{.greek-omitted} [[ιησους]{.greek-abbr}]{.greek-added} [ο]{.greek-added} [[χριστος]{.greek-abbr}]{.greek-added} ηκολουθησαν αυτω δυο τυφλοι κραζοντες και λεγοντες ελεησον ημας [υιε]{.greek-omitted} [υιος]{.greek-added} [δαυιδ]{.greek-abbr}[9:27]{.aside}

ελθοντι δε εις την οικιαν προσηλθον αυτω οι τυφλοι και λεγει αυτοις ο [ιησους]{.greek-abbr} πιστευετε οτι [δυναμαι]{.greek-omitted} [δυναμε]{.greek-added} τουτο ποιησαι λεγουσιν αυτω ναι [κυριε]{.greek-abbr}[9:28]{.aside}

τοτε ηψατο των [οφθαλμων]{.greek-omitted} [οφθαλ]{.greek-added} [μων]{.greek-added} αυτων λεγων κατα την πιστιν υμων [γενηθητω]{.greek-omitted} [γεννηθητω]{.greek-added} υμιν[9:29]{.aside}

και ανεωχθησαν αυτων οι οφθαλμοι και ενεβριμησατο αυτοις ο [ιησους]{.greek-abbr} λεγων ορατε μηδεις γινωσκετω[9:30]{.aside}

οι δε εξελθοντες [διεφημισαν]{.greek-omitted} [διεφημησαν]{.greek-added} αυτον εν ολη τη γη εκεινη[9:31]{.aside}

[[και]{.corr}]{.greek-added} [εξερχομενων]{.greek-added} [δε]{.greek-added} αυτων [δε]{.greek-omitted} [εξερχομενων]{.greek-omitted} ιδου προσηνεγκαν αυτω [ανθρωπον]{.greek-abbr} κωφον [και]{.greek-added} δαιμονιζομενον[9:32]{.aside}

και εκβληθεντος του δαιμονιου ελαλησεν ο κωφος και εθαυμασαν οι οχλοι λεγοντες ουδεποτε εφανη ουτως εν τω [ισραηλ]{.greek-abbr}[9:33]{.aside}

οι δε [φαρισαιοι]{.greek-omitted} [φαρεισαιοι]{.greek-added} ελεγον εν τω αρχοντι των δαιμονιων εκβαλλει τα δαιμονια[9:34]{.aside}

και περιηγεν ο [ιησους]{.greek-abbr} τας πολεις πασας και τας κωμας διδασκων εν ταις συναγωγαις αυτων και κηρυσσων το ευαγγελιον της βασιλειας και θεραπευων πασαν νοσον και πασαν μαλακιαν [εν]{.greek-omitted} [τω]{.greek-omitted} [λαω]{.greek-omitted}[9:35]{.aside}

### Chapter 10

[ειπεν]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} [ημων]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [ο]{.greek-added} [[χριστος]{.greek-abbr}]{.greek-added} [τοις]{.greek-added} [εαυτου]{.greek-added} [μαθηταις]{.greek-added} ιδου εγω αποστελλω υμας ως προβατα [εν]{.greek-omitted} [μεσω]{.greek-omitted} [εμμεσω]{.greek-added} λυκων γινεσθε ουν [φρονιμοι]{.greek-omitted} [φρονημοι]{.greek-added} ως [οι]{.greek-omitted} οφεις και [ακεραιοι]{.greek-omitted} [ακερεοι]{.greek-added} [ωσει]{.greek-added} [ως]{.greek-omitted} [αι]{.greek-omitted} περιστεραι[10:16]{.aside}

προσεχετε δε απο των [ανθρωπων]{.greek-abbr} παραδωσουσιν γαρ υμας εις συνεδρια και εν ταις συναγωγαις αυτων μαστιγωσουσιν υμας[10:17]{.aside}

και επι ηγεμονας δε και βασιλεις [αχθησεσθε]{.greek-omitted} [αχθησεσθαι]{.greek-added} ενεκεν εμου εις μαρτυριον αυτοις και τοις [εθνεσιν]{.greek-omitted} [εθνε]{.greek-added}[10:18]{.aside}

[οτ]{.unclear}[αν]{.greek-supplied} [δε]{.greek-supplied} [παραδιδωσιν]{.greek-omitted} [[παραδωσιν]{.greek-supplied}]{.greek-added} υμα[ς]{.unclear} [μη]{.greek-supplied} [μεριμνησητε]{.greek-omitted} [[μεριμνη]{.greek-supplied}σειτα[ι]{.greek-supplied}]{.greek-added} [πως]{.greek-supplied} [η]{.greek-supplied} [τι]{.greek-supplied} [λαλησητε]{.greek-omitted} [δοθησεται]{.greek-omitted} [γαρ]{.greek-omitted} [υμιν]{.greek-omitted} [εν]{.greek-omitted} [εκεινη]{.greek-omitted} [τη]{.greek-omitted} [ωρα]{.greek-omitted} [τι]{.greek-omitted} [λαλησετε]{.greek-omitted} [[λαλη]{.greek-supplied}σειτε]{.greek-added}[10:19]{.aside}

ου γαρ [υμεις]{.greek-supplied} [εστε]{.greek-omitted} [[εσ]{.greek-supplied}[τα]{.unclear}ι]{.greek-added} ο[ι]{.greek-supplied} [λα]{.greek-supplied}λου[ντες]{.greek-supplied} [αλλα]{.greek-supplied} το [πνευμα]{.greek-abbr} το[υ]{.greek-supplied} [[πατρος]{.greek-abbr}]{.greek-supplied} [υμ]{.greek-supplied}ων το λαλ[ο]{.unclear}[υν]{.greek-supplied} [ε]{.greek-supplied}[ν]{.unclear} [υμιν]{.unclear}[10:20]{.aside}

παρα[δωσε]{.greek-supplied}ι δε αδελφος α[δελφ]{.greek-supplied}ον εις θανατον [και]{.greek-supplied} [[πατηρ]{.greek-abbr}]{.greek-supplied} τεκνον και [επανα]{.greek-supplied}στησονται τε[κνα]{.greek-supplied} [επι]{.greek-supplied} [γονεις]{.greek-supplied} και θα[να]{.greek-supplied}τω[σ]{.greek-supplied}ουσιν αυτο[υς]{.unclear}[10:21]{.aside}

και [εσεσθε]{.greek-omitted} [εσε[σ]{.unclear}θαι]{.greek-added} μι[σου]{.greek-supplied}μενοι υπο [π]{.unclear}αντων δια το ονο[μ]{.unclear}[α]{.greek-supplied} μου ο δε υπομεινας ε[ις]{.greek-supplied} [τε]{.greek-supplied}λος ουτος σωθησεται[10:22]{.aside}

[μη]{.greek-omitted} [ουν]{.greek-omitted} [φοβηθητε]{.greek-omitted} [αυτους]{.greek-omitted} [ουδεν]{.greek-omitted} γαρ εστιν κεκαλυμμεν[ον]{.unclear} ο ουκ αποκαλυφ[θη]{.greek-supplied}σεται και κρυπτον [ο]{.greek-supplied} [ο]{.greek-supplied}υ γνωσ[θ]{.unclear}ησεται[10:26]{.aside}

[ο]{.greek-supplied} [λεγω]{.greek-supplied} [υμ]{.greek-supplied}[ι]{.unclear}ν [ε]{.unclear}ν τη [σκ]{.unclear}ο[τια]{.greek-supplied} [ειπα]{.greek-supplied}τε εν τω φω[τι]{.greek-supplied} [και]{.greek-supplied} ο εις το ους [ακουετε]{.greek-supplied} [κηρυξατε]{.greek-supplied} [επι]{.greek-supplied} [των]{.greek-supplied} [δωματων]{.greek-supplied}[10:27]{.aside}

[και]{.greek-supplied} [μη]{.greek-supplied} [φοβεισ]{.greek-supplied}θε [α]{.unclear}πο των [αποκτενοντων]{.greek-omitted} [[αποκτεννον]{.greek-supplied}των]{.greek-added} το σω[μ]{.greek-supplied}[α]{.unclear} [τ]{.unclear}ην [δε]{.greek-supplied} [ψυ]{.greek-supplied}[χ]{.unclear}ην μη δυναμε[ν]{.unclear}ω[ν]{.greek-supplied} [α]{.greek-supplied}ποκτειναι φοβη[θη]{.greek-supplied}τε δε μαλλον το[ν]{.unclear} δυναμ[ενον]{.greek-supplied} και [την]{.greek-omitted} ψυχ[η]{.unclear}ν και [το]{.greek-omitted} [σω]{.unclear}[μα]{.greek-supplied} α[π]{.unclear}ολεσαι εν γεεννη[10:28]{.aside}

ου[χ]{.unclear}ι [δ]{.unclear}υο [σ]{.unclear}τρ[ο]{.unclear}υ[θι]{.unclear}α ασσαριου [πωλειται]{.unclear} και εν [εξ]{.unclear} αυτω[ν]{.unclear} [ου]{.greek-supplied} [πεσειται]{.greek-supplied} επι την γη[ν]{.greek-supplied} [ανευ]{.greek-supplied} [του]{.greek-supplied} [πατρος]{.greek-abbr} υμων[10:29]{.aside}

[υ]{.unclear}[μων]{.greek-supplied} [δε]{.greek-supplied} [κ]{.unclear}αι αι τριχες [τ]{.unclear}[η]{.greek-supplied}[ς]{.unclear} [κεφαλης]{.greek-omitted} [[κεφα]{.greek-supplied}]{.greek-added} [λης]{.greek-added} πασαι ηριθμημεναι εισιν[10:30]{.aside}

μη ουν [φοβηθητε]{.greek-omitted} [[φ]{.unclear}[οβει]{.greek-supplied}σθε]{.greek-added} πολλων στρ[ου]{.greek-supplied}θιων διαφερετε [υ]{.greek-supplied}με[ι]{.unclear}ς[10:31]{.aside}

πας ου[ν]{.unclear} [οστις]{.greek-supplied} ο[μ]{.unclear}[ο]{.greek-supplied}λογησει εν εμ[οι]{.greek-supplied} [εμπροσ]{.greek-supplied}θεν των [ανθρωπων]{.greek-abbr} [ομο]{.unclear}λογησω [καγω]{.greek-supplied} [εν]{.greek-supplied} [αυ]{.greek-supplied}τω εμπροσ[θεν]{.greek-supplied} [του]{.greek-supplied} [πατρος]{.greek-abbr} μου τ[ου]{.greek-supplied} [εν]{.greek-supplied} [[τοις]{.greek-supplied}]{.greek-added} [[ουρανοις]{.greek-abbr}]{.greek-supplied}[10:32]{.aside}

οστις δ αν [αρνησηται]{.greek-supplied} με εμ[προσθεν]{.greek-supplied} των [ανθρωπων]{.greek-abbr} [αρνησομ]{.greek-supplied}αι [καγω]{.greek-added} αυτον [καγω]{.greek-omitted} [εμπροσθ]{.greek-supplied}εν του [πατρος]{.greek-abbr} [μου]{.greek-supplied} [τ]{.unclear}ου εν ουρ[αν]{.greek-supplied}οις[10:33]{.aside}

[τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [ειπεν]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} [ημων]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [ο]{.greek-added} [[χριστος]{.greek-abbr}]{.greek-added} [τοις]{.greek-added} [εαυτου]{.greek-added} [μαθηταις]{.greek-added} [και]{.greek-added} [τοις]{.greek-added} [οχλοις]{.greek-added} ο φιλων [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} υπερ εμε ουκ εστιν μου αξιος και ο φιλων υιον η θυγατερα υπερ εμε ουκ εστιν μου αξιος[10:37]{.aside}

και ος ου λαμβανει τον [σταυρον]{.greek-abbr} αυτου και ακολουθει οπισω μου ουκ εστιν μου αξιος[10:38]{.aside}

ο ευρων την ψυχην αυτου απολεσε[ι]{.unclear} αυ[τη]{.unclear}ν και ο απολεσας την ψυχην αυτου εν[ε]{.unclear}κεν εμου ευρησει αυτην[10:39]{.aside}

ο δεχομενος υμας εμε δεχεται και ο εμε δεχομενος δεχεται τον αποστειλαντα με[10:40]{.aside}

ο δεχομενος προφητην εις ονομα προφητου μισθον προφητου [ληψεται]{.greek-omitted} [λημψεται]{.greek-added} και ο δεχομενος δικαιον εις ονομα δικαιου μισθον δικαιου [ληψεται]{.greek-omitted} [λημψεται]{.greek-added}[10:41]{.aside}

και ος [εαν]{.greek-omitted} [αν]{.greek-added} ποτιση ενα των μικρων τουτων ποτηριον ψυχρου μονον εις ονομα μαθητου αμην λεγω υμιν ου μη απολεση τον μισθον αυτου[10:42]{.aside}

### Chapter 11

[ο]{.greek-omitted} [δε]{.greek-omitted} [εν]{.greek-added} [εκεινω]{.greek-added} [τω]{.greek-added} [καιρω]{.greek-added} [ακουσας]{.greek-added} ιωαννης [ακουσας]{.greek-omitted} εν τω δεσμωτηριω τα εργα του [[κυριου]{.greek-abbr}]{.greek-added} [ημων]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} [χριστου]{.greek-abbr} πεμψας [δυο]{.greek-omitted} [δια]{.greek-added} των μαθητων αυτου[11:2]{.aside}

ειπεν αυτω συ ει ο ερχομενος η ετερον [προσ]{.greek-added} [προσδοκωμεν]{.greek-omitted} [δοκωμεν]{.greek-added}[11:3]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις πορευθεντες απαγγειλατε ιωαννη α ακουετε και βλεπετε[11:4]{.aside}

τυφλοι αναβλεπουσιν [κα]{.unclear}ι χω[λ]{.unclear}οι περιπατουσιν λ[ε]{.unclear}προι καθαριζονται και κωφοι ακουουσιν νεκροι εγειρονται και πτωχοι ευαγγελιζονται[11:5]{.aside}

και μακαριος εστιν ος εαν μη σκανδαλισθη εν εμοι[11:6]{.aside}

τουτων δε πορευομενων ηρξατο ο [ιησους]{.greek-abbr} [λεγειν]{.greek-omitted} τοι[ς]{.unclear} οχλοις [λεγειν]{.greek-added} περι ιωαννου τι [εξηλθετε]{.greek-omitted} [εξηλθατε]{.greek-added} εις την ερημον θεασασθαι καλαμον υπο ανεμου σαλευομενον[11:7]{.aside}

αλλα τι [εξηλθετε]{.greek-omitted} [εξηλθατ[ε]{.unclear}]{.greek-added} ιδειν [ανθρωπον]{.greek-abbr} εν μαλακοις ιματιοις [ημφιεσμενον]{.greek-omitted} [ημφιε]{.greek-added} [σμενον]{.greek-added} ιδου οι τα μαλακα φορουντες εν τοις ο[ι]{.unclear}κοις των [βασιλειων]{.greek-omitted} [βασιλεων]{.greek-added} εισιν[11:8]{.aside}

αλλα τι [εξηλθετε]{.greek-omitted} [εξηλθατε]{.greek-added} ιδειν προφητην ναι λεγω υμιν και περισσοτερον προφητου[11:9]{.aside}

ουτος γαρ εστιν περι ου γεγραπται ιδου εγω αποστελλω [τ[ο]{.unclear}[ν]{.greek-supplied}]{.corr} [αγ[γ]{.unclear}[ε]{.greek-supplied}λο[ν]{.unclear}]{.corr} μου προ προσωπου σου ος κατασκευασει την οδον σου εμπροσθεν σου[11:10]{.aside}

αμην λεγω υμιν ουκ [εγηγερται]{.greek-omitted} [εγει[γ]{.unclear}ερ[τ]{.unclear}αι]{.greek-added} εν γεννητοις γυναι[κ]{.unclear}ων [μειζων]{.greek-omitted} [μειζον]{.greek-added} ιωαννου του βαπτιστου ο δε μικροτερος εν τη βασ[ι]{.greek-supplied}λεια των [ουρανων]{.greek-abbr} [μειζων]{.greek-omitted} [μειζον]{.greek-added} αυτου εστιν[11:11]{.aside}

απο δε των ημερων ιωαννου του βαπτιστου εως αρτι η βασιλεια των [ουρανων]{.greek-abbr} βιαζεται και βιασται αρπαζουσιν αυτην[11:12]{.aside}

παντες γαρ οι προφηται και ο νομος εως ιωαννου προεφητευσαν[11:13]{.aside}

και ει θελετε [δεξασθαι]{.greek-omitted} [δεξασθε]{.greek-added} αυτος εστιν ηλιας ο μελλων ερχεσθαι[11:14]{.aside}

ο εχων ωτα ακουειν ακουετω[11:15]{.aside}

[εν]{.greek-omitted} [εκεινω]{.greek-omitted} [τω]{.greek-omitted} [καιρω]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} [εξομολογουμαι]{.greek-omitted} [σοι]{.greek-omitted} [πατερ]{.greek-abbr} [κυριε]{.greek-abbr} [του]{.greek-supplied} [[ουρανου]{.greek-abbr}]{.greek-supplied} και της [γης]{.greek-supplied} [οτι]{.greek-supplied} [απεκρυψας]{.greek-omitted} [[ε]{.greek-supplied}κρυψ[ας]{.greek-supplied}]{.greek-added} [ταυτα]{.greek-supplied} [απο]{.greek-supplied} σοφων κ[αι]{.greek-supplied} [συνετων]{.greek-supplied} και απεκαλ[υψας]{.greek-supplied} [αυ]{.greek-supplied}τα νηπιοις[11:25]{.aside}

[ν]{.unclear}[αι]{.greek-supplied} [ο]{.greek-supplied} [[πατηρ]{.greek-abbr}]{.greek-supplied} οτι ουτως ε[γ]{.unclear}[ενετο]{.greek-supplied} ευδοκια εμ[πρ]{.unclear}[οσθεν]{.greek-supplied} σου[11:26]{.aside}

[παντα]{.greek-supplied} [μοι]{.greek-supplied} [παρεδοθη]{.greek-omitted} [[παρε]{.greek-supplied}δω[θ]{.greek-supplied}η]{.greek-added} υπ[ο]{.greek-supplied} [του]{.greek-supplied} [πατρος]{.greek-abbr} μου και ου[δεις]{.greek-supplied} επιγι[ν]{.greek-supplied}ωσκει τον [υιον]{.greek-abbr} [ει]{.greek-supplied} [μ]{.greek-supplied}η ο [πατηρ]{.greek-abbr} ουδε τον [πατερα]{.greek-abbr} [τις]{.greek-omitted} [επιγινωσκει]{.greek-omitted} ει μη ο [υιος]{.greek-abbr} και ω ε[α]{.unclear}[ν]{.greek-supplied} [β]{.unclear}ουληται ο [υιος]{.greek-abbr} αποκαλυψαι[11:27]{.aside}

δευτε προς με παντ[ες]{.greek-supplied} οι κοπιωντες και [π]{.unclear}[ε]{.greek-supplied}φορτισμενοι καγ[ω]{.unclear} [ανα]{.greek-supplied}[π]{.unclear}αυσω υμας[11:28]{.aside}

[αρατ]{.greek-supplied}ε τον ζυγον μου [εφ]{.greek-supplied} [υ]{.unclear}μας και μαθετ[ε]{.greek-supplied} [α]{.greek-supplied}[π]{.unclear} εμου οτι [πραος]{.greek-omitted} [πρα[υς]{.greek-supplied}]{.greek-added} [ε]{.greek-supplied}[ι]{.unclear}μι [και]{.corr} [ταπεινος]{.greek-omitted} [[τ[απι]{.unclear}νος]{.corr}]{.greek-added} [τη]{.corr} [καρδια]{.corr} [και]{.greek-supplied} [ευρησετε]{.greek-omitted} [[ε]{.greek-supplied}υρησεται]{.greek-added} αναπαυ[σιν]{.greek-supplied} [τ]{.unclear}αις ψυχαις υμων[11:29]{.aside}

[ο]{.greek-supplied} [γα]{.greek-supplied}[ρ]{.unclear} [ζ]{.unclear}υγος μου χρη[σ]{.unclear}[τος]{.greek-supplied} [κ]{.unclear}αι το φορτιο[ν]{.unclear} [μου]{.greek-supplied} [ελ]{.greek-supplied}[α]{.unclear}φ[ρ]{.greek-supplied}ον εστιν[11:30]{.aside}

### Chapter 12

[και]{.greek-omitted} [μεταβας]{.greek-omitted} [εκειθεν]{.greek-omitted} [ηλθεν]{.greek-omitted} [ελθων]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} [ημων]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [ο]{.greek-added} [[χριστος]{.greek-abbr}]{.greek-added} εις την συναγωγην [αυτων]{.greek-omitted}[12:9]{.aside}

και ιδου [ανθρωπος]{.greek-abbr} ην [εκει]{.greek-added} την χειρα εχων ξηραν και επηρωτησαν αυτον λεγοντες ει εξεστιν τοις σαββασιν θεραπευειν ινα κατηγορησωσιν αυτου[12:10]{.aside}

ο δε ειπεν αυτοις τις [εσται]{.greek-omitted} [εστιν]{.greek-added} εξ υμων [ανθρωπος]{.greek-abbr} ος εξει προβατον εν και εαν εμπεση τουτο τοις σαββασιν εις βοθυνον ουχι κρατησει [ατο]{.greek-added} [αυτο]{.corr} και εγερει [[εγειρει]{.corr}]{.greek-added}[12:11]{.aside}

ποσω ουν διαφερει [ανθρωπος]{.greek-abbr} προβατου ωστε εξεστιν τοις σαββασιν καλως ποιειν[12:12]{.aside}

τοτε λεγει τω [ανθρωπω]{.greek-abbr} εκτεινον [σου]{.greek-added} την χειρα [σου]{.greek-omitted} και εξετεινεν και [αποκατεσταθη]{.greek-omitted} [απεκατεσταθη]{.greek-added} υγιης ως η αλλη[12:13]{.aside}

οι δε [φαρισαιοι]{.greek-omitted} [φαρεισαιοι]{.greek-added} [συμβουλιον]{.corr} ελαβον κατ αυτου [εξελθοντες]{.greek-omitted} οπως αυτον απολεσωσιν[12:14]{.aside}

ο δε [ιησους]{.greek-abbr} γνους ανεχωρησεν εκειθεν και ηκολουθησαν αυτω οχλοι πολλοι και εθεραπευσεν αυτους παντας[12:15]{.aside}

και επετιμησεν αυτοις ινα μη φανερον αυτον ποιησωσιν[12:16]{.aside}

οπως πληρωθη το ρηθεν δια ησαιου του προφητου λεγοντος[12:17]{.aside}

ιδου ο παις μου ον [ηρετισα]{.greek-omitted} [ηρετησα]{.greek-added} ο αγαπητος μου εις ον ευδοκησεν η ψυχη μου θησω το [πνευμα]{.greek-abbr} μου επ αυτον και κρισιν τοις εθνεσιν απαγγελει[12:18]{.aside}

ουκ ερισει ουδε κραυγασει ουδε ακουσει τις εν ταις πλατειαις την φωνην αυτου[12:19]{.aside}

καλαμον συντετριμμενον ου κατεαξει και λινον τυφομενον ου σβεσει εως αν [εκβαλη]{.greek-omitted} [εκβαλει]{.greek-added} εις νικος την κρισιν[12:20]{.aside}

και τω ονοματι αυτου εθνη ελπιουσιν[12:21]{.aside}

τοτε προσηνεχθη αυτω δαιμονιζομενος τυφλος και κωφος και εθεραπευσεν αυτον ωστε τον [κωφον]{.greek-added} [και]{.greek-added} τυφλον [και]{.greek-omitted} [κωφον]{.greek-omitted} και λαλειν και βλεπειν [και]{.greek-added} [παντες]{.greek-added} [εθαυμαζον]{.greek-added} [και]{.greek-added} [εδοξαζον]{.greek-added} [τον]{.greek-added} [[θεον]{.greek-abbr}]{.greek-added}[12:22]{.aside}

### Chapter 13

[οτε]{.greek-omitted} [δε]{.greek-omitted} [εβλαστησεν]{.greek-omitted} [ο]{.greek-omitted} [χορτος]{.greek-omitted} [και]{.greek-omitted} [καρπον]{.greek-omitted} [εποιησεν]{.greek-omitted} [τοτε]{.greek-supplied} [εφανη]{.greek-supplied} [κ]{.greek-supplied}αι τα [ζιζανια]{.greek-supplied}[13:26]{.aside}

[προσ]{.greek-supplied}ελθον[τες]{.greek-supplied} [δε]{.greek-supplied} [οι]{.greek-supplied} [δουλοι]{.greek-supplied} του [οικοδεσποτου]{.greek-omitted} [ειπον]{.greek-omitted} [αυτω]{.greek-omitted} [κυριε]{.greek-omitted} [ουχι]{.greek-omitted} [καλον]{.greek-omitted} [σπερμα]{.greek-omitted} [εσπειρας]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [σω]{.greek-omitted} [αγρω]{.greek-omitted} [ποθεν]{.greek-omitted} [ουν]{.greek-omitted} [εχει]{.greek-omitted} [ζιζανια]{.greek-omitted}[13:27]{.aside}

[αφετε]{.greek-omitted} [συναυξανεσθαι]{.greek-omitted} [αμφοτερα]{.greek-omitted} [μεχρι]{.greek-omitted} [του]{.greek-omitted} [θερισμου]{.greek-omitted} [και]{.greek-omitted} εν [τ[ω]{.greek-supplied}]{.greek-added} [καιρω]{.greek-supplied} [του]{.greek-supplied} [θε]{.greek-supplied}ρισμ[ου]{.greek-supplied} [ερω]{.greek-supplied} [τοις]{.greek-supplied} [θε]{.greek-supplied}ριστ[αις]{.greek-supplied} [συλλεξατε]{.greek-omitted} [πρωτον]{.greek-omitted} [τα]{.greek-omitted} [ζιζανια]{.greek-omitted} [και]{.greek-omitted} [δησατε]{.greek-omitted} [αυτα]{.greek-omitted} [εις]{.greek-omitted} [δεσμας]{.greek-omitted} [προς]{.greek-omitted} [το]{.greek-omitted} [κατακαυσαι]{.greek-omitted} [αυτα]{.greek-omitted} [τον]{.greek-omitted} [δε]{.greek-omitted} [σιτον]{.greek-omitted} [συναγαγετε]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [αποθηκην]{.greek-omitted} [μου]{.greek-omitted}[[13:30 *(lacunose)*]{.lacunose}]{.aside}

[τοτε]{.greek-omitted} [αφεις]{.greek-omitted} [τους]{.greek-omitted} [οχλους]{.greek-omitted} [ηλθεν]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} οικιαν ο [ιησους]{.greek-abbr} και προσηλθον αυτω οι μαθηται αυτου λεγοντες φρασον ημιν την παραβολην των ζιζανιων του αγρου[13:36]{.aside}

ο δε αποκριθεις ειπεν αυτοις ο σπειρων το καλον σπερμα εστιν ο υιος του [ανθρωπου]{.greek-abbr}[13:37]{.aside}

ο δε αγρος εστιν ο κοσμος το δε καλον σπερμα ουτοι εισιν οι υιοι της βασιλειας τα δε ζιζανια εισιν οι υιοι του πονηρου[13:38]{.aside}

ο δε εχθρος ο σπειρας αυτα εστιν ο διαβολος ο δε θερισμος συντελεια του αιωνος εστιν οι δε θερισται αγγελοι εισιν[13:39]{.aside}

ωσπερ ουν [συλλεγεται]{.greek-omitted} [συλλεγετε]{.greek-added} τα ζιζανια και πυρι [καιεται]{.greek-omitted} [και]{.greek-added} [εται]{.greek-added} ουτως εσται εν τη συντελεια του αιωνος τουτου[13:40]{.aside}

αποστελει ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} τους αγγελους αυτου και συλλεξουσιν εκ της βασιλειας αυτου παντα τα σκανδαλα και τους ποιουντας την ανομιαν[13:41]{.aside}

και βαλουσιν αυτους εις την καμινον του πυρος εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[13:42]{.aside}

τοτε οι δικαιοι εκλαμψουσιν ως ο ηλιος εν τη βασιλεια του [πατρος]{.greek-abbr} αυτων ο εχων ωτα ακουειν ακουετω[13:43]{.aside}

[παλιν]{.greek-omitted} [εν]{.greek-added} [εκεινω]{.greek-added} [τω]{.greek-added} [καιρω]{.greek-added} [ειπεν]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} [ημων]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [[χριστος]{.greek-abbr}]{.greek-added} [τοις]{.greek-added} [εαυτου]{.greek-added} [μαθηταις]{.greek-added} [και]{.greek-added} [τοις]{.greek-added} [οχλοις]{.greek-added} [την]{.greek-added} [παραβολην]{.greek-added} [ταυτην]{.greek-added} ομοια εστιν η βασιλεια των [ουρανων]{.greek-abbr} θησαυρω κ[ε]{.unclear}κρυμμενω εν [τω]{.greek-omitted} αγρω ον ευρων [ανθρωπος]{.greek-abbr} εκρυψεν και απο της χαρας αυτου υπαγει και παντα οσα εχει πωλει και αγοραζει τον αγρον εκεινον[13:44]{.aside}

παλιν ομοια εστιν η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} εμπορω ζητουντι καλους [μαργαριτας]{.greek-omitted} [μαργαρητας]{.greek-added}[13:45]{.aside}

ος ευρων ενα πολυτιμον [μαργαριτην]{.greek-omitted} [μαργαρητην]{.greek-added} απελθων πεπρακεν παντα οσα ειχεν και ηγορασεν αυτον[13:46]{.aside}

παλιν ομοια εστιν η βασιλεια των [ουρανων]{.greek-abbr} σαγηνη [βληθειση]{.greek-omitted} [βληθεισα]{.greek-added} εις την θαλασσαν και εκ παντος γενους συναγαγουση[13:47]{.aside}

ην οτε [επληρωθη]{.greek-omitted} [αναβιβασαντες]{.greek-omitted} [επι]{.greek-omitted} [επ]{.greek-added} [τον]{.greek-omitted} [αιγιαλον]{.greek-omitted} [και]{.greek-omitted} [καθισαντες]{.greek-omitted} [συνελεξαν]{.greek-omitted} [τα]{.greek-omitted} [καλα]{.greek-omitted} [εις]{.greek-omitted} [αγγεια]{.greek-omitted} [τα]{.greek-omitted} [δε]{.greek-omitted} [σαπρα]{.greek-omitted} [εξω]{.greek-omitted} [εβαλον]{.greek-omitted}[13:48]{.aside}

### Chapter 14

εν εκεινω τω καιρω ηκουσεν ηρωδης ο [τετραρχης]{.greek-omitted} [τετρααρχης]{.greek-added} την ακοην [ιησου]{.greek-abbr}[14:1]{.aside}

και ειπεν τοις παισιν αυτου ουτο[ς]{.greek-supplied} [εστ]{.greek-supplied}[ι]{.unclear}ν ιωαννης ο βαπτιστ[η]{.unclear}ς αυτος η[γερθ]{.unclear}[η]{.greek-supplied} [απο]{.unclear} των νεκρων [και]{.unclear} δια τουτ[ο]{.unclear} αι [δυνα]{.unclear}[μ]{.unclear}εις ενεργουσιν εν αυτω[14:2]{.aside}

ο γαρ ηρωδης κρατησας τον [ι]{.unclear}ωαννην ε[δ]{.unclear}ησεν αυτον και εθ[ε]{.unclear}το εν φυλακη δια ηρωδιαδα την γυναικα φιλιππου του α[δ]{.unclear}ελφου αυτου[14:3]{.aside}

ελεγεν γαρ αυτω ο ιωαννης ουκ εξεστιν σοι εχειν αυτην[14:4]{.aside}

και θελων αυτον αποκτειναι εφοβηθη τον οχλον οτι ως προφητην αυτον ειχον[14:5]{.aside}

γενεσιων δε αγομενων του ηρωδου ωρχησατο η θυγατηρ της ηρωδιαδος εν τω μεσω και ηρεσεν τω ηρωδη[14:6]{.aside}

οθεν με[θ]{.unclear} ορκου [ωμολογησεν]{.greek-omitted} [ομολογησεν]{.greek-added} αυτη δουναι ο εαν [αιτησηται]{.greek-omitted} [αιτ[η]{.unclear}σειται]{.greek-added}[14:7]{.aside}

η δε [προβιβασθεισα]{.greek-omitted} [προβιβασθησα]{.greek-added} υπο της [μητρος]{.greek-abbr} αυτης δος μοι φησιν ωδε επι πινακι την κεφαλην ιωαννου του βαπτιστου[14:8]{.aside}

και ελυπηθη ο βασιλευς δια δε τους ορκους και τους συνανακειμενους εκελευσεν δοθηναι[14:9]{.aside}

και πεμψας [απεκεφαλισεν]{.greek-omitted} [απεκεφαλησεν]{.greek-added} τον ιωαννην εν τη φυλακη[14:10]{.aside}

και ηνεχθη η κεφαλη αυτου επι [πινακι]{.greek-omitted} [πινακει]{.greek-added} και εδοθη τω κορασιω και ηνεγκεν τη [μητρι]{.greek-abbr} αυτης[14:11]{.aside}

και προσελθοντες οι μαθηται αυτου ηραν το [σωμα]{.greek-omitted} [πτωμα]{.greek-added} και εθαψαν αυτο και ελθοντες απηγγειλαν τω [ιησου]{.greek-abbr}[14:12]{.aside}

[και]{.greek-omitted} εξελθων ο [[κυριος]{.greek-abbr}]{.greek-added} [ημων]{.greek-added} [ιησους]{.greek-abbr} [ο]{.greek-added} [[χριστος]{.greek-abbr}]{.greek-added} ειδεν πολυν οχλον και εσπλαγχνισθη επ αυτοις και εθεραπευσεν τους αρρωστους αυτων[14:14]{.aside}

οψιας δε γενομενης προσηλθον αυτω οι μαθηται [αυτου]{.greek-omitted} λεγοντες ερημος εστιν ο τοπος και η ωρα [παρηλθεν]{.greek-added} ηδη [παρηλθεν]{.greek-omitted} απολυσον τους οχλους ινα απελθοντες εις τας κωμας αγορασωσιν εαυτοις βρωματα[14:15]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ου χρει[α]{.unclear}ν εχουσιν απελθειν δοτε αυτοις υμει[ς]{.unclear} φαγειν[14:16]{.aside}

οι δε [γουσιν]{.greek-added} [λεγουσιν]{.corr} αυτω ουκ εχομεν ωδε ει μη πεντε αρτους και δυο ιχθυας[14:17]{.aside}

ο δε ειπεν φερετε μοι αυτους ωδε[14:18]{.aside}

και κελευσας [τους]{.greek-omitted} [τοις]{.greek-added} [οχλους]{.greek-omitted} [οχλοις]{.greek-added} [ανακλιθηναι]{.greek-omitted} [ανακληθηναι]{.greek-added} επι τους χορτους λαβων τους πεντε αρτους και τους δυο ιχθυας αναβλεψας εις τον [ουρανον]{.greek-abbr} ευλογησεν και κλασας εδωκεν τοις μαθηταις τους αρτους οι δε μαθηται τοις οχλοις[14:19]{.aside}

και εφαγον παντες και εχορτασθησαν και ηραν το περισσευον των κλασματων δωδεκα κοφινους πληρεις[14:20]{.aside}

οι δε εσθιοντες ησαν ανδρες [ωσει]{.greek-omitted} [ως]{.greek-added} πεντακισχιλιοι χωρις γυναικων και παιδιων [και]{.greek-added} [παντες]{.greek-added} [εθαυμαζον]{.greek-added} [και]{.greek-added} [εδοξαζον]{.greek-added} [τον]{.greek-added} [[θεον]{.greek-abbr}]{.greek-added}[14:21]{.aside}

[και]{.greek-omitted} [ευθεως]{.greek-omitted} ηναγκασεν ο [[κυριος]{.greek-abbr}]{.greek-added} [ημων]{.greek-added} [ιησους]{.greek-abbr} [ο]{.greek-added} [[χριστος]{.greek-abbr}]{.greek-added} τους μαθητας [αυτου]{.greek-added} εμβηναι εις [το]{.greek-omitted} πλοιον και προαγειν αυτον εις το περαν εως ου [απολυση]{.greek-omitted} [απολυσει]{.greek-added} τους οχλους[14:22]{.aside}

και απολυσας τους οχλους ανεβη εις το ορος κατ ιδιαν προσευξασθαι οψιας δε γενομενης μονος ην εκει[14:23]{.aside}

το δε πλοιον ηδη μεσον της θαλασσης ην βασανιζομενον υπο των κυματων ην γαρ εναντιος ο ανεμος[14:24]{.aside}

τεταρτη δε φυλακη της νυκτος [απηλθεν]{.greek-omitted} [ηλθεν]{.greek-added} προς αυτους [ο]{.greek-omitted} [ιησους]{.greek-omitted} περιπατων επι [της]{.greek-omitted} [την]{.greek-added} [θαλασσης]{.greek-omitted} [θαλασσαν]{.greek-added}[14:25]{.aside}

και ιδοντες αυτον οι μαθηται επι [την]{.greek-omitted} [της]{.greek-added} [θαλασσαν]{.greek-omitted} [θαλασσης]{.greek-added} περιπατουντα εταραχθησαν λεγοντες οτι φαντασμα εστιν και [α]{.greek-added} [απο]{.greek-omitted} [πο]{.greek-added} του φοβου εκραξαν[14:26]{.aside}

ευθεως δε ελαλησεν αυτοις ο [ιησους]{.greek-abbr} λεγων θαρσειτε εγω ειμι μη φοβεισθε[14:27]{.aside}

αποκριθεις δε αυτω ο πετρος ειπεν [κυριε]{.greek-abbr} ει συ ει κελευσον με [ελθειν]{.greek-added} προς σε [ελθειν]{.greek-omitted} επι τα υδατα[14:28]{.aside}

ο δε [[ιησους]{.greek-abbr}]{.greek-added} ειπεν ελθε και καταβας απο του πλοιου ο πετρος περιεπατησεν επι τα υδατα ελθειν προς τον [ιησουν]{.greek-abbr}[14:29]{.aside}

βλεπων δε τον ανεμον ισχυρον εφοβηθη και αρξαμενος καταποντιζεσθαι εκραξεν λεγων [κυριε]{.greek-abbr} σωσον με[14:30]{.aside}

ευθεως δε ο [ιησους]{.greek-abbr} εκτεινας την χειρα επελαβετο αυτου και λεγει αυτω ολιγοπιστε εις τι εδιστασας[14:31]{.aside}

και εμβαντων αυτων εις το πλοιον εκοπασεν ο ανεμος[14:32]{.aside}

οι δε εν τω πλοιω ελθοντες προσεκυνησαν αυτω λεγοντες αληθως [θεου]{.greek-abbr} [υιος]{.greek-abbr} ει[14:33]{.aside}

και διαπερασαντες ηλθον [εις]{.greek-omitted} [επι]{.greek-added} την γην [εις]{.greek-added} γεννησαρετ[14:34]{.aside}

και [επιγνοντες]{.greek-omitted} [επιγνωντες]{.greek-added} αυτον οι ανδρες του τοπου εκεινου απεστειλαν εις ολην την περιχωρον εκεινην και προσηνεγκαν αυτω παντας τους κακως εχοντας[14:35]{.aside}

και παρεκαλουν αυτον ινα μονον αψωνται του κρασπεδου του ιματιου αυτου και οσοι [αν]{.greek-added} ηψαντο [διεσωθησαν]{.greek-omitted} [εσωθησαν]{.greek-added} [και]{.greek-added} [παντες]{.greek-added} [εθαυμαζον]{.greek-added} [και]{.greek-added} [εδοξαζον]{.greek-added} [τον]{.greek-added} [[θεον]{.greek-abbr}]{.greek-added}[14:36]{.aside}

### Chapter 15

[και]{.greek-omitted} εξελθων [εκειθεν]{.greek-omitted} ο [[κυριος]{.greek-abbr}]{.greek-added} [ημων]{.greek-added} [ιησους]{.greek-abbr} [ο]{.greek-added} [[χριστος]{.greek-abbr}]{.greek-added} ανεχωρησεν εις τα [μερη]{.greek-omitted} [μερι]{.greek-added} τυρου και σιδωνος[15:21]{.aside}

και ιδου γυνη χαναναια απο των οριων εκεινων εξελθουσα [εκραυγασεν]{.greek-omitted} [εκραυγαζεν]{.greek-added} [αυτω]{.greek-omitted} λεγουσα ελεησον με [κυριε]{.greek-abbr} υιε [δαυιδ]{.greek-omitted} [δαυειδ]{.greek-added} η θυγατηρ μου κακως δαιμονιζεται[15:22]{.aside}

ο δε ουκ απεκριθη αυτη λογον και προσελθοντες οι μαθηται αυτου ηρωτων αυτον λεγοντες απολυσον αυτην οτι κραζει [οπισθεν]{.greek-omitted} [εμπροσθεν]{.greek-added} ημων[15:23]{.aside}

ο δε αποκριθεις ειπεν ουκ απεσταλην ει μη εις τα προβατα τα απολωλοτα οικου [ισραηλ]{.greek-abbr}[15:24]{.aside}

η δε ελθουσα προσεκυνησεν αυτω λεγουσα [κυριε]{.greek-abbr} βοηθει μοι[15:25]{.aside}

ο δε αποκριθεις ειπεν ουκ εστιν καλον λαβειν τον αρτον των τεκνων και βαλειν τοις κυναριοις[15:26]{.aside}

η δε ειπεν ναι [κυριε]{.greek-abbr} και γαρ τα κυναρια εσθιει απο των ψιχιων των πιπτοντων απο της τραπεζης των κυριων αυτων[15:27]{.aside}

τοτε αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτη ω γυναι μεγαλη σου η πιστις γενηθητω σοι ως θελεις και ιαθη η θυγατηρ αυτης απο της ωρας εκεινης[15:28]{.aside}

και μεταβας εκειθεν ο [ιησους]{.greek-abbr} ηλθεν παρα την θαλασσαν της γαλιλαιας και αναβας εις το ορο[ς]{.unclear} [ε]{.unclear}καθητο εκει[15:29]{.aside}

και προσηλθον αυτω οχλοι πολλοι εχοντες μεθ εαυτων [κωφους]{.greek-added} [τυφλους]{.greek-added} χωλους [τυφλους]{.greek-omitted} [κωφους]{.greek-omitted} κυλλους και ετερους πολλους και ερριψαν [α]{.greek-supplied}υτους παρα τους ποδας [του]{.greek-omitted} [αυτου]{.greek-added} [ιησου]{.greek-omitted} και εθεραπευσεν αυτους[15:30]{.aside}

ωστε τους οχλους θαυμασαι βλεποντας κωφους λαλουντας κυλλους υγιεις [και]{.greek-added} χωλους περιπατουντας και τυφλους βλεποντας και εδοξασαν τον [θεον]{.greek-abbr} [ισραηλ]{.greek-abbr}[15:31]{.aside}

[προσκαλεσαμενος]{.greek-added} ο [δε]{.greek-omitted} [[κυριος]{.greek-abbr}]{.greek-added} [ημων]{.greek-added} [ιησους]{.greek-abbr} [προσκαλεσαμενος]{.greek-omitted} [ο]{.greek-added} [[χριστος]{.greek-abbr}]{.greek-added} τους μαθ[η]{.unclear}τας [αυτου]{.greek-omitted} ειπεν σπλαγχνιζομαι επι τον οχλον ο[τι]{.unclear} ηδη [ημε]{.greek-added} [ημεραι]{.corr} τρεις προσμενουσ[ιν]{.unclear} μοι και ουκ εχουσιν τι φαγωσιν και απολυσαι αυτους νηστεις [ο]{.unclear}υ θελω [μη]{.greek-added} [μηποτ[ε]{.unclear}]{.corr} εκλυθω[σ]{.unclear}ιν εν τη οδω[15:32]{.aside}

και λεγουσιν αυτω οι μαθηται αυτο[υ]{.unclear} ποθεν ημιν εν ερημια [α]{.unclear}ρτοι τοσουτοι ωστε [χορ]{.greek-added} [χορτασαι]{.greek-omitted} [οχλον]{.greek-omitted} [τοσουτον]{.greek-omitted}[15:33]{.aside}

[και]{.greek-omitted} [εφαγον]{.greek-omitted} [παντες]{.greek-omitted} [και]{.greek-omitted} [εχορτασθησαν]{.greek-omitted} [και]{.greek-omitted} [ηραν]{.greek-omitted} [το]{.greek-omitted} [περισσευον]{.greek-omitted} [των]{.greek-omitted} [κλασμ]{.greek-supplied}[ατ]{.unclear}ων [επτ]{.unclear}α [σπυριδ]{.greek-supplied}ας πληρεις[15:37]{.aside}

[οι]{.greek-supplied} [δε]{.greek-supplied} [εσθιοντ]{.greek-supplied}ες ησαν [αν[δρες]{.greek-supplied}]{.greek-added} [τετ]{.greek-supplied}ρακισχιλιοι [ανδρες]{.greek-omitted} [χωρις]{.greek-supplied} [γυ]{.greek-supplied}[ν]{.unclear}αικων και [παιδιων]{.greek-supplied} [και]{.greek-added} [παντες]{.greek-added} [ε[θαυμαζ]{.greek-supplied}ον]{.greek-added} [και]{.greek-added} [δεδοξαζον]{.greek-added}[15:38]{.aside}

### Chapter 16

[τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} ελθων [δε]{.greek-omitted} ο [[κυριος]{.greek-abbr}]{.greek-added} [ημων]{.greek-added} [ιησους]{.greek-abbr} [ο]{.greek-added} [[χριστος]{.greek-abbr}]{.greek-added} εις τα μερη καισαρειας της φιλιππου ηρωτα τους μαθητας αυτου λεγων τινα με λεγουσιν οι [ανθρωποι]{.greek-abbr} ειναι τον υιον του [ανθρωπου]{.greek-abbr}[16:13]{.aside}

οι δε ειπον οι μεν ιωαννην τον βαπτιστην αλλοι δε ηλιαν ετεροι δε ιερεμιαν η ενα των προφητων[16:14]{.aside}

λεγει αυτοις υμεις δε τινα με λεγετε ειναι[16:15]{.aside}

αποκριθεις δε σιμων πετρος ειπεν συ ει ο [χριστος]{.greek-abbr} ο [υιος]{.greek-abbr} [τ]{.unclear}[ο]{.greek-supplied}[υ]{.unclear} [θεου]{.greek-abbr} του ζωντος[16:16]{.aside}

[και]{.greek-omitted} αποκριθεις ο [ιησους]{.greek-abbr} ειπεν [αυ]{.unclear}[τω]{.greek-supplied} μακαριος ει σιμων βαριωνα οτι σαρξ και αιμα ουκ απεκαλυψεν σοι αλλ ο [πατηρ]{.greek-abbr} μου ο εν τοις ουρανοις[16:17]{.aside}

καγω δε σοι λεγω οτι συ ει πετρος και επι ταυτη τη πετρα οικοδομησω μου την εκκλησιαν και πυλαι [αδου]{.greek-omitted} ου κατισχυσουσιν αυτης[16:18]{.aside}

και δωσω σοι τας κλεις της βασιλειας των [ουρανων]{.greek-abbr} και ο εαν δησης επι της [γης]{.corr} εσται δεδεμενον εν [τοις]{.greek-omitted} [ουρανοις]{.greek-omitted} [τω]{.greek-added} [ουρανω]{.greek-added} και ο εαν λυσης επι της γης εσται λελυμενον εν τοις ουρανοις[16:19]{.aside}

[αμην]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [[τω]{.greek-supplied}]{.greek-added} [[καιρω]{.greek-supplied}]{.greek-added} [ε[κ]{.unclear}εινω]{.greek-added} [[ειπεν]{.greek-supplied}]{.greek-added} [[ο]{.greek-supplied}]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} [ημων]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [[ο]{.greek-supplied}]{.greek-added} [[χριστος]{.greek-abbr}]{.greek-added} [[τοις]{.greek-supplied}]{.greek-added} [[εαυτο]{.greek-supplied}υ]{.greek-added} [μα[θηταις]{.greek-supplied}]{.greek-added} [ει]{.greek-supplied}σιν [τ]{.unclear}ινες [[των]{.greek-supplied}]{.greek-added} [ωδε]{.greek-supplied} [εστωτες]{.greek-omitted} [[ε]{.greek-supplied}σ[τ]{.unclear}ωτων]{.greek-added} [οιτινες]{.greek-supplied} [ου]{.greek-supplied} μη γευσων[ται]{.greek-supplied} [θ]{.greek-supplied}[αν]{.unclear}ατου εως [αν]{.greek-supplied} [ιδω]{.greek-supplied}σιν τον [υιον]{.greek-abbr} [του]{.greek-supplied} [ανθρωπου]{.greek-abbr} ερχομενον [εν]{.greek-supplied} [τ]{.greek-supplied}η βασιλεια αυτου[16:28]{.aside}

### Chapter 17

[και]{.greek-supplied} [μεθ]{.greek-supplied} [η]{.unclear}μερας εξ [παρ]{.greek-supplied}[α]{.unclear}λαμβανει ο [ιησους]{.greek-abbr} [τον]{.greek-supplied} [π]{.unclear}ετρον και [τον]{.greek-added} [ιακωβ]{.greek-supplied}ον και ιωαν[νην]{.greek-supplied} [τον]{.greek-supplied} [α]{.unclear}δελφον [αυτου]{.greek-supplied} [κ]{.greek-supplied}αι αναφε[ρει]{.greek-supplied} [αυτους]{.greek-supplied} [ει]{.unclear}ς ορος [υψηλον]{.greek-supplied} [κα]{.greek-supplied}τ ιδιαν[17:1]{.aside}

και [μετεμορ]{.greek-supplied}[φ]{.unclear}ωθη ε[μ]{.unclear}[προσθε]{.greek-supplied}[ν]{.unclear} αυτων [και]{.greek-supplied} [ελα]{.greek-supplied}[μ]{.unclear}ψεν το προσ[ω]{.unclear}[πον]{.greek-supplied} [αυτ]{.greek-supplied}ου ως ο ηλιο[ς]{.greek-supplied} [τα]{.greek-supplied} [δε]{.greek-supplied} [ι]{.greek-supplied}ματια αυ[του]{.greek-supplied} [εγενοντο]{.greek-omitted} [[εγενε]{.greek-supplied}το]{.greek-added} λευκα [ως]{.greek-supplied} [το]{.greek-supplied} [φως]{.greek-supplied}[17:2]{.aside}

και ιδου [ω]{.unclear}[φθησαν]{.greek-supplied} αυτοις [μωσης]{.greek-omitted} [μ[ωυσης]{.greek-supplied}]{.greek-added} [και]{.greek-supplied} ηλιας [συ[νλ]{.unclear}[αλουν]{.greek-supplied}τες]{.greek-added} μετ αυτ[ο]{.unclear}[υ]{.greek-supplied} [συλλαλουντες]{.greek-omitted}[17:3]{.aside}

αποκριθεις δε [ο]{.greek-omitted} π[ε]{.unclear}[τρος]{.greek-supplied} ειπεν τω [ιησου]{.greek-abbr} [[κυριε]{.greek-abbr}]{.greek-supplied} [καλον]{.greek-supplied} [εστιν]{.greek-omitted} [ημας]{.greek-omitted} [ωδε]{.greek-omitted} [ειναι]{.greek-omitted} [ει]{.greek-omitted} [θελεις]{.greek-omitted} [ποιησωμεν]{.greek-omitted} [ωδε]{.greek-omitted} [τρεις]{.greek-omitted} [σκηνας]{.greek-omitted} [σοι]{.greek-omitted} [μιαν]{.greek-omitted} [και]{.greek-omitted} [μωση]{.greek-omitted} [μιαν]{.greek-omitted} [και]{.greek-omitted} [μιαν]{.greek-omitted} [ηλια]{.greek-omitted}[17:4]{.aside}

[[πο]{.greek-supplied}νη[ρ]{.unclear}α]{.greek-added} [αποκριθεις]{.greek-omitted} [δε]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} [ω]{.greek-omitted} [γενεα]{.greek-omitted} [απιστος]{.greek-omitted} και δ[ιεστραμμε]{.greek-supplied}νη εως [π]{.unclear}[οτε]{.greek-supplied} [εσομαι]{.greek-omitted} [μεθ]{.greek-supplied} [υ]{.greek-supplied}μων [εσομ[α]{.unclear}[ι]{.greek-supplied}]{.greek-added} [εως]{.greek-supplied} [ποτε]{.greek-supplied} ανεξομαι υ[μ]{.unclear}[ων]{.greek-supplied} [φε]{.greek-supplied}ρετε μοι αυτ[ο]{.unclear}[ν]{.greek-supplied} [ωδε]{.greek-supplied}[17:17]{.aside}

[κ]{.unclear}αι επετιμησ[εν]{.greek-supplied} [αυτω]{.greek-supplied} ο [ιησους]{.greek-abbr} και εξηλθ[εν]{.greek-supplied} [απ]{.greek-supplied} [αυ]{.greek-supplied}του το δαιμον[ιον]{.greek-supplied} [και]{.greek-supplied} εθεραπευθη ο [παις]{.greek-supplied} [απο]{.greek-supplied} [της]{.greek-omitted} [ωρας]{.greek-omitted} [εκεινης]{.greek-omitted}[17:18]{.aside}

### Chapter 19

[τοτε]{.greek-omitted} [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} αποκριθεις ο πετρος ειπεν [αυτω]{.greek-omitted} [τω]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} ιδου ημεις αφηκαμεν παντα και ηκολουθησαμεν σοι τι αρα εσται ημιν[19:27]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις αμην λεγω υμιν οτι υμεις οι ακολουθησαντες μοι εν τη παλιγγενεσια οταν καθιση ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} επι θρονου δοξης αυτου καθισεσθε και υμεις επι δωδεκα [θρονους]{.greek-omitted} [θρονων]{.greek-added} κρινοντες τας δωδεκα φυλας του [ισραηλ]{.greek-abbr}[19:28]{.aside}

και πας [ος]{.greek-omitted} [οστις]{.greek-added} αφηκεν οικιας η αδελφους η αδελφας η [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} η γυναικα η τεκνα η αγρους ενεκεν του ονοματος μου [εκατονταπλασιονα]{.greek-omitted} [εκατον]{.greek-added} [ταπλασιων]{.greek-added} [ληψεται]{.greek-omitted} [λημψεται]{.greek-added} και ζωην αιωνιον κληρονομησει [εις]{.greek-added} [μαρτυρας]{.greek-added} [κατα]{.greek-added} [ματθαιον]{.greek-added}[19:29]{.aside}

### Chapter 20

[ομοια]{.greek-omitted} [γαρ]{.greek-omitted} [εστιν]{.greek-omitted} [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [ειπε[ι]{.unclear}]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} [ημων]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [ο]{.greek-added} [[χριστος]{.greek-abbr}]{.greek-added} [τοις]{.greek-added} [εαυτου]{.greek-added} [μαθηταις]{.greek-added} [και]{.greek-added} [τοις]{.greek-added} [οχλοις]{.greek-added} [την]{.greek-added} [παραβολην]{.greek-added} [ταυτην]{.greek-added} [ομοιωθη]{.greek-added} η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} οικοδεσποτη οστις εξηλθεν αμα πρωι μισθωσασθαι εργατας εις τον αμπελωνα αυτου[20:1]{.aside}

και εξελθων περι τριτην ωραν [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} αλλους εστωτας εν τη αγορα αργους[20:3]{.aside}

[και]{.greek-omitted} [εκεινοις]{.greek-omitted} [κακεινοις]{.greek-added} ειπεν υπαγετε και υμεις εις τον αμπελωνα και ο εαν η δικαιον δωσω υμιν[20:4]{.aside}

οι δε απηλθον παλιν [δε]{.greek-added} εξελθων περι [εκ]{.greek-added} [εκτην]{.greek-omitted} [την]{.greek-added} και ενατην ωραν εποιησεν ωσαυτως[20:5]{.aside}

περι δε την ενδεκατην ωραν εξελθων [ευρεν]{.greek-omitted} [ιδεν]{.greek-added} αλλους εστωτας αργους και λεγει αυτοις τι ωδε εστηκατε ολην την ημεραν αργοι[20:6]{.aside}

λεγουσιν αυτω οτι ουδεις ημας εμισθωσατο λεγει αυτοις υπαγετε και υμεις εις τον αμπελωνα και ο εαν η δικαιον [ληψεσθε]{.greek-omitted} [λημψεσθαι]{.greek-added}[20:7]{.aside}

[οψιας]{.greek-omitted} [οψειας]{.greek-added} δε γενομενης λεγει ο [κυριος]{.greek-abbr} του αμπελωνος τω επιτροπω αυτου καλεσον [του]{.greek-added} [τους]{.corr} εργατας και αποδος αυτοις τον μισθον αρξαμενος απο των εσχατων εως των πρωτων[20:8]{.aside}

και ελθοντες οι περι την ενδεκατην ωραν ελαβον ανα δηναριον[20:9]{.aside}

ελθοντες δε οι πρωτοι ενομισαν οτι [πλειονα]{.greek-omitted} [πλειωνα]{.greek-added} [ληψονται]{.greek-omitted} [λημψονται]{.greek-added} και ελαβον και αυτοι ανα δηναριον[20:10]{.aside}

λαβοντες δε εγογγυζον κατα του οικοδεσποτου[20:11]{.aside}

λεγοντες οτι ουτοι οι εσχατοι μιαν ωραν εποιησαν και ισους ημιν αυτους εποιησας τοις [βαστασασιν]{.greek-omitted} [βαστασασι]{.greek-added} το βαρος της ημερας και τον καυσωνα[20:12]{.aside}

ο δε αποκριθεις ειπεν ενι αυτων [εταιρε]{.greek-omitted} [ετερε]{.greek-added} ουκ αδικω σε ουχι δηναριου συνεφωνησας μοι[20:13]{.aside}

αρον το σον και υπαγε θελω δε τουτω τω εσχατω δουναι ως και σοι[20:14]{.aside}

η ουκ [εστι]{.greek-added} [εξεστιν]{.greek-omitted} [[[ε]{.unclear}ξεστι]{.corr}]{.greek-added} μοι ποιησαι ο θελω εν τοις εμοις [ει]{.greek-omitted} [η]{.greek-added} ο οφθαλμος σου πονηρος εστιν οτι εγω αγαθος ειμι[20:15]{.aside}

ουτως εσονται οι εσχατοι πρωτοι και οι πρωτοι εσχατοι [πολλοι]{.greek-omitted} [γαρ]{.greek-omitted} [εισιν]{.greek-omitted} [κλητοι]{.greek-omitted} [ολιγοι]{.greek-omitted} [δε]{.greek-omitted} [εκλεκτοι]{.greek-omitted}[20:16]{.aside}

[τω]{.greek-added} [και]{.greek-omitted} [καιρω]{.greek-added} [εκεινω]{.greek-added} αναβαινων ο [[κυριος]{.greek-abbr}]{.greek-added} [ημων]{.greek-added} [ιησους]{.greek-abbr} [ο]{.greek-added} [[χριστος]{.greek-abbr}]{.greek-added} εις ιεροσολυμα παρελαβεν [του]{.greek-added} [τους]{.corr} δωδεκα μαθητας κατ ιδιαν εν τη οδω και ειπεν αυτοις[20:17]{.aside}

ιδου αναβαινομεν εις ιεροσολυμα και ο υιος του [ανθρωπου]{.greek-abbr} παραδοθησεται τοις [αρχιερευσιν]{.greek-omitted} [αρχιερευσι]{.greek-added} και [γραμματευσιν]{.greek-omitted} [γραμματευσι]{.greek-added} και κατακρινουσιν αυτον θανατω[20:18]{.aside}

και παραδωσουσιν αυτον τοις εθνεσιν εις το εμπαιξαι και μαστιγωσαι και σταυρωσαι και τη τριτη ημερα αναστησεται[20:19]{.aside}

τοτε προσηλθεν αυτω η [μητηρ]{.greek-abbr} των υιων ζεβεδαιου μετα των υιων αυτης προσκυνουσα και αιτουσα τι παρ αυτου[20:20]{.aside}

ο δε ειπεν αυτη τι θελεις λεγει αυτω ειπε ινα καθισωσιν ουτοι οι δυο υιοι μου εις εκ δεξιων σου και εις εξ ευωνυμων σου εν τη βασιλεια σου[20:21]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν ουκ οιδατε τι αιτεισθε δυνασθε πιειν το ποτηριον ο εγω μελλω πινειν η το βαπτισμα ο εγω βαπτιζομαι βαπτισθηναι λεγουσιν αυτω [δυναμεθα]{.greek-omitted} [δυνα]{.greek-added} [μεθα]{.greek-added}[20:22]{.aside}

και λεγει αυτοις το μεν ποτηριον μου πιεσθε και το [βαπτισ]{.greek-added} [βαπτισμα]{.corr} ο εγω βαπτιζομαι βαπτισθησεσθε το δε καθισαι εκ δεξιων μου και εξ ευωνυμων [μου]{.greek-omitted} ουκ εστιν εμον [τουτο]{.greek-added} δουναι αλλ οις ητοιμασται υπο του [πατρος]{.greek-abbr} μου[20:23]{.aside}

και ακουσαντες οι δεκα ηγανακτησαν περι των δυο αδελφων[20:24]{.aside}

ο δε [ιησους]{.greek-abbr} προσκαλεσαμενος αυτους ειπεν οιδατε οτι οι αρχοντες των εθνων κατακυριευουσιν αυτων και οι μεγαλοι κατεξουσιαζουσιν αυτων[20:25]{.aside}

ουχ ουτως [δε]{.greek-omitted} εσται εν υμιν αλλ ος εαν [θελη]{.greek-omitted} [θελει]{.greek-added} εν υμιν [ειναι]{.greek-added} μεγας γενεσθαι εσται υμων διακονος[20:26]{.aside}

και ος εαν [θελη]{.greek-omitted} [θελει]{.greek-added} εν υμιν ειναι πρωτος [εστω]{.greek-omitted} [εσται]{.greek-added} υμων δουλος[20:27]{.aside}

ωσπερ ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ουκ ηλθεν [διακονηθη]{.greek-added} [διακονηθηναι]{.corr} αλλα διακονησαι και δουναι την ψυχην αυτου λυτρον αντι πολλων[20:28]{.aside}

### Chapter 21

και οτε ηγγισαν εις ιεροσολυμα και ηλθον εις [βηθσφαγη]{.greek-omitted} [βηθφαγη]{.greek-added} προς το ορος των ελαιων τοτε ο [[κυριος]{.greek-abbr}]{.greek-added} [ημων]{.greek-added} [ιησους]{.greek-abbr} [ο]{.greek-added} [[χριστος]{.greek-abbr}]{.greek-added} απεστειλεν δυο [μαθητας]{.greek-omitted} [των]{.greek-added} [μαθητων]{.greek-added}[21:1]{.aside}

λεγων αυτοις [πορευθητε]{.greek-omitted} [πορευθεντες]{.greek-added} εις την κωμην την [απεναντι]{.greek-omitted} [κατεναντι]{.greek-added} υμων και ευθεως ευρησετε ονον δεδεμενην και πωλον μετ αυτης λυσαντες αγαγετε μοι[21:2]{.aside}

και εαν τις υμιν ειπη τι ερειτε οτι ο [κυριος]{.greek-abbr} αυτων χρειαν εχει ευθεως δε αποστελλει αυτους[21:3]{.aside}

τουτο δε [ολον]{.greek-omitted} γεγονεν ινα πληρωθη το ρηθεν δια του προφητου λεγοντος[21:4]{.aside}

ειπατε τη θυγατρι σιων ιδου ο βασιλευς σου ερχεται σοι πραυς και επιβεβηκως επι ονον και [επι]{.greek-added} πωλον υιον υποζυγιου[21:5]{.aside}

πορευθεντες δε οι μαθηται και ποιησαντες καθως προσεταξεν αυτοις ο [ιησους]{.greek-abbr}[21:6]{.aside}

ηγαγον την ονον και τον πωλον και επεθηκαν επανω αυτων τα ιματια αυτων και επεκαθισεν επανω αυτων[21:7]{.aside}

ο δε [πλειστος]{.greek-omitted} [πληστος]{.greek-added} οχλος εστρωσαν εαυτων τα ιματια εν τη οδω αλλοι δε εκοπτον κλαδους απο των δενδρων και εστρωννυον εν τη οδω[21:8]{.aside}

οι δε οχλοι οι προαγοντες [αυτον]{.greek-added} και οι ακολουθουντες εκραζον λεγοντες ωσαννα τω [υιω]{.greek-abbr} [δαυιδ]{.greek-abbr} ευλογημενος ο ερχομενος εν ονοματι [κυριου]{.greek-abbr} ωσαννα εν τοις υψιστοις[21:9]{.aside}

και εισελθοντος αυτου εις ιεροσολυμα εσεισθη πασα η πολις λεγουσα τις εστιν ουτος[21:10]{.aside}

οι δε οχλοι ελεγον ουτος εστιν [ιησους]{.greek-abbr} ο προφητης ο απο ναζαρετ της γαλιλαιας[21:11]{.aside}

και εισηλθεν ο [ιησους]{.greek-abbr} εις το ιερον του [θεου]{.greek-abbr} και εξεβαλεν [παντας]{.greek-omitted} [παν]{.greek-added} [τας]{.greek-added} [του]{.greek-added} [τους]{.corr} πωλουντας και αγοραζοντας εν τω ιερω και τας τραπεζας των κολλυβιστων κατεστρεψεν και τας καθεδρας των πωλουντων τας περιστερας[21:12]{.aside}

και λεγει αυτοις γεγραπται ο οικος μου οικος προσευχης κληθησεται υμεις [δε]{.greek-omitted} αυτον εποιησατε σπηλαιον ληστων[21:13]{.aside}

και προσηλθον αυτω [τυφλοι]{.greek-added} [και]{.greek-added} χωλοι [και]{.greek-omitted} [τυφλοι]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ιερω]{.greek-omitted} και εθεραπευσεν αυτους[21:14]{.aside}

ιδοντες δε οι αρχιερεις και οι γραμματεις τα θαυμασια α εποιησεν και τους παιδας [κραζοντας]{.greek-omitted} εν τω ιερω [κραζοντας]{.greek-added} και λεγοντας ωσαννα τω υιω [δαυιδ]{.greek-omitted} [δαυειδ]{.greek-added} [ηγανακτησαν]{.greek-omitted}[21:15]{.aside}

[αλλην]{.greek-omitted} [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [ειπεν]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} [ημων]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [ο]{.greek-added} [[χριστος]{.greek-abbr}]{.greek-added} [τοις]{.greek-added} [εαυτου]{.greek-added} [μαθηταις]{.greek-added} [και]{.greek-added} [τοις]{.greek-added} [οχλοις]{.greek-added} [την]{.greek-added} παραβολην [ακουσατε]{.greek-omitted} [ταυτην]{.greek-added} [ανθρωπος]{.greek-abbr} [τις]{.greek-omitted} ην οικοδεσποτης οστις εφυτευσεν αμπελωνα και φραγμον αυτω περιεθηκεν και ωρυξεν εν αυτω ληνον και ωκοδομησεν πυργον και εξεδοτο αυτον γεωργοις και απεδημησεν[21:33]{.aside}

οτε [δε]{.greek-omitted} ηγγισεν ο καιρος των καρπων απεστειλεν τους δουλους αυτου προς τους γεωργους λαβειν τους καρπους αυτου[21:34]{.aside}

και λαβ[οντ]{.unclear}ες οι γεωργοι τους δουλους αυτου ον μεν εδειραν ον δε απεκτειναν ον δε ελιθοβολησαν[21:35]{.aside}

παλιν απεστειλεν αλλους δουλους [πλειονας]{.greek-omitted} [πλειωνας]{.greek-added} των πρωτων και εποιησαν αυτοις ωσαυτως[21:36]{.aside}

υστερον δε απεστειλεν προς αυτους τον [υιον]{.greek-abbr} αυτου λεγων εντραπησονται τον [υιον]{.greek-abbr} μου[21:37]{.aside}

οι δε γεωργοι ιδοντες τον υιον ειπον εν εαυτοις ουτος εστιν ο κληρονομος δευτε αποκτεινωμεν αυτον και κατασχωμεν την κληρονομιαν αυτου[21:38]{.aside}

και λαβοντες αυτον [οι]{.greek-added} [γεωργοι]{.greek-added} εξεβαλον εξω του αμπελωνος και απεκτειναν[21:39]{.aside}

οταν ουν ελθη ο [κυριος]{.greek-abbr} του αμπελωνος τι ποιησει τοις γεωργοις εκεινοις[21:40]{.aside}

λεγουσιν αυτω κακους κακως απολεσει αυτους και τον αμπελωνα [εκδωσεται]{.greek-omitted} [εκδοσεται]{.greek-added} αλλοις γεωργοις οιτινες αποδωσουσιν αυτω τους καρπους εν τοις καιροις αυτων[21:41]{.aside}

λεγει αυτοις ο [ιησους]{.greek-abbr} ουδεποτε [ανεγνωτε]{.greek-omitted} [ανεγνωται]{.greek-added} εν ταις γραφαις λιθον ον [απεδοκιμασαν]{.greek-omitted} [απεδοκημασαν]{.greek-added} οι οικοδομουντες ουτος εγενηθη εις κεφαλην γωνιας παρα [κυριου]{.greek-abbr} εγενετο αυτη και εστιν θαυμαστη εν οφθαλμοις ημων[21:42]{.aside}

δια τουτο λεγω υμιν οτι αρθησεται αφ υμων η [βασιλεια]{.greek-omitted} [βασιλει]{.greek-added} [του]{.greek-omitted} [θεου]{.greek-omitted} [α]{.greek-added} [των]{.greek-added} [[ουρανων]{.greek-abbr}]{.greek-added} και δοθησεται [εθνει]{.greek-omitted} [εθνη]{.greek-added} ποιουντι τους καρπους αυτης[21:43]{.aside}

και ο πεσων επι τον λιθον τουτον συνθλασθησεται εφ ον δ αν [πεση]{.greek-omitted} [πεσει]{.greek-added} λικμησει αυτον[21:44]{.aside}

και ακουσαντες οι αρχιερεις και οι [φαρισαιοι]{.greek-omitted} [φαρεισαιοι]{.greek-added} τας παραβολας αυτου εγνωσαν οτι περι αυτων λεγει[21:45]{.aside}

και ζητουντες αυτον κρατησαι εφοβηθησαν τους οχλους [επειδη]{.greek-omitted} [επηδει]{.greek-added} ως προφητην αυτον ειχον[21:46]{.aside}

### Chapter 22

[εν]{.greek-added} [εκεινω]{.greek-added} [τω]{.greek-added} [καιρω]{.greek-added} [ειπεν]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} [ημων]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [ο]{.greek-added} [[χριστος]{.greek-abbr}]{.greek-added} [τοις]{.greek-added} [εαυτου]{.greek-added} [μαθηταις]{.greek-added} και [αποκριθεις]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [παλιν]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [τοις]{.greek-added} [εν]{.greek-omitted} [παραβολαις]{.greek-omitted} [λεγων]{.greek-omitted} [οχλοις]{.greek-added} [την]{.greek-added} [παραβολην]{.greek-added} [ταυτην]{.greek-added}[22:1]{.aside}

ωμοιωθη η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} βασιλει οστις εποιησεν γαμους τω υιω αυτου[22:2]{.aside}

και απεστειλεν τους δουλους αυτου καλεσαι τους κεκλημενους εις τους γαμους και ουκ ηθελον ελθειν[22:3]{.aside}

παλιν απεστειλεν αλλους δουλους λεγων ειπατε τοις κεκλημενοις ιδου το αριστον μου ητοιμασα οι ταυροι μου και τα σιτιστα τεθυμενα και παντα ετοιμα δευτε εις τους γαμους[22:4]{.aside}

οι δε αμελησαντες απηλθον ο μεν εις τον ιδιον αγρον ο δε εις την εμποριαν αυτου[22:5]{.aside}

οι δε λοιποι κρατησαντες τους δουλους αυτου υβρισαν και απεκτειναν[22:6]{.aside}

και ακουσας ο βασιλευς εκεινος ωργισθη και πεμψας τα στρατευματα αυτου [απωλεσεν]{.greek-omitted} [απολεσεν]{.greek-added} τους φονεις εκεινους και την πολιν αυτων [ενεπρησεν]{.greek-omitted} [ενεπρισεν]{.greek-added}[22:7]{.aside}

τοτε λεγει τοις δουλοις αυτου ο μεν γαμος ετοιμος εστιν οι δε κεκλημενοι ουκ ησαν αξιοι[22:8]{.aside}

[πορευεσθε]{.greek-omitted} [πορευεσθαι]{.greek-added} ουν επι τας διεξοδους των οδων και οσους [αν]{.greek-omitted} [εαν]{.greek-added} ευρητε καλεσατε εις τους γαμους[22:9]{.aside}

[και]{.greek-omitted} εξελθοντες [δε]{.greek-added} οι δουλοι εκεινοι εις τας οδους συνηγαγον [παντας]{.greek-omitted} οσους ευρον πονηρους [τε]{.corr} και αγαθους και επλησθη ο γαμος ανακειμενων[22:10]{.aside}

εισελθων δε ο βασιλευς θεασασθαι τους ανακειμενους ειδεν εκει [ανθρωπον]{.greek-abbr} ουκ ενδεδυμενον ενδυμα γαμου[22:11]{.aside}

και λεγει αυτω [εταιρε]{.greek-omitted} [ετερε]{.greek-added} πως εισηλθες ωδε μη εχων ενδυμα γαμου ο δε εφιμωθη[22:12]{.aside}

τοτε ειπεν ο βασιλευς τοις διακονοις δησαντες αυτου [π]{.unclear}οδας και χειρας αρατε αυτον και [εκβαλετε]{.greek-omitted} [εκβαλατε]{.greek-added} εις το σκοτος το εξωτερον εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[22:13]{.aside}

πολλοι γαρ εισιν κλητοι ολιγοι δε εκλεκτοι[22:14]{.aside}

### Chapter 23

[τοτε]{.greek-omitted} [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [ειπεν]{.greek-added} ο [[κυριος]{.greek-abbr}]{.greek-added} [ημων]{.greek-added} [ιησους]{.greek-abbr} [ελαλησεν]{.greek-omitted} [ο]{.greek-added} [[χριστος]{.greek-abbr}]{.greek-added} [τοις]{.greek-added} [εαυτου]{.greek-added} [μαθηταις]{.greek-added} [και]{.greek-added} τοις οχλοις [και]{.greek-omitted} [τοις]{.greek-omitted} [μαθηταις]{.greek-omitted} [αυτου]{.greek-omitted}[23:1]{.aside}

[λεγων]{.greek-omitted} επι της [καθεδρας]{.greek-added} μωσεως [καθεδρας]{.greek-omitted} εκαθισαν οι γραμματεις και οι [φαρισαιοι]{.greek-omitted} [φαρεισαιοι]{.greek-added}[23:2]{.aside}

παντα ουν οσα εαν ειπωσιν υμιν τηρειν τηρειτε και [ποιειτε]{.greek-omitted} [ποι]{.greek-added} [ητε]{.greek-added} κατα δε τα εργα αυτων μη [ποιειτε]{.greek-omitted} [ποιητε]{.greek-added} [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} γαρ και ου ποιουσιν[23:3]{.aside}

[δεσμευουσιν]{.greek-omitted} [δεσμευουσι]{.greek-added} [γαρ]{.greek-omitted} [δε]{.greek-added} φορτια βαρεα και δυσβαστακτα και επιτιθεασιν επι τους ωμους των [ανθρωπων]{.greek-abbr} τω δε δακτυλω αυτων ου θελουσιν κινησαι αυτα[23:4]{.aside}

παντα δε τα εργα αυτων ποιουσιν προς το θεαθηναι τοις [ανθρωποις]{.greek-abbr} [πλατυνουσιν]{.greek-omitted} [πλατυνουσι]{.greek-added} δε τα φυλακτηρια αυτων και [μεγαλυνουσιν]{.greek-omitted} [μεγαλυνουσι]{.greek-added} τα κρασπεδα των ιματιων αυτων[23:5]{.aside}

[φιλουσιν]{.greek-omitted} [φιλουσι]{.greek-added} [τε]{.greek-omitted} [δε]{.greek-added} την πρωτοκλισιαν εν τοις δειπνοις και τας πρωτοκαθεδριας εν ταις συναγωγαι[ς]{.unclear}[23:6]{.aside}

και τους ασπασμους εν ταις αγοραις και καλεισθαι υπο των ανθρωπων ραββι [ραββι]{.greek-omitted}[23:7]{.aside}

υμεις δε μη κληθητε ραββι εις γαρ εστιν υμων ο καθηγητης ο [χριστος]{.greek-abbr} παντες δε υμεις αδελφοι [εστε]{.greek-omitted} [εσται]{.greek-added}[23:8]{.aside}

και [πατερα]{.greek-abbr} μη [καλεσητε]{.greek-omitted} [καλεσειτε]{.greek-added} υμων επι της γης εις γαρ εστιν ο [πατηρ]{.greek-abbr} υμων ο εν τοις [ουρανοις]{.greek-abbr}[23:9]{.aside}

μηδε [κληθητε]{.greek-omitted} [κληθηται]{.greek-added} καθηγηται εις γαρ [υμων]{.greek-omitted} εστιν ο καθηγητης ο [χριστος]{.greek-abbr}[23:10]{.aside}

ο δε μειζων υμων [εσται]{.greek-omitted} [εστω]{.greek-added} υμων διακονος[23:11]{.aside}

οστις δε υψωσει εαυτον ταπεινωθησεται και οστις [ταπεινωσει]{.greek-omitted} [ταπινωσει]{.greek-added} εαυτον υψωθησεται[23:12]{.aside}

ουαι [δε]{.greek-omitted} υμιν γραμματεις και [φαρισαιοι]{.greek-omitted} [φαρεισαιοι]{.greek-added} υποκριται οτι [κατεσθιετε]{.greek-omitted} [τας]{.greek-omitted} [οικιας]{.greek-omitted} [κλειεται]{.greek-added} [την]{.greek-added} [βασιλειαν]{.greek-added} των [χηρων]{.greek-omitted} [και]{.greek-omitted} [προφασει]{.greek-omitted} [μακρα]{.greek-omitted} [προσευχομενοι]{.greek-omitted} [δια]{.greek-omitted} [τουτο]{.greek-omitted} [ληψεσθε]{.greek-omitted} [περισσοτερον]{.greek-omitted} [κριμα]{.greek-omitted} [[ουρανων]{.greek-abbr}]{.greek-added} [εμπροσθεν]{.greek-added} [των]{.greek-added} [[ανθρωπων]{.greek-abbr}]{.greek-added} [υμεις]{.greek-added} [γαρ]{.greek-added} [ουκ]{.greek-added} [εισερχεσθαι]{.greek-added} [ουδε]{.greek-added} [τους]{.greek-added} [εισερχομενους]{.greek-added} [αφιεται]{.greek-added} [εισελθειν]{.greek-added}[23:13]{.aside}

ουαι [δε]{.greek-added} υμιν γραμματεις και φαρισαιοι [υπο]{.greek-added} [υποκριται]{.greek-omitted} [κριται]{.greek-added} οτι [κλειετε]{.greek-omitted} [την]{.greek-omitted} [βασιλειαν]{.greek-omitted} [κατεσθιεται]{.greek-added} [τας]{.greek-added} [οικιας]{.greek-added} των [χηρων]{.greek-added} [και]{.greek-added} [προφασει]{.greek-added} [μακρα]{.greek-added} [προσευχομενοι]{.greek-added} [δια]{.greek-added} [τουτο]{.greek-added} [λημψεσθαι]{.greek-added} [περισσοτερον]{.greek-added} [κριμα]{.greek-added} [ουρανων]{.greek-omitted} [εμπροσθεν]{.greek-omitted} [των]{.greek-omitted} [ανθρωπων]{.greek-omitted} [υμεις]{.greek-omitted} [γαρ]{.greek-omitted} [ουκ]{.greek-omitted} [εισερχεσθε]{.greek-omitted} [ουδε]{.greek-omitted} [τους]{.greek-omitted} [εισερχομενους]{.greek-omitted} [αφιετε]{.greek-omitted} [εισελθειν]{.greek-omitted}[23:14]{.aside}

ουαι υμιν γραμματεις και [φαρισαιοι]{.greek-omitted} [φαρεισαιοι]{.greek-added} υποκριται οτι [περιαγετε]{.greek-omitted} [περιαγεται]{.greek-added} την θαλασσαν και την ξηραν ποιησαι ενα προσηλυτον και οταν [γενηται]{.greek-omitted} [γενητε]{.greek-added} ποιειτε αυτον [υιον]{.greek-abbr} γεεννης [διπλοτερον]{.greek-omitted} [διπλωτερον]{.greek-added} υμων[23:15]{.aside}

ουαι υμιν οδηγοι τυφλοι οι λεγοντες ος αν [ομοση]{.greek-omitted} [ομωση]{.greek-added} εν τω ναω ουδεν εστιν ος [αν]{.greek-added} δ αν [ομοση]{.greek-omitted} [ομωση]{.greek-added} εν τω χρυσω του ναου [οφειλει]{.greek-omitted} [οφιλει]{.greek-added}[23:16]{.aside}

μωροι και τυφλοι τις γαρ μειζων εστιν ο χρυσος η ο ναος ο αγιαζων τον χρυσον[23:17]{.aside}

και ος [εαν]{.greek-omitted} [αν]{.greek-added} [ομοση]{.greek-omitted} [ομωσει]{.greek-added} εν τω θυσιαστηριω ουδεν εστιν ος δ αν [ομωσεν]{.greek-added} [ομοση]{.greek-omitted} [εν]{.greek-omitted} τω δωρω τω επανω αυτου [οφειλει]{.greek-omitted} [οφιλει]{.greek-added}[23:18]{.aside}

μωροι και τυφλοι τι γαρ [μειζον]{.greek-omitted} [μειζων]{.greek-added} το δωρον η το θυσιαστηριον το [αγιαζον]{.greek-omitted} [αγιαζων]{.greek-added} το δωρον[23:19]{.aside}

ο ουν [ομοσας]{.greek-omitted} [[ο]{.unclear}μωσας]{.greek-added} εν τω θυσιαστηριω ομνυει εν αυτω και εν πασιν τοις επανω αυτου[23:20]{.aside}

και ο [ομοσας]{.greek-omitted} [ομωσας]{.greek-added} εν τω ναω ομνυει εν αυτω και εν τω κατοικησαντι αυτον[23:21]{.aside}

και ο [ομοσας]{.greek-omitted} [ομωσας]{.greek-added} εν τω [ουρανω]{.greek-abbr} ομνυει εν τω θρονω του [θεου]{.greek-abbr} και εν τω [καθημενω]{.greek-omitted} [καθιμενω]{.greek-added} επανω αυτου[23:22]{.aside}

ουαι υμιν γραμματεις και [φαρισαιοι]{.greek-omitted} [φαρεισαιοι]{.greek-added} υποκριται οτι [αποδεκατουτε]{.greek-omitted} [αποδεκατουται]{.greek-added} το ηδυοσμον και το ανηθον και το [κυμινον]{.greek-omitted} [κυμηνον]{.greek-added} και αφηκατε τα βαρυτερα του νομου την κρισιν και τον [ελεον]{.greek-omitted} [ελαιον]{.greek-added} και την πιστιν ταυτα [εδει]{.greek-omitted} [δε]{.greek-added} [εδη]{.greek-added} ποιησαι [κακειν]{.greek-added} [κακεινα]{.corr} μη [αφιεναι]{.greek-omitted} [αφηεναι]{.greek-added}[23:23]{.aside}

οδηγοι τυφλοι οι διυλιζοντες τον κωνωπα την δε καμηλον καταπινοντες[23:24]{.aside}

ουαι υμιν γραμματεις και [φαρισαιοι]{.greek-omitted} [φαρεισαιοι]{.greek-added} υποκριται οτι [καθαριζετε]{.greek-omitted} [καθαριζεται]{.greek-added} το εξωθεν του ποτηριου και της παροψιδος εσωθεν δε γεμουσιν εξ αρπαγης και [αδικιας]{.greek-omitted} [ακ[αθ]{.unclear}α[ρ]{.unclear}σιας]{.greek-added} [[ακρασιας]{.corr}]{.greek-added}[23:25]{.aside}

φαρισαιε τυφλε καθαρισον πρωτον το εντος του ποτηριου και της παροψιδος ινα γενηται και το εκτος αυτων καθαρον[23:26]{.aside}

ουαι υμιν γραμματεις και [φαρισαιοι]{.greek-omitted} [φαρεισαιοι]{.greek-added} υποκριται οτι [παρομοιαζετε]{.greek-omitted} [παρομοιαζεται]{.greek-added} ταφοις κεκονιαμενοις οιτινες εξωθεν μεν φαινονται ωραιοι [εσωθεν]{.greek-omitted} [εσων]{.greek-added} δε γεμουσιν οστεων νεκρων και πασης ακαθαρσιας[23:27]{.aside}

ουτως και υμεις εξωθεν μεν [φαινεσθε]{.greek-omitted} [φαινεσθαι]{.greek-added} τοις [ανθρωποις]{.greek-abbr} δικαιοι εσωθεν δε [εσται]{.greek-added} μεστοι [εστε]{.greek-omitted} υποκρισεως και ανομιας[23:28]{.aside}

ουαι υμιν γραμματεις και [φαρισαιοι]{.greek-omitted} [φαρεισαιοι]{.greek-added} υποκριται οτι [οικοδομειτε]{.greek-omitted} [οικοδομηται]{.greek-added} τους ταφους των προφητων και κοσμειτε τα μνημεια των δικαιων[23:29]{.aside}

και λεγετε ει ημεν εν ταις ημεραις των [πατερων]{.greek-abbr} ημων ουκ αν ημεν κοινωνοι αυτων εν τω αιματι των προφητων[23:30]{.aside}

ωστε [μαρτυρειτε]{.greek-omitted} [μαρτυρειται]{.greek-added} εαυτοις οτι υιοι [εστε]{.greek-omitted} [εσται]{.greek-added} των φονευσαντων τους προφητας[23:31]{.aside}

και υμεις [πληρωσατε]{.greek-omitted} [πληρωσεται]{.greek-added} το μετρον των [πατερων]{.greek-abbr} υμων[23:32]{.aside}

οφεις γεννηματα εχιδνων [πως]{.greek-omitted} [φυγητε]{.greek-omitted} [τις]{.greek-added} [υπεδειξεν]{.greek-added} [υμιν]{.greek-added} [φυγειν]{.greek-added} απο της κρισεως της γεεννης[23:33]{.aside}

δια τουτο ιδου [εγω]{.corr} αποστελλω προς υμας προφητας και σοφους και γραμματεις [και]{.greek-omitted} εξ αυτων αποκτενειτε και [σταυρωσετε]{.greek-omitted} [σταυρωσεται]{.greek-added} και εξ αυτων [μαστιγωσετε]{.greek-omitted} [μαστιγωσεται]{.greek-added} εν ταις συναγωγαις υμων και [διωξετε]{.greek-omitted} [διωξεται]{.greek-added} απο πολεως εις πολιν[23:34]{.aside}

οπως ελθη εφ υμας παν αιμα δικαιον [εκχυνομενον]{.greek-omitted} [εκκεχυμενον]{.greek-added} επι της γης απο [του]{.greek-omitted} αιματος αβελ του δικαιου εως [του]{.greek-omitted} αιματος ζαχαριου υιου βαραχιου ον εφονευσατε μεταξυ του ναου και του θυσιαστηριου[23:35]{.aside}

αμην λεγω υμιν οτι ηξει [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} επι την γενεαν ταυτην[23:36]{.aside}

[ιερουσαλημ]{.greek-abbr} [ιερουσαλημ]{.greek-abbr} η [αποκτενουσα]{.greek-omitted} [αποκτεννουσα]{.greek-added} τους προφητας και λιθοβολουσα τους απεσταλμενους προς αυτην ποσακις ηθελησα [επισυναγαγειν]{.greek-omitted} [επισυναγειν]{.greek-added} τα τεκνα σου ον τροπον επισυναγει ορνις τα νοσσια εαυτης υπο τας πτερυγας και ουκ ηθελησατε[23:37]{.aside}

ιδου αφιεται υμιν ο οικος υμων ερημος[23:38]{.aside}

λεγω γαρ υμιν ου μη με ιδητε απ αρτι εως αν [ειπητε]{.greek-omitted} [ειπειτε]{.greek-added} ευλογημενος ο ερχομενος εν ονοματι κυριου[23:39]{.aside}

### Chapter 24

[κ]{.greek-added} [εκεινο]{.greek-omitted} [δε]{.greek-omitted} [γινωσκετε]{.greek-omitted} [οτι]{.greek-omitted} [ει]{.greek-omitted} [ηδει]{.greek-omitted} [ο]{.greek-omitted} [οικοδεσποτης]{.greek-omitted} [ποια]{.greek-omitted} [φυλακη]{.greek-omitted} [ο]{.greek-omitted} [κλεπτης]{.greek-omitted} [ερχεται]{.greek-omitted} [εγρηγορησεν]{.greek-omitted} αν [και]{.greek-omitted} [ουκ]{.greek-omitted} [αν]{.greek-omitted} [ειασεν]{.greek-omitted} [ιασεν]{.greek-added} διορυγηναι την οικιαν αυτου[24:43]{.aside}

δια τουτο και υμεις γινεσθε ετοιμοι οτι η ωρα ου δοκειτε ο υιος του [ανθρωπου]{.greek-abbr} ερχεται[24:44]{.aside}

τις αρα εστιν ο πιστος δουλος και [φρονιμος]{.greek-omitted} [φρονημος]{.greek-added} ον κατεστησεν ο [κυριος]{.greek-abbr} αυτου επι της [θεραπειας]{.greek-omitted} [οικετι]{.greek-added} αυτου [του]{.greek-omitted} [διδοναι]{.greek-omitted} [δουναι]{.greek-added} αυτοις την τροφην εν καιρω[24:45]{.aside}

μακαριος ο δουλος εκεινος ον ελθων ο [κυριος]{.greek-abbr} αυτου ευρησει [ουτως]{.greek-added} ποιουντα [ουτως]{.greek-omitted}[24:46]{.aside}

αμην λεγω υμιν οτι επι πασιν τοις υπαρχουσιν αυτου καταστησει αυτον[24:47]{.aside}

εαν δε ειπη ο κακος δουλος εκεινος εν τη καρδια αυτου χρονιζει ο [κυριος]{.greek-abbr} μου ελθειν[24:48]{.aside}

και αρξηται τυπτειν τους συνδουλους [εσθιειν]{.greek-omitted} [αυτου]{.greek-added} [εσθιη]{.greek-added} δε και [πινειν]{.greek-omitted} [πινη]{.greek-added} μετα των μεθυοντων[24:49]{.aside}

ηξει ο [κυριος]{.greek-abbr} του δουλου εκεινου εν ημερα η ου προσδοκα και εν ωρα η ου γινωσκει[24:50]{.aside}

και διχοτομησει αυτον και το μερος αυτου μετα των υποκριτων θησει εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[24:51]{.aside}

### Chapter 25

τοτε ομοιωθησεται η βασιλεια των ουρανων δεκα παρθενοις αιτινες λαβουσαι τας λαμπαδας αυτων εξηλθον εις απαντησιν του νυμφιου[25:1]{.aside}

πεντε δε [ησαν]{.greek-omitted} εξ αυτων [ησαν]{.greek-added} [μωραι]{.greek-added} [και]{.greek-added} [πεντε]{.greek-added} φρονιμοι [και]{.greek-omitted} [αι]{.greek-omitted} [πεντε]{.greek-omitted} [μωραι]{.greek-omitted}[25:2]{.aside}

[αιτινες]{.greek-omitted} [αι]{.greek-added} [γαρ]{.greek-added} μωραι λαβουσαι τας λαμπαδας αυτων ουκ ελαβον μεθ εαυτων ελαιον[25:3]{.aside}

αι δε φρονιμοι ελαβον ελαιον εν τοις [αγγειοις]{.greek-omitted} [αγγιοις]{.greek-added} [αυτων]{.greek-omitted} μετα των λαμπαδων αυτων[25:4]{.aside}

χρονιζοντος δε του νυμφιου ενυσταξαν πασαι και εκαθευδον[25:5]{.aside}

μεσης δε [νυκτος]{.greek-omitted} [νυκκτος]{.greek-added} κραυγη γεγονεν ιδου ο νυμφιος ερχεται εξερχεσθε εις απαντησιν αυτου[25:6]{.aside}

τοτε [ηγερθησαν]{.greek-omitted} [ηγερ]{.greek-added} [θησαν]{.greek-added} πασαι αι παρθενοι εκειναι και εκοσμησαν τας λαμπαδας αυτων[25:7]{.aside}

αι δε μωραι ταις φρονιμοις [ειπον]{.greek-omitted} [ειπαν]{.greek-added} δοτε ημιν εκ του ελαιου υμων οτι αι λαμπαδες ημων σβεννυνται[25:8]{.aside}

απεκριθησαν δε αι φρονιμοι λεγουσαι μηποτε ουκ αρκεση ημιν και υμιν πορευεσθε [δε]{.greek-omitted} μαλλον προς τους πωλουντας και αγορασατε εαυταις[25:9]{.aside}

απερχομενων δε αυτων αγορασαι ηλθεν ο νυμφιος και αι ετοιμοι εισηλθον μετ αυτου εις τους γαμους και εκλεισθη η θυρα[25:10]{.aside}

υστερον δε ερχονται και αι λοιπαι παρθενοι λεγουσαι [κυριε]{.greek-abbr} [κυριε]{.greek-abbr} ανοιξον ημιν[25:11]{.aside}

ο δε αποκριθεις ειπεν αμην λεγω υμιν ουκ οιδα υμας[25:12]{.aside}

γρηγορειτε ουν οτι ουκ οιδατε την ημεραν ουδε την ωραν [εν]{.greek-omitted} [η]{.greek-omitted} [ο]{.greek-omitted} [υιος]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [ερχεται]{.greek-omitted}[25:13]{.aside}

ωσπερ γαρ [ανθρωπος]{.greek-abbr} αποδημων εκαλεσεν τους ιδιους δουλους και παρεδωκεν αυτοις [παντα]{.greek-added} τα υπαρχοντα αυτου[25:14]{.aside}

και ω μεν εδωκεν πεντε ταλαντα ω δε δυο ω δε εν εκαστω κατα την ιδιαν δυναμιν και απεδημησεν ευθεως[25:15]{.aside}

πορευθεις δε ο τα πεντε ταλαντα λαβων [ειργασατο]{.greek-omitted} [ηργασατο]{.greek-added} εν αυτοις και [εποιησεν]{.greek-omitted} [εκερδησεν]{.greek-added} αλλα πεντε ταλαντα[25:16]{.aside}

ωσαυτως και ο τα δυο εκερδησεν και αυτος αλλα δυο[25:17]{.aside}

ο δε το εν λαβων απελθων ωρυξεν εν τη γη και [απεκρυψεν]{.greek-omitted} [εκρυψεν]{.greek-added} το αργυριον του [κυριου]{.greek-abbr} αυτου[25:18]{.aside}

μετα δε [πολυν]{.greek-added} χρονον [πολυν]{.greek-omitted} ερχεται ο [κυριος]{.greek-abbr} των δουλων εκεινων και συναιρει [λογον]{.greek-added} μετ αυτων [λογον]{.greek-omitted}[25:19]{.aside}

και προσελθων ο τα πεντε ταλαντα λαβων προσηνεγκεν αλλα πεντε ταλαντα λεγων [κυριε]{.greek-abbr} πεντε ταλαντα μοι παρεδωκας ιδε αλλα πεντε ταλαντα εκερδησα επ αυτοις[25:20]{.aside}

εφη δε αυτω ο [κυριος]{.greek-abbr} αυτου ευ δουλε αγαθε και πιστε επι ολιγα ης πιστος επι πολλων σε καταστησω εισελθε εις την χαραν του [κυριου]{.greek-abbr} σου[25:21]{.aside}

προσελθων δε και ο τα δυο ταλαντα λαβων ειπεν [κυριε]{.greek-abbr} δυο ταλαντα μοι παρεδωκας ιδε αλλα δυο ταλαντα εκερδησα επ αυτοις[25:22]{.aside}

εφη αυτω ο [κυριος]{.greek-abbr} αυτου ευ δουλε αγαθε και πιστε επι ολιγα ης πιστος επι πολλων σε καταστησω εισελθε εις την χαραν του [κυριου]{.greek-abbr} σου[25:23]{.aside}

προσελθων δε και ο το εν ταλαντον ειληφως ειπεν [κυριε]{.greek-abbr} εγνων σε οτι σκληρος ει [ανθρωπος]{.greek-abbr} θεριζων οπου ουκ εσπειρας και συναγων οθεν ου διεσκορπισας[25:24]{.aside}

και φοβηθεις απελθων εκρυψα το ταλαντον σου εν τη γη ιδε εχεις το σον[25:25]{.aside}

αποκριθεις δε ο [κυριος]{.greek-abbr} αυτου ειπεν αυτω πονηρε δουλε και οκνηρε ηδεις οτι θεριζω οπου ουκ εσπειρα και συναγω οθεν ου [διεσκορπισα]{.greek-omitted} [διεσκορ]{.greek-added} [πησα]{.greek-added}[25:26]{.aside}

εδει [σε]{.greek-added} ουν [σε]{.greek-omitted} βαλειν το αργυριον μου τοις [τραπεζιταις]{.greek-omitted} [τραπεζηταις]{.greek-added} και ελθων εγω εκομισαμην αν το εμον συν τοκω[25:27]{.aside}

αρατε ουν απ αυτου το ταλαντον και δοτε τω εχοντι τα δεκα ταλαντα[25:28]{.aside}

τω γαρ εχοντι παντι δοθησεται και περισσευθησεται απο δε του μη εχοντος και ο εχει αρθησεται απ αυτου[25:29]{.aside}

και τον αχρειον δουλον εκβαλετε εις το σκοτος το εξωτερον εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[25:30]{.aside}

οταν δε ελθη ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εν τη δοξη αυτου και παντες οι [αγιοι]{.greek-omitted} αγγελοι μετ αυτου τοτε καθισει επι θρονου δοξης αυτου[25:31]{.aside}

και [συναχθησεται]{.greek-omitted} [συναχθησονται]{.greek-added} εμπροσθεν αυτου παντα τα εθνη και [αφοριει]{.greek-omitted} [αφορισει]{.greek-added} αυτους απ αλληλων ωσπερ ο ποιμην αφοριζει τα προβατα απο των εριφων[25:32]{.aside}

και στησει τα μεν προβατα εκ δεξιων αυτου τα δε εριφια εξ ευωνυμων[25:33]{.aside}

τοτε ερει ο βασιλευς τοις εκ δεξιων αυτου δευτε οι ευλογημενοι του [πατρος]{.greek-abbr} μου κληρονομησατε την ητοιμασμενην υμιν βασιλειαν απο καταβολης κοσμου[25:34]{.aside}

επεινασα γαρ και εδωκατε μοι φαγειν εδιψησα και εποτισατε με [ξενος]{.corr} [ημην]{.corr} [και]{.corr} [συνηγαγετε]{.corr} [με]{.corr}[25:35]{.aside}

γυμνος και περιεβαλετε με ησθενησα και επεσκεψασθε με εν φυλακη [ημην]{.greek-omitted} [ημιν]{.greek-added} και [ηλθετε]{.greek-omitted} [ηλθατε]{.greek-added} προς με[25:36]{.aside}

τοτε αποκριθησονται αυτω οι δικαιοι λεγοντες [κυριε]{.greek-abbr} ποτε σε [ειδομεν]{.greek-omitted} [ιδομεν]{.greek-added} [πεινωντα]{.greek-omitted} [πινωντα]{.greek-added} και εθρεψαμεν η [διψωντα]{.greek-omitted} [διψοντα]{.greek-added} και εποτισαμεν[25:37]{.aside}

ποτε δε σε [ειδομεν]{.greek-omitted} [ιδομεν]{.greek-added} ξενον και συνηγαγομεν η γυμνον και περιεβαλομεν[25:38]{.aside}

ποτε δε [σ]{.unclear}ε [ειδομεν]{.greek-omitted} [ιδομεν]{.greek-added} ασθενη η εν φυλακη και ηλθομεν προς σε[25:39]{.aside}

και αποκριθεις ο βασιλευς ερει αυτοις αμην λεγω υμιν εφ οσον εποιησατε ενι τουτων [των]{.corr} αδελφων μου των ελαχιστων εμοι εποιησατε[25:40]{.aside}

τοτε ερει και τοις εξ ευωνυμων πορευεσθε απ εμου οι κατηραμενοι εις το πυρ το αιωνιον το ητοιμασμενον τω διαβολω και τοις αγγελοις αυτου[25:41]{.aside}

[επεινασα]{.greek-omitted} [επινασα]{.greek-added} γαρ και ουκ εδωκατε μοι φαγειν [εδιψισα]{.greek-added} [εδιψησα]{.corr} και ουκ εποτισατε με[25:42]{.aside}

ξενος [ημην]{.greek-omitted} [ημιν]{.greek-added} και ου συνηγαγετε με γυμνος και ου περιεβαλετε με ασθενης και εν φυλακη και ουκ επεσκεψασθε με[25:43]{.aside}

τοτε αποκριθησονται και αυτοι λεγοντες [κυριε]{.greek-abbr} ποτε σε [ειδομεν]{.greek-omitted} [ιδομεν]{.greek-added} [πεινωντα]{.greek-omitted} [πινωντα]{.greek-added} η διψωντα η ξενον η γυμνον η ασθενη η εν φυλακη και ου διηκονησαμεν σοι[25:44]{.aside}

τοτε αποκριθησεται αυτοις λεγων αμην λεγω υμιν εφ οσον ουκ εποιησατε ενι τουτων των ελαχιστων ουδε εμοι εποιησατε[25:45]{.aside}

και απελευσονται ουτοι εις κολασιν αιωνιον οι δε δικαιοι εις ζωην αιωνιον[25:46]{.aside}

### Chapter 26

και εγενετο οτε ετελεσεν ο [ιησους]{.greek-abbr} παντας τους λογους τουτους ειπεν τοις μαθηταις αυτου[26:1]{.aside}

οιδατε οτι μετα δυο ημερας το πασχα γινεται και ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} παραδιδοται εις το σταυρωθηναι[26:2]{.aside}

[του]{.greek-omitted} [δε]{.greek-omitted} [[τω]{.greek-supplied}]{.greek-added} [[καιρω]{.greek-supplied}]{.greek-added} [[εκεινω]{.greek-supplied}]{.greek-added} [[κυριου]{.greek-abbr}]{.greek-added} [ημων]{.greek-added} [ιησου]{.greek-abbr} γε[νομεν]{.greek-supplied}ου εν βηθανι[α]{.greek-supplied} [εν]{.greek-supplied} [οικι]{.greek-supplied}α σιμωνος [του]{.greek-supplied} [λ]{.greek-supplied}επρου[26:6]{.aside}

προση[λ]{.unclear}[θεν]{.greek-supplied} [αυ]{.greek-supplied}[τω]{.unclear} γυνη [ε[χ]{.unclear}ου[σα]{.greek-supplied}]{.greek-added} [αλαβ]{.greek-supplied}αστρον μυ[ρου]{.greek-supplied} [εχουσα]{.greek-omitted} [βαρυ]{.greek-supplied}τιμου και [κατεχ]{.greek-supplied}εεν επι την κε[φαλην]{.greek-supplied} αυτου ανα[κειμεν]{.greek-supplied}ου[26:7]{.aside}

ιδον[τες]{.greek-supplied} [δε]{.greek-supplied} [οι]{.greek-supplied} [μα]{.greek-supplied}θηται [αυτου]{.greek-omitted} ηγανα[κτησ]{.greek-supplied}αν [λ]{.greek-supplied}εγοντες εις [τ]{.unclear}[ι]{.greek-supplied} [η]{.greek-supplied} [απωλεια]{.greek-omitted} [[α]{.greek-supplied}πολεια]{.greek-added} αυτ[η]{.unclear}[26:8]{.aside}

[ηδυνατο]{.greek-omitted} [εδυνα[τ]{.unclear}ο]{.greek-added} γαρ τουτο το μυρον πραθηναι πολλου και δοθη[ν]{.unclear}[αι]{.greek-supplied} πτωχοις[26:9]{.aside}

γ[νους]{.greek-supplied} [δε]{.greek-supplied} ο [ιησους]{.greek-abbr} ειπεν αυ[τοις]{.greek-supplied} [τι]{.greek-supplied} κοπους παρεχ[ετε]{.greek-supplied} τη γυναικι [εργον]{.greek-supplied} γαρ καλον ειρ[γασα]{.greek-supplied}το εις [εμε]{.greek-supplied}[26:10]{.aside}

[παντοτε]{.greek-supplied} γαρ το[υς]{.greek-supplied} [πτωχους]{.greek-supplied} εχε[τ]{.greek-supplied}ε [μεθ]{.greek-supplied} [εαυτων]{.greek-supplied} εμε δε [ου]{.unclear} [παντοτε]{.greek-supplied} εχετ[ε]{.unclear}[26:11]{.aside}

[βαλουσα]{.greek-supplied} [γαρ]{.greek-supplied} [αυτη]{.greek-supplied} το [μυ]{.unclear}[ρον]{.greek-supplied} [τουτο]{.greek-supplied} [επι]{.unclear} [του]{.greek-supplied} [σωματος]{.greek-supplied} [μου]{.greek-supplied} π[ρ]{.unclear}[ος]{.greek-supplied} [το]{.greek-supplied} [ενταφιασαι]{.greek-supplied} [με]{.greek-supplied} [εποιησεν]{.greek-supplied}[26:12]{.aside}

[αμ]{.unclear}[ην]{.greek-supplied} [λεγω]{.greek-supplied} [υμιν]{.greek-supplied} [οπου]{.greek-supplied} [εαν]{.greek-supplied} [κηρυχ]{.greek-supplied}[θη]{.greek-supplied} [το]{.greek-supplied} [ευαγγελιον]{.greek-supplied} το[υτο]{.greek-supplied} [εν]{.greek-supplied} [ολω]{.greek-supplied} [τω]{.greek-supplied} [κοσ]{.greek-supplied}μω λαλ[ηθησεται]{.greek-supplied} και ο ε[π]{.unclear}[οιησεν]{.greek-supplied} [αυτη]{.greek-supplied} εις μνη[μοσυ]{.greek-supplied}νον αυτ[ης]{.greek-supplied}[26:13]{.aside}

τοτε πορευθεις εις των δωδεκα ο λεγομενος ιουδας ισκαριωτης προς τους αρχιερεις[26:14]{.aside}

ειπεν τι [μοι]{.greek-added} θελετε [μοι]{.greek-omitted} δουναι καγω υμιν παραδωσω αυτον οι δε εστησαν αυτω τριακοντα αργυρια[26:15]{.aside}

και απο τοτε εζητει [ευκαιριαν]{.greek-omitted} [ευ[κ]{.unclear}εριαν]{.greek-added} ινα αυτον παραδω[26:16]{.aside}

τη [δε]{.greek-omitted} πρωτη των αζυμων προσηλθον οι μαθηται τω [[κυριω]{.greek-abbr}]{.greek-added} [ημων]{.greek-added} [ιησου]{.greek-abbr} [[χριστω]{.greek-abbr}]{.greek-added} λεγοντες [αυτω]{.greek-omitted} που θελεις [ετοιμασομεν]{.greek-omitted} [ετοιμασωμεν]{.greek-added} σοι φαγειν το πασχα[26:17]{.aside}

ο δε [[ιησους]{.greek-abbr}]{.greek-added} ειπεν υπαγετε εις την πολιν προς τον δεινα και ειπατε αυτω ο διδασκαλος λεγει ο καιρος μου εγγυς εστιν προς σε ποιω το πασχα μετα των μαθητων μου[26:18]{.aside}

και εποιησαν οι μαθηται ως συνεταξεν αυτοις ο [ιησους]{.greek-abbr} και ητοιμασαν το πασχα[26:19]{.aside}

οψιας δε [γενης]{.greek-added} [γενομενης]{.corr} ανεκειτο μετα των δωδεκα [μαθητων]{.greek-added}[26:20]{.aside}

και εσθιοντων αυτων ειπεν αμην λεγω υμιν οτι εις εξ υμων παραδωσει με[26:21]{.aside}

και λυπουμενοι σφοδρα ηρξαντο λεγειν αυτω εκαστος αυτων μητι εγω ειμι [κυριε]{.greek-abbr}[26:22]{.aside}

ο δε αποκριθεις ειπεν ο εμβαψας μετ εμου [τη]{.greek-added} [[την]{.corr}]{.greek-added} [χειρα]{.greek-added} εν τω τρυβλιω [την]{.greek-omitted} [χειρα]{.greek-omitted} ουτος με παραδωσει[26:23]{.aside}

ο μεν υιος του [ανθρωπου]{.greek-abbr} υπαγει καθως γεγραπται περι αυτου ουαι δε τω [ανθρωπω]{.greek-abbr} εκεινω δι ου ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοται καλον ην αυτω ει ουκ εγεννηθη ο [ανθρωπος]{.greek-abbr} εκεινος[26:24]{.aside}

αποκριθεις δε ιουδας ο παραδ[ι]{.unclear}δους αυτον ειπεν μητι εγω ειμι ραββι λεγει αυτω συ ειπας[26:25]{.aside}

εσθιοντων δε αυτων λαβων ο [ιησους]{.greek-abbr} [τον]{.greek-omitted} αρτον και ευχαριστησας εκλασεν και [εδιδου]{.greek-omitted} [διδους]{.greek-added} τοις μαθηταις [και]{.greek-omitted} ειπεν λαβετε φαγετε τουτο εστιν το σωμα μου[26:26]{.aside}

και λαβων [το]{.greek-omitted} ποτηριον και ευχαριστησας εδωκεν αυτοις λεγων πιετε εξ αυτου παντες[26:27]{.aside}

τουτο γαρ εστιν το αιμα μου το της καινης διαθηκης το περι πολλων [εκχυνομενον]{.greek-omitted} [εκχυννομενον]{.greek-added} εις αφεσιν αμαρτιων[26:28]{.aside}

λεγω δε υμιν οτι ου μη πιω απ αρτι εκ τουτου του γεννηματος της αμπελου εως της ημερας εκεινης οταν αυτο πινω [καινον]{.greek-added} μεθ υμων [καινον]{.greek-omitted} εν τη βασιλεια του [πατρος]{.greek-abbr} μου[26:29]{.aside}

και υμνησαντες εξηλθον εις το ορος των ελαιων[26:30]{.aside}

τοτε ερχεται [μετ]{.greek-omitted} [αυτων]{.greek-omitted} ο [ιησους]{.greek-abbr} [μετα]{.greek-added} [των]{.greek-added} [μαθητων]{.greek-added} [αυτου]{.greek-added} εις χωριον λεγομενον [γεθσημανη]{.greek-omitted} [γεθσημανει]{.greek-added} και λεγει [τοις]{.greek-omitted} [αυτοις]{.greek-added} [μαθηταις]{.greek-omitted} καθισατε αυτου εως [ου]{.greek-omitted} απελθων προσευξωμαι εκει[26:36]{.aside}

και παραλαβων τον πετρον και τους [[δ]{.greek-supplied}υο]{.corr} υιους ζεβεδαιου ηρξατο λυπεισθαι και [α]{.greek-supplied}δημονειν[26:37]{.aside}

τοτε λεγει αυτοις ο [ιησους]{.greek-abbr} περιλυπος εστιν η ψυχη μου εως θανατου μεινατε ωδε και γρηγορειτε μετ εμου[26:38]{.aside}

και προσελθων μικρον επεσεν επι προσωπον αυτου προσευχομενος και λεγων [πατερ]{.greek-abbr} μου ει δυνατον [εστιν]{.greek-omitted} [παρελθετω]{.greek-omitted} [παρελθατω]{.greek-added} απ εμου το ποτηριον τουτο πλην ουχ ως εγω θελω αλλ ως συ[26:39]{.aside}

και ερχεται προς τους μαθητας και ευρισκει αυτους [καθευδοντας]{.greek-omitted} [καθευτας]{.greek-added} και λεγει τω πετρω ουτως ουκ ισχυσατε μιαν ωραν γρηγορησαι μετ εμου[26:40]{.aside}

γρηγορειτε και προσευχεσθε ινα μη εισελθητε εις πειρασμον το μεν [πνευμα]{.greek-abbr} προθυμον η δε σαρξ ασθενης[26:41]{.aside}

παλιν εκ δευτερου απελθων προσηυξατο λεγων [πατερ]{.greek-abbr} μου ει ου [δυναται]{.greek-omitted} [δυνατε]{.greek-added} τουτο το ποτηριον παρελθειν [απ]{.greek-omitted} [εμου]{.greek-omitted} εαν μη αυτο πιω γενηθητω το θελημα σου[26:42]{.aside}

και ελθων [ευρισκει]{.greek-omitted} [παλιν]{.greek-added} [ευρεν]{.greek-added} αυτους [παλιν]{.greek-omitted} καθευδοντας ησαν γαρ [αυτων]{.greek-omitted} οι οφθαλμοι [αυτων]{.greek-added} βεβαρημενοι[26:43]{.aside}

και αφεις αυτους απελθων [παλιν]{.greek-omitted} προσηυξατο εκ τριτου τον αυτον λογον ειπων[26:44]{.aside}

τοτε ερχεται προς τους μαθητας [αυτου]{.greek-omitted} και λεγει αυτοις καθευδετε το λοιπον και αναπαυεσθε ιδου ηγγικεν η ωρα και ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} παραδιδοται εις χειρας αμαρτωλων[26:45]{.aside}

εγειρεσθε αγωμεν ιδου [ηγγικεν]{.greek-omitted} ο παραδιδους με [ηγγικεν]{.greek-added}[26:46]{.aside}

[και]{.greek-omitted} ετι αυτου λαλουντος ιδου ιουδας εις των δωδεκα ηλθεν και μετ αυτου οχλος πολυς μετα μαχαιρων και ξυλων απο των αρχιερεων και πρεσβυτερων του λαου[26:47]{.aside}

ο δε παραδιδους αυτον εδωκεν αυτοις σημειον λεγων ον αν φιλησω αυτος ε[σ]{.unclear}τιν κρατησατε αυτον[26:48]{.aside}

και ευθεως προσελθων τω [ιησου]{.greek-abbr} ειπεν χαιρε ραββι και κατεφιλησεν αυτον[26:49]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω [εταιρε]{.greek-omitted} [ετερε]{.greek-added} εφ ω [παρει]{.greek-omitted} [παρη]{.greek-added} τοτε προσελθοντες επεβαλον τας χειρας επι τον [ιησουν]{.greek-abbr} και εκρατησαν αυτον[26:50]{.aside}

και ιδου εις των μετα [ιησου]{.greek-abbr} εκτεινας την χειρα απεσπασεν την μαχαιραν αυτου και παταξας τον δουλον του αρχιερεως αφειλεν αυτου το ωτιον[26:51]{.aside}

τοτε λεγει αυτω ο [ιησους]{.greek-abbr} αποστρεψον [σου]{.greek-omitted} την μαχαιραν [σου]{.greek-added} εις τον τοπον αυτης παντες γαρ οι λαβοντες μαχαιραν εν [μαχαιρα]{.greek-omitted} [μαχαιρη]{.greek-added} [αποθανουνται]{.greek-omitted} [απολουνται]{.greek-added}[26:52]{.aside}

η δοκεις οτι ου δυναμαι [αρτι]{.greek-omitted} παρακαλεσαι τον πατερα μου και παραστησει μοι [αρτι]{.greek-added} [ωδε]{.greek-added} πλειους η δωδεκα [λεγεωνας]{.greek-omitted} [λεγεωνων]{.greek-added} αγγελων[26:53]{.aside}

πως ουν πληρωθωσιν αι γραφαι οτι ουτως δει γενεσθαι[26:54]{.aside}

εν εκεινη τη ωρα ειπεν ο [ιησους]{.greek-abbr} τοις οχλοις ως επι ληστην [εξηλθετε]{.greek-omitted} [εξηλθατε]{.greek-added} μετα μαχαιρων και ξυλων συλλαβειν με καθ ημεραν [προς]{.greek-omitted} [υμας]{.greek-omitted} [εκαθεζομην]{.greek-omitted} [διδασκων]{.greek-omitted} εν τω ιερω [εκαθεζομην]{.greek-added} [προς]{.greek-added} [υμας]{.greek-added} [διδασκων]{.greek-added} και ουκ εκρατησατε με[26:55]{.aside}

τουτο δε ολον γεγονεν ινα πληρωθωσιν αι γραφαι των προφητων τοτε οι μαθηται παντες αφεντες αυτον εφυγον[26:56]{.aside}

οι δε κρατησαντες τον [ιησουν]{.greek-abbr} απηγαγον προς καιαφαν τον αρχιερεα οπου οι [γραμματεις]{.greek-omitted} [αρχιερεις]{.greek-added} και οι πρεσβυτεροι συνηχθησαν[26:57]{.aside}

ο δε πετρος [ηκολουθει]{.greek-omitted} [ηκολουθη]{.greek-added} [αυτω]{.greek-omitted} [αυτου]{.greek-added} απο μακροθεν εως της αυλης του [αρχιερεως]{.greek-omitted} [αρχιε]{.greek-added} [ρεως]{.greek-added} και εισελθων εσω εκαθητο μετα των υπηρετων [ιδειν]{.greek-omitted} [ειδειν]{.greek-added} το τελος[26:58]{.aside}

οι δε αρχιερεις και οι πρεσβυτεροι και το συνεδριον [ολον]{.greek-omitted} εζητουν ψευδομαρτυριαν κατα του [ιησου]{.greek-abbr} οπως [θανατωσωσιν]{.greek-omitted} αυτον [θανατωσουσιν]{.greek-added}[26:59]{.aside}

και ουχ [ευρον]{.greek-omitted} [ηυρον]{.greek-added} [και]{.greek-omitted} πολλων ψευδομαρτυρων προσελθοντων [ουχ]{.greek-omitted} [ευρον]{.greek-omitted} [υστερον]{.greek-added} [δε]{.greek-added} [προσελθοντες]{.greek-added} [δυο]{.greek-added} [ψευδομαρτυρες]{.greek-added}[26:60]{.aside}

[υστερον]{.greek-omitted} [δε]{.greek-omitted} [προσελθοντες]{.greek-omitted} [δυο]{.greek-omitted} [ψευδομαρτυρες]{.greek-omitted} ειπον ουτος εφη δυναμαι καταλυσαι τον ναον του [θεου]{.greek-abbr} και δια τριων ημερων οικοδομησαι αυτον[26:61]{.aside}

και αναστας ο αρχιερευς ειπεν αυτω [ουδε]{.greek-added} [ουδεν]{.corr} αποκρινη τι ουτοι σου [καταμαρτυρουσιν]{.greek-omitted} [κατηγορουσιν]{.greek-added}[26:62]{.aside}

ο δε [ιησους]{.greek-abbr} εσιωπα και αποκριθεις ο αρχιερευς ειπεν αυτω [εξορκιζω]{.greek-omitted} [ορκιζω]{.greek-added} σε κατα του [θεου]{.greek-abbr} του ζωντος ινα ημιν [ειπης]{.greek-omitted} [ειπεις]{.greek-added} ει συ ει ο [χριστος]{.greek-abbr} ο [υιος]{.greek-abbr} του [θεου]{.greek-abbr} [του]{.greek-added} [ζωντος]{.greek-added}[26:63]{.aside}

λεγει [αυτοις]{.greek-added} [αυτω]{.greek-omitted} [[αυτο]{.corr}]{.greek-added} ο [ιησους]{.greek-abbr} συ ειπας πλην λεγω υμιν απ αρτι οψεσθε τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} καθημενον εκ δεξιων της δυναμεως και ερχομενον [επι]{.greek-omitted} [μετα]{.greek-added} των νεφελων του [ουρανου]{.greek-abbr}[26:64]{.aside}

τοτε ο αρχιερευς [διερρηξεν]{.greek-omitted} [διερριξεν]{.greek-added} τα ιματια αυτου λεγων οτι εβλασφημησεν τι ετι [χρειαν]{.greek-omitted} [χριαν]{.greek-added} εχομεν μαρτυρων [ιδε]{.greek-omitted} [ειδε]{.greek-added} νυν ηκουσατε την [βλασφημιαν]{.greek-omitted} [βλασφημι]{.greek-added} [αν]{.greek-added} αυτου[26:65]{.aside}

τι υμιν δοκει οι δε αποκριθεντες ειπον ενοχος θανατου εστιν[26:66]{.aside}

τοτε ενεπτυσαν εις το προσωπον αυτου και εκολαφισαν αυτον οι δε [ερραπησαν]{.greek-added} [ερραπισαν]{.corr} [αυτον]{.greek-added}[26:67]{.aside}

λεγοντες προφητευσον ημιν [χριστε]{.greek-abbr} τις εστιν ο παισας σε[26:68]{.aside}

ο δε πετρος [εκαθητο]{.greek-added} εξω [εκαθητο]{.greek-omitted} εν τη αυλη και προσηλθεν αυτω μια παιδισκη λεγουσα και συ [ησθα]{.greek-omitted} μετα [ιησου]{.greek-abbr} [ησθα]{.greek-added} του γαλιλαιου[26:69]{.aside}

ο δε ηρνησατο εμπροσθεν [αυτων]{.greek-omitted} παντων λεγων ουκ οιδα τι λεγεις[26:70]{.aside}

εξελθοντα δε αυτον εις τον πυλωνα ειδεν αυτον αλλη και λεγει [αυτοις]{.greek-omitted} [τοις]{.greek-added} εκ[ει]{.greek-supplied} και ουτος ην μετα [ιησου]{.greek-abbr} του ναζωραιου[26:71]{.aside}

και παλιν ηρνησατο μεθ ορκου οτι ουκ οιδα τον [ανθρωπον]{.greek-abbr}[26:72]{.aside}

μετα μικρον δε προσελθοντες οι [εστωτες]{.greek-omitted} [παρεστωτες]{.greek-added} ειπον τω πετρω αληθως και συ εξ αυτων ει και γαρ η λαλια σου δηλον [σε]{.corr} ποιει[26:73]{.aside}

τοτε ηρξατο καταθεματιζειν και ομνυειν οτι ουκ οιδα τον [ανθρωπον]{.greek-abbr} και ευθεως αλεκτωρ εφωνησεν[26:74]{.aside}

και εμνησθη ο πετρος [του]{.greek-omitted} [ρηματος]{.greek-omitted} του [ιησου]{.greek-abbr} ειρηκοτος αυτω [ο]{.unclear}τι πριν [αλεκτορα]{.greek-omitted} [αλεκτωρα]{.greek-added} φωνησαι [τρις]{.greek-omitted} [τρεις]{.greek-added} απαρνηση με και εξελθων εξω εκλαυσεν πικρως[26:75]{.aside}

### Chapter 27

πρωιας δε γενομενης συμβουλιον ελαβον παντες οι αρχιερεις και οι πρεσβυτεροι του λαου [κατα]{.greek-omitted} [[ωσ]{.greek-supplied}τε]{.greek-added} [[κα]{.corr}]{.greek-added} [του]{.corr} [[ιησου]{.greek-abbr}]{.corr} [ωστε]{.corr} θανατωσαι αυτον[27:1]{.aside}

και δησαντες αυτον απηγαγον και παρεδωκαν [αυτον]{.greek-omitted} ποντιω πιλατω τω ηγεμονι[27:2]{.aside}

τοτε [ιδων]{.greek-omitted} [ειδων]{.greek-added} ιουδας ο [παραδιδους]{.greek-omitted} [παραδους]{.greek-added} αυτον οτι κατεκριθη [μεταμεληθεις]{.greek-omitted} [μεταμελιθεις]{.greek-added} απεστρεψεν τα τριακοντα αργυρια τοις αρχιερευσιν και [τοις]{.greek-omitted} πρεσβυτεροις[27:3]{.aside}

λεγων ημαρτον παραδους αιμα [αθωον]{.greek-omitted} [δικαιον]{.greek-added} οι δε ειπον τι προς ημας συ [οψει]{.greek-omitted} [οψη]{.greek-added}[27:4]{.aside}

και ριψας τα αργυρια [εν]{.greek-omitted} [τω]{.greek-omitted} [ναω]{.greek-omitted} [εις]{.greek-added} [τον]{.greek-added} [ναον]{.greek-added} ανεχωρησεν και απελθων απηγξατο[27:5]{.aside}

οι δε αρχιερεις λαβοντες τα αργυρια [ειπον]{.greek-omitted} [ειπαν]{.greek-added} ουκ εξεστιν βαλειν αυτα εις τον κορβαναν επει τιμη αιματος εστιν[27:6]{.aside}

συμβουλιον [δε]{.greek-omitted} [τε]{.greek-added} λαβοντες ηγορασαν εξ αυτων τον αγρον του κεραμεως [εις]{.greek-omitted} [εισς]{.greek-added} ταφην τοις ξενοις[27:7]{.aside}

διο εκληθη ο αγρος εκεινος αγρος αιματος εως της σημερον[27:8]{.aside}

τοτε επληρωθη το ρηθεν δια ιερεμιου του προφητου λεγοντος και ελαβον τα τριακοντα αργυρια την τιμην του τετιμημενου ον ετιμησαντο απο υιων [ισραηλ]{.greek-abbr}[27:9]{.aside}

και εδωκαν αυτα εις τον αγρον του κεραμεως καθα συνεταξεν μοι [κυριος]{.greek-abbr}[27:10]{.aside}

ο δε [ιησους]{.greek-abbr} εστη εμπροσθεν του ηγεμονος και επηρωτησεν αυτον ο ηγεμων λεγων συ ει ο βασιλευς των ιουδαιων ο δε [ιησους]{.greek-abbr} εφη αυτω συ λεγεις[27:11]{.aside}

και εν τω κατηγορεισθαι αυτον υπο των αρχιερεων και [των]{.greek-omitted} πρεσβυτερων ουδεν απεκρινατο[27:12]{.aside}

τοτε λεγει αυτω ο πιλατος ουκ ακουεις ποσα σου καταμαρτυρουσιν[27:13]{.aside}

και ουκ [α]{.greek-added} [απεκριθη]{.greek-omitted} [πεκριθη]{.greek-added} αυτω προς ουδε εν ρημα ωστε θαυμαζειν τον ηγεμονα λιαν[27:14]{.aside}

κατα δε εορτην [ειωθει]{.greek-omitted} [ιωθι]{.greek-added} ο ηγεμων απολυειν [ενα]{.greek-omitted} τω οχλω [ενα]{.greek-added} δεσμιον ον ηθελον[27:15]{.aside}

ειχον δε τοτε δεσμιον επισημον λεγομενον [[ιησουν]{.greek-abbr}]{.greek-added} βαραββαν[27:16]{.aside}

συνηγμενων [ουν]{.greek-omitted} [δε]{.greek-added} αυτων ειπεν αυτοις ο πιλατος τινα θελετε [ινα]{.greek-added} απολυσω υμιν [ιησουν]{.greek-added} βαραββαν η [ιησουν]{.greek-abbr} τον λεγομενον [χριστον]{.greek-abbr}[27:17]{.aside}

ηδει γαρ οτι δια φθονον παρεδωκαν αυτον[27:18]{.aside}

καθημενου δε αυτου επι του βηματος απεστειλεν προς αυτον η γυνη αυτου λεγουσα μηδεν σοι και τω δικαιω εκεινω πολλα γαρ επαθον σημερον κατ οναρ δι αυτον[27:19]{.aside}

οι δε αρχιερεις και οι πρεσβυτεροι επεισαν τους οχλους ινα αιτησωνται τον βαραββαν τον δε [ιησουν]{.greek-abbr} απολεσωσιν[27:20]{.aside}

αποκριθεις δε ο ηγεμων ειπεν αυτοις τινα θελετε απο των δυο απολυσω υμιν οι δε ειπον βαραββαν[27:21]{.aside}

λεγει αυτοις ο πιλατος τι ουν ποιησω [ιησουν]{.greek-abbr} τον λεγομενον [χριστον]{.greek-abbr} λεγουσιν [αυτω]{.greek-omitted} παντες σταυρωθητω[27:22]{.aside}

ο δε ηγεμων εφη τι γαρ κακον εποιησεν οι δε περισσως εκραζον λεγοντες σταυρωθητω[27:23]{.aside}

[ιδων]{.greek-omitted} [ειδων]{.greek-added} δε ο [πι]{.greek-added} [πιλατος]{.greek-omitted} [λατος]{.greek-added} οτι ουδεν ωφελει αλλα μαλλον θορυβος γινεται λαβων υδωρ απενιψατο τας χειρας απεναντι του οχλου λεγων αθωος ειμι απο του αιματος [του]{.greek-omitted} [δικαιου]{.greek-omitted} τουτου υμεις οψεσθε[27:24]{.aside}

και αποκριθεις πας ο λαος ειπεν το αιμα αυτου εφ ημας και επι τα τεκνα ημων[27:25]{.aside}

τοτε απελυσεν αυτοις τον βαραββαν τον δε [ιησουν]{.greek-abbr} φραγελλωσας παρεδωκεν ινα σταυρωθη[27:26]{.aside}

τοτε οι στρατιωται του ηγεμονος παραλαβοντες τον [ιησουν]{.greek-abbr} εις το πραιτωριον συνηγαγον επ αυτον ολην την [σπειραν]{.greek-omitted} [σπιραν]{.greek-added}[27:27]{.aside}

και εκδυσαντες αυτον περιεθηκαν αυτω χλαμυδα κοκκινην[27:28]{.aside}

και πλεξαντες στεφανον εξ ακανθων [επεθηκαν]{.greek-omitted} [εθηκαν]{.greek-added} επι την κεφαλην αυτου και καλαμον [επι]{.greek-omitted} [εν]{.greek-added} [την]{.greek-omitted} [τη]{.greek-added} [δεξιαν]{.greek-omitted} [δεξια]{.greek-added} αυτου και γονυπετησαντες εμπροσθεν αυτου ενεπαιζον αυτω λεγοντες χαιρε [ο]{.greek-omitted} [βασιλευς]{.greek-omitted} [βασιλευ]{.greek-added} των ιουδαιων[27:29]{.aside}

και εμπτυσαντες εις αυτον ελαβον τον καλαμον και ετυπτον [εις]{.greek-omitted} την κεφαλην αυτου[27:30]{.aside}

και οτε [ενεπαιξαν]{.greek-omitted} [ενεπεξαν]{.greek-added} αυτω εξεδυσαν αυτον την χλαμυδα και ενεδυσαν αυτον τα ιματια αυτου και απηγαγον αυτον εις το σταυρωσαι[27:31]{.aside}

εξερχομενοι δε [ευρον]{.greek-omitted} [ηυρον]{.greek-added} [ανθρωπον]{.greek-abbr} [κυριναιον]{.greek-added} [κυρηναιον]{.corr} ονοματι σιμωνα τουτον ηγγαρευσαν ινα αρη τον σταυρον αυτου[27:32]{.aside}

και [ελθοντες]{.greek-omitted} [εξελθοντες]{.greek-added} εις τοπον λεγομενον γολγοθα ο εστιν [λεγομενος]{.greek-omitted} κρανιου τοπος[27:33]{.aside}

εδωκαν αυτω πιειν [οξος]{.greek-omitted} [οινον]{.greek-added} μετα χολης μεμιγμενον και γευσαμενος ουκ ηθελεν πιειν[27:34]{.aside}

σταυρωσαντες δε αυτον διεμερισαντο τα ιματια αυτου βαλλοντες κληρον [ινα]{.greek-added} [πληρωθη]{.greek-added} [το]{.greek-added} [ρηθεν]{.greek-added} [δια]{.greek-added} [του]{.greek-added} [προφητου]{.greek-added} [διεμερισαν]{.greek-added} [τα]{.greek-added} [ιματια]{.greek-added} [μου]{.greek-added} [εαυτοις]{.greek-added} [και]{.greek-added} [επι]{.greek-added} [τον]{.greek-added} [ιματισμον]{.greek-added} [μου]{.greek-added} [εβαλλον]{.greek-added} [κληρον]{.greek-added}[27:35]{.aside}

και καθημενοι ετηρουν αυτον εκει[27:36]{.aside}

και επεθηκαν επανω της κεφαλης αυτου την αιτιαν αυτου γεγραμμενην ουτος εστιν [ιησους]{.greek-abbr} ο βασιλευς των ιουδαιων[27:37]{.aside}

τοτε σταυρουνται συν αυτω δυο λησται εις εκ δεξιων και εις εξ ευωνυμων[27:38]{.aside}

οι δε παραπορευομενοι εβλασφημουν αυτον κινουντες τας κεφαλας αυτων[27:39]{.aside}

και λεγοντες ο καταλυων τον ναον και εν τρισιν ημεραις οικοδομων σωσον σεαυτον ει [υιος]{.greek-abbr} ει του [θεου]{.greek-abbr} καταβηθι απο του σταυρου[27:40]{.aside}

ομοιως [δε]{.greek-omitted} και οι αρχιερεις εμπαιζοντες μετα των [γραμματεων]{.greek-omitted} [και]{.greek-omitted} πρεσβυτερων και [γραμματαιων]{.greek-added} [και]{.greek-added} [φαρισαιων]{.greek-omitted} [φαρεισαιων]{.greek-added} ελεγον[27:41]{.aside}

αλλους εσωσεν εαυτον ου δυναται σωσαι ει βασιλευς [[ισραηλ]{.greek-abbr}]{.corr} εστιν καταβατω νυν απο του σταυρου και [πιστευσομεν]{.greek-omitted} [πιστευσωμεν]{.greek-added} [επ]{.greek-omitted} αυτω[27:42]{.aside}

[ει]{.greek-added} πεποιθεν επι τον [θεον]{.greek-abbr} ρυσασθω [νυν]{.greek-omitted} αυτον ει θελει αυτον ειπεν γαρ οτι [θεου]{.greek-abbr} ειμι [υιος]{.greek-abbr}[27:43]{.aside}

το δ αυτο και οι λησται οι [συσταυρωθεντες]{.greek-omitted} [συνσταυρωθεν]{.greek-added} αυτω ωνειδιζον αυτον[27:44]{.aside}

απο δε εκτης ωρας σκοτος εγενετο επι πασαν την γην εως ωρας ενατης[27:45]{.aside}

περι δε την ενατην ωραν [ανεβοησεν]{.greek-omitted} [εβοησεν]{.greek-added} ο [ιησους]{.greek-abbr} φωνη μεγαλη λεγων [ηλι]{.greek-omitted} [ηλει]{.greek-added} [ηλι]{.greek-omitted} [ηλει]{.greek-added} [λιμα]{.greek-omitted} [λεμα]{.greek-added} [σαβαχθανι]{.greek-omitted} [σαβαχθανει]{.greek-added} τουτ εστιν θεε μου θεε μου [ινα]{.greek-omitted} [ινατι]{.greek-added} [τι]{.greek-omitted} με [εγκατελιπες]{.greek-omitted} [εγκατελειπας]{.greek-added}[27:46]{.aside}

τινες δε των εκει εστωτων ακουσαντες ελεγον οτι ηλιαν φωνει ουτος[27:47]{.aside}

και ευθεως δραμων εις εξ αυτων και λαβων σπογγον πλησας τε οξους και περιθεις καλαμω εποτιζεν αυτον[27:48]{.aside}

οι δε λοιποι [ελεγον]{.greek-omitted} [ειπον]{.greek-added} αφες [ιδωμεν]{.greek-omitted} [ειδωμεν]{.greek-added} ει ερχεται ηλιας [σωσων]{.greek-omitted} [σωσαι]{.greek-added} αυτον[27:49]{.aside}

ο δε [ιησους]{.greek-abbr} παλιν κραξας φωνη μεγαλη αφηκεν το [πνευμα]{.greek-abbr}[27:50]{.aside}

και ιδου το καταπετασμα του ναου εσχισθη εις δυο απο ανωθεν εως κατω και η γη [εσεισθη]{.greek-omitted} [εσισθη]{.greek-added} και αι πετραι εσχισθησαν[27:51]{.aside}

και τα μνημεια ανεωχθησαν και πολλα σωματα των κεκοιμημενων αγιων [ηγερθη]{.greek-omitted} [ηγερθησαν]{.greek-added}[27:52]{.aside}

και εξελθοντες εκ των μνημειων μετα την εγερσιν αυτου εισηλθον εις την αγιαν πολιν και ενεφανισθησαν πολλοις[27:53]{.aside}

ο δε [εκατονταρχος]{.greek-omitted} [εκατονταρχης]{.greek-added} και οι μετ αυτου τηρουντες τον [ιησουν]{.greek-abbr} ιδοντες τον [σεισμον]{.greek-omitted} [σισμον]{.greek-added} και τα γενομενα εφοβηθησαν [σφοδρα]{.greek-omitted} [σφο]{.greek-added} [δρα]{.greek-added} λεγοντες αληθως [θεου]{.greek-abbr} [υιος]{.greek-abbr} ην ουτος[27:54]{.aside}

ησαν δε εκει γυναικες πολλαι απο μακροθεν θεωρουσαι αιτινες ηκολουθησαν τω [ιησου]{.greek-abbr} απο της γαλιλαιας διακονουσαι αυτω[27:55]{.aside}

εν αις ην μαρια η μαγδαληνη και μαρια η [του]{.greek-omitted} ιακωβου και [ιωση]{.greek-omitted} [ιωσητος]{.greek-added} [μητηρ]{.greek-abbr} και η μητηρ των υιων ζεβεδαιου[27:56]{.aside}

οψιας [δε]{.greek-omitted} γενομενης ηλθεν [ανθρωπος]{.greek-abbr} πλουσιος απο αριμαθαιας τουνομα ιωσηφ ος και αυτος εμαθητευσεν τω [ιησου]{.greek-abbr}[27:57]{.aside}

ουτος προσελθων τω πιλατω ητησατο το σωμα του [ιησου]{.greek-abbr} τοτε ο πιλατος εκελευσεν αποδοθηναι το σωμα[27:58]{.aside}

και λαβων το σωμα ο ιωσηφ ενετυλιξεν αυτο σινδονι καθαρα[27:59]{.aside}

και εθηκεν [αυτο]{.greek-omitted} εν τω καινω αυτου μνημειω ο ελατομησεν εν τη πετρα και [προσκυλισας]{.greek-omitted} [προσκυλησας]{.greek-added} λιθον μεγαν τη θυρα του μνημειου απηλθεν[27:60]{.aside}

ην δε εκει [μαρια]{.greek-omitted} [μαριαμ]{.greek-added} η μαγδαληνη και η αλλη μαρια καθημεναι απεναντι του ταφου[27:61]{.aside}

τη [δε]{.greek-omitted} επαυριον ητις εστιν μετα την παρασκευην συνηχθησαν οι αρχιερεις και οι [φαρισαιοι]{.greek-omitted} [φαρεισαιοι]{.greek-added} προς πιλατον[27:62]{.aside}

λεγοντες κυριε εμνησθημεν οτι εκεινος ο πλανος ειπεν ετι ζων μετα τρεις ημερας εγειρομαι[27:63]{.aside}

κελευσον ουν ασφαλισθηναι τον ταφον εως της τριτης ημερας μηποτε ελθοντες οι μαθηται αυτου νυκτος κλεψωσιν αυτον και ειπωσιν τω λαω [οτι]{.greek-added} ηγερθη απο των νεκρων και εσται η εσχατη πλανη χειρων της πρωτης[27:64]{.aside}

εφη δε αυτοις ο πιλατο[ς]{.unclear} εχετε κουστωδιαν υπαγετε ασφαλισασθε ως οιδατε[27:65]{.aside}

οι δε πορευθεντες ησφαλισαντο τον ταφον σφραγι[σ]{.greek-supplied}αντες τον λιθον μετα της κουστωδιας[27:66]{.aside}

### Chapter 28

οψε [δε]{.greek-omitted} σαββατων τη επιφωσκουση εις μιαν σαββ[α]{.greek-supplied}των ηλθεν [μαρια]{.greek-omitted} [μαριαμ]{.greek-added} η μαγδαληνη και η αλλη μαρια θεωρησαι τον ταφον[28:1]{.aside}

και ιδου [σεισμος]{.greek-omitted} [σισμος]{.greek-added} εγενετο μεγας αγγελος γαρ [κυριου]{.greek-abbr} καταβας εξ [ουρανου]{.greek-abbr} [προελθων]{.greek-added} [προσελθων]{.corr} [απεκυλισεν]{.greek-omitted} [απεκυλησε]{.greek-added} τον λιθον [[α]{.unclear}πο]{.corr} [της]{.corr} [[θ]{.greek-supplied}υρας]{.corr} [[[τ]{.greek-supplied}ου]{.corr}]{.greek-added} [[μνη[μ]{.greek-supplied}ειου]{.corr}]{.greek-added} και εκαθητο επανω αυτου[28:2]{.aside}

ην δε η ιδεα αυτου ως αστραπη και το ενδυμα αυτου λευκον ωσει χιων[28:3]{.aside}

απο δε του [φ]{.unclear}οβου αυτου εσεισθησαν οι τηρουντες και [εγενοντο]{.greek-omitted} [ωσει]{.greek-omitted} [εγενηθησαν]{.greek-added} [ως]{.greek-added} νεκροι[28:4]{.aside}

[απο]{.greek-added} [αποκριθεις]{.greek-omitted} [κριθεις]{.greek-added} δε ο αγγελος ειπεν ταις γυναιξιν μη φοβεισθε υμεις οιδα γαρ οτι [ιησουν]{.greek-abbr} τον εσταυρωμενον ζητειτε[28:5]{.aside}

ουκ εστιν ωδε ηγερθη γαρ καθως ειπεν δευτε ιδετε τον τοπον οπου εκειτο ο [κυριος]{.greek-abbr}[28:6]{.aside}

και ταχυ [πορευθεισαι]{.greek-omitted} [πορευθησαι]{.greek-added} ειπατε τοις μαθηταις αυτου οτι ηγερθη απο των νεκρων και ιδου προαγει υμας εις την γαλιλαιαν εκει αυτον οψεσθε ιδου [ειπον]{.greek-omitted} [ειπα]{.greek-added} υμιν[28:7]{.aside}

και εξελθουσαι ταχυ απο του μνημειου μετα φοβου και χαρας μεγαλης εδραμον απαγγειλαι τοις μαθηταις αυτου[28:8]{.aside}

[ως]{.greek-omitted} [δε]{.greek-omitted} [επορευοντο]{.greek-omitted} [απαγγειλαι]{.greek-omitted} [τοις]{.greek-omitted} [μαθηταις]{.greek-omitted} [αυτου]{.greek-omitted} και ιδου [ο]{.greek-added} [ιησους]{.greek-abbr} [απηντησεν]{.greek-omitted} [υπιντησεν]{.greek-added} [αυ]{.greek-added} [αυταις]{.greek-omitted} [ταις]{.greek-added} λεγων χαιρετε αι δε προσελθουσαι εκρατησαν αυτου τους ποδας και προσεκυνησαν αυτω[28:9]{.aside}

τοτε λεγει αυταις ο [ιησους]{.greek-abbr} μη φοβεισθε υπαγετε απαγγειλατε τοις αδελφοις μου ινα απελθωσιν εις την γαλιλαιαν [και]{.greek-omitted} [κακει]{.greek-added} [εκει]{.greek-omitted} με οψονται[28:10]{.aside}

πορευομενων δε αυτων ιδου τινες της κουστωδιας ελθοντες εις την πολιν απηγγειλαν τοις αρχιερευσιν απαντα τα γενομενα[28:11]{.aside}

και συναχθεντες μετα των πρεσβυτερων συμβουλιον [τες]{.greek-added} [[τε]{.greek-supplied}]{.corr} [[λα]{.greek-supplied}βοντες]{.corr} [[αργυ]{.greek-supplied}ρια]{.corr} [[ι]{.greek-supplied}κανα]{.corr} εδωκαν τοις στρατιωταις[28:12]{.aside}

λεγοντες ειπατε οτι οι μαθητ[α]{.unclear}ι αυτου νυκτος [ελθοντες]{.greek-omitted} [ελθον]{.greek-added} [τες]{.greek-added} εκλεψαν αυτον ημων κοιμωμενων[28:13]{.aside}

και εαν ακουσθη τουτο επι του ηγεμονος ημεις πεισομεν [αυτον]{.greek-omitted} και υμας αμεριμνους [ποιησομεν]{.greek-omitted} [ποιησωμεν]{.greek-added}[28:14]{.aside}

οι δε λαβοντες τα αργυρια εποιησαν ως εδιδαχθησαν και διεφημισθη ο λογος ουτος παρα ιουδαιοις μεχρι της σημερον[28:15]{.aside}

οι δε ενδεκα μαθηται επορευθησαν εις την γαλιλαιαν εις το ορος ου εταξατο αυτοις ο [ιησους]{.greek-abbr}[28:16]{.aside}

και ιδοντες αυτον προσεκυνησαν [αυτω]{.greek-omitted} οι δε εδιστασαν[28:17]{.aside}

και προσελθων ο [ιησους]{.greek-abbr} ελαλησεν αυτοις λεγων εδοθη μοι πασα εξουσια εν [ουρανω]{.greek-abbr} και επι γης[28:18]{.aside}

πορευθεντες [ουν]{.greek-added} μαθητευσατ[ε]{.unclear} παντα τα εθνη βαπτιζοντες αυτους εις το ονομα του [πατρος]{.greek-abbr} και του [υιου]{.greek-abbr} και του αγιου [πνευματος]{.greek-abbr}[28:19]{.aside}

διδασκοντες αυτους τηρειν παντα οσα ενετειλαμην υμιν και ιδου εγω μεθ υμων ειμι πασας τας ημερας εως της συντελειας του αιωνος [αμην]{.greek-omitted}[28:20]{.aside}

## The Gospel of Mark

### Chapter 1

αρχη του ευαγγελιου [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} υιου του [θεου]{.greek-abbr}[1:1]{.aside}

ως γεγραπται εν [τοις]{.greek-omitted} [ησαια]{.greek-added} [τω]{.greek-added} [προφηταις]{.greek-omitted} [προφητη]{.greek-added} ιδου εγω αποστελλω τον αγγελον μου προ [προσωπου]{.greek-omitted} [προσω]{.greek-added} σου ος κατασκευασει την οδον σου εμπροσθεν σου[1:2]{.aside}

φωνη βοωντος εν τη ερημω ετοιμασατε την οδον [κυριου]{.greek-abbr} ευθειας ποιειτε τας τριβους αυτου[1:3]{.aside}

εγενετο ιωαννης βαπτιζων εν τη ερημω και κηρυσσων βαπτισμα μετανοιας εις αφεσιν αμαρτιων[1:4]{.aside}

και εξεπορευετο προς αυτον πασα η ιουδαια χωρα και οι [ιεροσολυμιται]{.greek-omitted} [ιεροσολυμηται]{.greek-added} [παντες]{.greek-added} και εβαπτιζοντο [παντες]{.greek-omitted} [υπ]{.greek-added} [αυτου]{.greek-added} εν τω ιορδανη ποταμω [εξολογουμενοι]{.greek-added} [υπ]{.greek-omitted} [αυτου]{.greek-omitted} [εξομολογουμενοι]{.corr} τας αμαρτιας αυτων[1:5]{.aside}

ην δε ο ιωαννης ενδεδυμενος τριχας καμηλου και ζωνην δερματινην περι την οσφυν αυτου και εσθιων ακριδας και μελι αγριον[1:6]{.aside}

και [εκηρυσσεν]{.greek-omitted} [εκηρυσεν]{.greek-added} λεγων ερχεται ο ισχυροτερος μου οπισω μου ου ουκ ειμι ικανος [κυψας]{.greek-omitted} λυσαι τον ιμαντα των υποδηματων αυτου[1:7]{.aside}

εγω μεν εβαπτισα υμας εν υδατι αυτος δε [βαπτισει]{.greek-omitted} [βαπτιζει]{.greek-added} υμας εν [πνευματι]{.greek-abbr} αγιω[1:8]{.aside}

και εγενετο εν εκειναις ταις ημεραις ηλθεν [ο]{.greek-added} [ιησους]{.greek-abbr} απο ναζαρετ της γαλιλαιας και εβαπτισθη [υπο]{.greek-omitted} [ιωαννου]{.greek-omitted} εις τον ιορδανην [υπο]{.greek-added} [ιωαννου]{.greek-added}[1:9]{.aside}

και ευθεως αναβαινων απο του υδατος ειδεν σχιζομενους τους [ουρανους]{.greek-abbr} και το [πνευμα]{.greek-abbr} ωσει περιστεραν καταβαινον επ αυτον[1:10]{.aside}

και φωνη εγενετο εκ των [ουρανων]{.greek-abbr} συ ει ο [υιος]{.greek-abbr} μου ο αγαπητος εν [ω]{.greek-omitted} [σοι]{.greek-added} [ευδοκησα]{.greek-omitted} [ηυδοκησα]{.greek-added}[1:11]{.aside}

### Chapter 9

[τω]{.greek-added} [και]{.greek-omitted} [καιρω]{.greek-added} [ελεγεν]{.greek-omitted} [εκεινω]{.greek-added} [ειπεν]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} [ημων]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [ο]{.greek-added} [[χριστος]{.greek-abbr}]{.greek-added} [αυτοις]{.greek-omitted} [τοις]{.greek-added} [εαυτου]{.greek-added} [μαθηταις]{.greek-added} [αμην]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} οτι εισιν τινες των ωδε εστηκοτων οιτινες ου μη [γευσωνται]{.greek-omitted} [γευσονται]{.greek-added} θανατου εως αν [ιδωσιν]{.greek-omitted} [ειδωσιν]{.greek-added} την βασιλειαν του [θεου]{.greek-abbr} εληλυθυιαν εν δυναμει[9:1]{.aside}

και μεθ ημερας εξ παραλαμβανει ο [ιησους]{.greek-abbr} τον πετρον και τον ιακωβον και ιωαννην και αναφερει αυτ[ο]{.unclear}υς εις ορος υψηλον κατ ιδιαν μονους και μετεμορφωθη εμπροσθεν αυτων[9:2]{.aside}

και τα [ια]{.greek-added} [ιματια]{.corr} αυτου εγενοντο στιλβοντα λευκα λιαν [ως]{.greek-omitted} [χιων]{.greek-omitted} οια γναφευς επι της γης ου [δυναται]{.greek-omitted} [δυνατε]{.greek-added} [ουτως]{.greek-added} λευκαναι[9:3]{.aside}

και ωφθη αυτοις ηλιας συν μωση και ησαν [συλλαλουντες]{.greek-omitted} [συνλαλουντες]{.greek-added} τω [ιησου]{.greek-abbr}[9:4]{.aside}

και αποκριθεις ο πετρος λεγει τω [ιησου]{.greek-abbr} ραββι καλον εστιν ημας ωδε ειναι και ποιησωμεν σκηνας τρεις [σοι]{.greek-omitted} [σου]{.greek-added} μιαν και [μωση]{.greek-omitted} [μωυσει]{.greek-added} μιαν και ηλια μιαν[9:5]{.aside}

ου γαρ ηδει τι [λαλησει]{.greek-omitted} [ησαν]{.greek-omitted} [αποκριθη]{.greek-added} [εκφοβοι]{.greek-added} γαρ [εκφοβοι]{.greek-omitted} [εγενοντο]{.greek-added}[9:6]{.aside}

και εγενετο νεφελη επισκιαζουσα [αυτοις]{.greek-omitted} [αυτους]{.greek-added} και [ηλθεν]{.greek-omitted} [εγενετο]{.greek-added} φωνη εκ της νεφελης ουτος εστιν ο [υιος]{.greek-abbr} μου ο αγαπητος [ακο[υ]{.unclear}ετε]{.greek-added} αυτου [ακουετε]{.greek-omitted}[9:7]{.aside}

και εξ[α]{.unclear}πινα περιβλεψαμενοι ουκετι ουδενα ειδον αλλα τον [ιησουν]{.greek-abbr} μονον μεθ εαυτων[9:8]{.aside}

[και]{.greek-added} καταβαινοντων [δε]{.greek-omitted} [[καταβαιννοντων]{.corr}]{.greek-added} αυτων απο του ορους διεστειλατο αυτοις ινα μηδενι [διηγησωνται]{.greek-omitted} α ειδον [διηγησονται]{.greek-added} ει [μη]{.greek-omitted} [μι]{.greek-added} οταν ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εκ νεκρων αναστη[9:9]{.aside}

### Chapter 10

[τω]{.greek-added} [και]{.greek-omitted} [καιρω]{.greek-added} [εκεινω]{.greek-added} προσεφερον [αυτω]{.greek-omitted} [τω]{.greek-added} [[κυριω]{.greek-abbr}]{.greek-added} [ημ[ω]{.unclear}ν]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} [[χριστω]{.greek-abbr}]{.greek-added} παιδια ινα [[αυ]{.unclear}των]{.greek-added} αψηται [αυτων]{.greek-omitted} οι δε μαθηται επετιμων τοις προσφερουσιν [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [προσεφερον]{.greek-added} [τω]{.greek-added} [κω]{.greek-added} [ημ[ω]{.unclear}ν]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} [[χριστω]{.greek-abbr}]{.greek-added} [παιδια]{.greek-added} [ινα]{.greek-added} [α[υ]{.unclear}των]{.greek-added} [αψηται]{.greek-added} [οι]{.greek-added} [δε]{.greek-added} [μαθηται]{.greek-added} [επετιμων]{.greek-added} [τοις]{.greek-added} [προσφερουσιν]{.greek-added}[10:13]{.aside}

[ιδων]{.greek-omitted} [δε]{.greek-omitted} [και]{.greek-added} [αποκριθεις]{.greek-added} ο [ιησους]{.greek-abbr} [ηγανακτησεν]{.greek-omitted} [ειπεν]{.greek-added} [αυτοις]{.greek-added} [αφετε]{.greek-added} [[τα]{.unclear}]{.greek-added} [παιδια]{.greek-added} [ερχεσ[θα]{.greek-supplied}[ι]{.unclear}]{.greek-added} [[πρ]{.unclear}ος]{.greek-added} [με]{.greek-added} και [μη]{.greek-added} [[κωλυετ]{.greek-supplied}αι]{.greek-added} [αυτα]{.greek-added} [των]{.greek-added} [[γαρ]{.greek-supplied}]{.greek-added} [[τοιου]{.greek-supplied}των]{.greek-added} [εστιν]{.greek-added} [[η]{.greek-supplied}]{.greek-added} [[βασιλεια]{.greek-supplied}]{.greek-added} [των]{.greek-added} [[ουρανων]{.greek-abbr}]{.greek-added} [και]{.greek-added} [αποκριθεις]{.greek-added} [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} ειπεν αυτοις αφετε [τ]{.unclear}[α]{.greek-supplied} παιδια ερχεσ[θαι]{.greek-supplied} [π]{.greek-supplied}[ρ]{.unclear}ος με μη [κωλυετε]{.greek-omitted} [[κωλυετ]{.greek-supplied}αι]{.greek-added} αυτα των [γαρ]{.greek-supplied} [τοιου]{.greek-supplied}των εστιν [η]{.greek-supplied} [βασιλεια]{.greek-supplied} [του]{.greek-omitted} [θεου]{.greek-omitted} [των]{.greek-added} [[ουρανων]{.greek-abbr}]{.greek-added}[10:14]{.aside}

[αμη]{.greek-supplied}ν λεγω υ[μ]{.greek-supplied}[ι]{.unclear}ν [ος]{.greek-supplied} [εαν]{.greek-omitted} [[αν]{.greek-supplied}]{.greek-added} [μη]{.greek-supplied} [δεξηται]{.greek-omitted} [[δε]{.greek-supplied}ξειτε]{.greek-added} τη[ν]{.greek-supplied} [βασιλεια]{.greek-supplied}[ν]{.unclear} το[υ]{.unclear} [θεου]{.greek-abbr} [ω]{.unclear}ς [παιδιον]{.greek-supplied} ου [μη]{.unclear} εισελ[θη]{.greek-supplied} [εις]{.greek-supplied} [αυτην]{.greek-supplied} [[αμην]{.greek-supplied}]{.greek-added} [[αμη]{.greek-supplied}ν]{.greek-added} [λεγω]{.greek-added} [υ[μι]{.greek-supplied}ν]{.greek-added} [[ος]{.greek-supplied}]{.greek-added} [[αν]{.greek-supplied}]{.greek-added} [[μη]{.greek-supplied}]{.greek-added} [[δε]{.greek-supplied}ξειται]{.greek-added} [τη[ν]{.greek-supplied}]{.greek-added} [[βα]{.greek-supplied}[σιλεια]{.greek-supplied}[ν]{.unclear}]{.greek-added} [το[υ]{.unclear}]{.greek-added} [[θεου]{.greek-abbr}]{.greek-added} [[ω]{.greek-supplied}ς]{.greek-added} [[παιδιον]{.greek-supplied}]{.greek-added} [ου]{.greek-added} [[μη]{.unclear}]{.greek-added} [εισελ[θη]{.unclear}]{.greek-added} [[εις]{.greek-supplied}]{.greek-added} [[αυτη]{.greek-supplied}[ν]{.unclear}]{.greek-added}[[10:15 *(lacunose)*]{.lacunose}]{.aside}

και [εναγκαλισ]{.greek-supplied}[α]{.unclear}μενος [αυτα]{.greek-supplied} [[κα]{.greek-supplied}τηυλογει]{.greek-added} [τιθεις]{.greek-supplied} [τ]{.greek-supplied}ας χειρας ε[π]{.greek-supplied} [αυτα]{.greek-supplied} [ευλογει]{.greek-omitted} [και]{.greek-added} [[εναγκαλισ]{.greek-supplied}[α]{.unclear}μενος]{.greek-added} [αυτα]{.greek-supplied} [[κα]{.greek-supplied}τηυλογει]{.greek-added} [[τιθεις]{.greek-supplied}]{.greek-added} [[τα]{.greek-supplied}ς]{.greek-added} [χειρας]{.greek-added} [ε[π]{.greek-supplied}]{.greek-added} [[αυτα]{.greek-supplied}]{.greek-added}[10:16]{.aside}

[θε]{.greek-added} [και]{.greek-omitted} [εκπορευομενου]{.greek-omitted} [αυτου]{.greek-omitted} [εις]{.greek-omitted} [οδον]{.greek-omitted} [προσδραμων]{.greek-omitted} [εις]{.greek-omitted} [και]{.greek-omitted} [γονυπετησας]{.greek-omitted} [αυτον]{.greek-omitted} [επηρωτα]{.greek-omitted} [αυτον]{.greek-omitted} [διδασκαλε]{.greek-omitted} [αγαθε]{.greek-omitted} τι ποιησω ινα ζωην αιωνιον κληρονομησω[10:17]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω τι με λεγεις αγαθον ουδεις αγαθος ει μη εις ο [θεος]{.greek-abbr}[10:18]{.aside}

τας εντολας οιδας μη [φονευσης]{.greek-added} [μη]{.greek-added} μοιχευσης [μη]{.greek-omitted} [φονευσης]{.greek-omitted} μη κλεψης μη ψευδομαρτυρησης μη [αποστερησης]{.greek-omitted} [αποστερησις]{.greek-added} τιμα τον [πατερα]{.greek-abbr} [σου]{.greek-omitted} και την [μητερα]{.greek-abbr}[10:19]{.aside}

ο δε αποκριθεις ειπεν αυτω διδασκαλε ταυτα παντα [εφυλαξαμην]{.greek-omitted} [εφυλαξα]{.greek-added} εκ νεοτητος μου[10:20]{.aside}

ο δε [ιησους]{.greek-abbr} εμβλεψας αυτω ηγαπησεν αυτον και ειπεν αυτω εν σοι υστερει [ει]{.greek-added} [θελεις]{.greek-added} [τελιος]{.greek-added} [ειναι]{.greek-added} υπαγε οσα εχεις [πωλησον]{.greek-omitted} [πολησον]{.greek-added} και δος [τοις]{.greek-added} πτωχοις και εξεις θησαυρον εν ουρανω και [δευρο]{.greek-omitted} [δευρω]{.greek-added} ακολουθει μοι αρας τον [σταυρον]{.greek-abbr}[10:21]{.aside}

ο δε στυγνασας επι τω λογω απηλθεν λυπουμενος ην γαρ εχων κτηματα πολλα[10:22]{.aside}

και περιβλεψαμενος ο [ιησους]{.greek-abbr} λεγει τοις μαθηταις αυτου πως δυσκολως οι τα χρηματα εχοντες εις την βασιλειαν του [θεου]{.greek-abbr} εισελευσονται[10:23]{.aside}

οι δε μαθηται εθαμβουντο επι τοις λογοις αυτου [δοξαζοντες]{.greek-added} [τον]{.greek-added} [ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [παλιν]{.greek-omitted} [αποκριθεις]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [τεκνα]{.greek-omitted} [πως]{.greek-omitted} [δυσκολον]{.greek-omitted} [εστιν]{.greek-omitted} [τους]{.greek-omitted} [πεποιθοτας]{.greek-omitted} [επι]{.greek-omitted} [χρημασιν]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [βασιλειαν]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [[θεον]{.greek-abbr}]{.greek-added} [εισελθειν]{.greek-omitted}[10:24]{.aside}

### Chapter 11

και οτε εγγιζουσιν εις [ιερουσαλημ]{.greek-omitted} [ιεροσολυμα]{.greek-added} [και]{.greek-added} [ηλθον]{.greek-added} εις [βηθσφαγη]{.greek-omitted} [βηθφαγη]{.greek-added} και βηθανιαν προς το ορος των ελαιων [αποστελλει]{.greek-omitted} [απεστειλεν]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} [ημων]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [ο]{.greek-added} [[χριστος]{.greek-abbr}]{.greek-added} δυο των μαθητων αυτου[11:1]{.aside}

και λεγει αυτοις υπαγετε εις την κωμην την κατεναντι υμων και ευθεως εισπορευομενοι εις αυτην ευρησετε πωλον δεδεμενον εφ ον ουδεις [ουπω]{.greek-added} [ανθρωπων]{.greek-abbr} [κεκαθικεν]{.greek-omitted} [κεκαθηκεν]{.greek-added} λυσαντες αυτον αγαγετε[11:2]{.aside}

και εαν τις υμιν [ειπη]{.greek-omitted} [ειπει]{.greek-added} τι ποιειτε τουτο ειπατε οτι ο [κυριος]{.greek-abbr} αυτου χρειαν εχει και ευθεως αυτον αποστελλει ωδε[11:3]{.aside}

απηλθον δε και ευρον πωλον δεδεμενον προς την θυραν εξω επι του αμφοδου και λυουσιν αυτον[11:4]{.aside}

και τινες των εκει εστηκοτων ελεγον αυτοις τι ποιειτε λυοντες τον πωλον[11:5]{.aside}

οι δε [ειπον]{.greek-omitted} [ειπαν]{.greek-added} αυτοις καθως ενετειλατο [αυτοις]{.greek-added} ο [ιησους]{.greek-abbr} και αφηκαν αυτους[11:6]{.aside}

και ηγαγον τον πωλον προς τον [ιησουν]{.greek-abbr} και επεβαλον [επ]{.greek-added} αυτω τα ιματια αυτων και εκαθισεν επ [αυτω]{.greek-omitted} [αυτον]{.greek-added}[11:7]{.aside}

πολλοι δε τα ιματια αυτων εστρωσαν εις την οδον αλλοι δε [στοιβαδας]{.greek-omitted} [στιβαδας]{.greek-added} εκοπτον [εκ]{.greek-omitted} [απο]{.greek-added} των δενδρων και εστρωννυον [εις]{.greek-omitted} [εν]{.greek-added} [την]{.greek-omitted} [τη]{.greek-added} [οδον]{.greek-omitted} [οδω]{.greek-added}[11:8]{.aside}

και οι προαγοντες και οι ακολουθουντες εκραζον λεγοντες ωσαννα ευλογημενος [ο]{.corr} [ερχομενος]{.corr} εν ονοματι [κυριου]{.greek-abbr}[11:9]{.aside}

ευλογημενη η ερχομενη βασιλεια [εν]{.greek-omitted} [ονοματι]{.greek-omitted} [κυριου]{.greek-omitted} του [πατρος]{.greek-abbr} ημων [δαυιδ]{.greek-abbr} ωσαννα εν τοις υψιστοις[11:10]{.aside}

και εισηλθεν εις ιεροσολυμα ο [ιησους]{.greek-abbr} [και]{.greek-omitted} εις το ιερον και περιβλεψαμενος παντα οψιας ηδη ουσης της ωρας εξηλθεν εις βηθανιαν μετα των δωδεκα[11:11]{.aside}

[και]{.greek-omitted} τη επαυριον εξελθοντων αυτων απο βηθανιας [επεινασεν]{.greek-omitted} [επινασεν]{.greek-added} [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added}[11:12]{.aside}

και ιδων συκην μακροθεν [εχουσαν]{.greek-omitted} [φυλλα]{.greek-omitted} ηλθεν [ει]{.greek-omitted} [αρα]{.greek-omitted} [ευρησει]{.greek-omitted} [τι]{.greek-omitted} [επ]{.greek-added} [αυτην]{.greek-added} [και]{.greek-added} [ελθων]{.greek-added} [ου]{.greek-added} [δεν]{.greek-added} [ευρεν]{.greek-added} εν αυτη [και]{.greek-omitted} [ελθων]{.greek-omitted} [επ]{.greek-omitted} [αυτην]{.greek-omitted} [ουδεν]{.greek-omitted} [ευρεν]{.greek-omitted} ει μη φυλλα ου γαρ ην καιρος συκων[11:13]{.aside}

και αποκριθεις [ο]{.greek-omitted} [ιησους]{.greek-omitted} ειπεν αυτη μηκετι εκ σου εις τον αιωνα μηδεις καρπον φαγοι και ηκουον οι μαθηται αυτου[11:14]{.aside}

και ερχονται εις ιεροσολυμα και εισελθων ο [ιησους]{.greek-abbr} εις το ιερον ηρξατο εκβαλλειν τους πωλουντας και [τους]{.greek-added} αγοραζοντας εν τω ιερω και τας τραπεζας των κολλυβιστων και τας καθεδρας των πωλουντων τας περιστερας κατεστρεψεν[11:15]{.aside}

και ουκ ηφιεν ινα τις διενεγκη σκευος δια του ιερου[11:16]{.aside}

και εδιδασκεν λεγων αυτοις ου γεγραπται οτι ο οικος μου οικος προσευχης κληθησεται [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις εθνεσιν υμεις [δε]{.corr} εποιησατε αυτον σπηλαιον ληστων[11:17]{.aside}

και [ηκουσαν]{.greek-omitted} [ηκουον]{.greek-added} [οι]{.greek-added} [αρχιερεις]{.greek-added} [και]{.greek-added} οι γραμματεις [και]{.greek-omitted} [οι]{.greek-omitted} [αρχιερεις]{.greek-omitted} και εζητουν πως αυτον απολεσωσιν εφοβουντο γαρ αυτον οτι πας ο οχλος εξεπλησσετο επι τη διδαχη αυτου[11:18]{.aside}

### Chapter 14

[και]{.greek-omitted} παραλαμβανει [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} τον πετρον και [τον]{.greek-added} ιακωβον και ιωαννην [μεθ]{.greek-omitted} [μετ]{.greek-added} [εαυτου]{.greek-omitted} [αυτου]{.greek-added} και ηρξατο [εκθαμβεισθαι]{.greek-omitted} [εκθαβεισθαι]{.greek-added} και αδημονειν[14:33]{.aside}

και λεγει αυτοις περιλυπος εστιν η ψυχη μου εως θανατου μεινατε ωδε και γρηγορειτε[14:34]{.aside}

και προσελθων [μικρον]{.greek-omitted} [μικ]{.greek-added} [ρον]{.greek-added} επεσεν επι της γης και προσηυχετο [ινα]{.greek-omitted} ει δυνατον εστιν [ινα]{.greek-added} παρελθη απ αυτου η ωρα[14:35]{.aside}

και ελεγεν αββα ο [πατηρ]{.greek-abbr} [μου]{.greek-added} παντα δυνατα σοι [εστιν]{.greek-added} παρενεγκε το ποτηριον [τουτο]{.greek-added} απ εμου [τουτο]{.greek-omitted} αλλ [ου]{.greek-omitted} [ουχ]{.greek-added} [τι]{.greek-omitted} [ως]{.greek-added} εγω θελω [αλλα]{.greek-omitted} [αλλ]{.greek-added} [τι]{.greek-omitted} [ως]{.greek-added} συ[14:36]{.aside}

και ερχεται και ευρισκει αυτους καθευδοντας και λεγει τω πετρω σιμων καθευδεις ουκ ισχυσας μιαν ωραν γρηγορησαι[14:37]{.aside}

[γρηγορειτε]{.greek-omitted} [γρηγορειται]{.greek-added} και προσευχεσθε ινα μη εισελθητε εις πειρασμον το μεν [πνευμα]{.greek-abbr} προθυμον η δε σαρξ ασθενης[14:38]{.aside}

και παλιν απελθων [προσηυξατο]{.greek-omitted} [ηυξατο]{.greek-added} τον αυτον λογον ειπων[14:39]{.aside}

και υποστρεψας [παλιν]{.greek-added} ευρεν αυτους [παλιν]{.greek-omitted} καθευδοντας ησαν γαρ οι οφθαλμοι αυτων [βεβαρημενοι]{.greek-omitted} [καταβαρυνομενοι]{.greek-added} και ουκ ηδεισαν τι αυτω αποκριθωσιν[14:40]{.aside}

και ερχεται το τριτον και λεγει αυτοις καθευδετε [το]{.greek-added} λοιπον και αναπαυεσθε απεχει [το]{.greek-added} [τελος]{.greek-added} ηλθεν η ωρα ιδου παραδιδοται ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εις τας χειρας των αμαρτωλων[14:41]{.aside}

εγειρεσθε αγωμεν ιδου ο παραδιδους με ηγγικεν[14:42]{.aside}

### Chapter 15

οι δε στρατιωται απηγαγον [αυτον]{.greek-omitted} [τον]{.greek-added} [ιν]{.greek-added} εσω [της]{.greek-omitted} [εις]{.greek-added} [την]{.greek-added} [αυλης]{.greek-omitted} [αυλην]{.greek-added} ο εστιν πραιτωριον και [συγκαλουσιν]{.greek-omitted} [συνκαλουσιν]{.greek-added} ολην την [σπειραν]{.greek-omitted} [σπιραν]{.greek-added}[15:16]{.aside}

και [ενδυουσιν]{.greek-omitted} [ενδιδυσκουσιν]{.greek-added} αυτον [χλαμυδα]{.greek-added} [κοκκινην]{.greek-added} [και]{.greek-added} πορφυραν και περιτιθεασιν αυτω πλεξαντες [ακανθινον]{.greek-omitted} στεφανον [εξ]{.greek-added} [ακανθων]{.greek-added}[15:17]{.aside}

και ηρξαντο ασπαζεσθαι αυτον [και]{.greek-added} [λεγειν]{.greek-added} χαιρε [ο]{.greek-omitted} [βασιλευς]{.greek-omitted} [βασιλευ]{.greek-added} των ιουδαιων[15:18]{.aside}

και ετυπτον αυτου την κεφαλην καλαμω και ενεπτυ[ο]{.unclear}ν αυτω και τιθεντες τα γονατα προσεκυνουν αυτω[15:19]{.aside}

και οτε ενεπαιξαν αυτω εξεδυσαν αυτον [την]{.greek-added} [χλαμυδα]{.greek-added} [και]{.greek-added} την πορφυραν και ενεδυσαν αυτον τα ιματια τα ιδια και εξαγουσιν αυτον [ινα]{.greek-omitted} [ωστε]{.greek-added} [σταυρωσωσιν]{.greek-omitted} [σταυρωσαι]{.greek-added} [αυτον]{.greek-omitted}[15:20]{.aside}

και αγγαρευουσιν παραγοντα [σιμωνα]{.greek-added} τινα [σιμωνα]{.greek-omitted} κυρηναιον ερχομενον [απ]{.greek-omitted} [απο]{.greek-added} αγρου τον [πατερα]{.greek-abbr} αλεξανδρου και ρουφου ινα αρη τον σταυρον αυτου[15:21]{.aside}

και φερουσιν αυτον επι [τον]{.greek-added} γολγοθα τοπον ο εστιν [μεθερμηνευομενον]{.greek-omitted} [μεθερμηνευομενος]{.greek-added} κρανιου τοπος[15:22]{.aside}

και εδιδουν αυτω [πιειν]{.greek-omitted} εσμυρνισμενον οινον [πιειν]{.greek-added} ο δε ουκ ελαβεν[15:23]{.aside}

και σταυρωσαντες αυτον [διαμεριζονται]{.greek-omitted} [διεμεριζον]{.greek-added} τα ιματια αυτου βαλλοντες κληρον επ αυτα τις τι αρη[15:24]{.aside}

ην δε ωρα [τριτη]{.greek-omitted} [τρι]{.greek-added} [τη]{.greek-added} και εσταυρωσαν αυτον[15:25]{.aside}

και ην η επιγραφη της αιτιας αυτου επιγεγραμμενη ο βασιλευς των ιουδαιων[15:26]{.aside}

και συν αυτω σταυρουσιν δυο ληστας ενα εκ δεξιων και ενα εξ ευωνυμων αυτου[15:27]{.aside}

και επληρωθη η γραφη η λεγουσα και μετα ανομων ελογισθη[15:28]{.aside}

και οι παραπορευομενοι εβλασφημουν αυτον κινουντες τας κεφαλας [αυτων]{.greek-omitted} και λεγοντες [ουα]{.greek-omitted} [ουαι]{.greek-added} ο καταλυων τον ναον και εν τρισιν ημεραις οικοδομων[15:29]{.aside}

σωσον σεαυτον και [καταβα]{.greek-omitted} [καταβηθι]{.greek-added} απο του σταυρου[15:30]{.aside}

ομοιως και οι αρχιερεις εμπαιζοντες [προς]{.greek-omitted} [εις]{.greek-added} αλληλους μετα των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} ελεγον αλλους εσωσεν εαυτον ου δυναται σωσαι[15:31]{.aside}

ο [χριστος]{.greek-abbr} ο βασιλευς [του]{.greek-omitted} [ισραηλ]{.greek-abbr} καταβατω νυν απο του σταυρου ινα [ιδωμεν]{.greek-omitted} [ειδωμεν]{.greek-added} και πιστευσωμεν αυτω και οι [συνεσταυρωμενοι]{.greek-omitted} [συνσταυρουμενοι]{.greek-added} αυτω ωνειδιζον αυτον[15:32]{.aside}

[και]{.greek-added} γενομενης [δε]{.greek-omitted} ωρας εκτης σκοτος εγενετο εφ ολην την γην εως ωρας ενατης[15:33]{.aside}

και τη [ενατη]{.greek-added} ωρα [τη]{.greek-omitted} [ενατη]{.greek-omitted} εβοησεν ο [ιησους]{.greek-abbr} φωνη μεγαλη λεγων ελωι ελωι [λιμα]{.greek-omitted} [λαμα]{.greek-added} [σαβαχθανι]{.greek-omitted} [σαβαχθανει]{.greek-added} ο εστιν μεθερμηνευομενον ο [θεος]{.greek-abbr} [μου]{.greek-omitted} ο [θεος]{.greek-abbr} μου εις τι με [εγκατελιπες]{.greek-omitted} [εγκατελειπας]{.greek-added}[15:34]{.aside}

και τινες των παρεστηκοτων ακουσαντες ελεγον [ιδου]{.greek-omitted} [οτι]{.greek-added} ηλιαν φωνει[15:35]{.aside}

[δραμων]{.greek-omitted} [δε]{.greek-omitted} [εις]{.greek-omitted} και [δραμοντες]{.greek-added} [γεμισας]{.greek-omitted} [εγεμισαν]{.greek-added} [σπογγον]{.greek-omitted} [σπονγον]{.greek-added} οξους [και]{.greek-added} [περιθεις]{.greek-omitted} [περιθεντες]{.greek-added} [τε]{.greek-omitted} καλαμω [εποτιζεν]{.greek-omitted} [εποτιζον]{.greek-added} [λεγοντες]{.greek-added} [αφες]{.greek-added} [αυτον]{.greek-omitted} [λεγων]{.greek-omitted} [αφετε]{.greek-omitted} [ιδωμεν]{.greek-omitted} [ειδωμεν]{.greek-added} ει ερχεται ηλιας καθελειν αυτον[15:36]{.aside}

ο δε [ιησους]{.greek-abbr} αφεις φωνην μεγαλην εξεπνευσεν[15:37]{.aside}

και το καταπετασμα του ναου εσχισθη εις δυο απο ανωθεν εως κατω[15:38]{.aside}

ιδων δε ο κεντυριων ο [παρεσκως]{.greek-added} [παρεστηκως]{.corr} [εξ]{.greek-omitted} [εναντιας]{.greek-omitted} αυτου οτι [ουτως]{.greek-omitted} κραξας εξεπνευσεν ειπεν αληθως ο [ανθρωπος]{.greek-abbr} ουτος [[θεου]{.greek-abbr}]{.greek-added} υιος ην [θεου]{.greek-omitted}[15:39]{.aside}

ησαν δε και γυναικες απο μακροθεν θεωρουσαι εν αις ην [και]{.greek-omitted} μαρια η μαγδαληνη και μαρια η [του]{.greek-omitted} ιακωβου του μικρου και [ιωση]{.greek-omitted} [ιωσητος]{.greek-added} [μητηρ]{.greek-abbr} και σαλωμη[15:40]{.aside}

αι και οτε ην εν τη γαλιλαια ηκολουθουν αυτω και διηκονουν αυτω και αλλαι πολλαι αι συναναβασαι αυτω εις ιεροσολυμα[15:41]{.aside}

### Chapter 16

[και]{.greek-omitted} λιαν πρωι [της]{.greek-omitted} [τη]{.greek-added} [μιας]{.greek-omitted} [μια]{.greek-added} [των]{.greek-added} [σαββατων]{.greek-omitted} [σαβαβατων]{.greek-added} ερχονται [αι]{.greek-added} [γυναικες]{.greek-added} επι το μνημειον [ετι]{.greek-added} ανατειλαντος του ηλιου[16:2]{.aside}

και ελεγον προς εαυτας τις [αποκυλισει]{.greek-omitted} [αποκυλησει]{.greek-added} ημιν τον λιθον [εκ]{.greek-omitted} [απο]{.greek-added} της θυρας του μνημειου[16:3]{.aside}

και [α]{.greek-added} [αναβλεψασαι]{.greek-omitted} [ναβλεψασαι]{.greek-added} θεωρουσιν οτι αποκεκυλισται ο λιθος ην γαρ μεγας σφοδρα[16:4]{.aside}

και εισελθουσαι εις το μνημειον [ειδον]{.greek-omitted} [ιδον]{.greek-added} νεανισκον καθημενον εν τοις δεξιοις περιβεβλημενον στολην λευκην και εξεθαμβηθησαν[16:5]{.aside}

ο δε λεγει αυταις μη εκθαμβεισθε [ιησουν]{.greek-abbr} ζητειτε τον [ναζαρηνον]{.greek-omitted} [ναζαρινον]{.greek-added} τον εσταυρωμενον ηγερθη ουκ εστιν ωδε ιδε ο τοπος οπου εθηκαν αυτον[16:6]{.aside}

αλλ υπαγετε ειπατε τοις μαθηταις αυτου και τω πετρω οτι προαγει υμας εις την γαλιλαια[ν]{.unclear} εκει αυτον οψεσθε καθως ειπεν υμιν[16:7]{.aside}

και εξελθουσαι εφυγον απο του μνημειου ειχεν δε αυτας τρομος και εκστασις και ουδενι ουδεν ειπον εφοβουντο γαρ[16:8]{.aside}

αναστας [δε]{.greek-omitted} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} [ημων]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [ο]{.greek-added} [[χριστος]{.greek-abbr}]{.greek-added} πρωι πρωτη σαββατου εφανη πρωτον μαρια τη μαγδαληνη αφ ης εκβεβληκε[ι]{.greek-supplied} επτα δαιμονια[16:9]{.aside}

εκεινη [πορευθεισα]{.greek-omitted} [πορευθησα]{.greek-added} απηγγειλ[εν]{.greek-supplied} τοις μετ αυτου [γεν[ο]{.unclear}]{.greek-added} [γενομενοις]{.greek-omitted} [μενοις]{.greek-added} πενθουσιν και κλαιουσιν[16:10]{.aside}

κακεινοι ακουσαντες οτι ζη και εθεαθη υπ αυτης ηπιστησαν[16:11]{.aside}

μετα δε ταυτα δυσιν εξ αυτων περιπατουσιν εφανερωθη εν ετερα μορφη πορευομενοις εις αγρον[16:12]{.aside}

κακεινοι απελθοντες απηγγειλαν τοις λοιποις ουδε εκεινοις επιστευσαν[16:13]{.aside}

υστερον ανακειμενοις αυτοις τοις ενδεκα εφανερωθη και [ονειδησεν]{.greek-added} [ωνειδισεν]{.greek-omitted} [[ωνειδησεν]{.corr}]{.greek-added} την [απιστιαν]{.greek-omitted} [απιστειαν]{.greek-added} αυτων και σκληροκαρδιαν οτι τοις θε[ασα]{.unclear}μενοις αυτον [εγει]{.greek-added} [εγηγερμενον]{.greek-omitted} [γερμενον]{.greek-added} [εκ]{.greek-added} [νεκρων]{.greek-added} ουκ επιστευσαν[16:14]{.aside}

και ειπεν αυτοις πορευθεντες εις τον κοσμον απαντα κηρυξατε το ευαγγελιον παση τη κτισει[16:15]{.aside}

ο πιστευσας και βαπτισθεις σωθησεται ο δε απιστησας κατακριθησεται[16:16]{.aside}

σημεια δε τοις πιστευσασιν ταυτα παρακολουθησει εν τω ονοματι μου δαιμονια εκβαλουσιν γλωσσαις [λαλησουσιν]{.greek-omitted} [λαλησουσι]{.greek-added} καιναις[16:17]{.aside}

[και]{.greek-added} [εν]{.greek-added} [ταις]{.greek-added} [χερσιν]{.greek-added} οφεις αρουσιν καν θανασιμον τι πιωσιν ου μη αυτους βλαψη επι αρρωστους χειρας [επιθησουσιν]{.greek-omitted} [επιθησου]{.greek-added} [σιν]{.greek-added} και καλως εξουσιν[16:18]{.aside}

ο μεν [ουν]{.greek-omitted} [κυριος]{.greek-abbr} [[ιησους]{.greek-abbr}]{.greek-added} μετα το λαλησαι αυτοις [ανεληφθη]{.greek-omitted} [ανελιμφθη]{.greek-added} εις τον [ουρανον]{.greek-abbr} και εκαθισεν εκ δεξιων του [θεου]{.greek-abbr}[16:19]{.aside}

εκεινοι δε εξελθοντες εκηρυξαν πανταχου του [κυριου]{.greek-abbr} συνεργουντος και τον λογον βεβαιουντος δια των επακολουθουντων σημειων [αμην]{.greek-omitted}[16:20]{.aside}

