---
title: "Collation of Byz^RP^ vs 41602 (*ℓ*-1602)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read *ℓ*-1602 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=41602).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and *ℓ*-1602                                   	| λογος                              	|
| *ℓ*-1602 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| *ℓ*-1602 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of *ℓ*-1602               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of *ℓ*-1602                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| *ℓ*-1602 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in *ℓ*-1602                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Mark

### Chapter 16

[ϩⲧⲟⲟⲩⲉ]{.greek-added} [ⲇⲉ]{.greek-added} [ⲛ̄ϣⲱⲣ︤ⲡ︥]{.greek-added} [ⲙ̄ⲡⲟⲩⲁ̄]{.greek-added} [ⲛ̄ⲛ̄ⲥⲁⲃⲃⲁⲧⲟⲛ]{.greek-added} [ⲁⲩⲉⲓ̄]{.greek-added} [ⲉϩⲣⲁⲓ̈]{.greek-added} [ⲉⲡⲉⲙϩⲁⲟⲩ]{.greek-added} [ⲙ̄[ⲡ]{.unclear}ⲁⲧⲉⲡⲣⲏ̄]{.greek-added} [ϣⲁ̄]{.greek-added} [και]{.greek-omitted} [λιαν]{.greek-omitted} [πρωι]{.greek-omitted} [της]{.greek-omitted} [μιας]{.greek-omitted} [σαββατων]{.greek-omitted} [ερχονται]{.greek-omitted} [επι]{.greek-omitted} [το]{.greek-omitted} [μνημειον]{.greek-omitted} [ανατειλαντος]{.greek-omitted} [του]{.greek-omitted} [ηλιου]{.greek-omitted}[16:2]{.aside}

[ⲁⲩⲱ]{.greek-added} [ⲛⲉⲩϫⲱ̄]{.greek-added} [ⲙ̄ⲙⲟⲥ]{.greek-added} [ⲛ̄ⲛⲉⲩⲉⲣⲏⲩ]{.greek-added} [ϫⲉ]{.greek-added} [ⲛⲓⲙ̄]{.greek-added} [ⲡⲉⲧⲛⲁⲥ︤ⲕ︦ⲣ︥ⲕ︤ⲣ︥ⲡⲱ]{.greek-added} [ⲛⲁⲛ]{.greek-added} [ⲙⲙⲁⲩ]{.greek-added} [ⲉⲃⲟⲗ̄]{.greek-added} [ϩⲓⲣ︤ⲛ︥]{.greek-added} [ⲧⲧⲁⲡⲣⲟ̄]{.greek-added} [ⲙ̄ⲡⲉⲙϩⲁⲟⲩ]{.greek-added} [και]{.greek-omitted} [ελεγον]{.greek-omitted} [προς]{.greek-omitted} [εαυτας]{.greek-omitted} [τις]{.greek-omitted} [αποκυλισει]{.greek-omitted} [ημιν]{.greek-omitted} [τον]{.greek-omitted} [λιθον]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [θυρας]{.greek-omitted} [του]{.greek-omitted} [μνημειου]{.greek-omitted}[16:3]{.aside}

[και]{.greek-omitted} [αναβλεψασαι]{.greek-omitted} [θεωρουσιν]{.greek-omitted} [οτι]{.greek-omitted} [αποκεκυλισται]{.greek-omitted} [ο]{.greek-omitted} [λιθος]{.greek-omitted} [ην]{.greek-omitted} [γαρ]{.greek-omitted} [μεγας]{.greek-omitted} [σφοδρα]{.greek-omitted} [ⲛ̄ⲧⲉⲣⲟⲩϥⲓⲉⲓⲁⲧⲟⲩ]{.greek-added} [ⲇⲉ]{.greek-added} [ⲉϩⲣⲁⲓ̈]{.greek-added} [ⲁⲩⲛⲁⲩ]{.greek-added} [ⲉⲡⲱⲛⲉ]{.greek-added} [ⲉⲁⲩϥⲓⲧ︤ϥ︥]{.greek-added} [ⲙ̄ⲙⲁⲩ]{.greek-added} [ⲛⲉⲩⲛⲟϭ]{.greek-added} [ⲅⲁⲣ]{.greek-added} [ⲡⲉ]{.greek-added} [ⲉⲡⲉϩⲟⲩⲟ]{.greek-added}[16:4]{.aside}

[και]{.greek-omitted} [εισελθουσαι]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [μνημειον]{.greek-omitted} [ειδον]{.greek-omitted} [νεανισκον]{.greek-omitted} [καθημενον]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} [δεξιοις]{.greek-omitted} [περιβεβλημενον]{.greek-omitted} [στολην]{.greek-omitted} [λευκην]{.greek-omitted} [και]{.greek-omitted} [εξεθαμβηθησαν]{.greek-omitted} [ⲁⲩⲱ]{.greek-added} [ⲛⲧⲉⲣⲟⲩⲃⲱⲕ]{.greek-added} [ⲉϩⲟⲩⲛ]{.greek-added} [ⲉⲡⲉⲙϩⲁⲁⲩ]{.greek-added} [ⲁⲩ[ⲛ]{.unclear}ⲁⲩ]{.greek-added} [ⲉⲩϩ︤ⲣ︥ϣⲓⲣⲉ]{.greek-added} [ⲉϥϩⲙⲟⲟⲥ]{.greek-added} [ⲉϩⲣⲁⲓ̈]{.greek-added} [[ⲛ]{.unclear}[ⲥ]{.greek-supplied}[ⲁ]{.unclear}ⲟⲩⲛⲁⲙ]{.greek-added} [[ⲙ̄ⲙ]{.unclear}[ⲟϥ]{.greek-supplied}]{.greek-added} [ⲉϥϭⲟ[ⲟ]{.unclear}[ⲗⲉ]{.greek-supplied}]{.greek-added} [[ⲛⲟⲩ]{.greek-supplied}ⲥⲧⲟⲗⲏ]{.greek-added} [ⲛ[ⲟⲩⲱ]{.unclear}ⲃ︤ϣ︥]{.greek-added} [ⲁⲩⲱ]{.greek-added} [ⲁⲧϩ[ⲟ]{.unclear}ⲧⲉ]{.greek-added} [ϫⲓⲧⲟⲩ]{.greek-added}[16:5]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [λεγει]{.greek-omitted} [αυταις]{.greek-omitted} [μη]{.greek-omitted} [εκθαμβεισθε]{.greek-omitted} [ιησουν]{.greek-omitted} [ζητειτε]{.greek-omitted} [τον]{.greek-omitted} [ναζαρηνον]{.greek-omitted} [τον]{.greek-omitted} [εσταυρωμενον]{.greek-omitted} [ηγερθη]{.greek-omitted} [ουκ]{.greek-omitted} [εστιν]{.greek-omitted} [ωδε]{.greek-omitted} [ιδε]{.greek-omitted} [ο]{.greek-omitted} [τοπος]{.greek-omitted} [οπου]{.greek-omitted} [εθηκαν]{.greek-omitted} [αυτον]{.greek-omitted} [ⲛ̄ⲧⲟϥ]{.greek-added} [ⲇⲉ]{.greek-added} [ⲁ[ϥ]{.unclear}ϣⲁϫⲉ]{.greek-added} [ⲛ︤ⲙ︥ⲙⲁⲩ]{.greek-added} [ϫⲉ]{.greek-added} [ⲙ̄ⲡ︤ⲣ︥ⲣ̄ϩⲟⲧⲉ]{.greek-added} [ⲥⲟⲟⲩⲛ]{.greek-added} [ⲅⲁⲣ]{.greek-added} [ϫ[ⲉ]{.greek-supplied}]{.greek-added} [ⲉⲧⲉⲧ︤ⲛ︥ϣⲓⲛⲉ]{.greek-added} [ⲛ̄ⲥⲁ]{.greek-added} [[ⲓⲥ]{.greek-abbr}]{.greek-added} [ⲡⲛⲁⲍⲱⲣⲁⲓⲟⲥ]{.greek-added} [ⲡⲉⲛⲧⲁⲩⲥ⳨ⲟ︤ⲩ︥]{.greek-added} [ⲙ̄ⲙⲟϥ]{.greek-added} [ⲁϥⲧⲱⲟⲩⲛ]{.greek-added} [ⲛ︤ϥ︥ϩ︤ⲙ︥]{.greek-added} [ⲡⲉⲓ̈ⲙⲁ̄]{.greek-added} [ⲁⲛ]{.greek-added} [ⲉⲓⲥ]{.greek-added} [ⲡⲙⲁ̄]{.greek-added} [ⲉⲛⲧⲁⲩⲕⲁⲁϥ]{.greek-added} [ⲛ̄ϩⲏⲧ︤ϥ︥]{.greek-added}[16:6]{.aside}

[ⲁⲗⲗⲁ]{.greek-added} [ⲃⲱⲕ̄]{.greek-added} [ⲛ̄ⲧⲟϥ]{.greek-added} [ⲛ̄ⲧⲉⲧ︤ⲛ︥ϫⲟⲟⲥ]{.greek-added} [ⲛ̄ⲛⲉϥⲙⲁⲑⲏⲧⲏⲥ]{.greek-added} [ⲙ︤ⲛ︥]{.greek-added} [ⲡⲕⲉⲡⲉⲧⲣⲟⲥ]{.greek-added} [ϫⲉ]{.greek-added} [ϥⲛⲁⲣ̄ϣⲟⲣ︤ⲡ︥]{.greek-added} [ⲉⲣⲱⲧ︤ⲛ︥]{.greek-added} [ⲉⲧⲅⲁⲗⲓⲗⲁⲓⲁ]{.greek-added} [ⲉⲧⲉⲧⲛⲁⲛⲁⲩ]{.greek-added} [ⲉⲣⲟϥ]{.greek-added} [ⲙ̄ⲡⲙⲁ̄]{.greek-added} [ⲉⲧ︤ⲙ︥ⲙⲁⲩ]{.greek-added} [ⲕⲁⲧⲁ]{.greek-added} [ⲑⲉ]{.greek-added} [[ⲉ]{.unclear}ⲛⲧⲁϥϫⲟ[ⲟ]{.unclear}[ⲥ]{.greek-supplied}]{.greek-added} [ⲛⲏⲧ︤ⲛ︥]{.greek-added} [αλλ]{.greek-omitted} [υπαγετε]{.greek-omitted} [ειπατε]{.greek-omitted} [τοις]{.greek-omitted} [μαθηταις]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [τω]{.greek-omitted} [πετρω]{.greek-omitted} [οτι]{.greek-omitted} [προαγει]{.greek-omitted} [υμας]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [γαλιλαιαν]{.greek-omitted} [εκει]{.greek-omitted} [αυτον]{.greek-omitted} [οψεσθε]{.greek-omitted} [καθως]{.greek-omitted} [ειπεν]{.greek-omitted} [υμιν]{.greek-omitted}[16:7]{.aside}

[και]{.greek-omitted} [εξελθουσαι]{.greek-omitted} [εφυγον]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [μνημειου]{.greek-omitted} [ειχεν]{.greek-omitted} [δε]{.greek-omitted} [αυτας]{.greek-omitted} [τρομος]{.greek-omitted} [και]{.greek-omitted} [εκστασις]{.greek-omitted} [και]{.greek-omitted} [ουδενι]{.greek-omitted} [ουδεν]{.greek-omitted} [ειπον]{.greek-omitted} [εφοβουντο]{.greek-omitted} [γαρ]{.greek-omitted} [[ⲁⲩⲱ]{.greek-supplied}]{.greek-added} [ⲛ̄ⲧⲉⲣⲟⲩ[ⲥ]{.unclear}[ⲱⲧⲙ]{.greek-supplied}]{.greek-added} [ⲁⲩⲉⲓ̄]{.greek-added} [ⲉ[ⲃⲟ]{.unclear}[ⲗ]{.greek-supplied}]{.greek-added} [[ϩ]{.unclear}ⲙ]{.greek-added} [ⲡⲉⲙϩⲁ[ⲁⲩ]{.unclear}]{.greek-added} [ⲁⲩⲡⲱⲧ]{.greek-added} [ⲛ[ⲉⲣ]{.unclear}ⲉⲟⲩϩⲟⲧⲉ]{.greek-added} [ⲅⲁ[ⲣ]{.greek-supplied}]{.greek-added} [ⲛ︤ⲙ︥ⲙⲁⲩ]{.greek-added} [ⲡⲉ]{.greek-added} [ⲁⲩⲱ]{.greek-added} [ⲛⲉⲩⲣ̄ϣⲡⲏ[ⲣ]{.unclear}ⲉ]{.greek-added} [ⲙ̄ⲡⲟⲩϫⲉ]{.greek-added} [ⲇⲉ]{.greek-added} [ⲛ̄ϣⲁϫⲉ]{.greek-added} [ⲉⲗⲁⲁⲩ]{.greek-added} [ⲛⲉⲩⲣ̄ϩⲟⲧⲉ]{.greek-added} [ⲅⲁ[ⲣ]{.unclear}]{.greek-added} [?]{.greek-added} [ϩ︤ⲛ︥]{.greek-added} [ϩⲉⲛⲕⲉ]{.greek-added} [ⲁⲛⲧⲓⲅⲣⲁⲫⲟⲛ]{.greek-added} [ⲇⲉ]{.greek-added} [ⲛⲁⲓ̈]{.greek-added} [ϫⲓ̄]{.greek-added} [ⲉϩⲟⲩ⳯]{.greek-added} [ⲉⲣⲟⲟⲩ]{.greek-added} [ⲛⲉⲛⲧⲁϥϩⲟⲡⲟⲩ]{.greek-added} [ⲇⲉ]{.greek-added} [ⲧⲏⲣⲟⲩ]{.greek-added} [ⲉⲧⲟⲟⲧⲟⲩ]{.greek-added} [ⲛ̄ⲛⲁⲡⲉⲧⲣⲟⲥ]{.greek-added} [ⲁⲩϫⲟⲟⲩ]{.greek-added} [ϩ︤ⲛ︥]{.greek-added} [ⲟⲩϣⲱⲱⲧ̄]{.greek-added} [ⲉⲃⲟⲗ']{.greek-added} [ⲙ︤ⲛ︥ⲛ̄ⲥⲁ]{.greek-added} [ⲛⲁⲓ̈]{.greek-added} [ⲇⲉ]{.greek-added} [ϩⲱⲟⲩ]{.greek-added} [ⲟⲛ]{.greek-added} [ⲁ[ⲓⲥ]{.greek-abbr}]{.greek-added} [ⲟⲩⲱⲛ︤ϩ︥]{.greek-added} [ⲛⲁⲩ]{.greek-added} [ⲉⲃⲟⲗ]{.greek-added} [ϫⲓⲛ]{.greek-added} [ⲙ̄ⲙⲁ̄]{.greek-added} [ⲛ̄ϣⲁ̄]{.greek-added} [ⲙ̄ⲡⲣⲏ]{.greek-added} [ϣⲁ]{.greek-added} [ⲙ̄ⲙⲁ̄]{.greek-added} [ⲛ̄ϩⲱⲧ︤ⲡ︥]{.greek-added} [ⲁϥϫⲟⲟⲩ]{.greek-added} [ⲉⲃⲟⲗ]{.greek-added} [ϩⲓⲧⲟⲟⲧⲟⲩ]{.greek-added} [ⲙ̄ⲡⲧⲁϣⲉⲟⲉⲓϣ̄]{.greek-added} [ⲉⲧⲧⲟⲩⲁⲁⲃ]{.greek-added} [ⲁⲩⲱ]{.greek-added} [ⲛ̄ⲁⲧⲧⲁⲕⲟ̄]{.greek-added} [ⲛ̄ⲧⲉⲡⲟⲩϫⲁⲓ̈]{.greek-added} [ⲙ̄ⲡϣ[ⲁ]{.unclear}]{.greek-added} [ⲉⲛⲉϩ']{.greek-added} [ϩⲁⲙⲏⲛ]{.greek-added} [ⲛⲁⲓ̈]{.greek-added} [ⲇⲉ]{.greek-added} [ⲟⲛ]{.greek-added} [ϫⲓ̄]{.greek-added} [ⲉϩ[ⲟⲩⲛ]{.unclear}]{.greek-added} [ⲉⲣⲟⲟⲩ]{.greek-added} [ⲛⲉⲣⲉⲟⲩⲥⲧⲱ[ⲧ]{.greek-supplied}]{.greek-added} [ⲇⲉ]{.greek-added} [ⲁⲙⲁϩⲧⲉ]{.greek-added} [ⲙ̄ⲙⲟⲟⲩ]{.greek-added} [ⲙ︤ⲛ︥]{.greek-added} [ⲟⲩϣⲧⲟⲣⲧ︤ⲣ︥]{.greek-added} [ⲁⲩⲱ]{.greek-added} [ⲙ̄ⲡⲟⲩϫⲉⲗⲁⲁⲩ]{.greek-added} [ⲛ̄ϣⲁϫⲉ]{.greek-added} [ⲉⲗⲁⲁⲩ]{.greek-added} [ⲛⲉⲩⲣ̄ϩⲟⲧⲉ]{.greek-added} [ⲅⲁⲣ]{.greek-added}[16:8]{.aside}

[αναστας]{.greek-omitted} [δε]{.greek-omitted} [πρωι]{.greek-omitted} [πρωτη]{.greek-omitted} [σαββατου]{.greek-omitted} [εφανη]{.greek-omitted} [πρωτον]{.greek-omitted} [μαρια]{.greek-omitted} [τη]{.greek-omitted} [μαγδαληνη]{.greek-omitted} [αφ]{.greek-omitted} [ης]{.greek-omitted} [εκβεβληκει]{.greek-omitted} [επτα]{.greek-omitted} [δαιμονια]{.greek-omitted} [ⲛ̄ⲧⲉⲣⲉϥⲧⲱⲟⲩ⳯]{.greek-added} [ⲇⲉ]{.greek-added} [ⲉϩⲧⲟⲟⲩⲉ]{.greek-added} [ⲛ̄ⲥⲟⲩ]{.greek-added} [ⲁ̄]{.greek-added} [ⲙⲡⲥⲁⲃⲃⲁⲧⲟⲛ]{.greek-added} [ⲁϥⲟⲩⲱⲛ︤ϩ︥]{.greek-added} [ⲛ̄ϣⲟⲣ︤ⲡ︥]{.greek-added} [ⲉⲙⲁⲣⲓⲁ]{.greek-added} [ⲧⲙⲁⲅⲇⲁⲗⲏⲛⲏ]{.greek-added} [ⲧⲁⲓ̈]{.greek-added} [ⲉⲛⲧⲁϥⲛⲟⲩϫⲉ]{.greek-added} [ⲉⲃⲟⲗ']{.greek-added} [ⲛ̄ϩⲏⲧ︤ⲥ︥]{.greek-added} [ⲛ̄ⲥⲁϣ︤ϥ︥]{.greek-added} [ⲛ̄ⲇⲁⲓⲙⲟⲟⲛⲓⲟⲛ]{.greek-added}[16:9]{.aside}

[ⲧⲉⲧ︤ⲙ︥ⲙⲁⲩ]{.greek-added} [ⲇⲉ]{.greek-added} [ⲁⲥⲃⲱⲕ̄]{.greek-added} [ⲁⲥⲧⲁⲙⲉⲛⲉⲛⲧⲁⲩϣⲱⲡⲉ]{.greek-added} [ⲛ︤ⲙ︥ⲙⲁϥ]{.greek-added} [ⲉⲩⲣ̄ϩⲏⲃⲉ]{.greek-added} [ⲁⲩⲱ]{.greek-added} [ⲉⲩⲣⲓⲙⲉ]{.greek-added} [εκεινη]{.greek-omitted} [πορευθεισα]{.greek-omitted} [απηγγειλεν]{.greek-omitted} [τοις]{.greek-omitted} [μετ]{.greek-omitted} [αυτου]{.greek-omitted} [γενομενοις]{.greek-omitted} [πενθουσιν]{.greek-omitted} [και]{.greek-omitted} [κλαιουσιν]{.greek-omitted}[16:10]{.aside}

[κακεινοι]{.greek-omitted} [ακουσαντες]{.greek-omitted} [οτι]{.greek-omitted} [ζη]{.greek-omitted} [και]{.greek-omitted} [εθεαθη]{.greek-omitted} [υπ]{.greek-omitted} [αυτης]{.greek-omitted} [ηπιστησαν]{.greek-omitted} [ⲛ̄ⲧⲟⲟⲩ]{.greek-added} [ϩⲱⲟⲩ]{.greek-added} [ⲟⲛ]{.greek-added} [ⲛ̄ⲧⲉⲣⲟⲩⲥⲱⲧ︤ⲙ︥]{.greek-added} [ϫⲉ]{.greek-added} [ϥⲟⲛ︤ϩ︥]{.greek-added} [ⲁⲩⲱ]{.greek-added} [[ϫ]{.unclear}ⲉ]{.greek-added} [ⲁⲥⲛⲁⲩ]{.greek-added} [ⲉⲣⲟϥ]{.greek-added} [ⲁⲩⲣ̄ⲁⲧⲛⲁϩⲧⲉ]{.greek-added}[16:11]{.aside}

[[ⲙ]{.greek-supplied}ⲛⲛ̄ⲥⲁ]{.greek-added} [ⲛⲁⲓ̈]{.greek-added} [ⲇⲉ]{.greek-added} [[ⲥ]{.greek-supplied}ⲛⲁⲩ]{.greek-added} [ⲉⲃⲟⲗ̄]{.greek-added} [ⲛ̄ϩⲏⲧⲟⲩ]{.greek-added} [ⲉⲩⲙⲟⲟϣⲉ]{.greek-added} [ⲁϥⲟⲩⲱⲛ︤ϩ︥]{.greek-added} [ⲉⲣⲟⲟⲩ]{.greek-added} [ϩ︤ⲛ︥]{.greek-added} [ⲕⲉⲙⲟⲣⲫⲏ̄]{.greek-added} [ⲉⲩⲃⲏⲕ̄]{.greek-added} [ⲉⲧⲥⲱϣⲉ]{.greek-added} [μετα]{.greek-omitted} [δε]{.greek-omitted} [ταυτα]{.greek-omitted} [δυσιν]{.greek-omitted} [εξ]{.greek-omitted} [αυτων]{.greek-omitted} [περιπατουσιν]{.greek-omitted} [εφανερωθη]{.greek-omitted} [εν]{.greek-omitted} [ετερα]{.greek-omitted} [μορφη]{.greek-omitted} [πορευομενοις]{.greek-omitted} [εις]{.greek-omitted} [αγρον]{.greek-omitted}[16:12]{.aside}

[κακεινοι]{.greek-omitted} [απελθοντες]{.greek-omitted} [απηγγειλαν]{.greek-omitted} [τοις]{.greek-omitted} [λοιποις]{.greek-omitted} [ουδε]{.greek-omitted} [εκεινοις]{.greek-omitted} [επιστευσαν]{.greek-omitted} [ⲛⲉⲧ︤ⲙ︥ⲙⲁⲩ]{.greek-added} [ϩⲱⲟⲩ]{.greek-added} [ⲟⲛ]{.greek-added} [ⲁⲩⲃⲱⲕ̄]{.greek-added} [ⲁⲩⲧⲁⲙⲉⲡⲕⲉⲥⲉⲉⲡⲉ]{.greek-added} [ⲟⲩⲇⲉ]{.greek-added} [ⲟⲛ]{.greek-added} [ⲙ̄ⲡⲟⲩⲡⲓⲥⲧⲉⲩⲉ]{.greek-added} [ⲛ̄ⲛⲉⲧ︤ⲙ︥ⲙⲁⲩ]{.greek-added}[16:13]{.aside}

[ⲙ︤ⲛ︥ⲛ̄ⲥⲱⲥ]{.greek-added} [ⲉⲩⲛⲏϫ]{.greek-added} [ⲛ̄ⲧⲟⲟⲩ]{.greek-added} [ⲙ̄ⲡ︤ⲙ︦ⲛ︥ⲧⲟⲩⲉ]{.greek-added} [ⲁϥⲟⲩⲱⲛ︤ϩ︥]{.greek-added} [ⲛⲁⲩ]{.greek-added} [ⲉⲃⲟⲗ']{.greek-added} [ⲁⲩⲱ]{.greek-added} [ⲁϥⲛⲟϭⲛⲉϭ]{.greek-added} [ⲛ̄ⲧⲉⲩⲙ︤[ⲛ︦ⲧ︥]{.unclear}[ⲁ]{.greek-supplied}[ⲧ]{.unclear}ⲛⲁϩⲧⲉ]{.greek-added} [ⲙ︤ⲛ︥]{.greek-added} [[ⲧ]{.unclear}[ⲉⲩ]{.greek-supplied}ⲙⲛⲧⲛ[ⲁϣⲧϩⲏⲧ]{.greek-supplied}]{.greek-added} [ϫⲉ]{.greek-added} [ⲙ̄ⲡⲟ[ⲩⲡ]{.unclear}[ⲓⲥⲧⲉ]{.greek-supplied}[ⲩ]{.unclear}ⲉ]{.greek-added} [ⲛ̄ⲛⲉⲛⲧⲁⲩⲛ[ⲁⲩ]{.greek-supplied}]{.greek-added} [ⲉⲣⲟϥ]{.greek-added} [ⲉⲁϥⲧⲱⲟⲩⲛ]{.greek-added} [υστερον]{.greek-omitted} [ανακειμενοις]{.greek-omitted} [αυτοις]{.greek-omitted} [τοις]{.greek-omitted} [ενδεκα]{.greek-omitted} [εφανερωθη]{.greek-omitted} [και]{.greek-omitted} [ωνειδισεν]{.greek-omitted} [την]{.greek-omitted} [απιστιαν]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [σκληροκαρδιαν]{.greek-omitted} [οτι]{.greek-omitted} [τοις]{.greek-omitted} [θεασαμενοις]{.greek-omitted} [αυτον]{.greek-omitted} [εγηγερμενον]{.greek-omitted} [ουκ]{.greek-omitted} [επιστευσαν]{.greek-omitted}[16:14]{.aside}

[ⲡⲉϫⲁϥ]{.greek-added} [ⲛⲁⲩ]{.greek-added} [ϫⲉ]{.greek-added} [ⲃⲱⲕ]{.greek-added} [ⲉϩⲣⲁⲓ̈]{.greek-added} [ⲉⲡⲕⲟⲥⲙⲟⲥ]{.greek-added} [ⲧⲏⲣ︤ϥ︥]{.greek-added} [ⲛ̄ⲧⲉⲧ︤ⲛ︥ⲧⲁ]{.greek-added} [ϣⲉⲟⲉⲓϣ]{.greek-added} [ⲙ̄ⲡⲉⲩⲁⲅⲅⲉⲗⲓⲟⲛ]{.greek-added} [ⲙ̄ⲡⲥⲱⲛ︤ⲧ︥]{.greek-added} [ⲧⲏⲣ̄ϥ]{.greek-added} [και]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [πορευθεντες]{.greek-omitted} [εις]{.greek-omitted} [τον]{.greek-omitted} [κοσμον]{.greek-omitted} [απαντα]{.greek-omitted} [κηρυξατε]{.greek-omitted} [το]{.greek-omitted} [ευαγγελιον]{.greek-omitted} [παση]{.greek-omitted} [τη]{.greek-omitted} [κτισει]{.greek-omitted}[16:15]{.aside}

[ⲡⲉⲧⲛⲁⲡⲓⲥⲧⲉⲩⲉ]{.greek-added} [ⲛ︤ϥ︥ϫⲓⲃⲁⲡⲧⲓⲥⲙⲁ]{.greek-added} [ϥⲛⲁⲟⲩϫⲁⲓ̈]{.greek-added} [ⲡⲉⲧⲛⲁⲡⲓⲥⲧⲉⲩⲉ]{.greek-added} [ⲁⲛ]{.greek-added} [ⲥⲉⲛⲁⲧϭⲁⲉⲓⲟϥ]{.greek-added} [ο]{.greek-omitted} [πιστευσας]{.greek-omitted} [και]{.greek-omitted} [βαπτισθεις]{.greek-omitted} [σωθησεται]{.greek-omitted} [ο]{.greek-omitted} [δε]{.greek-omitted} [απιστησας]{.greek-omitted} [κατακριθησεται]{.greek-omitted}[16:16]{.aside}

[ⲛⲉⲓ̈ⲙⲁⲉⲓⲛ]{.greek-added} [ⲇⲉ]{.greek-added} [ⲛⲁⲟⲩⲱϩ]{.greek-added} [ⲉⲛⲉⲧⲛⲁⲡⲓⲥⲧⲉⲩⲉ]{.greek-added} [ⲥⲉⲛⲁⲛⲉϫ̄ⲇⲁⲓⲙⲟⲛⲓⲟⲛ]{.greek-added} [ⲉⲃⲟⲗ]{.greek-added} [ϩ︤ⲙ︥]{.greek-added} [ⲡⲁⲣⲁⲛ]{.greek-added} [ⲥⲉⲛⲁϣⲁϫⲉ]{.greek-added} [ϩ︤ⲛ︥]{.greek-added} [ⲛ̄ⲁ[ⲥ]{.unclear}ⲡⲉ]{.greek-added} [σημεια]{.greek-omitted} [δε]{.greek-omitted} [τοις]{.greek-omitted} [πιστευσασιν]{.greek-omitted} [ταυτα]{.greek-omitted} [παρακολουθησει]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ονοματι]{.greek-omitted} [μου]{.greek-omitted} [δαιμονια]{.greek-omitted} [εκβαλουσιν]{.greek-omitted} [γλωσσαις]{.greek-omitted} [λαλησουσιν]{.greek-omitted} [καιναις]{.greek-omitted}[16:17]{.aside}

[[ⲁ]{.unclear}[ⲩ]{.greek-supplied}ⲱ]{.greek-added} [ⲥⲉⲛⲁϥⲓ]{.greek-added} [ⲛ[ⲛϩ]{.greek-supplied}[ⲟϥ]{.unclear}]{.greek-added} [ϩ︤ⲛ︥]{.greek-added} [ⲛⲉⲩ[ϭⲓϫ]{.greek-supplied}]{.greek-added} [[ⲕⲁ]{.greek-supplied}[ⲛ]{.unclear}]{.greek-added} [ⲉⲩϣⲁⲛⲥⲱ̄]{.greek-added} [[ⲛ]{.greek-supplied}ⲟⲩⲡⲁϩⲣⲉ]{.greek-added} [ⲙ̄ⲙⲟ̄ⲩ]{.greek-added} [ⲛ︤ⲥ︥ⲛⲁⲣⲃⲟⲟ[ⲛ]{.unclear}ⲉ]{.greek-added} [ⲛⲁⲩ]{.greek-added} [ⲁⲛ]{.greek-added} [ⲥⲉⲛⲁⲧⲁⲗⲉⲧⲟⲟⲧⲟⲩ]{.greek-added} [ⲉϫ︤ⲛ︥]{.greek-added} [ⲛⲉⲧϣⲱⲛⲉ]{.greek-added} [ⲛ̄ⲥⲉⲙ̄ⲧⲟⲛ]{.greek-added} [οφεις]{.greek-omitted} [αρουσιν]{.greek-omitted} [καν]{.greek-omitted} [θανασιμον]{.greek-omitted} [τι]{.greek-omitted} [πιωσιν]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [αυτους]{.greek-omitted} [βλαψη]{.greek-omitted} [επι]{.greek-omitted} [αρρωστους]{.greek-omitted} [χειρας]{.greek-omitted} [επιθησουσιν]{.greek-omitted} [και]{.greek-omitted} [καλως]{.greek-omitted} [εξουσιν]{.greek-omitted}[16:18]{.aside}

[τα]{.greek-added} [ο]{.greek-omitted} [μεν]{.greek-omitted} [ουν]{.greek-omitted} [κυριος]{.greek-omitted} [μετα]{.greek-omitted} το λαλησαι αυτοις [ανεληφθη]{.greek-omitted} [ανελημφθη]{.greek-added} εις τον [ουρανον]{.greek-abbr} και εκαθισεν εκ δεξιων του [θεου]{.greek-abbr} [ⲡϫⲟⲉⲓⲥ]{.greek-added} [ⲇⲉ]{.greek-added} [[ⲓⲥ]{.greek-abbr}]{.greek-added} [ⲙ︤ⲛ︥ⲛ̄ⲥⲁ]{.greek-added} [ⲧⲣⲉϥϣⲁϫⲉ]{.greek-added} [ⲛ︤ⲙ︥ⲙⲁⲩ]{.greek-added} [ⲁⲩϫⲓⲧ︤ϥ︥]{.greek-added} [ⲉϩⲣⲁⲓ̈]{.greek-added} [ⲉⲧⲡⲉ]{.greek-added} [ⲁϥϩⲙⲟⲟⲥ]{.greek-added} [ⲛ̄ⲥⲁ]{.greek-added} [ⲟⲩⲛⲁⲙ']{.greek-added} [ⲙ̄ⲡⲛⲟⲩⲧⲉ]{.greek-added}[16:19]{.aside}

εκεινοι δε εξελθοντες εκηρυξαν πανταχου του [κυριου]{.greek-abbr} συνεργουντος και τον λογον βεβαιουντος δια των επακολουθουντων [σημειων]{.greek-omitted} [σημειων]]{.greek-added} [αμην]{.greek-omitted} [ⲡⲥⲟⲟⲩ]{.greek-added} [ⲙ̄ⲡϣⲁ̄Ⳇ]{.greek-added} [ⲡⲉⲩⲁⲅⲅⳆ]{.greek-added} [ⲛ̄ⲕⲁⲧⲁ]{.greek-added} [ⲙⲁⲣⳤ]{.greek-added} [ⲛ̄ⲧⲟⲟⲩ]{.greek-added} [ⲇⲉ]{.greek-added} [ϩⲱⲟⲩ]{.greek-added} [ⲛ̄ⲧⲉⲣⲟⲩⲉⲓ̄]{.greek-added} [ⲉⲃⲟⲗ̄]{.greek-added} [ⲁⲩⲧⲁϣⲉⲟⲉⲓϣ̄]{.greek-added} [ⲙ̄ⲙⲁ]{.greek-added} [ⲛⲓⲙ]{.greek-added} [ⲉⲣⲉⲡϫⲟⲉⲓⲥ]{.greek-added} [ϯ]{.greek-added} [ⲛⲧⲟⲟⲧⲟⲩ]{.greek-added} [ⲉϥⲧⲁϫⲣⲟ]{.greek-added} [ⲙ̄ⲡϣⲁϫⲉ]{.greek-added} [ⲛⲙ̄ⲙⲁⲉⲓ[ⲛ]{.unclear}]{.greek-added} [ⲉⲧⲟⲩⲏϩ]{.greek-added} [ⲛ̄ⲥⲱⲟⲩ]{.greek-added}[16:20]{.aside}

