---
title: "Collation of Byz^RP^ vs 42005 (*ℓ*-2005)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read *ℓ*-2005 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=42005).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and *ℓ*-2005                                   	| λογος                              	|
| *ℓ*-2005 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| *ℓ*-2005 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of *ℓ*-2005               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of *ℓ*-2005                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| *ℓ*-2005 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in *ℓ*-2005                                                     	| [―]{.gap}                        	|
:::

## The Gospel of John

### Chapter 16

[εως]{.greek-omitted} [αρτι]{.greek-omitted} [ουκ]{.greek-omitted} [ητησατε]{.greek-omitted} [ουδεν]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ονοματι]{.greek-omitted} [μου]{.greek-omitted} [αιτειτε]{.greek-omitted} και ληψεσθε ινα η χαρα υμων η πεπλη[ρ]{.unclear}ωμενη[16:24]{.aside}

ταυτα εν παροιμιαις λελαληκα υμιν αλλ ερχεται ωρα οτε ουκετι εν παροιμιαις λαλησω υμιν αλ[λα]{.unclear} παρρησια π[ε]{.unclear}ρι του [πατρος]{.greek-abbr} [αναγγελω]{.greek-omitted} [απ[αγ]{.unclear}γελω]{.greek-added} υμιν[16:25]{.aside}

εν εκεινη τη ημερα εν τω ονοματι μου αιτησεσθ[ε]{.unclear} και ου λεγω υμιν οτι εγω ερωτησω τον [πατερα]{.greek-abbr} περι [υμων]{.greek-supplied}[16:26]{.aside}

αυτος γαρ ο [πατηρ]{.greek-abbr} φιλει υμας οτι υμεις εμε πεφιληκατε και πεπιστευκατε οτι εγω παρα του [θεου]{.greek-abbr} εξηλθο[ν]{.greek-supplied}[16:27]{.aside}

εξηλθον παρα του [πατρος]{.greek-abbr} και εληλυθα εις τον κοσμον παλιν αφιημι τον κοσμον κ[αι]{.unclear} π[ορευομαι]{.greek-supplied} [προς]{.greek-supplied} τον [πατερα]{.greek-abbr}[16:28]{.aside}

λεγουσι[ν]{.greek-supplied} αυτω οι μαθηται αυτου ιδε νυν παρρησια λαλ[εις]{.unclear} και παροιμιαν ουδεμιαν λεγεις[16:29]{.aside}

νυν οιδαμεν οτι οιδας παντα και [ου]{.greek-omitted} [χρειαν]{.greek-omitted} [εχεις]{.greek-omitted} [ινα]{.greek-omitted} [τις]{.greek-omitted} [σε]{.greek-omitted} [ερωτα]{.greek-omitted} [εν]{.greek-omitted} [τουτω]{.greek-omitted} [πιστευομεν]{.greek-omitted} [οτι]{.greek-omitted} [απο]{.greek-omitted} [θεου]{.greek-omitted} [εξηλθες]{.greek-omitted}[16:30]{.aside}

[νυν]{.greek-omitted} [οιδαμεν]{.greek-omitted} [οτι]{.greek-omitted} [οιδας]{.greek-omitted} [παντα]{.greek-omitted} [και]{.greek-omitted} ου χρειαν εχεις ινα τις σε ερωτα εν τουτω πιστευομεν οτι απο [θεου]{.greek-abbr} εξηλθες[16:30 | instance no. 2]{.aside}

απεκριθη αυτοις ο [ιησους]{.greek-abbr} αρτι πιστευετε[16:31]{.aside}

ιδου ερχεται ωρα και νυν εληλυθεν ινα σκορπισθητε εκαστος εις τα ιδια και εμε μονον αφητε και ουκ ειμι μονος οτι ο [πατηρ]{.greek-abbr} μετ εμου [εστιν]{.greek-omitted} [εστι]{.greek-added}[16:32]{.aside}

ταυτα λελαληκα υμιν ινα εν εμοι ειρηνην εχητε εν τω κοσμω θλιψιν εχετε αλλα θαρσειτε εγω νενικηκα τον κοσμον[16:33]{.aside}

### Chapter 17

ταυτα ελαλησεν ο [ιησους]{.greek-abbr} και [επηρεν]{.greek-omitted} [επηρε]{.greek-added} τους οφθαλμους αυτου εις τον [ουρανον]{.greek-abbr} και ειπεν [πατερ]{.greek-abbr} εληλυθεν η ωρα δοξασον [σ]{.unclear}ου τον [υιον]{.greek-abbr} ινα και ο [υιος]{.greek-abbr} σου δοξαση σε[17:1]{.aside}

καθως εδωκας αυτω εξουσιαν πασης σαρκος ινα παν ο [δεδωκας]{.greek-omitted} [εδωκας]{.greek-added} αυτω δωσει αυτοις ζωην αιωνιον[17:2]{.aside}

αυτη δε εστιν η [αιω]{.greek-added} [αιωνιος]{.greek-omitted} [ζωη]{.greek-omitted} [ινα]{.greek-omitted} [γινωσκωσιν]{.greek-omitted} [σε]{.greek-omitted} [τον]{.greek-omitted} [μονον]{.greek-omitted} [αληθινον]{.greek-omitted} [θεον]{.greek-omitted} [και]{.greek-omitted} [ον]{.greek-omitted} [απεστειλας]{.greek-omitted} [ιησουν]{.greek-omitted} [χριστον]{.greek-omitted}[17:3]{.aside}

